### ISSUE TITLE
The method eth_compileSolidity does not exist/is not available

### ISSUE THREAD

**Issue by falehenrique** [ethereum/web3.js#1000]
Hi!
I am studying about smart contracts, I did the download of project and I try to test the **contract.html** but i had this problem.
`var compiled = web3.eth.compile.solidity(source);`

`web3.js:3143 Uncaught Error: The method eth_compileSolidity does not exist/is not available
    at Object.InvalidResponse (web3.js:3143)
    at RequestManager.send (web3.js:6347)
    at Object.send [as solidity] (web3.js:5081)
    at contract.html:20`

Can someone can help me?

**Comment by liusy182** [comment]
Check out this [issue here](https://github.com/ethereum/go-ethereum/issues/3793). It has been removed but docs are not updated yet.
