### ISSUE TITLE
Error: Provider not set or invalid

### ISSUE THREAD

**Issue by pannous** [ethereum/web3.js#1001]
Could you preconfigure a default provider for noobs?
`var web3 = new Web3(web3.currentProvider);` doesn't help

**Comment by pannous** [comment]
`    web3.setProvider(new web3.providers.HttpProvider());` did it

**Comment by KeepChen** [comment]
`var web3 = new Web3();
web3.setProvider(new Web3.providers.HttpProvider("http://localhost:8545"));`
Don't forget to run testrpc.
Wish helpful with you.

**Comment by KeepChen** [comment]
At first,you should be run testrpc as a server.Then ｀Web3.providers.HttpProvider("http://localhost:8545"));｀is available.

**Comment by utgarda** [comment]
```js
const web3 = new Web3(Web3.givenProvider);
```
gets you wherever Metamask is connected at the moment.

**Comment by fhrryDeveloper** [comment]
const web3 = new Web3(Web3.givenProvider);
But this is not working on mobile browser.
Which provider should I use for mobile browser.
I can see this error:
"Provider not set and invalid"

**Comment by avirajkhare00** [comment]
> ```js
> const web3 = new Web3(Web3.givenProvider);
> ```
> 
> gets you wherever Metamask is connected at the moment.

Thanks, @utgarda. You made my day
