### ISSUE TITLE
RFE: Provide support for instant finalty mode (parity)

### ISSUE THREAD

**Issue by ethernian** [ethereum/web3.js#1003]
It should be possible to setup an instant finalty delay (in blocks) using web3. In instant finalty mode, a web3 should report a chain state to be N blocks behind actual chain HEAD, preventing (most) chain reorganisations to break the dapp state.

Hier is the correspondend Issue on [Parity
](https://github.com/paritytech/parity/issues/6351)

**Comment by keorn** [comment]
@tomusdrw made https://www.npmjs.com/package/firm.web3

**Comment by nivida** [comment]
This can be configured in the latest version with the transaction confirmation option properties: https://web3js.readthedocs.io/en/1.0/web3-eth.html#transactionconfirmationblocks
