### ISSUE TITLE
Web3 1.0 Breaks BigNumbers

### ISSUE THREAD

**Issue by dskvr** [ethereum/web3.js#1016]
It appears that the new `web3.utils.toBN` does not return a true BigNumber object. It's missing a number of it's _most critical_ functions, including but not limited to

`toFixed()`
`toFormat()`

I confirmed this by including BigNumbers.js separately, creating a `new BigNumber()` from web3's `BigNumber` object, and then calling `toFixed()` (it worked). If this was intentional, it should be noted somewhere.

**Comment by TheRyanHickman** [comment]
Having same issue.
```let tokens = web3.utils.toBN(result).toString()```

![image](https://user-images.githubusercontent.com/2328000/35645825-39bb954e-069b-11e8-95f7-67b0a393b3db.png)

**Comment by dennisli92** [comment]
+1 on this. If you look at the library used, https://github.com/SilentCicero/number-to-bn, it says in the README that decimals aren't supported...

> A simple method to convert integer or hex integer numbers to BN.js object instances. Does not supprot decimal numbers.

```
console.log(numberToBN('0.9')); // or {}, [], undefined, 9.9

// throws new Error(...)
```

**Comment by dennisli92** [comment]
Sorry to harp on this, but tt'd be nice to know if there are plans to fix this. It's breaking my transactions/transfers too, since they call `web3.utils.toBN`, even if you supply the decimal value as a string.

**Comment by nivida** [comment]
We have started a discussion [here](https://github.com/ethereum/web3.js/issues/2171) about the future of big numbers and Web3.js.
