### ISSUE TITLE
"0x" results should return an error as oposed to being parsed as zero values

### ISSUE THREAD

**Issue by wighawag** [ethereum/web3.js#1020]
Currently web3 is interpretating "0x" as signifying zero values

I posted an issue on geth (https://github.com/ethereum/go-ethereum/issues/15102) thinking it was an issue there. I still think get should return a jsonrpc error for the case described in the issue but there might be other case where "0x" is a valid?  like calling a contract on a block where the contract did not exist yet ?

I think web3 should in that case return an error instead of interpretating the return values as being zeroes since this can be misleading.

As described in the geth issue, you can never sure that your data is actually zero at that particular block or it is the node that has not synced fully yet.

**Comment by nivida** [comment]
``0x`` will be handled as ``null`` with this PR https://github.com/ethereum/web3.js/pull/2608. I've decided to return null because of the [discussion](https://github.com/ethereum/go-ethereum/pull/3485#issuecomment-268793870) in the geth PR.
