### ISSUE TITLE
web3.fromWei(num, 'ether') freezes Safari

### ISSUE THREAD

**Issue by lightninglu10** [ethereum/web3.js#1034]
I'm using web3 version 0.20.0 and the call for `web3.fromWei(num, 'ether')` freezes Safari. This might be related to the issue here: https://github.com/ethereum/web3.js/issues/877

Not 100% sure, but anyone know what's going on?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
