### ISSUE TITLE
utils.fromWei & toWei returns string when I pass BigNumber

### ISSUE THREAD

**Issue by szerintedmi** [ethereum/web3.js#1042]
When I pass  [MikeMcl BigNumber](https://github.com/MikeMcl/bignumber.js/) the return value is string. It used to recognise BigNumbers from that library pre 1.0.0
```
import BigNumber from "bignumber.js";
let ethStringToWei = web3.utils.toWei("1");
    let ethBNToWei = web3.utils.toWei(new BigNumber("1"));
    console.log(
        web3.version,
        typeof ethStringToWei,
        ethStringToWei,
        typeof ethBNToWei,
        ethBNToWei
    );

// output:
// 1.0.0-beta.18 string 1000000000000000000 string 1000000000000000000
```

**Comment by frozeman** [comment]
Yes we don't return Bignumber anymore, you can choose your own BN lib you want to use and convert the number string yourself.
Internally we use BN.js

**Comment by linusnorton** [comment]
@frozeman is there a migration document somewhere? I only found this out by trial and error.
