### ISSUE TITLE
Error: Invalid number of arguments to Solidity function, when correct number of arguments is passed to a contract method

### ISSUE THREAD

**Issue by smoove** [ethereum/web3.js#1043]
I have this contract:

```solidity
contract MyContract {
    function add(bytes32 _var1, string _var2, bytes32[] _var3) {
        // ...
    }
}
```

I call the method like this:

```js
myContractInstance.add("a string", "another string", ["an", "array", "of", "strings"]);
```
Expected result: Transaction is successfull.
**Actual result:** "Error: Invalid number of arguments to Solidity function"

While debugging this, i tried adding another argument:

```js
myContractInstance.add("a string", "another string", ["an", "array", "of", "strings"], "this argument does not exist in the declaration");
```
Expected result: "Error: Invalid number of arguments to Solidity function"
**Actual result:** Transaction is successfull. 

This is the generated ABI:

```json
{
  "constant": false,
  "inputs": [
    {
      "name": "_var1",
      "type": "bytes32"
    },
    {
      "name": "_var2",
      "type": "string"
    },
    {
      "name": "_var3",
      "type": "bytes32[]"
    }
  ],
  "name": "add",
  "outputs": [
    {
      "name": "owner",
      "type": "address"
    }
  ],
  "payable": false,
  "type": "function"
},
```

This exact code worked, before i upgraded web3 to the latest version.

**Comment by smoove** [comment]
Possibly related to: #925

**Comment by frozeman** [comment]
It expects a callback, and for send transaction an object as last parameter.
I tested it against the 1.0 branch and its working.

Can please retest, also you are sending strings and not valid bytes as parameters, so there is a type mismatch between your input and your ABI

**Comment by smoove** [comment]
@frozeman You mean like this?

`myContractInstance.add("a string", "another string", ["an", "array", "of", "strings"], {from: ...}).then(...);` ?

I do that in my real code, i just cut that out for brevity.

Regarding the type mismatch: Well, it worked before, i assumed web3 (or truffle / truffle-contract) would handle type conversion internally.

**Comment by frozeman** [comment]
I dont know what truffle adds or changed on the contract object...
i will have a test locally with the 0.20.0

**Comment by frozeman** [comment]
I tested locally and doesnt give me this parameter error, so it seems that this is related to truffle. @tcoulter any idea?

**Comment by tcoulter** [comment]
Might be us. I'll take a look!

**Comment by smoove** [comment]
Little update:

The problem seems to only occur inside truffles migration files. I use migrations to add some data to the development chain for testing purposes.

As mentioned above, i can get the migrations to run by adding the additional argument.

Running my tests does not require the additional argument.

**Comment by tcoulter** [comment]
Sounds like it's interpreting the last parameter, an array, as an object, and then assuming it's the tx params object. Thanks for this. Will get on it right now.

**Comment by smoove** [comment]
Thanks gents, closing this issue.

**Comment by tcoulter** [comment]
Alright, update on this. It all comes back to #995; `instanceof Array`, which #995 replaces, doesn't correctly test for arrays in some situations. The built version of Truffle exposes one of those cases with web3 v0.20.1.

Fortunately, web3 v0.20.2 fixes the issue. We'll upgrade Truffle to use `v0.20.2` and put out a new release Monday.

**Comment by tcoulter** [comment]
Truffle v3.4.11 is out, upgrading web3 to v0.20.2. Thanks all!

**Comment by tavitohanian** [comment]
web3 is at 0.20.1 in latest beta, is this intentional? when will it be upgraded?
Truffle v4.0.0-beta.2 (core: 4.0.0-beta.2)
Solidity v0.4.17 (solc-js)
less ~/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/package.json
"_from": "truffle@beta",
  "_id": "truffle@4.0.0-beta.2",
...
"web3": "^0.20.1",
...

**Comment by cyberience** [comment]
Guys, Delete your build folder, then run the command.
```
npm run truffle migrate --reset --compile-all
```
I find it works best when running truffle locally to the folder rather than globally, due to the beta and different versions getting updated quickly recently.
if you prefer the global approach try
```
truffle migrate --reset --compile-all
```

**Comment by Hu4F00d** [comment]
I keep having to delete the build folder to make things work. I was having a different problem where trying to read simple info from my smart contracts would throw a Big Number error. Deleting the build folder solved it again.

**Comment by k26dr** [comment]
I get this error occasionally with Truffle. Deleting the `build` folder and re-compiling fixes the error every time.

**Comment by kyriediculous** [comment]
Still getting this error even after recompilng everyting.

**Comment by k26dr** [comment]
@kyriediculous delete the `build/` folder?

**Comment by beether** [comment]
Guys, this is an API that nearly EVERY Ethereum developer will end up using. Errors like this should be embarrassing.  This error is awful and wastes so much time for every developer.

Please add better errors, and allow calling functions in a more declarative way.

for `myMethod(uint _val1, string _val2)` allow calls like `myContract.myMethod({_val1: 123, _val2: "foo"} , {...opts...})`

Or: `myContract.myMethod([val1, val2], {..opts..})`

Using ordinality in arguments is always a mess.  You have to type check, and it's annoying to reflectively call things via `fn.call` and `fn.apply`.

Next, give SENSIBLE ERRORS about inputs. If one is expected and not provided, vice versa, or type mismatch.

I made an issue about this about a year ago, and have seen this error cited in COUNTLESS places ALL OVER THE PLACE.

**Just make a sensible API FFS**

**Comment by k26dr** [comment]
@beether It's open source software. You're free to contribute

**Comment by kyriediculous** [comment]
Why would anyone contribute to the pile of junk they created. Just don’t use truffle , easy as that.

**Comment by beether** [comment]
@kyriediculous It's web3. It's what comes with every browser extension that supports Ethereum.

**Comment by h36yang** [comment]
I get this issue too, with the following latest stable truffle and web3 versions:
* truffle: 4.1.5
* truffle-contract: 3.0.4
* web3: 0.20.6

> Uncaught (in promise) Error: Invalid number of arguments to Solidity function

I see this issue is closed, but don't seem to be able to find a solution for this. Can anyone please help? I'm still new to blockchain development :(

**Comment by koirikivi** [comment]
@h36yang and whomever else it may concern, I got this same issue when working with 0x.js. What was strange is that the error only happened in the production (= minified) js build, not with the development (= unminified) JS build!

Well, turns out that this piece of code in web3's `utils/utils.js`:

```
var isBigNumber = function (object) {
    return object instanceof BigNumber ||
        (object && object.constructor && object.constructor.name === 'BigNumber');
};
```

is used to validate arguments of type `BigNumber`, and if any of those arguments doesn't pass the check, it results in the `Uncaught (in promise) Error: Invalid number of arguments to Solidity function` error.

However, the `isinstance` check didn't return true for whatever reason (I assume there are multiple `BigNumber`s in our node_modules and as such the `BigNumber` used by web3). What also happened with our production build was that the name `BigNumber` was optimized to `Y`, and as such, the constructor name check didn't return true either!

I don't know if this relevant for your situation, but I'm just posting this here in case it helps someone else. Anyway, I think it would be better to do the `isBigNumber` check some other way. There's even a function in the BigNumber.js library called *drumroll* `BigNumber.isBigNumber` that could probably be used.

**Comment by beether** [comment]
@koirikivi Easiest work around is to always use the web3's version of BigNumber:

`const BigNumber = web3.toBigNumber(0).constructor`

**Comment by koirikivi** [comment]
@beether Thanks for the tip!

I agree on the point about the error messages. The "wrong number of arguments" line is confusing since that's not what's actually happening in this case. A minimal change, even without breaking the current API, would be to throw something like `expected argument N to be Array or BigNumber, was XXX` instead of just filtering the wrongly-typed parameters away.

**Comment by AlvaroLuken** [comment]
Deleting build folders and truffle migrate --reset --compile-all does not work for me! :( Can't test!!

**Comment by JamesANZ** [comment]
Hi all, I am getting this issue too but using the contract object directly instead of the truffle object i.e. web3.eth.Contract(abi, address). This is only broken now after I updated to ^1.0.0-beta.36 from an early pre beta version (0.18.4). Any ideas?

**Comment by dcsan** [comment]
>  Basically the error should read "Incorrect data types". My contract was expecting numbers and got strings so a quick Number("string) fix solved the issue.

so basically this error which has 100s of thousands of instances in google, is actually just a mistaken message? it is about argument types not number of args?

**Comment by cgewecke** [comment]
@dcsan The majority of these reports were caused by compilation bug in Truffle 4, although there are a handful of other possible causes. But this thread has been quiet for a while... 

What context are you seeing it in?

**Comment by legendaryphoenixicarus** [comment]
I've got the same issue with Hardhat v2.8.0.
In my case, I tried to deploy contract which have only one param, but had the error.
`Error: missing argument: passed to contract (count=1, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.5.0)`

My contract constructor: 
```
    constructor(uint256 cap_)
        ERC20("CreditCapital Platform Token", "CAPL")
        ERC20Capped(cap_)
    {
        _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(MINTER_ROLE, msg.sender);
    }
```
And I tried to deploy like this:
```
const deployContract = async (contract, params) => {
	let c = await ethers.getContractFactory(contract);
	if (params) c = await c.deploy(params);
	else c = await c.deploy();
	return await c.deployed();
}

const deployContracts = async (cap) => {
	const capl = await deployContract("CreditCapitalPlatformToken", cap)
	return capl
}
```

I've wasted huge days as this issue. Can anyone help me?

**Comment by dmadindividual** [comment]
this is 2023 and i still have this error
#  Web3ContractError: The number of arguments is not matching the methods required number. You need to pass 0 arguments.
