### ISSUE TITLE
"Filter not found"

### ISSUE THREAD

**Issue by tailongwang** [ethereum/web3.js#1046]
When i run this code, i got error.
pls help me
```js
const Web3 = require('web3')
const winston = require('winston')
const axios = require('axios')


let web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"))
let accounts = (web3.personal.listAccounts).toLocaleString().toLowerCase().split(',')
var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.Console)(),
    new (winston.transports.File)({ filename: 'webhook.log' })
  ]
});

let filter = web3.eth.filter('latest')
filter.watch(function(error, result) {
  if (!error) {
    let confirmedBlock12 = web3.eth.getBlock(web3.eth.blockNumber - 11)
    confirmedBlock12.transactions.forEach(function(txId) {
      let transaction = web3.eth.getTransaction(txId)
      if (accounts.indexOf(transaction.to) > -1) {
          logger.log('info', transaction) ; 
          axios.post('https://192.168.3.3/webhooks/eth', {
            type: 'transaction',
            hash: transaction.hash
          })
          .then(function (response) {
              logger.log('info', response);
          })
          .catch(function (error) {
              logger.log('error', error);
          });
      }
    })
  }
})

```
--------error in webhook.log-----------
`{"message":"filter not found","stack":"Error: filter not found\n    at Object.InvalidResponse (/home/ubuntu/web3/node_modules/web3/lib/web3/errors.js:38:16)\n    at /home/ubuntu/web3/node_modules/web3/lib/web3/requestmanager.js:255:40\n    at Array.filter (native)\n    at /home/ubuntu/web3/node_modules/web3/lib/web3/requestmanager.js:252:12\n    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/web3/node_modules/web3/lib/web3/httpprovider.js:118:13)\n    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:64:18)\n    at XMLHttpRequest._setReadyState (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:354:12)\n    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:509:12)\n    at IncomingMessage.<anonymous> (/home/ubuntu/web3/node_modules/xhr2/lib/xhr2.js:469:24)\n    at emitNone (events.js:91:20)","level":"error","timestamp":"2017-09-15T20:03:33.500Z"}`

**Comment by frozeman** [comment]
Is this an error you can reproduce? This error seem to come from geth itself.

**Comment by tailongwang** [comment]
@frozeman 
https://ethereum.stackexchange.com/questions/12546/error-filter-not-found-when-watching-for-latest-blocks?newreg=14363d4274fe40109f4de0d360c0e35f

Same as this.
web3.js version is 0.19.0

**Comment by koreaex** [comment]
Hello, I also returned this wrong `Error: filter not found`, my situation is that there are two geth nodes in the private network, I set up a internal domain in my router, such as `geth.localdomain`, and bind the IP of two nodes for the domain, Execute the following code to return the error.
```
var Web3 = require('web3');

var web3 = new Web3();
var tokenAbi = "...";
web3.setProvider(new web3.providers.HttpProvider("http://geth.localdomain:8545"));

var tokenContract = web3.eth.contract(tokenAbi);

tokenContract.at(tokenAddr).Transfer().watch(function(err, payload) {
	if(err || payload.args == undefined) {
	  console.log("=================== Error Payloads Checking ======================");
	  console.log(err);    // err => [Error: filter not found]
	}
});
```
If the domain name is only bound to single IP, it is normal, I don't know what the problem is.

```
Geth version: 1.8.13-stable
Web3 version: 0.15.1
```

**Comment by nivida** [comment]
@koreaex Please update to the latest v0.20.7 Version or directly to v1.0.0-beta.35 and test it again.

**Comment by sontuphan** [comment]
Hi @frozeman and @nivida, thanks for your help in advance. I have gotten the same issue as @koreaex, I built 2 geth and set up a kind of communication via a load balancer. Then I got ```Error: filter not found``` every time I try to connect my client to those geth via the load balancer for watching events. However, if I connect the geth directly with the same code, it no longer shown error.
I was using ```Web3 20.0.7``` and ```Geth/v1.8.14-stable-316fc7ec/linux-amd64/go1.10```. Do you have any idea to help me get around that?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
