### ISSUE TITLE
sendSignedTransaction transactions get stuck

### ISSUE THREAD

**Issue by johnbailon** [ethereum/web3.js#1050]
I build and sign a transaction using `ethereumjs-tx` and use `web3.eth.sendSignedTransaction` to broadcast. The transaction never pushes through unless I broadcast another transaction from the same account using [MyEtherWallet.com](https://www.myetherwallet.com/#send-transaction).

Example:
1. This transaction was broadcasted via my app: [0x91963377c4d92303d9d1d30ee8b5bc5c0af97d1905b52b75a941eae7acaabfd0](https://rinkeby.etherscan.io/tx/0x91963377c4d92303d9d1d30ee8b5bc5c0af97d1905b52b75a941eae7acaabfd0)
2. This transaction was broadcasted a few minutes after transaction 1 via MyEtherWallet.com: [0xf177deea75dc9713b48cb7b19e9c81cf1770b1604ea516da373944f74e4ac436](https://rinkeby.etherscan.io/tx/0xf177deea75dc9713b48cb7b19e9c81cf1770b1604ea516da373944f74e4ac436)

Both were mined at the same time, and almost right away after I sent transaction 2. I'm stumped why this is consistently the case. Any pointers where to look?

`Geth/v1.6.7-stable-ab5646c5/darwin-amd64/go1.9`
`ethereumjs-tx 1.3.3`
`web3 1.0.0-beta.18`

**Comment by johnbailon** [comment]
Also, I've connected Mist wallet to the same geth instance and it sends quickly too, same as MyEtherWallet which tells me it's not geth that's the problem.

**Comment by johnbailon** [comment]
Figured this out. Turns out, I mistakenly set `nonce = transactionCount + 1` when it should just be `nonce = transactionCount`. 🤦‍♂️

**Comment by johnbailon** [comment]
Figured this out. Turns out, I mistakenly set `nonce = transactionCount + 1` when it should just be `nonce = transactionCount`. 🤦‍♂️

**Comment by sneak** [comment]
🤣 My setting `nonce = txCount + 1` just cost me 4 hours of endless troubleshooting (including switching out libraries) until I found your comment.  Thank you, @johnbailon.

**Comment by duall** [comment]
> 🤣 My setting `nonce = txCount + 1` just cost me 4 hours of endless troubleshooting (including switching out libraries) until I found your comment. Thank you, @johnbailon.

same, some m****ker on overflow decided to add +1 :D  so I fell for that
