### ISSUE TITLE
Can't install web3 on windows or ubuntu 

### ISSUE THREAD

**Issue by VexyCats** [ethereum/web3.js#1060]
```
C:\Users\Spader>npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue


 scrypt@6.0.3 preinstall C:\Users\Spader\node_modules\.staging\scrypt-27aa434c
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\Spader\node_modules\scrypt
> node-gyp rebuild


C:\Users\Spader\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\Spader\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, eith
er 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual
Studio 2008.  [C:\Users\Spader\node_modules\scrypt\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, eith
er 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual
Studio 2008.  [C:\Users\Spader\node_modules\scrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Spader\node_modules\scrypt
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
spader@1.0.0 C:\Users\Spader
`-- (empty)

npm WARN spader@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild'
npm ERR! Exit status 1
```

I've tried updating nodejs, npm, I've downloaded the windows SDK in the message, and visual studios. I have visual studios 2017 and 2015. I've tried npm install msvs=2008, and finally I tried switching over to linux. On ubuntu I get a different error, but still ultimately fails at 

npm ERR! scrypt@6.0.3 install: `node-`node-scrypt-preinstall.js'
npm ERR! spawn ENOENT

I don't think this is related to web3, but I can't install any ethereum packages, so can someone help me? 

I've been struggling with this for a week now and I don't know how to fix this. It looks like I may need a new computer to try programming some Dapps...

**Comment by vospader** [comment]
I see the issue is related to node-gyp rebuild but: 1. I  don't know what that is, 2: I don't know how to fix it.

**Comment by frozeman** [comment]
Might be related to https://github.com/barrysteyn/node-scrypt/issues/88 i

**Comment by alexeymarunin** [comment]
Try install [node-gyp](https://github.com/nodejs/node-gyp#on-windows) before

**Comment by alexeymarunin** [comment]
@vospader, try install [node-gyp](https://github.com/nodejs/node-gyp#on-windows) before

**Comment by jojeyh** [comment]
Also having this problem, did install node-gyp before and place it in the correct folder.  Running Ubuntu 16.04.

**Comment by guinotch** [comment]
Same problem on Ubuntu 16.04

**Comment by guinotch** [comment]
update : it woks after installing node 6.x
follow the instructions here : https://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6

**Comment by pd164594** [comment]
I am getting the same error on Windows

**Comment by Geo-Joy** [comment]
@pd164594 I had the same issue and solved it as given below:
run: npm install --global --production windows-build-tools
refer: https://github.com/nodejs/node-gyp

**Comment by dejunqi2008** [comment]
I had similar problem in Ubuntu, not exactly the same though. I solved it by installing GCC compiler: `sudo apt-get install build-essential`, then I am able to install web3

**Comment by finalwombat** [comment]
@dejunqi2008 That worked for me. Thanks

**Comment by LEscobar-Driver** [comment]
Im having this problem on ubuntu 16.04.

This is by debug log

857 silly saveTree   │ │ ├─┬ scrypt.js@0.2.0
857 silly saveTree   │ │ │ ├── scrypt@6.0.3
857 silly saveTree   │ │ │ └── scryptsy@1.2.1
857 silly saveTree   │ │ ├── underscore@1.8.3
857 silly saveTree   │ │ └── uuid@2.0.1
857 silly saveTree   │ └─┬ web3-eth-contract@1.0.0-beta.34
857 silly saveTree   │   └── underscore@1.8.3
857 silly saveTree   ├── web3-net@1.0.0-beta.34
857 silly saveTree   ├── web3-shh@1.0.0-beta.34
857 silly saveTree   └── web3-utils@1.0.0-beta.34
858 warn webpack-cli@2.0.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
859 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
859 verbose stack Exit status 1
859 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
859 verbose stack     at EventEmitter.emit (events.js:180:13)
859 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
859 verbose stack     at ChildProcess.emit (events.js:180:13)
859 verbose stack     at maybeClose (internal/child_process.js:936:16)
859 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
860 verbose pkgid scrypt@6.0.3
861 verbose cwd /home/ancientevil/CompleteDevelopersGuide
862 verbose Linux 4.13.0-38-generic
863 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "web3@1.0.0-beta.26" "--unsafe-perm=true" "--allow-root" "web3"
864 verbose node v9.10.1
865 verbose npm  v5.6.0
866 error code ELIFECYCLE
867 error errno 1
868 error scrypt@6.0.3 install: `node-gyp rebuild`
868 error Exit status 1
869 error Failed at the scrypt@6.0.3 install script.
869 error This is probably not a problem with npm. There is likely additional logging output above.
870 verbose exit [ 1, true ]


It seems that I am missing scrypt@6.0.3 and cannot install it? Super lost

**Comment by iurimatias** [comment]
@LEscobar-Driver did you do ```sudo apt-get install build-essential``` ?

**Comment by katkol** [comment]
I too face same issue on Ubuntu 16.04. I tried ```sudo apt-get install build-essential```, but it too didn't resolve the error.

`$ sudo npm install --save web3npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /home/ltu/Ethereum-tutorial/inbox/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /home/ltu/Ethereum-tutorial/inbox/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ltu/Ethereum-tutorial/inbox/node_modules/scrypt/build'
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ltu/Ethereum-tutorial/inbox/node_modules/scrypt
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN inbox@1.0.0 No description
npm WARN inbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ltu/.npm/_logs/2018-04-20T09_15_43_733Z-debug.log
`

**Comment by sujanapathuri** [comment]
npm install web3@0.20.1 is working.

**Comment by nivida** [comment]
Please look at this issue: https://github.com/ethereum/web3.js/issues/1783
