### ISSUE TITLE
error on installing web3

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#1064]
## hi i have tried to install web3 but every time i fail, this is what I receive as an error

# **here is the problem occurs  at first it installs and proceds but nearly at the end  it fails**

c:\mylocal>npm install web3 --save
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrypt@6.0.3 preinstall c:\mylocal\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install c:\mylocal\node_modules\scrypt
> node-gyp rebuild

c:\mylocal\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Ali\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ali\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\mylocal\node_modules\scrypt
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN mylocal@1.0.0 No description
npm WARN mylocal@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ali\AppData\Roaming\npm-cache\_logs\2017-09-22T10_26_48_623Z-debug.log

c:\mylocal>

**Comment by vibhumbhardwaj** [comment]
You actually need to have python and Visual Studio Build Tools installed on your windows PC for this to work.

Thankfully, there's a npm package for this:
`npm install --global windows-build-tools`
If you want it to also configure python's path for you, do this instead:
`npm --add-python-to-path install --global windows-build-tools`
