### ISSUE TITLE
Getter return type state lost when methods are concurrency called

### ISSUE THREAD

**Issue by abec** [ethereum/web3.js#1069]
For version 1.0.0-beta.21, autogenerated getters that are supposed to return strings return the number 32. e.g. the following.

```
pragma solidity ^0.4.11;

contract MyContract {
  string public name;

  function MyContract(string _name) {
    name = _name;
  }
}
```

`MyContract.methods.name().call()` => `32`

EDIT:

It turns out the above is true only when method calls are concurrent.

```
return Promise.join(
        Software.methods.method1().call(),
        Software.methods.method2.call(),
        Software.methods.method3().call()
      ).spread((m1, m2, m3) => {
        console.log(m1);
        console.log(m2);
        console.log(m3);
      });
```

The above yields 32, 0, 0 in output. Where m2 and m3 and uint256 typed and m1 is string typed.

**Comment by abec** [comment]
It turns out this is happening when you do something like:
```
    return Promise.join(
        Software.methods.method1().call(),
        Software.methods.method2.call(),
        Software.methods.method3().call()
      ).spread((m1, m2, m3) => {
        console.log(m1);
        console.log(m2);
        console.log(m3);
      });
```

Where m2 and m3 have types of `uint256`. This is purely a concurrency issue. If you linearize the execution, the problem does not occur.

**Comment by perissology** [comment]
I'm having the same issue. If using async `call`, the `method.outputs` is being overwritten by whichever the last method call outputs are.

Ex.
```
return Promise.all([
    this.liquidPledging(),
    this.idProject(),
    this.maxAmount(),
    this.cumulatedReceived(),
    this.reviewer(),
    this.recipient(),
    this.newReviewer(),
    this.newRecipient(),
    this.accepted(),
    this.canceled(),
  ])
```
will return a bool for each method call, even though only `accepted` and `canceled` are bools. the others are addresses or unit.

something like:
```
return Promise.all([
    this.liquidPledging(),
    this.idProject(),
    this.maxAmount(),
    this.cumulatedReceived(),
    this.reviewer()
])
```
will return all hex values, as `reviewer` is an address.

**Comment by ferOnti** [comment]
I have additional information about this issue (web3js 1.0.0-beta.21)
- checking with ngrep/tcpdump I can see the complete string returned in the json, but the library only returns the first 32 bytes
var myContract = new web3.eth.Contract(contract.abi,
contractAddress, {
from: txAccount,
gasPrice: txGasPrice
});

**Comment by frozeman** [comment]
Thanks for the find! will be fixed in the next version: beta.22
