### ISSUE TITLE
web3.eth.accounts.privateKeyToAccount returns a different address than shown on MyEtherWallet

### ISSUE THREAD

**Issue by narcis2007** [ethereum/web3.js#1072]
When I call web3.eth.accounts.privateKeyToAccount it returns a different address than what I get on MyEtherWallet. Do you know why? Or it's a bug?

**Comment by narcis2007** [comment]
Nevermind, I had to add 0x to it

**Comment by adnan-i** [comment]
Just to clarify for any future wanderers, like I was.
You need to prepend `0x` to your private key:
```
const privateKey = '555';
const account = web3.eth.accounts.privateKeyToAccount('0x' + privateKey);
```

**Comment by gernotpokorny** [comment]
thx adnan-i. I guess nobody knows why this is not documented in the API docs...

**Comment by leberknecht** [comment]
Also good to know: for me, with web3@1.0.0-beta.52 , passing the key without `0x` did resulted in a successful transaction while the address was wrong oO So apparently the signing does check for the prefix and handles the prefix-missing case, while this is not done on the address-derivation. I guess.
