### ISSUE TITLE
web3.eth.accounts.signTransaction produced errant bytecode

### ISSUE THREAD

**Issue by cmditch** [ethereum/web3.js#1074]
Bytecode produced with a period in it.

Should be able to replicate it with the code params below:
```js
signTxParams = { 
    data: "0x23123123123123123",
    gas: 42424242424242,
    gasPrice: 42424242,
    nonce: 1,
    to: "0xd8b0990c007ba1ad97b37c001d1f87044312162a",
    value: "42424242",
    chainId: 1
}
privateKey = "0xef1ae7c6a04a3191b364c603f6f506938c98ec259597007300b42242f9fcc4b1"
signedTx = web3.eth.accounts.signTransaction(signTxParams, privateKey)

console.log(signedTx.rawTransaction);

> "0xf86b.80184028757b2862695a9e649b294d8b0990c007ba1ad97b37c001d1f87044312162a84028757b225a0254b9251405d5b83d688d0db794ef069fbb87a24d"
```

Browser : confirmed on Chrome & Safari
Web3.js Version : 1.0.0-beta.18

Note: To be fair, I don't think the above `data` field is totally valid bytecode. Nonetheless, thought this errant period might still be noteworthy.

**Comment by frozeman** [comment]
@MaiaVictor can you have a look?

**Comment by netpi** [comment]
I have the same problem !

**Comment by girish-bluefin** [comment]
its new api not implemented yet. You can see it
https://web3js.readthedocs.io/en/1.0/web3-eth.html#id73

**Comment by bytniak** [comment]
I have exactly the same problem.
With some normal transaction data and:
`data: "0x2ca5a332000000000000000000000000000000000000000000000000000000000000753000000000000000000000000000000000000000000000000000000000000003e8"`
My signed rowTransaction looks like this:
`> 
 "0xf9ab.8038417bd2c89832dc6c094279915231c108f8f371ef75aa58e18d181bf863380b8442ca5a332000000000000000000000000000000000000000000000000000000000000753000000000000000000000000000000000000000000000000000000000000003e881.817aa086b303cdcb77810d5419c31fedd0ba7fc3f07e26de8b90af2cf96e4a54d37938a0366ab73e00884eb024174b1daf8dac605b3537d9ac0fa49d1073c93af38d51d4"`

Now we have two periods..

Environment: NodeJS  v8.9.1
Web3.js Version: 1.0.0-beta.26

not really sure what @girish-bluefin  meant...
