### ISSUE TITLE
npm install web3 error on ubuntu 16.04

### ISSUE THREAD

**Issue by keepchen** [ethereum/web3.js#1083]
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /home/ubuntu/.npm/_cacache/tmp/git-clone-49c1c456
npm ERR! /home/ubuntu/.npm/_cacache/tmp/git-clone-49c1c456/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-09-28T10_56_30_865Z-debug.log
ubuntu@ip-*:/var/www/ethereum_demo$ vi /home/ubuntu/.npm/_logs/2017-09-28T10_56_30_865Z-debug.log
===============================================================

800 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "web3"
801 verbose node v8.6.0
802 verbose npm  v5.3.0
803 error code 1
804 error Command failed: /usr/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /home/ubuntu/.npm/_cacache/tmp/git-clone-49c1c456
804 error /home/ubuntu/.npm/_cacache/tmp/git-clone-49c1c456/.git: Permission denied

**Comment by slemsvamp** [comment]
Trying to set this up as well, but getting the same error. I tried running it manually sticking a nice lil "sudo" infront of it, but the installing won't progress past this problem.

**Comment by JonasDev99** [comment]
same here...

**Comment by simoh92** [comment]
same problem here as well

**Comment by slemsvamp** [comment]
I'm not 100% sure this is the solution, or a possible solution but maybe someone could test this out since it did work for me. Try running:

`npm cache clear`

..to make sure that npm does stuff correctly. I might have changed something else that I can't recall that made the difference, but maybe it was the cache clear that saved me.

**Comment by msbachler** [comment]
I have the same issue. Just npm cache clear did not work for me unfortunately. It would be great if you could recall what else you did. Could you maybe check you console history to find out?

**Comment by msbachler** [comment]
OK. I gave up with npm install pulling it and I downloaded the zip of the release from GitHub. Put it in my node_modules folder and ran npm install on it. That seems to allow it to finish the install process. It seems to be working fine.

**Comment by ZeeshanJan** [comment]
I faced the same issue while installing web3 on fresh Ubuntu 16. However, it worked after when I installed **nodejs-legacy**.

**Comment by watrindade** [comment]
Facing the same issue.
I wonder if could, somehow, be related to this issue: https://github.com/ethereum/web3.js/issues/966

**Comment by slemsvamp** [comment]
Sorry, I don't have the logs left and I honestly think it was just the npm cache clear in my case, but glad you got it working!

**Comment by XatMassacrE** [comment]
same problem.

**Comment by vic08** [comment]
same issue on mac os sierra, npm v5. Anyone found a real cause of the problem?

**Comment by vic08** [comment]
alrite, this is probably happening because npm creates cache folders with ownership/permissions somehow not writable for git, so git dependency can not be written to cache folder. Too lazy to confirm what is going on exactly there. 

**Quick solution is: switch to npm version 4 instead of 5.** 

It appears like v5 release of npm is not usable, this is not the first time I can't load dependencies that worked with previous npm versions.

**Comment by JasonCoombs** [comment]
similar problem, Mac OS High Sierra, attempting to `npm install -g web3`

apparent quick work-around:

`npm install web3`

(do not use -g parameter, do not sudo, install for active user only not as global npm package)

**Comment by OriBori** [comment]
I have sloved this problem 

```
sudo npm uninstall web3
sudo npm install web3
```

**Comment by KorbinianK** [comment]
I have exactly the same issue, tried cleaning the cache and installing the depencies on their own, to no avail.

**Comment by kinganeng** [comment]
npm install web3@0.19

**Comment by saikat909** [comment]
`sudo npm install -g web3 --unsafe-perm=true --allow-root` this worked for me in ubuntu 18.04.01

**Comment by ranjithapr** [comment]
Manually execute git clone,and chang git:// to https://, and proceed with your npm install

**Comment by sbansal96** [comment]
`sudo npm install -g web3 --unsafe-perm=true --allow-root` this work for me

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
