### ISSUE TITLE
Provider does not reconnect after failure

### ISSUE THREAD

**Issue by gabi-t** [ethereum/web3.js#1085]
How to reproduce:
1. instantiate a web3 instance using a websockets provider (in my case - I connected it to a local parity client)
2. create a subscription to an event (in my case - newBlockHeaders)
3. kill parity 
Result: The process crashes with the following output:
[..]node_modules/web3-core-subscriptions/src/subscription.js:279
                            _this.options.requestManager.provider.reconnect();
                                                                  ^
TypeError: _this.options.requestManager.provider.reconnect is not a function
    at Timeout._onTimeout ([..]node_modules/web3-core-subscriptions/src/subscription.js:279:67)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

**Comment by nivida** [comment]
This got implemented with version beta.38
