### ISSUE TITLE
Include Typescript typings into npm package

### ISSUE THREAD

**Issue by ritave** [ethereum/web3.js#1087]
1.0 branch has already Typescript types prepared, but they are not included in the npm deployment. Ideally doing `npm install --save web3` would allow development in Typescript without any additional configuration.

**Comment by GrandSchtroumpf** [comment]
Hello,
You said the Typescript definitions file for web3 1.0 est ready. Where can I find it for now ?
Thanks =)

**Comment by ritave** [comment]
Check the 1.0 got branch, there’s index.d.ts there.

**Comment by GrandSchtroumpf** [comment]
Hmmm the definitions are not totally in line with the documentation. web3.eth.subscribe returns a Promise<Subscribe> in the definition while the documentation says it should returns a Subscribe object. Do you know which one is up-to-date ?

**Comment by ritave** [comment]
Huh, if they're not up-to-date then I don't think there are any better ones around. A shame.
0x project has some nice ones for the [0.* versions here](https://github.com/0xProject/web3-typescript-typings), but from what I understand, they will not be creating typings for 1.0 branch since there are some already in this repo.
@LogvinovLeon ping?

**Comment by GrandSchtroumpf** [comment]
I cannot tell if this is the documentation or the definition that is not up-to-date since MetaMask doesn't support eth.subscribe anyway...

**Comment by connectdotz** [comment]
related discussion: https://github.com/ethereum/web3.js/pull/897#issuecomment-335196079

**Comment by nivida** [comment]
Closed because of https://github.com/ethereum/web3.js/pull/897#issuecomment-335196079
