### ISSUE TITLE
Signed State changing method call with ethereumjs-tx from meteor

### ISSUE THREAD

**Issue by TimRicta** [ethereum/web3.js#1088]
How can i call a signed state-changing method/ function from meteor in the name of a certain private key. Of course i can simply call the function and confirm the call with metamask, but i really want to call this function "setFinisehd" automatically without clicking "submit". 
I followed the ethereumjs-tx example, heres my script:

`global.Buffer||require("buffer").Buffer;`
const EthereumTx = require('ethereumjs-tx')
const privateKey =Buffer.from('my private key', 'hex')
const txParams = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
  // EIP 155 chainId - mainnet: 1, ropsten: 3
  chainId: 3
}
const tx = new EthereumTx(txParams)
tx.sign(privateKey)
const serializedTx = tx.serialize()

myContractInstance.setFinised(true, what to insert here?, function(err, res){});`

**Comment by nivida** [comment]
Please ask your question on https://ethereum.stackexchange.com/
