### ISSUE TITLE
TypeError: token.methods.balanceOf(...).call(...).on is not a function

### ISSUE THREAD

**Issue by dzarezenko** [ethereum/web3.js#1089]
Hi,

I am trying to get `ERC20` tokens balance on some address with `web3.js` lib but received this error:

```
Unhandled rejection Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt (...\node_modules\web3-eth-abi\src\formatters.js:176:15)
    at SolidityTypeUInt.SolidityType.decode (...\node_modules\web3-eth-abi\src\type.js:252:17)
    at ...\node_modules\web3-eth-abi\src\index.js:327:49
    at Array.forEach (native)
    at ABICoder.decodeParameters (...\node_modules\web3-eth-abi\src\index.js:326:13)
    at Contract._decodeMethodReturn (...\node_modules\web3-eth-contract\src\index.js:451:22)
    at Method.outputFormatter (...\node_modules\web3-eth-contract\src\index.js:798:46)
    at Method.formatOutput (...\node_modules\web3-core-method\src\index.js:162:54)
    at sendTxCallback (...\node_modules\web3-core-method\src\index.js:453:33)
    at ...\node_modules\web3-core-requestmanager\src\index.js:144:9
    at XMLHttpRequest.request.onreadystatechange (...\node_modules\web3-providers-http\src\index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (...\node_modules\xhr2\lib\xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (...\node_modules\xhr2\lib\xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (...\node_modules\xhr2\lib\xhr2.js:509:12)
    at IncomingMessage.<anonymous> (...\node_modules\xhr2\lib\xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

My code:

```
var getTokenBalance = function(address) {
    var token = new web3.eth.Contract(contract_data.abi, contract_data.TOKEN_CONTRACT_ADDRESS);
    token.methods.balanceOf(address).call().then(function (result) {
        console.log(result);
    });
}
```

**Comment by sponnet** [comment]
I also received this bug - upgrading to ```^1.0.0-beta.22``` fixed this for me.

**Comment by thackerronak** [comment]
Same issue facing in "web3": "^1.0.0-beta.23",
`this.contractObj.methods.balanceOf(address).call(function (err, wieBalance) {}`
```
Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (formatters.js:162)
    at SolidityTypeUInt.webpackJsonp.../../../../web3-eth-abi/src/type.js.SolidityType.decode (type.js:252)
    at index.js:327
    at Array.forEach (<anonymous>)
    at ABICoder.webpackJsonp.../../../../web3-eth-abi/src/index.js.ABICoder.decodeParameters (index.js:326)
    at Contract.webpackJsonp.../../../../web3-eth-contract/src/index.js.Contract._decodeMethodReturn (index.js:451)
    at Method.outputFormatter (index.js:798)
    at Method.webpackJsonp.../../../../web3-core-method/src/index.js.Method.formatOutput (index.js:162)
    at sendTxCallback (index.js:453)
    at index.js:144
    at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (index.js:64)
    at XMLHttpRequest.wrapFn (zone.js:1166)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1540)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1566)
```

**Comment by thackerronak** [comment]
also tried with ^1.0.0-beta.22 but issue remains same

**Comment by jacobsimon** [comment]
Hey all, I was also receiving this bug and it turned out to be a slight difference in the ABI of my contract and the one I was using in my application. Not sure if there's another cause, but I would make sure that you're using the most recent version of your contract's ABI.

**Comment by skiral** [comment]
We are getting the same issue!

**Comment by guptapriyank** [comment]
no luck yet, anybody have a solution, please list

**Comment by dzarezenko** [comment]
I have resolved this with enclosing functionality into `Promise`:

```
_getTokenBalance : function (address) {
        var _this = this;
        return new Promise(function(resolve, reject) {
            var tokenBalance = 0;
            _this.contract.methods.balanceOf(address).call().then(function (result) {
                var tokensWei = result;
                console.log("Tokens Wei: " + tokensWei);
                _this.contract.methods.decimals().call().then(function (result) {
                    var decimals = result;
                    console.log("Token decimals: " + decimals);

                    tokenBalance = parseFloat(tokensWei) / Math.pow(10, decimals);
                    console.log("Token balance: " + tokenBalance);

                    resolve(tokenBalance);
                });
            });
        });
    }
```

and call it like:

```
this._getTokenBalance(address).then(function(tokenBalance) {
    // ...
});
```

**Comment by jdkanani** [comment]
For now, you can use - 
```javascript
web3.eth.call({
    to: address,
    data: contract.methods.balanceOf(address).encodeABI()
}).then(balance => {})
```

**Comment by lionello** [comment]
I disagree with the fix that was introduced in 15ffd55. This should not be handled by such low-level conversion code.

**Comment by frozeman** [comment]
So to understand that right, the contract returns `0x`? If so then this is certainly not a good fix, and i changed it in develop to make sure 0x will fail.

**Comment by frozeman** [comment]
@lionello you are right. Its actually wrong behaviour.
So if it would return `0` the value would look like:
```js
> web3.eth.call({to: '0x6d72f4097b093518114ac0ba54d7c9fd73eecc05', data: '0x39f6ca500000000000000000000000000000000000000000000000000000000000000000'})
"0x0000000000000000000000000000000000000000000000000000000000000000"
```
Though if it throws, it looks like:
```js
> web3.eth.call({to: '0x4597b8c3b40d96dc0365ced9dc9b56b81247120d', data: '0x39f6ca500000000000000000000000000000000000000000000000000000000000000000'})
"0x"
```

Therefore the raw value is also empty if it failed. This is a problem of how the token contract is build and not one of web3.js

**Comment by lionello** [comment]
@frozeman Yeah, that's more like it.

I'd really like to see some test that warrants the `!param.rawValue` clauses you've added. For the current tests, those clauses don't appear to changes the behavior at all, suggesting that they might be superfluous.

**Comment by frozeman** [comment]
I added the `!param.rawValue` only for int, uint and bool, as here we don't want it to be accidentally interpreted as `0`, or `false`

**Comment by mobilesite** [comment]
same error in version 1.0-beta.28. How to solve it?

**Comment by MRHarrison** [comment]
same error in version 1.0-beta.29.  Anybody figure this out yet?

**Comment by dgrant069** [comment]
I was getting this with beta.26. I figured out that my deployed and compiled contracts were out of sync. In other words, I made a change to my contract, compiled and deployed. I hadn't updated the address to my deployed contract (which I used to created instances of another contract that in my web ui was something like "add new <whatever>"). Once I updated the address, refreshed, and created a new instance through my browser, it worked.

**Comment by faizan-ali** [comment]
Started getting this error today in beta.29 after I updated my locally deployed Smart Contract with a constructor (it previously had none)
Calling any constant function causes the error, other functions work fine. Would very much appreciate some insight

**Comment by jamboj** [comment]
Same here... calling a const contract method periodically triggers 

```
Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/Users/tu/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/Users/tu/node_modules/web3-eth-abi/src/type.js:252:17)
    at /Users/tu/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/Users/tu/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/Users/tu/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/Users/tu/node_modules/web3-eth-contract/src/index.js:811:46)
    at Method.formatOutput (/Users/tu/node_modules/web3-core-method/src/index.js:162:54)
    at sendTxCallback (/Users/tu/node_modules/web3-core-method/src/index.js:453:33)
    at Object.<anonymous> (/Users/tu/node_modules/web3-core-requestmanager/src/index.js:144:9)
    at /Users/tu/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/tu/node_modules/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/tu/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/tu/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/tu/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:160:13)
    at WebSocketConnection.processFrame (/Users/tu/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/tu/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:150:11)

```

**Comment by TrejGun** [comment]
same here

**Comment by akucheruk-vareger** [comment]
same here

**Comment by srameshr** [comment]
This still remains :(

**Comment by mustafakemal16** [comment]
same here! Latest version: 1.0.0-beta.33

**Comment by VulgarnyKarlson** [comment]
same here! Latest version: 1.0.0-beta.33

**Comment by akucheruk-vareger** [comment]
So, I have fixed this and number of other things with just better ethereum js lib https://github.com/ethers-io/ethers.js

**Comment by akucheruk-vareger** [comment]
No, this issue isn’t depend on abi or address. I have every 10 seconds call that just read a balance, and in ~5-10% I’ve got this error.

**Comment by GoodBoy962** [comment]
same here

**Comment by noprom** [comment]
version `1.0.0-beta.33` still has this problem.
Anyone has already solved this problem?

**Comment by ArjunBhuptani** [comment]
Still having this problem here as well

**Comment by yzhang1994** [comment]
same here

**Comment by frozeman** [comment]
@dacarley @sponnet I would like to get to the bottom of this. It doesn't look like its a problem of web3.js, in fact it should error on a wrong output. Maybe this problem lies withing geth, or its an out of gas issue. 
More input would be welcome.

**Comment by RobOnChain** [comment]
Using web3 1.0 and MetaMask. Simple call of a getter function with 
```
var MyContract = new web3.eth.Contract(abi, address);
MyContract.methods.myFunction().call().then(console.log);
```
Same issue.

**Comment by davidmoradi** [comment]
I had the same problem, upgrading to 1.0.0-beta.34 from 1.0.0-beta.33 fixed it for me.

**Comment by haydenadams** [comment]
@Slaals can you expand on 

> I think the error is because of the provider in 100% of cases

I am using infura and am not running my own node.

**Comment by Slaals** [comment]
@haydenadams Infura is retuning you an empty response for some reasons (most probably, must investigate more on that). This error could be raised for some reasons I'm not aware of.

I don't know how you can fix this since you have no control on Infura, Make sure your ABI is the good one and you call the good contract address on the good provider URL.

I had the issue because I didn't correctly setup my private provider using Geth.

**Comment by quantumproducer** [comment]
@Slaals can you explain? I'm running geth, but no miner. I didn't think we needed a from: address to call contracts with.

**Comment by Slaals** [comment]
@quantumproducer I didn't go deeper about this issue, I just found why I had this one in the first place. AFAIK you have to run a miner in order to make this work.

When you run `geth` make sure you open the `console`; once you're in the console, simply type `miner.start()`, it will start to mine (sync and mine if it's desync). After that you shouldn't have this error again.

**Comment by quantumproducer** [comment]
@Slaals I don't want to mine, I just want to use geth to read from transactions. I tried miner.start() then running my code, same issue.

**Comment by Aniket-Engg** [comment]
facing this problem in web3 version `1.0.0-beta-34`  with metamask & Ropsten
Anyone has proper solutioin?

**Comment by k06a** [comment]
@Aniket-Engg this problem means you try to call the method of a contract which is not existing on this address.

**Comment by drewstaylor** [comment]
I have this issue on Kovan at the moment and I can confirm I am using the correct ABI. I have recompiled it so many times, and I always get the same result.

**Comment by drewstaylor** [comment]
After some review, I seem to have been having an issue similar to @Slaals I didn't realize my Kovan node had stopped silently syncing. Although I could see the transaction on Etherscan, I didn't have the block yet.

**Comment by sidharthaa** [comment]
when am working with test rpc i am not getting this error. But with ropsten sometimes contract loading with abi and addresse is working and most of the time failing. But didnt get this error for a single time in test rpc.
To be noted in both case am using metamask injected provider.
And i am creating a new object of web3 by doing
`web3 = new Web3 (injected_web3)`

**Comment by barakman** [comment]
Same problem when working with Parity.

**Comment by fritzmatias** [comment]
i found the same problem, but was because the address of the contract was wrong.
So, for me the real issue is "an invalid contract can be mapped to an object without throw an exception". Then, when you try to call the method the exception is throwed. 
'''
    "web3": "^1.0.0-beta.34",
    "web3-core-requestmanager": "^1.0.0-beta.34",
    "web3-eth": "^1.0.0-beta.34",
    "web3-eth-contract": "^1.0.0-beta.34"
'''

**Comment by ramxis** [comment]
I am having the same issue,  My dapp is using infura ropsten node as geth provider, Its a Nodejs app, and I have triple checked my Contract ABI and address, If i downgrade to Web3 0.20 i do not see this error with the same provider, and setup. I only encounter this problem if i use web 1.0

**Comment by zhouxbalabala** [comment]
Maybe the network environment of your plugin is not synchronized with your contract. Try switching.

**Comment by leavesgreen** [comment]
1.0.0-beta.35 , same issue, and sth more wired that  at the begining the code runing correctly , but after I install another package keythereum , all codes about contract  get the error 
---
then I deploy a new contract with the same code , and everything goes ok this time.

**Comment by disadone** [comment]
Hey ,em...... ,is this problem solved? is there a solution?

**Comment by antonpegov** [comment]
Double check the abi. I've got this 'bug' after minor changes in contract code without updating the abi.

**Comment by yzhang1994** [comment]
One possibility is that the blockchain node Metamask uses is corrupt / has false data. Found that error in my dapp today (metamask mainnet node) and it was causing the lookup of one constant `.call()` to fail about 5% of the time. The issue was fixed after switching metamask network to Custom RPC and connected it to a node that I myself am hosting, and the issue disappeared.

**Comment by xoxoj** [comment]
version 1.0.0-beta.33 still has this problem.
Anyone has already solved this problem?

**Comment by k06a** [comment]
@xoxoj this problem means you try to call the method of a contract which is not existing on this address.

**Comment by xoxoj** [comment]
@k06a I am sure it has

**Comment by Pupin3** [comment]
Any ideas on how to resolve this issue would be highly appreciated...
I am using  web3@1.0.0-beta.37 on windows7 Truffle v4.1.14 npm: '6.4.1'. 
Ganache is running and my app works fine. However, if I use .call() I get the error "contract.images(...).call is not a function"

**Comment by quantumproducer** [comment]
What is `contract.images` ?

**Comment by Pupin3** [comment]
@quantumproducer thank you for your answer. You were right, I was mistakenly calling "images" which is an array and not a function. I figured it out soon after posting my previous message.

**Comment by vauvenal5** [comment]
I have the same behavior like @dacarley had. Sometimes it works and sometimes it does not. Interestingly enough, it just started appearing without any obvious reason.

The first thing I tried is to run a local geth node instead of using the Infura API, this did not change anything. My local geth node is running in light mode. 

I also reverted my code base to the state when I deployed the contracts originally to make sure I am using the ABI as deployed.

I was calling some functions on my contracts that modify the state before all started and to be honest at this point it might have been that my ABIs we're not entirely correct however since the functions finished without error I assume it should be fine. Furthermore, as mentioned sometimes I am able to read the data from the contract so it is on chain.

I am by now at the point to simply try and redeploy everything to see if the behavior goes way.

I am working on the Ropsten network and currently running web3@1.0.0-beta.34. Open for any suggestions.

Edit: The behavior is the same with Metamask in the web browser as with my own client that uses a HttpProvider.

**Comment by felixwatts** [comment]
I have the same problem. ABI is definitely in sync with deployed contract. web3-provider-engine, HttpProvider, ganache-cli, embark. Started seemingly randomly today and occurs seemingly unpredictably. I get it when calling contract.getPastEvents (there are no events in the log that match the type)

**Comment by felixwatts** [comment]
OK, I was able to fix by specifying a from address when calling contract.getPastEvents:

    const stateEvents = await Atl.getPastEvents('EventName', {
        filter: {a: b},
        fromBlock: 0,
        toBlock: 'latest',
    }, { from: fromAddress });

**Comment by felixwatts** [comment]
Sorry that was wrong. It just randomly worked a couple fo times then started failing again

**Comment by surendersinghIT** [comment]
I were receiving same error and finally, I were able to fix issue as per following.
1.  const Election = new web3.eth.Contract(abi, contractAddress, {   from: web3.eth.defaultAccount });
I were using incorrect contract address

2.     web3.eth.getTransactionCount(address, function (err, nonce) {        
        const functionAbi = Election.methods.mymethod().encodeABI();

        var details = {
            'nonce': nonce,
            'gasPrice': web3.utils.toHex(web3.utils.toWei('20', 'gwei')),
            'gas': 6721975,
            'from': address,
            'to': contractAddress,
            'value': 0,
            'data': functionAbi,
        };
        const transaction = new EthereumTx(details);
        transaction.sign(Buffer.from(pk, 'hex') )
        var rawData = '0x' + transaction.serialize().toString('hex');
        console.log(rawData);
        web3.eth.sendSignedTransaction(rawData)
        .on('transactionHash', function(hash){
            console.log(['transferToStaging Trx Hash:' + hash]);
        })
        .on('receipt', function(receipt){
            console.log(['transferToStaging Receipt:', receipt]);
            res.send(receipt);
        })
        .on('error', console.error);
    });

i were using incorrect contract address in 'to' field of details of transaction.

I corrected contract address at both places and code worked correctly. I hope it would be helpful for someone.

Happy Coding!

**Comment by razik-r** [comment]
got this error : Unhandled Rejection (TypeError): token.methods.balanceOf is not a function
 when i was trying to load tokenbalance as javascript version of the token smart contract

here is my code :
     const token = new web3.eth.Contract(Token.abi, tokenData.address)
    this.setState({ token })
    let tokenBalance = await token.methods.balanceOf(this.state.account).call()
    this.setState({ tokenBalance: tokenBalance.toString() })

**Comment by barakman** [comment]
@razik-r : your `Token.abi` is probably wrong.

**Comment by razik-r** [comment]
oh my god ..tkysm !! I was trying to solve the problem like 6 hours 
so what happened is that when I imported the token contract and other contract I made some typo errors

I did this
import EthSwap from '../abis/EthSwap.json'
import Token from '../abis/EthSwap.json'

instead of this :
import EthSwap from '../abis/EthSwap.json'
import Token from '../abis/Token.json'
