### ISSUE TITLE
sync mode does not work

### ISSUE THREAD

**Issue by shaozi** [ethereum/web3.js#1090]
Hi, 
Just used npm to install web3 under node 8.6.0

But sync method does not work, although async methods work.

The very simple code is:
```javascript
const Web3 = require('web3')
var web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))

var coinbase = web3.eth.coinbase
console.log(coinbase)
```
and it print out `undefined`.

While the following code works fine:
```javascript
const Web3 = require('web3')
var web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))
web3.eth.getCoinbase().then(coinbase => {
    console.log("Coinbase:", coinbase)
})
```
Any special initialization thing I missed?

**Comment by naddison36** [comment]
@shaozi  What happens if you call `console.log(web3.eth.coinbase)` in the callback of the async example?

**Comment by shaozi** [comment]
undefined

**Comment by bardiainjast** [comment]
+1
i'm using node 6.10.2 on ubuntu 17.10 and npm 3.10.10
the problem does not exists on web3 version 0.20.2

**Comment by Westlad** [comment]
Same here with node 8.4 and OSx.  Synchronous calls give undefined.

**Comment by gmk292** [comment]
Please refer to this gist: 
https://gist.github.com/gmk292/5e2bed448a6373502284bf0020fe453b

I don't know whether this approach is recommended or not. These functions are extracted from Web3 HttpProviders. I am currently using this for making synchronous calls.

**Comment by shaozi** [comment]
That is still async.

**Comment by gmk292** [comment]
I am not sure what you are expecting. As far as I can understand, this line https://gist.github.com/gmk292/5e2bed448a6373502284bf0020fe453b#file-ethsync-js-L77 clearly tells that it will make a synchronous call.

Are you expecting a native web3.js solution?

**Comment by nivida** [comment]
I'll close this issue because web3.eth.coinbase does not exists please have a look at the documention (https://web3js.readthedocs.io/en/1.0/web3-eth.html) 😄
