### ISSUE TITLE
Public address received from private key is not the same as real address

### ISSUE THREAD

**Issue by dzarezenko** [ethereum/web3.js#1094]
I have generated new address with __MyEtherWallet__ and received private key. When I have tried to execute this code:

```
var from = web3.eth.accounts.privateKeyToAccount(ETH_OWNER_PRIVATE);
console.log(from);
```

I have noticed that `from.address` value is not the same as my address for this private key. 
I am confused. What can it be?

Thanks!

**Comment by dzarezenko** [comment]
Looks like private key should starts with `0x` prefix for the correct work.

**Comment by evalenzuela** [comment]
@dzarezenko you save me a lot of time!! thanks

**Comment by damianobarbati** [comment]
Wow, I lost a lot of time in this: why not emitting a simple warning when prv key doesn't start with 0x?
