### ISSUE TITLE
'logs' subscription not converting `fromBlock` to hex

### ISSUE THREAD

**Issue by perissology** [ethereum/web3.js#1097]
When calling `web3.eth.subscribe('logs', {fromBlock: 1823919})`, the sent request is:

```
{
  "jsonrpc": "2.0",
  "id": 7,
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": 1823919,
    }
  ]
}
```

and parity returns the error: `Invalid params: invalid type: integer `1823919`, expected a block number or 'latest', 'earliest' or 'pending'.`

If I call `myContract.events.allEvents({fromBlock: 1823919})`, the sent request is:

```
{
  "jsonrpc": "2.0",
  "id": 5,
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "0x1bd4af",
      "address": myContract_address,
      "topics": []
    }
  ]
}
```

and the getLogs call is successfull.

**Comment by nivida** [comment]
@perissology This issue will be solved in version 1.0.0.beta-36.
