### ISSUE TITLE
npm install web3 doesn't install /dist/web3.min.js

### ISSUE THREAD

**Issue by wrisx** [ethereum/web3.js#1099]
When doing a fresh project, npm install web3 doesn't install anything in the module web3 other than src folder. Dist/web3.min.js required by front end is not there

**Comment by gasolin** [comment]
same issue as https://github.com/ethereum/web3.js/issues/1041

**Comment by nivida** [comment]
Please have a look at: https://github.com/ethereum/web3.js/issues/1041

**Comment by igormuba** [comment]
Still not fixed, what should I do to get the min?

**Comment by luiz1919** [comment]
I have the same problem and it doesnt' work in any way, even in the #1041 ... I am completely lost, the file web3.min.js doesnt exist anymore in beta 41, and the code in the web fails by saying, " Web3 is not defined"... any help?
