### ISSUE TITLE
Web3 Installation Error

### ISSUE THREAD

**Issue by iluvandrewko** [ethereum/web3.js#1106]
Below (all the way at the bottom of the log) is the error. Can someone explain what is happening here? It looks like ENOENT is the problem...

$ npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp D                                                                                                                                                                            oS issue
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit  git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible resetting remote C:\Users\A                                                                                                                                                           Ko\AppData\Roaming\npm-cache\_git-remotes\git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e b                                                                                                                                                           ecause of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }

> scrypt@6.0.3 preinstall C:\Users\AKo\node_modules\.staging\scrypt-483a6835
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\AKo\node_modules\scrypt
> node-gyp rebuild

C:\Users\AKo\node_modules\scrypt>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu                                                                                                                          les\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebu                                                                                                                          ild"
gyp ERR! cwd C:\Users\AKo\node_modules\scrypt
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\AKo
+-- web3-bzz@1.0.0-beta.22
| +-- got@7.1.0
| | +-- decompress-response@3.3.0
| | | `-- mimic-response@1.0.0
| | +-- duplexer3@0.1.4
| | +-- get-stream@3.0.0
| | +-- is-plain-obj@1.1.0
| | +-- is-retry-allowed@1.1.0
| | +-- is-stream@1.1.0
| | +-- isurl@1.0.0
| | | +-- has-to-string-tag-x@1.4.1
| | | | `-- has-symbol-support-x@1.4.1
| | | `-- is-object@1.0.1
| | +-- lowercase-keys@1.0.0
| | +-- p-cancelable@0.3.0
| | +-- p-timeout@1.2.0
| | | `-- p-finally@1.0.0
| | +-- safe-buffer@5.1.1
| | +-- timed-out@4.0.1
| | +-- url-parse-lax@1.0.0
| | | `-- prepend-http@1.0.4
| | `-- url-to-options@1.0.1
| +-- swarm-js@0.1.35
| | +-- buffer@5.0.8
| | | +-- base64-js@1.2.1
| | | `-- ieee754@1.1.8
| | +-- decompress@4.2.0
| | | +-- decompress-tar@4.1.1
| | | | +-- file-type@5.2.0
| | | | `-- tar-stream@1.5.4
| | | |   +-- bl@1.2.1
| | | |   +-- end-of-stream@1.4.0
| | | |   `-- readable-stream@2.3.3
| | | |     +-- core-util-is@1.0.2
| | | |     +-- isarray@1.0.0
| | | |     +-- process-nextick-args@1.0.7
| | | |     +-- string_decoder@1.0.3
| | | |     `-- util-deprecate@1.0.2
| | | +-- decompress-tarbz2@4.1.1
| | | | +-- file-type@6.2.0
| | | | +-- seek-bzip@1.0.5
| | | | `-- unbzip2-stream@1.2.5
| | | |   +-- buffer@3.6.0
| | | |   | `-- base64-js@0.0.8
| | | |   `-- through@2.3.8
| | | +-- decompress-targz@4.1.1
| | | +-- decompress-unzip@4.0.1
| | | | +-- file-type@3.9.0
| | | | +-- get-stream@2.3.1
| | | | | `-- pinkie-promise@2.0.1
| | | | |   `-- pinkie@2.0.4
| | | | `-- yauzl@2.8.0
| | | |   +-- buffer-crc32@0.2.13
| | | |   `-- fd-slicer@1.0.1
| | | |     `-- pend@1.2.0
| | | +-- graceful-fs@4.1.11
| | | +-- make-dir@1.0.0
| | | +-- pify@2.3.0
| | | `-- strip-dirs@2.0.0
| | |   `-- is-natural-number@4.0.1
| | +-- fs-extra@2.1.2
| | | `-- jsonfile@2.4.0
| | +-- fs-promise@2.0.3
| | | +-- any-promise@1.3.0
| | | +-- mz@2.7.0
| | | | `-- object-assign@4.1.1
| | | `-- thenify-all@1.6.0
| | |   `-- thenify@3.3.0
| | +-- mime-types@2.1.17
| | | `-- mime-db@1.30.0
| | +-- mkdirp-promise@5.0.1
| | | `-- mkdirp@0.5.1
| | |   `-- minimist@0.0.8
| | +-- mock-fs@4.4.1
| | +-- setimmediate@1.0.5
| | +-- tar.gz@1.0.5
| | | +-- bluebird@2.11.0
| | | +-- commander@2.8.1
| | | | `-- graceful-readlink@1.0.1
| | | +-- fstream@1.0.11
| | | | `-- rimraf@2.6.2
| | | |   `-- glob@7.1.2
| | | |     +-- fs.realpath@1.0.0
| | | |     +-- inflight@1.0.6
| | | |     +-- minimatch@3.0.4
| | | |     | `-- brace-expansion@1.1.8
| | | |     |   +-- balanced-match@1.0.0
| | | |     |   `-- concat-map@0.0.1
| | | |     `-- path-is-absolute@1.0.1
| | | +-- mout@0.11.1
| | | `-- tar@2.2.1
| | |   `-- block-stream@0.0.9
| | `-- xhr-request-promise@0.1.2
| |   `-- xhr-request@1.0.1
| |     +-- buffer-to-arraybuffer@0.0.2
| |     | `-- tape@3.6.1
| |     |   +-- deep-equal@0.2.2
| |     |   +-- defined@0.0.0
| |     |   +-- glob@3.2.11
| |     |   | `-- minimatch@0.3.0
| |     |   |   +-- lru-cache@2.7.3
| |     |   |   `-- sigmund@1.0.1
| |     |   +-- object-inspect@0.4.0
| |     |   `-- resumer@0.0.0
| |     +-- object-assign@3.0.0
| |     +-- query-string@2.4.2
| |     | `-- strict-uri-encode@1.1.0
| |     +-- simple-get@1.4.3
| |     | +-- once@1.4.0
| |     | | `-- wrappy@1.0.2
| |     | `-- unzip-response@1.0.2
| |     +-- timed-out@2.0.0
| |     `-- url-set-query@1.0.0
| `-- underscore@1.8.3
+-- web3-eth-personal@1.0.0-beta.23
| +-- web3-core@1.0.0-beta.23
| | `-- web3-core-requestmanager@1.0.0-beta.23
| |   +-- web3-providers-http@1.0.0-beta.23
| |   | `-- xhr2@0.1.4
| |   +-- web3-providers-ipc@1.0.0-beta.23
| |   | `-- oboe@2.1.3
| |   |   `-- http-https@1.0.0
| |   `-- web3-providers-ws@1.0.0-beta.23
| |     `-- websocket@1.0.24  (git://github.com/frozeman/WebSocket-Node.git#7004c39c42ac98875ab61126e5b4a925430f592c)
| |       +-- debug@2.6.9
| |       | `-- ms@2.0.0
| |       +-- nan@2.7.0
| |       +-- typedarray-to-buffer@3.1.2
| |       `-- yaeti@0.0.6
| +-- web3-core-helpers@1.0.0-beta.23
| | `-- web3-eth-iban@1.0.0-beta.23
| |   `-- bn.js@4.11.8
| +-- web3-core-method@1.0.0-beta.23
| | `-- web3-core-promievent@1.0.0-beta.22
| |   `-- bluebird@3.3.1
| +-- web3-net@1.0.0-beta.23
| `-- web3-utils@1.0.0-beta.23
|   +-- bn.js@4.11.6
|   +-- eth-lib@0.1.27
|   | +-- elliptic@6.4.0
|   | | +-- brorand@1.1.0
|   | | +-- hash.js@1.1.3
|   | | +-- hmac-drbg@1.0.1
|   | | +-- inherits@2.0.3
|   | | +-- minimalistic-assert@1.0.0
|   | | `-- minimalistic-crypto-utils@1.0.1
|   | +-- keccakjs@0.2.1
|   | | +-- browserify-sha3@0.0.1
|   | | | `-- js-sha3@0.3.1
|   | | `-- sha3@1.2.0
|   | +-- nano-json-stream-parser@0.1.2
|   | +-- servify@0.1.12
|   | | +-- body-parser@1.18.2
|   | | | +-- bytes@3.0.0
|   | | | +-- content-type@1.0.4
|   | | | +-- depd@1.1.1
|   | | | +-- http-errors@1.6.2
|   | | | | `-- setprototypeof@1.0.3
|   | | | +-- iconv-lite@0.4.19
|   | | | +-- on-finished@2.3.0
|   | | | | `-- ee-first@1.1.1
|   | | | +-- qs@6.5.1
|   | | | +-- raw-body@2.3.2
|   | | | | `-- unpipe@1.0.0
|   | | | `-- type-is@1.6.15
|   | | |   `-- media-typer@0.3.0
|   | | +-- cors@2.8.4
|   | | | `-- vary@1.1.2
|   | | +-- express@4.16.2
|   | | | +-- accepts@1.3.4
|   | | | | `-- negotiator@0.6.1
|   | | | +-- array-flatten@1.1.1
|   | | | +-- content-disposition@0.5.2
|   | | | +-- cookie@0.3.1
|   | | | +-- cookie-signature@1.0.6
|   | | | +-- encodeurl@1.0.1
|   | | | +-- escape-html@1.0.3
|   | | | +-- etag@1.8.1
|   | | | +-- finalhandler@1.1.0
|   | | | +-- fresh@0.5.2
|   | | | +-- merge-descriptors@1.0.1
|   | | | +-- methods@1.1.2
|   | | | +-- parseurl@1.3.2
|   | | | +-- path-to-regexp@0.1.7
|   | | | +-- proxy-addr@2.0.2
|   | | | | +-- forwarded@0.1.2
|   | | | | `-- ipaddr.js@1.5.2
|   | | | +-- range-parser@1.2.0
|   | | | +-- send@0.16.1
|   | | | | +-- destroy@1.0.4
|   | | | | `-- mime@1.4.1
|   | | | +-- serve-static@1.13.1
|   | | | +-- setprototypeof@1.1.0
|   | | | +-- statuses@1.3.1
|   | | | `-- utils-merge@1.0.1
|   | | +-- request@2.83.0
|   | | | +-- aws-sign2@0.7.0
|   | | | +-- aws4@1.6.0
|   | | | +-- caseless@0.12.0
|   | | | +-- combined-stream@1.0.5
|   | | | | `-- delayed-stream@1.0.0
|   | | | +-- extend@3.0.1
|   | | | +-- forever-agent@0.6.1
|   | | | +-- form-data@2.3.1
|   | | | | `-- asynckit@0.4.0
|   | | | +-- har-validator@5.0.3
|   | | | | +-- ajv@5.2.3
|   | | | | | +-- co@4.6.0
|   | | | | | +-- fast-deep-equal@1.0.0
|   | | | | | +-- json-schema-traverse@0.3.1
|   | | | | | `-- json-stable-stringify@1.0.1
|   | | | | |   `-- jsonify@0.0.0
|   | | | | `-- har-schema@2.0.0
|   | | | +-- hawk@6.0.2
|   | | | | +-- boom@4.3.1
|   | | | | +-- cryptiles@3.1.2
|   | | | | | `-- boom@5.2.0
|   | | | | +-- hoek@4.2.0
|   | | | | `-- sntp@2.0.2
|   | | | +-- http-signature@1.2.0
|   | | | | +-- assert-plus@1.0.0
|   | | | | +-- jsprim@1.4.1
|   | | | | | +-- extsprintf@1.3.0
|   | | | | | +-- json-schema@0.2.3
|   | | | | | `-- verror@1.10.0
|   | | | | `-- sshpk@1.13.1
|   | | | |   +-- asn1@0.2.3
|   | | | |   +-- bcrypt-pbkdf@1.0.1
|   | | | |   +-- dashdash@1.14.1
|   | | | |   +-- ecc-jsbn@0.1.1
|   | | | |   +-- getpass@0.1.7
|   | | | |   +-- jsbn@0.1.1
|   | | | |   `-- tweetnacl@0.14.5
|   | | | +-- is-typedarray@1.0.0
|   | | | +-- isstream@0.1.2
|   | | | +-- json-stringify-safe@5.0.1
|   | | | +-- oauth-sign@0.8.2
|   | | | +-- performance-now@2.1.0
|   | | | +-- stringstream@0.0.5
|   | | | +-- tough-cookie@2.3.3
|   | | | | `-- punycode@1.4.1
|   | | | +-- tunnel-agent@0.6.0
|   | | | `-- uuid@3.1.0
|   | | `-- xhr@2.4.0
|   | |   +-- global@4.3.2
|   | |   | +-- min-document@2.19.0
|   | |   | | `-- dom-walk@0.1.1
|   | |   | `-- process@0.5.2
|   | |   +-- is-function@1.0.1
|   | |   +-- parse-headers@2.0.1
|   | |   | +-- for-each@0.3.2
|   | |   | `-- trim@0.0.1
|   | |   `-- xtend@4.0.1
|   | `-- ws@3.2.0
|   |   +-- async-limiter@1.0.0
|   |   `-- ultron@1.1.0
|   +-- ethjs-unit@0.1.6
|   | `-- bn.js@4.11.6
|   +-- number-to-bn@1.7.0
|   | +-- bn.js@4.11.6
|   | `-- strip-hex-prefix@1.0.0
|   |   `-- is-hex-prefixed@1.0.0
|   +-- randomhex@0.1.5
|   `-- utf8@2.1.1
`-- web3-shh@1.0.0-beta.23
  `-- web3-core-subscriptions@1.0.0-beta.23
    `-- eventemitter3@1.1.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\AKo\package.json'
npm WARN AKo No description
npm WARN AKo No repository field.
npm WARN AKo No README data
npm WARN AKo No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

**Comment by lzl124631x** [comment]
Try this https://github.com/felixrieseberg/windows-build-tools/issues/56#issuecomment-308739624 ?

npm --add-python-to-path='true' --debug install --global windows-build-tools

Run it in powershell as administrator

**Comment by nivida** [comment]
Please have a look at this issue: https://github.com/ethereum/web3.js/issues/1783
