### ISSUE TITLE
react native web3.js call

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#1108]
Hi, I have simple method to connect go-ethereum that runs in local device and trying to check the web3 connection. this is my code 

```const Web3 = require('web3')
var web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))
console.log(web3);
```
sample web3 log result 
```
Web3 {_requestManager: RequestManager, currentProvider: HttpProvider, eth: Eth, db: DB, shh: Shh, …}
bzz
:
Swarm {_requestManager: RequestManager, blockNetworkRead: ƒ, syncEnabled: ƒ, swapEnabled: ƒ, download: ƒ, …}
currentProvider
:
HttpProvider {host: "http://localhost:8545", timeout: 0, user: undefined, password: undefined}
db
:
DB {_requestManager: RequestManager, putString: ƒ, getString: ƒ, putHex: ƒ, getHex: ƒ}
eth
:
```
But when check the connection with following code

```
if(!web3.isConnected()) {
    console.log("connection failed");
} else {
    console.log("connection successful");
}
```
It always returns **connection failed**. Can you please help me ?

**Comment by dacarley** [comment]
If you're running this code in react native, how are you running geth on the device?  Are you certain that geth is actually running?  Can you connect to http://localhost:8545 with a browser on the device?

React Native exposes the `fetch` API.  What is the result of placing `var foo = fetch("http://localhost:8545")` in your code?

**Comment by jitendraauxesis** [comment]
Im tried using web3 with import statement like,
import * as Web3 from 'web3';
var Web3 = require('web3');
in following code
var web3;
if (typeof web3 !== 'undefined') {
        web3 = new Web3(new Web3.currentProvider);
    } else {
        web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:1000"));
    }

in function
if (!web3.isConnected()) {
 console.log(web3.isConnected(),"not connected")
}else{
 console.log(web3.isConnected(),"connected")
}

always shows 
false not connected

**Comment by ToJen** [comment]
@dacarley what I do is use ngrok to expose my http://localhost:8545 and then pass the ngrok url to the HttpProvider.

**Comment by themotu** [comment]
Same issue here, tried my aws instance and my local network instance. Always shows false.

**Comment by themotu** [comment]
@dacarley foo returns Promise {_40: 0, _65: 0, _55: null, _72: null} which is basically what I'm getting from my app both from ganache and my geth instance with CORS *

also tried using ngrok with 0.0.0.0 and gnache

**Comment by john-osullivan** [comment]
Has anything ever happened with this?

**Comment by dev1644** [comment]
http://localhost:8545 is the default endpoint of Geth JSON RPC Server, if you are passing this in Web3 provider and not getting a connection, this means either the endpoint is not exposed or Geth isn't running at all.

There are some issues while importing web3 in React Native Project because of Crypto-Js dependency.
