### ISSUE TITLE
Accept ERC20 token payment using web3.js

### ISSUE THREAD

**Issue by jatarga** [ethereum/web3.js#1109]
I'm accepting Ethereum and Bitcoin payments in an trading site and I persist user balances in a database. I'd like to be able to receive ERC20 tokens too (like Bancor) if possible. **I am not creating new token contract, just want to accept them as payment.**

As the %90 of the answers on the web, they suggest polling `filter` event of `Transfer(address,address,uint256)` using web3.js. Please correct me if I'm wrong, but how will I get corresponding TX of that payment from that event?

**Comment by greggmojica** [comment]
+1

**Comment by resultakakdev** [comment]
+1

**Comment by nivida** [comment]
Please ask your question on https://ethereum.stackexchange.com/
