### ISSUE TITLE
Unexpected output using .toWei()

### ISSUE THREAD

**Issue by ledfusion** [ethereum/web3.js#1110]
I'm sending transactions and I need to convert values using `web3.util.toWei()`

As I lower the amount of `ether`, the amount of `wei` lowers accordingly:

```
> web3.utils.toWei(0.001)
'1000000000000000'            // OK
> web3.utils.toWei(0.0001)
'100000000000000'             // OK
> web3.utils.toWei(0.00001)
'10000000000000'              // OK
> web3.utils.toWei(0.000001)
'1000000000000'               // OK
```
But as I cross below `0.000001`, the resulting amount of wei becomes kind of arbitrary:
```
> web3.utils.toWei(0.0000001)
'2377000000000000000000'            // ?

> web3.utils.toWei(0.00000001)
'2378000000000000000000'            // ?

> web3.utils.toWei(0.000000001)
'2379000000000000000000'            // ?

> web3.utils.toWei(0.0000000001)
'23710000000000000000000'            // ?

> web3.utils.toWei(0.00000000001)
'23711000000000000000000'            // ?

> web3.utils.toWei(0.000000000001)
'23712000000000000000000'            // ?

> web3.utils.toWei(0.0000000000001)
'23713000000000000000000'            // ?

> web3.utils.toWei(0.00000000000001)
'23714000000000000000000'            // ?
```

Multiplying the value by 5, the result increases the first digit by 4 units (the rest of digits stay the same)
```
> web3.utils.toWei(0.00000001)
'2378000000000000000000'

> web3.utils.toWei(0.00000005)
'6378000000000000000000'
```

**Is this expected?**
I know Javascript is not especially designed for precision floating point operations, but this issue does not look anything like a rounding up/down precision error. 

I am currently using version:
```
package.json
{
   ...
   "web3": "^1.0.0-beta.23"
}
```

Thank you!

**Comment by ledfusion** [comment]
Switching to a String does work as expected:
```
> web3.utils.toWei(0.000000000001)
'23712000000000000000000'

> web3.utils.toWei('0.000000000001')
'1000000'
```

If a numeric input value goes out of an acceptable range, I think that `toWei()` should at least warn about potential incorrect results

Thank you

**Comment by frozeman** [comment]
Thanks for the catch i throw an error now when passing in numbers, which aren't strings or BigNumber objects in 037b116
