### ISSUE TITLE
Unable to pass two parameters to the constructor of the contract

### ISSUE THREAD

**Issue by varadarajana** [ethereum/web3.js#1112]
I created a contract that involves two parameters for construction:
```js
contract EventsLedger {

bytes 32 demand;
bytes32 supply;

function EventsLedger (bytes32 _producer, bytes32 _consumer) {
        demand=_producer;
        supply=_consumer;
    }

...
}
```
When I try to reply this on a node console with web3js I get an error when I invoke 2 parameters.
```js
>eventsContract= web3.eth.contract(abiDefinition)
>byteCode = compiledCode.contracts[':EventsLedger'].bytecode
>deployedContract = eventsContract.new('advertiser1','advertiser2',{data: byteCode, from: web3.eth.accounts[0], gas: 4700000})
```
This statement sends an error as sendTransaction is incorrect. Am I missing the way I am invoking. This works fine for single parameter as contractor, or using a single parameter as array.

Thanks
Varada

**Comment by raymondcarl** [comment]
@varadarajana,  it looks like you have the input correct inputs.  Is there a line where you specify the address of the contract and create an instance of the contract?

**Comment by varadarajana** [comment]
Here are the CLI commands I use to create the instance:

$ node
>Web3 = require('web3')
>web3 = new Web3();
>web3.setProvider(new Web3.providers.HttpProvider("http://localhost:8545"));
>code = fs.readFileSync('EventsLedger.sol').toString()
>solc = require('solc')
>compiledCode = solc.compile(code)
>abiDefinition=JSON.parse(compiledCode.contracts[':EventsLedger'].interface)
>AdImpression= web3.eth.contract(abiDefinition)
>byteCode = compiledCode.contracts[':EventsLedger'].bytecode
>deployedContract = AdImpression.new('advertiser1','advertiser2',{data: byteCode, from: web3.eth.accounts[0], gas: 4700000})
>deployedContract.address
'0xa79721b60cc5f8c1badbd1687a02fe6cf7535801'
>contractInstance = AdImpression.at(deployedContract.address)

**Comment by frozeman** [comment]
You might need to pass a callback to the `...new` function. Or better use web3.js 1.0 beta. It has a new API: http://web3js.readthedocs.io/en/1.0/
