### ISSUE TITLE
[1.0] account management API questions

### ISSUE THREAD

**Issue by connectdotz** [ethereum/web3.js#1113]
First of all, it is great to see account management API made it to web3, I think it will go a long way to reduce friction for dapp development. 

A few questions to make sure I understand the idea behind the design: 

1. Is there any particular reason the current accounts implementation does not support HD wallet (BIP32/BIP39) for account creation? 
1. the current Wallet.save/Wallet.load is hard-coded with localStorage, will it make sense to allow customization?
1. while there is a clear extension point for `provider`, it didn't seem to be one for accounts. Most of the wallets out there used provider interface to inject its own accounts. It's a necessary evil before, but now with the modular accounts API, I wonder would it make sense to split extension points and allow accounts to be customized independent of the provider? (better for composition and less monolithic)

**Comment by frozeman** [comment]
1. we were planning on doing that, but it is more work. I would be happy for contributions on that side.
2. load save is only available in the browser, and you can easily encrypt yourself and choose what ever storage you like, the API is not restricting that. Load/save isa convenient function.
3. Not sure if i understand right, but there is a separate `web3-eth-accounts` package, if you want it network ID it can't sign, which if not give, will be automatically fetched from the node.

**Comment by netpi** [comment]
@jellegerbrandy @frozeman 
This PR can solve this problem https://github.com/ethereum/web3.js/pull/1755

**Comment by nivida** [comment]
@jellegerbrandy Feel free to submitt a PR with a [TransactionSigner](https://web3js.readthedocs.io/en/1.0/web3.html#transactionsigner) object. We could add the possibility to pass a string like ``hd-wallet`` instead of an object which will load the HDWallet transaction signer.
