### ISSUE TITLE
What's the advantage of using the Meteor package as opposed to the regular npm package?

### ISSUE THREAD

**Issue by elie222** [ethereum/web3.js#1114]
What's the advantage of using the Meteor package as opposed to the regular npm package?

If there's no difference I may as well use the npm version.

**Comment by frozeman** [comment]
This was not always the case in meteor, and its currently mainly for the meteor frontend apps. I can think of removing it in the future.

**Comment by elie222** [comment]
Thanks. So you'd recommend using the regular npm package from now on. Or
this package still has value?

Would you still recommend building dapps with Meteor, or it doesn't matter
to much if you use CRA or any other solution nowadays?

**Comment by frozeman** [comment]
The package is still available, and i will continue to update not, but it doesn't work for the meteor backend, here you need to use the npm package anyway.

Meteor is still viable, as it is easy and fast top build apps. but there are also other good solutions, like react and vue.js. This is up to you.
