### ISSUE TITLE
web3.currentProvider.sendAsync is undefined

### ISSUE THREAD

**Issue by lightninglu10** [ethereum/web3.js#1119]
Hey guys, getting a weird bug here.

I'm setting up my web3 like this

```javascript
var web3 = new Web3(new Web3.providers.HttpProvider(BLOCKCHAIN_ADDR));
```

But I'm getting an error with web3.currentProvider.sendAsync is undefined, but web3.currentProvider.send is defined. Anyone know what's up?

**Comment by dkchv** [comment]
try to add before create new instance:
`Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send`

**Comment by frozeman** [comment]
@dkchv thanks, could you tell me where you get this? which version of web3.js?

**Comment by dkchv** [comment]
I tried to use web3 v1, but out app also use truffle-contract, which use web3 0.20. So then I `setProvider` to web3 v1, I also set this provider to truffle-contract. And finally truflle-contract tried to invoke sendAsync throw web3 0.20 interface.
Line above fix this difference for httpProvider bettween v1 and v0.20.

**Comment by pfrank8** [comment]
Hey folks, another potential fix for this could be to make sure you import Web3 before you import any artifacts -- even if you define networks later.

**Comment by Alexintosh** [comment]
I have the same issue, strangely, this happen only on specific iphone models.
The workaround doesn't seem to work.
```
"web3": "^0.20.6",
"web3-provider-engine": "13.6.0"
```

**Comment by Alexintosh** [comment]
This issue should probably be reopened

**Comment by Alexintosh** [comment]
@devzl it doesn't work client side with Infura nodes. Particularly with American iPhones.

**Comment by Alexintosh** [comment]
Following my previous comment. I couldn't find any way to solve this client side, so I ended up only signing the transaction in the mobile client and broadcasting it server side. If you are interested in a microservice to do that you can find the [Tx-broadcaster Repository by DEXlab.io here.](https://github.com/dexlab-io/Tx-broadcaster)

**Comment by Alexintosh** [comment]
Not sure why this has been closed ¯\_(ツ)_/¯

**Comment by nivida** [comment]
Oops sorry.. 🙈

**Comment by jsliu27** [comment]
> Hey guys, getting a weird bug here.
> 
> I'm setting up my web3 like this
> 
> ```js
> var web3 = new Web3(new Web3.providers.HttpProvider(BLOCKCHAIN_ADDR));
> ```
> 
> But I'm getting an error with web3.currentProvider.sendAsync is undefined, but web3.currentProvider.send is defined. Anyone know what's up?

您好，我想知道如何创建自己的web3，来实现链上支付，如果您知道，还请您多多帮助一下

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
