### ISSUE TITLE
sendSignedTransaction is not working

### ISSUE THREAD

**Issue by NicholasJarr** [ethereum/web3.js#1134]
When I call sendSignedTransaction it throws: `invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes`. I'm using geth with a private chain (with the -dev flag). The web3.js was installed with npm and the version is: ^1.0.0-beta.24.
I get the private key from the decrypt method and using the JSON from the keystore. start is the contract function that I'm calling. It has one argument (an int) and it is not payable. I think there might something wrong with the rawTransaction that is returned with the signTransaction method.

```javascript
var admin = "0x2694fC48505267C8159850aC7Df2c280a17d2C46";
var contract_address = "0x19496da364962A5Ac96139775F8d50d5d31605f9";
var tx = {
    from: admin,
    to: contract_address,
    gas: 184000,
    data: start.encodeABI(),
    chainId: "1337"
};
web3.eth.accounts.signTransaction(tx, private_key).then((hash) =>{
    web3.eth.sendSignedTransaction(hash.rawTransaction).then((receipt) =>{
        resolve();
    }, (error) =>{
        console.log(error);
        reject(500);
    });
}, (error) =>{
    reject(500);
});
hash.rawTransaction == "0xf986.84d808302cec09419496da364962a5ac96139775f8d50d5d31605f980a495805dad000000000000000000000000000000000000000000000000000000000000001481.8a95a00f9daa90306d103f908f6c8064a5ce005e7608ea14ddf469a73943e2a2ea54b5a012de7959ceee8d3d685d6622d77949a879b364165bcfd6f9fea88c4d1ea51aa3"
```

**Comment by NicholasJarr** [comment]
I have found a temporary solution:
```javascript
web3.eth.personal.unlockaccount(admin, "p").then((suc) =>{
    start.send(tx).then((receipt) =>{
        console.log(receipt);
        web3.eth.personal.lockaccount(admin, "p").then((suc) => {
            resolve();
        });
    }, (error) =>{
        console.log(error);
        web3.eth.personal.lockaccount(admin, "p").then((suc) =>{
            reject(500);
        });
    });
}, (error) =>{
    reject(500);
});
```

**Comment by idrabenia** [comment]
The same error!

**Comment by Wullee** [comment]
You must sign the directives, you may need to visit the wiki.

**Comment by idrabenia** [comment]
Hello @Wullee ,

What does it mean "sign the directives"? Transaction is signed in code under - as you may see.
What is "directive"? I see only javascript objects and properties.

**Comment by idrabenia** [comment]
"you may need to visit the wiki"
This code almost from wiki.

**Comment by NicholasJarr** [comment]
I'm using the documentation from [ReadTheDocs](http://web3js.readthedocs.io/en/1.0/getting-started.html)

**Comment by daragao** [comment]
Anyone found a solution for this?

If i use testrpc and add chainId to the transaction object it signs well, but with geth it does not :(
Any ideas?

**Comment by zaro** [comment]
Can confirm the same, I made a private chain with puppeth, and if I change the chain_id to 3 for example, it works fine. If I try to use chain_id 1337 it fails.

**Comment by imhari213** [comment]
**web3.eth.sendSignedTransaction** is not a function getting this error can anyone help me on this please....

**Comment by nguyenquangthang1997** [comment]
I have this issue: after I send signTransaction, transactionHash event is emit but then nothing happenning, i search this transaction return from transactionHash even in ropsten is not found, please fix it

**Comment by roqueorts** [comment]
Good morning,
Is there any solution? Still not working with ropsten blockchain, when it works using Ganache.
Thanks
