### ISSUE TITLE
getTransactionReceipt should include status if it's present in the rpc response.

### ISSUE THREAD

**Issue by michalwarda** [ethereum/web3.js#1138]
After Byzantium rolled out the getTransactionReceipt rpc call returns also status field which indicates if the transaction passed or not: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt. I think it should be added to the existing output of the function inside web3.

**Comment by kot-begemot** [comment]
Indeed, that would be great to have.

**Comment by kot-begemot** [comment]
Good news, you can have it already. Make sure your geth client version is at least 1.7.3 or above.

**Comment by ShengkunZhang** [comment]
@kot-begemot @michalwarda 
no status
geth client version 1.7.3

**Comment by sbwdlihao** [comment]
no status in mac os
geth-darwin-amd64-1.7.3-4bb3c89d

this is a test in private net

```bash
> eth.getTransactionReceipt("0xb8314bbdd1394e65abe5f5f011fd6b668e31156ac2b901752384c1c74f16db89")
{
  blockHash: "0xb701d5b83f4bed349912144ce9f8116fd43192f27d5ecc11f12d12e0972ff6d1",
  blockNumber: 15343,
  contractAddress: null,
  cumulativeGasUsed: 21000,
  from: "0xddd24f735ebb48421577c3f538ba421168649862",
  gasUsed: 21000,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0xd79aa239640d0d497f319579ef328c5d8d63604539acb10896ffb2512bc7b284",
  to: "0x51533a6e1de29c8e69ac063a659054b337a5ce49",
  transactionHash: "0xb8314bbdd1394e65abe5f5f011fd6b668e31156ac2b901752384c1c74f16db89",
  transactionIndex: 0
}
```

**Comment by ShengkunZhang** [comment]
on the main network, I can get this field when txhash 
 is '0x23ec45f5530ca118ebcc1189706b46092d81147c0972434c4fd08967200764c6' ,
but not get 'status' in txhash '0xeacb0daa203bddfcb515b2ee0982b58ca296b6100760824cc2b2d06f5f5fa6c4'
why is that? i can't understand

**Comment by Andromelus** [comment]
Someguy in stackoverflow once said that to get the status property, you need to set, in the genesis file, what is the byzantin block. Not sure if it's true though.

**Comment by Mobelis** [comment]
```json
"config": {
    "chainId": 15,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "daoForkSupport": true
}

**Comment by Pipeliner** [comment]
With `byzantiumBlock` record in genesis file, geth (1.8.3 in my case) returns expected status field.

**Comment by sharif2008** [comment]
@peculiarity @Mobelis  how could I add the feature in already running Geth?
