### ISSUE TITLE
Offline transaction signing

### ISSUE THREAD

**Issue by milosjovac** [ethereum/web3.js#1141]
For Android and iOS there is a [geth wrapper](https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction) that enables mobile apps to sign transactions offline.

I'm trying to find the best way to do the same on react-native, so web3 was natural place to search for such a functionality. Anyhow I cannot find the answer. 

Is Offline transaction signing supported with web3?

**Comment by monokh** [comment]
I didn't find a way to do this using web3 directly. But I did use this module that works well: https://github.com/ethereumjs/ethereumjs-tx

**Comment by milosjovac** [comment]
@monokh you are right. Somehow I missed it, but there is an example in official web3 documentation when already signed transaction is sent. [They are using ethereumjs.tx for signing.](https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction)

**Comment by neuhaus** [comment]
See also: https://gist.github.com/neuhaus/7387edf411513a9f11f1242dcec8d62e
