### ISSUE TITLE
Security warning when installing web3.js

### ISSUE THREAD

**Issue by antoniocapelo** [ethereum/web3.js#1142]
When installing the newest version of `web3` — 1.0.0-beta.24 — with npm, it gives the following output

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

The cause of this issue can be checked [here](https://nodesecurity.io/check/web3). 

It seems like web3 is pushing a subdependency of a `minimatch` version which has a known Regular Expression Denial of Service.

I'm not entirely inside the codebase to know if this is indeed a risk we're taking.

Some urgent advise regarding this issue is appreciated.

Thanks in advance.

**Comment by JamesKnippel** [comment]
Same issue! Please check this out!!

**Comment by lukehedger** [comment]
This is an issue with `xhr-request` not `web3`. The issue has been raised on that repo (https://github.com/Jam3/xhr-request/issues/3) so this can be closed.

**Comment by lukehedger** [comment]
The issue with `xhr-request` has now been resolved. Awaiting merge of https://github.com/MaiaVictor/xhr-request-promise/pull/2 before updating the [web3.js dependencies](https://www.npmjs.com/browse/depended/xhr-request-promise) that use `xhr-request-promise`.

**Comment by nivida** [comment]
This got fixed with the refactoring. Please update to the latest version of Web3.js (1.0.0-beta.51).
