### ISSUE TITLE
web3.bzz.upload returning false

### ISSUE THREAD

**Issue by jucasoliveira** [ethereum/web3.js#1143]
I'm trying to upload a file to Swarm from the browser . 
My application get the file by <input type='file/> and I'm passing it to web3.bzz as a buffer

Following the documentation , I'm trying to upload like this : 

```
// upload from disk in the browser
bzz.upload({pick: "file"}) // could also be "directory" or "data"
.then(console.log);

```

The console.log it's returning false.

I could upload files from the disk, raw data and raw directory without problem.

**Comment by dacarley** [comment]
The API for web3 has changed in the beta branch, but the documentation has not yet been updated.

The correct code should be:

```javascript
    this.web3.bzz.pick.file()
        .then(console.log);
```
