### ISSUE TITLE
How can I subscribe to all ether transaction events

### ISSUE THREAD

**Issue by kot-begemot** [ethereum/web3.js#1145]
**web3.js** 
version: 1.0.0-beta.24

I want to listen all ether transaction events and then write them into database once transferred value is bigger than 0. I went multiple times though the (documentation)[https://web3js.readthedocs.io/en/1.0/web3-eth.html#id56]. Can you point me the a page or tell where can I find any info about that?

**Comment by kot-begemot** [comment]
Ok, I think the answer was this one

```
web3.eth.subscribe('pendingTransactions', function(error, result){})
.on("data", function(trxData){
  web3.eth.getTransaction(trxData).then(console.log);
});
```

Got confused due to #1144

**Comment by raahil190** [comment]
This doesn't seem to work for me. I get the following error after running this via node  
> connection not open on send()

**Comment by raahil190** [comment]
how did you get it to work @kot-begemot ?

**Comment by kot-begemot** [comment]
@raahil190  you might be missing core cors for ws port. Here is how I start my client

geth --datadir /PATH_TO_STORAGE --testnet --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --ws --wsport 8585 --wsorigins="*"

**Comment by raahil190** [comment]
@kot-begemot I can't seem to get it to work without the 
`--wsorigins "*"` flag , that should make it pretty insecure I guess - or is there a way around it ?

**Comment by kot-begemot** [comment]
@raahil190 Depends on your setup. Do you plan to make it available to whole internet?

**Comment by raahil190** [comment]
No - I plan to use it myself only. But if I *don't* use `--wsorigins "*"` it does not work @kot-begemot

**Comment by catalsdevelop** [comment]
Maybe same error, when I start geth in docker. Without "--wsorigins *", I got `connection not open on send()` in my client. Add the cmd line args, it works.
