### ISSUE TITLE
returns null on new web3.eth.Contract(abi).deploy()

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#1147]
"web3": "^1.0.0-beta.24"
```
let Web3 = require('web3')
let web3 = new Web3();
let abi = [{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}];
let contract = new web3.eth.Contract(abi);
let deploy = contract.deploy(); // supposed to return estimateGas, send, encodeABI
//return null
```

why?

**Comment by rstormsf** [comment]
Looks like I had to do this:
```
contract.options.data = {}
```

**Comment by rstormsf** [comment]
so, without setting actual bytecode, I can't estimateGas/encodeABI which defeats the purpose.

**Comment by rstormsf** [comment]
I was stupid, of course you have to supply data, what I was thinking?

**Comment by klivin** [comment]
I was stupid and did the same thing, @rstormsf.   Would be nice for missing bytecode to throw an exception rather than return null...

**Comment by x5engine** [comment]
2020 I was dumb and did it without the bytecode but it seems the fault of the docs not telling you must add it!

also make you sure you add 0x before a bytecode string
