### ISSUE TITLE
TypeScript definition for getGasPrice defines return as Promise<number>, documentation tells it should be Promise<string>

### ISSUE THREAD

**Issue by hodlbank** [ethereum/web3.js#1153]
Documentation here: http://web3js.readthedocs.io/en/1.0/web3-eth.html#getgasprice

> Returns
> Promise returns String - Number string of the current gas price in wei.

Code here:
https://github.com/ethereum/web3.js/blob/1.0/packages/web3/types.d.ts

`getGasPrice(cb?: Callback<number>): Promise<number>`

**Comment by nivida** [comment]
I will close because this issue because the typings are now on DefinitlyTyped.
