### ISSUE TITLE
Web3 & Angular2<

### ISSUE THREAD

**Issue by raisty** [ethereum/web3.js#1155]
Is here any tutorial how too implement web3.js with Angular2<?

After npm install and integration:
`import Web3 from 'web3';`
I get:
`Module '".../node_modules/web3/index"' has no default export.`

It is really hard to implement.

**Comment by raisty** [comment]
BTW I solve problem with bignumber.js error with installing "bignumber.js": "4.1.0"

**Comment by hodlbank** [comment]
Until it is fixed, you can use "allowSyntheticDefaultImports" in "compilerOptions" in tsconfig.json .
Then you can import Web3 as 
`import * as Web3 from 'web3';`

**Comment by BennettLarson** [comment]
Any further news with this problem?

**Comment by raisty** [comment]
I will test it. BTW I upgrade to Angular 2+
