### ISSUE TITLE
How to set up dev environment to debug the library itself?

### ISSUE THREAD

**Issue by doraemondrian** [ethereum/web3.js#1160]
Maybe I'm missing something, but I'm having hard time figuring out how to debug the web3.js library itself.

I've come across a potential bug and have been trying to track down what the cause is without digging into the library itself, just by stepping through each line from chrome developer tools, but have realized it's impossible to figure out the problem just by stepping through a browserified code, especially when everything is so inter-wined together.

More specifically, I'm trying to debug `Contract.methods.MyMethod().send` as it's throwing some rlp error. I've found it's impossible to debug this without digging into the low level code.

But as it stands, the whole thing is a huge collection of multiple node modules, and each module references one another using NPM namespace, which makes it hard to just put a breakpoint or even a `console.log` in any of the code and step through.

Is there a simple way to debug this library? (I'm talking about the ver1.0 branch)

**Comment by nivida** [comment]
We have no simpler way to debug web3.js :)
