### ISSUE TITLE
How to know a contract method call is successful or not like Ethereum Wallet?

### ISSUE THREAD

**Issue by hoanghuynh1995** [ethereum/web3.js#1163]
With Ethereum Wallet, when I choose a function, set parameters, then click 'EXECUTE', but not confirm yet
![image](https://user-images.githubusercontent.com/17693732/32591527-0e9bba36-c552-11e7-80ea-e1a38787226a.png)
As you can see, Ethereum Wallet can determine that transaction will be failed if there is any issue with my inputs.
How can Ethereum Wallet accomplish this without sending transaction? Can I do it using web3js?

**Comment by theoport** [comment]
https://ethereum.stackexchange.com/questions/27452/how-to-estimate-gas-cost

**Comment by hoanghuynh1995** [comment]
So how estimating gas and gas cost can determine a transaction will be successful or not?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/ and have a look at our documentation http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-estimategas
