### ISSUE TITLE
Returning multiple nested arrays returns correctly for first array and returns empty or incorrect for remaining arrays

### ISSUE THREAD

**Issue by theoport** [ethereum/web3.js#1165]
```
contract Test{

  bytes32[3][] arrayOne;
  bytes32[3][] arrayTwo;

  function Test() {
  }

  function addArrayOne(bytes32[3] _arrayOne) public {
    arrayOne.push(_arrayOne);
  }

  function addArrayTwo(bytes32[3] _arrayTwo) public {
    arrayTwo.push(_arrayTwo);
  }

  function getArrays() constant public returns (bytes32[3][], bytes32[3][]) {
    return (array, arrayTwo);
  }
  
}
```

After sending **_addArrayOne(["one", "two", "three"])_** and **_addArrayTwo(["four", "five", "six"])_**, calling **_getArrays()_** returns: 

Result {
  '0': 
   [ [ '0x6f6e650000000000000000000000000000000000000000000000000000000000',
       '0x74776f0000000000000000000000000000000000000000000000000000000000',
       '0x7468726565000000000000000000000000000000000000000000000000000000' ] ],
  '1': [] }

When using remix, calling **_getArrays()_** on the identical contract successfully returns:

{
	"0": "bytes32[3][]: 0xone\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000,two\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000,three\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
	"1": "bytes32[3][]: 0xfour\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000,five\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000,six\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
}

I'm not sure how remix decodes return values but that seems to be the issue here? 
This issues pops up both with web3@0.20.0 and web3@1.0.0-beta.24
Solidity compiler version is v0.4.18 (but that shouldn't make a difference anyway cause remix calls successfully from the same compiled contract)

**Comment by ojow** [comment]
I guess i have the same issue with several `byte64[2][]` arrays in event, Remix is showing everything correctly, web3.js gives garbage after the first array.

**Comment by nivida** [comment]
https://github.com/ethereum/web3.js/issues/1148
