### ISSUE TITLE
eth.sign allow {encoding: 'hex'} parameter

### ISSUE THREAD

**Issue by christoph2806** [ethereum/web3.js#1168]
For `web3.sha3()`, you can specify the that the data is hex-encoded by adding the `{encoding: 'hex'}` parameter. 
For `web3.eth.sign()`, you don't have that option. It would be good to have that. 
The current implementation makes it impossible to sign a hex encoded string, for example a message hash, because a hash usually contains bytes > 127 and therefore this hash cannot be encoded as string (javascript will interpret bytes > 127 as unicode chars and transform them in a 2-byte sequence).

`web3.eth.sign(account, msg)` is basically implemented as `sign(account, web3.sha3('\19Ethereum Signed Message\n'+msg.length+msg)`. It should be possible to call `web3.eth.sign(account, msg, {encoding: 'hex'})` which would be implemented as `sign(account, web3.sha3(Buffer.from('\x19Ethereum Signed Message\n'+(msg.length-2)/2).toString('hex')+msg.slice(2), {encoding: 'hex'}))`

Usecase: 
In the upcoming multisigs which work with presigned transactions, you need to pass a signature to `ecrecover` which is calculated on a hash of the transaction parameters (source, destination, value, data, nonce). 
This is impossible at the moment with `web3.eth.sign`; you need to use non-standard signing functions e.g. from lightwallet (which do not prefix the message), which should be avoided .

**Comment by enderphan94** [comment]
This `web3.utils.sha3(lengthSlot, {encoding: 'hex'})` does not return the same thing as `web3.sha3(lengthSlot, {encoding: 'hex'})`. Any ideas?
