### ISSUE TITLE
Couldn't find package "web3-requestManager" on the "npm" registry.

### ISSUE THREAD

**Issue by Math3v** [ethereum/web3.js#1171]
I'm getting this error while installing with Yarn.

`Couldn't find package "web3-requestManager" on the "npm" registry.`

Yarn version: 1.2.1
OS: OSX

**Comment by OR13** [comment]
I've not been able to install 1.X with yarn ever, if you can get by without it:

```
yarn add web3@0.20.2
```

I'd really like to try out the new features, but I can't seem to find a stable version of 1.0 that will install with yarn or npm.

**Comment by frozeman** [comment]
I thought i removed all references. Is it working now for you?
