### ISSUE TITLE
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable.

### ISSUE THREAD

**Issue by Math3v** [ethereum/web3.js#1172]
I get this warning while installing web3

`npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar`

I'd consider updating the dependencies.

Cheers!

**Comment by sgehrman** [comment]
I'm getting this:

$ npm list -prod

npm ERR! missing: tar.gz@^1.0.5, required by swarm-js@0.1.37
npm ERR! missing: websocket@git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible, required by web3-providers-ws@1.0.0-beta.26

fails to build

**Comment by lukehedger** [comment]
This is caused by `swarm-js` not `web3`. Issue has been raised on that repo (https://github.com/MaiaVictor/swarm-js/issues/10) so this can be closed.

**Comment by lebed2045** [comment]
+1

**Comment by paramtatv** [comment]
Please change the dependency of swarm-js from 37 to 39.
Swarm-js has already been updated.

Thanks

**Comment by nivida** [comment]
@tim-coin this is already done but not released (PR #2000)

**Comment by K84N666LEE** [comment]
# npm i tar -g
/usr/lib
└─┬ tar@4.4.8 
  ├── chownr@1.1.1 
  ├── fs-minipass@1.2.5 
  ├── minipass@2.3.5 
  ├── minizlib@1.2.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── safe-buffer@5.1.2 
  └── yallist@3.0.3 

# npm install web3 -g
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ??  WARNING ?? tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> websocket@1.0.26 install /usr/lib/node_modules/web3/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/lib/node_modules/web3/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/lib/node_modules/web3/node_modules/websocket/build'
/usr/lib
└─┬ web3@1.0.0-beta.37 
  └─┬ web3-core@1.0.0-beta.37
    └─┬ web3-core-requestmanager@1.0.0-beta.37
      └─┬ web3-providers-ws@1.0.0-beta.37
        └── websocket@1.0.26  (git://github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2)
