### ISSUE TITLE
TypeError: web3.eth.contract is not a function

### ISSUE THREAD

**Issue by Math3v** [ethereum/web3.js#1173]
There should be a function `web3.eth.contract` according to the [docs](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract).

Instead I'm getting `TypeError: web3.eth.contract is not a function`.

**Comment by MrTibbles** [comment]
`web3.eth.Contract`

Uppercase "C".

**Comment by josephg** [comment]
The docs for the current version of web3 in npm (1.0beta) are [here](http://web3js.readthedocs.io/en/1.0/index.html)
