### ISSUE TITLE
example/contract_array.html - Runtime Error: out of gas

### ISSUE THREAD

**Issue by stefek99** [ethereum/web3.js#1175]
Playing with examples: https://github.com/ethereum/web3.js/blob/develop/example/contract_array.html

![image](https://user-images.githubusercontent.com/249703/32801587-cf3ea47c-c97d-11e7-95b5-c3cf7d5c4d61.png)

```
  Transaction: 0xa6254da90cb45b15b371ab590a98e2ba66965fead7d2cac820828a8e97240b6d
  Contract created: 0x3b952d90c7beff045398585aa64f989c348137bf
  Gas usage: 0x015f90
  Block Number: 0x06
  Block Time: Tue Nov 14 2017 20:48:35 GMT+0100 (CET)
  Runtime Error: out of gas
```

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
