### ISSUE TITLE
Referencing contracts in docs appear inaccurate.

### ISSUE THREAD

**Issue by joepagan** [ethereum/web3.js#1176]
On [this section](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction)

It appears the docs reference contracts:

    let abi = compiledContract.contracts['nameContract'].interface;
    let bytecode = compiledContract.contracts['nameContract'].bytecode;

Though, this does not work for me, in other examples the contracts need to be prefixed with a colon.

    let abi = compiledContract.contracts[':nameContract'].interface;
    let bytecode = compiledContract.contracts[':nameContract'].bytecode;

Could be a genuine reason, but, as someone new to this I can't get it to work.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
