### ISSUE TITLE
Official "Hello World" greeter contract using deprecated compiling feature

### ISSUE THREAD

**Issue by joepagan** [ethereum/web3.js#1177]
[Official "Hello World" greeter contract using deprecated compiling feature](https://www.ethereum.org/greeter)

Uses:

    eth.getCompilers()
    var greeterCompiled = web3.eth.compile.solidity(greeterSource)

[Then in your own docs you suggest they are being deprecated](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetcompilers)

**Comment by nivida** [comment]
Please create an issue here: https://github.com/ethereum/ethereum.org
