### ISSUE TITLE
Does web3.js handle strings correctly?

### ISSUE THREAD

**Issue by chriseth** [ethereum/web3.js#1179]
Javascript strings are always unicode encoded and ABI strings have to be utf8-ecoded. The "fromASCII" routine does not even throw an exception if it encounters characters outside of the ASCII range: https://github.com/ethereum/web3.js/blob/develop/lib/utils/utils.js#L173

Instead, it just uses the unicode code point and does not properly encode it as utf-8.

Does web3.js in general encode strings properly?

**Comment by wjmelements** [comment]
Using fromAscii is not sufficient, we should use fromUtf8. Here is an example of it failing:

```
내가 제일 잘 나가
```
is not encoded correctly when I send it as a `bytes` parameter.

Expected:
```
0xEB82B4EAB08020ECA09CEC9DBC20EC9E9820EB8298EAB080
```

Actual:
```
web3.toHex('내가 제일 잘 나가')
"0xb0b4ac0020c81cc77c20c79820b098ac00"
```

I think the fix is to always use fromUtf8 instead.

**Comment by wjmelements** [comment]
https://github.com/ethereum/web3.js/pull/1398
