### ISSUE TITLE
Documentation for `_extend`

### ISSUE THREAD

**Issue by Anemy** [ethereum/web3.js#1182]
Introduced in PR https://github.com/ethereum/web3.js/pull/229

It's a pretty useful method and I only stumbled across it through a comment on a pr.
It may help people out to document it somewhere.

**Comment by frozeman** [comment]
Its described in the 1.0 here: http://web3js.readthedocs.io/en/1.0/web3.html#extend

And the old one has an example here:  https://github.com/ethereum/go-ethereum/blob/master/internal/web3ext/web3ext.go#L36-L63

**Comment by yxliang01** [comment]
@frozeman This documentation for `_extend` is now gone. Is there anything happened? Is it unavailable in the latest 1.0?

**Comment by ashish10677** [comment]
Even I can't find the extend function. Where is it now? Please help.

**Comment by yxliang01** [comment]
@ashish10677 Actually I found it. So, they are in process of changing the web3 1.0 structure. We now should create a "Web3Module" if we want to add new methods, the `extend` way is deprecated. See https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b .

**Comment by ghost** [comment]
@yxliang01 Hello, may I ask is there any source code for https://www.npmjs.com/package/web3-parity? Thanks.

**Comment by yxliang01** [comment]
@btenterprise2020 It's not yet available. But anyways, I don't think we should hi-jack this issue here. If you want to discuss something about it, maybe can have a chat at https://gitter.im/yxliang01/community . PM there is also fine.
