### ISSUE TITLE
Watching Events does not work when `fromBlock` and `toBlock` not defined 

### ISSUE THREAD

**Issue by philippphb** [ethereum/web3.js#1186]
When I create a reference to an Event in JS without specifying `fromBlock` and `toBlock`
```
var event = contract.Event();
```
the watch callback function
```
event.watch(function(error, result) {
if (!error) {
    //...
});
```
is never triggered. However, if I do specify the two parameters like 
```
var event = contract.Event({}, {fromBlock: startBlockNo, toBlock: 'latest'});
```
it works fine.

To my understanding, also the first definition should work and look at the complete block chain.

**Comment by Zvezdin** [comment]
Perhaps this is intentional? Using `{fromBlock: 0, toBlock: 'latest'}` is far more readable. Without it, web3 can't be sure what your intentions are. Should it watch for new blocks and ignore the old ones? Should it iterate over the whole chain and then stop? Should it iterate and continue watching in the future?

**Comment by MrTibbles** [comment]
Can you confirm what version of web3 you are using? 
As the syntax shown in your example appears to be the old implementation (!1.0). Even without that, it defaults to ['latest'](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter).

**Comment by philippphb** [comment]
You are correct, I'm using 0.19.0.

**Comment by MrTibbles** [comment]
Unless there is a reason for you not migrating to 1.0, i would recommend it.
Failing that, try inline chaining the event listener to see if that encourages it to behave:

`Contract.SomeEvent().watch((err, event) => console.info(event))`

**Comment by philippphb** [comment]
Should be ok migrating to 1.0, just didn't do it since it is still in beta. Alternatively I will try inline chaining.
Thanks for your support.

**Comment by MrTibbles** [comment]
Glad i could help.
