### ISSUE TITLE
Version 1 beta should NOT be default on the npm registry

### ISSUE THREAD

**Issue by bwheeler96** [ethereum/web3.js#1190]
The version 1.0.0 Beta is a great start, but at the moment it is horribly fragmented. The documentation is in many places lacking or erroneous (and the web3js.readthedocs.io page has many dead links).

I'm happy to help move the web3 project along to its 1.0.0 release in any way I can, but I also would like to voice the opinion that at the moment it is, in a word, painful to use. Web3.js 1.0.0 should NOT be installed by default from NPM, and the documentation for it should point more aggressively towards installing the functioning version.

**Comment by nivida** [comment]
@bwheeler96 Sorry that you didn't got a response for a long time. Because we are now "close" before the stable release I will let the 1.0 version be on NPM as it is right now. But yes I agree with you the 0.20 should have been on NPM as stable version :-)
