### ISSUE TITLE
No basic authentication functionality in web3-providers-http 1.0.0

### ISSUE THREAD

**Issue by Alex314Ru** [ethereum/web3.js#1192]
In Readme it said that we can [use HttpProvider with Basic Authentication](https://github.com/ethereum/web3.js#usage). I suppose that it works in web3.js 0.x, but in current version of [web3-providers-http](https://www.npmjs.com/package/web3-providers-http) (1.0.0-beta.26) `HttpProvider` constructor accepts only `host` and `timeout` parameters.

**Comment by ppohja** [comment]
```
let web3 = new Web3(
    new Web3.providers.HttpProvider(
      'http://' + username + ':' + password + '@'+ ip + ':' + port
    )
  )

```

.. works for me. 

Also, somewhere between beta.18 and beta.33, the constructor has gained also the headers parameter.
