### ISSUE TITLE
subscribe(“logs”) don't support address list?

### ISSUE THREAD

**Issue by netpi** [ethereum/web3.js#1195]
as web3.js document it support subscribe(“logs”) by address array 

![image](https://user-images.githubusercontent.com/8254020/33161548-3aec1442-d05f-11e7-95fc-d1f9ba295110.png)

```javascript 

// work well
web3.eth.subscribe('logs',{address:"address1"}).on('data',console.log)
// can't work
web3.eth.subscribe('logs',{address:["address1","address2"]}).on('data',console.log)
// also can't work
web3.eth.subscribe('logs',{address:"address1,address2"}).on('data',console.log)

```
![image](https://user-images.githubusercontent.com/8254020/33161467-a4aeebee-d05e-11e7-8d04-6fa47409601a.png)

**So how to listen to multiple addresses?**

**Comment by frozeman** [comment]
Good point. Actually it supports only one. Could you test the raw subscribe endpoint, whether it supports arrays as well? If so we can make that in 1.0 possible

**Comment by joojis** [comment]
The same problem here with the getPastLogs and the corresponding JSON-RPC doc is describing itself to support it.

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs
`Contract address or a list of addresses from which logs should originate.`

I hope that I could check the JSON-RPC actually supports it in the near future.

**Comment by mikemcdonald** [comment]
Is there a rough ETA on subscribe working with an array of addresses in 1.0? Trying to decide if I should rewrite a good amount of code back to 0.20 or wait until this is added.

**Comment by frozeman** [comment]
@mikemcdonald @joojis can you please test the latest 1.0 branch and see if you can receive logs from multiple addresses? Sorry for the delay!

**Comment by mikemcdonald** [comment]
Looks great, thanks again!

**Comment by swarupdonepudi** [comment]
@frozeman what version  of the npm package is this change available with?

**Comment by nivida** [comment]
@swarupdonepudi since 1.0.0-beta.28
