### ISSUE TITLE
web3 is undefined in server/lib/lib.js - Web3@1.0.0 -Meteor

### ISSUE THREAD

**Issue by ali5152** [ethereum/web3.js#1198]
I am creating a Dapp and new to all this stuff. Have developed a meteor application which talks with my chrome extension but now major issue is that web3@1.0.0 says that web3 is not defined. It works fine on the client side.

**Comment by ali5152** [comment]
@frozeman 
I saw this issue #381 as well but do not know where I am doing wrong. The web3 stable version 0.0.X works fine on client and server but I need to use personal.NewAccount function which is available in 1.0.0

**Comment by robertdavid010** [comment]
I was experiencing a similar problem recently, but in my case the web3 object was empty `{}` on the Meteor server. I'll leave this link here for anyone coming across this issue.

[SO: web3-empty-object-server-side-in-meteor](https://ethereum.stackexchange.com/questions/60335/web3-empty-object-server-side-in-meteor/60595#60595)

**Comment by nivida** [comment]
Does this still happen with the latest version of Web3?

**Comment by nivida** [comment]
Closed due to the inactivity of the creator of this issue.
