### ISSUE TITLE
web3-bzz has es6 depedencies which don't work with old nodejs versions

### ISSUE THREAD

**Issue by er3es** [ethereum/web3.js#1199]
My project uses an old version of nodejs. Thus some features of es6 don't work with even with the --harmony flag. When I import web3 in my project I get an error which has to do with some es6 depedencies of web3-bzz:

```
/node_modules/web3/node_modules/web3-bzz/node_modules/swarm-js/node_modules/fs-extra/lib/index.js:9 
Object.keys(gfs).forEach(key => {
                              ^
SyntaxError: Unexpected token > 
```

**Comment by frozeman** [comment]
we Will have a babel compiled version in the upcoming es6 version. This Es6 is in a dependency. I can only suggest adding your own transpileing steps.

**Comment by er3es** [comment]
Cheers
