### ISSUE TITLE
are docs wrong/outdated ?

### ISSUE THREAD

**Issue by wallaceturner** [ethereum/web3.js#1200]
Docs for simple things like balance and contracts seem wrong:
e.g. [docs for contracts][1]

```
var MyContract = web3.eth.contract(abiArray);

// instantiate by address
var contractInstance = MyContract.at(address);
```

when in fact this doesnt work and should be

`var MyContract = new web3.eth.Contract(abiArray, address);`

There are plenty more examples. even something like

`web3.fromWei`

is supposed to be

`web3.utils.fromWei`

[1]: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract

**Comment by MrTibbles** [comment]
If you are using master those docs are correct, if you are using 1.0 they are outdated and you should refer to [these](web3js.readthedocs.io/en/1.0/index.html)

**Comment by frozeman** [comment]
I added a note on top of the old docs. Thanks @MrTibbles for advising him.
