### ISSUE TITLE
[1.0] account management inconsistency

### ISSUE THREAD

**Issue by connectdotz** [ethereum/web3.js#1204]
Trying to use the new eth.accounts to manage the local wallet, noticed that in [Method.sendRequest](https://github.com/ethereum/web3.js/blob/17e1631bb4f93c6f670017739d2f2dfd18bfa26b/packages/web3-core-method/src/index.js#L503), it only routed 2 RPC to the accounts object: `eth_sendTransaction` and `eth_sign`, but not `eth_accounts` .... so potentially eth.getAccouts() and eth.accounts could return different results... is that by design or just a bug?

**Comment by connectdotz** [comment]
looks like this problem is bigger than I thought. Found related issue (#1154), looks like there are other RPC api not intercepted in sendRequest, such as the personal API...  I am now more convinced that this inconsistency is a serious issue if some API is getting account information from eth.accounts while others from RPC provider...

**Comment by connectdotz** [comment]
Based on the code and documents, I assume the following: if the local accounts (eth.accounts) are available, they should be used for all API consistently.

@frozeman I can address this issue but would like to know if my assumption aligns with your intended design, please advise...

**Comment by Stradivario** [comment]
So no one gives a shit about it right ? :D it is totally messy everything... the types are completely wrong methods that not exists...they..do..exist and i am like "debugger" everywhere to see what they put inside this object :D back to 2001 :D
