### ISSUE TITLE
(Question) How to get returned value when you call state changing function?

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#1207]
Lets say we have this contract:
```javascript
contract X {
  uint x;
  function set() public returns(uint someValue) {
    x = 2;
   someValue = x;
  }
}
```
how to read value `2` that should be returned after you make a call to `set()` from web3?

**Comment by MrTibbles** [comment]
Emit the value in an event:

```
contract X {
  uint x;
  event foo(uint indexed _x);
  function set() public returns(uint someValue) {
    x = 2;
   someValue = x;
   foo(x);
  }
}
```

Then subscribe to that [event from web3](http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events)

**Comment by rstormsf** [comment]
@MrTibbles thank you, we already doing that, just curious if it's possible receive returned values from solidity in javascript as well.

**Comment by nivida** [comment]
Please ask this on https://ethereum.stackexchange.com/
