### ISSUE TITLE
providers seems to be null

### ISSUE THREAD

**Issue by Andromelus** [ethereum/web3.js#1210]
I am trying to run connect to a remote node using a AWS lambda expression and serverless framework.

Every thing works on my local machine, but when uploaded to lambda, I get this error:
```

TypeError: Cannot read property 'HttpProvider' of undefined
    at getNode (/var/task/web3.js:62:43)
    at /var/task/web3.js:16:13
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/task/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/task/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
    at /var/task/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)
    at next (/var/task/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5)
```

Here is the code:

```
function getNode(callback) {
    console.log(Web3);
    var web3 = new Web3(new Web3.providers.HttpProvider('http://<IP>:<PORT>'));   <== Error
    console.log(web3);
....
```

I could not find anything similar anywhere, any idea?

**Comment by Shrugs** [comment]
Make sure that Web3 is being included in that environment. What's the output of `console.log(Web3)` on the first line of that function?

How does serverless handle node modules? does it bundle them into the lambda zip correctly? unarchive your uploaded zip file and confirm that the web3 module is in there?

**Comment by Andromelus** [comment]
- I unzipped it and all modules are here

- Web3 returns `{ handler: [Function] }`

- The problem **seems**  to be only with this module. When I use `XmlHttpRequest`, it works fine. Same for other modules.

**Comment by Shrugs** [comment]
On my local machine, `console.log(require('web3'))` outputs

```
> console.log(require('web3'))
{ [Function: Web3]
  providers:
   { HttpProvider: [Function: HttpProvider],
     IpcProvider: [Function: IpcProvider] } }
```

Therefore this is almost definitely a specific issue with the lambda environment or how severless packages your bundle. Perhaps it's worth looking into how the web3 package loads the `providers` property in the source code.

**Comment by Shrugs** [comment]
Actually, that `handler` property is weird; I don't see it on my own instance. Confirm you're importing the correct thing?

**Comment by Andromelus** [comment]
Yes I am. But I fucked up with all this shit for 2 days. Now I have the following issue: https://stackoverflow.com/questions/47693281/c-error-in-aws-lambda

I have no word to describe how I feel right now...

**Comment by Shrugs** [comment]
One route that _might_ work is to use a bundler like webpack or whatever to inline your modules and produce a single javascript file that is run by lambda.

**Comment by Robinhoodbharadwaj** [comment]
mein 3 din se chud rha hu

**Comment by nivida** [comment]
Looks like this a problem with your environment and does not directly depend on web3.js. Please drop a comment if not.
