### ISSUE TITLE
sendTransaction/sendSignedTransaction does not return tx hash on error

### ISSUE THREAD

**Issue by mxmauro** [ethereum/web3.js#1216]
Scenario: Create a transaction that calls a contract's method that throws an error.

The `sendTransaction/sendSignedTransaction` call, internally ends in a call to provider's `send/sendAsync`. The result object in the callback contains the error message, like "VM exception.... revert" but the code builds an `ErrorResponse` object with only the message.

Although transaction hash is returned in `result.result`, it is discarded.

**Comment by gavrilyak** [comment]
Same problem here. I need transaction hash from sendTransaction but is seems the only way to get it is monkeypatching RequestManager.prototype.send like this
 ```      
      if (!Jsonrpc.isValidResponse(result)) {
        return callback(errors.InvalidResponse(result));
      }

      if ('result' in result) {
        return callback(null, result.result);
      }

      if (result && result.error) {
        return callback(errors.ErrorResponse(result));
      }
 ```

It works, but monkeypatching is ugly and uses undocumented internals. It would be nice to have more straitforward way to get transaction hash from sendTransaction call.

**Comment by nivida** [comment]
You are able to get the transaction hash if you use the EventEmitter API instead of the Promise API from the PromiEvent we provide. Be aware that you can't combine the EventEmitter and the Promise.

``` javascript 

web3.eth.sendTransaction(...).on('transactionHash', console.log).on('receipt', console.log)
```
