### ISSUE TITLE
web3.js always returns invalid JSON RPC response

### ISSUE THREAD

**Issue by Moejoe90** [ethereum/web3.js#1218]
I am talking about latest stable release web3 0.19.0

Web3 always emits `invalid JSON RPC response`, and this makes it almost impossible to recognize if the connection loss happened during initial connection with node or midway while response or a real wrong response from the node. 

This shouldn't be the case for sure as I can see in [errors.js](https://github.com/ethereum/web3.js/blob/develop/lib/web3/errors.js) a node connection error and it is utilized in the [httpprovider](https://github.com/ethereum/web3.js/blob/develop/lib/web3/httpprovider.js)

Additionally 

While being to be able to initialize `new web3()` and wrap it around different providers easily is a good idea, it makes it almost impossible to recognize if the connection loss happened during initialization or midway. 

Now i now can use `web3.isConnected()` during initialization and emit a specific error but why not provide a strict mode for example where I would wrap web3 around a specific provider and expect the connection to be there. Maybe there is a way to do this already?

**Comment by Freyert** [comment]
This is always, always? Or just a lot of the time?

I'm seeing: `Invalid JSON RPC response: ""`

**Comment by edyrkaj** [comment]
Hi,

Can we have any solution about this issue? Still happening on version: `web3@1.0.0-beta.34`
Thnx

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
