### ISSUE TITLE
Uncaught ReferenceError: Web3 is not defined

### ISSUE THREAD

**Issue by Alex-Gorbach** [ethereum/web3.js#1233]
Hello! I'm trying to create an instance of web3 using the following code in the index.js file:
 `var web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));`
But have an error:
![screenshot 4](https://user-images.githubusercontent.com/14149328/34022217-02c730dc-e14f-11e7-86bc-7b70e352ee3b.png)
I have installed Web3 and started the testrpc.
When I execute this code in the node.js terminal , there are no errors.
Why is this happening? Thanks.

**Comment by nisdas** [comment]
Most likely you did not import the web3 library using this : ` var Web3 = require("web3") `
Do that and you should be fine

**Comment by Alex-Gorbach** [comment]
`var Web3 = require("web3")` also produced an error: "Uncaught ReferenceError: require is not defined".
I solved this problem using the following construction from [here:](https://github.com/ethereum/wiki/wiki/JavaScript-API#adding-web3)
`
            if (typeof web3 !== 'undefined') {
                web3 = new Web3(web3.currentProvider);
            } else {
                // set the provider you want from Web3.providers
                web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
            }`
Thanks.

**Comment by ddb1** [comment]
i have also meet this problem ,who can tell me how to solve it. thanks!
