### ISSUE TITLE
Dependency Error while installing Web3.js

### ISSUE THREAD

**Issue by alexvcasillas** [ethereum/web3.js#1240]
Good afternoon,
I'm trying to make an implementation of Web3 to connect to my external Quorum Blockchain but I can't manage to install this library while I'm still getting this error every time I try to execute the following command: `npm install --save web3`

```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Expiró el tiempo de conexión
npm ERR! github.com[1: 192.30.253.113]: errno=Expiró el tiempo de conexión
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2017-12-20T13_10_02_657Z-debug.log
```

**Environment Details**
OS: Ubuntu 16.04
Node Version: v9.2.1
NPM Version: v5.6.0

**More Details**
It got stucked always with the `/ fetchMetadata: sill resolveNewModule http-https@1.0.`, stays there forever untill it got a timeout then not move forwards.

Thanks for your support.
Regards,
Alex.

**Comment by balinskia** [comment]
Sometimes I also have such problem that in random places npm is being stuck. I solved it by switching to `yarn` :)

**Comment by alexvcasillas** [comment]
It works with yarn? Really, @balinskia ?
(╯°□°）╯︵ ┻━┻

**Comment by alexvcasillas** [comment]
Still not working for me with `yarn`

**Comment by alexvcasillas** [comment]
Suddendly started working ... Sorry for the annoying issue, i'm gonna close this ...

**Comment by leehankyeol** [comment]
This somehow happens sometimes. https://github.com/ethereum/web3.js/issues/1211

**Comment by izotx** [comment]
For me it was a firewall issue.
