### ISSUE TITLE
handling tuples (structs)

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/web3.js#1241]
in solidity verion 0.4.19 tuples are supported, which allow structs as input-params. The current encoder in `web3-eth-abi` does not support them yet.
a definition of them can be found here: http://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=tuple#handling-tuple-types

example:

```json
[
  {
    "name": "f",
    "type": "function",
    "inputs": [
      {
        "name": "s",
        "type": "tuple",
        "components": [
          {
            "name": "a",
            "type": "uint256"
          },
          {
            "name": "b",
            "type": "uint256[]"
          },
          {
            "name": "c",
            "type": "tuple[]",
            "components": [
              {
                "name": "x",
                "type": "uint256"
              },
              {
                "name": "y",
                "type": "uint256"
              }
            ]
          }
        ]
      },
      {
        "name": "t",
        "type": "tuple",
        "components": [
          {
            "name": "x",
            "type": "uint256"
          },
          {
            "name": "y",
            "type": "uint256"
          }
        ]
      },
      {
        "name": "a",
        "type": "uint256"
      }
    ],
    "outputs": []
  }
]
```

**Comment by frozeman** [comment]
We should definitely support that. I started looking into this. Any help would be welcome.

**Comment by splut** [comment]
Any updates on this? Thanks.

**Comment by Remi-Burgel** [comment]
Will it be available for solidity view function too ?

**Comment by OlyRice** [comment]
This will be a great feature, it will let me focus more of the filtering on the frontend instead of within the contract. Also should reduce the number of calls to the contract.

**Comment by realseanp** [comment]
Any updates?

**Comment by pnicorelli** [comment]
+1

**Comment by splut** [comment]
@OlyRice ethers.js have this working now https://github.com/ethers-io/ethers.js/issues/84

**Comment by gassogba** [comment]
+1

**Comment by Pczek** [comment]
+1

**Comment by TomaszWaszczyk** [comment]
++;

03.02.2018 7:10 PM "Phil" <notifications@github.com> napisał(a):

**Comment by Rainbow-Unicorn-Oo** [comment]
+= 1;

**Comment by saniales** [comment]
+1

**Comment by willnwhite** [comment]
I've encountered this issue now using Truffle. I looked at the link with the definition, but it looks like a lot of work. Could ethers.js and web3 share the same code?

**Comment by vascomedici** [comment]
+1

**Comment by partyka1** [comment]
+1

**Comment by frozeman** [comment]
Im on this in the #newAbiLib branch, but wont be able to finish the next two weeks, as im on holidays.

**Comment by svendeckers** [comment]
Just ran into the same thing, wanting to pass a struct as a constructor argument with contract.new(constructorArg, {data:...});

**Comment by NoChance777** [comment]
I've joined to waiting

**Comment by victorrseloy** [comment]
+1

**Comment by multigcs** [comment]
+1

**Comment by PaulFasola** [comment]
+1

**Comment by frostini** [comment]
bandwagon +1 :(

**Comment by rainbowcreatures** [comment]
+1

**Comment by gogolevdms** [comment]
+1

**Comment by SirElTomato** [comment]
+1

**Comment by hadv** [comment]
+1

**Comment by Taces** [comment]
+1

**Comment by Pipeliner** [comment]
Any news on this one?

**Comment by frozeman** [comment]
Im
Traveling this week and waiting for https://github.com/ethers-io/ethers.js/issues/163
If you push there Rico might get it faster done :)

**Comment by belyak** [comment]
+1

**Comment by Astrovicis** [comment]
+1

**Comment by Amxx** [comment]
+1

**Comment by wickstjo** [comment]
+1

**Comment by kmeraz** [comment]
+1

**Comment by frozeman** [comment]
We've worked on adding ether-js ABI decode to support tuples. Could you guys please test the https://github.com/ethereum/web3.js/tree/newAbiLib branch and see if it works for you guys?
It would be great if the community could provide test cases for tuples (ins and out puts of the EVM), so we can test that i en/decodes properly.
Current tests can be found here: https://github.com/ethereum/web3.js/blob/newAbiLib/test/abi.decodeParameter.js
And for components it would expect the outputs or inputs of the json interface, as follows:

```
web3.eth.abi.decodeParameters(jsonInterface.outputs, bytes) > Results {....}

web3.eth.abi.encodeParameters(jsonInterface.inputs, parameters) > 0x12345.....
```

**Comment by gakonst** [comment]
+1

**Comment by MoMannn** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by MoMannn** [comment]
@frozeman  I have been trying this: https://github.com/ethereum/web3.js/tree/newAbiLib if it works with tuple but I always get invalid solidity type error. Has this been programmed? 

Maybe I'm doing something wrong are there any instructions for this?

**Comment by Amxx** [comment]
@frozeman I had a look at the newAbiLib branch, and run the test locally to make sure I was loading the right version of web3-eth-abi, yet I fail to see how to use it.

Making a call to a contract with outputs a struct fails (`Error: invalid solidity type!: tuple`) and I don't know how to get the raw output to decode it.

I also tried to encode a function call, but when the function fails if one of the input has `type: 'tuple'` :/

**Comment by xpepermint** [comment]
@frozeman Would you be so kind and publish the `newAbiLib` branch to `npm`? It seems that `lerna` causes problems on some platforms thus adding `git+http` path as a dependency is not always possible. You also need to have additional packages installed globally. Puting this to `npm` (e.g. `web3-newabilib`) would really help!

**Comment by mehtamanan** [comment]
@frozeman I couldn't get it work. I deployed the following contract locally and tried to call foo but it error'd out:

```
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;

contract Test {

    struct Bar {
        uint a;
        uint b;
    }

    Bar public z;
    string public y;

    function foo(string s, Bar b) public {
        y = s;
    }

}
```

When I did `contract.methods.foo("hello", { a: 1, b: 2 }).send().then(d => console.log(d)).catch(d => console.log(d))`, it gave me the following error:

```
Error: invalid number value (arg=undefined, type="undefined", value=undefined)
    at Object.throwError (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/errors.js:74:17)
    at Object.encode (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:68:24)
    at /Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:340:59
    at Array.forEach (<anonymous>)
    at pack (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:339:12)
    at Object.encode (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:521:20)
    at /Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:340:59
    at Array.forEach (<anonymous>)
    at pack (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:339:12)
    at Object.encode (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:521:20)
    at Coder.encode (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:661:62)
    at ABICoder.encodeParameters (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-abi/src/index.js:103:27)
    at /Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-contract/src/index.js:421:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-contract/src/index.js:420:12)
    at Object._processExecuteArguments (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-contract/src/index.js:736:39)
    at Object._executeMethod (/Users/mananmehta/Desktop/bar/node_modules/web3/packages/web3-eth-contract/src/index.js:761:54)
```

**Comment by mehtamanan** [comment]
@MoMannn So the order of the arguments in the tuple should match the order in which the struct parameters are declared?

**Comment by xpepermint** [comment]
@mehtamanan [this](https://github.com/chainspin/monorepo/blob/cb11653eb8ada8f0f97bbedf837039a70bd285f2/packages/chainspin-utils/src/web3.ts#L5) method should help you transform objects to tuples. You can check tests [here](https://github.com/chainspin/monorepo/blob/cb11653eb8ada8f0f97bbedf837039a70bd285f2/packages/chainspin-utils/src/tests/web3.test.ts#L6) to se how you should use it.

**Comment by mehtamanan** [comment]
@xpepermint Right on!

**Comment by Amxx** [comment]
@mehtamanan I might sound stupid but how do you npm install ethereum/web3.js#newAbiLib ?
Also, my contract (obtained by `artifacts.require(path);`) does not contain any `.methods.xxx` objects ...

**Comment by xpepermint** [comment]
@Amxx In nodejs you include a GIT dependency as 
```
"web3": "git+https://github.com/ethereum/web3.js.git#newAbiLib"
```
Based on `artifacts.require` I assume you are using `truffle`. You'll have to fork the truffle project to achieve that.

**Comment by mehtamanan** [comment]
Hey guys, any ideas when this will be resolved and released? :)

**Comment by xblue55** [comment]
+1

**Comment by droconnel22** [comment]
+1

**Comment by mrwillis** [comment]
+1

**Comment by gjgd** [comment]
+1

**Comment by thebrunchguy** [comment]
+1

**Comment by clockknock** [comment]
+1

**Comment by AnthonyAkentiev** [comment]
+1

**Comment by 0x-r4bbit** [comment]
Friendly reminder: since 2 years, we can use GitHub Reactions to express how we feel about something 🙂

https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/

**Comment by nivida** [comment]
The new ABICoder implementation is merged and this issue will be solved in the next release.

**Comment by maroodb** [comment]
Any updates?

**Comment by Remi-Burgel** [comment]
Hi, anything new ? When I'm here, it looks like the problem should be solved, but I still have the same message when I call a method that return a tuple array.

**Comment by gked** [comment]
Any updates on this?
Can you suggest a workaround?

**Comment by adityachap** [comment]
Faced the same isuue while trying to call a solidity function which returns dynamic array of structures , used the latest version of web3 which supports "pragma experimental ABIEncoderV2" of solidity

**Comment by nivida** [comment]
Could you please open an issue in the ethers.js repository? We use the ABICoder from there currently and just pass the data in. :-) @adityachap @gked 

I'll update the ethers.js lib to the latest version on the next release. Maybe this will already solve it.

**Comment by PhABC** [comment]
Ethers.js indeed already has a [coder](https://github.com/ethers-io/ethers.js/blob/36172f7f7ba1d2043d6e331c76cfb4c52d425ba7/src.ts/utils/abi-coder.ts#L900) for tuples.

**Comment by aakilfernandes** [comment]
@nivida I'm confused. is this fixed in web3 or ethers.js? Is ethers.js a dependency of web3? I'm a little confused at how these projects interact

**Comment by aakilfernandes** [comment]
@nivida 

> The new ABICoder implementation is merged and this issue will be solved in the next release.

Which release was this? I'm using 0.18.4 but still having a problem

**Comment by araa47** [comment]
I am still running into issues while trying to generate java contract wrappers. I get the following error ```Unsupported type encountered: tuple``` , any update on progress of this? Or is there any branch i can switch to that has this working?

**Comment by timsankara** [comment]
@araa47 did you happen to find a solution to this issue?

**Comment by araa47** [comment]
@chimpyTheDev can't remember correctly, but If I am not wrong I ended up using https://github.com/esaulpaugh/headlong

**Comment by timsankara** [comment]
@araa47 I'll check it out, Thanks.

I see in many comments that web3 1.0 supports the solution to:
 `Uncaught (in promise) Error: invalid solidity type!: tuple[]`
 However I can't seem to find any documentation or implementation of the same, any lead anyone?
