### ISSUE TITLE
no value retuned for transaction?

### ISSUE THREAD

**Issue by makc** [ethereum/web3.js#1246]
I am running parity and then this code
```javascript
var Web3 = require ('web3');

var web3 = new Web3 (new Web3.providers.HttpProvider ("http://localhost:8545"));

// https://etherscan.io/tx/0xfb8e4e5e112890ef60d279a047bf49923dd39f34efcc00d5c84272a7279fa584

web3.eth.getTransaction ("0xfb8e4e5e112890ef60d279a047bf49923dd39f34efcc00d5c84272a7279fa584", function () {
	console.log (arguments);
});
```
in node.js; the output is:
> { '0': null, '1': null }

why?

also tried this code:
```javascript
web3.eth.getTransaction ("0xfb8e4e5e112890ef60d279a047bf49923dd39f34efcc00d5c84272a7279fa584").then (function (what) {
	console.log (what);
});
```
the result was
> null

**Comment by eepstein** [comment]
From the code it looks like you were a) connecting to a local testrpc instance and b) (from the comment in) looking to find a transaction that was visible on the mainnet via etherscan.

The result you got - a null - is correct.  There is no such transaction on your local testrpc.

This is not a bug.

If you want to use web3js to lookup live transactions on the mainnet, then you need to connect to a web3 provider on the mainnet.  You have options for that from running your own parity or geth node to using Infura or similar, to using MetaMask if this is in a browser.

**Comment by eepstein** [comment]
This appears to be user error and not a bug.  If so, it might be best to mark this issue resolved, close it, and continue the discussion on gitter.

**Comment by makc** [comment]
okay, thanks.
