### ISSUE TITLE
Error accessing accounts

### ISSUE THREAD

**Issue by ToJen** [ethereum/web3.js#1247]
**Versions**
Node: v9.3.0
npm: 5.6.0
web3@1.0.0-beta.27

**Problem**
I'm following the [Voting dApp tutorial](https://medium.com/@mvmurthy/full-stack-hello-world-voting-ethereum-dapp-tutorial-part-1-40d2d0d807c2) which is *pre* web3v1.0.

I'm unable to get any accounts from web3. I have `testrpc` running on a separate terminal. In the current terminal, I opened node and created the `Web3` and `web3` variables correctly. When I run `web3.eth.accounts[0]`, I get back `undefined`. Yes I can see the 10 testrpc accounts when I run `web3.eth.getAccounts().then(console.log)` but I would like to have the account set automatically.

This also seems to affect any contract I create as `myContract.options.address` always returns `null`.

Any idea what's wrong?

**Comment by ToJen** [comment]
@frozeman it seems like v1.0 has an issue with returning addresses

**Comment by mjhm** [comment]
@ToJen Here's my port of that tutorial to web3 1.0.0-beta.27 https://github.com/mjhm/hello_world_dapp

**Comment by eumend** [comment]
I'm doing migrations with 1.0.0-beta.27 and web3.eth.accounts[0] gives me undefined, had to use .getAccounts()
