### ISSUE TITLE
is there a release process? what's the current version ?

### ISSUE THREAD

**Issue by eepstein** [ethereum/web3.js#1250]
I'm trying to sort through the releases and the release process and each location references a different version.

1) npm site references:  1.0.0.beta.27  https://www.npmjs.com/package/web3 
That references https://github.com/ethereum/web3.js/tree/master/packages/web3,  but that page doesn't exist and gives a 404.

2) https://github.com/ethereum/web3.js/releases  lists 1.0.0-beta.18 as the most recent release.
(by contrast https://github.com/ethereum/web3.js/releases/tag/1.0.0-beta.27 gives a 404)

3) The Readme.md in the github repo reference migrating to v 0.14.0  

4) Looking in the dist folder on github doesn't offer much clue as to the current version #.

So, I'm not sure what the latest version is.  It's not clear to me what the release process is and how one finds the current package in a way that is consistent across npm and github. 

Is there a secret decoder ring?

**Comment by mjhm** [comment]
FWIW the `1.0` branch seems to be the current release branch https://github.com/ethereum/web3.js/blob/1.0/lerna.json#L2  This will probably become clearer when 1.0 gets out of beta.

**Comment by eepstein** [comment]
releases are made from a branch, but are they branch-specific?  isn't a release for the whole project?

https://github.com/ethereum/web3.js/releases seems to be the same page for all branches and lists beta.18, but npm has beta.27 - but the links from npm to the project don't work.

Can @frozeman or someone on the project shed a little light?
Thanks!

**Comment by eepstein** [comment]
Trying to use the latest 1.0 beta.27 release doens't seem to work with Typescript modules:

    import { default as Web3 } from 'web3';

gives: web3/index resolves to a non-module entity...

**Comment by helxsz** [comment]
@eepstein I am currently upgrading to latest 1.0 beta.27, import { default as Web3 } from 'web3'; doesn't work as you said. 

**/node_modules/web3/index"' resolves to a non-module entity and cannot be imported using this construct.**

what do you mean by 
**gives: web3/index resolves to a non-module entity...**

**Comment by eepstein** [comment]
AFAICT it means that the 1.0 beta releases of web3.js aren't packaged in a typescript-friendly way.

My work-around has been to fall-back to generic, untyped JavaScript via this import construct:

    const Web3 = require('web3');

The downside is this loses 'Web3' as a type, and hence all the IDE support is lost too.  But, so far, it does work.

You may need to also tell the TypeScript system to support this by adding something like:

      "types": [
          // add node as an option
          "node"
      ]

to your ts config file.
