### ISSUE TITLE
[1.0] sendTransaction not timing out as expected

### ISSUE THREAD

**Issue by connectdotz** [ethereum/web3.js#1252]
used web3.js 1.0.0-beta.26 with Parity 1.8.4. 

Sent a not-signable transaction via websocket provider interface, expecting it to time out after x blocks read, but didn't happen... 

parity showed it received the request, but never responded, and web3 never timeout...

After digging further realized the `startWatching` is only invoked in `_confirmTransaction`, which only called after the provider responded the initial sendTransaction(), which parity never did... While there might be a parity problem that it should have responded something, nevertheless, web3 should be able to act properly by timing out after x blocks as `startWatching` intended... 

Can `startWatching` start prior to provider's initial response?

**Comment by nivida** [comment]
This should be fixed within the next release. (PR #2000)

**Comment by nivida** [comment]
This got fixed with the latest release.
