### ISSUE TITLE
Getting contract balance at a particular block number 

### ISSUE THREAD

**Issue by darxtrix** [ethereum/web3.js#1262]
Hi, just like we can view ether balance at an address at a particular block number by passing `defaultBlock` value in `web3.eth.getBalance(address [, defaultBlock] [, callback])`

Is there a way to read ERC20 balance at a particular block corresponding to an address using `balanceOf` method of the contract ?

**Comment by dannystox** [comment]
Hi,
Try the following call:
`myERC20Contract.methods.balanceOf(accountAddress).call(transactionObject, blockNumber, callback)`

The second parameter in the call function is the block number.
You can leave the transactionObject `undefined`

**Comment by omar-saadoun** [comment]
The error remains? Any update?

**Comment by catalsdevelop** [comment]
@darxtrix,  dannystox's solution worked, but pay attention that it must be full sync mod.

**Comment by nivida** [comment]
Please ask further questions on https://ethereum.stackexchange.com/
