### ISSUE TITLE
Opportunity to allow use of Promises with Subscriptions instead of just Callbacks

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/web3.js#1265]
# INFO
**Which Web3.js version?**: 1.0.0-beta.27
**Which operating system?**: MacOS
**How installed?**: NPM

# **actual behaviour, expected behaviour, and steps to reproduce**

I’m using Web3.js v1.0.0-beta.27.
When I follow the documentation and pass a Callback as the second argument of a subscription it works successfully by creating a subscription

```
// Subscriptions - http://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#
let subscriptionToPendingTransactions = web3.eth.subscribe('pendingTransactions', 
  (error, transaction) => {
    if (!error) {
      console.log(`Subscription - Pending Transaction: `, transaction);
    } else {
      console.log(`Error - Subscription - Pending Transaction: `, error);
    }
  })
  .on("data", function(transaction) {
    console.log(`Subscription - Pending Transaction Data: `, transaction);
  });
```

But if instead I try to use a Promise instead with `.then`, it gives me error `Unhandled rejection TypeError: web3.eth.subscribe(...).then is not a function`

```
let subscriptionToLogs = web3.eth.subscribe('logs', {
    address: senderAddress,
    topics: [null]
  })
  .then((log) => { 
    console.log(`Subscription - Log: `, log); 
  })
  .catch((error) => {
    console.log(`Error - Subscription - Log: `, error);
  })
  .on("data", function(log) {
    console.log(`Subscription - Log Data: `, log);
  })
  .on("changed", function(log) {
    console.log(`Subscription - Log Changed: `, log);
  });
```

And when I use Promises with Events:

```
newContractInstance.once('Created', {
    fromBlock: 0
  })
  .then(function(event){
    console.log(`Once event received event: `, event); 
  }).catch((error) => {
    console.log(`Error - Once event: `, error);
  });
```

It gives error: `Unhandled rejection Error: Once requires a callback as the second parameter.`

But it works with Callbacks, as required by the docs
```
newContractInstance.once('Created', {
    fromBlock: 0
  },
  (error, createdEvent) => {
    if (!error) {
      console.log(`Once event received event: `, createdEvent); 
    } else {
      console.log(`Error - Once event: `, error);
    }
  });
```

Is it desired functionality to be able to use Promises with the Subscriptions and Events?

**Comment by quantumproducer** [comment]
Agree. Oddly I found online guides describing how to use promises with Web3 and was disappointed to find out that API didn't work.

**Comment by nivida** [comment]
We will implement subscriptions with RxJs in 2.0 and all other async processes are handled with the native Promise.
