### ISSUE TITLE
Having a really hard time understanding contracts' API

### ISSUE THREAD

**Issue by jjant** [ethereum/web3.js#1269]
I went through the docs, and now I'm reading the code because I'm incredibly confused on how contract methods are supposed to be called, for example:

```js
const Contract = window.web3.eth.contract(abi);
const contractInstance = Contract.at(contractAddress);

// index is a public field of my contract
contractInstance.index(console.log) // { s: 0, e: 1, c: [5] } what? Where's this object coming from?

// sequence is a public array field in my contract 
contractInstance.sequence(console.log) // SolidityError: Wrong number of params

// Turns out I have to call it like
contractInstance.sequence(index, console.log)
```

Now, I **really** dislike this api (why not just get the whole array instead of having to get one element at a time?). But that's not the point of this issue, it's **documentation**.

This might be there somewhere (I really tried finding this), but I think this could be more explicit/visible on the docs.

**Comment by quantumproducer** [comment]
+1.

**Comment by Andromelus** [comment]
The doc is not bad actually. Public variables are called with implicit getter "generated" when contract is deployed. So if you want to call a public int called "myInt", you do:
`contractInstance.methods.myInt().call`

If you want to check a specific element of a mapping public mapping

`contractInstance.methods.myMapping(key).call()`

**Comment by nivida** [comment]
@Andromelus Thank you very much for answering that.
