### ISSUE TITLE
Bower still points to cubedbro/ethereum.js.

### ISSUE THREAD

**Issue by simondlr** [ethereum/web3.js#127]
Hi. Not sure if this is intentional, but I wanted to use the recent new tags (thanks for that) in my bower packages, but the current setup points to cubedbro's repo of Ethereum.js (where the 0.1.0 tag is not installed). Is the intent to keep the bower reference to that repo or to change it to this one (which seems like it should be the correct one).

**Comment by cubedro** [comment]
I added an [issue](https://github.com/bower/bower/issues/120#issuecomment-86980876) on bower registry to change the repo name. The other only option is to remove the package from the bower registry and re-add it.

**Comment by debris** [comment]
wow... that's a huge issue! Hopes it will re resolved soon ;)

**Comment by debris** [comment]
new bower package is [web3](http://bower.io/search/?q=web3). Closing
