### ISSUE TITLE
Return JSON Object with key:value pairs for mutli return contract calls

### ISSUE THREAD

**Issue by robertsimoes** [ethereum/web3.js#1270]
Consider:
```
// SalaryInfo.sol
contract SalaryInfo {
    struct User {
        uint salaryId;
        string name;
    }
    User[] public users;

    function getUser(uint index) public constant returns(uint id, string name) {
        return (
           users[index].salaryId, 
           users[index].name);
    }
}
```

Returns: 

```
> salaryInfo.getUser(0)
[123, "User 123"]
```

Would be nice if when making a function call instead of returning an array with indices as seen above, it returns key:value pairs for the properties with the _value_ of the `name` key found in the contract abi in the outputs section of a given function.

For example: 
```
// ..abi
 {
  "constant": true,
      "inputs": [],"name": "getUser",
      "outputs": [
        {
          "name": ***"id"***,
          "type": "uint"
        },
        {
          "name": ***"name"***,
          "type": "string"
        }
  ]
}
```
Would return instead as:

```
> salaryInfo.getUser(0)
{"id":123, "name":"User123"}
```

**Comment by niroj08** [comment]
Any status on this issue??

**Comment by nivida** [comment]
@niroj08 I can recommend you to change to the 1.0 version of web3. Currently it's not clear which patches we will be releasing for the 0.20 version.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
