### ISSUE TITLE
Is there any guide for migration from 0.2x to 1.0.0 beta?

### ISSUE THREAD

**Issue by mobilesite** [ethereum/web3.js#1271]
Excuse me! Is there any guide for migration from 0.2x to 1.0.0 beta? Can I use the beta version in production now?

**Comment by mjhm** [comment]
It's probably too soon to use web3@1.X in production yet. A key holdup for most people would be an update to MetaMask to be Web3 1.X compatible https://github.com/MetaMask/metamask-extension/issues/2350

**Comment by Alexintosh** [comment]
Would be nice to reconsider this idea

**Comment by nivida** [comment]
Great Idea! 
Feel free to submit an PR @mobilesite

**Comment by nivida** [comment]
I'm closing this issue because of the newly created issue from @ChrisChinchilla.
