### ISSUE TITLE
receipt no longer return outOfGas when the transaction runs out of gas

### ISSUE THREAD

**Issue by 7Ds7** [ethereum/web3.js#1272]
On the current 1.0.0-beta.27
LN 21241 dist/web3.js
https://github.com/ethereum/web3.js/blob/develop/dist/web3.js
there is a check to see if the transaction ran out of gas
```
 // CHECK for normal tx check for receipt only
.then(function (receipt) {

  if (!isContractDeployment && !promiseResolved) {

    if (!receipt.outOfGas && (!gasProvided || gasProvided !== receipt.gasUsed)) {
      defer.eventEmitter.emit('receipt', receipt);
      defer.resolve(receipt);

      // need to remove listeners, as they aren't removed automatically when succesfull
      if (canUnsubscribe) {
        defer.eventEmitter.removeAllListeners();
      }
    } else {
      if (receipt) {
        receipt = JSON.stringify(receipt, null, 2);
      }
      utils._fireError(new Error("Transaction ran out of gas. Please provide more gas:\n" + receipt), defer.eventEmitter, defer.reject);
    }

    if (canUnsubscribe) {
      sub.unsubscribe();
    }
    promiseResolved = true;
  }
```

I no longer get the outOfGas in the receipt when such occurs, i get it as a successful transaction, although i have the feeling i had it before.
Using Metamask as current provider, does this happens to anyone else or it might be something with my setup?

**Comment by 7Ds7** [comment]
Am i the only one affected by this?
If so the issue can be closed

**Comment by quantumproducer** [comment]
Hi, can you verify this by trying a gas-expensive request and be sure it runs out with no out of gas error?

**Comment by 7Ds7** [comment]
OK so assuming this transaction which fails out of gas on purpose
https://ropsten.etherscan.io/tx/0xbd2ce77728267043f2b100fc43cb00c48c2edb6931ab644c8241a92094372395

I got this object
```
{
  "blockHash": "0xa14a961a18b7296ca5bfa6b5376f210378341701bac8b7b347a63406ca2cef31",
  "blockNumber": 2473533,
  "contractAddress": null,
  "cumulativeGasUsed": 118888,
  "from": "0x4c899fcf15cb84224bcde138c9f6fbc3a3e9990b",
  "gasUsed": 35619,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": "0x0",
  "to": "0xbcabb686fe320532f552e020de9ad0a3b7188066",
  "transactionHash": "0xbd2ce77728267043f2b100fc43cb00c48c2edb6931ab644c8241a92094372395",
  "transactionIndex": 3,
  "events": {}
}
```

Not on error but on both on promise resolve, confirmation as well as receipt.
I see the status as 0x0 which for successful transactions is 0x1, and that is what i am using at the moment to workaround the error for out of gas being triggered.

But it used to fire` .on('erroe') ` or `on('receipt') `when a transaction ran out of gas, shouldn't it still do that?
