### ISSUE TITLE
Installation issue on windows

### ISSUE THREAD

**Issue by jorgeog96** [ethereum/web3.js#1273]
SO: windows7
node version: v8.9.4
npm version: 5.6.0.
git: 2.15.1.windows.2

Give me a configure error
can't find python executable "python"

So, I can't install web3 in my device
  
You can see part of the log (because it's so long) here:
...
...
7803 silly saveTree   | | | `-- randomfill@1.0.3
7803 silly saveTree   | | +-- eth-lib@0.2.5
7803 silly saveTree   | | +-- scrypt.js@0.2.0
7803 silly saveTree   | | | +-- scrypt@6.0.3
7803 silly saveTree   | | | `-- scryptsy@1.2.1
7803 silly saveTree   | | `-- uuid@2.0.1
7803 silly saveTree   | `-- web3-eth-contract@1.0.0-beta.27
7803 silly saveTree   +-- web3-net@1.0.0-beta.27
7803 silly saveTree   +-- web3-shh@1.0.0-beta.27
7803 silly saveTree   `-- web3-utils@1.0.0-beta.27
7804 warn enoent ENOENT: no such file or directory, open 'C:\Windows\Dell\package.json'
7805 verbose enoent This is related to npm not being able to find a file.
7806 warn Dell No description
7807 warn Dell No repository field.
7808 warn Dell No README data
7809 warn Dell No license field.
7810 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
7810 verbose stack Exit status 1
7810 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
7810 verbose stack     at emitTwo (events.js:126:13)
7810 verbose stack     at EventEmitter.emit (events.js:214:7)
7810 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
7810 verbose stack     at emitTwo (events.js:126:13)
7810 verbose stack     at ChildProcess.emit (events.js:214:7)
7810 verbose stack     at maybeClose (internal/child_process.js:925:16)
7810 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
7811 verbose pkgid scrypt@6.0.3
7812 verbose cwd C:\Windows\Dell
7813 verbose Windows_NT 6.1.7601
7814 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
7815 verbose node v8.9.4
7816 verbose npm  v5.6.0
7817 error code ELIFECYCLE
7818 error errno 1
7819 error scrypt@6.0.3 install: `node-gyp rebuild`
7819 error Exit status 1
7820 error Failed at the scrypt@6.0.3 install script.
7820 error This is probably not a problem with npm. There is likely additional logging output above.
7821 verbose exit [ 1, true ]

**Comment by lzl124631x** [comment]
Try this https://github.com/felixrieseberg/windows-build-tools/issues/56#issuecomment-308739624 ?

npm --add-python-to-path='true' --debug install --global windows-build-tools

Run it in powershell as administrator

**Comment by ChinhPLQ** [comment]
after doing above command, somehow I also need to run below one to set python config again
npm config set python "[My Python path] \python.exe" 
I found my python path in PATH Environment Variable
