### ISSUE TITLE
"Returned error: unknown account" after upgrading from 1.0.0-beta.26 to 1.0.0-beta.27

### ISSUE THREAD

**Issue by starspire** [ethereum/web3.js#1274]
Hello,
After web3js package update from 1.0.0-beta.26 to 1.0.0-beta.27 I faced following issue. Anytime I execute state changing contract method (like this):
```
exampleToken.methods
	.mint(toAddress, tokenNumber)
	.send({from: web3.eth.defaultAccount, gas: 100000});
```

I get an error: 
```
Unhandled rejection Error: Returned error: unknown account
    at Object.ErrorResponse (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/web3-providers-http/src/index.js:66:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/krzysztof/Documents/work/projects/Level01/level01_ethereum_backend_integration/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

I dived deeper and checked how it is transformed behind to json-rpc:

Request:
```
{"jsonrpc":"2.0","id":2,"method":"eth_sendTransaction","params":[{"from":"0x1781bd8bb7c48de5c77650bf0795328ba41dc46e","gas":"0x186a0","data":"0x40c10f190000000000000000000000001781bd8bb7c48de5c77650bf0795328ba41dc46e00000000000000000000000000000000000000000000000000000000002625a0","gasPrice":"0x651a35bc2","to":"0xde5409f015fc173adec5eec8bb54223685790d37"}]}
```

Response:
```
{"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"unknown account"}}
```

DefaultAccount is added and private key for this address is in the wallet.

```
web3.eth.accounts.wallet.add(baseAccount.key);
web3.eth.defaultAccount = baseAccount.address;
```

Completely don't know what's going on. On the previous version everything was fine, but now I cannot back to beta26 because even I back with main package, all dependencies are at beta27(latest).

**Comment by MrTibbles** [comment]
@starspire - Please see the [Personal API](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal), all the methods are not documented on the web3js read the docs, just yet, but the signatures are the same. The methods you need to use for unlocking arbitrary accounts via a dapp is `importRawKey()` and `unlockAccount()`; make sure the `personal` [API](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#enabling-the-management-apis) is enabled for the respective protocol you are using (HTTP || WS).
Previously when i have attempted to use the `defaultAccount` method, geth returned `unknown account` error.

**Comment by vldmkr** [comment]
It seems I came across a related issue. As a temporary solution, you can set your dependencies as follows:
```json
"dependencies": {
  "web3": "1.0.0-beta.26",
  "web3-eth": "1.0.0-beta.26",
  "web3-eth-contract": "1.0.0-beta.26"
}
```
More details I described here #1276

**Comment by starspire** [comment]
Thanks @vldmkr for your temp solution. I confirm that locking this 3 dependencies solves the problem. @MrTibbles, thank you for your response also! However I don't want to use `unlockAccount()` in my implementation (unless I really don't have to), rather sign transaction locally and send as it is. Using `wallet` functionality as long as it was working was perfect solution according to the docs:

> The from property can also be an address or index from the web3.eth.accounts.wallet. It will then sign locally using the private key of that account, and send the transaction via web3.eth.sendSignedTransaction().

**Comment by MrTibbles** [comment]
@starspire yeah, agreed, it is not ideal. To be clear, i still sign the transactions locally and then send it. I did find that even with signing and sending it still returned unknown account.

**Comment by lakshmankashyap** [comment]
how can implement in hdwallet there no call unlock account method can you sugget frozeman

**Comment by BacchuRenuka** [comment]
@frozeman though I am using this above three package I am getting same issue.

**Comment by nivida** [comment]
@BacchuRenuka Have you also tested it with the latest version of web3.js (1.2.4 or the RC version 1.2.5-rc.0)?

**Comment by BacchuRenuka** [comment]
@nivida Yes I have used 1.2.4 also getting same issue it is for all not for only eth

**Comment by nivida** [comment]
@BacchuRenuka Thanks for your quick answer. As you can see here in our e2e tests is it working as expected. By side of those test cases will the [Wallet](https://web3js.readthedocs.io/en/v1.2.4/web3-eth-accounts.html#wallet) documentation help you to find your issue.
