### ISSUE TITLE
contractInstance.methods.someMethod(123).send(...) produce an error Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by vldmkr** [ethereum/web3.js#1276]
### Description

Using binary search I found out that the problem appeared after the [6cd3885](https://github.com/ethereum/web3.js/commit/6cd3885103e69f9a0a251e73446d45e16847e9d0) commit.
The problem is that **ethAccounts** is *undefined* at the stage when it is used. For example, when the **eth_sendTransaction** Method is being created at [884](https://github.com/ethereum/web3.js/blob/6cd3885103e69f9a0a251e73446d45e16847e9d0/packages/web3-eth-contract/src/index.js#L884) line.

### Temporary solution
In *package.json* you need to set the version of **web3-eth-contract** and everything that depends on it up to version **1.0.0-beta.26**.
```json
"dependencies": {
  "web3": "1.0.0-beta.26",
  "web3-eth": "1.0.0-beta.26",
  "web3-eth-contract": "1.0.0-beta.26"
}
```

**Comment by vldmkr** [comment]
https://github.com/vldmkr/web3-beta27-problem

I am adding a repository with a SSCCE so you can be sure. There are two files **package.json**. Make sure that you delete **node_modules** and **package-lock.json** before you change the version of **package.json**

**Comment by VoR0220** [comment]
Also having issues with this. Not sure if what I'm doing is correct for npm installation. Trying a couple things. This project is cluttered.
