### ISSUE TITLE
`eth.personal.ecRecover` produces a slightly different address than the signer one.

### ISSUE THREAD

**Issue by hickscorp** [ethereum/web3.js#1277]
When using `eth.personal` methods `sign` / `ecRecover`, I get a weird result.

Use case:

- I use a given address to sign an arbitrary message using `sign`.
- I then provide the original message and the signature to `ecRecover`.

Result:

The address returned by `ecRecover` is **slightly** different than the one used to sign, by just a few upcased / downcased characters.

To then know whether or not the signature matches, I downcase both addresses, but it feels quite weird to have to do that. Note that I am not providing the address used to sign the message manually, I retrieve it from `web3.eth.getAccounts`. Therefore it would be expected to be formatted the same way "in and out".

**Comment by jdkanani** [comment]
It's checksum address - https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md
