### ISSUE TITLE
for method 'getLogs' error: Error: [ethjs-format] hex string '0x654d0482c7d06d36384bfa8bbb30c5c4c4729364' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes

### ISSUE THREAD

**Issue by marzwu** [ethereum/web3.js#1278]
when i use web3.eth.filter as bellow:

      var options = {
        fromBlock: 0,
        toBlock: 'latest',
        topics: [],
        address: ['654d0482c7d06d36384bfa8bbb30c5c4c4729364']
      }

      filter = web3.eth.filter(options)
      filter.watch(function (error, log) {
        if (error) {
          console.error(error)
        } else {
          console.log(log)
        }
      })
    }

    filter.get(function (error, logs) {
      if (error) {
        console.error(error)
      } else {
        console.log(logs)
      }
    })

but i got:
**Error: [ethjs-query] while formatting inputs '[{"fromBlock":"0x0","toBlock":"0x17b759","address":["0x654d0482c7d06d36384bfa8bbb30c5c4c4729364"],"topics":[]}]' for method 'getLogs' error: Error: [ethjs-format] hex string '0x654d0482c7d06d36384bfa8bbb30c5c4c4729364' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 0 bytes**
    at Object.InvalidResponse (app.js:7314)
    at app.js:52118
    at inpage.js:9909
    at completeRequest (inpage.js:9960)
    at inpage.js:683
    at replenish (inpage.js:1203)
    at iterateeCallback (inpage.js:1193)
    at inpage.js:1168
    at inpage.js:9837
    at inpage.js:9933

any idea about this?

**Comment by benbaker** [comment]
+1

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
