### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by Suhail** [ethereum/web3.js#1285]
With the following content security policy: Content Security Policy directive: "default-src 'self'

The following becomes an issue:

```javascript
/**
 * @file givenProvider.js
 * @author Fabian Vogelsteller <fabian@ethereum.org>
 * @date 2017
 */

"use strict";

var givenProvider = null;

// ADD GIVEN PROVIDER
/* jshint ignore:start */
var global = Function('return this')(); // <--- THIS
```

I think it's important to be able to have strict security policies since XSS can easily become rampant across web pages and have devastating effects on users.

**Comment by dennisli92** [comment]
This is causing an issue for me as well. I am working on a chrome extension dApp with a similarly strict security policy in its manifest.

**Comment by williamchong007** [comment]
+1 this is causing me an issue when I am working on CSP
Was there a reason that line was written like that in the first place?
Removing it seems totally fine for my application.

**Comment by bokysan** [comment]
This [fix](https://github.com/nachomazzara/web3.js/commit/598c7429a6202942839e4f9e0e547b9c9dda46f2) is not good enough: it continues to spam our report logs with errors every time the page is loaded.

Is there any specific reason it can't simply be:

```javascript
global = window;
```
