### ISSUE TITLE
getPastEvents only returns results if fromBlock is high enough

### ISSUE THREAD

**Issue by JohanTh** [ethereum/web3.js#1297]
Using web3@1.0.0-beta.27.

Unless I have the `fromBlock` set to a too high number I get an error message when using `getPastEvents`. Setting it to 0 or removing it does not work. Depending on which address I am filtering on I have to set the `fromBlock` differently to not get this error message.

The error:
```
I20180117-00:31:35.710(1)? Error: CONNECTION ERROR: Couldn't connect to node on IPC.
I20180117-00:31:35.712(1)?     at Object.InvalidConnection (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\web3-core-helpers\src\errors.js:35:16)
I20180117-00:31:35.712(1)?     at WebsocketProvider._timeout (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\web3-providers-ws\src\index.js:192:48)
I20180117-00:31:35.713(1)?     at W3CWebSocket.connection.onclose (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\web3-providers-ws\src\index.js:96:15)
I20180117-00:31:35.713(1)?     at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\yaeti\lib\EventTarget.js:107:17)
I20180117-00:31:35.714(1)?     at W3CWebSocket.onClose (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\websocket\lib\W3CWebSocket.js:228:10)
I20180117-00:31:35.714(1)?     at WebSocketConnection.<anonymous> (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\websocket\lib\W3CWebSocket.js:201:17)
I20180117-00:31:35.715(1)?     at emitTwo (events.js:126:13)
I20180117-00:31:35.716(1)?     at WebSocketConnection.emit (events.js:214:7)
I20180117-00:31:35.716(1)?     at WebSocketConnection.drop (C:\Users\gatsu\Documents\Meteor\dapp\node_modules\websocket\lib\WebSocketConnection.js:468:14)
I20180117-00:31:35.717(1)?     at C:\Users\gatsu\Documents\Meteor\dapp\node_modules\websocket\lib\WebSocketConnection.js:301:18
I20180117-00:31:35.718(1)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180117-00:31:35.718(1)?     at process._tickCallback (internal/process/next_tick.js:180:9)
```

My event:

```
const fromBlock = 0;
const toBlock = latestBlock.numer - 10000;

contract.getPastEvents("CreatorContent", {
  filter: {
    creator: address,
  },
  fromBlock: fromBlock,
  toBlock: toBlock,
}, (error, event) => {
  // ...
});
```

**Comment by frozeman** [comment]
Which node are you using, or infura?
normally if you dont send `fromBlock` its `latest`. Its shouldnt error though

**Comment by JohanTh** [comment]
I am running a [gwhale](https://github.com/WhaleCoinOrg/WhaleCoin) node locally. Can it be a node setting issue?

I run this node using `gwhale --syncmode "full" --cache=4096 --networkid 30373 --mine --minerthreads 1 --rpc --rpcapi="db,eth,net,web3,personal,web3" --rpccorsdomain="http://domain:port" --rpcport 8545 --ws --wsapi="db,eth,net,web3,personal,web3" --wsorigins="*" --wsport 8546 --datadir="D:\Eth\whalecoin" --etherbase="address" console`

Sorry, not providing a `fromBlock` gives an empty array as results but no error, so it's working when it's `latest`.

**Comment by JohanTh** [comment]
This was a "max frame size" issue, I increased `maxReceivedFrameSize` and `maxReceivedMessageSize` to solve it.

**Comment by eladmallel** [comment]
@JohanTh thanks for sharing this! could you please share how you increased these values? 

was it by editing the npm module code directly? - for that you'd have to fork the library and then source your package from a git repo for this change to work anywhere (i.e. CI servers)

or was it a different approach somehow setting up your web3 client with a different configuration?

thanks!!

**Comment by JohanTh** [comment]
@eladmallel I edited the npm modules directly. Not the best way but works for me since my app was made for myself only so I did not bother forking.

**Comment by eladmallel** [comment]
@JohanTh thank you!

**Comment by daffl** [comment]
Made a comment how it can be done now without modifying your node modules in https://github.com/ethereum/web3.js/issues/1217#issuecomment-422584624
