### ISSUE TITLE
Unable to sign message, Error: Provided address "[object Object],[object Object]" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/web3.js#1298]
My code:

```
    const msgParams = [{
            type: 'string', name: 'Message', value: 'Hi, Alice!'  
         },{   type: 'uint32', name: 'A number', value: '1337'
          }];
          let from = Merchant.accounts[0];
          console.log(window.provider);
          let p = window.provider;
          console.log(Object.keys(window.web3));
          
          window.web3.eth.sign(from, msgParams, function(err, res) {
            console.log(err);
            console.log(res);
          });
```

(window.provider is the current provider.. window.web3 loses its current provider, see question https://ethereum.stackexchange.com/questions/36559/window-web3-currentprovider-is-null for details)

Running this I get the error in the title

Metamask prompted to sign.. once. Now the prompt won't show. The signing prompt did have the Alice, 1337 data in it.

How do I sign a message with Metamask to get the encrypted string of that signed message?

The logged output of Merchant.accounts[0] is

`0x2e290a50d3193753f156e5b0b12e4231bd568526`

and `typeof` is `string`.

**Comment by frozeman** [comment]
@kumavis ?

**Comment by quantumproducer** [comment]
@frozeman @kumavis Mispasted error the first time, updated topic. I am using  `1.0.0-beta.27`. I tried using the `web3.utils.sign` function:

```
const msgParams = [{
        type: 'string', name: 'Message', value: 'Hi, Alice!'  
     },{   type: 'uint32', name: 'A number', value: '1337'
      }];
      let from = window.web3.utils.toChecksumAddress(Merchant.accounts[0]);
      console.log(typeof(from));
      console.log(from);
      
      console.log(Object.keys(window.web3));
      
      window.web3.eth.sign(from, msgParams, function(err, res) {
        console.log(err);
        console.log(res);
      });
```

and I get the same error: `Error: Provided address "[object Object],[object Object]" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.`

**Comment by quantumproducer** [comment]
I tried this:

https://ethereum.stackexchange.com/questions/31488/provided-address-is-invalid-the-capitalization-checksum-test-failed-or-its-an is not a dupe, this is about signing messages

My code:

    const msgParams = [{
            type: 'string', name: 'Message', value: 'Hi, Alice!'  
         },{   type: 'uint32', name: 'A number', value: '1337'
          }];
          let from = Merchant.accounts[0];
          console.log(window.provider);
          let p = window.provider;
          console.log(Object.keys(window.web3));
          
          window.web3.eth.sign(from, msgParams, function(err, res) {
            console.log(err);
            console.log(res);
          });

(window.provider is the current provider.. window.web3 loses its current provider, see my other question https://ethereum.stackexchange.com/questions/36559/window-web3-currentprovider-is-null for details)

Running this I get the error in the title

Metamask prompted to sign.. once. Now the prompt won't show. The signing prompt did have the Alice, 1337 data in it.

How do I sign a message with Metamask to get the encrypted string of that signed message?

EDIT: Merchant is my utility class for Metamask. The logged output of Merchant.accounts[0] is

`0x2e290a50d3193753f156e5b0b12e4231bd568526`

EDIT 2: I have tried this:

    web3.eth.getAccounts(function(a,b) {
          Merchant.accounts = b;
          // alert("Saving accounts" + Merchant.accounts);
          console.log("Merchant accounts: " + Merchant.accounts);
          let x = web3.eth.getBalance;
          console.log(x);
        });



     toChecksumAddress (address) {
        address = address.toLowerCase().replace('0x', '')
        var hash = createKeccakHash('keccak256').update(address).digest('hex')
        var ret = '0x'
    
        for (var i = 0; i < address.length; i++) {
          if (parseInt(hash[i], 16) >= 8) {
            ret += address[i].toUpperCase()
          } else {
            ret += address[i]
          }
        }
    
        return ret
      }
    
    reloadKeys() {
            const msgParams = [{
            type: 'string', name: 'Message', value: 'Hi, Alice!'  
         },{   type: 'uint32', name: 'A number', value: '1337'
          }];
          // Merchant.accounts[0]
          // let addr = 0x2E290A50d3193753F156e5b0b12e4231Bd568526;
          let from = this.toChecksumAddress(Merchant.accounts[0]);
    
          // window.web3.utils.toChecksumAddress();
          console.log(typeof(from));
          console.log(from);
          
          console.log(Object.keys(window.web3));
          
          window.web3.eth.sign(from, msgParams, function(err, res) {
            console.log(err);
            console.log(res);
          });

**Comment by menacher** [comment]
I am also facing the same error. Any workarounds for this?

**Comment by quantumproducer** [comment]
Workaround: Paste your address from geth or wherever into etherscan.io, then copy the correct checksum address back into your javascript.

**Comment by TiagoGouvea** [comment]
Solution, explained: https://ethereum.stackexchange.com/questions/36561/signing-message-provided-address-is-invalid-the-capitalization-checksum-test-f/48320#48320

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
