### ISSUE TITLE
Transaction: stack underflow

### ISSUE THREAD

**Issue by stern0** [ethereum/web3.js#1300]
I have the following functions which store some info in a map:

The following are JS and Solidity code:
```js
const storeData = async(name, hash) => {
  const nameBytes = web3.fromAscii(name)
  const hashBytes = web3.fromAscii(hash)

  await contractInstance.storeData(nameBytes, hashBytes, { from: web3.eth.accounts[0] })
}
```
```js
mapping (bytes16 => bytes16) nameAndhash;

bytes16[] public imageList;

function storeData(bytes16 name, bytes16 imageHash) public {
  nameAndhash[imageHash] = name;
  imageList.push(imageHash);
}
```

When invoked I get the following error:
```Error: VM Exception while processing transaction: stack underflow```

I am using testrpc and here are the logs:

```
  Transaction: 0x21dbebdd360197e2b8b7383f568b874fd41200b8fb5e2257b546defe1e582223
  Contract created: 0xf58d311145c64569b711b7666e119f14a57c657f
  Gas usage: 90000
  Block Number: 11
  Block Time: Wed Jan 17 2018 14:22:04 GMT+0000 (UTC)
  Runtime Error: stack underflow
```

**Comment by frozeman** [comment]
Hi,

this is not a web3.js issue. This is either related to solidity, or how the js EVM works. @chriseth you have some ideas?

**Comment by stern0** [comment]
@frozeman I am not entirely sure about that as it works well with just the solidity code. If I dump the solidity code on remix it works fine like.

```js
  mapping (bytes16 => bytes16) nameAndhash;

  bytes16[] public imageList;

  function Image() public {}

  function storeData(bytes16 name, bytes16 imageHash) public returns (bool) {
    nameAndhash[imageHash] = name;
    imageList.push(imageHash);
    return true;
  }
```

**Comment by chriseth** [comment]
Stack underflow should never occur in any program generated from the solidity compiler. Which virtual machine did you use?

**Comment by yogeshwar607** [comment]
@kaskerd got any solution for this ?
