### ISSUE TITLE
what is the gas value  in web3.eth.accounts.signTransaction ?

### ISSUE THREAD

**Issue by alsemany** [ethereum/web3.js#1309]
wha should be the gas value ?? 

```
web3.eth.accounts.signTransaction({to: '0x',
    value: '1000000000',
    gas: VALUE
},

```

**Comment by alsemany** [comment]
it give me this 
insufficient funds for gas * price + value

**Comment by Andromelus** [comment]
First, you should not send to 0x, it does not exists.
Second, the gas value is the gas limit you want to provide to the transaction
Third, the insufficient founds error is there because the account you are trying to send ether from has not enough ether to execute the transaction.

**Comment by alsemany** [comment]
0x is just an example of address not sending to 0x

**Comment by alsemany** [comment]
Thank you for reply, 
is there a way to catch an exception  ?

**Comment by Andromelus** [comment]
Yes. According to the documentation, use the callback:

```
web3.eth.accounts.signTransaction({
    to: '0x',
    value: '1000000000',
    gas: VALUE
}, function (error, signedTx) {
    if (error) {
        //do stuff if error
    } else {
        //do stuff if no error, the second parameter is the signedTransaction (at least in web3js 1.0.0)
    }
})
```

**Comment by alsemany** [comment]
```
 web3.eth.sendSignedTransaction(data.rawTransaction, function(err, hash) {
    if (!err)
    {
      console.log(hash);
      res.send(hash);
    } else {
      console.log(err);
      res.send('err');
    }
});
```

thank you I actually doing it like that , but it still give errors
with the test network it works perfect , but the live not working

**Comment by Andromelus** [comment]
What is the error? Do we have to guess?

**Comment by alsemany** [comment]
ok never mind
