### ISSUE TITLE
Missing module in 1.0.0-beta2

### ISSUE THREAD

**Issue by Andromelus** [ethereum/web3.js#1310]
Hi.

In nodejs, importing` "web3": "^1.0.0-beta2"`, the module `web3-requestManager` is missing.

![web3jsbeta2missingmanager](https://user-images.githubusercontent.com/10050024/35181251-3903a22c-fdf9-11e7-8481-56af9743d683.png)

**Comment by justinmchase** [comment]
I get the same thing.

**Comment by lsaether** [comment]
This is a problem with how the package is registered (?) or being downloaded from NPM. To fix it locally you can specify the exact version. First uninstall web3 from your project, then install it again and specify the exact version you want, e.g. `npm i web3@1.0.0-beta.28`.

It would be nice to get a fix to this. I want to distribute a package over NPM that bundles web3 1.0.0 and if I try, NPM will always install the erroneous `web3@1.0.0-beta2` leading to this error.

**Comment by justinmchase** [comment]
Basically instead of doing `beta.28` it should just be `1.0.28-beta`. Then npm would pick up the patch change version.

**Comment by justinmchase** [comment]
How can I run a 1.0.0-beta node? I'm trying to use INFURA but its not working.

```js
var Web3 = require('web3')
var web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('https://ropsten.infura.io/sH34tSfDKm34ecQwz43N'))
web3.shh.getVersion((err, version) => {
  if (err) return console.error(err.message) // err, 
  console.log(version)
})
```

**Comment by suspended** [comment]
Same problem too

**Comment by Andromelus** [comment]
As @lsaether said, you can "fix" this specifying the version you want. works fine. But having a fix would be great!

**Comment by jellegerbrandy** [comment]
you can only "fix" it liek this using npm, though.

With `yarn`, I know of no fix (except using npm)

**Comment by frozeman** [comment]
I guess i should release this soon as 1.0.0
