### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by gmk292** [ethereum/web3.js#1315]
I need some help to figure out how to handle errors.

Sample Contract:

```javascript
pragma solidity ^0.4.19;

contract Sample{

   mapping(string => uint) balance;

   function creditUser(string name) public{
      balance[name] = 100;
   }
      
   function getBalance(string name) public view returns(uint){
      return balance[name]; 
   }
   
   function transfer(string from, string to, uint value) public{
      require(balance[from] > value); // Catch this error
      balance[from] -= value;
      balance[to] += value;
   }
}
```

I am using 1.0.0-beta.28 version of web3. 

**CONTRACT WRAPPER**
```javascript
const SampleContract = new web3.eth.Contract(sampleContract_ABI, sampleContract_Address);
```

After crediting **Alice** with 100 tokens, I am trying to call **transfer** function

```javascript
function transfer(from ,to, amount){
    var t = SampleContract.methods.transfer(from, to, amount).send({
        from: ethSync.getCoinbase() //custom method to make sync calls
    });

    t.then(receipt => {
        console.log(`${from} transferred ${amount} token to ${to}`);        
        getBalance(from);
        getBalance(to);
    }).catch(error => {
        console.log(error);
    });

    t.on('error', error => {
        console.log(error);
    });
}

function getBalance(name){
    SampleContract.methods.getBalance(name).call().then(data => {
        console.log(`${name} token balance is ${data}`);
    });
}

transfer('Alice', 'Bob', 5000); //Alice has a balance of 100.
```
I am expecting an error to be printed in the console. But the transaction is mined and is returning a transaction receipt.

Accoring to [solidity documentation](https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions)

> A require-style exception is generated in the following situations:
>  * Calling require with an argument that evaluates to false.

What is the correct approach of error handling?

**Comment by hrntknr** [comment]
It is correct behavior. The transaction is rollbacked by `revert()`, the history is on chain. If you want to handle error, you can reference `state` field of receipt. I think you got a receipt as this.
```js
{ blockHash: '0xdc1cc4ebdee4853fb58b06b94c3e188b882cd1ee40e809a5faa2d26516d032a7',
  blockNumber: 1053,
  contractAddress: null,
  cumulativeGasUsed: 29334,
  from: '0xbfe06b543964758e1e79033798e684371b7f9996',
  gasUsed: 29334,
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: '0x0',
  to: '0x7cf9da327e63d9cb51be495baf1c2a2377141248',
  transactionHash: '0x05e796941c51c02bf46ac3cb52d357619d4ce44cfaff2b6cbc22660ff13b4999',
  transactionIndex: 0,
  events: {} }
```
Please check [EIP658](https://github.com/ethereum/EIPs/pull/658) for details

**Comment by pmdcosta** [comment]
I am getting receipts like:
```
{
  blockHash: '0xa8af11f8ec753fd3e31de6e47122382992627ddc4cc36c189e28f1540ff7afb9',
  blockNumber: 4406,
  contractAddress: null,
  cumulativeGasUsed: 90000,
  from: '0x9304116169303a2dcc5072ac8a94a640e7f04130',
  gasUsed: 90000,
  logsBloom: '0x00000000000000...000000',
  root: '0x5b7ff312e2bd6748708f2fa83ec69e1b101d980f7a7b5ece4717aa72d1688b0e',
  to: '0xf2e6dbd55f5a3cc21e523b79e1ce01e9ad837bb2',
  transactionHash: '0x1c5a527687bc0e5631bb39e847a7b30cd27115fc0f2056347002cc06fcbee1d7',
  transactionIndex: 0,
  events: {} 
}
```

I am on v1.8.4 of geth and 1.0.0-beta.34 of web3.
Any idea, why I am not getting the `status` field in the receipt?

**Comment by jayliang701** [comment]
same issue. any idea?

**Comment by RolandBarro** [comment]
I have experienced the same error just recently and I was able to manage it by checking up on these lines of codes:
----
const provider =  new HDWalletProvider(process.env.MNENOMIC, `https://rinkeby.infura.io/v3/${process.env.INFURA_API_KEY}`);
-----
check: console.log(provider) if you can see perfectly your mnemonic and your Infura connection string
if yes, the check on this code:
----
const contract = require('../build/contracts/Contract.json');
const abi = contract.abi;

const instance = new web3.eth.Contract(abi, process.env.CONTRACT_ADDRESS);
console.log(instance)
----
try again and check the same as above but now include the `contract address` and your contract creator address

If any of those where not the same or lacking. This surely is the reason why you get such transaction results.

**Comment by RolandBarro** [comment]
sorry for the formatting, I never thought it look like that when sent :)

**Comment by arinddas** [comment]
> I am getting receipts like:
> 
> ```
> {
>   blockHash: '0xa8af11f8ec753fd3e31de6e47122382992627ddc4cc36c189e28f1540ff7afb9',
>   blockNumber: 4406,
>   contractAddress: null,
>   cumulativeGasUsed: 90000,
>   from: '0x9304116169303a2dcc5072ac8a94a640e7f04130',
>   gasUsed: 90000,
>   logsBloom: '0x00000000000000...000000',
>   root: '0x5b7ff312e2bd6748708f2fa83ec69e1b101d980f7a7b5ece4717aa72d1688b0e',
>   to: '0xf2e6dbd55f5a3cc21e523b79e1ce01e9ad837bb2',
>   transactionHash: '0x1c5a527687bc0e5631bb39e847a7b30cd27115fc0f2056347002cc06fcbee1d7',
>   transactionIndex: 0,
>   events: {} 
> }
> ```
> I am on v1.8.4 of geth and 1.0.0-beta.34 of web3.
> Any idea, why I am not getting the `status` field in the receipt?

I was also facing this issue, but finally solved it.

If you are using private ethereum setup then add :

"byzantiumBlock": 0 in the cofig portion of genesis file.

Sample:
     "config": {
		"chainID": 577,
		"homesteadBlock": 0,
		"eip155Block": 0,
		"eip158Block": 0,
		"byzantiumBlock": 0
	}

Hope it will resolve your issue.
