### ISSUE TITLE
subscribe(“logs”) only returns first log

### ISSUE THREAD

**Issue by mikemcdonald** [ethereum/web3.js#1322]
https://github.com/ethereum/web3.js/blob/2386448e3068e98ebeb671f62f142b24d65ba79e/packages/web3-core-subscriptions/src/subscription.js#L258-L259

Is this ready to be updated so the full array of logs is returned? I saw the note about removing these lines once fixed in geth

**Comment by AC0DEM0NK3Y** [comment]
Please update on this, I just found an issue that looks like it stems from this i.e. if you are subscribed and multiple events occur in the same mined block, you only get the first event data.
