### ISSUE TITLE
new Web3.providers.HttpProvider(...) error

### ISSUE THREAD

**Issue by lightninglu10** [ethereum/web3.js#1327]
Hey guys, is there anyway to tell when this call 
```
new Web3.providers.HttpProvider(...)
```
errors? Sometimes I can't connect to certain blockchain nodes and I want to connect to another one if that's the case. I put a try catch around it but it doesn't work.

**Comment by mishfit** [comment]
Just looking at the function and it doesn't actually do anything other than set properties for an actual 'send'/'sendAsync': [lib/web3/httpprovider.js](https://github.com/ethereum/web3.js/blob/fb5ff9f46527a22a2ae5d650fdebac13755fe2bb/lib/web3/httpprovider.js#L42-L48)

A call to `web3.isConnected` might help you out
