### ISSUE TITLE
Contract examples aren't waiting for contracts to be confirmed before calling them 

### ISSUE THREAD

**Issue by drcode** [ethereum/web3.js#133]
Hi, near as I can tell, the contract.html example code won't work if the user presses the second button before waiting for the contract to be confirmed first. (at least when using the go-ethereum client)

Shouldn't there be some code that waits for the contract to be confirmed before enabling the ability to call?

This would be especially valuable since there is little documentation as to how one actually can tell when a transaction has confirmed... I realize I can use "web3.eth.filter('latest').watch()", but that function doesn't seem to give me any info on a specific transaction's confirmation status...

Also: I believe your examples are still missing the "From" parameter that is required by the latest go-ethereum client.

**Comment by frozeman** [comment]
To see if a tx was mined you could check the next blocks tx and see if the from is matching your sending address.

Could be done in a simple script.

**Comment by debris** [comment]
on latest develop `contract.html` and `event_inc.html` are waiting for mining the block.
