### ISSUE TITLE
gasUsed doesn't report units used.

### ISSUE THREAD

**Issue by nickjm** [ethereum/web3.js#1332]
From personal experiments I've determined `gasUsed` and `cumulativeGasUsed` are in units of 10^11 Wei, which is pretty random. This should be explicitly conveyed in all the relevant places in the documentation.

**Comment by nickjm** [comment]
I asked about this on this [Ethereum Stack Exchange post](https://ethereum.stackexchange.com/questions/37805/why-is-the-units-of-gasused-in-the-transaction-receipt-1011-wei) in case there is something deeper going on here

**Comment by Andromelus** [comment]
I think there is a misunderstanding. gas is not ether. It is just a value used to determine the actions made by the EVM. To get the equivalent in ether, you multiply it by gasPrice.

**Comment by nickjm** [comment]
That's what I thought too. I think I was confused by Ganache's interface which told me the "Gas Price" was 20000000000 -- which I assumed was a global default for all transactions. This number didn't work with my calculations so I made a bad assumption, that web3 was wrong.
