### ISSUE TITLE
Performance issue with web3js@0.20.x

### ISSUE THREAD

**Issue by subhasisbanik** [ethereum/web3.js#1337]
I am working on a project which requires bulk processing of transactions sent to the node.
I am using web3js version as 0.20.x for posting and getting responses from my local running node cluster.
I am facing severe performance issues while posting such bulk transactions.
Also nodejs server crashes when huge number of concurrent requests are made.

Contract I am using:

pragma solidity ^0.4.0;

contract Sample{
    uint _val;
    function setVal(uint val){
        _val = val;
    }
    function getVal() returns (uint){
        return _val;
    }
}

Report from Apache bench on hitting my exposed API is attached.
Note: I am only calling the getVal() from web3js.
[apache bench report.xlsx](https://github.com/ethereum/web3.js/files/1677815/apache.bench.report.xlsx)

Update:
Just tested the same code in web3@1.0.0-beta.29 and found far better results attached.
I would surely love to know if there is any serious performance issues found in web3@0.20.4 which was fixed in web3@1.0.0-beta.29. Also since 1.0.0-beta.29 is a beta version, is there any alpha version lined up for release?
[apache bench report1.xlsx](https://github.com/ethereum/web3.js/files/1681046/apache.bench.report1.xlsx)

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
