### ISSUE TITLE
Web3 1.0 Provider interface (type declarations)

### ISSUE THREAD

**Issue by dekz** [ethereum/web3.js#1339]
Looking forward to using Web3 1.0 when it is fully out of beta! From my understanding, previously the simplest provider used to construct a Web3 instance is a object that implements `send`, aka an [IProvider](https://github.com/ethereum/web3.js/blob/1.0/packages/web3/types.d.ts#L232-L234).

The `HttpProvider` `IPCProvider` and `WebsocketProvider` define additional methods and parameters outside of this interface. These are joined together on a union type of `Provider`. It is this `Provider` union type which is the declared type in the [Web3 constructor](https://github.com/ethereum/web3.js/blob/1.0/packages/web3/index.d.ts#L13), not a type of `IProvider`.

This forces simple providers which only implement `send` to define additional parameters and methods beyond the `IProvider` interface. 

We have been using [Provider Engine](https://github.com/MetaMask/provider-engine) to initialise Web3 in `0.20.x` and unfortunately this will not work with Web3 1.0 without an adapter or a change to Provider Engine.

Is the simplest Provider in Web3 1.0 still an object with a `send` method? Can the constructor be changed to accept anything that is an `IProvider` rather than the `Provider` union type?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
