### ISSUE TITLE
getPastEvents not recongnizing fromBlock value

### ISSUE THREAD

**Issue by HatimKH** [ethereum/web3.js#1343]
The fromBlock filter is ignored. The results are including all the blocks even if fromBlock > 0

The method used is 
```
contractInstance.getPastEvents('Transfer', { fromBlock: 19, toBlock: 'latest'});
```
Thanks for your support

**Comment by HatimKH** [comment]
Fixed in "web3": "^1.0.0-beta.18"

**Comment by Freydal** [comment]
Has there been a regression with this?  

```
// block_number = the block of the most recent event
contractInstance.getPastEvents('DealAdded', { fromBlock: block_number, toBlock: "latest" }).then((r) => console.log(r.length));
//Prints 228 (the total events events from contract). I think I would expect 1.
contractInstance.getPastEvents('DealAdded', { }).then((r) => console.log(r.length));
//Prints 0
```

Initial development using 1.0.0-beta.31.  I rolled back to beta 18 and experience the same behavior.

**Comment by alexiicon** [comment]
This is repeated on latest version whatever value i use in "fromBlock" it doesn't return anything
