### ISSUE TITLE
web3.sha3 returns incorrect result

### ISSUE THREAD

**Issue by bingtimren** [ethereum/web3.js#1344]
I was calculating the hash of an address but the result was not as expected. Consider the commands and results below.

I am expecting the result of "web3.sha3(something)" is always the same as the result of "web3.sha3(web3.toHex(something),{encoding:'hex'});"  Am I wrong?

=====================================================================
```

truffle(develop)> buyer = "f17f52151EbEF6C7334FAD080c5704D77216b732"
'f17f52151EbEF6C7334FAD080c5704D77216b732'
truffle(develop)> addr = web3.toAscii(buyer)
'ñR\u0015\u001e¾öÇ3O­\b\fW\u0004×r\u0016·2'
truffle(develop)> web3.toHex(addr);
'0xf17f52151ebef6c7334fad080c5704d77216b732'
truffle(develop)> web3.sha3(web3.toHex(addr),{encoding:'hex'});
'0xe52111628d5433237c36e91f159620decfa7747d736dee9676f3afc40471618a'
truffle(develop)> web3.sha3('0xf17f52151EbEF6C7334FAD080c5704D77216b732',{encoding:'hex'});
'0xe52111628d5433237c36e91f159620decfa7747d736dee9676f3afc40471618a'
truffle(develop)> web3.sha3('f17f52151EbEF6C7334FAD080c5704D77216b732',{encoding:'hex'});
'0xe52111628d5433237c36e91f159620decfa7747d736dee9676f3afc40471618a'
truffle(develop)> web3.sha3(addr)
'0x6a39914de34bb322b1ff6db83d1f7865d40df3d8b5a83592c9c6710bf517d71e'
truffle(develop)> 

```

**Comment by DanielMReed** [comment]
Your hashes are the same for all cases other than your last, which is hashing the Ascii of the address, not the hex

**Comment by bingtimren** [comment]
That was the point. I was expecting web3.sha3(web3.toHex(addr),{encoding:'hex'}) same as web3.sha3(addr). If I hash the hex representation of an ascii string and telling the function it's a hex by providing {encoding:'hex'}, should I expect the results are the same?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
