### ISSUE TITLE
Should allow overload to sign hash without ethereum signed message prefix 

### ISSUE THREAD

**Issue by James-Sangalli** [ethereum/web3.js#1345]

**Comment by James-Sangalli** [comment]
hi @alexwagg, thanks for your reply.

We are building a wallet and need to sign messages for trading, to protect our users against scam signing we add our own custom prefix.

With the current implementation you cannot sign Binary data like we want to because it enforces a utf8 cast on the message length making it impossible, for us to efficiently encode our messages we need to be able to do this (and many others will need this too). 

Libraries like Web3j allow REAL developers to sign messages without this prefix attached, since this is one of the most popular libraries out there for ethereum, it should allow it too.

**Comment by pubkey** [comment]
Another concern I have is that the signature is overloaded with the same string each time. This means that when my contract is deployed multiple times, the signatures could be replayed on each of them. Of course we should always overload before signing things but I question if this should automatically be done by web3js.

**Comment by JamesANZ** [comment]
I realise that web3js is at the mercy of Geth client as it calls the RPC for everything including hashing and signing. This therefore needs to go into the client and not here.

**Comment by pubkey** [comment]
Isnt signing done without a RPC-call?

**Comment by JamesANZ** [comment]
@pubkey 
It seems (and correct me if I am wrong) that how the signing is done is determined by the client (e.g. Geth), using eth_sign rpc call. Web3js just facilitates the exchange with the RPC server; unlike Web3j which allows you to independently do functions like this. 

It is exactly the same when using metamask, metamask would act like the geth node and call eth_sign meaning that what happens to the message is controlled by the node implementation. Web3js is just the conduit to the rpc server. 

Hence, if we wanted to change the way signing is done in web3js, we would have to change the client implementation e.g. geth
