### ISSUE TITLE
web3.eth.getAccounts returns only limited addresses

### ISSUE THREAD

**Issue by tony-stark001** [ethereum/web3.js#1347]
Hi,
In my website, there are more than 4000+ addresses currently. When I try to get all accounts using 'web3.eth.getAccounts' it only returns 3360 addresses. I don't know why this happens. For the remaining addresses which are not listed in getAccounts, I have tried 'getBalance' to check if address is valid or not, but it returns expected balance.

**Comment by nivida** [comment]
Please provide more information such as code snippets

**Comment by nivida** [comment]
Closed due to no reaction of the creator.
