### ISSUE TITLE
Incorrect provider on Contracts when using multiple instances of web3

### ISSUE THREAD

**Issue by henryaddison** [ethereum/web3.js#1349]
I'm using version `1.0.0-beta.26` of web3.js to try and build an oracle to watch for an event on one chain and respond by sending a transaction to another chain. Creating multiple instances of Web3 is fine but creating `Contract` objects is behaving unexpected as the `currentProvider` of the `Contract` instance seems to depend on the `currentProvider` of the last instantiated `Web3` object rather than the `currentProvider` of the `Web3` object used to build create contract object. 

Suppose chain a is accessible on port 8546 and chain b on 9546. I create two instances of `Web3`:

    web3a = new Web3('ws://localhost:8546');
    web3b = new Web3('ws://localhost:9546');

But then if I try and get a contract on the `a` chain, it will try and talk to the `b` chain. e.g.

    const someContractOnA = new web3a.eth.Contract(abi, address)
    console.log(someContractOnA.currentProvider.connection.url)
    # => ws://localhost:9546

The `b` connection url is logged rather than the `a` connection that I would expect.

Further if the order in which `web3a` and `web3b` are created is switched then the url will also change leading me to conclude that it's using the last instantiated `Web3` object's provider.

**Comment by nivida** [comment]
```someContractOnA.setProvider()``` will solve your problem for now. We have already an issue about this and because of that I will close this one.

**Comment by xeroblood-io** [comment]
Can you share the open issue so that some of us may follow the progress?  Thanks!
