### ISSUE TITLE
How to multi-send ERC20 token?

### ISSUE THREAD

**Issue by FradSer** [ethereum/web3.js#1350]
Hey all, I have written a simple script to send ERC20 token. [Here](https://github.com/MineFIL/mfil-erc20-smart-contract/blob/master/scripts/single-address-allocation.js) is the code and it works fine.

**But I have some problem with sending the ERC20 token to the different address at same time. Is there any simple way to do this?**

**Comment by kongnet** [comment]
+1
multi address
mulit transfer method

**Comment by iurimatias** [comment]
Hi @FradSer this question is more apropriate for the ethereum stack exchange.

https://ethereum.stackexchange.com

AFAK, if you want to send the token to multiple addresses in the same tx, you'll need to implement this on the contract site.

**Comment by rstormsf** [comment]
efficiently distribute massive batches of tokens and airdrops in a single click using https://multisender.app

**Comment by c0deCn** [comment]
efficiently distribute massive batches of tokens and airdrops in a single click using https://cointool.app
