### ISSUE TITLE
Issue with formatter while running web3.eth.getBlock in web3@1.0.0-beta.29

### ISSUE THREAD

**Issue by subhasisbanik** [ethereum/web3.js#1351]
In web3-core-helpers/src/formatters.js, line no. 220,
block.timestamp = utils.hexToNumber(block.timestamp);
the conversion from hex to Number throws an error, "Error in parsing....."
To fix this, 
block.timestamp = utils.hexToNumberString(block.timestamp);

I think this change should be made into the repo.

**Comment by Freyert** [comment]
@subhasisbanik are you running against JPMorgan's Quorum fork? Or does this happen against the main Ethereum chain?

**Comment by nivida** [comment]
@subhasisbanik feel free to submit an PR. :)

**Comment by princesinha19** [comment]
@nivida I tried to reproduce this bug. But, I think this problem is not with geth or ganache. This can be with Quorum.
You can close this ticket and can tag **Duplicate** of #1215.
