### ISSUE TITLE
Web3 Ethereum/wiki docs need updating or web3 and json-rpc related issues need responding to

### ISSUE THREAD

**Issue by jamesray1** [ethereum/web3.js#1352]
Someone please update the docs in the Ethereum Wiki on web3.js and json-rpc as people are complaining that nobody is maintaining them in the Ethereum Wiki issues, or there are just a lot of open issues for these topics.

https://github.com/ethereum/wiki/search?utf8=✓&q=web3&type=

**Comment by jamesray1** [comment]
Many of the issues in that repo are about web3.

**Comment by jamesray1** [comment]
I've closed a lot of issues without addressing them, referring them indirectly via a help section to here.

**Comment by nivida** [comment]
I will close this issue because the current wiki does get updated by the broad ethereum community. I will keep an eye on this wiki as well.
