### ISSUE TITLE
getNetwork not available

### ISSUE THREAD

**Issue by evbots** [ethereum/web3.js#1353]
using the tag: ^1.0.0-beta.29

<img width="216" alt="screen shot 2018-02-03 at 10 42 50 am" src="https://user-images.githubusercontent.com/3102036/35768741-0659030e-08cf-11e8-86cc-af905fa0d216.png">

The version property on the `web3` object is a string, not an object. So attempting to call properties like `node`, `network`, or `getNetwork` all fail. Any guidance is appreciated.

**Comment by zulhfreelancer** [comment]
Also facing this issue in web3.js v1.0.0-beta.34.
Did anyone managed to solve this?

**Comment by nivida** [comment]
The ``web3-eth`` (``web3.eth.*``) and ``web3-net`` (``web3.eth.net.*``) packages do provide all required methods.
