### ISSUE TITLE
Cannot send a transation even though I have enough balance

### ISSUE THREAD

**Issue by AyushG3112** [ethereum/web3.js#1357]
In `version 1.0.0-beta.29`:

My account Balance:

`eth.getBalance(eth.accounts[7])` gives `10029800000000000`

So I calculate the transaction fee as 
`web3.eth.gasPrice + web3.eth.estimateGas({
    from: eth.accounts[7],
    to: eth.coinbase
})`

which comes out to be: `420000000000000`

Now, I try to send the transaction as:

`web3.eth.gasPrice + web3.eth.estimateGas({
    from: eth.accounts[7],
    to: eth.coinbase,
   value: 10029800000000000 - 420000000000000
})`

But I get the Insufficient Funds Error,

I also tried doubling the transaction fee, but I still get an error.

Is this a bug with web3 or am I doing something wrong?

**Comment by GustavoRSSilva** [comment]
Have you sign the transaction?

> The Ethereum network needs to know that you actually own that account to make sure someone else doesn’t execute this transaction on your behalf. The way to prove this to the network is by signing the transaction using the private key corresponding to that account.

**Comment by AyushG3112** [comment]
I unlocked the account before sending the transaction

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
