### ISSUE TITLE
web3.eth.Contract.deploy()  exception   version 1.0.0-beta.29

### ISSUE THREAD

**Issue by weijunlee** [ethereum/web3.js#1358]
```
function Voting(bytes32[] candidates) public { 
}
```
when 
```
VotingContract.deploy({data : byteCode, arguments:['Rama','Nick','Jose']})
```
got exception :
``
Invalid number of parameters for "undefined". Got 3 expected 1!
``

and then 
```
VotingContract.deploy({data : byteCode, arguments:[['Rama','Nick','Jose']]})
```
got exception : 
``
Given parameter is not bytes: "Rama"
``

I'm not sure that this problerm is a bug or my usage is not correct.

**Comment by Jusdev89** [comment]
Did you ever figure this out? having the same issue.

**Comment by weijunlee** [comment]
@Jusdev89 Not yet

**Comment by congxinUSC** [comment]
@weijunlee I think you might need an extra pair of brackets around your parameters and might also need to convert the strings into hex bytes by web3.utils.asciiToHex(). (Not sure.)

**Comment by fabiosalzano** [comment]
Same issue here. My contract constructor wants two input `string` fields.

`contract.deploy({arguments: ['abc', 'def']})` gives `Error: Invalid number of parameters for "undefined". Got 0 expected 2!`

`contract.deploy({arguments: [['abc', 'def']]})` gives `Error: Invalid number of parameters for "undefined". Got 1 expected 2!`

`contract.deploy({arguments: [['abc'], ['def']]})` gives `Error: Given parameter is not a valid string: abc`

`contract.deploy({arguments: [['abc'].toString(), ['def']]}))` gives `Error: Given parameter is not a valid string: def`

`contract.deploy({arguments: [['abc'].toString(), ['def'].toString()]}))` gives `Error: Invalid number of parameters for "undefined". Got 0 expected 2!`

`contract.deploy({arguments: [['abc'.toString()], ['def'.toString()]]})` gives `Error: Given parameter is not a valid string: abc`

**Comment by sc0Vu** [comment]
The arguments length should match the function param length, check this line: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/index.js#L689

So if the function is
```
function Voting(bytes32[] candidates) public { 
}
```

You need to deploy like this
```
Contract.deploy({data : byteCode, arguments:[[web3.utils.asciiToHex('Rama')]]})
```

Hope it helps:!

**Comment by weijunlee** [comment]
@sc0Vu Aha, it worked, thank you very much!

**Comment by fabiosalzano** [comment]
@sc0Vu thank you for your reply!

I've changed my contract constructor, now I've the same constructor you posted above.

I deploy in this way:

`contract.deploy({data: bytecode, arguments:[[web3.utils.asciiToHex('Name1')], [web3.utils.asciiToHex('Name2')]]})`

But i get the same error:

```
Error: Invalid number of parameters for "undefined". Got 2 expected 1!
    at Object.InvalidNumberOfParams (C:\Projects\test\node_modules\web3-core-helpers\src\errors.js:32:16)
    at Object._createTxObject (C:\Projects\test\node_modules\web3-eth-contract\src\index.js:693:22)
    at Contract.deploy (C:\Projects\test\node_modules\web3-eth-contract\src\index.js:498:33)
```
Seems that the problem was here:

```
    return this._createTxObject.apply({
        method: constructor,
        parent: this,
        deployData: options.data,
        _ethAccounts: this.constructor._ethAccounts
    }, options.arguments);
```

**Comment by weijunlee** [comment]
@fabiosalzano Please change your code to 
```
contract.deploy({data: bytecode, arguments:[[web3.utils.asciiToHex('Name1'),web3.utils.asciiToHex('Name2')]]})
```
wish you success!

**Comment by fabiosalzano** [comment]
@weijunlee I had tried this way too, but I received a slightly changed error

`Error: Invalid number of parameters for "undefined". Got 0 expected 1!`

Zero parameters??!? I can't understand...

**Comment by fabiosalzano** [comment]
I place a `console.log('args', args);` before the code that thrown the error.

```
    console.log('args', args);
	
    if (args && this.method.inputs && args.length !== this.method.inputs.length) {
        if (this.nextMethod) {
            return this.nextMethod.apply(null, args);
        }
        throw errors.InvalidNumberOfParams(args.length, this.method.inputs.length, this.method.name);
    }
```
This is what it logged:

```
args [ [ '0x4e616d6531', '0x4e616d6532' ] ]
args []
```
For some reason it executes the code two times, I've to understand why

**Comment by fabiosalzano** [comment]
I've found the problem, was my fault, I had a subsequent call to deploy in the code to which I had not passed parameters by mistake. The problem is that the error was reported to me on the first call.

**Comment by INTERESTING-OMG** [comment]
Can you give me your web3.js ， I want the version . Thank you very much. I tried my best to install and failed. I  hope very much to get your folders named "node_modules" to wmm930426@gmail.com. Thank you!

**Comment by erinbagel** [comment]
I literally don't even understand the need for parameters/what the parameters in the case of deploying. wtf.

**Comment by cwang25** [comment]
Send()  will have the same issue. 
Tried passed in 
```[[web3.utils.asciiToHex('Name1'),web3.utils.asciiToHex('Name2')]]
```

still get Uncaught Error: Given parameter is not bytes: "undefined"...

My solidity function is : byte[100][] Names

Please help... thanks!

**Comment by weijunlee** [comment]
@cwang25 Please change your web3.js version or change your parameter to bytes[] ,not sure,just try it.
