### ISSUE TITLE
Cannot subscribe to more than one topic

### ISSUE THREAD

**Issue by justinmchase** [ethereum/web3.js#1361]
I'm not sure if this is a bug or if I'm doing it wrong but when I subscribe to multiple topics using the whisper API but I am only getting messages for the "last topic" in the topics array.

So the tldr; is in my call to `shh.subscribe` if I have:
```js
topics: [topic, topic2, topic3]
```
And in my call to `shh.post`, I will only recieve messages from `topic3`. If you just alter the order of the topics in the array and the common thread is that its always the "last" topic.

I am running geth in docker with the `--shh` flag enabled.

Here is my full code:
```js
import Web3 from 'web3'

;(async function main () {
  const web3 = new Web3()
  web3.setProvider('ws://localhost:8546')
  web3.eth.defaultAccount = await web3.eth.getCoinbase()

  const version = await web3.shh.getVersion()
  console.log({ version })

  const info = await web3.shh.getInfo()
  console.log({ info })

  const symKey = await web3.shh.newSymKey()
  const keyPair = await web3.shh.newKeyPair()
  const topic1 = '0xffaadd11'
  const topic2 = '0xffaadd22'
  const topic3 = '0xffaadd33'
  const subscription = await web3.shh.subscribe('messages', {
    symKeyID: symKey,
    topics: [topic1, topic2, topic3] // only last topic here gets messages
  })
  .on('data', data => console.log(new Buffer(data.payload.replace(/^0x/, ''), 'hex').toString('utf8')))
  await web3.shh.post({
    symKeyID: symKey,
    sig: keyPair,
    ttl: 100,
    topic: topic1,
    payload: `0x${new Buffer(topic1).toString('hex')}`,
    powTime: 3,
    powTarget: 0.5
  })
  await web3.shh.post({
    symKeyID: symKey,
    sig: keyPair,
    ttl: 100,
    topic: topic2,
    payload: `0x${new Buffer(topic2).toString('hex')}`,
    powTime: 3,
    powTarget: 0.5
  })
  await web3.shh.post({
    symKeyID: symKey,
    sig: keyPair,
    ttl: 100,
    topic: topic3,
    payload: `0x${new Buffer(topic3).toString('hex')}`,
    powTime: 3,
    powTarget: 0.5
  })
})()
```

Output:
```sh
01:53:35:justin:/mnt/e/code/erc/apps/api$ node -r @babel/register .
{ version: '5.0' }
{ info: { memory: 915, messages: 0, minPow: 0.2, maxMessageSize: 1048576 } }
0xffaadd33
```

**Comment by justinmchase** [comment]
Possibly related to #1059

**Comment by justinmchase** [comment]
If I make 3 subscriptions, each to a different topic then it works fine.

**Comment by dhl** [comment]
I'm also having the same issue with geth 1.8.1 and web3.js 1.0.0-beta.30. The workaround, as @justinmchase described, is to have individual subscriptions to each of the topics.

**Comment by justinmchase** [comment]
I am also using the 1.0 beta

**Comment by dhl** [comment]
@justinmchase I have been able to reproduce the issue by making JSON-RPC call to geth 1.8.1. This appears to be a regression in geth, and is not web3 specific.

**Comment by fizikst** [comment]
I have a similar story when I subscribe to multiple topics using the whisper API:

```javascript
    web3.shh.subscribe('messages', {
      topics: [],
      symKeyID: symKeyID
    }, (err, msg, subscr) => { console.log(msg) })
```
I always get logs is empty for any topics (0x44001122, 0x44001133, 0x44000000, 0x44444444 e.t.).
any idea?

**Comment by justinmchase** [comment]
@fizikst I think @dhl 's answer to the issue should explain it.

What we're doing is supposed to work but there is currently a regression in geth itself which is causing the issue. So until that bug is fixed you'll need to do a work around which is to make multiple subscriptions, one for each topic you wish to listen for.

**Comment by justinmchase** [comment]
@nivida Was there a commit we can tag to this that resolved it? Or was it just magically fixed in geth?

**Comment by richard-ramos** [comment]
Issue is still present in geth 1.8.14
