### ISSUE TITLE
isConnected

### ISSUE THREAD

**Issue by zamoore** [ethereum/web3.js#1362]
What is the new method for determining if you have an active connection to a node? I need to set up an error state in my app if the user stops parity.

**Comment by Andromelus** [comment]
There is not. You can try the method to get the geth version or an other "small" function.

**Comment by vora007mayur** [comment]
web3.version.node or web3.version.getNode() is not working!!

**Comment by iurimatias** [comment]
```web3.eth.getNodeInfo()``` is now available in beta-34
