### ISSUE TITLE
Contract owner address not Deploying retrive null in trascation reciept  

### ISSUE THREAD

**Issue by switchtoriyaz** [ethereum/web3.js#1368]
I am using Robsten Network on geth 

var myContract = new web3.eth.Contract(abi);

myContract.options.address = '0x12345...';

{"blockHash":"0x81b47274082ebdbf7866e8754cc2f1d73417069cf83b53611e9a82a2030a7194","blockNumber":2626516,"contractAddress":"0x4AE6b3f6001174eF06A4c34ab2339C4eD96888f5","cumulativeGasUsed":2021099,"from":"0x3f1ab25c5c7830329db1662cc22b55431dc614f2","gasUsed":1300837,"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x1","to":null,"transactionHash":"0x90c97aad1669bf2aac5e03ac9d88eb13b6eab5211a487c722f6c1ceba52e62b2","transactionIndex":6,"events":{}}

**Comment by nivida** [comment]
Please ask your question on https://ethereum.stackexchange.com/
