### ISSUE TITLE
Web3.js subscription for 'newBlockHeaders' misses blocks occasionally

### ISSUE THREAD

**Issue by zebpayShravan** [ethereum/web3.js#1375]
**Ethereum Client:** Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
**web3.js:** 1.0.0-beta.29
**Node:** 8.9.1
**Provider**: Websocket

The below code misses one or two blocks once in a while.

This is how I'm using the subscribe
```
  var blockWatcher = web3ws.eth.subscribe('newBlockHeaders',function(err,res){
    if(err){
      logger.error('coudlnot subscribe to latest blocks',err);
      process.exit(-1);
    }
        //logger.debug('succefully subscribed to latest blocks',res);
  });

  blockWatcher.on('data', function(blockHeader) {
     //process block
  });
```

Am I missing something here?

**Comment by evseevnntmp** [comment]
That can be problem of Parity.

**Comment by nivida** [comment]
This has to be an issue of the connected node.
