### ISSUE TITLE
Not receiving events after redeploying contract

### ISSUE THREAD

**Issue by Tenareth** [ethereum/web3.js#1378]
I feel like I'm missing something simple, but I can't find the source of the problem.  I had the SimpleVote demo working great in Azure on a PrivateNet with MetaMask.  All was great.  I redeployed a new version of the contract and updated the address in the node.js app to the new address and while the contract executes the front-end app is not getting any events.

EtherVote.sol

```solidity
pragma solidity ^0.4.4;

contract EtherVote {
  event LogProposal (string proposal, bytes32 proposalHash, address addr);
  event LogVote (bytes32 proposalHash, bool support, address addr);

  function propose (string proposal, bytes32 proposalHash) public {
    LogProposal(proposal, proposalHash, msg.sender);
  }

  function vote (bytes32 proposalHash, bool support) public {
    LogVote(proposalHash, support, msg.sender);
  }

  function () public {
    revert();
  }
}
```

The code that does the watch (inside a Vuex state server):

```javascript
      watchProposals: async ({ commit, state }) => {
        // watch for proposals
        const logProposals = await etherVote.logProposal()
        logProposals.on('proposal', event => {
          const { addr, proposal, proposalHash } = event.args
          const { transactionHash } = event

          commit('updateProposal', {
            proposal,
            proposalHash,
            transactionHash
          })

          commit('updateTransaction', {
            from: addr,
            tx: transactionHash,
            type: 'proposal',
            status: 'confirmed'
          })
        })
```

And proof that the contract is executing and submitting the event via remix monitoring this is what is displayed in the logs section:

```json
[
	{
		"topic": "0x0f93869514c094038a841d4b37219d883c25eb7ca32c22a3079a2943a2ae8051",
		"event": "LogProposal",
		"args": [
			"Test Proposal D",
			"0x6164353130343536623463366537336661303261616239333664353337363265",
			"0x14845928d240dd3c9ec9f030106905f79edb549d"
		]
	}
]
```

All of this was working until I redeployed the contract.   My only guess is that somehow there is a disconnect between the contract and the event listener, but I can't determine a way to validate that.  Based on the remix monitoring of the chain it is properly using the new version of the contract at the new address.

**Comment by nivida** [comment]
Does this error still occur with the latest version of Web3?

**Comment by nivida** [comment]
Closed due to the inactivity of the creator of this issue.
