### ISSUE TITLE
filtering 'getPastEvents' for a specific event does not work

### ISSUE THREAD

**Issue by raduuu2k7** [ethereum/web3.js#1379]
when trying to filter for a specific event, it returns all the records for it, ignoring the filter:

`contract.getPastEvents('EventName',{
         filter: {transactionHash: '0xad8aa9241fda2fc6cd3793bdfd66dc2646763f3638f15584414334b4ed8d33f2'            
            }, 	
    fromBlock: 0,
    toBlock: 'latest'	
}, `

web3 1.0.0-beta.30

**Comment by buhrmi** [comment]
Having the same issue. getPastEvents seems to ignore the `filter` option.

**Comment by atomixxx2** [comment]
Same issue here, using 1.0.0.beta30, filter is not being considered, both with and without "allEvents"

**Comment by Freydal** [comment]
I'm having a similar issue.  I was digging into web3-core-method.  I thought perhaps that should be handling it somewhere within buildCall.  I'm still descending the rabbit hole.

**Comment by buhrmi** [comment]
Looks like filters on allEvents are simply not supported. Need to build your own `topics` array. Also, filters on single events won't work if the parameter is not indexed. That was the problem for me.

**Comment by Freydal** [comment]
I guess my issue was slightly different.  My contract doesn't have any other event types for me to know if it is filtering by event type.  My issue is fromBlock always seems to behave as if it is from block 0.  If i do fromBlock of the current most recent block I still get all of the historical events.

**Comment by freezepro** [comment]
Interesting, as I cant get any from getPastEvents, are you reading local node via http, or infura(http or webservice)?

**Comment by geeogi** [comment]
Are your event parameters 'indexed'? This code is working for me using Infura WS Ropsten: 
```
registry.getPastEvents('myEvent', {
  filter: {myIndexedParameter: _value},
  fromBlock: 0,
  toBlock: 'latest'
})
.then(function(events){
  console.log(events)
})
.catch(function(e) { throw new Error(e) })
```

**Comment by nivida** [comment]
@raduuu2k7 Are your event parameters 'indexed'?

**Comment by prashantprabhakar** [comment]
@nivida I am having the same issue when trying to apply filter on indexed params.
**Event**: `event Transfer(address indexed from, address indexed to, uint tokens);`

Code to get events:
```
var filter = {  'to': '0x693732204104A6e0e636844C85e021d25306A6Cc'}
var pastTransferEvents = contractInstance.getPastEvents('Transfer', filter, {fromBlock: 190, toBlock: 'latest'})
pastTransferEvents.then(events => {
  console.log(events)
}).
```

This still returns me all the transactions with different to addresses.

Response of above code:
```
[ { address: '0x72576Bf9f96165381231ba65B803540ACBB23230',
    blockNumber: 200,
    transactionHash: '0xbe76a89ef88f6682d132ff765b757a8cdcfa1d1a3f72c1890aef4581367b3b7c',
    transactionIndex: 0,
    blockHash: '0xf4d9c5e63c28ca8d7ff3a2be34620cc8140f8c13d10ba34073322dcca73bbb34',
    logIndex: 0,
    removed: false,
    id: 'log_732281d2',
    returnValues: 
     Result {
       '0': '0x0E37Fb8dFF427f5a2ed75D311e818E1Eab924a74',
       '1': '0x693732204104A6e0e636844C85e021d25306A6Cc',
       '2': '16',
       from: '0x0E37Fb8dFF427f5a2ed75D311e818E1Eab924a74',
       to: '0x693732204104A6e0e636844C85e021d25306A6Cc',
       tokens: '16' },
    event: 'Transfer',
    signature: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    raw: 
     { data: '0x0000000000000000000000000000000000000000000000000000000000000010',
       topics: [Array] } },
  { address: '0x72576Bf9f96165381231ba65B803540ACBB23230',
    blockNumber: 208,
    transactionHash: '0x57d09b85455836139672e55e4e91d79d160023fcb5f13436f0669e8025ddd6e2',
    transactionIndex: 0,
    blockHash: '0x8adbc2d9fc3d487d436c18e1be94c1874f759c592abff9c346dde87bc8f9cad4',
    logIndex: 0,
    removed: false,
    id: 'log_3824029d',
    returnValues: 
     Result {
       '0': '0x0E37Fb8dFF427f5a2ed75D311e818E1Eab924a74',
       '1': '0x6eff1193545f1234afe5069D9bdE071Bc10D18CD',
       '2': '12',
       from: '0x0E37Fb8dFF427f5a2ed75D311e818E1Eab924a74',
       to: '0x6eff1193545f1234afe5069D9bdE071Bc10D18CD',
       tokens: '12' },
    event: 'Transfer',
    signature: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    raw: 
     { data: '0x000000000000000000000000000000000000000000000000000000000000000c',
       topics: [Array] } } ]
```

**Comment by Mizumaki** [comment]
@prashantprabhakar 
I think your code to get events is wrong.

You should write like this.
```
var filter = {  'to': '0x693732204104A6e0e636844C85e021d25306A6Cc'}
var pastTransferEvents = contractInstance.getPastEvents('Transfer', { filter, fromBlock: 190, toBlock: 'latest'})
```

Filter option should be in the option object. 
https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#getpastevents

And in my web3 "^1.0.0-beta.35", filtering is working correctly.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.

**Comment by crazyrabbitLTC** [comment]
Was this ever solved?

**Comment by LuisNeves05** [comment]
When using getPastEvents with 'allEvents', the filter still gets ignored
