### ISSUE TITLE
returning int16[] invalid return type

### ISSUE THREAD

**Issue by James-Sangalli** [ethereum/web3.js#1382]
Hi,

I have been quering via rpc a node to enquire about a balance which is coded to be an array of int16.

The data which is returned from this call is: data	String	"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000"	

The balance should be zero for that address. 

When I go to decode the parameter using: web3.eth.abi.decodeParameter('int16[]', '\(data)')

i get back that the return type is invalid.

any idea why this might be? 

Thanks,
James

**Comment by chankruze** [comment]
I think issue is with functions first parameter 'int16[]'. Do check https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#decodeparameter

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
