### ISSUE TITLE
bluebird warnings about promises not being returned

### ISSUE THREAD

**Issue by mdcoon** [ethereum/web3.js#1386]
My D-App runs extremely slow because of the many interactions I am making with web3js from redux-saga. Here are versions:

web3js: 1.0.0-beta.30,
redux-saga: 1.0.0-beta.0,
redux: 3.7.2

For some reason, when I call any web3js function from inside a saga "yield call(...)", bluebird spews warnings "Warning: a promise was created in a handler but was not returned from it". There are literally thousands of these being spewed at runtime when I interact with web3js for anything including getting accounts, balances, blocks, transactions, anything. I tried disabling the warning per bluebird's docs and it doesn't work. It says configuration is reset for each instance of bluebird, so I'm guessing web3js has its own instantiation internally with its own config. So either we need a way to turn off the warnings or we need to get to the bottom of why redux-saga doesn't play well with web3js 1.0.

**Comment by DiscRiskandBisque** [comment]
Have you tried implementing #1415 ? I had this same issue and swapping out `any-promise` for `bluebird` got rid of the warnings.
