### ISSUE TITLE
Address String Case Inconsistencies

### ISSUE THREAD

**Issue by mdcoon** [ethereum/web3.js#1395]
It is extremely frustrating to use contract and account addresses in maps only to find that the case of the address string is being changed internally by web3js. For example, even when I set the address on a contract to normalized string/case format, it is changed immediately to a random case! Some upper and some lower case characters. So when I go to lookup a contract by its address in my redux state tree, for example, it doesn't match causing hours of head banging. Either do not change the case as I set it in the options, or always apply normalization addresses of any kind to upper or lower case.

**Comment by kmturley** [comment]
I am having the same issue. You can replicate with web3 1.0.0-beta.30:
```
pragma solidity ^0.4.17;
contract Example {
  function getAddress() public view returns (address) {
    return msg.sender;
  }
}
```

and then in JavaScript using web3:
```
this.web3.eth.getAccounts((err, accs) => {
  console.log('getAccounts', accs[0]);
  this.example.getAddress().then((id) => {
    console.log('getAddress', id);
  });
});
```

The output I get is:

> getAccounts 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
> getAddress   0x627306090abab3a6e1400e9345bc60c78a8bef57

Very annoying, because I need to match the two addresses together...

**Comment by pubkey** [comment]
Why not just post-convert all addresses to [checksum-format](http://web3js.readthedocs.io/en/1.0/web3-utils.html?highlight=checksum#tochecksumaddress)?

**Comment by kmturley** [comment]
That could be a nice workaround until it's fixed!

Why not have them outputted in the correct format in the first place? I'm checking multiple owners of items directly loaded from the contract, putting them through a conversion step is additional code, would prefer to avoid it!

Especially with Angular, some comparison is done in the templates. Consider the three approaches as code:

toChecksumAddress workaround:
`<span *ngIf="web3.utils.toChecksumAddress(item.owner)==web3.utils.toChecksumAddress(ethService.account.id)">Owner</span>`

toUpperCase workaround:
`<span *ngIf="item.owner.toUpperCase()==ethService.account.id.toUpperCase()">Owner</span>`

Web3 changes the library:
`<span *ngIf="item.owner==ethService.account.id">Owner</span>`

I know which solution makes the most sense to me :)

**Comment by leberknecht** [comment]
Does anyone know _why_ this conversion to mixed-case is happening? Is there any benefit from that?

**Comment by pubkey** [comment]
@leberknecht it is a checksumed address.

**Comment by leberknecht** [comment]
For the logs: found more details here: https://ethereum.stackexchange.com/questions/267/why-dont-ethereum-addresses-have-checksums :)
