### ISSUE TITLE
How to get return value by contract function 

### ISSUE THREAD

**Issue by zhubin123** [ethereum/web3.js#1397]
I have some problems when I get return value by contract function.
In my contract, a function like this:

function myFunction() public constant returns(string myString) {
        return "Hello";
    }

,then In my web3,I use like this:

myContract.methods.myFunction().call({
                        from: '0xC0f517b443A2a53014fAF5F53373821b277b6714',
                    }, function(error, result){
                        console.log ( result);
                    });

but the result is always "",not the "Hello",So how do I do,thanks

**Comment by bisratyalew** [comment]
There is a logical error in your solidity contract. on your code you said you will return a (string myString) but you are returning undeclared string. So you have two options.
1.
`function myFunction() public constant returns(string) {
    return "Hello";
}
`

or 2.
`function myFunction() public constant returns(string myString) {
    var myString = "Hello";
    return myString;
}
`
