### ISSUE TITLE
Typescript types don't match function signatures

### ISSUE THREAD

**Issue by epheph** [ethereum/web3.js#1400]
The types provided in 1.0.0-beta.30 do not match the underlying javascript. As an example.

Web3.eth.accounts has this type:
```
export declare class Eth {
  accounts: {
    signTransaction(tx: Tx, privateKey: string, returnSignature?: boolean, cb?: (err: Error, result: string | Signature) => void): Promise<string> | Signature
```

but has this implementation:
```
function signTransaction(tx, privateKey, callback)
```

and returns Promise of:`{ messageHash, v, r, s, rawTransaction }`, not `string`

There's other issues, too, like no type for `Web3.eth.accounts.create()`

I'm unblocked by using without types (`const Web3 = require('web3');`), but getting types working with Web3 1.0 would be great.

**Comment by hodlbank** [comment]
Also soliditySha3 has type 
`soliditySha3(val: string): string` but in javascript implementation and reference documentation it can accept many parameters with various types.

**Comment by hodlbank** [comment]
Also Web3.utils.toWei() does not understand unit "gwei" in type definition, but does in implementation.

**Comment by seunlanlege** [comment]
I just ran into this very confusing bug. I depend heavily on typescript type definitions, @nivida do you need any help fixing this?

**Comment by nivida** [comment]
@seunlanlege We are currently adding the typings directly to the web3.js repository (thanks @joshstevens19) currently they are maintained in the DefinitelyTyped repository. Maybe you can help him to write all typings :)

**Comment by lucashenning** [comment]
I was just about to create an issue when I found this. I can confirm the buggy return type. 

`web3.eth.accounts.signTransaction(tx,privateKey)` returns `Promise<{ messageHash, v, r, s, rawTransaction }>`, not `string`

The following code works perfectly but `signedTx.rawTransaction` throws a type error during typescript compilation. 

```
let signedTx = await web3.eth.accounts.signTransaction(tx,privateKey);
web3.eth.sendSignedTransaction(signedTx.rawTransaction)
```

**Comment by joshstevens19** [comment]
good spot i will fix this tomorrow for you @lucashenning, can you create a issue for this please.

**Comment by joshstevens19** [comment]
@lucashenning PR is up - https://github.com/ethereum/web3.js/pull/2217 👍

**Comment by winterowolf** [comment]
web3.eth.accounts.wallet - i can't figure that class.
in docs - https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#wallet - there is length
in git - https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-accounts/src/models/Wallet.js - there is accountsIndex 
in typings - there nothing except methods
