### ISSUE TITLE
Side effects on some methods like estimateGas

### ISSUE THREAD

**Issue by ianaya89** [ethereum/web3.js#1402]
I figured out that when I called the `estimateGas` method,  the `inputFormatter`  is called and changed the values of the estimateGas's `params` object. 

It's great to convert and cast values to make the method work but I think will be better to make a local copy of `params` instead of updating the given reference and avoid introducing side effects to web3 functions.

For instance, if I have a `value` property in `params` and the value is in `wei` after `estimateGas` ends the original `params` reference is updated and `value` will be cast to hex.

### `estimateGas()` => Gets a `params` object.

```javascript
// web3.js/packages/web3-eth/src/index.js
    var estimateGas = new Method({
        name: 'estimateGas',
        call: 'eth_estimateGas',
        params: 1,
        inputFormatter: [formatters.inputCallFormatter],
        outputFormatter: utils.toDecimal
    });
```

### `inputCallFormatter()` => Updates given `params` reference.

```javascript
// web3.js/packages/web3-core-helpers/src/formatters.js

var inputCallFormatter = function (options){

    var from = options.from || config.defaultAccount;

    if (from) {
        options.from = inputAddressFormatter(from);
    }

    if (options.to) { // it might be contract creation
        options.to = inputAddressFormatter(options.to);
    }

    ['gasPrice', 'gas', 'gasLimit', 'value', 'nonce'].filter(function (key) {
        return options[key] !== undefined;
    }).forEach(function(key){
        options[key] = utils.fromDecimal(options[key]);
    });

    return options;
};
```

Not sure if you are intentionally doing this. If not, I can work on PR to find this kind of patterns and 
avoid side effects in web3 methods.

**Comment by gburtini** [comment]
I vote in favor of you creating that PR. Mutating inputs is an antipattern.

**Comment by nivida** [comment]
This got fixed during the refactoring. Please update to the latest version of Web3.js. (1.0.0-beta.51).
