### ISSUE TITLE
event's returnValue is null instead of false

### ISSUE THREAD

**Issue by congxinUSC** [ethereum/web3.js#1403]
I'm not totally sure if this is a solidity issue or a web3 issue. I'm using 1.0.0-beta.29 (got same result on beta.30) over testrpc.

In my solidity contract, I set an event like this to check if some non-constant successfully run or failed:
`event opDone(bool indexed _isSet);`
Then in some function I used it like this:
```
function setRecord(address _target, string _record) public {
        if(!rights[_target][msg.sender]) {
            opDone(false);
            return;
        }
        User storage _usr = userList[_target];
        _usr.recordIndices.push(recordCount);
        records[recordCount] = _record;
        recordCount++;
        rights[_target][msg.sender] = false;
        opDone(true);
    }
```
On the JavaScript side, I called the function and captured the event like this:
```
contractInstance.methods.setRecord(target, encrypted.cipher).send({
      from: accountAddress,
      gas: '1500000'
    }).on('transactionHash', (hash) => {
      console.log('hash: ' + hash);
    }).on('confirmation', (confirmationNumber, receipt) => {
      console.log(res.json(receipt.events));
    }).on('error', console.error);
```
When the event's returnValue is true, everything seems to be fine, but if it's false (or when it should be), I got the event like this:
```
{
    "opDone": {
        "logIndex": 0,
        "transactionIndex": 0,
        "transactionHash": "0xbce295310aacd114b36474aa9a8dff199460c8af5bb2c6c8ce6f8ffd85006ba5",
        "blockHash": "0x71ce77af33ed7f601c6035f432200c8de75d8f6818fd42870541ae220920d6fa",
        "blockNumber": 8,
        "address": "0x307dcF18755ED7746CA33E70d1B8656fBe2DcA5A",
        "type": "mined",
        "id": "log_5fd6bfb4",
        "returnValues": {
            "0": null,
            "_isSet": null
        },
        "event": "opDone",
        "signature": "0xd02ea5da3b63612ae7b8f9b8708ebd07566a19a447b98061c09b4b6a9ac7de9b",
        "raw": {
            "data": "0x0",
            "topics": [
                "0xd02ea5da3b63612ae7b8f9b8708ebd07566a19a447b98061c09b4b6a9ac7de9b",
                "0x0000000000000000000000000000000000000000000000000000000000000000"
            ]
        }
    }
}
```
You can see that not only my return value (_isSet) itself looks weird, the index become null, too.
I'm not sure if it's a bug or some environment specific problem or maybe just my own fault. I know event subscription doesn't work while using http provider but I think it's okay just getting return values from an event.
BTW can anyone tell me how to test event subscription without connecting to a real chain? For example is there some "testipc" stuff? Thanks a lot if you can provide any help!

**Comment by rossng** [comment]
I have the same problem - `false` values in events are returned as `null`s.

**Comment by jchen86** [comment]
Same problem here. I'm using 1.0.0-beta.33 and parity 1.10.0.

**Comment by jchen86** [comment]
PR raised #1627

**Comment by nivida** [comment]
I tested it with 1.0.0-beta.34 and my local testrpc. 

I created this contract method: 
```
function addUser() public {
        users[msg.sender].user.isActive = true;
        usersCount++;

        emit UserAdded(false);
} 
```

Called it with this JS: 
```
contract.methods['addUser']().send({
        from: addressFromAccount,
        gas: gasAmount,
        gasPrice: gasPrice
}).on('confirmation', function(confirmationNumber, receipt){
        console.log(receipt);
});
``` 

This was the response: 

``` json 
{
  "UserAdded":
    {
      "logIndex": 0,
      "transactionIndex": 0,
      "transactionHash": "0xef81c4b5256c982e083c5100f941d5b92eb8b11c79d6bf898a4701e6d4cd79dc",
      "blockHash": "0xc751982e2aa09a43925117aa00b7f06cf1f0a766e85dc181fcc16bb7f8eaf06c",
      "blockNumber": 32,
      "address": "0x8ACEe021a27779d8E98B9650722676B850b25E11",
      "type": "mined",
      "id": "log_116423b7",
      "returnValues": {
        "0": false,
        "testingBoolean": false
      },
      "event": "UserAdded",
      "signature": "0x6d160ec14baac55bfc8421ebcc8f85b984e3350ae28d89a3f43a7e6b304d89e0",
      "raw": {
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "topics":["0x6d160ec14baac55bfc8421ebcc8f85b984e3350ae28d89a3f43a7e6b304d89e0"]
      }
    }
}
```

As you can see it works for me. Can you perhaps give me some more details?

**Comment by jchen86** [comment]
Hi @nivida 

I'm using web3-1.0.0-beta.33
contract compiled using solidity 0.4.24

contract code
```
pragma solidity ^0.4.21;

contract DemoContract {
    event BooleanEvent(bool value);

    function emitFalse() public {
        emit BooleanEvent(false);
    }
}
```

js
```javascript
contract.methods.emitFalse()
  .send({ from: fromAddress })
  .on('confirmation', function (confirmationNumber, receipt) {
    // prints {"0":null,"value":null}
    console.log(JSON.stringify(receipt.events.BooleanEvent.returnValues))
    process.exit(0)
  })
```

Please see https://github.com/jchen86/web3.js-1403

This unit test does not pass on the 1.0 branch
https://github.com/ethereum/web3.js/pull/1627/files#diff-4dcec647a69c036c21b28389578ec59c

Thanks!

**Comment by nivida** [comment]
Thank you for your reply. With the new ABI library the issue will be solved. 
So i will close your PR and reference the other Issue (https://github.com/ethereum/web3.js/issues/1241) here.

**Comment by nivida** [comment]
The new ABICoder implementation is merged and this issue will be solved in the next release.
