### ISSUE TITLE
I want the web3.js module which version is greater than 1.0

### ISSUE THREAD

**Issue by INTERESTING-OMG** [ethereum/web3.js#1405]
I can install the web3.js by npm install web3@^0.20.0. However, I need 1.0 to use the API. Can someone mail me the 1.0 mudule ? Thanks! wmm930426@gmail.com

**Comment by hodlbank** [comment]
`npm install web3` should give you version 1.0.0-beta.30 .

**Comment by INTERESTING-OMG** [comment]
@hodlbank I tried and failed......

PS D:\blockchain\temp> npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated
> scrypt@6.0.3 preinstall D:\blockchain\temp\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install D:\blockchain\temp\node_modules\scrypt
> node-gyp rebuild


D:\blockchain\temp\node_modules\scrypt>if not defined npm_config_node_gyp (node "D:\note\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\note\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
D:\blockchain\temp\node_modules\scrypt\build\..\scrypt\win\include\config.h
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
D:\blockchain\temp\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: 未找到导入的项目“D:\Microsoft.Cpp.Defau
lt.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
D:\blockchain\temp\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: 未找到导入的项目“D:\Microsoft.Cpp.Def
ault.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\note\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\note\\node.exe" "D:\\note\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\blockchain\temp\node_modules\scrypt
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\blockchain\temp\package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2018-03-01T00_17_03_079Z-debug.log
PS D:\blockchain\temp>

**Comment by wendy2003888** [comment]
Could you check your system path variable (%PATH%) of C++ and retry 
`npm install > web3@1.0.0-beta.30`

**Comment by INTERESTING-OMG** [comment]
@wendy2003888 There is no C++ in my system path, Which C++ version to install ?

**Comment by INTERESTING-OMG** [comment]
@wendy2003888
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Server 5.7\bin;%MAVEN_HOME%\bin;%JAVA_HOME%\bin;D:\svn\bin;D:\tortoiseGit\bin;D:\note\;D:\Git\bin;D:\Geth;D:\gradle-4.5.1\bin;C:\Python27;

**Comment by wendy2003888** [comment]
I am not sure it's c++ or node.js, I am thinking you should check your system path variables both for gcc/g++ and NODE_PATH. 

According to the following error log, I think your env is not set properly.

`D:\blockchain\temp\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: 未找到导入的项目“D:\Microsoft.Cpp.Defau
lt.props”。请确认 声明中的路径正确，且磁盘上存在该文件。`

I think you could try these solutions:
https://github.com/AlexeyKupershtokh/node-v8-clone/issues/7
https://stackoverflow.com/questions/18774929/npm-install-g-karma-error-msb4019-the-imported-project-c-microsoft-cpp-defau
https://stackoverflow.com/questions/16092169/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-progr

I am using Linux and Mac OS, so the above advice is just for your reference.  Hope you can figure out quickly. : )

**Comment by INTERESTING-OMG** [comment]
@wendy2003888 I hava to say I failed again.

**Comment by wendy2003888** [comment]
@INTERESTING-OMG  How about try to search that error on Google and find more possible solutions? I guess there will be one that works.
try these keywords: `node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019`

P.S. If you are in an area blocking Google, plz try to use a VPN.
