### ISSUE TITLE
0.20.4: Missing filtered events on mainnet Chrome only

### ISSUE THREAD

**Issue by wjmelements** [ethereum/web3.js#1406]
The events filter correctly on Firefox and on Rinkeby, but not on mainnet + Chrome. On mainnet+Chrome I only get one event instead of two. You can see this issue live at finneyvote.com; only the first proposal is visible.

Here are the filter options:
```
{topics: Array(1), from: undefined, to: undefined, address: "0x000000002bb43c83ece652d161ad0fa862129a2c", fromBlock: "0x4ee93f", …}
address
:
"0x000000002bb43c83ece652d161ad0fa862129a2c"
from
:
undefined
fromBlock
:
"0x4ee93f"
to
:
undefined
toBlock
:
"latest"
topics
:
["0xd721fc4b71111225bba131141f013ef3e3956654b0eade3c9e9f611f0d93b551"]
__proto__
:
Object
```

I am using filter.watch, but on mainnet+Chrome there is still only one event if I do filter.get. Of course this could also be an issue with INFURA, but the browser-specificity leads me to suspect web3.

**Comment by wjmelements** [comment]
The web3.version on both Firefox and chrome for their injected web3 from metamask is `0.20.4`

**Comment by wjmelements** [comment]
Expected events: https://etherscan.io/tx/0x6c3b1d133e347b0841c28a26e07f717e9ae6323031fd9c6671008b295b1b2b95#eventlog

**Comment by wjmelements** [comment]
I have a report of 0.20.3 Chrome not experiencing this issue.

**Comment by wjmelements** [comment]
I have two reports of 0.20.3 not experiencing this issue.

**Comment by wjmelements** [comment]
I have also tried these options:
```
{topics: Array(1), from: undefined, to: "pending", address: "0x000000002bb43c83ece652d161ad0fa862129a2c", fromBlock: "0x4ee93f", …}
address
:
"0x000000002bb43c83ece652d161ad0fa862129a2c"
from
:
undefined
fromBlock
:
"0x4ee93f"
to
:
"pending"
toBlock
:
undefined
topics
:
["0xd721fc4b71111225bba131141f013ef3e3956654b0eade3c9e9f611f0d93b551"]
__proto__
:
Object
```

**Comment by wjmelements** [comment]
When I am using web3.version=0.20.3, I am not experiencing the issue anymore. It may be specific to 0.20.4.

**Comment by winwintogether** [comment]
I had also gotten this issue  yesterday. Testnets such as Rinkeby and Ropsten are working well for now.
But web3.js is missing filtered events on mainnet...

**Comment by win2win** [comment]
I'm talking to developers at the conference right now. The metamask has this problems for everyone.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
