### ISSUE TITLE
npm install fail on nodejs Docker build

### ISSUE THREAD

**Issue by stasbar** [ethereum/web3.js#1416]
Hello.
I want to dockerize my nodejs app with web3js dependencies, but I'm facing with error during docker build phase (I'm writing here because without web3js in dependencies it's working fine)

Here is my package.json:
````json
{
  "name": "docker_web_app",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.16.2",
    "web3": "^1.0.0-beta.30"
  }
}
````

Dockerfile:
````yaml
FROM node:carbon
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD [ "npm", "start" ]
````

and here is my `docker build .` output

> Sending build context to Docker daemon  91.14kB
> Step 1/7 : FROM node:carbon
>  ---> 672002a50a0b
> Step 2/7 : WORKDIR /usr/src/app
>  ---> Using cache
>  ---> 17bc8ca34c26
> Step 3/7 : COPY package*.json ./
>  ---> c6fa0684719b
> Step 4/7 : RUN npm install
>  ---> Running in 6df1c1367322
> 
> scrypt@6.0.3 preinstall /usr/src/app/node_modules/scrypt
> node node-scrypt-preinstall.js
> 
> 
> scrypt@6.0.3 install /usr/src/app/node_modules/scrypt
> node-gyp rebuild
> 
> make: Entering directory '/usr/src/app/node_modules/scrypt/build'
>   SOLINK_MODULE(target) Release/obj.target/copied_files.node
>   COPY Release/copied_files.node
>   CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
>   CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
>   CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
>   CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
>   AR(target) Release/obj.target/scrypt_wrapper.a
>   COPY Release/scrypt_wrapper.a
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
>   CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
>   AR(target) Release/obj.target/scrypt_lib.a
>   COPY Release/scrypt_lib.a
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
> In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
>                  from ../src/node-boilerplate/scrypt_params_async.cc:4:
> ../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
> ../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>        callback->Call(1, argv);
>                              ^
> ../src/node-boilerplate/scrypt_params_async.cc: In member function 'virtual void ScryptParamsAsyncWorker::HandleOKCallback()':
> ../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>    callback->Call(2, argv);
>                          ^
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
> In file included from ../src/node-boilerplate/inc/scrypt_kdf_async.h:28:0,
>                  from ../src/node-boilerplate/scrypt_kdf_async.cc:4:
> ../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
> ../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>        callback->Call(1, argv);
>                              ^
> ../src/node-boilerplate/scrypt_kdf_async.cc: In member function 'virtual void ScryptKDFAsyncWorker::HandleOKCallback()':
> ../src/node-boilerplate/scrypt_kdf_async.cc:28:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>      callback->Call(2, argv);
>                            ^
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_sync.o
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_sync.o
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_async.o
> In file included from ../src/node-boilerplate/inc/scrypt_kdf-verify_async.h:28:0,
>                  from ../src/node-boilerplate/scrypt_kdf-verify_async.cc:4:
> ../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
> ../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>        callback->Call(1, argv);
>                              ^
> ../src/node-boilerplate/scrypt_kdf-verify_async.cc: In member function 'virtual void ScryptKDFVerifyAsyncWorker::HandleOKCallback()':
> ../src/node-boilerplate/scrypt_kdf-verify_async.cc:30:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>    callback->Call(2, argv);
>                          ^
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_sync.o
>   CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_async.o
> In file included from ../src/node-boilerplate/inc/scrypt_hash_async.h:28:0,
>                  from ../src/node-boilerplate/scrypt_hash_async.cc:28:
> ../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
> ../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>        callback->Call(1, argv);
>                              ^
> ../src/node-boilerplate/scrypt_hash_async.cc: In member function 'virtual void ScryptHashAsyncWorker::HandleOKCallback()':
> ../src/node-boilerplate/scrypt_hash_async.cc:52:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
>    callback->Call(2, argv);
>                          ^
>   CXX(target) Release/obj.target/scrypt/scrypt_node.o
>   SOLINK_MODULE(target) Release/obj.target/scrypt.node
>   COPY Release/scrypt.node
> make: Leaving directory '/usr/src/app/node_modules/scrypt/build'
> 
> sha3@1.2.0 install /usr/src/app/node_modules/sha3
> node-gyp rebuild
> 
> make: Entering directory '/usr/src/app/node_modules/sha3/build'
>   CXX(target) Release/obj.target/sha3/src/addon.o
> ../src/addon.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)':
> ../src/addon.cpp:59:58: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.9.4/include/node/v8.h:3831): Use maybe version [-Wdeprecated-declarations]
>     info.GetReturnValue().Set(cons->NewInstance(argc, argv));
>                                                           ^
>   CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
>   CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
>   CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
>   CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
>   SOLINK_MODULE(target) Release/obj.target/sha3.node
>   COPY Release/sha3.node
> make: Leaving directory '/usr/src/app/node_modules/sha3/build'
> 
> websocket@1.0.24 install /usr/src/app/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)
> 
> make: Entering directory '/usr/src/app/node_modules/websocket/build'
>   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
>   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
>   COPY Release/bufferutil.node
>   CXX(target) Release/obj.target/validation/src/validation.o
>   SOLINK_MODULE(target) Release/obj.target/validation.node
>   COPY Release/validation.node
> make: Leaving directory '/usr/src/app/node_modules/websocket/build'
> npm WARN docker_web_app@1.0.0 No repository field.
> npm WARN docker_web_app@1.0.0 No license field.
> 
> added 297 packages in 29.413s
> Removing intermediate container 6df1c1367322
>  ---> b4cf643ecbd8
> Step 5/7 : COPY . .
>  ---> f9ec526c6023
> Step 6/7 : EXPOSE 8080
>  ---> Running in ac13c9885593
> Removing intermediate container ac13c9885593
>  ---> 91f892107c77
> Step 7/7 : CMD [ "npm", "start" ]
>  ---> Running in 2d4cd40185fd
> Removing intermediate container 2d4cd40185fd
>  ---> 6eb3b003f9c7
> Successfully built 6eb3b003f9c7

same error on 
FROM node:latest
and node:boron

**Comment by iurimatias** [comment]
@stasbar what's the actual error? the output seen is typical of compiling issue with scrypt, I suggest you try installing that first and solving any dependencies, then re-try web3 as the dependency

**Comment by Trycoder** [comment]
Hi ,
Even I have the same issue.I have dockerized my node js app without web3.It is working fine.But when i add the following line of code the docker application exits without running.
const Web3 = require('web3');

However I need web3 for further process.

**Comment by lucashenning** [comment]
@Trycoder @stasbar did you have any luck solving this issue? 

This is a pretty big deal, it seems like it's not possible to create a working docker image of a nodeJS app that contains web3. My app works fine in my local env and as a NPM package but `npm install` fails in docker. 

I tried the following versions:
web31.0.0-beta.34
web31.0.0-beta.36
web31.0.0-beta.38
web31.0.0-beta.41

### Docker File:
```
FROM node:10.15.0

# Create Directory for the Container
WORKDIR /app

# Copy the files we need to our new Directory
ADD . /app

# Expose the port outside of the container
EXPOSE 4000

# Grab dependencies and transpile src directory to dist
RUN npm i

# Start the server
CMD npm run dev
```

### Error log:
Scrypt is throwing actual errors, not the usual warnings.
```
> scrypt@6.0.3 preinstall /app/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /app/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/app/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h: In constructor 'NodeScrypt::Params::Params(const v8::Local<v8::Object>&)':
../src/node-boilerplate/inc/scrypt_common.h:39:63: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /root/.node-gyp/10.15.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.15.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/root/.node-gyp/10.15.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.15.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:63: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /root/.node-gyp/10.15.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.15.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/root/.node-gyp/10.15.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.15.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:63: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
                                                               ^
In file included from /root/.node-gyp/10.15.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.15.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/root/.node-gyp/10.15.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.15.0/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1674:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
```

**Comment by Trycoder** [comment]
Adding the following lines in my docker file solved my issue:
RUN apk update && apk upgrade && 
apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

And my docker file looks like this:
FROM node:8.11.1-alpine
RUN apk update && apk upgrade && 
apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN npm install
RUN npm install pm2 -g
WORKDIR /usr/src/app
EXPOSE 8080
CMD [ "pm2-runtime","start","ecosystem.config.js","--only","dev" ]

**Comment by Garoth** [comment]
Thanks @Trycoder -- same issue with alpine/node, same solution to update everything + install kerberos libs manually. Good job figuring this out
