### ISSUE TITLE
I installed web3 on Windows 10, successed, but everything is undefined

### ISSUE THREAD

**Issue by xiongzhend** [ethereum/web3.js#1419]
after I installed, I create a test.js file, and input as follow:

`var Web3 = require('web3');
// create an instance of web3 using the HTTP provider.
// NOTE in mist web3 is already available, so check first if it's available before instantiating
var web3 = new Web3();
web3.setProvider(new Web3.providers.HttpProvider("http://localhost:8545"));

var version = web3.version.api;
console.log(version); // "0.2.0"`

and I tried many functions all of them return undefined

**Comment by gburtini** [comment]
You have not provided enough information to gleen any insight on what has gone wrong. Specifically, everything you've provided appears to work correctly: can you give us an example of a function that you think should work, but does not?

**Comment by macbem** [comment]
You probably don't have any build system in place so when you run web3.js from your browser, it isn't injected by `require` and the rest of the code, quite obviously, can't work.  It should work from Node.js though.

**Comment by iurimatias** [comment]
@xiongzhend do you have a node at localhost:8545? what functions are returning undefined? is the Web3 object defined or injected in some way?

**Comment by albomo** [comment]
Any updates on it?
Have the same problem

**Comment by xiongzhend** [comment]
sorry, guys, I don't know why I asked this question, it seems all good now, maybe is because I didn't open the node on localhost:8545
