### ISSUE TITLE
can't install web3 

### ISSUE THREAD

**Issue by helderjnpinto** [ethereum/web3.js#1420]
npm --version
5.6.0
nodejs --version
v8.9.4

**Comment by slesolliec** [comment]
Any error message?

**Comment by gburtini** [comment]
@helderjnpinto Can you please provide some context? What do you believe has gone wrong? What evidence leads you to conclude you cannot install web3?

**Comment by iurimatias** [comment]
@helderjnpinto can you provide the log or some more context?
