### ISSUE TITLE
How to get web3-eth-accounts.js? Where is the dist folder containing web3-eth-accounts.js? 

### ISSUE THREAD

**Issue by buleflw** [ethereum/web3.js#1424]
After npm install web3-eth-accounts, I'd try npm run-script build-all at node_modules/web3/.

/node_modules/web3# ls
bower.json  example      lib           package-init.js  package-lock.json
circle.yml  gulpfile.js  LICENSE       package.js       README.md
dist        index.js     node_modules  package.json     styleguide.md

/node_modules/web3# npm run-script build-all
npm ERR! missing script: build-all

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-05T01_52_14_418Z-debug.log

/node_modules/web3/dist# ls
web3.js  web3.js.map  web3-light.js  web3-light.min.js  web3.min.js

/node_modules/web3-eth-accounts# ls
node_modules  package.json  package-lock.json  README.md  src

**Comment by nivida** [comment]
Please ask this on https://ethereum.stackexchange.com/
