### ISSUE TITLE
In what way I can get all calls and transactions for any address (in the ethereum blockchain) with web3.js? Or in what way I can get it at all?

### ISSUE THREAD

**Issue by kalash2294** [ethereum/web3.js#1426]
In what way I can get all calls and transactions for any address (in the ethereum blockchain) with web3.js?
Or in what way I can get it at all?

**Comment by mxito3** [comment]
i want to know too

**Comment by nivida** [comment]
Duplicated issue and currently not supported. Please have a look at QuickBlocks and this issue https://github.com/ethereum/web3.js/issues/580
