### ISSUE TITLE
Invalid JSON RPC reponse ""

### ISSUE THREAD

**Issue by rayeaster** [ethereum/web3.js#1431]
We recently got a frequent [Invalid JSON RPC reponse ""] from web3js library and the whole app then crash, no matter using local parity or infura node. However, local parity node seems more stable on this issue. seems the web3 library get some bug in eth_getBlockByNumber which might return empty string. Not sure if it is the real culprit. we are testing on kovan.

**Comment by ghost** [comment]
Note that this issue has been addressed by the recent PR #5179 to replace the broken xhr2-cookies for the modern [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API.
