### ISSUE TITLE
 connect to main network of ethereum to transfer coins.

### ISSUE THREAD

**Issue by mxito3** [ethereum/web3.js#1432]
how to call functions of contract in main network of ethereum in my codes using web3.js?i want to connect to it then transfer my own coin.

**Comment by mxito3** [comment]
my coin contract had been in ethereum block.

**Comment by lakshmankashyap** [comment]
same here in web3 beta version

**Comment by williamchong007** [comment]
have you try creating a `contract` object, then calling its `methods` ?
https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html

**Comment by nivida** [comment]
Please ask on https://ethereum.stackexchange.com/
