### ISSUE TITLE
web3.js replaces response object. should just add to the map

### ISSUE THREAD

**Issue by 1blockologist** [ethereum/web3.js#1433]
web3 1.0.0 asynchronous calls replace a variable "res". This is a common variable name for other methods, for example with express router.

Upon returning a web3 asynchronous method, or a promise, the res variable will have been overwritten and missing expected methods. This will be counterintuitive to some.

The current solution is for the user to not use the variable named 'res' as a function variable. I think web3 should not interfere if the variable exists, or should add its methods to an existing res variable, perhaps in a web3 sub object.

**Comment by nivida** [comment]
@1blockologist Thanks for submitting this issue but could you please add a example to reproduce this behavior? :-)
