### ISSUE TITLE
web3.eth undefined

### ISSUE THREAD

**Issue by sathyamlokare** [ethereum/web3.js#1441]
`var web3 = require('web3');
`
when I say web3.eth or web3.Eth it says undefined.
Why is that so ?

**Comment by slesolliec** [comment]
Could you please open an issue that would make more sense?

You write "when I say web3.eth" ... are you talking to your computer?
Could you actually paste your code and explain what you were intending to do, in which context and which platform?

If you open such a fuzzy issue, how do you expect any good willing person to ever be able to help you?

**Comment by sathyamlokare** [comment]
got it fixed.
Instance of web3 was not created. So it said undefined wherever I used it.
