### ISSUE TITLE
no remote found for dependency "ethereum/web3.js@1.0.0-beta.18"

### ISSUE THREAD

**Issue by ayham-madi** [ethereum/web3.js#1444]
Hello 

I am trying to install the ethereum component install ethereum/web3.js with this command 
component install ethereum/web3.js
But I am receiving this 

github remote: 59 of 60 requests remaining, resetting at Sun Mar 11 2018 14:13:30 GMT+0000 (GMT)
github remote: see https://github.com/component/guide/blob/master/changelogs/1.0.0.md#required-authentication for more information.
                  fatal : no remote found for dependency "ethereum/web3.js@1.0.0-beta.18". Visit http://component.github.io/troubleshooting for help.

I couldnt find anything usfull here **http://component.github.io/troubleshooting **

any ideas? 

thanks

**Comment by iurimatias** [comment]
@ayham-madi are you still experiencing this issue?
