### ISSUE TITLE
npmjs doesn't have web3 1.0

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#1454]
Where did it go? I can't install it anymore from npmjs

```
➜   npm view web3@* version
web3@0.2.5 '0.2.5'
web3@0.2.6 '0.2.6'
web3@0.2.7 '0.2.7'
web3@0.2.8 '0.2.8'
web3@0.3.0 '0.3.0'
web3@0.3.1 '0.3.1'
web3@0.3.2 '0.3.2'
web3@0.3.3 '0.3.3'
web3@0.3.4 '0.3.4'
web3@0.3.6 '0.3.6'
web3@0.4.0 '0.4.0'
web3@0.4.1 '0.4.1'
web3@0.4.2 '0.4.2'
web3@0.4.3 '0.4.3'
web3@0.5.0 '0.5.0'
web3@0.6.0 '0.6.0'
web3@0.7.0 '0.7.0'
web3@0.7.1 '0.7.1'
web3@0.8.0 '0.8.0'
web3@0.8.1 '0.8.1'
web3@0.9.0 '0.9.0'
web3@0.9.1 '0.9.1'
web3@0.9.2 '0.9.2'
web3@0.10.0 '0.10.0'
web3@0.11.0 '0.11.0'
web3@0.12.0 '0.12.0'
web3@0.12.1 '0.12.1'
web3@0.12.2 '0.12.2'
web3@0.13.0 '0.13.0'
web3@0.14.0 '0.14.0'
web3@0.14.1 '0.14.1'
web3@0.15.0 '0.15.0'
web3@0.15.1 '0.15.1'
web3@0.15.2 '0.15.2'
web3@0.15.3 '0.15.3'
web3@0.16.0 '0.16.0'
web3@0.18.0 '0.18.0'
web3@0.18.1 '0.18.1'
web3@0.18.2 '0.18.2'
web3@0.18.4 '0.18.4'
web3@0.19.0 '0.19.0'
web3@0.19.1 '0.19.1'
web3@0.20.0 '0.20.0'
web3@0.20.1 '0.20.1'
web3@0.20.2 '0.20.2'
web3@0.20.3 '0.20.3'
web3@0.20.4 '0.20.4'
web3@0.20.5 '0.20.5'
web3@0.20.6 '0.20.6'
```

before if I did `npm install web3 --save` it would install 1.0 beta version

However, I can still do
```
npm install web3@1.0.0-beta.30
```
so the question is : 
1. Where to find the latest release? 
2. How to query npm to see web3 1.0 beta versions? 
3. Why doesn't github releases match the releases on npmjs?

**Comment by Freydal** [comment]
If you cut down your view command to `npm view web3` you can see more information.  One bit of info which can explain what you are experiencing are the timestamps of deployments which are in the time object in the returned json.  

As of a few mins ago:
```
'1.0.0-beta.30': '2018-02-13T11:33:48.515Z',
     '1.0.0-beta.31': '2018-03-13T14:06:49.805Z',
     '0.20.6': '2018-03-13T14:15:51.188Z' },
```
There was a new version of the 0.20 code pushed up very recent.

Hope this helps.

**Comment by rstormsf** [comment]
Yeah, I can see it now. Thank you.
Still curious what happened to the default web3 installation from npm.  Before it would take web3 1.0 as default, now it uses 0.20

**Comment by Freydal** [comment]
I don't know this for a fact, but based on observation I expect that it by default when nothing is specified installs the most recently added version.
