### ISSUE TITLE
Creating a Secure wallet application using web3 js

### ISSUE THREAD

**Issue by sathish76** [ethereum/web3.js#1455]
I'm new to ethereum and geth. I just want to know that my current architecture or solution to make a new Mobile wallet with secure way.
Mobile wallet -> sends private keys over https -> REST API(Node js) -> Web3.js -> Geth JSON RPC (locally available).

is it secure way to develop a wallet or communicating to geth node?
![arch](https://user-images.githubusercontent.com/11909272/37423257-645f277a-27e3-11e8-9037-d383adc6057e.png)

**Comment by nivida** [comment]
Please ask this on https://ethereum.stackexchange.com/
