### ISSUE TITLE
windows 10  install web3  error 

### ISSUE THREAD

**Issue by jeremy16601** [ethereum/web3.js#1457]
npm ERR! code 128
npm ERR! Command failed: D:\cygwin64\bin\git.EXE clone -q https://github.com/frozeman/bignumber.js-nolookahead.git C:\Users\jeremy\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-75611951 --config core.longpaths=true
npm ERR! fatal: Invalid path '/cygdrive/c/Users/jeremy/AppData/Roaming/npm-cache/_cacache/tmp/C:\Users\jeremy\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-75611951': No such file or directory
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jeremy\AppData\Roaming\npm-cache\_logs\2018-03-15T05_44_43_645Z-debug.log

**Comment by iurimatias** [comment]
@jeremy16601 can you provide the complete log?
