### ISSUE TITLE
Whisper invalid id

### ISSUE THREAD

**Issue by REPTILEHAUS** [ethereum/web3.js#1460]
Getting invalid id when running the demo from the web3 whisper docs:

```
Unhandled rejection Error: Returned error: invalid id
    ["./node_modules/web3-core-helpers/src/errors.js"]/module.exports.ErrorResponse@http://localhost:4200/vendor.bundle.js:234107:16
    ["./node_modules/web3-core-requestmanager/src/index.js"]/RequestManager.prototype.send/<@http://localhost:4200/vendor.bundle.js:244399:29
    ["./node_modules/web3-providers-http/src/index.js"]/HttpProvider.prototype.send/request.onreadystatechange@http://localhost:4200/vendor.bundle.js:267084:13
    ["./node_modules/zone.js/dist/zone.js"]/</</wrapFn@http://localhost:4200/polyfills.bundle.js:3152:30
    ["./node_modules/zone.js/dist/zone.js"]/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2407:17
    forkInnerZoneWithAngularBehavior/zone._inner<.onInvokeTask@http://localhost:4200/vendor.bundle.js:68456:24
    ["./node_modules/zone.js/dist/zone.js"]/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2406:17
    ["./node_modules/zone.js/dist/zone.js"]/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:2174:28
    ["./node_modules/zone.js/dist/zone.js"]/</</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:2482:24
    patchEventTarget/invokeTask@http://localhost:4200/polyfills.bundle.js:3503:9
    patchEventTarget/globalZoneAwareCallback@http://localhost:4200/polyfills.bundle.js:3529:17
From previous event:
```
    this.web3.shh.getVersion().then(console.log);

    this.web3.shh.getInfo().then(console.log);

    var identities = [];
    var subscription = null;
    
    Promise.all([
         this.web3.shh.newSymKey().then((id) => {identities.push(id);}),
         this.web3.shh.newKeyPair().then((id) => {identities.push(id);})
    ]).then(() => {
    
        // will receive also its own message send, below
        subscription =  this.web3.shh.subscribe("messages", {
            symKeyID: identities[0],
            topics: ['0xffaadd11']
        }, (err) => console.log )
        .on('data', console.log);
    
    }).then(() => {
        this.web3.shh.post({
            symKeyID: identities[0], // encrypts using the sym key ID
            sig: identities[1], // signs the message using the keyPair ID
            ttl: 10,
            topic: '0xffaadd11',
            payload: '0xffffffdddddd1122',
            powTime: 3,
            powTarget: 0.5
        })
    });
 
```

**Comment by cammellos** [comment]
@REPTILEHAUS I am getting the same, did you find out what the issue was?

**Comment by REPTILEHAUS** [comment]
@cammellos  sorry man, no luck. I believe they are launching v1 soon (soon-ish) and some things will be sorted out.

**Comment by cammellos** [comment]
@REPTILEHAUS we managed to sort it out, the key was not registered in the key store. 

One thing to be noted in your code is that you might be getting into a race condition depending on which promise is resolved first.

```
Promise.all([
     this.web3.shh.newSymKey().then((id) => {identities.push(id);}), // identities[0] or identities[1], depending which one is resolved first
     this.web3.shh.newKeyPair().then((id) => {identities.push(id);})
])

```

You might want to try something on the lines:

```
Promise.all([
     this.web3.shh.newSymKey(),
     this.web3.shh.newKeyPair()
]).then(([symKey, keypair])) => {

})
```

Good luck!

**Comment by REPTILEHAUS** [comment]
Awesome, thanks man, I'll try this out for sure when I get back around to playing with it

**Comment by nivida** [comment]
Closed due to inactivity of the creator. Feel free to open a new issue if the error still occurs.
