### ISSUE TITLE
Disable caching of eth_call requests

### ISSUE THREAD

**Issue by melnikaite** [ethereum/web3.js#1463]
I have following code
```
        contractInstance.methods.read().call().then(items => {
          this.items = items // sometimes cached
        })
```
Sometimes I'm getting cached items. When it happens I don't see eth_call in Ganache log.

Workaround
```
        contractInstance.methods.read().call({
          gas: gas // random gas
        }).then(items => {
          this.items = items // always correct
        })
```

Ganache 1.0.2
Web3 1.0.0-beta.31
Node v9.2.1
OS X 10.13.3

**Comment by gburtini** [comment]
I believe a call is implemented a local simulation. If it is cached, as long as the cache expires per block, that should be sufficient. I assume you're saying the cache does not expire per block in at least some circumstances.

Can you post the ABI for your `read` method?

**Comment by melnikaite** [comment]
Sure
```
    {
      "constant": true,
      "inputs": [],
      "name": "read",
      "outputs": [
        {
          "name": "_items",
          "type": "bytes32[]"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    }
```

**Comment by showmeyourcode** [comment]
Was facing the same issue even after restarting GANACHE and redeploying the smart contract several times using truffle.
Sending random gas trick mention by @melnikaite  worked for me.

web3 : 1.0.0-beta.34
Ganache : 1.1.0
OS : Mac OS X El Capitan (10.11)
react : 16.3.2
Metamask : 4.5.5

**Comment by nivida** [comment]
This is an issue of ganache and you should open it there.
