### ISSUE TITLE
Cannot watch for only future contract events

### ISSUE THREAD

**Issue by anthonymq** [ethereum/web3.js#1464]
Hi,

I'm trying to watch for future events and i'm getting a lot trouble.
In the documentation for [contract events](https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-events ), it is said that i can use event filters.

The problem with the filters is the parameter ```fromBlock```. It can be set to (last block number + 1).
If it is, no events are captured.

The other thing is if I set ```fromBlock: 'pending'```, it retrieves the last block mined.
I'm just trying to watch for events that are only in the future, do you have other ways to this ?

My code :
```
self.instance.MyEvent({_currentAddress: window.web3.eth.accounts[0]}, {fromBlock: 'pending', toBlock: 'latest'})
```
or
```
self.instance.MyEvent({_currentAddress: window.web3.eth.accounts[0]}, {fromBlock: lastBlockNumber + 1, toBlock: 'latest'})
```

I don't know if it's a bug are a mistake of mine.

**Comment by atomixxx2** [comment]
try using fromBlock:0 and toBlock: 'latest', this will not give you past events, for past events there is a separate function getPastEvents.

var MyContract = web3.eth.contract(abi);
var myContractInstance = MyContract.at('0x78e97bcc5b5dd9ed228fed7a4887c0d7287344a9');
// watch for an event with {some: 'args'}
var myEvent = myContractInstance.MyEvent({some: 'args'}, {fromBlock: 0, toBlock: 'latest'});
myEvent.watch(function(error, result){
   ...
});

**Comment by anthonymq** [comment]
Hi,

I tried that but when i use ```fromBlock: 0```I receive every events from the block number 0.
This is very strange, i should receive only the future events.

I'm using 
```
"web3": "1.0.0-beta.33",
"truffle-contract": "^3.0.0",
"truffle": "^3.4.9"
```

Any help ?

**Comment by anthonymq** [comment]
@dpurhar27  I updated to 4.1.5 but I still have the same behaviour, I get every events from the beginning.
I'm using Ganache by the way.

**Comment by iurimatias** [comment]
@anthonymq use ```{fromBlock: 'latest'}```
