### ISSUE TITLE
ERROR TypeError: web3_eth_personal_1.default is not a constructor 

### ISSUE THREAD

**Issue by helxsz** [ethereum/web3.js#1465]
my web3 version is version: '1.0.0-beta.20', and  web3 personal version is web3-eth-personal@1.0.0-beta.31.

I am loading the web3 using the angular 4.

```
      import * as Web3 from 'web3';
      import Personal from 'web3-eth-personal';
      this.web3 = new Web3(window.web3.currentProvider);
      console.log(window.web3.currentProvider);
      this.personal = new Personal(window.web3.currentProvider);
```
web3 is loaded well, however initalizing Personal gives an error,

` ERROR TypeError: web3_eth_personal_1.default is not a constructor`

the web3-eth-personal 's code exports Personal as 
`module.exports = Personal;
`
why comes with an error like web3_eth_personal_1.default?

**Comment by Can-Sahin** [comment]
@helxsz  did you get anything on this ? I'm at the same issue. Just getting started with Web3js

**Comment by iurimatias** [comment]
@helxsz are those the versions specified in package.json ? if so, can you specify the same version for both of them and see if it works afterwards?
