### ISSUE TITLE
bytes32 characters don't show correctly on chrome(win10)

### ISSUE THREAD

**Issue by jacktang** [ethereum/web3.js#1467]
Hello,

The value of `web3.toAscii(b32Chars) ` does not show correctly on chrome(version: 65.0.3325.162 / 65.0.3325.162), see the screenshot:
![error](https://pbs.twimg.com/media/DYZR1fkVMAAAEHw.jpg:large)

OS: win10
web3js: 0.14.0

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
