### ISSUE TITLE
1.0 should use solidity/coder like pre-1.0

### ISSUE THREAD

**Issue by jtakalai** [ethereum/web3.js#1476]
No offense, but (no really, this is a question and not just bashing) what is the rationale behind the kind of parameter passing convention as seen in web3-eth-contract _createTxObject? Looking at the current state of _createTxObject in 1.0 branch: https://github.com/ethereum/web3.js/blob/fb683e3b6b06f423fb8ce24bcac4986969f54715/packages/web3-eth-contract/src/index.js#L498
_createTxObject is nominally declared as a function without arguments, just the first line is parsing args from `arguments`; also the function uses `this` to get the other half of (what should be called) the arguments from an object that the call site populates and then passes to Function.apply. Seeing a function called like this makes it my daily WTF of today.

I understand historical reasons, and I guess my glass house isn't always pretty either, so I shouldn't throw rocks. Looking at the code with this use of `this` was created:
https://github.com/ethereum/web3.js/blob/23f428b09627095658d09d306455082641424aac/lib/web3/contract.js#L692
it sort of makes sense, it looks like a constructor... only... how did it evolve into the function with the exotic calling convention without getting refactored at some point?

Real reason I started digging around was: I wanted to contribute a checker that checks that arguments to constructor are not undefined. Following code snippet caused a bug that was very hard to track:
```
const contract1 = await (new web3.eth.Contract(Contract1.abi)).deploy({ data: Contract1.bytecode, arguments: [] }).send({from: accounts[0]})
const contract2 = await (new web3.eth.Contract(Contract2.abi)).deploy({ data: Contract2.bytecode, arguments: [
        contract1.address,
        accounts[0]
]}).send({from: accounts[0]})
```
(can you spot the bug? Web3 1.0 was used)

Curiously, the (pre-1.0) develop branch of Contract class https://github.com/ethereum/web3.js/blob/2fba1d2f2b4c5c0afb286e30b6b756d33faf9c8a/lib/web3/contract.js#L44 seems to use solidity/coder in the same branch:  https://github.com/ethereum/web3.js/blob/2fba1d2f2b4c5c0afb286e30b6b756d33faf9c8a/lib/solidity/coder.js 
this kind of "Solidity encoder" which might have caught that mistake. Also that pre-1.0 code is clean and readable. Is there anything besides the git commit tree (changelogs?) where you'd recommend I read more about how 1.0 branch has diverged from pre-1.0 codebase?

Any chance 1.0 could also use solidity/coder to encode the parameters? Now that I start thinking, pre-1.0 did a lot of useful conversions such as between Solidity `bytes` and Javascript string, so that you wouldn't need to use `web3.(utils.)fromUtf8`...

**Comment by erinbagel** [comment]
@jtakalai it doesn't help that the documentation for deploying is super confusing. I need halp. on beta.29

**Comment by jtakalai** [comment]
@erinbagel that's not even a question. What have you tried? Paste your script(s) to a gist.

**Comment by nivida** [comment]
I've closed this issue because of inactivity.

**Comment by danuid** [comment]
has this been achieved by any chance?
