### ISSUE TITLE
Unable to install ethereum web3 

### ISSUE THREAD

**Issue by juni381** [ethereum/web3.js#1478]
i have tried several code to install Web3.js in Windows 10 , codes are below 
`npm install ethereum/web3.js --save
npm install web3@^0.20.0
npm install --save web3@1.0.0-beta.26`

but none of these works for me .. Errors are approx coming same in running these codes 

`npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15)
npm WARN addRemoteGit  ethereum/web3.js resetting remote C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-6339a8c5 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-6339a8c5: undefined
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-6339a8c5: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15)
npm WARN addRemoteGit  ethereum/web3.js resetting remote C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ethereum-web3-js-git-a32ab180 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ethereum-web3-js-git-a32ab180: undefined
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ethereum-web3-js-git-a32ab180: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15)
npm WARN addRemoteGit  ethereum/web3.js resetting remote C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-f9d31afd because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\Junaid\AppData\Roaming\nvm\v7.6.0\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-f9d31afd: undefined
npm ERR! git clone --template=C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ethereum/web3.js.git C:\Users\Junaid\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-f9d31afd: undefined
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ethereum/web3.js" "--save"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Junaid\code\juni-eth\npm-debug.log`

**Comment by jordanmurkin** [comment]
It seems that the script is not able to use the `git` command.

Have you made sure that `git` is installed?

It looks like you are on Windows, if you have already installed git make sure that when you installed you checked the option "Run Git from Windows Command Prompt". More details here: https://stackoverflow.com/questions/19290899/git-is-not-installed-or-not-in-the-path/21614660#21614660

**Comment by juni381** [comment]
yup git is installed , nd i used it daily purpose for pushing my repository... but it is not installed Global.
I have to go Git CMD for pushing or cloning the Repository.
Should i reinstalled it or make it global??

**Comment by iurimatias** [comment]
The git cmd needs to be installed globally and available in the path
