### ISSUE TITLE
Expected output instead throws VM exception 

### ISSUE THREAD

**Issue by maektwain** [ethereum/web3.js#1482]
```
 web3.eth.contract(MarketToken.abi).at("").name()

```

The above code returns 

``
VM Exception while processing transaction: stack underflow
``

But instead should return Invalid Address or Empty Address.

I would like to implement this functionality.

**Comment by nivida** [comment]
Could you please provide more informations? @maektwain

**Comment by nivida** [comment]
I've closed this issue due to inactivity.
