### ISSUE TITLE
Async calls cause InvalidStateError in IE 11

### ISSUE THREAD

**Issue by jakubukrop** [ethereum/web3.js#1483]
`HttpProvider.sendAsync()` causes InvalidStateError in IE 11

It seems that IE has a problem when `request.timeout` is set before `request.open()`.
See `lib/web3/httpprovider.js`:

    HttpProvider.prototype.prepareRequest = function(async) {
        var request;

        if (async) {
            request = new XHR2();
            request.timeout = this.timeout; // <-- IE11 needs this after request.open()
        } else {
            request = new XMLHttpRequest();
        }
        request.open('POST', this.host, async);

Note: The same issue has been reported in other projects: https://github.com/stephanebachelier/superapi/issues/5
and https://github.com/airbrake/airbrake-js/issues/302

**Comment by nivida** [comment]
This got fixed here: https://github.com/ethereum/web3.js/commit/02073695284afdeafb004699e593054c7d2aa29f.
