### ISSUE TITLE
web3.eth.personal.sign gives error: error TS2554: Expected 0 arguments, but got 3

### ISSUE THREAD

**Issue by gkd720** [ethereum/web3.js#1485]
I'm getting an error using web3.eth.personal.sign, with it complaining that the call "Expected 0 arguments, but got 3". I called it in an Angular/Typescript/javascript environment 2 different ways:

`this.bottleSig=this.web3.eth.personal.sign(this.bottleDataToSign, this.addressProd, this.passwordProd);`

`this.web3.eth.personal.sign(this.bottleDataToSign, this.addressProd, this.passwordProd).then((sig)=>{console.log(sig)});`

I'm using a recent version of the npm web3 package: 1.0.0-beta.33. I'm following the documentation at http://web3js.readthedocs.io/en/1.0/web3-eth-personal.html. I poked around under .../node_modules and looked at various web3* directories, but nothing obvious looked wrong, at least to me. Under node_modules/web3-eth-personal/src/index.js, it looks like it should be expecting 3 args:

`new Method({
        name: 'sign',
        call: 'personal_sign',
        params: 3,
        inputFormatter: [formatters.inputSignFormatter, formatters.inputAddressFormatter, null]
    }),`

Any searching returns very few results, which don't seem to be applicable here. Any thoughts on what's wrong? How to fix/workaround? Since beta, just need to wait till "fixed"? Thanks.

Update:

This link seems to offer some solutions, but a little too deep into directives and controllers for me!

http://danlec.com/st4k#questions/46692046 

Update2:

This was answered/resolved in ethereum.stachexchange as missing argument specs in types.d.ts, and looks like a few more methods would need this treatment.

https://ethereum.stackexchange.com/questions/43472/error-using-web3-eth-personal-sign

**Comment by nivida** [comment]
Does the error still occurs in the latest version of web3? @gkd720

**Comment by gkd720** [comment]
@nivida I don't know. I probably won't be trying it anytime soon either, as I've changed my approach to not use web3.js. Looks like the latest is beta34, and I couldn't find "sign" in open or closed issues. Thanks for checking in.

**Comment by nivida** [comment]
@gkd720 Sorry that you made this experince with web3.js I'll try to fix and improve the lib as much as possible but there is a lot to do. Hopefully you will use it after the 1.0 stable release big things are coming. :-) 

I'm closing this issue for now.
