### ISSUE TITLE
getPastEvents not recongnizing fromBlock value

### ISSUE THREAD

**Issue by Freydal** [ethereum/web3.js#1486]
Has there been a regression with this?  #1343 

I have not been able to successfully limit results by block number range. I am using a websocket provider pointing at geth locally running 1.8.2-stable and infura via 'wss://ropsten.infura.io/ws' and 'wss://ropsten.infura.io/_ws'.  With infura the code below fails I believe due to response size

```
// block_number = the block of the most recent event
contractInstance.getPastEvents('DealAdded', { fromBlock: block_number, toBlock: "latest" }).then((r) => console.log(r.length));
//Prints 228 (the total events events from contract). I think I would expect 1.
contractInstance.getPastEvents('DealAdded', { }).then((r) => console.log(r.length));
//Prints 0
```

Initially developed using 1.0.0-beta.31.  I rolled back to try beta 18 and experience the same behavior.

**Comment by Freydal** [comment]
I was able to resolve my issue.

**Comment by dpurhar27** [comment]
I'm having an issue with the same behaviour, would you mind telling me how were you able to solve this problem?

**Comment by Freydal** [comment]
I believe in my case the fromBlock wasn't the block number I expected.   I had an error in the query I was using on the api side that was returning the block number of the first event instead of the most recent event.
