### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [ethereum/web3.js#1492]
Hi guys

We would like to host your library on cdnjs, but there is [some issues](https://github.com/cdnjs/cdnjs/pull/12025#pullrequestreview-103312337) that we need your answer for them. Could you please help us with [them](https://github.com/cdnjs/cdnjs/pull/12025#pullrequestreview-103312337).
Thanks

**Comment by sashberd** [comment]
@debris @frozeman Could you help us to answer questions?

**Comment by nivida** [comment]
@sashberd Sorry for the delayed response but I thought fabian will help out. I will have a look at the cdnjs issue thanks!
