### ISSUE TITLE
web3.eth.personal.sign gets error "The method personal_sign does not exist"

### ISSUE THREAD

**Issue by gkd720** [ethereum/web3.js#1498]
Getting past the issue over number of arguments, I now get a "does not exist" error when trying to invoke.

`this.web3.eth.personal.sign(this.bottleDataToSign, this.addressProdFrom, this.passwordProd)
  .then((sig)=>{
    console.log("sig="+sig);`

Console:
`ERROR
Error: Uncaught (in promise): Error: Returned error: The method personal_sign does not exist/is not available ErrorResponse onreadystatechange wrapFn onInvokeTask runTask invokeTask invokeTask globalZoneAwareCallback`

Poking around in other node_modules/web3 directories/files, I didn't see any declaration for it:

```
$ grep -r "personal_sign" web3*
web3-core-helpers/src/formatters.js: * Hex encodes the data passed to eth_sign and personal_sign
web3-eth-personal/src/index.js:            call: 'personal_signTransaction',
web3-eth-personal/src/index.js:            call: 'personal_sign',
```
So does this imply the code is just missing? Am I calling it correctly? I'm still using npm web3 package: 1.0.0-beta.33, and used it from an `import  Web3  from "web3"`; Anything else to try? A few more details in https://ethereum.stackexchange.com/questions/43894/error-does-not-exist-using-web3-eth-personal-sign
Thanks.

**Comment by gkd720** [comment]
Looks like my "geth" invocation caused this, by not having "personal" in the list of --rpcapi values. Maybe add this reason to the error message?

**Comment by JimLynchCodes** [comment]
I'm getting this on rinkeby network...

**Comment by leonidlewis** [comment]
How to add the "personal" to the list of --rpcapi values ?

**Comment by misitesun** [comment]
通过webview的方式，将web3.js注入到三方的H5中，H5调用签名，从我这里监听签名，提示：Error: Returned error: The method personal_sign does not exist/is not available
这种是什么原因呢，打印数据web3.eth.personal.sign，方法也存在
