### ISSUE TITLE
web3@1.0.0-beta2 cannot find module 'web3-requestManager'

### ISSUE THREAD

**Issue by cchen408** [ethereum/web3.js#1505]
After upgrading my `web3@1.0.0-beta2` i get the following error

```
Error: Cannot find module 'web3-requestManager'
```

It looks like web3-requestManager has been deprecated and we should be using web3-core-requestmanager

**Comment by cchen408** [comment]
currently using `"web3": "^1.0.0-beta.33"` but I thought that beta2 was newer beta.

**Comment by iurimatias** [comment]
closing this as per @HarderThenBetter comment.

**Comment by mryellow** [comment]
> Currently using "web3": "^1.0.0-beta.33" but I thought that beta2 was newer beta.

It's not?

`npm update` resulted in:

```
-    "web3": "^1.0.0-beta.34"
+    "web3": "^1.0.0-beta2"
```
