### ISSUE TITLE
contract.methods.return:object

### ISSUE THREAD

**Issue by ajax-2** [ethereum/web3.js#1511]
Hello, I encounter a problem when i call my contract's method:
## Error result:
> [Error: ERROR: The returned value is not a convertible string:]
## my contract's method

>     function getAuthor() public pure returns(string result){
        return "Allence";
    }

## and my contract's abi with the method

>  { constant: true,
    inputs: [],
    name: 'getAuthor',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'pure',
    type: 'function',
    signature: '0xa5faa125' },

## I call my method
> mycontract.methods.getAuthor().call(console.log)

So, I have a issue: why output is [[ object ]], owing to the result of method is 'string'. 
If this is a property of web3.js, what should i do so that i can use normally.

**Comment by arnoudbevers** [comment]
This is since Solidity does not support strings, they are represented by bytes32. In your ABI you see that the outputs is an [ [Object] ], since I assume the EVM is assuming 'string' is a Struct. You need to treat string as bytes32 and convert them through the web3.utils functions https://web3js.readthedocs.io/en/1.0/web3-utils.html#hextoutf8 Let me know if you need some more help.

**Comment by ajax-2** [comment]
@arnoudbevers thanks for your attention. My proplem can be not only 'string' but also uint or int.
I tried an example https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id18 [methods.myMethod.call]. It works well in that book, but
It is also [[object,object]] in my web3.js. So I think this issue is because of my environment. But when I install web3, nodejs, solc, I use the official method.
Yes, my Ubuntu is server1604. Does it affect this?

**Comment by arnoudbevers** [comment]
Your server should not affect this. I run a Quorum test environment on Ubuntu 16.04 and this works fine. I could take a look at your whole codeflow to see what is wrong. I think that even every return value is treated as an Object in web3js, so you have to know how to deal with the request.

**Comment by ajax-2** [comment]
Hello, this is my code:

## script about web3.js
> var Web3 = require('web3');
var web3;
var address = ["0x288b178f7538633275002f7795e2bdb177dd6555", "0xd18178da6e57ebacc0302d2e046699419914f973",
 "0x29b9ebbecda13c6ed9ed6223962e852b3877d9d2", "0xf97895d1b6808aa44a7fe01a009579d37a311dd7"];
var p_file = 'Deno.sol';
var p_name = ':Pano'
if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:5587"));
}
var eth = web3.eth;
eth.defaultAccount = address[0]
const fs_c = require('fs')
const solc_c = require('solc')
var source_c = fs_c.readFileSync(p_file,'utf8');
var compileContract_c = solc_c.compile(source_c, 1);
var abi_c = compileContract_c.contracts[p_name].interface;
var bytecode_c = compileContract_c.contracts[p_name].bytecode;
var mycontract = new eth.Contract(JSON.parse(abi_c));
mycontract.options.address = address[0];
mycontract.options.from = address[0];
mycontract.options.gasPrice = 1000000000;
mycontract.options.gas = 5000000;
mycontract.options.data = '0x' + bytecode_c;
mycontract.deploy().send({from: "0x288b178f7538633275002f7795E2bDB177dD6358"});

## solidity
>pragma solidity ^0.4.0;
contract Pano {

  function getAuthor() public pure returns (string name) {
    name = "Allence";
  }

  function getAge() public pure returns (uint age){
    age = 23;
  }
}

## problem
> abi from solc:
[{"constant":true,
  "inputs":[],
  "name":"getAge",
  "outputs":[{"name":"age","type":"uint256"}],
  "payable":false,
  "stateMutability":"pure",
  "type":"function"},
  {"constant":true,
  "inputs":[],
  "name":"getAuthor",
  "outputs":[{"name":"name","type":"string"}],
  "payable":false,
  "stateMutability":"pure",
  "type":"function"}]

> and abi from web3.js:
[ { constant: true,
    inputs: [],
    name: 'getAge',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'pure',
    type: 'function',
    signature: '0x967e6e65' },
  { constant: true,
    inputs: [],
    name: 'getAuthor',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'pure',
    type: 'function',
    signature: '0xa5faa125' } ]
### they outpus is differece.
## call method:
mycontract.methods.getAge().call(console.log)
get output:
[Error: Couldn't decode uint256 from ABI: 0x]

**Comment by ajax-2** [comment]
Maybe this is a bug in nodejs, so i should close it!
