### ISSUE TITLE
Error: ERROR: The returned value is not a convertible string:

### ISSUE THREAD

**Issue by GarryPlays** [ethereum/web3.js#1512]
Works great in remix and web3 0.20.3
Not at all in web3 1.0.0-beta.33

What I get in remix back:
0: string: moves0 dkMq+ciRPocrymdSicJ54esSDqo6zfdUBn7T833NagoKVz0PbKnfgchQ1kp/7XBmiOYWbJCbbAEajzu/dRYTeA==
1: string: moves1 gw5QIWGdtYAdKa7FUAckp1VJWNi97PYZUykq33+IghkdCjDIpgM98k/GW7zvnrCE4XVutCvy3DbSD8XkpCVVqA==
2: string: moves2 UQ8QgWjNZI0R5hPciNLp2F3JR4WNv+JiMwSASkbwkaJvDY5wuhigS7EkWRCMk7qrrnxpj3kfZ8jBi7afutikTg==
3: string: moves3 3xnli6jScKuQtfWBbwlcTidyMp1oUoRsCUS+bWCEvKM0Rv5KgkP13+gRL+R/SRpZj7N5nxzYgCAfSmDM2mhaOA==
4: string: moves4 qufMAoHutJ+Zn+eOAFvAD9ABIR5/1SAj18u6Z/r1WxWskse5F5nmSHYxwpt6a8CvA6/q4ENxvSnJy1bCtmCGUA==

what my function does:
function queryMoves(uint _battleNum, bool _isDeathMatch, bool _battleSwitch, bool _att_def) view public battleSolver returns (
        string moves0,
        string moves1,
        string moves2,
        string moves3,
        string moves4
        )

that ABI part:
"name": "queryMoves",
			"outputs": [
				{
					"name": "moves0",
					"type": "string"
				},
				{
					"name": "moves1",
					"type": "string"
				},
				{
					"name": "moves2",
					"type": "string"
				},
				{
					"name": "moves3",
					"type": "string"
				},
				{
					"name": "moves4",
					"type": "string"
				}
			],

**Comment by GarryPlays** [comment]
actually web3 0.20.3 returns a null!
it's only remix and truffle web3 that returns the correct string/s

**Comment by nivida** [comment]
This got fixed with the new AbiCoder of Web3.js. Please update to the latest version of Web3.js.
