### ISSUE TITLE
Using web3 1.0 aside with Metamask given error to get accounts

### ISSUE THREAD

**Issue by eduardonunesp** [ethereum/web3.js#1516]
The error just happens if we try to use `web3` new version aside with `Metamask`. If the comment the line `<script language="javascript" type="text/javascript" src="https://cdn.rawgit.com/ethereum/web3.js/1.0/dist/web3.min.js"></script>` it works properly.

Does `web3 1.0` create some sort of conflict here?

```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="style.css">
    <script language="javascript" type="text/javascript" src="https://cdn.rawgit.com/ethereum/web3.js/1.0/dist/web3.min.js"></script>
  </head>

  <body>
    <script>
      window.addEventListener('load', function() {
        var web3js;
        
        if (typeof web3 !== 'undefined') {
          web3js = new Web3(web3.currentProvider);
        }

        var accountInterval = setInterval(function() {
          console.log(web3.eth.accounts);
        }, 1000);
      })
    </script>
  </body>
</html>```

Is given the following error

```
inpage.js:1 Uncaught Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (inpage.js:1)
    at s.send (inpage.js:1)
    at n.accounts (inpage.js:1)
    at (index):15
InvalidResponse @ inpage.js:1
s.send @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ (index):15
setInterval (async)
startApp @ (index):14
(anonymous) @ (index):31
load (async)
(anonymous) @ (index):19
inpage.js:1 Uncaught TypeError: e is not a function
    at inpage.js:1
    at inpage.js:1
    at o (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
```

**Comment by jerryji** [comment]
I have the same problem, web3.js 1.0.0-beta.33

**Comment by eduardonunesp** [comment]
How I did to fix that is to use the `web3.eth.getAccounts` instead of using `web3.eth.accounts`,  it will request accounts from `Metamask` in the same way but returning a `promise`, so it's async, also it never hits the Ethereum node only the `Metamask` extension.

**Comment by bordalix** [comment]
This works:

    <script>
      window.addEventListener('load', function() {
        var web3 = new Web3();
        web3.setProvider(new web3.providers.HttpProvider());    
        web3.eth.getAccounts().then(accounts => {
          console.log(accounts);
        })
      })
    </script>

**Comment by eduardonunesp** [comment]
@bordalix be careful when using the fat arrow `=>` isn't widely supported unless you are using some transpiler to ES6 like Babel.

**Comment by bordalix** [comment]
@eduardonunesp you're right. Force of habit. Edited.

**Comment by iurimatias** [comment]
@eduardonunesp metamask only supports async methods, so stuff like ```web3.eth.accounts``` wouldn't work.

Has this issue been solved or are you still experiencing problems?

**Comment by jerryji** [comment]
No longer an issue for me in web3.js 1.0.0-beta.34 -- admitted that I could have done something wrong previously

**Comment by antonpegov** [comment]
Still has it! Metamask api version "0.20.3", my web3 version 1.0.0-beta.36
