### ISSUE TITLE
bn.js bundled multiple times

### ISSUE THREAD

**Issue by wenq1** [ethereum/web3.js#1518]

**Comment by wenq1** [comment]
![screen shot 2018-04-04 at 12 57 34 am](https://user-images.githubusercontent.com/110781/38263655-38a23594-37a3-11e8-85ea-4585c3751c30.png)

**Comment by wenq1** [comment]
Indeed "big number" for disk space...

**Comment by kosmos** [comment]
@wenq1 How did you solve this problem?

**Comment by koledaivan** [comment]
@wenq1 faced the same issue, did you find any solution?

**Comment by yzhang1994** [comment]
@wenq1 How did you solve this problem?

**Comment by damianobarbati** [comment]
Any news on this? Also: can't we opt-in to use native BigInts since Chrome does support them now?
