### ISSUE TITLE
Websocket Library options for Basic Auth

### ISSUE THREAD

**Issue by Freyert** [ethereum/web3.js#1524]
I'm very excited about `websocket` support since subscriptions are a _huge_ feature. However, I'm already running into a major issue with the current `websocket` library: it doesn't support basic auth.

According to RFC 6455 any authentication method supported by HTTP should be supported during the upgrade.

I think you may also be able to get away without forking the project to obtain browserify support by using https://github.com/heineiuo/isomorphic-ws to handle the transition between nodejs and browser.

If you are amenable to a PR I'd love to take a crack at swapping out the libraries.

**Comment by peterbroadhurst** [comment]
I've just submitted a PR here for consideration: https://github.com/ethereum/web3.js/pull/1541

**Comment by frozeman** [comment]
Thanks!
