### ISSUE TITLE
web3.js: events not sorted by blockNumber when pulled historically

### ISSUE THREAD

**Issue by chetmurthy** [ethereum/web3.js#1525]
I'm using web3.js 0.20.6, and subscribing to two different events from the same smart-contract.  It appears that all historical (that is, already mined) event-instances for the first event are delivered FIRST, and ONLY AFTER THAT for the second event-instance.

This results in behaviour that is different from what would occur if a client subscribed to watch these events, and then event-instances were delivered afterwards (hence, not historical).

I'm not sure whether this is desired behaviour, but it seems quite suboptimal, and I don't see a way to work around this problem.

I'll look around and see if I can figure out how to fix it, but thought I ought to report it.

Maybe it's fixed in 1.0.0?  I can't use that (b/c using truffle-contract 3.0.4 (and there's a version-constraint).

**Comment by kingpine81** [comment]
I also have the same problem !

It does not occur with local node, Ganache, but on public Rinkeby.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
