### ISSUE TITLE
arguments property should be optional

### ISSUE THREAD

**Issue by YuichiNukiyama** [ethereum/web3.js#1530]
### version
1.0.0-beta33

### description
According to the [official document](http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html?highlight=send#id9), the arguments of the deploy method is optional. However, it is mandatory in type definition.

### expected
```typescript
deploy(options: {
    data: string
    arguments?: any[]                    // this is optional!
}): TransactionObject<Contract>
```

### actual
```typescript
deploy(options: {
    data: string
    arguments: any[]
}): TransactionObject<Contract>
```

https://github.com/ethereum/web3.js/blob/1.0/packages/web3/types.d.ts#L326

**Comment by nivida** [comment]
Typing are now on DefinitelyTyped as you can see here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/web3
