### ISSUE TITLE
UX: Instantiating contract should fail if contract missing or ABI mismatch

### ISSUE THREAD

**Issue by d10r** [ethereum/web3.js#1535]
Currently, [new contract](http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#new-contract) will always succeed, even if there's no contract deployed at the given address or if the deployed contract doesn't match the ABI. Only when invoking contract methods, it will fail - often with obscure error messages, for example [this one](https://github.com/ethereum/web3.js/issues/898).

For better usability, instantiation should fail if there's no contract with matching ABI deployed at the given address.

**Comment by nivida** [comment]
@d10r Yes but maybe you would like to deploy a contract with the contract.deploy() method and that's why the address field is optional. I will overthink this and maybe I move the deployment of a contract out of the Contract class.

**Comment by d10r** [comment]
Intuitively I would expect that if an address parameter is given and no (matching) contract is located there, it fails.
When using for deployment, the address parameter will likely not be set, so that should not be an issue.
