### ISSUE TITLE
MaxListenersExceededWarning in RequestManager (v1.0.0-beta.33)

### ISSUE THREAD

**Issue by Xcrux** [ethereum/web3.js#1536]
When provider implements provider.on, `RequestManager` is listening to its 'data' event, but never calls 'removeListener' (https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-requestmanager/src/index.js#L98)

the solution in https://github.com/ethereum/web3.js/pull/1494 will not fix the issue (not calling removeListener).
removeListener can be added at `clearSubscriptions()`, however, it is not always called (it will help if setProvider is called)

every place where `packageInit` is called should eventually also remove these listeners
it means that when you create a contract, you have to call a function of this contract to remove listeners (which doesn't scale well). I think listening to subscriptions should be opt-in/opt-out mechanism in automatic way:

on the first `addSubscription()` listen to the 'data' event
on the last `removeSubscription()` remove listener

**Comment by NoahZinsmeister** [comment]
Any update on this issue?

**Comment by nivida** [comment]
This will be fixed with the PR #2000
