### ISSUE TITLE
Issue creating key pair with shh

### ISSUE THREAD

**Issue by ToJen** [ethereum/web3.js#1539]
I'm using `ganache-cli` as my provider and when I do `web3.shh.newKeyPair(console.log)
`, I get back `Error: Returned error: Error: Method shh_newKeyPair not supported.` Is this function call limited to geth?

**Comment by ToJen** [comment]
Same when I do `web3.shh.getInfo().then(console.log)` = `Error: Returned error: Error: Method shh_info not supported.`

**Comment by iurimatias** [comment]
@ToJen this is only supported in geth

**Comment by ToJen** [comment]
I think the issue will be resolved by updating geth.
