### ISSUE TITLE
mandatory from in sendTransaction, add 'defaultAccount'

### ISSUE THREAD

**Issue by debris** [ethereum/web3.js#154]
just a reminder to myself. 
- [x] [contract example](https://github.com/ethereum/web3.js/blob/master/example/contract.html) should be updated to use from (which is mandatory)
- [x] add to web3 object property 'defaultAccount', which will be used as a from for transactions
- [x] add from to [new Contract constructor call](https://github.com/ethereum/web3.js/blob/master/lib/web3/contract.js#L199)

**Comment by simondlr** [comment]
Is this mandated by the RPC or is this just from the web3 lib level? Currently not able to instantiate contracts and the documentation doesn't give an indication what "from" is. An account, I assume?

**Comment by debris** [comment]
>Is this mandated by the RPC or is this just from the web3 lib level?

It's just from web3 lib level.

>Currently not able to instantiate contracts and the documentation doesn't give an indication what "from" is. An account, I assume?

Yes, I will update the docs.

**Comment by simondlr** [comment]
Thanks! :+1:

**Comment by simondlr** [comment]
@derbis. Thanks, but I still don't quite understand what the new format is & what should be specified if you create a contract (& the documentation is still out of date)?

What is required for it to work like before? ie contract.sendTransaction().doSomething() will correctly issue a tx to that contract? I see in the new examples you only specify the source? Aren't addresses also required? When I specify nothing (no data, or address), it prints out an address which I'm not sure where it is getting it from (it only has the ABI).

Anything you "don't" add into the initial default will just have to be issued through the sendTransaction() right? Is that correct? ie, you instantiate with no extra options. You will have to manually add "to" and other options when you call the contract?

**Comment by debris** [comment]
> What is required for it to work like before? ie contract.sendTransaction().doSomething() will correctly issue a tx to that contract?

Yes, it  will.

> I see in the new examples you only specify the source? Aren't addresses also required?

No, If we want to create new contract.
Example:

```javascript
//
var source = "605280600c6000396000f3006000357c010000000000000000000000000000000000000000000000000000000090048063c6888fa114602e57005b60376004356041565b8060005260206000f35b6000600782029050604d565b91905056";


// new way
web3.eth.defaultAccount = web3.eth.coinbase; // we set coinbase to be used as default "from"
var Contract = web3.eth.contract(desc);
var myContract = new Contract({data: source}); // we are creating new contract on the blockchain
var res = myContract.multiply(param);

// old way (still valid):
var Contract = web3.eth.contract(desc);
var address = web3.eth.sendTransaction({data: source, from: web3.eth.coinbase});
var myContract = new Contract(address); // we are reusing contract, that already exist
var res = myContract.call({from: web3.eth.coinbase}).multiply(param);
```

> Anything you "don't" add into the initial default will just have to be issued through the sendTransaction() right? Is that correct? ie, you instantiate with no extra options. You will have to manually add "to" and other options when you call the contract?

That's not fully supported yet. Not anything... I will update the docs soon, to clarify changes ;)

**Comment by simondlr** [comment]
Thanks @debris. I tried just adding address and gave an error. Shouldn't it be?

```
var myContract = new Contract({address : address}); // we are reusing contract, that already exist
```

So: if you've already created it and just want to map a created contract, do you just do?

```
var Contract = web3.eth.contract(desc);
var myContract = new Contract({address : address}); // we are reusing contract, that already exist
```

Any address I pass through like that constantly returns a specific address "0x9e78ee996d0160cf72f00d73462f6ea167736430" (which is not the coinbase). Not sure where it finds that. Or my perception is a bit wonky.

**Comment by debris** [comment]
no...
```javascript
var myContract = new Contract(address); 
```

Should be working, as long as `address` matches `/^(0x)?[0-9a-f]{40}$/`

**Comment by debris** [comment]
I will add throwing exception, if the input params are not correct.

**Comment by simondlr** [comment]
Ah, thanks. That works. I was using "0x0" which I thought was valid (it's ABI-related stuff, so the contract doesn't have to exist). It gave: 

"Uncaught Error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"

It did give invalid params, but it wasn't clear what was going wrong. Thanks again @debris!
