### ISSUE TITLE
PLEASE PROVIDE SENSIBLE ERRORS

### ISSUE THREAD

**Issue by beether** [ethereum/web3.js#1543]
"Invalid number of solidity arguments" is AIDS.

You have the freaking ABI that defines which inputs are expected, their order, and their type. Why such a miserable error message? FFS... it's so unnecessarily difficult to debug this error, especially since you (rather idiotically) try to infer the different inputs (which CAN be objects) from the transaction options (which IS an object).

It infuriates me, and countless others.

JUST FREAKING FIX THIS.  LET ME PASS AN ARRAY OF INPUTS.

**Comment by Andromelus** [comment]
Your demand might be legit, but the way you demand it is not. They work for you, at least respect it.

**Comment by frozeman** [comment]
:)
In 1.0 there is no transaction object anymore.
And yes the euro could be more concise, and as this is an open source projects youre welcome to make the change, PR and we discuss ;)

**Comment by beether** [comment]
So, in other words, it's not a priority to fix this, even though pretty much all dApp developers need to target MetaMask, which uses v0.2.x.  v1 is great and I love the design and can't wait to use it... but It's really annoying that you don't seem to care about making _actual_ development easier, and quite telling that your response is "it's open source, take it or leave it"

**Comment by beether** [comment]
@Andromelus what do you mean "they work for you"?

**Comment by nick** [comment]
@beether you can use v1 with MetaMask https://guillaumeduveau.com/en/blockchain/ethereum/metamask-web3

**Comment by nivida** [comment]
@beether I will implement the Winston logger for a better and consistent error handling.
