### ISSUE TITLE
web3 instance doesn't return events/logs

### ISSUE THREAD

**Issue by OlypsisAli** [ethereum/web3.js#1552]
I can't get logs from my contract. I am using my local node. 

i.e: 

>  `web3js` = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));

```
var ethEvent = passthrough.transactionIDs({},{from: 'latest', to: 'latest'});
        ethEvent.watch((error, result) => {
          console.log("events:");
          if (error){
            console.log("error");
            console.log(JSON.stringify(error,null,4));
            
          }else {
            console.log("resultevents:" ,JSON.stringify(result, null, 4));
            console.log("result.args: \t"+ result.args);
          } 
        });

```
The event seems not to be recognized or throws an error that is empty. 

I have tried this with both metaMask and mist to no avail. Anyone else have this issue?

**Comment by Dobberoonski75** [comment]
@OlypsisAli By any chance have you tried using `new Web3(new Web3.providers.WebsocketProvider('wss://localhost:port'))` to catch events instead of using an HttpProvider?

**Comment by nivida** [comment]
Contract event subscriptions are only possible with an socket provider (MetamaskInpageProvider, EthereumProvider, IpcProvider and WebsocketProvider)
