### ISSUE TITLE
Reconnect on Websocket Drop

### ISSUE THREAD

**Issue by Plinpod** [ethereum/web3.js#1558]
Hello, 

I am making a websocket connection to Infura Ropsten
`wss://ropsten.infura.io/ws`

and then making contract event subscription like so
` contract.events.MyEvent()
        .on('data', function(event) {
            console.log('Event Generated', data)
        })
        .on('error', function(error) {
            console.log('Event Error', error)
        })`

Infuras websockets seem to be unstable and drop randomly. Unfortunately the websocket drops silently in the background and my event never receives the error. My app just continues to work and stops receiving event data. 

I can tell that websocket drops by running `setInterval` on
`web3.eth.net.isListening()`

Is there a graceful way to catch the websocket drop and reconnect immediately? If not what is a safe interval to run isListening on?

Thanks!

**Comment by Dobberoonski75** [comment]
I've been having this issue as well. Is there any sort of `keep-alive` message we can send to prevent disconnects altogether or an `.on('close', (event) => {...})` we can use to detect a dropped connection and open a new one?

**Comment by cmaliwal** [comment]
I am also facing the same issue.I use websocket (ws) coneection to Infura node

`web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ropsten.infura.io/ws"));`

sometimes it's works fine or sometimes it give error on console :

```
Error: CONNECTION ERROR: Couldn't connect to node on WS.

Uncaught (in promise) Error: CONNECTION ERROR: Couldn't connect to node on WS.
```

**Comment by refrigerator** [comment]
Also having this issue. Handling connection in errors using `provider.on('end', err => {...})` and `provider.on('error', err => {...})` doesnt solve it :(

**Comment by ztnark** [comment]
Does anyone have a working solution via polling web3.eth.net.isListening()?
