### ISSUE TITLE
Synchronous "eth_coinbase" call in Node hangs, pegs CPU

### ISSUE THREAD

**Issue by tcoulter** [ethereum/web3.js#156]
I'm using web3 from node, written in CoffeeScript. It seems that whenever I call `web3.eth.coinbase`, the script hangs and pegs the CPU at 100% (it's a laptop, ooh how it burns :) ). Anyway, I created a simple test script to better illustrate the problem:

```coffeescript
web3 = require "web3"

host = "...your eth host..."
port = "...your eth port..."

provider = new web3.providers.HttpProvider("http://#{host}:#{port}")
web3.setProvider(provider)

console.log "Calling eth_coinbase asynchronously..."
provider.sendAsync
  jsonrpc: "2.0"
  method: "eth_coinbase"
  params: []
  id: 1
, (err, result) ->
  # Success
  console.log result

  console.log "Now calling it synchronously..."

  # The following will make the script wait seemingly indefinitely,
  # pegging the CPU to 100%
  console.log web3.eth.coinbase
```

Here's example output:

```
root@1f56ea2bbac4:/src# ./deploy_contracts.coffee 
Setting provider...
Calling eth_coinbase asynchronously...
{ id: 1,
  jsonrpc: '2.0',
  result: '0xd170c0c9d689c7e4bfa9e909c34edc94fb241081' }
Now calling it synchronously...
^C
root@1f56ea2bbac4:/src#
```

I'm using `geth` as my eth client, but I assume that shouldn't matter as the asynchronous call completed successfully. I attempted to wait awhile for the synchronous call to complete, but it never seemed to. 

This seems like a good time to point out that regardless of whether the above issue gets fixed, it'd be a nice addition to add a method, say `getCoinbase`, that takes a parameter allowing this request to be asynchronous. Asynchronicity is the backbone of node and JS; we should allow for it whenever possible.

All tha said, I appreciate your great work so far. Thanks all!

**Comment by kumavis** [comment]
what do you see in the network tab for that request?

**Comment by tcoulter** [comment]
Hmm, unfortunately my environment's a little complex. I'm running the script above within an Ubuntu Docker container that's running within boot2docker on an OS X host. If the Network tab within OS X's Activity Monitor correctly shows traffic from that request, then there's not a whole lot going on: A few kilobytes sent and received per second.

If you know a way I can easily monitor that request from within the container, happy to try.

**Comment by kumavis** [comment]
ah, i was assuming use within a browser, and referring to the browser's network tab.

**Comment by tcoulter** [comment]
Ahhhh, that makes sense. 

I tried it out in Chrome, just in case the behavior might reproduce there. I got the same message as in #44, but it returned fine. Possibly because Chrome didn't actually make an asynchronous call.

![screen shot 2015-04-12 at 10 11 29 pm](https://cloud.githubusercontent.com/assets/92629/7110124/ec9d5156-e160-11e4-8316-e828c108753c.png)

**Comment by kumavis** [comment]
@tcoulter so then you're running on node? do any synchronous methods work for you?

**Comment by tcoulter** [comment]
Hmm, good question. Looks like they don't. Just reproduced the same issue with `web3.eth.mining`.

**Comment by kumavis** [comment]
If you need node.js to support of all ethereum.js, then some debugging may be in order. it might be possible to get the sync calls to work, that would lie somewhere in https://github.com/driverdan/node-XMLHttpRequest

remember to post your node version and resolved version of `XMLHttpRequest` if continuing this quest

**Comment by tcoulter** [comment]
Node v0.12.2
XMLHttpRequest v1.7.0

I'll keep digging into it.

**Comment by tcoulter** [comment]
I haven't figured the crux of this issue out yet, but I just wrote a wrapper to work around it in the mean time: https://github.com/tcoulter/Web3RPC

**Comment by tcoulter** [comment]
@debris Was this closed because of a fix?

**Comment by mjackson001** [comment]
FYI - I identified a similar problem in web3 (node hangs, 100% CPU) and charted out the RPC packet flow by hand from a packet capture using wireshark.  The workaround for me was to force contracts to deploy in series, which turns out to be way faster as well, due to the bugs. More information on what I found on this Google docs spreadsheet:

https://docs.google.com/spreadsheets/d/133YWv7dwVqcfDETK_5SPfu3McMPNvfcMNcVFhZraKqw/edit#gid=0

**Comment by harlantwood** [comment]
I'm still getting the same issue running from Node, both with the latest version on NPM and also from the master branch.

@tcoulter it looks like https://github.com/tcoulter/Web3RPC has been removed, do you have any other recommendations?

**Comment by harlantwood** [comment]
@debris this issue  should probably be re-opened.

**Comment by harlantwood** [comment]
FWIW, your Node.js example at https://github.com/ethereum/web3.js/blob/master/example/node-app.js has this issue, at least in my environment -- it just hangs, never completes.

**Comment by tcoulter** [comment]
@harlantwood 

I'm not sure this will be fixed anytime soon, but it might. It can be fixed it by using a different xhr library.

That said, are you calling `web3.eth.coinbase()` or using `var coinbase = web3.eth.coinbase;? `.coinbase` is a property which makes a synchronous xhr request (why, I don't know). The way to avoid this is to always use asynchronous calls. You can get the same information by using `web3.eth.getCoinbase()` instead.

**Comment by harlantwood** [comment]
I'm now using https://github.com/ConsenSys/ether-pudding via https://github.com/ConsenSys/truffle (links mostly for those who might get here via search), so it's no longer a serious issue for me.  

Having said that, the example should be updated at least, probably with also a note saying that synchronous calls in Node don't work.
