### ISSUE TITLE
can't get public property of contract

### ISSUE THREAD

**Issue by TrejGun** [ethereum/web3.js#1562]
Hi guys how can I get value of public property of contract using web3 1.0.0-beta34?
```js
const oracleContract = new window.web3js.eth.Contract(OracleABI, OracleAddr);
oracleContract.methods.PLATprice().call().then(console.log)
```
this code throws error
```
Returned error: Attempting to run transaction which calls a contract function, but recipient address 0x2339a01f8424d116ff7cf0869c9c37b769ed274f is not a contract address
```
contract code can be found here https://etherscan.io/address/0x2339a01f8424d116ff7cf0869c9c37b769ed274f#code

**Comment by nivida** [comment]
Hay I've tested it and it works as expected and because of that I'll close this issue.
