### ISSUE TITLE
eth_call with no specified `from` parameter

### ISSUE THREAD

**Issue by kumavis** [ethereum/web3.js#157]
what is the prescribed behaviour of `ORIGIN ` op code during an `eth_call` when no `from` parameter is specified ?

**Comment by kumavis** [comment]
@debris so can you still call eth_call without specifying a `from`?

**Comment by debris** [comment]
yes. This behaviour is not specified. It's up to the implementation how its handled. eg. cpp is lenient and do not require `from`.

**Comment by kumavis** [comment]
:+1:
