### ISSUE TITLE
Small spelling error in side bar

### ISSUE THREAD

**Issue by MatthewDLudwig** [ethereum/web3.js#1574]
On the [page](https://web3js.readthedocs.io/en/1.0/web3-utils.html#unitmap) for unitmap the side bar will show an incorrect spelling of "Return Value" instead saying "Retrun value".   This also doesn't fit with the standard for the docs of "Returns".

I didn't want to fork and submit a pull request for something so simple especially considering the difference in format may make the spelling error irrelevant in favor of "Returns".

**Comment by frozeman** [comment]
fixed in #1876
