### ISSUE TITLE
Unable to install Web3 - Windows 10 - npm ERR! No git binary found in $PATH

### ISSUE THREAD

**Issue by par143134** [ethereum/web3.js#1575]
After trying all possible solutions that I could find on the web to the following error I'm already a bit desperate and need your help!

I'm using Windows 10 system and I got the following error when tyring to installing web3:

![err](https://user-images.githubusercontent.com/38649277/39114549-ae304f1e-46ce-11e8-8a7e-6982ef70a013.png)

I tried already to add the path to git's bin in "advanced system settings" as follows:

actual Path:         ;C:\Program Files\Git\cmd
adjusted Path:    ;C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd

Even after adjusting the path I still get the same error.
Would be great if anyone could help me with this issue!

**Comment by williamchong007** [comment]
Does the command `git` runs no problem in your cmd?
If not, you need to fix your git installation

Also since you are on win10, using ubuntu bash on windows would save you much compatibility trouble
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by zeeshanmohiuddin** [comment]
@williamchong007 i also faced the same problem and git command is not working in my cmd

**Comment by nivida** [comment]
Please ask this question on stackoverflow.
