### ISSUE TITLE
web3-eth-abi ReferenceError: name is not defined

### ISSUE THREAD

**Issue by Fi1osof** [ethereum/web3.js#1577]
Error here: https://github.com/ethereum/web3.js/blob/v1.0.0-beta.34/packages/web3-eth-abi/src/formatters.js#L152
Reason: returns param have not name.
.sol:
`function getBalance(address userAddress) public view returns (int){`
Meta:
```
          "name": "getBalance",
          "outputs": [
            {
              "name": "",
              "type": "int256"
            }
          ],
```
With returns name works fine.

**Comment by Fi1osof** [comment]
I was did not correct. Error always when return 0. No error, if >0.

**Comment by adityagoel19** [comment]
facing this error, any idea as to how can I debug and resolve?
