### ISSUE TITLE
Beta-1-33 && Beta-1-34: MyContract.events.MyEvent() working but outputting error

### ISSUE THREAD

**Issue by robrobbins** [ethereum/web3.js#1585]
Working with a compiled EIP20 ethPM "tokens" package:

    `pragma solidity ^0.4.11;

      import "tokens/eip20/EIP20.sol";

      contract CToken is EIP20 {

      }`

Basic testing works fine for transfers balances (various call() and send())...
However, any call to the `Transfer` event (even just trying to get back the eventEmitter) results in:

<img width="406" alt="screen shot 2018-04-24 at 3 26 48 pm" src="https://user-images.githubusercontent.com/60326/39219022-e664abc8-47dc-11e8-92d3-4241c2c81770.png">

Interestingly enough, the event subscription _does_ work. The code below does correctly log the event object from the 'data' event. The code:

<img width="647" alt="screen shot 2018-04-24 at 3 27 16 pm" src="https://user-images.githubusercontent.com/60326/39219058-169781f8-47dd-11e8-87c6-52dae3af0c6e.png">

The output from the console.log:

<img width="628" alt="screen shot 2018-04-24 at 3 27 51 pm" src="https://user-images.githubusercontent.com/60326/39219067-33abcd12-47dd-11e8-85a2-5df3668cbd54.png">

As I said if i take it all the way down to just getting the emitter back, i.e:
    `const emitter = eip20.events.Transfer()`
I do get back the emitter, but also get the same error.

**Comment by nivida** [comment]
This got fixed with https://github.com/ethereum/web3.js/pull/2608 and will be released this week.
