### ISSUE TITLE
App never exits after eth.subscribe call

### ISSUE THREAD

**Issue by colltoaction** [ethereum/web3.js#1586]
I have the following script:

```js
var Web3 = require('web3');
var web3 = new Web3('ws://localhost:8546');

var subscription = web3.eth.subscribe(
    'newBlockHeaders',
    function (err, blockHeader, sub, existingReceipt) {
        console.log("blockHeader", blockHeader);
        subscription.unsubscribe(function() {
            console.log('Successfully unsubscribed!');
        });
    });
```

I run it and see the following:

```
$ node manualtest.js
blockHeader { parentHash: '...',
  sha3Uncles: '...',
  ...
 }
Successfully unsubscribed!
```

**But the node process doesn't exit**. I can't find any other `close()` or `disconnect()` function to call.

**Comment by diega** [comment]
Does anybody know how a websocket connection can be closed explicitly from the client?

**Comment by ubrals** [comment]
@tinchou this may somehow be useful to you and everybody :)

I had this situation on creating contracts. I am using `node smart.js`
I can create a smart contract but node does not exit
Even setting closeTimeout variables to 60 seconds

Anyway

We have to keep in mind that we are working with callback functions. Thus, it must be coded such as you know that the function is going to remain in memory.

So, the code below should create a contract and exit, after creation:
`var iSmart = new web3.eth.Contract(JSON.parse('' + iSmartAbi + ''));
iSmart.deploy({data: iSmartBin, arguments: ['official']})
.send(
  {from: buyer, gas: '1700000', gasPrice: '24000000'}
  , function(error, transactionHash){ console.log('deployment') }
)
  .on('confirmation', function(confirmationNumber, receipt){
     console.log('CONF:' + confirmationNumber)
  })
    if(confirmationNumber > 0){
      iSmart._provider.connection.onclose()
      web3.currentProvider.connection._connection.close()
    }
});

web3.currentProvider.connection.onclose = (function() {
  console.log('bye')
})`

Hope it works for you

Regards,
.

**Comment by nivida** [comment]
The WebsocketProvider got a refactoring and does now support reconnecting and resubscribing. The PR #2000 will fix this issue and add a disconnect method to the provider.
