### ISSUE TITLE
Unsubscribe from listening to events in web3 1.0

### ISSUE THREAD

**Issue by elie222** [ethereum/web3.js#1587]
Is it possible to unsubscribe from listening to events in 1.0?

I don't see anything in the docs or when checking the object in js either:
https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#events

**Comment by imbaniac** [comment]
After calling Contract.events.EventName you get a subscription in response. It has unsubscribe method.

**Comment by pors** [comment]
Does anyone have an example of this? I don't see an unsubscribe method in the Subscription response:

```
Subscription {id: null, callback: ƒ, arguments: Array(1), _reconnectIntervalId: null, options: {…}, …}
arguments: [{…}]
callback: ƒ (_x, _x2)
id: "0x6d7919d45ee718d3322556d20a4086d6"
options: {subscription: {…}, type: "eth", requestManager: RequestManager, params: {…}}
subscriptionMethod: "logs"
_reconnectIntervalId: null
__proto__: EventEmitter
```

I'm using web3 version 1.0.0-beta.36

**Comment by likwrk** [comment]
@pors it's under prototype
```
_reconnectIntervalId: null
​arguments: Array [ {…} ]
​callback: function _on()
​id: "0x0dfc42cec71a4745"
​options: Object { subscription: {…}, type: "eth", requestManager: {…}, … }
​subscriptionMethod: "logs"
​<prototype>: {…}
    _extractCallback: function _extractCallback()
    _formatInput: function _formatInput()
    ​​_formatOutput: function _formatOutput()
    ​​_toPayload: function _toPayload()
    ​​_validateArgs: function _validateArgs()
    ​​constructor: function Subscription()
    ​​subscribe: function subscribe()
    ​​unsubscribe: function unsubscribe()
```

**Comment by mswezey23** [comment]
> Does anyone have an example of this? I don't see an unsubscribe method in the Subscription response:
> 
> ```
> Subscription {id: null, callback: ƒ, arguments: Array(1), _reconnectIntervalId: null, options: {…}, …}
> arguments: [{…}]
> callback: ƒ (_x, _x2)
> id: "0x6d7919d45ee718d3322556d20a4086d6"
> options: {subscription: {…}, type: "eth", requestManager: RequestManager, params: {…}}
> subscriptionMethod: "logs"
> _reconnectIntervalId: null
> __proto__: EventEmitter
> ```
> I'm using web3 version 1.0.0-beta.36

1) the `unsubscribe` method does exist
2) when the `id` is still `null`, unsubscribe doesn't work fully (callbacks are still functioning)

**Comment by maroodb** [comment]
any solution ?

**Comment by amitOodles** [comment]
@imbaniac @nivida @elie222 , I wanted to know what is the use of unsubscribe ? Is it required that i should unsubscribe my contract subscription after some time interval?

**Comment by pom421** [comment]
This is painful for React useEffect indeed.

My solution, thanks to previous hint: 

```jsx

    const currentBlock = await web3.eth.getBlockNumber()
   
    const listener = await contract.events.VoterRegistered({
      fromBlock: currentBlock,
    })

    listener.on("data", (event) => {
      setVoters((voters) => [...voters, event.returnValues.voterAddress])
    })

    // This way, you can unsubscribe with
    listener.unsubscribe()
   
    // For example in return of React's useEffect
    return () => listener.unsubscribe()
```
