### ISSUE TITLE
HTTP Basic Authentication not working

### ISSUE THREAD

**Issue by narayanprusty** [ethereum/web3.js#1589]
Here is the code I am using to connect to nginx that is in front of geth RPC:

```
let web3 = new Web3(
			    new Web3.providers.HttpProvider(
			    	'http://' + "mmqfxnxe" + ':' + "mmqfxnxe" + '@'+ "52.43.83.54/mmqfxnxe" + ':' + "31988"
			    )
			)

            console.log(web3.isConnected())
```

It says 401 error. if i try to open "52.43.83.54/mmqfxnxe:31988" directly from browser and enter creds then it works. Why web3js is failing?

**Comment by jacksonng77** [comment]
Hi Narayan, I am hit with the same problem. Wondering if you managed to solve it?

**Comment by web3rover** [comment]
@jacksonng77 this works in 0.20.*

`let web3 = new Web3( new Web3.providers.HttpProvider("url", 0, "username", "password") );
`

**Comment by jacksonng77** [comment]
> @jacksonng77 this works in 0.20.*
> 
> `let web3 = new Web3( new Web3.providers.HttpProvider("url", 0, "username", "password") ); `

Thanks Narayan, but I needed it working with Web3.js 1.0.

I found the solution, it involves making some some changes to \node_modules\web3-providers-http\src\index.js.

I passed the authorization to HttpProvider as a header like this.

`new Web3(new Web3.providers.HttpProvider('https://node-url',0,{Authorization: 'Basic myauthenticationstring'}))`

And then at \node_modules\web3-providers-http\src\index.js., i changed the following
```
HttpProvider.prototype._prepareRequest = function(){
    var request = new XHR2();

    request.open('POST', this.host, true);
    request.setRequestHeader('Content-Type','application/json');

    if(this.headers) {
                                request.setRequestHeader(Object.keys(this.headers)[0], Object.values(this.headers)[0]);
                                /*
        this.headers.forEach(function(header) {
                                                console.log(Object.keys(header.headers));
                                                console.log(Object.values(header.headers));
            //request.setRequestHeader(header.name, header.value);
        });
                                */
    }
                
    return request;
};
```
