### ISSUE TITLE
Impossible to pass default block when calling contract function

### ISSUE THREAD

**Issue by Georgi87** [ethereum/web3.js#159]
I can pass the default block to the call function like described in the documentation:

web3.eth.call(callObject [, defaultBlock] [, callback]);

However if I call a function on my contract I dont see any possibility to pass the defaultblock:

contract.call().function_name();

**Comment by frozeman** [comment]
Shouldn't you be able to call then:

`contract.call({} [, defaultBlock] [, callback]).function_name();`
?

Btw we are restructuring the way to call contract method.

**Comment by frozeman** [comment]
We restructured it, but you still cant pass the defaultBlock or callback, we will fix it see https://github.com/ethereum/web3.js/issues/192

**Comment by Georgi87** [comment]
Thanks! I saw you changes and noticed it didn't have any effect, when I passed the "pending" block.
