### ISSUE TITLE
How to call the function of my smart-contract with web3 1.0-beta.34 correctly?

### ISSUE THREAD

**Issue by titancat** [ethereum/web3.js#1592]
```
myContract.deployed().then((instance) => {
  let myInstance = instance
  myInstance.myfunc.sendTransaction().then((rs) => {
    console.log(rs)
  })
})
```

It works. But if I want to add some event emitters like [this](https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendtransaction)

```
myContract.deployed().then((instance) => {
  let myInstance = instance
  myInstance.myfunc.sendTransaction().on('confirmation', function(hash) {
    console.log(hash)
  })
})
```
I got a error: `sendTransaction(...).on is not a function`
How to add  event emitters correctly?

**Comment by tinchoabbate** [comment]
Have you tried following [the examples on the docs](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send) ?

**Comment by nivida** [comment]
```myInstance.myfunc().send({from: from}).on(...)``` would be the correct usage of the web3.js API.
