### ISSUE TITLE
Web3 give an error if i try to get an ENTIRE solidity list of a struct 

### ISSUE THREAD

**Issue by Giulio2002** [ethereum/web3.js#1595]
Example :

`
contract example{

      struct myStruct{
           uint one;
           uint two;
     }
     myStruct[] private list;
     //if i call this i get an error
    function getList() constant returns(myStruct[]){
           return list;
     }
}

`

**Comment by Giulio2002** [comment]
i get invalid type tuple

**Comment by nivida** [comment]
Type tuple will be supported in the next web3.js 1.0 version.
