### ISSUE TITLE
error TS2305: Module ''bn.js'' has no exported member 'BigNumber'

### ISSUE THREAD

**Issue by leoplct** [ethereum/web3.js#1596]
I am following this tutorial: https://0xproject.com/wiki#Create,-Validate,-Fill-Order

When I run 

> yarn run order_actions

I get this error

    yarn run v1.6.0
    $ run-s build tutorial:order_actions
    $ tsc
    node_modules/web3/types.d.ts(1,10): error TS2305: Module ''bn.js'' has no exported member 'BigNumber'.
    node_modules/web3/types.d.ts(1,27): error TS2497: Module ''bn.js'' resolves to a non-module entity and cannot be imported using this construct.
    error Command failed with exit code 2.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ERROR: "build" exited with 1.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**package.json**

    {
        "name": "0xStarterProject",
        "version": "0.1.0",
        "description": "",
        "scripts": {
            "order_actions": "run-s build tutorial:order_actions"
    ....

```
"dependencies": {
        "0x.js": "0.36.3",
        "@0xproject/connect": "^0.6.10",
        "@0xproject/tslint-config": "^0.4.16",
        "@0xproject/utils": "^0.5.2",
        "@types/underscore": "^1.8.8",
        "body-parser": "^1.18.2",
        "express": "^4.16.2",
        "web3": "^1.0.0-beta.34",
        "websocket": "^1.0.25"
    }
```

**Comment by freeatnet** [comment]
Looks like this was solved here: https://github.com/0xProject/0x-starter-project/issues/11#issuecomment-386889563

**Comment by emkman** [comment]
@freeatnet It isn't clear to me what the resolution is besides trying to change web3 version or delete some relative folder. Can you elaborate? I am using ` "web3": "^1.0.0-beta.34"` and `"@types/web3": "^1.0.0"`

**Comment by emkman** [comment]
Following up, it looks like the suggestion is to delete the type definitions from `node_modules/web3`. This solves the error but is just a workaround and not a solution correct? Is the ultimate goal to update the type definitions in the `web3` package?

**Comment by freeatnet** [comment]
@emkman There are now proper type definitions available through DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26031), along with an guide to using them here: https://github.com/ethereum/web3.js/issues/1658#issuecomment-395662469. There's also a request to remove type definitions from web3.js itself: https://github.com/ethereum/web3.js/issues/1658.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
