### ISSUE TITLE
signTransaction gives 'Must provide "signTransaction" fn in constructor option' error

### ISSUE THREAD

**Issue by ArvsIndrarys** [ethereum/web3.js#1599]
For my project, I need to do some offline transaction signing, before sending the result to the backend, which will send them. But I am encountering the following error : 
```
Error: Error: ProviderEngine - HookedWalletSubprovider - Must provide "signTransaction" fn in constructor options
    at HookedWalletSubprovider.signTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:18092)
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:486)
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:486)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:456
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:18092
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:459
...
```
I currently have : 
```
> web3.version
{api: "0.20.3", getNode: ƒ, getNetwork: ƒ, …}
```
And I saw it in : https://github.com/ethereum/web3.js/blob/6d3e61a010501011a107a79574cc7516900fa9e4/lib/web3/methods/eth.js#L205
and (outdated) : https://web3js.readthedocs.io/en/1.0/web3-eth.html#signtransaction

I am clueless about how to resolve it as it don't seem to be due to my code... Can somebody help?

**Comment by ArvsIndrarys** [comment]
I am using Metamask, which use Infura, for testing my app, so I am almost sure it isn't an ethereum client problem.

**Comment by jetpack3331** [comment]
@ArvsIndrarys  I have signTransaction implemented like this:

`signTransaction: async (txParams, cb) => {
   // Fetch private key as u want
    const res = await wallets.fetchPrivateKey(txParams.from);
    const privateKey = typeof res.result !== 'undefined' ? res.result : res;
    const gasPrice = await web3.eth.getGasPrice();

    const txObject = {
      from: txParams.from,
      to: txParams.to,
      data: txParams.data,
      gasPrice: web3.utils.toHex(gasPrice),
      gasLimit: web3.utils.toHex(gasLimit),
      value: '0x00',
      nonce: txParams.nonce,
      chainId: <NETWORKID>, // see: https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids
    };

    const tx = new Tx(txObject);
    tx.sign(Buffer.from(privateKey, 'hex'));
    try {
      const serialized = tx.serialize();
      cb(null, `0x${serialized.toString('hex')}`);
    } catch (error) {
      console.log({ error });
    }

  },`

**Comment by ArvsIndrarys** [comment]
As my code would be expected to go to production and of public use, I won't accept extracting the private key because of security breach. 
This method would extract and use Metamask under the hood without giving access to this key.

**Comment by jetpack3331** [comment]
@ArvsIndrarys of course, but if you can't use MetaMask or Ledger or something and u have your own methods tosigning, there is probably no other way. Ofc better is to have it on API hidden from browser

**Comment by jetpack3331** [comment]
@ArvsIndrarys It wasnt abandoned. 
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign is documentation for 0.2x.x

In version 1.0.0 there is signTransaction method

**Comment by ArvsIndrarys** [comment]
My bad, I don't know know about my first problem then... `Must provide "signTransaction" fn in constructor options` is obscure to me

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
