### ISSUE TITLE
Why web3.js doesn't have eth_getFilterChanges API anymore for http rpc nodes

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#1604]
web3.py has such awesome feature called:
https://web3py.readthedocs.io/en/stable/filters.html#web3.utils.filters.Filter.get_new_entries

```
Retrieve new entries for this filter.

Logs will be retrieved using the web3.eth.Eth.getFilterChanges() which returns only new entries since the last poll.
```

How  come web3.js 1.0 doesn't have anything  like it that would work with http/https? 

it seems to me that web3.js enforces users to switch to websockets which  is not available for example in infura kovan chain.

**Comment by nivida** [comment]
Yes, HTTP 1.0 does not support subscriptions. 

Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.

**Comment by rstormsf** [comment]
Do I read this correctly, that it means web3.js will never implement such feature?
