### ISSUE TITLE
npm install failed web3

### ISSUE THREAD

**Issue by SanghyukYi** [ethereum/web3.js#1606]
C:\project\node_demon>npm install -g web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Suppor
t
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecat
ed and your application is vulnerable. Please use tar module instead: https://np
mjs.com/tar
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\3\AppData\Roaming\npm-cache\_logs\2018-05-03T10_16_10_983Z
-debug.log
-------------------------------------------------------------------------------
[debug.log]

798 silly fetchPackageMetaData error for websocket@git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible No git binary found in $PATH
799 verbose stack Error: No git binary found in $PATH
799 verbose stack     at checkGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:203:17)
799 verbose stack     at spawnGit (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:182:10)
799 verbose stack     at pinflight (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\git.js:114:12)
799 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
799 verbose stack     at Promise._execute (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\debuggability.js:303:9)
799 verbose stack     at Promise._resolveFromExecutor (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:483:18)
799 verbose stack     at new Promise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:79:10)
799 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
799 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
799 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
799 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
799 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
799 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
799 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
799 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
799 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
800 verbose cwd C:\project\node_demon
801 verbose Windows_NT 6.1.7601
802 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "web3"
803 verbose node v8.9.4
804 verbose npm  v5.6.0
805 error code ENOGIT
806 error No git binary found in $PATH
807 error Failed using git.
807 error Please check if you have git installed and in your PATH.
808 verbose exit [ 1, true ]

**Comment by ikhemissi** [comment]
Some dependencies require `git` to be installed, for example https://github.com/ethereum/web3.js/blob/develop/package.json#L11 and the one you have in the error message above:
```
websocket@git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible No git binary found in $PATH
```

install [git](https://git-scm.com/download/win) and it will work better (you may need to do extra steps in windows like adding it to your path) 
by the way, I don't recommend installing `web3` as a global package, it is not a command line after all.
