### ISSUE TITLE
Question - how to get currentProvider HTTP URL?

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/web3.js#1607]
Hi,

How do I get web3 `currentProvider` HTTP URL? I'm using web3 `1.0.0-beta.34`. I tried many functions and already looked at the docs -- but still couldn't find the right way to get the URL of the current HTTP RPC node.

The pseudocode that I'm looking for:

```
if (is_using_http_rpc_fn) {
  return currentProvider.url;
}
```

What functions to call for `is_using_http_rpc_fn` and `currentProvider.url` in above pseudocode?

**Comment by nivida** [comment]
For getting the current host use: ```web3.eth.currentProvider.host``` please ask further questions on https://ethereum.stackexchange.com/

**Comment by barakman** [comment]
@nivida : In web3.js v1.3 (and maybe also prior that version), it seems to be:
```
web3.eth.currentProvider.wrappedProvider.host
```

**Comment by Garito** [comment]
I can't make this work
Any update?
