### ISSUE TITLE
Error after update rxjs v6

### ISSUE THREAD

**Issue by SShushmintcev** [ethereum/web3.js#1611]
After update angular and rxjs to v6

ng build

WARNING in ./node_modules/asn1.js/lib/asn1/api.js
Module not found: Error: Can't resolve 'vm' in '******\toh-pt6\node_modules\asn1.js\lib\asn1'

ERROR in ./node_modules/eth-lib/lib/bytes.js
Module not found: Error: Can't resolve 'crypto' in '******\toh-pt6\node_modules\eth-lib\lib'
ERROR in ./node_modules/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js
Module not found: Error: Can't resolve 'crypto' in '******\toh-pt6\node_modules\web3-eth-accounts\node_modules\eth-lib\lib'
ERROR in ./node_modules/web3-eth-accounts/src/index.js
Module not found: Error: Can't resolve 'crypto' in '******\toh-pt6\node_modules\web3-eth-accounts\src'
ERROR in ./node_modules/browserify-sign/browser/index.js
Module not found: Error: Can't resolve 'stream' in '******\toh-pt6\node_modules\browserify-sign\browser'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '******\toh-pt6\node_modules\cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in '******\toh-pt6\node_modules\hash-base'

**Comment by Pedro-vk** [comment]
I'm having the same problem with similar libraries (like `web3-eth-accounts`). But I think that the problem comes from Angular upgrade and the webpack configuration.

**Comment by kmturley** [comment]
Related issue here:
https://github.com/ethereum/web3.js/issues/1555

Workarounds suggested:

- downgrade to Angular 5
- try upgrading NodeJS version which includes crypto
- download the build files from the [releases](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.33) page, copy the source to app/src and include it on scripts property of the angular.json config

I tried these, and they didn't work for me! From what I understand it's an issue with the typings file. Or a dependency.

My workaround was to downgrade to an older version of web3:
`npm install web3@0.20.5`

**Comment by Pedro-vk** [comment]
Another workaround is the suggested here: angular/angular-cli#1548 (comment)
It replaces the webpack config of `@angular/cli`

**Comment by kmturley** [comment]
The solution with the patch worked for me!
https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

```
node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js
node: {crypto: true, stream: true}
```

**Comment by SShushmintcev** [comment]
@Pedro-vk Thanks. It is working for me
