### ISSUE TITLE
About the WebSocket.

### ISSUE THREAD

**Issue by reanox** [ethereum/web3.js#1612]
In the WebSocket-Node

https://github.com/frozeman/WebSocket-Node/blob/master/lib/WebSocketFrame.js#L256

`maskKey = nullMask ? 0 : (Math.random()*0xFFFFFFFF) | 0;`

To above out of range,change to
`maskKey = nullMask ? 0 : ((Math.random() * 0xFFFFFFFF) >>> 0);`
or Update WebSocket-Node to the latest version?

Thx

**Comment by BenjaminSchaaf** [comment]
I'm experiencing the same issue.

An update to the latest `websocket` would solve this. Currently websockets are completely unusable due to this.

**Comment by nivida** [comment]
@frozeman we should update your fork to the latest version of WebSocket-Node.

**Comment by frozeman** [comment]
web3-providers-ws is using the `browserifyCompatible` branch: "git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible"

In line:
https://github.com/frozeman/WebSocket-Node/blob/browserifyCompatible/lib/WebSocketFrame.js#L256
There is this fix already in, and its update with upstream. maybe you need to clear your `node_modules` folder, and rerun `npm install`?

**Comment by frozeman** [comment]
Please re-open if its still an issue.
