### ISSUE TITLE
web3.eth.getTransactionReceipt returns status being a string instead of boolean

### ISSUE THREAD

**Issue by jerryji** [ethereum/web3.js#1614]
according to 1.0 document, the "status" returned by web3.eth.getTransactionReceipt should be a boolean --

```
var receipt = web3.eth.getTransactionReceipt('0x9fc76417374aa880d4449a1f7f31ec597f00b1f6f3dd2d66f4c9c6c445836d8b').then(console.log);
> {
  "status": true,
```

However, what actually returned is a string, "0x1" (for true) or "0x0" (for false) --

```
    const Web3 = require('web3');
    let provider = new Web3.providers.HttpProvider("https://mainnet.infura.io/<apiKey>");
    let web3 = new Web3(provider);
    web3.eth.getTransactionReceipt(''0xc889aac1552dd93eb9ae8f3b96c671870ffb293651df0f9f8765236a8757a9ef)
    .then(txObj => {
        console.log(typeof txObj.status); // logs "string"
    });
```
Is it a bug?

**Comment by seesemichaelj** [comment]
Per the [JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-31): `status: QUANTITY either 1 (success) or 0 (failure)`, and the example below then states: `status: '0x1'`

The web3 [code](https://github.com/ethereum/web3.js/blob/1271b7b37f4a68b6ba2276c2e4d39593a3bbf753/packages/web3-core-helpers/src/formatters.js#L219-L221) and [docs](http://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-gettransactionreceipt-return) do both state it as a `Boolean`, so it'd be a bug if you're getting a `string` (I may as well; I will double check).

However, I believe it should be a hex string per the JSON-RPC

**Comment by seesemichaelj** [comment]
Verified I'm only receiving `boolean`s on status. My version is `1.0.0-beta.34`. Please verify your version @jerryji (`npm list web3`) as the boolean stuff was added somewhat recently (April 13th)

**Comment by jerryji** [comment]
@seesemichaelj  I confirm that status is boolean now -- not exactly sure how I got the '0x..' string previously, could be due to the web3 0.2 that comes default with truffle -- thank you very much for your time and sorry for the confusion.
