### ISSUE TITLE
web3.eth.getTransactionReceipt not working as expected on Node >= 8

### ISSUE THREAD

**Issue by Temeteron** [ethereum/web3.js#1617]
I just update my ubuntu distribution to 18.04 which runs node 8+. My implementation works just fine on node < 8. The error that  occurs when calling the previous function is:
```
Invalid JSON RPC repsonse: ""
```
I am testing the same code in other distributions with node < 8 and it is working perfectly. This error occurs sometimes because of the open files limit, but i have increased that enough.

Thus, i think its a bug of the specific function. If i re-call my function less and less errors occurs. There is no pattern on the error. For 1000 calls on that function at least the 500 will return "invalid".

**Comment by nivida** [comment]
Please provide some more informations :) @Temeteron
