### ISSUE TITLE
Language used in documentation for getPastEvents is unclear [1.0.0-beta.34]

### ISSUE THREAD

**Issue by dskvr** [ethereum/web3.js#1619]
From [documentation](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#getpastevents)

```
fromBlock - Number (optional): The block number from which to get events on.
toBlock - Number (optional): The block number to get events up to (Defaults to "latest").
```

This is ambiguous, when dealing with indices, it should be made 100% clear what the functionality entails. I'm trying to debug something, and finding it difficult to confirm the functionality.

The language above could technically mean any of the following.
* result > fromBlock && result < toBlock
* result > fromBlock && results <= toBlock
* result >= fromBlock && results < toBlock
* result >= fromBlock && results <= toBlock (what I assume documentation means, but the uncertainty is unsettling) 

Please confirm, and consider using gte/lte/lt/gt terminology in the docs for these types of methods.

Cheers

**Comment by shalen-original** [comment]
True, I also had problem with this.
Additionally, I would add that the `fromBlock` parameter does not default to zero: if you actually want all past events, you have to set it manually. 

I would have some time in the next days to update that part of the documentation, if someone is able to provide clarification. Should I prepare a pull request or what?

**Comment by wbt** [comment]
As an inquiry, is additional documentation also appropriate for [web3.eth.subscribe\(“logs”\)](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-logs) and/or [web3.eth.Contract.events](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events)?
