### ISSUE TITLE
web3 send amount between account get Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by willieyang1979** [ethereum/web3.js#1620]
I'm very begin in web3. 
Follow a example online and create a simple dapp

contract
'contract MetaCoin {
    mapping (address => uint) balances;
    constructor() public {
    // constructor
    balances[tx.origin] = 500000;
  }

    function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
        if (balances[msg.sender] < amount) return false;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        return true;
    }
    function getBalance(address addr) public view returns(uint) {
    return balances[addr];
    }
}
`

in app.js
`web3.eth.getAccounts(function(error, accounts) {
        if (error) {
          console.log(error);
        }
        var account = accounts[0];
        App.contracts.Coin.deployed().then(function(instance) {
          coinInstance = instance;
          console.log(coinInstance);
          //return coinInstance.getBalance(account);
          var amount = web3.toWei(10, "ether");
          return coinInstance.sendCoin(accounts[1],amount);
        }).then(function(data) {
           console.log(data);
        }).catch(function(err) {
          console.log(err.message);
        });
      });
`

I run this on my local window10, with metamask. other functions are fine, just when send amount, always give this error.

please help!

thanks

**Comment by willieyang1979** [comment]
when I try run in truffle console, is ok
truffle(development)> cont.sendCoin(web3.eth.accounts[1],2)

**Comment by nivida** [comment]
Please ask your question on https://ethereum.stackexchange.com/
