### ISSUE TITLE
Setting option "gasLimit" does not work

### ISSUE THREAD

**Issue by kk3hi3123** [ethereum/web3.js#1621]
Hello. There is version 0.20.3. I am trying to call a contract method and set the gas required. It works well with options like "value" and "gasPrice". However, gasLimit always return 0 after I set a value for it. How to set the gasLimit? Is there any careless mistake?

```
myContract.myMethod("These are some params", 
{from: web3.eth.accounts[0],
 value: value,
 gasLimit: "1000000",
 gasPrice: gasPrice},
 function (err, result) { ... })
```

<img width="806" alt="2018-05-10 2 47 43" src="https://user-images.githubusercontent.com/20828545/39833470-b40fd4f0-53fc-11e8-8124-7706c4729b7b.png">

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
