### ISSUE TITLE
Stronger wording in docs re 1.0.0 and current limitations? 

### ISSUE THREAD

**Issue by jmahhh** [ethereum/web3.js#1623]
Hey @frozeman, just a heads up that I'm seeing a fair amount of web3 1.0 questions on stackexchange - npm installs 1.0 by default even though according to the documentation it's not ready for release yet. 

As such you may want to give a stronger warning in the docs, possibly advising people to downgrade to 
0.20.6 if they're looking for a stable and well-documented version? Just thinking out loud.

**Comment by nanspro** [comment]
There is warning note on the GettingStarted Page so we can just add a npm link there to 0.20.6!!
