### ISSUE TITLE
Getting "Error: Invalid chain id." on sendRawTransaction in eth methods

### ISSUE THREAD

**Issue by amirsimhi** [ethereum/web3.js#1633]
I'm trying to send transaction and getting "Error: Invalid chain id."

this is the code  how I build the raw transaction:

`
signedTransaction.r = EthereumUtils.toBuffer(EthereumUtils.addHexPrefix(response.r));
signedTransaction.s = EthereumUtils.toBuffer(EthereumUtils.addHexPrefix(response.s));
signedTransaction.v = EthereumUtils.toBuffer(EthereumUtils.addHexPrefix(response.v));
let tx = new EthereumTx(signedTransaction);
const serializedTx = tx.serialize();
const rawTx = '0x' + serializedTx.toString('hex');
`

The signed transaction looks like:
{
chainId: 1,
data:"0xf0843ba900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000096245e72a00000000000000000000000000000000000000000000000000000001dac9a5e414900000000000000000000000000000000000000000000000000000000000000050000000000000000000000000e66591a568c6e1537528617c4c1e651244cb7c4d00000000000000000000000060a221e002bcde48ac8620c018599a904318117f00000000000000000000000060a221e002bcde48ac8620c018599a904318117f000000000000000000000000df73c600d8d47bfd3f0c9eeb25d8c84bb7995033000000000000000000000000df73c600d8d47bfd3f0c9eeb25d8c36bb7995033", from:"0xbb58920ac8da844a39eb7cc747db25650d8545d2" ,
gas:"0x81d78" ,
gasPrice:"0x12a05f200" ,
nonce:"0x0",
 r:"0x5fca7b5662638a69dacd84a5be3988f8e8adeb1bb95823a490b9377766eaba96",
s:"0x6cfef449a7cdde0091efb0bf8e47522e23019a5d4a29bcbca4cf8684266f52af",
to:"0x996e114d5a591ace6ab4d5ca751dcd80ab87873d",
 v:"0x25" ,
value:"0x9184e72a000"
}

Does anyone know why I'm getting this error?

Thanks a lot!

**Comment by oliversd** [comment]
Are you doing this transaction on the Mainnet? You have to set the ChainID according to the Chain that you are using Mainnet, Rinkeby, Ropsten, etc.

You can see more here [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)

**Comment by nivida** [comment]
I close this issue because no further information has been added.
