### ISSUE TITLE
Node >= 10 c++ compilation failed

### ISSUE THREAD

**Issue by ellis2323** [ethereum/web3.js#1634]
Error with:
../src/addon.cpp:59:36: error: no matching member function for call to 'NewInstance'
                        info.GetReturnValue().Set(cons->NewInstance(argc, argv));
Probably same fix as:
https://github.com/phusion/node-sha3/pull/33/commits/3da944ecef0d4732739f7f121b6238cac6bbcd33

**Comment by ellis2323** [comment]
If you force sha3 in package-lock.json with 1.2.1. It works.... I'm using web3-utils 1.0.0-beta.34

**Comment by nivida** [comment]
In which package-lock have you changed the version?

**Comment by nivida** [comment]
I've updated all dependencies in the latest version of web3.
