### ISSUE TITLE
Bytes encoding not consistent for empty bytes

### ISSUE THREAD

**Issue by rmeissner** [ethereum/web3.js#1635]
### Expected behaviour
Using `0`, `""` and `"0x"` should return the same payload. 
The expected payload would be 32 zero-bytes (`0000000000000000000000000000000000000000000000000000000000000000`)

### Actual behaviour
Using `0` or `""` returns `00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

while using `"0x"` return `0000000000000000000000000000000000000000000000000000000000000000`

### Version
npm list web3 -> web3@0.20.6 

### Steps to reproduce
```
const f = require('./web3/lib/solidity/formatters')
f.formatInputBytes('')
> SolidityParam { value: '0000000000000000000000000000000000000000000000000000000000000000', offset: undefined }
f.formatInputBytes("0x")
> SolidityParam { value: '', offset: undefined }

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
