### ISSUE TITLE
The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by cmaliwal** [ethereum/web3.js#1637]
I am trying to send the args on function from owner account but getting Returned error.

I am using [web3 1.0](https://github.com/ethereum/web3.js/blob/1.0/dist/web3.min.js) .

**Function in contract :**

```
/**
* @dev Adds single address to whitelist.
* @param trusted Address to be added to the whitelist
*/
function addToWhiteList(address trusted) public onlyOwner {
    require(!whitelist[trusted]);
    whitelist[trusted] = true;

    emit UserWhitelist(true);
}
```
**Code on index.html :**

```
// Add user on whitelist
abc.methods.addToWhiteList("0x9DA80947ACf5Fc16299311EdAabc37fF7d201C95")
.send({ from: "0x61A44075419C4402f6DE631341d875Ece6A3922e" })
.on("receipt", function(receipt) {
  console.log(receipt);
})
.on("error", function(error) {
  console.error(error);
});
```
**ERROR :** `Returned error: The method eth_sendTransaction does not exist/is not available`

**Note :** I add web3 in script tag :

`<script language="javascript" type="text/javascript" src="web3.min.js"></script>`

**and init. like this** 

`web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ropsten.infura.io/ws"));`

**Note :**  

- Node : v8.10.0
- NPM : 5.6.0
- OS : Ubuntu 
- Truffle v4.1.6 (core: 4.1.6)
- Solidity v0.4.21 (solc-js)

**Comment by masterviana** [comment]
Same thing happen with me on version ^1.0.0-beta.34. 

Try to call .send method, this is the log :
`{ jsonrpc: '2.0',
  id: 0,
  error:
   { code: -32601,
     message: 'The method eth_sendTransaction does not exist/is not available' } }`

**Comment by hadarbmdev** [comment]
I've reproduced the same issue,web3 version: 1.0.0-beta.34, using infura ropsten as external provider.

this is after following the PKEY tip:
[ https://ethereum.stackexchange.com/questions/26999/invalid-json-rpc-response-error-for-sendtransaction-on-infura-ropsten-node-t]( https://ethereum.stackexchange.com/questions/26999/invalid-json-rpc-response-error-for-sendtransaction-on-infura-ropsten-node-t)

used:

`this.web3.eth.accounts.wallet.add(this.pkey)`

`this.walletOwnerAddress = '0x'+ethUtils.privateToAddress(ethUtils.toBuffer('0x' + this.pkey)).toString('hex')
`

`this.web3.eth.defaultAccount = this.walletOwnerAddress`

`this.web3.eth.sendTransaction({ to: toAddr, value: this.web3.utils.toWei("0.1", "ether") })`

**Comment by webkonglong** [comment]
我也遇到了这个问题，如何解决呢。

**Comment by webkonglong** [comment]
> I am trying to send the args on function from owner account but getting Returned error.
> 
> I am using [web3 1.0](https://github.com/ethereum/web3.js/blob/1.0/dist/web3.min.js) .
> 
> **Function in contract :**
> 
> ```
> /**
> * @dev Adds single address to whitelist.
> * @param trusted Address to be added to the whitelist
> */
> function addToWhiteList(address trusted) public onlyOwner {
>     require(!whitelist[trusted]);
>     whitelist[trusted] = true;
> 
>     emit UserWhitelist(true);
> }
> ```
> **Code on index.html :**
> 
> ```
> // Add user on whitelist
> abc.methods.addToWhiteList("0x9DA80947ACf5Fc16299311EdAabc37fF7d201C95")
> .send({ from: "0x61A44075419C4402f6DE631341d875Ece6A3922e" })
> .on("receipt", function(receipt) {
>   console.log(receipt);
> })
> .on("error", function(error) {
>   console.error(error);
> });
> ```
> **ERROR :** `Returned error: The method eth_sendTransaction does not exist/is not available`
> 
> **Note :** I add web3 in script tag :
> 
> `<script language="javascript" type="text/javascript" src="web3.min.js"></script>`
> 
> **and init. like this**
> 
> `web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ropsten.infura.io/ws"));`
> 
> **Note :**
> 
> * Node : v8.10.0
> * NPM : 5.6.0
> * OS : Ubuntu
> * Truffle v4.1.6 (core: 4.1.6)
> * Solidity v0.4.21 (solc-js)

-----------------------------------

这个问题是 web3.js的版本不对。
删除node_modules。从新安装0.20.4版本的web3就行

附上代码

### web3.js
`import Web3 from 'web3';

const web3Provider = window.web3 ? window.web3.currentProvider : null;

const web3 = web3Provider
  ? new Web3(web3Provider)
  : new Web3(new Web3.providers.HttpProvider('https://ropsten.infura.io/v3/d5686d6d07d0421eb166c521250af71b'));

web3.eth.defaultAccount = web3.eth.accounts[0];

export default web3;`

### api.js
`import { BigNumber } from 'bignumber.js';
import web3 from './web3';
import Promise from 'bluebird';

const myContract = web3.eth.contract(abi.abi).at('合约地址');

export const buyItem = (id, price) => new Promise((resolve, reject) => {
  cryptoWaterMarginContract.bid(id, {
    value: price, 
    gas: 220000,
    gasPrice: 1000000000 * 100,
  },
  (err, result) => (err ? reject(err) : resolve(result)));
});
`
### 页面调用合约

`import { buyItem } from './api.js'
buyItem(2, 1000000000000000000).then(resp => {
      console.log(resp, 'success');
    }).catch(e => {
      console.log(e, 'error');
    })
`

**Comment by webkonglong** [comment]
回退web3版本为 0.20.4。   1.0.0-beta.34版本确实有这个问题，拿用户私钥绕过钱包服务端签名也不行 ，会出现 交易哈希，但是区块链查询不到，矿工很久没有被挖矿。

demo地址  https://github.com/LinkIdol/eth-dapp-demo

**Comment by OFRBG** [comment]
Infura doesn't support sending non-raw transactions. See: https://infura.io/docs/ethereum/json-rpc/eth_sendRawTransaction
