### ISSUE TITLE
Deployed contract's address is undefined

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/web3.js#1641]
## Context
I'm compiling a sol file and trying to deploy it to a local testnet without truffle. The smart contract is a simple token, taken from this [article](https://blog.zeppelin.solutions/a-gentle-introduction-to-ethereum-programming-part-2-7bbf15e1a953).

## Expected
I should be able to get an address after running `MyTokenContract.new(contractData)`.

## Behaviour
The value of `deployedContract.address` is undefined.

## Reproduce
Source code can be found [here](https://github.com/PaulRBerg/web3.js-undefined-address). Using solcjs 0.4.23, web3.js 0.20.6 and Ganache 1.1.0

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
