### ISSUE TITLE
filter.watch notified multiple times

### ISSUE THREAD

**Issue by karalabe** [ethereum/web3.js#165]
I am running this simple code with the latest web3.js (+my fix #164) and against the go-ethereum client.

```javascript
var web3 = require('web3')
var shh  = web3.shh
var rpc  = new web3.providers.HttpProvider("http://localhost:8545")

web3.setProvider(rpc)

shh.filter({}).watch(function(err, msg) {
	console.log("Error:", err)
	console.log("Message:", msg)
})
shh.post({payload: "Hi whisper"})
```

However, the message is received/reported twice by web3. I checked the latest whisper code (https://github.com/karalabe/go-ethereum/tree/whisper-cleanup) and it notifies its listener a single time of an event, so it would seem that somewhere web3 duplicates the events.

```javascript
Error: null
Message: { payload: 'Hi whisper',
  to: '0x0',
  from: '0x0',
  sent: 0,
  expiry: 0,
  ttl: 0,
  workProved: 0,
  payloadRaw: '0x48692077686973706572',
  topics: [] }
Error: null
Message: { payload: 'Hi whisper',
  to: '0x0',
  from: '0x0',
  sent: 0,
  expiry: 0,
  ttl: 0,
  workProved: 0,
  payloadRaw: '0x48692077686973706572',
  topics: [] }
```

Could you please look into this?

**Comment by frozeman** [comment]
I will take a look

**Comment by karalabe** [comment]
The issue seems to be that the callback is invoked at these two places:

 - https://github.com/ethereum/web3.js/blob/master/lib/web3/filter.js#L84
 - https://github.com/ethereum/web3.js/blob/master/lib/web3/filter.js#L98

Don't know what the difference is.

Also, it's weird that beside the payload, all other fields are empty, but I'll check this at my end first and make sure it's not a server issue.

**Comment by frozeman** [comment]
Thats because we call the getMessages on when you create a watch to get the old messages too. It seems like go does this internally as well, which it shouldn't. Can you please check go?

**Comment by frozeman** [comment]
Go should only give new incoming messages on `shh_getFilterChanges` not past ones. This is now handled by web3.js

**Comment by ethers** [comment]
For clarity, I suggest let's try to remember to add the protocol to the title of issues, this would be ``shh.filter.watch notified multiple times``  (I realized this because I opened similar issues with filter.watch, but for eth, and forgot to put the title as eth.filter.watch)

**Comment by karalabe** [comment]
@frozeman I've checked the Go implementation, and it works correctly, but there's a subtlety not handled client side. You are probably executing quite a lot of operations async, and in essence even though I "watch" first and "send" afterwards, the operations get inverted by the time they read the RPC server:

This is the order of events server side:
```
Creating filter &{To: From: Topics:[]}
Creating filter &{To: From: Topics:[0x73696e676c65746f6e]}
Creating filter &{To: From: Topics:[0x61 0x63]}
Posting &{Payload:0x4869207768697370657220656d707479 To: From: Topics:[] Priority:0 Ttl:0}
Posting &{Payload:0x486920776869737065722073696e676c6520746f706963 To: From: Topics:[0x73696e676c65746f6e] Priority:0 Ttl:0}
Posting &{Payload:0x48692077686973706572206d756c746920746f706963 To: From: Topics:[0x61 0x62 0x63] Priority:0 Ttl:0}
Requesting all messages &{Id:0}
Requesting all messages &{Id:1}
Requesting all messages &{Id:2}
Requesting updates &{Id:0}
Requesting updates &{Id:1}
Requesting updates &{Id:2}
Requesting updates &{Id:0}
Requesting updates &{Id:1}
Requesting updates &{Id:2}
Requesting updates &{Id:0}
Requesting updates &{Id:1}
Requesting updates &{Id:2}
[...]
```

In essence, immediately after you created the filter you returned from `watch`, allowing the `shh.post` ops to continue. So before you got to actually request the *old* messages, you dumped the new ones in there too, so they were matched by the filter as new ones.

With getMessages you retrieve every old messages, as well as these racy ones, and with getFilterChanges you request just the changes, the racey ones.

What you should actually do is to make sure getMessages finished running, before you allow the `filter.watch` operation to continue.

**Comment by karalabe** [comment]
This has been discussed and fixed server side, so closing.
