### ISSUE TITLE
web3.js can not watch event on geth

### ISSUE THREAD

**Issue by KeepChen** [ethereum/web3.js#1653]
Hi, @frozeman 
One problem I encountered was that when I started the geth server using 
`geth --datadir /var/disk/gethDataDir/ --rpc --rpcapi db,eth,net,personal,web3 --ws --wsapi db,eth,net,personal,web3 --wsorigins=* --unlock "my address" --password "my password"`, 
there was no way to successfully listen to events.
But when I start the geth server in this way 
`geth --datadir /var/disk/gethDataDir/ --rpc --rpcapi db,eth,net,personal,web3 --ws --wsapi db,eth,net,personal,web3 --wsorigins=*`,
web3.js can listen to events normally.
The difference between the two startup methods is that `--unlock "my address" --password "my password"`.
I'm not sure why this is a web3.js or a geth server. Is this a bug?
Hope to answer, thank you very much!

**Comment by frozeman** [comment]
Looks like a bug in geth itself,can you file that issue in go-ethereum?

**Comment by KeepChen** [comment]
Of course.Thanks a lot!
