### ISSUE TITLE
How to track incoming to smart contract transactions using web3js?

### ISSUE THREAD

**Issue by Gim6626** [ethereum/web3.js#1655]
I've got one Ethereum smart contract which calls functions of the other one. How could I track these calls using web3js if it is possible at all? I need it because I want to execute some JavaScript code after receiving such call and then call other function of first smart contract so the sequence of calls should be following:

1. Smart contract N1 calls N2 smart contract function.
2. JavaScript code catches this call and execute some code.
3. Smart contract N2 calls back N1 using data from previous step.

Could anybody help with it?

**Comment by nivida** [comment]
You could do this by emitting an event on the second contract and creating an event listener with web3js which is executing method X if the event was emitted. Please ask further questions on https://ethereum.stackexchange.com/.
