### ISSUE TITLE
err: Error: base fee exceeds gas limit when values are correct

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum/web3.js#1656]
## Expected
Token transaction should execute successfully.

## Behaviour
The base fee exceeds the gas limit, when that's not the case. The gas limit I set is 0xEA60, which in decimal is 60,000, definitely lower than Ganache's block gas limit of 6,721,975.

## Code
```node
const Tx = require('ethereumjs-tx');

const config = require('./config');
const contract = require('./contract');
const web3 = require('./web3');

const main = async () => {
	const count = await web3.eth.getTransactionCount(config.from);
	const nonce = web3.toHex(count);

	const gasPrice = web3.eth.gasPrice.toNumber();

	const block = await web3.eth.getBlock(3);
	console.log('block.gasLimit', block.gasLimit);
	console.log('web3.toDecimal(\'0xEA60\')', web3.toDecimal('0xEA60'));

	const rawTx = {
		'from': config.from,
		'nonce': nonce,
		'gasPrice': gasPrice,
		'gasLimit': '0xEA60',
		'to': config.to,
		'value': '0x10',
		'data': contract.transfer.getData(config.to, 10, { from: config.from }),
		'chainId': '0x03'
	};

	const privateKey = Buffer.from('8c...', 'hex');
	const tx = new Tx(rawTx);
	tx.sign(privateKey);
	const serializedTx = tx.serialize();

	web3.eth.sendRawTransaction('0x' + serializedTx.toString('hex'), (err, hash) => {
		if (!err) {
			console.log('hash:', hash);
			console.log(web3.eth.getTransaction(hash));
		} else {
			console.log('err:', err);
		}

		console.log('from\'s balance:', contract.balanceOf.call(config.from));
		console.log('to\'s balance:', contract.balanceOf.call(config.to));
	});
};

main();
```

## Tools
• web3: `0.20.6`
• ethereumjs-tx: `1.3.4`
• ganache (UI): `1.1.0`
• node: `9.3.0`
• os: `osx high sierra 10.13.3`

Full log ouput [here](https://www.dropbox.com/s/yydng4hhxnfdhjr/ethrereumjs-tx-0.0.5.log?dl=0).

**Comment by Levino** [comment]
I recommend using formating for your code block like so:
```js
import tool from 'tool'`
function foo() {
  return tool()
}
const bar = foo(5)
```
I am not sure whether web3 `0.x` is supported any more. Looks to me like `1.0.0` is to be released pretty soon. Could you try using `1.0.0-beta`?

**Comment by PaulRBerg** [comment]
Thanks for the syntax highlighting heads up.

Indeed, I upgraded to `1.0.0-beta.34` and it works now. I still don't know what's wrong with the code from above, so I'll keep the issue open until a solution is found or the repo is upgraded to a stable version of 1.0.0.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
