### ISSUE TITLE
myContract.method uses sendTransaction no call

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#166]
When calling a contract method, it uses `eth_sendTransaction` instead of `ethical` to call the method, though the default behaviour should be a call.

**Comment by debris** [comment]
can you also attach json ABI? Only const methods should use 'call'.

**Comment by frozeman** [comment]
it was about that example:
```js
 
var sender = eth.accounts[0]
var compiledCode= "603580600c6000396000f30060003560e060020a90048063c6888fa114601557005b601e6004356028565b8060005260206000f35b6000816007029050919050"
var GasPrice = web3.toWei(0.00001, "ether") 
var newAddress = web3.eth.sendTransaction({data: compiledCode, from: sender, gas: 2000000, gasPrice:GasPrice }); 
 
// wait for a minute or so and try this:
 
eth.getCode(newAddress)
 
// if it returns 0x then wait for a bit more until your contract finds it's way to the blockchain. Proceed when done
 
 
var desc =  [{ "name": "multiply(uint256)", "type": "function", "inputs": [ { "name": "a", "type": "uint256" } ], "outputs": [ { "name": "d", "type": "uint256" } ]}];
 
someContract = web3.eth.contract(desc)
contractInstance = new someContract(newAddress)
contractInstance.call().multiply(10);
 
contractInstance.call({from:sender, gas: 3000000}).multiply(10);
```

For web3.js it makes only sense to use call always when just calling a method, as otherwise you would have to specify a `from`, which you can't calling only the method e.g. `myContract.myMethod()`.

So i would make call the default here, when not sendTransaction or call is specified.

Additionally i would put the sendTransaction and call behind the method call, as it is more logical this way.

**Comment by debris** [comment]
>For web3.js it makes only sense to use call always when just calling a method, as otherwise you would have to specify a from, which you can't calling only the method e.g. myContract.myMethod().

>So i would make call the default here, when no sendTransaction().myMethod() or call().myMethod() is specified.

This example is outdated, I will update it in few minutes. But let me clarify few things.

Solidity has two types of 'functions' - `function` && `const function`. And despite the fact, that they have similar names, their behaviour is completely different. `function` can modify the state of the contract. that means, that it **cannot** be called using `call` method. `const function` doesn't modify state of the contract, so there is no point of using `sendTransaction` in this case. What's more, `functions` cannot return anything, cause we do not now, when they will be executed. Only `const functions` can return a value.

**Comment by debris** [comment]
Solidity functions are described [here](https://github.com/ethereum/wiki/wiki/Solidity-Tutorial)

**Comment by frozeman** [comment]
right. Then the abi is incorrect in the example.
Though we might think of putting the sendTransaction call behind the method. Not sure how easily we can do that though.
