### ISSUE TITLE
"npm install web3" is failed

### ISSUE THREAD

**Issue by kinmy** [ethereum/web3.js#1661]
$ npm install web3@1.0.0-beta.27

> scrypt@6.0.3 preinstall C:\Users\Administrator\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\Administrator\node_modules\scrypt
> node-gyp rebuild

C:\Users\Administrator\node_modules\scrypt>if not defined npm_config_node_gyp (n                                                                                                                                  ode "C:\Users\Administrator\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_mo                                                                                                                                  dules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r                                                                                                                                  ebuild )  else (node "C:\Users\Administrator\AppData\Roaming\nvm\v8.11.1\node_mo                                                                                                                                  dules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                                                                                                                  HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Administrator\AppData\                                                                                                                                  Roaming\nvm\v8.11.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:                                                                                                                                  19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Administrator\AppData\R                                                                                                                                  oaming\nvm\v8.11.1\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:1                                                                                                                                  6)
gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\nvm\v8.11.1\node_mo                                                                                                                                  dules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator                                                                                                                                  \\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\node_modules\\node-gyp\\bin                                                                                                                                  \\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\scrypt
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\                                                                                                                                  package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                  ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-05-25T1                                                                                                                                  4_33_15_223Z-debug.log

**Comment by Levino** [comment]
Does it also happen with `1.0.0-beta.34` which is the latest version?

**Comment by Fofir** [comment]
@Levino yes

**Comment by Levino** [comment]
So issue can be closed, right?

**Comment by Levino** [comment]
Btw: Looks like you do not have python installed. It says so in the logs you shared.
