### ISSUE TITLE
filter.watch() does not handle sticky sessions

### ISSUE THREAD

**Issue by ianthpun** [ethereum/web3.js#1665]
Currently, filter.watch() doesn't seem to support sticky sessions. The initial call to `web3.eth.filter('latest')` does not hold the cookies set from the response

**Comment by itpun** [comment]
I noticed that `HTTPProvider` uses `XMLHttpRequest()`, which has the option to set `withCredentials = true`, allowing for `set-cookie` to work for cookie-based sticky sessions. Is there a reason why this was not set to `true` or why there is no option to?

**Comment by edevil** [comment]
I also have this problem. I access a parity node farm behind a load-balancer that sets sticky sessions based on cookies. Some of the flows like creating and using filters require that we reach the same node. If the correct cookie value is not sent when we want to fetch events from the filter we just created this will not work.

@ianthpun did you manage to get this to work?

**Comment by frozeman** [comment]
I merged and fixed the tests, can you test develop?
