### ISSUE TITLE
Ethereumj + web3js

### ISSUE THREAD

**Issue by 1jose234** [ethereum/web3.js#1667]
hi
i have worked with Ethereumj to create a blockchain and Harmony to RPC,  i use a smart contract of example.

```
contract Sample {
  int i;
  event Inc(
      address _from,
      int _inc,
      int _total
  );  
  
  function inc(int n) {
    i = i + n;
    Inc(msg.sender, n, i);  
  }  
  
  function get() returns (int) {
    return i;  
  }
}  
```

i can get a value of method get

![image](https://user-images.githubusercontent.com/38274938/40638958-dd172746-62d3-11e8-9f1b-96414667538f.png)

but i can't set value in the variable of method inc and update the blockchain.

![image](https://user-images.githubusercontent.com/38274938/40638982-f29388ee-62d3-11e8-8654-84b16ec9d27e.png)

somebody could helpme

**Comment by dstawinski** [comment]
The response you get is transaction hash. You should try pasting that hash to Etherscan, wait till it gets mined and then check value of `i` using contract method `get()`.
