### ISSUE TITLE
Uncaught Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by denshest** [ethereum/web3.js#1671]
Hello guys!
I need to write a code for transfer tokens from one account to another. I don't use node.js but I use pure web3.js and pure ethereum-tx.js.
Now my code is stopping here:
`let data = tokenInst.methods.transfer("0x95E5B0D5a44C82D6Dd0685b0856f0B55986EE830", 10).encodeABI()`
With error message:
`Uncaught Error: Invalid JSON RPC response: ""`

scripts:
`<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>`
`<script src="https://cdn.rawgit.com/ethereumjs/browser-builds/2fb69a714afe092b06645286f14b94f41e5c062c/dist/ethereumjs-tx.js"></script>`

Full code:

`<script>
{
                web3 = new Web3(new Web3.providers.HttpProvider("https://rinkeby.infura.io"))
            	let tokenAddress = '0xA928bE04430FBA6c1A72588d3cbF854D61821b93'
            	let tokenABI = JSON.parse(ABI)
            	let tokenInst = web3.eth.contract(tokenABI).at(tokenAddress)
                let privateKey = new EthJS.Buffer.Buffer('XXX', 'hex')
                web3.eth.getTransactionCount("0xD81407738d90EDE372D1336b040B220B9e7485fe", function (err, nonce) {
                    let data = tokenInst.transfer("0x95E5B0D5a44C82D6Dd0685b0856f0B55986EE830", 10).encodeABI() //Error here
                    let txParams = {
                        nonce:    web3.utils.toHex(nonce),
                        gasPrice: web3.utils.toHex(1000e9), 
                        gasLimit: web3.utils.toHex(30000),
                        to:       '0xD81407738d90EDE372D1336b040B220B9e7485fe', 
                        value:    '0x00', 
                        data:     data  
                    }
                    let tx = new EthJS.Tx(txParams)
                    tx.sign(privateKey)
                    let serializedTx = '0x' + tx.serialize().toString('hex')
                    console.log('serializedTx:', serializedTx)
                })
            }
        </script>`

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
