### ISSUE TITLE
npm github link broken 

### ISSUE THREAD

**Issue by NatalieChin80** [ethereum/web3.js#1672]
Is the link on `npm` indicative of the link posted here? https://www.npmjs.com/package/web3

The github repository which links to it (https://github.com/ethereum/web3.js/tree/master/packages/web3) is an invalid link.

**Comment by nivida** [comment]
@frozeman Can you fix this? :)

**Comment by roschler** [comment]
Still broken.  Should go to:

https://github.com/ethereum/web3.js/tree/1.0/packages/web3-utils

Gets a 404 error instead.

**Comment by aj07** [comment]
@NatalieChin80 @roschler where exactly in doc this link is broken ?

**Comment by 0xicingdeath** [comment]
In the Github section of NPM package link mentioned in the first post: https://www.npmjs.com/package/web3

**Comment by aj07** [comment]
@NatalieChin80  gottcha. But, that link are redirected from web3 github repo or from npm repo ?

**Comment by 0xicingdeath** [comment]
I'm not too sure what you're asking, but the link when I click on this leads to a 404: 

![image](https://user-images.githubusercontent.com/16736724/50096835-9bd45300-01e6-11e9-824c-4ecdcd794c8c.png)

**Comment by aj07** [comment]
yes, but that link can't be corrected by web3 repo. It's the doc page of npm. Probably, raising issue on npm doc would be the best place.

**Comment by tcrowe** [comment]
For reference this is where the GitHub URL comes from:
https://github.com/ethereum/web3.js/blob/1.0/packages/web3/package.json#L6

@nivida This `repository` URL is correct for the future *IF* `1.0` branch merges into `master`, not `develop`.

*Optionally* it can be changed to `1.0` branch if that branch will remain in progress a long while.

*Optionally* do nothing and wait until `1.0` goes into `master` then the URL is correct.

Was this helpful?

**Comment by tcrowe** [comment]
![web3-npm-link](https://user-images.githubusercontent.com/1634015/50244094-4afe5f00-038c-11e9-9a6b-e644e2e43425.gif)
