### ISSUE TITLE
Creating a new wallet mobile application for newly created crypto currency

### ISSUE THREAD

**Issue by sugalivijaychari** [ethereum/web3.js#1673]
0
down vote
favorite
I am doing as a Intern in Apogee Tech Global in Bangalore on Blockchain for three months. My commitments is to learn solidity language, build smart contracts, learn Ethereum and Hyperledger. I learnt solidity language. I haven't yet practised more on solidity. Just learnt. By using ERC20, I have created a new crypto currency in ropsten test network and also verified in ether scan. I can also create real crypto currency in main ethereum network if ethers are available.

But, here the company employee told me to practise on solidity more. Also learn UI develpment part parallelly. To do UI part, they said to learn Javascript. I learnt javascript in codecademy. Now I am going through React.js.

Now, based on above criteria. Please suggest me the best path and suggestions to learn the required technologies to develop a crypto wallet and to build UI in prior time.

**Comment by nivida** [comment]
Please ask your question on https://ethereum.stackexchange.com/
