### ISSUE TITLE
how do i install v1.0.0-beta34 on client side?

### ISSUE THREAD

**Issue by chovy** [ethereum/web3.js#1676]
I installed using `npm install web3@1.0.0-beta34` but inside node_modules I have a bunch of different directories. is there a production dist folder somewhere?

I am trying to get web3.utils to work in angular.

**Comment by ndtuan89** [comment]
Here you are.

https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.34

**Comment by hudsonburgess** [comment]
From the readme:
> include `dist/web3.js` in your html file

We lose TS types with this approach; are standalone type definitions available anywhere?
