### ISSUE TITLE
Wrong blocknumber in response of sendSignedTransaction

### ISSUE THREAD

**Issue by mudlee** [ethereum/web3.js#1683]
I sent a signed transaction via sendSignedTransaction, which after 1 sec returned a receipt, which had these interesting properties "typed":"mined", "blockNumber": A_NUMBER

When I checked the transaction on the blockchain, the blocknumber was different. 
So questions:
- how can a transaction be mined if the blocknumber is not the same? 
- When will the sendSignedTransaction return with a receipt? 

I use ^1.0.0-beta.26

**Comment by mudlee** [comment]
No one can answer in 20 days at least "we will get back to you"? Cmon guys... :(

**Comment by nivida** [comment]
Is this issue still there in the latest version?

**Comment by nivida** [comment]
I've closed this issue because of no further information are provided.
