### ISSUE TITLE
npm install web3 not working

### ISSUE THREAD

**Issue by 26rahulsingh** [ethereum/web3.js#1685]
$ npm install web3
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated                         and your application is vulnerable. Please use tar module instead: https://npmj                        s.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Suppor                        t
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=No such file or directory
npm ERR! github.com[1: 192.30.253.113]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DevJS\AppData\Roaming\npm-cache\_logs\2018-06-06T14_21_09_702Z-debug.log

**Comment by junjchen** [comment]
looks like a network/firewall issue. have you tried to use http:// instead of git://

**Comment by nivida** [comment]
Please ask further question on stackoverflow or if they are related to ethereum ask your questions on https://ethereum.stackexchange.com/
