### ISSUE TITLE
web3 gasPrice vs cumulativeGas

### ISSUE THREAD

**Issue by NatalieChin80** [ethereum/web3.js#1686]
I wrote a contract to open payment channels in solidity. After running into a bug of balances not being equal, despite the updated balances showing up in Ganache, I realized that, in order to calculate the total amount of wei that was used on a transaction - that would be `gasUsed * gasPrice`. 

The description in the documentation doesn't explicitly make this connection very clear. There should be a note somewhere, just mentioning that `gasPrice` is the wei per unit of gas, and in order to find the total amount spent on gas, it should be the product of gasPrice and the amount of gas used.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
