### ISSUE TITLE
Documentation for web3.eth.getGasPrice suggests it returns a Promise when it does not

### ISSUE THREAD

**Issue by ghzwrapper** [ethereum/web3.js#1695]
While the documentation for web3.eth.getGasPrice suggests it returns a Promise, it does not at the moment, instead it expects a callback function as an input parameter.

Encountered this issue on MetaMask on Chrome, it's possible this is an implementation detail of MetaMask?

See: https://web3js.readthedocs.io/en/1.0/web3-eth.html#getgasprice

And a few examples of other issues logged from the expected vs. actual behavior: 
- https://github.com/ethereum/web3.js/issues/1153
- https://github.com/ethereum/web3.js/issues/1355

**Comment by ribordy** [comment]
Those docs are for web3 1.0, which IIRC is still in beta. We're using whatever version comes with truffle, which IIRC is not 1.0
