### ISSUE TITLE
"Invalid number of arguments to Solidity function." without Truffle and with correct number of args

### ISSUE THREAD

**Issue by alessandro308** [ethereum/web3.js#1696]
I've the following contract function:

`/*Solidity Code, inside my contract*/
function isGranted(address _user, address _content) view external returns (bool) {
    return (grantedAccess[_user][_content]);
}`

That works on Remix IDE without any problem.

Then I wrote a Web3JS frontend

`this.catalog = (this.web3.eth.contract(this.props.catalog.abi)).at(this.props.catalog.address);
this.catalog.isGranted(
            this.web3.eth.defaultAccount, //Parameter1
            this.state.address, //Parameter2
        (err, res) => { //Callback
            if(!err){
                console.log(res);
                this.setState(this.setState({userHasRightAccess: res}));
            } else {
                console.error(err);
            }
        })`

But the execution returns `Error: Invalid number of arguments to Solidity function.` I tried to add the other optional parameter to Web3js function but the error remains. Any idea/solution?

(I don't use Truffle or any more framework. Web3JS version is "0.20.6")

**Comment by burz** [comment]
@alessandro308 Did you ever figure this out?

**Comment by alessandro308** [comment]
Yes. The problem was that one passed value was undefined

Il gio 6 set 2018, 04:59 Anthony Burzillo <notifications@github.com> ha
scritto:
