### ISSUE TITLE
Total Transaction Gas 

### ISSUE THREAD

**Issue by NatalieChin80** [ethereum/web3.js#1699]
# Steps to Reproduce 
1. Download repo located here: https://github.com/STKtoken/ETH-smart-contracts  on branch `develop` 
2. Run `npm install` 
3. Run `truffle test` 

# Expected Action 

The last test case of the `settle` function asserts a balance equality between two values. In this case, the use of `gasUsed * gasPrice` should be indicative of the total amount spent on gas. 

Assuming `gasUsed` is equal to the cumulativeGas from a web3 transfer. 

Thus, the following assumption would be made: 
`Number (balanceAfterTransfer) == Number(previousBalance) + amount - (gasUsed * gasPrice)`

# Actual Output 

However, this number seems to be almost always 10000 off - but at times, 20000. One idea I have is that `gasUsed` does not include the inherent gas that is used to transfer money back to the recipient. Is there any way to get this value and/or ensure that the above assertion would be true?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
