### ISSUE TITLE
web3.eth.contract synchronous save contract to vuex store

### ISSUE THREAD

**Issue by xrei** [ethereum/web3.js#1704]
web3 version `0.20.6`

Hi, i'm making a contract and try to save it to vuex  store.
The part of making contract is fine but when i try to `commit` to store i get the error
`Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_mining without a callback parameter.`

Here is the code

```js
import Web3 from 'web3'
import abi from './abi'
const makeContract = () => new Promise((resolve, reject) => {
  let web3 = new Web3(window.web3.currentProvider)
  let contract = web3.eth.contract(abi)
  let contractInstance = contract.at('address')
  resolve(contractInstance)
})

// action
  setContractAddress ({ commit, state }, contractAddr) {
    makeContract(contractAddr).then(res => {
      commit('setContract', res) // when this line is removed, no error
    })
  }

//mutation
  setContract (state, p) {
    state.web3.contractInstance = () => p
    console.log(state.web3) // here is the contract but still have the error
  }

// call the action
this.$store.dispatch('Web3/setContractAddress')
```
I don't know where am i doing it wrong, please any advice?
Thanks

**Comment by chovy** [comment]
is res the same as p? what is p supposed to be?

**Comment by xrei** [comment]
@chovy Yeah, p is the contract

**Comment by chovy** [comment]
are you using axios?

**Comment by xrei** [comment]
@chovy Nope

**Comment by chovy** [comment]
ok, never mind. can you log this:

```
  let contractInstance = contract.at('address')
  console.log(contractInstance)
  resolve(contractInstance)
```

**Comment by xrei** [comment]
@chovy 
![image](https://user-images.githubusercontent.com/9521710/41382841-9a9f8cd2-6f76-11e8-96d2-5ddf14194329.png)

**Comment by th-ink** [comment]
have you managed to resolve this @xrei? I am getting the same error from the same state mutation as you.

**Comment by xrei** [comment]
@th-ink 
I made a reusable function which makes contract, and wherever i need contract i'm generating new contract. So i don't store contract.

```js
const makeContract = (addr, abi) => new Promise((resolve, reject) => {
  if (!addr) reject(new Error('Provide address'))
  let web3 = new Web3(window.web3.currentProvider)
  let contract = web3.eth.contract(abi).at(addr)
  resolve(contract)
})
```

**Comment by th-ink** [comment]
that is a nice workaround! Thanks @xrei .

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
