### ISSUE TITLE
extending txpool_content causes web3 to throw error

### ISSUE THREAD

**Issue by AyushyaChitransh** [ethereum/web3.js#1709]
Geth provides some non standard management APIs and I am extending web3 functions to use those APIs. In order to use them I enabled txpool API from geth console as follows:

     admin.startWS("0.0.0.0",8556,"*","eth,debug,shh,web3,txpool")

When I access the content function, I get error, while other functions are working properly.
## Problem

Incorrect error message is shown when a call fails. I am unable to call `txpool_content` api, and neither am I able to debug the issue due to the error message. Associated question: [txpool_content not working while other txpool APIs work](https://ethereum.stackexchange.com/q/51349/16048)

## Code:

    const Web3 = require("web3");
    var web3 = new Web3(new Web3.providers.WebsocketProvider("ws://localhost:8556"));
    web3.eth.extend({
        property: 'txpool',
        methods: [{
          name: 'content',
          call: 'txpool_content'
        },{
          name: 'inspect',
          call: 'txpool_inspect'
        },{
          name: 'status',
          call: 'txpool_status'
        }]
      });
      web3.eth.txpool.status().then(console.log).catch(console.error)
      web3.eth.txpool.content().then(console.log).catch(console.error)

## Output:

    { pending: '0xf92', queued: '0x4e' }
    Error: CONNECTION ERROR: Couldn't connect to node on IPC.
        at Object.InvalidConnection (/Users/user1/projects/backend/node_modules/web3-core-helpers/src/errors.js:35:16)
        at WebsocketProvider._timeout (/Users/user1/projects/backend/node_modules/web3-core-requestmanager/node_modules/web3-providers-ws/src/index.js:192:48)
        at W3CWebSocket.connection.onclose (/Users/user1/projects/backend/node_modules/web3-core-requestmanager/node_modules/web3-providers-ws/src/index.js:96:15)
        at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/user1/projects/backend/node_modules/yaeti/lib/EventTarget.js:107:17)
        at W3CWebSocket.onClose (/Users/user1/projects/backend/node_modules/websocket/lib/W3CWebSocket.js:228:10)
        at WebSocketConnection.<anonymous> 

## Environment:

    web3 version: tried 1.0.0-beta.29 and 1.0.0-beta.34
    geth version: 1.8.4 at commit de2a7bb764c82dbaa80d37939c5862358174bc6e

**Comment by lhaste** [comment]
Anyone get `txpool` to work with `web3 1.0.x`?

**Comment by AyushyaChitransh** [comment]
@lhaste As a temporary fix, I ended up using two web3 in one project. For `tx_pool` and other non standard function calls to RPC, I am using older web3 under the name `web3Legacy`. Web3Legacy was included in `package.json` as follows:

    "web3Legacy": "git+https://github.com/AyushyaChitransh/web3.js.git",

**Comment by princesinha19** [comment]
@nivida I think this ticket can be closed.

**Comment by AyushyaChitransh** [comment]
Is web3 now supporting txpool_content?

**Comment by princesinha19** [comment]
Yes, @AyushyaChitransh., In the next release, you will get all management API including txpool in Web3 which are supported by Geth.

**Comment by Jorocha** [comment]
Hi! Did anyone used the **web3-eth-txpool** package? I'm having difficulties with the **options** parameter:
`const txPool = new TxPool(new Web3.providers.HttpProvider('http:/localhost:8545'), null, options);
`
I followed the documentation (https://web3js.readthedocs.io/en/1.0/web3-eth-txpool.html#options) and tried the options example that is provided there, but still couldn't make it work. I'm trying to get this done in order to get the pending transactions using **txPool.getContent()**.

**Comment by Tronglx** [comment]
Hi! Did anyone have an action for this issue as a temporary fix?

**Comment by Tronglx** [comment]
> @lhaste As a temporary fix, I ended up using two web3 in one project. For `tx_pool` and other non standard function calls to RPC, I am using older web3 under the name `web3Legacy`. Web3Legacy was included in `package.json` as follows:
> 
> ```
> "web3Legacy": "git+https://github.com/AyushyaChitransh/web3.js.git",
> ```
@AyushyaChitransh can you explain how to use web3Legacy in more detail?

**Comment by princesinha19** [comment]
@Tronglx Txpool module is already released.
Please have a look. https://github.com/ethereum/web3.js/blob/2.x/docs/web3-eth-txpool.rst

**Comment by Tronglx** [comment]
@princesinha19  so, may i use web3-eth-txpool version 2.0.0-alpha? I have tried with this version but it is not running for me.
It is runnable with http provider but not work with ws provider.

**Comment by princesinha19** [comment]
@Tronglx No, you can run it using version 1.0.

**Comment by Tronglx** [comment]
@princesinha19 I have already using it but the function txPool.getContent() always return error if using WebsocketProvider although another functions such as txPool.getInspect()... are ok. If i use HTTPProvider i can use function txPool.getContent(). So, finally, i decide using HTTPProvider for this feature.
Thanks.
