### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by Levino** [ethereum/web3.js#1710]
What is happening? Are there any maintainers? There are nearly 500 open issues...

**Comment by hexagon6** [comment]
I am open to help on automated CI-builds, linting & formatting and ES2015 migration.
let me know if this is welcome.
we were lacking up to date stuff (ES-modules build) for integrating this in our project.

**Comment by nivida** [comment]
Yes me I‘ve started working ob Web3.js this week. I implementig the new ABI library right now and it should be done next week if anything goes fine :) 
First I will fix some bugs and after them i will starting solving the issues here.

**Comment by Levino** [comment]
Most of the issues here are bugs...

**Comment by Levino** [comment]
But I am happy to see that something happens again. One single developer is surely not enough for this project though.
