### ISSUE TITLE
How do you encode raw arguments into bytes value using web3 0.20?

### ISSUE THREAD

**Issue by aleybovich** [ethereum/web3.js#1711]
My DApp wil be using MetaMask and currently MetaMask injects web3 0.20.3 into a web page, so I have to use that. 
I interact with an ERC223 token and need to pass a few arguments packed as a single bytes object into it (last argument to `ERC223.transfer(to, value, data)` function), and i can't find a way to do that using web3 v0.20.
Any ideas?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
