### ISSUE TITLE
web3.currentProvider.sendAsync ALWAYS undefined on mobile devices

### ISSUE THREAD

**Issue by Alexintosh** [ethereum/web3.js#1712]
**Bug report**

Version: 0.20.6

The method sendAsync appears to be always undefined on mobile devices, I've trying with different JSON rpc nodes including Infura, myetherapi and others.

I cannot figure it out why this happen or how to solve it so far. I've been talking about this also in [web3.js/issues/1119](https://github.com/ethereum/web3.js/issues/1119) and the gitter chat without any luck so far.

The proposed workaround doesn't work either
```
web3.providers.HttpProvider.prototype.sendAsync = web3.providers.HttpProvider.prototype.send;
```

It's interesting to notice that everything will work fine on the iOs or android simulators.

**Comment by Alexintosh** [comment]
I couldn't find any way to solve this client side, so I ended up only signing the transaction in the client and broadcasting it server side. If you are interested in a microservice to do that you can find the [Tx-broadcaster Repository by DEXlab.io here.](https://github.com/dexlab-io/Tx-broadcaster)

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
