### ISSUE TITLE
event "confirmation" of myContract.methods.myMethod().send() fired at 1 instead of 0 

### ISSUE THREAD

**Issue by vrolland** [ethereum/web3.js#1713]
Hello Guys,

Thanks for all the work you do providing this very usefull library.

I am facing an issue when I retrieve the event "confirmation" after a myContract.methods.myMethod().send(). The confirmation number start at 1 since the version web3@1.0.0-beta.31.

But the doc suggests that it should "Fired from confirmation 0". (see [http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send](http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send))

Is the documentation outdated or this is an odd behaviour ?

Best,

**Comment by frozeman** [comment]
Thanks for the find!
