### ISSUE TITLE
sendTransaction documentation error

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#1714]
The documentation of `web3.eth.sendTransaction` states that [an event is fired for every confirmation up to the 12th confirmation](https://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-sendtransaction-return).

I executed this code, and got prints up to the 24th confirmation:

```
async function send(address, transaction) {
    let options = {
        to: address, 
        data: transaction.encodeABI(),
        gas: await transaction.estimateGas()
    };
    let signedTransaction = await web3.eth.accounts.signTransaction(options, PRIVATE_KEY);
    return await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
```

Side note:

The documentation for `web3.eth.sendSignedTransaction` says

> Please see the return values for `web3.eth.sendTransaction` for details.

Hence the title of this issue.

This fact also aligns well with the documentation of `methods.myMethod.send`, which states that [an event is fired for every confirmation up to the 24th confirmation](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id22).

**Comment by nivida** [comment]
This can now be configured over the [module options](https://web3js.readthedocs.io/en/1.0/web3-shh.html#web3-module-transactionconfirmationblocks). I'll update the documentation asap.

``` javascript
new Web3(provider, null, options);
```
