### ISSUE TITLE
To get contract address

### ISSUE THREAD

**Issue by tbenny** [ethereum/web3.js#1715]
var  ContractABI = [{"constant":true,"inputs":[{"name":"_parent","type":"address"},{"name":"register","type":"address[]"}],"name":"isNotDuplicateChild","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"pure","type":"function"},{"constant":true,"inputs":[{"name":"_address","type":"address"}]}];
        var RegContract = web3.eth.contract(  RegContractABI);
        console.log(RegContract.address);
        var  Reg = RegContract.at("Contract Address");

How to get contract address

**Comment by barakman** [comment]
Step 1:
Run `npm install keythereum`.

Step 2:
Locate your key file somewhere on your system.
The name of this file should be something like `UTC--2018-05-13T13-14-58Z--xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`.
Typically, this file should be located at:
- On Windows: `%UserProfile%\AppData\Roaming\Parity\Ethereum\keys`
- On Linux: `~/.local/share/io.parity.ethereum/keys`
- On macOS: `$HOME/Library/Application Support/io.parity.ethereum/keys`

Step 3:
Create a folder `keystore`, and copy your key file into it.

Step 4:
Create a file `recoverPrivateKey.js` next to this folder.
In this file, do:
```
var keythereum = require("keythereum");
var keyObject = keythereum.importFromFile("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "./");
var privateKey = keythereum.recover("Your Password", keyObject);
console.log(privateKey.toHex());
```
Step 5:
Run `node recoverPrivateKey.js`.

**Comment by barakman** [comment]
@tbenny:

Change `console.log(privateKey.toHex());` to `console.log(privateKey.tostring("hex"));`.

**Comment by nivida** [comment]
Please ask further questions on https://ethereum.stackexchange.com/
