### ISSUE TITLE
Documentation for creating a new contract

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#1717]
Your description for `new web3.eth.Contract(jsonInterface[, address][, options])` [here](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html?highlight=deploy#new-contract), states the following about the `address` (second) argument passed to this constructor function:

> The address of the smart contract to call, can be added later using `myContract.options.address = '0x1234..'`

This statement is somewhat misleading, because adding this field by itself will not have any real impact on the contract instance (except for... well... this additional field).

For example, the `methods` field of the contract instance will still remain empty, so the contract instance is not going to become any "more usable" than it was before adding this field.

When creating a new contract, the address field should be omitted **if and only if** the new contract is to be deployed (that by itself should probably be emphasized in the documentation).

After that, if one wants to create a **usable** contract instance, then they should recreate a contract instance, but this time, in addition to the `jsonInterface` argument, the should also provide the `address` argument (which should be available after signing and sending the contract-deployment transaction).

**Comment by Flash-Git** [comment]
Hopefully that satisfies this issue.
