### ISSUE TITLE
Transaction receipt documentation spelling error

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#1719]
Misspelled `successful` as `susccessfull` [here](https://web3js.readthedocs.io/en/1.0/web3-eth.html?highlight=susccessfull#eth-gettransactionreceipt-return).

**Comment by mik-laj** [comment]
Related to: https://github.com/ethereum/web3.js/pull/1579

**Comment by frozeman** [comment]
fixed in #1876
