### ISSUE TITLE
Create an NPM package for bignumber.js-nolookahead

### ISSUE THREAD

**Issue by mer1dian** [ethereum/web3.js#1720]
web3js lists github.com/frozeman/bignumber.js-nolookahead as a dependency and causes issues when installing, can we please add this as a package

**Comment by nivida** [comment]
Good idea that would solve the problem if some has not configured GIT correctly. 
@frozeman could you do this?

**Comment by nivida** [comment]
This got fixed with the latest version of Web3.js
