### ISSUE TITLE
Why web3.js function call is so slow?How can I improve it?

### ISSUE THREAD

**Issue by and2352000** [ethereum/web3.js#1729]
My app environment : 
- web3.js version 0.20.X
- node.js version 8.11.1
- express version 4.16.3

The web page can handle requests  500 req/s without the function call,
but web page can only handle requests about 10 req/s when I add function call down below. 

```javascript
var msg = this.contract.getFileWithHash(hashId);
```

This is my smart contract
```solidity
/*Get singal file with Hash ID*/
    function getFileWithHash(bytes32 hashId) public constant returns(string, address, uint) {
        return (fileInfos[hashId].fileName, fileInfos[hashId].addr, fileInfos[hashId].timestamp);
    }
```

I had already  tried to package  the  function call method with Promise, but It's still get huge response time when large requests coming. 

Why it's so slow and How can I improve it?? 

Thank you!!

**Comment by nivida** [comment]
Please ask this on https://ethereum.stackexchange.com/.
