### ISSUE TITLE
[React-native] Web3 Not connected to node Ethereum!

### ISSUE THREAD

**Issue by anhnam00** [ethereum/web3.js#1736]
Hello, 
i'm having a problem with my app (develop by React-Native) didn't connect to ETH Node.
console debug alway : ------------------isConnected: false 
please help me.

`
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableOpacity,
  View
} from 'react-native';

const Web3 = require('web3');
const web3 = new Web3();
web3.setProvider(new Web3(new Web3.providers.HttpProvider("https://rinkeby.infura.io/")));

export default class mobile extends Component {

	getBalance() {
		console.log('------------------isConnected: ' + web3.isConnected());
	}

	render () {
		return (
		  <View style={styles.container}>
			<TouchableOpacity style={styles.balanceButton} onPress={this.getBalance.bind(this)}>
			  <Text style={styles.balanceText}>Get Balance</Text>
			</TouchableOpacity>
		  </View>
		);
	 }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  balanceButton: {
    backgroundColor: '#0dab7f',
    padding: 10,
    width: 200,
    margin: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5
  },
  balanceText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16
  },
});

AppRegistry.registerComponent('mobile', () => mobile);
`

my dependencies:
"web3": "^0.20.6"
 "react": "16.3.1",
 "react-native": "0.55.4",

Thanks all!

**Comment by ToJen** [comment]
@anhnam00 did you come up with a solution

**Comment by jiangbo0216** [comment]
Invalid JSON RPC response: "Failed to connect to mainnet.infura.io.....
I met this, when i run web3.js like this 
```js
    web3.eth.getBlock('latest', (err, block) => {
      alert(block)
      console.log(block,err)
    });
```
is there anyone could help
