### ISSUE TITLE
web3 doesn't work in vanilla JS

### ISSUE THREAD

**Issue by yidongw** [ethereum/web3.js#1737]
I simply put this following JS on the local server but it didn't work. Does anyone know why?

`<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>`

`<script type="text/javascript">`

`const web3 = new Web3(window.web3.currentProvider);`

`if(!web3.isConnected()) {
  console.log("connected");
}
else {
  console.log("not connected")
}`

`</script>`

**Comment by MoreHotSauce** [comment]
`web3.isConnected()` should return true if it is connected and false if it isn't connected. So you don't need to do `!web3.isConnected()` because then you would be inverting the boolean.

**Comment by yidongw** [comment]
OK, I think I made a mistake there. The reason I'm asking about this is I couldn't get the Accounts. Please try the following script. I attached the result on my end.

`<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>`

`<script type="text/javascript">`

`const web3 = new Web3(window.web3.currentProvider);`

`if(web3.isConnected()) { console.log("connected"); } else { console.log("not connected") }`

`test();`
  `async function test(){`
`    console.log("here");`
`    const accounts = await web3.eth.getAccounts();`
`    console.log(accounts);`
`  };`

![image](https://user-images.githubusercontent.com/12843927/42013692-52d9efb8-7a53-11e8-9f7d-b326bfb8bc19.png)

**Comment by MoreHotSauce** [comment]
I would do something more like this: 
`if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  alert("No web3");
}
if(web3.isConnected()) { console.log("connected"); } else { console.log("not connected") }

web3.eth.getAccounts(function (error, accounts) {
  if (error) return console.error(error)
  web3.eth.defaultAccount = accounts[0];
  console.log(accounts[0])
})`

**Comment by yidongw** [comment]
Great. This actually worked.

How would I know that return promise is like this [error, accounts]?

https://web3js.readthedocs.io/en/1.0/web3-eth.html#getaccounts seems outdated.

**Comment by yidongw** [comment]
Is there anyway to use async/await ?
```
async function func(){ 
    const [error, accounts] = await web3.eth.getAccounts();
    console.log(accounts[0])
}
```
just doesn't work.

**Comment by yidongw** [comment]
I figured it out. I put the 0.20 version. Now I'm using 1.0.0, everything looks okay.
