### ISSUE TITLE
What is the path to getting 1.0 out of beta?

### ISSUE THREAD

**Issue by 1blockologist** [ethereum/web3.js#1740]
Out of curiosity.

Wasn't sure where the updated doc or team was on this

**Comment by max7z** [comment]
any roadmap?

**Comment by nivida** [comment]
We have no specific roadmap right now. I‘m implementing the new abi library next week and after that I will merge the ens implementation. We have some bugs with websockets and other things too. I will talk about an release plan with Fabian next week. I apologize for the delays.

**Comment by 1blockologist** [comment]
"We have some bugs with websockets and other things too"

1.0.0 doesn't have to be perfect, it needs to be called "not-beta". Who do I talk to about making that happen.
