### ISSUE TITLE
TypeError: this.provider.sendAsync is not a function

### ISSUE THREAD

**Issue by breckinridge22** [ethereum/web3.js#1742]
So I am trying to connect a web3 to a react application. I have made a local instance of my web3 provider using this code:

Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send
    if(typeof web3 != 'undefined'){
      console.log("Using web3 detected from external source like Metamask");
      this.web3Provider = new Web3(web3.currentProvider);
    } else {
       console.log("Using testrpc");
       this.web3Provider = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
    }

    this.web3 = new Web3(this.web3Provider);

I am trying to simply get the first account associated with this provider using an asynchronous call to 
this.web3.eth.getAccounts like this:

this.web3.eth.getAccounts(function(error, accounts) {
      if (error != null) {
        console.log("Error fetching accounts");
        return;
      }
      this.accounts = accounts;
      this.account = accounts[0];
      console.log(this.accounts);
    });

But I get this type error: TypeError: this.provider.sendAsync is not a function

I am using web3 version ^0.20.0. Can anyone help?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/

**Comment by kyriediculous** [comment]
No one ever answers on stackexchange so start doing your job. You're a collaborator and this is a community. It's not like it's a long answer either. 


the answer is

Before 1.0.0 
`const web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:port"))`

after 1.0.0 
`const web3 = new Web3("ws://127.0.0.1:port")`

`Now use web3 as you please`
