### ISSUE TITLE
isAddress just returned true for non-address

### ISSUE THREAD

**Issue by shaharsol** [ethereum/web3.js#1747]
web3 version: 0.20.6

nodejs code:

```
var Web3 = require('web3')
var web3 = new Web3()
console.log(web3.isAddress('60bDfEAc47d7B013A8AD9009043Ead33FF86F48A'))

```

output is "true"...

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
