### ISSUE TITLE
shh_newFilter: update API to allow complex topics

### ISSUE THREAD

**Issue by karalabe** [ethereum/web3.js#175]
The idea is to allow specifying potentially nested topic lists to create complex filter criteria. At the highest level the `topics` argument is still a list, but each element may be one of:

 - string: as used previously
 - null: signalling a wildcard/match-all
 - string array: to match any element within

A few samples:
```javascript
shh.filter({}).watch(function(err, msg) {
	console.log("Empty catcher:", msg)
})
shh.filter({topics: ["singleton"]}).watch(function(err, msg) {
	console.log("Single catcher:", msg)
})
shh.filter({topics: ["a", "b"]}).watch(function(err, msg) {
	console.log("Multi catcher:", msg)
})
shh.filter({topics: [["1", "2"]]}).watch(function(err, msg) {
	console.log("Binary catcher:", msg)
})
shh.filter({topics: [null, "x"]}).watch(function(err, msg) {
	console.log("Wildcard catcher:", msg)
})
```

These currently produce these JSON requests, the last two of which seem wrong

```javascript
[{"topics":[]}]
[{"topics":["0x73696e676c65746f6e"]}]
[{"topics":["0x61","0x62"]}]
[{"topics":["0x5b2231222c2232225d"]}]
[{"topics":["0x6e756c6c","0x78"]}]
```

**Comment by frozeman** [comment]
Thats currently not supported. @debris we would need to modifiy the topics parser to parse even two dimensions and transform values to hex (if not already)

**Comment by frozeman** [comment]
@debris Thats how topics filtering in whisper is now implemented in go:
```
[A, B] = A && B
[A, [B, C]] = A && (B || C)
```

**Comment by frozeman** [comment]
fixed in https://github.com/ethereum/web3.js/commit/c8f42262cc194b5898576514f1d2242cbff60e65
