### ISSUE TITLE
error in code example of subscribing logs

### ISSUE THREAD

**Issue by mohit-lala** [ethereum/web3.js#1762]
Top most example in web3.eth.subscribe

**old code :** 
var subscription = web3.eth.subscribe('logs', {
    address: '0x468b4f26e9294ae914fb24f32cc5dd5373032447'
}, function(error, result){
    if (!error)
        console.log(log);
});

// the log in console.log() should be replaced by result.

**Comment by frozeman** [comment]
fixed in #1876
