### ISSUE TITLE
Error: Transaction was not mined within750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!

### ISSUE THREAD

**Issue by saitam1** [ethereum/web3.js#1763]
I am getting the `tx hash` returned, but the transaction is never mined. Does anybody know how to solve this issue? Here is the complete error message:

> sent 0xb14852674c10adfdaf590c687d5502ea0d992d469791ae8e4094b22ccfc0de5d
> 
> (node:20982) UnhandledPromiseRejectionWarning: Error: Transaction was not mined within750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
>     at /home/user/code/node_modules/web3-core-method/src/index.js:392:42
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:182:7)
> (node:20982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:20982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

And here is the code I use for `nodejs` + `web3` :

```
const Web3 = require('web3')
const Tx = require('ethereumjs-tx')

const web3 = new Web3(new Web3.providers.HttpProvider('https://kovan.infura.io/apikey'))
const addressFrom = '0x002D18...'
const privKey = '240462...'
const addressTo = '0x36075430619b21Fff798454e2D5C81E9C18DEe81'

var contractABI = new web3.eth.Contract(
    [...abi...], addressTo);

const contractFunction = contractABI.methods.changeBox(5);
const functionAbi = contractFunction.encodeABI();

function sendSigned(txData, callback) {
    //const privateKey = new Buffer(config.privKey, 'hex')
    const privateKey = Buffer.from(privKey, 'hex');
    const transaction = new Tx(txData)
    transaction.sign(privateKey)
    const serializedTx = transaction.serialize().toString('hex')
    web3.eth.sendSignedTransaction('0x' + serializedTx, callback)
}

web3.eth.getTransactionCount(addressFrom).then(txCount => {
    // construct the transaction data
    const txData = {
        nonce: web3.utils.toHex(txCount),
        gasLimit: web3.utils.toHex(40000),
        //gasPrice: web3.utils.toHex(10e9), // 10 Gwei
        to: addressTo,
        from: addressFrom,
        data: functionAbi
        //value: web3.utils.toHex(web3.utils.toWei(123, 'wei'))
  }

    sendSigned(txData, function(err, result) {
        if (err) return console.log('error', err)
        console.log('sent', result)
    })

})
```

The smart contract itself looks like this:

```
pragma solidity ^0.4.24;

contract Test2 {
    address public bank;

    struct Box {
        uint size;
    }
    Box public box;

    constructor() public {
        box.size = 3;
        bank = 0xa2079636c495bDbaCfe0298a5aB92B397c12a3E5;

    }

    function changeBox(uint _change) public {
        box.size = _change;
    }

    function getBox() public returns (uint) {
        return box.size;
    }  
}
```

**Comment by saitam1** [comment]
Thank you! I am doing it now this way:

```
const Web3 = require('web3')

// connect to Infura node
const web3 = new Web3(new Web3.providers.HttpProvider('https://kovan.infura.io/api_key'))

// the addresses & private key 
const addressFrom = '0x002D189c25958c60736aE21C966ff3131C2AC849';
const contractAddress = '0x36075430619b21Fff798454e2D5C81E9C18DEe81';
const privKey = '240462d...';

//ABI objects
var contractABI = new web3.eth.Contract(
    [ ...abi... ],
    contractAddress);
const contractFunction = contractABI.methods.changeBox(5);
const functionABI = contractFunction.encodeABI();

// construct the Tx data
const rawTx = {
    //gasPrice: '0x09184e72a000',
    gasLimit: web3.utils.toHex(25000),
    to: contractAddress,
    from: addressFrom,
    data: functionABI
    };

//sign Tx
web3.eth.accounts.signTransaction(rawTx, privKey)
    .then(RLPencodedTx => {
        web3.eth.sendSignedTransaction(RLPencodedTx['rawTransaction'])
            .on('receipt', console.log);
    });
```

But now I am getting the following error returned:

> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 750000000000000 and got: 0.

The thing is my account has enough funds, you can check it here `0x002D189c25958c60736aE21C966ff3131C2AC849` Do you know why web3 is throwing the wrong error?

**Comment by jroberts101** [comment]
Check your `privKey`. I suspect it should be `0x``240462d...`

**Comment by nivida** [comment]
Please ask further questions on https://ethereum.stackexchange.com/

**Comment by Runskey** [comment]
I got the same issue under Geth/POA private chain.

I referred to this post: https://github.com/ethereum/web3.js/issues/1102, and got the issue resolved by downgrading web3js from 1.0.0-beta.36 to 1.0.0-beta.34.

**Comment by pieterhartel** [comment]
Is there  way to reduce the 750 seconds? I have about 50,000 transactions in my truffle tests and if many of these take 750 seconds, my tests will take a very, very long time.

```
$ truffle version
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v10.15.0
```

**Comment by ChristobelDiana** [comment]
tried downgrading web3 to 1.0.0-beta.34. still I have the same problem

**Comment by parin13** [comment]
@nivida  it doesn't work with infuera, is there any workaround for that
