### ISSUE TITLE
Bug Of Docs eth.subscribe - receiptRoot Should Be receiptsRoot

### ISSUE THREAD

**Issue by justinchou** [ethereum/web3.js#1769]
I Read The Doc About [subscribe(“newBlockHeaders”)](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-newblockheaders) And Found The Returns Value `receiptRoot` May Be `receiptsRoot`. Missing A `s` In The Middle.

**Comment by frozeman** [comment]
fixed in #1876
