### ISSUE TITLE
Using web3 inside a web worker

### ISSUE THREAD

**Issue by 26000** [ethereum/web3.js#1774]
Is it possible? When i `importScripts("web3.min.js")` inside one, says `Uncaught ReferenceError: Web3 is not defined` when i try to call it. I tried browserify with webworkify, but it said `Uncaught ReferenceError: window is not defined`. So does web3 necessarily need `window`, which is inaccessible from a web worker context, or there's a workaround?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
