### ISSUE TITLE
npm install web3 failed

### ISSUE THREAD

**Issue by CorentinPacaud** [ethereum/web3.js#1776]
When I try to install the web3 package, it always fails !
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No such file or directory
npm ERR! github.com[1: 192.30.253.112]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128 #

**Comment by Miraj98** [comment]
Same here! I am using macOS Mojave beta 2 version. This is my error message: 
```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /usr/local/lib/node_modules/web3/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
./configure: line 1904: config.log: Permission denied
./configure: line 1914: config.log: Permission denied


> scrypt@6.0.3 install /usr/local/lib/node_modules/web3/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/web3/node_modules/scrypt/build'
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/web3/node_modules/scrypt
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mirajshah/.npm/_logs/2018-07-14T17_11_11_366Z-debug.log
```

**Comment by dp12321** [comment]
C:\ruanjian\webstorm\webstromspace\untitled>npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
[..................] | fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] | fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] \ fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] / fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
[..................] - fetchMetadata: WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmj
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\base64-js-62c584e3\lib\b64.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\duplex.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\GOVERNANCE.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\passthrough.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\readable-browser.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\readable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\transform.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\writable-browser.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\readable-stream-4ab32570\writable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\web3-providers-http-8e9c99df\package-lock.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\eth-lib-38d2d9ee\lib\transaction.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\eth-lib-38d2d9ee\lib\account.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\eth-lib-38d2d9ee\lib\types.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\eth-lib-38d2d9ee\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\tar.gz-98b4a0fa\history.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\tar.gz-98b4a0fa\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\tar.gz-98b4a0fa\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\tar.gz-98b4a0fa\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\node_modules\.staging\underscore-dfe23047\underscore.js'
npm WARN enoent ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\package.json'
npm WARN untitled No description
npm WARN untitled No repository field.
npm WARN untitled No README data
npm WARN untitled No license field.

npm ERR! code EINTEGRITY
npm ERR! sha1-K9OB8usgECAQXNUOpZ2mMJBpRoY= integrity checksum failed when using sha1: wanted sha1-K9OB8usgECAQXNUOpZ2mMJBpRoY= but got sha1-N6e+vlvXXfaoFBgonLOujPlgv80=. (6011 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dongpeng\AppData\Roaming\npm-cache\_logs\2018-07-15T12_42_11_829Z-debug.log

C:\ruanjian\webstorm\webstromspace\untitled>npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN enoent ENOENT: no such file or directory, open 'C:\ruanjian\webstorm\webstromspace\untitled\package.json'
npm WARN untitled No description
npm WARN untitled No repository field.
npm WARN untitled No README data
npm WARN untitled No license field.

npm ERR! code EINTEGRITY
npm ERR! sha1-K0hl29Rr6BIlcT9Om/5Lz09oCk8= integrity checksum failed when using sha1: wanted sha1-K0hl29Rr6BIlcT9Om/5Lz09oCk8= but got sha1-eiyOx7aRpSPXSMabTDC2Yns+3WA=. (572023 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dongpeng\AppData\Roaming\npm-cache\_logs\2018-07-15T12_43_58_728Z-debug.log

**Comment by dp12321** [comment]
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\dongpeng>npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Suppor
t
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecat
ed and your application is vulnerable. Please use tar module instead: https://np
mjs.com/tar

> scrypt@6.0.3 preinstall C:\Users\dongpeng\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\dongpeng\node_modules\scrypt
> node-gyp rebuild


C:\Users\dongpeng\node_modules\scrypt>if not defined npm_config_node_gyp (node "
C:\ruanjian\webstorm\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\ru
anjian\webstorm\node.js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\ruanjian\webstorm\node.js\no
de_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\ruanjian\webstorm\node.js\nod
e_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\ruanjian\webstorm\node.js\node_modules\npm\node_modules
\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\ruanjian\\webstorm\\node.js\\node.exe" "C:\\ruanjian\\webs
torm\\node.js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\Users\dongpeng\node_modules\scrypt
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\dongpeng\packa
ge.json'
npm WARN dongpeng No description
npm WARN dongpeng No repository field.
npm WARN dongpeng No README data
npm WARN dongpeng No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dongpeng\AppData\Roaming\npm-cache\_logs\2018-07-15T12_52_
04_495Z-debug.log

C:\Users\dongpeng>

**Comment by Radioff** [comment]
I tried to install this version: web3@1.0.0-beta.26 and got the same issue on Windows10:

1031 warn inbox@1.0.0 No description
1032 warn inbox@1.0.0 No repository field.
1033 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
.......
1038 verbose node v8.9.3
1039 verbose npm  v5.5.1
1040 error code ELIFECYCLE
1041 error errno 1
1042 error scrypt@6.0.3 install: `node-gyp rebuild`
1042 error Exit status 1
1043 error Failed at the scrypt@6.0.3 install script.
1043 error This is probably not a problem with npm. There is likely additional logging output above.
1044 verbose exit [ 1, true ]

**Comment by arherzf8er** [comment]
Same here on Windows 10. One week ago there were no problems.

> 
> scrypt@6.0.3 preinstall c:\b\d\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install c:\b\d\node_modules\scrypt
> node-gyp rebuild

> c:\b\d\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
module.js:549
    throw err;
    ^

> gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\b\d\node_modules\scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN d@1.0.0 No description
npm WARN d@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.

**Comment by nivida** [comment]
Sorry guys I can't reproduce this error. I've created an new folder and created an package.json with ```npm init```after that I installed web3 with ```npm install web3``` and it works as expected. Have you tried todo this in a clean folder like i have?

**Comment by CorentinPacaud** [comment]
@nivida For me, it is blocked at 
```fetchMetadata: sill resolveWithNewModule http-https@1.0.0 checking installable status```
and then, this error appears : 
```npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No such file or directory
npm ERR! github.com[1: 192.30.253.112]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128```

I will contact my IT team to see it can be resolve with them but one of my friend tried to install it, and he had an error too.

**Comment by nivida** [comment]
@CorentinPacaud You tried in a new folder with an empty package.json? and the same NPM and node versions as I have?

**Comment by nivida** [comment]
@dp12321 i think you should set python in the cli PATH as you can see here: https://github.com/felixrieseberg/windows-build-tools/issues/56

It also looks like you don't have a package.json in the directory: ```C:\Users\dongpeng\```

**Comment by nivida** [comment]
@Miraj98 I don't think you installed npm/node with the right permissions.. try with ```sudo npm install web3``` or install npm/node correctly :)

**Comment by nivida** [comment]
I will close it because I can't see any errors on our site.

**Comment by CorentinPacaud** [comment]
@nivida it is a proxy/firewall problem. I fixed it the help of my IT team.

**Comment by adnanozsoy** [comment]
git config --global hub.protocol https 
will solve it.

**Comment by bryenxie** [comment]
here is on Macbook (OS X 10.11.6 (15G20015))


npm install web3



```

npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /Users/IDK/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /Users/IDK/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/IDK/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/IDK/node_modules/scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/IDK/package.json'
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN IDK No description
npm WARN IDK No repository field.
npm WARN IDK No README data
npm WARN IDK No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/IDK/.npm/_logs/2018-10-04T21_41_54_923Z-debug.log

```

**Comment by Elvise177** [comment]
@CorentinPacaud
The same problem as yours. How did you solve this problem?

**Comment by chuanqin3** [comment]
> @Miraj98 I don't think you installed npm/node with the right permissions.. try with `sudo npm install web3` or install npm/node correctly :)

Actually this `sudo` command solved my problem. weird... Usually I don't need to use it when install a package. But thanks anyway.

**Comment by borgeens** [comment]
root@iZj6cbd4df3cja1epkztv9Z:~# sudo npm install web3
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

> websocket@1.0.26 install /root/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/root/node_modules/websocket/build'
/root
└─┬ web3@1.0.0-beta.37 
  └─┬ web3-core@1.0.0-beta.37
    └─┬ web3-core-requestmanager@1.0.0-beta.37
      └─┬ web3-providers-ws@1.0.0-beta.37
        └── websocket@1.0.26  (git://github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2)

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
root@iZj6cbd4df3cja1epkztv9Z:~# 



help

**Comment by navya-penmetsa** [comment]
Not able to install web3.js on Ubuntu 18.04.1, getting the below error:

ubuntu@ubuntu:~/web3$ sudo npm install web3
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "web3"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install web3 as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/web3/npm-debug.log

Please tell if I am doing it wrong.
[npm-debug.log](https://github.com/ethereum/web3.js/files/2762695/npm-debug.log)

**Comment by GameBitToken** [comment]
Try to install npm install web3@0.19

**Comment by SebastianGiro** [comment]
> Sorry guys I can't reproduce this error. I've created a new folder and a package.json with `npm init`after that I installed web3 with `npm install web3` and it works as expected. Have you tried todo this in a clean folder like i have?
> 
> Versions:
> 
> ```
> OS: macOS High Sierra 10.13.6
> NPM: 6.1.0
> Node: 10.0.5
> ```

try with node 12.3.1, for some reason the error appears when updating node, its working fine with an old version of nodejs

**Comment by abdulmuqsit10101** [comment]
hay I have answer of that just delete package-lock.json and run command "npm install"

**Comment by G-PRABU** [comment]
I had same issue in windows 10 and i solved this by doing these steps.

- Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).

or 
 https://github.com/nodejs/node-gyp
refer this link

**Comment by ehanoc** [comment]
This issue keeps popping up and keeps being closed. Its extremely annoying.

the issue is this : ``` https://github.com/ethereum/web3.js/blob/58a4432cb19626254d10054e2a800ef178221a8f/packages/web3-providers/package.json#L31 ```

Forces all of us to change global configs to forcebly use https instead of git protocol. Can we change this?
