### ISSUE TITLE
Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 750000 and got: 0.

### ISSUE THREAD

**Issue by saitam1** [ethereum/web3.js#1779]
When checking with `web3.eth.getBalance` my balance, I get the following return value: `2839511483168873270`.

At the same time I get the following error!: 

> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 750000 and got: 0.

Whats going on here??

My `nodejs` / `web3` code is as simple as this:

```
const Web3 = require('web3')

// connect to Infura node
const web3 = new Web3(new Web3.providers.HttpProvider('https://kovan.infura.io/api_key'))

// the addresses & private key 
const addressFrom = '0x002D189c25958c60736aE21C966ff3131C2AC849';
const contractAddress = '0x36075430619b21Fff798454e2D5C81E9C18DEe81';
const privKey = '240462d...';

//ABI objects
var contractABI = new web3.eth.Contract(
    [ ...abi... ],
    contractAddress);
const contractFunction = contractABI.methods.changeBox(5);
const functionABI = contractFunction.encodeABI();

// construct the Tx data
const rawTx = {
    gasLimit: web3.utils.toHex(25000),
    to: contractAddress,
    from: addressFrom,
    data: functionABI
    };

//sign & send Tx
web3.eth.accounts.signTransaction(rawTx, privKey)
    .then(RLPencodedTx => {
        web3.eth.sendSignedTransaction(RLPencodedTx['rawTransaction'])
            .on('receipt', console.log);
    });
```

**Comment by carver** [comment]
This was cross-posted to https://stackoverflow.com/questions/51342417/ethereum-web3-sendsignedtransaction-insufficient-funds-the-account-does-no

I highly recommend updating `signTransaction` to throw an error if the private key does not match the address in the `from` field.

**Comment by nivida** [comment]
I will close this because it's already been posted on stackoverflow.

**Comment by daniel-hursan** [comment]
Any idea why I have this exact same error, although the private key is correct (exported as string from MetaMask)? Can there be any other hidden errors behind this?
