### ISSUE TITLE
Win10 npm install web3 doesn't work

### ISSUE THREAD

**Issue by arherzf8er** [ethereum/web3.js#1783]
Not new to web3 and have been actively using web3@1.0.0 since May, never experienced errors on numerous installs. Last time I ```npm install web3``` on this machine over a week ago with no probs.
Also to mention no programs were installed on this machine after last successful web3 installation.

Since last Sunday I'm getting quite the same result. Please find attached the log file.
It should be also noted that ```npm install web3@0.20.6``` works as usual.
```
npm install --save web3@0.20
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN deal1@1.0.0 No description
npm WARN deal1@1.0.0 No repository field.

+ web3@0.20.6
added 4 packages from 4 contributors, removed 295 packages and audited 6 packages in 34.952s
found 0 vulnerabilities
```

Please inform what additional information might help to resolve the issue.

What have been done since then:
-

- [x] Uninstall nodejs while cleaning all trails
- [x] Uninstall python 3.6
- [x] Cleaning all the registry from relevant trails
- [x] npm install -g --production windows-build-tools
- [x] npm install -g node-gyp-install
- [x] npm install -g node-gyp
- [x] Install python 2.7 in root directory c:\python\
- [x] Add all relevant pathes to PATH
- [x] Install latest nodejs in root directory c:\nodejs\

Using node@v10.6.0 and npm@6.1.0:
-
```
mkdir app
cd app
npm init
npm install web3 --save
```
> npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module i
nstead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall c:\app\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install c:\app\node_modules\scrypt
> node-gyp rebuild
c:\app\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
rebuild )
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:91:20)
    at Object.runInThisContext (vm.js:298:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at evalScript (internal/bootstrap/node.js:527:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\app\node_modules\scrypt
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Also tried yarn add with no luck.

Please find attached the log file
-
[2018-07-17T09_45_55_624Z-debug.log](https://github.com/ethereum/web3.js/files/2201125/2018-07-17T09_45_55_624Z-debug.log)

**Comment by nivida** [comment]
Thanks for that well documented issue! I'll test it on my windows computer tonight.

**Comment by CryptoSmileee** [comment]
You could try to run this first as workaround:

npm install nan --save

**Comment by arherzf8er** [comment]
Thank you for the suggestion, I've already tried and unfortunately it didn't work out this time either.

> c:\app>npm install nan --save
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

> +nan@2.10.0
removed 296 packages and updated 1 package in 2.224s

> c:\app>npm install --save web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall c:\app\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install c:\app\node_modules\scrypt
> node-gyp rebuild


> c:\app\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
module.js:549
    throw err;
    ^

> Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\app\node_modules\scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.

> npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nivida** [comment]
So I've tested it on my windows notebook and I can install web3 if everything is configured correctly. 

1. ```npm install --global --production windows-build-tools```
2. ```setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"````
3. ```npm config set python python2.7 --global```
4. ```npm config set python C:\Python27\python.exe --global```
5. ```npm config set msvs_version 2015 --global```
6. ```set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140```

After that it worked for me.

**Comment by migueldeguzman** [comment]
@nividia this didnot work, the scrypt remains a problem

**Comment by sreepriyaks** [comment]
tried all these options. but cannot get web3 installed on win10.

**Comment by igoreskin** [comment]
The problem with web3@^0.20.0 and probably with other versions earlier than web3@^1.0.0-beta.36 is that modules like web3.utils necessary for getting balances, building transactions etc. don't seem to work or perhaps even exist, so installing the 0.20.0 version doesn't really solve the problem. I am nowhere near 100% sure, but it seems that running npm install --global --production windows-build-tools from Windows PowerShell (as an ADMIN!) and then installing web3@^1.0.0-beta.36 is the only way.

**Comment by jaikrish5** [comment]
@nivida even the first step 1. npm install --global --production windows-build-tools
$ npm install --global --production windows-build-tools

> windows-build-tools@5.1.0 postinstall C:\Users\S.Jaikrish\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js



Downloading python-2.7.15.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\S.Jaikrish\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\S.Jaikrish\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows-build-tools@5.1.0 postinstall: `node ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the windows-build-tools@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\S.Jaikrish\AppData\Roaming\npm-cache\_logs\2019-01-31T17_19_56_059Z-debug.log

**Comment by jaikrish5** [comment]
@nivida i have followed all the steps as mentioned above . but facing problems regarding the last one
i.e:set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140
when i open my MSBuild folder i do not have v.4.0 but v3.0 and v3.5 .
what should i do????
please help

**Comment by paulmelero** [comment]
I think these steps (https://github.com/ethereum/web3.js/issues/1783#issuecomment-405650471) should be included in the [Readme](https://github.com/ethereum/web3.js/blob/1.0/README.md).

Or check if with https://github.com/ethereum/web3.js/pull/2642 these errors cease to raise.

**Comment by siaosiw** [comment]
I ahve tried about every option I can come across in regards to downloading a particular version web3@1.0.0-beta46 for a bootcamp Im doing at the moment can anyone help me out please, it would be greatly appreciated. tbelow is the script I consistently get back.
Cheers.

gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\HOME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HOME\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\test\node_modules\scrypt
gyp ERR! node -v v9.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache\_logs\2019-06-05T02_50_11_237Z-debug.log
PS C:\Windows\system32\test> npm install --save scrypt6.0.3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/scrypt6.0.3 - Not found
npm ERR! 404
npm ERR! 404  'scrypt6.0.3@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache\_logs\2019-06-05T02_52_50_289Z-debug.log
PS C:\Windows\system32\test>

**Comment by Islandersfan2016** [comment]
> I ahve tried about every option I can come across in regards to downloading a particular version web3@1.0.0-beta46 for a bootcamp Im doing at the moment can anyone help me out please, it would be greatly appreciated. tbelow is the script I consistently get back.
> Cheers.
> gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\HOME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\HOME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Windows\system32\test\node_modules\scrypt
> gyp ERR! node -v v9.10.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\test\package.json'
> npm WARN test No description
> npm WARN test No repository field.
> npm WARN test No README data
> npm WARN test No license field.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scrypt@6.0.3 install: node-gyp rebuild
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the scrypt@6.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache_logs\2019-06-05T02_50_11_237Z-debug.log
> PS C:\Windows\system32\test> npm install --save scrypt6.0.3
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/scrypt6.0.3 - Not found
> npm ERR! 404
> npm ERR! 404  'scrypt6.0.3@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache_logs\2019-06-05T02_52_50_289Z-debug.log
> PS C:\Windows\system32\test>

I am having the same problem with the same error message while trying to install web3@1.0.0-beta46. Has anyone solved this issue?

**Comment by siaosiw** [comment]
Sorry I didn't get that problem solved. I ended up asking for refund  with
much regret. Apparently it is much easier if you use a Linux OS.
Let me know if you find a fix please.

Very best

**Comment by Meharab** [comment]
### need help!!!..i am having this issues when i try to install node-gyp **3.6.2**
PS C:\Users\User> npm install --global node-gyp@3.6.2
npm WARN deprecated request@2.88.2: request has been deprecated, see #3142
npm ERR! path C:\Users\User\AppData\Roaming\npm\node-gyp.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\User\AppData\Roaming\npm\node-gyp.cmd: is outside C:\Users\User\AppData\Roaming\npm\node_modules\node-gyp and not a link
npm ERR! File exists: C:\Users\User\AppData\Roaming\npm\node-gyp.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\User\AppData\Roaming\npm-cache_logs\2020-02-13T05_12_13_683Z-debug.log
