### ISSUE TITLE
how private(local) network works ?

### ISSUE THREAD

**Issue by kashifaa** [ethereum/web3.js#1786]
Hi all , 

I build a private network of 4 nodes , and I send a message with web3.shh . In subscription console it shows message just one time, I think it should show this message 3 time .

I want to know how this private network works in terms of code ? .

is there any better way that all nodes on same machine receives the messages and respond to these messages ?

Thanks in advance

**Comment by kashifaa** [comment]
can anybody plz reply here ????

**Comment by nivida** [comment]
@kashifaa Please ask this question here: https://ethereum.stackexchange.com/
