### ISSUE TITLE
Wrong function mapping in web3 when 2 functions with different number of arguments exist

### ISSUE THREAD

**Issue by a-romero** [ethereum/web3.js#1787]
Two of the functions in Solidity are the following:
`    function setNum(uint _num) registeredOnly(msg.sender) external {   
        storage.setNum(msg.sender, _num);   
    }`

`function setNum(address _address, uint _num) registeredOnly(msg.sender) external {
        storage.setNum(_address, _num);
    }`

I'd expect the number of arguments determine which one to use, but does not seems to be the case:

`MyContract.setNum(number, (error, txHash) => { 
      if (error) { this.props.actions.setNumERROR(error) }
      waitForMined(addr, txHash, { blockNumber: null }, actions,
        () => {
          this.props.actions.setNumPENDING()
        },
        (total) => {
          console.log('waitForMined complete')
          this.props.actions.setNumSUCCESS(txHash, total)
        }
      )
    }`

The above will throw an **Invalid number of arguments to Solidity function** error, and will only work if I pass the additional address parameter.

After further testing, web3 seems to always pick up the first function defined in the ABI interfaces.

**Comment by nivida** [comment]
This will solve your issue http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id12 
``` 
The methods of this smart contract are available through:

The name: myContract.methods.myMethod(123)
The name with parameters: myContract.methods['myMethod(uint256)'](123)
The signature: myContract.methods['0x58cf5f10'](123)

This allows calling functions with same name but different parameters 
from the JavaScript contract object.
```
