### ISSUE TITLE
How can I deploy contract by private key?

### ISSUE THREAD

**Issue by zacard-orc** [ethereum/web3.js#1788]
If I have address 0x5696627a830f91132cc83eb7FD38c11A2AFba021 and privateKey 0x***************************，How can I deploy and sendSignTranscation？

//Code Sample Below:
let bb=web3_TokenDemoByInParam
  .deploy({
    data: src_bytecode,
    // arguments: [100000000,"HYAC ASFSDF",18,"HYAC"]
    arguments:[ArgContactAmount,ArgContactFullName,ArgContactDecimal,ArgContactSymbol]
  })
  .send({
    from: '0x5696627a830f91132cc83eb7FD38c11A2AFba021',
    gas: 4712388,
    gasPrice: 6000000000,
  }, function(error, transactionHash){
    if(error){ console.log('[DPCT]'+JSON.stringify(error,2)) }
  })

I see Docs :https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html?highlight=deploy#deploy
no any comment about sendSignTransaction in this section.

Object: The transaction object:

Array - arguments: The arguments passed to the method before. They can be changed.
Function - send: Will deploy the contract. The promise will resolve with the new contract instance, instead of the receipt!
Function - estimateGas: Will estimate the gas used for deploying.
Function - encodeABI: Encodes the ABI of the deployment, which is contract data + constructor parameters

Please help me :)

**Comment by fangdengfu** [comment]
i was do this, but it has error. i don't know why.   so sad..
https://ethereum.stackexchange.com/questions/54907/deploy-contract-for-web3-js-1-0-bate-3-4-jump-error-transaction-ran-out-of-g

**Comment by justinchou** [comment]
@fangdengfu your transaction shows gas limit error, and below the gas and gasUsed are the same is also a sign that you need to provide more gas to make the transaction successful.

**Comment by nivida** [comment]
Please ask further question on https://ethereum.stackexchange.com/
