### ISSUE TITLE
A return value of toHex a character string of only numerals can not be as expected.

### ISSUE THREAD

**Issue by kobumax** [ethereum/web3.js#1792]
The application generates a character string of type bytes32. Data after HEX conversion is passed to the contract. There are cases where the character string is rarely only numbers.
For example, `"0003"` is the case.
I expect `0x30303033` as a result of `toHex`, but in fact it will be `0x3`.
Is this normal behavior?
Even if one character is entered, it will result as expected.
For example, `"A003"` will be `0x41303033` and it is as expected.
I know that the cause is a branch by `isFinite`, but why does this check exist?
I'd like to treat bytes32 type value as character string generically.

**Comment by DmytroNazarenko** [comment]
+1

**Comment by kobumax** [comment]
I 'm sorry I do not understand the above meaning...

**Comment by DmytroNazarenko** [comment]
I have the similar issue as you

**Comment by kobumax** [comment]
That's right, thank you！

**Comment by nivida** [comment]
Could you add a code example and the version of web3 you are using?
