### ISSUE TITLE
The signTransaction method does not work correctly.

### ISSUE THREAD

**Issue by zuart** [ethereum/web3.js#1793]
**Input:**
oTX: 
{
  "to": "0xed32e0fd016810B7d3606e1Ae163B58266c544B0",
  "gasLimit": "0xc350",
  "value": "0x2386f26fc10000",
  "chainId": "0x01",
  "gasPrice": "0x4a817c800",
  "nonce": "0x4"
};
var key = "9cb1 ... 2a84";

**Method 1 - OK:**
var _key = new Buffer(key, 'hex');
var _tx = new TX(tx);
_tx.sign(_key);

var _raw = _tx.serialize();
var _rr = '0x' + _raw.toString('hex');

:: HASH1 = '0xf86b ... 25a00b3b ... 7f39';

**Method 2 - ERR:**
web3.eth.signTransaction(tx, key).then(trans);

:: HASH2 = '0xf86b ... 25a009fd ... 08b5';

And the description of the method signTransaction  in the documentation does not correspond to the actual result.

**Comment by takahser** [comment]
I had the same error as in #1986 when using `signTransaction`. Rolling back to `"web3": "1.0.0-beta.34"` fixed it for me.

**Comment by takahser** [comment]
I had the same error as in #1986 when using `signTransaction`. Rolling back to `"web3": "1.0.0-beta.34"` fixed it for me.

**Comment by takahser** [comment]
I had the same error as in #1986 when using `signTransaction`. Rolling back to `"web3": "1.0.0-beta.34"` fixed it for me.

**Comment by takahser** [comment]
I had the same error as in #1986 when using `signTransaction`. Rolling back to `"web3": "1.0.0-beta.34"` fixed it for me.

**Comment by dileepfrog** [comment]
I have also just verified this problem - it seems that `chainId` is not being properly encoded. In my case, I'm using a private network with `chainId` of 4 decimal digits, which seems to be causing the issue. When using `ethereumjs-tx` to sign and RLP encode identical arguments, the tx sends successfully. 

Rolling back to `"web3": "1.0.0-beta.37"` fixes this issue.
