### ISSUE TITLE
I can't make token listening for deployed contract

### ISSUE THREAD

**Issue by vincentwang0736** [ethereum/web3.js#1796]
Hi all ,
I have a mission is to make token event lisenting for a deployed contract.
Here is my code:

> var Web3 = require("web3");
> var fs = require("fs");
> var web3 = new Web3();
> web3.setProvider(new Web3.providers.HttpProvider("https://mainnet.infura.io/xxxxxx"));
> var eth=web3.eth;
> var tokenABI = '[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"tokens","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"tokens","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balances","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowed","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"tokenOwner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balanceOfOwner","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"tokens","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"tokenOwner","type":"address"},{"name":"spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"tokens","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"tokenOwner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"tokens","type":"uint256"}],"name":"Approval","type":"event"}]';
> 
> var tokenAddr = '0x4d9e23a3842fe7eb7682b9725cf6c507c424a41b';
> var tokenContract = new web3.eth.Contract(tokenABI);
> //var tokenContract = web3.eth.contract(tokenABI);
> var tokenContractInstance = tokenContract.at(tokenAddr);
> 
> tokenContract.events.Transfer({
>     fromBlock: 0,
>     toBlock:'latest'
> }, function(error, event){ /*console.log("result:\n"+JSON.stringify(event)); */})
> .on('data', function(event){
>     console.log(event); // same results as the optional callback above
> })
> .on('changed', function(event){
>     // remove event from local database
> })

But I got this exception:

> throw new Error('You must provide the json interface of the contract when instantiating a contract object.');
>         ^
> 
> Error: You must provide the json interface of the contract when instantiating a contract object.
>     at Contract (/home/code/nodepro/erctest/node_modules/web3-eth-contract/src/index.js:70:15)
>     at new Contract (/home/code/nodepro/erctest/node_modules/web3-eth/src/index.js:148:22)
>     at Object.<anonymous> (/home/code/nodepro/erctest/listener.js:11:21)
>     at Module._compile (internal/modules/cjs/loader.js:654:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
>     at Module.load (internal/modules/cjs/loader.js:566:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
>     at startup (internal/bootstrap/node.js:201:19)

I'm using the ABI of BNB for testing.

Anyone can help me? Thanks a lot!

**Comment by frozeman** [comment]
I can see you prove the json interface correctly. The Code that spits out this error is:
```
if(!jsonInterface || !(Array.isArray(jsonInterface))) {
        throw new Error('You must provide the json interface of the contract when instantiating a contract object.');
    }
```

Could it be that you run it in an old browser that doesn’t have `Array.isArray()`?

**Comment by vincentwang0736** [comment]
Thanks for your reply @frozeman .after I removed ' of tokenABI,.like this:

> var tokenABI = [{"constant":true,"inputs":[],"name":"name","outputs":
It runs.

But I heard that Infura dosen't suport web3.eth.filter. Is really？

**Comment by Saurabh1402** [comment]
this is wrong ---> var tokenContract = new web3.eth.Contract(tokenABI);
this is correct ---> var tokenContract = web3.eth.contract(tokenABI);
