### ISSUE TITLE
How to SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by vincentwang0736** [ethereum/web3.js#1808]
I was follwing the web3.filter guide,
Here is my code:

> from web3.auto import w3

But when I run this code,I got this exception:

> (function (exports, require, module, __filename, __dirname) { from web3.auto import w3
>                                                                    ^^^^
> 
> SyntaxError: Unexpected identifier
>     at new Script (vm.js:51:7)
>     at createScript (vm.js:136:10)
>     at Object.runInThisContext (vm.js:197:10)
>     at Module._compile (internal/modules/cjs/loader.js:618:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
>     at Module.load (internal/modules/cjs/loader.js:566:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
>     at startup (internal/bootstrap/node.js:201:19)

Anyone can help me? Thanks a lot.

**Comment by nivida** [comment]
The correct syntax for the import statement in JS is: ```import * from "module"```
Could you please add the complete code?
Without more information is it hard to figure out what the problem might be.

**Comment by nivida** [comment]
Please ask further questions on https://ethereum.stackexchange.com
