### ISSUE TITLE
How to fix TypeError: 'xxx' is not a function

### ISSUE THREAD

**Issue by vincentwang0736** [ethereum/web3.js#1809]
I have a project is to listen event of one deployed contract.
Now I' m using BNB for testing.
Here is my code:

> var Web3 = require("web3");
> var fs = require("fs");
> web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/xxxxxx"));
> var eth=web3.eth;
> var tokenABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"tokens","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"tokens","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balances","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowed","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"tokenOwner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balanceOfOwner","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"tokens","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"tokenOwner","type":"address"},{"name":"spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"tokens","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"tokenOwner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"tokens","type":"uint256"}],"name":"Approval","type":"event"}];
> 
> var tokenAddr = '0x4d9e23a3842fe7eb7682b9725cf6c507c424a41b';
> var tokenContract = new web3.eth.Contract(tokenABI, tokenAddr);
> 
> 
> var myEvent = tokenContract.Transfer({}, {fromBlock: 400000,toBlock:'latest'});
> myEvent.watch(function(error, result){
>     console.log("on watch"); 
>     console.log(result);
> });

But after I run this code, I got error as below:

> var myEvent = tokenContract.Transfer({}, {fromBlock: 400000,toBlock:'latest'});
>                             ^
> 
> TypeError: tokenContract.Transfer is not a function
>     at Object.<anonymous> (/home/code/nodepro/erctest/ListenerDemo.js:27:29)
>     at Module._compile (internal/modules/cjs/loader.js:654:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
>     at Module.load (internal/modules/cjs/loader.js:566:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
>     at startup (internal/bootstrap/node.js:201:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

I'm using abi and address of BNB. and Transfer is one of BNB's events.
So anyone can tell me what's the wrong or give me some help? Thanks a lot!

**Comment by nivida** [comment]
I think your support request has resolved as I can see here: https://github.com/ethereum/web3.js/issues/1811
