### ISSUE TITLE
web3.js  web3.eth.Contract通过getPastEvents获取历史交易记录如何取？

### ISSUE THREAD

**Issue by wslys** [ethereum/web3.js#1810]
**以下是我的测试代码，我连历史Event都得不到（我本机数据目前只同步到2017-11月份）**
`// in node.js
var Web3 = require('web3');
var web3 = new Web3('http://localhost:8545');

var request = require('request');
request('http://api.etherscan.io/api?module=contract&action=getabi&address=0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0', function (error, response, body) {
    if (!error && response.statusCode == 200) {
		var myaddress = "0x902f2dd8cff4341510ed2fd239d83d34bfa90819";
		var contractAddress = "0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0";

		var bodyObj = JSON.parse(body);
		var contractABI = '';
		contractABI = JSON.parse(bodyObj.result);

		if (contractABI !=''){
			var myContractInstance = new web3.eth.Contract(contractABI, contractAddress);

			myContractInstance.getPastEvents('allEvents', {
			    fromBlock: 0,
			    toBlock: 'latest'
			}, function(error, events){ 
			    console.log(events); 
			})
			.then(function(events){
			    console.log(events) // same results as the optional callback above
			});

		} else {
			console.log("错误");
		}    

    }
});`

顺便问问可有公开的节点（等数据同步完我这边至少得花一周）

**Comment by nivida** [comment]
Could you please translate it into English? :)

**Comment by pokerface0206** [comment]
解决了么兄弟，  我每次获取到的都是空数组，难道是只能获取到页面打开后监听到的交易记录么 ？  不应该是获取到链上的所有记录么 ？

**Comment by axboy** [comment]
```js
contractInstance.getPastEvents('allEvents', { filter: {fromBlock: 0, toBlock: 'latest' } },
(error, events) => {
    console.log(events);    //return empty array, not all events
})
```
兄弟解决了没有，同样的问题，我这只能获取到最后一个块的事件
How to get all historical events, the code only gets last block events, not all events.

**Comment by lanyuxqh** [comment]
> ```js
> contractInstance.getPastEvents('allEvents', { filter: {fromBlock: 0, toBlock: 'latest' } },
> (error, events) => {
>     console.log(events);    //return empty array, not all events
> })
> ```
> 
> 兄弟解决了没有，同样的问题，我这只能获取到最后一个块的事件
> How to get all historical events, the code only gets last block events, not all events.
请问你后来怎么解决的，我也只能拿到最新的一条记录。

**Comment by axboy** [comment]
> ```js
> contractInstance.getPastEvents('allEvents', { filter: {fromBlock: 0, toBlock: 'latest' } },
> (error, events) => {
>     console.log(events);    //return empty array, not all events
> })
> ```
> 
> 
> 兄弟解决了没有，同样的问题，我这只能获取到最后一个块的事件
> How to get all historical events, the code only gets last block events, not all events.
> 请问你后来怎么解决的，我也只能拿到最新的一条记录。

当时曲线救国，java写的，给页面提供接口

**Comment by axboy** [comment]
> ```js
> contractInstance.getPastEvents('allEvents', { filter: {fromBlock: 0, toBlock: 'latest' } },
> (error, events) => {
>     console.log(events);    //return empty array, not all events
> })
> ```
> 
> 兄弟解决了没有，同样的问题，我这只能获取到最后一个块的事件
> How to get all historical events, the code only gets last block events, not all events.

## fix my error

我这个获取不到是因为代码错误，fromBlock不是在filter里面，换成如下代码可用。
I can’t get this because of a bad code, The param 'fromBlock' is not in the filter block, It can use the following code instead.

```js
contractInstance.getPastEvents('allEvents', { filter: {}, fromBlock: 0,toBlock: 'latest' },
      (error, events) => {
          console.log(events)
      }
);
```

## full code
```javaScript
let contractAddress = "0x7276558Caf21231AE5470A9DDf353f88F3e962F5"
let currentAddress = "0x8d1d0f053fa79ac075cbbb98af6092ae4d69213a"
let contractAbi = abiJSON      //replace it

//let web3 = new Web3(web3.currentProvider);
let web3Call = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/v3/xxx"))   //replace xxx
let callContract = new web3Call.eth.Contract(contractAbi, contractAddress, {
    from: currentAddress,
    gasPrice: '100'
})

callContract.getPastEvents('allEvents', { filter: {},fromBlock: 0,toBlock: 'latest' },
    (error, events) => {
        console.log(events)
    }
);

callContract.getPastEvents('Transfer', { filter: {},fromBlock: 0,toBlock: 'latest' },
    (error, events) => {
        console.log(events)
    }
);
```

## Suggest

建议使用infura调试，浏览器能看到http请求记录，参数直观，call请求不依赖MetaMask，send请求酌情考虑
