### ISSUE TITLE
Uncaught Error: invalid address

### ISSUE THREAD

**Issue by MuhammadAhmad-BlockchainDeveloper** [ethereum/web3.js#1812]
I am getting error of invalid address
and in the console debugging pannel i got error
anonymous function
here is screenshot of it
![cons](https://user-images.githubusercontent.com/31615879/43363323-a98cc872-931b-11e8-96a8-243525cc105b.PNG)
.....
....
....
error showing in browser after calling function:.......
![browser](https://user-images.githubusercontent.com/31615879/43363295-4503989a-931b-11e8-9c29-69f40dc0a4cf.PNG)
.....
.....
....
here is my javascript code with ABI screenshot
![js](https://user-images.githubusercontent.com/31615879/43363296-45380f76-931b-11e8-8528-9fb98c24d1a7.PNG)
![js2](https://user-images.githubusercontent.com/31615879/43363297-456b8752-931b-11e8-89b4-e4af86c0e26f.PNG)
....
....
.....
here is code of solidity on remix IDE
![sol](https://user-images.githubusercontent.com/31615879/43363298-459f391c-931b-11e8-8594-485a3682193a.PNG)

any help will be really appreciated

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com
