### ISSUE TITLE
Remix - Solidity IDE web3Provider issue

### ISSUE THREAD

**Issue by MuhammadAhmad-BlockchainDeveloper** [ethereum/web3.js#1815]
I am facing issue when i change the environment to WEB3Provider and deploy it to get account (to use in my JS file for GUI) then it shows me red cross in the console. Below is the screen shot of my contract.
Any help will be really appreciatable.
.
.
. 
![tempsnip](https://user-images.githubusercontent.com/39688960/43378312-82a8c17e-93df-11e8-98d5-96d7e6daad6e.png)

**Comment by nivida** [comment]
This is the repository for web3.js. Please post your question to https://ethereum.stackexchange.com/ or directly in the Remix repository if it's really a bug.
