### ISSUE TITLE
How to get all users name in SOLIDITY (smart contract)

### ISSUE THREAD

**Issue by MuhammadAhmad-BlockchainDeveloper** [ethereum/web3.js#1816]
Here is the code of my smart contract in solidity
I want to print all candidates list in getCandidatesList() function.
Right now i am getting only one candidate as a result

pragma solidity ^0.4.18;
contract Vote {
    string name;
    struct People
   {
        string name;
    }
    
    mapping (address => People) peoples;
    address[] public peoplesAccts;
    
    //when a new instructor added or updated 
    event peopleInfo(
        string name
    );
    
    function addCandidates(address _address,string _name) public{
        
        var people = peoples[_address];
        peoplesAccts.push(_address) -1;
        
        people.name = _name;
        peopleInfo(_name);
    }
    
    function getCandidatesList() view public returns (string){
        
        for(uint i=0; i<peoplesAccts.length ; i++)
        {
            
            var addr = peoplesAccts[i];
            var naame = (peoples[addr].name);
             
            return naame;
            
        }
    }
}

**Comment by Asone** [comment]
Please use [Ethereum stackexchange](https://ethereum.stackexchange.com/) if you have programming related questions for solidity. 

The issues opened here are for web3js development.
