### ISSUE TITLE
ethereumjs-wallet HD key path 

### ISSUE THREAD

**Issue by hussainsdei** [ethereum/web3.js#1817]
truffle-hdwallet-provider :- In Index.js file Hd key path is incorrect. Make it like
" require('ethereumjs-wallet/dist/hdkey');"

**Comment by Mischi** [comment]
There exists already an issue to this problem (https://github.com/ethereumjs/ethereumjs-wallet/issues/64) ....

**Comment by holgerd77** [comment]
This should now have been fixed with the [v0.6.2](https://github.com/ethereumjs/ethereumjs-wallet/releases/tag/v0.6.2) release (confirm would be nice), sorry for the inconvenience.

**Comment by frozeman** [comment]
will be in the next release.
