### ISSUE TITLE
Issue installing on windows

### ISSUE THREAD

**Issue by Legitimate** [ethereum/web3.js#1818]
I am getting issues with web3 during installation of etheratom via apm. I have apm configured to use python2.8 and have installed windows-build-tools via apm.
This is the end of a long error I get when attempting to install via apm.
`npm ERR! node v6.9.5
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! web3@1.0.0-beta.18 postinstall: lerna bootstrap
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.18 postinstall script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs web3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls web3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Nesquil\AppData\Local\Temp\apm-install-dir-118630-1636-wx1gxk.492vrevcxr\npm-debug.log
npm ERR! code 1`
I installed the windows-build-tools before this, as administrator, and had set apm config to python2.7 to get rid of python errors. I installed latest nodejs too.

**Comment by pierreneter** [comment]
Did you try installing the latest beta version of web3 (`1.0.0-beta.35`)?

**Comment by Legitimate** [comment]
I reinstalled web3 (`1.0.0-beta.35`), but I still get the `web3@1.0.0-beta.18 postinstall: `lerna bootstrap`
npm ERR! Exit status 1` after executing `apm install etheratom`.

**Comment by nivida** [comment]
This will help you https://github.com/ethereum/web3.js/issues/1783 for further questions please ask them on https://ethereum.stackexchange.com.
