### ISSUE TITLE
contract.allEvents() never calls the callback function if there are no events

### ISSUE THREAD

**Issue by uluhonolulu** [ethereum/web3.js#1822]
In this code:
```
    let events = token.allEvents({fromBlock: creationBlock, toBlock: 'latest'}, (err, res) => {
        try {
            let result = events.get();
            console.log(result);            
        } catch (error) {
            console.error(error);            
        }
    });
```
the callback is called for every event. This is because of this code in https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L101: 

```
                messages.forEach(function (message) {
                    callback(null, message);
                });
```

The problem is that if there are no events for my contract, the callback is never called, and I'm left with a hung web request.

I can't call `events.get` synchronously, since by that time `events.filterId` is not set (it is set at https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L165), and `get` throws an error at https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L233.

What I'm trying to do is get all events for my contract.

**Comment by nivida** [comment]
This is the correct behaviour of the callback method it should only be called when an event occurs. If you want to get past events than please use ```getPastEvents```  as described here: http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#getpastevents

Please ask further questions on https://ethereum.stackexchange.com/
