### ISSUE TITLE
Parity + Whisper (via web3) in browser not working

### ISSUE THREAD

**Issue by emizzle** [ethereum/web3.js#1823]
> I'm running:
>
> - **Which web3 version**: 1.0.0-beta.33
> - **Which Parity version?**: 1) v1.10.9-stable-23a9eef-20180707/rustc1.27.0 and 2) v2.0.1-20180726 beta
> - **Which operating system?**: x86_64-macos
> - **How installed?**: 1) `bash <(curl https://get.parity.io -L) -r stable` 2) via Parity UI installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: localhost, DevelopmentChain
> - **Did you try to restart the node?**: yes

I am not able to get a whisper subscription data when using Parity 1.10.9-stable nor 2.0.1-20180726. I am using web3 `1.0.0-beta.33`. 

The js used to reproduce is from a basic react app (for demo purposes) but the code is essentially straight from the [web3.shh docs](https://web3js.readthedocs.io/en/1.0/web3-shh.html#id74), with fields `topics` and `priority` added to the `shh.post` object, as Parity seems to require these fields.

**Steps to reproduce**
1. Update config on your machine to 
```
# This config should be placed in following path:
#   $HOME/Library/Application Support/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "dev"
# Forces Parity to run even if there are known issues regarding consensus. Not recommended.
no_consensus = true

[rpc]
# Allows Cross-Origin Requests from domain 'http://localhost:8000,embark'.
cors = ["http://localhost:8000", "http://localhost:3000", "embark"]

[websockets]
# Allows connecting from Origin 'parity://*,chrome-extension://*,moz-extension://*,embark,http://localhost:8000,'.
origins = ["parity://*", "chrome-extension://*", "moz-extension://*", "embark", "http://localhost:8000", "http://localhost:3000", ""]
# Allow connections only using specified addresses.
hosts = ["http://localhost:8000","http://localhost:3000"]

[whisper]
# Enable the Whisper network.
enabled = true

[network]
# Network ID of the chain will be overridden to: 1337
id = 1337
```
2. Create new react app (for repro ease - this issue does not have a dependency on react by any means)
```
npx create-react-app parity-whisper-not-working
cd parity-whisper-not-working
npm start
```
3. Modify App.js to the following:
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Web3 from 'web3';

class App extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      symKeyID: null,
      sig: null,
      web3: null,
      error: null,
      info: null,
      data: null
    };
  }

  componentDidMount() {
    const web3 = new Web3(new Web3.providers.WebsocketProvider("ws://localhost:8546"));
    this.setState({ web3: web3 });

    Promise.all([
      web3.shh.newSymKey().then((id) => { this.setState({ symKeyID: id }); }),
      web3.shh.newKeyPair().then((id) => { this.setState({ sig: id }); })

    ]).then(() => {

      // will receive also its own message send, below
      web3.shh.subscribe("messages", {
        symKeyID: this.state.symKeyID,
        topics: ['0xffaadd11']
      }).on('data', (message) => {
        this.setState({ data: JSON.stringify(message) }); // <==== THIS IS NEVER HIT WITH PARITY!
      });

    }).then(() => {
      web3.shh.post({
        symKeyID: this.state.symKeyID, // encrypts using the sym key ID
        sig: this.state.sig, // signs the message using the keyPair ID
        ttl: 10,
        topic: '0xffaadd11', // required for geth
        topics: ['0xffaadd11'], // required for Parity
        priority: 1,
        payload: '0xffffffdddddd1122',
        powTime: 3,
        powTarget: 0.5
      }).then(h => this.setState({ info: `Message with hash ${h} was successfuly sent` }))
        .catch(err => this.setState({ error: err.message}));
    });
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <h4>Info</h4>
        <pre>{this.state.info}</pre>
        <h4>Data received</h4>
        <pre>{this.state.data}</pre>
        <h4>Error</h4>
        <pre>{this.state.error}</pre>
        <h4>Web3 version</h4>
        <pre>{this.state.web3 ? this.state.web3.version : ''}</pre>
        <h4>Symmetric Key ID</h4>
        <pre>{this.state.symKeyID}</pre>
        <h4>Signature</h4>
        <pre>{this.state.sig}</pre>
      </div>
    );
  }
}

export default App;
```
4. Run Parity node from cli or Parity UI
5. Run the site in the browser `http://localhost:3000`
6. **Expected**: "Data received" should show whisper message data
**Actual**: There is no message received. Essentially the `on('data')` event appears to never be emitted.
7. This works with Geth. If you kill the Parity node and instead run a Geth node, then refresh the site, there will be a whisper message shown under "Data received" as expected. 

Is there something I'm missing?
  
Does anyone have a working example they could share with me?

For reference, I have asked the same question to the Parity folks: https://github.com/paritytech/parity-ethereum/issues/9263.

**Comment by rphmeier** [comment]
See https://github.com/ethereum/web3.js/issues/937

Whisper as a wire protocol and set of RPCs are both nowhere near stable. The Ethereum Foundation and Web3 Foundation are collaborating on making something with provable security properties, better routing, scalability, etc..

Unfortunately, RPCs for using some prototype of whisper have been included in a "stable" release of web3.js. That doesn't mean that the RPCs you are currently using are going to stick around as the protocol evolves.

**Comment by nivida** [comment]
I close this issue because of https://github.com/ethereum/web3.js/issues/937
