### ISSUE TITLE
Cannot install web3 node module

### ISSUE THREAD

**Issue by Paradox-AT** [ethereum/web3.js#1824]
As per the documentation, `npm install web3` would install the library but when I am trying to install the module it is throwing following error:
```
PS F:\Sportist> npm install web3
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! Error while executing:
npm ERR! C:\Users\aayush.thakur\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: read error: Invalid argument
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aayush.thakur\AppData\Roaming\npm-cache\_logs\2018-08-01T07_46_08_899Z-debug.log
```

**Comment by pierreneter** [comment]
Check your `git`, can you install any other packages?

**Comment by KaranKool** [comment]
same issue

`root@ip-172-31-0-237:/home/ubuntu/test/deploy# npm -v
6.2.0
root@ip-172-31-0-237:/home/ubuntu/test/deploy# npm i web3 --save
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /root/.npm/_cacache/tmp/git-clone-194c5553
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-194c5553': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-01T10_56_38_656Z-debug.log
root@ip-172-31-0-237:/home/ubuntu/test/deploy#
`

**Comment by Paradox-AT** [comment]
@pierreneter Yes, I am able to use git on my computer.
@KaranKool I think you got some permissions issue on your system, have a look at [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by Paradox-AT** [comment]
Change the git config from git://github.com/something.git to https://github.com/something.git using: `git config --global url."https://".insteadOf git://` and then change default version of build tools using: `npm config set msvs_version 2015 --global`

**Comment by pierreneter** [comment]
Finally, it's about your `git` :sweat_smile:
