### ISSUE TITLE
[v1.0] missing .modules at instance of Web3

### ISSUE THREAD

**Issue by pierreneter** [ethereum/web3.js#1830]
At this document: https://web3js.readthedocs.io/en/1.0/web3.html#modules
The `modules` object can get from any instance of Web3, but I can't get it.

```javascript
const web3 = new Web3(new Web3.providers.HttpProvider(mainnet));
console.log("web3.modules", Object.keys(web3.modules));

> console.log("web3.modules", Object.keys(web3.modules));
>                                    ^
> TypeError: Cannot convert undefined or null to object
```

If it was removed, maybe I can edit the document, else, I can add it back to the Instance.

So what next we have to do?

**Comment by pierreneter** [comment]
I think the example of code at here: https://web3js.readthedocs.io/en/1.0/web3.html#web3 (don't exist `> web3.modules`) is conflict with https://web3js.readthedocs.io/en/1.0/web3.html#modules

**Comment by nivida** [comment]
If you log ```Web3.modules``` instead of ```web3.modules``` you will find all the modules you are looking for. 
The documentation is confusing and wrong would you like to change this and propose an PR?

**Comment by pierreneter** [comment]
I will send a PR. <3
