### ISSUE TITLE
Explain in read the docs for 1.0.0 the difference between getPastEvents() and events.myEvent({ fromBlock: 0 }).

### ISSUE THREAD

**Issue by nicoszerman** [ethereum/web3.js#1837]
I'm posting this issue because I have this question myself and no one in stack exchange answered yet.

By the way, here are links to the question:

https://ethereum.stackexchange.com/questions/55621/what-is-the-difference-between-getpastevents-vs-events-myevent-fromblock-0

https://stackoverflow.com/questions/51663186/ethereum-web3-what-is-the-difference-between-getpastevents-vs-events-myevent

**Comment by nivida** [comment]
Please ask further questions like this only on stackoverflow or in our gitter channel. :)

**Comment by nicoszerman** [comment]
@nivida I believe my post is really an issue with the documentation. Why do you think that it's not?

**Comment by nivida** [comment]
Because it's clear to most of the developers but feel free to submit an PR for improving the documentation if you think its necessary to describe this. :)
