### ISSUE TITLE
Version 0.20.7 published

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#1838]
There is a version `0.20.7` published on NPM. I think this is a mistake. I cannot find the source code for it or a tag with that version.

**Comment by nivida** [comment]
@frozeman git tag is missing for 0.20.7 :)

**Comment by nivida** [comment]
@Levino Sorry I though Fabian will do this because he created the release. I will do it today sorry for the confusion.

**Comment by dkent600** [comment]
Still no tag

**Comment by akudo7** [comment]
Any luck so far?

**Comment by holgerd77** [comment]
Outdated, will close.
