### ISSUE TITLE
setProvider throws "Maximum call stack size exceeded" in v1.0.0-beta.35

### ISSUE THREAD

**Issue by kostysh** [ethereum/web3.js#1839]
If I trying to set a new provider, with:
`
web3.setProvider(web3.providers.WebsocketProvider(<ws_url>));
`

I began to receive the following error (in v1.0.0-beta.35):
`
RangeError: Maximum call stack size exceeded\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:156:36)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)\n    at Eth.Contract.self.setProvider (/node_modules/web3-eth/src/index.js:157:23)
`

**Comment by pierreneter** [comment]
Try again with: `web3.setProvider(new Web3.providers.WebsocketProvider(<ws_url>))`

**Comment by kostysh** [comment]
sorry, I have missed this in my message. I am doing definitely the same
`web3.setProvider(new Web3.providers.WebsocketProvider(<ws_url>))`

for now, I have downgraded my app to v1.0.0-beta.34 (mostly stable version)

**Comment by nivida** [comment]
@kostysh Could you please provide your code for reproducing this issue?

**Comment by kostysh** [comment]
I have tried but I can not reproduce this error in simple example. Possibly, it was a side effect of my library. In the next release, I will try to upgrade web3 version again and if an error occurs I will back to this issue. But for now, I propose to close this error.

**Comment by AsyncLegs** [comment]
I've encountered this issue again:
```
(node:84) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:157:36)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/app/node_modules/web3-eth/src/index.js:158:23)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 202658)
```


version: "web3": "1.2.1",

And code to reproduce:
```typescript
import Web3 from 'web3';
import { Provider, Logger, Scope } from '@nestjs/common';
import { EDGE_ETHEREUM_CONNECTION } from './web3.constants';
import { httpsOverHttp } from 'tunnel';
import { isEmpty } from 'lodash';
const logger = new Logger('Web3.JS Client');
export const createWeb3Instance = async () => {
  let reConnections = 0;
  const providerUrl = process.env.INFURA_ENDPOINT_URL;
  const interval = Number(
    process.env.ETHEREUM_NETWORK_CONNECTION_RETRY_INTERVAL || 10000,
  );
  const provider = getProvider(providerUrl);
  const web3 = new Web3(provider, null, {
    transactionConfirmationBlocks: Number(process.env.BLOCK_FINALITY_AMOUNT),
  });
  setInterval(() => {
    web3.eth.net
      .isListening()
      .then((isListening: boolean) => {
        if (isListening && reConnections > 0) {
          logger.log(
            `Successfully connected to ${providerUrl}. Healthcheck interval: ${interval}`,
          );
          reConnections = 0;
        }
      })
      .catch((e: Error) => {
        logger.error(
          `Lost connection to the ${providerUrl}, reconnecting(${reConnections})...Healthcheck interval: ${interval}`,
        );
        logger.error(e.message);
        reConnections++;
        web3.setProvider(getProvider(providerUrl));
      });
  }, interval);

  return web3;
};

const getProvider = (providerUrl: string) => {
  const isProxyEnabled = !isEmpty(process.env.PROXY_HOSTNAME);
  let provider;
  if (isProxyEnabled) {
    logger.warn(
      `Proxy configuration is enabled: Proxy server hostname is: ${process.env.PROXY_HOSTNAME} and proxy server port is: ${process.env.PROXY_PORT}`,
    );
    const tunnelingAgent = httpsOverHttp({
      proxy: {
        host: process.env.PROXY_HOSTNAME,
        port: Number(process.env.PROXY_PORT),
      },
    });
    provider = new Web3.providers.WebsocketProvider(providerUrl, {
      requestOptions: {
        agent: tunnelingAgent,
      },
    });
  } else {
    logger.warn(`Proxy configuration is disabled`);
    provider = new Web3.providers.WebsocketProvider(providerUrl);
  }
  return provider;
};```
