### ISSUE TITLE
Callbacks not working/erroring

### ISSUE THREAD

**Issue by joeykrug** [ethereum/web3.js#184]
Just pulled this from the wiki: https://github.com/ethereum/wiki/wiki/JavaScript-API
Occurs on latest geth which has latest web3.js pulled in

Test case:
```js
web3.eth.getBlock(48, function(error, result){
    if(!error)
        console.log(result)
    else
        console.error(error);
})


Error:
TypeError: 'sendAsync' is not a function
    at sendAsync (<anonymous>:-29864:-133)
    at getBlock (<anonymous>:-27642:-133)
    at <anonymous>:1:1

**Comment by debris** [comment]
This looks like a go-ethereum issue. If it will be impossible/hard to fix in geth, we will prepare a fallback in web3.js.

**Comment by zsfelfoldi** [comment]
https://github.com/ethereum/go-ethereum/pull/771 will implement this.

**Comment by frozeman** [comment]
Thats a problem of the geth console and should soon be fixed
