### ISSUE TITLE
geth console cannot access node_modules

### ISSUE THREAD

**Issue by ayham-madi** [ethereum/web3.js#1849]
webe version 0.20.1
geth version  1.8.12-stable-37685930

I am trying to run the loadScript command
```'Script.js'
- - 
- - var Web3 = require('web3');
- - var web3 = new Web3();
- - web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
- - var version = web3.version.api;
- - console.log(version); 
- - var account = web3.eth.accounts[0];
```
- 
but loadScript('Script.js') returns 
==> err: TypeError: 'XMLHttpRequest' is not a function

and I am not able to add any of the of the node.js modules 

eg 
require('solc')
==> err: Error: Cannot find module 'solc'
please advice 
thanks

**Comment by pierreneter** [comment]
You just can `loadScript` that `console` of `geth` support it.
Example, i have a file: `~/.test/test.js`

```
console.log(JSON.stringify(admin.peers, null, 4));
```

and loadScript: `loadScript('.test/test.js');`

**Comment by ayham-madi** [comment]
Aha .... Thanks, for explaining this to me

**Comment by levino** [comment]
@ayham-madi Problem solved? Then please be a nice citizen of the internet and close your issue!

**Comment by ShubhamChouksey123** [comment]
Hey I wanted to know how to add node modules in Geth JavaScript Console
