### ISSUE TITLE
Reconnect feature is missing when websocket connection is closed.

### ISSUE THREAD

**Issue by nujabes403** [ethereum/web3.js#1852]
**Expected behavior**
After websocket connection is closed, it should try reconnecting.

**Actual behavior**
After websocket connection is closed, it doesn't do anything except notifying "connection is closed".

**Steps to reproduce the behavior**
Try offline mode on chrome developer tool.

**Versions**
npm 5.6.0
node 8.11.3
web3js 1.0.0.beta-35
OS X high sierra

**Comment by nujabes403** [comment]
fix on #1851

**Comment by levino** [comment]
The PR does not solve this issue. Also I think this is a non-issue. See PR review. I vote for closing this issue as 'wontfix'.

**Comment by ArsenKulikov** [comment]
@Levino @nujabes403 
so, is there any solution of this problem?

**Comment by nivida** [comment]
I'm closing this PR because of the PR #1966
