### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#1854]
I move for forking web3 and have other people maintain it. It looks like @frozeman and the crew are not up to the task.

**Comment by frozeman** [comment]
we are working on it, some bigger additions are coming like the new ABI coder, which took time. I myself also work significantly less, as im switching to my own project. Sorry for the delay, we'll try our best. @nivida is helping out now and it should go a lot smoother now.

**Comment by levino** [comment]
@nivida @frozeman Thanks for answering. Hope is not lost! :) I recommend going through all open PRs and Issues first, generally aiming to close them (maybe close all of them and say "reopen if you want" to the creator of the issue) and giving an eta on a review of a PR or an issue that you are not able to solve immediatly.

**Comment by levino** [comment]
Another question: Looks to me you do not have enough resources. What is the issue? Not enough money or not enough talent? I might be able to help with the latter, if you have the money.

**Comment by frozeman** [comment]
Thats a good point, we are just finishing off some bigger additions. You are always welcome to help out if you want ;) Its an OPEN source project.

**Comment by levino** [comment]
> Its an OPEN source project.

Which a lot of people with shitloads of money depend on. I guess one can either contribute with work hours or with some ICO-Ether. I think it should be possible to pay more people to work on this without taking a dollar out of your pocket.

**Comment by leonprou** [comment]
Yeah, It's a long process to merge your PR if you're not a member. I have waited 10 days for [PR](https://github.com/ethereum/web3.js/pull/1813) took me less a hour to work on. Which is merged now 😊 .

But forking should be the least preferable solution (as we know from the blockchain). I think just more members are needed, not just for writing new feature but for answering to issues and doing code reviews. I think I would like to contribute 😊 .

**Comment by frozeman** [comment]
Thanks, answering issues is always helpful. @nivida will be more and more taking responsibility for web3.js, i will move to a more consulting role. But to more help the better :)
