### ISSUE TITLE
web3.eth.sign - Error: Invalid JSON RPC response:

### ISSUE THREAD

**Issue by gersonsistemas** [ethereum/web3.js#1860]
I'm using version 1.0.0-beta.35

web3.eth.sign("Hello world", "0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe").then(console.log);

(node:14708) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (E:\ap\node_modules\web3-core-helpers\src\errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (E:\ap\node_modules\web3-providers-http\src\index.js:75:32)
    at XMLHttpRequestEventTarget.dispatchEvent (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:14708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nivida** [comment]
Is your local node running? :)

**Comment by gersonsistemas** [comment]
I'm using  node version v8.11.3

**Comment by Eugnis** [comment]
Same error on `web3.eth.net.isListening()`, 1.0.0-beta.35
```javascript
let web3 = new Web3(new Web3.providers.HttpProvider('https://ropsten.infura.io'));
web3.eth.net.isListening()
                .then(() => console.log('connected'))
                .catch(e => console.log('error', e));
```
`Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse`
But provider is running with no problems, also tested through curl.

**Comment by dtmle** [comment]
@moralesgersonpa, You need a wallet to sign the message with. If done on a local node with accounts setup, web3 should be able to detect them. If done over a remote node like Infura:
https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#wallet-add

**Comment by fabdarice** [comment]
Having the exact same issue.
Using truffle develop as local node.
Accounts are correctly unlocked. This used to work

**Comment by Eugnis** [comment]
Same error on >=beta34 with all requests. On <=beta33 all ok.
Btw, for me this issue only in react-native with browserify. On pure node.js no such issues.

**Comment by JayJay1989** [comment]
any news on this thread?

**Comment by nivida** [comment]
Can't reproduce it. Would be great if someone could provide a demo project for reproducing this error.

**Comment by huy-springlabs** [comment]
> Same error on >=beta34 with all requests. On <=beta33 all ok.
> Btw, for me this issue only in react-native with browserify. On pure node.js no such issues.

Running into the same issues as well when running my tests and attempting to sign a message. Tried to downgrade from beta34 to beta33 and beta30 with no luck.

**Comment by huy-springlabs** [comment]
I am able to work around the Invalid JSON RPC response error for >= beta.36, but now the call just freezes and the callback never gets called

**Comment by nivida** [comment]
@huy-springlabs It should be fixed in the latest version. Feel free to open a new issue if this error still occurs.

**Comment by huy-springlabs** [comment]
cool thanks for the update @nivida

**Comment by dozcan** [comment]
hello still get invalid rpc response for ec2 instance geth node

**Comment by makoog120** [comment]
> I'm using version 1.0.0-beta.35
> 
> web3.eth.sign("Hello world", "0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe").then(console.log);
> 
> (node:14708) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: "" at Object.InvalidResponse (E:\ap\node_modules\web3-core-helpers\src\errors.js:42:16) at XMLHttpRequest.request.onreadystatechange (E:\ap\node_modules\web3-providers-http\src\index.js:75:32) at XMLHttpRequestEventTarget.dispatchEvent (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22) at XMLHttpRequest._setReadyState (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14) at XMLHttpRequest._onHttpResponseEnd (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14) at IncomingMessage. (E:\ap\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9) (node:14708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:14708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Good

**Comment by makoog120** [comment]
Good
