### ISSUE TITLE
How to add available accounts at infura HttpProvider .

### ISSUE THREAD

**Issue by argubaby** [ethereum/web3.js#1862]
I launch web3 at nodejs server,not in explorer(no MetaMask).

const END_POINT = 'http://localhost:8545';
web3 = new Web3(new Web3.providers.HttpProvider(END_POINT));
web3.eth.getAccounts()
.then((accounts)=>{console.log})

I can get accounts from localhost:8085.

const END_POINT = 'https://ropsten.infura.io/v3/XXXXXXXXXXXXXXXXXX';
web3 = new Web3(new Web3.providers.HttpProvider(END_POINT));
web3.eth.getAccounts()
.then((accounts)=>{console.log})

But I can't get accounts from infura,return array is 0 length.
If no accounts that I will get error like "Specified signerAddress 0x4897b54979b9bf339f13dd461628476430cf0ea5 isn't available through the supplied web3 provider".

How to add available accounts?

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
