### ISSUE TITLE
Code does not follow .editorconfig definitions.

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#1863]
Currently the code does not follow the `.editorconfig` definitions. For example: https://github.com/ethereum/web3.js/blob/9bf580321868430554b00c75a650bbdc856f9804/package.json has an indentation of 2 instead of 4. `jshint` looks like a bad tool to me. What about using `eslint` instead?

**Comment by frozeman** [comment]
That should actually be `lerna` and `npm --save` that auto updates package.json and reformats them to 2 spaces.

**Comment by levino** [comment]
You are right, these tools format the `package.json` files. But they do not lint them. We should have a linter in place to make sure the format stays correct. Then one can add `npm --save` or so to the `format` script.

**Comment by nivida** [comment]
This got fixed with adding of eslint.
