### ISSUE TITLE
RangeError: private key length is invalid : while signing transaction locally

### ISSUE THREAD

**Issue by VishalDalve** [ethereum/web3.js#1869]
const web3 = new Web3('https://ropsten.infura.io/v3/3c52917848e945229c0d33d632b10490');

const account1 = '0x0982081d5a2bba0a9da9fe722c92edc0cb0e9b6a'
const account2 = '0xabc46ddc17a0c37ef70e8a153d4724f199705e8b'

const ac1_pvtkey =Buffer.from('XXXX9F79B587B1DE553E2ADCA3DC8D49BE3E2840083D970C41D83F7FD471XXXX', 'hex');

const ac2_pvtkey =Buffer.from('XXXXC15FBDB4634400B7F8FA17C9491B2E346AEC1BC86A493B18F5759042XXXX', 'hex');

`web3.eth.getTransactionCount(account2, (err, txCount) => {

//build transaction here ---------------------------
const txObject = {
    nonce: web3.utils.toHex(txCount), 
    to: account2,
    value: web3.utils.toHex(web3.utils.toWei('0.2','ether')),
    gaslimit: web3.utils.toHex(2100),
    gasPrice: web3.utils.toHex(web3.utils.toWei('10', 'gwei'))   
    }

    console.log(txObject)
 
//signing transaction here ---------------------------
const tx = new Tx(txObject);
tx.sign(ac2_pvtkey); //using account2 private key

------------------------------------------ERROR GIVING -------------------------------------------------- :

var sig = secp256k1.sign(msgHash, privateKey);
                      ^
RangeError: private key length is invalid `

**Comment by 0xicingdeath** [comment]
Hey @VishalDalve, did you happen to find a solution to this yet? I am running into the exact same thing.

**Comment by VishalDalve** [comment]
Hi, I got solution, I'll share it soon.

**Comment by nanom1t** [comment]
@VishalDalve What is the solution? Faced with same issue.

**Comment by gabrielvenegas** [comment]
Facing same issue, anyone with the solution?

**Comment by 0xicingdeath** [comment]
@nanom1t @gabrielvenegas I found a solution to this problem, albeit not using `web3`. This error was causing our tests to invariably fail inconsistently. After talking to a few other devs in the community, I ended switching our framework to use [ethers.js](https://docs.ethers.io/ethers.js/html/) instead. If you're still running into issues with this, and it's not too difficult to switch to another tool, I'd recommend using `ethers.js`. In addition to the amazing documentation, it's consistently works.

**Comment by ruzpuz** [comment]
@VishalDalve any solution?

**Comment by selvatica** [comment]
The solution: use the private key without the "0x" prefix in the environment..
then it works..

**Comment by selvatica** [comment]
> @VishalDalve any solution?

The solution: use the private key without the "0x" prefix in the environment.. then it works..

**Comment by selvatica** [comment]
> Facing same issue, anyone with the solution?

The solution: use the private key without the "0x" prefix in the environment..
then it works..

**Comment by nivida** [comment]
The creator of this issue found a solution please ask him for further details. It looks like it isn't an issue on the side of Web3.js. Please open a new issue if this error still occurs on the latest version of Web3. (beta.50)

**Comment by Ravi16209990** [comment]
I have changed my private keys afterwards and now it is working. So I think your private keys are not accurate or not supported

**Comment by x5engine** [comment]
Guys guys you know what?

The solution: use the private key without the "0x" prefix in the environment..
then it works..
