### ISSUE TITLE
Still no basic auth implimentation in web3.js 1.0.0

### ISSUE THREAD

**Issue by Caoxuyang** [ethereum/web3.js#1870]
As the title says.

**Comment by nivida** [comment]
Please have a look at this two lines:
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-http/src/index.js#L43 
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-http/src/index.js#L60

You can set the authorization headers over the provider options.
