### ISSUE TITLE
1.0: fromWei and toWei documentation is wrong

### ISSUE THREAD

**Issue by 26000** [ethereum/web3.js#1874]
1. `web3.utils.toWei` [doesn't take numbers](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/index.js#L234) as arguments, while the documentation [says](https://github.com/ethereum/web3.js/blob/1.0/docs/web3-utils.rst#parameters-22) it does:
```js
console.log(web3.utils.toWei(1000000000, "shannon"));
```
[throws](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/index.js#L235) with `Please pass numbers as strings or BigNumber objects to avoid precision errors.`

Which is also wrong, it doesn't take `BigNumber` objects either as web3.js 1.0 moved to `BN.js`.

2. `web3.utils.fromWei` never returns a BN.js instance, as opposed to what [documentation says](https://github.com/ethereum/web3.js/blob/1.0/docs/web3-utils.rst#returns-23):
```js
console.log(typeof web3.utils.fromWei(new web3.utils.BN(1000000000), "shannon"));
```
returns `string` (which equals to "1").

The code [here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/index.js#L238) calls ethjs-unit, in documentation of which [it's said](https://github.com/ethjs/ethjs-unit#about) that
>Note, the toWei returns a BN instance while fromWei always returns a string number.

And so the `toString(10)` method does nothing, it's already a string.

**Comment by haydencarlson** [comment]
I was confused with this myself before I figured out it was a big number instance.

**Comment by nventuro** [comment]
Is this planned to be included in a future release? The fix (either on the code or on the docs) is trivial, but this issue has been open for over a year (!).
