### ISSUE TITLE
Unable to install web3-utils through npm - Failed at the sha3@1.2.2 install script.

### ISSUE THREAD

**Issue by conwise18** [ethereum/web3.js#1882]
Connors-MacBook-Pro:~ connor$ npm install web3-utils

> sha3@1.2.2 install /Users/connor/node_modules/sha3
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/connor/node_modules/sha3
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN token@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/connor/.npm/_logs/2018-08-16T03_33_05_203Z-debug.log

Any help as to why I am un-able to install web3-utils would be great. 

Thanks in advance !

**Comment by nivida** [comment]
As you can see in the error message ```gyp ERR! configure error``` is it an configuration problem of your development environment. Please ask this question on stackoverflow.
