### ISSUE TITLE
Why not an opensource C++ implementation? 

### ISSUE THREAD

**Issue by yarnauy** [ethereum/web3.js#1883]
I have been working on a C++  implementation of Ethereum JSON-RPC API,  since I cannot find any existing opensource project.

Actually it is just the beginning ( about 1000 line C++ ). I have encapsulated some http-rpc code and implemented a few interfaces(**web3_sha3,** **eth_call**, **eth_send**). 

Is there any  chance to develop it into a opensource project?  And dees anybody want to come with me?

**Comment by nivida** [comment]
Hay @njuyuanrui I think you should ask your question somewhere else this is the repository of web3.js. Maybe is reddit or an other platform the better way to connect with other developers who share the same idea.

**Comment by ytrezq** [comment]
@njuyuanrui I would like to assist, I m currently resarching about having the lowest latency for transaction arbitrage and I m currently struggling with some problem like getting the right buffer size for reading ipc and how to detect what the reply I m receiving corresponds to when having several pubsub subscriptions?
