### ISSUE TITLE
why  web3.eth.subscribe('newBlockHeaders') on wss://mainnet.infura.io/ws can not receive the message

### ISSUE THREAD

**Issue by lebron112** [ethereum/web3.js#1884]
const Web3 = require('web3');
const web3 = new Web3();
web3.setProvider(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws'));
//main-line
// web3.setProvider(new Web3.providers.WebsocketProvider('wss://rinkeby.infura.io/ws'));
//test-line
// web3.setProvider(new Web3.providers.WebsocketProvider('wss://ropsten.infura.io/ws'));
//test-line
const subNewBlockHeaders = () =>{
  const  newBlockHeaders = web3.eth.subscribe('newBlockHeaders', function(error, result){
    if(error){ logger.error(`newBlockHeaders error:${error}`); }
  });
  newBlockHeaders.on('data', function(blockHeader){
    logger.info('data blockHeader',blockHeader);
  }).on('error', function(isSyncing){
    logger.error(`error blockHeader:${isSyncing}`);
  });
};
subNewBlockHeaders();

why on the 'main-line' can not  receive the message;
but on the 'test-line' can receive the message;

**Comment by justuswilhelm** [comment]
@lebron112 I remember that the websocket URLs for infura look a little different depending on the network. You might have more luck by spelling it `/_ws`, at least if you can believe this comment on StackExchange: https://ethereum.stackexchange.com/questions/49454/is-there-any-websocket-ethereum-provider#comment58597_49456

**Comment by dev1644** [comment]
I tried your code and it's working fine. In April 2018, Infura Ws was experimental that's why you must be encountering errors.  As of today, your snippet is fully functional.
