### ISSUE TITLE
Fixed Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by yyy999** [ethereum/web3.js#1885]
This is old geth version' bug.
Sovled method:  Download Geth – Swarming (v1.8.13) – Release Notes and install it.

微信yyy99966

**Comment by nivida** [comment]
Could you please provide more informations to your issue. @yyy999

**Comment by yisiliu** [comment]
@nivida I think this is pretty much a spam since he is obviously broadcasting his wechat account.
