### ISSUE TITLE
Webpack bundle is EXTREMELY HUGE

### ISSUE THREAD

**Issue by sweetpalma** [ethereum/web3.js#1889]
I am using Beta 35 and Webpack 4 and it produces EXTREMELY huge bundle size. 

As I stated in issue #1178, final size of my bundle grown from 240kb to more than 1mb after importing web3 and making basic setup like configuring provider, what is basically unacceptable. As @pubkey has stated in his comment, major part of that size growth is caused by multiple inclusions of the same bn.js package what is not tracked by Webpack for some mysterious reason.

Any ideas how to fix this?

![](https://user-images.githubusercontent.com/8926560/42589986-e15299d0-8542-11e8-8805-d89dbae6e9b5.png)

**Comment by nivida** [comment]
I'll close this issue because we already have an issue to this topic. I'll have an closer look on this next week.

**Comment by rene78** [comment]
Don't really understand the referenced issue, but my bundle size is huge as well.
Any ideas on how to fix it?
Edit: This seems to be the same issue discussed in more detail: https://github.com/ethereum/web3.js/issues/1178
