### ISSUE TITLE
 web3.eth.sendSignedTransaction is not a function

### ISSUE THREAD

**Issue by imhari213** [ethereum/web3.js#1892]
web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'))
         ^

TypeError: web3.eth.sendSignedTransaction is not a function

getting this error can anyine please help me on this...,

**Comment by fenixm8** [comment]
I have the same issue, with: web3.eth.getbalance, or x other function, Thanks for help

**Comment by boxsnake** [comment]
I think you haven't create instance of web3.

For new version, this will not work any more:
```javascript
const web3 = require('web3');
```

You have to create instance of web3:
```javascript
const Web3 = require('web3');
const web3 = new Web3(<provider>);
```

**Comment by imhari213** [comment]
thanks.. working close the issue... :)

**Comment by Eggsyz** [comment]
Hello, how do you solve this problem?

**Comment by imhari213** [comment]
choose the compatible version of web3 it will work.In my case web3 version is **"web3": "^0.19.1"**

**Comment by boxsnake** [comment]
* Option 1: Lock the dependency version below `1.0`
* Option 2: Create new instace from web3 as metioned above for new versions (maybe for `>= 1.0`)

**Comment by yuanziwoxin** [comment]
@imhari213 It's so pity! It didn't matter for me! Anyone have some other suggestions!

**Comment by yuanziwoxin** [comment]
Oh, I know that! In web3  0.x.x，the function is `sendRawTransaction()`，but in web3 1.x.x，it change to `sendSignedTransaction()`.
