### ISSUE TITLE
npm install  :: ethereum/web3.js ERROR

### ISSUE THREAD

**Issue by nil3sh99** [ethereum/web3.js#1894]
I am trying to install web3.js using ethereum, but its showing git remote error.
Is the URL has been migrated. 
Help needed !!

~sudo npm install ethereum/web3.js --save
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit  ethereum/web3.js resetting remote /home/nilesh/.npm/_git-remotes/git-github-com-ethereum-web3-js-git-6339a8c5 because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }

**Comment by leonprou** [comment]
Just do
`npm install web3`

**Comment by ateebahmed** [comment]
> Just do
npm install web3

@leonprou tried it but was unsuccessful.

**Comment by Huanzhang89** [comment]
Hi @nil3sh99 , like @leonprou suggested `npm install web3` should work (Please refer to the readme at https://github.com/ethereum/web3.js)

@ateebahmed Could you elaborate on the issue? What operating system are you running on, also what versions of `node` and `npm`?

Some error logs would also be helpful to pin-point the exact issue you are experiencing.

**Comment by nil3sh99** [comment]
Hi @Huanzhang89 thanks for the reply...Will try to do it again, but my schedule is lil tight right now (my high school exams are going on :P).
So will be closing the issue after testing in a couple of days.

**Comment by sbansal96** [comment]
Hi @nil3sh99 , have you tried `npm install web3` yet .?
You should try to run `npm install web3` with administrator privileges if you are on a windows system , 
and if on linux just add 'sudo' in front of it `sudo npm install web3`.

Sometime running these from admin privilege solve the problem

**Comment by chankruze** [comment]
It seems like communication with git was not successful. Is there any issue with config.
By the way installation via npm should work.
Try `npm install web3`

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
