### ISSUE TITLE
Unable to Install Web3 on Ubuntu 16 LTS [Scrypt node-gyp issue]

### ISSUE THREAD

**Issue by pranavburnwal** [ethereum/web3.js#1896]
Unable to install web3 by npm. Sub-module scrypt throws error! The installation succeeds but later when we start the node app it says module scrypt not found.

SHA3 error ins solved with `--unsafe-perm` but scrypt doesn't.

**Things tried:**
Node version(stable): 6, 7, 8 & 9
NPM latest
Python is installed & mapped
`gcc -v` -> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
`sudo npm install -g scrypt` -> doesnt work as well.
Install with -g and manually link
noge-gyp -g is already installed.
Ran with and without `sudo`
`npm install -g web3 --unsafe-perm=true --allow-root` and manual link as well. GIves same error.

**Tickets tried:**
Refernced all tickets on this
#1781 
#1776 
#1700 

**Debug Log:**

```
npm i web3

> scrypt@6.0.3 preinstall /home/ubuntu/test/node_modules/scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /home/ubuntu/test/node_modules/scrypt
> node-gyp rebuild

make ✖ ERR  Missing Makefile / Bakefile
make ℹ info Run "make init" to generate a Makefile.

> sha3@1.2.2 install /home/ubuntu/test/node_modules/sha3
> node-gyp rebuild

make ✖ ERR  Missing Makefile / Bakefile
make ℹ info Run "make init" to generate a Makefile.

> websocket@1.0.26 install /home/ubuntu/test/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


  $ make <target...> [options]

  Options:
    --help             Show this help output
    --version          Show package version
    --debug            Enable extended log output

  Targets:
    all                Run target all
    clean              Run target clean
    autobahn           Run target autobahn
    autobahn-server    Run target autobahn-server

  Templates:
    ava                Generate ava setup (ava)
    cli                Generate cli setup (minimist, tabtab, ge...)
    default            Generate default setup (babel-cli, babel-plu...)
    eslint             Generate eslint setup (eslint, eslint-confi...)
    livereactload      Generate livereactload setup (babel-plugin-react-t...)
    mocha              Generate mocha setup (mocha)
    simple             Generate simple setup


npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/test/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ web3@1.0.0-beta.35
added 302 packages in 11.973s
```

**Comment by ctrlaltvikas** [comment]
Try this `sudo apt-get install build-essential`

**Comment by pranavburnwal** [comment]
@vikaskyadav  Did that the first thing. Didn't help. I switched my OS on the cloud for now to handle this. WIll retry anyway, I will leave this open in case anyone finds a fixed solution. 

Thanks for your help.
Pranav

**Comment by chankruze** [comment]
what is the version of python installed ?
It needs to be 2.7 not 3.x cause node-gyp does not work with python v3.x.

**Comment by pranavburnwal** [comment]
It was 2.7, It was the first thing I checked that time as I did that mistake before.

I changed the OS type for this to solve this now using RHEL.
