### ISSUE TITLE
Handle `getPastEvent` to choose overloaded events

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#1899]
Imagine we have 2 events:

```
Transfer(address,address,uint256)
Transfer(address,address,uint256,bytes)
```
i should be able to make a call like
```
await tokenContract.getPastEvents('Transfer(address,address,uint256)', {})
```

I can only do it with subscriptions:

`tokenContract.events['Transfer(address,address,uint256)']`

**Comment by nivida** [comment]
This got implemented during the refactoring: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/AbstractContract.js#L174
