### ISSUE TITLE
'nonce too low' when run sendRawTransaction second time.

### ISSUE THREAD

**Issue by nbxtruong** [ethereum/web3.js#1901]
I have a function like this:

> sendRaw = (rawTx, callback) => {
    const privateKey = new Buffer(process.env.WALLET_PREVATE_KEY, 'hex');
    const transaction = new tx(rawTx);
    transaction.sign(privateKey);
    const serializedTx = transaction.serialize().toString('hex');
    this.web3.eth.sendRawTransaction(
      '0x' + serializedTx, function (err, result) {
        if (err) {
          callback(err, null);
        } else {
          callback(null, result);
        }
      });
  }

I ran it for the first time, everything work fine. When I ran it in the second time, my application had 'nonce too low'.

I found out on the internet and found [this article](https://ethereum.stackexchange.com/questions/56350/deploy-to-mainnet-with-truffle-infura-nonce-too-low). The nonce counter do not increase the  for a long time. Is that correct in my case?

I am using Web3JS 0.19.1. I have a lot of difficulties trying to solve this problem. help me please.

**Comment by daffl** [comment]
When sending new transactions, the `nonce` should be set to the from addresses transaction count (`getTransactionCount(fromAddress)`).

I found [this blog post helpful explaining this](https://medium.com/kinblog/making-sense-of-ethereum-nonce-sense-3858d5588c64).

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
