### ISSUE TITLE
Incorrect return message for require() in public/external pure/view-type functions

### ISSUE THREAD

**Issue by wuya666** [ethereum/web3.js#1903]
when directly calling a public/external pure/view-type function with a failing require(), the return message is incorrect as shown here

ethereum/solidity#4840

for an example contract deployed on the mainnet
https://etherscan.io/address/0xd0b4e64c323186340ed2d8168ddae8f18677560e#code

```
pragma solidity ^0.4.24;

contract test {
    
    function sub1(uint256 _a, uint256 _b) public pure returns (uint256 result) {
        require(_a >= _b);
        return _a - _b;
    }
    
    function sub2(uint256 _a, uint256 _b) public pure returns (uint256 result) {
        require(_a >= _b, "_a cannot be less than _b");
        return _a - _b;
    }
    
}
```

And calling sub1(3, 5) and sub2(3, 5) with web3.js 

```
Web3 = require("web3")
web3 = new Web3("...")  // ... is some mainnet provider url, for example Infura.io
abi = ... // ... is the abi json object
contract = new web3.eth.Contract(abi);
ontract.options.address = "0xd0B4e64c323186340ed2D8168DdaE8f18677560E"
contract.methods.sub1(3, 5).call().then(console.log)
contract.methods.sub2(3, 5).call().then(console.log)
```

And for sub1(3, 5) it throws an "Error: Couldn't decode uint256 from ABI: 0x" which I think is quite vague and not informative at all.

Then for sub2(3, 5) it will not throw any error but return an absurd value of 

> 3963877391197344453575983046348115674221700746820753546331534351508065746944

While the error message returned by sub1(3, 5) could use some improvement, the return message by sub2(3, 5) is definitely wrong and should be fixed, as it is basically telling the Dapp front-end that 3 minus 5 equals to 3963877391197344453575983046348115674221700746820753546331534351508065746944 and that could even become a security vulnerability.

**Comment by vbilici** [comment]
I have the same issue, I will remove all the messages until this issue resolves

**Comment by BennyTheDev** [comment]
Any progress on this? This is a clear bug that leads to security issues (besides confusion for dapp devs)

**Comment by cma00000** [comment]
same here!

**Comment by cma00000** [comment]
```
        uint currBlock = block.number;
        require(currBlock > futureBlockNumber,"Future time to execute required.");
        return currBlock;    
```
Just tried in remix + ropsten
which the "require" never fire the revert, but just return a 3963877391197344453575983... non-sense value.

**Comment by ghost** [comment]
This bug is also affecting my application!

**Comment by nivida** [comment]
Will test it asap. Sorry for the long waiting time.

**Comment by ross-rosario** [comment]
I can reproduce that disturbing issue with the same conditions mentioned above; calling a `view` function that should revert, rather returns `3963877391197344453575983046348115674221700746820753546331534351508065746944`. 
Thanks for looking into this @nivida !

**Comment by nivida** [comment]
The revert handling ([EIP-140](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md)) is not yet implemented in the Web3.js library. I will change this issue from a ``bug`` to a ``feature request`` and will implement it asap.

**Comment by nivida** [comment]
We have implemented this feature for 1.x and will release it on the next minor release. We will implement this feature also for 2.x and I'm closing this issue for now because we will anyways synchronize the existing features between 1.x and 2.x later.
