### ISSUE TITLE
Move from node-gyp to cmake.js

### ISSUE THREAD

**Issue by munrocket** [ethereum/web3.js#1908]
Node-gyp is not support python 3 at least 10 years. And why we use it in 2018?
Maybe [cmake-js](https://github.com/cmake-js/cmake-js) is better?
All packages that depend on web3 have problems with installation now under windows.

**Comment by gokuflashdev** [comment]
I try to install web3 for a few days, a lot of info how to do it right is out of date. You can get an impression that few dependencies are not supported any more. The problem in future will be bigger and bigger. Who knows maybe we, poor windows users have to install windows 95 to use web3;p

**Comment by munrocket** [comment]
@gokuflashdev just write in web3, it's unrelated to ccxt.
Web3 is new package but somehow they desided to use node-gyp.
Like ccxt with browserify :-P
