### ISSUE TITLE
Unable to install web3 higher  web3@^1.0.0-beta.22

### ISSUE THREAD

**Issue by StepanyanAlbert** [ethereum/web3.js#1910]
**RUN PROGRAM AS ADMINISTRATOR**
Env 
Centos 7 
`npm -v `
`6.1.0`
`node -v
v8.11.1
`

`npm i web3` or `npm i web3@^1.0.0-beta.33` throws 

> npm install  web3@^1.0.0-beta.33
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

> scrypt@6.0.3 preinstall /var/www/vhosts/cryp/crypto_plugin/node_modules/scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install /var/www/vhosts/money.io/crypto_plugin/node_modules/scrypt
> node-gyp rebuild

> 
> make: Entering directory `/var/www/vhosts//wallet.money.io/crypto_plugin/node_modules/scrypt/build'
>   SOLINK_MODULE(target) Release/obj.target/copied_files.node
> make: execvp: g++: Permission denied
> make: *** [Release/obj.target/copied_files.node] Error 127
> make: Leaving directory `/var/www/vhosts//wallet.money.io/crypto_plugin/node_modules/scrypt/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/opt/plesk/node/8/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 3.10.0-514.6.1.el7.x86_64
> gyp ERR! command "/opt/plesk/node/8/bin/node" "/opt/plesk/node/8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /var/www/vhosts/wallet.cryptoio/crypto_plugin/node_modules/scrypt
> gyp ERR! node -v v8.11.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm WARN kiwi_crypto_wallet@1.0.0 No description
> npm WARN kiwi_crypto_wallet@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the scrypt@6.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /var/www/vhosts/.npm/_logs/2018-08-30T09_39_56_474Z-debug.log

**Comment by ateebahmed** [comment]
Can you tell us the workaround for this problem. I am having the same issue.

**Comment by StepanyanAlbert** [comment]
@ateebahmed   for me it was a problem with permissions . 
So  I tried command with root user . After just do this 
`chown your_user:your_group  path_to_node_modules -R`
Should do the job.
