### ISSUE TITLE
how to call a method in smart contract deployed in test-network  and that method takes parameter as string 

### ISSUE THREAD

**Issue by imhari213** [ethereum/web3.js#1911]
how to  call a method in smart contract deployed in test-network  and that method takes parameter as string 

example

pragma solidity ^0.4.16;

contract Lot {
    
    string name;
    
    function set(string n)public{
        name = n;
    }
    
    function get()public constant returns(string){
        return name;
    }
    
}

i want to call **set** method in the above smart contract and above contract is deployed in rinkeby test network ?

**Comment by nivida** [comment]
Hay @imhari213 please ask your question on https://ethereum.stackexchange.com/
