### ISSUE TITLE
how to grant access from 1 account to others?

### ISSUE THREAD

**Issue by leimin78** [ethereum/web3.js#1913]
There is a scene

I has a geth node , in this node has lots accounts, and a special i call its **admin account**.

i wanted let lots accounts transfer accounts , all gas price used from **admin accounts**?

**Comment by leimin78** [comment]
ERC20 support method approve can do this scene.

Can anyone anwser ETH support approve method?  Thank you so much.

**Comment by kay07** [comment]
have no,you could transfer to others only by admin accounts ,or admin transfer to some accounts,and the accounts transfer to others.

**Comment by nivida** [comment]
Hay @leimin78 please ask your question on https://ethereum.stackexchange.com/

**Comment by leimin78** [comment]
Thanks all already know it .
