### ISSUE TITLE
how to get keystore file path 

### ISSUE THREAD

**Issue by anyluck** [ethereum/web3.js#1918]
Web3js gets the keystore file path according to the address and password

**Comment by nemani** [comment]
Hey @anyluck, do you still need help with this? Can you tell me more about exactly what your query is so that I can help :smile:

**Comment by Flash-Git** [comment]
Is [this](https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts) what you're looking for? Geth lets you manage your keystore files.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
