### ISSUE TITLE
Make defaultBlock and callback possible in contract methods

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#192]
We need to make the optional `defaultBlock` and `callback` parameter possible for:

- `new MyContract({from: ...} [, callback])`
- `myContract.myMethod(param1, param2 [, {from: ...}] [, defaultBlock] [, callback])`
- `myContract.myMethod.call(param1, param2 [, {from: ...}] [, defaultBlock] [, callback])`
- `myContract.myMethod.sendTransaction(param1, param2 [, {from: ...}] [, callback])`

**Comment by debris** [comment]
there is already separate issue for defaultBlock #159 I'm closing this, cause callback has been implemented in 0.4.0
