### ISSUE TITLE
Ethers encoder errors when processing Web3 BN values (beta.36)

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#1920]
With a solidity method like:
```solidity
function set(uint val) public {
  ..etc..
}
```
In `beta.36`this:
```javascript
const val = web3.utils.toBN(1);
const data = myContract.methods.set(val).encodeABI();
```
throws this:
```shell
 Error: invalid number value (arg="val", coderType="uint256", value="1")
      at Object.throwError (/Users/cgewecke/code/consensys/e2e-beta36/wild-truffle/truffle/packages/truffle/build/webpack:/~/ethers/utils/errors.js:68:1)
      at CoderNumber.encode (/Users/cgewecke/code/consensys/e2e-beta36/wild-truffle/truffle/packages/truffle/build/webpack:/~/ethers/utils/abi-coder.js:353:1)
      at /Users/cgewecke/code/consensys/e2e-beta36/wild-truffle/truffle/packages/truffle/build/webpack:/~/ethers/utils/abi-coder.js:605:21
```

However this works:
```javascript
const ethers = require('ethers');

const val = ethers.utils.bigNumberify(1);
const data = myContract.methods.set(val).encodeABI();
```

**Comment by spacelan** [comment]
Same issue when decode the returned values

**Comment by gkaemmer** [comment]
This seems like a really big change to the web3 internals..is it better to use utils from ethers going forward?

**Comment by eyezick** [comment]
Also getting this issue now when passing a `BigNumber.js` object directly. Breaking change.

```
 Error: invalid number value (arg="_tokenCap", coderType="uint256", value="300")
      at Object.throwError (node_modules/ethers/utils/errors.js:68:17)
      at CoderNumber.encode (node_modules/ethers/utils/abi-coder.js:353:20)
      at node_modules/ethers/utils/abi-coder.js:605:59
```

**Comment by justinkchen** [comment]
Maybe it is fixed in ethers.js 4.0.5? web3 beta.36 is still on ethers.js 4.0.1-beta.1

**Comment by shumailxyz** [comment]
Stuck at same issue. Was working fine on beta.34.
@eyezick can confirm too that passing a `BigNumber` object directly also breaks.

Is it related to https://github.com/ethereum/web3.js/issues/1936#issuecomment-421032814 ? 
Somehow passing hex works for me too.

Tagging @nivida & @frozeman for input over this.

**Comment by alexpee** [comment]
Having the same issue, it works fine for Ganache but not working for Ropsten with Infura

**Comment by piesrtasty** [comment]
Any update to this?

**Comment by nivida** [comment]
Updated ethers to the latest version in PR #2000 and this should fix it. Otherwise please open an issue in the ethers.js repository.
