### ISSUE TITLE
web3 installed but not accessible

### ISSUE THREAD

**Issue by SarathSahadevan** [ethereum/web3.js#1921]
web3 is already installed but in different path i think because of that i cant access it. how can i resolve the issue?

<img width="242" alt="web3" src="https://user-images.githubusercontent.com/30496887/45075404-a6218400-b104-11e8-8e70-00f4cc82c6a7.PNG">
<img width="583" alt="web3e" src="https://user-images.githubusercontent.com/30496887/45075406-a752b100-b104-11e8-9d55-e93c6c82735b.PNG">

**Comment by glemmaPaul** [comment]
@sarath777 possibly better to handle this issue in https://github.com/ethereum/web3.py
