### ISSUE TITLE
How to confirm the transaction has reached the receiver address?

### ISSUE THREAD

**Issue by qingyang-id** [ethereum/web3.js#1925]
I use the senTransaction make a contract transfer, but I want confirm the contract has reached the receiver address by the web3, what should I do?
Thanks for first!

**Comment by qingyang-id** [comment]
and how to confirm the transaction has reached or failed?

**Comment by Flash-Git** [comment]
It sounds like you're looking to confirm the arrival of a transaction that you are sending? You can do this a few different ways, for example, after broadcasting it, you could grab the hash, subscribe to a periodical event, and use that to call `web3.eth.getTransactionReceipt(hash, [, callback])` until it returns something valid. 

You could equally use the `.on("confirmation" [,callback])` when broadcasting, this'll return the number of confirmations every time one is received.

You can find more information [here](https://web3js.readthedocs.io/en/1.0/web3-eth.html), but I'm happy to answer any further questions you have.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
