### ISSUE TITLE
Cannot read property 'name' of undefined at Contract._generateEventOptions

### ISSUE THREAD

**Issue by Eugene282** [ethereum/web3.js#1926]
it is in **web3-eth-contract** library.

stack:

TypeError: Cannot read property 'name' of undefined at Contract._generateEventOptions (.../node_modules/web3/node_modules/web3-eth-contract/src/index.js:540:42) at Contract.getPastEvents (.../node_modules/web3/node_modules/web3-eth-contract/src/index.js:655:49) at Promise... 

**The reason is obvious** (web3-eth-contract/src/index.js:540):

```
if (!event) {
   throw new Error('Event "' + event.name + '" doesn\'t exist in this contract.');
}
```

**event** is undefined in event.name.
Please, fix it.

**Comment by nivida** [comment]
Thanks for opening this issue. This is already solved in PR https://github.com/ethereum/web3.js/pull/2000 and should be released within the next build.
