### ISSUE TITLE
Invalid JSON RPC response error is thrown instead of a timeout error

### ISSUE THREAD

**Issue by uluhonolulu** [ethereum/web3.js#1928]
When I set a timeout for my HttpProvider, and my request times out, I see the following error:
```
Error: Invalid JSON RPC response: ""
```

I believe this is caused by the `onreadystatechange` event emitted before the `timeout` event, see `_setReadyState` called before `_dispatchProgress('timeout')`:
```
    XMLHttpRequest.prototype._onHttpTimeout = function(request) {
      if (this._request !== request) {
        return;
      }
      this._setError();
      request.abort();
      this._setReadyState(XMLHttpRequest.DONE);
      this._dispatchProgress('timeout');
      return this._dispatchProgress('loadend');
    };
```
(in xhr2.js).

I think an obvious solution would be to listen to the `loadend` event instead.

My web3 version is 0.20.0.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
