### ISSUE TITLE
Metamask and Web3 return different values for web3.eth.getAccount

### ISSUE THREAD

**Issue by TimDaub** [ethereum/web3.js#1931]
Hi,

I can't really pinpoint if web3 or Metamask are causing this problem but the following happens:

I have an account on Metamask that has the following address:
0x56aa86fe8c16afb609d35890457071188140ea5a

When in my frontend I do `web3.eth.getAccounts()`, I get 0x56AA86Fe8c16Afb609D35890457071188140eA5.

Notice how it is the same address but with a few letters capitalized. Maybe I'm being incompetent here but aren't these two different addresses?

If this a metamask problem, I'm happy to close this issue and move it to their repository.

**Comment by SvenMeyer** [comment]
It's the same address , an 'A' = 'a' = 10 (decimal). The capitalization is just used as a checksum without (!) changing the address.
[https://medium.com/@danielque/why-ethereum-addresses-have-some-capitalized-letters-b8e55728ecaa](https://medium.com/@danielque/why-ethereum-addresses-have-some-capitalized-letters-b8e55728ecaa)

**Comment by TimDaub** [comment]
Thanks!
