### ISSUE TITLE
using web3 sendSignedTransaction not work

### ISSUE THREAD

**Issue by athlona64** [ethereum/web3.js#1932]
this code look like this
` if (!ks.isDerivedKeyCorrect(pwDerivedKey)) {
                    throw new Error("Incorrect derived key!");
                }

                try {
                    ks.generateNewAddress(pwDerivedKey, 1);
                } catch (err) {
                    console.log(err);
                    console.trace();
                }

                var sendingAddr = ks.getAddresses()[0]
                web3.eth.getTransactionCount(sendingAddr, (err, nonce) => {
                    console.log(nonce);
                    txOptions = {
                        gasPrice: web3.utils.toHex(60 * 1e9),
                        gasLimit: web3.utils.toHex(200000),
                        value: web3.utils.toHex(0),
                        nonce: nonce,
                        data: code,
                        chainId: web3.utils.toHex(4)
                    }

                    txOptions.to = contractAddress
                    txOptions.nonce += 1
                    var registerTx = txutils.functionTx(abi, 'transfer', [receivingAddr, web3.utils.toHex(amount * 10e17)], txOptions)
                    var signedValueTx = signing.signTx(ks, pwDerivedKey, registerTx, sendingAddr)
                    console.log('Signed register key TX: ' + '0x' + signedValueTx)
                    web3.eth.sendSignedTransaction('0x' + signedValueTx, (err, hash) => {
                        console.log(err);
                        console.log(hash);
                        if (!err) {
                            res.json({ success: hash, status: 200 });
                        } else {
                            res.json({ success: err, status: 404 });

                        }
                    })
                })`

function return correct hash but i can't find transaction hash on etherscan or get transaction from web3

how to solve help me pls.

**Comment by nivida** [comment]
Please ask this question on stackoverflow or in our gitter channel.
