### ISSUE TITLE
Bug in uint256 type check? doesn't allow numbers over ~100e14

### ISSUE THREAD

**Issue by mjdietzx** [ethereum/web3.js#1936]
```javascript
tokenSale.deploy({ data, arguments: [params.openingTime, params.closingTime, params.rate, params.wallet, 100e14, params.token, params.goal] }).send({
   from: '0xdeadbeef',
   gas: 5000000,
   gasPrice: 10e9,
}).then(console.log);
```
fails with:
`Uncaught Error: invalid number value (arg="_cap", coderType="uint256", value=10000000000000000)`
```javascript
tokenSale.deploy({ data, arguments: [params.openingTime, params.closingTime, params.rate, params.wallet, 100e13, params.token, params.goal] }).send({
   from: '0xdeadbeef',
   gas: 5000000,
   gasPrice: 10e9,
}).then(console.log);
```
passes as normal (and any values smaller than 100e13

**Comment by mjdietzx** [comment]
It looks like this isn't a problem with web3. I think it's due to https://github.com/MetaMask/metamask-extension/issues/2350

I'm using MetaMask as web3 provider and I was using `"web3": "^1.0.0-beta.36"`. So i downgraded to 0.2.0 which MetaMask requires and it works now. I only see this problem for deploying functions with large uint256 arguments in constructor

**Comment by mjdietzx** [comment]
<img width="621" alt="screen shot 2018-09-13 at 3 14 49 pm" src="https://user-images.githubusercontent.com/7217256/45490607-db168200-b767-11e8-9997-0ee48a4aff41.png">

My above comment, downgrading `web3js` deployed the contract. Then I realized all the arguments were set to `"3.963877391197344453575983046348115674221700746820753546331534351508065746944e+75"`

**Comment by mjdietzx** [comment]
Ah, number inputs need to be in hex format:

```javascript
const { toHex } = web3.utils;
const arguments = [toHex(params.openingTime), ...]
```

**Comment by wigy-opensource-developer** [comment]
@mjdietzx Where did you get the info that *all* number inputs need to be in hex? In 1.0.0-beta34 we could send bignumber decimal strings into web3 without any problems. In 1.0.0-beta.36 there is this extra heuristic added that prevents us to send higher bignumbers to the API. So what piece of documentation or announcement did we miss?

**Comment by SalahAdDin** [comment]
@wigy-opensource-developer Look at this: https://github.com/ethereum/web3.js/issues/2077
