### ISSUE TITLE
Add flow typings

### ISSUE THREAD

**Issue by gomesalexandre** [ethereum/web3.js#1938]
Hey guys and good work on this amazing library first of all 🔥 really helping with the ecosystem here by having an easy-to-use interface for web devs, to the Ethereum world !

I saw that TS typings were provided in https://github.com/ethereum/web3.js/pull/897 however no sign of flowtype there, which is a shame for folks out here who prefer static type-checking rather than a whole superset of JS.

Has any work been started on it, and if not, could I ? Thanks !

**Comment by nivida** [comment]
I think I will first just write the typings and port it to TypeScript after the stable release but I agree with you that type safety is an import thing! I will close this issue but believe types will be implemented as soon as possible :-)
