### ISSUE TITLE
web3 v1.0.0 - how to avoid native modules

### ISSUE THREAD

**Issue by andrewheadricke** [ethereum/web3.js#1939]
In web3 0.20.x there were no native modules that required compiling.  In web3 v1.0.0 there are several.

Is it possible to use web3 v1.0.0 without native modules?  falling back to javascript only just like the browser dist?

**Comment by nemani** [comment]
Hey @andrewheadricke!

Do you still need help with this? 
Can you tell me exactly what you mean by `native modules`?

If you want to use web3 without npm/webpack/etc, you can use a CDN and directly add it to your html page. 
```
<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.36/dist/web3.min.js" integrity="sha256-nWBTbvxhJgjslRyuAKJHK+XcZPlCnmIAAMixz6EefVk=" crossorigin="anonymous"></script>
```

The compiled files are also given in the dist folder of this repo, you can download and use them.
```
<script src="./dist/web3.min.js"></script>
```


Let me know you if you meant something else. :smile:

**Comment by andrewheadricke** [comment]
Thanks @nemaniarjun, so the issue I was having is bundling web3 for Electron.  I was trying to keep things simple by avoiding native node modules having to match Electrons built-in node version.  

If I try to import the browserified version into Electrons node it fails.  

It would be great to have js fallbacks instead of requiring the native compiles of things like scrypt etc.

**Comment by nemani** [comment]
@andrewheadricke understood! Unfortunatly I dont have any experience with Electron. 
However you maybe to take pointer from how [Mist implements web3 with Electron](https://github.com/ethereum/mist)

Cheers :smile:

**Comment by lastmjs** [comment]
Is there no browser-ready distribution anymore? The ES Modules build looked promising, but I'm having a lot of issues with the built-in node modules...can we make an ES Module version that will run straight in the browser? Or at least one that only requires bare specifier rewrites?

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
