### ISSUE TITLE
[web3@1.x] sendTransaction's error event doesn't return receipt as the second parameter

### ISSUE THREAD

**Issue by Anaphase** [ethereum/web3.js#1941]
When calling `web3.eth.sendTransaction()` or `web3.eth.sendSignedTransaction()`, the PromiEvent returned does not provide `receipt` as the second parameter to it's `error` event [like the docs suggest here](https://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-sendtransaction-return):

```javascript
// using the event emitter
web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '1000000000000000'
})
.on('transactionHash', function(hash){
    ...
})
.on('receipt', function(receipt){
    ...
})
.on('confirmation', function(confirmationNumber, receipt){ ... })
.on('error', console.error); // If a out of gas error, the second parameter is the receipt.

```

Instead, it appears to be `JSON.stringify`-ing the receipt and just appending it to the error message, which isn't super useful if you need to read some data off the receipt object. As a workaround, I can just call `web3.eth.getTransactionReceipt()` in the error handler (or like, `JSON.parse()` everything after the first line break in `error.message`?), but that's not ideal since the receipt _should_ be available to me already.

After digging around a bit, I found that [this line](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/index.js#L362) is indeed `JSON.stringify`-ing the receipt and appending it to the error message.

You can test this with some trivial example code:

```javascript
web3.eth.sendTransaction(transactionData) // specify a gasLimit you know will be too low for the contract method you're calling

  .on('error', (error, receipt) => {
    // receipt is undefined and error.message is:
    //
    // Transaction has been reverted by the EVM:
    // {
    //   "transactionHash": "0xa2ac91c7affd59a761dd088230008082a0bcd3c43e46dd70a70e79db9c5df993",
    //   "transactionIndex": 0,
    //   "blockHash": "0x8efa4a788fd29ccc0d25a893635c4c37ebe9ddc452df83f7c249181451f8c0e0",
    //   "blockNumber": 267,
    //   "gasUsed": 240358,
    //   "cumulativeGasUsed": 240358,
    //   "contractAddress": null,
    //   "logs": [],
    //   "status": false,
    //   "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    // }
  })
```

**Comment by nivida** [comment]
Thanks for your pull request!
Could you update this PR later when the ethereumProvider branch got merged or do these changes against the ethereumProvider branch?

**Comment by nivida** [comment]
This got fixed with the [AbstractObservedTransactionMethod](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js#L154).
