### ISSUE TITLE
Move errors from web3-core-helpers

### ISSUE THREAD

**Issue by rumkin** [ethereum/web3.js#1942]
Currently [errors](https://github.com/ethereum/web3.js/blob/1.0ES6/packages/web3-core-helpers/src/errors.js) are located in web3-core-helpers which has in dependencies several libraries which need to build native modules. But errors itself aren't using any of this dependency or another core helpers component. So it looks reasonable to move them to separated package.

I've met this issue trying to create custom provider for the web. I propose to move it to it's own package web3-core-errors.

**Comment by nivida** [comment]
This will be improved as soon as possible. I will implement a logger class and move them to the web3-core package or I will create a new package for the logger and error types.
