### ISSUE TITLE
if the function of web3.eth.accounts.create()  will generate same address or privateKey?

### ISSUE THREAD

**Issue by qingyang-id** [ethereum/web3.js#1945]
I use the function of web3.eth.accounts.create() to create address and private key, but I am not sure if it will generate duplicate addresses or private key.whether it will?

**Comment by dtmle** [comment]
The chances of generating a duplicate address or private key using that method is slim to none.
If you really want to increase the randomness, supply a string of atleast 32 characters into the function.

Please see here: https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html
