### ISSUE TITLE
new Buffer is deprecated and unsafe

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#1950]
`new Buffer` is deprecated and unsafe. We should not use deprecated/unsafe Buffer constructor.

This issue can be resolved by this PR: 
https://github.com/ethereum/web3.js/pull/1949

The behavior of new Buffer() is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or Buffer initialization is not performed.

To make the creation of Buffer instances more reliable and less error-prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.

**Comment by nivida** [comment]
I've already fixed the Buffer usage in the PR https://github.com/ethereum/web3.js/pull/2000. 🙈
