### ISSUE TITLE
Need Help : Unhandled Rejection (TypeError): __WEBPACK_IMPORTED_MODULE_5__lottery__.a.methods.manager is not a function

### ISSUE THREAD

**Issue by DTiapan** [ethereum/web3.js#1951]
I am trying to call manager method from the contract but after saving the code react server throws above error.
Below is my smart contract:

`
pragma solidity ^0.4.17;
contract Lottery {
    address public Manager;
    address[] public Players;
    uint index;
    function Lottery() public {
    Manager = msg.sender;
    }
    function enter() public payable {
    require(msg.value > 0.1 ether);
    Players.push(msg.sender);
    }
    function getPlayers() public view returns(address[]) {
    return Players;
    }
    function random() private view returns(uint) {
    return uint(keccak256(block.difficulty, now, Players));
    }
    function pickWinner() restricted public {
    index = random() % Players.length;
    Players[index].transfer(this.balance);
    Players = new address[](0);
    }
    modifier restricted() {
    require(msg.sender == Manager);
    _;
    }
}
`
App.js having below code,
`` import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import web3 from './web3';
import lottery from './lottery';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {manager : ''};
  }
  async componentDidMount() {    
    const manager = await lottery.methods.manager().call();
    this.setState({ manager});
  }
  render() {

    return (

      <div className="App">
    <h2>lottery Contract</h2>
    <p>This contract managed by {this.state.manager}</p>
      </div>
    );
  }
}

export default App;``

I am using Web3@1.0.0.beta-26 please help me to fix this error

Please help me to fix this.

**Comment by DTiapan** [comment]
i figured it out..

the issue was with delecration of constructor , the constructor name should be same as of contract name.

constructor definiton should be ,

`function AjToken (uint256 _initialSupply) public {
		balanceOf[msg.sender] = _initialSupply; 
		totalSupply = _initialSupply;
	}	`

whereas i used,

`constructor (uint256 _initialSupply) public {
		balanceOf[msg.sender] = _initialSupply; 
		totalSupply = _initialSupply;
		//allocate the totalSupply
	}`

becuase of warning as it said : 

> Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.

reverting helped me to solve it..

**Comment by nivida** [comment]
Please ask this question on stackoverflow or in our gitter channel.
