### ISSUE TITLE
web3.eth.Contract.events.MyEvent does not work.

### ISSUE THREAD

**Issue by biigpongsatorn** [ethereum/web3.js#1957]
I want to get past event of my contract and i try to use `getPastEvents` but this function only return success transactions, I want to get all transactions status (Success, Fail, Pending (optional)) and I try to use `contract.events.MyEvent` and this function return `Subscription` data or something like that (example return value below).

![image](https://user-images.githubusercontent.com/10693658/45704065-35687600-bba0-11e8-8851-969dca5bd0e8.png)

I used web3.js version `1.0.0-beta.34`.

Thank you.

**Comment by nivida** [comment]
Please read the documentation about contract events. It's explained there how to subscribe to a contract event. https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events
