### ISSUE TITLE
hi i have tried to install web3 but every time i fail, this is what I receive as an error here is the problem occurs at first it installs and proceds but nearly at the end it fails

### ISSUE THREAD

**Issue by rajmantechnology** [ethereum/web3.js#1959]
PS F:\seondtesti> npm install --save web3@1.0.0-beta.26

> scrypt@6.0.3 preinstall F:\seondtesti\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install F:\seondtesti\node_modules\scrypt
> node-gyp rebuild

F:\seondtesti\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\rajma\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\rajma\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\rajma\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\rajma\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\rajma\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rajma\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\seondtesti\node_modules\scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'F:\seondtesti\package.json'
npm WARN seondtesti No description
npm WARN seondtesti No repository field.
npm WARN seondtesti No README data
npm WARN seondtesti No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rajma\AppData\Roaming\npm-cache\_logs\2018-09-19T06_49_41_609Z-debug.log

**Comment by dtmle** [comment]
Hi there,
You need to have python installed, notably 2.7 to install web3.
Try installing window-build-tools, adding Python2.7 to your system paths.
Here is how to install window-build-tools: https://github.com/felixrieseberg/windows-build-tools
Hope this helps.

**Comment by Sandybaby07** [comment]
may be you can try
sudo npm install scrypt --unsafe-perm=true --allow-root

**Comment by therightstuff** [comment]
It's also possible that windows-build-tools aren't sufficient, I had to install Visual Studio community edition for gyp to work
