### ISSUE TITLE
Error while installing any Web3js 1.0.Beta release

### ISSUE THREAD

**Issue by arnoudcommandeur** [ethereum/web3.js#1962]
I get an error while I try to install the web3js 1.0.beta versions on my Windows 10 machine.

De commandline log is as follow:

C:\eth4>npm install web3@1.0.0-beta.34
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall C:\eth4\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\eth4\node_modules\scrypt
> node-gyp rebuild

C:\eth4\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\arnou\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\arnou\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\arnou\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\arnou\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\eth4\node_modules\scrypt
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN eth4@1.0.0 No description
npm WARN eth4@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arnou\AppData\Roaming\npm-cache\_logs\2018-09-20T06_09_00_461Z-debug.log

I have installed a lot op npm packages but still the installation fails. Web3 0.2.0 works fine.

Hope anyone can figure out how to solve this.

Thanks in advance!

Arnoud

**Comment by dtmle** [comment]
Hi there,

Do you have python 2.7 installed? If so, you will have to change which version of python you are using.
`npm config set python python2.7` should do the trick.

If you don't have python 2.7 installed, a great way to get it as well as other dependencies is using windows-build-tools.

Here's a link about windows-build-tools: https://github.com/felixrieseberg/windows-build-tools

Hope this helps,
Good luck!

**Comment by arnoudcommandeur** [comment]
Hi dtmle,

thanks for your answer. The installation works fine now. Unfortunately I still get an error while using web3 within Chrome. Tge error I get is: failed to load http://localhost:8545/: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

I tried several solutions, unfortunately without any succes.

I'm running my page via a webserver (http-server). Any suggestions how to solve this issue too?

Thanks in advance,
Arnoud

**Comment by arnoudcommandeur** [comment]
I solved the latest issue by starting Chrome via: chrome.exe --disable-web-security --user-data-dir
(on an Windows 10 computer)

**Comment by dtmle** [comment]
@arnoudcommandeur Nice work! I've never ran into that problem. I've only hosted web3.js using Express.js.
Thanks for telling us how you fixed it!
