### ISSUE TITLE
What is the returnSignature?

### ISSUE THREAD

**Issue by donamk** [ethereum/web3.js#1963]
In the manual, web3.eth.signedTransaction() and web3.eth.sign Retruns section, it is wrriten that
`if returnSignature is true the signature values as follows:`

However, there is no `returnSignature` in web3-eth-accounts/index.js(v1.0.0-beta.36) or in both function params.

What is the returnSignature?

@frozeman

**Comment by donamk** [comment]
Another question, what is the purpose of the return value of web3.setProvider? It seems like return true always.

**Comment by nivida** [comment]
Please ask these questions on stackoverflow or in our gitter channel.

**Comment by tjanson** [comment]
The question about `returnSignature` seems legitimate: That parameter simply does not exist, it’s only mentioned in the docs. (A leftover from some previous version?)
Or am I missing something?
