### ISSUE TITLE
Cannot read property 'id' of undefined when calling `websocketProvider.send()`

### ISSUE THREAD

**Issue by mrwillis** [ethereum/web3.js#1967]
Currently when calling send on the WebsocketProvider in the `_addResponseCallback` method there is a check to make sure `id` is defined. If you pass 0 into this method it will always throw an error because `0 || payload[0].id` is an error. The workaround is to put anything but 0. 

I think perhaps the second condition in the OR should be removed.

Here is code to reproduce this (send in a websocket provider):

```javascript
import Web3 from "web3";
import { Provider } from "web3/providers";

export class GanacheSnapshotter {
  private web3: Web3;
  constructor(web3Provider: Provider) {
    this.web3 = new Web3(web3Provider);
  }

  public async takeSnapshot() {
    return new Promise((resolve, reject) => {
      this.web3.currentProvider.send(
        {
          method: "evm_snapshot",
          jsonrpc: "2.0",
          params: [],
          id: 0
        },
        (e, _) => {
          if (e) {
            reject(e);
          } else {
            resolve();
          }
        }
      );
    });
  }

  public async revertSnapshot() {
    return new Promise((resolve, reject) => {
      this.web3.currentProvider.send(
        {
          method: "evm_revert",
          jsonrpc: "2.0",
          params: [],
          id: 0
        },
        (e, _) => {
          if (e) {
            reject(e);
          } else {
            resolve();
          }
        }
      );
    });
  }
}
```

The error:

>      Uncaught TypeError: Cannot read property 'id' of undefined
>       at WebsocketProvider._addResponseCallback (node_modules\web3-providers-ws\src\index.js:222:39)
>       at WebsocketProvider.send (node_modules\web3-providers-ws\src\index.js:283:10)
>       at Timeout._onTimeout (node_modules\web3-providers-ws\src\index.js:263:19)

**Comment by nivida** [comment]
This got fixed in the PR #2000 and the ```send()``` method parameters did also change.
