### ISSUE TITLE
Build fixes and localhost geth test connections

### ISSUE THREAD

**Issue by therightstuff** [ethereum/web3.js#1970]
1. `npm run-script build` is failing without updating gulp usage to gulp 4 and the vinyl-source-stream package to version 2

2. The example code cannot be used to connect to a local geth node without credentials, so I've set the credentials to be required only in the case that a user and password have been supplied.

I've already submitted a PR https://github.com/ethereum/web3.js/pull/1956 and would be very grateful for a review!

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
