### ISSUE TITLE
web3.utils.stringToHex()  returning single quotes strings - breaks solidity

### ISSUE THREAD

**Issue by salpalacios** [ethereum/web3.js#1971]
Using version  '1.0.0-beta.36'
when using web3.utils...like such
 <img width="300" alt="screen shot 2018-09-25 at 3 54 25 pm" src="https://user-images.githubusercontent.com/14198661/46042600-65050a00-c0db-11e8-9c6f-aab5fdf921fc.png">

Currently the web3.utils.stringToHex() function and other, are returning single quote strings of hex values, which is problematic since solidity only accepts them as a double quoted character.

Example:

> web3.utils.stringToHex("test")
'0x74657374'

Solidity reject this as a valid hex string argument

Shouldnt it  Be (docs use double quotes in examples too):
"0x74657374"

The serialized output with single quotes causes issues inside solidity:
![err1](https://user-images.githubusercontent.com/14198661/46043125-bfeb3100-c0dc-11e8-9ac9-e5963951eb29.png)

serialized output with double quotes now works:
![err2](https://user-images.githubusercontent.com/14198661/46043324-54ee2a00-c0dd-11e8-9bfe-c75ffdf0232a.png)

The read the docs, example do indeed show double quotes:
<img width="919" alt="screen shot 2018-09-25 at 4 21 41 pm" src="https://user-images.githubusercontent.com/14198661/46044026-3db03c00-c0df-11e8-8c69-d268a29f4b49.png">

**Comment by yzevm** [comment]
@nivida Not sure that its a `web3.js` problem. You can send transaction with single quotes using `web3.js` and `node.js`, solidity works fine here

But you use `remix IDE` and `Google Chrome`, which prefers double quotes (http://2ality.com/2012/09/javascript-quotes.html) therefore you need to change it manually or use web3 in `chrome console`
![Screenshot from 2019-06-11 12-31-16](https://user-images.githubusercontent.com/31797554/59260756-dcb49e00-8c44-11e9-83ad-c812aa2f0c08.png)

**Comment by nivida** [comment]
@YegorZaremba Thanks for giving me additional details regarding this issue! I will close this issue for now.
