### ISSUE TITLE
transaction of erc20token  is not being broadcasted

### ISSUE THREAD

**Issue by i-am-vivek** [ethereum/web3.js#1972]
Hi there,

#### System information
Geth
Version: 1.8.12-stable
Git Commit: 37685930d953bcbe023f9bc65b135a8d8b8f1488
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

I am trying to send the erc20 tokens one address to another. but transaction hash is generating. but it is not broadcasted. 
When I search transaction has on etherscan.io  it shows  

> Sorry, We Are Unable To Locate This transaction Hash.

I'm using **web31.0.0-beta.33** node plugin to make the transaction. 

after some time I'm getting following error on nodejs console

> Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Beware that it might still be mined!

My Code to transact the token is,
`let ctx = new web3.eth.Contract(ABI, contract_address, {
            from: xxxxxxx,
            gasPrice: gasPrice,
            gas: gas
        });

ctx.methods.transfer(to, 1000000000000000000 * amount).send()
                .on('transactionHash', (txHash) => {
                    rs({ txHash });
                })
                .on('receipt', console.log)
                .on('confirmation', console.log)
                .on('error', console.error);`
any help would be appreciated.

**Comment by chankruze** [comment]
Update to latest beta and do clean try. And make sure it don't hit transition limit.

**Comment by i-am-vivek** [comment]
It is working now As I moved to infura blockchain. I don't know what was the real issue. But moving to infura solved the issue.
