### ISSUE TITLE
10+ Hours Trying to Install Web3

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#1979]
_Been troubleshooting this for ~10 hours now :(.

Anyone have an idea why I may be receiving this error?

I reset the environment variable to no available. 

Any help would be much appreciated_

**Running NPM Install**

C:\Users\jeremy.nau\inbox>npm install

npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN inbox@1.0.0 No description

npm WARN inbox@1.0.0 No repository field.

added 90 packages from 505 contributors and audited 145 packages in 671.06s

found 0 vulnerabilities

**Then tried to install web 3 to no avail :(**

C:\Users\jeremy.nau\inbox>npm install --save web3@1.0.0-beta.35

npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall C:\Users\jeremy.nau\inbox\node_modules\scrypt

> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\jeremy.nau\inbox\node_modules\scrypt

> node-gyp rebuild

C:\Users\jeremy.nau\inbox\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

gyp ERR! configure error

gyp ERR! stack Error: Can't find Python executable "python27\python", you can set the PYTHON env variable.

gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)

gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)

gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29

gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)

gyp ERR! System Windows_NT 10.0.16299

gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd C:\Users\jeremy.nau\inbox\node_modules\scrypt

gyp ERR! node -v v8.12.0

gyp ERR! node-gyp -v v3.8.0

gyp ERR! not ok

npm WARN inbox@1.0.0 No description

npm WARN inbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the scrypt@6.0.3 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\jeremy.nau\AppData\Roaming\npm-cache\_logs\2018-10-01T23_07_15_297Z-debug.log

_And here are my file paths and variable sets_

![env var](https://user-images.githubusercontent.com/37713561/46325296-73a46300-c5ac-11e8-9000-b54fc15fe25b.png)
![file path](https://user-images.githubusercontent.com/37713561/46325303-78691700-c5ac-11e8-9bb1-a35e39228725.PNG)

_Any help would be much appreciated.

Thanks!

JN

**Comment by Jason-Soo** [comment]
You can try this "Run as admin in your Powershell or Node.js CMD

npm install --global --production windows-build-tools
after the installation is complete

npm install web3@1.0.0-beta.20 (or any beta version you like up to 36 if i'm not mistaken)

If you still can't try to clean your package files and everything delete away the word web3 from the package and try installing it again or try the web3 0.2 version it works fine normally for a lot of people with 1.x.x error, but 1.x and 0.2 has different documentation
