### ISSUE TITLE
Personal Sign on Web3 throws an error

### ISSUE THREAD

**Issue by sidsverma** [ethereum/web3.js#1981]
When I am trying to sign via the web3(0.20.7) personal sign method, metamask pops out the dialog for signing with the appropriate message:
<img width="358" alt="screen shot 2018-10-02 at 6 44 49 am" src="https://user-images.githubusercontent.com/13417050/46353098-370a5300-c610-11e8-826e-bdb37b78a1e3.png">

and upon clicking on Sign or Cancel, I get this error:

> Uncaught TypeError: e is not a function
>     at inpage.js:1
>     at inpage.js:1
>     at i (inpage.js:1)
>     at inpage.js:1
>     at inpage.js:1
>     at u (inpage.js:1)
>     at s (inpage.js:1)
>     at inpage.js:1
>     at inpage.js:1
>     at inpage.js:1

This is the code used for signing:
```javascript
async personalAuth(nam) {
            // nam = ssss
            var ethUtil = require('ethereumjs-util')
            var sigUtil = require('eth-sig-util')
            var name = ethUtil.bufferToHex(new Buffer(nam, 'utf8'))
            console.log(name)
            var from = web3.eth.accounts[0];
            var params = [name, from]
            console.log(params)
            var method = 'personal_sign'
            var result = null
            try {
			web3.currentProvider.sendAsync({
			        method,
			        params,
			        from,
	                }), function (err,res) {
                            if(err)
                                console.log(err)
                            result = res;
                            console.log('PERSONAL SIGNED:' + (result.result))
                            this.addUser(result.result)
                        }
            } catch(error) {
                console.log(error)
                }
        }```

**Comment by vibern0** [comment]
I can't see where this error came from.
Can you consider this article [here](https://consensys.zendesk.com/hc/en-us/articles/360004427792) and try to run an example?
Or maybe you consider any 1.x beta version of web3.js and use [web3.eth.personal.sign](https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign) instead.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.

**Comment by DeployIsComing** [comment]
Hello, I'm trying to sign two or more vouchers. 

To sign just one voucher I manage to make it work:

```
const signedVoucherPromise = new Promise(async (resolve, reject) => {
                    await web3.currentProvider.sendAsync({
                        id: new Date().getTime(),
                        method,
                        params,
                        from,
                    }, function (error, result) {
                        if (error) {
                            console.error(`Error on sendAsync: `, error)
                            reject(error)
                        }
                        resolve(result)
                    })
                })

                const signature = await signedVoucherPromise.then(res => {
                    return res.result
                }).catch(e => {
                    console.error('Error getting signed voucher: ', e)
                    throw new Error(e)
                })

                const signedVoucher = {...voucher, signature}
```

however I tried to add this function to batch.add and didn't work. 

I tried to add two blocks of the code above and just one worked, the other was ignored. 

I tried to add an array in sendAsync like 

  await web3.currentProvider.sendAsync([ {...}, {...}, {...}].... 
  
  and didn't work as well, I received this message:
  
`  eth_signTypedData_v4 request. Please provide a valid signer public address.`

Does anybody knows how to sign multiple itens and showing sign screen just one time?
