### ISSUE TITLE
encodeABI() doesn't work in web3 1.0.0-beta.36

### ISSUE THREAD

**Issue by Tetz** [ethereum/web3.js#1982]
I tried these code in web3 1.0.0-beta.36
```
const web3 = new Web3(new Web3.providers.HttpProvider(rinkebyUrl))
const contract = new web3.eth.Contract(abi, contractAddress)
contract.methods.transfer(toAddress, amount).encodeABI()
```
And then encodeABI() doesn't return any values. 
But if I try web3 1.0.0-beta.34, it works fine.  It's a kind of bug, isn't it?

**Comment by nivida** [comment]
Tested with version beta.43: 

```javascript

console.log(contract.methods.testBytes32(10).encodeABI());
> 0x518b31f1000000000000000000000000000000000000000000000000000000000000000a

```

Because it does work will I close this issue.

**Comment by BeycanDeveloper** [comment]
@nivida still have a problem sir.

![image](https://user-images.githubusercontent.com/50718965/227723542-264ea3ab-43a9-46d5-849f-22ba86606104.png)
