### ISSUE TITLE
WebSocket connection does not work - connection not open on send()

### ISSUE THREAD

**Issue by msflorez** [ethereum/web3.js#1987]
Hi, I'm getting the next error `connection not open on send()`, my *geth* was started with `--ws --wsport 8546 --wsaddr="0.0.0.0" --wsorigins "*"` params in a `docker-compose.yml` file and my *web3* has the next lines

```js
'use strict'

const Web3 = require('web3')
const Web3WsProvider = require('web3-providers-ws')

const web3 = new Web3(new Web3WsProvider('ws://localhost:8546'))

module.exports = web3
```

I'm using the next version of web3 and web3-provider-ws

```json
    "web3": "^1.0.0-beta.36",
    "web3-providers-ws": "^1.0.0-beta.36"
```

Someone can help me please?

Thanks in advance.

**Comment by 0x-r4bbit** [comment]
Happen to run in to the same issue. Was there any fix for this?

**Comment by msflorez** [comment]
Check your `ws` port, it has to be different of the `http` port. Changed it solved my issue.

**Comment by 0x-r4bbit** [comment]
Thanks for getting back here. And yes, this has been figured out on my side too. Turned out to be a race condition :)

Thanks again!
