### ISSUE TITLE
eth_signTypedData is not injective within type

### ISSUE THREAD

**Issue by brianbwong** [ethereum/web3.js#1992]
A key goal of EIP 712 is to create an injective hash for typed data structures. The current implementation of `eth_signTypedData` doesn't satisfy this property. For example, suppose the struct contains two string values. Part of the hashing process involves concatenating the raw string values and then hashing the result (as opposed to hashing both string values individually and then concatenating, which solves the problem because the hash output has fixed size). So the signature will be the same if the two strings are "onetwo", "three" as when the two strings are "one", "twothree". Example code below:

```
    const msgParams = [
      {
        type: 'string',
        name: 'Message1',
        value: 'one'
     },
     {
       type: 'string',
          name: 'Message2',
          value: 'twothree'
      },
    ];

    // NOTE: Swapping the boundary between the string values
    // eg "one", "twothree" ----> "onetwo", "three" as below
    // leads to the same signature and same hash.

    // const msgParams = [
    //   {
    //     type: 'string',
    //     name: 'Message1',
    //     value: 'onetwo'
    //  },
    //  {
    //    type: 'string',
    //       name: 'Message2',
    //       value: 'three'
    //   },
    // ];

    const from = this.du.accts[0];
    this.web3.currentProvider.sendAsync({
      method: 'eth_signTypedData',
      params: [msgParams, from],
      from: from,
    }, function (err, result) {
      if (err) return console.error(err)
      if (result.error) {
        return console.error(result.error.message)
      }

      const sig = result.result;
      console.log("Signature:", sig);
      const hash = sigUtil.typedSignatureHash(msgParams);
      console.log("Typed data hash:", hash);
    })
```

I'm using the latest stable release of web3 (0.20.6).

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. 
Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
