### ISSUE TITLE
web3.eth.subscribe returns null with ganache (TestRPC)

### ISSUE THREAD

**Issue by princesinha19** [ethereum/web3.js#1993]
I am using web3 version:- web3.js 1.0.0-beta.36
Ganache cli version :- Ganache CLI v6.1.5 (ganache-core: 2.1.4)

I tried to run web3.eth.subscribe but it's returns null with every new transaction. I have tried pending transaction,logs and newBlockHeaders.

> var subscription = web3.eth.subscribe('logs', {
>     address: '0x123456..'
> }, function(error, result){
>     if (!error)
>         console.log(result);
> });

All method return nulls.

I am using subscribe for getting latest transaction of particular account. Please let me know, If there is another method which can solve my issue.

**Comment by nivida** [comment]
Could you please provide the complete code and also which broser or node version you're using? thanks :-)

**Comment by princesinha19** [comment]
@nivida I have solved the issue.
