### ISSUE TITLE
web3.js does not diplay getTransactionReceipt()'s topics array detail in logs field

### ISSUE THREAD

**Issue by doorisys** [ethereum/web3.js#1994]
In Geth's javascript console getTransactionReceipt call displays whole details of logs.
And web3j(java implementation) does the same result.
But web3.js displays topics array as merely [Array].
 
logs: 
   [ { address: '0x809826cceab68c387726af962713b64cb5cb3cca',
       blockHash: '0x9d24b8def303f28d584ab27cb83cfc46005f8b049b48317545851993e5a60f38',
       blockNumber: 6489944,
       data: '0x0000000000000000000000000000000000000000000000c1daf81d8a3ce00000',
       logIndex: 117,
       removed: false,
       topics: [Array],
       transactionHash: '0x47b3f85ee994c36ec00cd82b983ee21b7302b2316d71f27b94a57d1fde56b31c',
       transactionIndex: 129 } ]

Is this intended?
Do I have to another step to see topics array details?

**Comment by nivida** [comment]
``console.log(log.topics)`` will log the array as expected.
