### ISSUE TITLE
Return a receipt on reverting transactions

### ISSUE THREAD

**Issue by eggy-eth** [ethereum/web3.js#1999]
Right now Web3 does not return a receipt if you send a transaction to a contract. It will only throw and event and fails to even fire a transactionHash event which can be calculated before actually sending the transaction. 

It is important to get the receipts of these transactions - especially to get the transactionHash - so these transactions can be debugged.

**Comment by nivida** [comment]
This got fixed during the refactoring [here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js). Please update to the latest version of Web3.js (1.0.0-beta.51)
