### ISSUE TITLE
web3.eth.estimateGas - Transaction execution error

### ISSUE THREAD

**Issue by PinnacleOne** [ethereum/web3.js#2004]
**web3 version 1.0.0-beta.36**
I'm using Kovan network and infura provider.

Here is my code:

```
async function test_eth() {
  const Web3 = require('web3')
  const web3 = new Web3(new Web3.providers.HttpProvider('https://your_infura_kovan_provider_url_here'))
  const gas = await web3.eth.estimateGas({ 
        nonce: '0x2',
        from: '0xb59dB86f4044Ac70C4eC7433341c108e1A3CB680',
        to: '0xd713A720CAc038C52eFfCdD709A9718C3143f30C',
        value: '0x00',
        data: '0xa9059cbb000000000000000000000000092fb7a515927844fea209e77e1b71efd93b508f0000000000000000000000000000000000000000000000000de0b6b3a7640000' 
    })
}
test_eth() 
```

Then execution of this code throw error:

> Error: Returned error: Transaction execution error.

What is inserting if I replace "to" address to something non ERC20 token contract the issue is gone and never appear. It only throw error if set in "to" address of ERC20 contract.

**Comment by mqklin** [comment]
@PinnacleOne it's because ERC20 token contract doesn't accept ethereum and rejects all those transactions

**Comment by Aniket-Engg** [comment]
> Error: Returned error: Transaction execution error.

Is this error defined by you or thrown by web3?

**Comment by guangxingmao** [comment]
web3.eth.estimateGas can't use for ERC20 contract now? i have the same error. and how can i do?

**Comment by mqklin** [comment]
@guangxingmao ERC20 token contract doesn't accept eth and rejects all these transactions. You can't send ETH to ERC20 contract

**Comment by guangxingmao** [comment]
> @guangxingmao ERC20 token contract doesn't accept eth and rejects all these transactions. You can't send ETH to ERC20 contract

but i use estimateGas, “to” is ERC20 contract,and only “data” is different, some transactions is ok, some transcations is error-( Transaction execution error)

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
