### ISSUE TITLE
Include minified file in npm release

### ISSUE THREAD

**Issue by fulldecent** [ethereum/web3.js#2013]
Currently, releases to npm include a single index.js file. Alternatively, or additionally, there should be an index.min.js file. This is a security issue.

# Security impact

CDN providers like jsdelivr are finding the not-compressed files as suboptimal and they are using their own proprietary, non-repeatable processes to generate their the index.min.js that they distribute to users.

For business reasons, they will not support SRI in these types of release.

Source: https://github.com/jsdelivr/jsdelivr/issues/18105#event-1916397273

To support end-user security (SRI) this project should publish proper, canonical, minified files which can be distributed as-is, without modification (uglification) by CDNs.

# References:

https://www.npmjs.com/package/web3/v/1.0.0-beta.36

I don't know how to cite the package formulas other than installing them myself. npm should be better at this. But here is the proof.

![screen shot 2018-10-21 at 7 07 19 pm](https://user-images.githubusercontent.com/382183/47273579-d8782b00-d564-11e8-8cfe-ee3bd8008165.png)

**Comment by nivida** [comment]
Thanks! I will add the minified UMD bundles on the next release (#2000) :-)

**Comment by nivida** [comment]
Got closed because of this issue. (https://github.com/ethereum/web3.js/issues/2623)
