### ISSUE TITLE
Correct way to send erc20 token with web3?

### ISSUE THREAD

**Issue by medied** [ethereum/web3.js#2017]
Couple of similar issues are #1775 and #1151, but one difference is that I'm using web3 v0.20.7. I was initially going off of [human-standard-token-abi](https://github.com/danfinlay/human-standard-token-abi) docs (reading calls such as `balanceOf()` are working fine), then tried with `sendTransaction()` directly. I'm getting the same error in both approaches though: 

`Failed to load resource: the server responded with a status of 405 () [https://rinkeby.infura.io/v3/xxx]
DEBUG - error in _sendToken 
web3Util.js:148
Error: Invalid JSON RPC response: ""`

This is what the method looks like: 

```
const _sendToken = (contractAddress, _to, _from, value) => {
  const contract = web3.eth.contract(abi).at(contractAddress);

  const rawTransaction = {
    from: _from,
    to: contractAddress,
    value: 0,
    data: contract.transfer.getData(_to, value),
    gas: 200000,
    chainId: 3,
  };

  web3.eth.sendTransaction(rawTransaction, (error, receipt) => {
    if (error) {
      console.log('DEBUG - error in _sendToken ', error)
    }
    console.log(receipt);
  });

  // Initial try following human-standard-token-abi
  // tokenInstance.transfer(_to, value, { from: _from }, function (err, txHash) {
  //   if (err) console.error(err);

  //   if (txHash) {
  //     console.log('Transaction sent!');
  //     console.dir(txHash);
  //   }
  // });
};
```

Any insight on what to try? What's the right way to do this with web3 v0.20.7

**Comment by vibern0** [comment]
Hi,
send from one account to another? Are you using metamask extension?

I've never done this kind of thing the way you are doing. I always have an ERC20 contract that holds balances and has a transfer method. Just call that method. Done.
In the end, if you follow the ERC20 standard you have those methods https://github.com/ethereum/EIPs/issues/20

Btw, I'm using web3.js and open-zeppelin for a while, always using the most recent versions (even the beta ones) and I never had problems.

**Comment by medied** [comment]
Hey @obernardovieira, yea just from one account to another. I have Metamask available but I initially thought it wasn't going to be necessary precisely because of the standard erc20 `transfer()` method you mention. As in something like below outlined [here](https://github.com/danfinlay/human-standard-token-abi):

```
tokenInstance.transfer(_to, value, { from: _from }, function (err, txHash) {
    if (err) console.error(err);

    if (txHash) {
      console.log('Transaction sent!');
      console.dir(txHash);
    }
  });
```

What version of web3 are you using? Token I'm testing with is with Zeppelin tech as well, using zOS

**Comment by vibern0** [comment]
web3-1.0.0-beta35
Does this example you posted, work ?

**Comment by medied** [comment]
No with that example I'm getting the `Invalid JSON RPC response: ""` error as well, starting to wonder if the web3 version is the issue (am using v0.20.7)

**Comment by Aniket-Engg** [comment]
@medied In your `rawtransaction` you are passing `chainId` as 3 and you seems sending transaction using rinkeby infura whose id is 4. I think this mismatch may be a reason for the error.

**Comment by medied** [comment]
@Aniket-Engg @obernardovieira thank you both for looking into this! I ended up upgrading web3 to 1.x.x and was able to get it working, safe to close this issue from my end

**Comment by jsliu27** [comment]
> contract.transfer
contract.transfer is undefined 
web vue + web3 
web3@0.20.X
@medied
