### ISSUE TITLE
Pdf download functionality in node js

### ISSUE THREAD

**Issue by rajmantechnology** [ethereum/web3.js#2018]
We are using this code to download the pdf file but we are getting problem. i want when i hit this route then pdf file will download.
But when i hit this api in postman and click on the download button then pdf file download. So i wnat to download the pdf file with data.

router.get('/demo',function (req,res){
async function getinvoicelist(){
         
 var chunks = [];
 var options = { method: 'GET',
 url: 'https://api.fortnox.se/3/invoices/31/preview',
 
request(options, function (error, response, body) {
 
  console.log(body);

});

Image :1 
![screenshot_35](https://user-images.githubusercontent.com/25636468/47427822-1ff1f780-d7af-11e8-92c2-8f31778248c2.png)

Image : 2
![screenshot_36](https://user-images.githubusercontent.com/25636468/47427839-2b452300-d7af-11e8-8022-5035b219c1c8.png)

Please check to solve this problem. Please help me to solve this problem.

**Comment by cdolek** [comment]
@rajmantechnology maybe you aimed for another repo, this is not quite the right place to post such a question.

You can go to https://www.stackoverflow, describe your problem [better](https://stackoverflow.com/help/how-to-ask) and get some answers.

**Comment by rajmantechnology** [comment]
cdolek

ok.....

**Comment by rajmantechnology** [comment]
cdol

> @rajmantechnology maybe you aimed for another repo, this is not quite the right place to post such a question.
> 
> You can go to https://www.stackoverflow, describe your problem [better](https://stackoverflow.com/help/how-to-ask) and get some answers.

**Comment by rajmantechnology** [comment]
> @rajmantechnology maybe you aimed for another repo, this is not quite the right place to post such a question.
> 
> You can go to https://www.stackoverflow, describe your problem [better](https://stackoverflow.com/help/how-to-ask) and get some answers.

ok.
Now you can answer this on stack over flow . i have already mention the url:
https://stackoverflow.com/questions/52969856/pdf-download-functionality-in-node-js

**Comment by cdolek** [comment]
Please close this issue as this is not related to web3.js. Thank you.
