### ISSUE TITLE
web3-core-requestmanager needs unsafe eval

### ISSUE THREAD

**Issue by jvluso** [ethereum/web3.js#2023]
When using web3 in an extension, I am getting the error:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:".
```

It is coming from the line 
```
var global = Function('return this')();
```
in the web3-core-requestmanager.

Is this the correct place to raise this issue? Does this need to be written this way, or can it be written to work in a safe eval environment?

**Comment by nivida** [comment]
This issue is already solved and will be released with the next build. Because of that, I'll close this issue.
