### ISSUE TITLE
how to clean web3js cache

### ISSUE THREAD

**Issue by cowkeys** [ethereum/web3.js#2026]
these days i found that i always fetch the old data with web3js

i have to logout the metamask or click the reset account button first, so that i can get the newest data.

so how to handle this kindof problem?

**Comment by BennyTheDev** [comment]
Do you get this on a testnet (ropsten, rinkeby, private testnet) or mainnet, as well?
I need to know about this, too as it makes my dapp unusable with MetaMask.
If I find something out, I will post it here.

**Comment by BennyTheDev** [comment]
OK, found an acceptable workaround:

1. For state changing operations/functions (send), keep using window.web3 (Metamask will pick it up and use it)

2. For non-state changing functions (call), use a separate provider like Infura and inject it yourself into window._web3 or something like that and perform reading calls on this one instead.

This will slightly bloat your code but gives you un-cached results and both instances won't conflict with each other.

Example:

if (window.ethereum) {
     // standard web3 instance, being used for .send() operations
    window.web3 = new Web3(ethereum);
     try {
        ethereum.enable();
        // ROPSTEN example, can be changed to MAINNET in infura
        // This web3 instance is being used for .call() operations
        window._web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/v3/YOUR-API-KEY"));
        run(true);
     } catch (error) {
        console.log(error);
        _alert('You rejected to use this dapp.');
    }
}

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
