### ISSUE TITLE
npm install fail on nodejs Docker build

### ISSUE THREAD

**Issue by Trycoder** [ethereum/web3.js#2029]
Hi ,
Even I have the same issue as of #1416 .I have dockerized my node js app without web3.It is working fine.But when i add the following line of code the docker application exits without running.
const Web3 = require('web3');

However I need web3 for further process.

Note:
It works fine when it is run as a normal web app.But when i try to dockerize the app.I am not able to run the app.If I remove the web3 and its relational functions.I am able to dockerize the app.

**Comment by ctrlaltvikas** [comment]
@Trycoder Could you please check for the node version and npm version.

**Comment by Trycoder** [comment]
Adding the following lines in my docker file solved my issue:
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

And my docker file looks like this:
FROM node:8.11.1-alpine
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN npm install
RUN npm install pm2 -g
WORKDIR /usr/src/app
EXPOSE 8080  
CMD [ "pm2-runtime","start","ecosystem.config.js","--only","dev" ]

**Comment by Trycoder** [comment]
Thanks for your response @vikaskyadav

**Comment by schadokar** [comment]
@Trycoder  thanks it really helped. I was also struck at this stage. Can you please tell what that piece of code resolving? And Do we really need rest of the packages otherthan python?

**Comment by stefanone91** [comment]
> Adding the following lines in my docker file solved my issue:
> RUN apk update && apk upgrade &&
> apk add --no-cache bash git openssh
> RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev
> 
> And my docker file looks like this:
> FROM node:8.11.1-alpine
> RUN apk update && apk upgrade &&
> apk add --no-cache bash git openssh
> RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev
> RUN mkdir -p /usr/src/app
> WORKDIR /usr/src/app
> COPY . /usr/src/app/
> RUN npm install
> RUN npm install pm2 -g
> WORKDIR /usr/src/app
> EXPOSE 8080
> CMD [ "pm2-runtime","start","ecosystem.config.js","--only","dev" ]

thank you! Build with Docker now works!
