### ISSUE TITLE
You must provide the json interface of the contract when instantiating a contract object

### ISSUE THREAD

**Issue by jameszou707** [ethereum/web3.js#2032]
**when i try to get a contract object with web3 from Rinkelby net , here comes a error out :** 
--------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/3175690/47898912-d4c49c80-deb2-11e8-848d-8dab3b49e771.png)
--------------------------------------------------------------------------------------------------
### error msg: Error: You must provide the json interface of the contract when instantiating a contract object.

**Comment by jameszou707** [comment]
### Solution: then we found if we change the web3 version from 1.0.0-beta.36 back to 1.0.0-beta.35 , the bug disappeared：
`npm install --save web3@1.0.0-beta.35`

**Comment by Aniket-Engg** [comment]
Possible reason of throwing error are : Either ABI is not provided or ABI is not an array as per the code below.
```
if(!jsonInterface || !(Array.isArray(jsonInterface))) {
        throw new Error('You must provide the json interface of the contract when instantiating a contract object.');
    }
```
And this has not changed from `beta.35` to `beta.36`

**Comment by nivida** [comment]
I'm closing this issue because it seems like it isn't an issue of web3.

**Comment by elvioorg** [comment]
> ## **when i try to get a contract object with web3 from Rinkelby net , here comes a error out :**
> ## ![image](https://user-images.githubusercontent.com/3175690/47898912-d4c49c80-deb2-11e8-848d-8dab3b49e771.png)
> ### error msg: Error: You must provide the json interface of the contract when instantiating a contract object.

**Comment by GregTheGreek** [comment]
Please open a new issue
