### ISSUE TITLE
web3.js not installing

### ISSUE THREAD

**Issue by aparnathi567** [ethereum/web3.js#2035]
C:\>e:

E:\>mkdir test

E:\>cd test

E:\test>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to E:\test\package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

Is this OK? (yes)

E:\test>npm install web3
****npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall E:\test\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install E:\test\node_modules\scrypt
> node-gyp rebuild

E:\test\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\kaushik\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kaushik\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\kaushik\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kaushik\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\test\node_modules\scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kaushik\AppData\Roaming\npm-cache\_logs\2018-11-03T07_03_58_094Z-debug.log**

E:\test>**

**Comment by mqklin** [comment]
You have a problem with `node-gyp`, not with `web3`

**Comment by aparnathi567** [comment]
> You have a problem with `node-gyp`, not with `web3`

then, how to solve it

**Comment by mqklin** [comment]
Google it, depends on your errors
https://github.com/nodejs/node-gyp#installation try this for example

**Comment by thundo** [comment]
You should probably install Python 2.7, not 3.x.

**Comment by Huanzhang89** [comment]
@thundo makes a good point, node-gyp does not work with python v3.x as stated by their github page https://github.com/nodejs/node-gyp

**Comment by EddieOne** [comment]
Also, I think just [update Node](https://nodejs.org/en/download/)

**Comment by paulmelero** [comment]
have you seen https://github.com/ethereum/web3.js/issues/1783#issuecomment-405650471 ? Kind regards!

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
