### ISSUE TITLE
this.provider.send is not a function

### ISSUE THREAD

**Issue by diogomartino** [ethereum/web3.js#2038]
I'm trying some examples from the wiki, nothing is working:

`var web3 = new Web3(Web3.givenProvider || "https://mainnet.infura.io/v3/5d4d4f7190b94eb4893ef4dbdc782255");
web3.eth.getBalance("0x407d73d8a49eeb85d32cf465507dd71d507100c1").then(console.log);`

throws:

**Uncaught TypeError: this.provider.send is not a function
    at s.send (web3.min.js:1)
    at _.e [as getBalance] (web3.min.js:1)
    at script.js:7**

And this:

`web3.eth.getBlockNumber().then(console.log);`

throws this:

**Uncaught TypeError: this.provider.sendAsync is not a function
    at s.sendAsync (web3.min.js:1)
    at _.e [as getBlockNumber] (web3.min.js:1)
    at <anonymous>:1:10**

This isn't the only fuctions that don't work, none of the ones I used worked so far. Directly from the wiki. I'm importing:

`<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>`

**Comment by taarushv** [comment]
Can confirm the same behavior. 

Simply the following in app.js:
`var web3 = new Web3("https://ropsten.infura.io/v3/e6780ebea2fe4b1b8dde4c72fa0c78a8");
`
returns :
web3.min.js:1 Uncaught TypeError: this.provider.send is not a function
    at s.send (web3.min.js:1)
    at _.accounts (web3.min.js:1)
    at app.js:5

**Comment by diogomartino** [comment]
> Can confirm the same behavior.
> 
> Simply the following in app.js:
> `var web3 = new Web3("https://ropsten.infura.io/v3/e6780ebea2fe4b1b8dde4c72fa0c78a8"); `
> returns :
> web3.min.js:1 Uncaught TypeError: this.provider.send is not a function
> at s.send (web3.min.js:1)
> at _.accounts (web3.min.js:1)
> at app.js:5

@taarushv I managed to fix that error, just do like this:

`var web3 = window.web3 ?
  new Web3(window.web3.currentProvider) :
  new Web3(new Web3.providers.HttpProvider("https://mainnet.infura.io/v3/5d4d4f7190b94eb4893ef4dbdc782255"));`

The problem is that the documentation is all wrong. If you copy code from the wiki, it will not work, but it should. I just gave up, I'm using another library.

**Comment by jpantunes** [comment]
@bruxo00 can you run web.version and check what the loaded library version is please? 

I ran your code with web3@1.0.0-beta36 and it worked fine.

`ProBook:tcr EthDev$ node
> const Web3 = require('Web3')
undefined
> var web3 = new Web3(Web3.givenProvider || "https://mainnet.infura.io/v3/5d4d4f7190b94eb4893ef4dbdc782255"); 
undefined
> web3.eth.getBalance("0x407d73d8a49eeb85d32cf465507dd71d507100c1").then(console.log);
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> 0
> web3.eth.getBlockNumber().then(console.log);
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> 6783557
> web3.version
'1.0.0-beta.36'
> 
`

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
