### ISSUE TITLE
Feature request: `personal.decrypt`, enable an encrypted message for a publicKey to be decrypted from that wallet

### ISSUE THREAD

**Issue by mjdietzx** [ethereum/web3.js#2039]
A really nice feature of `web3` is [`personal.sign`](https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign), enabling a user to sign data with their wallet. It seems like this has enabled a lot of interesting features in DApps (i.e. logging in by signing a message with wallet, signing legal documents with wallet, etc..)

I think it would be great to also support the 'inverse', `personal.decrypt` - enabling a user to decrypt data (encrypted for their public key) with their private key. ie data for a specific public wallet address can be decrypted from the wallet (similar to https://github.com/pubkey/eth-crypto#decryptwithprivatekey). assuming the data was encrypted for that specific public wallet address (similar to: https://github.com/pubkey/eth-crypto#encryptwithpublickey)

One example use-case, a DApp has some info for a specific user (ie a transaction receipt), so they encrypt it for that user's public wallet address, upload this encyrpted data to ipfs, and then the user can pull this encypted data and decrypt it by confirming in their wallet. this way the DApp can display the data to the user in the frontend without access to the user's private key

DApps could even facilitate the sharing of data between parties (ie user to user, or user to a different dapp) without actually having access to that data

Is this a realistic feature to get added to the web3 interface? Any potential blockers or issues?

Thanks,
Mike

**Comment by emilianobonassi** [comment]
Completely agree with you @mjdietzx it's an enabler feature which could led to develop more l2 protocols on top of it.

Sign and decrypt are the basis of them.

@nivida I would like to work on it, do you have any suggestion on the workflow to follow?

**Comment by nivida** [comment]
@emilianobonassi Thanks for offering your help here! We currently do define contribution rules in PR https://github.com/ethereum/web3.js/pull/3224. Feel free to read them and to use the PR template we do provide and also don't hesitate to ask here in this issue or on your proposed PR if something isn't clear to you. 

Btw.: I would recommend implementing this feature in the 1.x codebase because the 2.x architecture is changing heavily (refactoring 2.x: https://github.com/ethereum/web3.js/pull/3249).

**Comment by FCO** [comment]
any update about this?

**Comment by mahdi-ln** [comment]
Metamask has added asymmetric encryption support in V8.0.0 
how can I use it.in web3.js?

**Comment by emilianobonassi** [comment]
Look at this @Mahdi321 

https://github.com/emilianobonassi/test-dapp

https://encrypt-decrypt.ebonassi.vercel.app

https://twitter.com/emilianobonassi/status/1278988848828239874

**Comment by mqklin** [comment]
hey @emilianobonassi 
could you please send a link to a working github repo? a get 404 for the test-dapp
