### ISSUE TITLE
how to get txhash before transaction is mined

### ISSUE THREAD

**Issue by toknT** [ethereum/web3.js#2041]
my web3 version is 1.0.0-beta.36

i am working on dapp, and the code

```js
let result = await SimpleStoreContractInstance.methods.set(value).send({ from: web3.eth.defaultAccount });
```

but it wait until the transaction is mined

**Comment by miyao-gmo** [comment]
@qding-bot 

if you use not promise but callback, you can get txhash before mining.

`web3.eth.sendTransaction({
    from: "__ADDRESS__",
    gasPrice: "20000000000",
    gas: "21000",
    to: '__ADDRESS__',
    value: "100000",
}, (error, txHash) => console.log(txHash)).then(console.log).catch(console.log);`

**Comment by miyao-gmo** [comment]
@toknT @qding-bot 

if you use not promise but callback, you can get txhash before mining.

```
web3.eth.sendTransaction({
    from: "0x41f69de3862788f01aC6eA3eF8951102434AF474",
    gasPrice: "20000000000",
    gas: "21000",
    to: '0x3535353535353535353535353535353535353535',
    value: "100000",
}, (error, txHash) => console.log(txHash)).then(console.log).catch(console.log);
```
