### ISSUE TITLE
Possible to set multiple providers?

### ISSUE THREAD

**Issue by mayupumi** [ethereum/web3.js#2046]
Hi.
I've built private geth network with two nodes.
I want web3js to use both nodes as the provider.
Seems web3.py support such operation. https://web3py.readthedocs.io/en/stable/providers.html
Is there any way to set multiple providers? Or generally web3 shouldn't do that?

**Comment by Asone** [comment]
From what i read of the sources of Web3 there is no way right now to have multiple providers. 

`setProvider` is defined here : 

https://github.com/ethereum/web3.js/blob/822cf8d76a04b85c2b91842dc6efb1058b7aabb5/lib/web3.js#L86

it sets the provider for its dependency, Request manager using eponym method which is defined here : 

https://github.com/ethereum/web3.js/blob/822cf8d76a04b85c2b91842dc6efb1058b7aabb5/lib/web3/requestmanager.js#L126

Request manager caches given provider to `this.provider` which is defined in its constructor. I couldn't find any array type management around provider. 

Such possibility could be requested as feature, however i don't think it'll be a priority. 

Meanwhile i guess you can write your own providers management system without to much pain by using `try{}catch(){}` around `setProvider`.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
