### ISSUE TITLE
Extracting signature parameters r, s, v

### ISSUE THREAD

**Issue by deanvaessen** [ethereum/web3.js#2047]
Hi,

I needed a function to generate the r, s, v parameters of the signature of a message that I signed with web3, and was surprised that I couldn't find such a function available in web3 (unless I missed something of course). Does it fit within the scope of the project to include this? I can make a pull request if so, this is my current implementation:

```
    getSignatureParameters( signature ) {
        const r = signature.slice( 0, 66 );
        const s = `0x${signature.slice( 66, 130 )}`;
        let v = `0x${signature.slice( 130, 132 )}`;
        v = this.web3.utils.toDecimal( v );

        if ( ![ 27, 28 ].includes( v ) ) v += 27;

        return {
            r,
            s,
            v
        };
    };
```

**Comment by ryanc414** [comment]
Was this function removed? I can't find it in the docs for the v1.10.0 release.
