### ISSUE TITLE
The gap of nonce.

### ISSUE THREAD

**Issue by Bat-Orshikh** [ethereum/web3.js#2049]
What happens when I set a wrong nonce on transaction. On the other hand, I made the gap between the nonces.

Latest nonce: 6
New nonce: 8.

**Comment by baterson** [comment]
Hi! check this answer you will find all you want . 
https://ethereum.stackexchange.com/questions/2808/what-happens-when-a-transaction-nonce-is-too-high

**Comment by Bat-Orshikh** [comment]
Yes I got it. 

I'm gonna close this issue.
