### ISSUE TITLE
Function web3.eth.sendTransaction occasionally reverts when 'gas' is not provided

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#2058]
I have just spent many hours trying to find which line of code in my contracts could possibly cause a revert.

Naturally, I started in the main contract's fallback function (invoked when transferring funds to that contract), and followed down the line to every other function invoked from it.

I have investigated by disabling different parts of the code, until arriving at the point where a single increment operation (`++`) made the difference (`sendTransaction` reverted when this line was included, and did not revert when this line was excluded).

At this point, I started suspecting that this was a `gas` issue.
So I added `gas: Number.MAX_SAFE_INTEGER` when calling `sendTransaction`, and voila!

Now please correct me if I'm wrong, but shouldn't the function throw an `insufficient gas` exception or something like that? Throwing a `revert` exception is extremely misleading IMO.

Please note that this problem occurs when testing with Truffle v4.1.14, which uses web3.js v0.18.4, so it might be irrelevant for more recent versions of web3.js.

Thanks

UPDATE:

I realize that this problem could in fact go back to the Ethereum node itself, so to add some related info, I am using ganache-cli v6.1.8.

**Comment by nivida** [comment]
Thanks for submitting this issue I will definitely test it! :)

**Comment by barakman** [comment]
@nivida:
Thank you.

To be honest, after applying the `gas: Number.MAX_SAFE_INTEGER` workaround, I have encountered a more critical problem.

When running a stress-test (which invokes `sendTransaction` over thousands of iterations), I receive the following error from Ganache:
```
CONNECTION ERROR: Couldn't connect to node http://127.0.0.1:8545
```
This error occurs sporadically, which makes it very hard to investigate on client side (i.e., my side).
It does not occur if I replace `sendTransaction` with an explicit call to a contract function which does exactly what the fallback function does (with the only difference being that, in contrast with the "anonymous" fallback function, this one has a name).

I have also observed that `sendTransaction` appears to run much longer than an explicit contract function call, which might explain the connection error.

This problem essentially prevents me from running exhaustive tests on the fallback function.

Thanks

**Comment by grabastart** [comment]
Security question regarding the following method/code sample of executing web3's sendTransaction for ether as a function for a web application that is not related to Ethereum, 

// using the promise
web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '100'
})
.then(function(receipt){
    ...
});

Where and how does it indicate I or someone else who owns the the account or address of 0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe
has granted this code the permission to send 100 ether to 
0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe
?

**Comment by barakman** [comment]
@grabastart:
This kind of access-control is implemented on-chain, not off-chain (i.e., in the contract itself).
And you should generally ask this type of questions at https://ethereum.stackexchange.com or similar.
In either case, it doesn't seem to have anything to do with this specific thread.
Thanks.

**Comment by grabastart** [comment]
@barakman while I appreciate your thought, for an API, I would think web3.js is faulty without additional parameters on the authentication part for the "from" field, such authentication value can be hashed so that it protects it as well.  For instance, auth1 = {value} would be unsafe while hash(auth1) = {hashedValue} would be safe.
