### ISSUE TITLE
web3.eth.defaultAccount is undefined

### ISSUE THREAD

**Issue by jesuscript** [ethereum/web3.js#206]
When used as a nodejs lib, defaultAccount is always undefined, requiring sendTransaction to specify from: explicitly. This contradicts the documentation.

As a suggestion, why not default it to web3.eth.coinbase?

**Comment by SilentCicero** [comment]
Agreed.

**Comment by kumavis** [comment]
I would say that web3 should have no consideration of mining and that `coinbase` should be removed. `defaultAccount` should be used anywhere `coinbase` was.

**Comment by frozeman** [comment]
I don't agree, as we don't know what a dapp tries to do, so assuming it should drain your coinbase by default is not smart.

Its easy to set the defaultAccount and should be set explicitly set by the dapp.
