### ISSUE TITLE
'TypeError: t.XMLHttpRequest is not a constructor' when using web3.min.js

### ISSUE THREAD

**Issue by Alenius** [ethereum/web3.js#2061]
Hello!

I am building an Azure function app with web3 for calling some smart contract. There is a problem with deploying to Azure using the web3-package because of scrypt. So instead i went for including web3.min.js like so:

    const Web3 = require('./web3.min.js');

When I deploy this to Azure or run it locally i get the error:

     'TypeError: t.XMLHttpRequest is not a constructor'

This seems weird to me since the code is working fine otherwise. Does anyone have a workaround?

I have already tried the light version and the regular web3.js aswell.

When installing the package with npm and using it in the regular way it works locally but as stated above, the problem then arises when deploying to Azure, so I need some other way of doing it.

**Comment by nivida** [comment]
This should be fixed with the PR #2000 please reopen this issue if not.
