### ISSUE TITLE
Unhandled Promise Rejection on 'sendRequest'

### ISSUE THREAD

**Issue by gabmontes** [ethereum/web3.js#2062]
When `.send()`'ing a contract method, web3 creates the handling logic, returns a `promiEvent` and finally executes the call at:

https://github.com/ethereum/web3.js/blob/0d54d94e637832abf97834e4fc444fbff87f874b/packages/web3-core-method/src/index.js#L581

Inside `sendRequest`, there is a call to `signTransaction`:

https://github.com/ethereum/web3.js/blob/0d54d94e637832abf97834e4fc444fbff87f874b/packages/web3-core-method/src/index.js#L536

If for any reason the signing fails, i.e. the `net` API is not enabled in the underlying node, `signTransaction` returns a failed promise that will be lost as the original `sendRequest` call does handle it (does not act on `defer` or `defer.eventEmitter`).

The result is an `Unhandled Promise Rejection` error and the web3 user code client hangs given the `promiEvent` does never emit even an `error` event.

@nivida I'm happy to contribute with a fix/PR. Just wondering if you or @frozeman have any thoughts on the better way to handle this.

Issue #1220 is possibly related or similar to this.

**Comment by nivida** [comment]
This will be fixed with the PR #2000

**Comment by nivida** [comment]
This is fixed since beta.38.
