### ISSUE TITLE
Can't find variable: btoa

### ISSUE THREAD

**Issue by yongloon** [ethereum/web3.js#2066]
Hi, I am using web3 on react native... i am facing this error

`Can't find variable: btoa`

I tried to install btoa and atob via npm but it is not working.

**Comment by Aniket-Engg** [comment]
@nyl9488 Please consider putting the related code

**Comment by kouohhashi** [comment]
Hi @nyl9488 
I got same error. Have you solved the error?

**Comment by nivida** [comment]
Does this error still occur with the latest version of Web3?

**Comment by nivida** [comment]
Closed due to the inactivity of the creator of this issue.

**Comment by ghost** [comment]
@nyl9488 @kouohhashi and anyone else experiencing the issue, you'll need to polyfill an implementation in. See https://stackoverflow.com/a/51525605 for an example.

**Comment by SurpriseMF3000** [comment]
Installing atob via `yarn add atob` works ;)
