### ISSUE TITLE
Join forces with web3x

### ISSUE THREAD

**Issue by xpepermint** [ethereum/web3.js#2067]
Hey guys. I have a friendly proposal to join forces with https://github.com/xf00f/web3x. The code design is much cleaner and typescript works as it should. It's better for the community to have only one web3 version that we all love. @frozeman @xf00f

**Comment by nivida** [comment]
Hay, yes I agree with you it would be better to have just one project. I already contacted web3x and asked him to work together :) 
Have you seen the changes in the ethereumProvider branch? I‘ve refactored a lot of the codebase.

Please have a look at my medium post about it:
 https://medium.com/@samuel_91690/my-first-months-as-the-maintainer-of-web3-js-7715470b7ef7

**Comment by xf00f** [comment]
@xpepermint Just saw this when sifting through old emails.

I'd of course be delighted to focus our efforts singularly, but it would require the abandonment of one of the libraries as web3x, while still close in API alignment, is heavily diverged from web3.js in terms of code and structure.

I'm still working on web3x as it's meeting needs for me that web3.js does not. I've suggested to @nivida that web3x could be the baseline for a web3.js version 2, but at present I think we are prioritising things a bit differently.

@nivida Please do feel free to subsume any of web3x back into web3.js if you feel it can be useful.

**Comment by nivida** [comment]
> I'm still working on web3x as it's meeting needs for me that web3.js does not. I've suggested to @nivida that web3x could be the baseline for a web3.js version 2, but at present I think we are prioritising things a bit differently.

That's right currently the focus is just on the QA and bug fixing. I've done a lot of improvements already but there is still a lot to do. I did some drafts for a v2 API already and will finalize them for an open discussion here on GitHub. Stay tuned, big things are planned for the web3.js project :-)

> Please do feel free to subsume any of web3x back into web3.js if you feel it can be useful.

@xf00f Yep, I will definitely do :-)
