### ISSUE TITLE
Cannot find module 'web3-requestManager': web3@1.0.0-beta.36 in MAC

### ISSUE THREAD

**Issue by spechaker** [ethereum/web3.js#2072]

**Comment by spechaker** [comment]
I've installed "npm i web3"  (web3 1.0.0.beta.36)
I'm using npm 6.4.1 and node 10.14.0
I've imported web3 on my project. My project is using node.js for Firebase functions.
  const Web3 = require('web3')
And I never used Web3 at all. only declared the web3 object.
But I'm getting error when I deploy to my server:

> ----------------------------------------------------------

     Function load error: Code in file index.js can't be loaded.
     Did you list all required modules in the package.json dependencies?
     Detailed stack trace: Error: Cannot find module 'web3-requestManager'
         at Function.Module._resolveFilename (module.js:476:15)
         at Function.Module._load (module.js:424:25)
         at Module.require (module.js:504:17)
         at require (internal/module.js:20:19)
         at Object.<anonymous> (/user_code/node_modules/web3/packages/web3-core/src/index.js:26:22)
         at Module._compile (module.js:577:32)
         at Object.Module._extensions..js (module.js:586:10)
         at Module.load (module.js:494:32)
         at tryModuleLoad (module.js:453:12)
         at Function.Module._load (module.js:445:3)

> -------------------------------------------------------

But in my node_modules folder, there are `web3-core-requestmanager`.
Could you help me please?
Thanks

**Comment by Huanzhang89** [comment]
Hi @spechaker, could you elaborate on what your deployment script does?

This error seems pretty strange since the actual module is called `web3-core-requestmanager` and you can see from the error message that it is being required on line 26 of index.js inside web3-core.

I just did a fresh install of web3@1.0.0.beta.36 and checked out the line. It shows `var requestManager = require('web3-core-requestmanager');` which seems to be correct.

Could you check what your `/user_code/node_modules/web3/packages/web3-core/src/index.js:26` says and paste it here please?

**Comment by spechaker** [comment]
Hi @Huanzhang89 
Thanks to check out my question.
`var requestManager = require('web3-core-requestmanager');`

It seems correct.
But when I deploy to my firebase project, it's the same error.
And there is no the folder at /user_code/node_modules/web3/packages/
Maybe, does it has some issues on web3.js?

PS: When I install web3, there are many warnings. is it the same with you?

**Comment by spechaker** [comment]
@Huanzhang89 
[Warnings.txt](https://github.com/ethereum/web3.js/files/2634727/Warnings.txt)
Here is the warning logs

**Comment by Huanzhang89** [comment]
Yep I get quite a lot of warnings too but don't worry they are quite common when installing npm packages. 

Could you confirm that your project runs locally? Could you paste your package.json to show the version of web3 listed there. Also your deployment script.

Another thing you can do is try to build the project locally without deploying to see if it builds correctly at least. If it does, we can isolate the issue to the deployment process and not build.

**Comment by Huanzhang89** [comment]
https://firebase.google.com/docs/functions/handle-dependencies

Looking at the docs for firebase, make sure you have the correct version of web3 listed in your `package.json`

**Comment by spechaker** [comment]
Hi @Huanzhang89 
Here is json file

[package.json.txt](https://github.com/ethereum/web3.js/files/2636082/package.json.txt)
And it works on locally.
my testing function is simple:

> `const Web3 = require('web3')`
`const web3 = new Web3(Web3.givenProvider)`

It's really strange...
What do you think about this?

**Comment by Huanzhang89** [comment]
Looking at the docs for firebase deploy here https://firebase.google.com/docs/functions/get-started

It seems that firebase functions are usually located in its own folder with another package.json file. Could you check if that package.json contains the right version of web3? Not an expert on firebase but I expect that would be the package.json used when you run `firebase deploy --only functions`

**Comment by spechaker** [comment]
@Huanzhang89 Thanks for your kindly support!
I can't find the reason and will change the way to track the transactions.
Thanks again!!!

**Comment by Huanzhang89** [comment]
Sorry to hear that @spechaker, did you manage to check the `package.json` inside the `functions` folder? 

Thanks for your patience, hopefully once v1 is fully released the library will be more stable and easier to integrate with other technologies
