### ISSUE TITLE
Info requested: what code is configuring the _fireError event listener?  Getting "Invalid JSON RPC response" errors

### ISSUE THREAD

**Issue by roschler** [ethereum/web3.js#2074]
# Environment:

Ubuntu 18.04 Bionic Beaver
Node.JS v8.3.0
web3-utils v1.0.0-beta.36
web3 v1.0.0-beta.36
Ganache GUI v1.2.2

NOTE: I have spoken with at least 2 other people on the Web that are having similar problems.

I recently upgraded to Truffle 5.0 beta.  Ever since then I have started getting frequent "_Invalid JSON RPC response_" errors when running queries against Ganache while running my dApp.  My dApp uses the `web3` and `web3-utils` NPM packages.  

To isolate the problem I wrote a simple test project that does a few `web3` calls before sending a signed transaction to Ganache.  I _still_ get the RPC errors, even when making basic calls like `getAccounts()` or `getGasPrice()`, etc.  Note, in the test project I directly _require_ the `web3-utils` package so I can sign the transaction I send to Ganache.

If I try to run my dApp when Chrome+Metamask is running, my test project or dApp becomes unusable with the RPC errors occurring most of the time when I make a `web3` call.  I'm guessing it has something to do with Metmask making an `eth_blockNumber` call against Ganache once a second.  But just to be clear, it does happen frequently even when Metamask is _not_ running.

If I trace out the code the error is occurring in an emitter event listener named `_fireError()` found in the `web3_utils` package.  I did a full code scan for any references to the `_fireError()` method and found none.  Unfortunately I did not find any `addListener()` calls or it's alias `on()` involving the `_fireError()` call either.  

Given my lack of familiarity with event emitter listeners, I don't know how to trace out or find the code that is configuring `_fireError()` for use or "attaching" it as an emitter event listener so I can see if this listener is firing when it should.  **Right now it feels like it is firing when it shouldn't**, and when it does fire it rejects the promise in an anonymous method fired off by a `setTimeout()` call with a 1 millisecond delay.  This then breaks the entire promise chain in my test project or in my dApp.

Can someone tell me how to find the code that is configuring `_fireError()` for use?  Also, if you could point me to a general document on how emitter event listeners work in the context of an RPC server I would really appreciate it.   As of now my dApp development is halted until I can get this solved.

**Comment by roschler** [comment]
I found it.  The usage references to `_fireError()` are in the node_modules directory, which was excluded from my search path.  I added the node_modules directory to my search path and now I see the references to that function.

I would still appreciate comments on the overall problems I'm having with "Invalid JSON RPC response" errors.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
