### ISSUE TITLE
Trouble setting gas value with contract.method.sendTransaction(...)

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/web3.js#208]
Been using the new 4.2. Great work. Digging it. It seems as though the gas value I'm setting in my transactionObject is not translating into the RPC packet.

Example usage:
```js
var cOBJ = web3.eth.contract(ABI); 
var cInst = cOBJ.at(ADDR);
cInst.method.sendTransaction(PARAM, {from: web3.eth.accounts[0], gas: 900000});
```

The transaction sends successfully, the RPC data packet looks healthy. But the gas value, no matter what I set it to does not translate into the RPC call. It stays constant at 90000. And naturally, as I need more gas, it gives me a "TX error, out of gas!" - which is how I noticed this problem.

**Comment by kumavis** [comment]
I think the new syntax is `cInst.method(PARAM, {from: web3.eth.accounts[0], gas: 900000});`

**Comment by frozeman** [comment]
Could you provide what your web3.js send to the RPC?

You can also call web3.eth.estimateGas() before to measure, what the gas cost will be.

**Comment by frozeman** [comment]
Ok i just tested and the gas i provide is properly passed onto `eth_sendTransaction`

**Comment by SilentCicero** [comment]
@kumavis that will work out of the box for just sending transactions off of the contract object. The problem I'm having is setting the gas value when sending a method transaction off of a contract instance: so contractInstance.methodName.sendTransaction(param, options); I don't know if there was a key change, although I don't see any evidence of such currently.

@frozeman did you try sendTransaction off of a contract instance method, like the example I provided above? Or just off of the contract instance?

I will try all this again and see if I can get this to fly. Not quite sure, I'm using the latest geth, its a day old, and the method exists on my contract instance (as I see it on a console print out of the contract instance).

Also, thank you to however put the code or pre wrapper in my issue. I always forget Github issues support markdown.

Also, thank you to however put the code or pre wrapper in my issue. I always forget Github issues support markdown.

**Comment by frozeman** [comment]
Yes i did send the transaction like you did above. And i did edit you issue comment :)

**Comment by SilentCicero** [comment]
@frozeman cheers. Alright, I'll have to try again.

**Comment by SilentCicero** [comment]
@frozeman it seems to have changed to my new default and my transaction just worked. Very strange. I'll close for now.

**Comment by yxliang01** [comment]
It is very weird. I have the same problem too!
