### ISSUE TITLE
web3.eth.getBlockNumber().then(console.log) result is zero

### ISSUE THREAD

**Issue by zyq20130111** [ethereum/web3.js#2083]
my code is following:
var web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'))
web3.eth.getBlockNumber().then(console.log);

web3.eth.getBlockNumber().then(console.log)  this code show zero, but my node sync block number is 4523458  why ??

**Comment by nivida** [comment]
I've tested it, something is strange with the getBlockNumber method. 
I apologize for the troubles.

**Comment by Meabo** [comment]
Hi @zyq20130111 @nivida 

I reproduced the following steps:
- truffle console 
- let Web3 = require('web3')
- let web3 = new Web3(new Web3(YOUR_INFURA_MAINNET_ENDPOINT))
- web3.eth.getBlockNumber().then(console.log)
Output : 6806450

web3 version:  web3@1.0.0-beta.36

I think there is no issue here. Only need to upgrade your web3 version.

**Comment by nivida** [comment]
@Meabo I've tested it in the browser and it looks like a bug. Thanks for your additional information!

**Comment by Meabo** [comment]
@nivida this is still a bug ? I can't reproduce the issue. Tested it in the browser : no error.

**Comment by nivida** [comment]
Yep tested it again no error too. Sorry for the confusion.

**Comment by eyezick** [comment]
I see this issue on node.js on an Ubuntu 18.04 instance with a local geth node

**Comment by keennay** [comment]
Ok, yeah I get the same problem where I'm not seeing any output while connecting to my local IPC node. Seems @eyezick is as well, dunno if he was able to resolve it since then.

I'm on Ubuntu 18.04, Geth v1.9.0-unstable, web3. 1.0.0-beta.53

Code:

```
const Web3 = require('web3');
const net = require('net');

const web3 = new Web3(
new Web3.providers.IpcProvider('/ssd_nvme_geth/mainnet/geth.ipc', net));

web3.eth.getBlockNumber().then(console.log);
web3.eth.getBlock('latest').then(console.log);
```

Results are completely empty
