### ISSUE TITLE
web3js 1.0 Release Date

### ISSUE THREAD

**Issue by mandritac** [ethereum/web3.js#2101]
Hi,

When will web3 js 1.0 version be released officially? Currently only getting beta updates which we are unable to recommend for any customer pilot projects.

Thanks.

**Comment by nivida** [comment]
It's hard to say when exactly the 1.0 stable release will happen but I think we are close to it. 
If you would like to know more about the ongoing work then please have a look at:
to-do list: https://github.com/ethereum/web3.js/projects 
PR #2000 
https://medium.com/@samuel_91690/my-first-months-as-the-maintainer-of-web3-js-7715470b7ef7
