### ISSUE TITLE
npm install web3 installs 1.x beta instead of 0.20.x

### ISSUE THREAD

**Issue by subhasisbanik** [ethereum/web3.js#2108]
I tried installing web3js from:
npm install web3 
and found out from package.json that it installed 1.x beta.
But as I see web3js docs, it still says that 0.20.x is the main release and 1.x is beta.
Could anyone throw light into this?
![image](https://user-images.githubusercontent.com/25420904/49688188-4d62ec80-fb34-11e8-9719-64a9db0cb835.png)
![image](https://user-images.githubusercontent.com/25420904/49688209-93b84b80-fb34-11e8-9fdc-f91f7cf02533.png)

**Comment by joshstevens19** [comment]
Hey @subhasisbanik thanks for your issue, 

web3 1.0.x is currently in beta and not yet released, as its under the same package manager name in theory when you do `npm installl web3` it install the latest package which in this case is the beta web3. The latest release for web3 0.xx is here - https://www.npmjs.com/package/web3/v/0.20.7 

To install this you can do 

`npm install web3@0.20.7`

We are hoping to release a none beta version for web3 1.0.x soon 👍 Hope this helps
