### ISSUE TITLE
eth.abi.encodeParameters not encoding uint8 properly

### ISSUE THREAD

**Issue by AnAllergyToAnalogy** [ethereum/web3.js#2115]
eth.abi.encodeParameters appears to be encoding uint8's as uint256s.

`web3.eth.abi.encodeParameters(['int256','int256','uint8'], ['1','1','1']).toString();`

returns 
```
0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000
0000000000000000000000000000001
```

whereas I believe it should return 
```
0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000101
```

ie, the uint8 seems to be encoded as a uint256?

**Comment by tcrowe** [comment]
@AnAllergyToAnalogy All numbers get encoded into 256 bit.

For example your first ABI hex, if broken down into it's parts goes like this:

```
0x
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
```

For the second:

```
0x
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
01
```

The parser would not understand because it's expecting them all to come in as 256 bits long. This is just for the serialization process. It will surely be treated differently once chewed up by the EVM.

Does that help? If so please 👍🏻👎🏻 and or close. 🤗

**Comment by tcrowe** [comment]
Solidity ABI specification: https://solidity.readthedocs.io/en/latest/abi-spec.html

**Comment by AnAllergyToAnalogy** [comment]
That does make sense, thanks. I was operating under the impression that the web3.js function `web3.eth.abi.encodeParameters` was analogous to Solidity's `abi.encodePacked`, but `abi.encode` makes more sense... 😐

**Comment by tcrowe** [comment]
Underneath it uses ethers module. Supposedly it can do non-standard packed mode but I am unsure how atm. https://github.com/ethers-io/ethers.js/issues/77
