### ISSUE TITLE
Update web3-bzz dependency for tar.gz outages

### ISSUE THREAD

**Issue by paramtatv** [ethereum/web3.js#2116]
Hi,

We have found that web3-buzz npm repo depends on swarm-js@0.1.37 where as the latest stable v-0.1.39 can be used. The older verision works on tar.gz which has been deprecated. Where as the newer verisions use tar lib.
There are apparent benefits to it.

Please accept to raise PR.

Thanks

**Comment by nivida** [comment]
I apologize for the bug but this will be fixed with the version 1.0.0-beta.38. 
You can have a look at the fix here in this PR: #2000.
