### ISSUE TITLE
TypeError: BigNumber is not a constructor

### ISSUE THREAD

**Issue by isaacsultan** [ethereum/web3.js#2117]
# Usage
```
const BigNumber = web3.BigNumber;

module.exports = {
  ZERO_ADDRESS: '0x0000000000000000000000000000000000000000',
  MAX_UINT256: new BigNumber(2).pow(256).minus(1),
};
```
# Details

* Truffle v5.0.0-next.20 (core: 5.0.0-beta.2)
* Solidity v0.5.0 (solc-js)
* Node v8.9.3
* web3@1.0.0-beta.37

**Comment by mswezey23** [comment]
BigNumber is no longer bundled in Web3 since the 1.X.X release.

https://ethereum.stackexchange.com/questions/50294/typeerror-web3-is-not-a-constructor-when-trying-to-use-node-js-with-truffle-con

Use `web3.utils.BN`

**Comment by joshstevens19** [comment]
Hey thanks for the issue as @mswezey23 has stated you need to use `web3.utils.BN` -https://web3js.readthedocs.io/en/1.0/web3-utils.html#bn 

Will close it now
Thanks
