### ISSUE TITLE
Incompatible prefix Serpent and web3

### ISSUE THREAD

**Issue by Georgi87** [ethereum/web3.js#214]
For some reason serpent (latest) and web3 (latest) calculate different prefixes for function names.

Some examples:
```
web3: serpent
'0xa598cea1': '0xbae156b7',  # get_market_hashes(int256)
'0x69a074aa': '0x5ae33b80',  # create_market(int256,int256,int256,int256,int256,int256,int256,int256,int256)
'0x35ba47f8': '0xfafa69c2',  # get_market(int256)
```

Not sure if this is an serpent or web3.js issue.

**Comment by kumavis** [comment]
@Georgi87 'latest' as in latest master, latest develop, lastest npm, lastest bower?
There was a change in the way hashes were handled recently

**Comment by kumavis** [comment]
this is where you'd want to stop and check inputs
https://github.com/ethereum/web3.js/blob/16861fc1944cca721672bb8faa81909d69be2b99/dist/web3.js#L2153

my guess is that '0x' is being included in one of the inputs instead of being stripped

**Comment by Georgi87** [comment]
Thanks, I will check this. Using latest develop for both, serpent and web3.

**Comment by kumavis** [comment]
@Georgi87 also when checking inputs check all:
```js
this._name
web3.fromAscii(this._name)
web3.sha3(web3.fromAscii(this._name))
web3.sha3(web3.fromAscii(this._name)).slice(2)
```

**Comment by Georgi87** [comment]
The commit you are reffering to is not in the develop branch.
Should I use BlockFilterProposal instead?

Develop:
```
return sha3(this._name).slice(0, 8);
```

BlockFilterProposal:
```
return web3.sha3(web3.fromAscii(this._name)).slice(2, 10);
```
The code you reffered to was for events not functions.

**Comment by kumavis** [comment]
whoops.. we'll you're looking at the right spot now.

newer `return sha3(this._name).slice(0, 8);`
older: `return web3.sha3(web3.fromAscii(this._name)).slice(2, 10);`

**Comment by Georgi87** [comment]
I just checked all:

```
get_market_hashes(int256)
a598cea1 // web3.sha3(web3.fromAscii(this._name)).slice(2, 10);
0xbae156 // sha3(this._name).slice(0, 8); // latest develop
0xbae156b7 // serpent
```
Seems like just the slice operation is wrong either in serpent or in web3.

**Comment by Georgi87** [comment]
Maybe because of adding the 0x they forgot to increase the slice size?

**Comment by kumavis** [comment]
@Georgi87 theres the bug. Seems like they expected sha3 to not return the prefix... can you tell is it doing sha3 via rpc or in js?

**Comment by Georgi87** [comment]
Via RPC.

**Comment by Georgi87** [comment]
Sorry I just did a mistake, using the wrong RPC. I checked now with the go client and got:

```
get_market_hashes(int256)
bae156b7 // web3.sha3(web3.fromAscii(this._name)).slice(2, 10)
0xc5d246 // web3.sha3(this._name).slice(0, 8)
0xbae156b7 // serpent
```

**Comment by kumavis** [comment]
heres where it was moved to the browser
https://github.com/ethereum/web3.js/pull/205

**Comment by kumavis** [comment]
not `web3.sha3(this._name).slice(0, 8)`
but `sha3(this._name).slice(0, 8)`

**Comment by Georgi87** [comment]
Ok, sorry my bad I had still something outdated. It works now. Thanks for your help.
