### ISSUE TITLE
Method call broken after geth upgrade (1.7->1.8)

### ISSUE THREAD

**Issue by alicerocheman** [ethereum/web3.js#2140]
Hi there,
We can't seem to find our way out of this, so here's my call for help.

**Web3.js version** : 1.0.0-beta.37 and 1.0.0-beta.36
**GETH version**: 1.8.12
**provider type**:  remote, websocket

Issue appears only if GETH is upgraded from 1.7 to 1.8
When tested locally via the node's console, the issue does not present.

#### Method call
```javascript
getThat = () => {
  const myContractName = new this.web3.eth.Contract(SC.abi, SC.address, {
    from: this.myAccount.address,
    gas: 1000000
  });
  myContractName.methods
    .myMethod()
    .call()
    .then(r => {
      console.log("getThat succeeded", r);
    })
    .catch(e=>{
      console.log("getThat failed", e);
    });
};
```

####Expected results (aka with geth 1.7, or locally on the node)
```
getThat succeeded, [...]
```

####Actual results (with geth 1.8)
```
getThat failed Error: Returned values aren't valid, did it run Out of Gas?
```

In the logs on the Node, we get an Out of gas error.

#### Method details
Other methods on the same smart contract work well.

The method that fails calls several other contracts' methods to gather data, which is then concatenated and returned as a string.

A different method that calls another contract's method works fine...

There seems to be a problem with the functions imported from [Solidity Util](https://github.com/willitscale/solidity-util) that are used in the smart contract's problematic method.

The method is supposed to concat an array of objects as a JSON string.

The method call works if it is set to return a static JSON string of several objects.

The method call works if it only results in 1 object in the array. But the loop with concat and stringify functions fails if it goes around more than once... 

here's the solidity code
```
pragma solidity ^0.4.2;
[...]
function myMethod() public view returns(string)
	{
		string memory list;
		nodeReference n;
		
		list = '[';
		for (uint i=0;i < nodes.length; i++)
		{
		    if (i > 0) { list = list.concat(','); }
		    list = list.concat("{");
		    n = nodeReference(nodes[i]);
		    bytes32 a = n.getNodeNameB();
		    string memory m = bytes32tostr(a);
		    bytes32 l = n.getNodeKeyBL();
		    string memory y = bytes32tostr(l);
		    bytes32 r = n.getNodeKeyBR();
		    string memory z = bytes32tostr(r);
		    list = list.concat('"name":"').concat(m).concat('"');
			list = list.concat(',"id":"').concat(uint2str(n.getNodeID())).concat('"');
			list = list.concat(',"status":"').concat(uint2str(n.getNodeStatus())).concat('"');
			list = list.concat(',"consortium":"').concat(uint2str(n.isConsortiumMember())).concat('"');
			list = list.concat(',"pubkey":"').concat(y);
			list = list.concat(z).concat('"');
			list = list.concat("}");
		}
		list = list.concat(']');
		return(list);
	}
[...]
```

An issue was opened on the external library's github.

We have no idea why this fails only via Web3js remote connection, while it works normally when executed directly on the node.

**Comment by chankruze** [comment]
Make sure 'contract address' is correct. I am afraid that this is maybe due to https://github.com/ethereum/web3.js/issues/1916.

**Comment by nivida** [comment]
This got fixed with PR https://github.com/ethereum/web3.js/pull/2608 and will be released asap.
