### ISSUE TITLE
TypeError when supplying the wrong event name to getPastEvents

### ISSUE THREAD

**Issue by wjmelements** [ethereum/web3.js#2142]
```
......../node_modules/web3-eth-contract/src/index.js:540
        throw new Error('Event "' + event.name + '" doesn\'t exist in this contract.');
                                          ^

TypeError: Cannot read property 'name' of undefined
```
`event` is undefined, which throws an error.
To reproduce, supply the wrong event name to `getPastEvents` in web3.eth.Contract.

I am using web3 version 1.0.0-beta.31.

**Comment by nivida** [comment]
Could you test it also in beta.37? But it should be definitely solved on version beta.38 because of the ongoing refactoring. (PR #2000)

**Comment by wjmelements** [comment]
I have reproduced the issue on `1.0.0-beta.37`

**Comment by nivida** [comment]
Sorry for the confusion this fix will get released in beta.38.

**Comment by nivida** [comment]
This got fixed in the beta.38 release. Because of this, I will close this issue.
