### ISSUE TITLE
TypeError: Cannot access member 'unlockAccount' of undefined

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/web3.js#2150]
Hi,

I'm using Geth 1.8.18 light client which comes with web3js 1.0.
I got this error:

```
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.18-stable-58632d44/darwin-amd64/go1.11.2
 modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> web3.eth.personal
undefined

> web3.eth.personal.unlockAccount()
TypeError: Cannot access member 'unlockAccount' of undefined
    at <anonymous>:1:1
```

I think I know what's the issue. The `unlockAccount` method is available inside `web3.personal` and not in `web3.eth.personal`.

I've forked this repo but I'm not sure how to get started contributing to this documentation. Couldn't find any information on how to contribute to docs section.

Any pointers for me?

Thanks.

**Comment by Flash-Git** [comment]
On the top right of each page there's a link to the file on github. Fork the repo, make the fix you think is appropriate and then make the pull request. There isn't much red tape to follow for simple fixes(assuming you're correct).

**Comment by nivida** [comment]
The Geth Javascript Console is using v0.20.x of the web3.js lib and is extending the object with methods. Please have a look at the Geth Javascript Console documentation and report further issues regarding the console in the go-ethereum repository.

**Comment by EnchanterIO** [comment]
For clarity and other people, here is the **0.20.x** syntax:

```
web3.personal.unlockAccount(from, pwd, timeinseconds)
```
