### ISSUE TITLE
Error: Failed to check for transaction receipt:

### ISSUE THREAD

**Issue by dk-lan** [ethereum/web3.js#2152]
```javascript
console.time('transactionHash')
    console.time('receipt')
    console.time('error')
    web3.eth.sendSignedTransaction(serializedTx).once('receipt', (r) => {
        console.log('receipt')
        console.timeEnd('receipt')
        console.log(`address => ${_dispatcher.address} nonce => ${_nonce}`)
        console.log('================================================')
    }).once('transactionHash', (r) => {
        console.log('transactionHash')
        console.timeEnd('transactionHash')
        console.log(`address => ${_dispatcher.address} nonce => ${_nonce}`)
        console.log('txhash')
        console.log(r);
        console.log('================================================')
        resolve(r);
    }).once('error', (r) => {
        console.log('error');
        console.timeEnd('error')
        console.log(`address => ${_dispatcher.address} nonce => ${_nonce}`)
        console.log('================================================')
        console.log(r)
    })
})```

receipt
receipt: 16611.903ms
address => *** nonce => 70
================================================
error
error: 43979.945ms
address =>  ***  nonce => 89
================================================
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/node_modules/web3-utils/src/index.js:56:17)
    at node_modules/web3-core-method/src/index.js:261:23
    at <anonymous>
receipt
address => *** nonce => 71
================================================

**Comment by dk-lan** [comment]
Too many requests in a short time can cause this problem

**Comment by alvin854** [comment]
@dk-lan I seem to be having this issue with too many requests in a short time as well. If you remember, can you elaborate on why this causes a problem? I'd prefer this method (and getting access to the returned `PromiEvent` on each transaction) than using a `BatchRequest` with no `PromiEvent`.

**Comment by Conviley** [comment]
@chicobermuda I also have this problem. Have you managed to overcome this? If so, could you shed some light on this? Thanks!

**UPDATE** I found my problem. I use Infura and i am getting rate limited

**Comment by vkhymenko** [comment]
Having same kind of a problem. Also using Infura as a provider and getting rate limited. There's some interesting statistics regarding requests: 99.74% of all the requests is this one - `eth_getBlockByNumber` . I'm sure I do not call the method anywhere in my code, so web3 (`eth_getTransactionReceipt` in particular) calls it internally so many times that it became a problem real fast. Is there a way to optimize it somehow?

**Comment by Conviley** [comment]
@the-inevitable My suggestion is that you start looking at setting up your own local client. Ultimately that is what me and my partner did. Sure it's not without friction to do it, but when you have it up and running it's really nice to know that you're free of various limits and restrictions. We set up our own node using geth

**Comment by PabloPerezAguilo** [comment]
> Having same kind of a problem. Also using Infura as a provider and getting rate limited. There's some interesting statistics regarding requests: 99.74% of all the requests is this one - `eth_getBlockByNumber` . I'm sure I do not call the method anywhere in my code, so web3 (`eth_getTransactionReceipt` in particular) calls it internally so many times that it became a problem real fast. Is there a way to optimize it somehow?

I had the same problem with this code:

```javascript
web3.eth.sendSignedTransaction(signedTx)
                .once('confirmation', (confirmationNumber, receipt) => {
                    console.log('Transaction mined:', receipt.transactionHash);
                })
                .on('error', error => console.error(error));
```
It was making polling with `eth_getTransactionReceipt` and never ends. Because of this reason I got the rate limit error from Rinkeby.

![image](https://user-images.githubusercontent.com/9373112/91638266-55e90e00-ea0e-11ea-980a-246568d2ea61.png)

I fixed it using the returned promise instead the events:

```javascript
const res = await web3.eth.sendSignedTransaction(serializedTx);

console.log(res);

/*
 {
  transactionHash: '0x9....25',
  transactionIndex: 0,
  blockHash: '0x053......84',
  blockNumber: 3XX,
  from: '0x9.......c1',
  to: '0x2.b',....
  gasUsed: 7XX1,
  cumulativeGasUsed: 7XX1,
  ....
}
*/

```

In other way, you can optimize with web socket connection instead api rest:

```javascript
const web3 = new Web3(new Web3.providers.WebsocketProvider(endpoint));
```
