### ISSUE TITLE
Ubuntu 16.04 npm install fails with error code: 128

### ISSUE THREAD

**Issue by asmodat** [ethereum/web3.js#2153]
Fails on ubuntu 16.04

Initially had issue, that git was not installed in /usr/bin/git, so I added a simlink using this command:

ln -s /usr/bin/git /bin/git

Which fixed the issue of this npm awful package not being able to find git where it was looking for it, but I am still getting the following error, what is going on ?

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128

Note: I can't install this package globally, because I don't want to to use sudo!

git config --global url.https://github.com/.insteadOf git://github.com/

Does not helped either.

**Comment by Flash-Git** [comment]
What command are you using? I'm not sure what you're trying to do.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
