### ISSUE TITLE
Contract Encryption and Decryption

### ISSUE THREAD

**Issue by nxycdl** [ethereum/web3.js#2154]
I have a Contract 
```
contract Test10 {	
	function getData(bytes32 _key,uint keycode) public view returns(string) {
	   //when i want get my data , i want decode('abcdef') = '1234'
	   return decode('abcdef')

	}
	function setData(bytes32 _key, string extend)  public {
	  //when i setData(_key,'1234'); I want encode('1234') = 'abcdef' then save to blockChain 
	  mysaveMethod(_key, 'abcdef')	
	  emit xxxx;
	}
}
```
when i setData('myunkey','1234'); 
I want encode('1234') = 'abcdef' 
then save to blockChain

when i want get my data , i want decode('abcdef') = '1234'
Is there any way to do that?
Thanks

**Comment by Flash-Git** [comment]
Anyone could look at the transaction and read the unencrypted data regardless of what your contract does to it, same goes for decryption. You'll want to encrypt data before you send it to the contract and then decrypt it later.

**Comment by nxycdl** [comment]
@Flash-Git thanks. contract  is public, so every could look at ，it need Centralization programe to encrypt 
 and decrypt 。 thanks very much。
