### ISSUE TITLE
Does web3.js support deterministic account generation?

### ISSUE THREAD

**Issue by smartcontracts** [ethereum/web3.js#2156]
As per the [web3.js docs](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#create), a user can create a new public/private keypair via:

```
web3.eth.accounts.create([entropy]);
```

I thought the `entropy` parameter might act as a deterministic seed, but it instead acts as a

> A random string to increase entropy

(as per the documentation).

I'm trying to generate accounts with a specific seed for testing purposes. I know that a few other libraries, like [eth-lightwallet](https://github.com/ConsenSys/eth-lightwallet) and [ethers](https://github.com/ethers-io/ethers.js/) support this, but I can't figure out if web3 does.

**Comment by Flash-Git** [comment]
By seed, do you mean private key? You can generate accounts with private keys with `web3.eth.accounts.privateKeyToAccount(privateKey);` as per [this](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html?highlight=private%20key#privatekeytoaccount).

**Comment by smartcontracts** [comment]
Oh yeah, I guess `web3.eth.accounts.privateKeyToAccounts` can handle arbitrary private keys, as long as it's hex. Thank you!
