### ISSUE TITLE
web3.utils.toBN fails when passing scientific notation 

### ISSUE THREAD

**Issue by rbndg** [ethereum/web3.js#2157]
`web3.utils.toBN(1.0194e+21)`

`Error: Error: [number-to-bn] while converting number 1.0194e+21 to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "1.0194e+21"`

Why does Web3 use bn.js instead of BigNumber.js?

**Comment by askucher** [comment]
I think you need to pass Number as String in case of big numbers

**Comment by dev1644** [comment]
Yes, To avoid imprecision or inaccuracy the large value needs to be passed either as String or As BigNumber.
Web3 uses this https://github.com/frozeman/bignumber.js-nolookahead

**Comment by smalaichami** [comment]
This worked for me.. in "web3": "1.0.0-beta.35"  
let value = web3Local.utils.toWei(amount, 'ether')

**Comment by jjhesk** [comment]
can someone explain to me what happen to this conversion? https://github.com/MikeMcl/bignumber.js/issues/305
