### ISSUE TITLE
Don't auto transform bytes(X) to string and introduce string as a new type for solidity contracts

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#216]
Currently bytes sometimes get decoded wrong, which make it impossible to use bytes as non-strings, because you can't reliable encode them back to bytes.

```js
web3.toAscii('731a3afc00d1b1e3461b955e53fc866dcf303b3eb9f4c16f89e388930f48134b')
"s:ü"

web3.toAscii('731a3afc')
"s:ü"
```

Instead we need to re-introduce the `string` type in solidity and only decode this one to strings and keep bytes as is: https://www.pivotaltracker.com/n/projects/1189488/stories/95173586

**Comment by ethers** [comment]
related to #218
