### ISSUE TITLE
Returned error: The method net_listening does not exist/is not available

### ISSUE THREAD

**Issue by gnorbsl** [ethereum/web3.js#2160]
Hi,

I'm trying to figure out how to know if web3js is successfully connected to the node.

I assumed that would work with `web3.eth.net.isListening().then(console.log('listening'))`.
This doesn't seem to be the case though, I get this error:
`Returned error: The method net_listening does not exist/is not available`

Full code that should work:

```const Web3 = require('web3');
if (typeof web3 !== 'undefined') {
    web3 = new Web3(web3.currentProvider);
} else {
    const wsProvider = new Web3.providers.WebsocketProvider('ws://' + process.env.nodeHost + ':' + process.env.nodePort, {
        headers: {
            Origin: process.env.nodeApiKey
        }
    });
    web3 = new Web3(wsProvider);

    web3.eth.net.isListening().then(console.log('listening'));

}

**Comment by Flash-Git** [comment]
I'm not sure that `web3.eth.net` is exposed by default, you might have to run your node with a command that changes this. 

As a work around, in the past I have used something like this to check whether I am connected to my node:
```
web3.eth.getNodeInfo(
  function(error, data) {
    if(!error){
      console.log("Successful connection to Geth Node");
    }else{
      console.log("No connection to Geth Node");
    }
  }
);
```

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
