### ISSUE TITLE
error: rlp: input string too short for common.Address, decoding into (types.Transaction)(types.txdata).Recipient

### ISSUE THREAD

**Issue by dk-lan** [ethereum/web3.js#2161]
```javascript
    let web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:8545"));
    let pkey = '****';
    let privateKey = Buffer.from(pkey, 'hex');  
    let gaspriceWei = web3.utils.toWei('9', 'Gwei'); 
    let amountWie = web3.utils.toWei('100', 'ether'); 
    let amountBn = new web3.utils.BN(amountWie);      
    let from = '****';
    let to = '****'
    _nonce =  await web3.eth.getTransactionCount(from);
    let rawTransaction = {
        "from": from,
        "nonce": web3.utils.numberToHex(_nonce),
        "gasPrice": web3.utils.numberToHex(gaspriceWei),
        "gasLimit": web3.utils.numberToHex('182000'),
        "to": to,
        "value": amountBn,
        "data": '',
    };  

    let tx = new Tx(rawTransaction);
    tx.sign(privateKey);
    let serializedTx = '0x' + tx.serialize().toString('hex');
    web3.eth.sendSignedTransaction(serializedTx).on('receipt', (r) => {
        console.log('receipt')
    }).on('error', (r) => {
        console.log('error');
        console.log(r)
    })
```

then get error
Error: Returned error: rlp: input string too short for common.Address, decoding into (types.Transaction)(types.txdata).Recipient

how to fixed this issue

**Comment by Flash-Git** [comment]
Are you sure that the addresses you're using are all correct? You can check them with `web3.utils.isAddress(address)`.

**Comment by dk-lan** [comment]
> Are you sure that the addresses you're using are all correct? You can check them with `web3.utils.isAddress(address)`.

I sure the address are all correct, I have try the code on https://mainnet.infura.io and it no problem

**Comment by Flash-Git** [comment]
There used to be a bug where if an address started with `0x00`, it could cause a similar error but I thought that was fixed. Does this describe any of the ones you're using?

**Comment by dk-lan** [comment]
> There used to be a bug where if an address started with `0x00`, it could cause a similar error but I thought that was fixed. Does this describe any of the ones you're using?

tq for you reply, but the address format isn't  started with `0x00`

**Comment by dev1644** [comment]
So the same code is working from Infura API but doesn't work from Geth?

**Comment by dk-lan** [comment]
> So the same code is working from Infura API but doesn't work from Geth?

yes, my go-ethereum version is 1.7.2

**Comment by dk-lan** [comment]
the complete error like this
``` javascript
ALERT: [ethjs-rpc] rpc error with payload {"id":2118911378748,"jsonrpc":"2.0","params":["0xf86d8085400746fe008252089423b38117071c6b4e82483611e13667bcac7fa9ef89056bc75e2d63100000801ca04b81bd5b36ac8fd5485ebbddb8b9572c9db0d7366b72e5fd7f99093a2df91695a07ee248057f18ef2f1735ef07cb3096752af2d071c57c4c074464e57a7f786c55"],"method":"eth_sendRawTransaction"} Error: rlp: input string too short for common.Address, decoding into (types.Transaction)(types.txdata).Recipient
```
rlpdump -hex params like this
```java
[
  "",
  400746fe00,
  5208,
  23b38117071c6b4e82483611e13667bcac7fa9ef,
  056bc75e2d63100000,
  "",
  1c,
  4b81bd5b36ac8fd5485ebbddb8b9572c9db0d7366b72e5fd7f99093a2df91695,
  7ee248057f18ef2f1735ef07cb3096752af2d071c57c4c074464e57a7f786c55,
]
```
geth version: 1.7.4-stable
Go Version: go1.11.4

by the way, I use metamask to transfer and get the same error too

**Comment by dk-lan** [comment]
the issue already fixed by myself, tq all

**Comment by dev1644** [comment]
So What was the issue? I had tried your code with both Infura and Geth and it was working.

**Comment by React-Vishnu** [comment]
> the issue already fixed by myself, tq all

how did you fixed it? i am facing the same. can you help me to solve it?

**Comment by pepihasenfuss** [comment]
The "data": ''  statement is not working. Geth wants data or any input to be at least '0x', it will not accept empty strings or null objects. Also, if you are deploying a contract, it wants to: to be

 to: '0x'

The error codes coming back from tx.sign or/and sendSignedTransaction may be a bit confusing, as far as I think, but if it is data: '' and it expects data: '0x' then it may make sense in a way.
address: and to: expect hex values, I use isAdress() to check this in advance.
In general, I`ve tried to check as many format requirements in advance as possible.
Hope this may help someone here....
