### ISSUE TITLE
The web3js documentation /en/latest/ is empty

### ISSUE THREAD

**Issue by Flash-Git** [ethereum/web3.js#2164]
https://web3js.readthedocs.io/en/latest/ is empty yet continues to show up in search engines and in the docs' navigation bar under "Versions". It also happens to be what you get redirected to when you go to https://web3js.readthedocs.io.

The "Edit on GitHub" button links to https://github.com/ethereum/web3.js/blob/master/index.rst which doesn't exist.

**Comment by Flash-Git** [comment]
This also applies to https://web3js.readthedocs.io/en/master/, shouldn't these redirect to https://web3js.readthedocs.io/en/1.0/?

**Comment by levino** [comment]
Not important for 1.0 release.

**Comment by nivida** [comment]
This can be fixed because I will configure readthedocs when the stable release happens. It's just a thing of some minutes. :)

**Comment by wbt** [comment]
There are many links to `https://web3js.readthedocs.io/en/1.0/<subpage#anchor>`, now returning 404s.  Is there some configuration that can be done to automatically redirect to `https://web3js.readthedocs.io/en/v1.2.0/<subpage#anchor>`?

**Comment by nivida** [comment]
I've added the required redirects in the ``readthedocs`` settings.
