### ISSUE TITLE
Cannot get token contract *name, decimals and symbol*

### ISSUE THREAD

**Issue by yongloon** [ethereum/web3.js#2166]
Hi... I am using Web3 1.0 beta.37, I am not able to get the token name, decimals, and symbol by providing contract address and ABI.

```
var tokenContract = new web3.eth.Contract(contractABI, contractAddress);
var tokenName = tokenContract.methods.name().call().then(function(result) {
			
	return result;
});

console.log('tokenName: ' + tokenName);
```

**Comment by keennay** [comment]
Hey @nyl9488, how did you figure this one out?

**Comment by jorgeserranodev** [comment]
Use await to get the result object:

`var tokenN = await tokenName;`

**Comment by Gribesh** [comment]
Sometimes we might use account address instead of contract address. 
If its correct then that function would return promise, you might need to handle the promise.

**Comment by ubuntutest** [comment]
well, thats working for BSC contract address, but not for ethereum contract address, someone know how to fix it?
also something is deprecated here

**Comment by MarcoFr83** [comment]
Working for me on eth (with web3js.min.js, 1.3.6) : 
`const getTokenName= async () => {
              let MyContract = new web3.eth.Contract(contractABI,contractAddress);
                await MyContract.methods.name().call()
                  .then(function(res) {
                    tokenName = res;
                  })
                  tokenSymbol = await MyContract.methods.symbol().call();
                  console.log(tokenName + "(" + tokenSymbol +")" ) ;
              }   ``
