### ISSUE TITLE
Constantinopole hardfork compability

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2169]
Hello,

would the upcoming constantinople hardfork affect the implementation of web.js? The way transaction is formed and signed.

From what I've read only eip1234 has compatibility problems. So it won't affect the library

But I must be certain about that.

Thank you

**Comment by dev1644** [comment]
I don't think Constantinople hard-fork will affect this library in any way. AFAIK

**Comment by ghost** [comment]
Yes, seems like that.
