### ISSUE TITLE
[web3-eth-abi] Update ethers to v4.0.20

### ISSUE THREAD

**Issue by filips123** [ethereum/web3.js#2172]
Package `ethers (v4.0.0-beta.1)` gets installed as a dependency of `web3-eth-abi (v1.0.0-beta.37)`, which leads to the `xmlhttprequest` complaint and basically makes `truffle-contract` and other packages unusable.
This could probably be fixed with updating `ethers` to `v4.0.20`.

See trufflesuite/truffle#1614 and trufflesuite/truffle#1617.

**Comment by nivida** [comment]
Hay @filips123, Just fixed this in the PR #2000. Thanks!

**Comment by filips123** [comment]
When will it be merged and released?

**Comment by nivida** [comment]
In the next 2-3 weeks, I'm currently testing anything against Geth and Parity.

**Comment by filips123** [comment]
I will probably need this fix before that. Is it possible to merge and release it faster in different PR?

**Comment by filips123** [comment]
@nivida Actually, `ethers` was recently updated to `4.0.21` so it is a bit outdated. Why not require it with `^4.0.0` or something like this so it will be always updated?

**Comment by nicolashardy** [comment]
I have the same issue, making my app unbuildable

![capture d ecran 2019-01-17 a 10 51 22](https://user-images.githubusercontent.com/1556911/51310116-39b97880-1a46-11e9-956b-b65605001a97.png)

workaround : `yarn add ethers@latest`

**Comment by nivida** [comment]
Closed it because of: https://github.com/ethereum/web3.js/pull/2000#issuecomment-455178856
