### ISSUE TITLE
Incorrect description of function send's return-value

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#2174]
From https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id22:

> ... if this `send()` is called from a `someContract.deploy()`, then the promise will resolve with the new contract instance.

The resolved return-value is an object with a `contractAddress` field, which stores the address of the deployed contract. However, it is not equivalent to a `web3.eth.Contract` instance.

So for example, given the following:
```
let contract = new web3.eth.Contract(abi);
let handle = await contract.deploy(...).send(...);
```
If one wants an instance of the new contract, then they need to create it explicitly:
```
let newContract = new web3.eth.Contract(abi, handle.contractAddress);
```

**Comment by nivida** [comment]
This is already fixed in the PR #2000. Thanks :-)

**Comment by dev1644** [comment]
Is it fixed? I can still see the misprinting on the docs.

**Comment by nivida** [comment]
@dev1644 ```contract.deploy(...).send(...)``` will return a Contract object in version 1.0.0-beta.38. (PR #2000)
