### ISSUE TITLE
hexToNumberString sometimes interprets string as decimal

### ISSUE THREAD

**Issue by wjmelements** [ethereum/web3.js#2184]
```
> web3.utils.hexToNumberString('13')
'13'
```

**Comment by levino** [comment]
Thank you for this issue. Please link to the subpage in the docs where the expected behaviour is documented.

**Comment by levino** [comment]
https://web3js.readthedocs.io/en/1.0/web3-utils.html?highlight=hexToNumberString#hextonumberstring

**Comment by levino** [comment]
When I read the docs it looks to me as if a hex-string must be prefixed with `0x`, right? What is the expected behaviour from the documentation? So the issue should rephrased to:

Throw error when argument of `hexToNumberString` is not prefixed with `0x`.

**Comment by levino** [comment]
This should be made ready for dev and then go directly to "To Do" as a bug.
