### ISSUE TITLE
Issue installing web3 on new ubuntu desktop

### ISSUE THREAD

**Issue by pranavdaa** [ethereum/web3.js#2185]
initially stuck for a long time on this-
![image](https://user-images.githubusercontent.com/38764142/51086069-d094e500-1767-11e9-9020-3da219370534.png)

Later error-
![image](https://user-images.githubusercontent.com/38764142/51086075-eb675980-1767-11e9-9698-4d5dcc57b140.png)

**Comment by dev1644** [comment]
Do a `npm cache verify` and try again.

**Comment by nivida** [comment]
Closed due to inactivity.
