### ISSUE TITLE
web3.eth.getPastLogs

### ISSUE THREAD

**Issue by CChiaki** [ethereum/web3.js#2187]
getPastLogs match address  distinguish case from case;
`
web3.eth.getPastLogs({
									fromBlock: "7062678"

									toBlock: "7062680",

									address: "0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208",

									topics: []

								}).then(res => {

									printLog(res.length + '--------11111')

									console.log(res);

								});`

0x919C13C9fBf684F73f6E425FB08531CF7A558b10
0x9060C5394c068697f5BdCc4201CF7AC9F102ba69
0x04d104B73eC7660CAc00b012C1d5101AAa0182C3
0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208  // macth
0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208 // macth
0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208  // macth
0x1D71B7f5091B000F9aB79dFCdA166eCb7525B7b0
0x953e22945b416730bAD05009aF05B420e598E412
0xF3d7FbcBF4E38c83cdb463F322Aa4eC0A3e7F6a7
0x0413928De8ae06605f93e9A0CBA966A0F3DaFe05
0xA7dA87221D770D2d51555B492868c3d232FF71e2
0xeFC6e2790286121983726a9c9e29e257605aCf14
0x15f3DE2156F4a246A222B796cA34FfC4a07eB734
0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208
0x4A8aC7238357A259C6e1D9F891fab645E65fA726
0xb180870DE672527207d7395fc4793dEaf8a99e4a

0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208   my contact

**Comment by nivida** [comment]
Could you reformat your example and probably explain it better? Otherwise, it will be hard to help you. :)

**Comment by nivida** [comment]
Closed due to inactivity of the creator.
