### ISSUE TITLE
parity: web3.eth.personal.unlockAccount: integer to hex conversion not working?

### ISSUE THREAD

**Issue by derdrdirk** [ethereum/web3.js#2189]
I am having problems to unlock my account with a parity node. It seems like that the integer I am passing in ` web3.eth.personal.unlockAccount('...', '...', 10000)` is not converted to a hex and send to the parity endpoint. I am having no problems with *geth* but this[Parity issue](https://github.com/paritytech/parity-ethereum/issues/4380) send me over here. 

Could somebody confirm that this is not a problem with web3?

The error message I received is:
> UnhandledPromiseRejectionWarning: Error: Returned error: Invalid params: invalid type: integer `10000`, expected a 0x-prefixed, hex-encoded number of length 32.

**Comment by nivida** [comment]
That's true there is a missing mapping for the duration property of the unlockAccount method. Thanks for submitting this issue. I will add this fix as soon as possible.

**Comment by indigoram89old** [comment]
I have the same problem

**Comment by nivida** [comment]
I've checked it and web3.js can't handle this in a clean way because ``parity`` will have the number as hex string and ``geth`` as number. 
The only solution would be to create a ``web3.eth.personal.parityUnlockAccount()`` method until ``parity`` or ``geth`` has changed it. I will open an issue in the ``geth`` and parity repository for syncing this.

**Comment by gnorbsl** [comment]
So how do we unlock accounts now with parity?

EDIT: If anyone stumbles over the same problem, just use null as the duration parameter.

**Comment by skinderis** [comment]
Having the same issue, how do you solve it? Dont want my address to be decrypted for 300 seconds...

**Comment by skinderis** [comment]
> So how do we unlock accounts now with parity?
> 
> EDIT: If anyone stumbles over the same problem, just use null as the duration parameter.

It doesn't solve the problem, the account stays decrypted for 300 seconds.

**Comment by skinderis** [comment]
@nivida is there any progress regarding the issue? as I see it was closed.
