### ISSUE TITLE
Ens code is not included in Git repo

### ISSUE THREAD

**Issue by kevinsimper** [ethereum/web3.js#2191]
You can't find the code to the ENS and the package `web3-eth-ens` https://www.npmjs.com/package/web3-eth-ens leads to this repo, but the code is not to be found.

The sourcecode can be found in the assets in the packages that @nivida provided, but there is no sha's to compare the content to.

@nivida Can you help where I can find the sourcecode in git? :)

**Comment by nivida** [comment]
This is the ENS module of the current 1.0 version:
https://github.com/ethereum/web3.js/tree/1.0/packages/web3-eth-ens

And this is the ENS module of the coming 1.0.0-beta.38:
https://github.com/ethereum/web3.js/tree/ethereumProvider/packages/web3-eth-ens

**Comment by filips123** [comment]
@nivida Will ENS be available at `web3.eth.ens` when using Web3 from CDN? What about installing from NPM? Will it be required to separately install `web3-eth-ens`?
