### ISSUE TITLE
HTTP authentication isn't working as documented

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2195]
I had several problems as I tried to connect to my node using web3 with HTTP authentication.

This is not working at all (currently in the documentation):
`new web3.providers.HttpProvider('http://' + BasicAuthUsername + ':' + BasicAuthPassword + '@localhost:8545');`

In an older branch I found this:
`new web3.providers.HttpProvider('http://host.url', 0, BasicAuthUsername, BasicAuthPassword);`

Unfortunately this was also not working. By looking at the code I finally figured out there is an array for the headers missing. So this is how to call the provider correct:
`new web3.providers.HttpProvider('https://domain', 0, "user", "pw", []);`

After this I had the next problem. In line `4318` is the object Buffer missing, which is calculating the base64 value of `user:pw`. I couldn't solve this problem by including `bower install buffer` (what is also not to find in the dependencies of `web3`). After replacing this line with a static value (what is good enough for my use case) it's finally working.

**Comment by nivida** [comment]
You can define the headers over the options of the HttpProvider: 

``
new web3.providers.HttpProvider('https://domain', {headers: []});
``

Available options:
``` javascript 
interface HttpHeader {
    name: string;
    value: string;
}

interface HttpProviderOptions {
    host?: string;
    timeout?: number;
    headers?: HttpHeader[];
    withCredentials?: boolean;
}
```
