### ISSUE TITLE
getAccounts returns undefined

### ISSUE THREAD

**Issue by sarbogast** [ethereum/web3.js#2196]
I'm using web3 1.0 beta 37 inside a simple javascript app in Chrome with Metamask 5.3.0 to try and obtain the account Metamask is connected to, which is a Ganache account behind the scenes. Here is the code:

```
if (window.ethereum) {
        // Modern dapp browsers...
        window.web3 = new Web3(ethereum);
        try {
            // Request account access if needed
            await ethereum.enable();

            const accounts = await web3.eth.getAccounts();
            App.account = accounts[0]; //This line crashes the script because accounts is undefined
        } catch (error) {
            // User denied account access...
            console.error("Unable to retrieve your accounts! You have to approve this application on Metamask.");
        }
    } else if (window.web3) {
        // Legacy dapp browsers...
        window.web3 = new Web3(web3.currentProvider || "ws://localhost:8545");

        App.displayAccountInfo();
        return App.initContract();
    } else {
        // Non-dapp browsers...
        console.log("Non-Ethereum browser detected. You should consider trying MetaMask!");
    }
```

The line after web3.eth.getAccounts() crashes because accounts is undefined.
I don't know if it's Ganache's fault, Metamask's fault or a problem with web3.

**Comment by sarbogast** [comment]
Actually, I think I was able to eliminate Ganache as the culprit, because when I call the same function from a Truffle console, Ganache returns the 10 accounts it knows about. So it's either Metamask or web3.

**Comment by sarbogast** [comment]
After verification, my web3 object was in version 0.20.3 of the Web3 library instead of being in version 1.0 beta 37

**Comment by DavidFransch** [comment]
I'm having the same problem where I can access the accounts from Truffle console using 
const accounts = await web3.eth.getAccounts(). 

I use the exact same line in my JavaScript code, but the account is undefined.
My web3 object is version "1.0.0-beta.46".
