### ISSUE TITLE
Unable to catch exception thrown by method call

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2198]
Hello,

For few days I was trying to catch an exception thrown by method call and come to conclusion that that's probably impossible because of the way how PromiEvent works.

https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-promievent/src/index.js#L35

Here is what I've originally was trying:
```
try {
   // I'm deliberately missing gas option here
   const data = await contract.methods.myMethod().send({ from: account, gasPrice });
} catch (e) {
    // We will never get here
    console.log(e);
}
```

Here is basic implementation of the problem:
```
const getEmitter = () => {
    let resolve, reject;
    const eventEmitter = new Promise(function() {
        resolve = arguments[0];
        reject = arguments[1];
    });

    return { eventEmitter, resolve, reject };
};

(async () => {
    try {
        const { eventEmitter, resolve, reject } = await getEmitter();
        setTimeout(() => reject('Rejected'), 1000);
    } catch (e) {
        console.log('Exception catched', e);
    }
})();
```

The output:

```
(node:35732) UnhandledPromiseRejectionWarning: Rejected
(node:35732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.00s.
```

I'm not sure if that's a bug or I'm missing something, but if someone could suggest how to handle that kind of exceptions I would appreciate.

I'm using "web3": "^1.0.0-beta.37"

**Comment by nivida** [comment]
Thanks for creating this issue!
This should be solved with the PR #2000 and released within the next version (beta.38). Could you please reopen this issue if the behavior still not correct?
