### ISSUE TITLE
Make all communication async. 

### ISSUE THREAD

**Issue by Georgi87** [ethereum/web3.js#220]
I just adapted my application to work asynchronously using callbacks. The DAPP is way more responsive now. But it still lags sometimes. It could be due to the sha3 calls that are made for every request to get function signatures.

**Comment by Georgi87** [comment]
I didnt see the functions getBlockNumber etc are already there. All working.

**Comment by kumavis** [comment]
`web3` uses a lot of synchronous rpc calls **internally** for some reason. This has caused endless performance problems for me as well. If we can document the cases, it should be fairly easy to fix them.

**Comment by Georgi87** [comment]
It seems to me that mostely the sha3 calls are responsible. Why not calculating the hash inside the browser or cache the results for function signatures as they don't change.

**Comment by frozeman** [comment]
in develop sha3 is already an internal js function. not calling the RPC anymore

**Comment by frozeman** [comment]
Actually `newFilter`, which we use internally is also not async.

**Comment by frozeman** [comment]
Here is a list of functions, which need to be used async internally:

- [ ] eth_newFilter
- [ ] eth_uninstallFilter

**Comment by kumavis** [comment]
@frozeman thanks for taking a look into this

**Comment by frozeman** [comment]
fixed in https://github.com/ethereum/web3.js/pull/230

**Comment by kumavis** [comment]
yay~
