### ISSUE TITLE
txParams get contaminated by Web3 v1 calls

### ISSUE THREAD

**Issue by eternauta1337** [ethereum/web3.js#2205]
Web3 v1 is great, thank you for all your amazing work! :tada: 

We encountered a small annoyance when migrating ZeppelinOS to Web3 v1 though. Some Web3 methods that receive a txParams (or "options") object, which contain properties such as gas, from, value, etc. currently alter the incoming object. This may not have significant consequences when making a few, isolated calls to Web3, but they do cause problems that are very difficult to debug in more complex applications.

This may not sound like a big deal at first, but it actually hinders the DX of Web3 a lot. Our solution was to only pass a copy of txParams when interacting with Web3  by doing `{ ...txParams }`  instead of the actual object.
For example: https://github.com/zeppelinos/zos/blob/1aad03c6bdbccf336a8fc95602d4e7fec31937fd/packages/lib/src/utils/Transactions.ts#L104

If Web3 performed the copy internally, and hence avoided contaminating the incoming object, all these problems could easily be avoided.

**Comment by joshstevens19** [comment]
Hey firstly thanks for your issue. That’s a really good point and I’ve never thought about it until you just stated it here. Doing a deep clone of the object internally would make sense but we pass options like this in a lot of different function so if we rolled this out we would want to do it for the whole lib (which isn’t a small thing). I will add a tag for discussion required with this and see what we can do. 

To help you guys out here can you name a few of the main function which you encounter this the most? Maybe I can then fix them for you guys and come back to the rest of the library later on? A list would be great 👍 as I bet there is only certain calls where you kinda need the raw object again after?

**Comment by nivida** [comment]
Thanks for creating this issue! 
I will create a deep copy of all given method arguments in the Method-, EventSubscriptions- and MethodsProxy. This means it will be fixed for all contract calls and also for all ```eth.*, shh.* etc.``` calls. 

If you are interested to learn more about the internals of web3 then have a look at these ES6 classes:

MethodProxy: 
https://github.com/ethereum/web3.js/blob/ethereumProvider/packages/web3-core-method/src/proxy/MethodProxy.js

MethodsProxy:
https://github.com/ethereum/web3.js/blob/ethereumProvider/packages/web3-eth-contract/src/proxies/MethodsProxy.js

EventSubscriptionsProxy:
https://github.com/ethereum/web3.js/blob/ethereumProvider/packages/web3-eth-contract/src/proxies/EventSubscriptionsProxy.js

**Comment by nivida** [comment]
Fixed in #2209

**Comment by eternauta1337** [comment]
Wow, that was incredibly fast. Thank you ^^
