### ISSUE TITLE
how can we generate address using passphrase

### ISSUE THREAD

**Issue by anjalialance** [ethereum/web3.js#2212]
Hi,
I am trying to generate an address from passphrase. The passphrase or mnemonics are generated by bip39. Also, have created the wallet using web3 for ether. The successful transaction has already been performed using web3. Now, I want to extract the address from the passphrase without storing the passphrase and private key in database. Do you have any tutorial or any piece of code how can I perform the above mentioned problem. Kindly help.

**Comment by dev1644** [comment]
You can do this in the following way -:

- You need to convert your mnemonic sequence to a seed. (You can use npm package `bip39` for this).
- Then you can use sub-module `hdkey` of npm package `ethereumjs-wallet` to import the seed and can derive private key and address from it.

**Comment by anjalialance** [comment]
bip30 package is not getting installed. bip30 is not present in npm package collection only bip39 is present.

**Comment by dev1644** [comment]
Oh, I made a typo of `bip39`, Sorry for that.
If your issue is resolved you can close this thread.

**Comment by anjalialance** [comment]
Ohh, it's fine. It is giving the error of hex is not defined.

**Comment by anjalialance** [comment]
Done! Thanks for help!

**Comment by dev1644** [comment]
Hi @nivida, I think we can close this issue.
