### ISSUE TITLE
Failed to check for transaction receipt when deploying a contract to Parity light node

### ISSUE THREAD

**Issue by spalladino** [ethereum/web3.js#2213]
When deploying a contract using web3.js beta 37, connected via an http provider to a Parity light client node (version `v2.2.7-stable-b00a21f-20190115/x86_64-linux-gnu/rustc1.31.1`), the deployment fails with the following error:
```
C = new web3.eth.Contract(abi)
C.deploy({ data }).send({ from, gas, gasPrice: 21e9 })
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (.../node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:56:1)
```

Versions:
```
node --version
v10.13.0
npm --version
6.4.1
web3.version
'1.0.0-beta.37'
```

**Comment by spalladino** [comment]
@nivida let me know what kind of further clarification is needed! I found the code of the contract to be irrelevant to this bug, but I can provide it anyway if it helps.

**Comment by koma2hiroki** [comment]
@spalladino I also got the same error. It solved it.
https://github.com/paritytech/parity-ethereum/issues/5400

**Comment by nivida** [comment]
I will test it asap with the latest version of web3.js and give you further details. Sorry for the late response.

**Comment by mschristensen** [comment]
I'm also experiencing this issue but when sending a signed transaction like: 

```
        logger.info(`[WRITE] Sending signed transaction...`);
        const signedTransaction = await ownerAccount.signTransaction({
            data: tx.encodeABI(),
            from: ...,
            to: ...,
            gas: gas.toString(),
            gasPrice: price.toString(),
        });
        const receipt = await web3MainNet.eth.sendSignedTransaction(signedTransaction.rawTransaction);
``` 

gives:

```
info: [WRITE] Sending signed transaction...
(node:22491) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/ubuntu/<project>/node_modules/web3-utils/src/index.js:56:17)
    at /home/ubuntu/<project>/node_modules/web3-core-method/src/index.js:260:23
    at <anonymous>
```

node version: `v8.12.0`
npm version: `6.4.1`
web3 version: `^1.0.0-beta.30`

**Comment by nivida** [comment]
Does this error still occur with the latest version of Web3?

**Comment by nivida** [comment]
Closed because of the missing answer of the creator of this issue.

**Comment by d10r** [comment]
As I've reported in https://github.com/ethereum/web3.js/issues/1423#issuecomment-542684428, it still happens 1.2.1. In my case while connected to a full node.

**Comment by MoMannn** [comment]
Same is happening to me on parity (works with geth).

**Comment by kael-shipman** [comment]
This appears to still be happening for me.

* **Web3:** v0.20.6 and also v1.2.4
* **Parity:** v2.5.11-stable light node

Would love some clarity on why this is happening, although I believe it's likely Parity's fault.
