### ISSUE TITLE
Web3 1.0.0-beta.38 TypeError: DeployTransactionResponse estimateGas() arguments and return type incorrect

### ISSUE THREAD

**Issue by lucashenning** [ethereum/web3.js#2230]
#### Expected behavior
According to the documentation [web3.Contract methods.myMethod.estimateGas()](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html?highlight=estimategas#methods-mymethod-estimategas),
the `estimateGas()` function, defined in the `DeployTransactionResponse` interface expects 0 - 3 arguments and returns `Promise<number>`

#### Actual behavior
`estimateGas()` expects 1 - 2 arguments and returns `void`. 

#### Steps to reproduce the behavior
```
let deployTx : DeployTransactionResponse = databaseSyncContract.deploy({
        data: contractJson.bytecode,
        arguments: []
    });
    let tx : Transaction = {
        from: nodemanager.getAccountAddress(),
        data: deployTx.encodeABI(),
        gas : await deployTx.estimateGas(),
        value : 0
    };
```

`await deployTx.estimateGas()` requires as an argument: An object with the property `gas`. 

This works but doesn't make any sense:
`await deployTx.estimateGas( { gas : 1000 } )`

#### Incorrect Types Definition
This is the incorrect types definition of DeployTransactionResponse `node_modules/web3-eth-contract/types/index.d.ts`. 

`options` should be optional. The return type should be `number` instead of `void`. 

```
export interface DeployTransactionResponse {
    array: any[];

    send(options: SendOptions): () => Promise<Contract>;

    estimateGas(options: EstimateGasOptions, callback?: (err: Error, gas: number) => void): void;

    estimateGas(callback: (err: Error, gas: number) => void): void;

    estimateGas(options: EstimateGasOptions, callback: (err: Error, gas: number) => void): void;

    estimateGas(options: EstimateGasOptions): void;

    encodeABI(): string;
}
```

#### Versions
web3 v1.0.0-beta.38

**Comment by joshstevens19** [comment]
Thanks for this - PR is in https://github.com/ethereum/web3.js/pull/2231
