### ISSUE TITLE
"TypeError: this.utils.randomHex is not a function" in web3.eth.accounts.create()

### ISSUE THREAD

**Issue by jtremback** [ethereum/web3.js#2238]
#### Expected behavior
`web3.eth.accounts.create()` should create an account. 

#### Actual behavior
`web3.eth.accounts.create()` creates runtime error.

NOTE: `web3.eth.accounts.create("entropy")` works

#### Steps to reproduce the behavior

```
import Web3 from "web3";
const web3 = new Web3("ws://localhost:8546");
web3.eth.accounts.create();
```

#### Error Logs
```
TypeError: this.utils.randomHex is not a function
Proxy.create
node_modules/web3-eth-accounts/dist/web3-eth-accounts.umd.js:106
  103 | }, {
  104 |   key: "create",
  105 |   value: function create(entropy) {
> 106 |     return this._addAccountFunctions(Account.create(entropy || this.utils.randomHex(32)));
      | ^  107 |   }
  108 | }, {
  109 |   key: "privateKeyToAccount",
```

#### Versions
web3.js version 1.0.0-beta.38, Chrome 71, Typescript

**Comment by jtremback** [comment]
Also, calling `web3.utils.randomHex(32)` myself has the same error. Additionally, Typescript thinks that the function exists so that would also indicate that your typings are wrong.

**Comment by jtremback** [comment]
logging web3 to the console shows

![image](https://user-images.githubusercontent.com/1335122/51807075-2d4bd180-2237-11e9-8d93-af78f364256f.png)

randomHex seems to be explicitly undefined

**Comment by nivida** [comment]
@jtremback Thanks for creating this issue!

~~Does this error still occur in the beta.39?~~

Edit:
Checked the NPM package of randomHex. The source of it is the following GitHub repository (https://github.com/frozeman/randomHex#readme). 

Thanks for figuring this out.

**Comment by jtremback** [comment]
Thanks @nivida - are you indicating that it does not happen in beta.39? I will give it a shot. If that doesn't work i'll try the standalone.

**Comment by jtremback** [comment]
Very confusing, the actual code was deleted 2 years ago?

https://github.com/frozeman/randomHex/commit/cd6a244b84e42a0d166a746ac5ba542065b16e87

**Comment by tidusvn05** [comment]
same issue, some function error when utils.randomHex undefined.

utils:
      { randomHex: undefined,
        jsonInterfaceMethodToString: [Function: jsonInterfaceMethodToString],
        hexToAscii: [Function: hexToAscii],
        asciiToHex: [Function: asciiToHex],
        getUnitValue: [Function: getUnitValue],
        fromWei: [Function: fromWei],
        toWei: [Function: toWei],
        toChecksumAddress: [Function: toChecksumAddress],
        keccak256: [Function],
        sha3: [Function],

**Comment by nivida** [comment]
@jtremback Yeah, strange. I will have a closer look at this tomorrow and fix it.

**Comment by WhaleChen** [comment]
I also come across the similar problem, when I want to sign a message using my wallet: 
```   
Wallet signature confirmed.
TypeError: this.utils.randomHex is not a function
    at Proxy.create (~/.nvm/versions/node/v10.15.0/lib/node_modules/@auroradao/aurad-cli/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:96:77)
    at ConfigCommand.run (~/.nvm/versions/node/v10.15.0/lib/node_modules/@auroradao/aurad-cli/src/commands/config.js:116:53) 
```

So what's wrong and what should I do?

**Comment by inyutin** [comment]
I have exactly the same problem.

**Comment by jungle04** [comment]
+1

**Comment by kokleong98** [comment]
+1

**Comment by jtremback** [comment]
I wrote this for myself. It doesn't include all the bells and whistles of the one that was deleted 2 years ago, and it won't work in node.js

```typescript
export function randomHex(size: number) {
  if (size > 65536) {
    throw new Error("Requested too many random bytes.");
  }

  var cryptoLib: any = window.crypto || (window as any).msCrypto;

  if (cryptoLib) {
    var randomBytes = cryptoLib.getRandomValues(new Uint8Array(size));

    return Buffer.from(randomBytes).toString("hex");
  } else {
    var error = new Error(
      'No "crypto" object available. This Browser doesn\'t support generating secure random bytes.'
    );

    throw error;
  }
}
```

**Comment by TamanShergill** [comment]
I am getting the same issue.

**Comment by jungle04** [comment]
`web3.eth.accounts.create()` 
i just gave one string to args
`web3.eth.accounts.create("string")` and it works)

**Comment by jtremback** [comment]
@jungle04 that will generate the same address every time. Don't use it.

**Comment by jungle04** [comment]
![image](https://user-images.githubusercontent.com/31833764/52038162-8e3b1880-255b-11e9-84c2-be553150e1af.png)
<br>
![image](https://user-images.githubusercontent.com/31833764/52038270-dc501c00-255b-11e9-82ad-da586de44896.png)

@jtremback r u sure?? cause i am using same string, but create different addresses every time..

**Comment by darioAnongba** [comment]
I'm having the same issue...

**Comment by sanjukurian** [comment]
@jtremback : Its creating multiple different accounts everytime. Any other issues using that?

**Comment by riki95** [comment]
Having the same issue.
I just use
`web3js.eth.accounts.create();`
And I get 

`TypeError: this.utils.randomHex is not a function`

Any suggestion to fix?

**Comment by crazyrabbitLTC** [comment]
I am getting the same issue.
 web3.eth.accounts.create() returns: 
 TypeError: this.utils.randomHex is not a function

 web3.eth.accounts.create("string") does work. 
However, unlike @jtremback 's comment above, calling the function with the same string repeatedly gives me a different account each time.

**Comment by lbthomsen** [comment]
I see this error consistently in node on Ubuntu but on Debian it works fine.
