### ISSUE TITLE
Error: Missing parameter: provider

### ISSUE THREAD

**Issue by princesinha19** [ethereum/web3.js#2241]
Steps to reproduce:
1. Install web3 and truffle-contract
2. Use in nodejs code
3. Run `node app.js`  command then, you will get this error.

**Error Logs:**
```
node_modules/web3-core/dist/web3-core.cjs.js:148
      throw new Error("Missing parameter: ".concat(name));

Error: Missing parameter: provider
```
**Versions:**
NPM: 6.4.1
node: v10.13.0
Web3.js: ^1.0.0-beta.39
OS: ubuntu 18.04
truffle-contract: 0.4.2

I don't know this is the issue of web3 or truffle-contract. Truffle contract also uses web3 version ^1.0.0-beta.39. And, from error log, I guess this is the issue of web3.

**Comment by nivida** [comment]
Could you please use the issue template and add all of the information we need.

**Comment by princesinha19** [comment]
@nivida I have updated the information based on the issue template.

**Comment by nivida** [comment]
@princesinha19 This looks like an error of the truffle contract package. They use probably an unofficial API. Because of this, I'll close this issue. Please open an issue in the truffle package.

**Comment by princesinha19** [comment]
okay, @nivida. I will ask the question there.
