### ISSUE TITLE
1.0.0-beta.39 - External transaction signing with web3.eth.accounts.signTransaction(tx, privateKey) does not work without default account

### ISSUE THREAD

**Issue by lucashenning** [ethereum/web3.js#2243]
#### Expected behavior
According to https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#signtransaction
`web3.eth.accounts.signTransaction(tx, privateKey);` should sign a transaction without a default account (private key is provided as function argument).

#### Actual behavior
signTransaction fails if no default account is set. This makes external transaction signing impossible (i.e. it's not possible to use infura, nodes without accounts).  

#### Steps to reproduce the behavior
```
let deployTx : DeployTransactionResponse = contract.deploy({
        data: contractJson.bytecode,
        arguments: []
    });
let tx : Transaction = {
        from: nodemanager.getAccountAddress(),
        data: deployTx.encodeABI(),
        gas : await deployTx.estimateGas(),
        value : 0
};

web3.eth.accounts.signTransaction(tx, privateKey); // this line works fine in web3@1.0.0-beta.34 but fails in web3@1.0.0-beta.39
```

#### Error Logs
`TypeError: Cannot read property 'defaultAccount' of undefined`

#### Versions
web3@1.0.0-beta.39

**Comment by nivida** [comment]
@lucashenning Thanks for creating this issue!

I've added the missing parameter ``moduleInstance`` to the inputCallFormatter in the signTransaction method. PR: https://github.com/ethereum/web3.js/pull/2245
