### ISSUE TITLE
Send a transaction using passphrase and private key 

### ISSUE THREAD

**Issue by anjalialance** [ethereum/web3.js#2247]
Hi,

I want to make a transaction with the help of the passphrase or the mnemonics that I have generated using bip39. Now, I am having a private key and address generated by that particular mnemonics. How can I make a transaction using passphrase. Please help.
`var decryptedAccount = web3js.eth.accounts.encrypt(keyStore, 'Password');`
I am using this but I don't have a keystore can I use only password and not the keystore or i can include there my private key. Suggest.

Thanks in advance.

**Comment by nivida** [comment]
Closed because the issue template was not used.
