### ISSUE TITLE
Allow web3.sha3() to hash more than one thing, and numbers instead of strings.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/web3.js#226]
Solidity's sha3() can hash a group of numbers, while web3.sha3() can only hash a single string.

Consider a contract (an auction, say, or in my case a simple game) with secret numerical bids. Suppose the contract stores preimages of the bid hashed with a nonce and maybe a salt. When the bidding is over, the bidders can submit the bid and the nonce to confirm the bid, and solidity can hash them all to confirm the bid is accurate, then work with the bid. This part works fine.

But how does the client generate the preimages to send? web3.sha3() can only hash one string. The string "100" is not the same as the integer one hundred. If I send the string "100" however, the contract would have to waste gas parsing the string. It'd be far easier if web3.sha3 could just hash numbers on its own.

**Comment by tomlion** [comment]
Aha, I need this too to make life easier  :smiley:

**Comment by axic** [comment]
This is actually implemented in [ethereumjs-abi](https://github.com/ethereumjs/ethereumjs-abi):

```js
var abi = require('ethereumjs-abi')
var BN = require('bn.js')

abi.soliditySHA3(
    [ "address", "address", "uint", "uint" ],
    [ new BN("43989fb883ba8111221e89123897538475893837", 16), 0, 10000, 1448075779 ]
).toString('hex')
```

**Comment by marekkirejczyk** [comment]
That would be lovely if it fully worked. Unfortunately, does not work for type bytes32:

```
contract TestTightHash {
    
    function coded() constant returns (bytes32) {
        return keccak256(bytes32("Volume"), bytes32("Volume"));
    }

}
```

`var t = abi.soliditySHA3([ "string", "string" ], [ "Volume", "Volume" ]).toString('hex');`

coded() returns `0x7ab276f38b269dc879fb051ca72ac238c1a03c2db62bbd7a499c1dd822c3e020`

while t equals 

I guess I should report it on ethereumjs-abi:
`8239dae94d559efaf979a8ffdb349ed1d13c6636d28ab641f43ae2bc0c0b985a`

**Comment by frozeman** [comment]
I guess this is what you've wanted: http://web3js.readthedocs.io/en/1.0/web3-utils.html#soliditysha3
