### ISSUE TITLE
web3.js 1.0.0-beta.41 web3.eth.net is undefined

### ISSUE THREAD

**Issue by 7Ds7** [ethereum/web3.js#2267]
#### Expected behavior
web3.eth.net should not be undefined 

#### Actual behavior
web3.eth.net is undefined

#### Steps to reproduce the behavior

1. [First step]
Bundle one of the build files in web3.js/packages/web3/dist (ex: using browserify)

2. [Second step]
Include on the page

3. [and so on...]
web3.eth.net is undefined and per documentation it should not https://web3js.readthedocs.io/en/1.0/web3-eth-net.html

**Comment by nivida** [comment]
Thanks for submitting this issue!
Will test it on Monday it should work but I tested it with webpack.

**Comment by nivida** [comment]
I've created the bundle with webpack and ``console.log(web3.eth.net)`` returns the expected Network class. Be sure browserify is using the umd bundle of Web3.js. Because it isn't an issue of Web3.js itself do I close this issue now.

**Comment by agnelvishal** [comment]
I was trying to access the Network ID to find if Metamask account in the browser is in the testnet or mainet. I tried
```
web3.eth.net.getNetworkType()
.then(console.log);
```
but `web3.eth.net` was undefined. 
` web3.version.network` worked for me
