### ISSUE TITLE
Metamask Provider Engine no longer supported

### ISSUE THREAD

**Issue by molten-firescar96** [ethereum/web3.js#2273]
I tried using Metamask's [web3-provider-engine](https://github.com/MetaMask/provider-engine) with the latest release of web3-1.0. Using their example I get an error `'Please provide an valid Web3 provider` which I believe comes from here. Why was support for EthereumProvider, and SocketProviderAdapter dropped?

https://github.com/ethereum/web3.js/blob/599851753b4a35b5c11f902c7c592b111e190073/packages/web3-providers/src/resolvers/ProviderResolver.js#L90

**Comment by DefiCake** [comment]
Not only that. I am getting the same error out of most versions of ganache and truffle-hdwallet-provider out of the blue. Code that was working before now suddendly does not.

**Comment by davidmurdoch** [comment]
Related: https://github.com/ethereum/web3.js/issues/2266

**Comment by molten-firescar96** [comment]
I'll follow along with that issue
