### ISSUE TITLE
Web3 Contract address property

### ISSUE THREAD

**Issue by eternauta1337** [ethereum/web3.js#2274]
Once again, thank you for your awesome work with Web3 v1.x. 

Another thing that we found kind of cumbersome when migrating ZeppelinOS to Web3 v1.x, is that Web3 Contract objects no longer have an `.address` property, but an `._address` or an `.options.address` property. We ended up having to modify the produced Web3 Contract instances by addind a `.address` getter. Could this be avoided in future releases of Web3? Is there any reason for not doing what we did?

Thx! <3

#### Expected behavior

I see no reason for a Web3 Contract instance object not to have an `address` property.

#### Actual behavior

Instead, Web3 Contract instances have a `_address` and `options.address` properties.

#### Steps to reproduce the behavior

Deploy any contract and console log the resulting instance.

#### Versions
Web3 1.0.0-beta.37

**Comment by nivida** [comment]
Thanks for submitting this issue I'll fix this on Monday. I'm currently sick in the bed.

**Comment by nivida** [comment]
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/AbstractContract.js#L105 

As I saw on line 105 should a contract object already has an address property. The address should be set if you deployed the contract or the address was given over the constructor. Isn't this the current behavior in the latest 1.0 beta release?
