### ISSUE TITLE
Can possible 24/7 web3 events ?

### ISSUE THREAD

**Issue by athlona64** [ethereum/web3.js#2276]
i'm tried tracking ERC20 by Transfer events it running about 3-4 hr.. 

after pass 3-4 hour it's idle

i'm want to tracking ERC20 transfer this contract 24/7

but i'm not sure i'm wrong something. 

repo : https://github.com/athlona64/web3events

![selection_080](https://user-images.githubusercontent.com/3031787/52029963-2c24e800-2548-11e9-8620-adfce2679cef.png)

**Comment by nivida** [comment]
This issue got closed because the issue template is not used.
