### ISSUE TITLE
web3-core-method.umd.js?b3db:226 Uncaught (in promise) TypeError: Duplicated method __ob__. This method is defined as RPC call and as Object method.

### ISSUE THREAD

**Issue by mjdietzx** [ethereum/web3.js#2281]
**All issues which aren't created with this template will get immediately closed.**

#### Expected behavior

`const contract = web3js.eth.Contract(abi, address);`

should (and used to) return a contract instance

#### Actual behavior

instead it throws this error
`web3-core-method.umd.js?b3db:226 Uncaught (in promise) TypeError: Duplicated method __ob__. This method is defined as RPC call and as Object method.`

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Error Logs

```
web3-core-method.umd.js?b3db:226 Uncaught (in promise) TypeError: Duplicated method __ob__. This method is defined as RPC call and as Object method.
    at Object.get (web3-core-method.umd.js?b3db:226)
    at observe (vue.runtime.esm.js?2b0e:961)
    at defineReactive$$1 (vue.runtime.esm.js?2b0e:1002)
    at Observer.walk (vue.runtime.esm.js?2b0e:914)
    at new Observer (vue.runtime.esm.js?2b0e:902)
    at observe (vue.runtime.esm.js?2b0e:970)
    at defineReactive$$1 (vue.runtime.esm.js?2b0e:1002)
    at Observer.walk (vue.runtime.esm.js?2b0e:914)
    at new Observer (vue.runtime.esm.js?2b0e:902)
    at observe (vue.runtime.esm.js?2b0e:970)
```

#### Versions
[NPM, Node, Web3.js, OS, device...]

most recent versions of npm, node, web3.js (beta 41). in browser (Chrome with metamask)

**Comment by devedse** [comment]
I'm encountering the same issue with version higher then beta 37. With beta 41 I got all kinds of typescript errors, so no idea what's going on there.

**Comment by devedse** [comment]
When I downgrade to =beta37 then it works again.

**Comment by nivida** [comment]
Thanks for submitting this issue! 

I've tested it and can't reproduce this error. The thrown error has to come from somewhere else then on the creation of a Contract object. Could you provide further details about when this exactly happens?

**Comment by kvhnuke** [comment]
This is due to vuejs attaching `__ob__` to object as an oberserver, you should skip targets that starts with `$` or `_` https://011.vuejs.org/api/options.html

**Comment by nivida** [comment]
@kvhnuke Thanks for the clarification! will check that.

**Comment by vedmant** [comment]
I have the same issue, and yes, I use Vue.js.

**Comment by 0Alic** [comment]
I have a similar issue while building a DApp with ReactJS, the error is a bit different but I get it in a similar way

**Expected behavior**

`this.rsfContract.deployed().then((instance) => {}
`

**Actual behavior**

`web3-providers.umd.js:394 Uncaught (in promise) Error: Node error: {"message":"Method [object Object] not supported.","code":-32000,"data":{"stack":"Error: Method [object Object] not supported
`

**Steps to reproduce**

```
import RSFContract from './build/contracts/RSFContract.json'
this.rsfContract = TruffleContract(RSFContract);
this.rsfContract.setProvider(this.provider);
// It breaks below
this.rsfContract.deployed().then((instance) => {}
```

**Error Log**

```
web3-providers.umd.js:394 Uncaught (in promise) Error: Node error: {"message":"Method [object Object] not supported.","code":-32000,"data":{"stack":"Error: Method [object Object] not supported.\n    at GethApiDouble.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/lib/subproviders/geth_api_double.js:66:16)\n    at next (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at GethDefaults.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/lib/subproviders/gethdefaults.js:17:12)\n    at next (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at SubscriptionSubprovider.FilterSubprovider.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:89:7)\n    at SubscriptionSubprovider.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:135:49)\n    at next (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at DelayedBlockFilter.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:27:3)\n    at next (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at RequestFunnel.handleRequest (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at Web3ProviderEngine._handleAsync (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:103:3)\n    at Timeout._onTimeout (/tmp/.mount_ganache9QVnd/resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:87:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)","name":"Error"}}
    at Function.validate (web3-providers.umd.js:394)
    at eval (web3-providers.umd.js:794)
```

**Tools and versions**

Node v8.10.0
npm v3.5.2
Truffle v5.0.2
truffle-contract v4.0.5
web3 v1.0.0-beta.46
react v16.8.2


I have done previously a DApp without React, linking the minified scripts of web3 (I guess it was version 0.2) and of truffle-contract and everything was fine.

**Comment by mjdietzx** [comment]
We are using Vue.js as well. Our workaround has been to stick with =beta37. Will upgrade to master once this is fixed

**Comment by vedmant** [comment]
Current workaround I used is to use Object.freeze() on the contract that's added to vuex store.

**Comment by jamesmorgan** [comment]
I get this but freezing does not seem to help. Also using Vue

**Comment by pertsev** [comment]
Have the same issue. But I don't even put the contract instance to the state. Just creating an instance by a getter. Any advices? 

env:
1) vue + nuxt
2) web3@1.0.0-beta.51

**Comment by chriszer** [comment]
and I'm using react what about on react?

**Comment by nivida** [comment]
The proxies who occur this problem will get removed in the 2.x branch as soon as I refactored the public API for BatchRequest. The ES6 Proxy object was required because of the parameters handling for BatchRequests. The solution with the Proxy object is the clean version to handle it without having N bindings.
