### ISSUE TITLE
payable is not assigned in the contructor (AbiItemModel)

### ISSUE THREAD

**Issue by RussMist** [ethereum/web3.js#2285]
#### Expected behavior
Should be able to send transactions with value on payable contract method.
#### Actual behavior
Error ``` 'Can not send value to non-payable contract method or constructor' ```
#### Steps to reproduce the behavior

```
const contract = new web3.eth.Contract(
      ABI,
      CONTRACT_ADDRESS,
    );
contract.methods.method(...params).estimateGas({ value, from });
```
Method ```isValueValid``` from [MethodOptionsValidator.js](https://github.com/ethereum/web3.js/blob/7ff00822966aef2bd0588a5b39ff2f3eba6acfd1/packages/web3-eth-contract/src/validators/MethodOptionsValidator.js#L102) tried to call ``` abiItemModel.payable ```, but it doesn't have this property and then it returns ``` undefined ``` .
(in [constructor](https://github.com/ethereum/web3.js/blob/7ff00822966aef2bd0588a5b39ff2f3eba6acfd1/packages/web3-eth-contract/src/models/AbiItemModel.js#L31) the developer simply forgot to assign payable value to the method's property)

#### Error Logs
```Error: 'Can not send value to non-payable contract method or constructor' ```
#### Versions
``` web3@1.0.0-beta.41 ```

**Comment by markusait** [comment]
Can confirm this on my end as well. Web3 version 1.0.0-beta.3 works perfectly fine. Would be great to fix this as soon as possible, especially because Metamask is using the same corrupted version.
