### ISSUE TITLE
Property 'status' does not exist on type 'TransactionReceipt'.

### ISSUE THREAD

**Issue by e00dan** [ethereum/web3.js#2287]
#### Expected behavior

Property `status` will exist on type TransactionReceipt.

Type `TransactionReceipt` imported from:
```
import { TransactionReceipt } from 'web3/node_modules/web3-core';

const receipt : TransactionReceipt;
receipt.status // error
```

This is breaking change, because beta.37 contained it, when used with @types package.

#### Actual behavior

Property `status` missing in type TransactionReceipt

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Error Logs

Property 'status' does not exist on type 'TransactionReceipt'.

#### Versions
Node 8.12.0
NPM 6.4.1
Web3 1.0.0-beta.40
Windows 10

![error](https://user-images.githubusercontent.com/4950658/52116134-af117580-2610-11e9-9072-565b47773546.png)

**Comment by joshstevens19** [comment]
Hey @Kuzirashi Thanks for spotting this and raising it. I have put a PR to fix this issue here:

https://github.com/ethereum/web3.js/pull/2288

It will be released next week (probably Monday). 

Oh and FYI (sorry you probably know this)

`import { TransactionReceipt } from 'web3-core';` will work as well :)

Thanks

**Comment by e00dan** [comment]
Didn't know it works. Will test. Thank you @joshstevens19

**Comment by joshstevens19** [comment]
when i said it will work i meant the syntax i think is cleaner like that rather then `web3/node_modules/web3-core`. The fix for this status will be in the next release 👍 cheers.

**Comment by joshstevens19** [comment]
Will close as fix is in the next release. Thanks
