### ISSUE TITLE
Add mention of the "Ethereum Signed Message"  prefix to the eth.personal.sign documentation

### ISSUE THREAD

**Issue by montyly** [ethereum/web3.js#2293]
Hi, thank you for maintaining web3js!
The following is an issue related to the documentation that might mislead users.

#### Expected behavior

The documentation of [`eth.personal.sign`](https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html#sign ) should detail the hash schema used.

#### Actual behavior

The current documentation does not indicate that the message to be signed is prefixed with: 
```
"\x19Ethereum Signed Message:\n" + message.length
```

This might lead to the incorrect usage of the library. 

Note that the documentation of [`eth.accounts.sign`](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#sign) does mention the prefix: 

![image](https://user-images.githubusercontent.com/13798342/52163646-ddf51d80-26dc-11e9-9f63-af94a086372a.png)

#### Versions
https://github.com/ethereum/web3.js/tree/7ff00822966aef2bd0588a5b39ff2f3eba6acfd1

**Comment by axelgalicia** [comment]
Hello @montyly , please let me know if this pull request fulfills the expected outcome of your requirement. I will be happy to update it in case there is a missing part.

Thanks

**Comment by montyly** [comment]
#2295 fixes the issue, thank you!
