### ISSUE TITLE
Include web3.js into browser

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2294]
**All issues which aren't created with this template will get immediately closed.**

#### Expected behavior

Since `beta.38` I can't include web3.js in my browser anymore. Before I was able to do it like this:

    <script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.37/dist/web3.min.js"></script>

Than I had the `window.Web3` object.

#### Actual behavior

Since `beta.38` this isn't working anymore. The REAME don't answer how to include `web3.js` into the browser.

#### Steps to reproduce the behavior

Try to include this into your page:

    <script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.x/dist/web3.min.js"></script>

    x>37
#### Error Logs

It's not loading.

#### Versions

Since `beta.38`.

**Comment by ghost** [comment]
Just saw someone already asked something similar here #2291

**Comment by nivida** [comment]
Duplicated: #2291
