### ISSUE TITLE
web3.eth.requestAccounts is not a function

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2297]
#### Expected behavior

Get my accounts from metamask.

#### Actual behavior

Error: `Uncaught (in promise) TypeError: this.web3.eth.requestAccounts is not a function`

#### Steps to reproduce the behavior

    const web3 = new Web3(window['ethereum']); // for metamask
    web3.eth.requestAccounts().then(console.log);

#### Error Logs

    Uncaught (in promise) TypeError: this.web3.eth.requestAccounts is not a function

#### Versions
`https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.37/dist/web3.min.js`

**Comment by nivida** [comment]
The requestAccounts method got added with version 1.0.0-beta.38. Please use the latest version of Web3.
