### ISSUE TITLE
Difference between injected providers

### ISSUE THREAD

**Issue by filips123** [ethereum/web3.js#2298]
Web3 (1.0) has many ways to detect injected provider (MetaMask, Mist, ...). Some of them are `Web3.givenProvider`, `web3.currentProvider` and `window.ethereum`.

What is the difference between them? I know that `window.ethereum` uses EIP-1102, but what is the difference between the other two? Which one should I use?

**Comment by nivida** [comment]
Web3.js does not provide many ways to detect an injected provider. ```Web3.givenProvider``` is the only one. Please ask further questions about the EIP-1193 and EIP-1102 [here](https://ethereum-magicians.org/c/working-groups/provider-ring). 

Btw: Any other issue which isn't created with the issue template will get closed directly.
