### ISSUE TITLE
Batch requests can't be created for method estimateGas

### ISSUE THREAD

**Issue by melnikaite** [ethereum/web3.js#2331]
#### Expected behavior

```
const batch = new web3.BatchRequest();
batch.add(contract.methods.add(...args).estimateGas.request({from}, console.log));
```
adds new request to the batch

#### Actual behavior

error: `TypeError: contract.methods.add(...).estimateGas.request is not a function`

#### Steps to reproduce the behavior

1. add estimateGas request to batch

#### Error Logs

`TypeError: contract.methods.add(...).estimateGas.request is not a function`

#### Versions
OS X 10.14.2
npm 6.4.1
node v11.3.0
Ganache CLI v6.1.0 (ganache-core: 2.1.0)
web3 1.0.0-beta.37

**Comment by vlddm** [comment]
Still no `request()` method exist in `estimateGas` object using  web3js 1.3.4
