### ISSUE TITLE
postinstall node angular-patch.js causes install to fail

### ISSUE THREAD

**Issue by roblav96** [ethereum/web3.js#2334]
# Problem
Running `npm install web3@1.0.0-beta.42` exits with code 1

# Solution
Get rid of npm script `"postinstall": "node angular-patch.js"`

----

#### Expected behavior
`npm install` to not fail to install

#### Actual behavior
`npm install` fails to install

#### Steps to reproduce the behavior
```shell
npm install web3@1.0.0-beta.42
# <error logs go here>
```
Fails to install.

#### Error Logs
```shell
> web3@1.0.0-beta.42 postinstall /Users/me/Projects/switch/node_modules/ilp-plugin-ethereum/node_modules/web3
> node angular-patch.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/me/Projects/switch/node_modules/ilp-plugin-ethereum/node_modules/web3/angular-patch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm WARN The package fsevents is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.42 postinstall: `node angular-patch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.42 postinstall script.
```

#### Versions
```
▶ node -v
v10.15.0
▶ npm -v
6.7.0
```

**Comment by joshstevens19** [comment]
Hey thanks for spotting this, we need that script to run for certain things but it seems we did not add it to the `files` in the package.json hence why it can not find it.

I have added it within this PR - https://github.com/ethereum/web3.js/pull/2336

hopefully @nivida will deploy a new release soon. Sorry for the issues.

Thanks
Josh

**Comment by mfahampshire** [comment]
Also having this error on Ubuntu 18.04. Exactly the same error message. 

Versions: 
```
$ node -v 10.13.0
$ npm -v 6.4.1
```

**Comment by nivida** [comment]
Fixed and released some minutes ago
