### ISSUE TITLE
NPM can not install web3 beta42

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2335]
#### Expected behavior

Using

   npm -g install web3@1.0.0-beta.42

will install web3@1.0.0-beta.42

#### Actual behavior

Installation stops with

> web3@1.0.0-beta.42 postinstall /home/pi/.nvm/versions/node/v10.15.1/lib/node_modules/web3
> node angular-patch.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/pi/.nvm/versions/node/v10.15.1/lib/node_modules/web3/angular-patch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.42 postinstall: `node angular-patch.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.42 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The web3 folder does not exist anymore

#### Steps to reproduce the behavior

Use

   npm -g install web3@1.0.0-beta.42

#### Versions

web3@1.0.0-beta.42

**Comment by joshstevens19** [comment]
Hey thanks for raising a issue this is the same as this one https://github.com/ethereum/web3.js/issues/2334 and a PR is up to fix it. Will close this one due to duplicate.

**Comment by joshstevens19** [comment]
FYI fix has now been deployed so please try the `web3@1.0.0-beta.43` just tested and works fine now. Sorry again.
