### ISSUE TITLE
[web3@1.0.0-beta.41] getPastEvents not working - {"code":-32603,"message":"request failed or timed out"}

### ISSUE THREAD

**Issue by neocybereth** [ethereum/web3.js#2337]
**All issues which aren't created with this template will get immediately closed.**

#### Expected behavior

Expected .getPastEvents to fire for a particular contract and return the data based on the allocated toBlock/fromBlock parameters

#### Actual behavior

Console returns this error: 
{"code":-32603,"message":"request failed or timed out"}

#### Steps to reproduce the behavior

1. [First step]
find an ethereum contract
2. [Second step]
call an event on it between a particular pair of block numbers
3. [and so on...]

#### Error Logs

```
(node:37749) UnhandledPromiseRejectionWarning: Error: Connection error: Connection is not open on send()
    at /Users/smorgin099/projects/node_modules/web3-providers/dist/web3-providers.cjs.js:519:27
```

NOTE: https://github.com/ethereum/web3.js/issues/2311#issuecomment-461227922 ; in this comment @mistersandman provides valuable insight into what the potential issue is.

#### Versions
[NPM, Node, Web3.js, OS, device...]
web3@1.0.0-beta.37 - 41 (ive tried all instances to no avail)
node@v10.14.2
npm@6.7.0
OS: MacOS mojave

**Comment by nivida** [comment]
I'm closing this issue because I've reopened the other.
