### ISSUE TITLE
MetaMask is Broken in 1.0.0-beta.41 (works with 1.0.0-beta.37)

### ISSUE THREAD

**Issue by mwaeckerlin** [ethereum/web3.js#2340]
Please have a look at this ticket in MetaMask, according to them, the problem comes from web3,js:

[TypeError: NetworkError when attempting to fetch resource](https://github.com/MetaMask/metamask-extension/issues/6095)

If the problem is related to MetaMask, not to web3.js, then please get into contact with that team and try to find a solution together.

Here a summary of the problem:

**Downgrade web3 to 1.0.0-beta.37 solves the problem**

#### Expected behavior

Success, no error message, but access to the blockchain.

#### Actual behavior

Error: `DataCloneError: The object could not be cloned`

#### Steps to reproduce the behavior

 I can reproduce the problem with a simple [react-metamask-test](https://github.com/mwaeckerlin/react-metamask-test) demo:

```bash
git clone https://github.com/mwaeckerlin/react-metamask-test
cd react-metamask-test
npm install
solc --overwrite --combined-json abi,bin -o src/contracts/json src/contracts/test.sol
ganache-cli -d --db ${HOME}/tmp/ganache/db -i 123456
BROWSER=none npm start
```

1. Start Firefox, disable Metamask, head to http://localhost:3000, create a contract (chose a local account, add some text, press the button) → **It works without MetaMask!**
2. Enable Metamask, reload the page, try again → **ERROR: `DataCloneError: The object could not be cloned`**

The following patch fixed the problem:
```
diff --git a/package.json b/package.json
index b48ff8d..fc5a020 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
     "react": "^16.8.0",
     "react-dom": "^16.8.0",
     "react-scripts": "2.1.3",
-    "web3": "^1.0.0-beta.41"
+    "web3": "1.0.0-beta.37"
   },
   "scripts": {
     "start": "react-scripts start",
```

#### Error Logs

`DataCloneError: The object could not be cloned` (and other)

#### Versions

 - react 16.7.0
 - web3, 1.0.0-beta.41
 - canache-cli 6.2.5
 - canache-code 2.3.3
 - Firefox Quantum 64.0
 - Metamask 5.3.2, also tested backgrade to 5.3.0

**Comment by nivida** [comment]
Will test it with react. 

Edit: 
I've tested it with MetaMask and get some strange errors too. Will have a look at it tomorrow and probably fix it.

**Comment by AchinthyaBhat** [comment]
I am getting the same error when using metamask on polygon network on ff browser. Idk if it's related but loading my tokens and their icons is taking forever now on the metamask dropdown
