### ISSUE TITLE
TypeError: Duplicated method getAccounts. This method is defined as RPC call and as Object method.

### ISSUE THREAD

**Issue by kim-keepcoding** [ethereum/web3.js#2344]
Please allow to override web3.eth.getAccounts function.

Normally, I used it like this before 1.0.0-beta.41 to override rpc the same way as metamask do.
It works with others methods like privatekey keystore too.

#### Expected behavior

get assigned account

#### Steps to reproduce the behavior

```
this.web3.eth.accounts.wallet.add(account);
this.web3.eth.defaultAccount = account.address;
//Override resolver
this.web3.eth.getAccounts = cb => {
     cb(null, [this.web3.eth.defaultAccount]);
};
```

#### Error Logs
```
ERROR TypeError: Duplicated method getAccounts. This method is defined as RPC call and as Object method.
```
#### Versions
[NPM@6.4.1, Node@v8.12.0, Web3.js@1.0.0-beta.43, OS:macOs@10.14.2]

**Comment by nivida** [comment]
This does no longer work because of security an architectural reasons. I'm currently writing the documentation for the ``Web3 Module API`` this will provide you the possibility to create your own custom JSON-RPC calls and contract objects. (https://github.com/ethereum/web3.js/pull/2236)

**Comment by rhlsthrm** [comment]
We were writing test code and stubbing out Web3 methods using syntax like this: `validator.web3.eth.getTransaction = sinon.stub().returns(stubs[0])`.

After updating web3, these tests broke. Is there a workaround?

**Comment by keyz182** [comment]
Any word on this? This breaks our tests also, as we use [Sinon ](https://sinonjs.org/releases/v7.3.1/stubs/)to stub out methods.

**Comment by ExtraBB** [comment]
Same issue here
