### ISSUE TITLE
[types][web3-utils] Use bn.js directly for class BN instead of wrapper

### ISSUE THREAD

**Issue by sebastianst** [ethereum/web3.js#2350]
#### Expected behavior
Let `BN` denote the class as exported from `web3-utils`, not `bn.js`.
Assigning results of `BN` methods, like `add()`, to variables of type `BN` should work.

#### Actual behavior
Doesn't compile, throws typescript errors.

#### Steps to reproduce the behavior with error logs
The code 
```ts
import { BN } from "web3-utils";
let a = toBN(0); // or new BN(0)
let b: BN;
b = a.add(toBN(1));
```
gives error
```
error TS2741: Property 'super' is missing in type 'BN' but required in type 'BN'.

71 b = a.add(toBN(1));
   ~

  node_modules/web3-utils/types/index.d.ts:73:5
    73     super(number: number | string | number[] | Buffer | BN, base?: number | 'hex', endian?: 'le' | 'be'): BigNumber;
           ~~~~~
    'super' is declared here.
```
So right now I do arithmetics with `a.add(toBN(1)) as BN` hacks.

Now I could instead do `import BN = require('bn.js');` but then I get another error when passing those `BN`s into, e.g., `web3.utils.soliditySha3`:
```
error TS2345: Argument of type 'BN' is not assignable to parameter of type 'Mixed'.
  Property 'super' is missing in type 'BN' but required in type 'BN'.
```

#### Background
The web3-utils type declarations internally first do
```ts
import BigNumber = require('bn.js');
```
(which in itself is confusing, because `bn.js` is usually imported as `BN` and `BigNumber` is used for `bignumber.js`) and then declares and exports a wrapper class
```ts
export class BN extends BigNumber {
    constructor(number: number | string | number[] | Buffer | BN, base?: number | 'hex', endian?: 'le' | 'be');
    super(number: number | string | number[] | Buffer | BN, base?: number | 'hex', endian?: 'le' | 'be'): BigNumber;
}
```
Why is that? Why doesn't web3 just use `bn.js` directly?

This whole `BN` situation is a bit confusing, see also  #2171
 
#### Versions
Tested with node `v11.9.0` web3 version `1.0.0-beta.43` and typescript `3.3.1` in a truffle `v5.0.2` project.

**Comment by nivida** [comment]
Thanks for submitting this issue I'll fix this asap.

Edit:
Could you update the issue for being align with the issue template?

**Comment by sebastianst** [comment]
Thanks for fixing. Will update the issue.

**Comment by sebastianst** [comment]
Found an even easier example with `clone()`:
```ts
let a = toBN(0);
let b: BN = a.clone();
```
gives the same error.
