### ISSUE TITLE
"src/index.js" is missing after installing using "npm install web3".

### ISSUE THREAD

**Issue by msaikat** [ethereum/web3.js#2352]
#### Expected behavior
web3 modules under node_modules has "src/index.js" inside

#### Actual behavior
"src/index.js" is missing after installing using "npm install web3". Instead dist, node_modules and type is present.

#### Steps to reproduce the behavior

1. npm install web3

#### Error Logs
No error happened!

#### Versions
"web3": "^1.0.0-beta.43"

**Comment by OFRBG** [comment]
The entry point structure was changed to split into umd, cjs, and esm versions.

The `package.json`s instead of `index.js`, they have

```json
  "main": "dist/web3.cjs.js",
  "module": "dist/web3.esm.js",
```
