### ISSUE TITLE
Call to account.signTransaction({...}) throw TypeError

### ISSUE THREAD

**Issue by ericbinet** [ethereum/web3.js#2356]
#### Expected behavior
When supplying a fully defined transaction to `account.signTransaction`, a signed transaction should be returned.

#### Actual behavior
As it stands, the method throws a TypeError: this.signTransaction(...).bind is not a function. This is caused by the early return on line 230 of Accounts.js.

#### Steps to reproduce the behavior

```js
const Web3 = require("web3");

const web3 = new Web3(Web3.givenProvider || "ws://localhost:8546");
let pk = "0x0e652850717658cfd360d2c97474f4b2d8db5a9222adef2ebce67788f75e58f8";
let account = web3.eth.accounts.privateKeyToAccount(pk);
let signedTx = account.signTransaction({
    nonce: "0",
    chainId: "1",
    to: account.address,
    data: web3.utils.toHex('msg'),
    value: "0",
    gasPrice: "0",
    gas: "0"}
    );
```

#### Error Logs

`TypeError: this.signTransaction(...).bind is not a function`

#### Versions

* NPM: 6.4.1
* Node: 10.15.0
* Web3.js: 1.0.0-beta.44
* OS: Windows 10

**Comment by nivida** [comment]
Thanks for submitting this issue. Because I had several problems with the accounts module do I refactor it to finally solve these issues.

**Comment by stefdelec** [comment]
Was it closed because there is a solution?

**Comment by ericbinet** [comment]
Does it still occur in beta50? If so, post repro steps and reopen.

**Comment by stefdelec** [comment]
Ok. I still have this issue (a bit different) 

`       TypeError: this.accounts.signTransaction is not a function`

**Comment by ericbinet** [comment]
Since the symptoms are not the same, it's best to create a new issue with the proper description and repro steps.

**Comment by stefdelec** [comment]
ok.
