### ISSUE TITLE
filter fromBlock default to be current block instead of 0

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#236]
suggestion in https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter the fromBlock default is 0.  It is going to be rare for a dapp to want events since genesis; and on an ongoing basis a dapp would probably like to filter from the current block.

So this suggestion would make this behavior:
```
var myEvent = myContractInstance.MyEvent({some: 'args'}, {fromBlock: web3.eth.blockNumber, toBlock: 'latest'});
```

equivalent and simplified to:
```
var myEvent = myContractInstance.MyEvent({some: 'args'});
```

**Comment by frozeman** [comment]
default `fromBlock` should be `"latest"`, not sure why @debris add 0 there. This would be extremely unperformant for the nodes, requesting all logs from beginning of time.

Actually the RPC specs state it correctly https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
