### ISSUE TITLE
toDecimal() produces Error: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by ekkis** [ethereum/web3.js#2361]
#### Expected behavior
I should get a decimal number
#### Actual behavior
I get an error
#### Steps to reproduce the behavior

```
const Web3 = require('web3');
const net = 'https://mainnet.infura.io/';
const walletAddress = '0x44...';

const web3 = new Web3(new Web3.providers.HttpProvider(net));
web3.eth.getBalance(walletAddress).then((bal) => {
    bal = web3.utils.toDecimal(bal);
    console.log(bal);
});
```

#### Error Logs

> (node:50698) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
>     at assert (/Users/ekkis/dev/eth/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
>     at BN.toNumber (/Users/ekkis/dev/eth/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
>     at Object.hexToNumber (/Users/ekkis/dev/eth/node_modules/web3-utils/dist/web3-utils.cjs.js:103:22)
>     at web3.eth.getBalance.then (/Users/ekkis/dev/eth/index.js:9:19)
>     at process.internalTickCallback (internal/process/next_tick.js:77:7)
> (node:50698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:50698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

#### Versions
NPM: 6.7.0
Node: 11.5.0
Web3.js: '1.0.0-beta.43'
OS: OSX 10.14

**Comment by OFRBG** [comment]
Ethereum balances are stored in 256 bit memory slots. JS only supports numbers up to 53 bits. You need to store the result in a string. If you also need to perform operations with it, you can do things like

```js
const Web3 = require('web3');
const net = 'https://mainnet.infura.io/';
const walletAddress = '0x44...';

const web3 = new Web3(new Web3.providers.HttpProvider(net));

web3.eth.getBalance(walletAddress).then((bal) => {
    const doubled = web3.utils.toBN(bal).mul(web3.utils.toBN(2));
    console.log(doubled.toString());
});
```

**Comment by ekkis** [comment]
thank you.  one problem with the code is that `.toDecimal()` is deprecated but that wasn't clear to me.  It would help if there were official code samples out there that shared how exactly this kind of stuff is supposed to be handled.  thanks for your reply, I'm closing the ticket :)
