### ISSUE TITLE
Node Error

### ISSUE THREAD

**Issue by ishanjoshi02** [ethereum/web3.js#2362]
#### Expected behavior

`UserStore.deployed()` should return the instance of the contract

#### Actual behavior

Node Error: Method [object Object] not supported.

#### Steps to reproduce the behavior

1. `import TruffleContract from "truffle-contract";`
2. `const Web3 = require("web3");` 
3. `const UserStoreArtifact = require("artifact.json");`
4.
```
const web3 =  new Web3(
  new Web3.providers.HttpProvider(`http://localhost:${8545}`)
);
```
5. `UserStore.setProvider(web3.currentProvider);`
6. `const ins = await UserStore.deployed();`

#### Error Logs

![image](https://user-images.githubusercontent.com/14982214/52529851-f8a04580-2d1f-11e9-9406-08cd8c4fc3c2.png)

#### Versions

NPM - 6.4.1
Node - 10.15.1
Web3.js - 1.0.0-beta.37
OS - Windows 10
Device - Dell 7577

**Comment by ishanjoshi02** [comment]
While using `truffle console`, I am able to get the Instance of the contract.

**Comment by nivida** [comment]
Thanks for submitting this issue. As I see from the error message you are using a version higher then beta.37. Truffle does currently only support until version beta.37 of the Web3.js library. 

Please be sure you are using the right version.

**Comment by chipueatfast** [comment]
> Thanks for submitting this issue. As I see from the error message you are using a version higher then beta.37. Truffle does currently only support until version beta.37 of the Web3.js library.
> 
> Please be sure you are using the right version.

But he use exactly version beta.37 !

**Comment by takuyabz** [comment]
同じ問題が発生しています
