### ISSUE TITLE
SPV light-client support

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/web3.js#237]
Greeting!

You may have seen the video I made - https://www.youtube.com/watch?v=ghmSLvViqEo - of ethereumj-android running on my Samsung S6?   That was just a step on my own path towards making a DAPP on the Samsung Gear S smartwatch (http://www.gsmarena.com/samsung_gear_s-6620.php) which is a pure HTML5 environment.  That DAPP will be using web3.js.

My first step will be to build out my functionality on the Gear S just using web3.js to communicate to a full node running on my Mac.  I had hoped that node could be an ethereumj-android running on my tethered S6, but Jarrad tells me that ethereumj is currently missing json-rpc support, though that is coming very soon too (his team will be building that).    But when I have a working app on the watch my real aim is to untether it - because the Gear S has Wifi and 3G data - by running a light client directly on the watch.

So ...

Phase I - Build UX on the watch, using web3.js to connect to a full node on my Mac via json-rpc
Phase 2 - Switch to using web3.js to connect to an ethereumj-android service process running on my BLE tethered S6, still via json-rpc
Phase 3 - Cut the tether, and use web3.js in "SPV mode" to connect to the Ethereum network directly.  The light node would be running in-process of my HTML5 app, right inside the web runtime (which is Webkit2) on device.   That app will have access to 3G and Wifi connectivity.

Has any effort already been made towards SPV support in web3.js?   Or, indeed, in any of the other clients?

Any existing plans?   Do you have a decent feel for that what might "smell like"?   How hard it will be?   How long it might take?   Where it might fall in a priority list compared to other backlog items you may have?

How can I help you guys to achieve that aim?

George Hallam had suggested that it was probably DEV Grant worthy, and I have been chatting away in the dev grants forum for a couple of weeks now.   As it stands, though, I cannot start on the application process because I have no "work in progress".   I don't need the money, and would only tap into that process if the money could be used to accelerate the process (which would probably mean me spending the money to hire a contractor).

I can only contribute to the aim myself sporadically in the gaps which my day job and kids leave me.   The DEV grant could help accelerate that process, so maybe YOU apply for the dev-grant, and have the contractor work directly on web3.js.   But we will need to get some work-in-progress happening before the grant process can start.

Let's do this :-)

**Comment by jarradh** [comment]
I believe everyones on focusing on getting a stable network running, afaik SPV support is a way off for now. I could be mistaken but I'm not sure if web3 implements a full client either, my understanding is that it's a wrapper around json-rpc? Rather SPV needs to be implemented in one of the main libraries (go,cpp,java,etc)

**Comment by bobsummerwill** [comment]
You will be right on that, Jarrad, but an SPV client in JS should be entirely feasible. 

If web3.js in not an appropriate place for that and it should be in another JS library for inclusion within HTML5 apps then that is fine too.

If this is lower down on people's priorities that is fine.   That just means that I will end up driving it myself more.   Scratch my own itch and all that!

**Comment by bobsummerwill** [comment]
Or should I be looking at ethereumjs-lib?

**Comment by tgerring** [comment]
web3.js is a JavaScript library for communicating with Ethereum JSON RPC. The RPC speaks in hex, which is not very friendly for developers, so this library abstracts all that messiness into DApp-friendly JS.

You _probably_ want ethereumjs-lib instead, though I don't know how effective this is when running a browser... maybe the creators have tried. Here's a link to some usage examples: https://github.com/ethereum/ethereumjs-lib#examples

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/ethereumjs-lib/issues/106.   Will close here
