### ISSUE TITLE
Clarification on "notification" events from provider

### ISSUE THREAD

**Issue by pixelmatrix** [ethereum/web3.js#2372]
As the maintainer of a web3 provider, I'm looking for clarification about the state of subscription support via EIP-1193.

We're trying to update our SDK to be compatible with the latest beta, but it appears there are some inconsistencies with the new spec. Namely, the EIP states that providers should emit "notification" with the unmodified parameters from RPC response. However, we're seeing that this library currently ignores "notification" events emitted. 

It appears this library currently expects you to emit the subscription id as the event name instead. This is both a change from the previous behavior (It was using "data" before), and yet not what I would expect after reading the EIP.

I have our provider working with the latest beta, but I'm curious if the plan is to use "notification" or continue to emit with the subscription id. Ideally we'd like to limit the number of variations we support here.

#### Expected behavior

web3.js would listen for "notification" events from the provider.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#notification

#### Actual behavior

web3.js is listening for subscription id events from the provider.

https://github.com/ethereum/web3.js/blob/35ebbcacbecc75a6cac033fc648d0091e0235a83/packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js#L96

#### Steps to reproduce the behavior

1. Create a provider that emits "notification" on new data, as shown in the example on EIP-1193.
2. Subscribe to something in the SDK
3. Trigger an event that would normally be handled by the subscription
4. Observe that it is not handled

#### Error Logs

There are no errors thrown.

#### Versions

This seems to have been introduced in web3@1.0.0-beta.38

**Comment by OFRBG** [comment]
I'm not sure, but at a quick glance it seems to might related to https://github.com/ethereum/web3.js/issues/2266. There are still groups who haven't migrated to EIP-1193, so to avoid breaking half of the DApp world, the changes might be implemented a bit more cautiously.

I don't know if you started from scratch, but @nivida recommends prototyping from the [Abstract Socket Provider](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/lib/providers/AbstractSocketProvider.js). Maybe that could help to not fall out of sync with the dist?

**Comment by pixelmatrix** [comment]
@OFRBG Thanks for the suggestion! However, since we're using web3-provider-engine behind the scenes (for a number of other reasons) we can't easily inherit from the new abstract provider.

Unfortunately it looks like right now it's neither using the current proposed api, nor compatible with the older api. I actually only noticed because it broke our DApps all of a sudden.

These things happen, but we're just hoping to get some guidance on which event name to emit here for future compatibility. FWIW, I think a number of folks are using web3-provider-engine, so I bet many people have the same question.

One option could be to change this library back to use the old "data" method for now if the proposal isn't far enough along (restoring compatibility with other providers), but I'd be fine with implementing anything that is going to stick for a while.

**Comment by OFRBG** [comment]
What is the last web3@1.0.0 version that worked for you? I've seen more than a couple of projects that have opted to downgrade to web3@1.0.0-beta.37 for production until post-beta.37 implementations "stablize". Perhaps a midpoint would be keeping a branch with post-beta.37 for development testing, and one for beta.37 development 😝.

**Comment by nivida** [comment]
It's not required to inherit from the ``AbstractSocketProvider``. You should be able to just follow the EIP-1193 and Web3.js will detect it as a valid EIP-1193 provider and handle it. 

I've created a adapter for all EIP-1193 providers [here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/EthereumProvider.js). 

I think this is what you were looking for? @pixelmatrix 

(As I saw did the EIP-1193 change again and the ``isEIP1193`` property does no longer exist. I will update the implementation of the EIP-1193 in the next release to be again compatibel with it)

**Comment by pixelmatrix** [comment]
@nivida Thanks for taking a look. I'm mainly just wondering if you're going to follow the event naming from the spec, or if it is intentionally different.

EIP-1193 emits "notification", while the latest beta emits the subscription id. 

We won't be able to inherit from anything in this library directly, so we're trying to ensure compatibility according to the spec.

**Comment by nivida** [comment]
I will follow the EIP-1193 for all exposed providers (WebsocketProvider, IpcProvider, HttpProvider). I will update the interface of them and add a deprecation warning in the coming versions.
