### ISSUE TITLE
Invalid chainId used to sign transactions

### ISSUE THREAD

**Issue by gabmontes** [ethereum/web3.js#2378]
#### Expected behavior

When signing transactions in Ethereum Classic (might be applicable to other chains as well), the signing logic in the accounts package shall use the proper `chainId` (i.e. 61/62) if it is not specified in the transaction object by calling `eth_chainId` RPC.

#### Actual behavior

In the above mentioned case, the chainId value is actually retrieved using the `net_version` RPC call, which does return an incorrect value (prior EIP-155).

#### Steps to reproduce the behavior

1. Connect web3 to an Ethereum Classic node.
2. Create a wallet/account so allow web3 to sign the txs.
3. Send tx without specifying the chain ID.
4. Check the transaction was not created using a `chainId` value 61/62.

#### Error Logs

N/A 

#### Versions
Web3.js@1.0.0-beta.37

Related to #1644.

A quick fix for beta.37 and previous versions is to apply this patch:

```diff
--- a/node_modules/web3-eth-accounts/src/index.js
+++ b/node_modules/web3-eth-accounts/src/index.js
@@ -69,7 +69,7 @@ var Accounts = function Accounts() {
     var _ethereumCall = [
         new Method({
             name: 'getId',
-            call: 'net_version',
+            call: 'eth_chainId',
             params: 0,
             outputFormatter: utils.hexToNumber
         }),
```

**Comment by nivida** [comment]
Will check and fix this in the current working branch (https://github.com/ethereum/web3.js/pull/2367)
