### ISSUE TITLE
web3-bzz upload broken

### ISSUE THREAD

**Issue by wanyvic** [ethereum/web3.js#2379]
the latest version of swarm-js is 0.1.39 from npm .but it not modified `bzz-raw` replace  by `bzzr`
[swarm-js/issues/31](https://github.com/MaiaVictor/swarm-js/issues/31)

**Comment by nivida** [comment]
@wanyvic FYI: I've closed it because you didn't use the issue template. I know about the problems the BZZ module has. I will remove the swarm-js dependency and refactor the BZZ module. The removement of the swarm-js package will happen because it isn't actively maintained.

**Comment by wzup** [comment]
@nivida Any update with the issue?
I've installed `web3` and I've got this warning about `mkdirp-promise@5.0.1` in `swarm-js`. I don't know how to deal with it
```
$ npm i -P web3
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
```

Why in `swarm-js`? Because I traced it with `npm ls mkdirp-promise@5.0.1`:
```
$ npm ls mkdirp-promise@5.0.1
web3-app@0.0.1 /Users/sergey/sbox/ts/web3-app
└─┬ web3@1.3.4
  └─┬ web3-bzz@1.3.4
    └─┬ swarm-js@0.1.40
      └── mkdirp-promise@5.0.1
```
