### ISSUE TITLE
JS API registrar services

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#238]
will these be added to the JS api https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions#registrar-services ?

or how do Dapps access the GlobalRegistrar without hardcoding an address?

**Comment by debris** [comment]
Dapps can access GlobalRegistrar using `web3.eth.namereg` object. See [namereg](https://github.com/ethereum/web3.js/blob/master/example/namereg.html) example. I've also added short chapter about `namereg` to [Wiki](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethnamereg). I will improve it soon.

**Comment by ethers** [comment]
nice, thanks :)
