### ISSUE TITLE
Possible invalid gas check

### ISSUE THREAD

**Issue by gabmontes** [ethereum/web3.js#2381]
Up to version beta.37, there was an issue with checking the receipt for transaction execution status:

https://github.com/ethereum/web3.js/blob/1d9f6c0889c7f551b4ec1041cece0d50bc3ff2c8/packages/web3-core-method/src/index.js#L351

While `gasProvided` is a hex string, `receipt.gasUsed` is a number, making the condition always fail -and therefore failing to do any check-. Proper comparison would be:

```js
gasProvided !== utils.numberToHex(receipt.gasUsed)
```

It looks like after the refactor in version beta.38 and up, the condition is the same:

https://github.com/ethereum/web3.js/blob/599851753b4a35b5c11f902c7c592b111e190073/packages/web3-core-method/src/validators/TransactionReceiptValidator.js#L80

I was unable to check the latests versions yet as will remain in beta.37 for now but it is possible that the error persist.

**Comment by nivida** [comment]
Thanks for submitting this issue. Will fix it next week after my vacation 👌🏻
