### ISSUE TITLE
Docs say to link "dist/web3.min.js" but there is no web3.min.js.

### ISSUE THREAD

**Issue by igormuba** [ethereum/web3.js#2383]
#### Expected behavior

Either give web3.min.js or update the docs on how to work without it.

#### Actual behavior
The docs right away teach how to do it using web3.min.js.

#### Steps to reproduce the behavior

1. do to docs > adding web3
2. it asks to link web3.min.js
3. there is no web3.min.js

#### Versions
web3.js 1.0

**Comment by OFRBG** [comment]
Most modern websites are built with stuff like webpack that minifies the JavaScript dependencies. My guess is that for now the web3 package won't include a web3.min.js file. If you want to use one, however, there's a way. There are packages such as https://www.npmjs.com/package/uglify-js or https://www.npmjs.com/package/browserify that can do it for you via CLI commands.

**Comment by nivida** [comment]
Sorry, didn't see this in the ``Getting Started`` section I will update the documentation. The longterm goal will be to improve the ``Getting Started`` section with starter projects etc. this should help most developers to get introduced to the DApp development without any pain.
