### ISSUE TITLE
Make possible use of client ssl certificates in HTTP Provider

### ISSUE THREAD

**Issue by constb** [ethereum/web3.js#2395]
**All issues which aren't created with this template will get immediately closed.**

#### Expected behavior

I'm using eth node on remote servers. HTTP RPC endpoint is behind nginx, which checks client ssl certificate to authorise access. I want Web3 HttpProvider to accept certificate options and use them when instantiating `https.Agent`.

#### Actual behavior

The only option that is currently passed to the Agent is `keepAlive`.

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Versions

Web3.js 1.0.0-beta46

**Comment by nivida** [comment]
Thanks for creating this issue! I will update the ``HttpProvider`` for allowing other options.
