### ISSUE TITLE
ERC20 token with multi signature wallet

### ISSUE THREAD

**Issue by anubnair** [ethereum/web3.js#2397]
**All issues which aren't created with this template will get immediately closed.**
I have  ERC20 token in my wallet(my custom contract for multi-signature). This wallet has some ERC20 token which I need to transfer to another using my multisignature wallet. Read some article (https://medium.com/coinmonks/customizing-and-using-multisig-contracts-for-other-contract-executions-9698fbb6950f)
My multisignature contract is similar to https://github.com/ConsenSys/MultiSigWallet/blob/master/MultiSigWalletWithDailyLimit.sol). 

So I have two contract address. One for my token and another one for token. What I did is given below:

# this is for 
1) let data = myContract.methods.transfer(destination, 1).encodeABI();

let rawTx = {
    gas: config.gas,
    gasPrice: config.gasPrice,
    "to": tokendContract,   (token contract)
    "from": "0xD854A6D99f5769B35104e50afd46877eC3A13918",
    "value": "0x00",
    "data": data,
    executed: false
}

2) submitTransaction (with signature1) 

let txObj = {
    gas: config.gas,
    gasPrice: config.gasPrice,
    data: txABI, (this is from step 1, 
    from: owner.address,
    to: contractAddress(multisignature contract address)
  };

3) confirmTransaction (with signature 2)

Everything is happening, but the token transfer is not happening. Basically, it is not detecting has a token transfer.

#### Expected behavior
Expecting a token transfer similar to https://rinkeby.etherscan.io/tx/0x95a5c50277ab36b2863f8d7c9e452a180729c508477e9791945e442aa6974936

But now, it is creating a contract for multisignature. But actual token transfer is not happening.

#### Actual behavior
token transfer

#### Steps to reproduce the behavior
mentioned above

#### Versions
Node: 10.14.2
NPM: 6.7.0
OS: mac
Web3: 1.0.0-beta.46

**Comment by OFRBG** [comment]
Could you link an actual transaction that has had this behavior? That would help a lot.

**Comment by nivida** [comment]
Will close this issue because the creator didn't answer. @OFRBG thanks for helping me out!
