### ISSUE TITLE
web3.extend() has been removed?

### ISSUE THREAD

**Issue by fixanoid** [ethereum/web3.js#2400]
#### Expected behavior
`web3.extend(module)` works

#### Actual behavior
`web3.extend` is undefined

#### Steps to reproduce the behavior
Looks like it has been removed since beta 38. Why? This is immediately useful and is used in multiple libraries. I can't seem to find any documentation either. Thanks!

#### Versions
NPM 1.0.0-beta40+

**Comment by nivida** [comment]
Yes, as described in the release note of [version 1.0.0-beta.38](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b). I'm currently writing the documentation for the Web3 Module API [here](https://github.com/ethereum/web3.js/pull/2236). Because of this I will close this issue.

**Comment by fixanoid** [comment]
A medium post thats a release note? I didn't stumble on it anywhere prior to your reply. And while this is helpful, it leaves many a module broken until maintainers update them or manual dependency resolution is made to the last working version. Why not leave it available and throw warnings for a while?
