### ISSUE TITLE
Encoding incompatibility in status transaction receipt

### ISSUE THREAD

**Issue by alepc253** [ethereum/web3.js#2401]
#### Expected behavior

Any transaction receipt with `0x01` as result should be considered successful. 

#### Actual behavior

Function `isValidReceiptStatus`  in `TransactionReceiptValidator.js` doesn't consider `0x01` as valid. 

#### Steps to reproduce the behavior

This is seen in an RSK node but could happen in any node that manages this type of hexa encoding. 

1. Connect to an RSK network (i.e. `https://public-node.testnet.rsk.co`)
2. Execute this command: `web3.eth.getTransactionReceipt("0x3f7c81902c008538d5c9f39115a31e14036fc6b9110899239660f074203f3cc1")`
3. Check in the receipt that status value is `0x01`

Therefore, if you apply `isValidReceiptStatus`  from `TransactionReceiptValidator.js` to that receipt, it will throw an exception with this message: "Transaction has been reverted by the EVM".

#### Versions
Truffle v5.0.4 (core: 5.0.4)
Solidity v0.5.0 (solc-js)
Node v11.10.
web3.js 1.0.0-beta.46

**Comment by nivida** [comment]
Thanks for creating this issue! I will check and fix it asap.
