### ISSUE TITLE
Cannot read property 'gasLimit' of null

### ISSUE THREAD

**Issue by arnasledev** [ethereum/web3.js#2402]
#### Expected behavior
It should return block info as I'm requesting it 
`this.server.eth.getBlock(number, false, async (error, data) => {`

#### Actual behavior
Sometimes it passes well and I get block info but sometimes it returns me the unhandled error message that `gasLimit` is not there

#### Steps to reproduce the behavior
```javascript
this.server = await new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws'))
return this.server.eth.getBlock(hash, false, async (error, data) => {
            if (error) {
                console.error('Error while getting block data: ' + error.message)
                console.warn(`Repeating block ${hash} after error`)

                return this.getBlockData(hash, repeated++)
            }

            if (!data || !data.transactions) {
                console.warn(`Repeating block ${hash} without transactions`)
                return this.getBlockData(hash, repeated++)
            }

            return data
        })
```

#### Error Logs
`(node:86385) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'gasLimit' of null`

#### Versions
npm - 6.1.0
node - v10.4.1
OS - macOS Mojave
device - macbook pro

```
"web3": "^1.0.0-beta.46",
    "web3-utils": "^1.0.0-beta.37"
```

**Comment by nivida** [comment]
The ``await`` before ``new Web3(...)`` is not needed and the ``callback`` method doesn't have to be ``async``. I think this will fix it.

``` javascript
this.server = new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws'));
return this.server.eth.getBlock(hash, false, (error, data) => {
            if (error) {
                console.error('Error while getting block data: ' + error.message)
                console.warn(`Repeating block ${hash} after error`)

                return this.getBlockData(hash, repeated++)
            }

            if (!data || !data.transactions) {
                console.warn(`Repeating block ${hash} without transactions`)
                return this.getBlockData(hash, repeated++)
            }

            return data
        })

```

**Comment by arnasledev** [comment]
Thanks, tried this but didn't worked either.

**Comment by nivida** [comment]
Could you add the complete code example which also includes my example? :)

**Comment by MatthewDarnell** [comment]
I'm getting the same behavior. I have been running an application for some time, but `getBlock` has been throwing this error quite often lately. Running a Parity node, connected via ssh port forward.

```
TypeError: Cannot read property 'gasLimit' of null

Error starting web3 interface on uri ws://127.0.0.1:8546: TypeError: Cannot read property 'formatters' of undefined
```

`"web3": "^1.0.0-beta.34"`

Yet sometimes it works fine.

**Comment by arnasledev** [comment]
Okey, so this is the methods in my class.

```javascript
async initWssServer(e = false) {
        if (e) {
            console.error('WSS disconnected')
            console.error(e)
        }

        this.server = new Web3('wss://mainnet.infura.io/ws')
        this.events = events

        const subscribe = this.server.eth.subscribe('newBlockHeaders')
        subscribe.on('data', (data, error) => this.receiveBlock(data, error))
        subscribe.on('error', e => this.initWssServer(e))
        subscribe.on('end', e => this.initWssServer(e))

        return true
    }

async receiveBlock(data, err) {
        if (err) {
            return this.initWssServer(err)
        }

        const transactions = await this.getBlockData(data.hash)
        const blockData = {
            number: data.number,
            hash: data.hash,
            transactions: transactions.transactions,
        }

        return this.events.emit('new_block', blockData)
    }

getBlockData(hash, repeated = 0) {
        console.log(`Retrieving block ${hash} data for ${repeated} times`)
        return this.server.eth.getBlock(hash, true, (error, data) => {
            if (error || !data || !data.transactions) {
                console.warn(`No data in block ${hash} for ${repeated} times`)
                return setTimeout(() => this.getBlockData(hash, repeated++), 2000)
            }

            return data
        })
    }
```

**Comment by arnasledev** [comment]
By the way, downgrading the package version to `1.0.0-beta.34` removed the "Cannot read property 'gasLimit' of null". There is something suspicious in the latest packages i think. Also as @MatthewDarnell mentioned above - this is the new problem. Few days ago with the same package there was no problems like this.

**Comment by dmihal** [comment]
Had this same issue start within the past few days, in my case it's not coming from `getBlock`, but from an event subscription.

Let me know if there's any more information I can provide.

**Comment by MatthewDarnell** [comment]
> By the way, downgrading the package version to `1.0.0-beta.34` removed the "Cannot read property 'gasLimit' of null". There is something suspicious in the latest packages i think. Also as @MatthewDarnell mentioned above - this is the new problem. Few days ago with the same package there was no problems like this.

I also reverted to `1.0.0-beta.34`. Works fine now.

**Comment by nivida** [comment]
Thanks all for the additional information! I will test and fix it asap.

**Comment by nivida** [comment]
The simple method below is doing what you want without a problem. Your second code example was also a implementation issue. The reconnecting and resubscribing is implemented in the WebsocketProvider of the Web3.js library and you don't have to care about since version beta.38.


Code Example:
``` javascript 
let web3 = new Web3('wss://mainnet.infura.io/ws');

function subscribeToNewHeadersAndDoStuff() {
  web3.eth.subscribe('newBlockHeaders').on('data', async (data, error) => {
    if (!error) {
      const block = await web3.eth.getBlock(data.hash, true);
      if (block !== null) { // getBlock returns null when the block couldn't be found.
        console.log('EMIT new_block EVENT: ', {
          number: data.number,
          hash: data.hash,
          transactions: block.transactions,
        });
      }
    }

    console.log('EMIT error EVENT: ', error);
  });
}
```
