### ISSUE TITLE
web3.eth.sendTransaction fails with TypeError on ubuntu, but works on Windows

### ISSUE THREAD

**Issue by lcinacio** [ethereum/web3.js#2409]
#### Expected behavior
It should work in both windows and Ubuntu

#### Actual behavior
It works fine on windows, but not on Ubuntu.

#### Steps to reproduce the behavior

Code to reproduce issue:
const Web3 = require("web3");

const web3 = new Web3("ROPSTENINFURAURL");

const account = web3.eth.accounts.privateKeyToAccount("MYPRIVATEKEY");
web3.eth.accounts.wallet.add(account);

web3.eth.sendTransaction({
        from: "MYADDRESS",
        gas: "21000",
        gasPrice: "15000000000",
        to: "TOADDRESS",
        value: "20000000000000000"})
.then ((result) => {
    console.log(result)
})
.catch ((error) => {
    console.error(error);
})

#### Error Logs
TypeError: Cannot create property 'from' on string '0xf86a29840bebc20082520894fe86cc3496d29766fdd21c5cb162ad24bac752e3876a94d74f4300008029a0d8b35110ec5ebac6d7ce4c308930c8e07f8e83be678acf7a602c434ec8d335b2a0757a58ad0d38cf51aa75079da944f918a6f37d43a610e8572c015b3b20f8cf48'
    at Object.inputTransactionFormatter (/TEP_mirroring_escrow/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:78:21)
    at SendTransactionMethod.beforeExecution (/TEP_mirroring_escrow/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1075:44)
    at SendTransactionMethod.execute (/TEP_mirroring_escrow/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1006:12)
    at /TEP_mirroring_escrow/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1100:85
    at process._tickCallback (internal/process/next_tick.js:68:7)

#### Versions
[NPM, Node, Web3.js, OS, device...]
NPM: 6.4.1
Node: v10.15.1
Web3.js: ^1.0.0-beta.46
OS: docker ubuntu:latest

**Comment by nirmalgupta** [comment]
I am also getting similar error when calling a method on contract.

**Comment by nivida** [comment]
Thanks for opening this issue. This got already fixed with https://github.com/ethereum/web3.js/pull/2393 and will be released next week.
