### ISSUE TITLE
`PromiEvent` event listener `on` `confirmations` not returning correct confirmation information 

### ISSUE THREAD

**Issue by joshstevens19** [ethereum/web3.js#2418]
#### Expected behavior

When i hook onto `PromiEvent` event listener on confirmations i get the correct confirmation number at the correct time not just random count of confirmations number every second.

#### Actual behavior

When i hook onto `PromiEvent` event listener on confirmations it seems its not inline with when the next block has been mined, on Rinkeby it's every 15 seconds but on web3 it returns the confirmation every second which is not correct.

```
web3.eth.sendSignedTransaction(rawTransaction)
.on(
            'confirmation',
            (confirmationNumber: number, receipt: TransactionReceipt) => {
              // fires new confirmation number up to 24 every second
            },
          )
```

It also states in the documentation that it stops the event listener firing after 12 confirmations yet it goes up to 24. 

This should be in line with the proper confirmations number and fire correctly and not just return a fake confirmation number every second.

#### Versions
1.0.0-beta.46

**Comment by nivida** [comment]
Thanks for creating this issue! 
This behavior is because you'are connected over a ``HttpProvider`` this means the ``NewHeadWatcher`` will just emit each second a ``new_head`` event. I thought about to improve it during the refactoring but didn't have the time. I will add a check which guarantees us that there was a confirmation. Thanks!

**Comment by ohopton** [comment]
Hey all.  

Does this return the number of confirmations or just the number of blocks that have been mined since the transaction was mined? 

What happens in the event of a re-org?

Apologies if this is the wrong place to ask questions!
