### ISSUE TITLE
Illegal typescript syntax in v beta.46

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2423]
I do not think that this is valid. My compiler throws an error. https://github.com/ethereum/web3.js/blob/2f0ada25b3988e67ec0d9a86a593146a57b43114/packages/web3-providers/types/index.d.ts#L119
```sh
A tuple type element list cannot be empty.
 subscribe(subscribeMethod: string, subscriptionMethod: string, parameters: []): Promise<string>;
                                                                            ~~
```
I wonder how this can pass CI. Maybe you are using a special setting for the linter?

**Comment by levino** [comment]
Looks like this has been [fixed already](https://github.com/ethereum/web3.js/commit/769f2e69c6ef30d0d79d88ecdc286e5624ea430b). Should be published asap. It is **not** a minor bug. One cannot use this code in a TypeScript project.

**Comment by nivida** [comment]
I've closed this because it got already fixed and will be released this week. I will first finish the eth-accounts module [improvements](https://github.com/ethereum/web3.js/pull/2367).
