### ISSUE TITLE
ReturnValues are parsed incorrectly after 1.0.0-beta.47 release

### ISSUE THREAD

**Issue by vedmant** [ethereum/web3.js#2440]
I have following event in the ABI:

```
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "name":"from",
        "type":"address"
      },
      {
        "indexed":false,
        "name":"value",
        "type":"uint256"
      },
      {
        "indexed":false,
        "name":"uuid",
        "type":"bytes32"
      }
    ],
    "name":"LogShielding",
    "type":"event"
  },
```

In the 1.0.0-beta.46 "from" field was parsed incorrectly, but all others were good.
After upgrade to 1.0.0-beta.47 "from" field was fixed, but "uuid" field started to show the value of "value" field but in hex format.

Values I expect to get:
```
'0': '0x12fb805833E14568f429386a3934247cb76b5F60',
'1': '1000000000000',
'2': ''0xb1c3f723a1620d739303ad11fd5b5340a0d367e51e1db6982e36ce2186b2c4f0',
from: '0x12fb805833E14568f429386a3934247cb76b5F60',
value: '1000000000000',
uuid: ''0xb1c3f723a1620d739303ad11fd5b5340a0d367e51e1db6982e36ce2186b2c4f0'
```

Actual values I actually get:
```
'0': '0x12fb805833E14568f429386a3934247cb76b5F60',
'1': '1000000000000',
'2': '0x000000000000000000000000000000000000000000000000000000e8d4a51000',
from: '0x12fb805833E14568f429386a3934247cb76b5F60',
value: '1000000000000',
uuid: '0x000000000000000000000000000000000000000000000000000000e8d4a51000'
```

Raw data is following:
```
0x000000000000000000000000000000000000000000000000000000e8d4a51000b1c3f723a1620d739303ad11fd5b5340a0d367e51e1db6982e36ce2186b2c4f0
```

You can see raw data includes uuid.

#### Expected behavior
Return correct returnValues

#### Actual behavior
Returns not correct returnValues

#### Steps to reproduce the behavior
Not sure about this

#### Versions
web3: 1.0.0-beta.47
node: v10.15.1
###

**Comment by nivida** [comment]
Thanks for creating this issue but this got already fixed with this PR: https://github.com/ethereum/web3.js/pull/2439.
