### ISSUE TITLE
Documentation for eth.signTransaction incorrect

### ISSUE THREAD

**Issue by strideynet** [ethereum/web3.js#2442]
#### Expected behavior
web3.eth.signTransaction(transactionObject [, address] [, callback])

Should be the signature according to the docs.
https://web3js.readthedocs.io/en/1.0/web3-eth.html#signtransaction

#### Actual behavior

Calling signTransaction(transactionObject, null) throws "The latest parameter should be a function otherwise it can't be used as callback".

Inspecting the source for web3.js/packages/web3-core-method/src/methods/transaction/SignTransactionMethod.js, it appears to only support one parameter.

Either the documentation is wrong, something else is wrong, or I'm confused.

#### Steps to reproduce the behavior

1. Run eth.signTransaction(transactionObject, null)
2. Observe error

#### Versions
Node

**Comment by OFRBG** [comment]
This is the origin of the error:

https://github.com/ethereum/web3.js/blob/fa51dc3ebd9ebd5962f9e3448bf9a3eb9f3f3774/packages/web3-core-method/lib/methods/AbstractMethod.js#L180-L186

You cannot pass null as a function parameter. The lodash method `isFunction` won't pass `null`. If you don't need a callback, maybe you could try using `.then()` and omitting the second parameter?

**Comment by strideynet** [comment]
I'm not passing null instead of the callback, we intended to pass null as the address. Even if we had given the address a string hex it would still have thrown the error, since a string is not a function.

As far as I can tell, the documentation is incorrect to suggest that its possible for the second parameter to be the address. 

@OFRBG

**Comment by OFRBG** [comment]
Ah, that's slightly different. It is true that the documentation suggests that the second parameter can be the signing address and ignore the callback.

I believe that the correct documentation interface should be

```js
web3.eth.signTransaction(transactionObject [, callback])
```

Alternatively, the implementation at 
https://github.com/ethereum/web3.js/blob/fa51dc3ebd9ebd5962f9e3448bf9a3eb9f3f3774/packages/web3-core-method/src/methods/transaction/SignTransactionMethod.js#L43-L45
could be modified to check for `this.parameters[1]` and check if it is a valid address, to then append it to `this.parameters[0]`.

```js
beforeExecution(moduleInstance) { 
     if(this.utils.isValidAddress(this.parameters[1]))
         this.parameters[0].from = this.parameters[1];

     this.parameters[0] = this.formatters.inputTransactionFormatter(this.parameters[0], moduleInstance); 
 } 
```

**Comment by nivida** [comment]
Thanks for creating this issue a providing all these details! I will check and fix it asap.

**Comment by strideynet** [comment]
> Ah, that's slightly different. It is true that the documentation suggests that the second parameter can be the signing address and ignore the callback.
--snip
> ```

Yeah, I was considering submitting a PR to fix it, but I needed to know if the documentation was correct or the code was to correct, to know which half needed fixing. It's quite hard to infer intent in these circumstances.

**Comment by nivida** [comment]
@strideynet The documentation was correct. Have a look at the [``CallMethod``](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/methods/CallMethod.js) class if you would like to see an example with optional parameters. This will get simplified when Web3.js has removed the callback methods from the public API.

**Comment by OFRBG** [comment]
But the documentation states that the interface is

```js
web3.eth.signTransaction(transactionObject [, address] [, callback])
```

for it to be accurate, shouldn't it be

```js
web3.eth.signTransaction(transactionObject [, address, callback])
```

It's either both or neither.

**Comment by nivida** [comment]
@strideynet @OFRBG I will check this with an older version of Web3.js and fix and release it asap.
