### ISSUE TITLE
Clean up google search links

### ISSUE THREAD

**Issue by biocrypto730** [ethereum/web3.js#2443]
Because Web3 has habitual breaking changes to its function calls, please be sure to update each and every ethereum stackexchange answer that doesn't use the modern syntax, also use the `Google Search Console` to remove all the outdated syntaxes

I have no idea if you think this is your responsibility or not, but consider that the way things are now, this library probably does more harm than good for the Ethereum community, due to all the breaking changes

**Comment by nivida** [comment]
Thanks for creating this issue! I'll check this asap.
