### ISSUE TITLE
Cannot deploy smart contracts using web3js and Infura

### ISSUE THREAD

**Issue by strawberry-code** [ethereum/web3.js#2446]
I try to deploy a contract using Infura and Web3js on Ropsten or Rinkeby:

```

const HDWalletProvider = require('truffle-hdwallet-provider');
const Web3 = require('web3');
const {interface, bytecode} = require('./compile');

const MNEMONIC = 'myprivatekey';

const provider = HDWalletProvider(MNEMONIC, "https://rinkeby.infura.io/v3/myinfuratoken");

const web3 = new Web3(provider);


const deploy = async () => {
    const accounts = ['0x8882528C7104e146E0500203C353C09922575385'];
    console.log(accounts);
    console.log('Attempting to deploy from account', accounts[0]);


    const result = await new web3.eth.Contract(JSON.parse(interface))
        .deploy({data:bytecode, arguments:['This is deployed!']})
        .send({gas:'1000000', from: accounts[0]});

    console.log('Contract deployed to ', result.options.address);
};
deploy();
```

Running this code I get:

>  (node:12321) V8: /Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/solc/soljson.js:3 Invalid asm.js: Invalid member of stdlib
> (node:12321) UnhandledPromiseRejectionWarning: Error: Provider not set or invalid
>     at Object.InvalidProvider (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-helpers/src/errors.js:38:16)
>     at RequestManager.send (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-requestmanager/src/index.js:128:32)
>     at sendRequest (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:563:42)
>     at /Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:580:17
>     at Object._fireError (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-utils/src/index.js:60:9)
>     at sendTxCallback (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:494:30)
>     at RequestManager.send (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-requestmanager/src/index.js:128:16)
>     at sendRequest (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:563:42)
>     at send (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:584:13)
>     at send (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-core-method/src/index.js:575:13)
>     at Object._executeMethod (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/node_modules/web3-eth-contract/src/index.js:896:24)
>     at deploy (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/deploy.js:19:10)
>     at Object.<anonymous> (/Users/sahelanthropus/IdeaProjects/deploy-contracts/test/deploy.js:23:1)
>     at Module._compile (internal/modules/cjs/loader.js:734:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
>     at Module.load (internal/modules/cjs/loader.js:626:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
>     at executeUserCode (internal/bootstrap/node.js:526:15)
>     at startMainThreadExecution (internal/bootstrap/node.js:439:3)
> (node:12321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:12321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Where my package.json is:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ganache-cli": "^6.2.5",
    "mocha": "^5.2.0",
    "solc": "^0.4.25",
    "truffle-hdwallet-provider": "0.0.3",
    "web3": "^1.0.0-beta.35"
  }
}
```

and:

npm 6.8.0
node v11.9.0

But I am able to deploy contracts using Truffle framework, same network configurations.

Why I cant deploy using Web3js?

**Comment by OFRBG** [comment]
~~It seems from this~~

~~https://github.com/trufflesuite/truffle-hdwallet-provider/blob/a6f5524fbc8c973df7828bda59c61c47e51a3bec/index.js#L10~~

~~that the provider already has a web3 instance. You should try to directly use the `provider` object.~~

I see your problem. This was an issue and was fixed, but you need to update your web3 version. Here's the original issue: https://github.com/ethereum/web3.js/issues/2266.

**Comment by chaitanyapotti** [comment]
@cristiano-c Using web3@1.0.0-beta.37 and truffle-hdwallet-provider@1.0.5 works
web3@1.0.0-beta.47 still seems to have some issues concerning web3.eth.getAccounts()

**Comment by nivida** [comment]
@cristiano-c The latest version beta.47 will work with the truffle provider. I was in contact with the truffle team and implemented a wrapper for the truffle provider based on the interface they gave me. 

@chaitanyapotti Could you explain your problem with ``getAccounts`` in a separate issue?

**Comment by imthatcarlos** [comment]
@chaitanyapotti can you confirm that you are having the issue I'm having? #2447 
@nivida check it out, should we let truffle team know?

**Comment by chaitanyapotti** [comment]
I can confirm it. having the exact same issue. @imthatcarlos

**Comment by nivida** [comment]
The PR https://github.com/ethereum/web3.js/issues/2447 will fix this and beta.48 will be released today.
