### ISSUE TITLE
CREATE2 support for smart contract deployment

### ISSUE THREAD

**Issue by chompomonim** [ethereum/web3.js#2448]
#### Expected behavior

I'd like to deploy smart contract into predefined address using [EIP 1014](https://eips.ethereum.org/EIPS/eip-1014). 

I expect something like:

```JavaScript
myContract.deploy2( { data, salt, arguments })
```

#### Current behavior
No support of EIP 1014

#### Versions
Web3.js v1.0.0-beta.46

**Comment by OFRBG** [comment]
I doubt it will be possible to just use `CREATE2` from the API. `CREATE` and `CREATE2` are EVM opcodes, so they are used in Solidity instead. You need to implement this with inline assembly as of now.

Further reading:
https://github.com/miguelmota/solidity-create2-example
https://solidity.readthedocs.io/en/latest/using-the-compiler.html?highlight=create2
https://solidity.readthedocs.io/en/latest/assembly.html?highlight=create2

**Comment by mikulas-mrva** [comment]
Closed for inactivity, are there any plans to implement this eventually?
