### ISSUE TITLE
Why is signature verification wrong????

### ISSUE THREAD

**Issue by lancesf** [ethereum/web3.js#2454]
Why is the hash information different？？？

Should 'sign' not first encrypt 'message' with 'keccak256', then if I want to encrypt 'keccak256', what should I do??

![ced61e9f-778f-4bc6-a8e3-1930287c6d0e](https://user-images.githubusercontent.com/24428154/53803972-3a1fbb80-3f81-11e9-8eb0-cc63f7e0e3fe.png)

**Comment by nivida** [comment]
Could you please use the issue template and provide all the information we need?

**Comment by nivida** [comment]
Closed because of the missing response of the creator and because the issue template was not used.
