### ISSUE TITLE
[1.0.0-beta.48] Contract.methods.myMethod.send() hangs forever

### ISSUE THREAD

**Issue by sebayaki** [ethereum/web3.js#2462]
### Description 
I'm using HDWalletProvider with Infura API, and when I use HTTP API like

```
const web3 = new Web3(new HDWalletProvider(P_KEY, `https://${NETWORK}.infura.io/v3/${INFURA_API_KEY}`));
const contract = new web3.eth.Contract(ABI, CONTRACT_ADDRESS);
contract.methods.transfer(ETH_ADDRESS, 12345).send(defaultOption)
    .on('receipt', (res) => { ... });
```

This sends the transaction correctly, but crashes after with

> Error: Subscriptions are not supported with the CustomProvider.

I saw "The HTTP provider is deprecated" on the web3 document, so I changed the Infura endpoint using Websocket:

```
const web3 = new Web3(new HDWalletProvider(P_KEY, `wss://${NETWORK}.infura.io/ws/v3/${INFURA_API_KEY}`));
```

This doesn't send the transaction at all and just hangs forever (no error, nothing happens).

#### Expected behavior
Calling 
```
contract.methods.transfer(ETH_ADDRESS, 12345).send(defaultOption).on('receipt', (res) => { ... });
```
should sent the transaction and `receipt` event should be triggered.

#### Actual behavior
It doesn't send the transaction and `receipt` event doesn't get triggered.

### Versions 
* web3.js: 1.0.0-beta.48
* nodejs: v11.10.1
* browser: console
* ethereum node: Infura websocket

**Comment by nivida** [comment]
Thanks for opening this issue! I will fix and release it asap.

**Comment by FilipLaurentiu** [comment]
what's the fix for this ? I have the same issue

**Comment by sebayaki** [comment]
@nivida any plan to release this fix with beta.49 soon?

**Comment by nivida** [comment]
@sydneyitguy Yes, after I've improved the transaction confirmation workflow for having better confirmations. I think this will happen this weekend or at the beginning of next week.

**Comment by FilipLaurentiu** [comment]
> @sydneyitguy Yes, after I've improved the transaction confirmation workflow for having better confirmations. I think this will happen this weekend or at the beginning of next week.

but this issue must be put on Open

**Comment by taoxinyi** [comment]
I have the similar problem that I can send the transaction and verify it in remix but it hangs when receiving the receipt.

**Comment by princesinha19** [comment]
@nivida I am getting the same error with **geth** when deploying contract using web3.eth.deploy. On event .on('receipt') it got stuck. Nothing happens after that 
But when using .on('transactionHash') it works. 

Also, when I use same .on('receipt') with **Ganache**, it works.

Web3 version: 1.0.0-beta.48
Should I use some other version? Please solve my issue.
