### ISSUE TITLE
web3.js does not work when building in vue production mode (likely any webpack production build)

### ISSUE THREAD

**Issue by mjdietzx** [ethereum/web3.js#2465]
### Description 
async web3 methods are never firing callbacks when built for production (vue cli 3 / webpack build). this also includes contract methods:
```javascript
const MyContract = new web3.eth.Contract(abi, address);
MyContract.methods.myFunction().call()
.then(console.log);
```

everything works properly when running in development/test mode. 

#### Expected behavior

This is when running my standard vue app https://cli.vuejs.org in development mode or locally:
`npm run serve` or `npm run build --mode development`

<img width="674" alt="screen shot 2019-03-07 at 9 45 08 am" src="https://user-images.githubusercontent.com/7217256/53943629-c6cf9400-40bd-11e9-8b9e-126af6ef8335.png">

#### Actual behavior

This is when running my vue app after building for production `npm run build`
<img width="680" alt="screen shot 2019-03-07 at 9 43 30 am" src="https://user-images.githubusercontent.com/7217256/53943695-fa122300-40bd-11e9-8959-5018b605175d.png">

#### Steps to reproduce the behavior

* initialize a vue app https://cli.vuejs.org
* init your `web3js` instance
* call `web3js.eth.net.getId().then(console.log).catch(console.error);`

#### Error Logs 
Not seeing any error logs. This is silently failing. Callbacks never triggered

### Versions 
* web3.js:
everything over 1.0.0-beta.37

* nodejs:
v11.6.0

* browser:
all browsers

* ethereum node:
metamask/infura. seems to effect all nodes (ie coinbase wallet, trust wallet)

**Comment by nivida** [comment]
Could you please fill out the complete issue template and provide further details with it for reproducing this behavior?

**Comment by mjdietzx** [comment]
Hey @nivida, I looked into this issue more and was able to simplify the description above (edited).

Thanks,
Mike

**Comment by mjdietzx** [comment]
I also think this issue is related to an issue I made earlier (although I'm not seeing these error messages I described in that issue anymore, and behavior seems slightly different) https://github.com/ethereum/web3.js/issues/2281

**Comment by lunochkin** [comment]
I have the same problem on `1.0.0-beta.48` with webpack production build in create-react-app based application.

It works fine in dev mode and throws `The object could not be cloned. && DOMException: Failed to execute 'postMessage' on 'Window'` error in production.

And if I check `web3js.eth.net.getId()` it gives pending Promise object as in the task description.

**Comment by lunochkin** [comment]
@mjdietzx Have you found any solution to the problem?

**Comment by mjdietzx** [comment]
@lunochkin unfortunately no. I am using `"web3": "1.0.0-beta.37"` and this works

**Comment by nivida** [comment]
@mjdietzx I've tested the production build with version beta.49 and it worked for me. Did you have the time to test it with the latest version?

**Comment by lunochkin** [comment]
@nivida, at least I can confirm that with beta.49 the production build works for me now. Thanks :)

**Comment by LandingMars** [comment]
@nivida I met the same problem, the details are as follows:
```
import Web3 from 'web3'
let web3 = new Web3(window.web3.currentProvider);
let contract = web3.eth.Contract(abi, addr);
contract.methods.buyTokens(address, code).send({
      from: address,
      value: value,
    }, (err, transactionHash) => {
      if (err) {
        console.log(err);
      }
    }).catch(err => {
         console.log(err);
    })
```
The error returned is as follows：
```
Error: No privateKey given to the TransactionSigner.
```
It is strange that  this error only appears  when built for production (vue cli 3 / webpack build). I tried several versions and found this to be the case.

**Comment by devstein** [comment]
@nivida I'm also encountering this issue for production react build using the latest `1.0.0-beta.50` build

**Comment by fireblockdev** [comment]
Problem with beta.50 on vuejs. No problem in dev but in production, it doesn't work.

**Comment by patitonar** [comment]
Similar issue for me when trying to call `sendTransaction` on production build for react app with version `1.0.0-beta.50`. Works ok in dev environment
```
TypeError: Cannot set property 'parameters' of undefined
    at e.<anonymous> (web3-core-method.umd.js:1354)
    at _ (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.t.(:8887/anonymous function) [as next] (http://127.0.0.1:8887/static/js/2.bfd5ff30.chunk.js:1:649401)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at e.<anonymous> (asyncToGenerator.js:21)
    at e.<anonymous> (web3-core-method.umd.js:1381)
```

**Comment by patitonar** [comment]
After upgrading to `1.0.0-beta.51`:
```
Error: No privateKey given to the TransactionSigner.
    at web3-eth.umd.js:40
    at _ (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.t.(:8887/anonymous function) [as next] (http://127.0.0.1:8887/static/js/2.094ff145.chunk.js:1:643910)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at e.<anonymous> (asyncToGenerator.js:21)
    at e.<anonymous> (web3-eth.umd.js:78)
```

**Comment by nivida** [comment]
Thanks for testing it @patitonar! [This](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js#L161 ) line is the bug. I will fix and release it asap.

**Comment by ShivamArora** [comment]
I'm facing the same issue as @patitonar  provided with version `1.0.0-beta.51`. 
Was facing the `DOMException` issue earlier the same as @lunochkin with the version `1.0.0-beta.48`. Then upgraded the version to `1.0.0-beta.51` and facing the `No privateKey given to the TransactionSigner` issue.

I'm waiting for this to be fixed.

For now, I've switched back to version `1.0.0-beta.37` and everything is working fine with it.

**Comment by KyleYao113** [comment]
> 1.0.0-beta.51



> I'm facing the same issue as @patitonar provided with version `1.0.0-beta.51`.
> Was facing the `DOMException` issue earlier the same as @lunochkin with the version `1.0.0-beta.48`. Then upgraded the version to `1.0.0-beta.51` and facing the `No privateKey given to the TransactionSigner` issue.
> 
> I'm waiting for this to be fixed.
> 
> For now, I've switched back to version `1.0.0-beta.37` and everything is working fine with it.

Can you post your code? I used 1.0.0-beta.37 or this error. I didn't know what to do for one day.

**Comment by ShivamArora** [comment]
@whatTheHellDie I'm away from my machine right now, so can't share the snippet.

But basically I was just trying to send a transaction on my contract using `mycontract.methods.someContractMethod(params).send({from:sender_address})`.

Downgrading to version `1.0.0-beta.37` worked for me.

Are you facing any problem with `1.0.0-beta.37`? I think @nivida has fixed the issue as it seems but I'm yet to try out the latest build.

**Comment by AyushyaChitransh** [comment]
Using 1.0.0-beta.37 does not resolve the issue. I still get errors.

**Comment by ShivamArora** [comment]
> Using 1.0.0-beta.37 does not resolve the issue. I still get errors.

Try using the following command: 
`npm install web3@1.0.0-beta.37 --save --save-exact --unsafe-perm=true`

**Comment by devedse** [comment]
@nivida , is this already released?

**Comment by nikhil3000** [comment]
@devedse Yes it is live. Just use 
`npm install web3@1.0.0-beta.52 --save --save-exact --unsafe-perm=true`
