### ISSUE TITLE
Utils functions mention BigNumber instead of BN in error messages

### ISSUE THREAD

**Issue by rhlsthrm** [ethereum/web3.js#2468]
### Description 
Error messages for utils functions `toWei`, `fromWei`, etc. throw the following error:
```
Please pass numbers as strings or BigNumber objects to avoid precision errors.
```
The source itself checks if they are BN, not BigNumber. Relevant source (others in this file as well): https://github.com/ethereum/web3.js/blob/1.0/packages/web3-utils/src/index.js#L193

#### Steps to reproduce the behavior

1. Import `web3`
2. Call `web3.utils.toWei(5)` (i.e. pass in a number or other non-allowed type).

### Versions 
* web3.js: 1.0.0 Beta 48

**Comment by nivida** [comment]
Yes, the documentation is wrong it's currently returning the BigNumber object but was always named BN. I will update the documentation and the related function documentation blocks.

**Comment by rhlsthrm** [comment]
It's also the thrown error messages (not sure if you are counting this in "documentation").

**Comment by interfect** [comment]
Since there is an `isBigNumber` in the source, with auto-conversion to BN e.g. [here](https://github.com/ethereum/web3.js/blob/599851753b4a35b5c11f902c7c592b111e190073/packages/web3-utils/src/SoliditySha3.js#L87-L88), why shouldn't `toWei` and `fromWei` accept BigNumber objects? Why force a manual conversion with `toBN`?

**Comment by nivida** [comment]
@rhlsthrm @interfect I can't really answer that because I do not the thoughts the former maintainer had. The whole BigNumber handling here in Web3.js will get improved asap.

**Comment by mqklin** [comment]
@nivida are you going to use `bignumber.js` or `BN`? I'm migrating to `beta` now, and now I have to convert all `BN` objects to `BigNumber`,  because `bignumber` is more convenient.
