### ISSUE TITLE
web3-eth-accounts/dist/web3-eth-accounts wording error

### ISSUE THREAD

**Issue by Senshii** [ethereum/web3.js#2469]
Hello,

It seems like there is a wording error with 'transactionSinger' instead of 'transactionSigner' at web3-eth-accounts/dist/web3-eth-accounts.cjs.js:77:70)

### Versions 
* web3.js: web3@1.0.0-beta.47 and web3@1.0.0-beta.48 
* nodejs: v10.14.2

Thank you,

**Comment by nivida** [comment]
Will be fixed with this PR: https://github.com/ethereum/web3.js/pull/2466

**Comment by nivida** [comment]
The wording error got fixed with PR #2466.
