### ISSUE TITLE
problem deploy the contract using web3js and infura

### ISSUE THREAD

**Issue by ahmedahmado** [ethereum/web3.js#2470]
const HDWalletProvider = require("truffle-hdwallet-provider");
const Web3 = require("web3");
const compiledFactory = require("./build/Factory.json");

const provider = new HDWalletProvider(
  'my mnemonic'
    , 'my url from infura'
);
const web3 = new Web3(provider);

const deploy = async () => {
  const accounts = await web3.eth.getAccounts();

  console.log("Attempting to deploy from account", accounts[0]);

  const result = await new web3.eth.Contract(
    JSON.parse(compiledFactory.interface)
  )
    .deploy({ data: "0x" + compiledFactory.bytecode })
    .send({ gas: "5000000", from: accounts[0] });

  console.log("contract deployed to", result.options.address);
};
deploy();
--------------------------------------------------------------------------------------
{
  "name": "finalproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fs-extra": "^7.0.1",
    "ganache-cli": "^6.4.1",
    "mocha": "^6.0.2",
    "solc": "^0.4.25",
    "truffle-hdwallet-provider": "0.0.4",
    "web3": "^1.0.0-beta.35"
  }
}
---------------------------------------------------------
Attempting to deploy from account 0x9B05cde81704dFADECdC0Ebd06779Bdf8cF76F7F
(node:15996) UnhandledPromiseRejectionWarning: Error: Subscriptions are not supported with the CustomProvider.
    at CustomProvider.subscribe (C:\Users\User\Desktop\finalProject\node_modules\web3-providers\dist\web3-providers.cjs.js:1139:13)
    at NewHeadsSubscription.subscribe (C:\Users\User\Desktop\finalProject\node_modules\web3-core-subscriptions\dist\web3-core-subscriptions.cjs.js:52:43)
    at NewHeadsWatcher.watch (C:\Users\User\Desktop\finalProject\node_modules\web3-core-method\dist\web3-core-method.cjs.js:180:110)
    at C:\Users\User\Desktop\finalProject\node_modules\web3-core-method\dist\web3-core-method.cjs.js:50:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
---------------------------------------------
do you think it is because your code or Infura website ? I'm facing this issue here but  I'm not sure what the reason is (truffle-hdwallet-provider or infura or something in my code).

**Comment by selectstarfrom** [comment]
I believe this bug has been already reported and fixed. 
Please refer issue [#2462](https://github.com/ethereum/web3.js/issues/2462) and [#2463](https://github.com/ethereum/web3.js/issues/2462)

**Comment by ahmedahmado** [comment]
to be honest , i dont have much experience in that , but the error massage 'Subscriptions are not supported with the CustomProvider. at CustomProvider.subscribe ' i thought it can be from infura because i check the code twice .

for issue #2462 and #2463 i think they are different.

**Comment by nivida** [comment]
I've implemented the CustomProvider with the given interface from the truffle team Please open an issue there to get further details.

**Comment by koptan** [comment]
hi , 

i am also facing the same issue , please any help ... 

```
Error: Subscriptions are not supported with the CustomProvider.
    at CustomProvider.subscribe (D:\coding\ethrum\Taturial\inbox\node_modules\web3-providers\dist\web3-providers.cjs.js:1139:13)
    at NewHeadsSubscription.subscribe (D:\coding\ethrum\Taturial\inbox\node_modules\web3-core-subscriptions\dist\web3-core-subscriptions.cjs.js:52:43)
    at NewHeadsWatcher.watch (D:\coding\ethrum\Taturial\inbox\node_modules\web3-core-method\dist\web3-core-method.cjs.js:180:110)
    at D:\coding\ethrum\Taturial\inbox\node_modules\web3-core-method\dist\web3-core-method.cjs.js:50:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
nodejs : v10.15.3
webjs:1.0.48-beta
