### ISSUE TITLE
Could not deploy library because library can't have constructor

### ISSUE THREAD

**Issue by nhannamsiu** [ethereum/web3.js#2477]
#### Expected behavior
   let instance = await myContract.deploy({
    data: artifact.bytecode,
  })
  .send(transactionConfig,(err, transactionHash) => {
    if (err) throw err
  })
Should return an instance of deployed library with valid address

#### Actual behavior
throw error: TypeError: this.methods.contractConstructor is not a function

#### Steps to reproduce the behavior
1. Library code attached on gist
2. Run ganache-cli with no extra flag
3. script to deploy
```
const Web3 = require('web3')
const fs = require('fs')

let web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8545'));
let artifact = JSON.parse(fs.readFileSync("./build/contracts/foo.json","utf8"))
let account = "0xda61864c67bdfd2e584cb6bd4b5d6c6153b13fba"

let transactionConfig = {from:account,gas:1000000,gasPrice:1}
let myContract = new web3.eth.Contract(artifact.abi)

myContract.deploy({data:artifact.bytecode})
.send(transactionConfig,(err, transactionHash) => {
    if (err) throw err
  })
  .then(async(readyContract)=> {
    console.log(readyContract.address)
  })
```

#### Gists
compiled json: https://gist.github.com/nhannamsiu/00aa8130e6b2aad6a79603b4ec237a53
solidity code: https://gist.github.com/nhannamsiu/880267847b61ef130d40247722d8e8d0

### Versions 
* web3.js: 1.0.0 beta 46
* nodejs: 8.15.0
* ethereum node: ganache-cli 6.4.1

**Comment by nivida** [comment]
Thanks for opening this issue! But this got already fixed with version beta.48.

The appended example of you is wrong, the correct way is:
``` javascript 
myContract.deploy({data:artifact.bytecode}).send(transactionConfig).then((readyContract)=> {
    console.log(readyContract.address)
}).catch(error => {
    console.log(error)
});
```
