### ISSUE TITLE
batch interface not working or documentation out-of-date

### ISSUE THREAD

**Issue by scottzer0** [ethereum/web3.js#248]
it's not clear to me how i'm suppose to build batch rpc commands. i'm getting requests that have no method set and empty params list.  
```
var batch = web3.createBatch();
batch.add(myContract.myMethod.request(param1, callback));
batch.add(myContract2.myMethod2.request(param1, param2, callback2));
batch.execute();
```
fails to work for me.  i get `jsonrpc has no method set` error and when looking at the network rpc request it does not have any method set and the params property is an empty list.

**Comment by SilentCicero** [comment]
I get the same.

**Comment by scottzer0** [comment]
while it's not clear in the documentation it's come to my attention that this interface may not support contract methods, which might explain my issue.

while i generally think batching any rpc requests is useful, it seems to me that calls to contracts methods would be the original use case.

perhaps this issue should be repurposed as "Please implement batching for contract methods".
