### ISSUE TITLE
Running webpack on web3 yields a ReferenceError when loaded

### ISSUE THREAD

**Issue by Freydal** [ethereum/web3.js#2480]
#### Expected behavior

Loading the web3 pack delivers a working Web3 class

#### Actual behavior

Thrown:
ReferenceError: self is not defined

#### Steps to reproduce the behavior

```
mkdir web3Test
cd web3Test
npm i web3 webpack webpack-cli
mkdir src
echo "module.exports = require('web3');" > src/index.js
webpack
node dist/main.js
```

### Versions 
* web3.js: 1.0.0-beta.35, 1.0.0-beta.37 and 1.0.0-beta.48
* nodejs: 11.9.0

I have tried multiple webpack configurations, but I always seem to get the same result.  Sorry if it is something silly on my end.

**Comment by nivida** [comment]
It delivers a working version of the Web3 class. I know this because I'm testing it with NodeJS and webpack. I think the problem is that you import and directly export the Web3 class. What exactly is the use case for directly exporting it again?

**Comment by Freydal** [comment]
This was just an example case to illustrate the issue.  I am using it regularly.  

Last night I found another project that was webpacking web3.  I tried to see if it still build correctly and it failed.  I believe this has something do with some system wide change.  The only change that comes to mind is updating npm to 6.9.0.

**Comment by nivida** [comment]
I'm using [this](https://github.com/ethereum/web3-examples/tree/development/starters/webpack)  webpack config and version beta.48 of Web3.js and it builds and runs without a problem. 🤔

**Comment by Freydal** [comment]
I will give this a try when I come back around to this problem.  Afterward if it is unresolved, I will try a different machine to see if it is something on my dev machine.

**Comment by DmytroNazarenko** [comment]
I have the same issue when try to import minified version of script, that requires web3, and call it as node script. It throws 
```
'ReferenceError: self is not defined'
```
Also, it works well on ubuntu 16.04, but not on the mac and ubuntu 18.04

**Comment by Freydal** [comment]
I was able to address my issue in a different way, but part of the my issue was my lack of understanding of the target.  The pack works fine in a Chrome, but node was a different story.
