### ISSUE TITLE
Why web3.shh.defaultGas function exist?

### ISSUE THREAD

**Issue by NAKsir-melody** [ethereum/web3.js#2481]
### Description 
In my understand, whisper messages does not spend gas &  does not use chain information
So IMHO, below functions should be removed to avoid miss-usage 

web3.shh.defaultBlock
web3.shh.transactionBlockTimeout
web3.shh.defaultGas 
web3.shh.defaultGasPrice
web3.shh.transactionConfirmationBlocks

**Comment by nivida** [comment]
These properties do exist because the ``shh`` module inherits from the ``AbstractWeb3Module``. This means you can ignore them. I will later create a ``AbstractEthModule`` class for being more specific.
