### ISSUE TITLE
web3.eth.requestAccounts() does not handle correctly a promise rejection

### ISSUE THREAD

**Issue by wmitsuda** [ethereum/web3.js#2487]
### Description

I'm using Chrome + latest Metamask, testing a small React application.

If I run this code (calling the plain Metamask provider API):

```js
    try {
      const accounts = await window.ethereum.send("eth_requestAccounts");
    } catch (err) {
      console.log("User cancelled");
      console.log(err);
    }
    return;
```

the user is presented with a popup window asking his permission to access the local account data, per EIP-1102.

If the user cancels the operation, the promise is rejected and is thrown as an error which is caught and a message is printed in the console.

If I try the following code, using web3js and the injected Metamask provider:

```javascript
    try {
      const web3 = new Web3(Web3.givenProvider);
      const accounts = await web3.eth.requestAccounts();
    } catch (err) {
      console.log("User cancelled");
      console.log(err);
    }
```

and the user cancels the operation, something unexpected happens inside web3js, the catch statement is bypassed because the code aborts with some internal error. See the following screenshot.

<img width="574" alt="Screen Shot 2019-03-11 at 10 18 05" src="https://user-images.githubusercontent.com/28685/54126736-04e2f580-43e7-11e9-8752-a1c8bbdc1ef6.png">

I guess the correct behavior would be to throw the rejection as an error so I can handle the user cancellation in the dapp UI.

### Versions 
* web3.js: 1.0.0-beta.48
* nodejs: 10.15.0
* browser: latest macos Chrome
* ethereum node: latest Metamask

**Comment by nivida** [comment]
Thanks for creating this issue! This got already fixed in my working branch. I will release it asap.

**Comment by nivida** [comment]
This got fixed with https://github.com/ethereum/web3.js/pull/2522
