### ISSUE TITLE
contractInstance.options.jsonInterface is undefined

### ISSUE THREAD

**Issue by rjkz808** [ethereum/web3.js#2494]
### Description

There's no JSON interface when I'm accessing the contract instance options.

#### Source code

```js
// The contract ABI and address are defined correctly,
// the web3 object is initialized correctly too
const contractInstance = new web3.eth.Contract(abi, address);
console.log(JSON.stringify(contractInstance.options));
```

#### Expected behavior

The above code should output all the contract options, including the JSON interface (ABI).

#### Actual behavior

The above code output is next:

```js
> {"transactionSigner":{"utils":{},"formatters":{}},"address":"0x58bFaAb4fe3D8CE06Eeb3d0A565aBF25c53db0Ce"}
```

As you can see, there's no `jsonInterface` in the logged options.

> Also, when I'm trying to access the JSON interface in code
> ```js
> contractInstance.options.jsonInterface.forEach(console.log);
> ```
> It throws a `TypeError: Cannot read property 'forEach' of undefined`

#### Steps to reproduce the behavior

This behavior is reproducible with any created contract instance, just try to access the `contractInstance.options.jsonInterface`.

### Versions 

* web3.js: `1.0.0-beta.48`
* Node.js: `10.15.1`
* Brave Browser: `0.60.48`
* Chromium: `72.0.3626.121` (Official Build) (64-bit)
* MetaMask: `6.2.2`

**Comment by nivida** [comment]
I've simplified the AbstractContract object to be consistent with the other module options and the jsonInterface property returns now an AbiModel with some additional methods to check for or to get a ABI item.

``` javascript
contract.jsonInterface
contract.address
contract.defaultAccount
contract.defaultGas
contract.defaultGasPrice
...
```

I could add the ``contract.options`` but the code behind the scene wouldn't be that clean. Is it also a solution for you when I keep it the way it is now and I'm updating the documentation? 

I apologize for this change and I'll give my best to write asap integration tests for having a proof that nothing breaks on a change.

**Comment by rjkz808** [comment]
> I've simplified the AbstractContract object to be consistent with the other module options and the jsonInterface property returns now an AbiModel with some additional methods to check for or to get a ABI item.
> 
> ```js
> contract.jsonInterface
> contract.address
> contract.defaultAccount
> contract.defaultGas
> contract.defaultGasPrice
> ...
> ```
> 
> I could add the `contract.options` but the code behind the scene wouldn't be that clean. Is it also a solution for you when I keep it the way it is now and I'm updating the documentation?
> 
> I apologize for this change and I'll give my best to write asap integration tests for having a proof that nothing breaks on a change.

Ok, I think new solution is better than the one that was before. The only thing you need to fix is web3 documentation. I hope you'll close this issue after that 😄
