### ISSUE TITLE
getPastEvents not working for named event

### ISSUE THREAD

**Issue by sirpy** [ethereum/web3.js#2495]
### Description   
  
Contract ABI has two definitions for the same event. I require **ERC20**'s `Transfer` events, but I'm getting **ERC677** ones.  
  
#### Expected behavior  
  
  
Calling `GoodDollar.getPastEvents('Transfer', { fromBlock: 0 })` should return say `200` events.  
  
#### Actual behavior  
  
  
Calling `GoodDollar.getPastEvents('Transfer', { fromBlock: 0 })` returns `60` events.  
  
I'm positive about this, as calling `GoodDollar.getPastEvents('allEvents', { fromBlock: 0 })` and then filtering by `Transfer` events, I got the `200` expected events.  
  
Even more, if instead of using `GoodDollar` ABI I use the `ERC20` ABI (from which `GoodDollar` inherits), I got the `200` events: `ER20.getPastEvents('Transfer', { fromBlock: 0 })`  
  
#### Steps to reproduce the behavior  
  
  
1. install `eth-cli` (`npm i -g eth-cli`)  
2. `eth ct:lc GoodDollar.json 0xa61C416d99Df07246c033534326F7Cfd8Ba5412a --url=https://rpc.fuse.io`  
3.  
```js  
var e = []  
GoodDollar.getPastEvents('Transfer', { fromBlock: 0 }).then(events => e = events)  
e.length // 60
```  
4. On a different terminal  
5. `eth ct:lc ER20.json 0xa61C416d99Df07246c033534326F7Cfd8Ba5412a --url=https://rpc.fuse.io`  
6.  
 ```js  
var e = []  
ERC20.getPastEvents('Transfer', { fromBlock: 0 }).then(events => e = events)  
e.length // 200
```  
7. Consider that the address for both cases is the same, both point to the deployed `GoodDollar` contract.  
  
#### Error Logs  
  
No error. I'm not being able to recover all the `Transfer` events.  
  
#### Gists  
  
ABIs:  
===  
https://github.com/GoodDollar/GoodContracts/blob/master/build/contracts/ERC20.json  
https://github.com/GoodDollar/GoodContracts/blob/master/build/contracts/ERC677.json  
https://github.com/GoodDollar/GoodContracts/blob/master/build/contracts/GoodDollar.json  
  
Contract:  
===  
https://github.com/GoodDollar/GoodContracts/blob/master/contracts/GoodDollar.sol  
  
### Versions  
* web3.js: `1.0.0-beta.46`  
* nodejs:  
* browser:  
* ethereum node:  
  
  
<!---------------------------------------------------------------------  
                    Thanks for your cooperation!

**Comment by nivida** [comment]
Could you please update your issue to be aligned with the issue template we provide and could you tell me which provider you are using?

**Comment by nivida** [comment]
Closed due to inactivity of the creator.

**Comment by sirpy** [comment]
so basically it looks like the issue is about parsing events defined in other super contracts or other contracts in general.
For example this also happens when using the erc677 transferAndCall if the call is causing an event of another contract to be emitted the event is in the raw logs but not in the parsed logs.
I would expect events from super contracts to be parsed correctly as they are part of the ABI

**Comment by sirpy** [comment]
@nivida can you reopen this?
