### ISSUE TITLE
HTTP Basic Authentication working in node but not client-side

### ISSUE THREAD

**Issue by dbblackdiamond** [ethereum/web3.js#2497]
### Description
I am porting an Dapp from Ethereum to an Ethereum-based blockchain that requires HTTP Basic Auth. I have HTTP Basic Auth working perfectly fine in node, but when I use the exact same code  in my HTML template for the client-side, it doesn't work. I get a 401 No Authorization error.
I am using web3js version 0.20.7 and the web3.js file that came with that version.

#### Expected behavior
Here is my node code:
```
Web3 = require('web3');
{ [Function: Web3]
  providers:
   { HttpProvider: [Function: HttpProvider],
     IpcProvider: [Function: IpcProvider] } }
> web3 = new Web3();
> provider = new Web3.providers.HttpProvider('https://xxxxxx.com/eth/', 5000, "username", "pw");
> web3.setProvider(provider);
> web3.isConnected();
true 
```

As you can see, the code works as web3 shows as being connected and I can interact with contracts, etc..

#### Actual behavior
Here is my javascript client-side code:
```
<script>
var Web3 = require('web3');
var web3= new Web3();
provider = new Web3.providers.HttpProvider('https://xxxx.com/eth', 5000, "username", "pw");
web3.setProvider(provider);
....
</script>
```
It is the same code as the node code and yet, it gives me this error whenever I try to interact with a contract:
```
HTTP401: DENIED - The requested resource requires user authentication.
(XHR)OPTIONS - https://xxxxx.com/eth/

 SCRIPT5022: CONNECTION ERROR: Couldn't connect to node https://xxxx.com/eth/.
```

### Versions 
* web3.js: 0.20.7
* nodejs: v10.15.1
* browser: Tried in Chrome and Edge with the same issue

Thoughts? What am I doing wrong? Is the web3.js file in the dist directory of the module the same version as the module? It looks to be, but I'd thought I'd ask anyway. :)

Thanks in advance for looking into this and for you time,
B.

**Comment by nivida** [comment]
Version 0.20.x had his last maintenance release some months ago. Please update to the latest version of Web3.js. If the error still occurs then please open a new issue.

**Comment by dbblackdiamond** [comment]
Hi,

thanks a lot for the response, but while I appreciate that 0.20.x has had its last maintenance release months ago, it is still the latest stable version as far as I know, so what you are telling me is that if someone wants to build an application using the latest stable version and runs into a problem, they are on their own? My experience is that projects will usually continue supporting their latest stable version until a new stable version is released, which doesn't seem to be the case here. That is very unfortunate.

**Comment by nivida** [comment]
@dbblackdiamond Currently, we have that state and I apologize for it. But I can't maintain a 0.20.x version and also bring out a 1.0 stable release in the next months. It does look like a configuration issue because the error isn't thrown from the Web3.js library. Please ask your question in our [Gitter](https://gitter.im/ethereum/web3.js) channel and the community and I will help you.
