### ISSUE TITLE
sendTransaction: unhandled promise rejection

### ISSUE THREAD

**Issue by dukei** [ethereum/web3.js#2500]
### Description 
sendTransaction does not handle promise rejection sometimes and it leads to compete calling application freeze.

#### Expected behavior
Any error inside sendTransaction should be propagated to the caller.

#### Actual behavior
https://github.com/ethereum/web3.js/blob/5023c450a783b892da862712e0d8dc26cddba4ab/packages/web3-core-method/src/methods/transaction/SendTransactionMethod.js#L80

The above line does not handle promise rejection that leads to complete freeze of application calling sendTransaction. The promise can be rejected in case of connection failure, for example.

#### Steps to reproduce the behavior
1. Set any provider that is shut down (you can even point it to inexistent url)
2. Try to call `web3.eth.sendTransaction(...)`

#### Error Logs 
`Unhandled promise rejection.... and stuff`

### Versions 
* web3.js: 1.0.0-beta.48
* nodejs: any
* browser: n/a
* ethereum node: n/a

**Comment by nivida** [comment]
Thanks for creating this issue! This will get fixed on the next release.

Could you update your issue to be aligned with the issue template we provide?

**Comment by dukei** [comment]
Issue updated.
