### ISSUE TITLE
Use regular functions and not arrow functions in the index.js file of the modules.

### ISSUE THREAD

**Issue by vladimiry** [ethereum/web3.js#2503]
https://github.com/ethereum/web3.js/blob/5023c450a783b892da862712e0d8dc26cddba4ab/packages/web3-eth/src/index.js#L76

https://github.com/ethereum/web3.js/blob/5023c450a783b892da862712e0d8dc26cddba4ab/packages/web3-eth/src/index.js#L87

In a clean not-transpiled environment such code will give you `TransactionSigner is not a constructor` error as arrow function cannot be acting as a class constructor::
```javascript
class EthTransactionSigner {}

const TransactionSigner = () => {
    return new EthTransactionSigner();
};

new TransactionSigner()
```

![worng-arrow-function-call](https://user-images.githubusercontent.com/1560781/54383447-27089c00-46a3-11e9-9638-d00544f79538.png)

It's currently only working probably because Babel transpiles arrow functions to a regular/ES5 functions which can be acting as class constructors.

I'd suggest renaming `TransactionSigner` and `MethodFactory` to something like `constructTransactionSigner` and `constructMethodFactory` functions and then calling them without using `new` but as a regular function calls.

**Comment by nivida** [comment]
First I had such factory methods in each index.js but I've removed them because it would break the API for the standalone modules. This will get improved with the implementation of the [``Web3 Namespace``](https://gist.github.com/nivida/c7c24723353c243e295dbff954d06b50). 

Edit: 
I'm using the same pattern also for internal classes to have a consistent way over all index.js files and yes it wouldn't work without babel.

**Comment by vladimiry** [comment]
Maybe then for the sake of explicitness simply using regular/ES5 functions as they can act as classes.

**Comment by nivida** [comment]
Yes, right I will improve this later. Currently, there are issues with a higher priority. :)

**Comment by nivida** [comment]
Changed this issue label to bug because it does not work with the arrow methods if you use a submodule module. 
Thanks for figuring this out!
