### ISSUE TITLE
Wrong comparison in MethodOptionsValidator.isValueValid?

### ISSUE THREAD

**Issue by vladimiry** [ethereum/web3.js#2504]
This this code line: https://github.com/ethereum/web3.js/blob/970d837768f924febe377df39824d2ab9e13a55a/packages/web3-eth-contract/src/validators/MethodOptionsValidator.js#L104

Is round brackets missed here around `method.parameters[0].value > 0`?

**Comment by nivida** [comment]
There is already an issue regarding this (https://github.com/ethereum/web3.js/issues/2488) and the fix will get released asap. I will close this issue because it's a duplication.
