### ISSUE TITLE
Shh newKeyPair first arg not optional

### ISSUE THREAD

**Issue by fireblockdev** [ethereum/web3.js#2507]
In the version 1.0.0-beta.48, the **web3.shh.newKeyPair** function needs a callback parameter even if you use the await syntax. Previously in the version 1.0.0-beta.37, it was optional as defined in the [Documentation](https://web3js.readthedocs.io/en/1.0/web3-shh.html#newkeypair).
It could be a documentation error but it seems weird to me.

**Comment by nivida** [comment]
Thanks for creating this issue! I'll change the parameters amount [here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/methods/shh/NewKeyPairMethod.js) to 0.
