### ISSUE TITLE
Whisper and IPCProvider (1.0.0 beta 48)

### ISSUE THREAD

**Issue by fireblockdev** [ethereum/web3.js#2508]
Whisper worked great with the IPC Provider until 1.0.0 beta 37. Because of ganache bug, i can't upgrade until 1.0.0 beta 48. With this version, i have strange behavior.

Every shh function return oboe errors:
Uncaught Error: Unexpected token o in JSON at position 1
      at Timeout._onTimeout (node_modules/oboe/dist/oboe-node.js:2325:17)

If i use the http or ws providers, it works great. 

geth version 1.8.15 
web3js: 1.0.0 beta 35 or beta 48

**Comment by nivida** [comment]
Thanks for creating this issue! I'll test and fix it asap.

**Comment by MaxFriedman17** [comment]
Hi, this happens to me as well.

I am using web3 1.0.0-beta.48 version and trying to connect using IPC provider to my local geth node. I just try to subscribe to new block headers and the same oboe error appears:

Error: Unexpected token o in JSON at position 1
    at Timeout._onTimeout (<path to oboe-node.js>)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

Regards!
