### ISSUE TITLE
web3.version.getNode() alternative in v1.0 using typescript

### ISSUE THREAD

**Issue by oancius** [ethereum/web3.js#2514]
### Description 
After updating from  "web3": "0.20.3" to 1.0.0-beta34 i can't find anymore a method to get the type of the node that i am connected to

#### Expected behavior

    Calling `await web3.version.getNode()` should return info about the node that you are connected to.

#### Actual behavior

    The method can't be found anymore

### Versions 
* web3.js: 1.0.0-beta34
* nodejs: v10.15.3
* browser: not related
* ethereum node: not related

**Comment by nivida** [comment]
The method exists on the ``web3.eth`` module with the name ``getNodeInfo``. I will update the documentation asap.

**Comment by oancius** [comment]
Thank you for the fast answer! Should i close the issue or it will be closed when the docs will be updated?

**Comment by oancius** [comment]
@nivida  oh well... the method it's not in web3.eth, at least not in the @types for web3 (1.0.18)

i will attach a screenshot with what is available in index.d.ts for web3.eth
![image](https://user-images.githubusercontent.com/20577110/54459226-af07a800-476e-11e9-9a83-94182c7df559.png)

**Comment by ghost** [comment]
`web3.eth.getNodeInfo()` will do the job

example)

```
async function detectNode() {
  var nodeInfo = await web3.eth.getNodeInfo();
  if (nodeInfo.split('/')[0].toLowerCase().includes('parity')) {
    console.log("Web3 has detected parity node configuration");
    web3explorer(web3);
  }
  console.log("Node version = " + nodeInfo); // logs `Node version = Parity-Ethereum//v2.4.0-beta-c7d8ee1-20190227/x86_64-linux-gnu/rustc1.32.0`
}
detectNode();
```

**Comment by oancius** [comment]
@btenterprise2020 i fully agree with you, but this can't be done in typescript because the the function wasn't added to the types file

**Comment by nivida** [comment]
@oancius I'll close this issue after I've updated the documentation and the types.

**Comment by oancius** [comment]
Thank you very much!

**Comment by oancius** [comment]
i guess a new verision of typings will be also published on https://www.npmjs.com/package/@types/web3
