### ISSUE TITLE
Return performance from function call

### ISSUE THREAD

**Issue by billtlee** [ethereum/web3.js#2515]
try {
    const receipt = await factory.methods.functionCall(
      web3.utils.fromAscii(field1),
      web3.utils.fromAscii(field2),
      field3
    ).send({
      from: accounts[0],
      value: web3.utils.toBN(web3.utils.toWei('0.01', 'ether'))
    });
    console.log('contract address: ', receipt.events.Created.returnValues);
  } catch (error) {
    console.log(error);
  }

For some reason, the console.log doesn't happen until minutes (around 3 - 5) after I get confirmation from metamask that the transaction succeeded.  Is it suppose to take this long?  I am using a factory to create a contract and am firing an event so that I can get the contract address from the event log.  Is there a way to speed this up?

### Versions 
* web3.js:
* nodejs:
* browser:
* ethereum node:

**Comment by billtlee** [comment]
By the way, I am using and deployed the contracts on rinkeby

    "truffle-hdwallet-provider": "^1.0.5",
    "web3": "^1.0.0-beta.48"

**Comment by billtlee** [comment]
So, I tried to send in more gas I sent in 20 gwei (gasPrice: '20000000000') to test and am getting almost instant response from metamask.  However, the console.log still took about 5 minutes after the metamask confirmation.  Does the gas price pass through from the factory to the contract creation or it will just get used for executing the function that creates the contract?

**Comment by nivida** [comment]
@billtlee Web3.js does wait for some blocks (default 24) until the transaction gets declared as confirmed. You're able to configure the number of blocks over the eth module [options](https://web3js.readthedocs.io/en/1.0/web3-eth.html#transactionconfirmationblocks).

**Comment by billtlee** [comment]
Hi Sam,
Thanks for getting back.  I tried to set the transactionConfirmationBlocks to 5 but it didn't make a difference.  It took 6 mins for the receipt to get back.  Am I doing anything wrong?

```
let web3;

const options = {
  transactionConfirmationBlocks: 5
}
web3 = new Web3(window.web3.currentProvider, options);
```
