### ISSUE TITLE
web3.eth.Contract documentation issue

### ISSUE THREAD

**Issue by llxxee** [ethereum/web3.js#2519]
The [documentation](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#options) of the `options` in `web3.eth.Contract` is not complete, some options like `transactionConfirmationBlocks` are missing in the documentation.
This is misleading because `web3.eth.Contract`  actually uses its own options (e.g.  `transactionConfirmationBlocks`) in `web3.eth.Contract.options` , not those in `web3.eth.options`.

**Comment by nivida** [comment]
Duplication of https://github.com/ethereum/web3.js/issues/2494
