### ISSUE TITLE
accessing constants from a contract

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#252]
For future:
I'm finding that dapps/frontends/JS have to duplicate the constants that a contract has.  If there was a mechanism that the JS could access them more directly, it would avoid duplication and potential errors.

For an example of more direct access, the JS already has access to the abi/contract description object ( first param of eth.contract https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract ).  If contract constants were also added to this object eg

```
var abi = [ { SUCCESS_FOO: 20, ERROR_BAR: 700 .... },
{
     name: 'myConstantMethod',
     type: 'function',
     constant: true,
     inputs: [{ name: 'a', type: 'string' }],
     outputs: [{name: 'd', type: 'string' }]}
} ...
```

then the JS could access constants like abi[0].SUCCESS_FOO

The above is simply demo of the idea and the mechanism/implementation could be very different.

**Comment by debris** [comment]
:+1:

**Comment by frozeman** [comment]
I guess this is a discussion we should move to the https://github.com/ethereum/interfaces repository and solc and how it generates the ABI. 

I will close this here, @ethers please reopen in these other places if you are still in favour of this.
