### ISSUE TITLE
Track transaction hash changed [Feature request]

### ISSUE THREAD

**Issue by k06a** [ethereum/web3.js#2525]
### Description 

I think web3 should handle if wallet resends tx with a different `gasPrice`. Transactions could be tracked by `from` (recovered from signature) and `nonce` instead of `transactionHash`, and in case of only `gasPrice` and `transactionHash` and `signature` changed it should succeed.

Also, it may be reasonable to add callbacks for `hashChanged` event.

#### Steps to reproduce the behavior

```js
const tx = await web3.eth.sendTransaction(...);
```

And resend Tx with same `nonce` bug different `gasPrice` using a wallet (MetaMask)

#### Expected behavior

Web3 to indicate when transaction succeed or reverted

#### Actual behavior

Web3 does not indicate when transaction succeed or reverted

### Versions 
* web3.js: 1.0.0-beta.48

**Comment by nivida** [comment]
Could you update your issue to be aligned with the issue template we provide?
I like this idea. It would be possible with extending of the [``TransactionObserver``](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/observers/TransactionObserver.js) and [``AbstractObservedTransactionMethod``](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js) class.

**Comment by k06a** [comment]
@nivida updated 👌

**Comment by mjdietzx** [comment]
Also observing this behavior. web3 is not catching the completion of a transaction. promise never resolves when you `send` a transaction

**Comment by mjdietzx** [comment]
simple to reproduce:

`const promise = contract.methods[method](...args).send();`

promise never resolves. tested in chrome with metamask. using vue/webpack and latest web3

still stuck on web3 beta 0.37 which works

**Comment by k06a** [comment]
Any updates?

**Comment by k06a** [comment]
Oh no 😔

**Comment by ryanio** [comment]
@k06a check out https://github.com/ethereum/web3.js/issues/3585#issuecomment-664624241
