### ISSUE TITLE
Getting Error: Invalid bytes string given: 0x [web3@1.0.0-beta.48] on simple Solidity view function

### ISSUE THREAD

**Issue by netpoe** [ethereum/web3.js#2527]
*I've looked into the other issues related to this error, but this is caused by something different

### Description

Using `web3@1.0.0-beta.48` I have the following contract function: 

```
pragma solidity ^0.5.2;

contract Versioned {
    string[] public data; // when deployed, data already has 1 item

    function getVersionIndex() public view returns (uint count) {
        return data.length - 1;
    }
}
```

The Web3 code is: 

```
  const versionIndex = await contract.getVersionIndex();

  // ...
  public getVersionIndex(): Promise<any> {
    return this.contract.methods.getVersionIndex().call(); 
  }
```

Contract class already has an address and the method does not require any params. 

I've tried adding the `{ from: "0xadress" }`, but it makes no difference. 

#### Expected behavior

Return the value of the Solidity `data.length` as `uint count`. 

As a note, I've debugged the contract using https://remix.ethereum.org/ and the `getVersionIndex()` function works as expected.

#### Error Logs 

The error is originating at `AbiCoder.decodeParameters` of `web3-eth-abi.umd.js:65`: 

```
key: "decodeParameters",
      value: function decodeParameters(outputs, bytes) {

        if (!bytes || bytes === '0x' || bytes === '0X') {
          throw new Error("Invalid bytes string given: ".concat(bytes));
        }
```

### Versions 
* web3.js: web3@1.0.0-beta.48
* nodejs: v10.15.3
* browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit) MaxOSX
* ethereum node: Ropsten test network with Metamask

**Comment by nivida** [comment]
Will check this closer asap.

**Comment by koderholic** [comment]
I'm having exactly the same issue. @nivida what clarification do you need?

**Comment by Karandeep-singh-saini** [comment]
I'm too facing same issue , Is there any update on this?

**Comment by tgreco** [comment]
Same issue.

**Comment by rajeshsubhankar** [comment]
Same for me. Works fine after downgrading to `web3@1.0.0-beta.27`

**Comment by HoangJerry** [comment]
I still get it on beta 51
 Error: Uncaught (in promise): Error: Invalid bytes string given: 0x
Error: Invalid bytes string given: 0x

**Comment by HoangJerry** [comment]
![image](https://user-images.githubusercontent.com/27281406/55540646-98110180-56ed-11e9-9b37-9ee98b3fbc2f.png)

**Comment by jbtobar** [comment]
Similar issue with beta-58 
```Error: Invalid bytes string given: undefined```

**Comment by sumitpatel93** [comment]
> Same for me. Works fine after downgrading to `web3@1.0.0-beta.27`

I think downgrading and upgrading shouldn't be the solution for this problem.
