### ISSUE TITLE
npmjs package 1.0.0-beta.49 return 1.0.0-beta.48

### ISSUE THREAD

**Issue by fireblockdev** [ethereum/web3.js#2533]
I have upgraded to 1.0.0-beta.49 in package.json ( "web3": "1.0.0-beta.49" )

The file node_modules/web3/dist/web3.cjs.js contains:
```
...
var version = "1.0.0-beta.48";
...
```
So when a create a provider, the version is 1.0.0-beta48.

**Comment by nivida** [comment]
I apologize for the troubles. I will fix this on the next release.

**Comment by nivida** [comment]
Got fixed with the latest release.
