### ISSUE TITLE
Documentation: contract.deploy.estimateGas arguments and return type incorrect

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2543]
### Description 

If you want to estimate the gas of an contract you need to pass an callback to the function according to the documentation: https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#deploy.

But this is not working. The function returns a promise instead.

#### Expected behavior

Documentation says:

```
// Gas estimation
myContract.deploy({
    data: '0x12345...',
    arguments: [123, 'My String']
})
.estimateGas((err, gas) => {
    console.log(gas);
});
```

#### Actual behavior

`estimateGas` returns a promise and doesn't accept a callback. The following code is working:

```
myContract.deploy ({
    data: myBytecode,
    arguments: ['arg1']
})
.estimateGas ()
.then (console.log);
```

#### Error Logs 

`Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': (e, g) => console.log (g) could not be cloned.`

### Versions 
* web3.js: `web3.beta.46`
* browser: `Chromium`

**Comment by nivida** [comment]
Does this error still occur with the latest version of Web3.js? (1.0.0-beta.50)

**Comment by ghost** [comment]
@nivida I tried it today with `1.0.0-beta.50` and got the same behaviour.

**Comment by nivida** [comment]
We have planned to remove the callback support until the stable release. Any further discussion about the callback support can be held here: https://github.com/ethereum/web3.js/issues/2224

**Comment by nivida** [comment]
The reason for the closing of this issue is explained in the referenced PR.
