### ISSUE TITLE
Document web3.eth.getNodeInfo()

### ISSUE THREAD

**Issue by sohkai** [ethereum/web3.js#2544]
# Description
The documentation for the JSON-RPC method `web3_clientVersion` on the Eth module is missing.

## Expected behavior
The Web3.js documentation does contain the method `web3.eth.getNodeInfo()`.

## Actual behavior
The Web3.js documentation does not contain the method `web3.eth.getNodeInfo()`.

## Steps to reproduce the behavior
Check the Eth module documentation

**Comment by nivida** [comment]
Thanks for opening this issue but this is a duplication of https://github.com/ethereum/web3.js/issues/2514 :)
