### ISSUE TITLE
Rename DeployTransactionResponse

### ISSUE THREAD

**Issue by dileepfrog** [ethereum/web3.js#2551]
### Description

This interface can be used to estimate gas and encode ABI data for *any* Ethereum tx other than a simple ETH transfer, not just contract depoys. Perhaps a better name would be `TransactionData`

**Comment by nivida** [comment]
I think a name like ``TransactionMethod`` would be more accurate.

Edit: Or even more specific ``ContractSendMethod``

**Comment by dileepfrog** [comment]
The contract method is actually bound to specific arguments in this object, so it's more an `Invocation` than just `Method`, of course I'm just splitting hairs now 😛
