### ISSUE TITLE
TransactionConfig has incorrect from type

### ISSUE THREAD

**Issue by dileepfrog** [ethereum/web3.js#2552]
### Description

The `from` type allows both string and number, however this field must be a valid 0x-prefixed hex string

https://github.com/ethereum/web3.js/blob/9abc01feb1db7989d4f71b438919bc6497370f53/packages/web3-core/types/index.d.ts#L133

**Comment by nivida** [comment]
This is correct because you could also pass the index of an unlocked account. The account index will be used for signing the transaction locally.

**Comment by nivida** [comment]
It's also described here: 
https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendtransaction
