### ISSUE TITLE
The parameters that are sent to eth_sign is swapped

### ISSUE THREAD

**Issue by samueltangz** [ethereum/web3.js#2555]
### Description 

According to the documentation, the parameters for `web3.eth.sign` would be `dataToSign` and `address` [[1]](https://github.com/ethereum/web3.js/blob/v1.0.0-beta.50/packages/web3-eth/src/methods/EthSignMethod.js)[[2]](https://github.com/ethereum/web3.js/blob/v1.0.0-beta.50/packages/web3-core-method/src/methods/SignMethod.js)[[3]](https://github.com/ethereum/web3.js/blob/v1.0.0-beta.50/packages/web3-core-method/lib/methods/AbstractMethod.js).

However, for `eth_sign`, the parameters in order should be `address` and `data`; which is reversed compared to the given `web3.eth.sign` [[4]](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign).

From [1] to [3], the order of parameters are not swapped.  For versions prior to 1.0.0-beta.37, it seems to be handled.

#### Expected behavior

Either one of the following should work:
1. `web3.eth.sign('hello', '0xBCe00FD336be3be338458e93EfC80Da14f8a3e05')` (according to the documentation);
2. `web3.eth.sign('0xBCe00FD336be3be338458e93EfC80Da14f8a3e05', 'hello')` (according to the RPC)
would work.

#### Actual behavior

In the current (recent) versions, none of the above works:

When calling `web3.eth.sign('hello', '0xBCe00FD336be3be338458e93EfC80Da14f8a3e05')`, it shows
```
MetaMask - RPC Error: Error: WalletMiddleware - Invalid "from" address.
```

Yet, when calling `web3.eth.sign('0xBCe00FD336be3be338458e93EfC80Da14f8a3e05', 'hello')`, it shows
```
Error: Provided address "hello" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
```

I am testing with the MetaMask provider, but I tried [HookedWalletSubprovider](https://github.com/MetaMask/web3-provider-engine/blob/master/subproviders/hooked-wallet.js) and it doesn't work too.

### Versions 
* web3.js: 1.0.0-beta.50 (probably since 1.0.0-beta.38)
* nodejs: v10.15.3
* browser: Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by angus-hamill** [comment]
https://github.com/ethereum/web3.js/pull/2547
