### ISSUE TITLE
this.getGasPrice is not a function; GasPriceMethod vs GetGasPriceMethod

### ISSUE THREAD

**Issue by Fang-** [ethereum/web3.js#2558]
This is on version `1.0.0-beta.50`. Trying to sign a transaction fails with:

```
(node:87086) UnhandledPromiseRejectionWarning: TypeError: this.getGasPrice is not a function
    at Proxy._callee$ (/path/to/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:387:29)
```

I looked into the code that stack trace is pointing to, and it seems `getGasPrice` is indeed undefined there. I found a fix for it, but it feels a bit too straight-forward, so I'm suspicious I'm just doing something dumb. If someone could do a sanity check on the below that'd be great.

Shouldn't [this](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-accounts/src/factories/MethodFactory.js#L34) say `GetGasPriceMethod` instead, in line with [this](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/index.js#L42)?

**Comment by nivida** [comment]
Thanks for opening this issue! I'll fix it tomorrow and will release it asap.
