### ISSUE TITLE
RangeError parsing of 0x

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#256]
https://github.com/ethereum/go-ethereum/issues/1421

Per above, using the latest geth, when a result is 0x, a RangeError is being thrown
```
RangeError
    at <unknown>
    at <unknown>
    at <unknown>
    at formatInput (<anonymous>:-100809:-18)
    at toPayload (<anonymous>:-101988:-18)
    at getCode (<anonymous>:-102665:-18)
    at <anonymous>:1:1
```

**Comment by frozeman** [comment]
Could you try to reproduce this in the browser console?

**Comment by ethers** [comment]
closing, i think this was caused by passing the result of eth_sendTransaction to eth_getCode, which is no longer "allowed" because eth_getCode requires an address, and eth_sendTransaction 0.9.36 returns a transaction hash (whereas 0.9.35 returned an address if tx was contract creation)
