### ISSUE TITLE
Duplicated events when using contract.events.MyEvent

### ISSUE THREAD

**Issue by Jaime-Iglesias** [ethereum/web3.js#2561]
### Description 
When using myContract.events.MyEvent([options][, callback]) to listen to two completely different events i get duplicated events from both listeners.

 ``` depositListener() {
        this.props.exchangeContract.events.LogDepositToken({
            filter: { _user: this.props.userAccount }
        })
        .on('data', (event) => {
                this.setState({
                    fundsEventList: this.state.fundsEventList.concat(this.eventFormater(event)),
                });
        })...
  withdrawListener() {
        this.props.exchangeContract.events.LogWithdrawToken({
            filter: { _user: this.props.userAccount }
        })
        .on('data', (event) => {
                this.setState({
                    fundsEventList: this.state.fundsEventList.concat(this.eventFormater(event)),
                });
        })
```
So i've tried a couple more things and the problem, which at first I though was that both listeners where triggering each others events, is that when both listeners are active the events inside each listener (i.e only the Deposit in the first one, and Withdraw in the second one) get duplicated.

I've tried adding conditions, like checking that the TransactionHash for the event is not already present in the eventList, but it doesnt work,

I've also deleted the setState part and tried only with logs, the same happens.

For example if i use the next code:

```        
    depositListener() {
        this.props.exchangeContract.events.LogDepositToken({
            filter: { _user: this.props.userAccount }
        })
        .on('data', (event) => {
                /*this.setState({
                    fundsEventList: this.state.fundsEventList.concat(this.eventFormater(event)),
                });*/
                console.log(1);
                console.log(event);
        })
```

in console I'd get.

`1
{logIndex: 0, transactionIndex: 0, ...)
1
 {logIndex: 0, transactionIndex: 0, ...)`

Then if i comment the other listener:

`1
{logIndex: 0, transactionIndex: 0, ...)`

I've also checked if I'm calling the Listeners twice and it's not the case.

#### Expected behavior

Events inside each listener should only be triggered once.

#### Actual behavior

Duplicated events for both.

#### Solution

For now I've found that commenting one of them, makes the other behave as expected, although this is not a solution.

### Versions 
* web3.js: web3.1.0.0-beta-36, beta-50.
* browser: Chrome

**Comment by nivida** [comment]
Did you also test it with version beta.50?

Edit: 
A bigger [refactoring](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) happened with version beta.38.

**Comment by Jaime-Iglesias** [comment]
No, for now sticking to 36, I will give it a go tomorrow, thx for the
advice.

**Comment by Jaime-Iglesias** [comment]
> Did you also test it with version beta.50?
> 
> Edit:
> A bigger [refactoring](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) happened with version beta.38.

Tried with beta.38, was getting other errors (specifically getting networkId), changed to beta.50 still same prblem.

**Comment by nivida** [comment]
> Did you also test it with version beta.50?

Could you please use the latest version as said.

**Comment by Jaime-Iglesias** [comment]
> > Did you also test it with version beta.50?
> 
> Could you please use the latest version as said.

I said in the previous comment, that i tried the beta.50 and i still have the same problem. Maybe you didn't see it.

**Comment by iamtheoneaboveall** [comment]
@Jaime-Iglesias

Have you figured out a correct solution for this?

**Comment by Jaime-Iglesias** [comment]
@iamtheoneaboveall i'm afraid (from what i've tried) that it still triggrers events as many times as the number of listeners you have, the workaround i've found to work for now, is to use the eventEmitter from contract.method.send(), you can see an example in this other issue i opened a while back: https://github.com/ethereum/web3.js/issues/2680 i hope that helps you!

**edit:**
To elaborate a bit more, the receipt returned by the transaction, contains the events triggered during it's execution, you can see it in the docs here: https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id21

**Comment by NavyAdmiral** [comment]
@nivida This is an issue on .52 too. Subscribing to two different `contract.events.Event1` and `contract.events.Event2` will result in duplicate events received. Nothing I've tried has helped me resolve it

**Comment by Jaime-Iglesias** [comment]
@NavyAdmiral I think you are better off writing an issue yourself and refering to this one, this has been closed for a while now.

**Comment by nikosft** [comment]
I am wondering why this issue is closed. It still exists in 1.2.0

**Comment by miquelTC** [comment]
Is this topic still open? I am having the same issue...

**Comment by dsgriffin** [comment]
same issue, duplicate events when using a basic event listener on a contract
