### ISSUE TITLE
Returning of BigNumber objects instead of strings

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2570]
### Description 

It's returning strings instead of BigNumber objects on a contract method call.

#### Expected behavior

Returns a BigNumber object instead of a string.

#### Actual behavior

Returns a number as string.

#### Steps to reproduce the behavior

``` javascript
contract.methods.method().send().then(console.log);
```

#### Error Logs 
-

### Versions 
* web3.js: latest

**Comment by Anaphase** [comment]
Man, this breaking change really messed up my codebase :(

**Comment by nivida** [comment]
Yes, I see your point. But the decision was between a working react native production build or this breaking change. This was the reason why I‘ve decided to release this breaking change. I‘ve apologize for the troubles.

**Comment by levino** [comment]
IMO: It would be much better if only **strings were returned or required** by all methods of `web3`.
