### ISSUE TITLE
Accounts.getGasPrice() invocation error in Accounts.signTransaction()

### ISSUE THREAD

**Issue by mmshihov** [ethereum/web3.js#2578]
### Description
I've got the error when I specify `gasPrice:0` in raw tx object to be signed by `web3.eth.accounts.signTransaction()`. Example code snippet:

    let tx = {
        ... 
        gasPrice: 0, // it is OK in JP Quorum blockchain
        ...
    }

    let signedTx = await web3.eth.accounts.signTransaction(tx, privateKey);

#### Expected behavior
Signed tx object in`signedTx` variable.

#### Actual behavior

    TypeError: this.getGasPrice is not a function at Proxy._callee

Also it may be worthwhile to change the condition for checking the `tx.gasPrice`:

            // web3.js/packages/web3-eth-accounts/src/Accounts.js:128
            if (!tx.gasPrice) {
                tx.gasPrice = await this.getGasPrice();
            }

The condition is true if `ts.gasPrice` directly specified by user as 0. May be somthing like:

            if ((typeof tx.gasPrice == "undefined") || (tx.gasPrice < 0)) {
                tx.gasPrice = await this.getGasPrice();
            }

### Versions 
* web3.js: 1.0.0-beta.50
* nodejs: v8.11.3
* ethereum node: JP Quorum

**Comment by nivida** [comment]
This got already fixed and will be released this week.  PR: https://github.com/ethereum/web3.js/pull/2566

**Comment by nivida** [comment]
Sorry, didn't saw the last example. Will fix it asap.

**Comment by mmshihov** [comment]
Thanks
