### ISSUE TITLE
Add compiler "optimize" parameter

### ISSUE THREAD

**Issue by tgerring** [ethereum/web3.js#258]
For compilers that support optimisation (such as Solidity), users should be able to enable this option.

Suggest to add second parameter to the compile Solidity functions in web3.js and RPC which exposes this optional boolean parameter to the user, defaulting to false.

The argument to enable this with solc is `--optimize 1`

**Comment by frozeman** [comment]
As solidity compilation is soon not part of geth and the RPC api anymore and using solc directly is encouraged, i will close this here
