### ISSUE TITLE
npm install web3@1.0.0-beta.50 fails

### ISSUE THREAD

**Issue by j4ys0n** [ethereum/web3.js#2581]
### Description 
npm install web3@1.0.0-beta.50 fails

#### Expected behavior
npm install web3@1.0.0-beta.50 should succeed

#### Actual behavior
```
npm install web3@1.0.0-beta.50
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/truffle-contract/node_modules/web3/bignumber.js@git+https:/github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934" as it does not contain a package.json file
```

#### Steps to reproduce the behavior
`npm install web3@1.0.0-beta.50`

#### Error Logs 

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/truffle-contract/node_modules/web3/bignumber.js@git+https:/github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934" as it does not contain a package.json file
```

on navigating to https:/github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934, there is a package.json file. 

### Versions 
* web3.js: 1.0.0-beta.50 (also tried previous versions)
* nodejs: 11.12, 11.11, 11.2
* browser: n/a
* ethereum node: n/a

**Comment by nivida** [comment]
Could you please update your issue to be aligned with the issue template we provide?

**Comment by j4ys0n** [comment]
@nivida done

**Comment by j4ys0n** [comment]
looks like my package-lock.json was pinning an old version of `truffle-contract`. deleted package-lock.json and ran `npm install` again. good to go.
