### ISSUE TITLE
Web3() error with 1.0.0.beta50

### ISSUE THREAD

**Issue by fireblockdev** [ethereum/web3.js#2584]
The constructor with a provider works but not the default constructor Web3().
It's used in many unit tests in ganache-core.

```
/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-providers/dist/web3-providers.cjs.js:49
      if (provider.sendPayload && provider.subscribe) {
                   ^
TypeError: Cannot read property 'sendPayload' of undefined
    at ProviderResolver.resolve (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
    at Web3.AbstractWeb3Module (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
    at new Web3 (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3/dist/web3.cjs.js:30:68)
```

This ticket is related to this one: https://github.com/ethereum/web3.js/issues/2573

**Comment by nivida** [comment]
Could you please add a code example? I think you forgot to add a provider.

**Comment by Skyge** [comment]
Yeah, agree with `nivida`

**Comment by ellis2424** [comment]
@Skyge This is not the place to discuss if there is a need for a Web3(). @nivida said Web3() was a valid syntax, so it should work.
The syntax with providers works.

**Comment by nivida** [comment]
It was a bug and not a feature. The provider parameter was not declared as an optional parameter in the documentation. https://web3js.readthedocs.io/en/1.0/web3.html

**Comment by fireblockdev** [comment]
Ok. Thus, many projects like ganache must use the new syntax. I'll create a ticket on their project.

**Comment by barakman** [comment]
This is also the case for beta52.

I wouldn't normally bother about this, since I'm hanging on to a much earlier version (beta34) .

But now `npm install` encourages the user to upgrade to beta52:
```
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

Which brings me to the point where I have to move forward, but cannot, due to this issue.
