### ISSUE TITLE
privateKeyToAccount does not return what is in the doc

### ISSUE THREAD

**Issue by stefdelec** [ethereum/web3.js#2590]
### Description 

I initiate a wallet with a private key. It should return an object with signTransaction.

#### Expected behavior
const i=web3.eth.accounts.privateKeyToAccount(privateKey);
i.hasOwnProperty('signTransaction')===true;

#### Actual behavior
const i=web3.eth.accounts.privateKeyToAccount(privateKey);
i.hasOwnProperty('signTransaction')===false;

### Versions 
 "web3": "^1.0.0-beta.37"

**Comment by nivida** [comment]
I've fixed the accounts module with this PR: https://github.com/ethereum/web3.js/pull/2580 and will release the fix with version 1.0.0-beta.51.
