### ISSUE TITLE
web3.eth.accounts.wallet typings and documentation

### ISSUE THREAD

**Issue by winter38** [ethereum/web3.js#2591]
### Description 
I am trying update web3 lib from web3.1.0.0-beta.33 to current version (web3.js: 1.0.0 - beta.50).

`web3.eth.accounts.wallet` - i can't figure that class.
in docs - https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#wallet - there is length
in git - https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-accounts/src/models/Wallet.js - there is accountsIndex
in typings - there nothing except methods

in old code i used 
```js
web3.eth.accounts.wallet.load(password, keyname)
if (web3.eth.accounts.wallet.length){
   // any check
}
 ```

### Versions 
* web3.js: 1.0.0 - beta.50

**Comment by nivida** [comment]
Thanks for opening this issue! I'll fix and release it asap.

**Comment by davidbongcc** [comment]
Does Web3.py have this similar function(web3.eth.accounts.wallet) in the library? How can I create a wallet using web3.py?
