### ISSUE TITLE
Web3 doesn't work correctly with truffle-hdwallet-provider

### ISSUE THREAD

**Issue by rjkz808** [ethereum/web3.js#2599]
### Description

When I'm trying to subscribe to `'newBlockHeaders'` event using the [truffle-hdwallet-provider](https://www.npmjs.com/package/truffle-hdwallet-provider), web3 throws an error.

#### Expected behavior

Expected web3 to subscribe to an event.

#### Actual behavior

Subscribing to `'newBlockHeaders'` event throws the next error: 

```node
'Error: Subscriptions are not supported with the CustomProvider.'
```

#### Steps to reproduce the behavior

```node
// 1. import web3 and truffle-hdwallet-provider
const Web3 = require('web3');
const HDWalletProvider = require('truffle-hdwallet-provider');

// 2. create a valid HDWalletProvider class instance
const mnemonic = 'shrimp dial ...';
const provider = new HDWalletProvider(mnemonic, 'http://localhost:8545');

// 3. create a Web3 class instance using the created HDWalletProvider
const web3 = new Web3(provider);

// 4. subscribe to 'newBlockHeaders' event
web3.eth
  .subscribe('newBlockHeaders', (error, result) => {
    if (error) throw error;
    console.log(result);
  })
  .on('data', console.log)
  .on('error', console.error);
```

> I know that I can use `ws://localhost:8545` directly
> in the `Web3` constructor, but in my application I 
> expect cases when Infura should be used as a 
> web3 provider.

#### Error Logs 

```node
Error: Subscriptions are not supported with the CustomProvider.
    at CustomProvider.subscribe (/d/Desktop/cc-monorepo/cc-eth-utils/node_modules/web3-providers/dist/web3-providers.cjs.js:1094:13)
    at NewHeadsSubscription.subscribe (/d/Desktop/cc-monorepo/cc-eth-utils/node_modules/web3-core-subscriptions/dist/web3-core-subscriptions.cjs.js:49:43)
    at Proxy.subscribe (/d/Desktop/cc-monorepo/cc-eth-utils/node_modules/web3-eth/dist/web3-eth.cjs.js:425:77)
```

### Versions 

* nodejs: `10.15.1`
* web3: `1.0.0-beta.50`
* ganache-cli: `6.4.1`
* truffle-hdwallet-provider: `1.0.5`

**Comment by nivida** [comment]
The truffle hdwallet provider is HTTP based and does not support subscriptions. 
Please use the official socket based providers of the Web3.js library. (WebsocketProvider or IpcProvider)

If you would like to have a custom signing process then feel free to write your own custom TransactionSigner as described [here](https://web3js.readthedocs.io/en/1.0/web3-eth.html#transactionsigner).

**Comment by rjkz808** [comment]
> The truffle hdwallet provider is HTTP based and does not support subscriptions.
> Please use the official socket based providers of the Web3.js library. (WebsocketProvider or IpcProvider)
> 
> If you would like to have a custom signing process then feel free to write your own custom TransactionSigner as described [here](https://web3js.readthedocs.io/en/1.0/web3-eth.html#transactionsigner).

Thank you for your prompt response 😄
