### ISSUE TITLE
subscribe logs behaviour discrepancy between WebsocketProvider and HttpProvider

### ISSUE THREAD

**Issue by csokun** [ethereum/web3.js#2605]
### Description 

I have subscribed to a set of topics. When using `HttpProvider` I can subscribe and get events back. However, when I switch to `WebsocketProvider` the same subscription code doesn't return any events.

#### Expected behavior
I should be able to subscribe to logs event using either `HttpProvider` or `WebsocketProvider`.

#### Actual behavior
Not all topics can be subscribe via `WebsocketProvider`.

#### Steps to reproduce the behavior

```javascript
// using HttpProvider - work
const Web3 = require("web3");
const web3 = new Web3("http://localhost:8545");

const topics = [[
"0x6c740debfcfa3176dd2021b7d9972340f6babe2801faa17bdf2a2ca6157acb61",
"0x234054a8dbab6070c5da11760c916a835f62517aeae9f9cba526f99ae70fa1de",
"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
"0xdd117a11c22118c9dee4b5a67ce578bc44529dce21ee0ccc439588fbb9fb4ea3"
]];

web3.eth.subscribe('logs', { fromBlock: 100, topics }, (err, log) => {
  console.log("received event: ", log);
});
```

The following code doesn't work.

```javascript
// using WebSocket - doesn't work
const Web3 = require("web3");
const web3 = new Web3("ws://localhost:8546");

const topics = [[
"0x6c740debfcfa3176dd2021b7d9972340f6babe2801faa17bdf2a2ca6157acb61",
"0x234054a8dbab6070c5da11760c916a835f62517aeae9f9cba526f99ae70fa1de",
"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
"0xdd117a11c22118c9dee4b5a67ce578bc44529dce21ee0ccc439588fbb9fb4ea3"
]];

web3.eth.subscribe('logs', { fromBlock: 100, topics }, (err, log) => {
  console.log("received event: ", log);
});
```

#### Error Logs 

No error

### Versions 
* web3.js: 1.0.0-beta.51
* nodejs: 8.14.0
* browser: NA
* ethereum node: geth-1.8.20

**Comment by nivida** [comment]
The HttpProvider does not support subscriptions and will return an error. 
But because you defined the fromBlock to 100 will it first request all the past logs and return them. 

I've tested the logs subscription with the WebsocketProvider and didn't have a problem with it. Could you please add a GitHub repository for reproducing this behavior?

**Comment by princesinha19** [comment]
Yes, @csokun I also tested the logs subscription and it works fine with WebSocketProvider. I tested for logs and newBlockHeaders.
With HttpProvider, you will get an error because subscription doesn't support HttpProvider.

**Comment by csokun** [comment]
Thank @nivida that explain why I can get logs using `HttpProvider` because I had `fromBlock` configured.

@princesinha19 me too had successfully subscribed to logs using `WebsocketProvider`. However, it only when I started to add topics from one specific smart contract that the subscribe logs just stale. I am not sure is it because the volume of logs that the particular contract producer causing the provider to take time or something else. But I did leave the test code running for sometime and I got nothing back.

I will try to re-produce this problem in an isolate environment and share the finding.

**Comment by nivida** [comment]
Closed due to inactivity of the creator of this issue.
