### ISSUE TITLE
0.8 watches broken ?

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#261]
using Geth Frozen  and also updated to use atmospherejs web3.js 0.8 watches are no longer fired.
```
filter = contract.event...
filter.watch(function(err, callback) {
   // not getting fired anymore
```

**Comment by frozeman** [comment]
did you before used `contract.new` ?
If so than i already work on a fix...

**Comment by frozeman** [comment]
It seems like geth is broken.

**Comment by ethers** [comment]
geth is now fixed https://github.com/ethereum/go-ethereum/issues/1444
