### ISSUE TITLE
Error when when connection close while getting logs

### ISSUE THREAD

**Issue by vshab** [ethereum/web3.js#2614]
### Description 

Infura can close websocket connection when request takes a lot of time, for example query past events starting block 0 on mainnet. In this case web3 produce this error in console:
```
web3-providers.umd.js:293 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at WebsocketProvider._callee2$ (web3-providers.umd.js:293)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/0.chunk.js:112974:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/lib/providers/AbstractSocketProvider.js#L195 is the location in file where the error occurs.

Screenshot from debugger:
<img width="1107" alt="Screenshot 2019-03-30 at 02 19 32" src="https://user-images.githubusercontent.com/6755908/55257546-d1331700-5292-11e9-9701-2d610779b8ac.png">

#### Steps to reproduce the behavior

1. Connect to mainnet with Infura websocket provider
2. query past events from 0 to latest block several times in parallel (3 in my case)
3. Infura will close the connection with some probability and the error will be shown

### Versions 
* web3.js: 1.0.0-beta.51
* browser: Chrome 71
* ethereum node: Mainnet Infura WebSocket

**Comment by nivida** [comment]
Thanks for opening this issue! I'll test and fix it asap.
