### ISSUE TITLE
web3.eth.getTransactionReceipt() returns null

### ISSUE THREAD

**Issue by radster360** [ethereum/web3.js#262]
var receipt = web3.eth.getTransactionReceipt(transaction_hash_from_60_minutes_ago);

I am saving the transaction hash that was returned by contract creation in a earlier session. Maybe my use case is different and the call to getTransactionReceipt() is incorrect. What is the correct use of this new call?

Secondly, is this call applicable after other transaction type calls?

**Comment by frozeman** [comment]
It seems like you tx was never mined. the receipt is only available when its mined.
Did you check `web3.eth.getTransaction(hash)`, if it contains a block number and hash?

**Comment by debris** [comment]
Maybe it was related with https://github.com/ethereum/go-ethereum/issues/1473 ? If you ever reproduce this, please report in the client's repo (go, cpp or any other implementation).
