### ISSUE TITLE
can anyone saw it? I face the issue too #2595

### ISSUE THREAD

**Issue by silravend** [ethereum/web3.js#2620]
JUST LIKE HE SAID [https://github.com/ethereum/web3.js/issues/2595](#2595)

This is what I want to say too, mocha need a resolved result, but web3's return is not resolve.

**Comment by nivida** [comment]
Could you please update your issue to be aligned with the issue template we provide?

**Comment by nivida** [comment]
Closed due to missing information and inactivity of the creator of this issue.
