### ISSUE TITLE
Transaction confirmation poll rate as a constructor option

### ISSUE THREAD

**Issue by angus-hamill** [ethereum/web3.js#2621]
### Description
In the `TransactionObserver` class, the polling rate is set to poll every 1000 ms. While this is fine for the mainnet and testnets, people using private networks or ganache have experienced a significant performance dip.
I personally have fixed this locally by changing the observer to poll every 100ms.
Perhaps this could be added as a configurable option (with a default of 1000), similar to the options added under this new transaction confirmation workflow.
Plus it's nice to remove hardcoded values in the codebase.

#### Expected behavior
Transaction confirmations are processed multiple times per second.

#### Actual behavior
Confirmations take up to 1000ms each, a hardcoded value.

#### Steps to reproduce the behavior
Configure web3 with any private network that has a high transaction throughput and try to run many transactions in a row.

### Versions 
* web3.js: 1.0.0-beta.51

**Comment by silravend** [comment]
May I ask where to change it to 100ms, please?

**Comment by silravend** [comment]
`let accounts;
let contract;

beforeEach(async () => {
    accounts = await web3.eth.getAccounts();
    contract = await new web3.eth.Contract(interface)
        .deploy({ data: bytecode })
        .send({ from: accounts[0], gas: '500000'})
});

describe('LimitLess', () => {
    it('deploys a contract', async () => {
        done();
    });
});`

I tried to run this, and got :
**Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.**

**Comment by princesinha19** [comment]
@nivida I think we can add an option in the constructor for **transactionPollRate** in AbstractWeb3Module class. What's your thinking here?

**Comment by princesinha19** [comment]
@nivida add this too in 1.0 milestone.

**Comment by forshtat** [comment]
Hey @nivida @princesinha19 !
May I ask what is the status of this issue? It looks here like it was accepted and then closed.
Is there currently no way to configure the polling rate? I understand there is a `transactionPollingTimeout`, but it only changes the number of 1000ms intervals until the exception is thrown, am I right?

**Comment by steelep** [comment]
Bumping this, I have patched my own version, but would love to see this in the next release.

**Comment by GregTheGreek** [comment]
@steelep can you share a code snippet?

**Comment by nazarhussain** [comment]
As a community PR is created so reopening the issue.

**Comment by nazarhussain** [comment]
Closed by https://github.com/ChainSafe/web3.js/pull/4672
