### ISSUE TITLE
Timeout error when getting the transaction receipt and getting the block by its number.

### ISSUE THREAD

**Issue by afcajamarcar** [ethereum/web3.js#2627]
### Description 
Timeout error when getting the transaction receipt and getting the block by its number in **v1.0.0-beta.51**

#### Expected behavior
Receive the hash of the transaction that has been made.

#### Actual behavior

Receiving a timeout error.

#### Error Logs 
As you can see on this gif, when expecting the resulting hash of the transaction I get a timeout error.

![](https://user-images.githubusercontent.com/1184373/55192736-2d9f1500-5173-11e9-93dc-9dbe58d1f5db.gif
)
It gets properly initialized, then trying to execute the first transaction is where it gets stuck.

### Versions 
* web3.js: v1.0.0-beta.51
* nodejs: 10.15.3

I just updated to beta 51 and it seems to have resolved the previous issue with the status (can't confirm though), but now I got another issue. It gets stuck getting the transaction receipt and getting the block by its number.

**Comment by nivida** [comment]
Could you please add your code example for reproducing this error? 
The error looks like a project-specific error because Web3.js isn't importing a file called ``api.key``.

Edit: did you set the [``transactionConfirmationBlocks``](https://web3js.readthedocs.io/en/1.0/web3.html#options) options property? 
``` javacript 
new Web3(provider, null, options);
```

**Comment by afcajamarcar** [comment]
> Could you please add your code example for reproducing this error?
> The error looks like a project-specific error because Web3.js isn't importing a file called `api.key`.
> 
> Edit: did you set the [`transactionConfirmationBlocks`](https://web3js.readthedocs.io/en/1.0/web3.html#options) options property?
> 
> ```
> new Web3(provider, null, options);
> ```

You are absolutely right, the options param with the **transactionConfirmationBlocks** was not set. 
My project works fine right now.
Since I was working with a previous Web3.js version, there was no need to set said options param. 
And the file `api.key` is just a warning that I putted there depending on the environment one is currently developing, so is not related to Web3.js at all.

By the way, as stated in [Web3.js documentation](https://web3js.readthedocs.io/en/1.0/web3.html#options), there's not a second parameter for
```
new Web3(provider, null, options)
```
So I was wondering, on the one hand, if the documentation is outdated and on the other hand which parameter is the null one?

Thank you very much for your help.
