### ISSUE TITLE
Add Parity specific methods

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2636]
### Description 

Extend the Web3.js library with Parity specific JSON-RPC methods.

#### Expected behavior

All methods [here](https://wiki.parity.io/JSONRPC) are supported.

#### Actual behavior

They aren't supported.

### Versions 
* web3.js: latest

**Comment by AyushyaChitransh** [comment]
Currently, I am using a very old instance of web3 which supports some parity methods.
https://github.com/AyushyaChitransh/web3.js/tree/develop/lib/web3/methods

**Comment by sshelton76** [comment]
As I mentioned in the Geth specific thread.  These "specific methods" increase code bloat and add an additional moving target we'd have to chase.  It would be better to let the Parity team be responsible for any Parity specific API, and the Geth team to be responsible for a Geth API.

Note:  I only mean APIs which are specific to an underlying implementation.  Anything which is universal, of course should here.  But let these guys handle their own stuff where they diverge from spec.  It lowers our support burden and puts that burden where it belongs "on the implementors".
