### ISSUE TITLE
Add all management API methods of Geth

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2637]
### Description 

Implement all methods which are listed [here](https://github.com/ethereum/go-ethereum/wiki/Management-APIs).

#### Expected behavior

I can, for example, call the debug methods.

#### Actual behavior

Not all methods of the management API are supported.

### Versions 
* web3.js: latest

**Comment by sshelton76** [comment]
My honest opinion is that this does not belong as a web3 target.  The geth team can and should have ownership over geth specific management APIs.  Otherwise we're going to be stuck chasing them constantly.  Same with the parity issue for similar work.

**Comment by nivida** [comment]
All required Geth JSON-RPC methods are implemented with the new management modules web3 does provide.

**Comment by ceds** [comment]
I don't see this feature in web3 API ?  Where can I get it ?
