### ISSUE TITLE
Error: No privateKey given to the TransactionSigner. 

### ISSUE THREAD

**Issue by dillonsvincent** [ethereum/web3.js#2638]
### Description 
Web3 react build throwing Error: No privateKey given to the TransactionSigner. Development on localhost is working fine. 

File: web3-eth.umd.js
```
if (privateKey) {
_context.next = 2;
break;
}
throw new Error('No privateKey given to the TransactionSigner.');
```

#### Reproduce
I created an example dapp to show the error happening, just open the console 
https://console.atra.io/app/1bebd277-7945-4cab-9178-d10255884f95

### Versions 
* web3.js:
* nodejs:
* browser:
* ethereum node:

**Comment by dillonsvincent** [comment]
It's either an issue with the web3 build that gets deployed with `npm run build` or it's an issue with web3 giving access to the private key when I'm running on a domain.

**Comment by dillonsvincent** [comment]
Link to the issues I opened with metamask https://github.com/MetaMask/metamask-extension/issues/6390

**Comment by nivida** [comment]
Thanks for opening this issue! But this got already fixed and will be released this week.

**Comment by dillonsvincent** [comment]
I pulled down the repo, built it, ran bootstrap and made system link to my project, then deployed it, still getting this error, was the fix merged into 1.0 yet?

**Comment by dillonsvincent** [comment]
@nivida you don't happen to know if you're doing a release today? :)

**Comment by smiled0g** [comment]
@nivida Any news on this?

IMO, any release that utterly **break** dapps should never be push to `latest`. At least pull this back so other developers don't have to spend full day trying to fix a known bug.

**Comment by EddieOne** [comment]
Thanks, I was like WTF is this error.

Edit: I still have this error with 1.0.0-beta.52 😞 

https://gametest.cryptoserval.io/

**Comment by EddieOne** [comment]
@nivida will you make a release with this patch in it?

**Comment by dillonsvincent** [comment]
It's already fixed in v1.0.0-beta.52

**Comment by EddieOne** [comment]
I logged into the server and looked in the node_modules folder. It shows, v1.0.0-beta.52, so I'm not sure.

**Comment by nivida** [comment]
@EddieOne Could you open a new issue with all the steps to reproduce it?

**Comment by EddieOne** [comment]
I'm not sure, let me ask. Same definition as above. Locally everything works fine. Deploy it and get this `No privateKey given to the TransactionSigner` error.

Update: Just a build issue. Thanks for the help.

**Comment by raymogg** [comment]
@EddieOne could you provide some details on the build issue you faced? Having the same issue right now. How was this fixed?

**Comment by EddieOne** [comment]
In my case, I forgot to rebuild webpack before deploying.
