### ISSUE TITLE
Throw error on contract.new sync, when its not successfully deployed 

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#264]

**Comment by jesuscript** [comment]
as from the conversation with Jeff: alternatively we could make contract.new async only, and give the current sync version a different name.

Either way, it will solve the inconsistency issue

**Comment by frozeman** [comment]
fixed in develop, please test.

**Comment by frozeman** [comment]
<img width="879" alt="screen shot 2015-07-13 at 22 57 42" src="https://cloud.githubusercontent.com/assets/232662/8660656/87575d7e-29b2-11e5-9ed8-5b98d9280a01.png">
