### ISSUE TITLE
Filtering on String throwing 'response has no error or result for request'

### ISSUE THREAD

**Issue by devedse** [ethereum/web3.js#2641]
### Description
I'm trying to get events for my contract in my VueJS application using MetaMask as it's provider:
```js
event ContractAddressChanged(string indexed contractName, address newAddress);
```

I do this by executing the following code:
```js
const allEvents = await contractFinderContract.getPastEvents('ContractAddressChanged', {
        filter: { contractName: ['GreenEnergyContract'] },
        fromBlock: 0,
      });
```
I however keep getting the following error:
```json
Uncaught (in promise) Error: JsonRpcEngine - response has no error or result for request:
{
  "jsonrpc": "2.0",
  "id": 2424636363,
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "0x0",
      "topics": [
        "0x7cc5320aa18fb40c93aed6f76ae28088a8aaf67a112e0ca55367cd087b21802f",
        [
          "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013477265656e456e65726779436f6e747261637400000000000000000000000000"
        ]
      ],
      "address": "0x395aeee1e3c39e6d85da5776848e351c0f81a8ce"
    }
  ]
}
```
If I remove the string filter the query works and I get all the results back.

Contract with source code on ropsten:
https://ropsten.etherscan.io/address/0x395aeee1e3c39e6d85da5776848e351c0f81a8ce

When I query the contract you can see the data is correct:
![image](https://user-images.githubusercontent.com/2350015/55480859-78140c00-5621-11e9-8f3f-e2c77d0366b2.png)

The event is also fired according to Ropsten Etherscan:
![image](https://user-images.githubusercontent.com/2350015/55480889-8530fb00-5621-11e9-9124-377e42deace7.png)

Small note: Another place in my code does actually use a filter on a uint value. That one does actually work.

#### Expected behavior

Once you request an event with a filter provided, don't throw an error but return all the elements that match the filter.

#### Actual behavior
Error `Uncaught (in promise) Error: JsonRpcEngine - response has no error or result for request` is thrown when filtering on a string.

#### Steps to reproduce the behavior
Call the contract mentioned above on the Ropsten network with the code pasted above.

#### Error Logs 
See above

#### Gists
---

### Versions 
* web3.js: `1.0.0-beta.51`
* nodejs: `npm@6.8.0, Node: v10.11.0`
* browser: `Latest chrome`
* ethereum node: `Metamask Ropsten Network`

**Comment by nivida** [comment]
Did you test it with the correct syntax?

Example:
 
``` javascript 
await contractFinderContract.getPastEvents('ContractAddressChanged', {
        filter: { contractName: 'GreenEnergyContract'},
        fromBlock: 0,
      });
```

**Comment by devedse** [comment]
Yeah, I tried it again but I run into the same issue.

I believe you can pass an array to be able to filter on multiple indexed values.

**Comment by nivida** [comment]
Yes, you are able to pass an array and Web3.js is sending a correct JSON-RPC payload to the Metamask provider. This means it is an issue of Metamask and not of Web3.js. :-)

**Comment by devedse** [comment]
@nivida , created a bug report on the MetaMask github. Let's hope they respond as fast as you :smile:. Thanks for the help.

**Comment by devedse** [comment]
@nivida , just for your information, in the Metamask thread someone found out the underlying error. Apparently this error is returned from Infura:

```
error: {code: -32602,…}
code: -32602
message: "invalid argument 0: hex has invalid length 96 after decoding; expected 32 for topic"
id: 0
jsonrpc: "2.0"
```

Just asking your insight, but do you think this is due to Infura not parsing the inputs correctly?
