### ISSUE TITLE
sendRawTransaction() has wrong amount of input formaters

### ISSUE THREAD

**Issue by tcoulter** [ethereum/web3.js#265]
See this line: https://github.com/ethereum/web3.js/blob/master/lib/web3/eth.js#L174

Background: When I call `sendRawTransaction` with a signature of `sendRawTransaction(string, function)`, I receive an error stating I have passed the wrong number of input parameters. After stepping through the code, it turns out that because of the line above, the string I passed in gets clobbered leaving only the callback.

@frozeman tells me `sendRawTransaction`'s inputFormatters array should instead be `[null]`

**Comment by frozeman** [comment]
fixed in develop, please test

**Comment by tcoulter** [comment]
Works for me. Thanks!
