### ISSUE TITLE
Getting contract deploy error even though deploy was successful ("Transaction has been reverted by the EVM")

### ISSUE THREAD

**Issue by UnclePetros** [ethereum/web3.js#2650]
Hello,
I've found some time to test beta.50 against the issue #1477, that has been claimed as solved.
Unfortunately I've encountered the same problem, that is a contract is deployed correctly but an error is returned.
This time the error is different from the usual errors ("...check your gas limit..." or "...transaction was not mined after 750 blocks..."):
current error is the following:

`[2019-04-04T17:49:28.430] [ERROR] default - Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xc19160685d47c47ce30d0e9bf8a209bdf01344a775938c5372274498a253cb65",
  "blockNumber": 10688460,
  "contractAddress": "0x6E7d1e6ae9D6fe5eD8EED2bBF47694852b7676AE",
  "cumulativeGasUsed": 3412209,
  "from": "0xdf16a36efc3cb69ff3e2bc7c2d0000ba7f17d78e",
  "gasUsed": 3337040,
  "logs": [
    {
      "address": "0x6E7d1e6ae9D6fe5eD8EED2bBF47694852b7676AE",
      "blockHash": "0xc19160685d47c47ce30d0e9bf8a209bdf01344a775938c5372274498a253cb65",
      "blockNumber": 10688460,
      "data": "0x",
      "logIndex": 0,
      "removed": false,
      "topics": [
        "0x44a06b324619ce76fee5c0933f787fbffe4c3e03ed12fb56d19566a63f789ac5",
        "0x000000000000000000000000df16a36efc3cb69ff3e2bc7c2d0000ba7f17d78e"
      ],
      "transactionHash": "0x6352ae21725b03367342435ef0fc1f0536c9d189dfbd9d46181cafb3966d2444",
      "transactionIndex": 1,
      "transactionLogIndex": "0x0",
      "type": "mined",
      "id": "log_0xba18591d9bf0a8b8c3e34951bb1b9010e0f4a4ac819eb7a25cf4ac07f6c4d198"
    },
    {
      "address": "0x6E7d1e6ae9D6fe5eD8EED2bBF47694852b7676AE",
      "blockHash": "0xc19160685d47c47ce30d0e9bf8a209bdf01344a775938c5372274498a253cb65",
      "blockNumber": 10688460,
      "data": "0x00000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000013880000000000000000000000000000000000000000000000000000000000001388000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000067177657177650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000353515000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006717765717765000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000097177657177657771650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004368747470733a2f2f697066732e696f2f697066732f516d65585a346253617a65557548614c58756e7679774654334a46727454506b58616f6f7238557a3144655837610000000000000000000000000000000000000000000000000000000000",
      "logIndex": 1,
      "removed": false,
      "topics": [
        "0x59c3f5e971c30e4a33f6496d5c136a7103e88943fdeba1db9271615411391395",
        "0x8b5e6b63baf51e52f896243a372565d804face1fa173553c02d1de5967b29afc"
      ],
      "transactionHash": "0x6352ae21725b03367342435ef0fc1f0536c9d189dfbd9d46181cafb3966d2444",
      "transactionIndex": 1,
      "transactionLogIndex": "0x1",
      "type": "mined",
      "id": "log_0xc905f5ca7be0e859cc3f5a998fdad2a6ac4bee28ef9492c2935f745affed6a93"
    }
  ],
  "logsBloom": "0x00000000000000000000000001000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000008000000000000000000000000000000000080000000000000000000000000000000000000000000000000000200080000000000000000000000000000400000000000000000000000000000000000000000000000000000000100040000000000000000000000000000000000000000000000000000000000000080000000000080000000000000",
  "root": null,
  "status": true,
  "to": null,
  "transactionHash": "0x6352ae21725b03367342435ef0fc1f0536c9d189dfbd9d46181cafb3966d2444",
  "transactionIndex": 1
}
    at SafeSubscriber._next (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\web3\node_modules\web3-core-method\dist\web3-core-method.cjs.js:1017:32)
    at SafeSubscriber.__tryOrUnsub (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\rxjs\src\internal\Subscriber.ts:267:10)
    at SafeSubscriber.next (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\rxjs\src\internal\Subscriber.ts:209:14)
    at Subscriber._next (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\rxjs\src\internal\Subscriber.ts:139:22)
    at Subscriber.next (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at TransactionObserver.emitNext (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\web3\node_modules\web3-core-method\dist\web3-core-method.cjs.js:438:16)
    at _callee2$ (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\web3\node_modules\web3-core-method\dist\web3-core-method.cjs.js:408:24)
    at tryCatch (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Mega\Lavoro\Freelance\Threads s.r.l\Progettazione\love_smart_contract_virtualization\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)` 

As I said, contract is deployed correctly.

I hope this could be helpful.
Please, let me know if you want me to do some specific tests.

Regards
Pietro

**Comment by nivida** [comment]
Did you configure the ``transactionConfirmationBlocks`` option?

Edit: and can you tell me which node you are using?

**Comment by UnclePetros** [comment]
> Did you configure the `transactionConfirmationBlocks` option?
> 
> Edit: and can you tell me which node you are using?

Well,
no, I haven't configured this option.
I've node v9.9.0.

**Comment by nivida** [comment]
@UnclePetros Sorry, I mean the ethereum node, not the NodeJS version. I think you are using ganache and this "node" is returning an invalid value in the status property.

Btw.: I will update the documentation today which will improve the module options description.

**Comment by UnclePetros** [comment]
> @UnclePetros Sorry, I mean the ethereum node, not the NodeJS version. I think you are using ganache and this "node" is returning an invalid value in the status property.
> 
> Btw.: I will update the documentation today which will improve the module options description.

Oh sorry, I misunderstood.
Anyway I have to say I don't know exactly what you mean by "ethereum node". 
I've seen ethereum node tracker on etherscan but I'm not aware of that.
I use kovan network for test and mainnet for production. 
I have never used ganache locally (just sometimes at the beginning).

Thank you so much for the documentation update.
I'll wait for it.

Tomorrow and in the next few days I'll continue to work with web3 and blockchain.
Tell me if you need further info and test.

Pietro

**Comment by iheqi** [comment]
Hey, bro, Did you solved this issue?

**Comment by mato777** [comment]
Have the same issue with latest version.  I don't get the error even with .on("error", ...) callback.  Using async function await with try also give the same error.  If I use the raw tx with a curl I am able to see it.

**Comment by UnclePetros** [comment]
> Hey, bro, Did you solved this issue?

Hey, as nivida suggest, I've tried `transactionConfirmationBlocks` option set to 1 (you have to pass it when define a new web3 object (new web3(provider, null,options))).
I've not understood very well what it does, but it works fine on a test network (Kovan).
In the next days I'll try it on mainnet

**Comment by iheqi** [comment]
> > Hey, bro, Did you solved this issue?
> 
> Hey, as nivida suggest, I've tried `transactionConfirmationBlocks` option set to 1 (you have to pass it when define a new web3 object (new web3(provider, null,options))).
> I've not understood very well what it does, but it works fine on a test network (Kovan).
> In the next days I'll try it on mainnet

OK, thanks for your reply!
