### ISSUE TITLE
ENS: throws error when no resolver contract set

### ISSUE THREAD

**Issue by darrenlangley** [ethereum/web3.js#2656]
### Description 

When querying an ENS name, it is possible that a resolver contract is not set (0x0). Web3 throws an unspecific error message when no resolver is set.

#### Expected behavior
```js
const address = await web3.eth.ens.getAddress(ensNameWithoutResolver);
expect(address).toEqual('0x0');
```
There are two options for expected behaviour:
- returns 0x0 address when no resolver set
- throws specific error message "No resolver set"

There are pros/cons of both. Personally, I feel it should return 0x0 because the address doesn't exist and it makes the call more intuitive to use.

#### Actual behavior
```js
const address = await web3.eth.ens.getAddress(ensNameWithoutResolver); // throws error
```

#### Steps to reproduce the behavior
```js
(async () => {
  const Web3 = require('web3');
  const web3 = new Web3('https://mainnet.infura.io/v3/b0444015b0c64183a7dbea5d183661b5');
  const address = await web3.eth.ens.getAddress('ipledger.eth');
})();
```

#### Error Logs 
```shell
(node:31248) UnhandledPromiseRejectionWarning: Error: Invalid bytes string given: 0x
    at AbiCoder.decodeParameters (/home/langers/Source/kauri-io/enslookup/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:64:15)
    at AbiCoder.decodeParameter (/home/langers/Source/kauri-io/enslookup/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:55:19)
```

### Versions 
* web3.js: 1.0.0-beta.50
* nodejs: v10.15.3

Happy to raise a PR - just let me know what is the preferred expected behaviour.

**Comment by nivida** [comment]
This got fixed with beta.52 :)

**Comment by teamyudin** [comment]
I am getting:

The resolver at 0x0000000000000000000000000000000000000000does not implement requested method: "addr".
