### ISSUE TITLE
Getting an ENS address throws a "Network not synced" error

### ISSUE THREAD

**Issue by Flash-Git** [ethereum/web3.js#2665]
`await window.web3.eth.ens.getAddress("jaquinn.eth");` consistently throws a`Network not synced;` error when using metamask with localhost.

`Error: Network not synced; last block was 3623.4639999866486 seconds ago
    at Registry._callee3$ (web3-eth-ens.umd.js:1107)`

I get the same thing telling me that it's just over an hour out of sync no matter which name I use.

EDIT: Requested complete code example:
```
let ensAdd = await window.web3.eth.ens.getAddress("jaquinn.eth");
console.log(" Add: " + ensAdd);
```

Also might be worth noting that yes I'm on mainnet and yes other web3 calls are working fine.

**Comment by nivida** [comment]
Could you please add the complete code example?:)

**Comment by Flash-Git** [comment]
Added it as an edit, if you're looking for something more particular then I can add that too.

**Comment by nivida** [comment]
I thought you will add the complete code where I can see which provider you are using etc. 

Could you update your issue to be aligned with the issue template?

**Comment by nivida** [comment]
Closed due to the missing answer of the creator of this issue.

**Comment by Ezerous** [comment]
This happens in development networks when automining is on and blocks were mined more than an hour ago. It is thrown if for some reason `checkNetwork()` in `ENS.js` is triggered (e.g. with a simple `console.log(web3.eth.ens.registry)`).

**Comment by Ezerous** [comment]
Okay, it seems that another case that triggers it is the following one:

- Private development network
- A web3 object inside an action in Redux
- Opening Redux DevTools extension

This will always throw an error (either this one, if last block was mined more than an hour ago, or "ENS is not supported on network"). As far as I get it, the extension is accessing the web3 object, and when it reaches `web3.eth.ens.registry` a new Registry is attempted to be created ([this line here](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-ens/src/ENS.js#L45)). This causes [this ](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-ens/src/contracts/Registry.js#L43)to be called which in turn throws one of the errors mentioned above.

**Comment by sdelvalle57** [comment]
Happens the same to me.
When I open `redux-dev-tools` I get `ENS is not supported on network` error.
