### ISSUE TITLE
web3-eth PromiEvents never complete

### ISSUE THREAD

**Issue by macor161** [ethereum/web3.js#2666]
### Description 

Using the web-eth package, PromieEvent's `then` function never completes.

#### Expected behavior vs Actual behavior

```javascript
await contractInstance.methods.myMethod().send({ from: '...' })
```

This code runs fine using `web3` but it never completes using `web3-eth`. It doesn't throw an error either.

#### Steps to reproduce the behavior

I've created an example repo here: https://github.com/macor161/web3-eth-bug 
It's based on the truffle webpack box.
It has two examples: 
- One working with web3
- One not working, with web3-eth

Run instructions:

```bash
npm install
truffle compile
truffle migrate

npm run start:eth # To run the web3-eth example
npm run start:web3 # To run the web3 example
```

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: v10.15.3
* browser: Chrome 72
* ethereum node: ganache-cli v6.4.1
* truffle v5.0.8

**Comment by nivida** [comment]
Did you configure the transaction module options as described in the documentation? and could you add the complete code example?:)

**Comment by ricardo85x** [comment]
I have a similar problem.

It got stuck on **then** promise

follow my source code:

```
const HDWalletProvider = require('truffle-hdwallet-provider')
const Web3 = require('web3')
const { abi, evm } = require("./compile");

const provider = new HDWalletProvider(
    'bla bla bla bla bla',
        'http://192.168.3.11:8546'
    );

const OPTIONS = {
    defaultBlock: "latest",
    transactionConfirmationBlocks: 1,
    transactionBlockTimeout: 5
};
 
const web3 = new Web3(provider, null, OPTIONS);
let  inbox;
var init_msg = "Hello World"
const deploy = async () => {
    const accounts = await web3.eth.getAccounts()
    inbox = await new web3.eth.Contract(abi)
        .deploy({ data: '0x' + evm.bytecode.object, arguments: [init_msg]})
        .send({ from: accounts[0],   
            gasPrice: web3.utils.toHex(20000000000),
            gasLimit: web3.utils.toHex(800000)
        })
        .on('error', (error) => { 
            console.log("Error", error)
         })
        .on('transactionHash', (transactionHash) => { 
            console.log("Transacao", transactionHash)
         })
        .on('receipt', (receipt) => {
           console.log("receipt", receipt.contractAddress) 
        })
        .on('confirmation', (confirmationNumber, receipt) => { 
            console.log("confirmacao", confirmationNumber)
        })
    return inbox


};

deploy()
    .then(contract => {
        console.log("Finish Him", contract);
    })
    .catch(error => console.log("Got error:", error));
```

I got the **Finish Him** message with the contract, but the process never ends

**Comment by macor161** [comment]
@nivida Thanks for the quick response!

> Did you configure the transaction module options as described in the documentation?

I have not, this must be the problem. Those options must be configured manually with `web3-eth` but not `web3`? I haven’t configured them either in the `web3` example and it’s working. 

Actually I haven't found any documentation for `web3-eth` specifically, if you could point me in the right direction it would be greatly appreciated.

The https://github.com/macor161/web3-eth-bug repo is the complete code example, but these are the two main source files:
- with web3 (working): https://github.com/macor161/web3-eth-bug/blob/master/src/web3.js
- with web3-eth (not working): https://github.com/macor161/web3-eth-bug/blob/master/src/eth.js

By the way, great work replacing Fabian! I’m quite impressed by the development progress of the last couple of months.

**Comment by macor161** [comment]
@ricardo85x Your app goes through the `console.log("Finish Him", contract);` line? That's the expected behavior isn't it?

**Comment by ricardo85x** [comment]
@macor161 
I got the message, but the process does not finish.
I am running it from the terminal like
```node exemple.js```

But this script does not exit to the prompt shell.

**Comment by princesinha19** [comment]
> Actually I haven't found any documentation for web3-eth specifically, if you could point me in the right direction it would be greatly appreciated.

https://web3js.readthedocs.io/en/1.0/web3-eth.html#options

**Comment by princesinha19** [comment]
@ricardo85x We are facing this problem with ganache.
Your problem is similar to #2661.

**Comment by ricardo85x** [comment]
I believe my problem has something to do with truffle and not web3...

A simple code like that stuck the code:

```
const HDWalletProvider = require('truffle-hdwallet-provider')

const provider = new HDWalletProvider(
    'some valid Mnemonic here',
    'http://localhost:8545'
    );

console.log("Ok, you should exit now...  Doh!")
```

**Comment by macor161** [comment]
Thanks @nivida and @ricardo85x ! :) Got it working with `{ transactionConfirmationBlocks: 1 }`.
It seems that the default options of `web3` are different than `web3-eth`:

```javascript
const web3 = new Web3(window.ethereum)
const eth = new Eth(window.ethereum)

web3.transactionConfirmationBlocks === undefined
web3.eth.transactionConfirmationBlocks === undefined

eth.transactionConfirmationBlocks === 24
```

Maybe it would be a good idea to have the same default options across `web3` and its submodules.

**Comment by princesinha19** [comment]
Default options are the same for all @macor161. For `transactionConfirmationBlocks`, it is 24 by default. You can set as per your network.

**Comment by macor161** [comment]
@princesinha19 have you tried it? This is definitely the result that I get:

```javascript
import Web3 from 'web3'
import { Eth } from 'web3-eth'

const web3 = new Web3(window.ethereum)
const eth = new Eth(window.ethereum)

web3.transactionConfirmationBlocks === undefined
web3.eth.transactionConfirmationBlocks === undefined

eth.transactionConfirmationBlocks === 24
```

One is working with ganache and the other not.

**Comment by princesinha19** [comment]
@macor161 How are you setting it up. Can you provide me with your code? 
If I am testing it and it is working fine with me. 

```
const Web3 = require("web3");
const web3 = new Web3(Web3.givenProvider || 'ws://some.local-or-remote.node:8546', null, options);

console.log(web3.transactionConfirmationBlocks)
console.log(web3.eth.transactionConfirmationBlocks)
```
**Result:**
> console.log(web3.transactionConfirmationBlocks)
> = 24
> console.log(web3.eth.transactionConfirmationBlocks)
> = 24

**Comment by macor161** [comment]
@princesinha19 https://github.com/macor161/web3-eth-bug/blob/master/src/index.js

What version of web3 are you using? Mine is `1.0.0-beta.52`

**Comment by macor161** [comment]
In any case this is far from a critical issue so I will close this. Let me know if you want to reopen it or need more information.
