### ISSUE TITLE
Correctly list dependencies in subpackages

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2667]
https://github.com/ethereum/web3.js/blob/441c309d3304ffbc36fca4ef483adf314b5f4801/packages/web3-core-method/types/index.d.ts#L20-L22

This makes `web3-utils`, `web3-core` and  `web3-core-helpers` **dependencies** of `web3-core-method`.

I guess the same issue exists in many other places.

**Comment by levino** [comment]
~~Another solution could be to somehow flatten the type definitions.~~ That would be a nightmare because one would have different types all over the place.

**Comment by nivida** [comment]
I would like to fix this with the simplification of the folder structure to something like this: 

``` 
web3/
  core/
    method/
  eth/
...
```

**Comment by levino** [comment]
As in "stop shipping individual packages"?

**Comment by nivida** [comment]
Yes @Levino

**Comment by levino** [comment]
This is a big fat bug. You are using code but not adding it as a dep.

**Comment by nivida** [comment]
Will add the missing dependencies for the types on the next release.
