### ISSUE TITLE
Docs: clarify `fromBlock`'s behaviour in event subscriptions

### ISSUE THREAD

**Issue by sohkai** [ethereum/web3.js#2668]
### Description

The current documentation on [contract event subscriptions](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events) are a bit vague as to the _actual_ behaviour of event subscriptions.

Looking [under the hood](https://github.com/ethereum/web3.js/blob/cd32de24bf/packages/web3-core-subscriptions/src/subscriptions/eth/LogSubscription.js#L53), an `undefined`, `0`, or `'latest'` value for `fromBlock` skips the `eth_getlogs` call and immediately places a subscription.

It would be great if this was documented publicly and advertised as part of the API. We specifically have use cases where we want to avoid merge `eth_getlogs` and `eth_subscribe`'s results together in a transparent manner, to allow us to know when we've finished syncing past log state. We also sometimes want to only subscribe to new events.

#### Expected behavior

More information would be available in the documentation.

#### Actual behavior

Documentation is vague.

**Comment by nivida** [comment]
I've re-labeled this issue as an enhancement because it requires synchronization of the logic behind it between version 1.x and 2.x.
