### ISSUE TITLE
Field '_parent' is no longer viable in a transaction object

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#2669]
### Description 

In v1.0.0-beta34, when creating a transaction object via `myContract.methods.myMethod(...)`, this object stores a `_parent` field, which is the contract itself (`myContract` in this example).

This field is quite useful when "moving" the transaction object between functions.

For example:
```
async function send(transaction, value, gas) {
    return await signAndSendTransaction(transaction._parent._address, transaction.encodeABI(), value, gas);
}

async function signAndSendTransaction(to, data, value, gas) {
    const options = {to: to, data: data, value: value, gas: gas};
    const signedTransaction  = await web3.eth.accounts.signTransaction(options, MY_PRIVATE_KEY);
    const transactionReceipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
    return transactionReceipt;
}
```

With this field no longer being viable, I need to pass along the address of the contract along with the transaction object.

It would be very useful if one could somehow retrieve this address directly from the object.

Thanks :)

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: 10.15.3
* browser: N/A
* ethereum node: ganache-cli 6.4.1

**Comment by nivida** [comment]
Are you doing this because of the transaction signing?
If yes then you are able to pass a custom [TransactionSigner](https://web3js.readthedocs.io/en/1.0/web3.html#transactionsigner) for customizing the transaction signing process. (The default TransactionSigner will be used if there are local unlocked accounts and no custom signer got passed)

**Comment by barakman** [comment]
@nivida : 

How can I use this property in order to achieve:
```
const options = {to: to, data: data, value: value, gas: gas};
const signedTransaction  = await web3.eth.accounts.signTransaction(options, MY_PRIVATE_KEY);
const transactionReceipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
```
?

Thanks :)

**Comment by nivida** [comment]
``` javascript 

const web3 = new Web3(provider);
web3.eth.accounts.wallet.add(pkOfSenderAddress);
const options = {to: to, data: data, value: value, gas: gas};
const receipt = await web3.eth.sendTransaction(options);
```
