### ISSUE TITLE
toAscii bug

### ISSUE THREAD

**Issue by lexansoft** [ethereum/web3.js#267]
We need to break the string if zero byte. Otherwise if text is shorter than 32 bytes the result JS string will have hidden trailing zeros. 

```js
var toAscii = function(hex) {
// Find termination
    var str = "";
    var i = 0, l = hex.length;
    if (hex.substring(0, 2) === '0x') {
        i = 2;
    }
    for (; i < l; i+=2) {
        var code = parseInt(hex.substr(i, 2), 16);
        if( code == 0 ) break;        // <------------------------------- HERE 
        str += String.fromCharCode(code);
    }

    return str;
};
```

**Comment by debris** [comment]
`toAscii`/`fromAscii` is fixed in 9743787c07b6c57b8b87eab18bc6cce6ebcd09ec . Although solidity type `string` is now encoded by default with `utf8` which allows for trailing zeros.
