### ISSUE TITLE
ContractModuleFactory expects only three arguments, receives four.

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2670]
https://github.com/ethereum/web3.js/blob/441c309d3304ffbc36fca4ef483adf314b5f4801/packages/web3-eth-contract/src/factories/ContractModuleFactory.js#L41-L49

https://github.com/ethereum/web3.js/blob/441c309d3304ffbc36fca4ef483adf314b5f4801/packages/web3-eth-contract/src/index.js#L49

I came across this because my IDE is screaming at me "This makes no sense" (static code analysis):
![Selection_108](https://user-images.githubusercontent.com/1150767/56019816-ea61ac00-5d05-11e9-950f-ee8b5e990988.jpg)

Should not be very difficult to add some sort of static code analysis for this kind of stuff.

**Comment by princesinha19** [comment]
@Levino Yes, I think accounts is unnecessary parameter over there. we will remove it.
