### ISSUE TITLE
LGPL Licence amendment

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/web3.js#2671]
The web3 library uses LGPL-3.0. This causes legal issues when trying to bundle it using webpack or creating a mobile app, since this is considered static linking.

according to the ethereum wiki I found this explanation:

> „In this way, while we have not arrived at a final license, we expect to select one of the MIT license, the MPL license or the LGPL license. If the latter is chosen, it will come with an amendment allowing it to be linked to be statically linked to software for which source code is not available.“ ( https://github.com/ethereum/wiki/wiki/Licensing ) 

I am not a lawyer, but if we stay with LGPL, we should add amendment mentioned above.

**Comment by guylando** [comment]
@simon-jentzsch what happened with this?

**Comment by simon-jentzsch** [comment]
For now, we decided not to use web3 since we may have to bundle it.

**Comment by nivida** [comment]
I will compare the license of web3 with other projects of the ethereum foundation and will change/update the license if required. Bundling of the lib is definitely allowed. I apologize for the confusion. @simon-jentzsch

**Comment by guylando** [comment]
@nivida It is better to compare to licences of other javascript projects specifically (if non-js ethereum project has some license, it should not give conclusions about a js project like this). For javascript projects the licenses are usually MIT in general.

**Comment by jimmy-dg** [comment]
Hi @nivida, any updates on this?

Thanks!
