### ISSUE TITLE
Support `toFixed` method on BigNumbers

### ISSUE THREAD

**Issue by rhlsthrm** [ethereum/web3.js#2675]
### Description 
`web3.eth.abi.decodeLog` now returns ethers.js `BigNumber` instances (which itself is inconsistent seeing as how Web3 removed BigNumber in favor of BN.js). These `BigNumber` instances do not support the method `toFixed()`. `toString()` can be unsafe, so we would like to only use `toFixed()`. Alternatively, support for getting the decoded data as strings instead of BigNumbers is an acceptable workaround.

#### Expected behavior

Calling `bigNumberInstance.toFixed()` should work.

#### Actual behavior

Calling `bigNumberInstance.toFixed()` returns an error.

#### Steps to reproduce the behavior

See Gist.

#### Gists

https://gist.github.com/rhlsthrm/9c198a5c4537a01fa521c97f0e785801

### Versions 
* web3.js: Beta 52
* nodejs:
* browser:
* ethereum node:

**Comment by princesinha19** [comment]
The BN.js library is only for integers that's why it doesn't support toFixed (). Can you explain why toString() can be unsafe?

**Comment by nivida** [comment]
We get the BigNumber object from ethers.js. Could you please open an issue in the ethers.js repository?

**Comment by bohendo** [comment]
@princesinha19 I see in the [docs of bignumber.js](https://github.com/MikeMcl/bignumber.js/#use) that calling `.toString()` of a very large number might return a number in exponent-form which would likely cause problems & might be where the concern is coming from.

But the more recent version of ethers depends on [bn.js](https://github.com/ethers-io/ethers.js/blob/master/package.json#L24) which does not have this problem.

So looks like this might be a false alarm..?

**Comment by princesinha19** [comment]
Yes right @bohendo. But, it's a problem of ethers.js because we are using ethers.js for BigNumber Object so, I think this should be solved by ethers.js.

**Comment by rhlsthrm** [comment]
Yes @bohendo it looks like ethers calls it `BigNumber` but it's actually bn.js so it's not an issue.
