### ISSUE TITLE
Make web3-eth-contract to work offline

### ISSUE THREAD

**Issue by ali92hm** [ethereum/web3.js#2677]
### Description 
This is more of a suggestion and I would like to hear everyone's feedback. It would be nice to have the module `web3-eth-contract` to work offline and not depend on a `provider`.

There are situations that one might just want to use the `Contract` constructor as a convenient way to get the `encodeABI` of a function or a constructor with a set of parameters without needing to supply a provider.

This is actually possible today if you pass a dummy url to the `Contract` constructor.

#### Expected behavior (nice to have)

```
import { Contract } from 'web3-eth-contract';
const myContract = new Contract(contractABI);
const data = myContract.methods[functionName](...params).encodeABI();
```

#### Actual behavior (today's implementation)

```
import { Contract } from 'web3-eth-contract';
// Passing a dummy url 
const myContract = new Contract("http://doesntNeedToExist.com", contractABI);
const data = myContract.methods[functionName](...params).encodeABI();
```

### Versions 
* web3.js: `1.0.0-beta.52`
* nodejs: `v11.14.0`
* browser: `N/A`
* ethereum node: `N/A`

**Comment by sshelton76** [comment]
Honestly I think your way is the best solution at the moment.  There isn't a need to "fix" this, but maybe explicit methods could be added to return what you're seeking.  What you describe works, and I bet it would work with just an empty string or a connection to localhost.  

If anything what you describe as your solution ought to represent a bug, but let's call it a quirk or a hack for now.

Explicitly what methods could you envision?  What would the API look like?  methods, parameters and returns?

**Comment by nivida** [comment]
I think adding of a ``web3.eth.abi.encodeABIItem()`` would be the solution for this. Would that be okay for you? @ali92hm

**Comment by ali92hm** [comment]
Sorry for the delay. 

I think that is fine. What parameters would this function take? Also that method would still require an instantiated `web3` or `eth` object which requires the dummy URL to instantiate.

Did you have something else in mind?

**Comment by pluswave** [comment]
seems web3-eth-abi can be used directly. 

````
const abi= require('web3-eth-abi');
const erc20 = require('human-standard-token-abi');
const transferAbiInterface = erc20.filter(x => x.name == 'transfer')[0];
youTx.data = abi.encodeFunctionCall(transferAbiInterface, [address, amount]);
````
