### ISSUE TITLE
contract().new() idiosyncrasies 

### ISSUE THREAD

**Issue by tgerring** [ethereum/web3.js#268]
When using contract().new() with a callback to get the contract address, it is not currently possible (0.8.1) to know when the transaction hash is available. The developer must wait an indeterminate amount of time, for example with setInterval(), and watch for the transaction hash being added. This is suboptimal and puts extra work on the developer.

Since there are 2 separate async events happening (sendTransaction and the contract being mined) it would be useful to notify the developer when any part of the contract information is updated. One option is to fire the callback multiple times and let the developer determine what to do based on the information available. For example, the callback could be called once when the transaction hash is available and again when the contract address is available.

**Comment by nmushegian** [comment]
I use a "confirm_receipt" helper which takes trxid and returns a (promise for) the contract.
There are a few other places where having easy-to-chain promises would be helpful. Feeding the compiler output into a deploy sequence is an example.
