### ISSUE TITLE
ENS reverse lookup

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2683]
### Description 

Implement the ENS reverse lookup.

Docs: https://docs.ens.domains/contract-api-reference/reverseregistrar

**Comment by princesinha19** [comment]
@nivida I think the ENS registry is also missing. 
Docs: https://docs.ens.domains/contract-api-reference/ens

you can add in this issue or if you want I can create a new issue.

**Comment by nivida** [comment]
The ens registry isn't missing. https://web3js.readthedocs.io/en/1.0/web3-eth-ens.html#registry

**Comment by princesinha19** [comment]
@nivida  all methods are not present, which is listed in this [docs](https://docs.ens.domains/contract-api-reference/ens).
Only registry is there.

**Comment by nivida** [comment]
Yep, there are some missing new methods. I was in contact with the ENS team and told them to check it. I'll do this together with the ENS reverse lookup because it isn't a big thing to add these methods. 

The current registry: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-ens/src/contracts/Registry.js

@jefflau

**Comment by ellis2323** [comment]
Is the reverse on the roadmap? or can we create a PR ?

**Comment by jamesmorgan** [comment]
This would be great, I see its be flagged for the `2.x` branch - I guess this means we wont make it into `1.x`?

**Comment by jamesmorgan** [comment]
It would be really awesome if this was priorities to be fixed - the current way, from my understanding, to allow users to claim subdomains on ENS is to send them to the ENS manager site or write some custom code, would be great if this was part of native we3js

**Comment by gpersoon** [comment]
I've created a code snippet to do a reverse lookup. 
```JS
async function Reverse(address) {        
    var lookup=address.toLowerCase().substr(2) + '.addr.reverse'
    var ResolverContract=await web3.eth.ens.resolver(lookup);
    var nh=namehash.hash(lookup);
    var name=await ResolverContract.methods.name(nh).call()
    return name;
}    
```

**Comment by x48-crypto** [comment]
@nivida I see your commit "Implements all methods of the ENS registry," but don't see any information on reverse lookup in documentation. How can I use web3 to reverse resolve an address into an ENS name? Thanks!

**Comment by mqklin** [comment]
@x48-crypto check [this comment](https://github.com/ethereum/web3.js/issues/2683#issuecomment-547348416)

**Comment by lucadonnoh** [comment]
any update?

**Comment by blankey1337** [comment]
Here is a snippet of the above with the recommended forward lookup to avoid imposters:

```typescript
async function reverseENSLookup(address: string, web3: Web3) {        
  let lookup = address.toLowerCase().substr(2) + '.addr.reverse'
  let ResolverContract = await web3.eth.ens.getResolver(lookup);
  let nh = namehash.hash(lookup);
  try {
    let name = await ResolverContract.methods.name(nh).call();
    if (name && name.length) {
      const verifiedAddress = await web3.eth.ens.getAddress(name);
      if (verifiedAddress && verifiedAddress.toLowerCase() === address.toLowerCase()) {
        return name;
      }
    }
  } catch(e) { }
}  
```

**Comment by giannisftaras** [comment]
> Here is a snippet of the above with the recommended forward lookup to avoid imposters:
> 
> ```ts
> async function reverseENSLookup(address: string, web3: Web3) {        
>   let lookup = address.toLowerCase().substr(2) + '.addr.reverse'
>   let ResolverContract = await web3.eth.ens.getResolver(lookup);
>   let nh = namehash.hash(lookup);
>   try {
>     let name = await ResolverContract.methods.name(nh).call();
>     if (name && name.length) {
>       const verifiedAddress = await web3.eth.ens.getAddress(name);
>       if (verifiedAddress && verifiedAddress.toLowerCase() === address.toLowerCase()) {
>         return name;
>       }
>     }
>   } catch(e) { }
> }  
> ```

I am trying to implement your snippet using Web3JS from a CDN but I am getting an error "namehash: is not defined". The namehash object appears to be implemented in the library but I am not able to call it. Apparently I am missing something...

**Comment by gpersoon** [comment]
Namehash can be found here: https://www.npmjs.com/package/@ensdomains/eth-ens-namehash

**Comment by giuseppeg** [comment]
I am using this snippet:

```js
async function reverseLookup(address, web3) {
  const lookup = `${address.slice(2)}.addr.reverse`;
  const hash = namehash.hash(lookup);
  const resolver = await web3.eth.ens.getResolver(lookup);

  try {
    const name = await resolver.methods["name(bytes32)"](hash).call();
    return name;
  } catch (e) {
    return null;
  }
}
```

But fails with

```
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.decodeParametersWith (index.js?efc6:304:1)
    at ABICoder.decodeParameters (index.js?efc6:291:1)
    at Contract._decodeMethodReturn (index.js?0505:493:1)
    at Method.outputFormatter (index.js?0505:800:1)
    at Method.formatOutput (index.js?9c92:148:1)
    at sendTxCallback (index.js?9c92:531:1)
    at cb (util.js?2b38:701:1)
    at Item.run (browser.js?5cb3:153:1)
    at drainQueue (browser.js?5cb3:123:1)
```

This is regardless of whether I use `resolver.methods["name(bytes32)"](lookup)` or `resolver.methods.name(lookup)`.

Does anybody have any idea of what is going on?

**Comment by numtel** [comment]
I didn't want to import any extra modules to my frontend so I use this function:

```js
async function ensReverse(address) {
  const web3 = new Web3('https://eth.public-rpc.com/');
  const namehash = await web3.eth.call({
    to: '0x084b1c3c81545d370f3634392de611caabff8148', // ENS: Reverse Registrar
    data: web3.eth.abi.encodeFunctionCall({
      name: 'node', type: 'function',
      inputs: [{type: 'address', name: 'addr'}]
    }, [address])
  });
  return web3.eth.abi.decodeParameter('string', await web3.eth.call({
    to: '0xa2c122be93b0074270ebee7f6b7292c7deb45047', // ENS: Default Reverse Resolver
    data: web3.eth.abi.encodeFunctionCall({
      name: 'name', type: 'function',
      inputs: [{type: 'bytes32', name: 'hash'}]
    }, [namehash])
  }));
}
```
