### ISSUE TITLE
BN example does not work

### ISSUE THREAD

**Issue by kevinsimper** [ethereum/web3.js#2687]
There is a reference to an example with BN.js, but it doesn't work in the version ` 1.0.0-beta.52`.

https://web3js.readthedocs.io/en/1.0/web3-utils.html#id5

![image](https://user-images.githubusercontent.com/1126497/56169224-50626380-5f92-11e9-89c8-b9a7ac184ec6.png)

**Comment by nivida** [comment]
Thanks for opening this issue! I will fix and release it asap.

**Comment by kevinsimper** [comment]
@nivida Thanks for the response 😄 Great to hear 💛
