### ISSUE TITLE
Rethink utils

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2690]
[Currently](https://web3js.readthedocs.io/en/1.0/web3-utils.html) the instance of `web3` has a member variable `utils` which provides **static** util methods. So a lot of people who only need a static utils method like `randomHex` do this:

```js
import Web3 from 'web3'
const web3 = new Web3()
web3.utils.randomHex('...')
```

Which is totally wrong an awkward. There is no reason to attach the utils to the instance of web3. Right now one can use the package `web3-utils` for an easier approach:

```js
import * as web3Utils from 'web3-utils'
web3Utils.randomHex('...')
```

This is nicer but also a little annoying to do. I recommend to export the Utils as a variable at the global export object. Then one can do this:

```js
import Web3 from 'web3'
Web3.utils.randomHex('...')
```

To emphasize: Any method or variable that does not need instance state should always be static and never a member variable of a classes instance.

**Comment by nivida** [comment]
I totally agree with you 👌

**Comment by nivida** [comment]
@Levino Btw.: The long term goal will be to have a ``core/types`` module with VO e.g.: ``Hex.from()`` A friendly contributor already started with some drafts here https://github.com/ethereum/web3.js/pull/2208

``` javascript 
import {Hex} from 'web3';
const hex = Hex.from(100);
hex.toString();
```


Edit: 
Gist draft for types module https://gist.github.com/nivida/d75c26daea14607f0c57b42582b34f78
