### ISSUE TITLE
AbiCoder::decodeLog throws error when all inputs are indexed

### ISSUE THREAD

**Issue by Anaphase** [ethereum/web3.js#2695]
### Description

When decodeLogs is called (internally after I send a transaction) for a log that has all-indexed parameters, the `Empty outputs array given!` error is thrown.

#### Expected behavior
Calling `decodeLogs()` with inputs that are all "indexed" should not attempt to pass an empty `nonIndexedInputItems` array to `decodeParameters()`

#### Actual behavior
Calling `decodeLogs()` with inputs that are all "indexed" passes an empty `nonIndexedInputItems` array to `decodeParameters()` which throws an error.

#### Steps to reproduce the behavior
Send a transaction that generates a log with only indexed inputs. For reference, I'm calling `mint()` on a standard ERC-721 token.

I'm not sure the best way to give you reproducible steps, but here's sample input for decodeLogs:

```javascript
{
  "inputs": [
    {
      "indexed": true,
      "name": "_from",
      "type": "address"
    },
    {
      "indexed": true,
      "name": "_to",
      "type": "address"
    },
    {
      "indexed": true,
      "name": "_tokenId",
      "type": "uint256"
    }
  ],
  "data": "0x0",
  "topics": [
    "0x0000000000000000000000000000000000000000000000000000000000000000",
    "0x000000000000000000000000627306090abab3a6e1400e9345bc60c78a8bef57",
    "0x000000000000000000000000000000000000000000000000000000000000000c"
  ]
}
```

### Related Issues
This issue seems to be related: #2065

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: 10.11.0
* browser: Chrome 73.0.3683.103
* ethereum node: Ganache

**Comment by Anaphase** [comment]
Unfortunately, I still can't get the test suite to run locally on my machine so I can't reliably test a Pull Request. I think a possible solution would be to update [the conditional in `decodeLog` on line 234](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-abi/src/AbiCoder.js#L232):

```diff
- if (data) {
+ if (data && data !== '0x' && nonIndexedInputItems.length !== 0) {
    let values = this.decodeParameters(nonIndexedInputItems, data);

    let decodedValue;
    nonIndexedInputKeys.forEach((itemKey, index) => {
        decodedValue = values[index];

        returnValues[itemKey] = decodedValue;
        returnValues[nonIndexedInputItems[index].name] = decodedValue;
    });
}
```

(Note that the "empty data" check discussed in #2582 is also included above.)

**Comment by nivida** [comment]
Thanks for opening this issue! Did you test it also with geth or parity?

As it looks like is ganache returning an invalid JSON-RPC response because the data property should be ``0x`` which represents ``null`` or ``undefined``. The data property which ganache is returning ``0x0`` does represent ``false``.

**Comment by Anaphase** [comment]
Hmm, so you're saying if all inputs are indexed, then data is _always_ supposed to be `0x`? It might be an issue with Ganache then... Let me try to update Ganache and see if that helps.

**Comment by Anaphase** [comment]
Good call, it was indeed my outdated version of Ganache sending the wrong response data! I'll go ahead and close this, sorry for all the noise...
