### ISSUE TITLE
Cannot resolve module 'net'

### ISSUE THREAD

**Issue by caktux** [ethereum/web3.js#270]
```
ERROR in ./~/web3/lib/web3/ipcprovider.js
Module not found: Error: Cannot resolve module 'net' in [...]/web3/lib/web3
 @ ./~/web3/lib/web3/ipcprovider.js 36:17-31
```

**Comment by simondlr** [comment]
Getting the same. Shouldn't it be:

require('./net');

?

**Comment by frozeman** [comment]
hm net is a standard module in node. In which environments you're getting this error?

**Comment by caktux** [comment]
Using webpack, and if webpack complains then there's something fishy ;)

**Comment by frozeman** [comment]
The IPC provider is only useable in node environments and mist frontend, therefor probably you web pack complain.

**Comment by frozeman** [comment]
if you have an idea how we can hide that module from web pack, would be great.

**Comment by caktux** [comment]
added extra configs to webpack to solve it:
```
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```
having a `net` module in web3 made this issue rather confusing..

**Comment by debris** [comment]
@frozeman I think that it is good moment to clean up everything. Can we move `ipcprovider` from `web3.js` to `mist`? Or to it's own repo? It just doesn't belong here. We should make web3 a backbone, not double-edged sword.

**Comment by frozeman** [comment]
the IPC provider is necessary for node based applications, which want to talk t a local node.
So every hybrid dapp, would need it. Though it doesn't work in the browser, thats true. We can hide it from there and i add it in mist myself.

Would it be enough to add a check in the `index.js`?
```js
if(type window !== 'undefined')
 // add IPC provider
```
