### ISSUE TITLE
Create some sort of document for typing

### ISSUE THREAD

**Issue by princesinha19** [ethereum/web3.js#2704]
I was thinking that we should create some sort of document so that contributors can update typing modules as per said instructions. This will save much time when reviewing any PR.
As, When to use `any` and If some type got used in many places then, it should be added to web3-core.
Also, someone should not create any unnecessary dependency, when updating typings.

We can add this in contributors sections.

What do you say @joshstevens19 and @nivida?

**Comment by joshstevens19** [comment]
Yep i think that sounds good, we want to make it clear what to do and what not to do👍 Great idea!

**Comment by joshstevens19** [comment]
FYI I will mock something up about this next week and do a PR for it. It’s defo needed 👍

**Comment by princesinha19** [comment]
Sounds great @joshstevens19. Once you will create some document, I could contribute something from my side too.

**Comment by joshstevens19** [comment]
Sorry i have fall behind on this, mainly because other work commitments. I will get a PR up next week :+1:
