### ISSUE TITLE
web3.eth.subscribe() not working, all types

### ISSUE THREAD

**Issue by buildbrett** [ethereum/web3.js#2706]
### Description 
`web3.eth.subscribe(type)` is not working for types `'pendingTransactions'`, `'syncing'`, or `'newBlockHeaders'`.

#### Expected behavior

Calling 
```js
web3.eth.subscribe('pendingTransactions', 
  (error, result) => console.log(error, result)
) ;
```
should print the connection result or error to the console. Further, chained `.on('data')`, `.on('changed')`, and `.on('error')` do not fire.
The same would be expected with type `'syncing'` or `'newBlockHeaders'`.

#### Actual behavior

Calling `web3.eth.subscribe('syncing', (error, result) => console.log(error, result)) ;` does nothing. Nothing is logged, including on `'data', 'changed', or 'error'` events. 

#### Steps to reproduce the behavior

```js
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/v3/your-api-token-here'));

web3.eth.subscribe('pendingTransactions', (error, result) => {
  if (!error) console.log('result: ', result);
  console.log('error: ', error);
})
.on('data', (log) => {
  console.log('data: ', log);
})
.on('changed', (log) => {
  console.log('changed: ', log);
})
.on('error', (log) => {
  console.log('error: ', log);
});
```

### Versions 
* web3.js: `1.0.0.0-beta.52`
* nodejs: `v11.12.0`
* ethereum node: *not sure how to get this from Infura*

*NOTE, Infura RPC subscribe commands seem to be working using websockets, so my assumption is that this is not an issue with Infura.

#### P.S.
I'm new here. If my issue is can be improved in any way, suggestions on how to do so are welcome!

### EDIT:
May be related to issue #1752 ?

**Comment by nivida** [comment]
I think the WebSocket URL you are using is not correct. 

[WS Documentation Infura
](https://infura.io/docs/ethereum/wss/introduction)
It works with:
``` javascript
const web3 = new Web3(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/ws/v3/project-id'));

web3.eth.subscribe('pendingTransactions', (error, result) => {
  if (!error) console.log('result: ', result);
  console.log('error: ', error);
})
  .on('data', (log) => {
    console.log('data: ', log);
  })
  .on('error', (log) => {
    console.log('error: ', log);
  });
```

**Comment by buildbrett** [comment]
@nivida That's it, thank you. :man_facepalming: Looks like I copied https endpoint and changed to wss, missing the `/ws`.

Is it the correct behavior for `web3.eth.subscribe` to not log an error when the provider is responding with `404` errors? If the callback for `web3.eth.subscribe` isn't the place to catch the `404`, where would be the correct place?

**Comment by nivida** [comment]
I've closed this issue because I gave the answer in issue #2731
