### ISSUE TITLE
Can't execute batchRequest with privateKey

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#2708]
### Description 
```js
const Web3 = require('web3')
const {numberToHex, toWei, toHex} = require('web3-utils')
const web3 = new Web3('https://kovan.infura.io')

async function main() {
  const acc = web3.eth.accounts.wallet.add(process.env.KEY)
  const cb = number => {
    console.log(number, 'callback from batch tx')
  }
  const batch = new web3.BatchRequest()
  let i = 0
  const tx = web3.eth.sendTransaction.request(
    {
      from: acc.address,
      to: '0x0039f22efb07a647557c7c5d17854cfd6d489ef3',
      gas: numberToHex(21000),
      gasPrice: toWei('1', 'gwei'),
      value: toWei('2'),
      data: toHex('peppersec.com')
    },
    cb.bind(this, i)
  )
  i++
  batch.add(tx)
  await batch.execute()

}
main()
```

#### Expected behavior
should send batch request using sendRawTx RPC method if used with privateKey

#### Actual behavior
(node:47721) UnhandledPromiseRejectionWarning: Error: BatchRequest error: ["Response should be of type Array but is: object"]
    at /node_modules/web3-providers/dist/web3-providers.cjs.js:824:17
    at process._tickCallback (internal/process/next_tick.js:68:7)

The response object from `web3-providers/dist/web3-providers.cjs.js:824:17`:
```
response { jsonrpc: '2.0',
  id: 0,
  error:
   { code: -32601,
     message:
      'The method eth_sendTransaction does not exist/is not available' } }
```

I think it should sign tx, increment nonce and use `sendRaw` rpc method behind the scenes
### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: v10.15.3

**Comment by PeterTheOne** [comment]
Related https://github.com/ethereum/web3.js/issues/1321
