### ISSUE TITLE
type 'string' wont auto convert 'bytes32' value from geth RPC

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/web3.js#271]
So I have a bytes32 return from a contract getter (call). I want one of the return values which is a bytes32 to be treated like a string (so encoded/decoded automatically). I figured that I could just change the output ABI object type from 'bytes32' to 'string' and the auto conversion would be taken care of. In doing this, I got a 'Uncaught BigNumber Error: new BigNumber() not a base 16 number: ' error. Am I approaching this wrong?

```
var abi = [
  {
    "constant": true,
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "someCallMethod",
    "outputs": [
      {
        "name": "name",
        "type": "string" // was originally a 'bytes32'
      },
];

var Contract = web3.eth.contract(abi);
var ContractInstance = Contract.at(address);
console.log(ContractInstance.someCallMethod(0));
```

**Comment by debris** [comment]
`string` is not equal to `bytes32` but `bytes`. It's length is dynamic, eg

"gavofyork" as string/bytes is encoded to:

```js
'0000000000000000000000000000000000000000000000000000000000000020' +  // position of length
'0000000000000000000000000000000000000000000000000000000000000009' +  // length of the string
'6761766f66796f726b0000000000000000000000000000000000000000000000'  // "gavofyork"
```

whereas as bytes32 is encoded to:

```js
'6761766f66796f726b0000000000000000000000000000000000000000000000'  // "gavofyork"
```

I will talk to Christian about possible improvements. Maybe reintroducing `string32` type would be a good idea. I will give you and update later today.

**Comment by chriseth** [comment]
If you change the ABI, you should also change the source.
The reason why there is no `string32` is that the natural interpretation of `string32` is a string of 32 characters (not bytes). Since not all characters fit in one byte, the storage size of a 32 byte string could be anywhere between 32 bytes and 128 (?) bytes, so it is not guaranteed to fit in a EVM word.

**Comment by SilentCicero** [comment]
@chriseth ah, I see now. But will mapping(string => someType) be available? I guess i just need to know what the right way is to move between bytes32 and string.

@debris I secretly want to get auto conversion back for bytes32 as an option. I'll see if I can build my own layer on top to provide this functionality back (in a secondary module to web3). But it was nice when bytes32 was like strings. Even though I completely understand that thinking has its limitations (i.e. when bytes32 is not suppose to be a string).

**Comment by chriseth** [comment]
@SilentCicero mappings with strings as keys is on the backlog, but not available yet. As a workaround, you can sha3 the string before using it as key:
`mapping(bytes32 => uint) x; ... x[sha3(theString)] = 2;`
