### ISSUE TITLE
Absolutely wrong documentation for creating a new contract

### ISSUE THREAD

**Issue by Smyak** [ethereum/web3.js#2718]
### Description 
Documentation described at [https://github.com/ethereum/web3.js/blob/1.0/docs/web3-eth-contract.rst](url) has wrong method names and structure

#### Expected behavior
`const newContract = new web3.eth.Contract(jsonInterface, address, options);
newContract
.deploy({data: '0x12345...',arguments: [123, 'My String']})
.send({
    from: '0x1234567890123456789012345678901234567891',
    gas: 1500000,
    gasPrice: '30000000000000'
}, (error, transactionHash) => { ... })
.on('error', (error) => { ... })
.on('transactionHash', (transactionHash) => { ... })
.on('receipt', (receipt) => {
   console.log(receipt.contractAddress) // contains the new contract address
})
.on('confirmation', (confirmationNumber, receipt) => { ... })
.then((newContractInstance) => {
    console.log(newContractInstance.options.address) // instance with the new contract address
});`

should sign transaction for creating new contract and send it to blockchain (as described at documentation)
#### Actual behavior
Actually code above contains a lot of errors - there are no web3.eth.Contract function, no deploy function. Code that works:
`new web3.eth.contract(jsonInterface, address, options)
.new({
    data: '0x12345...',
    from: '0x1234567890123456789012345678901234567891',
    gas: 1500000,
    gasPrice: '30000000000000'
    }, (error, transactionHash) => { ... })
.on('error', (error) => { ... })
.on('transactionHash', (transactionHash) => { ... })
.on('receipt', (receipt) => {
   console.log(receipt.contractAddress) // contains the new contract address
})
.on('confirmation', (confirmationNumber, receipt) => { ... })
.then((newContractInstance) => {
    console.log(newContractInstance.options.address) // instance with the new contract address
});`

### Versions 
* web3.js: 1.0.0-beta.52 
* nodejs:10.15.3
* browser:
* ethereum node:Parity-Ethereum//v2.3.1

**Comment by princesinha19** [comment]
@Smyak  The documentation is right. I am using the below code and it works. I have tested it on Geth and it also works with Ganache.

```
// Defining New Contract 
let myContract = new web3.eth.Contract(abi);

// Deploying contract using Web3
myContract.deploy({
	data: '0x' + bytecode,
	arguments: []
}).send({
	from: "0x01........"
	gas: 21000
}).on('receipt', (receipt) => {};
```
And, the contract deployment using `new` is in web3 v0.2x.x, not web3 version 1.
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract

**Comment by Smyak** [comment]
You are right.
