### ISSUE TITLE
 1.0.0-beta.52 Contract.methods.myMethod.send() hangs 

### ISSUE THREAD

**Issue by eastredn** [ethereum/web3.js#2721]
### Description 
same problem with
https://github.com/ethereum/web3.js/issues/2462#issue-417798277

diff:  version 1.0.0-beta.52 
        call send will hangs :
  dataContract.methods.test().send(defaultOption)
    .on('transactionHash', function(hash){
        console.log("event hash:",hash);
        return false;
    })
    .on('confirmation', function(confirmationNumber, receipt){
        //console.log("confirmation confirmNum,receipt:",confirmationNumber,receipt);
        console.log("confirmation confirmNum,receipt:",confirmationNumber);
        return false;
    })
    .on('receipt', function(receipt){
        console.log("event receipt:",receipt);
        return false;
    })
    .on('error', console.error); 

#### Expected behavior

      contract.methods.test().send(defaultOption).on('receipt', (res) => { ... });
should sent the transaction and  recv  transactionHash,confirmation,receipt event 

#### Actual behavior

It  send the transaction ,I recv the  hash event,and once confirmation event, didn't recv receipt event .    then hang......
(in fact ,the transaction is successed send. )

#### Steps to reproduce the behavior

 1. Import `web3`
 2. Set the provider to `localhost`
....
### Versions 
* web3.js:  1.0.0-beta.52 
* nodejs:  10.5.0
* browser:  
* ethereum node:    1.8.24-stable-4e13a09c

**Comment by nivida** [comment]
This got fixed with https://github.com/ethereum/web3.js/pull/2703 and will be released asap.
