### ISSUE TITLE
web3.eth.accounts.wallet.create returns inconsistent accounts

### ISSUE THREAD

**Issue by sshelton76** [ethereum/web3.js#2725]
### Description 

When supplying your own entropy to web3.eth.accounts.wallet.create the address returned appears to be random.

#### Expected behavior
The expectation is that if entropy is supplied that the resulting wallet accounts will always be the same.

#### Actual behavior
It appears that the accounts created within the wallet are randomly generated despite the fact you are supplying entropy.  Either this is designed behavior which is undocumented, or there is a bug here.  We either need to fix the bug so the same accounts are created or we need to document what the entropy is supposed to be used for.  I have gone through the source code and it appears that consistent entropy should result in consistent accounts...
However eth-lib appears to be inserting random values despite supplied entropy...
https://github.com/MaiaVictor/eth-lib/blob/master/src/account.js

#### Steps to reproduce the behavior
1. Generate entropy from a consistent source, for example from bip39.js mnemonic to entropy or mnemonic to seed  function.
2. Call 
```
let seed = await (await bip39.mnemonicToSeed(mnemonic)).toString('hex');
        
        this.wallet = this.web3.eth.accounts.wallet.create(1, seed);
        console.debug("wallet: ",this.wallet);
```
3. Do this a few times and notice that the resulting accounts are different every time.

### Versions 
* web3.js:
beta-37 and beyond

**Comment by nivida** [comment]
Did you test it also with the latest version of Web3.js?

**Comment by nivida** [comment]
I will remove the eth-lib dependency and will refactor the code for the usage of the [ethereumjs-wallet](https://github.com/ethereumjs/ethereumjs-wallet) package.

**Comment by sshelton76** [comment]
Awesome thanks!

**Comment by lucille-bellepleure** [comment]
I have this issue!
