### ISSUE TITLE
CDN for the latest web3js version

### ISSUE THREAD

**Issue by BesrourMS** [ethereum/web3.js#2729]
I don't find a CDN link for the latest web3js version, the only cdn that I found is : 
https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.37/dist/web3.min.js

How can I use "web3.js 1.0.0-beta.52" directly in browser ?

**Comment by nivida** [comment]
Duplication of https://github.com/ethereum/web3.js/issues/2623
