### ISSUE TITLE
Invalid UTF8 not handled properly in ABI decoders

### ISSUE THREAD

**Issue by chriseth** [ethereum/web3.js#273]
If a contract returns an invalid utf8 string, the decoder throws an exception, which should be properly converted into an error and fed into the asynchronous call chain.

**Comment by caktux** [comment]
decodeURIComponent in utils.toAscii breaks any non-UTF8 string...

**Comment by debris** [comment]
fixed in ac7ac1476082fa4ce403948e38aa31c6e550d8c6
