### ISSUE TITLE
event loop crashes on web3 call

### ISSUE THREAD

**Issue by yabloki** [ethereum/web3.js#2730]
### Description 

Running a truffle test suite and event loop crashes  on await web3.eth.getNodeInfo();

#### Expected behavior

no crash

#### Actual behavior

an uncaught exception bubbles up and crashes event loop
I tried to surround all the calls with try-catch but wasn't able to catch the error.

#### Steps to reproduce the behavior

1.  get an unresolved promise of contract.send
2. await to getNodeInfo call

    ```js
      
       new web3.eth.Contract(token.abi, 
                          token.address).methods['send(address,uint256,bytes)](
        to,
        amount.toString(),
        web3.utils.toHex('test data'),
      ).send(meta);

       await web3.eth.getNodeInfo(); 

#### Error Logs 

Users/xx/src/xx/node_modules/mocha/lib/runner.js:707
  err.uncaught = true;
               ^
TypeError: Cannot create property 'uncaught' on string 'abort({}). Build with -s ASSERTIONS=1 for more info.'
    at Runner.uncaught (/Users/xx/src/xx/node_modules/mocha/lib/runner.js:707:16)
    at process.uncaught (/Users/xx/src/xx/node_modules/mocha/lib/runner.js:821:10)
    at process.emit (events.js:194:15)
    at process.emit (/Users/xx/src/xx/node_modules/truffle/build/webpack:/~/source-map-support/source-map-support.js:461:1)
    at process._fatalException (internal/bootstrap/node.js:496:27)


### Versions 
* web3.js: 1.0.0-beta.37
* nodejs: v10.15.3
* ethereum node:  EthereumJS TestRPC/v2.5.1/ethereum-js

**Comment by nivida** [comment]
Because of the added error message does it not look like an issue of Web3.js. Could you update to the latest version of Web3.js and could you also provide a GitHub repository to reproduce the issue?

**Comment by nivida** [comment]
I've closed this issue because of the inactivity of the creator. Feel free to open a new issue with all the required information.

**Comment by colltoaction** [comment]
I am facing this issue too. I'll try to make a shorter repro, but here are the steps I have so far:

1. clone https://github.com/rsksmart/openzeppelin-solidity
2. run the same steps as Circle CI:

```
docker build -t rsksmart/openzeppelin . -f docker/Dockerfile
docker build -t rsksmart/rskj https://github.com/rsksmart/rskj.git -f - < docker/Dockerfile-rskj
docker run -d --name rskj -e "miner.client.autoMine=true" rsksmart/rskj --regtest
docker run --name openzeppelin --network container:rskj rsksmart/openzeppelin npm test
```

At some point I see the exact same error, but it is always in a different part of the test suite. The only thing that's constant is that it happens when running OpenZeppelin's `expectRevert` (see https://github.com/OpenZeppelin/openzeppelin-test-helpers).

**Comment by colltoaction** [comment]
Worth noting:
* `expectRevert` also calls `getNodeInfo`: https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/099b53e051d8f5331dba1eafd45a8138760937dd/src/expectRevert.js#L28
* this happens on the Docker instance but not locally on my Mac
