### ISSUE TITLE
Improve error handling of subscriptions

### ISSUE THREAD

**Issue by alejagapatrick** [ethereum/web3.js#2731]
@nivida That's it, thank you. :man_facepalming: Looks like I copied https endpoint and changed to wss, missing the `/ws`.

Is it the correct behavior for `web3.eth.subscribe` to not log an error when the provider is responding with `404` errors? If the callback for `web3.eth.subscribe` isn't the place to catch the `404`, where would be the correct place?

_Originally posted by @carterbrett in https://github.com/ethereum/web3.js/issues/2706#issuecomment-485109475_

**Comment by nivida** [comment]
Thanks for opening this issue! 
No this isn't the correct behavior. I will add the socket error handling [here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js#L95).
