### ISSUE TITLE
Why test types with nightly builds of typescript?

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2732]
Currently `1.0` does not build because the nightly version of Typescript does not like the current type defs and has been updated tonight. Why are we using `--onlyTestTsNext` for dslint?

**Comment by nivida** [comment]
We have added this for testing the types only with the next version. But we could also define a local TS version with [``--localTS``](https://github.com/Microsoft/dtslint/pull/207).

**Comment by levino** [comment]
The next version is the nightly build. It changes every day. Why would one want to use this? Should one not use the latest stable version?

**Comment by nivida** [comment]
Yes, I agree with you. The localTS option didn’t exists when we were setting up the type tests.
