### ISSUE TITLE
Missing member names if struct contains single scalar variable

### ISSUE THREAD

**Issue by milesfrain** [ethereum/web3.js#2736]
Here is a scenario where this behavior becomes an issue for developers:
1. Use a struct that contains two scalar fields and a bunch of indexed fields (arrays, mappings). The additional indexed fields are merely to make this struct a less trivial example.
2. Write a test case that accesses these scalar fields by name.
3. Remove a scalar field from the struct, so that only one scalar field remains.
4. Test cases that accesses this remaining scalar field by name now fail with an `undefined` value, even though this field still exists in the struct.

Is this desired and expected behavior, and is this quirk documented anywhere?

Below is a simpler contract and test to demonstrate a disappearing field name:

In Remix, the `scalarVar` field is visible for both the `OneScalar` and `TwoScalars` structs, but in web3js in truffle the `scalarVar` field name is missing from the `OneScalar` struct. This prevents accessing scalar struct members by name in truffle (e.g. `oneScalar.scalarVar`) unless an additional dummy scalar member is included.

### Solidity Contract:
```
pragma solidity ^0.5.0;

contract StructAccess {

    struct OneScalar {
        uint scalarVar;
    }

    struct TwoScalars {
        uint scalarVar;
        uint dummyScalarVar;
    }

    OneScalar public oneScalar;
    TwoScalars public twoScalars;
}
```

### Truffle web3js Test Code:
```
const StructAccess = artifacts.require("StructAccess");
contract('StructAccess', (accounts) => {
  it('should log structs', async () => {
    const accessInstance = await StructAccess.deployed();

    const oneScalar = await accessInstance.oneScalar();
    const twoScalars = await accessInstance.twoScalars();

    console.log({oneScalar});
    console.log({twoScalars});
  });
});
```

### web3js Log Output:
```
  Contract: StructAccess

{ oneScalar: <BN: 0> }

{ twoScalars:
   Result {
     '0': <BN: 0>,
     '1': <BN: 0>,
     scalarVar: <BN: 0>,
     dummyScalarVar: <BN: 0> } }
```

#### Remix Interface:
![image](https://user-images.githubusercontent.com/3578681/56752953-ba26fe00-6746-11e9-87f7-9584e185aee1.png)

#### Version Info:
```
> truffle version
Truffle v5.0.13 (core: 5.0.13)
Solidity v0.5.0 (solc-js)
Node v8.11.2
Web3.js v1.0.0-beta.37
```

**Comment by nivida** [comment]
Does this behavior still occur with the latest version of Web3.js?

**Comment by milesfrain** [comment]
I am having difficulty upgrading truffle to use the latest version of Web3.js.
Are these still the appropriate instructions? I can install the latest version of Web3.js through npm, `1.0.0-beta.52`, but the last line, `var web3latest = new Web3latest();`, throws errors.
https://ethereum.stackexchange.com/questions/38669/manually-set-web3-version-in-truffle

I'm tempted to wait until the next truffle release, which should include a more recent version of Web3.js, although I'm not sure if this will ever be the latest version of Web3.js.

**Comment by nivida** [comment]
I'm in contact with the truffle team and the latest release (1.0.0-beta.53) contains the required fixes for truffle. The problem was that truffle was initiating the Web3 object without a provider and the Web3 library couldn't handle this.

**Comment by nivida** [comment]
I've closed this issue because it isn't directly an issue of Web3.js.
