### ISSUE TITLE
BatchRequest  execute catch error: TypeError: method.beforeExecution is not a function

### ISSUE THREAD

**Issue by eastredn** [ethereum/web3.js#2748]
### Description 
 var batch = new web3.BatchRequest();
batch.add(req);
batch.execute();

catch error：TypeError: method.beforeExecution is not a function

#### Expected behavior

1.batch send transaction  without error
2.if use await batch.execute() should block the program.
#### Actual behavior

1. catch  error：TypeError: method.beforeExecution is not a function
2. the tx  sent success.
3.if  use await  cound't block the program

#### Steps to reproduce the behavior

async function writeChain() {
    let total = 0;
    let count = 0;
    for (let index = 0; index < kindAry.length; index++) { 
        total += kindAry[index].fcall.length;
    }
    console.log("total:", total);

    let promise = new Promise((resolve, reject) => {
        var batch = new web3.BatchRequest();
        for (let index = 0; index < kindAry.length; index++) { 
            let afunc = kindAry[index];
            let afuncCount = afunc.fcall.length;
            for (let i = 0; i < afuncCount; i++) {
                if (!afunc.fcall[i].ignore) {
                    console.log(afunc.fcall[i].func.name);
                    let req = dataContract.methods[afunc.fcall[i].func.name].apply(dataContract, afunc.fcall[i].paraAry).send({ from: addrOwner, gasPrice: gasPriceh }, (err, res) => {
                        count++;
                        if (err) {
                            kindAry[index].fcall[i].sendErr = true;
                            kindAry[index].fcall[i].sendhash = "";
                            console.log("send err fcall: ", afunc.fcall[i]);
                            throw err;
                        } else {
                            kindAry[index].fcall[i].sendErr = false;
                            kindAry[index].fcall[i].sendHash = res;
                            console.log("result:", res)
                        }
                        if (count >= total) {
                            console.log("send complete");
                            resolve();
                        }
                    });
                    batch.add(req);
                }
            }
        }
        try {
            batch.execute();
        } catch (error) {
            console.log("try catch err:", error);
        }
    })
    return promise;
}

#### Error Logs 
try catch error:
TypeError: method.beforeExecution is not a function
restoreData.js:779
[[StableObjectId]]:27
message:"method.beforeExecution is not a function"
stack:"TypeError: method.beforeExecution is not a function\n    at e:\work\eth\contractData\node_modules\web3-providers\dist\web3-providers.cjs.js:731:16\n    at Array.forEach (<anonymous>)\n    at HttpProvider.sendBatch (e:\work\eth\contractData\node_modules\web3-providers\dist\web3-providers.cjs.js:730:15)\n    at BatchRequest.execute (e:\work\eth\contractData\node_modules\web3-providers\dist\web3-providers.cjs.js:799:50)\n    at Promise (e:\work\eth\contractData\restoreData.js:777:19)\n    at new Promise (<anonymous>)\n    at writeChain (e:\work\eth\contractData\restoreData.js:740:17)\n    at writeChainFromKindAry (e:\work\eth\contractData\restoreData.js:790:11)\n    at main (e:\work\eth\contractData\restoreData.js:881:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)"

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: 10.15.3
* browser:
* ethereum node:  geth 1.8.24

**Comment by nivida** [comment]
The documented way to add a item to the [BatchRequest](https://web3js.readthedocs.io/en/1.0/web3.html#batchrequest) object is:
``` javascript 
const contract = new web3.eth.Contract(abi, address);

const batch = new web3.BatchRequest();
batch.add(contract.methods.balance(address).call.request({from: '0x0000000000000000000000000000000000000000'}));
batch.add(contract.methods.setBalance(100).send.request({from: '0x0000000000000000000000000000000000000000'}));
batch.execute().then(...);
```

**Comment by vincent144** [comment]
I'm getting the same error when I try 

```
batch.add(web3.eth.getBalance.request(address, 'latest', callback);
```

which is how it is done in this test https://github.com/ethereum/web3.js/blob/1.x/test/batch.js#L43-L47

Is this approach no longer valid? Does this test not pass anymore?
