### ISSUE TITLE
Can't use parameters of type address

### ISSUE THREAD

**Issue by ckeenan** [ethereum/web3.js#275]
Tested with geth 0.9.38, 0.9.39 and web3 0.8.1, 0.9.1
The code
```
contract Test {
    function Test (address addr) {
        addrRef = addr;
    }

    function nonConstructor(address addr) {
        addrRef = addr;
    }
    address public addrRef;
}
```
will return a `0x0000000000000000000000000000000000000000` for addresses passed into both constructor and non-constructor methods. Other parameter types work without issue

**Comment by ckeenan** [comment]
Reinstalled solidity and that resolved the issue for non-constructor methods.
Now no parameter types are working in constructors

**Comment by chriseth** [comment]
Thank you for your report. I was not able to reproduce your issue. Which framework do you use and how do you use it?
