### ISSUE TITLE
app.js:480 TypeError: web3CoreMethod.MethodProxy is not a constructor

### ISSUE THREAD

**Issue by Tore19** [ethereum/web3.js#2750]
#### Steps to reproduce the behavior
1. import Web3 from "web3";
2. var web3 = new Web3(
      new Web3.providers.HttpProvider(
        "https://mainnet.infura.io/v3/5bc48f0bfeec43a793a0c769bbbcb22c"
      )
    );

#### Error Logs 
TypeError: web3CoreMethod.MethodProxy is not a constructor
    at Accounts.AbstractWeb3Module (index.js:54999)
    at new Accounts (index.js:55621)
    at new Accounts$1 (index.js:55784)
    at new Eth$1 (index.js:59234)
    at new Web3 (index.js:62571)

### Versions 
* web3.js:1.0.0-beta.52
* nodejs:8.15.0
* browser:chrome
* ethereum node:https://mainnet.infura.io/v3/5bc48f0bfeec43a793a0c769bbbcb22c

**Comment by nivida** [comment]
Did you use a bundler? (If you import the Web3 module on nodejs with a require statement is the bundling process not required)

**Comment by nivida** [comment]
Closed because of the inactivity of the creator. Feel free to provide all the information in a new issue.

**Comment by bohendo** [comment]
I encountered this same issue, also on web3 `1.0.0-beta.52`. Strangely, I couldn't reproduce it locally but it was appearing on our CI server.

In our package.json, we were also depending on: `"web3-core": "1.0.0-beta.52"`. I think explicitly depending on both `web3` and `web3-core` was causing some problems.

When we removed the `web3-core` dependency, this error disappeared.
