### ISSUE TITLE
Web3 cannot be instantiated without a provider

### ISSUE THREAD

**Issue by eggplantzzz** [ethereum/web3.js#2752]
### Description 
In earlier versions of Web3, you were able to construct a new Web3 object without a provider. As of version 1.0.0-beta.38 you can no longer do this.

There are several places in the Truffle codebase that rely on this ability. For example [here](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-contract/lib/contract/constructorMethods.js#L337).

#### Expected behavior
One should be able to do `const web3 = new Web3();`

#### Actual behavior
```
const web3 = new Web3();
>> TypeError: Cannot read property 'sendPayload' of undefined
>>    at ProviderResolver.resolve........
```

#### Steps to reproduce the behavior
Do the following with version 1.0.0-beta.52.
 ```js
 const Web3 = require("web3");
 const web3 = new Web3();
 ```

### Versions 
* web3.js: 1.0.0-beta.52
* nodejs: 8.16.0

**Comment by Senshii** [comment]
I think it will be fixed in beta 53 https://github.com/ethereum/web3.js/pull/2751
