### ISSUE TITLE
Web3JS incorrect return value of array

### ISSUE THREAD

**Issue by Solexplorer** [ethereum/web3.js#2760]
### Description 
When I return a string array with web3 I don't get the original array as expected, but rather I get an array of the same size, with the index off by one.

So instead of ["One","Two","Three"] I get ["","One","Two"]

I am certain my contract is correct, because when I call the function on remix.ethereum.org I correctly get ["One","Two","Three"] as the return value.
I think it's a problem with the web3 library as I am using the experimental pragma for testing purposes.

The contract:
`pragma experimental ABIEncoderV2;
pragma solidity ^0.5.0;

contract ProblemDemo {

    string[] private myStringArray;

    constructor () public {
        myStringArray.push("One");
        myStringArray.push("Two");
        myStringArray.push("Three");
    }

    function addToMyStringArray (string memory newEntry) public {
        myStringArray.push(newEntry);
    }

    function getMyStringArray () public view returns (string[] memory) {
        return myStringArray;
    }
}`

Simple HTML displaying the issue:

`https://github.com/RepRachid/Solidity/blob/master/simple%20html%20solidity`

It's not a Solidity problem. The experimental ABI encoder implements this functionality and it's working as intented. Calling the function in Remix IDE returns the expected values. What confuses me is that the query from web3js returns something different.
### Versions 
* web3.js:
* nodejs:
* browser:
* ethereum node:

**Comment by zemse** [comment]
I checked your repo, you are using an old version 0.20.3 that uses callbacks. I have tried your contract with a newer version web3@1.0.0-beta.37 that uses promises instead, and it is giving expected output ["One","Two","Three"]. Do check out the new version.

**Comment by nivida** [comment]
@zemse Thanks for checking this!

**Comment by Solexplorer** [comment]
@zemse @nivida I am using the latest version of web3 1.0.
I have also tried using promises but the output is the same.

![image](https://user-images.githubusercontent.com/50027175/57011390-bb9e6d80-6c01-11e9-9ea3-706cb488c770.png)

**Comment by Solexplorer** [comment]
@zemse @nivida Please check the repository with the new web3 1.0 implementation:

https://github.com/RepRachid/Solidity/tree/master/FreeSpeech/src

I am using promises and still getting the same error

**Comment by zemse** [comment]
Try web3.version in the browser console, you will see the version that's currently up.
![Screenshot 2019-05-01 15 37 37](https://user-images.githubusercontent.com/22412996/57013035-19917c00-6c27-11e9-9adb-ba6f51331508.png)
Also, you can turn on GitHub pages so that anyone can open the HTML page with ease without the need to fork.

Try using this src [https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.37/dist/web3.min.js](https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.37/dist/web3.min.js)

Hope this helps!
