### ISSUE TITLE
Cannot set provider on provider-less Web3 instance

### ISSUE THREAD

**Issue by eggplantzzz** [ethereum/web3.js#2763]
### Description 
When attempting to instantiate a Web3 instance without a provider, you cannot then use the `setProvider` method to set a provider.

#### Expected behavior
The web3 instance should set the provider.

#### Actual behavior
When attempting to use the `setProvider` method, you receive an error message due to there being no current provider (see the Error Logs section).

#### Steps to reproduce the behavior
```
const Web3 = require("web3");
const web3 = new Web3();
web3.setProvider(new Web3.providers.HttpProvider(someValidProviderUrl);
```

#### Error Logs 
```
TypeError: Cannot read property 'constructor' of undefined
    at Web3.isSameProvider (/Users/tyler/projects/truffle/node_modules/web3/node_modules/web3-core/dist/web3-core.cjs.js:54:34)
    at Web3.setProvider (/Users/tyler/projects/truffle/node_modules/web3/node_modules/web3-core/dist/web3-core.cjs.js:42:17)
    at Web3.setProvider (/Users/tyler/projects/truffle/node_modules/web3/dist/web3.cjs.js:41:73)
```

### Versions 
* web3.js: 1.0.0-beta.53
* nodejs: 8.16.0

**Comment by nivida** [comment]
Thanks for opening this issue! I will release the referenced fix asap. Is there any other special case truffle is using by side of initiating of a Web3 object without a provider?

**Comment by eggplantzzz** [comment]
Thanks @nivida! I will take a quick look to see if I can give more info.

**Comment by guylando** [comment]
@nivida relevant when trying to override truffle web3 with newer web3 version in truffle console.
It does not work.
web3newinst.setProvider(web3.currentProvider) fails
after
var web3new = require('web3')
var web3newinst = new web3new()
