### ISSUE TITLE
getBlock by number or hash does not work on Quorum

### ISSUE THREAD

**Issue by oktapodia** [ethereum/web3.js#2766]
### Description 
The getBlock method with a hash or a number as parameter does not work with a quorum permisionless blockchain

#### Expected behavior

    Calling `await web3.eth.getBlock(1)` or `await web3.eth.getBlock('0x000...')` should return an object.

#### Actual behavior

    Calling `await web3.eth.getBlock(1)` or `await web3.eth.getBlock('0x000...')` is throwing an error `Number can only safely store up to 53 bits` from bn.js.

#### Steps to reproduce the behavior

Install a quorum chain, connect to it and then 
```js
const web3 = new Web3('http://localhost:20200');
const block = await web3.eth.getBlock(1);
//const block = await web3.eth.getBlock('0x000...');

console.log(block);

// Throw 'Number can only safely store up to 53 bits'
```

#### Error Logs 

'Number can only safely store up to 53 bits'

### Versions 
* web3.js: 1.0.0-beta.53
* nodejs: v11.14.0
* ethereum node: N/A
* Quorum node: 2.2.0

**Comment by nivida** [comment]
Thanks for opening this issue! I'm currently testing different BigInt solutions to find a solution for the issue https://github.com/ethereum/web3.js/issues/2171. The improvement of the BigInt handling will also improve the method specific number handling.

**Comment by oktapodia** [comment]
Thank you, do you have an ETA to publish the new web3 release, please?

**Comment by nivida** [comment]
> Thank you, do you have an ETA to publish the new web3 release, please?

I've planned to release tomorrow a version beta.54 with this quick fix.

Sorry for bothering you but I will close this issue again because it's a duplication of https://github.com/ethereum/web3.js/issues/1905

**Comment by oktapodia** [comment]
No worries, thank you
