### ISSUE TITLE
Wrong return parameter decoding BigNumber instead of Array of BigNumbers

### ISSUE THREAD

**Issue by Georgi87** [ethereum/web3.js#277]
I have a problem with abi decoding of return arrays in web3. The following is a part of the ABI:
```
{
"inputs": [{"type": "uint256[]", "name": "event_description_hashes"}], 
"constant": false, "type": "function", "name": "getMarkets",
 "outputs": [{"type": "uint256[1024]", "name": ""}]
}
```

For some reason I don't get an array back but a single large integer in web3:

```
interface_contract.getMarkets.call(event_hashes, 'pending', function (err, markets) { 
    console.log(markets) // is  1.0151422069548598394975132446711695856e+38
});
```

**Comment by Georgi87** [comment]
After doing some debugging I found out that isArrayType is not recognizing static size arrays. E.g. uint[1024] is not recognized as an array. I removed 1024 from the abi and now isArrayType returns true.

But there is still another bug which causes the decoding to fail.

In the decodeParams function inside the mapping, type has the value of uint256[]. However the solidityType returns an SolidityType {_name: "uint", _match: "prefix", _mode: "value"}. I assume it is not recognized as an array again?

```
SolidityCoder.prototype.decodeParams = function (types, bytes) {
    var self = this;
    return types.map(function (type, index) {
        var solidityType = self._requireType(type);
        var p = solidityType.sliceParam(bytes, index, type);
        return solidityType.formatOutput(p, isArrayType(type));
    });
};
```

**Comment by Georgi87** [comment]
In formatOutput SolidityParam.decodeArray is called which calculates an offset.

This offset becomes huge in my case:

```
Input bytes:
000000000000000000000000000000004c5eed807d8755d4d13e2ca380a4e360
Return: 1.0151422069548598e+38 // should be BigNumber

var getOffset = function (bytes, index) {
    // we can do this cause offset is rather small
    return parseInt('0x' + bytes.substr(index * 64, 64));
};
```

**Comment by Georgi87** [comment]
I assume this offset is used to decode the number of array elements? Since static arrays don't have a dynamic number this offset will always be 0.

**Comment by debris** [comment]
You are right. I will take care of it today.

**Comment by Georgi87** [comment]
Great, thanks debris!

**Comment by debris** [comment]
@Georgi87 @chriseth can you verify these tests:

https://github.com/ethereum/web3.js/blob/abi_refactor/test/coder.encodeParam.js
https://github.com/ethereum/web3.js/blob/abi_refactor/test/coder.decodeParam.js

?

**Comment by Georgi87** [comment]
Great it all seems to be working now. Thanks debris!

**Comment by debris** [comment]
I just talked with Christian about pr and not everything is finished yet. Encoding and decoding nested arrays eg. `int[x][y]` is in reverse. I will update it shortly and probably tomorrow will merge and create new release.
