### ISSUE TITLE
fails to install on macOS

### ISSUE THREAD

**Issue by tcurdt** [ethereum/web3.js#2770]
### Description

`npm install web3` fails on macOS because https://github.com/barrysteyn/node-scrypt/issues/192

Turns out that module is deprecated
> #WARNING!!! This module is deprecated. Instead, use https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

#### Expected behavior

`npm install web3` should install

#### Actual behavior

Fails to install `node-scrypt` which should not be used anymore.

#### Steps to reproduce the behavior

See https://github.com/barrysteyn/node-scrypt/issues/192

#### Error Logs 

See https://github.com/barrysteyn/node-scrypt/issues/192

#### Gists

NA

### Versions 
* web3.js: tried most of the 1.0.0-beta releases
* nodejs: v12.1.0
* browser: NA
* ethereum node: NA

**Comment by nivida** [comment]
Thanks for opening this issue but there is already an issue regarding node-scrypt (https://github.com/ethereum/web3.js/issues/2385).

**Comment by tcurdt** [comment]
@nivida Ah, OK - I didn't make the connection from the title.
