### ISSUE TITLE
How to sign message Dapps

### ISSUE THREAD

**Issue by EnettyTech** [ethereum/web3.js#2771]
Hi, i want to sign in Dapp example: etheremon.com.
 I used `web3.eth.accounts.sign` but return `invalid signature`.
Can every body help me sign Dapp?

**Comment by nivida** [comment]
Could you please ask support question in our [gitter](https://gitter.im/ethereum/web3.js) channel, on [StackOverflow](https://ethereum.stackexchange.com/) or the community-driven [discord](https://discord.gg/EKCthR) server?
