### ISSUE TITLE
Unable to deploy contract

### ISSUE THREAD

**Issue by industral** [ethereum/web3.js#2773]
### Description

Unable to deploy contract. 
Was working on **beta-34**, error with **beta-50**, not working at all with **beta-53**.

#### Expected behavior

```jq
  const contractInstance = new web3.eth.Contract(contract.abi);

  const inbox = await contractInstance.deploy({
    data: contract.evm.bytecode.object,
    arguments: ["Test"]
  }).send({from: accounts[0], gas: 1000000});
```

should deploy contract.

#### Actual behavior
- web3@1.0.0-beta.34 - works fine
- web3@1.0.0-beta.50 - [error](https://gist.githubusercontent.com/industral/0aa368b8a5348613b07c3e27ff9bfdec/raw/a6f79bb1adb7af36efb530460993300145a05381/gistfile1.txt) 
- web3@1.0.0-beta.53 - doesn't return neither throw anything...

#### Steps to reproduce the behavior

[Inbox.sol](https://gist.github.com/industral/5615c0666787cebd70b6a41d1f6c97c7)
[test.js](https://gist.github.com/industral/16760065d5492c11107a462a1c3cdad3)

```jq
node ./test.js
```

### Versions 
* solc: 0.5.8
* ganache: 6.4.3
* web3.js: 1.0.0-beta.50/53
* nodejs: v10.15.3

[ABI ](https://gist.github.com/industral/5b85d37db8be35e638b3afa9d0716d06)

**Comment by nivida** [comment]
Could you add the thrown error message and did you configure the transaction confirmation workflow as described in the documentation?

**Comment by industral** [comment]
@nivida 
> Could you add the thrown error message

throw error linked above https://gist.githubusercontent.com/industral/0aa368b8a5348613b07c3e27ff9bfdec/raw/a6f79bb1adb7af36efb530460993300145a05381/gistfile1.txt

> did you configure the transaction confirmation workflow as described in the documentation?

Not sure what you mean. Code also provided above https://gist.github.com/industral/16760065d5492c11107a462a1c3cdad3

**Comment by nivida** [comment]
> throw error linked above 

The given error doesn't look like a normal Web3.js error. Did you also test it with geth and parity?

> Not sure what you mean. Code also provided above 

[Web3 Module Options](https://web3js.readthedocs.io/en/1.0/web3.html#transactionblocktimeout)

**Comment by industral** [comment]
Settings **transactionConfirmationBlocks** to 1 fixed problem.

By default it was 24.

```javascript
console.log(web3.eth.transactionConfirmationBlocks);
```


```javascript
const web3 = new Web3(provider, null, {
  transactionConfirmationBlocks: 1
});
```

I guess that should be **1**, as 24 blocks at ~15sec it's about 5 minute minimum of waiting. Also should be better documented. Thanks @nivida for help!

**Comment by nivida** [comment]
Great! Yes, this should be better documented and also added to the ``Getting Started`` section. I will improve it with the next update of the documentation. 
I think it should be one in a local development environment but it should be set to a way higher value in a production environment.
