### ISSUE TITLE
Empty Bytes causes RangeError w/ padRight method in web3.js

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/web3.js#278]
When working with bytes-bytes32 data and browser front-end HTML elements (namely, input text fields), an error can be caused when conversion doesn't clean away empty unused bytes after the use of toAscii. I kept getting a RangeError being thrown from the padRight method (new Array) constructor. Essentially if you convert bytes32 data into ascii via web3.toAscii, and then insert that data into an HTML input text field and attempt to use that bytes32 data again, back into web3, extra empty unused bytes remain and will create a string that is somehow unsuited for the padRight method in web3 (and thus throws a RangeError). I'm assuming it's because pad right attempts to pad overtop of the unused empty bytes.

My fix was to strip away these unused bytes, by adding in a strip method and using it with web3.toAscii. This is my cleanBytes method. 

```web3.cleanBytes = function(value){
     return value.replace(/\0/g, '');
}```

Either we should note this in the docs, provide the method above, and/or implement something like this with ascii convertion from bytes32.

**Comment by debris** [comment]
If I understood the problem correctly, it should be fixed in 9743787c07b6c57b8b87eab18bc6cce6ebcd09ec

[test is here](https://github.com/ethereum/web3.js/blob/9743787c07b6c57b8b87eab18bc6cce6ebcd09ec/test/utils.toAscii.js#L8)
