### ISSUE TITLE
Unexpected behavior when calling web3.eth.ens.getContenthash

### ISSUE THREAD

**Issue by jeluard** [ethereum/web3.js#2782]
### Description

`web3.eth.ens.getContenthash` does not return the decoded content as documented.
Not clear if the doc or the behavior is wrong.

#### Expected behavior

```javascript
web3.eth.ens.getContenthash('pac-txt.eth').then((result) => {
    console.log(result);
});
> 'QmdTEBPdNxJFFsH1wRE3YeWHREWDiSex8xhgTnqknyxWgu'
```

#### Actual behavior

```javascript
web3.eth.ens.getContenthash('pac-txt.eth').then((result) => {
    console.log(result);
});
> '0xe30101701220e08ea2458249e8f26aee72b95b39c33849a992a3eff40bd06d26c12197adef16'
```

**Comment by nivida** [comment]
This looks like an issue of the AbiCoder from @ricmoo who we are using. I will contact him asap.

**Comment by ricmoo** [comment]
The value returned from the Solidity contract is a `bytes`, so the above value is correct from the ABICoder’s point of view.

If the goal of that function is to return the IPFS multihash, it needs to be parsed by an IPFS multihash library.

See EIP-1577: https://eips.ethereum.org/EIPS/eip-1577

And here is our implementation we use in Meeseeks: https://github.com/ricmoo/meeseeks-app/blob/master/index.html#L958

Hope that helps. :)

**Comment by jeluard** [comment]
Thanks @ricmoo !

Probably decoding `contenthash` should be left to end users as it can be hairy if you want full support. So I would say current behavior is fine but doc should be updated? 

WDYT @nivida ? If that sounds good I will go ahead and update the doc to fix the example and provide relevant context.

**Comment by ricmoo** [comment]
I will be adding a small ipfs library to ethers.js in the near future, which could also be wrapped by Web3.js to do this conversion too. But that is a bit further down on my todo list.

**Comment by nivida** [comment]
Thanks, @ricmoo for the details. 

> If the goal of that function is to return the IPFS multihash, it needs to be parsed by an IPFS multihash library.

I could handle this with custom methods instead of using internally the ``Contract`` API in the ENS module.

> I will be adding a small ipfs library to ethers.js in the near future, which could also be wrapped by Web3.js to do this conversion too. But that is a bit further down on my todo list.

We could probably work together on one module which isn't ethers or Web3 to specific and use it later in both projects?

> WDYT @nivida ? If that sounds good I will go ahead and update the doc to fix the example and provide relevant context.

Sounds great! @jeluard

**Comment by jeluard** [comment]
FYI there is an existing library handling `content-hash` parsing: https://github.com/pldespaigne/content-hash 
It's used by e.g. [manager.ens.domains](https://manager.ens.domains). not sure how comprehensive it is.

**Comment by cgewecke** [comment]
`1.2.8` adds contentHash support. [Docs here][1]

[1]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth-ens.html#getcontenthash
