### ISSUE TITLE
Security vulnerability: extend 3.0.1 module in web3-bzz

### ISSUE THREAD

**Issue by dwalintukan** [ethereum/web3.js#2792]
### Description
Using `1.0.0-beta.54` Github complains of a security vulnerability in the `extend 3.0.1` module which is being used by `web3-bzz@1.0.0-beta.54` -> `swarm-js@0.1.39` -> `eth-lib@0.1.27` -> `servify@0.1.12` -> `request@2.87.0` -> `extend 3.0.1`.

#### Expected behavior
No security vulnerability warning in Github.

#### Actual behavior
![image](https://user-images.githubusercontent.com/4350404/57349934-3b8a8180-7186-11e9-9e4c-08f6b8fad18a.png)

### Versions 
* web3.js: 1.0.0-beta.54

**Comment by nivida** [comment]
Thanks for opening this issue! I've contacted yesterday the creator of the swarm-js dependency we use. He told me that the swarm-js package is no longer maintained and do not get any new version. The swarm team itself was once opening issues here to remove the bzz module and I think this will be the current solution. (I will later re-implement the bzz module)
