### ISSUE TITLE
require('web3/dist/web3.js') returns BigNumber function

### ISSUE THREAD

**Issue by asinyagin** [ethereum/web3.js#280]
Hey,

I use requirejs in my project and I want to include the library with require(), but require('web3/dist/web3.js') returns BigNumber for some reason. Here's the full code https://github.com/asinyagin/requirejs-test. Is web3 supposed to be used with requirejs?

**Comment by asinyagin** [comment]
Looks like `require('web3/dist/web3.js')` returns `BigNumber` and defines `web3` in the global scope. It works me, but I'm not sure if it's good behavior for amd module.

**Comment by debris** [comment]
that's probably because we expose both: `web3` and `BigNumber` [using browserify](https://github.com/ethereum/web3.js/blob/master/gulpfile.js#L63-L65). 

```js
        .require('./' + src + '.js', {expose: 'web3'})
        .ignore('bignumber.js')
        .require('./lib/utils/browser-bn.js', {expose: 'bignumber.js'})
```

I will try to fix it before next web3.js release.

**Comment by debris** [comment]
probably changing the order of `expose` will be enough

**Comment by dmytyar** [comment]
Got other issue with web3 dist and requirejs
in next code raised exception:
    return object instanceof BigNumber ||
        (object && object.constructor && object.constructor.name === 'BigNumber');

Expecting a function in instanceof check, but got #<Object>

**Comment by Manidos** [comment]
**index.html**

`<script` src="scripts/lib/require.js" data-main="scripts/main.js"></script>`

**main.js**

```
require.config({
    paths: {
		web3: 'lib/web3',
    }
});

require(['web3'],
    function() {	
		web3 = new Web3();
		web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));	
		console.log(web3.toBigNumber('234'));
    }
);
```

**Browser console:**

![1](https://cloud.githubusercontent.com/assets/16019131/17551444/e150788e-5f1b-11e6-887f-90b30f213982.png)

**Comment by frozeman** [comment]
This should be irrelevant now for web3.js 1.0.0
