### ISSUE TITLE
Error: Method [object Object] not supported.

### ISSUE THREAD

**Issue by kernelwhisperer** [ethereum/web3.js#2800]
### Description 

Using `ethjs-ens` to lookup an address, but `web3` is sending a malformed request to `ganache-core`. 

EDIT: it might be solvable by upgrading `ganache-core` which we currently have pinned to `v2.2.1`. Will try and report back.

#### Expected behavior

The request should look like this:

```js
{"id":4267477472488,"jsonrpc":"2.0","params":[{"to":"0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1","data":"0x0178b8bff57f57247b9ef2b45da478e1a16f7d563a2a97b75d4fdd3be4dc64fca67bc43a","from":"0xb4124ceb3451635dacedd11767f004d8a28c6ee7"},"latest"],"method":"eth_call"}
registry.resolver Result { '0': '0xe30c656d8dcf22b8ff3f36f3db718ead4b59c7c3' }
```

#### Actual behavior

The request it receives:

```js
{"jsonrpc":"2.0","id":1,"method":{"id":9887230978335,"jsonrpc":"2.0","params":[{"to":"0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1","data":"0x0178b8bff57f57247b9ef2b45da478e1a16f7d563a2a97b75d4fdd3be4dc64fca67bc43a"},"latest"],"method":"eth_call"}}
```

The error it throws:
```
(node:758) UnhandledPromiseRejectionWarning: Error: Node error: {"message":"Method [object Object] not supported.","code":-32000,"data":{"stack":"Error: Method [object Object] not supported.\n    at Get
```

#### Steps to reproduce the behavior

Where the request is sent from:

https://github.com/ethjs/ethjs-ens/blob/master/index.js#L109
https://github.com/aragon/apm.js/blob/master/src/ens/index.js#L14

### Versions 
* web3.js: beta.54, works with beta.34
* nodejs:
* browser:
* ethereum node:

**Comment by nivida** [comment]
Thanks for opening this issue! [ethjs-ens](https://github.com/ethjs/ethjs-ens) doesn't look maintained and is supporting the version 0.20.x of Web3.js. I can recommend you to use the [ENS](https://web3js.readthedocs.io/en/1.0/web3-eth-ens.html) module Web3.js does provide.
