### ISSUE TITLE
fix web3.eth.pendingTransactions types

### ISSUE THREAD

**Issue by geethpw** [ethereum/web3.js#2804]
Installed web3 on angular 6 CLI with following packages:

    "@angular/animations": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "typescript": "~2.7.2"
  

running `ng serve` gives the following error:

`ERROR in node_modules/web3-eth/types/index.d.ts(147,59): error TS1122: A tuple type element list cannot be empty.
node_modules/web3-eth/types/index.d.ts(147,81): error TS1122: A tuple type element list cannot be empty.`

**Solution**
Change: `web3-eth/types/index.d.ts` like number 147 from :
`pendingTransactions(callback?: (error: Error, result: []) => void): Promise<[]>;`
to
`pendingTransactions(callback?: (error: Error, result: any[]) => void): Promise<any[]>;`

This plugin does no support angular 6 or angular 6 cli. I think it's a noteworthy change.

**Comment by nivida** [comment]
Thanks for opening this issue! I will update the types asap. The hotfix for using this specific web3 method is adding of the [``@ts-ignore``](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html) comment as described [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html).

**Comment by geethpw** [comment]
> Thanks for opening this issue! I will update the types asap. The hotfix for using this specific web3 method is adding of the [`@ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html) comment as described [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html).

Thanks for the quick fix. Upgraded to angular 7 and it worked fine.

**Comment by princesinha19** [comment]
@nivida from PR https://github.com/ethereum/web3.js/pull/2762, this problem can be solved.

**Comment by joshstevens19** [comment]
This was an issue with the angular CLI - a few other projects had this 

https://github.com/immerjs/immer/issues/280
https://github.com/apollographql/apollo-client/issues/4501
... a hand full more

The syntax above 

```
pendingTransactions(callback?: (error: Error, result: []) => void): Promise<[]>;
```

is valid but due to the angular setup bug it throw on any module which did this, but we will add the any anyway.

But we can close this as angular CLI should not be throwing this error and is was an issue on their end with their release (which is now fixed in the newest angular CLI).
