### ISSUE TITLE
callback in web3

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2809]
### Description 
callback in for call() myMethod function call doesn't work when for a truffle contract in the test-bed.
What the issue is, in broad strokes.

#### Expected behavior

 A set function using the newTransact() function which is fine in working condition
2 a call function using getTransactionCount() to show the result using the callback.

#### Actual behavior

1 sucessfully executed.
2. no response the callback it does not execute.
#### Steps to reproduce the behavior

```
var Web3 = require('web3')
var assert = require('assert');

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

var accounts;
var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');

web3.eth.getAccounts().then(async function(res){

    var admin = res[9];
    var receiver = res[1];
    var sender = res[3];
    accounts = res;
    
    contract.deploy({
        data:bytecode
    }).send({
        from : admin,
        gas: 4712388,
        gasPrice: 100000000000
    }, (error,transactionHash) => {
      console.log(error,transactionHash)
                        
    }).on('receipt',(receipt) =>{
        
    }).then((instance)=>{

    })
    const receipt = await contract.methods.newTransact(receiver,'dob').send({from:sender},(error,transactionHash)=>{console.log(error,transactionHash)});
    const rec = contract.getTransactionCount.call().then((resu)=>{
        console.log(resu);

    });

    });
    ```

### Versions 
* web3.js:
* nodejs:
* browser:
* ethereum node:

**Comment by nivida** [comment]
I've closed this issue because we have a discussion with the truffle team [here](https://github.com/ethereum/web3.js/issues/2786).

**Comment by c3rf1g** [comment]
РУССКИЕ ВПЕРЕД
