### ISSUE TITLE
Loading new version provider(beta.55) into old web3 (beta.37) creates invalid json RPC.

### ISSUE THREAD

**Issue by makoto** [ethereum/web3.js#2810]
### Description 

NOTE: This was found via this issue on [ENSJS](https://github.com/ensdomains/ensjs/issues/36)

If you pass a provider created from beta.55 to Web3 object with beta.37, it throws `Error: Node error: {"code":-32600,"message":"invalid json request"}`

Here is the sample code. There is also [a gist](https://gist.github.com/makoto/a743f1a73caf78b12eddf44d0bb11a69/23786860112c9e005508e495faa438980888768c) with `package.json` to install the correct version.

```js
const Web3 = require('web3') 
const Web3Legacy = require('web3legacy')
console.log('web3 version', (new Web3()).version)
console.log('web3 legacy version', (new Web3Legacy()).version)
// Do "export INFURA_PROJECT_ID=YOURPROJECTID" on your terminal
const projectid = process.env.INFURA_PROJECT_ID
const endpoint = 'https://mainnet.infura.io/v3/' + projectid
const provider = new Web3.providers.HttpProvider(endpoint)
const web3 = new Web3(provider)
const web3legacy = new Web3Legacy(provider)
async function call(){
    console.log('latest web3')
    console.log('blocknumber', await web3.eth.getBlockNumber())

    console.log('lagacy web3')
    console.log('blocknumber', await web3legacy.eth.getBlockNumber())
}
call()
```

#### Expected behavior

```
~/.../tmp/ethereum-ens-versions (master)$node index.js 
web3 version 1.0.0-beta.55
web3 legacy version 1.0.0-beta.37
latest web3
blocknumber 7739194
lagacy web3
blocknumber 7739194

```

#### Actual behavior

```
~/.../tmp/ethereum-ens-versions (master)$node index.js 
web3 version 1.0.0-beta.55
web3 legacy version 1.0.0-beta.37
latest web3
blocknumber 7739194
lagacy web3
(node:97930) UnhandledPromiseRejectionWarning: Error: Node error: {"code":-32600,"message":"invalid json request"}
    at Function.validate (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at HttpProvider._callee$ (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/web3-providers/dist/web3-providers.cjs.js:710:61)
    at tryCatch (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/makoto/work/ens/tmp/ethereum-ens-versions/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:97930) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However, if you pass either the same version like [this](https://gist.github.com/makoto/a743f1a73caf78b12eddf44d0bb11a69/dffa98cdf86c8601104b393a363d0f1072dbc0a6), it does not throw an error.

Here is the diff

<img width="786" alt="Screenshot 2019-05-11 at 13 13 19" src="https://user-images.githubusercontent.com/2630/57569731-236a6a80-73f1-11e9-8441-9174b8bdf2fe.png">

When I raised the issue to [Infura team](https://community.infura.io/t/web3-js-1-0-0-beta-37-call-raises-code-32600-message-invalid-json-request/583), they noticed that the test case is generating invalid json request as follows

```
{"jsonrpc":"2.0","id":0,"method":{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}}

```

as opposed to this

```
{"jsonrpc":"2.0","id":0,"method":"eth_blockNumber","params":[]}
```

#### Steps to reproduce the behavior

    1. create a directory
    2. Download the gist
    3. npm install
    4. node index.js

#### Error Logs 

See the "actual behavior" section

#### Gists

- [Gist with the error](https://gist.github.com/makoto/a743f1a73caf78b12eddf44d0bb11a69/23786860112c9e005508e495faa438980888768c)
- [Gist without the error](https://gist.github.com/makoto/a743f1a73caf78b12eddf44d0bb11a69/dffa98cdf86c8601104b393a363d0f1072dbc0a6)

### Versions 

* web3.js: `1.0.0-beta.55` provider to `1.0.0-beta.37`
* nodejs: v11.14.0
* browser: none
* ethereum node: infura

**Comment by nivida** [comment]
Thanks for opening this issue! The internal provider interface did change on the [beta.38](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) release. We are currently defining a DApp wide provider interface in the Ethereum Provider Ring ([EPR](https://ethereum-magicians.org/c/working-groups/provider-ring)). All injected providers who aren't standard Web3 providers will get passed through to the [CustomProvider](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/CustomProvider.js) this provider does provide backward compatibility for the third parties providers from the community.

**Comment by ppoliani** [comment]
@nivida is there a solution to address this issue?

**Comment by nivida** [comment]
Yes, we will split up the code bases. The old beta.37 code base will be used for the 1.0 stable release and the new beta.38=< architecture will be used for v2.0. This should get released this week.
