### ISSUE TITLE
PromiEvent not behaving as promise anymore

### ISSUE THREAD

**Issue by sirpy** [ethereum/web3.js#2812]
### Description 
after upgrading to 54 from 37
Our TX flows dont work as expected any more
specifically the promievent
1. doesnt complete with receipt even though on('receipt') is called
2. doesnt reject if on('error') is subscribed to

#### Expected behavior
await somecontract.somemethod().then(receipt => console.log(receipt)).catch(console.log)
should print receipt and error and resolve

**Comment by nivida** [comment]
Did you configure the ``transactionConfirmationBlocks`` as described in the [documentation](https://web3js.readthedocs.io/en/1.0/web3.html#transactionconfirmationblocks) and referenced in the release note of [beta.49](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.49)?

**Comment by sirpy** [comment]
Yes I have.
Main thing to notice is that if I do .on('error',handler).catch(otherhandler) first handler is called but not the catch if i remove the .on then the catch happens.
.then() of the promievent never resolves even if I remove all .on subscribers

**Comment by nivida** [comment]
You shouldn't combine the Promise and EventEmitter pattern in one call. 

Use on of these [examples](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#methods-mymethod-send) and not all together combined:)
