### ISSUE TITLE
No operation to unsubscribe?

### ISSUE THREAD

**Issue by Mozeps** [ethereum/web3.js#2813]
I want to subscribe to a given event.

```
myContract.events.MyEvent({
    filter: {myIndexedParam: [20,23]},
    fromBlock: 0
}, (error, event) => {
//read content of event 
//do something
});
```

If the event I use for logging statuses contains a certain status, I know that I no longer need to subscribe to this contract.

But there seems to be no possible way to unsubscribe?

I found #1587 discussing this issue one year ago but the suggested solution (a unsubscribe method in the prototype) does not seem to exist anymore.

* web3.js: 1.0.0-beta.52

**Comment by nivida** [comment]
Thanks for opening this issue! 
``myContract.events.MyEvent(...)`` returns a [AbstractSubscription](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js) object with the unsubscribe method.

**Comment by HoangJerry** [comment]
No, I still get duplicate  events even unsubscribe at ngOnDestroy() angular.

**Comment by HoangJerry** [comment]
![image](https://user-images.githubusercontent.com/27281406/57824782-74e67100-77c6-11e9-8fcc-b53260547ba0.png)

**Comment by Mozeps** [comment]
> Thanks for opening this issue!
myContract.events.MyEvent(...) returns a AbstractSubscription object with the unsubscribe method.

Could you provide a working example for this? 

```
let ev = myContract.events.MyEvent({
    filter: {myIndexedParam: [20,23]},
    fromBlock: 0
}, (error, event) => {
//read content of event 
//do something
});

ev.unsubscribe(response => console.log(response);
```
fails with the following:

```
Provider error: Subscription with ID null does not exist
```

Because the id of ev is null.
