### ISSUE TITLE
calling view method returns big number error

### ISSUE THREAD

**Issue by paulhaem** [ethereum/web3.js#2817]
### Description 
When calling a external view method from my contract (on ropsten network) it throws following error: 
```
overflow (operation="setValue", fault="overflow", details="Number can only safely store up to 53 bits", version=4.0.26)
```

```
function getRecords(address _patient) external view OnlyOwnerOrWithReadPermission(_patient) returns (string[] memory) {
    return patients[_patient].
}
```

#### Expected behavior

It should return an array of strings. It worked once, but after updating MetaMask to the newest version it suddenly crashes, while using the latest web3 version.

### Versions 
* web3.js: 1.0.0-beta.55 and tried rolling back to 1.0.0-beta.48 without success
* nodejs: 10.15.3
* browser: Chrome 74.0.3729.131 + MetaMask 6.5.1
* ethereum node: ?

**Comment by nivida** [comment]
Could you please add a github repository to reproduce this?

**Comment by paulhaem** [comment]
https://github.com/paulhaem/ehr-platform

Its quite complex and experimental, as it is my first DApp project. Just ask if anythings unclear.

**Comment by nivida** [comment]
Thanks for referencing your GitHub repository. I will test and if required fix it.
