### ISSUE TITLE
web3.eth.getBlock return Block type in typescript have misleading transaction property

### ISSUE THREAD

**Issue by averman** [ethereum/web3.js#2819]
https://github.com/ethereum/web3.js/blob/9714f30869d2ba6d1a7bc80df67a029694b2abc3/packages/web3-eth/types/index.d.ts#L191

in here the Block type have transaction type is array of Transaction; but when returned by web3.eth.getBlock() the type is array of string.

suggestion: make it union type of Transaction and string

**Comment by joshstevens19** [comment]
Hey thanks for raising this issue. Brilliant spot i will do a PR now for this.

**Comment by joshstevens19** [comment]
This has been fixed here - https://github.com/ethereum/web3.js/pull/2844 @nivida will merge that when he has a second.

**Comment by joshstevens19** [comment]
merged.
