### ISSUE TITLE
Get transaction options out of trx built with utility functions

### ISSUE THREAD

**Issue by nmushegian** [ethereum/web3.js#282]
Let's say I do:

```
instance.do_something.sendTransaction(arg1, arg2, callback)
```

Can the exact transaction options object be made available in the callback or anywhere?
NOT in the receipt, I want to know what the _wallet_ attempted. Nonce, encoded arguments, etc.

**Comment by debris** [comment]
> Can the exact transaction options object be made available in the callback or anywhere?

Can you give a proposal, how it should look like?

> Can the exact transaction options object be made available in the callback or anywhere?

encoded args (data), from, value are known. Nonce is choosen by the ethereum client. 

I assume that all of this is only for debug purposes. Would it be sufficient to have a verbosity flag (eg. `web3.setVerbosity(3)`)  and log request to console?

**Comment by nmushegian** [comment]
The motivation here was to be able to retry specific transactions that were randomly getting dropped from the pending pool. If you can't specify the same nonce for the dropped trx, all subsequently generated transactions are invalidated as well and you end up thrashing

> encoded args (data), from, value are known.

Where is this visible? Do you just mean that you must know if you can generate that transaction?

**Comment by frozeman** [comment]
in 1.0.0 you have `instance.do_something(value1, value2).encodeABI()`. The node etc is not visible, as this is added by the node itself, except you sign locally using `web3.eth.accounts.wallet`.
