### ISSUE TITLE
unsubscribe events not work

### ISSUE THREAD

**Issue by HoangJerry** [ethereum/web3.js#2821]
### Description 
I am using angular and when I subscriber the web3js events, I want to remove them before I leave to other pages. If it's not deleted the events log will be duplicate, and we get 2 record at same data.

```
> ngOnInit() {
>       this.RegisterEvent = this.contractService.ticketContract.events.Register({ fromBlock: 0},  
>              (error, event) => {
>                     console.log(event);
>              })
>  }
```

```
> ngOnDestroy(){
>               this.RegisterEvent.unsubscribe()
>    	      this.RegisterEvent.unsubscribe(data => {
>    		  console.log('callback data', data)
>    	      });
>          }
```

#### Expected behavior
    Calling `this.RegistertEvent.unsubscribe()` should remove eventListener
#### Actual behavior
    Calling `this.RegistertEvent.unsubscribe()` do nothing.

    When I try to console 
```
    this.RegistertEvent.unsubscribe(data => {
           console.log('callback data', data)
    });
```
It return false
#### Steps to reproduce the behavior
    1. Import `web3`
    2. Catch an event at ngOnInit - like a constructor 
    3. Remove upper event at ngOnDestroy  - like a deconstructor

### Versions 
* web3.js:
* Angular 7

**Comment by nivida** [comment]
Could you add the whole code as gist file or github repository? and could you also update your issue to be aligned with the issue template we provide?

**Comment by nivida** [comment]
I've closed this issue due to the inactivity of the creator of this issue.

**Comment by HoangJerry** [comment]
@nivida I am using angular and when I subscriber the web3js events, I want to remove them before I leave to other pages. If it's not deleted the events log will be duplicate, and we get 2 record at same data.

**Comment by nivida** [comment]
Could you add the whole code as gist file or github repository? and could you also update your issue to be aligned with the issue template we provide?

**Comment by HoangJerry** [comment]
@nivida  I have updated the issue description. Could you double check?

**Comment by HoangJerry** [comment]
@nivida Can you help me, please?
