### ISSUE TITLE
`sendSignedTransaction` waits for N+1 transaction before returning

### ISSUE THREAD

**Issue by thomaseizinger** [ethereum/web3.js#2822]
### Description 

The API method `sendSignedTransaction` blocks until there are N+1 blocks confirmed given the sent transaction is included in block N. This is a problem in environments, where there is no continuous block generation (like parity instant seal) since the Promise returned by the function will actually never resolve unless there is another transaction. With parity instant seal though, transactions are mined as they are sent hence the code behaves wrongly in such environments.

I have been digging through the source code to find the reason for this and it seems like it only has been introduces recently (beta-48 still works). The source seems to be here:

https://github.com/ethereum/web3.js/blob/dc63f755665c511898c00969bdec6311d55e4109/packages/web3-core-method/src/observers/TransactionObserver.js#L149-L170

The `TransactionObserver` unnecessarily waits for the next block to be mined, even though we already have a valid `TransactionReceipt` for the transaction.

Even outside of parity's instant seal engine, this seems like undesired behaviour since it takes about 17 seconds on average for the next block to be mined, hence the promise does not resolve for this amount of time, even though the `TransactionReceipt` is already available.

#### Expected behavior

`await web3.eth.sendSignedTransaction` returns the `TransactionReceipt` once available.

#### Actual behavior

`await web3.eth.sendSignedTransaction` waits for the N+1 block before returning the receipt.

#### Steps to reproduce the behavior

I have created a MWE here:

https://github.com/thomaseizinger/web3-sendSignedTransaction-bug

### Versions 
* web3.js: last version I tested that works is beta-48. Unfortunately, there was a lot of moving around of the code recently so it is really hard to track where the bug was introduced.
* nodejs: 10.15.3
* browser: -
* ethereum node: parity 2.5.1

**Comment by jimmy-dg** [comment]
I'm also running into the same issue. This is critical especially for a private networks / development environment where blocks are not constantly created and the code just gets stuck until the next block is mined.

web3.js: beta-55
nodejs: 10.15.3
quorum: v2.1.1

**Comment by nivida** [comment]
Thanks for opening this issue! 
You should be able to get the receipt over the confirmation listener of the PromiEvent we return. Be aware to not combine the Promise and the EventEmitter. 

The amount of blocks it takes until the transaction call resolves can be configured with the transactionConfirmationBlocks options property of the Web3 module options. Further details are explained in the documentation.

Btw.: Web3.js is using internally the ethereumjs-tx module and your able to add an account to the Web3 wallet and it will automatically get signed locally. The signing process can be customized with the transactionSigner property of the Web3 module options.

@jimmy-dg I thought about to add a mode property to the Web3 module options who would define the required properties correctly for a development or production environment.

**Comment by jimmy-dg** [comment]
@nivida Thanks for the explanation! 
I don't quite understand what you mean by "Be aware to not combine the Promise and the EventEmitter."
This is a breaking change right? previously we were able to treat the returned `PromiEvent` as promise (and i thought this was the point of having PromiEvent instead of EventEmitter).

**Comment by nivida** [comment]
It’s still possible to use the Promise. We had a bug with unhandled promise rejections and the fix was to restrict the combination of the EventEmitter listeners and Promise. This means you are able to use the „on“ or „then“ method but you can’t combine them.

**Comment by thomaseizinger** [comment]
> The amount of blocks it takes until the transaction call resolves can be configured with the transactionConfirmationBlocks options property of the Web3 module options. Further details are explained in the documentation.

Unfortunately, that doesn't help.
I tried your suggestion in [this](https://github.com/thomaseizinger/web3-sendSignedTransaction-bug/compare/suggested-bugfix) branch but the problem perists.

Looking at the code referenced above, I can also not see how this would even potentially fix the problem because the following line

```js
const block = await this.getBlockByNumber(this.lastBlock.number + 1); 
```

has no mention of the above config setting.
Just to rehash this, in my opinion doing `this.lastBlock.number + 1` here is __wrong__ since in some environments, there is no automatic block generation so there will never be a new block until the current Promise resolves. In general, I don't understand why you would wait for the next block here? The transaction receipt is already valid and complete.

**Comment by nivida** [comment]
It should work if you set the transactionConfirmationBlocks to 1 instead of 0.

**Comment by diega** [comment]
I was facing this exact same issue on RSK using the _automine_ feature. I can confirm the workaround of setting the `transactionConfirmationBlocks` to 1 works fine on **beta.55**

**Comment by thomaseizinger** [comment]
Can confirm it works, thanks!

**Comment by jimmy-dg** [comment]
@nivida 
Thanks for the explanation and workaround. I'm curious to understand the reason behind this change in default behaviour - why does the web3 client needs to wait for an additional block before a transaction call could be resolved?
