### ISSUE TITLE
from parameter should accept a wallet

### ISSUE THREAD

**Issue by sshelton76** [ethereum/web3.js#2825]
This is a feature request.  Anytime we accept an address as a "from" parameter, it would be handy if we could pass it a wallet object instead of just an address.  I realize the from address is used as a lookup into a currently decrypted wallet.  But the place to decrypt should be during whatever procedure we're trying to pass in the address.  Otherwise we have to decrypt the wallet before calling the function and this is putting it back into the global space again.

The below is a really bad idea, but is presently the only way to handle it.
```
let result;
        if(window.confirm(`Would you like to send ${amount} ${symbol} to ${dest}?`)){
            try{
                let ctr = await this.XTokens[symbol];
                let fin = (await ctr.displayToRaw(amount)).toString();
                let wallet = await this.pinPrompt();
                let params = {
                    from : wallet[0].address
                }
                params.gas = await ctr.methods.transfer(dest,fin).estimateGas(params);
                console.debug("params: ",params);
                result = await ctr.methods.transfer(dest,fin).send(params);
                console.debug("result: ",result);
                window.alert(`Successfully sent ${amount} ${symbol} to ${dest}! Transaction Hash is ${result.transactionHash}`);
            }catch(err){
                window.alert(err);
            }
        }
```
FYI the "this.pinPrompt" prompts a user for a password, decrypts the wallet and hands back the decrypted wallet.
It would be far better if I could just hand in "wallet" and perhaps the password.

**Comment by nivida** [comment]
Thanks for proposing this feature. 
This request will extend the already existing feature request from issue https://github.com/ethereum/web3.js/issues/2739.
