### ISSUE TITLE
Using web3 with a proxy

### ISSUE THREAD

**Issue by darioAnongba** [ethereum/web3.js#2827]
### Description 

Our company uses web3 with a proxy. Proxies are not officially supported by web3 at the moment but we imperatively need it. We used the hack explained in this ticket: https://github.com/ethereum/web3.js/issues/887 to resolve the issue and it worked fine until web beta.37 but fails now that we updated to web3 beta.55.

The error we get is the following: 

> Connection refused or URL couldn't be resolved: https://{URL}
This didn't happen with web3 beta.37.

The purpose of this ticket is mostly to ask how to configure web3 with a proxy if anyone has succeeded in doing so.

#### Expected behavior

Calling `await web3.eth.getAccounts()` should return successfully using a proxy.

This behavior has been confirmed with integration tests.

#### Actual behavior

Calling `await web3.eth.getAccounts()` returns an error: _Connection refused or URL couldn\'t be resolved_

#### Steps to reproduce the behavior

1. Import `web3` and `http-proxy-agent`
2. Set the provider with
```js
    this.web3Provider = new Web3.providers.HttpProvider())
    this.web3Provider.httpAgent = new HttpProxyAgent(process.env.HTTP_PROXY)
```
3. Call any web3 function

#### Error Logs 

`await web3.eth.getAccounts()` returns an error: _Connection refused or URL couldn\'t be resolved_

### Versions 
* web3.js: 1.0.0.beta.55
* nodejs: 8
* ethereum node: geth

**Comment by nivida** [comment]
Thanks for opening this issue! I will close this one because of the already existing feature request. Feel free to update the [HttpProvider](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/HttpProvider.js) in the [web3-providers ](https://github.com/ethereum/web3.js/tree/1.0/packages/web3-providers/src/providers)module.
