### ISSUE TITLE
Request: web3 sign() should be limited to match ecrecover()

### ISSUE THREAD

**Issue by yaoshiang** [ethereum/web3.js#2829]
### Description 

web3's two sign() functions can create signatures that are unverifiable by Ethereum's ecrecover(). 

#### Expected behavior

web3.eth.sign(address, 'Arbitrary String') should fail. 

#### Actual behavior

web3.eth.sign(address, 'Arbitrary String') returns a signature which is unable to be verified by ecrecover(), because ecrecover() only accepts bytes32. 

The typical best practice is to hash 'Arbitrary String', resulting in 32 bytes, and calling sign() with the 32 byte hash. 

Solution: web3.eth.sign() and web3.eth.accounts.sign() should only accept strings formatted as padded 32 bytes. 

### Versions 
Truffle: v5.0.17 (core: 5.0.16)
Solidity: v0.5.0 (solc-js)
Nodejs: v8.10.0
Web3.js: v1.0.0-beta.37

**Comment by nivida** [comment]
Thanks for figuring this out I will test and if required fix it asap.
