### ISSUE TITLE
Error with react native

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/web3.js#2832]
Error when trying to use `web3` with React Native. 

```
error: bundling failed: Error: Unable to resolve module `http` from `/Users/ilan/Code/react-native/rns/node_modules/web3-providers/dist/web3-providers.umd.js`: Module `http` does not exist in the Haste module map
```

I think it is related with this https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

Steps to reproduce:

1. Create blank app
 ```
create-react-native-app sample
cd sample
yarn add web3
```
2. Import `web3` in `App.js`
```js
import Web3 from 'web3';
```
3. Run
```
react-native run-ios
```

**Comment by ilanolkies** [comment]
https://github.com/facebook/react-native/issues/24998

**Comment by nivida** [comment]
Thanks for opening this issue! I will test and if required fix it asap.

**Comment by ilanolkies** [comment]
Thanks. I will try to fix it in some free time

**Comment by ilanolkies** [comment]
A simple way to reproduce it:

1. Follow https://facebook.github.io/react-native/docs/getting-started with macOS cli
2. Create an app with `react-native init *`
3. `yarn add web3` in the app
4. `import Web3 from 'web3'`

```
error: bundling failed: Error: Unable to resolve module `http` from `/Users/ilanolkies/code/ReactNativeWeb3/node_modules/web3-providers/dist/web3-providers.umd.js`: Module `http` does not exist in the Haste module map
```

**Comment by ghost** [comment]
I'm having the same issue. Did you find a fix yet?

**Comment by JitendraLakhmani1824** [comment]
I am facing same issue, Any fix?

**Comment by joshstevens19** [comment]
I have seen this issue on a few other projects and i think its actually due to react native. Can you try to run what these guys suggest in upgrading react native and clearing the cache

https://github.com/facebook/react-native/issues/19019

**Comment by ilanolkies** [comment]
Hi. Is there any news? I got an answer from react native:

> React Native does not implement node apis, this is why you cannot use the `http` module. RN does implement `XMLHttpRequest` and `fetch` for networking instead. You'll have to open an issue for the `web3` package to see if they can support RN.

facebook/react-native#24998
