### ISSUE TITLE
Error while I try to send the transaction to rinkeby network using web3.

### ISSUE THREAD

**Issue by chainmonky** [ethereum/web3.js#2834]
I have prepared a lottery contract which have functions like to retrieve the address of the person who deploys the contract, enter the lottery and many more with the help of Metamask and web3. But I'm getting the following error when I try to enter the contract 
**Unhandled Rejection (Error): No "from" address specified in neither the given options, nor the default options.**
I'm providing each and every step that I followed with this issue. 
**Contract code** 
```
pragma solidity ^0.4.17;

contract Lottery {
    address public manager;
    address[] public players;

    function Lottery() public {
        manager = msg.sender;
    }

    function enter() public payable {
        require(msg.value > .01 ether);

        players.push(msg.sender);
    }

    function random() private view returns (uint) {
        return uint(keccak256(block.difficulty, now, players));
    }

    function pickWinner() public restricted {
        uint index = random() % players.length;
        players[index].transfer(this.balance);
        players = new address[](0);
    }

    modifier restricted() {
        require(msg.sender == manager);
        _;
    }

    function getPlayers() public view returns (address[]) {
        return players;
    }
}

```

In the above code, I'm successfully able to call getPlayers(),get balance of the contract and the players participants in the lottery. But failed to call enter method.
When I tried calling the enter() function in the above contract in the following way 

```
await lottery.methods.enter().send({
 from: accounts[0],
 value: web3.utils.toWei(this.state.value,'ether')
  });

```
It shoots me up the following error 
**Unhandled Rejection (Error): No "from" address specified in neither the given options, nor the default options.** 
### Versions 
* web3.js: web3@beta-37
Please let me know the issue

**Comment by saitejakuruva** [comment]
Got the issue instead of calling in the following way 
```
await lottery.methods.enter().send({
 from: accounts[0],
 value: web3.utils.toWei(this.state.value,'ether')
  });
```

Try to call enter() function on the following way
```
await lottery.methods.enter().call({
 from: accounts[0],
 value: web3.utils.toWei(this.state.value,'ether')
  });
```

**Comment by nivida** [comment]
Thanks for opening this issue! Could you please add the complete JS code to the issue?

**Comment by chainmonky** [comment]
https://github.com/saitejakuruva/Lottery-Dapp/blob/master/App.js

**Comment by nivida** [comment]
Thanks for referencing the related code! I will test and if required fix it asap.

**Comment by sshelton76** [comment]
Where in here https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html are you getting the idea that
```
const accounts = await web3.eth.getAccounts();
```
Is a valid way to obtain accounts?  
Are you possibly looking for this?
https://web3js.readthedocs.io/en/1.0/web3-eth-personal.html?highlight=getAccounts#getaccounts
```
web3.eth.personal.getAccounts([callback])
```
If so you need to realize you must be connected to a node under your control and it must have personal enabled and must be serving accounts and you're going to need to add a step to unlock those personal accounts.

A better solution would be connect to metamask or use an in Dapp wallet, because trying to secure a publicly accessible node serving up accounts is a sure fire way to get all your customer's funds stolen.

**Comment by chaitanyapotti** [comment]
This issue can be closed. 
The issue highlighted is due to incorrect configuration/ using private accounts in metamask which doesn't allow accounts[0] to be available until window.ethereum.enable() is called.
No bug in web3 @nivida
