### ISSUE TITLE
An intent to build a single-file, standalone web3.js

### ISSUE THREAD

**Issue by andy0130tw** [ethereum/web3.js#2839]
Hi there.

Since there has been no "dist" folder for nearly half a year (see #2623), I tried to build standalone (or/and minified) web3 JS files with latest release, beta 55, and gather the materials to a repository. The job is mostly done with webpack, with some caveats I encountered written in the comments.

https://github.com/andy0130tw/web3.js-browser

For now there is no built file in this repository. My plan is to also include built files after my packing stablizes. If you are a DApp developer, hope it helps you! As I am not a webpack expert, feel free to open issues for bugs or requests.

**Comment by nivida** [comment]
Thanks for providing such a repository! But I will close this issue because it's a duplication of #2623. The minified file will be added back asap. The current on-going development processes are documented in the ``Projects`` tab of this GitHub repository.
