### ISSUE TITLE
Improvement: Pass `signTransaction` object to `sendSignedTransaction()` method

### ISSUE THREAD

**Issue by ssteiger** [ethereum/web3.js#2840]
**Possible improvement:**

First: ```const signedTransaction = await web3.eth.accounts.signTransaction(tx, account.privateKey)```

Then doing the following does not work:
```
  const receipt = await web3.eth.sendSignedTransaction(signedTransaction)
```
Throws: `Error: Returned error: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`

This works:
```
  const receipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction)
```

Seems a bit weird that you can't pass a `signTransaction` object to the `sendSignedTransaction()` method?

cheers

**Comment by nivida** [comment]
Thanks for opening this issue! I will test and if required fix it asap.
