### ISSUE TITLE
Code hangs in terminal (after execution) when sourcing Web3 from a local IPC Node

### ISSUE THREAD

**Issue by keennay** [ethereum/web3.js#2841]
#### Expected behavior vs actual behavior
Code executes as expected when Web3 is referencing a remote node, such as my Infura node: outputs the correct 'latest' synced block:
```
var web3 = new Web3(Web3.givenProvider || 'https://mainnet.infura.io/v3/MYKEY');
```

However when Web3 is sourced from a local full node (within the same machine), the code executes the correct 'latest' synced block yet hangs afterwards instead of returning to the terminal prompt. I've already verified this local node is fully synced and works without any issues when writing scripts on other platforms such as Python.

Either of the below results in terminal hanging after code execution:
```
var web3 = new Web3('/home/geth.ipc', net);
var web3 = new Web3('ws://127.0.0.1:8546', net);
```

#### Steps to reproduce the behavior
```
const Web3 = require('web3');
const net = require('net');

var web3 = new Web3('/home/geth.ipc', net);
//var web3 = new Web3('ws://127.0.0.1:8546', net);
//var web3 = new Web3(Web3.givenProvider || 'https://mainnet.infura.io/v3/MYKEY')

    web3.eth.getBlock('latest').then(function(v){
        console.log("number:", v.number);
   }).catch(function(e) {
       console.log(e);
   });
```

### Versions 
* OS: Ubuntu 18.04.2 LTS
* web3.js: 1.0.0-beta.55
* nodejs: v10.15.3
* ethereum node: Geth v1.9.0-unstable

**Comment by nivida** [comment]
Thanks for opening this issue! I've tested it with my local Geth node and couldn't reproduce this issue. 

Used code: 
``` javascript 
const net = require('net');
const Web3 = require('web3');
const web3 = new Web3('./geth_chain/geth.ipc', net);

web3.eth.getBlock('latest').then(function(v){
  console.log("number:", v.number);
}).catch(function(e) {
  console.log(e);
});
```
And:
``` javascript 
const Web3 = require('web3');
const web3 = new Web3('ws://localhost:8546');

web3.eth.getBlock('latest').then(function(v){
  console.log("number:", v.number);
}).catch(function(e) {
  console.log(e);
});
```

**Comment by keennay** [comment]
Thanks Samuel.

Which version of geth are you using? I'm on v1.9.0-unstable, tried your exact code copied to my machine, & receive the same error on Ubuntu.

Perhaps this is a geth issue and I could then raise the issue in their repo.

**Comment by nivida** [comment]
Thanks for the answer! I will compare the behavior of different Geth versions asap.

**Comment by nivida** [comment]
The nodejs window is hanging because the IPC connection is still an active process. You would have to disconnect to kill the process.

**Comment by keennay** [comment]
> The nodejs window is hanging because the IPC connection is still an active process. You would have to disconnect to kill the process.

Hey, thanks for this Samuel. I know, this is a "thousand years later" response from my end, but I got this working! :)
