### ISSUE TITLE
websocket connection lose-regain crash web3

### ISSUE THREAD

**Issue by Jonas121** [ethereum/web3.js#2842]
### Description 

I have migrated my js code from 37 to 55 version of web3.
Using below presented code example to prepare provider and keep connection.
Issue is that current web3 version (55) crash after my Ethereum node lose and regain connection.

var Web3 = require('web3');
var ROPSTEN_WSS = 'ws://35.x.x.x:x';

function getProvider() {
    var provider = new Web3.providers.WebsocketProvider(ROPSTEN_WSS)
    provider.on('connect', () => {
     console.log('WS Connected')
    })	
    provider.on('error', e => {
	 console.error('WS Error ' + new Date().toISOString())
    })
    provider.on('end', async e => {
		console.log('WS End')
		await web3.setProvider(getProvider())
    })
    return provider
}

web3 = new Web3(getProvider())

#### Expected behavior
I expect that web3 automatically reconnect ws connection after Ethereum node get's back from temporary blackout

#### Actual behavior
After Ethereum node is back I check status if Ethereum network listening the peers. web3 library throws below error.

#### Steps to reproduce the behavior
1. running my js code on local node.js. Code connects using WS to my owned Ethereum node (geth)
2. for testing reasons disconnecting Ethereum node (geth console -> exit)
3. In web3(37) I was getting event 'end'. My code was presenting string 'WS end'. Using web3(55) events 'end' and 'error' are not fired at all! Question how to catch ws connection blackouts?
3. after some time running Ethereum node once again
4. On my js code running this line:
var isListening = await web3.eth.net.isListening()
5. Error immediately thrown on node.js console. According to documentation method should return Boolean (false).

Reference to documentation used:
https://web3js.readthedocs.io/en/1.0/web3-eth-net.html#islistening

#### Error Logs 
(node:25343) UnhandledPromiseRejectionWarning: Error: Connection error: Connection is not open on send()
    at /home/ec2-user/node_modules/web3-providers/dist/web3-providers.cjs.js:492:27
    at new Promise (<anonymous>)
    at WebsocketProvider.sendPayload (/home/ec2-user/node_modules/web3-providers/dist/web3-providers.cjs.js:487:14)
    at WebsocketProvider._callee$ (/home/ec2-user/node_modules/web3-providers/dist/web3-providers.cjs.js:185:29)
    at tryCatch (/home/ec2-user/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/ec2-user/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ec2-user/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/ec2-user/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/ec2-user/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/ec2-user/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
(node:25343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Versions 
web3.js: web3@1.0.0-beta.55
nodejs: v11.6.0
ethereum node: Geth Version: 1.8.27-stable

**Comment by nivida** [comment]
The reconnecting is now implemented directly in the WebsocketProvider and you do not have to listen to all these events etc. please use the WebsocketProvider as documented.

**Comment by Jonas121** [comment]
I agree that reconnection might be implemented in WebsocketProvider. Based on the code provided event 'end' never happening (so I am not doing reconnection).
Essence of this issue that after reconnection this command crash the code:
var isListening = await web3.eth.net.isListening()

**Comment by nivida** [comment]
Thanks for answering and sorry for not reading your issue close enough. There is already an open PR regarding the WebsocketProvider. I will check this [PR](https://github.com/ethereum/web3.js/pull/2811), test the described behavior, and if required will I fix it. This should get released in the beta.56.
