### ISSUE TITLE
Cannot read property 'gasLimit' of null

### ISSUE THREAD

**Issue by miguelmota** [ethereum/web3.js#2843]
### Description 

Getting the error `TypeError: Cannot read property 'gasLimit' of null` randomly 

#### Error Logs 

<img width="637" alt="Screen Shot 2019-05-24 at 4 30 03 PM" src="https://user-images.githubusercontent.com/168240/58361115-38a7b600-7e41-11e9-8368-b6a7e61efca4.png">

### Versions 
* web3.js: ^1.0.0-beta.37
* nodejs: 
* browser: Chrome
* ethereum node: infura rinkeby

**Comment by nivida** [comment]
Please update to the latest version of Web3.js and be aware that getBlock will return null if the requested block does not exist. This looks like an issue of infura.
