### ISSUE TITLE
web3.utils.hexToAscii prepends strange characters to a transaction's input data

### ISSUE THREAD

**Issue by joepagan** [ethereum/web3.js#2846]
### Description 

`web3.utils.hexToAscii` appears to add strange characters to a transaction's input data.

Sorry if this has been answered before, could not see anything, let me know if you need further info.

Example
```js
web3.utils.hexToAscii('0x4ed3885e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004035346565326633343264663132343361636161616136343536393331396131383930386531303835633132643861323031306433633362363639623765633539');
```

#### Expected behavior

returns:
`54ee2f342df1243acaaaa64569319a18908e1085c12d8a2010d3c3b669b7ec59`

#### Actual behavior

returns `NÓ^ @54ee2f342df1243acaaaa64569319a18908e1085c12d8a2010d3c3b669b7ec59`

### Versions 
* web3.js: ^1.0.0-beta.55
* nodejs: 10.14.2
* browser: node backend
* ethereum node: kovan test network

**Comment by nivida** [comment]
Thanks for opening this issue! I will fix and release it asap.

**Comment by OFRBG** [comment]
@joepagan Perhaps you've solved this issue, but `0x4ed3885e` is the solidity function signature. These 4 bytes are used to tell the EVM which function to execute, and they are essentially random, thus when converting them to ASCII you'll get random data. (Your function signature is parsed to `'NÓ� ^'`.) The zeros between the signature and the number payload are interpreted as `\u0000`, aka NULL, which are "no-ops".

Also, the `0x20` in the middle is interpreted as a whitespace, and the `0x40` as `@`.

**Comment by joepagan** [comment]
@OFRBG appreciate the response and thank you for the explanation! 

I had not solved this as I changed my condition to check the if the string is contained in the result instead:

```js
blockchainHash = await web3.eth.getTransaction(txHash)
hashMatch = web3.utils.hexToAscii(blockchainHash).includes(localHash);
```

Is the function signature so unique that I cannot parse it for an exact match?
