### ISSUE TITLE
web3-core-promievent missing from packages/

### ISSUE THREAD

**Issue by liamaharon** [ethereum/web3.js#2850]
### Description
I want to use the web3 PromiEvent in my project. 

#### Expected behavior
Based on the Github link provided here https://www.npmjs.com/package/web3-core-promievent, https://github.com/ethereum/web3.js/tree/1.0/packages/web3-core-promievent should exist 

#### Actual behavior
There is no directory at https://github.com/ethereum/web3.js/tree/1.0/packages/web3-core-promievent

**Comment by nivida** [comment]
This package got removed and the PromiEvent object got moved to the web3-core-method.
