### ISSUE TITLE
Error with default contract options

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/web3.js#2852]
### Description

Nor web3 default options neither contract default options are used when `send()` is executed.

#### Expected behavior
```js
this.contract = new web3.eth.Contract(registryAbi, address, { from: '0x...');
```

Should use `from` value when doing

```
this.contract.methods.setOwner(hash, owner).send()
```

When I use `this.contracts` it should use default options.

#### Actual behavior
```
Error: No "from" address specified in neither the given options, nor the default options.
```

#### Steps to reproduce the behavior

I'm using this in https://github.com/rnsdomains/rns-js/blob/master/test/registry.test.js

There I try changing my line 22 for

```js
registry = new Registry(web3, registryContract.address, { defaultAccount: accounts[0] });
```

Then tests failt with _no from_ error.

---

Adding options to each transaction is the workaround, but not the expected behaviour

**Comment by nivida** [comment]
Could you please add your environment details? (versions etc.)

**Comment by ilanolkies** [comment]
Yes sory!

```
$truffle version
Truffle v5.0.9 (core: 5.0.9)
Solidity - 0.4.25 (solc-js)
Node v11.12.0
Web3.js v1.0.0-beta.37
```

**Comment by nivida** [comment]
Sorry for the confusion with the removing and adding of the label. This got fixed in the latest version of Web3.js.

**Comment by ilanolkies** [comment]
Oh sory. The lib is using `v1.0.0-beta.55` but Truffle is running over 37.

**Comment by ilanolkies** [comment]
I'm trying to fix it wrapping truffle's `web3`...
