### ISSUE TITLE
Web3EthereumProvider does not await Promise from connection

### ISSUE THREAD

**Issue by pixelmatrix** [ethereum/web3.js#2857]
I'm testing an implementation of EthereumProvider using web3 1.0.0-beta.55, and it appears there is an issue with the Web3EthereumProvider adapter. All my requests error with: "".

It looks like this line is missing an `await`, since `send()` returns a Promise in EthereumProvider.
https://github.com/ethereum/web3.js/blob/e48511990199330cf5b100ed52dd7953df934ab3/packages/web3-providers/src/providers/Web3EthereumProvider.js#L132

I'd be happy to open a PR if this is indeed a bug.

**Comment by nivida** [comment]
Thanks for opening this issue! Because of the unclear state of this EIP did I stop to update or fix the EthereumProvider handling of Web3. Feel free to fix this and I will try to push this EIP to a final state.

**Comment by nivida** [comment]
This got fixed with PR: https://github.com/ethereum/web3.js/pull/2854

**Comment by pixelmatrix** [comment]
Thanks for the quick fix!
