### ISSUE TITLE
Greeter not working

### ISSUE THREAD

**Issue by linagee** [ethereum/web3.js#286]
I tried the example here: https://ethereum.org/greeter

``` js
> eth.getCompilers()
['Solidity' ]
>
```

I'm on develop branch of geth. (/v1.0.1-dcb23bc3/linux/go1.4.2)
solc: 0.9.39+1118SNAPSHOT20150807105538trusty-0ubuntu1

I'm trying to do the greeter as close to the original as possible in case I'm doing something wrong.

``` js
var greeterSource = 'contract mortal { address owner; function mortal() { owner = msg.sender; } function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { string greeting; function greeter(string _greeting) public { greeting = _greeting; } function greet() constant returns (string) { return greeting; } }'

var greeterCompiled = web3.eth.compile.solidity(greeterSource)
```

``` js
var _greeting = "Hello World!"
var greeterContract = web3.eth.contract(greeterCompiled.greeter.info.abiDefinition);

var greeter = greeterContract.new(_greeting,{from:web3.eth.accounts[0], data: greeterCompiled.greeter.code, gas: 1000000}, function(e, contract){
    if(!e) {

      if(!contract.address) {
        console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");

      } else {
        console.log("Contract mined! Address: " + contract.address);
        console.log(contract);
      }

    }
})
```

I have only changed the above gas to be 115510 instead of 1 million as the gas limit isn't that high yet.

Here is the error I get:

``` js
> var theGreeter = greeterContract.at('0x3dbdeeafa2aca6c8c4f6e442b07bb575fc5658a9')
undefined
> theGreeter
{
  address: '0x3dbdeeafa2aca6c8c4f6e442b07bb575fc5658a9',
  allEvents: function (),
  greet: function (),
  kill: function ()
}
> theGreeter.greet()
new BigNumber() not a base 16 number:
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at <unknown>
    at greet (<anonymous>:-93978:-19)
    at <anonymous>:1:1
```

Upon initially deploying the contract, I never get the "Contract mined! Address:" message. (That is why I tried to manually assign using .at() above.) I do get the message "Contract transaction send: TransactionHash". I am able to see the transaction on etherchain.org. (https://etherchain.org/tx/0x1a03e6f3a89a65a2cd146a215cbb8427f29c8695517dddc6a0901c9fbe179eb0) I am able to look up the contract address using eth.getTransactionReceipt(). (Because etherchain.org does not provide that yet.)

**Comment by linagee** [comment]
This looks similar to what I am seeing. It's possible to gas limit is not yet high enough on Frontier to run "the greeter".

https://github.com/ethereum/go-ethereum/issues/842

**Comment by frozeman** [comment]
Thats might be the case, but anyway we should add a better error reporting for such cases @debris
