### ISSUE TITLE
myContract.getPastEvents(“allEvents”) returns empty array

### ISSUE THREAD

**Issue by DamiToma** [ethereum/web3.js#2861]
### Description 
I want to get all past events from a contract I deployed on the Ropsten network.

Contract:
```
pragma solidity ^0.5.1;

contract SampleContract {
    uint storageData;

    event MamboNumberTwo(uint _value);
    event MamboNumberFive(uint _value);
    event MamboNumberString(string _value);

    function test(uint x, uint y, string memory s) public {
        emit MamboNumberTwo(x);
        emit MamboNumberFive(y);
        emit MamboNumberString(s);
    }
}
```
It is deployed at [0xdd73A24Ef263D9bed42b0db60607F915194A7fbF](https://ropsten.etherscan.io/address/0xdd73A24Ef263D9bed42b0db60607F915194A7fbF), as you can see this contract has emitted nine events so far.

I would like to get them using web3's `myContract.getPastEvents("allEvents")`, but this returns a Promise resolving in an empty array, as though no event was emitted yet.

Full code:
```
web3 = new Web3(...) // Connect to Ropsten node via Websocket
var contract = new web3.eth.Contract([...], "0xdd73A24Ef263D9bed42b0db60607F915194A7fbF");
contract.getPastEvents("allEvents").then(console.log);
```

#### Expected behavior
Calling `myContract.getPastEvents("allEvents")` should return an array of nine events emitted by the contract.

#### Actual behavior
Calling `myContract.getPastEvents("allEvents")` returns an empty array.

#### Steps to reproduce the behavior

1. Import `web3`
2. Set the provider to ws://x.x.x.x:8546
3. Instantiate contract using its ABI and address
4. Call `myContract.getPastEvents("allEvents")`
5. Print callback value to console

### Versions 
* web3.js: 1.0.0-beta35
* browser: Chrome 74 on Windows 10

**Comment by DamiToma** [comment]
This works fine with beta 55.

**Comment by kennie-larkson** [comment]
I am facing the same issue 
And I am working with web3 v 1.5.1

require("dotenv").config();
const Tx = require("ethereumjs-tx");
const Web3 = require("web3");
const web3 = new Web3(process.env.URL_ROPSTEN);

const contractAbi = process.env.DAITOKEN_CONTRACT_ABI;
const abi = JSON.parse(contractAbi);
const contractAddress = process.env.DAITOKEN_CONTRACT_ADDRESS;
const contract = new web3.eth.Contract(abi, contractAddress);


contract.getPastEvents(
  "AllEvents",
  { fromBlock: 1555027, toBlock: 1723017 },
  (err, events) => {
    console.log(events);
  }
);
