### ISSUE TITLE
issues with toHex()

### ISSUE THREAD

**Issue by VoR0220** [ethereum/web3.js#287]
This function appears to not be working, I've been trying to get it to run using this and an address as a test:

    var defaultAccount = web3.toHex("test"); 

    var defaultAccount = web3.toHex("6970e295044bfa4279689909f32e0d3b8aee3df9");

with no such luck....it returns this error:

Uncaught TypeError: Expecting a function in instanceof check, but got #< Object >

**Comment by debris** [comment]
what version of web3.js are you using (`web3.version`). I really cant reproduce it.

**Comment by VoR0220** [comment]
I'm sorry. I should have closed out this issue. I had been running this with a Backbone.js wrapper and combined with Jquery wanting to convert everything to UTF-8 that seems to have been the issue. Closing this out.
