### ISSUE TITLE
miner.start() is not a function?

### ISSUE THREAD

**Issue by king841997** [ethereum/web3.js#2876]
import {Miner} from 'web3-eth-miner';
then

  const options = {
        defaultAccount: "0x78dB3e2129D58685444989dD9682DDDC70dd3C82",
        defaultBlock: 'latest',
        defaultGas: 1,
        defaultGasPrice: 0,
        transactionBlockTimeout: 50,
        transactionConfirmationBlocks: 24,
        transactionPollingTimeout: 480,
      }
      const miner = new Miner("http://127.0.0.1:9545", null,options);
      console.log(miner); miner.start(2);
miner.start() says that it is not a function()... ref : https://web3js.readthedocs.io/en/1.0/web3-eth-miner.html

**Comment by nivida** [comment]
The documentation got already updated (https://github.com/ethereum/web3.js/blob/1.0/docs/web3-eth-miner.rst) I will build readthedocs asap.
