### ISSUE TITLE
where's getPendingTransactions? 

### ISSUE THREAD

**Issue by lebed2045** [ethereum/web3.js#2878]
there's description in the documentation https://web3js.readthedocs.io/en/1.0/web3-eth.html#getpendingtransactions,
but in `"@types/web3": "^1.0.18",` there no such function,
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth/types/index.d.ts
there's `pendingTransactions` hovewer, is it?

**Comment by nivida** [comment]
The types are included in the Web3 NPM package itself since version beta.38. The old types do still exists because some devs could use a older version of Web3. 

Btw.: This JSON-RPC method isn’t implemented for all node types but Aleth does definitely have this method.

**Comment by lebed2045** [comment]
is the package itself it also called 
```pendingTransactions(callback?: (error: Error, result: []) => void): Promise<[]>;``` and it seems it doesn't match docs and js implementation. 
Is there any example where this function works?
