### ISSUE TITLE
Inspecting the contract method object after creation

### ISSUE THREAD

**Issue by leonprou** [ethereum/web3.js#2880]
### Description
In `~web3-beta.30` it was possible to access method properties:

```
const method = myContract.methods.myMethod(...arguments)
console.log(method._method) // can be used to display the method name, signature, etc
```

Though `_method` is imply on private field, it was a nice feature and helped to inspect the method in our transaction flow. 

Now all the data is encapsulated from the user, as seen here: https://github.com/ethereum/web3.js/blob/9714f30869d2ba6d1a7bc80df67a029694b2abc3/packages/web3-eth-contract/src/proxies/MethodsProxy.js#L54.

I think that accessing the method's fields make sense. But otherwise, maybe some JS ninja can give an advice how to hijack the constructor and add my own method to the method class.

### Versions 
* web3.js: web3-beta.55

**Comment by nivida** [comment]
Extending of a module isn't possible without forking of Web3.js but you are able to create your own standalone module or just a custom method object with the [core API Web3.js](https://web3js.readthedocs.io/en/1.0/web3-module.html) does provide. 

Solution without a custom module:
``` js
class MyMethod extends AbstractMethod {
  constructor(utils, formatters, moduleInstance) {
    super('test_method', 0, utils, formatters, moduleInstance);
  }

  ...
}

import * as Utils from 'web3-utils';
import {formatters} from 'web3-core-helpers';

 // web3, web3.eth, or any other Web3 module.
new MyMethod(utils, formatters, web3.eth).execute().then(console.log);
```

**Comment by leonprou** [comment]
@nivida I don't, looks pretty verbose..

Why not to put this to discussion?
