### ISSUE TITLE
duplicate events and subscribe from smart contract

### ISSUE THREAD

**Issue by athlona64** [ethereum/web3.js#2881]
### Description 

when using events and subscribe event from smart contract some event duplicate firing looks like

![Selection_177](https://user-images.githubusercontent.com/3031787/59093080-4aa74f80-893d-11e9-899d-a2580912fc8e.png)

#### Expected behavior

should only firing one transaction from above but web3 subscribe and events duplicate event in one transaction

#### Actual behavior

duplicate firing in one transaction 

![Selection_177](https://user-images.githubusercontent.com/3031787/59093361-f8b2f980-893d-11e9-8590-7fcc7cfe34ee.png)

#### Steps to reproduce the behavior

```
>  let sub = web3.eth.subscribe('logs', {
>         address: contractAddress,
>         topics: [
>             transfer
>         ]
>     }, (error, log) => {
>         if (error) { console.error(error); return; }
>         let dlog = web3.eth.abi.decodeLog(ERC20_TRANSFER_EVENT_ABI.inputs, log.data, log.topics.slice(1))
>         console.log(`new log: ${dlog.from} -> ${dlog.to} : ${dlog.value}`);
>         console.log(log.transactionHash);
> 
>     }).on("data", (log) => {
> 
>     })
>         .on("changed", (log) => {
>             // console.log(log);
>         });
> 

```
#### Error Logs 

no error but duplicate firing on events

### Versions 
* web3.js: web3@1.0.0-beta.36
* nodejs: v8.16.0
* ethereum node: rinkeby

**Comment by nivida** [comment]
Could you please update your issue to be aligned with the issue template we provide?  (versions etc.)

**Comment by athlona64** [comment]
updated

**Comment by nivida** [comment]
Does this error still occur in the latest version of Web3? or with version beta.37?

**Comment by athlona64** [comment]
in latest version of Web3 and i think this problem maybe occur in only Rinkeby network

**Comment by HoangJerry** [comment]
#2821 It same as me, but he havent resolved yet.

**Comment by nivida** [comment]
Thanks for the additional details. @athlona64 are you using infura to test it?

**Comment by cgewecke** [comment]
We think duplicate events are resolved with the Websockets rewrite in Web3 1.2.7. If anyone continues to see this, please ping.

**Comment by JoseMiguelHerrera** [comment]
@cgewecke I have an older application  (last using 1.0.0-beta.37), where this problem was very apparent. I'm updating it now, with v1.2.8, and unfortunately I'm still getting multiple firings for events.

I'm connecting via websocket provider to  geth 1.9.9-stable

**Comment by cgewecke** [comment]
@JoseMiguelHerrera Do you have any tips for how to reproduce? Is there a recognizable pattern in your case?

**Comment by JoseMiguelHerrera** [comment]
I'm having a difficult time seeing a recognizable pattern, since it happens somewhat randomly. I just updated geth to the latest version and it still happens, perhaps much less often.

I know there's several ways to subscribe to events, but this is the way I've done it:

`            let web3 = connection._getWeb3().RPC;
            let ContractRPC = new web3.eth.Contract(ABI, Address)
            ContractRPC.events.LogPriceUpdate(function (error, result) {
                if (!error) {
                        callback(
                            {
                                newprice: result.returnValues._newPrice,
                                timestamp: result.returnValues.timestamp,
                            }
                        )
                } else {
                    callback(error)
                }
            });`

Could it be related to creating a new contract instance everytime? If so, why does it only happen sometimes?

**Comment by or2008** [comment]
have the same issue with subscribing to pendingTransactions

```
web3.eth.subscribe('pendingTransactions', async (error, txHash: string): Promise<void> => {
    console.log(txHash);
});
```

I can see duplicate tx hashes in my log, usually, the first tx hash get printed and a duplicate one is get printed 10 seconds after.
I am using web3 v1.2.9 connected via websocket to openethereum (parity) node v3.0.1

**Comment by psyfreak** [comment]
I had the same issue and on my side the reason was, that I used webpack and it seems that when you rebuild that the previous  event listener is still subscribed.
I could reproduce this meaing the every time I rebuild I got one duplicate more.
