### ISSUE TITLE
Can't install web3 due to missing build tool v141

### ISSUE THREAD

**Issue by pravsa** [ethereum/web3.js#2883]
Hey,

I recently started solidity programming and I am now trying to test and deploy my contract. I hope this is the correct way to ask this question:

When I want to install web3 with npm in the react app folder (npm install web3 --save), I get an error message that my v141 building tools are missing.

`Warning: Missing input files:
C:\Users\name\kfv-bet\node_modules\scrypt\build\..\scrypt\win\include\config.h
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen. //it says that i should add the switch /m to create the project. What does that mean?
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build u
sing the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, an
d then selecting "Retarget solution". [C:\Users\name\kfv-bet\node_modules\scrypt\build\copied_files.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build u
sing the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, an
d then selecting "Retarget solution". [C:\Users\name\kfv-bet\node_modules\scrypt\build\scrypt_wrapper.vcxproj]`

I have already googled a lot and most of the time the issue isn't related my problem or they suggest to reinstall Visual Studio and make sure that V141 tools are installed. I try the latter several times and I especially check if V141 is ticked when i install C++ dev tools.

Do you know what's wrong? And which "input files" are missing?

Thanks a lot in advance and best regards!

**Comment by chaitanyapotti** [comment]
@pravsa Have you tried installing [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) npm package globally.?
