### ISSUE TITLE
Batch Request intention- contract method call- order of mining

### ISSUE THREAD

**Issue by adrianturcato** [ethereum/web3.js#2885]
On the web3 documentation website, batch requests receive about 7 words of description (https://web3js.readthedocs.io/en/1.0/web3-eth.html#batchrequest): "Class to create and execute batch requests." With the code example:

```
const batch = new web3.BatchRequest();
batch.add(web3.eth.getBalance.request('0x0000000000000000000000000000000000000000', 'latest'));
batch.add(contract.methods.balance(address).call.request({from: '0x0000000000000000000000000000000000000000'}));
batch.execute().then(...);
```

Scouring the web I have found little additional description on what was the intention or use case for these batch requests. For example I am trying to understand what the above code is really intended to do. Is there somewhere that I missed that has a good rundown on the expected behavior. 

To be a bit more specific, when `batch.execute()` is called does this at all guarantee the order in which the contract methods will be mined?

Previously I was using this code:

```
    var batch = web3.createBatch();
    batch.add(myInstance1.approve.request(arg1).call({from: userAddress}));
    batch.add(myInstance2.myMethod2.request(arg2)).call({from: userAddress}));
    batch.execute();
```

I need myInstance1.approve to be mined before myInstance2.myMethod2, because the approval allows for a transfer of a custom token to occur within myInstance2.myMethod2. As far as I can tell at the moment batch requests do NOT guarantee this. I have no idea if this is the intended behavior or not.

I have moved on to using this approach, which definitely works but has some UX implications because there will be two separate MetaMask popups one after the first one is mined.

```
    myMethod1.methods
      .approve(arg1)
      .send({from: userAddress})
      .on('confirmation', contractInteraction)
      .on('error', console.error);

    function contractInteraction(confirmationNumber,receipt){
      if(confirmationNumber === 1){
        myInstance2.methods
          .myMethod2(arg2)
          .send({from:userAddress})
          .on('error', console.error);
      }
    }
```

I can set up a github to reproduce this situation if required but thought there might be an easy answer.

* web3.js: "1.0.0-beta.55"
* nodejs: v8.16.0
* browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* ethereum node: Rinkeby

**Comment by nivida** [comment]
Thanks for opening this issue! The execution order of the methods should not change but I will test it closer to be 100% sure and will drop a comment here.

**Comment by adrianturcato** [comment]
Hi nivida,
Thanks for the reply. Just to clarify when you say executed, you mean included in a block and mined, ie executed by the EVM? Sorry I am a little unsure of the exact lingo required to describe this situation. 
You flagged the question as clarification needed? What information can I provide that would help?

Thanks!!

**Comment by nivida** [comment]
Thanks for your answer! @adrianturcato 

 > Just to clarify when you say executed, you mean included in a block and mined, ie executed by the EVM

Yes I mean included in a block (mined). It got the ``clarification needed`` label because I have to test it closer for giving an exact answer.

**Comment by adrianturcato** [comment]
Hi Nivida,

Any thoughts about this? 

Thanks!

**Comment by adamsoffer** [comment]
Hey! I'm experimenting with batch request and I'm wondering the same thing. The docs imply that transactions should confirm sequentially, but I'm running into an issue where some transactions are failing because they're not actually being confirmed sequentially. Is anyone else encountering this?

**Comment by adamsoffer** [comment]
They're _supposed_ to be processed sequentially and if a user declines one of the requests, the rest of the unprocessed requests should be declined as well. This was how the functionality worked pre web3 1.0 as described here: https://docs.fortmatic.com/web3-integration/batch-request

**Comment by adamsoffer** [comment]
@nivida Currently testing and it appears transactions are _not_ being confirmed sequentially anymore. I'm using this pattern -> https://github.com/liamzebedee/awesome-solidity-patterns/blob/master/web3.md#making-large-numbers-of-requests

**Comment by adamsoffer** [comment]
@nivida @adrianturcato Interesting! It seems like this is actually a Metamask bug. I just tested with another web3 provider (portis) and it does, in fact, submit and confirm the transactions sequentially. MetaMask, however, *does not* honor the order in which you add transactions to the batch before executing. After calling `batch.execute()` MetaMask asks you to confirm the transactions in the incorrect order. I'll file a bug w/ Metamask.

**Comment by kolya182** [comment]
> They're _supposed_ to be processed sequentially and if a user declines one of the requests, the rest of the unprocessed requests should be declined as well. This was how the functionality worked pre web3 1.0 as described here: https://docs.fortmatic.com/web3-integration/batch-request

@nivida `.add` method requires `Method` argument type, where is this example up to date ?
```
export class BatchRequest {
    constructor();

    add(method: Method): void;

    execute(): void;
}
```

```
export interface Method {
    name: string;
    call: string;
    params?: number;
    inputFormatter?: Array<(() => void) | null>;
    outputFormatter?: () => void;
    transformPayload?: () => void;
    extraFormatters?: any;
    defaultBlock?: string;
    defaultAccount?: string | null;
    abiCoder?: any
}
```
web3 1.2.6

**Comment by kolya182** [comment]
> @nivida Currently testing and it appears transactions are _not_ being confirmed sequentially anymore. I'm using this pattern -> https://github.com/liamzebedee/awesome-solidity-patterns/blob/master/web3.md#making-large-numbers-of-requests

@nivida `.add` method requires `Method` argument type, is this example up to date ?
```
export class BatchRequest {
    constructor();

    add(method: Method): void;

    execute(): void;
}
```

```
export interface Method {
    name: string;
    call: string;
    params?: number;
    inputFormatter?: Array<(() => void) | null>;
    outputFormatter?: () => void;
    transformPayload?: () => void;
    extraFormatters?: any;
    defaultBlock?: string;
    defaultAccount?: string | null;
    abiCoder?: any
}
```

TS gives warning when i do this
```
const batch = new web3.BatchRequest();
 chunk.forEach((tx: string) => {
       batch.add(web3.eth.getTransactionReceipt(tx, callback));
 });
```
```
Argument of type 'Promise<TransactionReceipt>' is not assignable to parameter of type 'Method'.
  Type 'Promise<TransactionReceipt>' is missing the following properties from type 'Method': name, call
```
web3 1.2.6
