### ISSUE TITLE
Nodejs application gets stuck after Smart contract deployment

### ISSUE THREAD

**Issue by aditya-sahu** [ethereum/web3.js#2886]
### Description 
So I have been trying to deploy a smart contract using nodejs, but when I call the function to deploy, I get no contract address on my console. It's like the send() function never completed its execution. And that's why the next instruction never starts its execution, even though I know that the contract is still being deployed on my local blockchain network (I know it because I can see on the cmd prompt where my ganache-cli is running.
I'm trying to get the deployed contract address, please tell me how to do the same.

#### Expected behavior

Calling await contract.deploy({..}).send({..}) should return response, and after that contract address should be printed on the console.

#### Actual behavior

Instead, no output is printed on the console after this: 'Deploy function called, about to deploy'.

command prompt : 

> cmd> node src/deploy
> No web3? You should consider trying MetaMask!
> [AsyncFunction: deploy]
> entered, about to deploy

 
Although, I know that the contract has been deployed because my ganache-cli shows this output:

> Transaction: 0x12345
>   Contract created: 0x12345
>   Gas usage: 1605526
>   Block Number: 6
>   Block Time: Date and time of deployment is shown

#### Code Snippet (deploy.js)

```deploy.js
      
  var Web3 = require('web3');
// abibytecode[0] has abi, abibytecode[1] has bytecode
const abibytecode = require('../src/compile');
var web3;

if (typeof web3 !== 'undefined') {
    web3 = new Web3(web3.currentProvider);
} else {
    // set the provider you want from Web3.providers
    console.log('No web3? You should consider trying MetaMask!');
    web3 = new Web3('ws://localhost:8545');
}

let account = 'my account address is here';

const contract = new web3.eth.Contract(abibytecode[0]);

const deploy = async () => {
    console.log('Deploy function called, about to deploy');
    const response = await contract.deploy({data: abibytecode[1]}).send({
      from: account,
      gas: '3000000'
    });
    console.log('Contract deployed to:', response.address);
    console.log('Contract deployed to:', response.options.address);

    return response;
};
console.log(deploy);
deploy((res)=>{console.log(res)});

    ```

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: v10.16.0
* browser: None, running the script from command
* ethereum node: ganache-cli

**Comment by nivida** [comment]
Thanks for opening this issue! Configuring of the [transaction confirmation workflow](https://web3js.readthedocs.io/en/1.0/web3.html#transactionconfirmationblocks) will fix this.

**Comment by aditya-sahu** [comment]
> Thanks for opening this issue! Configuring of the [transaction confirmation workflow](https://web3js.readthedocs.io/en/1.0/web3.html#transactionconfirmationblocks) will fix this.

Hi @nivida ,
Thanks, but the problem isn't solved. I console logged the value of web3.transactionConfirmationBlocks in my deploy.js and the number 24 was printed. What should I change it to and how to configure it?
