### ISSUE TITLE
web3.eth.getPendingTransactions() returns empty array

### ISSUE THREAD

**Issue by DamiToma** [ethereum/web3.js#2890]
### Description 
I want to get the list of pending transactions on the Ropsten network, but `web3.eth.getPendingTransactions()` returns an empty array, while I can see on EtherScan that there are several transactions yet to be mined. I tried connecting to both mine and Infura's nodes and the result is the same.

#### Expected behavior

Calling `web3.eth.getPendingTransactions().then(console.log)` should print a list of pending transactions.

#### Actual behavior

Calling `web3.eth.getPendingTransactions().then(console.log)` prints an empty array.

#### Steps to reproduce the behavior

1. Import Web3
2. Connect to Ropsten node via Ropsten or local node
3. Call `web3.eth.getPendingTransactions().then(console.log)`

#### Error Logs 
No errors are generated.

### Versions 
* web3.js: 1.0.0-beta55
* nodejs: 8.9.0
* ethereum node: 1.8.27-stable-4bcc0a37

**Comment by nivida** [comment]
The empty array isn't a wrong return value. As it looks like is Infura not providing this feature.

**Comment by DamiToma** [comment]
@nivida Actually I get an empty array using my private node, while I get `null` using Infura.

**Comment by ProximalPod** [comment]
@nivida same issue here. Local node, getting empty array. This should be reopened

**Comment by matt-spark-health** [comment]
Same

**Comment by xklob** [comment]
Same issue.

**Comment by UnsignedInt8** [comment]
Same issue.  Personal local node, got empty array


    web3.js: 1.3.1
    nodejs: 12.18.3
    ethereum node: 1.9.24-stable

**Comment by nuno-tomas** [comment]
Any tips?

**Comment by afanasy** [comment]
This worked for me:
```js
var Web3 = require('web3')

var web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:9546', {clientConfig: {
  maxReceivedFrameSize: 10000000, //needed because txpool_content call returns a lot of data
  maxReceivedMessageSize: 10000000
}}))

//add txpool support
web3.extend({
  property: 'txpool',
  methods: [{
    name: 'content',
    call: 'txpool_content'
  }]
})

web3.txpool.content((err, data) => {
  console.log(err, data)
})
````
Geth node needs to have `txpool` API enabled, `web3@1.3.5`, [txpool_content docs](https://geth.ethereum.org/docs/rpc/ns-txpool#txpool_content)

**Comment by akegaviar** [comment]
btw, on the original issue for anyone coming from a search engine, `web3.eth.getPendingTransactions()` returns an empty array because it's supposed to return only txs originating [from an account on the node](https://github.com/ethereum/go-ethereum/blob/ead814616c094331915b03edd82d4200a7880178/internal/ethapi/api.go#L1700).

Check also [Exploring the methods of looking into Ethereum’s transaction pool](https://chainstack.com/exploring-the-methods-of-looking-into-ethereums-transaction-pool/).
