### ISSUE TITLE
Grabbing the raw ABI from a contract instance

### ISSUE THREAD

**Issue by adrianmcli** [ethereum/web3.js#2894]
I see that we no longer have direct access to the raw ABI via `contract.jsonInterface`, and instead it returns an `AbiModel` object. That's cool, but shouldn't there be a method that will return the raw ABI as well?

**Comment by adrianmcli** [comment]
Relevant source code: https://github.com/ethereum/web3.js/blob/aaf26c8806bc9fb60cf6dcb6658104963c6c7fc7/packages/web3-eth-contract/src/models/AbiModel.js

**Comment by nivida** [comment]
Closed because of the discussion in the Truffle slack.

**Comment by adrianmcli** [comment]
The Truffle slack is not public, so to give some context to the wider community. I had a discussion with @nivida and we decided to shelve this topic until discussions for the next major version release (i.e. v2.x).
