### ISSUE TITLE
Error in web3@1.0.0-beta.55 and installing web3@1.0.0-beta.37

### ISSUE THREAD

**Issue by HP213** [ethereum/web3.js#2895]
I have worked with web3.js with version .37 and solidity about a year ago, and now I want to use my same code. I have installed new version on web3 and it is not able to send/deploy my contract on local test network, i am using ganache-cli for it. It takes about 13min and then show error. It is fetching accounts but not able to deploy. I have tried to install previous versions of web3 like .37 but it is showing error and not able to install. Now i am unable to perform any work from latest version of web3.
![Screenshot from 2019-06-17 06-35-40](https://user-images.githubusercontent.com/34127674/59579720-2a456680-909c-11e9-8412-b71b12fc9876.png)

I have also tried to install previous version of web3 but they are showing error while installing and not able to install

**Comment by nivida** [comment]
Thanks for opening this issue! Configuring of the [transactionConfirmationBlocks](https://web3js.readthedocs.io/en/1.0/web3-eth.html#web3-module-transactionconfirmationblocks) property in the Web3 module options will solve your problem. 

Btw.: Initiating of a contract isn't a async operation.

**Comment by HP213** [comment]
Please open this issue again.
Sorry to say but the problem still persists.

Firstly there is no need of transactionConfirmationBlocks. I was using ubuntu 18.04 and web3@1.0.0-beta.27 is not installing on ubuntu, it just gives vulnerability warning and some errors and then just stop installation, whereas I tried in Windows 10 and same command work fine, same vulnerability warning but installed without error and the same above code run with same initializing contract in asynchronous function.

So why this happening, why it is behaving differently in two os?
