### ISSUE TITLE
web3.sha3 cannot handle bytes of value larger than 0x7f

### ISSUE THREAD

**Issue by chriseth** [ethereum/web3.js#290]
`web3.sha3('0x80', true)` should return
`56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421`
but it actually returns
`6b03a5eef7706e3fb52a61c19ab1122fad7237726601ac665bd4def888f0e4a0`

Furthermore, `web3.sha3(String.fromCharCode(0x80))` returns
`0f50dcb7f76b82d3cf8c843adacd5cb4d1ce1b6de2ef1f2557f196d07c26f08e`
which is not correct either.

**Comment by chriseth** [comment]
It is probably a good idea to use crypto-js's WordArray when passing the data over to crypto-js.

Furthermore, I would really appreciate a solution which is correct in 100% of the cases. With the current implementation, it is impossible to compute the sha3 hash of any string that starts with `"0x"`.

**Comment by debris** [comment]
are you sure that it should return '56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421' ?

I've just created a simple snippet, which encodes `0x80` to `6b03a5eef7706e3fb52a61c19ab1122fad7237726601ac665bd4def888f0e4a0` using WordArray. Can you show me what am I doing wrong? 

```
var CryptoJS = require('crypto-js');
var sha3 = require('crypto-js/sha3');

var wordArray = CryptoJS.enc.Utf8.parse('0x80');
assert.equal(sha3(wordArray, {
    outputLength: 256
}).toString(), '6b03a5eef7706e3fb52a61c19ab1122fad7237726601ac665bd4def888f0e4a0');
```

**Comment by chriseth** [comment]
`CryptoJS.enc.Utf8.parse` again assumes that the input is utf-8 encoded, but it is not a valid (hex-encoded) utf8-string.

**Comment by tomlion** [comment]
Solidity's sha3(128) returns `56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421`

and I want at least one of `web3.sha3('0x80', true)` and `web3.sha3('0x80')` should return same result as Solidity does.

But all I can get is either `URIError: URI malformed` or `6b03a5eef7706e3fb52a61c19ab1122fad7237726601ac665bd4def888f0e4a0`, and none is what I wanted

**Comment by debris** [comment]
Fixed in latest develop. Tests are available [here](https://github.com/ethereum/web3.js/blob/0a79a520a7d8b0c22ce15bb058900321ce9ab8e2/test/sha3.js#L13-L17). Also the api is slightly different.
