### ISSUE TITLE
getPendingTransactions

### ISSUE THREAD

**Issue by prographo** [ethereum/web3.js#2901]
According to this: https://web3js.readthedocs.io/en/1.0/web3-eth.html#getpendingtransactions

I would have expected this:
```
> web3.eth.getPendingTransactions().then(console.log)
{"code":-32601,"message":"The method eth_pendingTransactions does not exist/is not available"}
```
To return a list of pending transactions.

I am using Infura, other calls work as expected.

```
> web3.version
'1.0.0-beta.55'
> web3.eth.getProtocolVersion().then(console.log)
> 63
web3.eth.getNodeInfo().then(console.log)
> Geth/v1.8.22-omnibus-260f7fbd/linux-amd64/go1.11.1
```

**Comment by nivida** [comment]
This JSON-RPC method is not implemented in Infura. Aleth for example does have this method implemented.

**Comment by mo-masmoudi** [comment]
@nivida can you mention all Ethereum clients who support the **getPendingTransactions** method?

Thank you.

**Comment by realtebo** [comment]
OMG .. and so ... !? we have the common problem of nonce with infura, we cannot even send timer-generated nonces to infura and we cannot correct transactionCount using pending counting.... and so !?!?
