### ISSUE TITLE
web3.eth.getCode() returns '0x' on Goerli & Locally setup PoA network whereas it returns '0x0' on Ganache for non-contract addresses.

### ISSUE THREAD

**Issue by iamdoraemon-tech** [ethereum/web3.js#2907]
### Description 

> web3.eth.getCode("EOA Address") returns '0x0' on Ganache and '0x' on Locally set up PoA network & Goerli Testnet.

#### Expected behavior

`web3.eth.getCode("EOA Address") should return either '0x' or '0x0' irrespective of whether the network is Ganache, locally setup PoA node, Goerli Testnet or Mainnet.`

#### Actual behavior

_On Ganache:_
`web3.eth.getCode("EOA Address") returns '0x0'`
_On Locally setup PoA node & Goerli Testnet:_
`web3.eth.getCode("EOA Address") returns '0x'`

#### Steps to reproduce the behavior

```
function isContract(address) {
    let code = web3.eth.getCode(address)
    console.log('code: ', code) // returns '0x0' for EOA on Ganache and '0x' for EOA on locally setup PoA node & Goerli Testnet
}

isContract("EOA Address")
```

### Versions 
* web3.js: 0.20.1
* nodejs: 10.15.3
* browser: ----
* ethereum node: Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.10.4

**Comment by nivida** [comment]
The return value of the method ``getCode`` doesn’t get manipulated by Web3.js. This is an inconsistency between ganache and geth.
