### ISSUE TITLE
Export more types

### ISSUE THREAD

**Issue by mattfysh** [ethereum/web3.js#2925]
Hi there, just a small feature request to export more types from the top-level `web3` package. At the moment, I've gotta jump through a few hoops to get some needed typings:

```ts
import Web3 from 'web3'
type ContractInstance = InstanceType<Web3['eth']['Contract']>
type ContractAbiInput = ConstructorParameters<Web3['eth']['Contract']>[0]
type AbiItem = Required<Exclude<ContractAbiInput, Array<any>>>
```

**Comment by joshstevens19** [comment]
Hey @mattfysh thanks for the issue. The web3 repo is packaged up in many packages meaning we had to construct our typing's in places it can be shared across. 

So firstly `web3.eth.contract` is not initialised by default and is of type `Contract` so i think you can write your code like this:

```
import { Contract } from 'web3-eth-contract';

type ContractInstance = InstanceType<typeof Contract>;
type ContractAbiInput = ConstructorParameters<typeof Contract>[1];
type AbiItem = Required<Exclude<ContractAbiInput, Array<any>>>;
```

which in my mind looks super clean.

I used parameter 1 as i am basing this on web3 version 1.0.0-beta.52 with contract class constructor as 

```
export class Contract {
    constructor(
        provider: provider,
        abi: AbiItem[],
        address?: string,
        options?: ContractOptions
    )
```

let me know if this helps!
