### ISSUE TITLE
web3.js maps solidity uint256 to negative bignumbers

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/web3.js#294]
Example: contract x { function getUnsignedValue() constant returns (uint256 rval) { return uint256(sha3(0)); } }

calling getUnsignedValue() with web3.js returns a negative bigNumber

**Comment by debris** [comment]
fixed in bbe031a35f07d24c715baf3a5e3b57b9538f9bdf . Thanks for report. It was new bug, introduced after latest improvements in solidity coder.
