### ISSUE TITLE
transaction confirmation workflow issue with Ganache

### ISSUE THREAD

**Issue by davidmurdoch** [ethereum/web3.js#2940]
### Description

`web3-1.0.0-beta.55` (also tested `beta.52`) subscribes to `newHeads` _after_ sending the transaction, which means web3 may miss emitted `newHeads` notifications. While it is unlikely for this race condition to be a problem on mainnet, or even test nets, it is pretty much guaranteed to be a problem when testing against Ganache.

#### Expected behavior

When a sent transaction is mined via `await web3.eth.sendTransaction`, `web3` should request the transaction's receipt and resolve the promise.

#### Actual behavior

I suspect what happens is:

1. `web3` sends the transaction to Ganache
2. Ganache receives the transaction and returns the `transactionHash`
3. `web3` receives the `transactionHash` then sends a `newHeads` subscription to Ganache
4. Ganache mines the transaction and emits a `newHeads` notification
  - note: web3 _isn't_ subscribed yet
5. Ganache receives the `newHeads` subscription.
6. `web3` waits for forever.

Previous versions (like beta.37 don't have this issue)

#### Steps to reproduce the behavior

Full reproduction:

Run:
```console
mkdir test
cd ./test
npm init -y
npm install ganache-core@2.5.7 web3@1.0.0-beta.55 -E
```

Save this code as `test.js`:
```javascript
const Ganache = require("ganache-core");
const Web3 = require("web3");

const server = Ganache.server();
server.listen(8545, async () => {
  const provider = new Web3.providers.WebsocketProvider("ws://localhost:8545");
  const options = { transactionConfirmationBlocks: 1 };
  const web3 = new Web3(provider, null, options);
  const accounts = await web3.eth.getAccounts();
  const transactionReceipt = await web3.eth.sendTransaction({ from: accounts[0], to: accounts[1], value: 1 });
  // never gets here.
  console.log(transactionReceipt);

  // shut down the Ganache server
  server.close();
});
```

Run:
```console
node test.js
```

The application hangs.

A clumsy workaround (passer-bys: do NOT use this in your testing code!):

```javascript
const Ganache = require("ganache-core");
const Web3 = require("web3");

const server = Ganache.server();
server.listen(8545, async () => {
  const provider = new Web3.providers.WebsocketProvider("ws://localhost:8545");
  const options = { transactionConfirmationBlocks: 1 };
  const web3 = new Web3(provider, null, options);
  const accounts = await web3.eth.getAccounts();
  const transactionReceiptPromise = web3.eth.sendTransaction({ from: accounts[0], to: accounts[1], value: 1 });

  // web3 newHeads race-condition workaround:
  await new Promise(resolve => setTimeout(resolve, 500)); // 500 is arbitrary
  await web3.currentProvider.send("evm_mine"); // force another block to be mined

  const transactionReceipt = await transactionReceiptPromise;
  // This works now!
  console.log(transactionReceipt);

  // shut down the Ganache server
  server.close();
});
```

### Versions 
* web3.js: `1.0.0-beta.55`
* nodejs: `10.16.0`
* ethereum node: `ganache-core@2.5.7`

**Comment by nivida** [comment]
Deactivating of automine is currently the workaround for it:
<img width="796" alt="Bildschirmfoto 2019-07-12 um 17 07 53" src="https://user-images.githubusercontent.com/1699173/61138341-9febf900-a4c7-11e9-9ad6-e64dc34429ab.png">

I will add an additional check before the ``newHeads`` subscription gets started for being compatible with Ganache.
