### ISSUE TITLE
Unsubscribing from confirmation

### ISSUE THREAD

**Issue by lpeppe** [ethereum/web3.js#2941]
Hi everybody. I was wondering how to unsubscribe from the confirmation event returned by the send method. I need to wait for some blocks to be mined before considering my transaction accepted.

```
myContract.methods
        .transfer(to, amount)
        .send({ from: from })
        .on("confirmation", (confirmationNumber, receipt) => {
          console.log(confirmationNumber);
          // if(confirmationNumber > 12) unsubscribe() 
        });
```

**Comment by nivida** [comment]
You are able to configure the number of blocks over the ``Web3ModuleOptions`` as described [here](https://web3js.readthedocs.io/en/1.0/web3-shh.html#web3-module-transactionconfirmationblocks).

**Comment by MaestosoToad** [comment]
Maybe you can use off option on callback promises events 
[https://web3js.readthedocs.io/en/v1.2.0/callbacks-promises-events.html#promievent](url)
