### ISSUE TITLE
taking too long to return the transaction receipt

### ISSUE THREAD

**Issue by m-yahya** [ethereum/web3.js#2945]
### Description 
I'm using web3 version ` web3@1.0.0-beta.55` and I'm trying to call `send` method of my contract that is deployed on `volta` network.
Here is my method I'm trying to call:
```
    function setDsoValue(address _assetPubkey, uint256 _value) public {

        if (admins[msg.sender].adminType != uint8(2) || !ownership[msg.sender][_assetPubkey]) {
            emit RejectSetValue(msg.sender, "Sender is not registered as DSO");
            return;
        }

        dsoSetValues[msg.sender].assetPubkeys.push(_assetPubkey) - 1;
        dsoSetValues[msg.sender].values.push(_value) - 1;
        dsoSetValues[msg.sender].time.push(now) - 1;

        emit NewDsoValue(msg.sender, _assetPubkey, _value, now);

    }
```
and here is my `js` code example:
```
const Web3 = require('web3');
const web3 = new Web3("ws://localhost:7546");

// instance of asset logging contract
const AssetLoggingContract = new web3.eth.Contract(ABI.json, address);
```
In my `vue` app, I'm using `button click` to call the method:
```
 // set dso value method
    setDsoValue() {
      console.time("receipt");
      AssetLoggingContract.methods
        .setDsoValue(this.ownerAssetPubkey, this.dsoInput)
        .send({ from: this.ownerPubkey })
        .then(receipt => {
          console.log(receipt);
          console.timeEnd("receipt");
        });
    }
```

#### Expected behavior

The transaction receipt should be available in less time. 
Previously, I was using ` web3@1.0.0-beta.37` and the time for the `receipt` to available was less. I executed the method three times with ` web3@1.0.0-beta.37` and here are the times calculated for each execution:
`receipt: 3578.828857421875ms`
`receipt: 3194.14697265625ms`
`receipt: 3889.321044921875ms`
I was having an [issue](https://ethereum.stackexchange.com/a/72883/38516) and I got help from [here](https://github.com/ethereum/web3.js/issues/1260) and migrated to the latest release.

#### Actual behavior

with the latest release, I can get the `hash` immediately. However, `receipt` is taking too long to be available. Here is the time estimation for three executions of the `send` method:
`receipt: 115934.73291015625ms`
`receipt: 119201.4990234375ms`
`receipt: 116957.64526367188ms`

not sure why there is delay to get the `receipt`?
### Versions 
* web3.js: web3@1.0.0-beta.55
* nodejs: v10.16.0
* browser: google chrome
* ethereum node: volta chain

**Comment by nivida** [comment]
Configuring of the transaction confirmation workflow will fix your issue ([transactionConfirmationBlocks](https://web3js.readthedocs.io/en/1.0/web3.html#transactionconfirmationblocks)).
