### ISSUE TITLE
Web3.js fails to make calls with SOCKS5 proxy

### ISSUE THREAD

**Issue by tsujp** [ethereum/web3.js#2946]
### Description

I am trying to use web3 over a SOCKS5 proxy, it fails at URL resolution.

#### Expected behavior

That calling an `web3.eth.Contract`'s method returns data.

#### Actual behavior

The result of `node test.js` is: `Error: Connection refused or URL couldn't be resolved: http://127.0.0.1:9999`

#### Steps to reproduce the behavior

Use any boilerplate web3.js code with a contract ABI and call a method on that contract over a SOCKS5 proxy where the host is running a geth instance. Curling such an instance works, e.g.

```bash
~ $ curl --socks5-hostname localhost:9999 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://localhost:7007
{"jsonrpc":"2.0","id":67,"result":"Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9"}
```

however running web3 over the same SOCKS5 proxy does not.

#### Error Logs 

None. Only the `actual behaviour` section.

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: v11.11.0
* ethereum node: Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9

**Comment by nivida** [comment]
Duplication of: https://github.com/ethereum/web3.js/issues/887
