### ISSUE TITLE
[web3-eth-miner package] TypeError: Miner is not a constructor

### ISSUE THREAD

**Issue by jack75015** [ethereum/web3.js#2948]
### Description 

I'm trying to call mining method with web3-eth-miner

#### Steps to reproduce the behavior
```
var Miner = require("web3-eth-miner");
const options = {
        defaultAccount: "0x78dB3e2129D58685444989dD9682DDDC70dd3C82",
        defaultBlock: 'latest',
        defaultGas: 1,
        defaultGasPrice: 0,
        transactionBlockTimeout: 50,
        transactionConfirmationBlocks: 24,
        transactionPollingTimeout: 480,
      }
const miner = new Miner("http://127.0.0.1:9545", null,options);
```

#### Error Logs 

```
const miner = new Miner("http://127.0.0.1:9545", null,options);
              ^
TypeError: Miner is not a constructor
```

### Versions 
* "web3": "2.0.0-alpha"
* "web3-eth-miner": "2.0.0-alpha"
* nodejs: 8.11.1
* browser: Chrome
* ethereum node: Geth Punisher (v1.8.27)

**Comment by nivida** [comment]
The require statement isn't correct. I've kept the possibility open to expose more than one class or method. This means you have to import it like this: 
``var Miner = require("web3-eth-miner").Miner;`` (ES6: ``import {Miner} from 'web3-eth-miner';``).

**Comment by jack75015** [comment]
Alright! Thanks for your quick answer :)
