### ISSUE TITLE
Clarification on givenProvider

### ISSUE THREAD

**Issue by thecircleoflifefree** [ethereum/web3.js#2949]
From the following link: https://web3js.readthedocs.io/en/1.0/web3.html#givenprovider

"When using web3.js in an Ethereum compatible browser, it will set with the current native provider by that browser. Will return the given provider by the (browser) environment, otherwise null."

Do you have a list of Ethereum compatible browsers? What is considered an Ethereum compatible browser? How can I get one for a Red Hat machine.

**Comment by nivida** [comment]
The [ProviderDetector](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/detectors/ProviderDetector.js) does detect the current given provider if Metamask, Mist or another browser/extension is used. The EIP-1193 will define the "Ethereum compatible browsers" but is currently not implemented in the detector and will be added asap.
