### ISSUE TITLE
missing removing of the listeners on a timeout (WebsocketProvider)

### ISSUE THREAD

**Issue by jbpitts** [ethereum/web3.js#2953]
### Description 
If you are calling getBlock then In WebsocketProvider.js function sendPayload, two listeners are added to emitter as execute once, one for the 'error' and one for id. Only one will get called. However both are added to listeners array. If no errors happen over time (many hours) the error queue can get very large.

#### Expected behavior
remove uncalled listener in resolve or reject respectively or don't do once.

#### Actual behavior
Memory keeps growing

#### Steps to reproduce the behavior
Call this.web3.eth.getBlock for new blocks

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: 10.15.0

**Comment by nivida** [comment]
Thanks for opening this issue! 
The ``error`` listener will get removed on the response of the connected node as you can see on [line 237](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/providers/WebsocketProvider.js#L237) in the [WebsocketProvider](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/providers/WebsocketProvider.js). This error listener will also be removed if ``connection.send`` failed, ``readyState`` is not open, or when the connection is finally established and the ``sendPayload`` method gets called again. The only missing ``removeListener`` calls for the error and id event listener are on [line 222](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-providers/src/providers/WebsocketProvider.js#L222). The event emitter error queue can only grow if a lot of requests are done on the same time or if some requests do not response. I will add the missing ``removeListener`` calls for the timeout case I've mentioned above asap.

**Comment by jbpitts** [comment]
Looks like there already some fixes for this in 2.0.0, I was using 1.0.0-beta55. Will try out 2.0.0-alpha in code.
