### ISSUE TITLE
Empty outputs array given

### ISSUE THREAD

**Issue by TamirTian** [ethereum/web3.js#2956]
### Description 
I got a error ` Empty outputs array given` when the log is `emptyNoneIndexParams inputs` and `0x data` 

but i mean that the 0x of `data` can be interpreted as null

#### Expected behavior
```js
const inputs = [
  { 'indexed': true, 'name': 'from', 'type': 'address' },
  { 'indexed': true, 'name': 'to', 'type': 'address' },
  { 'indexed': true, 'name': 'tokenId', 'type': 'uint256' }
]

const topics = [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x000000000000000000000000b1a25d6e37ad12579801ebb6787636fd63ba87cc",
        "0x0000000000000000000000000000000000000000000000000000000001315411"
]

const data = "0x"
const { from, to, tokenId } = web3.eth.abi.decodeLog(inputs, data, topics)
```
should return a result

#### Actual behavior
I got an error, it goes into this logic

https://github.com/ethereum/web3.js/blob/04bbf4a40e470e94b71ea2f1719815e7a4fbb5c3/packages/web3-eth-abi/src/AbiCoder.js#L232

### Versions 
* web3.js: a few
* nodejs: any
* browser: any
* ethereum node: any

**Comment by nivida** [comment]
Thanks for the question! The data property should be empty if no non-indexed properties are existing. 

> [data: DATA - contains the non-indexed arguments of the log.](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges)
