### ISSUE TITLE
getTransactionCount() is returning a bigNumber 

### ISSUE THREAD

**Issue by nickjuntilla** [ethereum/web3.js#2957]
### Description 

getTransactionCount appears to be returning something like BigNumber { _hex: '0xf1' } now instead of a number or string. This is breaking lots of code.

#### Expected behavior
My old code expected it to return a plain number like 1 or 2.

#### Actual behavior
Calling getTransactionCount() returns something like BigNumber { _hex: '0xf1' }. I can't find any documentation for this change. It says it's supposed to be a number here:

https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransactioncount

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: v8.15.0

**Comment by OFRBG** [comment]
Related to #2615
