### ISSUE TITLE
Your document link on this page, points to "Page not Found"

### ISSUE THREAD

**Issue by prographo** [ethereum/web3.js#2967]

**Comment by prographo** [comment]
<img width="874" alt="Screen Shot 2019-07-23 at 16 41 49" src="https://user-images.githubusercontent.com/11575008/61726035-db5cb200-ad68-11e9-9276-f715177a3c4b.png">
<img width="870" alt="Screen Shot 2019-07-23 at 16 41 39" src="https://user-images.githubusercontent.com/11575008/61726042-df88cf80-ad68-11e9-8314-a63a22e23915.png">

**Comment by Skyge** [comment]
Yeah, I also find this. Hope it can be fixed soon.

**Comment by Skyge** [comment]
So when will we fix it? it is a little urgent, this has affected normal access.

**Comment by spalladino** [comment]
It seems to have been fixed on https://github.com/ethereum/web3.js/commit/43e64cb930b4859821caa57b5efee308ee0d3669

**Comment by nivida** [comment]
@spalladino Yep the URLs are update.
