### ISSUE TITLE
sendSignedTransaction promise never resolves when submitting signed transaction

### ISSUE THREAD

**Issue by HM999** [ethereum/web3.js#2968]
I'm not sure if this is a web3 thing or a ganache thing.

I sign a transaction locally to make a method call on a contract that will change the state, I call sendSignedTransaction with the signed transaction, in the ganache log I see the transaction processed, later I do a read only call to check the contract state, and indeed it has been updated. However the promise of sendSignedTransaction never resolves.

I include code below, incase it helps or perhaps I make stupid mistake.

Version: web3@1.0.0-beta.55
Provider: Ganache

```
  const txMethodCall = TEST.methods.write( "3", "2" );
  const chainId = await web3.eth.net.getId();
  const privateKey = '0x9990a0ef0c3ca76baf4040ab9c452dc8a597767668ee2d7fff680b'
  const account = await web3.eth.accounts.privateKeyToAccount(privateKey);
  const nonce = await web3.eth.getTransactionCount( account.address )
  encoded = await txMethodCall.encodeABI()
  var txObject = {
    to : address,
    from: account.address,
    data : encoded,
    nonce: nonce,
    gasPrice: web3.utils.toWei('20', 'gwei'),
    gasLimit: 100000,
    value: 0,
    chainId: chainId,
  }
  const signed = await web3.eth.accounts.signTransaction(txObject, privateKey);
  console.log( "GETS HERE" );
  const tx = await web3.eth.sendSignedTransaction(signed.rawTransaction);
  console.log("NEVER GETS HERE");
```
Ganache accepts and processes transaction:

```
eth_blockNumber
eth_blockNumber
eth_accounts
eth_estimateGas
net_version
eth_getTransactionCount
eth_blockNumber
eth_sendRawTransaction

  Transaction: 0xdc108cde0ff08d3d28455a831da1d2e180098ecd1906477558b8d4a1c6d86604
  Gas usage: 28200
  Block Number: 1468
  Block Time: Tue Jul 23 2019 22:22:08 GMT+0100 (British Summer Time)

eth_subscribe
eth_blockNumber
eth_getBlockByNumber
eth_blockNumber
eth_call
eth_blockNumber
eth_blockNumber
```

**Comment by HM999** [comment]
I installed an older version of web3, and everything worked as expected.

web3@1.0.0-beta.34

That kind of points to the issue being with the newer version of web3.

**Comment by fukaoi** [comment]
I too have the same issue.

```
  web3.eth.sendSignedTransaction(tx.rawTransaction).on('receipt', console.log);
```
Do  not call receipt event.

* web3@1.2.0

**Comment by levino** [comment]
Should be working with `web3@^1`. Please confirm.

**Comment by nivida** [comment]
@Levino Yes, version 1.x of web3.js should be preferred.

Version 2.0.0-alpha (later beta.55) does provide the possibility to [configure](https://web3js.readthedocs.io/en/v2.0.0-alpha/web3.html#options) the transaction confirmation workflow. The workaround if auto mine is activated in ganache is described in issue #2940.

**Comment by HM999** [comment]
Are you saying use web3@1.0.0-beta.37? (https://github.com/ethereum/web3.js/releases)

**Comment by levino** [comment]
Just remove web3 and run `npm i web3@^1`. Version `1.2.0` is the latest stable release.

**Comment by HM999** [comment]
k, thx

**Comment by levino** [comment]
I think we should give @HM999 time to confirm the fix, @nivida before closing this issue.

**Comment by HM999** [comment]
@Levino it's all working if I use as you suggest, many thx.
