### ISSUE TITLE
Multiple instances of web3 object

### ISSUE THREAD

**Issue by asinyagin** [ethereum/web3.js#297]
Hey,

I want to work with 2 web3 providers at the same time. As I see, web3 is not supposed to be used with multiple instances. Can you help me with some workaround for it?

**Comment by d11e9** [comment]
:+1: yeah I don't like to current global approach either. global == bad

**Comment by aakilfernandes** [comment]
+1. Working on a testchain with an oracle on the mainchain, this would be super useful

**Comment by debris** [comment]
:+1:

**Comment by d11e9** [comment]
:+1:

**Comment by emprisupriatna** [comment]
I looking for the right etherwallet address

**Comment by Adyfamba** [comment]
Support web3
