### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by pizzarob** [ethereum/web3.js#2970]
Getting a 404 from the documentation link https://web3js.readthedocs.io/en/1.0/

**Comment by nivida** [comment]
https://web3js.readthedocs.io/

**Comment by pizzarob** [comment]
Cool thanks. The README.md still points to the broken link.

**Comment by abitrolly** [comment]
And wiki link needs to be fixed https://github.com/ethereum/wiki/wiki/JavaScript-API#web3-javascript-app-api-for-02xx
