### ISSUE TITLE
[META] Further 1.x development

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2972]
As far as I understand the truffle team will take over the 1.x development from now on. How is this going to be managed? Is truffle going to fork `web3`? Who has write access to `web3` at npmjs? I do not think that truffle should have access as well as @nivida and others. So possibly one should find a new name like `@truffle/web3`? Could someone please outline the plan and also create a new repo asap to continue work on `1.x`? Tagging @iurimatias @gnidan @alcuadrado

**Comment by nivida** [comment]
@Levino 

> How is this going to be managed?

The issue will get labeled with the correct version and topic label (bug, types etc.) and can be moved by the mentioned contributors to the related project column here on GitHub.

> Is truffle going to fork web3?

We will all work here together in this repository.

> Who has write access to web3 at npmjs?

I will publish the packages on npm.


Resource: https://medium.com/@samuel_91690/1-0-release-web3-js-ddd23d3c8f62
