### ISSUE TITLE
Error installing web3.js on Windows

### ISSUE THREAD

**Issue by ElTotemRebelde** [ethereum/web3.js#2973]
I get the error in the pic when i try to install web3.js on windows. Can anyone help me to fix it?

![Captura_editada](https://user-images.githubusercontent.com/53355064/61983328-3cea7e00-b000-11e9-850b-192139242f09.PNG)

**Comment by michaelsbradleyjr** [comment]
For a workaround see: https://github.com/ethereum/web3.js/issues/2971#issuecomment-515700763.

**Comment by ElTotemRebelde** [comment]
Thank you! It worked
