### ISSUE TITLE
web3 0.20.7 constrains the provider to use a numeric RPC ID, which is not the JSON RPC spec

### ISSUE THREAD

**Issue by moodysalem** [ethereum/web3.js#2974]
### Description
web3 0.20.7 constrains the provider to use a numeric RPC ID, which is not the JSON RPC spec

#### Expected behavior
Check it's a number or a string

#### Actual behavior
Checks it's a number

#### Steps to reproduce the behavior
Use a provider that uses string ids, get error invalid JSON

#### Error Logs 
N/a

### Versions 
* web3.js: 0.20.7

**Comment by moodysalem** [comment]
Link to the relevant line
https://github.com/ethereum/web3.js/blob/804282da2d595f1a74ba7aa9a0eada70a9e05fa2/lib/web3/jsonrpc.js#L66

**Comment by nivida** [comment]
0.20.7 was the last maintenance patch as mentioned in the release announcement of 1.0-beta.38. Please update to the latest version of web3.js.

**Comment by moodysalem** [comment]
Ok can you deprecate versions that are no longer maintained to encourage people to upgrade? Also upgrading is a significant amount of work and most existing dApps aren’t going to bother
