### ISSUE TITLE
uint256 max value error

### ISSUE THREAD

**Issue by techkrtk** [ethereum/web3.js#2977]
I am trying to encode a function call with uint256 as one of the parameters. I want to pass the max value of the uint256 as a parameter. But web3js is throwing the following error. I am using web3js 1.0.0-beta.36 version.

**(node:7088) UnhandledPromiseRejectionWarning: Error: invalid number value (arg="value", coderType="uint256", value=1.157920892373162e+77)**

**Comment by nivida** [comment]
Does this error still occur with the latest version of web3.js?

**Comment by nivida** [comment]
Closed because of the inactivity of the creator of the issue.
