### ISSUE TITLE
toHex gives unexpected behavior with numeric strings

### ISSUE THREAD

**Issue by drcode** [ethereum/web3.js#298]
```
> web3.toHex('111');
'0x6f' 
> web3.toHex('foo');
'0x666f6f'
```

This is very confusing.

**Comment by tcoulter** [comment]
Bump. Just ran into this with one of my contracts where I'm using a Solidity `byte32` type to store text data.

Let's say I want to store the string "111111111111" - I get an error:

```
truffle(development)> web3.toUtf8(web3.toHex("111111111111"))
Error: Invalid byte index
  at Error (native)
  ...
```

But if I stick an 'a' on the front, everthing's fine:
```
truffle(development)> web3.toUtf8(web3.toHex("a111111111111"))
'a111111111111'
```

The rabbit hole goes deeper if, for instance, I want to store a floating point value as a string within that `bytes32` storage variable -- let's say a string representation of an app's version number. I can't do it with the the current version of `toHex()`/`bytes32` serialization using `toHex`:

```
truffle(development)> web3.toUtf8(web3.toHex("1.4"))
'\u0001ffffffffff'
truffle(development)> web3.toUtf8(web3.toHex("1.4a"))
'1.4a'
```

Would love your thoughts on how to fix this.

**Comment by frozeman** [comment]
Why using the toHex at all here, you can also use more explicit conversion methods. toHex is a catch all which tries to autodetect the input.
