### ISSUE TITLE
The old doc(1.0) page its broken

### ISSUE THREAD

**Issue by rotcivegaf** [ethereum/web3.js#2987]
### Description

In this moment the old documentation page is broken [doc 1.0](https://web3js.readthedocs.io/en/1.0/)

#### Expected behavior

Create the page or maybe redirect to new doc page

#### Actual behavior

the page shows `This page does not exist yet`

#### Steps to reproduce the behavior

Enter to [doc 1.0](https://web3js.readthedocs.io/en/1.0/)

**Comment by nivida** [comment]
The correct URL is: https://web3js.readthedocs.io/
