### ISSUE TITLE
Stop putting applications into web3!

### ISSUE THREAD

**Issue by nmushegian** [ethereum/web3.js#299]
This discussion needs to spill into this repo:  https://github.com/ethereum/go-ethereum/issues/1403

In particular:  https://github.com/ethereum/web3.js/commit/3373b8f660c2cbd47d8f944c76faf6a36709c868

This is crossing the line IMO. The IBAN interface / contract is being treated as first-class for no reason. Very alarming.

**Comment by frozeman** [comment]
Can you elaborate?

**Comment by nmushegian** [comment]
Why it's bad to add first-class features like this or why IBAN specifically is bad? The second is ultimately a design opinion, the first is a core ethereum principle!

**Comment by nmushegian** [comment]
"We Have No Features: as a corollary to generalization, we often refuse to build in even very common high-level use cases as intrinsic parts of the protocol, with the understanding that if people really want to do it they can always create a sub-protocol (eg. ether-backed subcurrency, bitcoin/litecoin/dogecoin sidechain, etc) inside of a contract. An example of this is the lack of a Bitcoin-like "locktime" feature in Ethereum, as such a feature can be simulated via a protocol where users send "signed data packets" and those data packets can be fed into a specialized contract that processes them and performs some corresponding function if the data packet is in some contract-specific sense valid."

https://github.com/ethereum/wiki/wiki/Design-Rationale

**Comment by nmushegian** [comment]
Building it into the default wrapper is nearly as bad as putting it into the protocol level because of how it directs new developer's attention.

If individual devs get input about which registries "just happen" to be in web3, I want to be one of those devs!

**Comment by nmushegian** [comment]
Now this:  https://github.com/ethereum/wiki/wiki/Standardized_Contract_APIs

If you prefer, I'll give up on neutrality and dump our own standards to everywhere we have write access whenever possible, i.e. compete for mindshare by shouting
