### ISSUE TITLE
web3.js v1.2.0 Documentation web3.*.net Example Mistake

### ISSUE THREAD

**Issue by mustafatalha** [ethereum/web3.js#3001]
### Description
https://web3js.readthedocs.io/en/v1.2.0/web3-net.html

isListening and getPeerCount examples have mistakes.

#### Expected behavior
web3.eth.net.isListening()
.then(console.log);
> true

web3.eth.net.getPeerCount()
.then(console.log);
> 25

#### Actual behavior
web3.eth.isListening()
.then(console.log);
>TypeError: web3.eth.getListening is not a function

web3.eth.getPeerCount()
.then(console.log);
> TypeError: web3.eth.getPeerCount is not a function

#### Steps to solve the behavior
Just add **net** to example.

web3.eth.**net**.isListening()
.then(console.log);

web3.eth.**net**.getPeerCount()
.then(console.log);

**Comment by plusspeed** [comment]
This issue still happens in https://web3js.readthedocs.io/en/v1.2.1/web3-net.html
