### ISSUE TITLE
I get error when I try to install on windows machine

### ISSUE THREAD

**Issue by startgeek** [ethereum/web3.js#3002]
when I try to install v 1.x.x of web3 via npm it has this error
npm ERR! web3-providers-ws@1.2.0 preinstall: `rm -rf node_modules/websocket/.git`

and I use powershell as terminal I'm 

it should be able to install its a beta version not alpha 

#### Error Logs 

'rm' is not recognized as an internal or external command,
operable program or batch file.

> scrypt@6.0.3 preinstall C:\Users\wish\Documents\work\tripleS\node_modules\scrypt
> node node-scrypt-preinstall.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3-providers-ws@1.2.0 preinstall: `rm -rf node_modules/websocket/.git`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3-providers-ws@1.2.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

### Versions 
* web3.js: 1.x.x
* nodejs: 12
* browser: dont have any
* ethereum node: docker geth

ps: I believe that its purely caused because rm command is not ok with power shell or at least its not ok with flags and I tested command rm without flag works but with -rf :

 rm -rf example
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf example
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by nivida** [comment]
This got fixed and will be released with [v1.2.1](https://github.com/ethereum/web3.js/blob/1.x/CHANGELOG.md).
