### ISSUE TITLE
Browser-side Importing issue.

### ISSUE THREAD

**Issue by jeffscottward** [ethereum/web3.js#302]
I'm using webpack and it gives me an error when not explictly requiring `net` in this way inside of IPCProvider.js
`require('./net')`

This was the error it was giving me.

```
ERROR in ./~/web3/lib/web3/ipcprovider.js
Module not found: Error: Cannot resolve module 'net' in /Users/jeffscottward/Documents/Development/Projects/ConsenSys/Balanc3/frontend/node_modules/web3/lib/web3
 @ ./~/web3/lib/web3/ipcprovider.js 36:17-31
```

Its works now, however I do get this warning now.

```
WARNING in ./~/web3/lib/web3/httpprovider.js
Critical dependencies:
27:84-91 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/web3/lib/web3/httpprovider.js 27:84-91
```

**Comment by frozeman** [comment]
This should not be the case anymore.
I would love to switch to web pack, but i have not yet played with it, fi you can provide a PR for the 1.0 branch would be awesome.
