### ISSUE TITLE
cant connect metamask via nodejs & web3

### ISSUE THREAD

**Issue by parin13** [ethereum/web3.js#3022]
I want to access the addresses from the metamask so that my backend doesn't need to deal with handling private keys. Here is the snippet I have enclosed, Can someone help me with it.

```
const Web3 =  require('web3')  
const window = require('window');
const web3 = new Web3(window.Web3.currentProvider)
```
> The error says TypeError: Cannot read property 'currentProvider' of undefined

**Comment by nivida** [comment]
Metamask just exists in the browser.:)
