### ISSUE TITLE
Fire an event when a subscription is confirmed

### ISSUE THREAD

**Issue by GrandChaman** [ethereum/web3.js#3027]
# Description
When I subscribe to a contract's event and then immediately fires up that event, the event listener doesn't get called every time.
## Expected behavior
I expect a listener to be ready as soon as the call for subscription is done
## Version
web3 1.2.1

**Comment by nivida** [comment]
Could be related to https://github.com/ethereum/web3.js/issues/2881 @gnidan

**Comment by nivida** [comment]
Thanks for opening this issue! Could you please provide an example to reproduce this issue? The possibility is here that the event got fired before the log subscription got established.

**Comment by nivida** [comment]
Closed because of missing additional information and sounds like a timing issue. (The WebsocketProvider was probably still connecting and the Contract event got triggered in the mean time)
