### ISSUE TITLE
npm install succeeds on latest version of Node on Windows but does show errors

### ISSUE THREAD

**Issue by devedse** [ethereum/web3.js#3033]
### Description

When I try to create a solution and install web3js using the following command, everything seems to succeed but when you check the logs there's quite some errors when the node-gyp rebuild is happening:

```
npm install web3 --save-dev
```

#### Expected behavior

No errors when doing an NPM install.

#### Actual behavior

I've created a package.json with the following content:

```
{
  "name": "nodegyperror",
  "version": "0.1.0",
  "private": true,
  "scripts": {},
  "dependencies": {},
  "devDependencies": {
    "web3": "^1.2.1"
  }
}
```

Running npm install shows the following red text:
![image](https://user-images.githubusercontent.com/2350015/63164170-e9c88180-c027-11e9-9fb3-5dafd5f6e5e2.png)

The command still returns succeeded though.

#### Steps to reproduce the behavior

I created a repository with builds to reproduce the issue:
https://github.com/devedse/NodeGypBufferUtilErrors

Windows build and linux builds can be found in the Readme.md on the main page of the repository

#### Error Logs 

Windows build (Errors shown):
https://ci.appveyor.com/project/devedse/nodegypbufferutilerrors

Linux build (No errors shown):
https://travis-ci.org/devedse/NodeGypBufferUtilErrors

### Versions 
* web3.js: ^1.2.1
* nodejs: v12.8.1
* NPM: v6.10.2
* browser: N/A
* ethereum node: N/A

**Comment by devedse** [comment]
@nivida , I'm not sure if it's related, but I also see that if I try to install web3@next (to be able to make use of TypeScript bindings) in my current repository it also fails on some Node-gyp related things:

![image](https://user-images.githubusercontent.com/2350015/63166067-93f6d800-c02d-11e9-9545-c67f5b071f92.png)

Shall I make a seperate issue for this or leave it here?

**Comment by michaelsbradleyjr** [comment]
@devedse I believe you can solve this problem by installing the [`windows-build-tools`](https://www.npmjs.com/package/windows-build-tools) package. Note that it should be installed from a cmd shell run as administrator, but there are [instructions for installing as a non-administrator](https://www.npmjs.com/package/windows-build-tools#installing-as-a-non-administrator) if that's what you need to do.

With the build tools installed, I have no problems installing `web3@1.2.1` on Windows 10.

**Comment by devedse** [comment]
@michaelsbradleyjr , I'll try this out and will let you know if this fixes the issues.

**Comment by nivida** [comment]
Duplication of https://github.com/ethereum/web3.js/issues/3151.
