### ISSUE TITLE
Moving Travis checks to Azure Pipelines

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3034]
### Description 

Example from Embark:
https://github.com/embark-framework/embark/blob/master/azure-pipelines.yml

**Comment by michaelsbradleyjr** [comment]
Per the linked example of an `azure-pipelines.yml`, there is support for running Linux, macOS, and Windows builds across multiple versions of Node.js, which makes AzP pretty attractive. The free tier for open source projects has been serving the Embark Framework well for many months now.

See: https://dev.azure.com/embark-framework/Embark/_build?definitionId=1

**Comment by ukstv** [comment]
Why, if you could have it here on GitHub via GitHub Actions? Also, it is quite similar in syntax to Azure DevOps.

**Comment by holgerd77** [comment]
Will close in favor of #3393
