### ISSUE TITLE
expose getheader functions

### ISSUE THREAD

**Issue by sidhujag** [ethereum/web3.js#3038]
Geth web3ext supports getting headers by number and hash, is it possible for web3 to hook into it for providers that do have those rpc functions? I would love to be able to get headers via a light client without forcing my light nodes from doing network requests on blocks it already has when I only need the info from the header.

**Comment by nivida** [comment]
Could please update your issue to be align with the issue template we provide? We are forced otherwise to close this issue.

**Comment by nivida** [comment]
Closed this issue because of the inactivity of the creator of it. Feel free to open a new issue that is aligned with the issue template we provide.
