### ISSUE TITLE
request: Provide way to determine if account is locked/unlocked

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#304]
Need to provide end user with message to unlock their account if its locked

**Comment by 0mkara** [comment]
Hi, is this feature available yet ?

**Comment by frozeman** [comment]
This error should be propagated by now

**Comment by Eithcowich** [comment]
Any update on this? I need to find out if an account is locked programmatically from nodejs. If there's any way to unlock the account synchronously even better.
