### ISSUE TITLE
web3 in react-native :  Cannot read property 'getReader'

### ISSUE THREAD

**Issue by callmejm** [ethereum/web3.js#3044]
### Version
`"web3": "^1.2.1"`
`"react-native": "0.59.10"`

From [set-up tutorial](https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766) and https://github.com/ethereum/web3.js/issues/1022 , I was able to install `web3` in `react-native`, however I got this error : 

### Error

`Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'getReader' of undefined
TypeError: Cannot read property 'getReader' of undefined
    at new exports.IncomingMessage (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:222317:34)
    at module.exports.ClientRequest._connect (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:222201:22)
    at blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:222115:14
    at tryCallOne (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:45372:14)
    at blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:45473:17
    at blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:46351:21
    at _callTimer (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:46240:9)
    at _callImmediatesPass (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:46276:9)
    at Object.callImmediates (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:46495:14)
    at MessageQueue.__callImmediates (blob:http://localhost:8081/4f48abd1-1bd3-445a-bdbc-3cdeca3a37a2:16572:16)`

error occur when i doing promise method like `web3.eth.getTransactionCount` or `web3.eth.getBlock('latest')`.

### Try
I tried `console.log(web3.version)` , no problem at all

**Comment by EnettyTech** [comment]
Try install old version web3. `1.0.0-beta.33` worked for me.

**Comment by callmejm** [comment]
> Try install old version web3. `1.0.0-beta.33` worked for me.

I haven't try, but what is the different between `1.2.1` and  `1.0.0-beta.33`

**Comment by guilhermepatriarca** [comment]
I has 1.2.1 version and downgrade to old version web3 1.0.0-beta.51 and worked for me.

**Comment by callmejm** [comment]
> I has 1.2.1 version and downgrade to old version web3 1.0.0-beta.51 and worked for me.

look like this version are missing some module right ? like https://www.npmjs.com/package/es5-ext , but after i install other error come out, can you describe how you install from `1.2.1` to ` 1.0.0-beta.51` ?

**Comment by guilhermepatriarca** [comment]
- pakage.json and change "web3": "^1.2.1" to "1.0.0-beta.51" our other (delete ^)
-  Delete node_modules
- Delete yarn.lock our package-lock.json
- yarn install our npm install

**Comment by youngkidwarrior** [comment]
Does this still require a downgrade? I want to use hd-wallet-provider in my RN app, but that depends on 1.2.1 version of web3.

**Comment by nivida** [comment]
@youngkidwarrior The Truffle hd-wallet-provider should work with the latest version of web3.js. Feel free to open an issue in the Truffle repository if this isn't the case and reference this issue here.

**Comment by youngkidwarrior** [comment]
@nivida The issue im facing now is getting react native to run on the latest version of Web3

**Comment by ryanio** [comment]
@youngkidwarrior can you share some more information about what errors you're getting with the latest version of web3.js? thanks!
