### ISSUE TITLE
web3 on react-native : Error: Returned error: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by callmejm** [ethereum/web3.js#3046]
using `web3@1.0.0-beta.33` and `react-native@0.59.10`, because latest `web3` have install issue on `react-native`, after deep research `1.0.0-beta.33` is suitable on `react-native`

    const web3 = new Web3("https://mainnet.infura.io:443"); 
    var count = await web3.eth.getTransactionCount(this.state.selectedWallet.publicaddress);
    var contractdata = new web3.eth.Contract(abiArray, SensitiveInfo.tokencontract);
    var rawTransaction = {
        "from": this.state.selectedWallet.publicaddress,
        "nonce": count,
        "gasPrice": 4500000000,
        "gas": web3.utils.toHex("519990"),
        "gasLimit":web3.utils.toHex("519990"),
        "to": SensitiveInfo.tokencontract,
        "value": "0x0",
        "data": contractdata.methods.transfer(this.state.recipientaddress,web3.utils.toWei('1', 'ether')).encodeABI(),
        "chainId": 0x01
    };
    var privKey = new Buffer(this.state.selectedWallet.privatekey,'hex');
    var tx = new Tx(rawTransaction);
    tx.sign(privKey);
    var serializedTx = tx.serialize();
    web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'), (err, hash) =>{
      if (!err) //SUCCESS
          console.log(hash);
      else
          console.log(err);
    });    
  }

### Note
 1. the same code base use in web are work, but `web3@1.2.1`
 2. I can very confirmed the **from** address have enough token and gas
 3. have do research said change all hex to number, like `gas` , `gasLimit`, `value` and `chainId`

**Comment by stefdelec** [comment]
@callmejm did you make web3 work on react-native? The only solution I have found is https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766

but `node-libs-browser`. Any solution?
