### ISSUE TITLE
Callbacks after send() are not working since 1.0.0-beta.49

### ISSUE THREAD

**Issue by iuwqyir** [ethereum/web3.js#3048]
### Description 
Since 1.0.0-beta.49 it is not possible to use `once()` to set a callback function after calling a smart contract function using `send()`.

For example:
`myContract.methods.set(10).send().once('receipt', (receipt) => {console.log(receipt)});`

#### Expected behavior
The code above should log the receipt to console after the transaction is completed.

#### Actual behavior

Callback function is not called and receipt is not logged.

### Versions 
* web3.js: 1.0.0-beta.49 and above
* nodejs: 10.15.3

**Comment by nivida** [comment]
Tested it with 2.0 which is using the beta.49 codebase and it works: 
``` javascript
var Web3 = require('web3');

const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:7545'), null);
web3.eth.sendTransaction({
 from: '0x6d6dC708643A2782bE27191E2ABCae7E1B0cA38B',
 to: '0x6FA59C2C8EAaCC1f8875794f2DAe145Bb32Bd9B1',
 value: 100,
 gas: 21000
}).once('confirmation', () => {console.log('CONFIRMED');})
.then(console.log)
.catch(console.log);
```
