### ISSUE TITLE
version 1.2.0 contract.methods.transfer is not a function [SOLVED]

### ISSUE THREAD

**Issue by Tolga-FNT** [ethereum/web3.js#3050]
I am trying to send some custom made tokens using this library, but it seems that the example code I found on stackoverflow isn't working anymore. I am using version 1.2.0, but I can't find examples or any solid documentation with some example codes anywhere.

#### Expected behavior

Trying to send tokens using this library.

```
const contract = new this.web3.eth.Contract(minABI, tokenAddress);
        let tx = await contract.methods.transfer(dto.toAddress, 10).send({from:crypto.address, gas:0x00, gasPrice:0x00});
        console.log(tx);
```

#### Actual behavior

`contract.methods.transfer is not a function`

#### Error Logs 
```
TypeError: contract.methods.transfer is not a function
    at TransactionService.pushETHTokenTransaction (/Users/omega/Development/crypto-provider-api/dist/api/transaction/transaction.service.js:99:41)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async /Users/omega/Development/crypto-provider-api/node_modules/@nestjs/core/router/router-execution-context.js:44:28
    at async /Users/omega/Development/crypto-provider-api/node_modules/@nestjs/core/router/router-proxy.js:8:17

```

### Versions 
* web3.js: 1.2.0
* nodejs: v12.4.0
* browser:Chrome Version 76.0.3809.100 (Official Build) (64-bit)
* ethereum node: -

**Comment by Tolga-FNT** [comment]
It seems that transfer is the method that should exist in the ABI file. I didn't have it and included later on. My mistake..

**Comment by defaultUser3214** [comment]
I get the same error nevertheless the included ABI is correct and contains the requested function. Is there a bug in 1.2.0?

**Comment by defaultUser3214** [comment]
@Tolga-FNT How did you solve this problem? Which Solc version do you use?

**Comment by Tolga-FNT** [comment]
> @Tolga-FNT How did you solve this problem? Which Solc version do you use?

You should check your abi file. If there is no transfer method inside, then you get to see this error popping up. ;)

**Comment by defaultUser3214** [comment]
@Tolga-FNT There was a methods section in the ABI but I manually included the whole myContract.json and not only the ABI section in it.
