### ISSUE TITLE
Filtration for Events => getPastEvents() method is not working.

### ISSUE THREAD

**Issue by RudrikaFichadiya** [ethereum/web3.js#3052]
### Description 
I have contract Index parameters 'to' and 'from' INDEXED. 
Still I am not able to get filtered events only. getPasEvents() method returns all data without filtration. 
  -> I am working with WEB3 version 1.2.1. 
Example:
  Calling `contractInstance.getPastEvents()` should give filtered events only.

Example:
    Implemented code as following:
```
     var instance = new web3.eth.Contract(abi, address);
      instance.getPastEvents(
        "Transfer",
        {filter: {_recipient: '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98'}},
        { fromBlock: 8443359 , toBlock: "latest" },
        (errors, events) => {
             if (!errors) {
                console.log(events);
             }
            //console.log(errors);
         }
    );
```
### Versions 
* web3.js:
* nodejs:
* browser:
* ethereum node:

**Comment by nivida** [comment]
Thanks for opening this issue! Could you provide the ABI you are using?

**Comment by nivida** [comment]
Closed because of the inactivity of the creator of this issue. Feel free to create a new issue if this error still occurs.

**Comment by RudrikaFichadiya** [comment]
@nivida , Hello. It worked for me. There is a little confusion over there in use of filtration. Now it is in working condition. Thank you!

**Comment by chetangdoinfotech** [comment]
I am getting same result with or without filter.  here is my code - 	 try{
	 		console.log(" >>>>>> Console logs here <<<<<  ");
	 		await myinstance.getPastEvents('allEvents',  {
	 				filter:{orderID: [1,2,3,4]},
	 				fromBlock: 9668423,       
					toBlock: 'latest'
	    		},function(error,events){
	    			console.log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	 				console.log(error);
	 				console.log(events);
	 				console.log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	 		});
	 }catch(e){
			console.log("<<<< Error >>>>",e);	 
	 }
