### ISSUE TITLE
Contract events are not filtered by string type value

### ISSUE THREAD

**Issue by yzevm** [ethereum/web3.js#3053]
### Description 

- [x] Bug

#### Expected behavior

Calling `contract.events.MyEvent({filter: {a: "string"}})` should return an event with same `string` index.

#### Actual behavior

Calling `contract.events.MyEvent({filter: {a: "string"}})` returns `null`.

#### Steps to reproduce the behavior

Open the `repl.it` link and press `run` on the top https://repl.it/@egorzaremba/web3-contract-filter-event-by-string

Also, contract address is https://rinkeby.etherscan.io/address/0x8f044afc2202ea44790f0081ea964b02f05783bd#code

### Versions 
* web3.js: 2.0.0-alpha.1
* nodejs: 10.2.0
* ethereum node: infura

**Comment by nivida** [comment]
Thanks for opening this issue! I will check this closer asap.

**Comment by nivida** [comment]
Closed because dynamically allocated types as for example ``string`` can't be defined as an indexed event property. ([stackexchange discussion about](https://ethereum.stackexchange.com/questions/6840/indexed-event-with-string-not-getting-logged/7170#7170))

**Comment by nivida** [comment]
re-opened it: It will add the string to the ``data`` array and it creates a hash of it and adds the hash to the ``topics`` array.
