### ISSUE TITLE
web3 installation - npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by DineshSachdeva** [ethereum/web3.js#3054]
a- I am trying to install web3 in Windows / DOS.
b- I get the errors when I run "npm install web3" ( updated 1 package and audited 951972 packages in 70.992s, found 3 vulnerabilities (1 low, 2 high), run npm audit fix to fix them, or npm audit for details )
c- When I run "npm audit fix", I get the error
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
d- My npm and minimatch version is already 6.11.2.
Requesting help. Thanks.

**Comment by nivida** [comment]
This warning can be ignored because it's just a deprecation message.
