### ISSUE TITLE
web3.min.js: ReferenceError: regeneratorRuntime is not defined (v1.2.1)

### ISSUE THREAD

**Issue by kingjerod** [ethereum/web3.js#3058]
### Description 
Including dist/web3.min.js on a page causes error in console `ReferenceError: regeneratorRuntime is not defined`. This is the downloaded source from releases.

#### Expected behavior
There will be no errors when including the file.

#### Actual behavior
Error shows up in console `ReferenceError: regeneratorRuntime is not defined`. Web3 does not work.

#### Steps to reproduce the behavior
Create html file. Put this script tag in:
`<script type="text/javascript" src="web3.min.js"></script>`

#### Error Logs 
`ReferenceError: regeneratorRuntime is not defined`

#### Gists
None

### Versions 
* web3.js: 1.2.1
* browser: Firefox 68.0.2

Note: I do not get this error in 1.2.0

**Comment by nivida** [comment]
Thanks for opening this issue! Downloading of the published package from NPM and bundling it with webpack does work. I will update the dist file here on GitHub asap.

Edit: 
The error is coming from the buffer dependency.

**Comment by ItalyPaleAle** [comment]
I have this issue on 1.2.2 downloaded from NPM and bundled with webpack. I didn't have the issue with 1.2.1.

The error appears when web3.js receives a confirmation of a transaction.

Regression?
