### ISSUE TITLE
web3.isConnected() is always true for IPC connections.

### ISSUE THREAD

**Issue by cozylife** [ethereum/web3.js#306]
web3.isConnected() has issues. When connecting to an IPC node, it'll always return true, even if that node's IPC server isn't up and running. That causes issues with further calls failing with no easy way to check for a connection.

**Steps to reproduce**
1. Launch Geth without any parameters so that it uses the default IPC path. (I'm on Windows, so mine is \\.\pipe\geth.ipc)
2. Very quickly run a program with the following Web3 code. You'll see that it says it's connected before it even starts the IPC server.

```
web3.setProvider(new web3.providers.IpcProvider('\\\\.\\pipe\\geth.ipc', require('net')));
if (true === web3.isConnected()) {
    alert('It returned true.');
}
```

**Comment by cozylife** [comment]
Is anyone working on a fix for this issue?

**Comment by drupalnomad** [comment]
With Geth attach I get:
```
> web3.isConnected()
TypeError: 'isConnected' is not a function
    at isConnected (<anonymous>:-65555:-19)
    at <anonymous>:1:1
```

**Comment by frozeman** [comment]
yes the console, provider probably doesn't support this... @bas-vk should be added ;)

**Comment by frozeman** [comment]
@cozylife Yes its always true for the IPC, and thats an issue im working on, sadly there is no easy solution for this. Assume that in mist you're always connected, rather mist should show if the node crashes not the dapp itself.

**Comment by mjackson001** [comment]
also, for socket connections isConnected() always throws an error if there is no listener on the socket.  this makes it impossible to gracefully detect when there is no connection.

**Comment by frozeman** [comment]
The `web3.currentProvider` has a `on('end', func)` event, which can be listened to. The isConnected is currently discussed if we want to provide that in the future.
