### ISSUE TITLE
toHex returns wrong values if used in nuxt SSR

### ISSUE THREAD

**Issue by pertsev** [ethereum/web3.js#3063]
### Description 
`toHex` function returns wrong values if it was used during `nuxt` server side rendering.
See [this](https://github.com/peppersec/web3_toHex_bug/blob/master/pages/index.vue#L65) demo project to reproduce the issue. Deployed version is [here](https://peppersec.github.io/web3_toHex_bug/)

#### Expected behavior
```
const toX = Web3Utils.toHex(n1)
console.log('toX', toX)
// 0xfbe43c36a80e36d7c7c584d4f8f3759fb51f0d66065d8a227b688d12488c5d4
```

#### Actual behavior
```
const toX = Web3Utils.toHex(n1)
console.log('toX', toX)
// 0x2266626534336333366138306533366437633763353834643466386633373539666235316630643636303635643861323237623638386431323438386335643422
```

#### Steps to reproduce the behavior
1. `yarn` 
2. `yarn generate`
3. `cd dist`
4. `python -m SimpleHTTPServer 8088`
5. open up js console in localhost:8088 and notice that there are incorrect `toHex` results
```
n1 7120861356467848435263064379192047478074060781135320967663101236819528304084
toX 0x2266626534336333366138306533366437633763353834643466386633373539666235316630643636303635643861323237623638386431323438386335643422
```

if you do `yarn dev -o` you will see that `toHex` is working as expected

```
n1 7120861356467848435263064379192047478074060781135320967663101236819528304084
toX 0xfbe43c36a80e36d7c7c584d4f8f3759fb51f0d66065d8a227b688d12488c5d4
```

### Versions 
* web3.js: 1.2.1
* nodejs: 11
* browser: chrome

![image](https://user-images.githubusercontent.com/11399003/64740014-977e6180-d4fc-11e9-924a-950406b6e102.png)

**Comment by rstormsf** [comment]
@nivida
