### ISSUE TITLE
Null parameters to contracts should throw an error

### ISSUE THREAD

**Issue by danfinlay** [ethereum/web3.js#3065]
Today if you construct a token object using web3.js, and accidentally set the `to` parameter to `null`, you will find yourself sending tokens to the null address, `0x000...`.

To prevent that kind of *expensive mistake*, web3.js should throw a hard error if any contract parameters are not concretely set, and not default to any value.

## Sample code
```
const minABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}];

var tokenAddress = this.selectedCurrency.base_address;
var tokenContract = web3.eth.contract(minABI).at(tokenAddress);

let decimals = web3.toBigNumber(this.selectedCurrency.decimal_count);
let amount = web3.toBigNumber(this.depositAmount); // hundred tokens to send
let value = amount.times(web3.toBigNumber(10).pow(decimals));

// If `myAccountAddress` is null:
tokenContract.transfer(myAccountAddress, value, {from:myMetamaskAddress, gasPrice: self.fp}, 
function(err, txHash) {
  // Look! I sent my tokens into the abyss!
});
```

**Comment by nivida** [comment]
Thanks for opening this issue! But the last maintenance release for 0.20.x got published around a year ago. We recommend to update to version 1.0 of web3.

**Comment by Milan-Popich** [comment]
Agree with that, however if web3 is necessary to show the data than integrate it with the app.

**Comment by pomnt** [comment]
> Today if you construct a token object using web3.js, and accidentally set the `to` parameter to `null`, you will find yourself sending tokens to the null address, `0x000...`.
> 
> To prevent that kind of _expensive mistake_, web3.js should throw a hard error if any contract parameters are not concretely set, and not default to any value.
> 
> ## Sample code
> ```
> const minABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}];
> 
> var tokenAddress = this.selectedCurrency.base_address;
> var tokenContract = web3.eth.contract(minABI).at(tokenAddress);
> 
> let decimals = web3.toBigNumber(this.selectedCurrency.decimal_count);
> let amount = web3.toBigNumber(this.depositAmount); // hundred tokens to send
> let value = amount.times(web3.toBigNumber(10).pow(decimals));
> 
> // If `myAccountAddress` is null:
> tokenContract.transfer(myAccountAddress, value, {from:myMetamaskAddress, gasPrice: self.fp}, 
> function(err, txHash) {
>   // Look! I sent my tokens into the abyss!
> });
> ```

**Comment by HMMM116** [comment]
T

**Comment by matuhinal** [comment]
> Today if you construct a token object using web3.js, and accidentally set the `to` parameter to `null`, you will find yourself sending tokens to the null address, `0x000...`.
> 
> To prevent that kind of *expensive mistake*, web3.js should throw a hard error if any contract parameters are not concretely set, and not default to any value.
> 
> ## Sample code
> ```
> const minABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}];
> 
> var tokenAddress = this.selectedCurrency.base_address;
> var tokenContract = web3.eth.contract(minABI).at(tokenAddress);
> 
> let decimals = web3.toBigNumber(this.selectedCurrency.decimal_count);
> let amount = web3.toBigNumber(this.depositAmount); // hundred tokens to send
> let value = amount.times(web3.toBigNumber(10).pow(decimals));
> 
> // If `myAccountAddress` is null:
> tokenContract.transfer(myAccountAddress, value, {from:myMetamaskAddress, gasPrice: self.fp}, 
> function(err, txHash) {
>   // Look! I sent my tokens into the abyss!
> });
> ```

Open on contur
