### ISSUE TITLE
inputGetLogsFormatter doesn't return an options object.

### ISSUE THREAD

**Issue by toffick** [ethereum/web3.js#3066]
Hi. ``inputGetLogsFormatter`` doesn't return an options object.
https://github.com/ethereum/web3.js/blob/0.20.7/lib/web3/formatters.js#L122

### Versions 
* web3.js: 0.20.7

**Comment by nivida** [comment]
Thanks for opening this issue but the last maintenance patch for 0.20.x got released a year ago and we recommend to update to the latest version of 1.0.
