### ISSUE TITLE
sender account not recognized error when using "WrestlingInstance.registerAsAnOpponent({from: account1}) "

### ISSUE THREAD

**Issue by Jcwilli585** [ethereum/web3.js#3068]
I'm following the ethereum walkthrough at: https://hackernoon.com/ethereum-development-walkthrough-part-2-truffle-ganache-geth-and-mist-8d6320e12269

I got stuck at account0 = web3.eth.accounts[0]. The result would be "undefined". Also the result is undefined for Wrestling.deployed().then(inst => { WrestlingInstance = inst }).

The command "WrestlingInstance.wrestler1.call()" does return the first address.

I was able to set account0 using the lines:
var account0;

web3.eth.getAccounts().then(e => {account0 = e[0]})

Now when I enter "WrestlingInstance.registerAsAnOpponent({from: account1}) " I get the error:
sender account not recognized

I expect truffle to return that a transaction has occurred.

**Comment by nivida** [comment]
Thanks for opening this issue! Which version of web3.js are you using?

**Comment by nivida** [comment]
Closed because of the inactivity of the creator of this issue. Feel free to open a new issue and to provide all the required information.
