### ISSUE TITLE
Web3 js installation error

### ISSUE THREAD

**Issue by NithinTD** [ethereum/web3.js#3071]
I want to install webjs so I run the below command but it is showing an error on Ubuntu OS.      
    
>$ sudo npm install -g web3
    
    npm ERR! path git
    npm ERR! code ENOENT
    npm ERR! errno ENOENT
    npm ERR! syscall spawn git
    npm ERR! enoent Error while executing:
    npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
    npm ERR! enoent 
    npm ERR! enoent 
    npm ERR! enoent spawn git ENOENT
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/nithin/.npm/_logs/2019-09-18T09_41_14_857Z-debug.log

**Comment by chaitanyapotti** [comment]
@nivida I have the same issue
```
Could not install from "node_modules/web3-providers-ws/websocket@github:web3-js/WebSocket-Node#905deb4812572b344f5801f8c9ce8bb02799d82e" as it does not contain a package.json file.
```

**Comment by chaitanyapotti** [comment]
Works fine with yarn though.! weird

**Comment by RobertoC27** [comment]
i have the same issue, both with npm and yarn. on win10

**Comment by ssimunec** [comment]
@nivida 

I got similar issue as others, when trying to install web3 using npm i got:

> 14390 verbose node v10.16.3
> 14391 verbose npm  v6.11.2
> 14392 error code ENOENT
> 14393 error syscall spawn git
> 14394 error path git
> 14395 error errno ENOENT
> 14396 error enoent Error while executing:
> 14396 error enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
> 14396 error enoent
> 14396 error enoent
> 14396 error enoent spawn git ENOENT
> 14397 error enoent This is related to npm not being able to find a file.
> 14398 verbose exit [ 1, true ]

**Comment by nivida** [comment]
Thanks for opening this issue! We will remove the GitHub dependency as soon as possible. But be sure the required tools (e.g.: git) are installed on your PC and the permissions are defined correctly.

**Comment by Abdullah-sudo** [comment]
> I want to install webjs so I run the below command but it is showing an error on Ubuntu OS.
> 
> > $ sudo npm install -g web3
> 
> ```
> npm ERR! path git
> npm ERR! code ENOENT
> npm ERR! errno ENOENT
> npm ERR! syscall spawn git
> npm ERR! enoent Error while executing:
> npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
> npm ERR! enoent 
> npm ERR! enoent 
> npm ERR! enoent spawn git ENOENT
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nithin/.npm/_logs/2019-09-18T09_41_14_857Z-debug.log
> ```

Did you issue get resolve
i am getting same error need your help????

**Comment by ssimunec** [comment]
> > I want to install webjs so I run the below command but it is showing an error on Ubuntu OS.
> > > $ sudo npm install -g web3
> > 
> > 
> > ```
> > npm ERR! path git
> > npm ERR! code ENOENT
> > npm ERR! errno ENOENT
> > npm ERR! syscall spawn git
> > npm ERR! enoent Error while executing:
> > npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
> > npm ERR! enoent 
> > npm ERR! enoent 
> > npm ERR! enoent spawn git ENOENT
> > npm ERR! enoent This is related to npm not being able to find a file.
> > npm ERR! enoent 
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /home/nithin/.npm/_logs/2019-09-18T09_41_14_857Z-debug.log
> > ```
> 
> Did you issue get resolve
> i am getting same error need your help????

Hi, yes we did. That version had git as dependency

In order to resolve this issue we installed git for windows from here 
https://git-scm.com/download/win or here https://gitforwindows.org/

**Comment by Abdullah-sudo** [comment]
Thank you Bro.....
