### ISSUE TITLE
[number-to-bn] while converting number 1.2345678912345679e+26 to BN.js instance,

### ISSUE THREAD

**Issue by AlexeyKub** [ethereum/web3.js#3072]
#### Example
When I make transaction
 const amount = web3.utils.toHex(123456789123456789123456789);
 token.methods.forceTransfer(from, to, amount).send({from: account[0]});

where amount is 123456789123456789123456789 (27 digits) and converted to hex 

I have error
Error: [number-to-bn] while converting number 1.2345678912345679e+26 to BN.js instance, error: invalid number value.....

when amount is 123123456789123456789 (21 digits) or smaller and converted to hex it works correctly.

**Comment by nivida** [comment]
Thanks for opening this issue! Which version of web3.js are you using?

**Comment by AlexeyKub** [comment]
Issue reproducing on this version of web3.js 1.0.0-beta.55

**Comment by nivida** [comment]
Thanks for providing the missing information. We will test and fix it asap.

**Comment by AlexeyKub** [comment]
Any updates?

**Comment by livingrock7** [comment]
Hi guys I'd like to reopen this issue

**Comment by ajoykarmakar** [comment]
The issue is still there.

**Comment by 1baga** [comment]
I had the same problem, I noticed that Javascript was always trying to convert big numbers to Exponentials, so if you look at the number above it is 1.234....... and when calling the toHex() it expects BN, string or Number.. It doesn't want a float.. a number with a decimal..


So what you can do is to make sure you convert exponent numbers to full decimals before passing as an argument to toHex() function. I hope it helps..
