### ISSUE TITLE
web3 invoke smart contract error

### ISSUE THREAD

**Issue by xuyangm** [ethereum/web3.js#3075]
I migrated a simple smart contract on my local private chain
(![contract](https://user-images.githubusercontent.com/16891612/65607777-a75b7280-dfdf-11e9-83f0-d68e022e43d0.JPG))
and then writed a web3 program to use this smart contract. The version of web3 is v1.2.1
![index](https://user-images.githubusercontent.com/16891612/65607957-0325fb80-dfe0-11e9-8a12-4a1ae20e011b.JPG)
Error occurs and I don't know how to fix it. It seems a bug in v1.0.0 and I don't know how it occurs now.
![error](https://user-images.githubusercontent.com/16891612/65608052-2fda1300-dfe0-11e9-8c87-ec0a9e74422c.JPG)

**Comment by nivida** [comment]
Thanks for opening this issue! Could you provide a gist file with the whole code?
