### ISSUE TITLE
[Feature Request] Please provide a way to look at the entire index=values of storage from a specific contract’s address !

### ISSUE THREAD

**Issue by ytrezq** [ethereum/web3.js#3077]
There’s currently web3.eth.getStorageAt() but it requires knowing the index position and you can’t find which storage address/index for a specific contract’s address are in use…

**Comment by gnidan** [comment]
This is a rather challenging problem :)

**Comment by ytrezq** [comment]
@gnidan : especially since downloading a full node would take more than 9 years at my connection speed so getting web3 modified is my only option in order to know if the storage of a specific address contains a specific value.

**Comment by gnidan** [comment]
The thing is, @ytrezq, is that there's no way to do it without having the full history. The best web3 can do is get that information from going one block at a time, tracking the storage changes. There's no record anywhere of "all the storage keys" for a given contract.

**Comment by cgewecke** [comment]
@gnidan To be clear, you think this is not something web3 can realistically implement?
@ytrezq Do you agree with this assessment? Do you have ideas for an alternative implementation?

If this isn't resolvable it should be closed.

**Comment by cgewecke** [comment]
Closing due to lack of response. If this possible, maybe it should be done by a dedicated service. Please ping if anyone wants this re-opened.
