### ISSUE TITLE
can't find module ./build/Release/scrypt

### ISSUE THREAD

**Issue by sirpy** [ethereum/web3.js#3079]
### Description 
After upgrading to  web3 2.0.0-alpha.1 from beta.55 on a project of create-react-app
Starting to get an error with the scrypt module.
This error seems to be around for a while, described here with also possible solutions
https://github.com/barrysteyn/node-scrypt/issues/162
another solution that worked for me was to also patch node_modules/scrypt by replacing the
require(' ./build/Release/scrypt') with require('scrypt')

In any case the scrypt package seems to be unmaintained.

This doesn't happen on a regular node project, so it also could be some kind of webpack settings of create-react-app

**Comment by Anaphase** [comment]
I also get a similar error and have been for a while now! I'm using Nuxt and when webpack bundles web3, I get this error in my console:

```
./node_modules/web3-eth-accounts/dist/web3-eth-accounts.umd.js

Module not found: Error: Can't resolve 'scrypt' in './node_modules/web3-eth-accounts/dist'
```

NODE: v10.16.0
WEB3: 2.0.0-alpha.1

**Comment by sethfork** [comment]
Can confirm that this issue has been present since the first 2.x release.

**Comment by jellydn** [comment]
This is a workaround if you run into this issue. Setup an `postinstall` with below script then it should work.

``` 
// package.json
 "scripts": {
    ...
    "postinstall": "node ./patch-scrypt.js",
  }
```

```
// patch-scrypt.js
const replace = require('replace-in-file');
const options = {
  files: './node_modules/scrypt/index.js',
  from: /\.\/build\/Release\/scrypt/g,
  to: 'scrypt',
};

replace(options)
  .then((results) => {
    console.log('Replacement results:', results);
  })
  .catch((error) => {
    console.error('Error occurred:', error);
  });
```

**Comment by thomasbromehead** [comment]
> This is a workaround if you run into this issue. Setup an `postinstall` with below script then it should work.
> 
> ```
> // package.json
>  "scripts": {
>     ...
>     "postinstall": "node ./patch-scrypt.js",
>   }
> ```
> 
> ```
> // patch-scrypt.js
> const replace = require('replace-in-file');
> const options = {
>   files: './node_modules/scrypt/index.js',
>   from: /\.\/build\/Release\/scrypt/g,
>   to: 'scrypt',
> };
> 
> replace(options)
>   .then((results) => {
>     console.log('Replacement results:', results);
>   })
>   .catch((error) => {
>     console.error('Error occurred:', error);
>   });
> ```

You saved my day with this one, thanks a lot!!
