### ISSUE TITLE
Customize timeout time (1.2)

### ISSUE THREAD

**Issue by dmihal** [ethereum/web3.js#3081]
Transactions that are not mined within a period of time will fail with the following message:

```
Transaction was not mined within750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
```

However, given the current network congestion, it's not uncommon for transactions to take long periods of time to be mined.

The amount of time and number of blocks to wait before timing out are currently [hardcoded as constants in web3-core-method](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L33).

It should be possible for applications to customize these options so they can avoid transactions failing when the network is congested.

**Comment by haflinger** [comment]
Maybe fixed in 2.x : 
[https://github.com/ethereum/web3.js/blob/38895c1bd34d51a307f6d6777e58d9f4b32e5895/packages/web3-core-method/lib/factories/AbstractMethodFactory.js#L131](url)

See documentation here : https://github.com/ethereum/web3.js/blob/2.x/docs/include_package-core.rst

```
const options = {
    defaultAccount: '0x0',
    defaultBlock: 'latest',
    defaultGas: 1,
    defaultGasPrice: 0,
    transactionBlockTimeout: 50,
    transactionConfirmationBlocks: 24,
    transactionPollingTimeout: 480,
    transactionSigner: new CustomTransactionSigner()
}
```

**Comment by dmihal** [comment]
Cool, thanks @haflinger 

I imagine this feature won't reach 1.x, so i'll close this

**Comment by cgewecke** [comment]
@dmihal Hi. Just leaving a cross-ref here...

This addition to the 1.x branch is still alive & under consideration at #3070 - tracked via an earlier discussion in #1581.
