### ISSUE TITLE
Uncaught Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by RashikaAggarwal** [ethereum/web3.js#3084]
i am using web3.js v1.2.1 and I am facing the above issue. 
Here is my code - 
```javascript
await myContractInstance.methods.getDetails(i).call((err, res)=>{
    if(err){
       console.log(err); }  // #Uncaught Error: Returned values aren't valid, did it run Out of Gas?
    else{
       console.log(result); 
   }
});
```

**Comment by cgewecke** [comment]
@RashikaAggarwal It's quite difficult to tell what's going wrong here based on the information you've provided. Please follow the guidelines in the issue template and provide a small, easily reproducible example which includes relevant solidity code and all the steps you took to get to the point above.

Thanks. Closing. If you'd like to pursue this further please just ping and I will re-open.
