### ISSUE TITLE
Compiler stop working with solc version 0.1.2

### ISSUE THREAD

**Issue by danielnovy** [ethereum/web3.js#309]
Upgrading solc from `0.1.1` to `0.1.2` makes the web3 compiler stop working with the message `solc: no build results found`. The solc command line options changed a lot from `0.1.1` to `0.1.2` and that's probably the reason. Downgrading solc to `0.1.1` solved the issue. I'm using Ubuntu 15.04.

**Comment by debris** [comment]
should be working fine now
