### ISSUE TITLE
[v1.2.1] Connection not Open.

### ISSUE THREAD

**Issue by NakOh** [ethereum/web3.js#3092]
### Description 
![스크린샷 2019-10-02 오후 5 54 53](https://user-images.githubusercontent.com/7420198/66031195-dc1a7d00-e53d-11e9-8b87-a4e7423025d7.png)

#### Expected behavior

I get an error periodically.

maybe

web3.eth.getBalance or web.eth.getBlock .. etc

#### Steps to reproduce the behavior
<!---------------------------------------------------------------------

const Web3 = require('web3');
const web3 = new Web3('ws://' + serverList[0].host + ":" + serverList[0].port);
var endBlockNumber = await web3.eth.getBlockNumber();
-> Error. Can't get BlockNumber.

Or 

		var amounts = await web3.eth.getBalance('0xFD2ACe8086F9FeF3da294Cc69b4750D59bd3C61A');

-> Error.

But sometimes Success...

Please Help me.. 

I'm crazing...

### Versions 
* web3.js: 1.2.1
* nodejs: v10.16.3
* browser: experess.

**Comment by nivida** [comment]
Thanks for opening this issue! Could you provide an explicit example setup to reproduce this issue?

**Comment by NakOh** [comment]
It's so simple.

just 


const web3 = new Web3('ws://' + serverList[0].host + ":" + serverList[0].port);
web3.setProvider('ws://' + serverList[0].host + ":" + serverList[0].port);


connect Socket.


			var endBlockNumber = await web3.eth.getBlockNumber();

or

		var amounts = await web3.eth.getBalance('MyAddress');


 Call Web.eth function.

Somtimes I got 'Connection not Open Error' !!!

i'm going crazy..

It happens only occasionally, so it's going crazy.

**Comment by nivida** [comment]
Thanks. This got fixed in the 2.x branch and will be back-ported asap.

**Comment by fengyh13** [comment]
I got this error too. It happens only occasionally! And eth.subscribe('newBlockHeaders') cannot get data anymore

**Comment by nivida** [comment]
@fengyh13 Thanks for letting us know about! We do currently improve the ``WebsocketProvider`` and the handling of providers in web3.js with PR #3190 and will release the changes as soon as anything is ready.

**Comment by cgewecke** [comment]
This should be resolved with the recent Websockets upgrade. You can configure the provider to automatically reconnect if your connection is unstable. 

[Relevant docs][1]

[1]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth.html#configuration
