### ISSUE TITLE
sendSignedTransaction does not fire receipt event

### ISSUE THREAD

**Issue by Jonas121** [ethereum/web3.js#3093]
### Description 

sendSignedTransaction does not fire receipt after transaction is mined.

#### Expected behavior

Should fire receipt event after mining finalized.
By my test it fires only Confirmation and TransactionHash events

#### Steps to reproduce the behavior

await main.web3.eth.sendSignedTransaction(signedRawTransaction)
	.on('transactionHash', async function(transactionHash){
		txHash = transactionHash
		}
	})
	.on('receipt', function(receipt){
		logger.log("RECEIPT", receipt)
		blockNumber = receipt.blockNumber
	})	
	.on('error', function(error){
		logger.log("ERROR", error)
	})	
	.on('confirmation', function(conf){
		logger.log("CONF", conf)
	})	

### Versions 
* web3.js: 2.0.0-alpha.1
* nodejs: 11.15.0
* browser:
* ethereum node: Infura ROPSTEN

**Comment by Jonas121** [comment]
Network - Ropsten

**Comment by Jonas121** [comment]
Further investigation shows that Receipt fires after 24 confirmations, which was not for web3 beta37 version. Very confusing.
I have changed web3.transactionConfirmationBlocks=1, and now Receipt fires after 1 block.

**Comment by nivida** [comment]
Instant seal/Automine support got implemented and will be released with the next version. The CHANGELOG.md file does document the coming fixes/features and is located in the root folder of this respository.

**Comment by jo-es** [comment]
Is this implemented in 1.x? Still having problems when executing sendSignedTransaction on ganache. Setting `web3.eth.transactionConfirmationBlocks = 1` did not resolve my issue either.
