### ISSUE TITLE
Proposal to add E2E and Integration testing on 1.x branch

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3098]
(This proposal is continuation of #2682, a companion to #3070, and a tracking issue for all integration testing related topics for the 1.x branch) 

##  E2E
Web3 1.x's stability might benefit from following [ethereum/solidity][8]'s example and E2E testing its latest state against large projects that already use the package.  Solidity does this [nightly in CI][1] - they build a new solc, swap it into Zeppelin, Gnosis and Colony and run those projects' own tests using the new version.  

Some targets that seem promising for this purpose here are: 
- [x] [@truffle/contract][3] 
- [ ] [gnosis/safe-react][4] 

**Technical**

Web3 is a Lerna monorepo and so are two of the potential targets listed above. Because its repo structure and published formats are quite different it won't just `npm install` from a github url. 

However, there's a nice tool called [verdaccio][5] that lets you set up a local private npm registry in CI. Web3 could "publish" a candidate branch to this ephemeral registry, clone an E2E target (ex: embark) and install the new web3 via npm proxy. Then run the target's tests.

It's also possible to chain publications together. For example, openzeppelin-solidity uses truffle so you could:
+ publish a new Web3, 
+ install it in Truffle, 
+ publish a new Truffle, 
+ swap the new Truffle into Zeppelin and run Zeppelin's tests.

Additionally: 
+ could be used to verify that built assets are located correctly and usable. 
+ [ethereum-js][9] may migrate some things to monorepo in future. Any solution developed here might pay dividends there as well. 

## Integration

**Clients**

To recap #2682 - Web3 1.x's unit tests rely primarily on mocked server responses. They're super fast but some things are hard to validate without testing against a node. There's also variance in behavior between the three most widely used clients. It would be good to create a small suite of tests for stuff like:

+ simple send and call
+ events
+ subscriptions
+ errors 
+ transaction signing 

..and make sure everything executes as expected across this matrix:

| Client       | instamine | automine 2s |
|--------------|-----------|-------------|
| geth --dev   |     x     |      x      |
| parity --dev |     x     |      x      |
| ganache-cli  |     x     |             |

**Client Helpers**

To simplify things in CI and make this work portable, Web3 could also publish small Node cli wrappers for the dockerized Parity and Geth dev clients.

These would:
+ pull down any client version from docker hub 
+ abstract away most of command config flags, 
+ open all APIs, 
+ have many well-funded accounts
+ make it easy for people to generate reproduction cases for client specific problems. 

Something that launches like this:
```
$ web3-geth-dev --period 2 --tag latest
```

See also: #2688 and #2693: I think access to these clients can be provided in a flexible way with JS wrappers alone - e.g without building any containers or using docker compose. 
  + [nomiclabs/builder-docker][10] provides a nice API for the general case of managing docker published resources from JS. 
  + [A basic geth dev wrapper][11] I've used in CI for other projects. Not perfect at all but [works][12]. 

- [ ] Parity dev Node cli wrapper
- [x] Geth dev Node cli wrapper

**Network Emulators**

- [ ] Dropped connections are frequently mentioned in the issues. Emulate with [comcast][7]?

## Installation

- [x] Windows: see #2971, #3033
- [ ] Mac OSX

The EF has an account with CircleCI. (EthereumJS uses it). They let you specify which OS a job is run with [pretty easily][14].

cf: #3034 (Azure Pipelines)

## Other stuff  :elephant:
There is definitely other stuff to test. Would be grateful for any and all community suggestions about this topic. 

- [ ] [generic create-react-app][15]
- [x] [headless browser testing for chromium, firefox, safari][16] (PR #3146)

[1]: https://github.com/ethereum/solidity/blob/develop/.circleci/config.yml#L590-L640
[2]: https://github.com/embark-framework/embark
[3]: https://github.com/trufflesuite/truffle
[4]: https://github.com/gnosis/safe-react
[5]: https://verdaccio.org/docs/en/e2e
[7]: https://github.com/tylertreat/Comcast
[8]: https://github.com/ethereum/solidity
[9]: https://github.com/ethereumjs
[10]: https://github.com/nomiclabs/buidler/tree/master/packages/buidler-docker
[11]: https://github.com/cgewecke/geth-dev-assistant
[12]: https://travis-ci.org/cgewecke/eth-gas-reporter/jobs/591355142#L1214
[13]: https://github.com/ethereum/web3.js/issues/2971
[14]: https://circleci.com/docs/2.0/hello-world-windows/
[15]: https://github.com/ethereum/web3.js/issues/3018
[16]: https://github.com/ethereum/web3.js/issues/2978

**Comment by holgerd77** [comment]
Can't completely judge any measure from this proposal but I think that such strong and practical integrational testing might really be a game changer for the future stability of the library, my general feeling for the situation of the web3 library is still limited though.

@cgewecke do you have got a rough estimate about the scope of work a stripped-down barebone version of this would eventually take?

**Comment by cgewecke** [comment]
@holgerd77 I'm not sure. Days? It's kind of hard to tell. Some things like test suites might take a bit longer to develop a good set of cases.

**Comment by holgerd77** [comment]
@cgewecke Ok, thanks!

**Comment by nivida** [comment]
@cgewecke I think we should now first focus on adding all e2e test cases. We can after extend the e2e tests with the virtual registry and the headless browser tests. Do you agree with that?

**Comment by cgewecke** [comment]
@nivida Yes, that makes sense to me! Will work in that direction.

**Comment by cgewecke** [comment]
This is mostly done..
