### ISSUE TITLE
Parameter documentation brings confusion

### ISSUE THREAD

**Issue by watchcrypto** [ethereum/web3.js#3103]
### Description 
As i needed to use some method to verify ( recover? ) a signed message, i did a lot of research and what came out of it is that apparently a lot of people ( mostly stackexchange ) reffer to a method that is rather complicated AKA : web3.eth.accounts.recover(signatureObject);

As i am working with Ethereum technologies since a long time, i know that it is really easy to implement.

By checking through the different help topics i even found a guy advising to use a smart contract to do this, which is a total overkill and useless waste of time.

NB: i am not frustrated, i just prefer when things are clear. http://threevirtues.com/ virtue n1

#### Expected behavior

The parameter description should be clear, especially in the OR part.

#### Actual behavior

Miss guiding description who leads a real burden and useless waste of time.
The paramater can be of 2 different types while only 1 is explicitly verbosed.

#### Steps to reproduce the behavior

1- Think as a newbie, or someone with a limited tech knowledge
2- check pages like : 
https://ethereum.stackexchange.com/questions/13652/how-do-you-sign-an-verify-a-message-in-javascript-proving-you-own-an-ethereum-ad?newreg=bc39e02bca304017bbc18739638894d0

or 

use these keywords in google ( preferably in private mode ) : ethereum verify signed message js
3- look at this : https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#recover
First thing you will see is the red text, for sure. And as the other docs to point to a comre complicated parameters setup you jump straight to it.

#### Error Logs 

MyBrainIsBurning.log

#### Gists

Obviously not required for this issue.

### Versions 
* web3.js: n/a
* nodejs: n/a
* browser: Firefox@latest
* ethereum node: n/a

**Comment by watchcrypto** [comment]
It's been a week, it just asks for 1 minute of time to fix this. 
If the team agrees i will make it myself.

**Comment by cgewecke** [comment]
@watchcrypto There has been some recent work on this topic in the following places:
+  #3091 (where how to use ecrecover with eth.personal.sign is added to the 1.x docs) 
+ #3122 (where examples of signing and recovering are included in E2E tests)

Could you describe the additional changes you'd like to see in more detail?

**Comment by watchcrypto** [comment]
Thanks a lot, now it is a lot more straight forward 👍 
I close the issue :)
