### ISSUE TITLE
Failed to minify the code from this file:  ./node_modules/typed-promisify with web3

### ISSUE THREAD

**Issue by i-holo** [ethereum/web3.js#3106]
# Description 

After adding library web3 during build process I get the error:

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/typed-promisify/index.js:4

#### Expected behavior
Application should be minified

#### Actual behavior
Build fails on optimization

#### Steps to reproduce the behavior

1. On the page: 
import * as Web3 from 'web3'

package.json

"bootstrap": "^4.1.3",
    "image-to-base64": "^2.0.1",
    "jquery": "3.3.1",
    "moment": "^2.24.0",
    "opensea-js": "^0.6.5",
    "react": "^16.10.2",
    "react-dom": "^16.0.0",
    "react-instagram-login": "^1.3.0",
    "react-moment": "^0.9.2",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^1.1.5",
    "reactstrap": "^6.3.0",
    "rimraf": "^2.6.2",
    "web3": "^1.2.1"

npm run build:
    "build": "react-scripts build",
----------------------------------------------------------------------->

#### Error Logs 

 react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/typed-promisify/index.js:4

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!  app@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Versions 
* web3.js: "1.2.1"
* nodejs: 10.14.1
* npm: 6.4.1

**Comment by nivida** [comment]
Thanks for opening this issue! We will test and if required fix it asap.

**Comment by nivida** [comment]
I've closed this issue because web3.js doesn't have ``typed-promisify`` as a dependency and the implemented minification we use does work without any problem. Also, the newly created build-pipeline in #3160 didn't have that problem.
