### ISSUE TITLE
Improving of the providers documentation

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3117]
### Description 

Documenting the existing web3.js providers with their interfaces and options. 

- [ ] HttpProvider
  + [ ] Configuration
  + [ ] Interface
  + [ ] Special behaviours 
- [ ] WebsocketProvider
  + [ ] Configuration
  + [ ] Interface
  + [ ] Special behaviours 
- [ ] IpcProvider
  + [ ] Configuration
  + [ ] Interface
  + [ ] Special behaviours 

### Versions 
* web3.js: 1.x

**Comment by leagithub** [comment]
Hi

**Comment by cgewecke** [comment]
We've added a config section to the docs [here][1] and the module README look complete as well. 

IPC is still under-documented but it receives very little use. Closing for now. 

[1]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth.html#configuration
