### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by tharinduvindula** [ethereum/web3.js#3124]
#### Expected behavior

how to resolve that problem
#### Error Logs 
WARNING in ./node_modules/web3-eth-accounts/src/scrypt.js 17:50-60
Critical dependency: the request of a dependency is an expression

### Versions 
* web3.js :1.0.0-beta.37
* nodejs:10.16.0
* browser:brave
* ethereum node:
angular cli :  6.0.3

**Comment by nivida** [comment]
duplication of #3018
