### ISSUE TITLE
public bytes32 mapping returns incorrect value.

### ISSUE THREAD

**Issue by d11e9** [ethereum/web3.js#314]
Given a simple contract

    contract test {
        bytes32 public val;
        mapping (bytes32 => bytes32) public keys;
        
        function set(bytes32 key, bytes32 value) returns(bytes32) {
            val = value;
            keys[key] = value;
            return keys[key];
        }
    }

When getting the mapping value, after setting it via web3,js it always returns `0x` ie:

    // assuming contract "test" has been created, mined and instantiated with web3
    test.set( "example", "myExampleValue", { gas: 9999999, from: web3.eth.accounts[0] })
    // after mining transaction
    test.val() // => "0x6d794578616d706c6556616c7565000000000000000000000000000000000000"
    test.keys("example") // => "0x00..."

Reproduction steps/example and comparison to vm results: 
http://d11e9.github.io/universal-dapp/mappingBytes32.html

**Comment by jdmaresco** [comment]
I've encountered the [same issue](https://gitter.im/ethereum/web3.js?at=55e78ed62ec6bacd1e2da468) and have given up on using `bytes32` in mappings for the time being.

**Comment by d11e9** [comment]
When reproducing on `geth console` I was using web3. Can confirm that fetching these values directly on the console by instantiating a contract and calling its methods does return the correct result.

Bug is certainly limited to web3 rpc calls.

**Comment by d11e9** [comment]
**Debugging:**

Note: created example contract using [browser-solidity](#) and deployed on `geth console`, mined the contract and called `keyvalueContract.at("<created address>").set( "name", "test" )` and mined the transaction.

Making a simple call from the clientside (created a contract `.at(<above created address>)` ) logs the following rpc call:

    {"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xa614801e000fce6b9b9e9ba83ec18d3f71174883","data":"0x3c6bb436"},"latest"],"id":24}

The response from geth rpc is `0x00000...` which implies that either the request is incorrect or the problem lies with geth rpc server.

Using the above request and sending directly on `geth console` like so:

     eth.call({to: "0xa614801e000fce6b9b9e9ba83ec18d3f71174883", data: "0x3c6bb436"})

returns the correct bytes32 result (ie: not `0x0000....`), so its not an issue with the request.

**So far:**

It seems the problem must lie with the geth rpc server, investigating further...

**Comment by debris** [comment]
I cannot reproduce the issue any longer. Please reopen if it still occurs.
