### ISSUE TITLE
[v2] methods that require to use .request in batch calls fail typescript

### ISSUE THREAD

**Issue by xzilja** [ethereum/web3.js#3144]
### Description 

To perform batch requests and add to batches we need to append `.request` on methods i.e

```
 batch.add(web3.eth.getBlock.request(blockNumber));
```

I believe type definitions don't have this `.request` option specified as it fails.

#### Expected behavior
Appending `.request` in batches should not throw type errors.

#### Actual behavior
<img width="739" alt="Screenshot 2019-10-18 at 16 55 46" src="https://user-images.githubusercontent.com/3154053/67100349-29e2e680-f1c8-11e9-8a4e-b1be61e0be8a.png">

### Versions 
* web3.js: 2.0.0-alpha.1
* nodejs: 10.16.3
* browser: Chrome latest
* ethereum node: Metamask

**Comment by mmv08** [comment]
This is also the case for 1.2.9

**Comment by Douglasacost** [comment]
some update about this requirement?

**Comment by itxtoledo** [comment]
@ChainSafe anyone can help?

**Comment by itxtoledo** [comment]
the team behind this project seems to ignore the PRs and problems that users have, they let most issues be closed by robots for lack of answers. 2021 and i have this problem too
