### ISSUE TITLE
Contract fails when bytes param greater than 127 bytes

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#315]
I think this is related to the way that params are encoded

Contract:

    contract Test{
        bytes meta;

        function Test(bytes _meta){
            meta = _meta;
        }

        function getMeta() constant returns(bytes){
            return meta;
        }
    }

Here's the test

    TestAbi = [{"constant":true,"inputs":[],"name":"getMeta","outputs":[{"name":"","type":"bytes"}],"type":"function"},{"inputs":[{"name":"_meta","type":"bytes"}],"type":"constructor"}]

    TestContract = web3.eth.contract(TestAbi)

    TestCode = "0x60606040526040516101db3803806101db8339016040526060805160600190602001505b806000600050908051906020019082805482825590600052602060002090601f016020900481019282156071579182015b8281111560705782518260005055916020019190600101906054565b5b50905060989190607c565b8082111560945760008181506000905550600101607c565b5090565b50505b50610130806100ab6000396000f30060606040526000357c010000000000000000000000000000000000000000000000000000000090048063a79af2ce1461003957610037565b005b6100446004506100b2565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100a45780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60206040519081016040528060008152602001506000600050805480601f0160208091040260200160405190810160405280929190818152602001828054801561012157820191906000526020600020905b81548152906001019060200180831161010457829003601f168201915b5050505050905061012d565b9056"

    TestTxObject = {data:TestCode,from:web3.eth.accounts[0],gas:3000000}

    bytes127 = '0x'+Array(128).join('ff')
    bytes128 = '0x'+Array(129).join('ff')

    TestContract.new(bytes127,TestTxObject,function(error,testContract){
        if(!testContract.address) return
        console.log(bytes127===testContract.getMeta()) // returns true
    })

    TestContract.new(bytes128,TestTxObject,function(error,testContract){
        if(!testContract.address) return
        console.log(bytes128===testContract.getMeta()) // returns false
    })

**Comment by debris** [comment]
I've added tests for encoding/decoding long sequences of bytes and everything seems to be working fine. @chriseth do you have any idea, what might be wrong? Do we have solidity tests for constructors with such input params?

**Comment by chriseth** [comment]
I also added tests here: https://github.com/ethereum/solidity/pull/115
Everything seems to work fine.
Could that be a utf8-issue?

**Comment by aakilfernandes** [comment]
Not sure exactly what the problem was, but my test scenario is no longer failing on my machine.
