### ISSUE TITLE
Typing issue in web3.eth.getBlock

### ISSUE THREAD

**Issue by princesinha19** [ethereum/web3.js#3150]
I guess we need to change the typing for [web3.eth.getBlock](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#getblock) because when we pass `true` in web3.eth.getBlock it returns the array of transaction objects instead of an array of transaction strings.

Currently, the type is `(property) Block.transactions: Transaction[] | string[]`.
So, when you will try to use `true` with getBlock then typescript will give you an error:-

```
Types of parameters 'tx' and 'value' are incompatible.
      Type 'string' is not assignable to type 'Transaction'.ts(2345)
```

So, I think we need to create two different types of getBlock like BlockTransactionsObject and BlockTransactionString.

Please suggest better name or a better way to solve this issue.

**Version**: 1.2.2 as well as 2.x

**Comment by joshstevens19** [comment]
we have a type which is

`getBlock(blockHashOrBlockNumber: string | number, returnTransactionObjects: boolean): Promise<Block>;`

so if you pass the 2nd parameter it it should say `Block`

![image](https://user-images.githubusercontent.com/18472422/67391258-3f745980-f596-11e9-9d34-d1c6395e78c1.png)

^^ just tried it and experienced no issues can i see your coding example?

**Comment by joshstevens19** [comment]
sure but why can you not write code like:

```
const block = await Web3Service._instance.eth.getBlock(1234, true);
const transactions = block.transactions as Transaction[];

// do what you want with the transactions
```

i don't get any `TS` errors doing it like this with strict mode on.

we should probably yes create 2 different interfaces on that case which returns only `Transaction[]` but you can work around with the code to make it not error.

if you're getting errors with the above can you show me your snippet and i can take a look.

**Comment by princesinha19** [comment]
@joshstevens19 Yes. The above code is proper and it will work. It's a workaround to not get error. But, If some will not write const `transactions = block.transactions as Transaction[]` then, he will get an error.

Consider this code:-
```
this.web3.eth.getBlock(i, true)
.then((block) => {
    block.transactions.forEach((tx: Transaction) => {
    });
});
```
Ideally, if we will make two different interfaces then, it will work fine. Something like below code.

```
getBlock(blockHashOrBlockNumber: string | number): Promise<BlockTransactionString>;
getBlock(
    blockHashOrBlockNumber: string | number,
    returnTransactionObjects: boolean
): Promise<BlockTransactionString>;
getBlock(
    blockHashOrBlockNumber: string | number,
    callback?: (error: Error, block: BlockTransactionString) => void
): Promise<BlockTransactionString>;
getBlock(
    blockHashOrBlockNumber: string | number,
    returnTransactionObjects: boolean,
    callback?: (error: Error, block: BlockTransactionObject) => void
): Promise<BlockTransactionObject>;


export interface BlockTransactionObject extends BlockHeader {
    transactions: Transaction[];
    size: number;
    difficulty: number;
    totalDifficulty: number;
    uncles: string[];
}

export interface BlockTransactionString extends BlockHeader {
    transactions: string[];
    size: number;
    difficulty: number;
    totalDifficulty: number;
    uncles: string[];
}
```

> we should probably yes create 2 different interfaces on that case which returns only Transaction[] but you can work around with the code to make it not error.

Yes, it will be better.

**Comment by joshstevens19** [comment]
yep that way would be better for sure i am away till Monday can put in a fix when i'm back. :+1: thanks for raising.
