### ISSUE TITLE
Detect if provider is unlocked

### ISSUE THREAD

**Issue by abitrolly** [ethereum/web3.js#3164]
### Description

Many functions in documentation require that provider should be unlocked for operation. However, no API to detect if provider is locked is given.

#### Expected behavior

Calling `web3.currentProvider.isLocked` should return `true` if the provider is locked.

#### Actual behavior

Nothing to call.

### Versions 
* web3.js: 0.20.7
* browser: Firefox 69.0.3

**Comment by cgewecke** [comment]
@abitrolly Are you referring to geth's [personal API](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal)?

**Comment by abitrolly** [comment]
@cgewecke I am using Metamask, but I'd like to use some generic API. https://abitrolly.github.io/metamask-status/demo.html

**Comment by nivida** [comment]
@abitrolly Thanks for providing the missing details! I will check the possibilities to implement it and will probably extend the [EIP-1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md).

**Comment by abitrolly** [comment]
I found that MetaMask exposes `ethereum._metamask.isUnlocked()` method. The method is `asynch`, and checking the flag in synchronous way is not trivial.

https://github.com/MetaMask/metamask-extension/blob/f9cd775eae5195f1d7ca4ba7c81f77cdda402ac5/app/scripts/inpage.js#L128-L145

**Comment by abitrolly** [comment]
I don't think it is fixed.

**Comment by Anvarmirzo** [comment]
This problem actually in 2022 y...
