### ISSUE TITLE
Error : Cannot create property 'from' on string when I deployed contract

### ISSUE THREAD

**Issue by 0xywzx** [ethereum/web3.js#3166]
### Description 

`myContract.deploy()` throw the error with `Cannot create property 'from' on string `.

The account created by 'web3.eth.accounts.privateKeyToAccount()' and added into wallet.
I want to deploy contract by using this account.

This is my code.

```js
const privateKey = "0xa ... 55"
const etherAccount = await web3.eth.accounts.privateKeyToAccount(privateKey)

await web3.eth.accounts.wallet.add({
  privateKey: privateKey,
  address: etherAccount.address 
});
web3.eth.defaultAccount = await etherAccount.address;

const gasPrice = await web3.eth.getGasPrice();
console.log(gasPrice)
const gasEstimate = await itemContract.deploy({ data: bytecode, arguments:[1] }).estimateGas();

  await itemContract.deploy({
    data: bytecode,
    arguments:[1]
  })
  .send({
    from: web3.eth.defaultAccount,
    gas: gasPrice,
    gasPrice: gasEstimate,
  }).on('error', (error) => {
      console.log("Error: ", error);
  }).on('transactionHash', (transactionHash) => {
      console.log("TxHash: ", transactionHash);
  }).on('receipt', (receipt) => {
    console.log("Address: ", receipt.contractAddress)
  }).then((newContractInstance) => {
      console.log(newContractInstance);   
  }).catch(function(error) {
      console.log(error);
  });
```

#### Expected behavior

`myContract.deploy()` should work.

#### Actual behavior

`myContract.deploy()` throw error `Cannot create property 'from' on string `

#### Error Logs 

```
TypeError: Cannot create property 'from' on string '0xf901b08083022591808080b90160608060405234801561001057600080fd5b506040516020806101408339810180604052602081101561003057600080fd5b8101908080519060200190929190505050806000819055505060e9806100576000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c8063822a634a146041578063c412eaba14606c578063ca6158cb146088575b600080fd5b606a60048036036020811015605557600080fd5b810190808035906020019092919050505060a4565b005b607260ae565b6040518082815260200191505060405180910390f35b608e60b7565b6040518082815260200191505060405180910390f35b8060008190555050565b60008054905090565b6000548156fea165627a7a723058207942a879e753640985945a1fc5ac2fb685daaae7c7dec98582b4a34a960ab0b200290000000000000000000000000000000000000000000000000000000000000001820bfaa037ab41699c31e6408133701bf0890d8c50ece7f811572150d21baba78d99ce79a049c7e9372c52625b39736e01448754474debaef93150fb555339bace9c9099d5'
    at Object.inputTransactionFormatter (web3-core-helpers.umd.js:94)
    at ContractDeployMethod.beforeExecution (web3-core-method.umd.js:1250)
    at ContractDeployMethod.beforeExecution (web3-eth-contract.umd.js:869)
    at ContractDeployMethod.execute (web3-core-method.umd.js:1167)
    at web3-core-method.umd.js:1281
```

### Versions 
* macOS
* web3.js: 1.2.1
* nodejs: v11.14.0
* browser: Google chrome

**Comment by cgewecke** [comment]
Hi @Yosuke-Aramaki, 

In the [wallet documentation][1], there's a note advising that automatic tx signing is enabled for [web3.eth.sendTransaction][2] rather than `contract.deploy.send`. 

This means you'll need to compose the deploy transaction 'data' using `encodeABI` as below:
 
```javascript 
const gasPrice = await web3.eth.getGasPrice();

const gasEstimate = await itemContract
  .deploy({ data: bytecode, arguments:[1] })
  .estimateGas();

const txData = itemContract
  .deploy({ data: bytecode, arguments:[1] })
  .encodeABI();

const receipt = await web3.eth.sendTransaction({
  from: etherAccount.address,
  data: txData,
  gas: gasEstimate,
  gasPrice: gasPrice
});
```

The receipt will include the new `contractAddress`. If you want to send method based transactions to the deployed contract using the wallet you'll follow the same pattern as above but use something like:
```javascript
const txData = itemContract
  .methods
  .myMethod('hello!')
  .encodeABI();

const receipt = await web3.eth.sendTransaction({
  from: etherAccount.address,
  to: receipt.contractAddress,
  data: txData,
  gas: gasEstimate,
  gasPrice: gasPrice
});

```



[1]: https://web3js.readthedocs.io/en/v1.2.2/web3-eth-accounts.html#wallet
[2]: https://web3js.readthedocs.io/en/v1.2.2/web3-eth.html#sendtransaction

**Comment by 0xywzx** [comment]
Hi @cgewecke 
Thank you for your comment.
I understood that 'web3.eth.sendTransaction' is better way and could deploy by using your code.

However, I want to find the way to deploy by using `contract.deploy()`, 
However, I could communicate with blockchain by using 'myContract.methods.myMethod()',
so I thought I could deploy contract by using `contract.deploy()` and the address that made with `web3.eth.accounts.privateKeyToAccount()`

Do you think there is no way to deploy by using the account made by `web3.eth.accounts.privateKeyToAccount()`?

**Comment by cgewecke** [comment]
@Yosuke-Aramaki Apologies, in fact I am able to get a contract deployment using the simpler syntax you suggest as well. Have thought it could only be used with sendTransaction but I was mistaken.

The only change I've made to the example above is replace the encodeABI and sendTransaction with this:
```javascript
const contractInstance = await itemContract
  .deploy({ data: bytecode, arguments:[1] })
  .send({
    from: etherAccount.address,
    gas: gasEstimate,
    gasPrice: gasPrice
})
```

Can you see if that works, without any of the listeners attached? That way it might simpler to isolate the specific problem in your example

**Comment by 0xywzx** [comment]
@cgewecke  Thank you for your comment.

I did that, but I got the same error which is in Error Log.
'etherAccount.address' is really address, but the error show long string, so I thought this is web3 problem.

**Comment by cgewecke** [comment]
@Yosuke-Aramaki If you create a complete example on GitHub that reproduces the problem I will look at it and get back to you tomorrow. Unfortunately I don't see a really obvious cause for this error at the moment and I can't reproduce it myself.

**Comment by 0xywzx** [comment]
@cgewecke Thank you so much. 
However, my 'web3' works wire now, maybe my node is something wrong.
This might happen the problem.
I will fix my web3 and node, then I'll let you know how it will work.

**Comment by akachi1409** [comment]
I have a new error in deploying the contract here.

`Error: Invalid JSON RPC response: {"message":"Not Found","logref":null,"path":null,"_links":{"self":{"href":"/v2/28v9IABMj7WtEWBqWRJMzu1qipsviW29;","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Page Not Found","logref":null,"path":null,"_links":{},"_embedded":{}}]}}`
