### ISSUE TITLE
Custom unit in web3.utils.fromWei for WBTC like tokens

### ISSUE THREAD

**Issue by smogili1** [ethereum/web3.js#3169]
### Description
Is there a way to use a custom unit in web3.utils.fromWei ? For example: WBTC token has 8 decimals and there is no way to use fromWei function to get the value for the WBTC token in current implementation.

WBTC Contract: https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

#### Expected behavior

    `web3.utils.fromWei(100000000, 8) == 1`

#### Actual behavior

Have to use a work around like:      

  `web3.utils.fromWei(100000000, 'gwei')*100`

**Comment by superMDguy** [comment]
I'd still love for this to be a feature, there's no clean way to handle token balances with arbitrary decimals right now. Anyone know what it would take to get this working?

**Comment by BarneyChambers** [comment]
I would also like this to be a feature, fwiw

**Comment by jeanbmar** [comment]
This is the `fromWei` implementation in v4:

https://github.com/web3/web3.js/blob/8da5d8331e18271d573f498fb046aa87fc096dd2/packages/web3-utils/src/converters.ts#L442-L484

It could be modified to build a denomination for a custom number of decimals when passing a `unit` parameter of type number.

Alternatively:

```js
export function fromWei(value, numberOfDecimals) {
  const denomination = BigInt(10) ** BigInt(numberOfDecimals);
  const numberOfZerosInDenomination = denomination.toString().length - 1;
  if (numberOfZerosInDenomination <= 0) return value;
  const zeroPaddedValue = value.padStart(numberOfZerosInDenomination, '0');
  const integer = zeroPaddedValue.slice(0, -numberOfZerosInDenomination);
  const fraction = zeroPaddedValue
    .slice(-numberOfZerosInDenomination)
    .replace(/\.?0+$/, '');
  if (integer === '') return `0.${fraction}`;
  if (fraction === '') return integer;
  return `${integer}.${fraction}`;
}
```
