### ISSUE TITLE
How to get the result by parsing the log after executing the contract? 

### ISSUE THREAD

**Issue by ying2025** [ethereum/web3.js#3174]
How to get the result by parsing the log after executing the contract? How can I get the execution result ?
![image](https://user-images.githubusercontent.com/28092539/68014691-3b99b300-fccb-11e9-9b92-bd6ae15895cd.png)
![image](https://user-images.githubusercontent.com/28092539/68014759-6126bc80-fccb-11e9-8b3d-ee7931d3b6fe.png)

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/68085161-d1267580-fe78-11e9-904b-3274b5fd8ba8.png)
Resolve the  status from logs.

**Comment by nivida** [comment]
Could you provide the complete code example and a more accurate explanation of your current problem?

**Comment by ying2025** [comment]
The contract code link is https://github.com/NetNational/test_sol/blob/8191adb4352c7cdcefe3ee3f78af97579020abc0/houseInfo3/register.sol#L84.
The code resolve the logs link(https://github.com/commoncom/web3/blob/117fb400ce12d0c3c95c5c0551a48c18ddb986f7/src/get_register.js#L57) by web3.js.

**Comment by ying2025** [comment]
I want to resolve the reulst of the contract. If it execute errror, I can know the error. @nivida

**Comment by cgewecke** [comment]
Closing because unclear.
