### ISSUE TITLE
Gulp build fails on `clean` task

### ISSUE THREAD

**Issue by asinyagin** [ethereum/web3.js#318]
Hey,

Looks like clean task is not correct. It gives the callback as the second arg `del([ DEST ], cb);`, but it should be `del([ DEST ]).then(cb);`. Because of that the tasks after `clean` task aren't called. Take a look at that build https://travis-ci.org/ethereum/web3.js/jobs/80465174#L395

**Comment by asinyagin** [comment]
Actually, it should be `del([ DEST ]).then(cb.bind(null, null))`.

**Comment by asinyagin** [comment]
This commit brakes compatibility https://github.com/sindresorhus/del/commit/6589c52f289a1f8e94652f6a2cad9413cdee26dc

**Comment by debris** [comment]
Thanks! fixed in latest develop
