### ISSUE TITLE
Install web3 error

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#3183]
At first I thought it was because I didn't install windows-build-tools, and I still got the same error after the installation.

### This is the approximate content of the error
![1573030322](https://user-images.githubusercontent.com/40221340/68283804-3071c900-00b7-11ea-9fb1-e23ef8d889a3.png)

### Wrong details
[2019-11-06T08_43_15_481Z-debug.log](https://github.com/ethereum/web3.js/files/3813458/2019-11-06T08_43_15_481Z-debug.log)

**Comment by nivida** [comment]
Duplication of https://github.com/ethereum/web3.js/issues/3181
