### ISSUE TITLE
Need better error messages for tx sending when "from" parameter is missing

### ISSUE THREAD

**Issue by vbuterin** [ethereum/web3.js#319]
Particularly:

```
> contract.foo(3)
invalid address
```

This confused me for a while before I realized that it was looking for either a json object containing a from parameter or for the method to be constant. Perhaps, if no json object is provided or if the from parameter is missing, the error should instead be "Sender address not specified. Please either specify a sender address or make sure the method you are calling is constant"

**Comment by frozeman** [comment]
Yes that is bad, we need to change that. Though at this point, we actually don't know it was a `from`, as we use this function in other places too.
I will look into this:
```
var inputAddressFormatter = function (address) {
    var iban = new Iban(address);
    if (iban.isValid() && iban.isDirect()) {
        return '0x' + iban.address();
    } else if (utils.isStrictAddress(address)) {
        return address;
    } else if (utils.isAddress(address)) {
        return '0x' + address;
    }
    throw 'invalid address';
};
```

**Comment by frozeman** [comment]
@debris your comment?

**Comment by redsquirrel** [comment]
This ambiguous error is still biting us. Interested in a pull request?

**Comment by alexvandesande** [comment]
We're always interested in pull requests

**Comment by redsquirrel** [comment]
Actually, it seems like the main issue was already resolved here: https://github.com/ethereum/web3.js/commit/a46cec3bb7ad216edd09489941e296b864f8699a

Thanks @axic 👍 

Looking forward to seeing that commit in the next release. Any clue when that will happen?
