### ISSUE TITLE
Eth is not a constructor

### ISSUE THREAD

**Issue by slavafomin** [ethereum/web3.js#3198]
Hello!

According to the typings, the `web3-eth` package exports the `Eth` class.

Here's the usage code which is 100% correct according to the provided typings:

```typescript
import { Eth } from 'web3-eth';

const eth = new Eth(provider);
```

However, at runtime it causes the `Eth is not a constructor` error.

I have to use this typing augmentation:

```typescript
import { Eth } from 'web3-eth';

declare module 'web3-eth' {
  export = Eth;
}
```

And to import it like this: `import Eth from 'web3-eth';` in order to make it work.

You need to replace `export class Eth { ... }` with `export = class Eth { ... }` in your declarations.

Thank you!

**Comment by nivida** [comment]
Thanks for opening this issue! I've checked your problem closer and you are missing the required ``allowSyntheticDefaultImports`` and ``esModuleInterop`` configuration options as documented [here](https://github.com/ethereum/web3.js#usage-with-typescript).

Feel free to ping me here again if this wasn’t the case and I will re-open this issue.

**Comment by slavafomin** [comment]
I'm using `esModuleInterop` and it's not the case here. When your are exporting a class like this: `export class Eth { ... }` you are using named exports, which is effectively translates to `modules.exports = { Eth: Eth };` and should be imported with `import { Eth } from '...'`.

I believe my issue still stands true.

**Comment by nivida** [comment]
@slavafomin Thanks for commenting here on this issue! I will reopen it and will try again to reproduce your issue. 👌

**Comment by benjlevesque** [comment]
I have a similar issue with `AbiCoder` in `web3-eth-abi`:

```typescript
import { AbiCoder } from "web3-eth-abi";
new AbiCoder().encodeEventSignature("");
```
=> `web3_eth_abi_1.AbiCoder is not a constructor`

___

My suggestion is to append these 2 lines to `web3-eth-abi/types/index.d.ts`
```typescript
declare const coder: AbiCoder;
export default coder;
```
It enables to use this code 

```typescript
import  AbiCoder  from "web3-eth-abi";
AbiCoder.encodeEventSignature("");
```

Indeed, the JS implementation exports an instance of AbiCoder, which should be reflected by the declaration file.

**Comment by AuHau** [comment]
Hey there,
I believe this is still an issue even with the required compiler flags. I created reproducible bug repo, just to be sure I am not missing something: https://github.com/AuHau/web3.js_types

**Comment by AuHau** [comment]
Still is an issue

**Comment by gopherine** [comment]
Still facing this issue

**Comment by AuHau** [comment]
This is still an issue even with the 1.3.0 version.

**Comment by colthreepv** [comment]
Fastest way to work around this mess is to use [patch-package](https://github.com/ds300/patch-package)

Make a correction inside `index.d.ts`, for me that was:
```patch
 export {
@@ -60,7 +48,7 @@ export {
     chain
 } from 'web3-core';
 
-export class Eth {
+export default class Eth {
     constructor();
```

**Comment by Guihgo** [comment]
I have problem with both, so i debug and find 'default' children when import and used it. 

It's works for me on typescript: 

`import * as Web3Eth from "web3-eth";`

`const provider = new Web3Eth['default'](new Web3.providers.HttpProvider('NETOWRK-RPC-URL'))`

Note: use `new Web3Eth['default']`

**Comment by hexcowboy** [comment]
None of the workarounds that don't involve patching the module have helped me. How do I use this module in TypeScript?
```ts
import { Eth } from "web3-eth";

const eth = new Eth("ws://localhost:8546");
```

```
error - TypeError: web3_eth__WEBPACK_IMPORTED_MODULE_1__.Eth is not a constructor
    at eval (webpack-internal:///./src/utils/ethereum.ts:17:13)
    at Object../src/utils/ethereum.ts (/Users/hex/repos/8aa8/webapp/.next/server/pages/oracle/new.js:316:1)
    at __webpack_require__ (/Users/hex/repos/8aa8/webapp/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/oracle/new.tsx:17:73)
    at Object../src/pages/oracle/new.tsx (/Users/hex/repos/8aa8/webapp/.next/server/pages/oracle/new.js:305:1)
    at __webpack_require__ (/Users/hex/repos/8aa8/webapp/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/hex/repos/8aa8/webapp/.next/server/pages/oracle/new.js:721:39)
    at /Users/hex/repos/8aa8/webapp/.next/server/pages/oracle/new.js:722:28
    at Object.<anonymous> (/Users/hex/repos/8aa8/webapp/.next/server/pages/oracle/new.js:725:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  page: '/oracle/new'
}
  1 | import { Eth } from "web3-eth";
  2 | 
> 3 | const eth = new Eth("ws://localhost:8546");
    |            ^
```

Related: https://github.com/ChainSafe/web3.js/issues/5196

**Comment by DarbyBurbidge** [comment]
This is still an issue in 2023. Still solved by changing:
```typescript
export class Eth {
```
to
```typescript
export default class Eth {
```
and
```typescript
import { Eth } from "web3-eth"
```
to
```typescript
import Eth from "web3-eth"
```
