### ISSUE TITLE
web3.sha3 does not work for hashing hex data

### ISSUE THREAD

**Issue by vbuterin** [ethereum/web3.js#320]
I am trying to hash the 32 bytes which are hex represented as '0x3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1'; in python the desired output is the first of the three given here:

    >>> s = '0x3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1'
     >>> from ethereum.utils import sha3
     >>> sha3(s[2:].decode('hex')).encode('hex')
    '82ff40c0a986c6a5cfad4ddf4c3aa6996f1a7837f9c398e17e5de5cbd5a12b28'
    >>> sha3(s[2:]).encode('hex')
    '22ae1937ff93ec72c4d46ff3e854661e3363440acd6f6e4adf8f1a8978382251'
    >>> sha3(s).encode('hex')
    'd6c19311d63530fc619641d35f9d7dd795e79e5fa6218451e3ee7c66ec061d4c'

In javascript, however, I get the following results depending on what parameters I put in:

    web3.sha3('0x3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1')
    Error: Invalid UTF-8 detected
    requirement of using web3.fromAscii before sha3 is deprecated web3.min.js:1:16713
    new usage: 'web3.sha3("hello")' web3.min.js:1:16791
     "see https://github.com/ethereum/web3.js/pull/205" web3.min.js:1:16841
    if you need to hash hex value, you can do 'sha3("0xfff", true)' web3.min.js:1:16906
    web3.sha3('0x3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1', true)
    "d6c19311d63530fc619641d35f9d7dd795e79e5fa6218451e3ee7c66ec061d4c"
     web3.sha3('3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1')
    "22ae1937ff93ec72c4d46ff3e854661e3363440acd6f6e4adf8f1a8978382251"
    web3.sha3('3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1', true)
    "22ae1937ff93ec72c4d46ff3e854661e3363440acd6f6e4adf8f1a8978382251"
    web3.sha3(web3.toAscii('0x3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1'))
    "0f4e34bbedeb0e99897705101b1e49bd21b8718cc6951ded5812d3499d4ddebc"
    web3.sha3(web3.toAscii('3c9229289a6125f7fdf1885a77bb12c37a8d3b4962d936f7e3084dece32a3ca1'))
    "0f4e34bbedeb0e99897705101b1e49bd21b8718cc6951ded5812d3499d4ddebc"

None of these match up with the desired result, although some of them do match up with the results that I obtain from hashing the string without hex-decoding it, with and without the 0x prefix. The last two results are likely a result of Javascript's generally poor handling of strings that contain bytes >= 0x80.

**Comment by tomlion** [comment]
web3.js uses utf8 to decode sha3 arguments that assume they are strings. so it failed when they are not.

if web3.sha3 can accept BigNumber as arguments, that will fit for all situations.

**Comment by chriseth** [comment]
This is probably related to #290.
Can BigNumber encode leading zeros?

**Comment by tomlion** [comment]
Yes, it's related to #290 

web3.sha3 can accept arguments like this: web3.sha3(0, 0, 0, 1234) if we need to support leading zeros like Solidity sha3 already did.
But I don't know how crypto-js works and have no idea if it can work like this.

Another way is to tell web3.sha3 how to padding argument.

**Comment by debris** [comment]
Fixed in latest develop. Tests are available [here](https://github.com/ethereum/web3.js/blob/0a79a520a7d8b0c22ce15bb058900321ce9ab8e2/test/sha3.js#L13-L17). Also the api is slightly different.
