### ISSUE TITLE
web3-core > @types/bignumber.js@5.0.0 — dependency is apparently not needed

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ethereum/web3.js#3209]
When running `yarn install` in a project that has the latest version `web3@1.2.3` as a dependency, I'm getting this in the install output:

```
warning workspace-aggregator-076b0d0e-a31b-4d15-a5bf-261416e7d734 > embark > web3-core > @types/bignumber.js@5.0.0:
This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/).
bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
```
[line breaks added by me]

~~Also, could `@types/...` dependencies generally be made devDependencies?~~

NOTE: Did a little reading re `@types/...` packages and it seems that when authoring a library, it *is* better to have them in `"dependencies"` and *not* `"devDependencies"` since that will benefit downstream devs authoring in TypeScript.

**Comment by wbt** [comment]
Just got a similar report when using "npm install web3" on my machine.
