### ISSUE TITLE
Problem with encoding / decoding of bytes4 / byte[4]

### ISSUE THREAD

**Issue by chriseth** [ethereum/web3.js#321]
Moved from https://github.com/ethereum/solidity/issues/84 : 
The javascript interface to the following contract does not seem to encode or decode the values correctly:
https://github.com/fivedogit/solidity-baby-steps/blob/abc6461b40271a1edd7b31e33bad3da1798a4894/contracts/57_fixedbytearray_to_byte_array.sol

**Comment by drupalnomad** [comment]
I have a similar problem. This contract works fine at https://chriseth.github.io/browser-solidity/

But if I deploy the code generated there, set() uses up all the gas.

```
contract Simple {

  bytes3[] test;
  
  function set(bytes3[] b) {
    test = b;
  }
  
  function get() constant returns (bytes3[]) {
    return test;
  }

}
```

**Comment by debris** [comment]
fixed in latest develop!

**Comment by drupalnomad** [comment]
Thanks!
