### ISSUE TITLE
Web3 1.2.4 - Issue with returning array 

### ISSUE THREAD

**Issue by igortas** [ethereum/web3.js#3216]
### Expected behavior
I'm expecting that web3 will return array, array element by index, or array element as tuple.
#### Actual behavior
Error is thrown and I'm gettng error message from web3
#### Steps to reproduce the behavior

1. [First step]
Get this contract at least
```
pragma solidity >=0.5.0 <0.7.0;
pragma experimental ABIEncoderV2;

contract test {
    
    string[] public items;
    
    function loadItems() public {
        items.push('Sword');
        items.push('Shield');
        items.push('Axe');
    }
    
    function getItem(uint index) public view returns (string memory) {
        return (items[index]);
    }
}
```
2. [Second step]
From node.js, try to deploy the contract
```
(async () => {

  const accounts = await web3.eth.getAccounts();
  web3.eth.defaultAccount = accounts[0];

  require('fs').writeFile('./interface.json', JSON.stringify(interface),
    function (err) {
      if (err) {
        console.error('Crap happens');
      }
    }
  );

  const result = await new web3.eth.Contract(interface)
    .deploy({ data: '0x' + bytecode })
    .send({
      from: accounts[0], gas: '3000000'
    });
  console.log('response', result.options.address);
})();
```
3. [Third step]
In client code add address and ABI as this code:
```
import web3 from './web3';

const address = '0x....';

const abi = [{ ...ABI CREATED IN HERE... }];
export default new web3.eth.Contract(abi, address);

```

4. [Fourth step]
In some client code, for example react try to run the function
```
getItem = async () => {
    try {
      const item = await contract.methods.getItem(1).call();
      this.setState({ item });
    } catch (err) {
      console.log(err);
    }
  }
```

#### Logs
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced
#### Versions
Web3 1.2.4
Node v10.16.3
OS: Windows
Solc: 0.5.13
@truffle/hdwallet-provider: 1.0.25

With Remix when I try to play with the contract I don't have the issue.

**Comment by cgewecke** [comment]
@igortas, the contract has a method
```solidity
function loadItems() public {
  items.push('Sword');
  items.push('Shield');
  items.push('Axe');
}
```
Do you ever call that in your script?

**Comment by igortas** [comment]
> @igortas, the contract has a method
> 
> ```solidity
> function loadItems() public {
>   items.push('Sword');
>   items.push('Shield');
>   items.push('Axe');
> }
> ```
> 
> Do you ever call that in your script?

Yes, Just is not provided in the issue. Yes first u need to call loadItems(), but than I have problem with getItem.
This is just snippet of code from bigger contract, but I'm stuck for a week with the issue I've mentioned.
Actually is not the issue with 1.2.4, but also with 1.2.1 or bigger version, as far as I've tried different versions.
As I've mentioned in remix playing around, i have no issue with the getItem call, but when switch to react, the issue appears, in 1.2.4, just give more descriptive message.

**Comment by cgewecke** [comment]
@igortas I've made a simple reproduction of your example on Github [here](https://github.com/cgewecke/web3-issue-3216) which works.

If you look in [test/items.js](https://github.com/cgewecke/web3-issue-3216/blob/master/test/items.js) for differences between your code and what's there, maybe you'll be able to isolate the problem.

**Comment by cgewecke** [comment]
@igortas Any luck with this problem?

**Comment by mastguer** [comment]
I'm having issues with this too. 

I have a mapping that returns all addresses in an array, NFTs owned by that user. 
mapping(address => address[]) contractsByUser;

This is called immediately upon landing on my index.html page. 
Until the user creates their first NFT, this contractsByUser[_usersAddress] would return some []/null/undefined value that I could handle and proceed forward with. 
This has worked fine historically.

Now,  I get Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas?
This function specifically seems to be the culprit:
 i.prototype.decodeParameters = function (e, t) {
        if (0 < e.length && (!t || "0x" === t || "0X" === t)) throw new Error("Returned values aren't valid, did it run Out of Gas?");

What changed? It seems to die upon making the call to get all the NFTs for their account.

**Comment by cgewecke** [comment]
> Until the user creates their first NFT, this contractsByUser[_usersAddress] would return some []/null/undefined value that I could handle and proceed forward with.
This has worked fine historically.

@mastguer Could you provide more information about what version this used to work for? The current message and behavior looks like it has existed for [over a year](https://github.com/ethereum/web3.js/pull/1820/files#diff-0f39f52256cec08b5ed7384cbbe93719R226). 

How does the error behavior prevent you from handling this condition?

**Comment by cgewecke** [comment]
Closing b/c stale. Please ping if anyone can provide more information about this.
