### ISSUE TITLE
Consistency in number formats

### ISSUE THREAD

**Issue by vbuterin** [ethereum/web3.js#322]
`web3.eth.contract` outputs bigNumber objects when returning outputs of functions; however, `web3.toWei` outputs strings. This essentially means that we now have three ways of representing numbers in web3:
- As javascript numbers (basically, double-precision floats, 53 bit mantissa + 11 bit exponent so perfect accuracy only up to ~9 finney)
- As strings
- As bigNumber objects

And there doesn't seem to be much logic behind why one format is chosen over the other. I recommend that we consider adding some consistency here, as it is otherwise confusing when outputs to web3 methods sometimes appear in one format and sometimes in the other. Perhaps we should restrict to two output types, so functions that return small numbers (eg. getTransactionCount) only return javascript numbers, and everything that might return a big number (especially including toWei) go into bigNumber format. Also, fromWei should IMO return an integer; it seems prudent to adopt the convention that values denominated in wei are meant to be exact, but everything else is for representation only and so using javascript numbers is fine.

**Comment by wanderer** [comment]
I think fromWie and ToWei should probably return the same thing.  It make the API a bit simpler. 

Also what do you think about breaking off the unit conversion into a seprate module? I like the idea of web3 being a interface for the RPC and then having small focused modules to handle amenities such as unit conversion.

**Comment by wanderer** [comment]
acutely someone already did unit conversion in a seprate module. https://github.com/ryepdx/ethereum-units

**Comment by frozeman** [comment]
Currently all wei values are big numbers and all others are numbers.
the only difference is `fromWei` and `toWei`, which returns a Bignumber if you pass in a BigNumber object and a string when you pass in a string. Internally it always converts to a big number.
It returns the number as string as the representation is a wei value and we want to prevent the scientific representation of 1e23.

In most cases dealing with wei values as strings, even if they are big numbers its not a problem. It only becomes one when you want to make calculations. I could even agree on only returning wei values as String and letting people use whatever big number library they want...

You only get after decimal problems (which is fixed to max 20 in js), when you represent ether values other than wei.

I agree we could modularise it, but the idea of web3 is that its like the `chrome` object in mist. it gives "native" functionality for the web3 (Though we should definitely go with more standards like web crypto)

**Comment by frozeman** [comment]
All large numbers (wei values) are now returned as number strings in web3.js 1.0
