### ISSUE TITLE
eth_signTypedData_v3 no longer supported in web3 v1.2.x

### ISSUE THREAD

**Issue by nicholasmueller** [ethereum/web3.js#3232]
#### Expected behavior

calling `web3.currentProvider.send('eth_signTypedData_v3', [signer, data])` to sign my typed data in web3 version 1.2.x

#### Actual behavior

returns `undefined`
This used to work great in `web3 v1.0.0-beta.55` 

#### Steps to reproduce the behavior

1. create typed data
2. try to sign it calling `web3.currentProvider.send('eth_signTypedData_v3', [signer, data])` in web3 v1.2.2

#### Versions
- web3 v1.2.2

**Comment by nivida** [comment]
The code architecture used for 1.0.0-beta.55 is 2.0.0-alpha.x. The current 1.0 version is the code architecture from 1.0.0-beta.37 with back-ported of most fixes from 2.0. 

Provider ``send`` function signature:
```
web3.currentProvider.send(method, params): Promise<Object>; // 2.0 interface
web3.currentProvider.send(payload, callback): undefined; // 1.0 interface
```

Edit:
The release announcement [here](https://github.com/ethereum/web3.js/releases/tag/v1.2.0) gives you further information about it.
