### ISSUE TITLE
EIP-1191 automatic chain id detection

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/web3.js#3237]
#### Expected behavior

Checksum address encoding should follow https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md for RSK Mainnet and Testnet. 

When `new Web3` I think it should take the chain id from the network and _initialize_ utils with the valid checksum encoding. 

#### Actual behavior

Checksum address encoding uses only Ethereum encoding. 

#### Steps to reproduce the behavior

1. `web3 = new Web(‘https://public-node.rsk.co’)`
2. `web3.utils.isAddress(‘ 0x27b1FdB04752BBc536007A920D24ACB045561c26’)`

> Address from EIP-1191 test cases.

**Comment by cokia** [comment]
https://github.com/ethereum/web3.js/blob/aaf26c8806bc9fb60cf6dcb6658104963c6c7fc7/packages/web3-utils/src/Utils.js#L140

is already exist in "feature/EIP-1193-subscriptions" branch

I think this is fully working function and it can be possible to merge,
I will make a merge of this function.

**Comment by ilanolkies** [comment]
The problem arrives when using RSK addresses as validated parameters. For example, when using call. All functions expect Ethereum addresses even when using RSK network.

**Comment by cokia** [comment]
There are two problems that I have identified now.

1. isadress function does not distinguish between chainid [30,31] (RSK Testnet/RSK Mainnet)

2. isaddress function is connected to the Ethereum mainnet node, and the RSK mainnet/testnet address also returns true.

The proposal you want to ask is number two or number one?

**Comment by ilanolkies** [comment]
2. I think...

I don’t think is a question. This is more like a proposal. @nivida got my idea and tagged feature request

**Comment by cokia** [comment]
sorry, My english is not good so i mean your proposal. (i edited)

While I was looking into submitting a pull request related to this, I found that the "EIP1193-subscription" branch was equipped with RSKIP60 (EIP-1191) and EIP55
#2727  The issue has been found.

I have a question for @nivida. The EIP document states that EIP-55 and EIP-1191 is applied to web3. I wonder why you don't merge "feature/EIP-1193 subscription" branch with the master branch.

**Comment by cokia** [comment]
I think this feature should be implement.
this issue is not stale, I trying to implement this feature.
