### ISSUE TITLE
Error in processing one filter prevents processing other filters

### ISSUE THREAD

**Issue by vbuterin** [ethereum/web3.js#324]
Code example:

```
web3.eth.filter('latest', function(err, block) { console.log(1) });
web3.eth.filter('latest', function(err, block) { console.log(2) });
web3.eth.filter('latest', function(err, block) { console.logcnunqwqwt(3) });
web3.eth.filter('latest', function(err, block) { console.log(4) });
```

This will print 1 and 2, but not 4, as the third line triggers an error from trying to function-call `undefined`. Suggested fix: in the JS that implements this, place each function execution inside a `setTimeout(function() { ... }, 0)` wrapper so they do not interfere with each other.

**Comment by frozeman** [comment]
actually good, idea, as all callbacks should always be async

**Comment by frozeman** [comment]
Should not be an issue in web3.js 1.0.0 anymore.
