### ISSUE TITLE
Can't detect new built-in "crypto wallets" extension of brave browser

### ISSUE THREAD

**Issue by ppeinsold** [ethereum/web3.js#3240]
#### Expected behavior
Web3js can detect built-in "crypto wallets"-extension of brave browser.

#### Actual behavior
Crypto wallets extension is not detected and leads to the false conclusion, that no web3 browser is installed.

#### Steps to reproduce the behavior
Let me add a little bit of a code example. The following code is to connect to web3 browser using web3js library:

```
        // Check for injected web3 (mist/metamask)             
        // Modern dapp browsers...
        let web3Provider = null;
        if (window.ethereum) {
            web3Provider = window.ethereum;
            try {
                // Request account access
                await window.ethereum.enable();
            } catch (error) {
                // User denied account access...
                console.error("User denied account access to metamask");
                return;
            }
        }
        // Legacy dapp browsers...
        else if (window.web3) {
            web3Provider = window.web3.currentProvider;
        }
        else {
            console.error("Unable to connect to metamask");
            return;
        }

        let web3 = new Web3(web3Provider);
        ...
```

This works fine for all browsers but in brave it crashes when "crypto wallets" is enabled. The problem here is, that a check is missing. On the line where I have " console.error("Unable to connect to metamask");" I need to detect "crypto wallets" because I end up here if only "crypto wallets" is installed. Does anyone know how to make this check?

#### Versions
newest npm version
newest brave browser

**Comment by nivida** [comment]
I was in contact with the Brave team:
<img width="468" alt="Bildschirmfoto 2019-11-26 um 10 18 30" src="https://user-images.githubusercontent.com/1699173/69616008-2861d500-1036-11ea-91c0-3090ffe298a6.png">

**Comment by ppeinsold** [comment]
Interesting, thx for your answer!
But then either my code is wrong, or the delegation does not work correctly. There is no "window.ethereum" or "window.web3" available if only crypto wallets is enabled and metamask is not installed. Do they maybe inject a different variable?

**Comment by nivida** [comment]
I've tested it and could reproduce the same behavior. As long as the MetaMask extension is installed is the ``window.ethereum`` property existing and otherwise not. I've also checked if the native wallet of Brave and his API is documented somewhere but I sadly couldn't find any documentation about. 

@BrendanEich Do we miss something here? or is this actually a bug of Brave?

**Comment by ppeinsold** [comment]
@nivida any update here? I think this breaks a lot of dapps for brave users...

**Comment by nivida** [comment]
There is nothing web3.js can do. Please open an issue in the Brave repository.
