### ISSUE TITLE
Missing support for Clef from Geth

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3243]
``Geth`` does have released ``Clef`` for the reason to improve the security with moving of the account management from ``Geth`` to a standalone process with a fully encrypted storage. It’s possible to communicate over IPC or HTTP and JSON-RPC requests with the ``Clef`` process. This means the ``Clef`` module would have his own provider. 

#### Expected behavior

Module ``web3.eth.clef.*`` does exist with all JSON-RPC methods implemented from the ``Clef`` API.

#### Actual behavior

The module doesn't exist.

#### Ressources

- https://geth.ethereum.org/docs/clef/apis

#### Versions
web3.js: latest

**Comment by alcuadrado** [comment]
IMO this shouldn't be handled by this library. It's something super specific of one of the clients. If someone wants to use it, they can always use the provider.
