### ISSUE TITLE
eth.defaultBlock must be set to hex of number not regular number

### ISSUE THREAD

**Issue by prographo** [ethereum/web3.js#3244]
#### Expected behavior

According to the documentation here: https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#defaultblock

defaultBlock can be set to string like 'latest' or Number, it gives the example below:

// set the default block
web3.eth.defaultBlock = 231;

#### Actual behavior

When you next make call you will get error: 
```
invalid argument 1: json: cannot unmarshal number into Go value of type string
```
See code at bottom.

Problem is you must supply Hex String of Number, so the following will work:

```
  const latestBlock = await web3.eth.getBlockNumber()
  web3.eth.defaultBlock = web3.utils.numberToHex( latestBlock - 1 )
```

So either, change documentation, or change something else I think.

#### js code to reproduce the behavior
```
const w3provider = 'wss://goerli.infura.io/ws/v3/<SECRETKEY>'
const Web3 = require('web3')
const web3 = new Web3(
  new Web3.providers.WebsocketProvider(w3provider)
)
;
( async () => {
  const latestBlock = await web3.eth.getBlockNumber()
  web3.eth.defaultBlock = latestBlock - 1
  const accountBal = await web3.eth.getBalance( '0x1addbb6462cb45c91f0dd116c6480aa586de0a29' )
  console.log(`(${accountBal})`)
})()
```

**Comment by nivida** [comment]
Thanks for opening this issue! I will add the missing conversion to a hex string asap.
