### ISSUE TITLE
Further bytes3 encoding problem

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/web3.js#325]
This function uses infinite gas:

```
contract Test {

  function testIt(bytes3 data1, bytes data2) {
  }

}
```

If you change bytes3 to bytes it works fine.

**Comment by drupalnomad** [comment]
Note that in browser-solidity the problem does not occur. It only happens when you mine the contract.

**Comment by drupalnomad** [comment]
I tried recompiling Geth with the JS changes from https://github.com/ethereum/web3.js/commit/72ed89fd1b0cf803d347c7bae427b4ecbc84dd7b but it did not fix the problem.

**Comment by chriseth** [comment]
Checked it to work fine with latest solidity and alethzero.

**Comment by drupalnomad** [comment]
I can reproduce it reliably on Geth.

**Comment by debris** [comment]
I wrote additional test and there was indeed an issue. I've added quick fix. Will work on better solution later. Thanks for issue!

**Comment by drupalnomad** [comment]
Thanks man!
