### ISSUE TITLE
Support eth_requestAccounts

### ISSUE THREAD

**Issue by gpersoon** [ethereum/web3.js#3250]
#### Expected behavior
Begin able to use eth_requestAccounts in a native way.
Because metamask will deprecate ethereum.enable().
See: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#new-api

#### Actual behavior
It possible to use eth_requestAccounts in the following way:
```JS
web3.extend({   
                methods: [{
                    name: 'eth_requestAccounts',
                    call: 'eth_requestAccounts',
                    params: 0
                }]
            }); 
await web3.eth_requestAccounts();
```
#### Versions
Web3.js 1.2.4

**Comment by nivida** [comment]
Thanks for opening this issue! The ``eth_requestAccounts`` JSON-RPC method got already implemented with PR https://github.com/ethereum/web3.js/pull/3219. We will release this addition as soon as possible.

Edit:
See [CHANGELOG.md](https://github.com/ethereum/web3.js/blob/1.x/CHANGELOG.md)
