### ISSUE TITLE
Failed to minify code, file : web3-core-method with web3@1.2.4

### ISSUE THREAD

**Issue by rudreshsolanki97** [ethereum/web3.js#3251]
#### Expected behavior

Successful building of the node modules

#### Actual behavior

Failure while minifying file at ./node_modules/web3-core-method

#### Steps to reproduce the behavior

1. Setup app using create-react-app & install web3@1.2.4
2. run `npm run build`

**Note**: On bringing down the web3 version to **1.2.0** it actually builds.

#### Logs

Failed to minify the code from this file: 

        ./node_modules/web3-core-method/src/index.js:282 

#### Versions
Web3 : 1.2.4
Nodejs : v10.17.0
NPM : 6.11.3
OS : Ubuntu 19.04

**Comment by nivida** [comment]
Thanks for opening this issue! I'm able to create a minified build with parcel and webpack with the latest version of web3.js. Could you please add the whole error message?

**Comment by rudreshsolanki97** [comment]
Yes, below is the complete log of the run.

**Error Message:**

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/web3-core-method/src/index.js:282 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Run log:**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle client@0.1.0~prebuild: client@0.1.0
6 info lifecycle client@0.1.0~build: client@0.1.0
7 verbose lifecycle client@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/my_dir/web/client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle client@0.1.0~build: CWD: /my_dir/web/client
10 silly lifecycle client@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle client@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle client@0.1.0~build: Failed to exec build script
13 verbose stack Error: client@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid client@0.1.0
15 verbose cwd /my_dir/web/client
16 verbose Linux 5.0.0-36-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.17.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error client@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the client@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Version:
    "webpack": "3.8.1"

**Comment by nivida** [comment]
@rudreshsolanki97 Thanks for providing additional information! We will test and if required fix it asap.

**Comment by cgewecke** [comment]
We're seeing Web3 1.2.8 install, run a webpack production build, and execute correctly on [gnosis/dex-react][1]. 

Going to close this but if someone has a simple reproduction case (e.g a repo with clear reproduction steps please just ping and will investigate further.)


[1]: https://github.com/gnosis/dex-react/blob/develop/webpack.config.babel.js
