### ISSUE TITLE
Add ENS support for Goerli testnet

### ISSUE THREAD

**Issue by manuelwedler** [ethereum/web3.js#3252]
#### Expected behavior
ENS should be supported on Goerli testnet. It is deployed at address `0x112234455c3a32fd11230c42e7bccd4a84e02010`.

#### Actual behavior
This error is thrown:
```
ENS is not supported on network: "private"
```

#### Steps to reproduce the behavior
Try to call `web3.eth.ens.getAddress(name)` when connected to a Goerli Provider.

#### Versions
web3.js 2.0.0-alpha.1

**Comment by nivida** [comment]
Thanks for opening this issue! This request is related to: https://github.com/ethereum/web3.js/issues/3225
