### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by mknycha** [ethereum/web3.js#3255]
I have been trying to sign a transaction offline, then connect to the ropsten network and send it. As per the [documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendrawtransaction) I have prepared a code you can see in the steps.

I have tried googling the issue and checking github issues as well - I found many that looked similar but none of them was helpful in my case.

It does not affect Parity logs anyhow.
I have also made sure that there are enough funds in the address.

#### Expected behavior
The signed transaction is sent to the network and processed.

#### Actual behavior
What happens is that I get the transaction hash in the console, and then after I while I get the error:
```
(node:72726) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/usr/local/lib/node_modules/web3/node_modules/web3-utils/src/index.js:57:17)
    at /usr/local/lib/node_modules/web3/node_modules/web3-core-method/src/index.js:272:27
(node:72726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:72726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I have also checked the transaction hash in the ETH ropsten explorer, but it was not found.

#### Steps to reproduce the behavior
Run the following code:
```
const EthereumTx = require('ethereumjs-tx').Transaction
const txParams = {
  gasPrice: 100,
  gasLimit: 1000000000,
  value: 0x1,
  to: '0xD3591403a396d219Ea48Fa890032c045E4D8fDee',
}
const privateKey = new Buffer.from(
  '[MY_PRIVATE_KEY]',
  'hex',
)
const tx = new EthereumTx(txParams, { chain: 'ropsten', hardfork: 'petersburg' })
tx.sign(privateKey)

var Web3 = require('web3');
var web3 = new Web3("ws://localhost:8546");

web3.eth.sendSignedTransaction('0x' + tx.serialize().toString('hex'), function(hash) {
  console.log(hash)
});
```

#### Versions
- node.js (13.1.0)
- npm (6.12.1)
- web3.js (1.2.4 installed with npm)
- ethereumjs-tx (2.1.1 installed with npm)
- Parity (2.5.10) as Ethereum node, connected to ropsten network, light node
- MacOS (Mojave)

Thanks in advance!

**Comment by nivida** [comment]
Thanks for opening this issue! We will check this closer asap and fix it if required.

**Comment by zyairzy** [comment]
I meet this error too.

I run private go-ethereum network by meself, then I use web3.js 'web3.eth.Contract' send to contract, when I add run times to high, this error occurs.

**Actual Error**
```js 
(node:25353) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/eric/vscode-proj/geth-test-client/node_modules/web3-utils/src/index.js:57:17)
    at /home/eric/vscode-proj/geth-test-client/node_modules/web3-core-method/src/index.js:272:27
(node:25353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34896) 
```

**Steps to reproduce the behavior**
Run the following code, if I modify cnt to a more big number, error easier to happen:
```js 
let cnt = 5000;
for (let idx = 0; idx < cnt; idx++) {
    myContractInstance.methods.oneMethod().send({from:coinbase}, function(err, txHash){
        if (err != null) {
            console.error(err);
        } else {
            console.log(txHash);
        }
    })   
} 
```

**Versions**

- node.js (10.17.0)
- npm (6.11.3)
- web3.js (1.2.4 installed with npm)
- go-ethereum (1.9.8) as Ethereum node, private network, full node
- CentOS 7

Thanks in advance!

**Comment by mknycha** [comment]
In case someone is looking for a workaround here: I got it working by using [signtransaction](https://web3js.readthedocs.io/en/v1.2.0/web3-eth-accounts.html#signtransaction) from `web3-eth-accounts` library.
Also my colleague said it's working for her with Parity full node, but I was not able to check this.

**Comment by pellarboss** [comment]
We had this issue with Rinkeby, been bashing our head against the desk for days, redeployed the contract to Ropsten and it is now resolved...

**Comment by chim4us** [comment]
Hi Mknycha,

I also face the error while am trying to deploy. a contract through truffle 

FAVORs-MacBook-Pro:inbox favor$ ls -lrt
FAVORs-MacBook-Pro:inbox favor$ node deploy.js
Trying to deploy our contract 0x2D7dc97AC04dd7d3871dA631afaF78F0c9d720bF
(node:6866) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/Users/favor/Documents/inbox/node_modules/web3-utils/src/index.js:57:17)
    at /Users/favor/Documents/inbox/node_modules/web3-core-method/src/index.js:282:27
(node:6866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:6866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FAVORs-MacBook-Pro:inbox favor$ node deploy.js
Trying to deploy our contract 0x2D7dc97AC04dd7d3871dA631afaF78F0c9d720bF
/Users/favor/Documents/inbox/node_modules/solc/soljson.js:1

**Comment by codemaster101** [comment]
Hi is there any update on this error?
I recently submitted a transaction on Parity (openethereum 3.0.1)
and got the following error: 
```{ error:
    Error: Failed to check for transaction receipt:
    {}
        at Object._fireError (/[redacted]/[redacted]/node_modules/web3-core-method/node_modules/web3-utils/src/index.js:57:17)
        at /[redacted]/[redacted]/node_modules/web3-core-method/src/index.js:282:27 }
```
This happened even though the transaction was successfully submitted on the chain.
This is a rospten transaction, with the transaction hash:
`0x42dd4efd6a12f8e339616c237111b32e5778b1d6eac9030559b860b0209e3e6a`

The following is my code to submitted the transaction:

```  async sendRawTransaction(rawTx) {
    let result = null;
    await this.web3.eth.sendSignedTransaction(rawTx)
      .on('transactionHash', (hash) => {
        result = {
          success: true,
          txHash: hash,
        };
      })
      .on('error', (error) => {
        console.log('---------------------------');
        console.log({ error });
        result = {
          success: false,
          message: error,
        };
      });
    return result;
  }
```

**`web3` version is `1.2.6`**

**Comment by ryanio** [comment]
@codemaster101 how are you connecting to the node? also try using `1.2.9` as there were some improvements since `1.2.6` with regards to checking for tx receipt.

**Comment by codemaster101** [comment]
> @codemaster101 how are you connecting to the node? 

`const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:8545'));`

Alright let me try to do a transaction with 1.2.9.

**Comment by cgewecke** [comment]
@codemaster101 This problem affects people using OpenEthereum/Parity quite frequently fwiw.

Believe it is related to [openethereum 10672][1].


[1]: https://github.com/openethereum/openethereum/issues/10672

**Comment by csmartinsfct** [comment]
> This happened even though the transaction was successfully submitted on the chain.

Probably the worst part about this error. Error is thrown but the transaction may be broadcasted.  Sometimes `.on("transactionHash"` doesn't get triggered either in that case.

Using v1.2.11

**Comment by gopherine** [comment]
to me roughly the same thing is happening but the transaction is stuck on reciept and i get no response , and it times out i assume, on checking the hash i dont see it processed at all 

for me .on("transactionHash" gets triggered 
however .on("receipt" 
```
Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
```

^above was solved when i omitted nonce <->

however, post that transaction is reverted and transaction fails

Edit2:

removed nonce and i let it automatically calculate and i set the value to 0x0 which i dont know what it corresponds to really
but then the transactions work properly

**Comment by NatPDeveloper** [comment]
Can anyone explain why this error would occur under normal circumstances?  Getting this on ropsten consistently, thought it could be related to nonce or gas configurations, but we've tried quite a few things and can't seem to get it working. 

**Update

Mine was a node related issue, after using my own node, expected behavior.

**Comment by chaitanya5** [comment]
Found searching for the solution and it lead me here. 

**My code, as I wanted to send a response only if it's confirmed with a confirmation number**
`web3.eth.sendSignedTransaction(serializedTx)
        .once('confirmation', (confirmationNumber, receipt) => {
            res.status(200).send({ Message: "Approval Successfull.", Receipt: receipt.transactionHash });
        })
        .on('error', (error) => {
            console.log(`Transaction Error => ${error}`);
            res.status(500).send({ Message: `Transaction Error: ${error}` })
        });`

**The response**

`POST /gamecoin/approve 200 80761.786 ms - 114
Transaction Error => Error: Failed to check for transaction receipt:
{}
_http_outgoing.js:558
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`
