### ISSUE TITLE
Loading web3.min.js in browser fails with "require is not defined"

### ISSUE THREAD

**Issue by digulla** [ethereum/web3.js#3256]
I've installed `web3@1.2.4` with `npm install`.
I copied the file `node_modules/web3/dist/web3.min.js` into my web app.
I'm loading the file with:

    <script type="text/javascript" src="js/web3.min.js"></script>

In the browser console (Chrome 70+), I see this error:

    Uncaught ReferenceError: require is not defined
        at web3.js:1

**Comment by nivida** [comment]
Thanks for opening this issue! The minified file here provided in the GitHub repository does work as expected but the published one in the web3 package not. We will publish a new fixed minified file on the next patch release. I apologize for all the trouble you might have.

**Comment by wktian1987** [comment]
v1.2.2 is ok without this error.

**Comment by digulla** [comment]
@nivida Where is the minified file? The one in the ZIP archive https://github.com/ethereum/web3.js/releases/tag/v1.2.4 has the same problem.

v1.2.2 works for me.

**Comment by nivida** [comment]
@digulla Thanks for asking this! The minified file can be found [here](https://github.com/ethereum/web3.js/tree/1.x/dist).

**Comment by digulla** [comment]
@nivida Still getting the same error with the file at your link.
sha256 of the file:

    42037f35ccf2195cdd80448f4963515dd8c6a2d7b416f042743c1d4cec7fc17d  web3.min.js
