### ISSUE TITLE
contract even listeners for mobile

### ISSUE THREAD

**Issue by leon-do** [ethereum/web3.js#3257]
#### Expected behavior
I am able to listen to contract events on desktop, but I'm unable to listen on mobile wallets (ie. coinbase wallet). Does web3 support contract even listeners for mobile?

#### Steps to reproduce the behavior

```javascript
// https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html#contract-events
const contractInstance = new web3.eth.Contract(abi, contractAddress);
contractInstance.events["myEvent"]().on("data", event => {
  console.log(event)
}
```

#### Versions
mobile coinbase wallet

**Comment by nivida** [comment]
web3.js does support event listeners on mobile devices in the same way as on desktop devices. As it looks like is the issue on side of the coinbase mobile wallet. Is it possible to add the whole code you are using as GitHub repository or gist file to this issue?

**Comment by leon-do** [comment]
Hey @nivida 

I can't post the whole code yet... I figured it was on the coinbase mobile wallet side. Is there documentation on what listeners mobile supports?

**Comment by nivida** [comment]
@leon-do 
> I can't post the whole code yet...

No problem 👌 

> I figured it was on the coinbase mobile wallet side

Thanks for doing additional tests! 

> Is there documentation on what listeners mobile supports?

I sadly also couldn't find good documentation about which JSON-RPC methods coinbase does provide over their API. I'm also not sure if they even do support any subscriptions by side of the defined one from EIP-1193 they definitely should support. 
I'm closing this issue now and will try to reach out to the coinbase team and will contact you over gitter if I do have something worth sharing.
