### ISSUE TITLE
Cache rpc results

### ISSUE THREAD

**Issue by kumavis** [ethereum/web3.js#326]
i've been working on some alternate web3 providers that let a user run a dapp without setting up and running a node. We've noticed some dapps trigger very aggressive polling for state. Since our network requests can take a little longer to resolve, we've seen significant improvements by caching network results. The setup looks like this:
- web3 continuously polls for the latest block
- while the block remains the same we can cache any results regarding the state of accounts (balance, storage)
- when the block increments, we dump the cache

we're implementing this at the provider level, but seems like something that everyone could benefit from at the web3 level

thoughts? would you merge a PR based on this?

**Comment by tcoulter** [comment]
:+1: Would love to see this behavior implemented in web3. Due to provider idiosyncrasies, would love the polling interval be configurable.

**Comment by frozeman** [comment]
What about a chain re-org where the latest block changes?
We are actually thinking about introducing push events, so that we can get rid of this polling all together.

This would make the cache absolute right away, so i would rather wait..

**Comment by kumavis** [comment]
> What about a chain re-org where the latest block changes?

re-org invalidates cache, seems pretty straightforward

> This would make the cache absolute right away,

not sure what you mean

**Comment by frozeman** [comment]
https://github.com/ethereum/go-ethereum/issues/1867

**Comment by kumavis** [comment]
what do you think of http long polling for blocks?

**Comment by frozeman** [comment]
Would require changes on both node and web3. We are already going another route (push).

**Comment by kumavis** [comment]
@frozeman what protocol are you going to push over?

**Comment by fjl** [comment]
@kumavis Bit late to the discussion but the answer we settled on is WebSocket. geth 1.4.x now has WebSocket support and there are RPC methods for subscribing to push events on the connection. Push events are sent as JSON-RPC notifications.

**Comment by kumavis** [comment]
@fjl thanks

**Comment by kumavis** [comment]
@frozeman @fjl hey gents, is there an update on the websocket work? looking for an issue to follow.

**Comment by frozeman** [comment]
Those are the relevant threads:
- https://github.com/ethereum/EIPs/issues/51
- https://github.com/ethereum/interfaces/issues/16
