### ISSUE TITLE
Debug truffle issue 2654 (random ganache disconnection)

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3266]
JoinColony/colonyNetwork and Synthetix are both unable to upgrade truffle because they have large test suites which fail with client disconnection after running for a while. These suites ran without problems before Truffle upgraded to Web3 1.2.2 so it looks like a problem might have been introduced then.

More at [truffle 2654](https://github.com/trufflesuite/truffle/issues/2654)

**TODO** 
+ Compare synthetix and joinColony test suites and find common source of problem
+ Mosaic [issue at ganache-cli](https://github.com/trufflesuite/ganache-cli/issues/702)

**Comment by nivida** [comment]
From the truffle issue:
> I've checked the changeset between 1.2.1 and 1.2.2 related to the used HttpProvider. We were changing some smaller stuff which shouldn't have an impact on existing code.
The withCredentials options property does now default to false instead to true and we added a method called supportsSubscription which does return the boolean value false. The default options change was required to fix a CORS issue for Firefox/Safari and the added method was a small feature request from a web3.js user.
We also improved the transaction confirmations over an HTTP connection. It was before just a setInterval which triggered a confirmation each second but didn't check if actually a new block was mined.

> The mentioned improvement of the transaction confirmations could probably be the thing that does give some problems in the Colony test suite but I'm not sure.
