### ISSUE TITLE
Web3 instance opens connection on initialization and not close it after execution ended

### ISSUE THREAD

**Issue by pavlovdog** [ethereum/web3.js#3268]
Here's the example program:

```
const Web3 = require('web3');

(async () => {
    setInterval(async function () {
      const web3 = new Web3(
        new Web3.providers.HttpProvider('http://parity-host:8545'),
      );

      console.log('requesting');

      const balance = await web3.eth.getBalance('0x62b9399970804035f8bd8bb1b881f894aa7bf0fe');

        console.log(balance);
    }, 100);
})();
```

#### Behavior

This code should perform one RPC request each time the callback function is called. And it actually does it, the logs are such as expected. But when I'm checking the list of opened connections on my Parity instance - it's growing all the time, until reaches the ~65000 opened connections and stops responding to the requests.

#### Steps to reproduce the behavior

1. Run the code above on the Parity (maybe it matters).

#### Versions
```
pavlovdog@machine:~$ node -v
v12.13.1
pavlovdog@machine:~$ npm -v
6.12.1

Parity Ethereum v2.5.11-stable
```

**Comment by nivida** [comment]
Thanks for opening this issue! Which version of web3.js are you using?

**Comment by nivida** [comment]
Closed this issue because of missing details. Feel free to tag me here with the version you are using and I will re-open this issue immediately and will do further investigations.

**Comment by pavlovdog** [comment]
@nivida hi! Sorry for the delay, I'm using the `1.2.1` version.

**Comment by nivida** [comment]
@pavlovdog Thanks for pinging me here! It should reuse the TCP connection on a nodejs environment if the [HTTP keepAlive ](https://en.wikipedia.org/wiki/HTTP_persistent_connection) configuration is set to ``true``. To achieve the same in the browser is it required to pass a custom ``keep-alive`` header to the ``HttpProvider``. How exactly custom headers can get passed is documented [here](https://github.com/ethereum/web3.js/tree/1.x/packages/web3-providers-http#usage).  Feel free to ping me here again if this doesn't work as expected for you and we will investigate further and find a solution for it.
