### ISSUE TITLE
Duplicate events for contract.events.MyEvent

### ISSUE THREAD

**Issue by m-yahya** [ethereum/web3.js#3269]
I'm trying to listen to an event from the latest block but getting duplicate events in the frontend application built with `vue.js`.
I'm sending transactions using simulation script in Jupyter notebook with `web3.py`.
I also tried sending transactions with Metamask.

#### Expected behavior
The event should be emitted only once for a single transaction.

#### Actual behavior
1. with `web3.py`, the same event emits twice.
2. if the transaction is sent using Metamask, the same event emits three times.

#### Steps to reproduce the behavior
1. Configure metamask to connect with `https://volta-rpc.energyweb.org`
2. Deploy the contract using truffle.
3. In the `vue` app component, create a method to listen for the event:
```
// ....rest of code
    watchData() {
      this.testContract.events
        .Data({
          fromBlock: "latest"
        })
        .on("data", function(event) {
          console.log(event); // same results as the optional callback above
        })
        .on("error", console.error);
    },
// ....rest of code
// call the method
  async created() {
    this.getMetamaskAccount();
    this.testContract = await TestInstance();
    this.watchData();
  },
```
#### Versions
Web3.js: ^1.2.4
Truffle: v5.0.41 (core: 5.0.41)
Node: v10.16.3
OS: Ubuntu 19.10
Browser: Google chrome

#### Additional information
If I subscribe for the event from block 0, it will return unique events without duplicates. But for every new event, it will emit duplicates

**Comment by nivida** [comment]
Thanks for opening this issue! There is already an existing issue which does address the same problem (https://github.com/ethereum/web3.js/issues/2881)

**Comment by m-yahya** [comment]
Thanks for taking care. 
I did look at that issue too, but I couldn't find a solution to fix that. It also seems that the issue is with older version, however I'm using the latest. 
Would you be so kind t guide me is that already fixed? Or how to actually fix this?
