### ISSUE TITLE
Handle error when creating a log filter

### ISSUE THREAD

**Issue by kumavis** [ethereum/web3.js#327]
https://github.com/ethereum/web3.js/blob/d163c9dee41c5d641fdc4f8fa28ec78cd262cf50/lib/web3/method.js#L164-L166

in the case of an error, it fails silently. should at least log to console.

:smile_cat:

**Comment by frozeman** [comment]
Why? The error is passed to the callback, and its the user who has to take care of logging his errors.

**Comment by kumavis** [comment]
Whoops, looks like i posted the wrong line. This is indeed forwarding the error upward, but it gets lost somewhere else. The context was creating a new LOG filter via a contract object.

**Comment by frozeman** [comment]
Could you try to figure out the line? Im busy with other stuff :)
