### ISSUE TITLE
Wrong AbiInput type

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/web3.js#3270]
https://github.com/ethereum/web3.js/blob/39220467f4a10de511bb0e7b024fc37c9f92a7d5/packages/web3-utils/types/index.d.ts#L225

Now Truffle is adding `internalType: "..."` in build. For example:

```js
const STR_ABI = [
  {
    constant: true,
    inputs: [
      { internalType: "bytes32", name: "node", type: "bytes32" }
    ],
    name: "str",
    outputs: [
      { internalType: "string", name: "", type: "string" }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
```

**Comment by nivida** [comment]
Thanks for opening this issue! We will improve the referenced type definition asap.
