### ISSUE TITLE
web3.eth.getAccounts() - localy working fine; after deploy to heroku returns “undefined”

### ISSUE THREAD

**Issue by 3rr0rrs** [ethereum/web3.js#3271]
Hello,
 localy APP catch MetaMask address without any problem, however after I've deployed APP to heroku it returns address "undefined". Web3 working well both, localy and on heroku.

The contract is deployed to Kovan testnetwork

**function to get web3:**

```
    export const _loadWeb3 = dispatch => {
	if (typeof window.ethereum !== 'undefined' || (typeof window.web3 !== 'undefined')) {
		const web3 = new Web3(window.web3.currentProvider || 'http://localhost:7545')
		dispatch(web3Loaded(web3))
		return web3
	} else {
		redirect();
	}}
```

**function to get account:**

```
    export const _loadAccount = async (web3, dispatch) => {
	const accounts = await web3.eth.getAccounts()
	const account = await accounts[0]
	if(typeof account !== 'undefined'){
		dispatch(web3AccountLoaded(account))
		return account
	} else {
		window.alert('account is undefined')
	}}
```

**part of package.json:**

```
    "dependencies": {
        "truffle-hdwallet-provider": "1.0.4",
        "truffle-hdwallet-provider-privkey": "1.0.3",
        "web3": "1.0.0-beta.46"},
```

I've tried different versions of web3, however usually the result was even worst also I've tried to makes changes with web3 like:

`const web3 = new Web3(Web3.givenProvider || 'http://localhost:7545')`

however it didn't help aswell. 

I've run out of the ideas, can anybody help me with that?

**Comment by yathartharora** [comment]
I am facing the same issue....Have you resolved the issue?

**Comment by PabloMunaretto** [comment]
Same here, did anyone solved it ?

**Comment by PabloMunaretto** [comment]
I've changed the method getAccounts() for requestAccounts() and worked, don't know why.
