### ISSUE TITLE
How to get the return value of encoded getter functions of contract

### ISSUE THREAD

**Issue by saarshah** [ethereum/web3.js#3275]
#### Expected behavior
N/A.. Need Some feature/solution
#### Steps to reproduce the behavior

I have list of encoded functions of my contract,  one of them is as below i.e.   `0x27e235e30000000000000000000000000000000000000000000000000000000000000000............` . In this encoded  (getter ) function,  there may be two, three or more arguments with valid values as per contract logic. As per contract, this getter function return some value (say.. uint), after successful executing transaction.  I have to call this getter function (0x27e235e3.........) alongwith its arguments values (which are embeded in it). Upon successful calling this funciton, web3 gives me transaction receipt. But I needs its return values.. which i have to store into my local variable.
```
try {
        await web3.eth.sendTransaction(
        {from:account1,
        to:myContAddr,
        data: myFunc /// here i am giving encoded function...
            }).then(function(res){
              console.log("Normal Getter", res); /// this return receipt, as expected.. but i need to get return value of contract function
              myResult.push(res);
          });
    } catch (error) {
      console.log(" Normal Getters: ERROR !"); 
    }
```
Should I have to decode such encoded function to extract arguments and methodID separately, and then call it ???
#### Logs
n/a
#### Versions
[NPM : 6.13.0, Node v10.17.0, Web3.js, OS : Windows10, ]

**Comment by nivida** [comment]
Thanks for opening this issue! The ``sendTransaction`` call does only return the transaction hash and we are able to get the receipt with his logs but not the actual return value of the contract method. There was once a [proposal](https://github.com/ethereumproject/wiki/wiki/sendTransaction-return-value-proposal) to improve this back in 2015 but as it looks like did no one push it further. The current solution would be to emit those values as an event and to decode those or to have a call method that does return those values (depends on your contract). I can recommend you to use the web3 [Contract](https://web3js.readthedocs.io/en/v1.2.4/web3-eth-contract.html) object which handles anything nicely for you.

I will discuss this closer with @cgewecke and we will try to re-open this proposal if possible.

**Comment by saarshah** [comment]
Thanks for your consideration .. but Contract object does not fulfill my use case scenario... i must have to call getter function with encoded values (including its parameters...), whereas contract object need parameters values (which i have not except in encoded value) ... So, **how to decode such encoded values for my getter parameters/arguments list ?**
