### ISSUE TITLE
 Error: Cannot have more than 45 oracles

### ISSUE THREAD

**Issue by saarshah** [ethereum/web3.js#3286]
#### Expected behavior
Contract should be deployed
#### Actual behavior
Gives error of VM Exception while processing transaction: revert cannot have more than 45 oracles
#### Steps to reproduce the behavior

1. Download the smart contract [from Etherscan.io ](https://etherscan.io/address/0x25fa978ea1a7dc9bdc33a2959b9053eae57169b5#code)
2. Run Ganache GUI
3. Write following code to deploy the said contract
```
const options = {
      data: '0x' + myBin[0]+constructorParams[0],
      gas: 5000000,
  };
  const signed = await web3.eth.accounts.signTransaction(options, privateKey1);
  const receipt = await web3.eth.sendSignedTransaction(signed.rawTransaction);
  console.log("Contract: " +r+" is deployed at  " +receipt.contractAddress);
```
in above 
`myBin[0] = 608060405260016004556001600d553480156200001b57600080fd5b506040516200317738038062003177833981018060405281019080805190602001909291908051906020019092919080519060200190929190805182019291906020018051820192919050505033600660006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550620000c385620000eb640100000000026401000000009004565b620000e0848484846200012f640100000000026401000000009004565b50505050506200055e565b80600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156200018c57600080fd5b826fffffffffffffffffffffffffffffffff168282602d8251111515156200021c576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260208152602001807f63616e6e6f742068617665206d6f7265207468616e203435206f7261636c657381525060200191505060405180910390fd5b82825110151515620002bc576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602f8152602001807f6d7573742068617665206174206c65617374206173206d616e79206f7261636c81526020017f657320617320726573706f6e736573000000000000000000000000000000000081525060400191505060405180910390fd5b805182511415156200035c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c8152602001807f6d75737420686176652065786163746c79206173206d616e79206f7261636c6581526020017f73206173206a6f6220494473000000000000000000000000000000000000000081525060400191505060405180910390fd5b86600a60006101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff16021790555085600a60106101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff16021790555083600b9080519060200190620003e692919062000409565b5084600c9080519060200190620003ff92919062000461565b5050505050505050565b8280548282559060005260206000209081019282156200044e579160200282015b828111156200044d5782518290600019169055916020019190600101906200042a565b5b5090506200045d9190620004f0565b5090565b828054828255906000526020600020908101928215620004dd579160200282015b82811115620004dc5782518260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055509160200191906001019062000482565b5b509050620004ec919062000518565b5090565b6200051591905b8082111562000511576000816000905550600101620004f7565b5090565b90565b6200055b91905b808211156200055757600081816101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055506001016200051f565b5090565b90565b612c09806200056e6000396000f300608060405260043610610112576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806333bfcdd8146101175780633ea478aa1461015c5780634162cc88146101b757806350d25bcd1461020057806354bcd7ff1461022b5780635b69a7d81461027a5780635cd9b90b146102e7578063668a0f02146103345780636a9705b41461035f578063715018a61461039a57806378a66674146103b15780638205bf6a1461049257806383197ef0146104bd5780638da5cb5b146104d4578063b5ab58dc1461052b578063b633620c1461056c578063c35905c6146105ad578063daa6d556146105fc578063eecea00014610613578063f2fde38b14610662575b600080fd5b34801561012357600080fd5b5061015a600480360381019080803560001916906020019092919080359060200190929190803590602001909291905050506106a5565b005b34801561016857600080fd5b5061019d600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610941565b604051808215151515815260200191505060405180910390f35b3480156101c357600080fd5b506101e260048036038101908080359060200190929190505050610961565b60405180826000191660001916815260200191505060405180910390f35b34801561020c57600080fd5b50610215610984565b6040518082815260200191505060405180910390f35b34801561023757600080fd5b506102406109a1565b60405180826fffffffffffffffffffffffffffffffff166fffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561028657600080fd5b506102a5600480360381019080803590602001909291905050506109c3565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3480156102f357600080fd5b50610332600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610a01565b005b34801561034057600080fd5b50610349610bc0565b6040518082815260200191505060405180910390f35b34801561036b57600080fd5b50610398600480360381019080803560001916906020019092919080359060200190929190505050610bca565b005b3480156103a657600080fd5b506103af610cae565b005b3480156103bd57600080fd5b5061049060048036038101908080356fffffffffffffffffffffffffffffffff16906020019092919080356fffffffffffffffffffffffffffffffff1690602001909291908035906020019082018035906020019080806020026020016040519081016040528093929190818152602001838360200280828437820191505050505050919291929080359060200190820180359060200190808060200260200160405190810160405280939291908181526020018383602002808284378201915050505050509192919290505050610db3565b005b34801561049e57600080fd5b506104a7611085565b6040518082815260200191505060405180910390f35b3480156104c957600080fd5b506104d26110a2565b005b3480156104e057600080fd5b506104e9611246565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561053757600080fd5b506105566004803603810190808035906020019092919050505061126c565b6040518082815260200191505060405180910390f35b34801561057857600080fd5b5061059760048036038101908080359060200190929190505050611289565b6040518082815260200191505060405180910390f35b3480156105b957600080fd5b506105c26112a6565b60405180826fffffffffffffffffffffffffffffffff166fffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561060857600080fd5b506106116112c8565b005b34801561061f57600080fd5b50610660600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803515159060200190929190505050611640565b005b34801561066e57600080fd5b506106a3600480360381019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506116f7565b005b6000600e60003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff168061074c5750600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16145b15156107e6576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602f8152602001807f4e6f7420616e20617574686f72697a6564206164647265737320666f7220637281526020017f656174696e67207265717565737473000000000000000000000000000000000081525060400191505060405180910390fd5b600f60008560001916600019168152602001908152602001600020549050600954811015156108a3576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260238152602001807f43616e6e6f74206d6f6469667920616e20696e2d70726f677265737320616e7381526020017f776572000000000000000000000000000000000000000000000000000000000081525060400191505060405180910390fd5b600f6000856000191660001916815260200190815260200160002060009055601060008281526020019081526020016000206001016000908060018154018082558091505090600182039060005260206000200160009091929091909150555061090c8161175f565b61093b8484636a9705b47c01000000000000000000000000000000000000000000000000000000000285611836565b50505050565b600e6020528060005260406000206000915054906101000a900460ff1681565b600b8181548110151561097057fe5b906000526020600020016000915090505481565b600060116000600954815260200190815260200160002054905090565b600a60109054906101000a90046fffffffffffffffffffffffffffffffff1681565b600c818154811015156109d257fe5b906000526020600020016000915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610a5f57600080fd5b610a676119d1565b90508073ffffffffffffffffffffffffffffffffffffffff1663a9059cbb84846040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b158015610b0c57600080fd5b505af1158015610b20573d6000803e3d6000fd5b505050506040513d6020811015610b3657600080fd5b81019080805190602001909291905050501515610bbb576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260148152602001807f4c494e4b207472616e73666572206661696c656400000000000000000000000081525060200191505060405180910390fd5b505050565b6000600954905090565b6000610bd5836119fb565b600f60008460001916600019168152602001908152602001600020549050600f6000846000191660001916815260200190815260200160002060009055601060008281526020019081526020016000206001018290806001815401808255809150509060018203906000526020600020016000909192909190915055503373ffffffffffffffffffffffffffffffffffffffff1681837fb51168059c83c860caf5b830c5d2e64c2172c6fb2fe9f25447d9838e18d93b6060405160405180910390a4610ca081611b73565b610ca98161175f565b505050565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610d0a57600080fd5b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff167ff8df31144d9c2f0f6b59d69b8b98abd5459d07f2742c4df920b25aae33c6482060405160405180910390a26000600660006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610e0f57600080fd5b826fffffffffffffffffffffffffffffffff168282602d825111151515610e9e576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260208152602001807f63616e6e6f742068617665206d6f7265207468616e203435206f7261636c657381525060200191505060405180910390fd5b82825110151515610f3d576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602f8152602001807f6d7573742068617665206174206c65617374206173206d616e79206f7261636c81526020017f657320617320726573706f6e736573000000000000000000000000000000000081525060400191505060405180910390fd5b80518251141515610fdc576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c8152602001807f6d75737420686176652065786163746c79206173206d616e79206f7261636c6581526020017f73206173206a6f6220494473000000000000000000000000000000000000000081525060400191505060405180910390fd5b86600a60006101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff16021790555085600a60106101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff16021790555083600b90805190602001906110649291906129b0565b5084600c908051906020019061107b929190612a03565b5050505050505050565b600060126000600954815260200190815260200160002054905090565b6000600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561110057600080fd5b6111086119d1565b905061120b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff166370a08231306040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b1580156111cb57600080fd5b505af11580156111df573d6000803e3d6000fd5b505050506040513d60208110156111f557600080fd5b8101908080519060200190929190505050610a01565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600060116000838152602001908152602001600020549050919050565b600060126000838152602001908152602001600020549050919050565b600a60009054906101000a90046fffffffffffffffffffffffffffffffff1681565b6112d0612a8d565b6000806000600e60003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff168061137a5750600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16145b1515611414576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602f8152602001807f4e6f7420616e20617574686f72697a6564206164647265737320666f7220637281526020017f656174696e67207265717565737473000000000000000000000000000000000081525060400191505060405180910390fd5b600a60009054906101000a90046fffffffffffffffffffffffffffffffff166fffffffffffffffffffffffffffffffff169150600090505b600c80549050811015611517576114a0600b8281548110151561146b57fe5b906000526020600020015430636a9705b47c010000000000000000000000000000000000000000000000000000000002611e5c565b93506114e6600c828154811015156114b457fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff168584611e8d565b9250600d54600f6000856000191660001916815260200190815260200160002081905550808060010191505061144c565b600a60109054906101000a90046fffffffffffffffffffffffffffffffff1660106000600d54815260200190815260200160002060000160006101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff160217905550600c8054905060106000600d54815260200190815260200160002060000160106101000a8154816fffffffffffffffffffffffffffffffff02191690836fffffffffffffffffffffffffffffffff1602179055506115ee6001600d5461221990919063ffffffff16565b600d819055503373ffffffffffffffffffffffffffffffffffffffff16600d547fc3c45d1924f55369653f407ee9f095309d1e687b2c0011b1f709042d4f457e1760405160405180910390a350505050565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561169c57600080fd5b80600e60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561175357600080fd5b61175c81612235565b50565b806010600082815260200190815260200160002060000160109054906101000a90046fffffffffffffffffffffffffffffffff166fffffffffffffffffffffffffffffffff16601060008381526020019081526020016000206001018054905014156118325760106000838152602001908152602001600020600080820160006101000a8154906fffffffffffffffffffffffffffffffff02191690556000820160106101000a8154906fffffffffffffffffffffffffffffffff021916905560018201600061182f9190612afb565b50505b5050565b600060056000866000191660001916815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905060056000866000191660001916815260200190815260200160002060006101000a81549073ffffffffffffffffffffffffffffffffffffffff021916905584600019167fe1fe3afa0f7f761ff0a8b89086790efd5140d2907ebd5b7ff6bfcb5e075fd4c560405160405180910390a28073ffffffffffffffffffffffffffffffffffffffff16636ee4d553868686866040518563ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808560001916600019168152602001848152602001837bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19168152602001828152602001945050505050600060405180830381600087803b1580156119b257600080fd5b505af11580156119c6573d6000803e3d6000fd5b505050505050505050565b6000600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b8060056000826000191660001916815260200190815260200160002060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515611b00576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260288152602001807f536f75726365206d75737420626520746865206f7261636c65206f662074686581526020017f207265717565737400000000000000000000000000000000000000000000000081525060400191505060405180910390fd5b60056000826000191660001916815260200190815260200160002060006101000a81549073ffffffffffffffffffffffffffffffffffffffff021916905580600019167f7cc135e0cebb02c3480ae5d74d377283180a2601f8f644edf7987b009316c63a60405160405180910390a25050565b6000806000806000856010600082815260200190815260200160002060000160009054906101000a90046fffffffffffffffffffffffffffffffff166fffffffffffffffffffffffffffffffff166010600083815260200190815260200160002060010180549050101515611e53578680600954111515611e515760106000898152602001908152602001600020600101805490509650611c1e60028861233190919063ffffffff16565b95506000600288811515611c2e57fe5b061415611d4e57611ca3601060008a8152602001908152602001600020600101805480602002602001604051908101604052809291908181526020018280548015611c9857602002820191906000526020600020905b815481526020019060010190808311611c84575b505050505087612347565b9350611d26601060008a8152602001908152602001600020600101805480602002602001604051908101604052809291908181526020018280548015611d0857602002820191906000526020600020905b815481526020019060010190808311611cf4575b5050505050611d2160018961221990919063ffffffff16565b612347565b92506002611d3d848661257590919063ffffffff16565b811515611d4657fe5b059450611dd2565b611dcf601060008a8152602001908152602001600020600101805480602002602001604051908101604052809291908181526020018280548015611db157602002820191906000526020600020905b815481526020019060010190808311611d9d575b5050505050611dca60018961221990919063ffffffff16565b612347565b94505b84600781905550876009819055504260088190555042601260008a81526020019081526020016000208190555084601160008a81526020019081526020016000208190555087857f0559884fd3a460db3073b7fc896cc77986f16e378210ded43186175bf646fc5f426040518082815260200191505060405180910390a35b505b50505050505050565b611e64612a8d565b611e6c612a8d565b611e8385858584612648909392919063ffffffff16565b9150509392505050565b600030600454604051602001808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c01000000000000000000000000028152601401828152602001925050506040516020818303038152906040526040518082805190602001908083835b602083101515611f295780518252602082019150602081019050602083039250611f04565b6001836020036101000a038019825116818451168082178552505050505050905001915050604051809103902090506004548360600181815250508360056000836000191660001916815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080600019167fb5e6e01e79f91267dc17b4e6314d5d4d03593d2ceee0fbb452b750bd70ea5af960405160405180910390a2600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16634000aea0858461203887612702565b6040518463ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b838110156120db5780820151818401526020810190506120c0565b50505050905090810190601f1680156121085780820380516001836020036101000a031916815260200191505b50945050505050602060405180830381600087803b15801561212957600080fd5b505af115801561213d573d6000803e3d6000fd5b505050506040513d602081101561215357600080fd5b810190808051906020019092919050505015156121fe576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260238152602001807f756e61626c6520746f207472616e73666572416e6443616c6c20746f206f726181526020017f636c65000000000000000000000000000000000000000000000000000000000081525060400191505060405180910390fd5b60016004600082825401925050819055508090509392505050565b6000818301905082811015151561222c57fe5b80905092915050565b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415151561227157600080fd5b8073ffffffffffffffffffffffffffffffffffffffff16600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e060405160405180910390a380600660006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b6000818381151561233e57fe5b04905092915050565b600060606000806060806000806000808b98508a975088519650866040519080825280602002602001820160405280156123905781602001602082028038833980820191505090505b509550866040519080825280602002602001820160405280156123c25781602001602082028038833980820191505090505b5094505b60011561256557886123e260028961233190919063ffffffff16565b8151811015156123ee57fe5b9060200190602002015191506000935060009250600090505b868110156124d95781898281518110151561241e57fe5b90602001906020020151121561246f57888181518110151561243c57fe5b90602001906020020151868581518110151561245457fe5b906020019060200201818152505083806001019450506124cc565b81898281518110151561247e57fe5b9060200190602002015113156124cb57888181518110151561249c57fe5b9060200190602002015185848151811015156124b457fe5b906020019060200201818152505082806001019350505b5b8080600101915050612407565b83881115156124fc578396506124ef898761292d565b809750819a505050612560565b61250f838861293d90919063ffffffff16565b8811156125575761253b61252c848961293d90919063ffffffff16565b8961293d90919063ffffffff16565b975082965061254a898661292d565b809650819a50505061255f565b819950612566565b5b6123c6565b5b50505050505050505092915050565b60008082840190506000831215801561258e5750838112155b806125a457506000831280156125a357508381125b5b151561263e576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260218152602001807f5369676e6564536166654d6174683a206164646974696f6e206f766572666c6f81526020017f770000000000000000000000000000000000000000000000000000000000000081525060400191505060405180910390fd5b8091505092915050565b612650612a8d565b6126608560800151610100612956565b50838560000190600019169081600019168152505082856020019073ffffffffffffffffffffffffffffffffffffffff16908173ffffffffffffffffffffffffffffffffffffffff16815250508185604001907bffffffffffffffffffffffffffffffffffffffffffffffffffffffff191690817bffffffffffffffffffffffffffffffffffffffffffffffffffffffff191681525050849050949350505050565b6060600360009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16634042994690507c01000000000000000000000000000000000000000000000000000000000260008084600001518560200151866040015187606001516001896080015160000151604051602401808973ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200188815260200187600019166000191681526020018673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001857bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200184815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b83811015612890578082015181840152602081019050612875565b50505050905090810190601f1680156128bd5780820380516001836020036101000a031916815260200191505b509950505050505050505050604051602081830303815290604052907bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050509050919050565b6060808284915091509250929050565b600082821115151561294b57fe5b818303905092915050565b61295e612b1c565b600060208381151561296c57fe5b061415156129895760208281151561298057fe5b06602003820191505b81836020018181525050604051808452600081528281016020016040525082905092915050565b8280548282559060005260206000209081019282156129f2579160200282015b828111156129f15782518290600019169055916020019190600101906129d0565b5b5090506129ff9190612b36565b5090565b828054828255906000526020600020908101928215612a7c579160200282015b82811115612a7b5782518260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555091602001919060010190612a23565b5b509050612a899190612b5b565b5090565b60c06040519081016040528060008019168152602001600073ffffffffffffffffffffffffffffffffffffffff16815260200160007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200160008152602001612af5612b9e565b81525090565b5080546000825590600052602060002090810190612b199190612bb8565b50565b604080519081016040528060608152602001600081525090565b612b5891905b80821115612b54576000816000905550600101612b3c565b5090565b90565b612b9b91905b80821115612b9757600081816101000a81549073ffffffffffffffffffffffffffffffffffffffff021916905550600101612b61565b5090565b90565b604080519081016040528060608152602001600081525090565b612bda91905b80821115612bd6576000816000905550600101612bbe565b5090565b905600a165627a7a7230582088c9834b5e82d9005576043710306a30d2d8cf09855b4f492b292d260b01ba260029`
[in constructorParams[0] = 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000](url)
#### Logs
```
UnhandledPromiseRejectionWarning: Error: Returned error: VM Exception while processing transaction: revert cannot have more than 45 oracles
    at Object.ErrorResponse (C:\Users\aa\node_modules\web3-core-helpers\src\errors.js:29:16)
    at C:\Users\aa\node_modules\web3-core-requestmanager\src\index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (C:\Users\aa\node_modules\web3-providers-http\src\index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\aa\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\Users\aa\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\aa\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (C:\Users\aa\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:13380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
#### Versions
[NPM : 6.13.0, Node: v10.17.0, Web3.js, OS: Windows 10,

**Comment by nivida** [comment]
@saarshah Thanks for opening this issue! web3.js does act correctly and rejects the ``Promise`` on an EVM revert instruction (A improved revert handling with more details returned will get released with the next version of web3). The max. value of ``45`` oracles is defined in the contract on line ``995`` you have referenced above.
