### ISSUE TITLE
No Bloom-related functions in web3.utils? 

### ISSUE THREAD

**Issue by jmahhh** [ethereum/web3.js#3290]
#### Expected behavior
`web3.utils.isTopicInBloom` is a function, [as documented](https://web3js.readthedocs.io/en/v1.2.4/web3-utils.html#bloom-filters). 

#### Actual behavior
`web3.utils.isTopicInBloom` is not a function. All bloom related functions in the documentation appear to be absent from `web3.utils`.

#### Steps to reproduce the behavior
Try to access any bloom related functions in `web3.utils`. 

#### Logs
`error undefined: TypeError: web3.utils.isTopicInBloom is not a function`

#### Versions
web3 1.2.4

**Comment by joshstevens19** [comment]
Hey thanks for raising this, it looks like it was forgotten to export these functions on the `index.js` on the utils package, this PR fixes that > https://github.com/ethereum/web3.js/pull/3291

If you're eager to use the bloom filters features and don't want to wait for a new web3 release to come out you can install `ethereum-bloom-filter` package directly. All web3js does is export functions from that package so to avoid waiting for a new web3js release you can download it directly here > https://www.npmjs.com/package/ethereum-bloom-filters

Will close ticket as this is now fixed (once merged), a solution in how to get around this without waiting is highlighted as well. This will be in the next web3js release. Thanks
