### ISSUE TITLE
web3-eth-accounts TypeScript definition file is broken (and/or confusing)

### ISSUE THREAD

**Issue by smithki** [ethereum/web3.js#3292]
#### Expected behavior

TypeScript definition file should reflect that `Accounts` is the _default_ export, not a named export.

#### Actual behavior

TypeScript compiler raises an error when attempting to import `Accounts` as the default export, but we reach a runtime TypeError if we import `Accounts` as a named export.

#### Steps to reproduce the behavior

1. Try this code snippet in a TypeScript file:

```ts
import { Accounts } from 'web3-eth-accounts';

new Accounts() // TypeScript does not complain
// => TypeError: "Accounts is not a constructor"
```

2. For comparison:

```ts
import Accounts from 'web3-eth-accounts';

new Accounts() // TypeScript complains with: "This expression is not constructable."
// => works at runtime...
```

#### Versions
`web3-eth-accounts@1.2.4`

**Comment by nivida** [comment]
Thanks for opening this issue! Have you followed our TS guidance [here](https://github.com/ethereum/web3.js#usage-with-typescript) which does require additional configuration? 

~~Btw.: We can't change this that easy because it would break many already existing projects.~~

Edit: Sorry, it is possible to change it in a non-breaking manner we would only have to export it named and as default from the same file.

**Comment by smithki** [comment]
> Btw.: We can't change this that easy because it would break many already existing projects.

I see this as a _bug_, though. Considering the expected behavior does not currently work, I do not understand how it can be considered a breaking change. Thankfully, there is a workaround using declaration merging:

```ts
import { AccountsBase } from 'web3-core';
import Accounts from 'web3-eth-accounts';

declare module 'web3-eth-accounts' {
  export default class Accounts extends AccountsBase {}
}
```

**Comment by GregTheGreek** [comment]
We are re-assessing this. There are a few inconsistencies within the deceleration files. Feel free to follow along on #3606 for updates

**Comment by smithki** [comment]
_bump_

**Comment by smithki** [comment]
_bump_

**Comment by ariesjia** [comment]
#3732 has fixed this issue， please review and merge ,related to #3198
