### ISSUE TITLE
Add project scope

### ISSUE THREAD

**Issue by fulldecent** [ethereum/web3.js#3293]
This artifact is now about 1MB compressed. It is so large that projects are working around it and creating their own slim versions.

Could the scope of this project (what should be included and what should not) please be added to the main README? This will help stop scope creep and set a reasonable project goal that we can all work towards.

**Comment by nivida** [comment]
The bundle size of web3.js will get improved with de-duplicating of the dependency tree in 1.0 and we will provide new ways to import functionalities from web3.js in the most tree shakable way with 2.0. 
But we will definitely add a section to the README to explain the exact scope of this project. Thanks!

**Comment by ruzyysmartt** [comment]
Eth:
Blockchain

More info:
Ruziisemat

 Contract 0x62991A1B4187481C8B5BB49Fa567711e09fF488D 
 
Contract Overview
Balance:
9.722843596414808444 Ether
Value:
$1,466.69 


 My Name Tag:
Ruzyysmarrt Ethereum 

Creator:
0x851cc731ce1613ae4fd8ec7f61f4b350f9ce1020
Transactions
Internal Txns
Erc20 Token Txns

Txn Hash	Block	Age	From		To	Value	[Txn Fee]
0xa0e04cc6ea9d382fa24474393e2acb1884e0235ecf36640900adcbc98fc95143	9278954	13 mins ago	0x8873b045d40a458e46e356a96279ae1820a898ba	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	34 Ether	0.000185872
0xdb1599d126bd82b40e20202aa3cbe350c299ac0dd840df3580d18310f8723a24	9222152	8 days 16 hrs ago	0xf8ef4ec06cf5814a3df097519d800a99cba1ad23	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	120.67761653 Ether	0.000069702
0xb9bfdc1e506c2e1d34772fe6fb8bc83ed05d2f8a84e451063f30692ad83b1140	9219719	9 days 1 hr ago	0x8873b045d40a458e46e356a96279ae1820a898ba	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	90 Ether	0.0001370806
0x487a743ee24f8cdb421bf6d00ccf78762b8b6c4dc9183606c8b4e8f471589387	9219670	9 days 1 hr ago	0x8873b045d40a458e46e356a96279ae1820a898ba	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	80 Ether	0.000185872
0x6068ef113da14df52bcc779d06087dd04d1684813ba5872a6e0044b335960c2a	9216012	9 days 15 hrs ago	0x17d38262ceb5317af645a246b0ce6fc4cc3088f6	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	13.5 Ether	0.0000743488
 0x17f0607e29e75963529a2fb59537c77a5be7131fcbe87e3facfff29794e70c6e	9216002	9 days 15 hrs ago	0x17d38262ceb5317af645a246b0ce6fc4cc3088f6	 IN 	 0x62991a1b4187481c8b5bb49fa567711e09ff488d	13.5 Ether	0.000068124
[ Download CSV Export  ] 





The proxy contract verification completed with the message:

The proxy's (0x62991A1B4187481C8B5BB49Fa567711e09fF488D) implementation contract is found at: 0xb1dd690cc9af7bb1a906a9b5a94f94191cc553ce
If this is correct, please click Save and the implementation address will be saved. 

Successfully saved. Feel free to return to the address 0x62991A1B4187481C8B5BB49Fa567711e09fF488D to view updates.
 Latest 25 Contract Events
Tip: Event Logs are used by developers/external UI providers for keeping track of contract actions and for auditing
Txn Hash	Method	Event Logs
0xcc14343962beb74bfd5420bb8d7c8e1d9f960a9176c599b1ea24254c98e961a4
# 9278987 
41 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 b3b77a5100000000000000000000000000000000000000000000000000000000
 00025a33000000000000000000000000000000000000000000000000b1a2bc2e
 c5000000
0xcc14343962beb74bfd5420bb8d7c8e1d9f960a9176c599b1ea24254c98e961a4
# 9278987 
41 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000f53ad2c6851052a81b42133467480961b2321c09
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000448a5065aebb8e423f0896e6c5d525c0
 40f59af3000000000000000000000000000000000000000000000000b1a2bc2e
 c5000000
0xcc14343962beb74bfd5420bb8d7c8e1d9f960a9176c599b1ea24254c98e961a4
# 9278987 
41 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000024
 049878f3000000000000000000000000000000000000000000000000b1a2bc2e
 c5000000
0xcc14343962beb74bfd5420bb8d7c8e1d9f960a9176c599b1ea24254c98e961a4
# 9278987 
41 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000448a5065aebb8e423f0896e6c5d525c0
 40f59af3000000000000000000000000000000000000000000000000ba5a15c6
 53cba60a
0xcc14343962beb74bfd5420bb8d7c8e1d9f960a9176c599b1ea24254c98e961a4
# 9278987 
41 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
[topic3] 0x000000000000000000000000000000000000000000000000ba5a15c653cba60a
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000004
 d0e30db0
0xf38e855b8dceac6bf5dd310d3a0e8b69ace34ee63324ed1d8b882e725a9ebc7b
# 9278979 
44 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000ed0da07aab7257df53efc4dfc076745744138ed9
[topic2] 0x000000000000000000000000a5c603e1c27a96171487aea0649b01c56248d2e8
[topic3] 0x0000000000000000000000000000000000000000000000000069c3e3108e126a
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000000
0xf38e855b8dceac6bf5dd310d3a0e8b69ace34ee63324ed1d8b882e725a9ebc7b
# 9278979 
44 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000ed0da07aab7257df53efc4dfc076745744138ed9
[topic2] 0x000000000000000000000000818e6fecd516ecc3849daf6845e3ec868087b755
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 00000000000000000000000000000000000000000000000000000000000000e4
 cb3c28c700000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a
 232603590000000000000000000000000000000000000000000000a1dfb8675e
 9f9fe9bd000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
 eeeeeeee00000000000000000000000062991a1b4187481c8b5bb49fa567711e
 09ff488d0000000000000000000000000000000000000000000000022608b6da
 c2d919ee00000000000000000000000000000000000000000000000000176087
 b41c7653000000000000000000000000a5c603e1c27a96171487aea0649b01c5
 6248d2e8
0xf38e855b8dceac6bf5dd310d3a0e8b69ace34ee63324ed1d8b882e725a9ebc7b
# 9278979 
44 mins ago	0xaacaaf88	Received (index_topic_1 uint256 value, index_topic_2 address sender, bytes data)
[topic0] 0x606834f57405380c4fb88d1f4850326ad3885f014bab3b568dfbf7a041eef738
[topic1] 0x000000000000000000000000000000000000000000000001136e1f5071faab0b
[topic2] 0x00000000000000000000000065bf64ff5f51272f729bdcd7acfb00677ced86cd
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000000
0xf38e855b8dceac6bf5dd310d3a0e8b69ace34ee63324ed1d8b882e725a9ebc7b
# 9278979 
44 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000ed0da07aab7257df53efc4dfc076745744138ed9
[topic2] 0x00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000818e6fecd516ecc3849daf6845e3ec86
 8087b7550000000000000000000000000000000000000000000000a1dfb8675e
 9f9fe9bd
0x67a932442250380df01997c25c99249b733dc823ceb4ecc92414a9d1829d035a
# 9278964 
47 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 440f19ba00000000000000000000000000000000000000000000000000000000
 00025a330000000000000000000000000000000000000000000000a1dfb8675e
 9f9fe9bd
0x5e35875d4a46e9e0e2029c1ccf58a8d9e6ac08bbd3b8136f2814b4d07d1f8787
# 9278957 
49 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 b3b77a5100000000000000000000000000000000000000000000000000000000
 00025a33000000000000000000000000000000000000000000000001a055690d
 9db80000
0x5e35875d4a46e9e0e2029c1ccf58a8d9e6ac08bbd3b8136f2814b4d07d1f8787
# 9278957 
49 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000f53ad2c6851052a81b42133467480961b2321c09
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000448a5065aebb8e423f0896e6c5d525c0
 40f59af3000000000000000000000000000000000000000000000001a055690d
 9db80000
0x5e35875d4a46e9e0e2029c1ccf58a8d9e6ac08bbd3b8136f2814b4d07d1f8787
# 9278957 
49 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000024
 049878f3000000000000000000000000000000000000000000000001a055690d
 9db80000
0x5e35875d4a46e9e0e2029c1ccf58a8d9e6ac08bbd3b8136f2814b4d07d1f8787
# 9278957 
49 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000448a5065aebb8e423f0896e6c5d525c0
 40f59af3000000000000000000000000000000000000000000000001b4c32308
 d4654d28
0x5e35875d4a46e9e0e2029c1ccf58a8d9e6ac08bbd3b8136f2814b4d07d1f8787
# 9278957 
49 mins ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
[topic3] 0x000000000000000000000000000000000000000000000001b4c32308d4654d28
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000004
 d0e30db0
0xa0e04cc6ea9d382fa24474393e2acb1884e0235ecf36640900adcbc98fc95143
# 9278954 
50 mins ago	0x	Received (index_topic_1 uint256 value, index_topic_2 address sender, bytes data)
[topic0] 0x606834f57405380c4fb88d1f4850326ad3885f014bab3b568dfbf7a041eef738
[topic1] 0x000000000000000000000000000000000000000000000001d7d843dc3b480000
[topic2] 0x0000000000000000000000008873b045d40a458e46e356a96279ae1820a898ba
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000000
0xff04b98caed83a9b7f1e6c6b19631afd431e39db866f6da01e70edd5dfb40e98
# 9248708 
4 days 15 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x0000000000000000000000002b6d87f12b106e1d3fa7137494751566329d1045
[topic2] 0x0000000000000000000000006b175474e89094c44da98b954eedeac495271d0f
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 a9059cbb0000000000000000000000008873b045d40a458e46e356a96279ae18
 20a898ba0000000000000000000000000000000000000000000000011421d3bc
 9b0d80d2
0x796d6dcedf12ccdb63c423ab7b6fdf1a2e566418e341e91eb6b8d886a28240de
# 9248702 
4 days 15 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000a5d7d68d7975e89feb240f42fed1d77bb71b1caf
[topic2] 0x0000000000000000000000005d3a536e4d6dbd6114cc1ead35777bab948e3643
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000024
 db006a7500000000000000000000000000000000000000000000000000000017
 1524aee3
0xeedcd28d17c2ed76beae084742c427750b7db59f3aa8688c74e7980e090c0687
# 9241395 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000a5d7d68d7975e89feb240f42fed1d77bb71b1caf
[topic2] 0x0000000000000000000000005d3a536e4d6dbd6114cc1ead35777bab948e3643
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000024
 a0712d6800000000000000000000000000000000000000000000006edcfa622e
 826d839b
0xeedcd28d17c2ed76beae084742c427750b7db59f3aa8688c74e7980e090c0687
# 9241395 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000a5d7d68d7975e89feb240f42fed1d77bb71b1caf
[topic2] 0x0000000000000000000000006b175474e89094c44da98b954eedeac495271d0f
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b30000000000000000000000005d3a536e4d6dbd6114cc1ead35777bab
 948e364300000000000000000000000000000000000000000000006edcfa622e
 826d839b
0xbee160ba541086563614af4aa22fae87ad140a708022027bec0bdf811e341adb
# 9241387 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x0000000000000000000000007557f4199aa99e5396330bac3b7bdaa262cb1913
[topic2] 0x000000000000000000000000c73e0383f3aff3215e6f04b0331d58cecf0ab849
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000024
 fbabdebd00000000000000000000000000000000000000000000006edcfa622e
 826d839b
0xbee160ba541086563614af4aa22fae87ad140a708022027bec0bdf811e341adb
# 9241387 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x0000000000000000000000007557f4199aa99e5396330bac3b7bdaa262cb1913
[topic2] 0x00000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000c73e0383f3aff3215e6f04b0331d58ce
 cf0ab84900000000000000000000000000000000000000000000006edcfa622e
 826d839b
0x4f6a692067b9cae89a70966b31a211d12ba20d3f0a580b1df23736af5acc5bd8
# 9241383 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 440f19ba00000000000000000000000000000000000000000000000000000000
 00025a3300000000000000000000000000000000000000000000006edcfa622e
 826d839b
0x4a924314a3e85a1a5db215940ef6b4a5eee35639fd4399fdc2a9aeb014923587
# 9241371 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 b3b77a5100000000000000000000000000000000000000000000000000000000
 00025a33000000000000000000000000000000000000000000000001158e4609
 13d00000
0x4a924314a3e85a1a5db215940ef6b4a5eee35639fd4399fdc2a9aeb014923587
# 9241371 
5 days 18 hrs ago	0xaacaaf88	[topic0] 0x7d2476ab50663f025cff0be85655bcf355f62768615c0c478f3cd5293f807365
[topic1] 0x000000000000000000000000963f86da34cf2ce619d4b8e5ce96577943f95b6b
[topic2] 0x000000000000000000000000f53ad2c6851052a81b42133467480961b2321c09
[topic3] 0x0000000000000000000000000000000000000000000000000000000000000000
 0000000000000000000000000000000000000000000000000000000000000020
 0000000000000000000000000000000000000000000000000000000000000044
 095ea7b3000000000000000000000000448a5065aebb8e423f0896e6c5d525c0
 40f59af3000000000000000000000000000000000000000000000001158e4609
 13d00000
