### ISSUE TITLE
Synchronous HTTP requests?

### ISSUE THREAD

**Issue by simov** [ethereum/web3.js#330]
:wave: 

I just noticed that the `web3.isConnected()` method for example is making synchronous request to the RPC server. On NodeJS you are using the [xmlhttprequest](https://github.com/driverdan/node-XMLHttpRequest) module internally, which in turn writes a file to the local file system, on each request, just to lock the process.

In case you don't like callbacks you can use [Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) with [Generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*) or even the nicer [async-await](https://github.com/tc39/ecmascript-asyncawait) interface (probably with [Babel](https://babeljs.io/) for the time being).

I personally don't think that relying on file system hacks is production ready approach, so my question is what is your opinion on that?

Thanks!

**Comment by frozeman** [comment]
The `isConnected` function is the only sync one. This is so you can write `if(web3.isConnected()){ ... }`.
Any better idea how to make this possible?

Also you're not forced to use this function in node and its not used internally.

**Comment by simov** [comment]
Ok, I was testing with some example code that uses the sync versions for almost all of the methods, but a quick search in your source code showed me that the send and sendAsync calls are equal number. If that's the case my bad, I won't use the `isConnected` method that's for sure :relieved:

**Comment by frozeman** [comment]
This method is intended for dapps, to check connection on start only once..

Any better idea for this?

**Comment by simov** [comment]
I'm not sure I understand the scenario. You can always have a state flag somewhere to indicate when the connection is established or lost. In fact this is what I'm going to do in my app, I'm going to execute my async RPC request on certain interval of time. Not perfect but it'll do for my case.

**Comment by frozeman** [comment]
The scenario is what you can see here, if you have no node running:
http://ethereum-dapp-wallet.meteor.com

**Comment by simov** [comment]
Nice demo @frozeman! Still I'm not getting what an asynchronous HTTP request have to do with your application logic? What exactly is the problem with having asynchronous `isConnected` method? What exactly you can't achieve with it? What's the benefits of having it synchronous?

**Comment by frozeman** [comment]
Writing `if(web3.isConnected()){ ... }`...
This sure could be done using:
```
web3.isConnected(function(e){
   if(!e) appInit();
})
```
But the latter is more convenient.

I will think about it again

**Comment by simov** [comment]
If the callbacks are the problem, in ES2016 you can have the following code:

```js
async function main () {
  if (await web3.isConnected()) {
    // do stuff as usual, even though isConnected is asynchronous
  }
}
```

Then you have modules that can convert your callback code into one returning Promises, so you're good to go. Still you have to use Babel for the time being, but `async-await` will be officially supported by all browser engines in less than a year.

Most importantly you won't fallback to using file system hacks on NodeJS.

**Comment by frozeman** [comment]
Looks promising, but i assume isConnected has to be changed internally to allow async return values.

**Comment by simov** [comment]
Yep, it should be regular function with a callback, that can be [promisified](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object) after that.

**Comment by simov** [comment]
```js
var web3 = require('web3')
var bluebird = require('bluebird')
require('babel/polyfill')

web3.eth.compile.solidity = bluebird.promisify(web3.eth.compile.solidity)

async function main () {
  try {
    // this is actually asynchronous
    var compiled = await web3.eth.compile.solidity('...')
  } catch (e) {
    console.log(e)
  }

  if (compiled) {
    // do stuff
  }
}

main()
```

So it's better to have asynchronous version for each method, including `isConnected`, as you can see there are no callback and still the code uses the asynchronous version.

You can use this `gulpfile` for testing:

```js
var gulp = require('gulp')
var sourcemaps = require('gulp-sourcemaps')
var babel = require('gulp-babel')

gulp.task('babel', function () {
  return gulp.src(['**/*.js', '!gulpfile.js', '!build/**/*.*'])
    .pipe(sourcemaps.init())
    .pipe(babel({
      optional: [
        'es7.asyncFunctions',
        'es7.exportExtensions'
      ]
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('build'))
})

gulp.task('default', ['babel'])
```

**Comment by tarrencev** [comment]
Using synchronous requests in javascript is an anti pattern, since execution is single threaded and it blocks the thread. I think it would be valuable to expose async interfaces to all the RPC calls by default, to encourage developers to use idiomatic javascript. It might necessitate some breaking changes, but would be the right course of action considering ethereum and this library is still in its infancy.

**Comment by frozeman** [comment]
@tarrencev i agree, it evolved this way due to internally hick hack ;)
We will get there. For now all is async, if you provide a callback.

**Comment by farhankhwaja** [comment]
I am trying to read a transactions inside a block using web3 and then pass on the result to another node server. But I am not able to do so. And I dont know what is wrong in this. Please if anyone can explain me. Below is my code:

```
for(var i=fromBlock,i<=toBlock;i++){
 var txs = web3.eth.getBlock(i).tranasctions;
 for(var k=0;k<txs.length;k++){
  var txData = web3.eth.getTransaction(txs[k]);
  var txReceipt = web3.eth.getTransactionReceipt(txs[k]);
  request,post({url: "<URL">, form: {txData: txData, txReceipt: txReceipt}});
 }
}
```
I want to send the transaction data and receipt. if anyone can help me with this. I think this is related to async/sync thing that you all just talked above
