### ISSUE TITLE
Cannot read property 'accounts' of undefined

### ISSUE THREAD

**Issue by DingGeng-GitHub** [ethereum/web3.js#3300]
web3.js：1.2.4

const web3 = require("web3");
var privateKey = "0x79e192e29236e84a060b0e0f74e4141166e41ff7bd4bf2183eef905bacd64f82";
var keystore = web3.eth.accounts.encrypt(privateKey,"123456");

请问我在调用这个方法时提示以下错误：
message: "Cannot read property 'accounts' of undefined"

请问这是什么原因？该怎么解决？

**Comment by nivida** [comment]
Thanks for opening this issue! Is it possible to follow the issue template we provide and to translate your issue into English?
