### ISSUE TITLE
CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by khuzama98** [ethereum/web3.js#3306]
i'm facing the issue of cors on firefox but not on chrome, on digging into the error i found that this error is originated from web.js file.

![web3](https://user-images.githubusercontent.com/44345364/72205255-aec95d80-34a2-11ea-80a7-0cc2630448d2.png)

Can anyone guide me on this matter.
Thanks

**Comment by nivida** [comment]
@khuzama98 Thanks for opening this issue! Could you update your issue to be aligned with the issue template we provide?
