### ISSUE TITLE
type AbiInput fails on TS compliation

### ISSUE THREAD

**Issue by vetri02** [ethereum/web3.js#3307]
#### Expected behavior
AbiItem should compile when using Typescript
#### Actual behavior
When compiling a typescript using ABI with web3-utils it fails.

#### Steps to reproduce the behavior

1. Add web3-utils to ur typescript project
2. When you define a ABI with type AbiItem and try to compile
3. it throws the above error

#### Logs
error: [app] Application is crashed: TSError: ⨯ Unable to compile TypeScript:
src/config/constants/MakerConstants.ts:868:13 - error TS2322: Type '{ internalType: string; name: string; type: string; }' is not assignable to type 'AbiInput'.
  Object literal may only specify known properties, and 'internalType' does not exist in type 'AbiInput'.

868             internalType: 'uint256',

####Possbile Solution
In `web3-utils/types/index.d.ts` 

```
export interface AbiInput {
    name: string;
    type: string;
    indexed?: boolean;
    components?: AbiInput[];
}
```
add ` internalType?: string;`

```
export interface AbiInput {
    name: string;
    type: string;
    indexed?: boolean;
    components?: AbiInput[];
    internalType?: string;
}
```

#### Versions
Node: v12.6.0
"web3-utils": "^1.2.4"

**Comment by nivida** [comment]
@vetri02 Thanks for opening this issue! We have already updated the related type definition and will release it asap. (PR: https://github.com/ethereum/web3.js/pull/3279)

**Comment by vetri02** [comment]
@nivida Any ETA on the release.

**Comment by nivida** [comment]
@vetri02 We have planned an RC release of 1.2.5 on Thursday with a testing phase of a week before we publish 1.2.5 on the latest track.

[Release Guidelines](https://github.com/ethereum/web3.js/blob/1.x/CONTRIBUTIONS.md#releases)
