### ISSUE TITLE
missing types for Subscription.on('connected')

### ISSUE THREAD

**Issue by Velenir** [ethereum/web3.js#3319]
#### Expected behavior
```
web3.eth.subscribe(<any event type>).on('connected', console.log)
```
would be properly typed.
#### Actual behavior

Typescript error `No overload matches this call`

#### Steps to reproduce the behavior
1 .Input `web3.eth.subscribe('newBlockHeaders').on('connected', console.log)`
2. compile with Typescript
3. see error

#### Versions
Node -- v12.14.1
web3 -- v1.2.4 

I think, it should be enough to add ` on(type: 'connected', handler: (subscriptionId: string) => void): Subscription<T>;` to Subscription type declaration.

**Comment by nivida** [comment]
@Velenir Thanks for opening this issue! We will improve the related types asap.
