### ISSUE TITLE
How to unsubscribe to method.send ??

### ISSUE THREAD

**Issue by Vivek205** [ethereum/web3.js#3331]
#### Steps to reproduce the behavior
execute any contract method
```cont method = contract.myMethod.send().on("confirmation",(confirmationNumber)=>console.log(confirmationNumber));```

how to unsubscribe when confirmationNumber = 5?

**Comment by nivida** [comment]
@Vivek205 Thanks for opening this issue! It is sadly not possible to unsubscribe within the confirmation listener or over the returned ``PromiEvent`` but you are able to configure the number of confirmations with the [transactionConfirmationBlocks](https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html#transactionconfirmationblocks) property. 

Could you update your issue to be aligned with the issue template we provide? 

We will label your request correctly after and implement this enhancement with the then defined priority. :)

**Comment by Vivek205** [comment]
Cool! @nivida 
I have made a workaround by using `.once` instead of `.on` while listening to `confirmation`.
Inside the callback, I'm using `await method.off()` to make sure, I'm not listening to it anymore.

**Comment by nivida** [comment]
Oh! thanks totally missed this possibility! :) 
I will close this issue for now but feel free to ping me here again if you think this should get implemented by us as a clear understandable/usable feature. Additionally, would other users coming by here definitely be happy to see the code-snippet you are using :-)

**Comment by miketeix** [comment]
@Vivek205 would you mind sharing your code snippet?
Also, was wondering what your particular need for the unsubscribe was?  

I'm seeing the old listener getting triggered again from a separate call and after a different promiEvent is created which is weird. Hoping it get's resolve in staging/rinkeby where there will be longer blocktimes, though it could very well by my implementation.
Cheers!
