### ISSUE TITLE
Analysis of the defined paths for the provided types

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3336]
### Expected behavior 

The path defined for example in the ``tsconfig`` file of the ``web3-providers-http`` package is misleading and should get corrected if possible in a non-breaking manner.

#### Actual behavior

The defined path is ``web3-providers`` instead of ``web3-providers-http``.

#### Steps to reproduce the behavior

1. Open a ``tsconfig`` file from one of the provider packages and check the ``path`` property.

#### Steps for this issue

1. Check all ``path`` properties of all ``tsconfig`` files and write the misleading down here
2. Analyze the possibilities to correct those paths in a non-breaking manner
3. Propose a PR with your solution.

**Comment by wirednkod** [comment]
@nivida I am on it:

Misleading paths are on following files:
- packages/web3-providers-ws/types/tsconfig.json
- packages/web3-providers-ipc/types/tsconfig.json
- packages/web3-providers-http/types/tsconfig.json

Also:
- packages/web3-core-requestmanager
- packages/web3-core-promievent
are missing directory types/* and all respective files under it

**Comment by su45fg** [comment]
ยังไม่ เข้าใจ พยายาม ทำความเข้าใจ
