### ISSUE TITLE
Support for solc > 1.1.5 in web3.compile.solidity

### ISSUE THREAD

**Issue by tymat** [ethereum/web3.js#334]
Solidity recently added the library feature which allows you to deploy library functions in external contracts.  Right now there's no way to compile/deploy contracts that use this functionality

```
solc --bin --libraries "somelibrary:someaddress"  MyContractThatUsesSomeLibrary.sol
```

This should be exposed to web3 like such:

```
web3.compile.solidity(<code>,{libraries: {somelib: someaddress}})
```

**Comment by tgerring** [comment]
Would like to see this expanded into an optional arguments object that may support optimization paramaters and should be more more extensible in the future

**Comment by frozeman** [comment]
@tymat thanks for putting this here, its in the back of my head, but good to track it here...

**Comment by tymat** [comment]
Any updates to this?

**Comment by frozeman** [comment]
Compiliation using the node is discurouged and solc should be used directly.
