### ISSUE TITLE
How to send from multiple addresses to one

### ISSUE THREAD

**Issue by Gennttii** [ethereum/web3.js#3341]
How to send from multiple addresses to one, not one to one !?

@alcuadrado @cgewecke @nivida

**Comment by alcuadrado** [comment]
You could implement a contract to do that. An normal ethereum tx can only send to one address, but if that address is a contract, it can forward parts of the received ETH to different addresses. I guess there's no other way of doing that.

This is out of the scope of this project though. https://ethereum.stackexchange.com/ would be a better place to ask about how to do that.
