### ISSUE TITLE
Add public address getter

### ISSUE THREAD

**Issue by ilanolkies** [ethereum/web3.js#3346]
https://github.com/ethereum/web3.js/blob/ee78ff70c82975b486da0e76ca29d66986d1460f/packages/web3-eth-contract/types/index.d.ts#L31

This is handy for factory testing.

**Comment by nivida** [comment]
The contract ``address`` and any other important property is accessible over the ``options`` object of the contract object as documented [here](https://web3js.readthedocs.io/en/v1.2.5/web3-eth-contract.html#options-address).
