### ISSUE TITLE
ESM & Pika.dev support

### ISSUE THREAD

**Issue by lildata** [ethereum/web3.js#3359]
From what I understand the new build pipeline (https://github.com/ethereum/web3.js/pull/3160) support ESM.
I'm trying to understand how far are we to support something like Pika.dev ? (https://www.pika.dev/search?q=web3) that requires a web-optimized "module" entrypoint in `package.json` like `"module": "lib/esm/index.js"`

As you probably know, the Pika people are trying to remove a lot of pain & weight in modern web tooling by leaving behind support for antique browsers. In the Ethereum space it totally makes sense as we most likely not gonna try to support IE 11.
Having web3.js support it would be pretty sweet & would unlock hopefully the whole ecosystem.

**Comment by nivida** [comment]
@lildata The build pipeline improvements didn't get approved as expected and got postponed for the 2.0 version of the web3.js library. But thanks for opening this issue I will re-start the discussion about it with my team colleague @cgewecke.
