### ISSUE TITLE
Missing documentation of TS type usage

### ISSUE THREAD

**Issue by fubar** [ethereum/web3.js#3364]
I can't find instructions on how to use Typescript types since they were integrated in v1.2.2. In v1.2.1 I used to be able to do:

```js
import { Account } from 'web3/eth/accounts';
```

What's the equivalent in v1.2.6?

#### Expected behavior

I was migrating from 1.2.1 to 1.2.6 and all type imports broke. I was expecting to find a migration guide in the docs.

#### Actual behavior

I could not find migration instructions.

#### Steps to reproduce the behavior

I was able to figure out the following replacements:

```js
import { Account } from 'web3/eth/accounts'; // old
import { Account } from 'web3-core'; // new

import { EventLog } from 'web3/types'; // old
import { EventLog } from 'web3-core'; // new

import Contract from 'web3/eth/contract'; // old
import { Contract } from 'web3-eth-contract'; // new

import { TransactionObject } from 'web3/eth/types'; // old
import { ContractSendMethod } from 'web3-eth-contract'; // new

import { TransactionReceipt } from 'web3/types'; // old
import { TransactionReceipt } from 'web3-eth'; // new

import { Tx } from 'web3/eth/types'; // old
import { TransactionConfig } from 'web3-core'; // new

import { Mixed } from 'web3/utils'; // old
import { Mixed } from 'web3-utils'; // new
```

#### Logs

n/a

#### Versions
Node 11.15.0
web3 1.2.6

**Comment by nivida** [comment]
@fubar Thanks for opening this issue! We do have the current TS guidelines [here in our readme file](https://github.com/ethereum/web3.js#usage-with-typescript).

But thanks for giving us the hint about the required documental improvement. Is it possible for you to update your issue to be aligned with the issue template we provide and to add all the missing points you see from your perspective? 

We will after add this issue as soon as possible to our planning and improve the situation.

**Comment by fubar** [comment]
Thanks @nivida, I updated the issue description and added the replacements that I figured out so far.

**Comment by nivida** [comment]
Thanks for doing that! I see the types the community wrote and especially the import paths are wrong. Feel free to finish the list above or I will do it later on my own. I think the goal of this issue would be to provide a small migration script for this.

**Comment by fubar** [comment]
I've added one more, that's all I have to contribute for now. I don't think this is something that needs to be automated with a script. It would be convenient for sure but I'm sure your time is better spent elsewhere. I would think that a simple migration guide with a list of replacements like the ones I mentioned is sufficient.

**Comment by nivida** [comment]
Thanks! Yes, it doesn't look like a big list of required changes. I was expecting more. 👌

**Comment by fubar** [comment]
To clarify, I assume there are many more replacements. The ones I provided are merely the ones we are using.

**Comment by bjackson** [comment]
I'm confused, too, about how to use the new types. I'm migrating a codebase to use v1.2.6. In this instance, the methods returned `TransactionObject<bool>`. However, the new `ContractSendMethod` is not generic and doesn't have the `call` method. Am I using it right or am I missing something?

Here is the file I'm migrating: https://github.com/ethereum-alarm-clock/lib/blob/master/types/web3-contracts/TransactionRequestCore.d.ts#L22

This is how `TransactionObject` was defined in @types/web3:
```typescript
export interface TransactionObject<T> {
	arguments: any[];
	call(tx?: Tx): Promise<T>;
	send(tx?: Tx): PromiEvent<T>;
	estimateGas(tx?: Tx): Promise<number>;
	encodeABI(): string;
}
```
