### ISSUE TITLE
Confirmation of contract's events

### ISSUE THREAD

**Issue by AuHau** [ethereum/web3.js#3372]
Not sure if I am missing something, but is there a way how to have confirmation-delay for contract's events? I know there is `confirmation` event for the `contract.methods.myMethod().send()` function, but have not found anything similar for `contract.events.myEvent()`

Is it possible to achieve that? Or am I missing something?

**Comment by nivida** [comment]
@AuHau Thanks for asking! I'm not sure if I understood you correctly but you would like to know if the event got removed or not? If this is the case do I recommend to you to use the ``changed`` listener as documented [here](https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#contract-events-return).

**Comment by AuHau** [comment]
Hmm I see, thanks for the reply! I am new to blockchain/smart-contract development so maybe I am missing something from the big picture here.

I guess it tackles the same problem but from a different angle. I want to make sure that I can "trust" an event. I believe for normal transactions it is done with waiting for several confirmations (eq. several new blocks on the chain). For the contract's method, it can be done using the `contract.methods.myMethod().send().on('confirmation', ()=>...)`.

With the `changed` approach I can react to the removed events, but in my use-case I would prefer to wait for several confirmations and then react to the event, hence delaying the actual firing of the event until confirmation...

**Comment by nivida** [comment]
Thanks for your response! You could achieve this with starting of a [newBlockHeaders](https://web3js.readthedocs.io/en/v1.2.6/web3-eth-subscribe.html#subscribe-newblockheaders) subscription.
