### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by brw31415** [ethereum/web3.js#338]
I   am using  cloud9, when I open a new workspace, and run the small sample program that comes with it, it runs fine.
When I install ethereum by doing this, meteor add ethereum:js, then try to run the sample program (without changing anything else), it doesn't work: => Exited from signal: SIGKILL
Unexpected mongo exit code null. Restarting.  
Killedlding the application

**Comment by frozeman** [comment]
Its called ethereum:web3


https://atmospherejs.com/ethereum/web3

**Comment by brw31415** [comment]
Thanks Fabian,

I have no idea why this happens, but Cloud9 is popular with developers, and
I havent had any other problems with them, but if you open a free account
there, open a meteor workspace, and run the sample program, everything
works great. But when I  add the library using this command : meteor add
ethereum:js
or meteor add ethereum:web3 , I get problems just running the sample program


Unexpected mongo exit code null. Restarting.
=> Exited from signal: SIGKILL

Can't start Mongo server.
Killedecting package versions

**Comment by brw31415** [comment]
Does the library somehow affect the address of mongodb?

**Comment by frozeman** [comment]
Did you add `ethereum:web3`?

**Comment by brw31415** [comment]
I just did it again:
 meteor add ethereum:web3

and ran the application 3 different ways:

meteor --port $IP:$PORT
meteor
sudo meteor

although it might be cloud9 problem, I haven't managed to get meteor on
anything else yet,
but cloud9 has been working fine.

I would think the fellows at cloud9 would be smart enough to fix it

but I did come across this post
https://docs.c9.io/discuss/5602254670694e0d00e3c732.

**Comment by frozeman** [comment]
I have no experience with cloud9. Could you create an empty meteor app locally and ad web3? This should work fine. If so then its most likely a problem with cloud9’s setup




Liebe GrüßeFabian

**Comment by brw31415** [comment]
I also have this error message:
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

**Comment by brw31415** [comment]
thanks for your help, i just got access to a debian box in holland, so i
can do a clean install of meteor, and go from there. cloud9 is ok, but you
don't really know whats going on under the hood

**Comment by frozeman** [comment]
If you find the issue, please report back
