### ISSUE TITLE
Use JavaScript BigInt for big integers?

### ISSUE THREAD

**Issue by olalonde** [ethereum/web3.js#3385]
Now that JavaScript support big integers natively, is there any plan to use them in a future release of web3? It would make it a lot easier to work with amounts rather than passing strings / objects around.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by alcuadrado** [comment]
Hey @olalonde,

This is a personal dream of mine, but unluckily, they can't be used yet.

JavaScriptCore (Safari's js engine) has no support for native BigInt. This is incredibly problematic, as every browser is forced to use Webkit and JavaScript core in iOS.

**Comment by holgerd77** [comment]
Will close here again for the moment, would nevertheless agree that it would be wonderful to be able to support native big integers at some PIT.

**Comment by jzxchiang1** [comment]
I think JSC in iOS 14 supports BigInt now. At least I've been using BigInts just fine when testing my React Native mobile app on iOS 14.

https://webkit.org/blog/11340/new-webkit-features-in-safari-14/
