### ISSUE TITLE
Couldn't connect to node on WS (using getBlock method at #599275 ropsten)

### ISSUE THREAD

**Issue by rlaace423** [ethereum/web3.js#3388]
#### Expected behavior
fetch block information

#### Actual behavior
Error with message like 
![image](https://user-images.githubusercontent.com/5516480/75116518-8beab580-56ac-11ea-830e-12773db383f0.png)

#### Steps to reproduce the behavior

1. create new web3 object with WebsocketProvider
2. call getBlock function like below
   web3.eth.getBlock(599275, true);

#### Versions
nodejs : v10.16.3
npm : v6.13.2
web3 : v1.2.6
os : ubuntu 16.04

**Comment by rlaace423** [comment]
I think in 599275, there's 1077 transactions in it. Is there any way to overcome it?

**Comment by cgewecke** [comment]
@rlaace423 Can confirm that Ropsten 599275 is a problem when calling Infura over Websockets with:
```
await web3.eth.getBlock(599275, true); // "true" means include full tx objects
```

This looks like it works:
```
await web3.eth.getBlock(599275); // only include transaction hashes
```

It also works for full tx objects using an Http provider instead of Websockets. 

Are either of those  options for you?

**Comment by cgewecke** [comment]
@rlaace423 Actually, just got it  to work as expected by using a suggestion in this [#1217 comment][1].   

It's possible to set the websocket frame size limits larger when instantiating the provider,  
```javascript
const web3 = new Web3(new Web3.providers.WebsocketProvider(
    'wss://ropsten.infura.io/ws/v3/<projectID>',
    {
      clientConfig: {
        maxReceivedFrameSize: 100000000,
        maxReceivedMessageSize: 100000000,
      }
    }
  ));
```

This needs to be added to the documentation.

[1]: https://github.com/ethereum/web3.js/issues/1217#issuecomment-425956862

**Comment by rlaace423** [comment]
@cgewecke Thank you for your help! 

In my situation, I can't handle Web3 constructor because it resides in 3rd party library (https://github.com/bitpay/bitcore).

Also, I've already tried https://github.com/ethereum/web3.js/issues/1217#issuecomment-425956862, but had no luck.

**Comment by cgewecke** [comment]
@rlaace423 I just ran this script and it worked...

**index.js**
```javascript
const Web3 = require('web3');
const util = require('util');

async function main(){
  const web3 = new Web3(new Web3.providers.WebsocketProvider(
    'wss://ropsten.infura.io/ws/v3/<infura-project-id>', // <-- Put your projectID here
    {
      clientConfig: {
        maxReceivedFrameSize: 100000000,
        maxReceivedMessageSize: 100000000,
      }
    }
  ));
  const block = await web3.eth.getBlock(599275, true);
  console.log(util.inspect(block))
}

main()
  .then(() => process.exit(0))
  .catch(err => {
    console.log(err);
    process.exit(1)
  });
```
**Run**
```
node ./index.js
```

Could you double-check that? 

> I can't handle Web3 constructor because it resides in 3rd party library

Do you mean you can't configure the provider?

**Comment by rlaace423** [comment]
I found that I only tested with maxReceivedFrameSize, and I figured out maxReceivedMessageSize must be used together! I works like a charm :) 

And, yes, I cannot configure the provider. But I can pull-request this. 

Thank you!

**Comment by cgewecke** [comment]
@rlaace423 I'm going to track the documentation need raised here via PR 3402 if that's ok with you. 

Please just ping if you'd like this re-opened / think more should be done here.
