### ISSUE TITLE
"ivalid address" after last update

### ISSUE THREAD

**Issue by imolfar** [ethereum/web3.js#339]
In one of the contracts I have public mapping which is accessible by automatic accessor method.
In web3 I access it like this:
Tokens.balances(user_address, 'BTC')   // it's 2-level structure.
After last web3.js update it stopped to work. Throws "ivalid address" error in formatters.js:270
If I execute web3.isAddress(user_address)  , it returns true.

**Comment by frozeman** [comment]
how does for that function ABI looks like?

**Comment by imolfar** [comment]
Can't recreate it now. Had several changes to the contract / code and it works now. Will reopen the issue if it'll occur again.
