### ISSUE TITLE
Move from Travis to GitHub Actions

### ISSUE THREAD

**Issue by holgerd77** [ethereum/web3.js#3393]
There was the suggestion by @ryanio in [this comment](https://github.com/ethereum/web3.js/pull/3376#issuecomment-590454282) to move the CI to GitHub Actions, being currently run on Travis, this was perceived positive by @cgewecke.

I would tend to give this some stronger priority cause I think workflow of bringing PRs up-to-date and have the checks pass to be mergeable would profit a lot by CI being faster and better integrated. Currently it is somewhat arduous to wait for PR updates to re-finish with the CI run.

@ryanio Can you take on this? Respectively other voices on this here?

References:

- [.travis.yml](https://github.com/ethereum/web3.js/blob/1.x/.travis.yml)

**Comment by holgerd77** [comment]
Ah, just remember, there was this eventual limitation to Action runs on the `ethereum` GitHub organization (can't find the reference atm). Any new information on this?

**Comment by holgerd77** [comment]
Update: @ryanio if you want you can nevertheless do a draft PR on this just to see and get a feel how things behave.

**Comment by nivida** [comment]
@holgerd77 This issue can probably get closed: https://github.com/ethereum/web3.js/issues/3034

**Comment by ryanio** [comment]
I started work on this here: https://github.com/ryanio/web3.js/pull/1. Feel free to give it a preliminary look.
