### ISSUE TITLE
isConnected() and isListening() don't exist anymore, so what is the correct way to check for an initial connection?

### ISSUE THREAD

**Issue by ilyador** [ethereum/web3.js#3397]
I'm using Metamask and I want to show an error in case the browser does not have it.
I tried using `eth.currentProvider` but it returns a Proxy which I'm not sure how to use. The other option that I found was `isSyncing` but I'm not sure if this is the correct use case, the docs don't say much.

**Comment by cgewecke** [comment]
@ilyador In Web3 1.x, the provider has a `connected` property. Over HTTP it's set to true [after a successful send][1]. A simple check might be to request some data like the current block number and see if the call succeeds or fails.

> it returns a Proxy which I'm not sure how to use

Could you explain this further? 

[1]: https://github.com/ethereum/web3.js/blob/a6ddec59e65116853435f203b25cb9c55824d084/packages/web3-providers-http/src/index.js#L109

**Comment by ilyador** [comment]
> > it returns a Proxy which I'm not sure how to use
> 
> Could you explain this further?

It returns a Javascript Proxy object, which must have some special method to access.

**Comment by cgewecke** [comment]
@ilyador 

Does the suggestion about making a test call work for your case or not?

**Comment by cgewecke** [comment]
@ilyador Closing, please just lmk if you're still having problems with this.
