### ISSUE TITLE
Swarm.js - Arbitrary File Write vulnerability

### ISSUE THREAD

**Issue by shaunazzopardi** [ethereum/web3.js#3399]
#### Expected behavior

No high vulnerabilities.

#### Actual behavior

Getting an _Arbitrary File Write_ vulnerability.

#### Steps to reproduce the behavior

1. npm install web3
2. npm audit

#### Logs

```
  High            Arbitrary File Write                                          

  Package         decompress                                                    

  Patched in      No patch available                                            

  Dependency of   web3                                                          

  Path            web3 > web3-bzz > swarm-js > decompress                       

  More info       https://npmjs.com/advisories/1217   
```

#### Versions
Web3 1.2.6

**Comment by cgewecke** [comment]
@shaunazzopardi Thanks for reporting. 

It looks like neither [swarm-js][1] or decompress are being actively developed, unfortunately.

The underlying issue is being tracked at [decompress #76][2]. 

[1]: https://github.com/MaiaVictor/swarm-js#disclaimer
[2]: https://github.com/kevva/decompress/issues/76

**Comment by cgewecke** [comment]
For near-term maintenance purposes we could fork swarm-js to the web3-js org (or ethereumjs) and move `decompress` to development dependencies. Believe it's only used in a [script to generate archive entries][1] and is incidental to the library methods.

Longer term options include migrating swarm support to the [erebos api][2] or just deprecating it altogether. 

[1]: https://github.com/MaiaVictor/swarm-js/blob/master/scripts/prepareArchives.js
[2]: https://github.com/MainframeHQ/erebos

**Comment by evertonfraga** [comment]
I probably still have push access to the repo and can get npm permissions.

Want me to perform those changes at swarm-js then?

**Comment by cgewecke** [comment]
@evertonfraga Ah that would be great! I saw commits by you but didn't see another publish.

**Comment by cgewecke** [comment]
@evertonfraga Opened [swarm-js 36][1] for that change.

[1]: https://github.com/MaiaVictor/swarm-js/pull/36

**Comment by evertonfraga** [comment]
I published swarm-js 0.1.40. please check!

**Comment by cgewecke** [comment]
@evertonfraga LGTM!
```
+ swarm-js@0.1.40
added 169 packages from 119 contributors and audited 356 packages in 18.645s
found 0 vulnerabilities
```

**Comment by evertonfraga** [comment]
That's great :)

if you need anything else in that front, lmk!

**Comment by holgerd77** [comment]
@cgewecke @evertonfraga Hi guys, greetings from EthCC, you are missed! 🥰 Thanks for keeping up on the real-work-to-be-done-front!
