### ISSUE TITLE
Unable to retrieve dynamic-length array from a contract's method.

### ISSUE THREAD

**Issue by imolfar** [ethereum/web3.js#340]
Say one want to get array of strings in web3.js from a contract. In contract you may have such method:
function getStrings() constant returns(bytes32[]){
    bytes32[] a;
    a[0] = “A”;
    a[1] = “B”;
    return a;
}
You will not receive this data in web3, it will be just empty array []
But if you’ll set bytes32[5]
You’ll have 2 first elements and 3 others empty. But that's not scalable, because I don't know beforehand what length of the array would be, plus it carries extra payload with response from a node.

**Comment by chriseth** [comment]
This is a limitation of solidity - this is not yet possible. Please

1. wait for the "inline array" / "creating memory arrays" feature or
2. construct the return value in storage or
3. return a fixed-size array.

**Comment by imolfar** [comment]
The interesting thing is that it works in solidity. I can access this array from the other function. But cannot access it from web3
