### ISSUE TITLE
Web3.js  vulnerability with no patches

### ISSUE THREAD

**Issue by Genysys** [ethereum/web3.js#3405]
#### Expected behavior

no security warning. 
#### Actual behavior

                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Write                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ decompress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ web3 > web3-bzz > swarm-js > decompress                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1217                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 99601 scanned packages
  1 vulnerability requires manual review. See the full report for details.

#### Steps to reproduce the behavior

1. npm audit
2. [Second step]
3. [and so on...]

#### Versions
[NPM, Node, Web3.js, OS, device...]
NPM: 6.13.4
Node v10.19.0
OS- Darwin (MacOs)
Web3j: 1.0.0-beta.26

**Comment by cgewecke** [comment]
@Genysys Thanks for reporting. This is a duplicate of #3399, which should be resolved by #3403.
