### ISSUE TITLE
Cannot pass in web3-core-helpers formatters into web3.extend inputFormatter/outputFormatter

### ISSUE THREAD

**Issue by pxyxyrus** [ethereum/web3.js#3407]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Versions
[NPM, Node, Web3.js, OS, device...]

**Comment by pxyxyrus** [comment]
sorry for the misinput but I have a problem when using web3.extend and trying to pass in predefined formatters in web3-core-helpers in typescript.
I'm getting some similar errors that says the function types does not match
Type '(blockNumber: string | number) => string | number' is not assignable to type '() => void'.ts(2322)

since the declaration file for outputFormatter or InputFormatter is both
 () => void
and
Array<() => void>

is there any solution to make this work in typescript?

**Comment by cgewecke** [comment]
@pxyxyrus Could you provide a basic example to reproduce this error with?   

> since the declaration file for outputFormatter or InputFormatter is both
() => void
and
Array<() => void>

Which declaration file do you see this in? In web3-core-helpers, the formatter types are [defined here][1].

[1]: https://github.com/ethereum/web3.js/blob/a6ddec59e65116853435f203b25cb9c55824d084/packages/web3-core-helpers/types/index.d.ts#L24-L58

**Comment by cgewecke** [comment]
@pxyxyrus 

Closing due to lack of response. Please just ping if you have more info about this.

**Comment by RilRil** [comment]
the issue is the type expected by the Method interface for `inputFormatter`
```
export interface Method {
    name: string;
    call: string;
    params?: number;
    inputFormatter?: Array<(() => void) | null>;
    outputFormatter?: () => void;
    transformPayload?: () => void;
    extraFormatters?: any;
    defaultBlock?: string;
    defaultAccount?: string | null;
    abiCoder?: any;
    handleRevert?: boolean;
}

here the return value should be "void" but any formatter that you linked here [](https://github.com/web3/web3.js/blob/a6ddec59e65116853435f203b25cb9c55824d084/packages/web3-core-helpers/types/index.d.ts#L24-L58) returns "something" not "void".

**Comment by hjhjdev** [comment]
Came here while following BSC gasLimit issue
https://github.com/web3/web3.js/issues/3936#issuecomment-797342613

Looks like outputFormatter should accept parameters like Transaction?
Or should we bind function into context?
