### ISSUE TITLE
ecrecover and web3.eth.accounts.sign problem

### ISSUE THREAD

**Issue by Aleione** [ethereum/web3.js#3409]
EXPECTED BEHAVIOUR:

Given privatekeyA and its generated address addressA

var  sig = web3.eth.accounts.sign (digest, 'privateKeyA') 

on Solidity smart contract:

Should be true
ecrecover(digest, sig.v,sig.r,sig.s) == addressA

ACTUAL BEHAVIOUR:

On smart contract the equality fails

Why this situation?

**Comment by cgewecke** [comment]
@Aleione  It might help to start from the following example which works (using data from #1778) 

**Solidity**
```solidity
pragma solidity ^0.5.1;

contract Example {
    function recoverAddress(bytes32 hash, uint8 v, bytes32 r, bytes32 s)
        public
        pure
        returns (address)
    {
        return ecrecover(hash, v, r, s);
    }
}
```

**Web3.js**
```javascript
const text = "apple, banana, orange";
const expectedAddress = "0x78feF8C1C50CB9fD16cf505d8b30d450d6241020";
const privateKey = "0x6c88dfd66a3c4294e3a0243218221f4337a6faa9c6b83380ec6f3d5ede3db982";

// After deploying Example....

const sig = web3.eth.accounts.sign(text, privateKey);

const address = await example
  .methods
  .recoverAddress(sig.messageHash, sig.v, sig.r, sig.s)
  .call({from: accounts[0]});

assert.equal(address, expectedAddress) // True
```

Could you look at your code and see what's different? What does your Solidity method look like?

You might find openzeppelin-solidity's [implementation][1] helpful. And their [unit tests][2]...

[1]: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol
[2]: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/cryptography/ECDSA.test.js

**Comment by cgewecke** [comment]
@Aleione Is this close-able? Do you have all the info you need?

**Comment by Aleione** [comment]
The problem is in the Solidity function that contains ecrecover command (I can't change it because already deployed by  a third party). The solidity code does not append at the beginning of the message the string "\x19Ethereum Signed Message:\n32", while web3.eth.sign append this so there is a mismatch. I have solved this using secpk256 library to sign message without append the string in order that message can match.

Thank you for your suggestions.
i can close this.
