### ISSUE TITLE
Using pragma experimental ABIEncoderV2

### ISSUE THREAD

**Issue by matheusroleal** [ethereum/web3.js#3410]
Hi!

Not sure if I should create a new issue or remain on others related. I am using the experimental support for arrays in ABIEncoderV2. Turns out,  if I am not wrong, there is currently no ABI decoder that supports it. Just wanted to open a ticket to make sure that this is indeed the case. 

If not, in which version of Web3js can I use the ABIEncoderV2.

**Comment by cokia** [comment]
https://github.com/ConsenSys/abi-decoder

I think the project is what you want. ABI encoder library where you can decode v2.

And I also thought when I heard you. Web3.j strives to support the abiencoder v2 but web3.js have no discussion of the matter. Couldn't this be the starting point for the discussion?

**Comment by cgewecke** [comment]
@matheusroleal For context, could you give an example of a Solidity method you're having difficulty encoding correctly with Web3?

Web3 uses the [Ethers V4 ABICoder][2] internally. 

It might be possible to use a more recent  version than the one [currently pinned here][1] though. 

#1738 may need to be re-opened as well...

**Resources**
+ [Returning 2D arrays with web3 1.2.2][3]
+ [Passing 2D arrays as params][4] (#1738)

[1]: https://github.com/ethereum/web3.js/blob/04c8d654d255eb9acb5b0035e1d39ff74a4129be/packages/web3-eth-abi/package.json#L16
[2]: https://docs.ethers.io/ethers.js/html/api-advanced.html#abi-coder
[3]: https://github.com/ethereum/web3.js/issues/2022#issuecomment-548410551
[4]: https://github.com/ethereum/web3.js/issues/1738

**Comment by matheusroleal** [comment]
I think I got the same issue (Passing 2D arrays as params - #1738). For example:

`    function store(string[] memory num) public {
        for (uint i = 0; i < num.length; i++) {
            adaArr[i] = num[i];
        }
    }`

**Comment by cgewecke** [comment]
@matheusroleal I haven't been able to reproduce this, sorry. 

**Solidity (0.5.14 / pragma experimental)**
```solidity
function paramString1D(string[] memory str) public returns (string memory) {
  return str[0];
}

function paramString2D(string[][] memory str) public returns (string memory) {
  return str[1][1];
}

function paramUint2D(uint[][] memory numbers) public returns (uint) {
  return numbers[0][0];
}
```

**Web3 1.2.6**
```js
const valA = await instance
      .methods
      .paramString1D(['hello', 'ciao'])
      .call({from: accounts[0]});

const valB = await instance
      .methods
      .paramString2D([['hello', 'ciao'], ['hola', 'hej']])
      .call({from: accounts[0]});

const valC = await instance
      .methods
      .paramUint2D([[2,3],[3,4]])
      .call({from: accounts[0]});

console.log(valA);
console.log(valB);
console.log(valC);
```

**Output**
```
hello
hej
2
```

Closing, please just ping with a complete, reproducible example including error and will re-open.
