### ISSUE TITLE
Failed to load web3, accounts, or contract. Check console for details. 

### ISSUE THREAD

**Issue by ZhBoKn** [ethereum/web3.js#3414]
I have install web3,truffle ,python and so on.
npm run start it successes 
but the edge brower tell me that Failed to load web3, accounts, or contract. Check console for details.  
the console tells that No web3 instance injected, using Local web3.
i don't change any files.i have metamask ,but the port 8545 shows me that it can't connect.i have no idea,please help me! thanks

**Comment by cgewecke** [comment]
@ZhBoKn You're using a large number of different components - it's difficult to tell what's going wrong from your description.

> i don't change any files

What does this refer to?

Please
+ follow the guidelines in the issue template
+ provide a set of simple, clear steps that someone reading this issue can follow to reproduce the problem.

Closing.

**Comment by ZhBoKn** [comment]
> @ZhBoKn You're using a large number of different components - it's difficult to tell what's going wrong from your description.
> 
> > i don't change any files
> 
> What does this refer to?
> 
> Please
> 
> * follow the guidelines in the issue template
> * provide a set of simple, clear steps that someone reading this issue can follow to reproduce the problem.
> 
> Closing.
ok，but now i have solve my question ,thank you
