### ISSUE TITLE
TypeError: Cannot read property 'Set' of undefined

### ISSUE THREAD

**Issue by ZhBoKn** [ethereum/web3.js#3416]
i want to know that why i can not use the function which named 'set',or i want to know which function i can use to achieve the foundation of interact with the web page
![$}L5HN AOZW4OVWY_D0M57W](https://user-images.githubusercontent.com/45094047/76780239-a580a800-67e7-11ea-85fb-8257489bc2b9.png)
![5JAR_09ISWPR@%)KI_S)LS1](https://user-images.githubusercontent.com/45094047/76780257-ac0f1f80-67e7-11ea-82fe-40089de4c238.png)

**Comment by cgewecke** [comment]
@ZhBoKn Is this question about Web3.js? 

Closing for now, please just ping if you can report this issue as:
+ a Web3 bug
+ a Web3 feature request

For other topics, the gitter channel is a good place to ask for help.

It's also best if you can follow the issue template guidelines, providing a clear, complete steps to reproduce whatever problem you're seeing.
