### ISSUE TITLE
No bignumber.js"

### ISSUE THREAD

**Issue by cokia** [ethereum/web3.js#3417]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Versions
[NPM, Node, Web3.js, OS, device...]

**Comment by cgewecke** [comment]
@cokia Are you using typescript? If so this is a duplicate of #3386 and has been patched with #3390. It will be fixed when `1.2.7` is published. 

An interim fix is to add bignumber.js to your project as a dependency.

**Comment by cgewecke** [comment]
Closing, please just ping if you're referring to a different problem.

**Comment by cokia** [comment]
oops, I saw your Pull request while I was trying to write this issue, and I tried to discard the writing. I think I uploaded the issue by mistake in my sleep. I'm sorry.

**Comment by cgewecke** [comment]
@cokia No problem at all!
