### ISSUE TITLE
Install Error Windows - 17-3-2020

### ISSUE THREAD

**Issue by roeldijkstra** [ethereum/web3.js#3418]
#### Expected behavior
No errors installing the packages and using mocha
#### Actual behavior
Getting errors and audit errors installing web3 & Ganache

#### Logs
https://pastebin.com/yKKd1n9U

#### Versions
    "ganache-cli": "^6.9.1",
    "mocha": "^4.0.1",
    "node-gyp": "^6.1.0",
    "solc": "^0.4.19",
    "web3": "^1.2.6"

NOTE: I've tried everything, installing node-gyp, uninstalling node-gyp, removing the node-modules folder and the package-lock and npm install.

I'm using web3 for a course so I really need to get this fixed.

**Comment by cgewecke** [comment]
@RoelDijkstra In the pastebin you linked to above, it looks like installation succeeds and the error occurs running mocha. Could you try either re-writing the command as `npx mocha` or installing mocha globally? (e.g `npm install -g mocha@4.0.1`)
```
> mocha
 
'Developing\Blockchain\inbox\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:797
    throw err;
    ^
 
Error: Cannot find module 'C:\Users\roel\Desktop\mocha\bin\mocha'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Web3 runs a basic installation & use test for Windows / Node 12.16.0 which is executing successfully in TravisCI [here][1].  

[1]: https://travis-ci.org/github/ethereum/web3.js/jobs/661907191#L861-L969

**Comment by roeldijkstra** [comment]
Worked! Thanks.
