### ISSUE TITLE
Why givenProvider is any?

### ISSUE THREAD

**Issue by cokia** [ethereum/web3.js#3419]
When I check type of web3, givenProvider is "any" type.

I found out what its return value was. In Metamask it is deprecated(it return null), and i can check value of mist broswer, It seem to be same as provider interface.

Why is its value set to any? Can't you set the provider || null | undefined?

![image](https://user-images.githubusercontent.com/24792377/76875587-17bebe80-68b4-11ea-9d30-0bb145ed9b25.png)

[in chrome]

![image](https://user-images.githubusercontent.com/24792377/76875636-2d33e880-68b4-11ea-8890-8356b0c688b8.png)

[in node console]

[in mist wallet]

**Comment by GregTheGreek** [comment]
This will probably be addressed with the general cleanup that will take place with #3606
