### ISSUE TITLE
easier way to work with hex string and bytes

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#342]
Should web3 include a function to convert a hex string to an array of bytes?
What else should web3 have to make it easier to work with hex string and bytes?

For an example, see this conversation with tom-seddon and vbuterin:
https://gitter.im/ethereum/web3.js?at=562ec2f5e8970e4c503eae8a

Should a decodeHex function be added to web3?
https://github.com/ethereum/dapp-bin/blob/master/ether_ad/scripts/sha3.min.js#L23

Can web3 functions, like `web3.sha3` be modified to work with these byte arrays?

Can these byte arrays be simply passed to a Solidity function with a signature like `foo(bytes b)` ?

**Comment by ethers** [comment]
#363 seems will help with this

**Comment by frozeman** [comment]
`web3.utils.soliditySha3` should help with that as well as `web3.utils.hexToBytes`

Can you confirm?
