### ISSUE TITLE
ABout web.eth naming

### ISSUE THREAD

**Issue by b00f** [ethereum/web3.js#3424]
Web3 defined a good prototype for working with smart contracts. In the new version (2.0.0) it is more mature. 
I would like to suggest to rename `web3.eth` to `web3`. The can helps other blockchains (which might not use etherum platform) to use web3 package.
In this case some specific methods might move to `web3.eth` but contract and account package can be more global and eth-free!

**Comment by mychalvlcek** [comment]
hi, what is the plan for webs.js ? Is it like locked for ETH only, or could it be something like standard for web3 wallets even for other blockchains?
