### ISSUE TITLE
Expired discord invite

### ISSUE THREAD

**Issue by everdimension** [ethereum/web3.js#3429]
Hi!

The docs link to this discord channel: https://discord.gg/NR42fy
But the invite seems to be expired.

Is the discord channel still active? Can you please update the link?

**Comment by cgewecke** [comment]
@everdimension 

Where in the docs did you see that discord link? Could not find by searching the ReadTheDocs or the  Github repository.

AFAIK the only chat group is at https://gitter.im/ethereum/web3.js

**Comment by everdimension** [comment]
Oh, I must've been looking at the [v2](https://github.com/ethereum/web3.js/blob/2.x/README.md) branch: https://github.com/ethereum/web3.js/blob/2ce573b65abd2f3c78d648b1d70f9a273e922e8c/README.md#community

**Comment by ryanio** [comment]
@everdimension sorry for the delay, here is a new invite link https://discord.gg/2mSaSCG
