### ISSUE TITLE
Setting a "to" address when using contract.new() to deploy results in a web3 error

### ISSUE THREAD

**Issue by tgerring** [ethereum/web3.js#343]
Seems to be thrown at https://github.com/ethereum/web3.js/blob/master/dist/web3-light.js#L3810

I can't seem to wrap this in a try/catch block because the code is in a callback handler after control leaves new() but before the users's callback reaches the stack

**Comment by frozeman** [comment]
Please re-open if thats still an issue in web3.js 1.0.0
