### ISSUE TITLE
sendSignedTransaction always pending.

### ISSUE THREAD

**Issue by anuragteapot** [ethereum/web3.js#3431]
Hello, everyone, I am trying to send signed transaction. But my transaction always pending. It only gives the transaction hash. If I search transaction hash on etherscan it results not found. 

` 
return new Promise(async (resolve, reject) => {

      try {
        const account = await this.web3.eth.accounts.decrypt(
          encryptedData,
          password
        );

        const { address } = account;
        this.web3.defaultAccount = address;

        const privateKey = account.privateKey.slice(2);

        const value = this.web3.utils.toWei("0.00", "ether");

        const gasLimit = await this.web3.eth.estimateGas({
          from: address,
          to: ERC721Address,
          data: byteCode
        });

        const gasPrice = parseInt(await this.web3.eth.getGasPrice());

        const nonce = await this.web3.eth.getTransactionCount(address);

        console.log("Building Transaction");

        let txData = {
          method: "publishAsset",
          toAddress: ERC721Address,
          nonce,
          value,
          gasLimit,
          gasPrice,
          privateKey,
          byteCode
        };

        try {
          let rawTx = this.txBuilder(txData);

          console.log({ txData, rawTx: rawTx.toString("hex") });

          console.log("Sending Signed Transaction");

          this.web3.eth
            .sendSignedTransaction("0x" + rawTx.toString("hex"), function(
              err,
              transactionHash
            ) {
              if (err) {
                reject(err);
              } else {
                console.log(transactionHash);
                return resolve(transactionHash);
              }
            })
            .on("receipt", console.log);
        } catch (error) {
          reject(error);
        }
      } catch (err) {
        reject(err);
      }
    });`

`  public txBuilder({ method, toAddress, nonce, value, gasLimit,  gasPrice, privateKey, byteCode }) {

    const privateKeyHex = new Buffer(privateKey, "hex");

    const nonceHex = this.web3.utils.toHex(nonce);
    const valueHex = this.web3.utils.toHex(value);
    const limitHex = this.web3.utils.toHex(gasLimit);
    const priceHex = this.web3.utils.toHex(gasPrice);

    let rawTx;

    if (method == "sendEther") {
      rawTx = {
        nonce: nonceHex,
        gasPrice: priceHex,
        gasLimit: limitHex,
        to: toAddress,
        value: valueHex
      };
    } else if (method == "publishAsset") {
      rawTx = {
        nonce: nonceHex,
        gasPrice: priceHex,
        gasLimit: limitHex,
        data: byteCode,
        to: toAddress,
        value: valueHex
      };
    } else {
      return throwError("Method not found");
    }

    console.log(rawTx);

    const tx = new Transaction(rawTx);

    tx.sign(privateKeyHex);

    const serializedTx = tx.serialize();

    return serializedTx;
  }`

* version
OS -> MAC OS Catalina 
Node.js -> v13.5.0
 "web3": "^1.2.6",

**Comment by cgewecke** [comment]
Hi @Anu1601CS 

+ do you have an example transaction hash (and network name)? 
+ how are you connecting to the network?

There are some examples of using sendSignedTransaction [in the unit tests here][1] which might help debug your case - they use web3-eth-accounts to manage the signing with the latest `ethereumjs-tx` version. 

If you try this approach, could you double check that the address generated when you supply your private key to the wallet is what you expect it to be? 



[1]: https://github.com/ethereum/web3.js/blob/af6472976c23cb61c05e925eebe5734d141384f4/test/e2e.method.signing.js#L62-L114

**Comment by anuragteapot** [comment]
@cgewecke 

Thank you for your reply. 

Now my problem is fixed by providing `chain`  name.

`const tx = new Transaction(rawTx, { chain: 'kovan' });`

Now, I am closing the issue. 

:)

**Comment by jo-es** [comment]
@cgewecke I've had issues with sendSignedTransaction not returning a tx receipt as well. I accidentally included the `from` property to the object which I passed to `web3.eth.accounts.signTransaction` and passed that to sendSignedTransaction. I've fixed it by removing the `from` property.
