### ISSUE TITLE
Checking if a provider supports subscriptions by checking for "on" property often breaks

### ISSUE THREAD

**Issue by dmihal** [ethereum/web3.js#3432]
When a transaction is sent, web3 chooses to either poll for a receipt, or subscribe to new blocks. However, it makes this decision by checking if `on` is a property of the provider:

https://github.com/ethereum/web3.js/blob/af6472976c23cb61c05e925eebe5734d141384f4/packages/web3-core-method/src/index.js#L515-L521

This means if a project is using a provider that includes `on`, such as web3-provider-engine, it will incorrectly try to subscribe. This can cause errors when sending a transaction:

![image](https://user-images.githubusercontent.com/1661138/77694803-71487c80-6f89-11ea-9093-2e6b793158c4.png)

The workaround I've used is to remove `on` from a provider, however I imagine this may break some providers or apps.

```javascript
const provider = new ProviderEngine();
provider.on = null;
const web3 = new Web3(provider)
```

I'm not sure what the correct way is to determine whether a provider supports subscriptions is, maybe this needs to be addressed in the provider spec/API?

**Comment by cgewecke** [comment]
@dmihal Thanks for reporting. Out of curiosity, which provider-engine version are you using?

**Comment by dmihal** [comment]
Thanks @cgewecke, I'm using web3-provider-engine@15.0.6

I also had the same problem while building [burner-wallet/burner-connect-provider](https://github.com/burner-wallet/burner-connect-provider). I wanted to implement the EventEmitter interface, but had to remove `on` as well:

![image](https://user-images.githubusercontent.com/1661138/77706412-14f15700-6fa1-11ea-9b9e-49556629aa9c.png)
