### ISSUE TITLE
Web3 events confirmation count support

### ISSUE THREAD

**Issue by andrej-zirko** [ethereum/web3.js#3434]
Currently when subscribed to an event using web3, web3 returns the event on its first mining / confirmation. In general it's recommended to wait for several confirmations before considering transaction to be final.

Please is there a way how to configure web3 to wait for X confirmations before firing the callback with event details?  

Thank you

**Comment by cgewecke** [comment]
@andrej-zirko 

The confirmations and events handling are decoupled, but you should be able to start monitoring events from within [your confirmations handler][1], after an appropriate threshold is reached. 

You can also limit the number of times the confirmations handler is fired by setting your contract's [transactionConfirmationBlocks][2] property.

Would that work for your use case?

[1]: https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#id36
[2]: https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#transactionconfirmationblocks

**Comment by andrej-zirko** [comment]
@cgewecke 
Thank you for your suggestion. I'm aware of the confirmation handler. Unfortunately it doesn't fit my case well. 

In my use case I'm listening to the events that are not trigger by me. I got a "workaround" in  mind, where I would get the blocknum in which the event was triggered, store it and then when new block is mined I would substitute the event blockNum from current blockNum and thus get the number of confirmations. This unfortunately involves storage for events and its blockNums as it has to be able to sustain outtages. Nevertheless I assumed this is something every developer has to do when dealing with events and thus it make sense to add it to the lib. My understanding is the confirmation count is major concept in ethereum and I should consider transaction / event final only after X number of confirmations.

**Comment by cgewecke** [comment]
@andrej-zirko Thanks for the explanation, makes sense.

 > In my use case I'm listening to the events that are not trigger by me

Something like your workaround solution seems necessary in that case. There *are* ways of getting the event history for a [range of blocks][1] that might be helpful, but Web3 doesn't automatically know when a contract was created given just its address.

[1]: https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#getpastevents

**Comment by cgewecke** [comment]
Thanks for raising this @andrej-zirko. 

Closing for now.  I don't think Web3 can realistically provide support for this as a built-in feature - it's something that needs to be developed one layer out from here.
