### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

### ISSUE THREAD

**Issue by miguelmota** [ethereum/web3.js#3439]
#### Expected behavior

No CSP errors

#### Actual behavior

error

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```

![Screenshot from 2020-03-30 13-27-07](https://user-images.githubusercontent.com/168240/77958745-58daa980-728a-11ea-9b76-a80078f4c604.png)

error line 31
![Screenshot from 2020-03-30 13-26-57](https://user-images.githubusercontent.com/168240/77958750-5b3d0380-728a-11ea-977e-c3b619886090.png)

#### Steps to reproduce the behavior

Disallow 'unsafe-eval' in CSP header

```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self' 'unsafe-inline' data: blob:; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'; object-src 'none'; form-action 'none'; manifest-src 'self'; base-uri 'none'; block-all-mixed-content;" />
```

#### Versions
web3 version 1.2.6
![Screenshot from 2020-03-30 13-28-16](https://user-images.githubusercontent.com/168240/77958733-537d5f00-728a-11ea-994c-f92681995383.png)

node version 11.15.0
![Screenshot from 2020-03-30 13-28-04](https://user-images.githubusercontent.com/168240/77958735-54ae8c00-728a-11ea-8016-d80eda57fd6f.png)

firefox version 74 on arch linux
![Screenshot from 2020-03-30 13-32-58](https://user-images.githubusercontent.com/168240/77959173-02219f80-728b-11ea-86c6-c05c5cef3068.png)

**Comment by evertonfraga** [comment]
Regression of: https://github.com/ethereum/web3.js/issues/1847

**Comment by cgewecke** [comment]
@evertonfraga Do you have any ideas about how to address this? The current state of the code flagged here as the source of the error is meant to be a fix (applied in [#1565/files][1])

[1]: https://github.com/ethereum/web3.js/pull/1565/files

**Comment by evertonfraga** [comment]
@cgewecke that `try/catch` only tackles one `Function()`, and might have even fixed the code at that point. 

I believe there might be other occurrences of `eval()` or `Function()` in the code, introduced by any other dependency. I am looking into it now, will report.

**Comment by GregTheGreek** [comment]
@evertonfraga Did you ever end up finding anything?

**Comment by muzhaqi16** [comment]
I am having the same issue with rendering react website through node.js server.

**Comment by GregTheGreek** [comment]
> I am having the same issue with rendering react website through node.js server.

Can you provide further details? Node.js & web3 version,

**Comment by joeczar** [comment]
> 
> 
> I am having the same issue with rendering react website through node.js server.

Me too. Node 14.11  "webpack": "^4.44.1",

**Comment by GregTheGreek** [comment]
Web3.js version please?

**Comment by joeczar** [comment]
> 
> 
> Web3.js version please?

sorry, wrong dependency.
