### ISSUE TITLE
Arrays and strings as event topics

### ISSUE THREAD

**Issue by chriseth** [ethereum/web3.js#344]
Arrays (including `bytes` and `string`) cannot be used as event topics as they are. Solidity automatically sha3-hashes such arguments them before setting them as topic. It might be worthwhile to do this also automatically in web3.js when filtering for events.

**Comment by frozeman** [comment]
Thats a restrictions of solidity index params.

**Comment by frozeman** [comment]
Does solidity also hashes strings and bytes longer than 32 bytes?
