### ISSUE TITLE
myContract.methods.myMethod().send() cannot transfer money from smart scontract to account

### ISSUE THREAD

**Issue by kuabhish** [ethereum/web3.js#3446]
What I am trying is:
1. give some ether to smart contract
2. when a user ask for ether the Smart contract send it.
3. I wrote the solidity smart contract in solidity, which is working nicely. I checked in remix.

4. But when I am writing the UI with web3:
 steps 1 and 2 are working, but step 3 is not working.

I thought even if I don't write` {from:}` in the send function. I t will work -- but it doesn't.
I also tried` {from: address of  smartcontract}` still it doesn't work.

How should I transfer money to a user from smart contract?

Thank you

**Comment by Amxx** [comment]
You cannot send a transaction from a smart contract using `{from: address of smart contract}`

Can you share the smart contract's code. My guess is you issue is with not knowing how to write the smart contract, not with web3.js

**Comment by cgewecke** [comment]
@kuabhish 

Closing because this is a general support question covered by many tutorials and guides to using Ethereum which can be found online. 

The issues here are for reporting bugs specific to the Web3.js library and requesting new features.

**Comment by azmain84** [comment]
> Anda tidak boleh menghantar transaksi dari kontrak pintar menggunakan `{from: address of smart contract}`
> 
> Bolehkah anda berkongsi kod kontrak pintar itu? Tebakan saya adalah isu anda dengan tidak mengetahui cara menulis kontrak pintar, bukan dengan web3.js



> Apa yang saya cuba ialah:
> 
> 1. memberikan beberapa eter kepada kontrak pintar
> 2. apabila pengguna meminta ether, kontrak Smart menghantarnya.
> 3. Saya menulis kontrak pintasan padat dalam kepantasan, yang berfungsi dengan baik. Saya menyemak remix.
> 4. Tetapi apabila saya menulis UI dengan web3: 
>    langkah 1 dan 2 berfungsi, tetapi langkah 3 tidak berfungsi.
> 
> Saya fikir walaupun saya tidak menulis ` {from:}`dalam fungsi hantar. Saya tidak akan berfungsi - tetapi tidak.
> Saya juga cuba ` {from: address of smartcontract}`masih tidak berfungsi.
> 
> Bagaimanakah saya hendak memindahkan wang kepada pengguna dari kontrak pintar?
> 
> Terima kasih

**Comment by kuabhish** [comment]
> You cannot send a transaction from a smart contract using `{from: address of smart contract}`
> 
> Can you share the smart contract's code. My guess is you issue is with not knowing how to write the smart contract, not with web3.js

It doesn't work even when I just write the send function without from 
like:
`myContract.methods.myMethod().send(){value:20}`

It works very nicely in Remix IDE, I am able to do all this funationality from Remix 

> 1. give some ether to smart contract
> 2. when a user ask for ether the Smart contract send it.







> @kuabhish
> 
> Closing because this is a general support question covered by many tutorials and guides to using Ethereum which can be found online.
> 
> The issues here are for reporting bugs specific to the Web3.js library and requesting new features.

I didn't find any tutorial for this task, which i have mentioned. All is working in solidity but when using web3 with metamask , I am not exactly sure , something fails.
