### ISSUE TITLE
BN type for the TypeScript

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.js#3447]
I am writing TypeScriot code with web3.js and was hoping to type in numbers that are `BN` objects.

#### Expected behavior

I can import `BN` from somewhere in Web3.js package, as a lot of type information is available.

#### Actual behavior

I could not find out where is `BN` type.

If someone can point out if this is possible then I can update the relevant documentation. Currently I have tried:

```typescript
import Web3 from 'web3';

// Declare BigNumber type
export type BN = ReturnType<Web3.Utils.toBN>
```

... but this is not valid TypeScript as Web3 is an object, not namespace.

**Comment by azmain84** [comment]
can you help me?

**Comment by cgewecke** [comment]
@miohtama Thanks for opening.

Just leaving some initial notes - this needs more investigation.

+ BN is required in [web3-utils TS defs here][1] - bn.js doesn't maintain its own types. 
+ there are typings for bn.js at [ethereum-ts here][2]. 

[1]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/types/index.d.ts#L23
[2]: https://github.com/ethereum-ts/bn.js-typings

**Comment by miohtama** [comment]
@cgewecke thank you for your kind support!
