### ISSUE TITLE
Batch requests don't include a defaultBlock in params

### ISSUE THREAD

**Issue by ckeenan** [ethereum/web3.js#345]
Is this intentional? I see that doing an non-batched `eth_call` will append "latest" to the params if not already included

But this is not the case for batched requests. Specifying the `defaultBlock` param does not include one in the request params either. The javascript documentation does show a [batch request with the defautlBlock parameter](https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests), which seems to indicate this could be a bug?

**Comment by frozeman** [comment]
PR welcome :)
Actually batch requests are not really useful and even bad, as they will process all the requests serial in the node.

I would actually like to remove them.

**Comment by frozeman** [comment]
Please re-open if thats still and issue with web3 1.0.0
