### ISSUE TITLE
Improve sendSignedTransaction revert reason fetching

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3457]
RE #3420 @nivida noted in gitter that it would be better to reconstitute the failed transaction for replay as a call without making any extra server reqs. In #3420 the call params are obtained by fetching the transaction record.  

An equally terse and more efficient way would be to use [ethers.utils.parseTransaction][1]. 

[1]: https://docs.ethers.io/ethers.js/html/api-utils.html#transactions

**Comment by nivida** [comment]
RLP decoding FTW ;-P @cgewecke
