### ISSUE TITLE
Error message is not appropriate

### ISSUE THREAD

**Issue by nphsu** [ethereum/web3.js#3458]
## Problem

Cannot write values to the contract when using a private key without `0x`.
MetaMask exports a key without `0x`, so I would like to add it automatically.

```javascript
const web3 = new Web3(new Web3.providers.HttpProvider(`https://rinkeby.infura.io/v3/${INFURA_KEY}`))
web3.eth.accounts.wallet.add(PRIV_KEY)

const txParam = {
    from: sender,
    gas: gas,
    gasPrice: gasPrice
}

const contract = new web3.eth.Contract(ABI, CONTRACT_ADDRESS)
contract.methods
        .initialize(...args)
        .send(txParam)
        .on('receipt', receipt => console.log(receipt.transactionHash))
        .catch(e => { if (e) throw e })
```

## Error Message
UnhandledPromiseRejectionWarning: Error: Returned error: The method eth_sendTransaction does not exist/is not available

## Versions
solc v0.5.16
web3 v1.2.6

**Comment by holgerd77** [comment]
Will  close here as well for the same reason as in #3459
