### ISSUE TITLE
Can't recover an account using private key without "0x" prefix 

### ISSUE THREAD

**Issue by bolt-global** [ethereum/web3.js#3474]
#### Expected behavior
I used the method `web3.eth.accounts.privateKeyToAccount`  to create an account but didn't add the prefix 0x in the private key. Since I didn't get any error I assumed it was a valid account. Then I sent some ETH to the account's address. I expected to be able to recover the ETH by calling `web3.eth.sendSignedTransaction`  with my private key 

#### Actual behavior
I can't recover the ETH, when I use the `web3.eth.sendSignedTransaction` method with my private key another account (with another address) is used instead, not the account I created originally. 

**I understand this bug has been reported previously, but is there a way I can recover the account I created using a private key without the 0x prefix?**

#### Steps to reproduce the behavior

1. Use private key without 0x and pass it to `web3.eth.accounts.privateKeyToAccount`
2. send ETH
3. I can't recover the ETH using `web3.eth.sendSignedTransaction` and the private key without 0x

#### Logs
N/A

#### Versions
web3.js: 1.2.6

**Comment by bolt-global** [comment]
I was able to fix the issue. When creating an account using a private key that doesn't have the 0x prefix, the package automatically replaces the 2 first characters of the private key with`00` 

For instance, 
- if I use `0x3e75d9792c6693391d194327f9bc8435033d4e25e97e143e688eaa6e09ed84a6`, the private key will be passed properly in `privateKeyToAccount` method. 
- However, if I pass `3e75d9792c6693391d194327f9bc8435033d4e25e97e143e688eaa6e09ed84a6`, the following key will be used instead: `0x0075d9792c6693391d194327f9bc8435033d4e25e97e143e688eaa6e09ed84a6`

**Comment by cgewecke** [comment]
Thanks for reporting this and the fix - that's good to know.

Changes made in #3316 and #3323 will enforce the 0x prefix by default. They're scheduled to be published with 1.2.7.
