### ISSUE TITLE
Translation web3.js document in korean

### ISSUE THREAD

**Issue by cokia** [ethereum/web3.js#3475]
I want to translate the Web3.js document into Korean. (We have confirmed that the translated document does not exist so far.)

May I take charge of this work?

And if possible, I would like to know if there is a guideline in the translation.

I'm going to use ReadTheDocs, and I'm thinking about whether it's better to PR in the Web3.js Repo or make a separate repo.

If any of you who are looking at this issue knows Korean, it would be good to translate documents with me. :)

**Comment by cgewecke** [comment]
@cokia Thanks for proposing! 

This will require some discussion. I think it would be the first docs translation here.

For future reference, there's some info about managing translations at ReadTheDocs:
+ https://docs.readthedocs.io/en/stable/guides/manage-translations.html

**Comment by cokia** [comment]
What kind of discussion is needed about this?

I'm preparing to translate this, and I'm writing simple translation guidelines in Korean first. However, I think the web3 document needs a "English version" translation guideline for later translation into another language.

**Comment by cgewecke** [comment]
>  I think the web3 document needs a "English version" translation guideline for later translation into another language.

Yes, this would be great.

The immediate questions I have are:
+ what are the technical details of localization at ReadTheDocs?
+ how are translations reviewed and maintained to make sure they're accurate?  
+ how are other Ethereum org projects managing this issue?

**Comment by cgewecke** [comment]
`ethereum/solidity` has several translations [listed here][1] and they look like they're independently maintained on forks.

For example Solidity docs in French are generated
+ at: https://solidity-fr.readthedocs.io/fr/latest/
+ from: https://github.com/Karocyt/solidity-fr/blob/solidity-fr/docs/index.rst


[1]: https://solidity.readthedocs.io/en/v0.6.6/index.html#translations

**Comment by holgerd77** [comment]
Like the `Solidity` way of addressing/organizing this, otherwise this will lead to too much maintenance work for the main repository maintainers.

**Comment by holgerd77** [comment]
@cokia Would you be willing to take on the hosting and maintenance of this on ReadTheDocs? That would be great! 😄

Then we can start a similar "Translated Docs" list in the `Web3` documentation.

**Comment by cokia** [comment]
So should I open an organization called web3-kr?

I may proceed so :)

One of my friend is trying to translate the web3-py document into Korean, and it would be better to gather together and make an organization called web3-kr.

**Comment by cgewecke** [comment]
@cokia Yes sounds good. Will you have separate docs domains for the programming languages? eg
+ `https://web3js-kr.readthedocs.io/en/v1.2.6/`
+ `https://web3py-kr.readthedocs.io/en/v1.2.6/`

As @holger suggested, as soon as you start we can add a docs section similar to the one at Solidity with links to translations so people can find & contribute to it.

**Comment by wanseob** [comment]
@cokia Hey Wu, Please let me know if you need any help with the translation. I'll connect you to the Korean Ethereum translator group who've worked for ethereum.org localization project!

**Comment by cokia** [comment]
https://github.com/web3-kr/web3-js-document-kr

this project is working at this organization.
I think we have to maintain this issue while translation in WIP
