### ISSUE TITLE
"utf8.encode is not a function" when calling a contract function with a string arg

### ISSUE THREAD

**Issue by asinyagin** [ethereum/web3.js#348]
Hi,

I'm getting an error calling a contract function with a string argument: "utf8.encode is not a function" on the line:
```
var fromUtf8 = function(str) {
    str = utf8.encode(str); // this line
    var hex = "";
```
I use web3-light.js in a browser.

**Comment by asinyagin** [comment]
Looks like lib utf8 has some problem with browserify. It's in web3-light.js, but `require('utf8')` returns an empty object.

**Comment by frozeman** [comment]
it was an old function, which was later renamed, fixed in develop
