### ISSUE TITLE
utf-8 encoding error for "min" version of web3.js

### ISSUE THREAD

**Issue by nicos99** [ethereum/web3.js#3480]
When sending message to contract with a string argument containing unicode chars, using web3.min.js v1.2.6, then the utf-8 encoding is wrong because bytes are swap.

#### Expected behavior
`utf8Contract.methods.setText("price is 10 €").send()` --> 
0x5d3a1f9d
0000000000000000000000000000000000000000000000000000000000000020
000000000000000000000000000000000000000000000000000000000000000f
707269636520697320313020**e282ac**0000000000000000000000000000000000
as UTF-8 of '€' = e2 82 ac

#### Actual behavior
0x5d3a1f9d
0000000000000000000000000000000000000000000000000000000000000020
000000000000000000000000000000000000000000000000000000000000000f
707269636520697320313020**ac82e2**0000000000000000000000000000000000
Notice that the 3 bytes for '€' are in reverse order !

#### Steps to reproduce the behavior
1. compile a contract using string, [like this one](https://gist.github.com/nicos99/f2a0dec00f62627ee7fc55988608e9c9#file-utf-8_bug-sol),
2. deploy the contract on a test net (event a localy one),
3. download web3.jv v1.2.6 and upload the file on a web site with an HTML interface to the contract like [this one](https://gist.github.com/nicos99/f2a0dec00f62627ee7fc55988608e9c9#file-utf-8_bug-html),
4. send message with unicode chars

#### Info
The bug is probably related to the "min" version web3 because the encoding is correct when I use the standard js version with Node or when I use Remix "Deploy & Run" module to set the text.

#### Versions
- Web3.js 1.2.6
- Firefox 75.0 (64 bits)
- MetaMask 7.7.8

**Comment by ryanio** [comment]
hey @nicos99, thanks for reporting this issue.

I was able to successfully reproduce that there is some problems in `web3.js` with non-ASCII characters with your test sol contract and html file, thanks for including those. I was able to reproduce in in both `web3.js.min` versions `1.2.6` and `1.2.7`. I saw the problems with the `€` character, and also setting any emojis led to different ones being output when clicking the "read" button.

After updating to `1.2.8-rc.1` which has an updated AbiCoder (#3490), the problems have seemed to resolve and I was able to successfully set and get a string with `€`, emoji characters, etc. using your contract and html file. Could you try using that version and see if the issue resolves for you?

**Comment by nicos99** [comment]
Thank-you @ryanio  for your investigation. I confirm that this bug is likely fixed in version `1.2.8-rc.1` as I see no encoding error anymore using some accented and emoji characters.

By the way I noticed that the behavior of the UTF-8 decoding string has changed : now I get an error from `utf8Contract.methods.text().call()` if input string is invalid (due to the bug for instance) instead of silently lose some chars. May be an other improvement of the AbiCoder ?

**Comment by ryanio** [comment]
> Thank-you @ryanio for your investigation. I confirm that this bug is likely fixed in version `1.2.8-rc.1` as I see no encoding error anymore using some accented and emoji characters.

great!

> By the way I noticed that the behavior of the UTF-8 decoding string has changed : now I get an error from `utf8Contract.methods.text().call()` if input string is invalid (due to the bug for instance) instead of silently lose some chars. May be an other improvement of the AbiCoder ?

yes that is our expected behavior now with the ethers v5 abicoder :) although @ricmoo did add a way to bypass bad data in https://github.com/ethers-io/ethers.js/issues/800 if you were interested in that.

**Comment by cgewecke** [comment]
Fixed in 1.2.8, thanks @nicos99.

**Comment by raymondjacobson** [comment]
Asking a follow up question here if anyone remembers or has thoughts --
ABI Encoding emojis worked for us historically for a *very* long time and around May 17th, 2021 we started receiving the `utf-8 error` as described in this change.

Upgrading to web3 1.2.8 did indeed resolve the issue, but I have a lack of understanding of how this started breaking for us while retaining the same web3 version (1.2.7) for a very very long time.
