### ISSUE TITLE
Web3 can't parse event indexed args of dynamic type

### ISSUE THREAD

**Issue by asinyagin** [ethereum/web3.js#350]
Hi,

Web3 parses event indexed args just like data args (https://github.com/ethereum/web3.js/blob/develop/lib/web3/event.js#L147), but in Solidity indexed arg can take only 32 bytes. So web3 fails to parse length of the value with the error: `Uncaught BigNumber Error: new BigNumber() not a base 16 number:`.

Since version 0.1.7 of `solc` the topic is a hash of a value (#344), earlier it were the beginning 32 bytes of a value.

**Comment by frozeman** [comment]
@chriseth thats exactly what we've talked about

**Comment by asinyagin** [comment]
Also, there's a problem with `allEvents()` and calling of `log0()` in a contract.

```javascript
contract.allEvents(function(err, result) {
    console.log(err, result);
});
contract.test({ from: '0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826' }, function(err, result) {
    console.log(err, result);
});
````

This code creates a filter for all events from contract's address, so it will get `log0()` too. Such logs don't have topics, but web3 expects at least one topic. It gives `Uncaught TypeError: Cannot read property 'slice' of undefined` on line https://github.com/ethereum/web3.js/blob/32b7ee5020e32cc6e0ff8d2b14d29ae116960c12/lib/web3/allevents.js#L55.

**Comment by frozeman** [comment]
This are anonymous logs and i though @debris fixed it. We will look into this.

**Comment by f00bar** [comment]
I'm also bumping into this issue. I'm using indexed strings as event topics but web3 event filter breaks with the following message:

```
contract$ epcis: commissioningAddEvent({fromBlock: 0, toBlock: 'latest'}).watch
contract$ epcis: 
/root/.nvm/versions/node/v5.1.0/lib/node_modules/@crypto/contract/node_modules/bignumber.js/bignumber.js:1177
            var error = new Error( [
                        ^
BigNumber Error: new BigNumber() not a base 16 number: 
    at raise (/root/.nvm/versions/node/v5.1.0/lib/node_modules/@crypto/contract/node_modules/bignumber.js/bignumber.js:1177:25)
```

**Comment by nikhilshekhawat** [comment]
JavaScript	error	22:47:40	web3.js - line 14280 - Uncaught BigNumber Error: new BigNumber() not a base 16 number:

**Comment by frozeman** [comment]
Please re-open if thats still and issue with web3 1.0.0
