### ISSUE TITLE
Websocket events are not emitted correctly

### ISSUE THREAD

**Issue by sirpy** [ethereum/web3.js#3500]
return is premature before calling super.onClose, so anyone subscribing to events will not get them.
same is true for the onError
https://github.com/ethereum/web3.js/blob/2ce573b65abd2f3c78d648b1d70f9a273e922e8c/packages/web3-providers/src/providers/WebsocketProvider.js#L78

**Comment by sirpy** [comment]
still not fixed

**Comment by sacgrover** [comment]
Could you please elaborate more?

**Comment by sirpy** [comment]
in events callbacks (see attached line in description as an example)
if there's ECONNREFUSED error it returns before calling super.onClose
the super class is in charge of emitting the events to other subscribers
so if I as a developer would like to know about these events I wont get them when using the parent class subscription options

**Comment by sirpy** [comment]
@sacgrover

**Comment by sirpy** [comment]
@sacgrover

**Comment by sacgrover** [comment]
@sirpy  this change has been done intentionally. I am not aware why he did that but may be @nivida can explain the reason.

https://github.com/ethereum/web3.js/commit/ff53a2d9f50b9ce306e9bd91d326660f371fff74#diff-82293a4b0698e4c6c953ae0dbf363f32

**Comment by sacgrover** [comment]
I think, I got the reason but it can be fixed another way without stopping parent event emit.. I will raise a pr for it
