### ISSUE TITLE
Write GH Actions "allowed failure" reporter

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3503]
There are 3 CI jobs marked `continue-on-error` which always pass. 

Would be nice if there was an additional cue in the UI about whether they failed or not.

**Comment by ryanio** [comment]
one idea could be to split up the ci script into smaller steps so the `continue-on-error` property can be moved to only the part of the expected failure, so if it fails before that we will get a red x.

**Comment by cgewecke** [comment]
@ryanio We would get a red x but CI would allow merging? That's all that's necessary really...
