### ISSUE TITLE
eth.filter("pending") and eth.filter("latest") do not work at all

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/web3.js#351]
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter

>The string "latest" or "pending" to watch for changes in the latest block or pending transactions respectively.

But neither of these commands output anything:

```
eth.filter("latest").watch(function(error, result) {console.log(result)});
eth.filter("pending").watch(function(error, result) {console.log(result)});
```

**Comment by barkthins** [comment]
They are working for me..

If you are not mining or submitting transactions you won't get those events, so you need to show more about how  you are reproducing the problem

**Comment by barkthins** [comment]
Here's example code that I finally got to completely synchronize modifying a contract and then being able to test that the modification was correct.

this is off of whatever npm gave me as of two days ago.  mining is enabled in geth.

```
    // this should increment for realz:
    myContract.incrData.sendTransaction(function (err, result) {
        if (err) {
            console.error(err);
            return;
        }
        txhash = result;
        filter = web3.eth.filter('latest');
        filter.watch(function(error, result) {
            // XXX this should be made asynchronous as well.  time
            // to get the async library out...
            var receipt = web3.eth.getTransactionReceipt(txhash);
            // XXX should probably only wait max 2 events before failing XXX 
            if (receipt && receipt.transactionHash == txhash) {
                var res = myContract.getData.call();
                console.log('the transactionally incremented data was: ' + res.toString(10));
                filter.stopWatching();
            }
        });
    });

```

**Comment by drupalnomad** [comment]
I thought these filters would just work my themselves without mining. Maybe the documentation just needs to be updated?

**Comment by drupalnomad** [comment]
I can no longer re-produce this issue.
