### ISSUE TITLE
transactionPollingTimeout might not work as documented

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.js#3513]
#### Expected behavior

Setting web3.eth.transactionPollingTimeout to a value changees the trasnaction polling timeout.

#### Actual behavior

`await contract.methods.myMethod.send()` still uses the default 750 seconds value.

#### Steps to reproduce the behavior

Trying to change the behavior using the following code.

```
const web3: any = new Web3(provider);
web3.eth.transactionPollingTimeout = 3600;
```

... does not seem to work as in here...

https://github.com/ethereum/web3.js/blob/2a5c5cb740ee8962846ac9d5416e6b8cc2e7d95d/packages/web3-core-method/src/index.js#L57

...the config value is read when the `Method` of `eth_getTransactionReceipt` is being constructed, which is only when `new Web3()` constructor is called, which is before you can actually set a value `web3.eth.transactionPollingTimeout`. 

I might be wrong and misunderstanding how is it supposed to work, but this is my initial analysis.  Please advise if I misunderstanding and if there is a way to override `transactionPollingTimeout` easily for the `web3` instance and all transactions.

#### Environment

web3.js 1.2.6

**Comment by cgewecke** [comment]
@miohtama 

Thanks for reporting, will investigate. Scanning [the code in web3-eth][1], it's possible this isn't wired up correctly. 

(related: #3498)

[1]: https://github.com/ethereum/web3.js/blob/2a5c5cb740ee8962846ac9d5416e6b8cc2e7d95d/packages/web3-eth/src/index.js#L174-L190

**Comment by cgewecke** [comment]
@miohtama I've tried to reproduce this in #3533 but things seem to be working as expected. 

Have a couple questions...

+ Is the provider being passed to Web3 definitely `http(s)`?
+ What error do you see when the timeout occurs? 
+ If you have a chance, could you look the tests in #3533 and see if they model your case correctly? 

Of necessity they set the polling timeout threshold *lower* than the default. But the outcome suggests that it's being set and evaluated correctly.

**Comment by miohtama** [comment]
It is the default WalletConnect provider, so it is Infura + HTTPS.

I tried to reproduce the issue by setting a timeout to 1 seconds. The timeout is not triggered. 

I can try again - but I would first also ask on the advice what is the proper code to configure the timeout for the smart contract interaction, as it is not clear from the document. Then I can write a minimum repeatable example - which hopefully we cannot repeat.

**Comment by cgewecke** [comment]
@miohtama 

> what is the proper code to configure the timeout for the smart contract interaction

The tests written to validate the setting in #3533 use
```js
web3.eth.transactionPollingTimeout = value
```

If you're experiencing the `.on` related issue you reported in #3498, the timeout failure could be related. A good test for your case might be to run the setting as above *and* use the [workaround suggested in #3498][1]. 

[1]: https://github.com/ethereum/web3.js/issues/3432#issue-588717496

**Comment by cgewecke** [comment]
Closing with 1.2.9...please just ping if this is still happening.
