### ISSUE TITLE
TypeError: Cannot read property 'registerPatient' of undefined. Please help

### ISSUE THREAD

**Issue by Sharmilinukapeyi** [ethereum/web3.js#3516]
my code is as follows
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

<script src="https://code.jquery.com/jquery-3.3.1.min.js""></script>
    <script type="text/javascript">
 window.ethereum.enable();
 window.addEventListener('load', function () {
 window.web3 = new Web3(window.web3.currentProvider);                
        })

var abi=[];
var contractaddress ='0x25b78d5ea0ebeb1fc21cfb030905fef6bade1efe';
var myfunction= new web3.eth.contract(abi,contractaddress);

function registerPatient() {
var name,age,bloodgroup,xname 
name = document.getElementById("name").value
age = document.getElementById("age").value
bloodgroup = document.getElementById("bloodgroup").value

window.ethereum.enable().then(function(err,result) {
try{
myfunction.defaultAccount = web3.eth.accounts[0];
myfunction.methods.registerPatient("akhi",12,"O").send({from: window.web3.eth.accounts[0]}).then(console.log);
}
catch(err) {document.getElementById("output").innerHTML = err; }
});

i am creating contract but i unable to call methods of contract

i m using npm 6.14.5
node v12.16.2
web3 v 1.2.7
but when i printing using alert(window.web3.version.api); it gives 0.20.7
please help to solve this problem

**Comment by cgewecke** [comment]
@Sharmilinukapeyi 

The [MetaMask docs][1] have some resources for building a basic Dapp which interacts with their wallet which you might find helpful.

Web3 1.x is available via CDN:
```html
<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.2.7/dist/web3.min.js">
```

MetaMask's provider can be passed to the Web3 constructor
```
web3 = new Web3(window.ethereum)
```

There's lots of [additional documentation about how to use Web3 here][2]

(Closing because this is a general support question).

[1]: https://docs.metamask.io/guide
[2]: https://web3js.readthedocs.io/en/v1.2.7/getting-started.html

**Comment by Sharmilinukapeyi** [comment]
<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.2.7/dist/web3.min.js">
by adding this nothing is commiing. please clarify

**Comment by cgewecke** [comment]
@Sharmilinukapeyi Just checked the link by visiting the address directly and it works (e.g. I can the minified text in the browser window).

**Comment by Sharmilinukapeyi** [comment]
I checked all. I am creating contract n i am able to access and see balances of all accounts of metamask . but when i try to access methods of remix injected web3 .sol file contract methods i am getting the error "Cannot read property 'registerPatient' of undefined". Where i am doing mistake i unable to know. please clarify
