### ISSUE TITLE
web3 & go-ethereum generating different signature for same message & private key.

### ISSUE THREAD

**Issue by MonarthS** [ethereum/web3.js#3524]
Trying to generate signature using web3:
```
signature = accounts.sign("hello", private_key);
console.log(signature);
// 0x0c196fc53f35d4f962a71d45111cbd5e9bb7005c97eb212d578b5f45d4da84315cc7ed41ba5f03e3f7a0f596db96276836d6094f005c78eede3bb278ab07b4c21b
```

Trying to generate signature using go-ethereum:
```
data := []byte("hello")
hash := crypto.Keccak256Hash(data)
fmt.Println(hash.Hex())
signature, err := crypto.Sign(hash.Bytes(), privateKey)
fmt.Println(hexutil.Encode(signature))
// 0xec911c13e732a6b72e40c731b32583db043c14c26014b4de31d1b1b35720a3580d392a739c525bfb27cebc8e12e5dce6209ad12ac2c1b278f59b4d2379bd72f700
```
#### Expected behavior
Signature should be same in web3 & go-ethereum.

#### Actual behavior
web3 & go-ethereum generating different signature for same message & private key.

#### Logs
The messageHash which is generated by web3 & go-ethereum are different.

web3:
```
messageHash: '0x50b2c43fd39106bafbba0da34fc430e1f91e3c96ea2acee2bc34119f92b37750'
```

go-ethereum:
```
messageHash: '0x1c8aff950685c2ed4bc3174f3472287b56d9517b9c948127319a09a7a36deac8'
```
#### Environment
node: v8.17.0
npm: 6.13.4
go:  1.14.2
OS: macOS Mojave 10.14.6

**Comment by MonarthS** [comment]
Solve signature problem by adding `\x19Ethereum Signed Message:\n` as prefix of message in go-ethereum.

**Comment by SHocker-Yu** [comment]
> 

please help, after add `\x19Ethereum Signed Message:\n` as prefix of message in go-ethereum, the signatures also different,
private_key is get by `crypto.HexToECDSA(private_key）`?

**Comment by SHocker-Yu** [comment]
Solve signature problem by adding length of the message, 
` message = fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s", len(message), message)`

**Comment by barry-en** [comment]
message := fmt.Sprintf("\x19Ethereum Signed Message:\n%d%s", len(msg), msg)
	hash := crypto.Keccak256Hash([]byte(message))
	
	signature, err := crypto.Sign(hash.Bytes(), privateKey)
	if err != nil {
		fmt.Println(err)
	}
	signature[64] += 27
        fmt.Println("go:",hexutil.Encode(signature))
