### ISSUE TITLE
Remove bignumber.js github dependency

### ISSUE THREAD

**Issue by chetan** [ethereum/web3.js#353]
BigNumber.js is currently pulled in from the github master branch instead of via latest npm stable. 

See: https://github.com/ethereum/web3.js/blob/master/package.json#L11

Would it be possible to switch back to npm? I presume that at some point a more recent fix was needed before it was released to npm, but I'm hoping that's not the case anymore. I have an environment where the github dependency isn't allowing me to install web3 easily.

**Comment by frozeman** [comment]
See #362

**Comment by chetan** [comment]
I saw that issue also. This would be an easy change in the meantime until that one is resolved.

**Comment by frozeman** [comment]
We needed to make changes to big number.js because it didn't work in the geth otto vm

**Comment by chetan** [comment]
Sigh :disappointed:, I just realized this is pointing to a fork of bignumber, and not the upstream master. My mistake! In that case, I'll have to find some other solution to getting this to build cleanly in my environment...
