### ISSUE TITLE
"coder.coders undefined" (Cannot read property 'forEach' of undefined)

### ISSUE THREAD

**Issue by pepoospina** [ethereum/web3.js#3538]
#### Expected behavior
Properties of internal objects of the library should not be `undefined`.

#### Actual behavior
The `coders` property of the `coder` variable is `undefined`

#### Steps to reproduce the behavior
I can't create a simple repo to reproduce it. I can only tell you that the [only thing](https://github.com/uprtcl/js-uprtcl/commit/18f6147c9b8fc9ecfb6bc02e7660508fdca052cd) I changed on my codebase was the version of web3.js. From `1.2.1` to `1.2.8`

#### Logs
I am trying to send a transaction of which some of its parameters are an of type `tuple[]`. [This line](https://github.com/ethereum/web3.js/blob/740a98258ead66c16b1ec12f3f888baee64694b6/packages/web3-eth-abi/src/index.js#L170) of 
code from `web3.js/packages/web3-eth-abi/src/index.js`
```
     coder.coders.forEach((c, i) => {
```
fails with an error.
```
index.js:187 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
```

If I debug the error I see that the variable coder is
```
> coder
ArrayCoder {name: "array", type: "tuple()[]", localName: null, dynamic: true, coder: TupleCoder, …}
coder: TupleCoder
    coders: []
    dynamic: false
    localName: null
    name: "tuple"
    type: "tuple()"
    __proto__: Coder
dynamic: true
length: -1
localName: null
name: "array"
type: "tuple()[]"
```

So `coder.coders` is `undefined` but `coder.coder.coders` is `[]`;

By the way, the `param` variable is
```
param
[{…}]
0:
context: "genesis-dao-wiki-7930_1590231082784"
perspective:
    headCid0: "0xbe9beb848cc43c9dec36499c8a8f2ef73de9ace310592b38f928e50dd0e25869"
    headCid1: "0x0000000000000000000000000000000000000000000000000000007a01551220"
    owner: "0xffcf8fdee72ac11b5c542428b35eef5769c409f0"
    perspectiveId: "zb2rhckLbBQCH9wUWvD4K2itS1wTMC1wRRfVCUEacUhkDutCv"
```

#### Environment
works fine with
```
    "web3": "^1.2.1",
    "web3-eth-contract": "^1.2.1",
    "web3-utils": "^1.2.1"
```

fails with
```
    "web3": "^1.2.8",
    "web3-eth-contract": "^1.2.8",
    "web3-utils": "^1.2.8"
```

I am using `"webpack": "^4.10.2",` to build the frontend app.

**Comment by cgewecke** [comment]
@pepoospina 

Can you share the function signature of the Solidity method you're calling and any relevant data type definitions so we can reproduce and fix?

**Comment by malaak-habashy** [comment]
I encountered the same issue

online example of the issue and the code I wrote. in the link below:
https://malaak-habashy.github.io/

I also asked about this issue on stackoverflow
https://stackoverflow.com/questions/61973747/how-to-send-an-array-of-structs-from-web3js-to-solidity-contract

**Comment by ryanio** [comment]
Hey guys, thanks for reporting, I was able to recreate the issue by adding a test for an array of tuples to  `test/abi.encodeParameter.js` e.g.:

```js
test({
  types: ['tuple(string,uint)[]'],
  values: [[['item1', 2], ['item2', 3]]],
  ...
});
```

I will work on a PR to fix this. edit: see #3541

**Comment by malaak-habashy** [comment]
@ryanio thank you

**Comment by layinka** [comment]
Getting this error on web3 1.7.0

**Comment by nyunyunyunyu** [comment]
> Getting this error on web3 1.7.0

<s>+1</s> Sry my bad. It's totally unrelated.
