### ISSUE TITLE
Feature Request : New function to decodeParameters with getTransaction

### ISSUE THREAD

**Issue by cokia** [ethereum/web3.js#3555]
"eth.abi.decodeParameters" is a function that decodes an encoded string based on abi, and I think the main use case is decode the input data of the transaction.

So I think it would be nice to create a function called "web3.eth.abi.decodeFunctionCall" and then take the transaction hash and decode the input data.

If many people and maintainer agree to the need for this function, I will pull request this function.

**Comment by cgewecke** [comment]
@cokia Could you show an example method signature and output for the new method?

**Comment by cokia** [comment]
```js
eth.abi.decodeFunctionCall(abi,TransactionHash);
>  
{
    'function1param1': 'Hello!%!',
    'function1param2': '234',
    function2param1: 'Hello!%!',
    function2param2: '234'
}
```

**Comment by cokia** [comment]
If you are not busy, please leave your comments on this :)

@cgewecke

**Comment by NicolasKritter** [comment]
I had to implement a function like this as we need to parse our own chain, I think this will be a very nice addition to the web3js package

**Comment by cokia** [comment]
I have a simple implementer.
With the accept of the maintainer, I will pull request right away.

**Comment by cgewecke** [comment]
@cokia I'm so sorry, this slipped through. Yes, agree this is a good idea.

**Comment by GregTheGreek** [comment]
@cokia Did you manage to open this pull request? I want to make sure this issue didn't get lost :)

**Comment by cokia** [comment]
I thought it wouldn't be difficult to make this function, but it didn't work as I thought.

```
/**
 * Decode function parameter input from transactionhash.
 *
 * @method decodeFunctionCall
 * @param {Array} jsonInterface
 * @param {string} transactionHash
 * @return {Array} array of parameter values
 */

ABICoder.prototype.decodeFunctionCall = (jsonInterface, transactionHash) => new Promise((resolve,rejct) => {
    var _this = this;
    eth.getTransaction(transactionHash).then(function(err,result){
        if(err){
            throw new Error(
                'Returned values aren\'t valid, did it run Out of Gas? ' +
                'You might also see this error if you are not using the ' +
                'correct ABI for the contract you are retrieving data from, ' +
                'requesting data from a block number that does not exist, ' +
                'or querying a node which is not fully synced.'
            );
        }
            const decodedValue = _this.decodeParameters(jsonInterface, result.input);
            resolve(decodedValue)
    });
})
```

It was my miscalculation that declared as above code, but I thought I could call up the eth sub function.

To call "eth.getTransaction()"you must declare new eth through the provider declared through new web3. But the web3 structure (I think it's problem of I am unskilled to class and constructor) eth need to create and process new constructor with abi, but I think it is not efficient. If anyone can actually implement this idea, please help me.

**Comment by TimDaub** [comment]
> I thought it wouldn't be difficult to make this function, but it didn't work as I thought.
> 
> ```
> /**
>  * Decode function parameter input from transactionhash.
>  *
>  * @method decodeFunctionCall
>  * @param {Array} jsonInterface
>  * @param {string} transactionHash
>  * @return {Array} array of parameter values
>  */
> 
> ABICoder.prototype.decodeFunctionCall = (jsonInterface, transactionHash) => new Promise((resolve,rejct) => {
>     var _this = this;
>     eth.getTransaction(transactionHash).then(function(err,result){
>         if(err){
>             throw new Error(
>                 'Returned values aren\'t valid, did it run Out of Gas? ' +
>                 'You might also see this error if you are not using the ' +
>                 'correct ABI for the contract you are retrieving data from, ' +
>                 'requesting data from a block number that does not exist, ' +
>                 'or querying a node which is not fully synced.'
>             );
>         }
>             const decodedValue = _this.decodeParameters(jsonInterface, result.input);
>             resolve(decodedValue)
>     });
> })
> ```
> 
> It was my miscalculation that declared as above code, but I thought I could call up the eth sub function.
> 
> To call "eth.getTransaction()"you must declare new eth through the provider declared through new web3. But the web3 structure (I think it's problem of I am unskilled to class and constructor) eth need to create and process new constructor with abi, but I think it is not efficient. If anyone can actually implement this idea, please help me.

What I don't understand about this example is that technically the JSON interface shouldn't be necessary as the function and its types are technically encoded in the input data of a transaction. I'm actually a bit surprised that this functionality doesn't exist in web3.js

**Comment by cokia** [comment]
@TimDaub you're right.
it dosen't needs JSON interface.

I think this is a very necessary method, and someone to continue to pull request what I haven't done.

**Comment by mconnelly8** [comment]
Hey @cokia, we will not be implementing this for v1, but we updated it for consideration for a v4 feature request.

**Comment by mconnelly8** [comment]
Closing this issue and tracking it in #4917
