### ISSUE TITLE
"require" smart contract message showed when transaction is revert

### ISSUE THREAD

**Issue by venuziano** [ethereum/web3.js#3557]
A little time ago in my tests transactions when i forced to trigger the require message of my smart contract, in the Status field of transaction it always showed the require message. Now i realized all revert transaction did not show the require message anymore. I checked olders transactions that actually showed this message but all are only with "Fail" now. Does the fail message of a transaction changed or am i crazy?

I was planning to show this require message into client side.

In my smart contract code i have some like that:
`require(keccak256....., "Hash already registered");`

#### Expected behavior
In the Status field a message like this: "fail - Hash already registered"

#### Actual behavior
A message only with "Fail".

#### Steps to reproduce the behavior
Send a transaction to trigger the **require** condition.

#### Logs
Don't have any problem with the log, but just to show the expected console.log.

```
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xaa3e85129f5288cd9fb677122438aaf9c0eae652ceeff54b785aaaa662a56747",
  "blockNumber": 6587528,
  "contractAddress": null,
  "cumulativeGasUsed": 26641,
  "from": "0x181857a9eafdf6412ba38e74e9cabf13d8d8dbdc",
  "gasUsed": 26641,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x2a673bf09b8b4685c094c9e047cebc7797ec93dc",
  "transactionHash": "0xd8c2ecd647984b62519deb3027afaf9e5782c02d3559ea57f7b27242aa1da05b",
  "transactionIndex": 0,
  "events": {}
}
```

#### Environment

npm: 6.14.5
node: v12.16.3
geth: 1.9.14-stable
web3: ^1.2.6

**Comment by cgewecke** [comment]
@venuziano Web3 does not attach the message to the `status` field of the receipt. 

Instead, a `reason` field is populated on the thrown error object if you've enabled revert reason handling using the `handleRevert` setting. 

There's more about this [in the docs here][1].

[1]: https://web3js.readthedocs.io/en/v1.2.8/web3-eth.html?highlight=handleRevert#handlerevert
