### ISSUE TITLE
return value type int and uint actually returns an object

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/web3.js#356]
I have a couple of test functions in solidity:

    function Test1() constant returns (uint)
    {
        return (1234);
    }
    function Test2() constant returns (int)
    {
        return (2234);
    }
    function Test3() constant returns (string)
    {
        return ("3234");
    }
    function Test4() constant returns (bool)
    {
        return (false);
    }

I am running these functions via an instance of a contract in the Chrome console and get some strange object which (amongst others) also contains my return value: 
![image](https://cloud.githubusercontent.com/assets/11379673/11914171/b0b5b308-a678-11e5-80cb-ac68fc344d02.png)

It would be much more convenient if the first two cases would also just return the plain int / uint value.

**Comment by frozeman** [comment]
The first two is an big number object, this is because javascript can't handle big numbers. Though we could return it as number in a string,a and then people could deal with their own big number libraries.

**Comment by SCBuergel** [comment]
Thanks for the explanation, that was not quite clear when looking at an object with members called c, e and s. I think this would be very useful to document.

**Comment by frozeman** [comment]
https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js
