### ISSUE TITLE
My function is payable,I  don't know why it threw the error "Cannot send value to non-payable function"

### ISSUE THREAD

**Issue by nansasuke** [ethereum/web3.js#3569]
This is my function:
![1](https://user-images.githubusercontent.com/50045460/83856245-d23fbe00-a74b-11ea-8950-37aed9605e11.png)

Then I deployed the contract .
![3](https://user-images.githubusercontent.com/50045460/83856763-a53fdb00-a74c-11ea-99c9-0664188bea76.jpg)

Finally,I want to call the bid(),it threw the error:
![2](https://user-images.githubusercontent.com/50045460/83856892-cf919880-a74c-11ea-9b56-59a3fe2d6516.jpg)

#### Environment
web3.js:@0.20.1
Node:12.17.0

**Comment by cgewecke** [comment]
@nansasuke 

Is it possible for you to upgrade to Web3 1.x? Web3 0.2.x has been deprecated for 2 years and is no longer receiving support.

There are some simple working examples of deploying a contract with Web3 1.x in the [unit tests][1] here you might find helpful.

[1]: https://github.com/ethereum/web3.js/blob/1.x/test/e2e.contract.deploy.js

**Comment by nansasuke** [comment]
> @nansasuke
> 
> Is it possible for you to upgrade to Web3 1.x? Web3 0.2.x has been deprecated for 2 years and is no longer receiving support.
> 
> There are some simple working examples of deploying a contract with Web3 1.x in the [unit tests](https://github.com/ethereum/web3.js/blob/1.x/test/e2e.contract.deploy.js) here you might find helpful.

yeah,I've got it!Thank you

**Comment by cgewecke** [comment]
Closing, please just ping if you continue to see this error.
