### ISSUE TITLE
Add browser wallet component to netlify/CDN test

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3577]
[Questions][1] sometimes pop up about how instantiate Web3 correctly in contexts where browser wallets inject the library. And PRs like #3378 and #3499 might benefit from a test fixture that can be used a sanity check for Metamask compatibility.

**Resources**
[MM gist][2]

[1]: https://github.com/ethereum/web3.js/issues/1439#issuecomment-641178492
[2]: https://gist.github.com/bitpshr/076b164843f0414077164fe7fe3278d9#file-provider-enable-js

**Comment by cokia** [comment]
I think this issue is not stale, this is a necessary part of the long term.

**Comment by joeelia** [comment]
I think this issue is not stale, this is a necessary part of the long term.
