### ISSUE TITLE
Error: The current provider doesn't support subscriptions: HttpProvider

### ISSUE THREAD

**Issue by emrem6** [ethereum/web3.js#3579]
#### Expected behavior
Application listens on event in smart contract
#### Actual behavior
null
Error: The current provider doesn't support subscriptions: HttpProvider
    at Timeout._onTimeout (/home/emre/Backend/node_modules/web3-core-subscriptions/src/subscription.js:215:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
#### Steps to reproduce the behavior

1. run node ServerApp.js

#### Environment
I am using Ganache on  RPC SERVER HTTP://127.0.0.1:7545
npm: 6.14.4
Version web3@1.2.8

**Comment by cgewecke** [comment]
@emrem6 

Contract event subscriptions are supported by the Websocket provider. We have some working examples of listening to events [in the unit tests, here][1].  

In ganache the Websocket provider exists on same port as `http` and all you have to do is change the protocol. In your case this would look like:
```
`ws://127.0.0.1:7545`
```

Finally, if you have to use an http provider, the [getPastEvents][2] method is available. 

[1]: https://github.com/ethereum/web3.js/blob/1.x/test/e2e.contract.events.js
[2]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth-contract.html?highlight=getPastEvents#getpastevents

**Comment by aakash4dev** [comment]
don't use `http`, use `wss`.
e.g. 
✅ const web3 = new Web3("wss://rpc-mainnet.maticvigil.com/..........")
👎⚠ const web3 = new Web3("https://rpc-mainnet.maticvigil.com/......")

**Comment by nol4lej** [comment]
> don't use `http`, use `wss`. e.g. ✅ const web3 = new Web3("wss://rpc-mainnet.maticvigil.com/..........") 👎⚠ const web3 = new Web3("https://rpc-mainnet.maticvigil.com/......")

I had problems to subscribe to incoming Block Headers using Moonbase. Change the provider from http to wss works for me! Thanks you

**Comment by Blockchain1207** [comment]
For subscribe, you should use websocket or infra id.
