### ISSUE TITLE
Contract creation in parallel causes bugs in RPC communication between web3.js and geth

### ISSUE THREAD

**Issue by mjackson001** [ethereum/web3.js#358]
Background: In general, deploying a single contract with something like:

var abi = [...];
var code = ‘0x…’;
var contract = web3.eth.contract(abi);
contract.new({data: code, from: web3.eth.coinbase, gas: 3141592});

results in the following 6 steps in order for web3 to create the contract object in Javascript:
1.  eth_sendTransaction - deploy the contract
2.  eth_newBlockFilter - wait for block
3.  eth_getFilterChanges - check for new block
4. eth_getTransactionReceipt - request transaction receipt to get contract address
5. eth_getCode - get the code for the new contract
6.  eth_uninstallFilter - uninstall the filter.

However, when deploying multiple contracts in parallel, the packet flow gets convoluted, extra packets are generated, and in at least some cases the 6th step is missed (possibly others).

In addition, it appears that after attempting to create 8 or more contracts in parallel, in some cases a subsequent synchronous call from a node.js environment will hang indefinitely, with the CPU spiking to 100%.

In tracking this down, there are definitely bugs in the RPC packet flow from the sending side - so I'm filing this to web3.js hoping someone can confirm.

I created a simple test case using node.js with 8 contracts that get deployed simultaneously (asynchronously).  It does not appear that the actual contract content is important - it's the management of the RPC communication channels on the web3.js side that appears to be in question.

I captured a wireshark .pcap file with the packet capture here: https://drive.google.com/file/d/0B-Wpp3xJR_PHZ0lMS1V2UWZsY28

This is a nicer format spreadsheet showing the packet flow, color coded into the 6 stages above for each of the 8 contracts, with comments to the left pointing out what appear to be bugs / observations: https://docs.google.com/spreadsheets/d/133YWv7dwVqcfDETK_5SPfu3McMPNvfcMNcVFhZraKqw/edit?usp=sharing

Text version of the packet capture here: https://drive.google.com/file/d/0B-Wpp3xJR_PHTEU3b18wZ2R4Xzg

**Comment by mjackson001** [comment]
I should add about the test environment: using testrpc, mining on demand, which could affect the timings considerably.

**Comment by frozeman** [comment]
Thanks, thats definitely sounds like a but. i will look into the code once i get time. 

if you want to check for yourself already:
https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L96-L157

**Comment by frozeman** [comment]
I tested this right now with IPC and i can deploy 50 contracts on my test chain without problems:
Testcode:
```js
var Web3 = require('./src/index.js'); var web3 = new Web3(new Web3.providers.IpcProvider('/Users/frozeman/Library/Ethereum/geth.ipc', net));

var contracts = [];
for(var i = 0; i < 50; i++) {
    
    contracts[i] = new web3.eth.Contract(
[{"constant":false,"inputs":[{"name":"tes","type":"address"}],"name":"call","outputs":[{"name":"","type":"bytes4"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"test","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"}],{
    data: '0x6060604052341561000f57600080fd5b5b6101c28061001f6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063f55332ab14610049578063f8a8fd6d146100d4575b600080fd5b341561005457600080fd5b610080600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610129565b60405180827bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19167bffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916815260200191505060405180910390f35b34156100df57600080fd5b6100e7610171565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6000816000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b919050565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600a165627a7a72305820f19efc0824f2ab8336d501f86c0ad79c3823a5f5c0930fa7f60cd501133211da0029'
});

count = 0;

contracts[i].deploy().send({
    from: '0xeb014f8c8b418db6b45774c326a0e64c78914dc0',
    gas: 4000000
})
.on('receipt', (result) => console.log('Receipt #', ++count))
.on('error', (result) => console.log('Error', result) );
}

> Receipt # 1
Receipt # 2
Receipt # 3
Receipt # 4
Receipt # 5
Receipt # 6
Receipt # 7
Receipt # 8
Receipt # 9
Receipt # 10
Receipt # 11
Receipt # 12
Receipt # 13
Receipt # 14
...
```

**Comment by frozeman** [comment]
On HTTP i could mine up to 30 contracts, and the rest was not mined and timed out after 50 blocks?
Im not sure if that has todo with the HTTP or with, geth and the connections itself.

**Comment by nivida** [comment]
Tested on my local node and could create all 50 contracts over HTTP without any problem.
