### ISSUE TITLE
web3.eth.Contract.events cannot catch events named Withdraw

### ISSUE THREAD

**Issue by ccolorado** [ethereum/web3.js#3582]
#### Expected behavior
`myContract.events.Withdraw` would catch events named Withdraw

#### Actual behavior
`myContract.events.Withdraw`  comes back empty

#### Steps to reproduce the behavior
Tried the code @ https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html#contract-events
I was able to get any event not named Withdraw

```
        let y = await this.myContract.events.myOtherEvent({
          fromBlock: 0
        }, function(error, event){ console.log(event); })
        .on("connected", function(subscriptionId){
          console.log('a: ', subscriptionId);
        })  
        .on('data', function(event){
              console.log('b :', event); // same results as the optional callback above
        })  
        .on('changed', function(event){
              console.log('c :', event); // same results as the optional callback above
              // remove event from local database
          })  
          console.log("y : ", y)
  
  
        let x = await this.myContract.events.Withdraw({
          fromBlock: 0
        }, function(error, event){ console.log(event); })
        .on("connected", function(subscriptionId){
          console.log('a: ', subscriptionId);
        })  
        .on('data', function(event){
              console.log('b :', event); // same results as the optional callback above
        })  
        .on('changed', function(event){
              console.log('c :', event); // same results as the optional callback above
              // remove event from local database
          })  
```
Using `getPastEvents` worked fine with Withdraw events
https://web3js.readthedocs.io/en/v1.2.7/web3-eth-contract.html#getpastevents

#### Environment
truffle on archlinux
web3 1.2.6

**Comment by cgewecke** [comment]
@ccolorado 

Just to double-check, could you update your filter param key so it's spelled correctly and retry?
```diff
- formBlock: 0
+ fromBlock: 0
```

**Comment by ccolorado** [comment]
@cgewecke thanks for noticing, updated the code, And I can confirm that It is still having the same behavior.

**Comment by cgewecke** [comment]
@ccolorado 

There's nothing at Web3 that would make `Withdraw` itself a problematic event name. I'm sorry. 

And you're saying that you're able to hear other events with same logic and retrieve it with getPastEvents?

You'll have make a minimal example that reproduces the problem so it can be investigated further.

**Comment by cgewecke** [comment]
Closing for now. If there's a reproduction case for this that indicates a Web3 bug please ping.
