### ISSUE TITLE
npm audit - security warnings for web3

### ISSUE THREAD

**Issue by positonic** [ethereum/web3.js#3588]
#### Expected behavior
No npm audit warnings

#### Actual behavior
Running `npm run audit` gives me this warning about web3:
### Steps to reproduce the behavior

1. npm i web3
2. npm audit

#### Logs

 Low           │ Insecure Credential Storage                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/877 

#### Environment

node v12.13.0 using nvm
nvm v6.12.0

**Comment by cgewecke** [comment]
This topic is being tracked at #2739 (the issue which ultimately prompted the audit report.) 

The consensus there is that this can't be addressed as a patch.  

Below is [the analysis][2] of the engineer who raised the advisory:

>To be clear, there is at present nothing wrong with the wallet as is. We could re-implement this system to be much more secure than it already is, and that is a good target for 2.0, but the current implementation isn't insecure in any realistic way if used properly.

>To use it properly, you just need to NOT perform wallet.load into any object available from within the global scope. Instead create a local variable, assign to it with wallet.load and pass it around as needed then simply delete it as soon as you are done with it. That addresses the issues I mentioned. In short, I wasn't using it right and that was what introduced the vulnerability.



Please also be aware of the warning published in [web3-eth-accounts documentation][1]:

>  This package has NOT been audited and might potentially be unsafe. Take precautions to clear memory properly, store the private keys safely, and test transaction receiving and sending functionality properly before using in production!

Closing as duplicate. 

[1]: https://web3js.readthedocs.io/en/v1.2.9/web3-eth-accounts.html#web3-eth-accounts
[2]: https://github.com/ethereum/web3.js/issues/2739#issuecomment-498216714
