### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [ethereum/web3.js#3589]
It would be great if web3.js provided support for deploying and upgrading diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by GregTheGreek** [comment]
I've briefly gone over the draft EIP and it looks very interesting. This is a Dapp framework specific issue, perhaps if wider adoption came it would make sense to implement. That being said, I'm curious to hear what exactly you envision direct support to be?

**Comment by mudgen** [comment]
@GregTheGreek Thanks for taking a look at this!

Support would be these things:  Make it easier to deploy and upgrade diamonds.  For example provide a function that takes a diamond proxy and a list of facet addresses and deploys them all and adds the facets to the diamond at the same time.

**Comment by GregTheGreek** [comment]
It sounds like this might be better suited for an independent js tool in all honesty. Support for very specific EIP like this is a tough to draw the line at what should and shouldn't be included, as you can imagine there are a lot of EIPs.

I think we'll close this for now, but please feel free to re-open this in the future if you believe its gotten to the point where its very widely adopted :)
