### ISSUE TITLE
BigNumber Error - address parameter in method

### ISSUE THREAD

**Issue by elmurci** [ethereum/web3.js#359]
Hi,

I have a contract with the following method:

```sh
function myMethod(address _to, uint _value) returns(bool success) {
```

However, when I try to call this method with web3:

```sh
myContract.myMethod('eec569b9890e90eb1a6e883ac32a9348564d99d8', 20);
```

I get the following error:

```sh
BigNumber Error: new BigNumber() not a number: eec569b9890e90eb1a6e883ac32a9348564d99d8
```

Not sure what I am missing as the first parameter on _myMethod_ is an address type not a number?

Thanks

**Comment by elmurci** [comment]
If I call the method locally it works fine:

```sh
myContract.myMethod.call('eec569b9890e90eb1a6e883ac32a9348564d99d8', 20);
```

**Comment by frozeman** [comment]
try adding `0x` and a from:
`myContract.myMethod('0xeec569b9890e90eb1a6e883ac32a9348564d99d8', 20, {from: '0x23456', gas: 12345678});`

**Comment by elmurci** [comment]
Adding a from worked.

However the transaction is going through and mined with no errors but the state is not being changed.

I have this line where I change the value of a variable

```sh
balance = 999;
```

But nothing is happening.

Thanks!

**Comment by elmurci** [comment]
thanks, adding a from worked.

**Comment by Tectract** [comment]
You can also see this error if you forgot to "migrate / deploy" your contract.
