### ISSUE TITLE
returnValues with incorrect Object formation

### ISSUE THREAD

**Issue by thecircleoflifefree** [ethereum/web3.js#3590]
Issue `returnValues` parsed incorrectly
#3158  is tagged as enhancement, current issue below is NOT an enhancement.

returnValues is returning an incorrect object formation. This example is using Truffle metacoin example and has been tested on other contracts as well:

   returnValues:
     Result {   <----------------------- incorrect formation
       '0': '0xabc',
       '1': '0xabc',
       '2': ''0xabc',
       _from: '0xyz',
       _to: '0xyx',
       _value: '1' },

Expected to have ':' i.e:   Result: {}

After checking the docs 1.2.1 and latest version, I do not even see "Result" as part of the parsed returning:

myContract.getPastEvents('MyEvent', {
    filter: {myIndexedParam: [20,23], myOtherIndexedParam: '0x123456789...'}, // Using an array means OR: e.g. 20 or 23
    fromBlock: 0,
    toBlock: 'latest'
}, function(error, events){ console.log(events); })
.then(function(events){
    console.log(events) // same results as the optional callback above
});

> [{
    returnValues: {  <--------------------------------------------- No "Result" 
        myIndexedParam: 20,
        myOtherIndexedParam: '0x123456789...',
        myNonIndexParam: 'My String'
    },

**Comment by cgewecke** [comment]
@thecircleoflifefree 

#3518 is about the hashing of dynamically sized types when they are indexed event parameters.

Truffle wraps Web3 with its own logic and may reformat some outputs. Is it possible the problem you're having originates there?

**Comment by thecircleoflifefree** [comment]
@cgewecke I do not know, but if you confirm issue is not here feel free to close and I'll reach out to them.

**Comment by cgewecke** [comment]
@thecircleoflifefree I don't believe the issue is here. 

If you have a simple reproduction case you can express in the style of our [events integration tests][1] am happy to re-open.

[1]: https://github.com/ethereum/web3.js/blob/1.x/test/e2e.contract.events.js

**Comment by thecircleoflifefree** [comment]
@cgewecke  this issue occurs even when you invoke instance.contract.getPastEvents() (the web3 method), not just when you invoke instance.getPastEvents() (the Truffle method), this should be enough to point out the issue being outside the scope of Truffle team. Let me know your thoughts.

**Comment by cgewecke** [comment]
@thecircleoflifefree 

This is what I see using `getPastEvents` and `web3 1.2.8`

```javascript
const event = await instance.getPastEvents('myEvent', {fromBlock: 0})
> [
 {
  "logIndex": 0,
  "transactionIndex": 0,
  "transactionHash": "0xd2476829aab00c6a193051cae019f6f4435f9f0c514315cadbbc894d55341cf7",
  "blockHash": "0x2b6f59aef2aec02c38b115d0220f6c0be60a31bd4c3b94271a65025edaf6a7c0",
  "blockNumber": 93,
  "address": "0x2B3985230F3ef0BeFAa71F4AF726FE8774A10162",
  "type": "mined",
  "id": "log_a799bfd5",
  "returnValues": {
   "0": "0x0000000000000001",
   "1": "0xaaaaaaaa",
   "2": "0xbbbbbbbb",
   "b1": "0x0000000000000001",
   "b2": "0xaaaaaaaa",
   "b3": "0xbbbbbbbb"
  },
  "event": "myEvent",
  "signature": "0xd21806d1d44bf86e639c142c7bb6fe868a5bae6f35b4934c84008233b4992c97",
  "raw": {
   "data": "0x0000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000840000000000000000000000000000000000000000000000000000000000000004aaaaaaaa0000000000000000000000000000000000000000000000000000000000000004bbbbbbbb",
   "topics": [
    "0xd21806d1d44bf86e639c142c7bb6fe868a5bae6f35b4934c84008233b4992c97"
   ]
  },
  "args": {
   "0": "0x0000000000000001",
   "1": "0xaaaaaaaa",
   "2": "0xbbbbbbbb",
   "__length__": 3,
   "b1": "0x0000000000000001",
   "b2": "0xaaaaaaaa",
   "b3": "0xbbbbbbbb"
  }
 }
]
```

If you **create a simple reproduction case in the style of our [events integration tests][1]** will be happy to look into this further. 

[1]: https://github.com/ethereum/web3.js/blob/1.x/test/e2e.contract.events.js
