### ISSUE TITLE
Decoding array of struct (MyStruct[]) to an array of objects?

### ISSUE THREAD

**Issue by kevholder** [ethereum/web3.js#3591]
### Expected behavior

When a method returns an array of structs (e.g. `MyStruct[]`), web3js should decode it to an array of objects that have the same shape as MyStruct.

#### Actual behavior

When a method returns an array of structs (e.g. `MyStruct[]`), web3js decodes it as an array of arrays.

#### Steps to reproduce the behavior

1. Deploy test contract

```solidity
pragma solidity >= 0.5.0 < 0.7.0;
pragma experimental ABIEncoderV2;

contract MyContract {
  struct Entry {
    uint inputAmount;
    uint outputAmount;
  }

  Entry[] public entries;

  constructor() public {
    Entry memory entry = Entry({
      inputAmount: 1,
      outputAmount: 2
    });
    entries.push(entry);
  }

  // workaround: otherwise web3js can only index into the array
  function entriesArray() external view returns (Entry[] memory) {
    return entries;
  }
}
```

2. Call entriesArray() getter

```javascript
const data = await myContract.methods.entriesArray().call();
// returns [["1", "2"]] but it should return:
// [{ inputAmount: "1", outputAmount: "2" }]
```

#### Environment

```
web3 1.2.9
```

**Comment by kevholder** [comment]
Using this as a workaround:

```javascript
const entryProps = exchangeAbi
  .find((abi) => abi.name === "entriesArray")
  .outputs[0].components.map((c) => c.name);

const decodeEntriesArray = (entries) => {
  // workaround: https://github.com/ethereum/web3.js/issues/3591
  return entries.map((entry) => {
    return Object.fromEntries(
      entry.map((val, idx) => {
        return [entryProps[idx], val];
      })
    );
  });
};
```

**Comment by GregTheGreek** [comment]
Sorry for the delay, this is a pretty great idea! Drastically improves the UX.

This would definitely be a breaking change in the way existing applications use web3.js, but an alternative option would be to include the above helpers, until a breaking change is ready. We could create a method (eg: `mapABItoResults` ) where you could wrap your results into.

Thoughts: @cgewecke @kevholder

**Comment by cgewecke** [comment]
Agree, a really good improvement.

There's also precedent at Web3 for gating some enhancements like this behind a settings flag. For example revert reason fetching is currently enabled by setting `web3.eth.handleRevert = true`.

**Comment by GregTheGreek** [comment]
Great idea. We can probably push this up the list

**Comment by kevholder** [comment]
Would you like me to send a pull request?

**Comment by GregTheGreek** [comment]
That would be great!

**Comment by debnath-d** [comment]
@GregTheGreek Any update on this issue? Were the helper functions mentioned in the discussion above implemented?

Also, I think the issue should be reopened and not marked stale.

**Comment by Ajit-91** [comment]
is there any inbuilt method in web3 for achieving this ?

**Comment by ilya-korotya** [comment]
Hi @GregTheGreek. Any updates on this issue?
