### ISSUE TITLE
Official documentation for web3 v0.x no longer viable

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#3595]
The official documentation for web3 v0.x, which used to be [here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3js-api-reference), is no longer viable.

This version is still used by many, as far as I'm aware of.
Specifically, by anyone using truffle v4.x, which relies on it.
I believe that this is also the case for many dapps out there.

Thanks

**Comment by cgewecke** [comment]
@barakman 

Thanks for flagging this. The 0.2.x docs can be found here now: 

https://github.com/ethereum/web3.js/blob/0.20.7/DOCUMENTATION.md

We will fix the wiki so it links to both.

**Comment by barakman** [comment]
@cgewecke : Awesome, thank you :)
I mostly use v1.2.0 documentation, but sometimes I require stuff from the old one...

**Comment by cgewecke** [comment]
Wiki's updated, thanks again.
