### ISSUE TITLE
utf8 confuses browserify

### ISSUE THREAD

**Issue by gpersoon** [ethereum/web3.js#3601]
#### Expected behavior
web3 can be browserified to use in browser

#### Actual behavior
Uncaught SyntaxError: Unexpected identifier in chrome developer console

#### Steps to reproduce the behavior
browserify web3.js and use it in an application

Open https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/src/index.js in an editor that can show files in multiple formats (like notepad++)
Switch the format to ASCII.
Observe the last 10 lines, start at toTwosComplement.
Here you see multiples instances of Â, which are utf8 characters
```js
    toTwosComplement:Â utils.toTwosComplement,

Â Â Â Â isBloom:Â utils.isBloom,
Â Â Â Â isUserEthereumAddressInBloom:Â utils.isUserEthereumAddressInBloom,
Â Â Â Â isContractAddressInBloom:Â utils.isContractAddressInBloom,
Â Â Â Â isTopic:Â utils.isTopic,
Â Â Â Â isTopicInBloom:Â utils.isTopicInBloom,
Â Â Â Â isInBloom:Â utils.isInBloom
};
```
 
#### Environment

windows 10, chrome, web3.js 1.2.9, installed via npm install web3

**Comment by cgewecke** [comment]
@gpersoon Thanks for reporting. 

This is very odd - it looks like those characters may have been introduced in #3291. (We should also check #3137).

Could you clarify when and how you see this error? Does the entire package fail to load?  

Web3.js [uses browserify][1] to generate the minified bundle it publishes to CDN and we run tests using it in Chrome and Firefox headless browsers. Everything works there but it's likely these whitespace chars are being removed during the uglification step. 

(That might be a work-around in your case as well.)

[1]: https://github.com/ethereum/web3.js/blob/898322bb6b4675c3778d526d9a01f9e147c25ece/gulpfile.js#L155-L220

**Comment by gpersoon** [comment]
> Could you clarify when and how you see this error? Does the entire package fail to load?

I see the error in a website that includes a bundle.js that is created with browserify.
The executing of the javascript in the website stops at:
```js
bundle.js:81190 Uncaught SyntaxError: Unexpected identifier
```
This is exactly the location where the Â characters are located

I also checked on firefox, where i saw this message:
```js
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```
I figured out putting the following line in the HTML file is a workaround to recognize & ignore the special characters:
```js
<meta charset="utf-8" />
```
