### ISSUE TITLE
Default export / TS types definition mismatches in Web3 sub-modules

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3606]
This is a tracking issue for the general problem described in #3587. 

The current types definitions for sub-modules listed below cause TS  to miscompile the class constructors, throwing an error like:
```
Uncaught TypeError: web3_eth_abi__WEBPACK_IMPORTED_MODULE_1__.AbiCoder is not a constructor
```
The root package is unaffected. 

| Package | Widely used |
| -------- | ---- |
| web3-bzz | |
| web3-core-method | |
| web3-eth | ✅  (#3198) |
| web3-eth-abi | ✅  (#3587) |
| web3-eth-accounts | ✅  (#3292) |
| web3-eth-contract | |
| web3-eth-ens | ✅  |
| web3-eth-iban | |
| web3-eth-personal | |
| web3-net | |
| web3-providers-http | ✅  |
| web3-providers-ws | ✅  (#3215) |
| web3-providers-ipc | |
| web3-shh | |

Notes:
+ This issue needs further analysis - there *may* be a way to rewrite the types or require a ts-config setting or some combination of the two which can resolve this in a non-breaking fashion.
+ Web3 should have some kind of ts-node based smoke test for sub-module usability. The existing typedef tests failed to catch the problem e.g the current definitions `tsc` (without error) down to unusable code.

**Comment by Velenir** [comment]
> * This issue needs further analysis - there _may_ be a way to rewrite the types or require a ts-config setting or some combination of the two which can resolve this in a non-breaking fashion.

I think the way I suggest to change exported types in #3587 is pretty non-breaking:

- Mark exported classes as `export type`
- Export variables that JS code actually exports

That way we make TS happy and don't touch actual JS, so nobody who uses JS has to change anything. And anybody who uses TS with workarounds (`as any`, declaration merging) also doesn't have to change anything.

**Comment by Legogris** [comment]
Bump

**Comment by truemoroz** [comment]
Bump
