### ISSUE TITLE
Improve Error reporting

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#361]
Add proper error, when properties are missing or wrong. Get rid of the weird BigNumber errors.

**Comment by chriseth** [comment]
Which component does this refer to?

**Comment by frozeman** [comment]
Its meant as a reminder in general.

The error reporting is bad, because you mostly get big number errors.

So we need better errors for:

- when the ABI output can't be parsed correctly by the given interface type (e.g. if the node sends something strange)

- for input parameters, e.g. if you forget the `from` in a sendTransaction. We have to go through these then one by one, once we get there.

**Comment by barkthins** [comment]
You also swallow errors in httpprovider, meaning any network or memory errors have their root cause thrown away. For example ENOMEM from spawn gets thrown away.

**Comment by frozeman** [comment]
Thanks for the hint, yes, this should improved

**Comment by philipcmonk** [comment]
I just ran into the issue barkthins described (ENOMEM error gets thrown away in httpprovider).

I'd love to fix this.  Does it sound reasonable to add an optional parameter to `InvalidConnection`[0] to specify a reason?  Then check for `errno` in the error here[1], and pass it to `InvalidConnection` if we have it?

[0] https://github.com/ethereum/web3.js/blob/d44d0b76/lib/web3/errors.js#L30
[1] https://github.com/ethereum/web3.js/blob/d44d0b76/lib/web3/httpprovider.js#L83
