### ISSUE TITLE
Rewrite confirmTransaction to handle re-orgs

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#3611]
### Problem
#3608 discovered a bug where [confirmTransaction](https://github.com/ethereum/web3.js/blob/77bd9f9d3ae4d0fbc5c1e1e59871177eb428a878/packages/web3-core-method/src/index.js#L268) doesn't properly handle a re-org. It is most likely occurring within [this code block](https://github.com/ethereum/web3.js/blob/77bd9f9d3ae4d0fbc5c1e1e59871177eb428a878/packages/web3-core-method/src/index.js#L311-L335), because there is no concept of a start/previous block theres no ability to perform a check for inconsistencies between blocks. 

### Potential solution
We probably want to track a few different things:
- StartBlock - When we began polling
- PreviousBlock - The block that we just checked (Note: this is not `block -1`, we must actually cache the received block)
- IncludedBlock - The block that the transaction was included in

This way we can do a check such as (very naive): `currentBlockNumber - PrevioudBlockNumber == 1` to ensure that we're on the sequential chain. We may also want to double check that the `includedBlock` hasn't changed with the incoming `receipt`. Doing those checks could **identify** a reorg took place. To properly account for the number of confirmations the counter, found on line [334](https://github.com/ethereum/web3.js/blob/77bd9f9d3ae4d0fbc5c1e1e59871177eb428a878/packages/web3-core-method/src/index.js#L334) should actually be computed by using `currentBlockNumber - PreviousBlockNumber` so it can reset if there is a re-org. I believe doing that alone, would probably solve this issue, but it might be interesting to see if we want to log a re-org.

I found an [stackoverflow](https://ethereum.stackexchange.com/questions/1187/how-can-a-dapp-detect-a-fork-or-chain-reorganization-using-web3-js-or-additional) that can be used as inspiration.

cc: @cgewecke

**Comment by benjamincburns** [comment]
I'm writing a new `TransactionManager` because of #3632. If I can't fix this issue as part of the initial PR, I'll at least do my best to lay some groundwork. At the very least, the code I submit will be a lot more readable than what's there today.

**Comment by GregTheGreek** [comment]
That would be awesome!

**Comment by GregTheGreek** [comment]
get outta here stale bot

**Comment by GregTheGreek** [comment]
@benjamincburns just want to confirm you're not touching on this anymore?
