### ISSUE TITLE
isHex(1) replies true,   isHexStrict(1) replies false, Regular expression of isHex is bad

### ISSUE THREAD

**Issue by pepihasenfuss** [ethereum/web3.js#3614]
web3.js 1.2.9

line 96492 is buggy, utils.isHex() DOES NOT reply correctly, the reg-ex part is false, sorry

var isHex = function isHex(hex) {
  return (_.isString(hex) || _.isNumber(hex)) && /^(-0x|0x)?[0-9a-f]*$/i.test(hex);
};

I took the code out of web3.js and tried a simple test:

function isString(arg) {
    return typeof arg === 'string';
  }
  
  function isNumber(arg) {
    return typeof arg === 'number';
  }
  
  function isHex(hex) {
    return (isString(hex) || isNumber(hex)) && /^(-0x|0x)?[0-9a-f]*$/i.test(hex);
  };
  
  function isHexStrict(hex) {
    return (isString(hex) || isNumber(hex)) && /^(-)?0x[0-9a-f]*$/i.test(hex);
  };

console.log( isHex(1), isHex(0), isHex(345), isHexStrict(1), isHexStrict(0), isHexStrict(345) );

#### Expected behavior

false false false false false false

#### Actual behavior

true true true false false false

#### Steps to reproduce the behavior

run utils.isHex(1)

#### Environment

web3.js 1.2.9, google chrome, MacOS-X

**Comment by GregTheGreek** [comment]
Do you mind providing a link to the part you believe to be incorrect?

**Comment by pepihasenfuss** [comment]
If you open web3.js (3Mb) version, not the minified one, you'll find the function isHex in line 96492 ! Yes, web3.js has almost 100.000 lines of code. isHEx() is pretty much at the end. I'm not familiar with Nodes.js and the building process, therefore I cannot locate where this part of utils. comes from, sorry.

**Comment by pepihasenfuss** [comment]
I guess it is from web3-utils/src/utils.js, the bug can also be found in web3-utils.js, of course, line 13784.
In the utils.js source file, the function return value is in additional closures, but it does not help. The part with the regular expression is the problem, but I'm not familiar with regular expressions.
I stumbled accross this after a painful experience. Then, I used isHexStrict() instead and it worked for me.

**Comment by GregTheGreek** [comment]
@pepihasenfuss After looking over the implementation, it appears that this is operating as expected. Do you mind explaining what exactly you're finding incorrect about this function?

`isHex()` & `isHexStrict()` accept both strings and numbers, the main difference between the two is that `isHex` does not require the `0x` prefix, where `isHexStrict()` does.

**Comment by pepihasenfuss** [comment]
Well, I expected that isHex('0x123') returns true, which is OK.
I expected that isHex(1) returns false. I thought that 1 is NOT a hex-value. Am I wrong?
At least, I thought this was misleading.
If this is intended, OK, but feels a bit strange to me. So what.

**Comment by GregTheGreek** [comment]
Because `isHex` does not strictly look for the prefix, `1` would be considered equivalent to `0x1`, If you want strict values, please use `isHexStrict()`

**Comment by pepihasenfuss** [comment]
ok, thank you!
