### ISSUE TITLE
Add unit tests to web3-utils

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#3615]
#3614 brought to light that the testing being conducted on web3-utils is lacking. Some basic unit tests should be added to cover some of the more common cases.

**Comment by andrew-m-higgs** [comment]
I have added a test for isHex. In it I have the following:

var tests = [
    { value: 1, expected: true },
    { value: '1', expected: true },
    { value: '0xH', expected: false},
    { value: 'H', expected: false},
    { value: [1,2,3,{test: 'data'}], expected: false},
    { value: {test: 'test'}, expected: false},
    { value: '{"test": "test"}', expected: false},
    { value: 'myString', expected: false},
    { value: 'myString 34534!', expected: false},
    { value: new BN(15), expected: false},
    { value: new BigNumber(15), expected: false},
    { value: 'Heeäööä👅D34ɝɣ24Єͽ-.,äü+#/', expected: false},
    { value: true, expected: false},
    { value: false, expected: false}
];

Are these all correct? Should isHex(BigNumber(15)) return false? 

They all pass as configured above. Any other tests that need to be added?

Regards

**Comment by andrew-m-higgs** [comment]
And isHexStrict: 

var tests = [
    { value: 0x1, expected: false },  //0x1 would be tested as 1
    { value: '0x1', expected: true },
    { value: '0xH', expected: false},
    { value: 'H', expected: false},
    { value: [1,2,3,{test: 'data'}], expected: false},
    { value: {test: 'test'}, expected: false},
    { value: '{"test": "test"}', expected: false},
    { value: 'myString', expected: false},
    { value: 'myString 34534!', expected: false},
    { value: new BN(15), expected: false},
    { value: new BigNumber(15), expected: false},
    { value: 'Heeäööä👅D34ɝɣ24Єͽ-.,äü+#/', expected: false},
    { value: true, expected: false},
    { value: false, expected: false}
];

Same as above. Any other checks that would be useful?

Regards

**Comment by GregTheGreek** [comment]
Big numbers should return false, they are not hex values in javascript

**Comment by GregTheGreek** [comment]
this looks good to me, would be happy to accept a pr :)

**Comment by andrew-m-higgs** [comment]
Great.

This will be my first. I have cloned on my side and added tests for both.
What do I need to do to send the PR to you?

Sorry. Bit of a noob.

Regards

**Comment by GregTheGreek** [comment]
Not a problem, we were all there once!
1. Fork the repo
2. Add changes to your branch
3. Open a pull request
4. Make sure the base branch targets `ethereum/web3.js` 

:)
