### ISSUE TITLE
Remove BigNumber.js dependency 

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#362]
Removing BigNumber.js will allow developers to choose their own big number library.

Large numbers will be returned as number string e.g. `'1234560000000000000000'`, which can be converted to a BigNumber using any big number library.

This improves readability, makes web3 more lightweight and removes the necessity to expose the BigNumber dependency to developers.

Should solve also #322

**Comment by chriseth** [comment]
Please note that there is a difference between "number" and "byte array". If you represent a byte array is a decimal string, leading zeros might be removed, so it could be better to always encode as hex string.
It might also be worthwile to think about using `Uint8Array`s.
Furthermore, please check that the added overhead of constantly en- and decoding might impact performance.

**Comment by frozeman** [comment]
no we only convert `int` types to `'2345678765432'`, not and they are transferred as HEX over RPC. But having these numbers readable gives a huge benefit for dapp developers.

could you point me to an example where we could accidentally convert a int value wrong?

**Comment by chriseth** [comment]
If this is only done for integer types (with known size), it is fine. Where we get problems are hash values and byte arrays in general. I certainly see the benefit of using decimals, but it might be confusing to have two different encodings.

(Just listing potential arguments here, not meant as criticism.)

**Comment by frozeman** [comment]
the encoding is always HEX in RPC, but a web developer needs proper types, so we convert them when  we know the type. We certainly will  not convert bytes32 to string or numbers.
