### ISSUE TITLE
ENS Error on Kovan

### ISSUE THREAD

**Issue by hbarcelos** [ethereum/web3.js#3620]
#### Expected behavior

Since I'm not using ENS for anything, there shouldn't be an error.

#### Actual behavior

Upon initialization, I get the following error:

```
18:42:52.381 Uncaught (in promise) Error: ENS is not supported on network kovan
    checkNetwork ENS.js:527
    Registry Registry.js:43
    get ENS.js:46
    get ENS.js:53
    e (index):1
    e (index):1
    e (index):1
    e (index):1
    e (index):1
    e (index):1
    e (index):1
    t (index):1
    stringify (index):1
    n (index):1
    m (index):1
    S (index):1
    x/$< (index):1
    _ (index):1
    O (index):1
    S (index):1
    setTimeout handler*x/< (index):1
    x (index):1
    W (index):1
    dispatch Redux
    e (index):1
    createSerializableStateInvariantMiddleware serializableStateInvariantMiddleware.ts:190
    createImmutableStateInvariantMiddleware Immutable
    Redux 2
    routerMiddleware middleware.js:22
    normalizeErrorMiddleware normalizeErrorMiddleware.js:3
    actionIdMiddleware actionIdMiddleware.js:4
    dispatch (index):1
    useConnectToProvider createHooks.js:50
    useEagerWalletConnection createHooks.js:112
    useComonentDidMount createHooks.js:186
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 4
    unstable_runWithPriority scheduler.development.js:653
ENS.js:527:18
```

#### Steps to reproduce the behavior

1. Connect to web3.js throught MetaMask injected provider pointed to Kovan.

#### Logs

N/A

#### Environment

- Node: 10.21.0
- Web3js: 1.2.9
- MetaMask: 8.0.1

**Comment by pepihasenfuss** [comment]
Perhaps, this may help you to find a workaround: 
I'm a huge fan of ens and my dapp needs it heavily. Someone asked for ENS2 on kovan and my tool needed it too, therefore, I did an (experimental) installation on kovan at https://kovan.etherscan.io/address/0xb66b2f307b6e46a6d038a85997b401ae87455772#code and https://kovan.etherscan.io/address/0x7966398e99a60c7b3465a394b22c0b5ce1012ec9#code .
I don't know if ENS 2.0 will be officially available on kovan, therefore I did it by myself in the meantime.
I know, this may not directly help you with your web3.js problem. Peter

**Comment by GregTheGreek** [comment]
Looking into this.. I know Metamask uses 0.9.0^ so I'll have to see what exactly is causing this...

**Comment by hbarcelos** [comment]
Additional info:

The last version where I don't see this error is `1.2.6`, any version `>=1.2.7` throws the error above.

**Comment by GregTheGreek** [comment]
Do you mind providing a code snippet? I'm having a hard time reproducing this error because metamask doesn't inject the web3 api anymore.

**Comment by zemse** [comment]
I have seen similar errors in `ethers.js` if I enter invalid address. Though it's a different lib, just trying to help if this solves the problem.

**Comment by hbarcelos** [comment]
@GregTheGreek there's no snippet really, it's just:

```javascript
const web3 = new Web3(window.ethereum);
```

Then if I interact with any contract, I see the error.
However, none of my contracts come nowhere near ENS.

**Comment by GregTheGreek** [comment]
> @GregTheGreek there's no snippet really, it's just:
> 
> ```js
> const web3 = new Web3(window.ethereum);
> ```
> 
> Then if I interact with any contract, I see the error.
> However, none of my contracts come nowhere near ENS.

ah ok, let me dive into this

**Comment by GregTheGreek** [comment]
Im unable to reporduce this on v1.2.3, can you confirm?

**Comment by hbarcelos** [comment]
I only see this issue on version `>=1.2.7`.

I'm currently locked in `1.2.6` because of an unrelated problem and there's no issue.

**Comment by GregTheGreek** [comment]
Sorry I'm not sure why i typed `3`... I meant to say `v1.2.11`

**Comment by grimmie38** [comment]
Did you find the solution? @hbarcelos
