### ISSUE TITLE
Fix UTF-8 encoding issues

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#363]
The functions `fromASCII` and `toASCII` should be removed.

There should be a clear distinction between binary data and utf-8-encoded text.
The types `bytesXX`, `bytes` should not be assumed to be utf8-encoded and they should not be cut off at the first zero byte.

A function to en- and decode utf8 should be provided (i.e. converting between hex string and javascript native string encoding) which should report errors and optionally cut at the first zero byte during en- or decoding, although in general, zero-terminated strings should be deprecated as they are needed neither in JavaScript nor in the EVM ABI.

**Comment by ethers** [comment]
please include these fixes https://github.com/ethereum/web3.js/issues?q=bytes+is%3Aopen

**Comment by ethers** [comment]
what are the proposed names for the new functions?
`fromBytes`, `toBytes`, `encodeUTF8`, `decodeUTF8` ?

**Comment by frozeman** [comment]
@ethers we are discussing this in #372 
Please post your ideas there too, these sound good.
