### ISSUE TITLE
Authentication issues using web3.js

### ISSUE THREAD

**Issue by JF0001** [ethereum/web3.js#3636]
#### Expected behavior
Trying to recover address on server side, using the signature produced by web3.eth.personal.sign on the client side.

#### Actual behavior
No issue signing a message on the client side, which is sent to the server via a post request (i.e. axios.post('/api/auth', signature))

However, I have tried to follow the web3.js documentation and numerous examples found online, using for example the following code, but always obtaining errors.

const Web3 = require('web3')
const web3 = new Web3('ws://localhost:MyServerPortNumber')
web3.eth.setProvider(web3)
web3.eth.personal.ecRecover(msg, signature, (err, recaddress) => {...

**Comment by cgewecke** [comment]
@JF0001 

We have some simple sign/recover examples [in the unit tests here][1] you might find helpful. (They use geth to execute the `personal.sign`.) 

Could you provide more detailed information about how you're generating the signature? 

[1]: https://github.com/ethereum/web3.js/blob/fbb29202288276e12e3449328f4ba5c18e16fd1f/test/e2e.method.signing.js#L368-L392

**Comment by JF0001** [comment]
Thank you cgewecke. I have finally managed to make it work using the following on the client side: this.web3.eth.personal.sign((msg), this.account, (err, signature) => {
And using web3.eth.accounts.recover(msg, signature) on the server side.

It should be okay to combined "eth.personal" methods with "eth.accounts" ones, right?

Thank you again. J

**Comment by JF0001** [comment]
Also, if I use the following (4000 being the port on which my server is running)
var Web3 = require('web3');
var web3 = new Web3('ws://localhost:4000');
I obtain the following error:
TypeError: this.provider[(intermediate value)(intermediate value)(intermediate value)] is not a function
Thank you again. J

**Comment by Cjw-259** [comment]
Java How to recover this Signature
