### ISSUE TITLE
Fix FALSE return values

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#364]
This are things like returning `false`, for  data type boolean, when `0x000000...` is returned (E.g. execution was stopped), so that not false `false` is received by dapp developers.

**Comment by chriseth** [comment]
Do I understand this issue correctly that web3.js should decode `bool` ABI types to javascript's `true` and `false` and it currently does not do that?

**Comment by frozeman** [comment]
It does it, but if there is an EVM exception it returns '0x' or something, which shouldn't then be interpret as `false`

**Comment by frozeman** [comment]
ideally if there is an EVM exception we get an RPC error back from the node, not simply `0x`

**Comment by frozeman** [comment]
Same as #272
