### ISSUE TITLE
Error: invalid number value (arg="", coderType="uint256"

### ISSUE THREAD

**Issue by ARR552** [ethereum/web3.js#3644]
Hello,
I have created this smart contract to reproduce the error.

> pragma solidity >=0.4.22 <0.7.0;
> 
> contract Test{
>     uint[1] public val;
>     constructor (uint _val) public {
>         val[0]=_val;
>     }
>     function get() public view returns(uint[1] memory) { 
>         return val;
>     }
>     function set(uint[1] memory _val) public {
>         val=_val;
>     }
> }
> 

#### Behavior
When the contract is deployed is created the value val[0] is set and we can set val[0] to 57896044618658097711785492504343953926634992332820282019728792003956564819968. 
We are able to recover the array successfully using the function get().
The problem is in set() function. If you try to set an uint256[] where the number is not very long it works perfect. However if you try to set a long value, i get the next error all the time.
`transact to Test.set errored: Error encoding arguments: Error: invalid number value (arg="", coderType="uint256", value=5.78960446186581e+76, version=4.0.47) `
I tried with different values. The max number supported by uint256 is 2^255 = 57896044618658097711785492504343953926634992332820282019728792003956564819968
The problem is when i try to sent an array like this:
`[57896044618658097711785492504343953926634992332820282019728792003956564819968]  =>DOESN' T WORK`
`[57896048] => WORKS!!!`

#### Environment
"web3": "1.2.1"
Node v12.18.2

Thank you

**Comment by ryanio** [comment]
hey @ARR552, if you give a read about big numbers in javascript you'll learn that you need to pass the big number in as a string (or bn.js or bignumber.js object) so that it doesn't get malformed.

i also recommend trying it out on the latest version of web3.js 1.x as the abicoder was upgraded in 1.2.8

**Comment by ARR552** [comment]
Hey @ryanio 
I get the same error using BigInt() function to treat the big number. Which other function should I use to avoid the problem??
The difference in message error is :
`transact to Test.set errored: Error encoding arguments: Error: invalid number value (arg="", coderType="uint256", value=57896044618658097711785492504343953926634992332820282019728792003956564819968, version=4.0.47) `

**Comment by ryanio** [comment]
@ARR552 bigints are not well supported across the ecosystem yet.
try passing it in as a string e.g. `'57896044618658097711785492504343953926634992332820282019728792003956564819968'`

**Comment by ARR552** [comment]
You are right. Passing the value as string works.

> ["57896044618658097711785492504343953926634992332820282019728792003956564819968"] =>WORKS
> [57896048] => WORKS!!!

Thank you @ryanio

**Comment by ryanio** [comment]
great to hear! ok i will close this issue then.

**Comment by jjhesk** [comment]
I dont know if this is related but I have the similar issue https://github.com/MikeMcl/bignumber.js/issues/305

**Comment by ankitpro** [comment]
the value that you are trying to write got to be something like "10000000000000000" for 0.1eth
