### ISSUE TITLE
Should not check provider supports subscriptions depend `on` method.

### ISSUE THREAD

**Issue by sapjax** [ethereum/web3.js#3669]
The code blew check if a wallet provider support subscriptions via the `on` method of provider.

https://github.com/ethereum/web3.js/blob/a5a739b7d1/packages/web3-core-subscriptions/src/subscription.js#L213

Some provider dones't support subscriptions, but they must has the `on` method. 
According to the [EIP1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#events) The provider must 
implement `on` method but can without the implemention of subscriptions.
I think it's better to use the old `supportsSubscriptions` method to detect, and merge it into `EIP1193`.

**Comment by GregTheGreek** [comment]
Based on eip1193, I believe the current workflow is correct. At the dapp level, you should be handling these errors. If a provider doesn't support eip1193, subscribing should throw

**Comment by sapjax** [comment]
The problem is `on` is not equal to `support subscriptions`.
A wallet provider may not support subscriptions, and still exist an `on` method.
So web3.js consider it support subscriptions, then do not fallback to the polling handler.

**Comment by GregTheGreek** [comment]
@frankiebee thoughts on this?

**Comment by ryanio** [comment]
@sapjax if the provider does not support subscriptions, it will fall back to interval polling [here](https://github.com/ethereum/web3.js/blob/a5a739b7d1834b53b7268c57f791db5d07b720da/packages/web3-core-method/src/index.js#L559-L560).

you are right that it is not an ideal way to detect if a provider supports subscriptions, but it's the best we have for now until the community decides on some kind of capabilities interface for providers.

**Comment by sapjax** [comment]
@GrandVizierOlaf @ryanio 

I hope the detect condition could be like:
```js
if (!this.requestManager.provider.on || this.requestManager.provider._unspupportSubscriptions) {
   // do interval polling
} else {
  // listen event subscriptions
}
```

So, for the providers who has `on` method but don't support subscriptions,  they can add `_unspupportSubscriptions` property to make web3 know they don't support it,  and make the polling works normally.

**Comment by sapjax** [comment]
@ryanio 
OK, I understood, if `eth_subscribe` failed, it will fallback to polling,  I didn't seen the fallback code before (look like it updated recently).
So, I think it's OK, just ignore this issue.
