### ISSUE TITLE
CONNECTION ERROR: Couldn't connect to node on WS.

### ISSUE THREAD

**Issue by JamesANZ** [ethereum/web3.js#3675]
Hi All,

I am trying to connect to a node via websocket, it works when I use an HTTP provider but not with websocket.

I have already tried with a connection callback on the provider to see if it is connected and it returns true but the moment I send a transaction I get the error in the header. 

This same node connection works fine in geth. 

Node version: v10.21.0
web3.js version: 1.2.9

Thank you for your help

**Comment by GregTheGreek** [comment]
Perhaps the endpoint you're using does not support websockets?

does it have the `ws:` prefix? What is the node type you're connecting to?

I noticed youre using an older version of web3 could you try and update it?

**Comment by JamesANZ** [comment]
Hi @GregTheGreek it was a problem from the websocket provider side, they have just fixed it and the same code works. Thanks!
