### ISSUE TITLE
Implement EIP-2876

### ISSUE THREAD

**Issue by junderw** [ethereum/web3.js#3688]
I will handle the implementation.

I am making this issue to discuss / ask about the methodology / get a loose green-light on the EIP before diving in on implementation.

## The EIP

https://eips.ethereum.org/EIPS/eip-2876

## My Plan

1. Add tools to utils such as `toDepositAddress(baseAddress, nonce) => string` and `verifyDepositAddress(depositAddress)`
2. Allow `web3.eth.sendTransaction` to accept a deposit address in the `to` field, but it will throw if the data field is not blank, and if blank it will properly insert the necessary data and replace the to field with the proper 20 byte address internally.
  i. *I will also need to make a PR for ethereumjs-tx to do something similar*

Any thoughts about my plan for implementation here should go in this thread.

Any thoughts about the EIP itself should go to the Discussions-To thread on the EIP.

Thanks for your time and I look forward to making things easier for exchanges and merchants (and lowering overall gas usage from value transaction based systems with naive forwarding)

**Comment by GregTheGreek** [comment]
Ive just browsers this briefly. Is there a reason this couldn't be implemented as a simple library alongside web3.js? We are trying to keep things slimer by including provider specific eips.

Happy to hear out your thoughts on inclusion of this eip though as it pertains this library being specific to provider functions ?

**Comment by junderw** [comment]
Thanks for the reply.

Can you clarify for me what you mean by "provider specific"?

I can certainly go the route of:

1. Make my own library.
2. Write a few examples of using my library alongside web3
3. Try to get exchanges to implement it.

But the success rate of getting exchanges to implement if it is coming from some random guy who, upon further inspection, works for a competitor (even if we only serve Japan right now) will be low.

It would be much higher if I can get a larger consensus from the ETH library developer community at large.

> "ok, this is a problem for exchanges that is exacerbated by high gas prices, and having this set as a new standard way of managing sending ETH to exchanges/merchants will be better for the network as a whole"

It could even eventually set a new standard for the next iteration of ERC-20-esque tokens. Maybe they'll all offer `transfer` methods that also takes the `bytes8 id` in the future and exchanges can manage those tokens in a similar manner.

But if it's "just some random EIP that one guy in Japan came up with that no one uses" then nothing really changes.

Just like most standards, it's a chicken and egg problem, and the egg I am aiming for from the beginning is wider consensus among the major libraries. I'm envisioning a world where I can take almost any client or library where I would normally input an address and wei amount, just replace the address with the 28 byte deposit address and magically the data field will be set to include the bytes8 id, and everything will just work. There would be almost no reason for services to not support (at least) sending to these types of contracts.

---

Anywho, if you could give me a bit more insight into what you mean by provider specific, I would greatly appreciate it.

Thanks.

**Comment by GregTheGreek** [comment]
> Can you clarify for me what you mean by "provider specific"?

Sorry that was vague. A provider aims to give access to a full node (i.e what web3.js does) for example the following [eip](https://eips.ethereum.org/EIPS/eip-1193) is a provider specific EIP.

Regarding your EIP:
I actually think this offers a lot of useful things for the wider community for sure. Although I'm not sure that web3.js is quite the place for it, for example you won't even find `erc20` specific code within the library. It becomes very difficult to draw the line down the road of what should be accepted and what shouldn't be.

We've been talking about adding feature branches, or even a `.add` function that would allow anyone to effectively _plug in_ their own module, i.e a module for this eip

**Comment by yihuang** [comment]
from my understanding:
- wallet needs to recognise the eip-2876 deposit address and transform into data field.
- exchange:
  - create a deposit contract and show the encoded deposit address to user (probably also show address + data pair to user in case their wallet don't support this yet)
  - monitor the event logs to discover deposit

The more important part for adoption is the wallet part,  if mainstream wallets don't support this yet, user would need to copy both an address and a data field which is demanding for non-technical user.

**Comment by junderw** [comment]
I'm putting this on the back burner for a while.
Seems like not much interest.
