### ISSUE TITLE
clearSubscriptions return undefined

### ISSUE THREAD

**Issue by johhonn** [ethereum/web3.js#3689]
#### Expected behavior
web3.eth.clearSubscriptions returns a boolean
#### Actual behavior
web3.eth.clearSubscriptions returns undefined
#### Steps to reproduce the behavior
install web3
instantiate with infura websockets
let web3=new Web3(new Web3.providers.WebsocketProvider(process.env.INFURA));
create a  subscription with logs
web3.eth.subscribe('logs', {} ,function(){ ... });

then call web3.eth.clearSubscriptions()
#### Logs
No error just an undefined result. I also do not seem to be able to start web.eth.subscribe again.

#### Environment

web3 1.2.11 ,node js version 12.18.3, wsl2 ubuntu 20.04

**Comment by GregTheGreek** [comment]
~It is the correct behavior for it to return void (or undefined).~

~Although I could see it to be beneficial if it did return a boolean.~

Thank you for reporting!

**Comment by cokia** [comment]
"web3.eth.clearsubscriptions()" is shown in the document return type 'Boolean'. It has no mention of return value  `undefined` in the document, and I don't know if this is a problem with your comments or  documentation. Under what circumstances is it normal for undefined to appear?

**Comment by GregTheGreek** [comment]
I misread the documentation, the code is in fact incorrect. The `clearSubscriptions` has no return value.
