### ISSUE TITLE
Drop/update swarm-js dependency?

### ISSUE THREAD

**Issue by wbt** [ethereum/web3.js#3691]
Web3 depends on web3-bzz which [depends on](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-bzz/package.json) [swarm-js](https://github.com/maiavictor/swarm-js), which depends on [eth-lib](https://github.com/MaiaVictor/eth-lib/) which depends on [servify](https://github.com/MaiaVictor/servify).  The latter three are by the same author, who clearly writes in the readmes for the first two that they are not being maintained.  The latter has a versioning [issue](https://github.com/MaiaVictor/servify/issues/4) fixed over three years ago but which throws a warning when installing web3.  We might consider forking or finding an alternative.

(npm 6.14.5; node 9.3.0; Windows 10)

**Comment by GregTheGreek** [comment]
This makes a pretty good argument for dropping bzz. Would love to see input from the swarm team... @ryanio do you know anyone there? 

If we can't get a hold of them it might be worth doing a "last call" for a month or so before fully deprecating it.

cc: @frankiebee @spacesailor24

**Comment by ryanio** [comment]
sorry I don't know anyone currently working on swarm but I will drop a message in their channel with a link to this issue.

**Comment by acud** [comment]
hi there, swarm team member here.
swarm-js builds on top of the classic `ethersphere/swarm` client which is no longer actively being maintained as we have been rewriting the whole project for the last nine months or so. The new client is being maintained at [ethersphere/bee](https://github.com/ethersphere/bee) and there's an ongoing effort to build a javascript proxy around that in nodejs (still unannounced). 
How can we further discuss this? we are reachable on [mattermost](https://beehive.ethswarm.org/).
Thanks!

**Comment by GregTheGreek** [comment]
Do you mind reaching out to our discord?

**Comment by acud** [comment]
@GregTheGreek which discord would that be? I am not on the ethereum discord. The web3.js repo does not mention any discord channel, only gitter.

**Comment by GregTheGreek** [comment]
https://discord.gg/NxzBFm

**Comment by acud** [comment]
i'm getting an error `invalid invite`

**Comment by GregTheGreek** [comment]
Try this one https://discord.gg/cRc2Jh8

**Comment by GregTheGreek** [comment]
Update:

After discussions with the Swarm team we are removing bzz support #3746
