### ISSUE TITLE
web3.eth.ens.setContenthash() with Infura http provider error

### ISSUE THREAD

**Issue by jacko125** [ethereum/web3.js#3698]
#### Expected behavior

Using web3.eth.ens library should allow interacting with the ENS Resolver contract with a signed transaction. 

```
const web3 = new Web3(new Web3.providers.HttpProvider(https://mainnet.infura.io/v3/INFURA_PROJECT_ID));
web3.eth.accounts.wallet.add("privateKey");
const account = web3.eth.accounts.wallet[0].address;

await web3.eth.ens.setContenthash(ensName, content, {
			from: account,
			gas: 200,000,
			gasPrice: w3utils.toWei(gasPrice.toString(), 'gwei'),
		});
```

#### Actual behavior

`Error: Returned error: The method eth_sendTransaction does not exist/is not available`

Infura doesn't support unsigned transactions (it requires the transaction to be signed and sent as eth_sendRawTransaction). 

#### Steps to reproduce the behavior

1. [First step]

```
const web3 = new Web3(new Web3.providers.HttpProvider(https://mainnet.infura.io/v3/INFURA_PROJECT_ID));
web3.eth.accounts.wallet.add("privateKey");
const account = web3.eth.accounts.wallet[0].address;

await web3.eth.ens.setContenthash(ensName, content, {
			from: account,
			gas: 200,000,
			gasPrice: w3utils.toWei(gasPrice.toString(), 'gwei'),
		});
```

2. [Second step]
3. [and so on...]

#### Environment

"web3": "^1.2.11",
node v12.18.3

**Comment by jjgonecrypto** [comment]
@cgewecke any ideas on this one? 🙏

**Comment by GregTheGreek** [comment]
Hmm, I actually stumbled upon a json-rpc interface mismatchwith Infura the other day. 

Let me dive into this (sorry took the weekend off). I think we may need some edge cases surrounding infura specific endpoints

**Comment by GregTheGreek** [comment]
Or we may need to switch `eth_sendTransaction` to `eth_sendRawTransaction`

**Comment by jacko125** [comment]
> Or we may need to switch `eth_sendTransaction` to `eth_sendRawTransaction`

Thanks Greg for looking into this, the issue with Infura Provider is that it would require a signed raw transaction. I believe if web3js is interacting with Metamask for example then using `eth_sendTransaction` would work as the tx is signed there.

**Comment by GregTheGreek** [comment]
I haven't had time today to get to this, but tomorrow I'll be poking around.

One thing that confuses me, is I run a local script against multiple providers (including infura), which works everytime. It seems this only happens with ens, which inherits the `eth` object with the correct provider(?)

Either way, I'll hopefully get to this tomorrow and have a solution. I'd like to cut a release wednesday, we have A LOT of stuff in this next rc

**Comment by jjgonecrypto** [comment]
Please keep this open Mr Robot :pray:

**Comment by jacko125** [comment]
> I haven't had time today to get to this, but tomorrow I'll be poking around.
> 
> One thing that confuses me, is I run a local script against multiple providers (including infura), which works everytime. It seems this only happens with ens, which inherits the `eth` object with the correct provider(?)
> 
> Either way, I'll hopefully get to this tomorrow and have a solution. I'd like to cut a release wednesday, we have A LOT of stuff in this next rc

Hi Greg, 

Any update on this issue? 

Thanks

**Comment by GregTheGreek** [comment]
Reassigning to @spacesailor24  :)

**Comment by jacko125** [comment]
Bump!

**Comment by jjgonecrypto** [comment]
damn, not stale but closed. @jacko125 we'll just use ethers.

**Comment by Papillon6814** [comment]
same issue
