### ISSUE TITLE
Metamask-deprecated .on({data, close}) used in constructor

### ISSUE THREAD

**Issue by wbt** [ethereum/web3.js#3699]
Substantive details are described [here](https://github.com/MetaMask/metamask-extension/issues/9301), but this Issue is filed in web3 for updates which may need to be made in web3 for no longer relying on deprecated `data` and `close` events if they are, in fact, actually deprecated.

**Comment by rekmarks** [comment]
Just to provide our perspective, from the point of view of MetaMask and current provider standards, `data` and `close` are deprecated.

**Comment by wbt** [comment]
I don't think this should be marked as stale.

**Comment by Polycarpik** [comment]
@koraykoska

**Comment by koraykoska** [comment]
Are we gonna try to be backward compatible with old providers with the close event? If not we'll need to mark this as a breaking change and als change the according unit tests and mock providers.

**Comment by koraykoska** [comment]
@wbt Could you please provide a complete example of a small webpage which results in those warnings with the newest 1.3.0 web3.min.js?

**Comment by wbt** [comment]
@koraykoska Unfortunately I won't be able to do that in the next week or so.
