### ISSUE TITLE
Web3 for Deno RTE --> web3.ts

### ISSUE THREAD

**Issue by michael-spengler** [ethereum/web3.js#3700]
I'd like to use web3 in a https://deno.land/ project. Are there any good recommendations out there yet? :)

The concrete question is:
**How can I connect to the Ethereum Network from an https://deno.land/ project?**

**Comment by michael-spengler** [comment]
I drafted the following third party module for deno: https://deno.land/x/ethereum 

If there are experienced developers here who would like to take this forward, let me know.

**Comment by michael-spengler** [comment]
as an alternative option to keep a similar separation of concerns: https://deno.land/x/web3 plus the corresponding repo [web3.ts](https://github.com/michael-spengler/web3.ts)

**Comment by michael-spengler** [comment]
I drafted https://deno.land/x/web3 plus the corresponding repo web3.ts - If you like it we can of course move the repo into the ethereum org.

**Comment by GregTheGreek** [comment]
@michael-spengler cool!

Just a little FYI, we've converted all our configs and compilers etc... to TypeScript :confetti_ball: we're slowly navigating our way through a full migration so we don't can have native deceleration files instead of the current broken ones.

**Comment by GregTheGreek** [comment]
To answer your question:

I haven't used Deno much more then when I saw the demo a few years back at websummit(?). We currently don't have the bandwidth to explore this, but if it's something you want we can provide some assistance.

**Comment by michael-spengler** [comment]
Hi Greg The Greek :) Thank you for your response. 

I'll explore some options potentially leveraging
https://medium.com/samsung-internet-dev/using-node-modules-in-deno-2885600ed7a9 resp. https://jspm.org/ and
https://stackoverflow.com/questions/61821038/how-to-use-npm-module-in-deno

If some funding via https://gitcoin.co/ would be beneficial from your perspective let me know. In this case feel free to put some fair price tag proposals on the issue or onto specific elements of it.

**Comment by michael-spengler** [comment]
Some more info which might be helpful along this journey: michael-spengler/wwi18seac#8 (comment)

Plus the link to the Deno community in Discord: https://discord.gg/deno Feel free to join.

**Comment by GregTheGreek** [comment]
@michael-spengler since deno isn't on our roadmap I'm not sure if we'll be able to provide and gitcoin grants at this time.

**Comment by michael-spengler** [comment]
@GregTheGreek O.K. We'll see what we can do on our side for the Deno Web3 enablement. We can leave the issue open if you like as I can give some updates on the corresponding progress during the upcoming weeks.

**Comment by Soremwar** [comment]
Hi there

Im currently working in a port of Web3 1.1.12 (some really good progress made already) to support Deno natively.

Maybe your TypeScript implementation (I assume web3 2.0 or higher) will be easier to use natively in Deno through tools like Skypack or Denoify.

You can track current progress here: (Credits were due)
https://github.com/deno-npm/deno_npm
And here
https://deno.land/x?query=npm+web3

**Comment by GregTheGreek** [comment]
we aren't actively maintiang 2.0 anymore.

We have a 1.4.0 branch (probably >1 month away) thats fully written in es6 to make everyone's life a bit easier  :) After that will be typescript!

**Comment by chovyprognos** [comment]
no progress on this? i'dalso like to use web3 inside deno

**Comment by v1rtl** [comment]
@chovyprognos try with esm.sh, i think it should import it fine

**Comment by chovyprognos** [comment]
@talentlessguy `error: Uncaught TypeError: Cannot read properties of undefined (reading 'Rand')`

https://stackoverflow.com/questions/69567044/how-do-i-import-web3-from-esm-sh-into-a-deno-deps-ts-file

**Comment by michael-spengler** [comment]
@Soremwar & @GregTheGreek: 
We have in the meantime worked with an ethereum-node-gateway-microservice which is of course not too cool. So we would reconsider this issue. 

Have you heard of any successful usage of web3 in deno - resp. which tricks are needed to make it work?

trying it via 
```ts
import web3 from 'https://cdn.skypack.dev/web3 

``` 
currently leads to 
.
.
.

![Screenshot 2021-10-24 at 14 12 21](https://user-images.githubusercontent.com/43786652/138593560-0c8d4c36-0b12-4159-938c-845b3adf1d02.png)

**Comment by Soremwar** [comment]
@michael-spengler Not really, thought the Node compatibility layer is seeing some rapid development from the mantainers who are currently very interested in attracting lib developers into the Deno ecosystem

I do see a quick way to solve this though, if the Web3 mantainers were to provide an ESM build of Web3JS for the browser it would likely just work on Deno, since most of the crypto APIs are available now

**Comment by michael-spengler** [comment]
@Soremwar Thank you.
We'll explore https://github.com/nolanlawson/cjs-to-es6 ...

**Comment by v1rtl** [comment]
there's also lebab

https://github.com/lebab/lebab

**Comment by michael-spengler** [comment]
@talentlessguy @Soremwar @GregTheGreek @chovyprognos @ntrotner: 

Good News: 
Especially thanks to the hint from @talentlessguy we managed to come up with a pretty good solution in our opinion:
https://deno.land/x/web3

Enjoy the features and feel free to raise issues. We want to continue to support web3.

**Comment by v1rtl** [comment]
https://esm.sh/web3 works as well btw, in v55 it got fixed

**Comment by michael-spengler** [comment]
@talentlessguy: Thank you. Two aspects we currently consider:
1. TypeSafety
2. Independence from esm.sh, skypack.dev et al.

It seems interesting how those things will evolve in the future. Will there be Deno Modules which just serve as a wrapper or will people just get used to writing things like `import ... from "...esm.sh/..."`? Feedback is always welcome.
