### ISSUE TITLE
web3-eth-abi is not compatible with ethers.js bignumber v5.0

### ISSUE THREAD

**Issue by toninorair** [ethereum/web3.js#3702]
#### Actual behavior
bignumber `toString` fails with an error `bigNumber.toString does not accept parameters` for the latest ethers.

These 2 lines are incompatible between `web3-eth-abi` and `ethers/bignumber`:

https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-abi/src/index.js#L258

https://github.com/ethers-io/ethers.js/blob/master/packages/bignumber/src.ts/bignumber.ts#L191
 

#### Environment

ethers - 5.0.8
web3 - 1.2.11

**Comment by GregTheGreek** [comment]
Do you mind providing us with a little code snippet :)?
