### ISSUE TITLE
web3.eth.abi.decodeLog returns incorrect first indexed event parameter

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#3705]
#### Expected behavior

Originally mentioned by @wbt in #3692, `web3.eth.abi.decodeLog` incorrectly returns the event identifier in place of the first indexed event parameter. In the replication steps provided by @wbt [here](https://github.com/ethereum/web3.js/pull/3692#issuecomment-675485588), the first indexed parameter should be `16`

#### Actual behavior

The first indexed parameter is returned as: `-395379449702`

#### Steps to reproduce the behavior

Replication steps found [here](https://github.com/ethereum/web3.js/pull/3692#issuecomment-675485588)

#### Environment

NPM - 6.14.4
Node - v12.16.2
Web3.js - ^1.2.11
OS - Ubuntu 19.10

**Comment by wbt** [comment]
How's it going @spacesailor24?
