### ISSUE TITLE
UnhandledPromiseRejectionWarning when sending a transaction and the error event handler throws

### ISSUE THREAD

**Issue by gabmontes** [ethereum/web3.js#3708]
#### Expected behavior

Send a transaction that will fail i.e. because the gas amount is not specified, and use the events interface of the promi-event. If the `error` event handler throws, that error should be handled exclusively in "userland". If the promises interface is used as well, the no-gas-specified error should be seen.

#### Actual behavior

An unhandled promise rejection is thrown within web3. On top of that, the error coming into the `.catch()` is not the original gas error but the error within the buggy `error` event handler. This is misleading because the issue is not within the library but in the user code and the error obtained shadows the actual send transaction error.

#### Spoiler alert

The following line must be  wrapped in a try-catch block to prevent the error to bubble up and wreak havoc: 

https://github.com/ethereum/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/packages/web3-core-method/src/index.js#L732

#### Steps to reproduce the behavior

```js
const Web3 = require('web3')
const web3 = new Web3()

web3.eth.accounts.wallet.create(0).add(process.env.PRIVATE_KEY)
const from = web3.eth.accounts.wallet[0].address

const emitter = web3.eth.sendTransaction({ from, to: from, value: '1' }) // no gas was specified!
emitter.on('error', function () { throw new Error('UNHANDLED') })
emitter.catch(console.error)
```

#### Logs

```consola
$ node bug.js                                                                          
(node:21330) UnhandledPromiseRejectionWarning: Error: UNHANDLED
    at Promise.<anonymous> (./bug.js:8:41)
    at Promise.emit (./packages/web3-core-promievent/node_modules/eventemitter3/index.js:181:35)
    at ./packages/web3-core-method/src/index.js:720:60
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Environment

web3@1.2.11

**Comment by GregTheGreek** [comment]
Thanks for reporting this and opening a pr! I'll take a look at this later today 😊
