### ISSUE TITLE
What's the hell is this library does? What can I do with this?

### ISSUE THREAD

**Issue by Ppang0405** [ethereum/web3.js#3712]

**Comment by michaelsbradleyjr** [comment]
Please see the documentation: https://web3js.readthedocs.io/en/v1.3.0-rc.0/

Also, a tutorial might be helpful: https://www.dappuniversity.com/articles/web3-js-intro

I haven’t worked through that one, but on first glance it seems decent enough.

**Comment by Ppang0405** [comment]
Thanks, I check that now.
