### ISSUE TITLE
Getting transactionDetails before transaction is actually mined

### ISSUE THREAD

**Issue by araa47** [ethereum/web3.js#3714]
Hi, is there a way to workout the transaction input details such as to, and from fields before the transaction is actually mined? 

I have found the following method 

```
const trx = await web3.eth.getTransaction(transaction);
```

however this only works when the transaction has already been mined.

**Comment by GregTheGreek** [comment]
To better help you i need to understand how you're obtaining a transaction hash for `getTransaction`?

**Comment by cokia** [comment]
I don't know if I understood you well.

If what you want is to "get the tx data with only the tx ID that occurred before it was mined," I just think it's the right way to get the to/from/data area from the trend that you've generated.

`const tx = web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '1000000000000000'
})

const from = tx.from
const to = tx.to
`

**Comment by araa47** [comment]
Hi sorry for the unclear information. I was actually referring to getting the transaction details of a transaction that hasn't been sent by me and not mined yet. I got the transaction ID of this by listening to pending transactions. 

Is it possible to get more details of these pending transactions without waiting for them to get mined?
