### ISSUE TITLE
Rename some utils functions

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#372]
functions like `toAscii` and `toDecimal` should rather be renamed to `toString` and `toNumber` or similar.

**Comment by androlo** [comment]
htoa, atoi, etc.? Friend suggested for a similar thing, thought it was clever.

**Comment by chriseth** [comment]
`toAscii` -> `fromUTF8`?
`toDecimal` -> `toNumber`, but it should raise an error if the number cannot be represented without loss in a javascript number.

**Comment by frozeman** [comment]
i would prefer `toString` and `toNumber`, as its a common js function and people know what it does (and in our case, it does the same)

we would also then need `fromNumber` and `fromString`, i had in the past a smart auto convert function called `toHex`, but i'm not sure if this will work nicely in all cases, but this would definitely be best understood.

**Comment by frozeman** [comment]
web3 is all about the ease of use for developers, so a good guessable API is key!

**Comment by chriseth** [comment]
Sure, good names are paramount, but they should not suggest wrong semantics. I'm fine with `toString` and `toNumber`.

`fromNumber` and `fromString` do not explain what their output is. Is it hex or binary? Furthermore, is the number padded to 32 bytes or not?

**Comment by frozeman** [comment]
i also don't like the `from*` semantic, thats why i introduced the `toHex` a while ago. we just have to make sure that it won't make mistakes. 

Which is for cases where you want to encode a string like `"211234"`, toHex would detect this as a number. (Otherwise we couldn't allow huge number strings to be detected and converted)

**Comment by kumavis** [comment]
if these are renamed please publish with a major version number change :+1:

**Comment by frozeman** [comment]
We will don't worry ;)

Liebe Grüße,
Fabian

[frozeman.de]
