### ISSUE TITLE
eth.isSyncing return type issue

### ISSUE THREAD

**Issue by qwhex** [ethereum/web3.js#3720]
#### Actual behavior

The type definition of `isSyncing` is:
```typescript
isSyncing(
    callback?: (error: Error, syncing: Syncing) => void
): Promise<Syncing | boolean>;
```

The return type should be `Promise<Syncing | false>` based on the docs below.

#### Expected behavior

According to the [documentation](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#eth-issyncing-return), the return value of `isSyncing` is a promise of "a sync object when the node is currently syncing or **false**". I found some old comments that `isSyncing` is `true` when "syncing just started", but it's undocumented and possibly not true anymore.

#### Steps to reproduce the behavior

The problem is that with the boolean return type, the user of this function should handle the `true` case, which never happens.

```typescript
const syncing = await web3.eth.isSyncing()

if (syncing === true) {
  throw Error('Unexpected')
}
```

**Comment by GregTheGreek** [comment]
@qwhex Im not really sure what a possible solution here is. If you can find any docs that point to it possibly returning true, please let me know. Otherwise the current code, and documentation is correct.

**Comment by GregTheGreek** [comment]
> The return type should be Promise<Syncing | false> based on the docs below.

also `false` is not a valid type
