### ISSUE TITLE
web3.eth.sendSignedTransaction throws "Invalid sender"

### ISSUE THREAD

**Issue by Valo-app** [ethereum/web3.js#3722]
Hey,  whenever i tried to broadcast my signed transaction on rinkeby test i get this `invalid sender` error. I took the signed and rawtx and tried to manual broadcast it from etherscan and it was sucessfully. The same txn is not giving error using `web3.eth.sendSignedTransaction` plus `web3.eth.getTransactionCount `also return 0 even if change my node provider.
please help.

`web3Http.eth.getTransactionCount(myAddress,"pending").then(function(blockcount){   `
    
`result = web3Http.utils.toWei(amt.toString(), 'ether');`
   
   
          count = blockcount;
    
         
          var rawTransaction = {
           "from":myAddress,
           "gasPrice":web3Http.utils.toHex(20* 1e9),
           "gasLimit":web3Http.utils.toHex(210000),
           "to":contractAddress,"value":"0x0",
           "data":contract.methods.approve(to,web3Http.utils.toHex(result)).encodeABI(),
           "nonce":web3Http.utils.toHex(count)
          }
         
          var transaction = new Tx(rawTransaction,{'chain':'rinkeby',hardfork: 'petersburg'});
          
          transaction.sign(Buffer.from(process.env.Key, 'hex'));
      
          web3Http.eth.sendSignedTransaction('0x'+transaction.serialize().toString('hex'))
          .on('receipt', ((data)=>{
            resolve(data);
           
          }))

**Comment by GregTheGreek** [comment]
Where is the wallet being used in this example?

**Comment by Valo-app** [comment]
It is an express app for transferring the erc20 from one account to other. It was working fine one month before recently it started failing. In this specific test example it a transferring from Admin wallet to a demo user wallet on rinkeby.

**Comment by GregTheGreek** [comment]
what version of web3.js are you using?

**Comment by Valo-app** [comment]
"web3": "^1.3.0",
"ethereumjs-tx": "^2.1.2"

**Comment by Valo-app** [comment]
I removed the "ethereumjs-tx": "^2.1.2" and it solved my problem thanks
