### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by chaitanyapotti** [ethereum/web3.js#3725]
#### Expected behavior
web3-eth exports itself as a [default export](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/src/index.js#L660) whereas the corresponding [types file ](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/types/index.d.ts#L63) exports it as just another export
This causes typescript to error while importing

#### Actual behavior
Should export Eth as the default export in types file

#### Environment
- web3 version: 1.3.0
- node.js version: 12.18.3

**Comment by AuHau** [comment]
Yeah this is known issue that was already reported many times but nothing was done about it for long time 🙄 For example #3198
