### ISSUE TITLE
`callbackify` from 'util' doesn't seem to be available in the browser

### ISSUE THREAD

**Issue by interfect** [ethereum/web3.js#3727]
When using Browserify 16.5.2, here's what I get from `require('util')`, as logged by `console.log`:
 ```
_extend: function _extend(origin, add)​
debuglog: function debuglog(set)​
deprecate: function deprecate(fn, msg)​
format: function format(f)​
inherits: function inherits(ctor, superCtor)​
inspect: function inspect(obj, opts)​
isArray: function isArray(ar)​
isBoolean: function isBoolean(arg)​
isBuffer: function isBuffer(arg)​
isDate: function isDate(d)​
isError: function isError(e)​
isFunction: function isFunction(arg)​
isNull: function isNull(arg)​
isNullOrUndefined: function isNullOrUndefined(arg)​
isNumber: function isNumber(arg)​
isObject: function isObject(arg)​
isPrimitive: function isPrimitive(arg)​
isRegExp: function isRegExp(re)​
isString: function isString(arg)​
isSymbol: function isSymbol(arg)​
isUndefined: function isUndefined(arg)​
log: function log()​
<prototype>: Object { … }
```

`callbackify` is not available. Yet, `web3` attempts to use it here:

https://github.com/ethereum/web3.js/blob/866cb9917474e6618851960000db26e118589cd6/packages/web3-core-requestmanager/src/index.js#L23

This produces an error wen I try to use `web3` 1.3.0 in the browser:

```
Uncaught (in promise) TypeError: callbackify is not a function
    send index.js:139
    sendRequest index.js:609
    send index.js:636
    get_account eth.js:92
    get_account eth.js:91
    ensure_enabled eth.js:66
    main main.js:458
    async*[12]< main.js:614
    o _prelude.js:1
    r _prelude.js:1
    <anonymous> _prelude.js:1
```

Please revise `web3` to avoid the use of `callbackify`, or adjust it to source the function in a way that works with `browserify`.

**Comment by frankiebee** [comment]
wow looking at are package.json and `nonde_modules/util` the version is at 0.10 where callbackifiy isn't available till later versions.
probably just need to bump the module thanks for the catch!

**Comment by yashnaman** [comment]
Any quick fixes for this?

**Comment by interfect** [comment]
I downgraded to an earlier web3.

September 29, 2020 4:35 AM, "Yash Shah" <notifications@github.com (mailto:notifications@github.com?to=%22Yash%20Shah%22%20<notifications@github.com>)> wrote:
	Any quick fixes for this?

**Comment by frankiebee** [comment]
you could bump the dependency for utli in a local build to 0.12 or downgrade web3 as suggested

**Comment by yashnaman** [comment]
I downgraded it.
Thanks, @frankiebee @interfect

**Comment by loonylabs-dev** [comment]
hey there,
I have the same issue with every function I use with web3.eth like web3.eth.getAccounts
 "web3": "^1.7.0"
  "util": "^0.12.4"

any idea to fix this?
thanks in advance

`TypeError: callbackify is not a function
    at RequestManager.send (index.js:153:1)
    at sendRequest (index.js:624:42)
    at Eth.send [as getBalance] (index.js:656:13)`

**Comment by snake-py** [comment]
@MartinL-MG did you fix it?

I am having this issue as well. ALways when I am trying to treat web3 functions with async and await. 
using Web3 1.7.3
and "util": "^0.12.0" in web§-core-requestmanager

```js
  async makeContract() {
    const networkId = await this.web3.eth.net.getId();

    this.contract = new this.web3.eth.Contract(
      Token.abi,
      Token.networks[networkId].address
    );
  }
```

**Comment by loonylabs-dev** [comment]
> @MartinL-MG did you fix it?
> 
> I am having this issue as well. ALways when I am trying to treat web3 functions with async and await. using Web3 1.7.3
> 
> ```js
>   async makeContract() {
>     const networkId = await this.web3.eth.net.getId();
> 
>     this.contract = new this.web3.eth.Contract(
>       Token.abi,
>       Token.networks[networkId].address
>     );
>   }
> ```

nope I switched to ether.js and this works like a charm

**Comment by ZuulAndRibbon** [comment]
i have the same issue.I have downgraded the util version.But it get the same error.Do someone know how to fix it?

**Comment by snake-py** [comment]
I tried downgrading to 1.6.1 but it did not help.

**Comment by wobsoriano** [comment]
Same issues
