### ISSUE TITLE
Cannot connect to websocket provider

### ISSUE THREAD

**Issue by aminlatifi** [ethereum/web3.js#3728]
#### Expected behavior
We has been using to connect nodes using websocket, it was working till yesterday maybe!
#### Actual behavior
Web3 cannot connect to some websocket providers and throws error `connection not open on send()` on request. Actually the `connect` event is not emitted and it's showing that the connection is not stablished well.
We have such problem on connecting to Aragon and our gateway, but Infura works well!
#### Steps to reproduce the behavior
The below code reproduces it
```
const Web3 = require("web3");
const EventEmitter = require("events");

const instantiateWeb3 = (url) => {
  const provider =
    url && url.startsWith("ws")
      ? new Web3.providers.WebsocketProvider(url, {
          clientConfig: {
            maxReceivedFrameSize: 100000000,
            maxReceivedMessageSize: 100000000,
          },
        })
      : url;
  return Object.assign(new Web3(provider), EventEmitter.prototype);
};

const w3 = instantiateWeb3("wss://rinkeby.eth.aragon.network/ws");

if (w3.currentProvider.on) {
  console.log("wait for connect event");
  w3.currentProvider.on("connect", () => {
    console.log("Connected");
  });
} else {
  console.log("does not have evetns");
}

```

#### Environment

Node: 8.17.0 or 12.16.3
web3.js: 1.2.2 or 1.3.0

**Comment by aminlatifi** [comment]
We had fixed the issue on our gateway by changing nginx configuration.

**Comment by cokia** [comment]
If your issue has been resolved, why don't you close it?

**Comment by aminlatifi** [comment]
@cokia I guess we should close this issue since it's not web3 problem probably.
