### ISSUE TITLE
Change web3.eth.sendRawTransaction -> web3.eth.sendSignedTransaction

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#373]
Any comments on that API name change? @SilentCicero 

I think its more clear then the previous name

**Comment by SilentCicero** [comment]
sendRaw was Jeff's idea. I'm fine with either.

**Comment by d11e9** [comment]
:+1: Name change makes its use and behavior clearer imho.

**Comment by CJentzsch** [comment]
I actually like sendRaw. Because that is exactly what it is.
It does not need to be a signed transaction, although this will be the case 99%.
Also there are applications relying on it, and one should only change the interface when absolutely necessary, which is not the case I think.

**Comment by frozeman** [comment]
@CJentzsch we are doing many braking changes for the web3.js API and RPC for the next version, which are easy to change in any code.

But its really necessary to have an API which is intuitively understandable. And this function does nothing else than accepting already signed transactions.

Internal meaning should not always be the same as external meaning. An API should always treat the backend as a blackbox and only describe what the respective function does.

Therefore i'm for changing this in our effort to streamline things.

**Comment by macbem** [comment]
This might be an issue for people using MetaMask and for dapps built on it - you'll never know if an user has already switched to the new version of the extension and if MetaMask has transferred to the new web3 release, so you'll have to have checks for `sendRawTransaction` and `sendSignedTransaction` in the code.

You'd have to watch two dependencies - web3 and MetaMask to know what's the current status. IMO, a function name change is not worth the hassle for the community.

**Comment by frozeman** [comment]
The underlying RPC method will not change, its the web3.js library which exposes this differently in 1.0
