### ISSUE TITLE
Serious bug: Cannot read a public contract property (added reproducible example)

### ISSUE THREAD

**Issue by vporton** [ethereum/web3.js#3730]
web3.js 1.2.9

Connect to POA Sokol network in MetaMask and execute:
```html
<html>
<script src="web3.min.js"></script>
<script>
if(window.ethereum) window.ethereum.enable();
web3 = new Web3(window.web3.currentProvider);
interface = [{inputs: [], name: "arToETHCoefficient", outputs: [{internalType: "int128", name: "", type: "int128"}], stateMutability: "view", type: "function"}]
contractInstance = new web3.eth.Contract(interface, "0xcD9Fd48364c1D5d706860666259Fb3c83360492c");
contractInstance.methods.arToETHCoefficient().call();
</script>
</html>
```

```
web3.min.js:1 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

This contract does have an `int128` function of this name without arguments.

**Comment by vporton** [comment]
Reproducible code to produce the bug:

https://github.com/vporton/test-web3-read-int128

**Comment by Spacesai1or** [comment]
So I ported over your example code into a Truffle project [here](https://github.com/spacesailor24/web3-3730-truffle/tree/master) (because I'm unfamiliar with Builder), and I do not get the error - I'm not sure if this means there's a bug within Builder, or perhaps more likely their web3 plugin?

**Comment by vporton** [comment]
> So I ported over your example code into a Truffle project [here](https://github.com/spacesailor24/web3-3730-truffle/tree/master) (because I'm unfamiliar with Builder), and I do not get the error - I'm not sure if this means there's a bug within Builder, or perhaps more likely their web3 plugin?

Yes, under Truffle and Ganache it does work.

The bug is produced also (see above) by running web3.js in a browser, so unless there was a contract deployment bug in Buidler, it cannot be a bug of Buidler.

I don't understand what it is. Maybe a contract deployment bug in Buidler?

**Comment by vporton** [comment]
Oh, my error. I am closing the bug.
