### ISSUE TITLE
[Public Announcement] Addressing TypeScript issues

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#3734]
There have been many reports that the typescript typings are incorrect (#3725, #3292, etc..). This issue is acting as a milestone for an upcoming release `1.4.0` (date TBD) which will effectively addresses issue #3606 as well as a few other things.

The objective is to address all the typing issues in a non-breaking manner to the JS code itself, by breaking the API on the typescript bindings themselves. This means that we will be update all the `.d.ts` files rather than actually updating the `.js` files. This is for a few reasons, most namely there is an active effort to restructure the entire project to es6, and subsequently TypeScript (wooo native bindings). Therefore we will eventually get to a point that will be much better/cleaner and we won't need to worry about matching types manually.

We will need to take sometime to actually fix everything, rather than just one or two files at a time. Currently the es6 refactor has the 1.4.0 release reserved, but I don't see a reason we couldn't also include the typings fix within it.

If you have any questions feel free to comment below.

**Comment by ariesjia** [comment]
Due to these issues, so we can't use TS in project.  These just are typing errors will not bring break changes or bugs. Is there any possible to fix this issue before v1.4 released?
I update all the .d.ts file in #3732.

**Comment by GregTheGreek** [comment]
You can still use the library, you just will not have access to some of the types.

**Comment by AuHau** [comment]
Ufff this is a problem already for a year. Any ETA for 1.4.0?

@ariesjia work around is to use custom declaration that overrides this like:
```
import { Contract } from 'web3-eth-contract'

declare module 'web3-eth-contract' {
  export default Contract
}
```

The problem for me is that I have a library that uses web3.js and now all its TS users have to use this hack in order to make it work...

**Comment by GregTheGreek** [comment]
@AuHau i totally understand, and we're rapidly trying to fix this.

We're very close to having our es6 branch completed, at which point we'll be making a lot of PR's to update the main exports to typescript, and slowly working our way down the tree. 

There's a good chance it could come after the current RC

**Comment by ynaciri** [comment]
I've added issue #3873 since I didn't find anything related to that point in the current and past issues.
