### ISSUE TITLE
Updated to web3 1.2.0

### ISSUE THREAD

**Issue by FahdW** [ethereum/web3.js#3736]
`Fetching failed Error: insufficient data for boolean type (arg="", coderType="boolean", value="0x")`

I recently upgraded my web3 from beta to web 1.2.0 and due to the upgrade the contract call is suddenly having an error. The error seems to be coming from ethers/abi-coder.

**Comment by Spacesai1or** [comment]
Hi there, thank you for reporting this! Is there any way we could a code snippet depicting the error you're receiving?
