### ISSUE TITLE
Binding provider callback in 1.3.0 breaks Magic JS SDK (Fortmatic)

### ISSUE THREAD

**Issue by smithki** [ethereum/web3.js#3737]
#### Expected behavior

Magic JS SDK should work with Web3 `^1.3.0`. A breaking change was somehow introduce between `1.2.x` and `1.3.x`.

I am a maintainer of Magic SDK, so I will try to mitigate from that side when I can. Problem is that Magic SDK works with `web3@<=1.2.x` without issue, so I consider this a breaking change on the Web3-side...

This is related to https://github.com/magiclabs/magic-js/issues/138

#### Actual behavior

The following error shows when attempting any Web3 method using the Magic RPC provider:

<img width="1051" alt="Screen Shot 2020-10-05 at 1 51 08 PM" src="https://user-images.githubusercontent.com/22753882/95130707-d687e200-0711-11eb-8f3c-cee6e13fdfe0.png">

I believe a bug was introduced [in this commit](https://github.com/ethereum/web3.js/commit/e7adda5727b1e5a003872fe0657bd47af2b64950#diff-11cbf793feb1c35899194d3a17c4ece4R166). Magic JS SDK has implemented it's RPC provider as a class with additional methods parameters that are used beyond Web3 use-cases. The binding (`this.provider.request.bind(this.provider)`) on line `166` of `web3-core-requestmanager/src/index.js` is seemingly causing the Magic provider to lose its `this` context.

#### Steps to reproduce the behavior

[Here's a CodeSandbox to test the issue](https://ru7ex.csb.app/).

1. Get an API key from Magic JS SDK: https://dashboard.magic.link
2. Input the API key into the field on the CodeSandbox
3. Login passwordlessly via your email address. A call to `eth_getAccounts` will be made upon successful login. You should see the error referenced above.

#### Environment

`web3@^1.3.0` and `magic-sdk@^2.7.0`

**Comment by GregTheGreek** [comment]
thanks for reporting this!
We addressed this in the latest 1.x branch. If you want do you mind giving it a run and see if it wokrs? We're planning a release next week!
