### ISSUE TITLE
Functions `fromUtf8` and `fromAscii` ignores optional `padding` parameter

### ISSUE THREAD

**Issue by ruchevits** [ethereum/web3.js#374]
Functions `fromUtf8` and `fromAscii` doesn't work as advertised (optional `padding` parameter is ignored). Shall I do a pull request?

fromUtf8: https://github.com/ethereum/web3.js/blob/0ae82cf895b74b264d309d21feecbf3645713d0b/lib/utils/utils.js#L139-L159

fromAscii: https://github.com/ethereum/web3.js/blob/0ae82cf895b74b264d309d21feecbf3645713d0b/lib/utils/utils.js#L161-L178

**Comment by frozeman** [comment]
The optional padding is not in the docs, https://github.com/ethereum/wiki/wiki/JavaScript-API#web3toascii

but it might make sense, so 32bytes right padding? @chriseth

**Comment by ruchevits** [comment]
https://github.com/ethereum/web3.js/pull/375

**Comment by frozeman** [comment]
Closing this in favour of http://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#encodeparameter
