### ISSUE TITLE
ENS Reverse Resolution is not supported

### ISSUE THREAD

**Issue by 3esmit** [ethereum/web3.js#3749]
Add support for reverse resolution.

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention, adding a [doc link](https://docs.ens.domains/dapp-developer-guide/resolving-names#:~:text=Reverse%20Resolution&text=ENS%20supports%20reverse%20resolution%20to,the%20resolver%20function%20name()%20.) for additional context

**Comment by 3esmit** [comment]
Why close this if not solved?

**Comment by 3esmit** [comment]
Why close this if not solved?
