### ISSUE TITLE
Not Compatible v1.3.0-rc.0 with 1.2.11 on web3-utils

### ISSUE THREAD

**Issue by safakoks** [ethereum/web3.js#3751]
We are developing a smart contract as called [tubu.io](https://www.tubu.io) for private and ethereum-based blockchain networks. Mostly, our focus is on ConsenSys Quorum. The main difference ConsenSys Quorum Blockchain is the `block timestamp` type.

So, the util method which is called 'hexToNumber' on 'web3-utils' is not suitable for Quorum Blockchain block timestamp type. There are many issues with these 'Number can only safely store up to 53 bits' situations such as #1905 and #1960.   

To fix this bug for Quorum, we update the 'hexToNumber' with formatters

```js
const newWeb3 = new Web3(
        new Web3.providers.WebsocketProvider(connectionString)
      );

web3 = newWeb3;
      await this.checkConnection();
      web3.extend({
        property: "eth",
        methods: [
          new web3.extend.Method({
            name: "getBlockByNumber",
            call: "eth_getBlockByNumber",
            params: 2,
            inputFormatter: [
              web3.extend.formatters.inputBlockNumberFormatter,
              (v) => !!v,
            ],
            outputFormatter: web3.extend.formatters.outputBlockFormatter,
          }),
        ],
      });

web3.utils.hexToNumber = (v) => {
        if (!v) return v;
        try {
          return numberToBN(v).toNumber();
        } catch (e) {
          return numberToBN(v).toString();
        }
      };
```

This fixation way is working on v1.2.11, but on v1.3.0-rc.0 web3-utils are working differently so the fixation method is not working as expected. In addition, we can not find how can we fix this bug on v1.3.0-rc.0 

#### Expected behavior

We expect that web3-utils would not regenerate after initializing on v1.3.0.-rc.0 like on v1.2.11. Another way, because of that `package.json` includes `^1.2.11` as default it will install the latest version as `v1.3.0-rc.0`. So, v1.2.11 must be compatible with this situation.

#### Actual behavior

After initializing web3, while calling `contract.deploy` or `eth.sendTransaction` web3-utils are initialized again so override functions do not work.

#### Possible Solution

`hexToNumber` method on web3-utils can be updated with :

```js
function hexToNumber(v) {
        if (!v) return v;
        try {
          return numberToBN(v).toNumber();
        } catch (e) {
          return numberToBN(v).toString();
        }
      };
```

But this updating can affect other parts of web3

#### Environment
web3 : v1.2.11 vs v1.3.0-rc.0
node : v12.18.2
OS : Linux Mint 20

**Comment by GregTheGreek** [comment]
Sorry for the late reply. I had taken some time off, im flagging this since you should not have been able to download the latest since its an RC

**Comment by GregTheGreek** [comment]
Do you mind explaining what you mean by `regenerating`?

**Comment by safakoks** [comment]
No problem with the late reply.

When I override the `hexToNumber` functions on web3-utils, it still uses the [`classic hexToNumber`](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/src/utils.js#L230) function. In other words, I can not override any functions on web3-utils after initializing a new web3 instance like that :

```js
const web3 = new Web3();

web3.utils.hexToNumber = (v) => {
        if (!v) return v;
        try {
          return numberToBN(v).toNumber();
        } catch (e) {
          return numberToBN(v).toString();
        }
      };
```

I think it does not use `utils` of web3 instance. when I set the `web3.utils` as `undefined`, it still uses its own `utils`.

**Comment by GregTheGreek** [comment]
let me investigate this cc: @frankiebee @koraykoska  any initial thoughts?

**Comment by GregTheGreek** [comment]
Still looking into this

**Comment by Spacesai1or** [comment]
@safakoks Are you manually calling `hexToNumber`, or is Quorum calling it somewhere and you're just getting the error? Because `hexToString` exists and I think it would make sense to update your code to use it rather than updating `hexToNumber` to possibly return a string

Also maybe you could use `hexToNumberString`?

Doc link for [hexToNumberString](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#hextonumberstring)
Doc link for [hexToString](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#hextoutf8)

**Comment by safakoks** [comment]
@spacesailor24 I uses `on('receipt')` event during [sending tx](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send). I think it uses `hexToNumber`. But `block.timestamp` type is the main problem. Because the type of Quorum's block timestamp is different, the original `hexToNumber` cannot convert as I understand. I do not use the method independently.

Overriding `hexToNumber` was the solution before update `web3` version from 1.2.11 to v1.3.0.rc.0
