### ISSUE TITLE
invalid rpc response on ethereum geth

### ISSUE THREAD

**Issue by dozcan** [ethereum/web3.js#3752]
despite thinking this is an solved issue. After 1 years i have faced this issue, never met before.

here is the  environment;

1) have dockerize aws ethereum instance which makes mining geth node 8545:8545
2) i have backend api with nodejs(>=8) and     
   "solc": "^0.4.24",
    "web3": "1.0.0-beta.33"
3) var web3 = new Web3(new Web3.providers.HttpProvider("http://54.191.162.75:8545"));

everything looks good but until this line; this line produces invalid rpc response

 let account = await web3.eth.getAccounts();

can you help me? i dont want to use ganache-cli....

**Comment by GregTheGreek** [comment]
You're using an outdated version of web3.js that we are not backporting to. Please try updating to the latest :)
