### ISSUE TITLE
Is semver being followed? 1.2.7 contains breaking changes

### ISSUE THREAD

**Issue by LudwikJaniuk** [ethereum/web3.js#3758]
Hi, I my deployment scripts recently started crashing and I identified that a version change from Web3 1.2.1 to 1.2.9 was a possible issue. I'm not going to get into the details of that, it was just how I got here :)

I want to ask: the version numbers look like semantic versioning, so is that assumption correct of me to make? I couldn't quickly find any documentation on it here. 

If you are using semantic versioning on this repository, then shouldn't version 1.2.7 have been version 2.0.0? The change notes state that behavior is being changed. Any external code that relied on the first user being used will fail after this. Given such a change, bumping only the patch number seems inappropriate to me. Am I missing something?

Best regards,
//Ludvig

**Comment by GregTheGreek** [comment]
Hey!

Thanks for pointing out, [ChainSafe](www.github.com/chainsafe) recently took over the development of web3.js, our first release was `v1.3.0`. For prior release I cannot confirm if there was a break in the API but i can promise you we are being very diligent to ensure we follow semver as closely as possible moving forward.

**Comment by LudwikJaniuk** [comment]
Thank you, and it makes me happy to hear it's something you're taking seriously moving forward. Can I ask that you insert some note about it in the README? For example something like this: https://github.com/ethereum/web3.js/pull/3763, so that anyone coming across this in the future knows what's up.

**Comment by GregTheGreek** [comment]
awesome thank you!
