### ISSUE TITLE
Request: web3.eth.isSynced

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#376]
`web3.eth.syncing` could be false for two reasons
1. The node has not yet started syncing
2. The node is completely synced

I'm not aware of any clean way of differentiating between the two. I'm currently using the following which makes me nervous. This is called inside a loop. `firstBlock` is outside the loop and is the first highest block recorded

```
 var isSynced = 
      ($rootScope.syncing && $rootScope.syncing.currentBlock === $rootScope.syncing.highestBlock)
      || (!$rootScope.syncing && web3.eth.blockNumber>firstBlock);
```

**Comment by chriseth** [comment]
If you want to check whether the blockchain is synced, I would say that assuming that the system clock is set correctly and just comparing the timestamp of the latest block with "now" is a good strategy.

**Comment by frozeman** [comment]
therefore we have the `web3.eth.isSyncing()` function which will notify you about syncing progress.
We will soon move this over to subscriptions anyway, which will then work similar like the current `web3.eth.isSyncing()`.

**Comment by hitchcott** [comment]
+1 for `isSynced`

Timestamps are pretty unreliable and we can't assume users have their clocks set correctly. I want something that works for everyone all the time.

My use case is that I am connecting to a node remotely with a light wallet. The problem with `isSyncing` is that the polling is too expensive on the network and I'd rather control the interval time myself.

The only workaround I can think of for now is a way to control poll speed for the `isSyncing` API. Possible?

**Comment by frozeman** [comment]
The one problem is that even if the node thinks its synced, doesn't mean it is, because it can later discover more peers with higher blocks.

So im not sure whats the difference to `eth_syncing` right now then?

**Comment by aakilfernandes** [comment]
`eth_synced` would return false up until the peer selection/handshakes are complete and the highest block from all peers have been reported

**Comment by frozeman** [comment]
For the web3.js < 1.0 please provide a PR, for version later we have the `web3.eth.subscribe('syncing', function)` subscription now. 
https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#syncing
http://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-syncing
