### ISSUE TITLE
Wrong doc about the result of "new BN('0xea').toString();"

### ISSUE THREAD

**Issue by hihidev** [ethereum/web3.js#3762]
Following 
https://web3js.readthedocs.io/en/v1.3.0/web3-utils.html?highlight=BN#bn

Run:
new BN('0xea').toString();

#### Expected behavior
"234"

#### Actual behavior
"3450"

PS: web3.utils.toBN('0xea') returns "234" correctly

**Comment by jdevassi** [comment]
When removing the single quotation marks -> expected behaviour.

On:
new BN(0xea).toString();

We get:
234

Same (previous comment's) conditions and results when using 'bn.js'  directly.

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention! This should be an easy one to fix :slightly_smiling_face:
