### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by koraykoska** [ethereum/web3.js#3767]
JSHint is a mess. Let's switch to ESLint. We can configure a style guide and let people install plugins for their editors to format on save, even with custom options and between TS and JS.

I suggest we also agree on one of the major style guides in the process and require it project wide before approving PRs. This can be done easily with Github Actions.

**Comment by cokia** [comment]
I really sympathize with your opinion.
I've never seen jshint work properly.

I think eslint is suitable way for typescript response.

**Comment by GregTheGreek** [comment]
yep, i also think we should probably switch over to using babel vs TSC
