### ISSUE TITLE
ENS Support for EWC

### ISSUE THREAD

**Issue by Agupane** [ethereum/web3.js#3768]
#### Expected behavior

ENS should be supported on EWC network. 

#### Actual behavior

It is not supported

![image](https://user-images.githubusercontent.com/21086218/97715907-b72a6d80-1aa1-11eb-9fdc-7ac844835fa1.png)

#### Steps to reproduce the behavior

Try to call web3.eth.ens.getAddress(name) when connected to a EWC.

#### Environment

Versions
web3.js 2.0.0-alpha.1

**Comment by GregTheGreek** [comment]
Hey, I'm not familiar with EWC, what exactly is this?

**Comment by Agupane** [comment]
Sorry, EWC means Energy Web Chain, [here](https://energyweb.org/technology/energy-web-chain/) is the URL to the web

**Comment by GregTheGreek** [comment]
Unfortunately we do not support the ability to change the ENS name. I presume this was originally done as a security measure. You can see available networks [here](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-ens/src/config.js)

**Comment by Agupane** [comment]
Hi @GregTheGreek the idea is to add EWC to the list of supported ENS, not to change the ens name. This issue requests the same as [this one](https://github.com/ethereum/web3.js/issues/3252). In which only adding the ENS address for EWC is needed.

Let me know if I explained myself correctly or if you have more questions

**Comment by ngyam** [comment]
Hi @GregTheGreek can we have this issue reopened?
It's just adding web3.js ENS support to our EVM chains, basically 2 additional Registry addresses, as in the open PR.
Many if our projects depend on it and it would be great to officially use the vanilla web3.js lib for this.

**EnergyWebChain (EWC)** - our live value bearing production chain - https://chainid.network/chains/#energy-web-chain--
**Volta** - testnet - https://chainid.network/chains/#energy-web-volta-testnet--

**EnergyWeb ENS manager app**: https://ens.energyweb.org -> works with [Metamask configured to Volta or EWC](https://energyweb.atlassian.net/wiki/spaces/EWF/pages/723681315/Connecting+via+Remote+RPC+and+Metamask)
**ENS addresses** can be verified here: https://energyweb.atlassian.net/wiki/spaces/EWF/pages/555745281/Using+ENS

**Project info**

EWC Explorer: https://explorer.energyweb.org
Volta explorer: https://volta-explorer.energyweb.org
 
brandsite: https://www.energyweb.org/
Official Telegram: https://t.me/energyweb
Unofficial Telegram: https://t.me/energywebtrader
Coinmarketcap: https://coinmarketcap.com/currencies/energy-web-token/
Coingecko: https://www.coingecko.com/en/coins/energy-web-token
Github: https://github.com/energywebfoundation

EWT <-> EWTB bridge: https://bridge.energyweb.org
Etherscan verified EWTB token page: https://etherscan.io/token/0x178c820f862b14f316509ec36b13123da19a6054
EWTB/ETH Uniswap pair: https://info.uniswap.org/pair/0xdc7d8cc3a22fe0ec69770e02931f43451b7b975e

**Comment by GregTheGreek** [comment]
I'm not trying to be rude, so please bare with me. Hopefully this highlights a larger concern we have with supporting blockchain specific features not included in Ethereum. The main problem is that we have to do this for every other blockchain.

EWC is not in our list of default networks that can be connected to, and thus I would say to have support for ENS we would also want that network to have support within the provider side. The only problem with this is where do we draw the line at networks we support or do not support?

Our 1.4.x releases will be adding a method `use` that will allow you to effectively build your own module (plugin style). I would suggest building a plugin that acts as a decorator for the relevant pieces that would affect EWC.
