### ISSUE TITLE
Changing IBAN library to ethereumjs-icap

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#377]
This issue is here as a "take a look later" reminder
@axic

**Comment by axic** [comment]
@frozeman you might want to check out https://github.com/ethereumjs/ethereumjs-icap/issues/1 for discussing a new API

**Comment by axic** [comment]
@frozeman released a brand new version which enforces the 0x prefix and expects fixed length hex addresses. That should be easier to integrate.

**Comment by frozeman** [comment]
I am not sure if it makes sense to switch to your library, or keep what we have in web3.js now: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-iban/src/index.js

**Comment by onbjerg** [comment]
Sorry if this is a common question, but why are ICAP-related functions even bundled in Web3 in the first place? Surely an external library would suffice?
