### ISSUE TITLE
web3 1.2.9 does not properly encode "-1" as int8 (signed)

### ISSUE THREAD

**Issue by shark0der** [ethereum/web3.js#3772]
My current contract has a function with the following signature:

`function submitCAVote(uint claimId, int8 verdict)`. I'm trying to pass `-1` as verdict value.

#### Expected behavior

`-1` passed as a string or BN should be encoded correctly and function called.

#### Actual behavior

When calling the contract web3 throws the following error:

`Error: invalid BigNumber string (argument="value", value="000000-1", code=INVALID_ARGUMENT, version=bignumber/5.0.8)`

#### Steps to reproduce the behavior

```
const abi = [{
    "constant": false,
    "inputs": [{
        "name": "id",
        "type": "uint256"
    }, {
        "name": "vote",
        "type": "int8"
    }],
    "name": "submitCAVote",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
}];

const { toBN } = web3.utils;
const negativeOne = toBN('-1');

const contract = new web3.eth.Contract(abi, contractAddress);
await contract.methods.submitCAVote('1', negativeOne);
```

I hope this is enough to reproduce the issue. Currently this code is untested as I have extracted the relevant parts from my testing environment. 

#### Logs

The stack trace does not include anything from `node_modules` (just the path to my test).

#### Environment

I'm using `web3@1.2.9` on node `v12.19.0` and npm `6.14.8` on Ubuntu.

cc @alcuadrado

**Comment by alcuadrado** [comment]
@shark0der you mentioned that there's a version and properly encodes it. Which version was it?

**Comment by shark0der** [comment]
@alcuadrado it works fine on `web3@1.2.1`

**Comment by shark0der** [comment]
There's also another issue which is more of an incompatibility rather than a bug. When passing `-1` for a `uint` parameter it complains that the value is bad while previously it was converting it to `MAX_UINT`.

**Comment by alcuadrado** [comment]
@ryanio @cgewecke I think we discussed some problems with the version of the ethers encoder used by web3. Can this be related?

**Comment by cgewecke** [comment]
Hi @shark0der - in an initial attempt I haven't been able to reproduce this. 

Could you show the complete stack trace of the error?

For both 1.2.9 and 1.3.0, the following seems to encode the params correctly
```js
const { toBN } = web3.utils;
const negativeOne = toBN('-1');

const contract = new web3.eth.Contract(abi);
const val = contract.methods.submitCAVote('1', negativeOne).encodeABI()

> 0xbfa52b120000000000000000000000000000000000000000000000000000000000000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

**Comment by cgewecke** [comment]
> There's also another issue which is more of an incompatibility rather than a bug. When passing -1 for a uint parameter it complains that the value is bad while previously it was converting it to MAX_UINT

There are a couple other behavioral changes listed in the `1.2.8` [release notes][1]. These are intended as bug-fixes, e.g. silently overflowing when a negative number is passed as an unsigned integer seems bad.  

[1]: https://github.com/ethereum/web3.js/releases/tag/v1.2.8

**Comment by shark0der** [comment]
I'm not sure I've correctly identified the issue because running `contract.methods.submitCAVote('1', negativeOne).encodeABI()` returns exactly what you have. The culprit might be truffle-contract but I'm really not sure where to dig because the stack trace does not show anything from `node_modules`:

```
[A2, status: 0, 4, 8, 14] CA no consensus, MV accept, closed with closeClaim():
  Error: invalid BigNumber string (argument="value", value="000000-1", code=INVALID_ARGUMENT, version=bignumber/5.0.8)
    at Context.<anonymous> (test/integration/ClaimPayoutAddress/payouts.js:161:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I've pushed the failing code here: https://github.com/NexusMutual/smart-contracts/tree/broken/remove-oraclize.
The test itself is here: https://github.com/NexusMutual/smart-contracts/blob/broken/remove-oraclize/test/integration/ClaimPayoutAddress/payouts.js#L117

`npm i && npm test` should suffice to reproduce the issue.

**Comment by cgewecke** [comment]
Awesome thanks @shark0der.

**Comment by cgewecke** [comment]
It looks like it *is* a problem here but only affects negative number strings... 

Modifying the NexusMutual tests like this makes them pass
```diff
-   await cl.submitCAVote(claimId, '-1', { from: member2 });
+   await cl.submitCAVote(claimId, toBN('-1'), { from: member2 });
```

Native negative numbers also work (for both truffle/contract and pure Web3).
```js
await cl.submitCAVote(claimId, -1, { from: member2 }); // OK
```

Relevant code at Web3 is [around this location][1]. 

[1]: https://github.com/ethereum/web3.js/blob/edf481d37ed0c4c4caae7a25619704010ac3639e/packages/web3-eth-abi/src/index.js#L265-L273

**Comment by shark0der** [comment]
Oh, unexpected. The other issue I was talking about was the `-1` to MAX_UINT conversion.
The failing code is here: https://github.com/NexusMutual/smart-contracts/blob/broken/remove-oraclize/test/integration/ClaimPayoutAddress/membership.js#L44

This was also working fine with web3 1.2.1

**Comment by cgewecke** [comment]
@shark0der 

> -1 to MAX_UINT conversion

See [comment above][1]. In your view should this not be seen as a bug-fix?

[1]: https://github.com/ethereum/web3.js/issues/3772#issuecomment-721301243

**Comment by shark0der** [comment]
I see it as a breaking change that should not be included in a patch version but rather in a minor version to follow the semver convention. If the library is silently updated - the tests start failing (which is exactly what happened).

Maybe that wasn't the intention initially but this is what we are using and perhaps others could be using as well. It's also similar to how solidity behaves so it was easy to understand and adopt it.

Might also be worth checking since when this started to happen. It was behaving like this in 1.2.1 which was released in Aug 6, 2019 so it was behaving like this for over 9 months until it was "fixed" - not sure how many people rely on this already.

Longterm, however, I strongly agree it should not silently overflow but rather throw to prevent unintended behaviour.

**Comment by GregTheGreek** [comment]
@koraykoska :)

**Comment by jo-es** [comment]
Experiencing a similar issue after updating from 1.2.4 to 1.3.1.
E.g. this [method](https://github.com/atpar/ap-monorepo/blob/dev/packages/protocol/contracts/ACTUS/test/TestSignedMath.sol#L15)  which takes two int256 params. Both values are passed as strings to the abi encoder.
```js
await TestFixedPointMath.methods._fixedMul(
  new BigNumber(1).toFixed(),
  new BigNumber(-1).shiftedBy(30).toFixed()).call()
);
``` 
works fine
```js
await TestFixedPointMath.methods._fixedMul(
  new BigNumber(1).toFixed(),
  new BigNumber(-1).shiftedBy(31).toFixed()).call()
);
``` 
Increasing the exponent of the second multiplier by 1 throws `invalid BigNumber string (argument="value", value="0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000-10000000000000000000000000000000", code=INVALID_ARGUMENT, version=bignumber/5.0.13)`.
