### ISSUE TITLE
Getting "Returned values aren't valid, did it run Out of Gas?" on 1.x

### ISSUE THREAD

**Issue by dmitry-salnikov** [ethereum/web3.js#3774]
Since the `2.x` branch seems to be not supported anymore, I'm trying to migrate to `1.x` branch.
Everything works fine except one thing the next error when trying to get ERC20 token balance:

```
let web3 = new Web3(httpProvider);
let tokenContract = new web3.eth.Contract((erc20 as AbiData).abi, tokenContractAddress);
let balance = await contract.methods.balanceOf(address).call(options);
```

I've seen a number on similar issues here, but in my case - I'm getting `Returned values aren't valid, did it run Out of Gas? ...` error on any version from `1.2.2` to `1.3.0` only - but it works fine on `2.0.0-alpha1`. 

I've tried to find any related breaking changes reading changelogs from 1.2.2 to 1.3.0 and haven't succeed. Could you please advice what could be wrong? Thanks for any help.

**Comment by Spacesai1or** [comment]
Hi there, just checking if this is still an issue for you?
