### ISSUE TITLE
stripHexPrefix is present in types for web3-utils but isn't present in js code

### ISSUE THREAD

**Issue by chaitanyapotti** [ethereum/web3.js#3776]
The types for web3-utils specify the export of `stripHexPrefix` but it isn't present in the js code.

#### Expected behavior
Actually export the function or remove the export from types

#### Environment
npm: 6.x
node: 12.x
web3.js: 1.3.0

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention, you are absolutely right - I'm sure we'll be able to correct this soon!

In the meantime, a quick workaround would be `string.replace(/^0x/i, '')`

**Comment by alemagio** [comment]
Hi, I'm new to this project but if you don't mind I would like to try and solve it.
