### ISSUE TITLE
Unexpected `transactionRoot` property name

### ISSUE THREAD

**Issue by tgmichel** [ethereum/web3.js#3777]
The [eth_getBlockByHash documentation](https://eth.wiki/json-rpc/API#eth_getblockbyhash) describes the response as including a `transactionsRoot` property, but `web3-eth` [BlockHeader interface](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/types/index.d.ts#L397) expects a `transactionRoot` (without an s).

Is this a known problem or am I missing something?

**Comment by Spacesai1or** [comment]
I don't know if there was a reason for it, but it looks like a typo - @GregTheGreek can you confirm?

**Comment by GregTheGreek** [comment]
Hmm... ill need to poke around and see what other teams are doing

**Comment by GregTheGreek** [comment]
I think this is a typo, but it would also be a breaking change due to it existing in the code like this...

**Comment by tgmichel** [comment]
In our particular case we have a workaround for it in the tests, however it's good to know that differs from the Ethereum specs so in the future we can take this into account.

Anyway, thank you for taking some time to look at it and please feel free to close this if no further action will be taken.

**Comment by GregTheGreek** [comment]
This is an issure, so we'll be keeping it open thanks for reporting this.
