### ISSUE TITLE
DevContainer

### ISSUE THREAD

**Issue by koraykoska** [ethereum/web3.js#3779]
I am thinking about setting up a VSCode DevContainer and running the CI flow inside the container as well. This would eliminate failing tests on just the CI or just locally as we could reproduce them perfectly on our machines.

Especially for a project with so many dependencies it's so important to be able to reproduce failing tests.

**Comment by cokia** [comment]
I agree with you that we need an easily accessible CI. However, I think VSC DevContainer is a way to rely on an IDE too much. Is there any other alternative?
