### ISSUE TITLE
Ya

### ISSUE THREAD

**Issue by tota999** [ethereum/web3.js#3783]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by tota999** [comment]
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the behavior
> 1. [First step]
> 2. [Second step]
> 3. [and so on...]
> 
> #### Logs
> #### Environment

**Comment by spacesailor24** [comment]
Hi there, did you mean to create an issue? If so, please fill out the description so we can try to help :)

**Comment by tota999** [comment]
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the behavior
> 1. [First step]
> 2. [Second step]
> 3. [and so on...]
> 
> #### Logs
> #### Environment
