### ISSUE TITLE
And this is the error

### ISSUE THREAD

**Issue by wbshobhit1** [ethereum/web3.js#3784]
And this is the error

Error: Cannot find module '/Users/pablo/Downloads/blockchain-for-healthcare-master/node_modules/web3/packages/web3/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:292:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:523:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:767:27)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/pablo/Downloads/blockchain-for-healthcare-master/node_modules/web3/package.json',
  requestPath: 'web3'

_Originally posted by @pabloiarriola in https://github.com/ethereum/web3.js/issues/2476#issuecomment-538602214_

**Comment by cokia** [comment]
Did you try 'npm install' or 'npm install web3.js'?

I think the reason why you are having this problem is just because you didn't install web3.js.

Also, if you do not understand the issue well when creating the issue from next time, please give us an intuitive title such as using the first line of error excluding the path. Thank you!

**Comment by Spacesai1or** [comment]
So the `package.json` provided [here](https://github.com/ethereum/web3.js/issues/2476#issuecomment-538602067) actually has a typo for the `test` script (two extra ")

And for the actual `web3` dependency, I was able to reproduce the error when using `"web3": "github:ethereum/web3.js"` however, the error went away after replacing `github:ethereum/web3.js` with a version number such as `^1.3.0`

If possible, please try updating the version for `web3` in the `package.json`

**EDIT** To be similar to the original code, you can also use `"web3": "git://github.com/ethereum/web3.js.git"` which will install the repo from Github directly
