### ISSUE TITLE
web3 / wallet connect / react throws "send is not a function"

### ISSUE THREAD

**Issue by elmariachi111** [ethereum/web3.js#3788]
#### Expected behavior
We can use a web3 library with a  provider by WalletConnect

#### Actual behavior
We binding web3 1.3.0 used inside CRA to a WalletConntect provider, any call to RPC throws a meaningless JS exception "send is not a function 

#### Explanation / related issues

(uses react-web3 under the hood):
https://github.com/aragon/use-wallet/issues/59
https://github.com/strudel-finance/monorepo/issues/20

see https://stackoverflow.com/questions/64464900/walletconnect-error-while-integration-in-reactjs-uncaught-in-promise-typeerr 

current solutions: "use ethers" (well, no ;) ) or downgrade to web3 1.2.11 :roll_eyes: 

#### Environment

React 16.13.1 / web3 1.3.0 / WalletConnect (via web3-react 6)

#### Logs 
This doesn't seem to be "directly" related to web3 code but is caused transitively by the connection manager. The code that wraps / throws the error is: 

https://github.com/ethereum/web3.js/pull/3649/files#diff-d25786686c1053b786cc2626dc6e048675050593c0ebaafbf0814e1996f22022R166

**Comment by sergey-chekriy** [comment]
you can also take this 'official' example for vanilla js: https://github.com/Web3Modal/web3modal-vanilla-js-example
replace in index.html, line 97: 1.2.11 on 1.3.0 and see the same error.

  <script type="text/javascript" src="https://unpkg.com/web3@1.2.11/dist/web3.min.js"></script>

**Comment by GregTheGreek** [comment]
Is this still an issue?

**Comment by elmariachi111** [comment]
Upgraded to the latest web3 package (1.3.3) and cannot reproduce anymore, thank you :)

**Comment by AmanGadadare** [comment]
is this still issue i was unable to connect to the wallet and it throws me the error      
Unhandled Runtime Error
TypeError: web3modal__WEBPACK_IMPORTED_MODULE_4___default(...).connect is not a function
