### ISSUE TITLE
this.send is not a function with Web3.js 1.3.0

### ISSUE THREAD

**Issue by miohtama** [ethereum/web3.js#3790]
I am opening this issue report here, because although this is documented elsewhere, we are getting so many issue reports regarding this. I hope this will help people to locate this issue faster and help themselves with Google, instead of coming to the chat.

#### Expected behavior

Creating a node connection with web3.js and WalletConnect works.

```js
import Web3 from "web3";
import WalletConnectProvider from "@walletconnect/web3-provider";

//  Create WalletConnect Provider
const provider = new WalletConnectProvider({
  infuraId: "" // Required
});

//  Enable session (triggers QR Code modal)
await provider.enable();

//  Create Web3
const web3 = new Web3(provider);
```

#### Actual behavior

You will get

```
Uncaught (in promise) TypeError: this.send is not a function
```

[This bug is documented in detail here in the associated PR where the bad behavior was added](https://github.com/ethereum/web3.js/pull/3649#issuecomment-696533463). 

#### Steps to reproduce the behavior

Use Web3.js 1.3.0.

Try to create WalletConnect connection using the code above.

#### Environment

Web3.js 1.3.0

#### Workaround

Downgrade your Web3.js package to 1.2.x.

**Comment by Alirun** [comment]
Confirm the issue with `v1.3.0`, had to downgrade to `v1.2.11`

**Comment by 0xMeir** [comment]
+1
