### ISSUE TITLE
I failed to send ether with some memo(custom data) to some NON-CONTRACT account by calling sendTransaction

### ISSUE THREAD

**Issue by fintechee** [ethereum/web3.js#3793]
Hi,

I failed to send ether with some memo(custom data) to some NON-CONTRACT account by calling sendTransaction

        web3.eth.sendTransaction({
          from: web3.givenProvider.selectedAddress,
          to: "0xXXXXXXXXXXXXXXX",
          value: 0.01,
          data: web3.toHex("Some Memo")
        }).then(function (receipt) {
        }).catch(function (e) {console.error(e)})

#### Expected behavior
successfully done, and the input of the receipt should include the memo(custom data)

#### Actual behavior
error:  Error: TxGasUtil - Trying to call a function on a non-contract address
{
  "originalError": {
    "errorKey": "transactionErrorNoContract",
    "getCodeResponse": "0x"
  }
}

#### Logs
error:  Error: TxGasUtil - Trying to call a function on a non-contract address
{
  "originalError": {
    "errorKey": "transactionErrorNoContract",
    "getCodeResponse": "0x"
  }
}

#### Environment
Chrome Browser, MetaMask, Web3js, Rinkeby Testnet

**Comment by yzevm** [comment]
@fintechee Not sure that you can send some `data` message to another address

If I remember it right, first 8 digits of `data` is hex id of contract method, rest is your params

**Comment by fintechee** [comment]
@YegorZaremba 
Thank you for your reply.
Yes, the web3 seems to regard all transactions with some data as calling of some contract functions.
But sometimes we have needs to send funds to a common address(not a contract address) and attach some reason to make the recipient know what the funds stand for. Right?
So, I think the data field should be reserved for this kind of use case.
Or, any custom data can't be on chain.

**Comment by fintechee** [comment]
The message "TxGasUtil - Trying to call a function on a non-contract address" is returned by the inpage.js of Metamask.
Actually, the transaction is done successfully.
Just the exception "TxGasUtil - Trying to call a function on a non-contract address" was caught by Metamask and thrown to web3.js.
So, I think it's a bug obviously.
And, this is a really necessary feature.
For example, in the case that I need to send ether with attached message, such as a message specifying the beneficiary address(based on another chain that is different from ethereum) to receive some tokens.
Without this feature, how can I do to make the recipient that received the ether trust the beneficiary address?? By sending mail, off chain ???

**Comment by frankiebee** [comment]
This looks like a metamask issue https://github.com/MetaMask/metamask-extension/blob/14d85b133233d5f806480d8896f0c11cafc04a87/app/scripts/controllers/transactions/index.js#L348 closing this issue. Removing that check in metamask should fix your problem

**Comment by fintechee** [comment]
@frankiebee 
But Metamask is an extension, it's impossible to make all the users except me have this updated, right?
I have released another issue in Metamask's repo.
Anyway, thank you a lot for your help.

**Comment by LukeSamkharadze** [comment]
@fintechee are you sure you were calling contract on correct chain?

I just had that problem and the issue was that I was using wrong chain

**Comment by fintechee** [comment]
@LukeSamkharadze
Yes, I was calling the correct chain(testnet).
