### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setInfo' of undefined      does not receive the value given when entering the text does not call the when using web3 

### ISSUE THREAD

**Issue by jhonny-fer** [ethereum/web3.js#3796]
function registerGetInfo() {
    contract.methods.getInfo().call().then( function( info ) { 
      console.log("info: ", info);
      document.getElementById('#lastInfo').innerHTML = info;
    });    
  }
  
  function registerSetInfo() {
   var info = $("#newInfo").val();
    contract.methods.setInfo(info).send( {from: account}).then( function(tx) { 
      console.log("Transaction: ", tx); 
    });
    $("#newInfo").val('');
  }

**Comment by frankiebee** [comment]
Can you provide the actual error and a description of what you are experiencing and a little more context to this code snippet?
