### ISSUE TITLE
documentation is lacking

### ISSUE THREAD

**Issue by zimmah** [ethereum/web3.js#3804]
In usage it simply says:

```
const Web3IpcProvider = require('web3-providers-ipc');
const net = require(net);

const ipc = new Web3IpcProvider('/Users/me/Library/Ethereum/geth.ipc', net);
```

What is '/Users/me/Library/Ethereum/geth.ipc' supposed to mean? Does it imply I need geth already installed?

**Comment by Spacesai1or** [comment]
As per the documentation:

```
Object - IpcProvider: The IPC provider is used node.js dapps when running a local node. Gives the most secure connection.
```

It would seem that an IPC connection should be used when running a local node and the file path you mentioned is to the `geth.ipc` that gets created when setting up a node using Geth

[Here](https://ethereum.stackexchange.com/questions/1492/when-is-the-geth-ipc-file-produced) is some additional information

**Comment by zimmah** [comment]
Ok, thanks, that seems pretty clear. I'll see if I can add that to the documentation
