### ISSUE TITLE
web3.eth.abi.decodeLog throws an error 

### ISSUE THREAD

**Issue by basedalexander** [ethereum/web3.js#3806]
#### Expected behavior
the logs parameters are decoded

#### Actual behavior
when decoding logs in this transaction I get exceptions (logs are in the end). (except receipts.logs[3] is decoded just FINE!!! , it's "data" field string is way bigger: "0x00000000000000000000000000000000000000000006dcac08e5dbcdb7fbe3ff000000000000000000000000000000000000000000000ac093660eee70f4a544" )

#### Steps to reproduce the behavior

```
const web3 = new Web3(new Web3.providers.HttpProvider("url"))
const txAddress = '0xd340d085fd0b6d1e206ac67c2667a45417e372425765f779d4688ef816644a59';
let receipt = await web3.eth.getTransactionReceipt(txAddress);

let logData = receipt.logs[0];

// Contract ABI is taken from here https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2#code

// then I found the matching event signature via web3.eth.abi.encodeEventSignature(...)
let inputs = [
        {
            "indexed": true,
            "name": "dst",
            "type": "address"
        },
        {
            "indexed": false,
            "name": "wad",
            "type": "uint256"
        }
 ];
let hexString = logData.data; // "0x000000000000000000000000000000000000000000000000047b83940ab20763"
let topics = logData.topics; // [ "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c", "0x0000000000000000000000007a250d5630b4cf539739df2c5dacb4c659f2488d" ]

        const decodedFirstLog = web3.eth.abi.decodeLog(
            inputs,
            hexString,
            topics
        );

```

#### Logs

```
        var error = new Error(message);
                    ^

null: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.0.8)
    at Logger.makeError (/Users/thohoh/Projects/whale-following/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/Users/thohoh/Projects/whale-following/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/Users/thohoh/Projects/whale-following/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at Object.hexZeroPad (/Users/thohoh/Projects/whale-following/node_modules/@ethersproject/bytes/lib/index.js:263:16)
```

#### Environment
node v15.2.0
npm v7.0.8
"web3": "^1.3.0
MacOS 10.15.7

**Comment by Spacesai1or** [comment]
Hi there, looking at the [event logs](https://etherscan.io/tx/0xd340d085fd0b6d1e206ac67c2667a45417e372425765f779d4688ef816644a59#eventlog) for the transactions you're retrieving the receipt for (`0xd340d085fd0b6d1e206ac67c2667a45417e372425765f779d4688ef816644a59`), there is no emitted event that contains the data with named properties `dst` and `wad` (which is why you're getting the `out of range` error)

Removing:

```javascript
{
            "indexed": true,
            "name": "dst",
            "type": "address"
        },
```

from your `inputs` array makes `decodeFirstLog` equal:

```javascript
{
            "indexed": true,
            "name": "dst",
            "type": "address"
        },
```

FYI, [here](https://github.com/spacesailor24/web3-3806) is my test repo for these changes

**Comment by Sufiyan-dev** [comment]
> Discussion

Have you solved this error

**Comment by danielj86** [comment]
Following web3js docs

The third parameter in decodeLog method

"topics - Array: An array with the index parameter topics of the log, without the topic[0] if its a non-anonymous event, otherwise with topic[0]."

You should provide an array only with topic[1] as topic[0] is a non-anonymous.
