### ISSUE TITLE
Web3.eth.subscribe syncing no longer works with OpenEthereum nodes

### ISSUE THREAD

**Issue by ytrezq** [ethereum/web3.js#3812]
The reason is simple, Parity dropped support for the `syncing` parameter starting with version it s version s 3.1 along some other apis.

Because of the divest from Paritytech, the issue is likely to remain never fixed.

Should this be fixed by web3 using a workaround?

**Comment by GregTheGreek** [comment]
Closing because this is a client issue, and we shouldn't be making workarounds. They need to follow the spec.

**Comment by ytrezq** [comment]
@GregTheGreek I would rather say the spec was updated after parity 1.8 so that when Openethereum restarted from an old version, it dropped support for that parameter while of course geth doesn t have this problem.

**Comment by ytrezq** [comment]
So please reopen.

**Comment by GregTheGreek** [comment]
Right, so this is an issue with OE. I think you should open an issue there since they are not conforming to the specification.

**Comment by ytrezq** [comment]
@GregTheGreek this is what I did. So please reopen this issue.
