### ISSUE TITLE
Hundreds of XHR Calls (Several per seconds) with web3.eth.sendSignedTransaction() 

### ISSUE THREAD

**Issue by iberthony** [ethereum/web3.js#3819]
Issue: When using web3.eth.sendSignedTransaction()  with or without any event listeners, there are round 753 XHR requests made attempting to get the transaction receipt, 

Same issue with :  
using Simply web3.eth.sendSignedTransaction().then() , web3.eth.sendSignedTransaction().on() or just  web3.eth.sendSignedTransaction()

In this file: node_modules\web3-core-method\lib\index.js

I noticed the exisence of this function:

```
 // start watching for confirmation depending on the support features of the provider
    var startWatching = function (existingReceipt) {
        const startInterval = () => {
            intervalId = setInterval(checkConfirmation.bind(null, existingReceipt, true), 1000);
        };
        if (!this.requestManager.provider.on) {
            startInterval();
        }
        else {
            _ethereumCall.subscribe('newBlockHeaders', function (err, blockHeader, sub) {
                if (err || !blockHeader) {
                    // fall back to polling
                    startInterval();
                }
                else {
                    checkConfirmation(existingReceipt, false, err, blockHeader, sub);
                }
            });
        }
    }.bind(this);
```

Is this the expected behaviour of the web3.eth.sendSignedTransaction() method ?
How can we get around that because when reaching 1,000 requests, the calls are being blocked.

**Comment by krychla1** [comment]
That is very unlucky feature, that can't be skipped as far as I tried. 
Removing listeners or unsubscribing from events have no effect as well. 

It just bombards the existing receipt till its mined - the sooner, the better. It's even more fun once you start replacing transactions (so that the replaced are never mined, but this function continues to check their receipts).

Any other input would be appreciated..

**Comment by sterlu** [comment]
Setting `web3.eth.transactionConfirmationBlocks` to a number lower than the default 24 blocks might be useful. The default behavior checks for confirmations until 24 blocks have included the transaction if I understood correctly. This might not be needed and should make the time web3 is polling for confirmations shorter. 

On a related note, there is an [issue](https://github.com/ChainSafe/web3.js/issues/3797) if the transaction fails (or is rejected) causing the underlying web3 logic to poll indefinitely.

**Comment by playnance-games** [comment]
Hi, someone knows how to overcome this issue?
I'm using web3auth with RPC and the same issue occurs.
