### ISSUE TITLE
1 low severity vulnerability

### ISSUE THREAD

**Issue by zak100** [ethereum/web3.js#3823]
#### Expected behavior
Don't know
#### Actual behavior
$ npm audit fix

up to date, audited 351 packages in 3s

44 packages are looking for funding
  run `npm fund` for details

# npm audit report

web3  *
Insecure Credential Storage - https://npmjs.com/advisories/877
No fix available
node_modules/web3

1 low severity vulnerability

Some issues need review, and may require choosing
a different dependency.

#### Steps to reproduce the behavior

1.$ npm install web3 (which gives this message but asks for audit fix)
2. npm audit fix (which again generates the problem message

#### Logs

no log file generated
#### Environment
Ubuntu 20.04 virtual machine running under ubuntu 18.04
npm@7.0.15 /home/osboxes/.nvm/versions/node/v15.4.0/lib/node_modules/npm
Laptop: amd64bit machine

**Comment by zak100** [comment]
Hi,
Please guide me how to install web3? I am using "npm install web3 " but I am getting one severe vulnerability error.(zulfi6000@yahoo.com)
Zulfi.

**Comment by Zhenyazhd** [comment]
> Hi,
> Please guide me how to install web3? I am using "npm install web3 " but I am getting one severe vulnerability error.([zulfi6000@yahoo.com](mailto:zulfi6000@yahoo.com))
> Zulfi.

Hi, did you solve this problem?? I have the same trouble. No matter what I do, I don't get to solve it...

**Comment by zak100** [comment]
Hi,No I can't solve this problem. I am getting this problem in javscript products.
Zulfi.    On Monday, March 1, 2021, 09:03:43 AM CST, Zhenyazhd <notifications@github.com> wrote:  
 
 



Hi,
Please guide me how to install web3? I am using "npm install web3 " but I am getting one severe vulnerability error.(zulfi6000@yahoo.com)
Zulfi.


Hi, did you solve this problem?? I have the same trouble. No matter what I do, I don't get to solve it...

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention, we'll have to look at whether or not it's possible to update web3.js's dependencies to remove the warning

**Comment by zak100** [comment]
Hi,Thanks a lot. I can't install javascript tools like web3 and chai due to this problem. And now I am getting this problem with Truffle. I don't remember how I installed it.
Zulfi.    On Friday, March 5, 2021, 12:12:07 PM CST, Wyatt Barnes <notifications@github.com> wrote:  
 
 


Thank you for bringing this to our attention, we'll have to look at whether or not it's possible to update web3.js's dependencies to remove the warning

**Comment by Ramsolz666** [comment]
i also have this problem. Maybe i use the old version to operate

**Comment by zak100** [comment]
Hi,I am getting vulnerability in all js tools.
Zulfi.
    On Tuesday, March 23, 2021, 7:37:45 AM CDT, Ramsolz666 ***@***.***> wrote:  
 
 


i also have this problem. Maybe i use the old version to operate

**Comment by DougZaoldyeck** [comment]
Any updates on this? I met the same problem when trying to run "npm install web3"

**Comment by Chinoiserie1** [comment]
I have the same issue when I use npm install -g web3

web3  *
Insecure Credential Storage - https://npmjs.com/advisories/877
No fix available
node_modules/web3

1 low severity vulnerability

Some issues need review, and may require choosing
a different dependency.

**Comment by sonitaaaaa** [comment]
me too

# npm audit report

web3  *
Insecure Credential Storage - https://npmjs.com/advisories/877
No fix available
node_modules/web3

1 low severity vulnerability

Some issues need review, and may require choosing
a different dependency.

**Comment by jdevcs** [comment]
This issue will be fixed with https://github.com/ChainSafe/web3.js/pull/4231 PR, and this issue is duplicate with https://github.com/ChainSafe/web3.js/issues/4225 so closing it.
