### ISSUE TITLE
How to gen mnemonic and restore wallet by mnemonic ?

### ISSUE THREAD

**Issue by suusofttruongnv** [ethereum/web3.js#3827]
How to create mnemonic and restore wallet from mnemonic ?

**Comment by Spacesai1or** [comment]
Web3.js doesn't offer private key generation, however [here](https://ethereum.stackexchange.com/questions/52370/web3-create-account-from-mnemonic-passphrase) seems to be a way to do it using Ethers (although be aware that the entropy used during key generation may not be enough for your needs)

What Web3.js does allow you to do is [importRawKey](https://web3js.readthedocs.io/en/v1.3.0/web3-eth-personal.html#importrawkey) using an already determined private key (in hexidecimal) and the private key password

You can also generate a new account using a provider that has your private key and the [newAccount](https://web3js.readthedocs.io/en/v1.3.0/web3-eth-personal.html#importrawkey) method

**Comment by italoHonoratoSA** [comment]
Web3.js is much more complicated when it comes to handling accounts and extracting private keys through mnemonic.

Check my reviews here:
https://github.com/web3/web3.js/issues/1594#issuecomment-1418483637

Check a solution here:
https://ethereum.stackexchange.com/questions/102090/retrieving-the-private-public-key-with-web3js-for-a-specific-wallet-provided-by
