### ISSUE TITLE
eth methods "not implemented" error

### ISSUE THREAD

**Issue by pawanjay176** [ethereum/web3.js#383]
I'm running a geth rpc instance on port 8545 on my localhost. 
When I try to access any eth method from a node server.js file, I get method not implemented error. 

For e.g, in my node server.js file
```
var Web3 = require("web3");
var web3 = new Web3(new Web3.providers.HttpProvider('http://0.0.0.0:8545'));
var balance = web3.eth.getBalance("0x428e4b53f6038d3ee7d918eb670b038b76b5c67c");
```
I get the following error:
 eth_getBalance method not implemented

**Comment by frozeman** [comment]
According to the docs, if you use `getBalance` you need to pass a callback ;)

**Comment by pawanjay176** [comment]
thank you! :)
