### ISSUE TITLE
The firefox extension disable used 'unsafe-eval' CSP, how I used web3 in extension background

### ISSUE THREAD

**Issue by tdvni** [ethereum/web3.js#3834]
#### Steps to reproduce the behavior

1. I used web3 in my firefox extension background js
2.  in development mode I can defined  'unsafe-eval' CSP in manifest.json but distribution firefox disable this setting.how can I do. ether if have no eval web3 version 

#### Logs

Uncaught EvalError: call to Function() blocked by CSP
    [321]< moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:48320
    o moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    r moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
web3.js:48320:11
    [321]< moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:48320
    o moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    r moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
    <anonymous> moz-extension://63fcb223-62f1-47d4-8dab-1e1318f403af/share/js/web3.js:1
Uncaught ReferenceError: Web3 is not defined
    web3 background.js:10908
    o background.js:1
    js background.js:163
    o background.js:1
    t background.js:1
    <anonymous> background.js:1
    <anonymous> background.js:1
background.js:10908
Content Security Policy: 页面设置阻止读取位于 eval 的一项资源("script-src")。

#### Environment

  - web3 1.3.0 
  - firefox  84.0 
  - window10 x64

**Comment by Spacesai1or** [comment]
Hi there, could you provide a code snippet or test repository for this?
