### ISSUE TITLE
npm install error - installing web3@1.0.0-beta.35

### ISSUE THREAD

**Issue by ahmedeid6842** [ethereum/web3.js#3839]
windows 
node -v 12.16.0

cmd : npm install --save web3@1.0.0-beta.35

error message:

npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

i can't install web3 package

**Comment by GregTheGreek** [comment]
Please install using:
```
npm install --save web3
```

**Comment by wzup** [comment]
@GregTheGreek 

How to deal with `deprecated` packages? After installation I've got 4 warnings about deprecated packages.

```
$ npm i -P web3
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated multicodec@0.5.7: stable api reached
```
