### ISSUE TITLE
[Public Announcement] CLA BUG

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#3846]
When web3.js was transferred to ChainSafe a CLA Bot was automatically added to the repository. We are aware of this, and unfortunately it was overseen when the initial transfer took place. By default ChainSafe repositories have it applied, and because the transfer was treated as a new repository, the CLA Bot was added. By no means what so ever, is the CLA Bot needed on web3.js, and we believe to have removed it as of today, we are still working through to rectify PR's that are sitting stale with the CLA Bot as a required check.

Thank you for bearing with us,

ChainSafe Team <3

**Comment by SGROI-06** [comment]
I love God

**Comment by GregTheGreek** [comment]
This has been resolved.
