### ISSUE TITLE
BN cannot be initialized with a 0x-prefixed hex-string, despite example in docs

### ISSUE THREAD

**Issue by vicnaum** [ethereum/web3.js#3847]
The docs example is here:
https://web3js.readthedocs.io/en/v1.3.1/web3-utils.html#bn

#### Expected behavior
new BN('0xea').toString();
> "234"

#### Actual behavior
new BN('0xea').toString();
> "3450"

#### Environment
Use any web3.utils.BN, for example from Remix console

The docs give an example which is incorrect.

BN cannot be initialized with 0x-prefixed hex-string, only without 0x prefix string, or with non-string 0x literal.

This leads to frustration (that was always there with everything regarding BN) when working with hex numbers.

I believe this should be corrected in docs, or at least this example should be removed, as it's incorrect.
Or maybe just encourage users to use toBN instead (which works correctly).

Or even better - update BN to v5 - which asserts hex for non-hex characters.

Or even more better - maybe I can persuade BN to trim 0x at the start of hex strings :-D

**Comment by cokia** [comment]
PR #3770
I suggested a PR for this, and it is not being merged.

**Comment by vicnaum** [comment]
Found a duplicate (but closed) issue: #3762

**Comment by Spacesai1or** [comment]
Based off of [this](https://github.com/ChainSafe/web3.js/pull/3770#issuecomment-770955247) comment, perhaps I tested this incorrectly - will look it again

Thank you for bringing it to our attention!

**Comment by vicnaum** [comment]
Still not solved
