### ISSUE TITLE
getPastLogs doesn't return events within the given block range

### ISSUE THREAD

**Issue by ppoliani** [ethereum/web3.js#3858]
#### Expected behaviour
I have experienced a somewhat non-deterministic behaviour when using `getPastLogs`. More specifically, I'm using both the `fromBlock` and `toBlock` options, and it happens that sometimes not all events are loaded.

For example,

At block height `11659558` I sent the following request:

```
  const opts = {
    address: contract.options.address,
    topics: [eventInterface.signature],
    fromBlock,
    toBlock
  }

 const results = await inst.web3.eth.getPastLogs(opts)
```

The problem is that most of the time it does return all events in the range `[fromBlock, toBlock]`. However, I have experienced situation where there is an event within the range but the function didn't not return any.

For example, in one occasion I tried to load a specific event in the range `[11659555, 11659558]`. I checked the blockchain explorer and there was one event in block 11659557. However `getPastLogs` returned none.

I'm using Infura as my JSON-RPC node.

#### Actual behavior

Expect to return all events within a range of blocks.

#### Environment

Node V14.7.0
Web3 V1.3.0

**Comment by ppoliani** [comment]
I just did a bit of investigation and I noticed that https://etherscan.io/block/11659558 was mined in 2 secs. So, my assumption is that Infura might not have synced all its nodes and thus the reason why `getPastLogs` didn't. 

However, this is just a theory of mine.

**Comment by Spacesai1or** [comment]
> I just did a bit of investigation and I noticed that https://etherscan.io/block/11659558 was mined in 2 secs. So, my assumption is that Infura might not have synced all its nodes and thus the reason why `getPastLogs` didn't.
> 
> However, this is just a theory of mine.

This does seem to be a possible culprit for your issue. I'm going to close this, but please feel free to re-open it with additional details if you experience the issue with a non-infura provider, or it happens again after giving the infura nodes enough time to sync

Thank you
