### ISSUE TITLE
Passing a large string into methds.call() results in invalid type conversion and out of bounds error

### ISSUE THREAD

**Issue by VexyCats** [ethereum/web3.js#3863]
tokenID: `5347359381416754638292106073567748474581852345025787828513953871505554409252111`

```
export async function getTokenURI(address, tokenID) {
  try {
    console.log(address, typeof tokenID);
    return await getterContract(ABI, address, "tokenURI", [tokenID]);
  } catch (err) {
    console.log(err);
    console.log(address, typeof tokenID);
    return "";
  }
}
export const getterContract = async (ABI, address, methodName, params) => {
  try {
    const contractInstance = await getDeployedContract(ABI, address);

    return await contractInstance.methods[methodName](...params)
      .call()
      .then((res) => {
        return res;
      });
  } catch (e) {
    throw e;
  }
};
```

Calling getTokenURI and passing in the token ID above - the actual value web3 is sending to the contract is: ```0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005347359381416754638292106073567748474581852345025787828513953871505554409252111```

Instead of the correct value of `5347359381416754638292106073567748474581852345025787828513953871505554409252111`

When passing in a smaller value such as `123456` it works fine.

Both values are passed into the function as strings - so not sure why the length of the string matters?

```
Error: value out-of-bounds (argument="tokenId", value="0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000534735938141675463829210607356774847458185234502578782851395387150555440925211", code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153)
    at Logger.makeError (index.ts:205)
    at Logger.throwError (index.ts:217)
    at Logger.throwArgumentError (index.ts:221)
    at NumberCoder._throwError (abstract-coder.js:38)
    at NumberCoder.encode (number.js:23)
    at array.js:41
    at Array.forEach (<anonymous>)
    at pack (array.js:27)
    at TupleCoder.encode (tuple.js:19)
    at AbiCoder.encode (abi-coder.js:82)
    at ABICoder.push../node_modules/web3-eth-abi/lib/index.js.ABICoder.encodeParameters (index.js:121)
    at index.js:439
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (index.js:438)
    at Object._processExecuteArguments (index.js:701)
    at Object._executeMethod (index.js:720)

```

How to fix this issue?

Web3 version:    "web3": "^1.2.11"

**Comment by GregTheGreek** [comment]
Can you try using the latest version of web3.js :)

**Comment by VexyCats** [comment]
Unfortunately I cannot as its on an existing project and upgrading web3 might break everything.... =/

**Comment by GregTheGreek** [comment]
Have you tried? There really shouldn't be anything breaking between the two. When we went from v1.2.11 -> v1.3.x it was more or less because we change the build system and made some minor tweaks but no API changes. Please see the [release](https://github.com/ChainSafe/web3.js/releases/tag/v1.3.0)

**Comment by Spacesai1or** [comment]
Hi there, were you able to upgrade to `1.3.x`?

If not, could you provide the contract you're using, or a test repository?

**Comment by JUGERNAUTUS** [comment]
Facing the same issue while sending tokenID as a parameter. Im using web3 1.3.5
