### ISSUE TITLE
deprecate bzz 

### ISSUE THREAD

**Issue by frankiebee** [ethereum/web3.js#3871]
remove bzz:
- [x] deprecation warning as a console.warn (1.3.4)
- [X] coms of depreciation 
- [ ] removal of package and tests release after warn release (1.3.5)

**Comment by jdevcs** [comment]
`web3.bzz` will not be included in  web3.js **_[4.x](https://github.com/ChainSafe/web3.js/tree/4.x)_** and will not be maintained in 1.x
