### ISSUE TITLE
Wrong type definition for AbiCoder.encodeFunctionCall

### ISSUE THREAD

**Issue by ynaciri** [ethereum/web3.js#3873]
#### Expected behavior

Calling AbiCoder.encodeFunctionCall through web3.eth.abi with array type parameters should work.

#### Actual behavior

Typescript is raising errors because the type definition expects only string parameters values :

```
encodeFunctionCall(abiItem: AbiItem, params: string[]): string;
```

Should instead be :

```
encodeFunctionCall(abiItem: AbiItem, params: (string|string[])[]): string;
```

Or something even more elaborate to support more exotic types.

#### Steps to reproduce the behavior

1. Create a smart contract with a method accepting an array parameter (ex : array of addresses)
2. Encode the contract call with web3.eth.abi.encodeFunctionCall.
3. Typescript reports a compile error

#### Logs

Compilation error message : 
`error TS2322: Type 'string[]' is not assignable to type 'string'.`

#### Environment

Tested with web3 1.3.0 but the definition is the same for 1.3.2 and even on 2.x branch.

**Comment by cokia** [comment]
I think this is a good type modification.
