### ISSUE TITLE
ReferenceError: TruffleContract is not defined after replacing web3.min.js with latest version

### ISSUE THREAD

**Issue by chuacw** [ethereum/web3.js#3881]
I have a working application using Javascript declared in this sequence:
```
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/web3.min.js"></script>
    <script src="./js/truffle-contract.js"></script>
    <script src="./js/admin.js"></script>
```
However, after downloading and replacing web3.min.js from https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js I'm now getting ReferenceError: TruffleContract is not defined in my Javascript console.

EXP: #### No error

ACT: #### Getting: ReferenceError: TruffleContract is not defined in Javascript console.

#### 

[web3.min.js.zip](https://github.com/ChainSafe/web3.js/files/5864156/web3.min.js.zip)

Attached here is the existing web3.min.js that I'm using.
Any ideas what's causing this?

**Comment by GregTheGreek** [comment]
thanks for reporting this, I won't be able to look at your .zip file. Can you confirm you are using `v1.3.3` ?

**Comment by chuacw** [comment]
Yes, I'm using v1.3.3, which was the latest supposedly, with the new Metamask fixes.
The attached zip file in the initial report was the version of web3.min.js I was using before I upgraded to v1.3.3

**Comment by GregTheGreek** [comment]
Can you provide a code snippet ?

**Comment by chuacw** [comment]
Just casting a variable into TruffleContract like so:

TruffleContract(data);

**Comment by GregTheGreek** [comment]
Could you perhaps provide truffle versions as well?

**Comment by chuacw** [comment]
Truffle v5.1.61 (core: 5.1.61)

**Comment by nicholasnadel** [comment]
@chuacw any luck resolving? Same issue here.

**Comment by chuacw** [comment]
@nicholasnadel  Yes, resolved.

Do this:
```
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/web3@1.3.3/dist/web3.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@truffle/contract@4.3.5/dist/truffle-contract.js"></script>

```

**Comment by nicholasnadel** [comment]
> @nicholasnadel Yes, resolved.
> 
> Do this:
> 
> ```
>   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
>   <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
>   <script src="https://cdn.jsdelivr.net/npm/web3@1.3.3/dist/web3.min.js"></script>
>   <script src="https://cdn.jsdelivr.net/npm/@truffle/contract@4.3.5/dist/truffle-contract.js"></script>
> ```

Thanks! @chuacw

**Comment by GregTheGreek** [comment]
Sorry what was the solution?

**Comment by nicholasnadel** [comment]
> Sorry what was the solution?

@GregTheGreek  you can try chuacw's solution above (in your index.html file), or if using MetaMask, try installing their legacy web extension alongside the current version: https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3
