### ISSUE TITLE
MetaMask warning from legacy window.web3 check

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#3887]
https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-requestmanager/src/givenProvider.js#L41

Because of this line, when we load web3.js into the front end code as standalone library, metamask shows a warning and some users get scared. 

![image](https://user-images.githubusercontent.com/9360827/106103274-8a641180-60f5-11eb-836f-550749721596.png)

**Comment by GregTheGreek** [comment]
Hmm I have seen this, but assumed it was because an old version was being used.

L41 should never be hit if you're using the correct version of MetaMask?

**Comment by GregTheGreek** [comment]
Hmm I have seen this, but assumed it was because an old version was being used.

L41 should never be hit if you're using the correct version of MetaMask? 

Will need to look into this further.

**Comment by rstormsf** [comment]
Nope. We use web3.js to make eth_call thru custom RPC url and because web3.js for SOME reason needs to call `window.web3.currentProvider` - metamask flags that the whole Dapp is using deprecated API. Please do something, everyone hates that warning, it forces me to rewrite the whole app into ethers.js because it doesn't do such things.

**Comment by GregTheGreek** [comment]
Do you have a demo app I can see? We have an RC out right now and I can easily add to it if this can be validated on my end

**Comment by rstormsf** [comment]
@GregTheGreek my apologies, I was doing a demo app and saw that it triggers because I used web3@1.2.6 version and version 1.3.3 fixes it.
Now I wonder if I upgrade my dapp to 1.3.3, what would be the breaking changes? 
Feel free to close the issue

**Comment by GregTheGreek** [comment]
There shouldn't be, v1.3.0 did not introduce any breaking changes.

**Comment by GregTheGreek** [comment]
Feel free to open a new issue if you find a problem. Thanks you!
