### ISSUE TITLE
deprecate shh

### ISSUE THREAD

**Issue by frankiebee** [ethereum/web3.js#3888]
remove shh:

- [x] deprecation warning as a console.warn (1.3.4)
- [ ] coms of depreciation
- [ ] removal of package and tests release after warn release (1.3.5)

**Comment by paulmillr** [comment]
Have you heard about SemVer?

**Comment by jdevcs** [comment]
`web3.shh` will not be included in  web3.js **_[4.x](https://github.com/ChainSafe/web3.js/tree/4.x)_** and will not be maintained in 1.x
