### ISSUE TITLE
The method personal_ecRecover does not exist/is not available

### ISSUE THREAD

**Issue by leon-do** [ethereum/web3.js#3911]
#### Expected behavior

`web3.eth.personal.ecRecover("Hello world", "0x30755ed65396facf86c53e6217c52b4daebe72aa4941d89635409de4c9c7f9466d4e9aaec7977f05e923889b33c0d0dd27d7226b6e6f56ce737465c5cfd04be400").then(console.log);
` 
prints address of owner

#### Actual behavior

The method personal_ecRecover does not exist/is not available

#### Steps to reproduce the behavior

1. https://web3js.readthedocs.io/en/v1.3.1/web3-eth-personal.html#ecrecover
2. web3.eth.personal.ecRecover("Hello world", "0x30755ed65396facf86c53e6217c52b4daebe72aa4941d89635409de4c9c7f9466d4e9aaec7977f05e923889b33c0d0dd27d7226b6e6f56ce737465c5cfd04be400").then(console.log);
3. The method personal_ecRecover does not exist/is not available

#### Solution

Move docs from `web3.eth.personal` to `web3.eth.accounts`

working method:

`web3.eth.accounts.recover(rawTx, signedTx);`

I think there's a few more to move. Will verify.

#### Environment

node: v14.15.4
"web3": "^1.3.4"

**Comment by lamberto15** [comment]
oh nice it works for me. the ecrcovery works on browser when using const web3 = new Web3(window.ethereum),
but when use with nodejs, const web3 = new Web3(window.ethereum)  is not working in server thats why ecrecovery not works on server.is all because of the provider.
