### ISSUE TITLE
how I can send to address(0) to "burn"

### ISSUE THREAD

**Issue by zAndrey95** [ethereum/web3.js#3915]
I need to remove delegated tokens.
Using https://ropsten.etherscan.io everything works great.
Using a web application, it gives errors that an incorrect Ethereum address

**Erorr**
`code: -32602
message: "Invalid parameters: must provide an Ethereum address."`

**My code:**

1. First variant

`await DELEGATIES_TOKEN_CONTRACT.methods
       .delegate('0x0000000000000000000000000000000000000000000000000000000000000000')
       .send({
         from: '0x0000000000000000000000000000000000000000000000000000000000000000'
       })
       .on('error', function(error, receipt) {
         console.log('error', error, 'receipt', receipt) //error.message
         setErrorDelegate(error.message)
       })`

2. Second variant

`await DELEGATIES_TOKEN_CONTRACT.methods
       .delegate('0x0000000000000000000000000000000000000000000000000000000000000000')
      call()`

Also tried sending addresses like this:
1. 0x0000000000000000000000000000000000000000000000000000000000000000
2. 0x0000000000000000000000000000000000000000
3. 0x0
4. 0

P.C. Other working methods

web3js - 1.3.1 version

**Comment by Spacesai1or** [comment]
Hi there, thank you for opening an issue!

Could you provide the contracts you're using, or even better a test repository for us to use to debug this?
