### ISSUE TITLE
web3.eth.sign questions

### ISSUE THREAD

**Issue by croqaz** [ethereum/web3.js#392]
Hello,

1. About the new "sign" function: after I sign some data with the private key, how can someone check the signed data using web3 and my Ethereum address? -- or I should send my public key, if so, how can I obtain it?

2. How can I derive from sign, or another function, the parameters necessary for `ecrecover(bytes32, byte, bytes32, bytes32)` from Solidity?
I asked the same question on https://github.com/ethereumjs/ethereumjs-util/issues/20#issuecomment-186223662 ; They have some similar function, but that doesn't seem to work...

**Comment by frozeman** [comment]
@SilentCicero can you comment?

**Comment by croqaz** [comment]
Hi,

I found a solution on this: https://github.com/obscuren/ethmail/blob/master/client/ethmail.js

The full code would be this:

```javascript
function signString(text) {
  /*
  * Sign a string and return (hash, v, r, s) used by ecrecover to regenerate the coinbase address;
  */
  let sha = '0x' + web3.sha3(text);
  let sig = web3.eth.sign(coinbase, sha);
  sig = sig.substr(2, sig.length);
  let r = '0x' + sig.substr(0, 64);
  let s = '0x' + sig.substr(64, 64);
  let v = web3.toDecimal(sig.substr(128, 2)) + 27;
  return {sha, v, r, s};
}
```

Then the contract would be like:

```C
contract Test {
    function check(bytes32 data, uint8 v, bytes32 r, bytes32 s) constant returns(address) {
      return ecrecover(data, v, r, s);
    }
}
```

So you can close this if you want @frozeman ;

**Comment by MrChico** [comment]
@croqaz You can also check out https://github.com/ethereumjs/ethereumjs-util ecrecover function

**Comment by jonnyhsy** [comment]
It seems web3.eth.sign() has different behaviors in different ethereum clients (geth, testrpc, parity)? What I concluded from this [issue](https://github.com/ethereumjs/testrpc/issues/243#issuecomment-296295847) is testrpc and parity would prepend the prefix (''\x19Ethereum Signed Message:\n" + message.length) to message before signing, while geth would sign the original message without prefix.
Could we strength this point in docs?

**Comment by golyalpha** [comment]
MetaMask returns (as far as I can tell) the bare signature (0xe2fa5e02...)
