### ISSUE TITLE
listening to all new transactions related to an account

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [ethereum/web3.js#3921]
Hi. I'm using the following code snippet that is provided in the web3 documentation to listen to new transactions related to an account but it prints nothing.

`var subscription = web3.eth.subscribe('logs', {`
    `address: address,`
    `}, function(error, result){`
    `if (!error)`
    `console.log(result);`
    `})`
    `.on("data", function(log){`
    `console.log(log);`
    `})`
    `.on("changed", function(log){`
   ` });`
what should I do?
I'm using `'wss://mainnet.infura.io/ws/v3/project API key'`

**Comment by Meshugah** [comment]
@spacesailor24 Is this something I could work on/ current progress on this? I need this working.

**Comment by Spacesai1or** [comment]
@Meshugah Yes, you are more than welcome to work on this, and your efforts would be greatly appreciated. Right now our efforts are focused on the rewrite of library (the `4.x` branch), so I'm not sure when we would have the availability to work on this

**Comment by Meshugah** [comment]
Ah okay. Let me know where I could start and if and when I could get a KT.
