### ISSUE TITLE
Error: "gas" is missing exception when gasPrice is 0

### ISSUE THREAD

**Issue by ackhia** [ethereum/web3.js#3925]
I have a Quorum network running which has a gas price of 0. I am trying to send a locally signed transaction to it but Web3 thinks my zero gas price means gas is missing due to [this](https://github.com/ChainSafe/web3.js/blob/e02374e0c97b2b8dccb00ffc0aba6dfa4a81e5d1/packages/web3-eth-accounts/src/index.js#L275) piece of code and throws the exception below. I'm not sure if Quorum is officially supported but I think zero is still a valid gas price so believe this should still be fixed.

#### Expected behavior

Web3 sends a signed translation.

#### Actual behavior

```
Error: "gas" is missing
    _validateTransactionForSigning index.js:218
    signed index.js:126
    signTransaction index.js:206
    promise callback*signTransaction index.js:202
    sendRequest index.js:581
    send index.js:642
    _executeMethod index.js:841
    _callee$ App.vue:21
    Babel 10
    VueJS 15
    <anonymous> main.js:6
    js app.js:1054
    __webpack_require__ app.js:849
    fn app.js:151
    1 app.js:1067
    __webpack_require__ app.js:849
    checkDeferredModules app.js:46
    <anonymous> app.js:925
    <anonymous> app.js:928
```

#### Steps to reproduce the behavior

1. Create a Quorum network
2. Use the following

```js
    let wallet = web3.eth.accounts.wallet.create(1)

    const gasPrice = await web3.eth.getGasPrice(); 
    console.log("gasPrice", gasPrice) // "0"

    const contract = new web3.eth.Contract(simpleStorageJson['abi'], 
      simpleStorageJson['networks']['10']["address"],
      {
        from: wallet[0].address,
        gasPrice
      }
    )

    await contract.methods.set(10).send()
```

#### Logs

None

#### Environment

Web3 version 1.3.4 running in Firefox

**Comment by anuj-upadhyay-2001** [comment]
Has this been fixed already?

**Comment by baughmann** [comment]
@anuj-upadhyay-inferenz Not as of `1.7.5`. Still an issue. Looks like its just been forgotten about. Too much obsession with coins, mining, and public chains and not enough focus on enterprise.
