### ISSUE TITLE
Ethereum web3.js error

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#3926]
I'm trying to install etethereum web3.js API, but it's showing an error about the github url.

C:\user\dell\folder> npm install --save ethereum/web3.js
npm ERR can't install github:ethereum/web3.js#09j0i0dkd0s0s0s088775678n8y86fd: Missing package.

//anyone to help..

**Comment by ackhia** [comment]
Try `npm i web3`

**Comment by ghost** [comment]
Ohh it worked. thanks.
