### ISSUE TITLE
sendTxCallback slices reasonData wrongly

### ISSUE THREAD

**Issue by Elyx0** [ethereum/web3.js#3937]
![Screen Shot 2021-03-07 at 3 55 41 PM](https://user-images.githubusercontent.com/706218/110254536-9b5a3b00-7f5d-11eb-8aa8-04d547408eff.png)

When using `web3.eth.handleRevert = true;` and getting a reverted error, it appears the `reasonData` can 
be truncated wrongly. At the ` reasonData = err.data.substring(10);` step.

Metamask error data is
```
"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094c50543a452d3130310000000000000000000000000000000000000000000000"
```

It then chokes on the decode from `node_modules/web3-eth-abi/node_modules/@ethersproject/abi/lib.esm/abi-coder.js` because it appends its own `0x` so it's now `0xx08...`

![Screen Shot 2021-03-07 at 3 59 07 PM](https://user-images.githubusercontent.com/706218/110254684-1facbe00-7f5e-11eb-92c6-3e71becc633c.png)

But even if I fix manually this hash to be correct in the decode level, it still doesn't decode.

Getting the `index.js:166 Uncaught Error: overflow (fault="overflow", operation="toNumber", value="3963877391197344453575983046348115674221700746820753546331534351508065746944", code=NUMERIC_FAULT, version=bignumber/5.0.14)`

![Screen Shot 2021-03-07 at 4 00 56 PM](https://user-images.githubusercontent.com/706218/110254733-584c9780-7f5e-11eb-80da-2f39534ded49.png)

#### Expected behavior

I get my reason data string.

#### Actual behavior

Boom.

#### Steps to reproduce the behavior

1. web3 1.3.4
2. Metamask 9.1.1
3. `web3.eth.handleRevert = true;`
3. Call a contract with a `require(false,'MY_ERROR_STR')'

#### Environment

node 14.2
npm 6.14
web3 1.3.4

**Comment by koraykoska** [comment]
Do you have a full example?
