### ISSUE TITLE
No error thrown out when using `handleRevert`

### ISSUE THREAD

**Issue by sjkelleyjr** [ethereum/web3.js#3939]
#### Expected behavior
I should see an error object with a `reason` attached to it in the `on('error')` handler.  This reason should contain the reason message in the corresponding `require` from the smart contract.

#### Actual behavior
No error is being thrown out.  Metamask recognizes that the transaction has failed, and eventually I see the errors in the `Logs` section, which I suspect are unrelated.

If I comment out the `handleRevert: true` line in the example below, I can see the error object in the handler, but obviously, can't retrieve the `reason` as it does't exist.

#### Steps to reproduce the behavior

1. deploy a smart contract with a `require(false, "some error message")` line in it at the beginning of a `mintTo` function.
2. send a transaction to it using the following code
```
	const nftContract = new web3.eth.Contract(
		NFT_ABI,
		NFT_CONTRACT_ADDRESS,
		{ 
                    gasLimit: "1000000", 
                    handleRevert: true 
                }
	);

	console.log('minting ' + imageUrl + ' to: ' + window.account)
	const result = await nftContract.methods
		.mintTo( imageUrl, window.account )
                .send({ from: window.account  })
                .on('error', (error) => {
                    console.log(error)
                 })
```

#### Logs

```
inpage.js:1 MetaMask - RPC Error: BlockReEmitMiddleware - retries exhausted {code: -32603, message: "BlockReEmitMiddleware - retries exhausted", data: {…}}...
web3.min.js:8 Uncaught TypeError: o.data.substring is not a function
```

#### Environment

OS: Mac
device: Macbook Pro
web3.js: [latest minified version](https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js)

Note that this code is running inside the browser after having been injected by a Chrome extension.  Everything works fine using this approach, so I don't expect it to be the cause of any issues, but given it's probably not the typical use case I figured I'd add this info just in case.

**Comment by sjkelleyjr** [comment]
Just realized this is likely the same root cause as [this issue](https://github.com/ChainSafe/web3.js/issues/3742) feel free to resolve this one if that is the case.

**Comment by koraykoska** [comment]
@frankiebee 
Is there a quick fix to that for 1.x?

**Comment by RobertoDonPedro** [comment]
Same issue here with:
Web3 version: 1.3.5
web3.eth.handleRevert = true;

The transaction fails due to revert as expected, but web3 does not catch any errors. Instead I get this javascript error.
`inpage.js:1 MetaMask - RPC Error: BlockReEmitMiddleware - retries exhausted 
Object
code: -32603
data: {originalError: {…}}
message: "BlockReEmitMiddleware - retries exhausted"
__proto__: Object`

Is there a fix or workaraoud available yet?

**Comment by sirmonin** [comment]
I am currently facing similar issue, but with Infura as provider. I was tracking down what could have gone wrong, and eventually found some interesting stuff in `web3-core-method@1.3.5` lib, by adding logs:

![image](https://user-images.githubusercontent.com/26631031/118852584-93aeff00-b8db-11eb-9787-ca4992f15a96.png)

![image](https://user-images.githubusercontent.com/26631031/118852607-99a4e000-b8db-11eb-9d94-79c627224eda.png)

In my case, revert reason is located in `err.message`, which is not considered a revert reason source in `web3-core-method` lib.

**Comment by laygir** [comment]
I am having same issues here.

Been trying to get the revert reason of a `send` call on my contract but the error object does not include the `revertReason` field. I did try both `web3.eth.Contract.handleRevert = true;` and `web3.eth.handleRevert = true;` 

if I call `call`  on the contract method I get the revertReason but not on a `send` call.

**Comment by Github-help** [comment]
#4712 #4786 #4769

**Comment by Github-help** [comment]
#4712
