### ISSUE TITLE
Are there any issues with installing the current version of web3?

### ISSUE THREAD

**Issue by ftppro** [ethereum/web3.js#3942]
I am getting ready to install the current version of web3 on a machine with CentOS v.7.8, 64 bit, and npm 6.14.11.

In the past, the web3 installation had some problems. Are there any issues with using the following command to install the current version of web3?
**npm install web3**

1. Does that command install web3 globally, or do I need to add a command for a global installation (so it will work with all domains on my server).
2. Do I need to make any directory current before typing "npm install web3"?
3. Does the default web3 installation include the features of ethereumjs-tx.js, or do I have to install something else?

Thanks!

**Comment by koraykoska** [comment]
This shouldn't be an issue. If you face any please let us know.
