### ISSUE TITLE
Request: expose .signature function

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#395]
https://github.com/ethereum/web3.js/blob/29e3efb8d88d41e1a7ef0fdfba0d652b503d63e0/lib/web3/function.js#L79-L81

I need access to the signature function. Could you expose it?

**Comment by frozeman** [comment]
We will expose those functions with the reform of web3.js

**Comment by aakilfernandes** [comment]
@frozeman sounds good. Any eta on that? Even a rough one? Wondering if I should fork in the meantime since its a showstopper

**Comment by frozeman** [comment]
Why fork? why you don't simply add this function to your own js? its not hard:
simply: https://github.com/ethereum/web3.js/blob/master/lib/utils/utils.js#L180-L194 and then https://github.com/ethereum/web3.js/blob/master/lib/web3/function.js#L79-L81

Concerning time frame, like 1-2 months? as there is the geth dependency for the web3 1.0 release

**Comment by aakilfernandes** [comment]
Ah good point. I'll just use a utility function.

**Comment by frozeman** [comment]
Its now exposed see: http://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#encodefunctionsignature
