### ISSUE TITLE
web3 callback on transaction receipt?

### ISSUE THREAD

**Issue by praveennagpal** [ethereum/web3.js#397]
The callback on getTransactionReceipt (txHash) returns a null receipt for pending transactions which have a hash number. How can I check within javascript to ensure that the transaction has been mined and then obtain a receipt when a send transaction is invoked. Is there any api with a callback which can inform that the transaction receipt is generated post mining. The callback for contract creation works ok when we check on the contract.address so is there anything similar for send transaction

**Comment by frozeman** [comment]
No this doesn't exists yet, you would have to add a `web3.eth.filter('latest', func)` and check for the next x blocks the receipt.
