### ISSUE TITLE
Utilize BigInts, drop bn.js and biginteger libraries

### ISSUE THREAD

**Issue by paulmillr** [ethereum/web3.js#3972]
If you're rewriting the library, I think it makes sense to switch to built-in JS Big ints. Every major browser and node version supports it. Folks who want to support older browsers can use older web3.

Switching to native bigints has several benefits:

1. Less security vulnerabilities: Any 3rd-party dep could get hacked and backdoored.
2. Performance. It's faster than bn.js.
3. Package size. Massively reduces it.

**Comment by Spacesai1or** [comment]
Hey there, thank you for bringing this to our attention, it's certainly a great idea!

@frankiebee @koraykoska How do y'all fell about this?

**Comment by paulmillr** [comment]
Example of such improvement: i've made cryptographic libraries that utilize bigints and have no dependencies. Example: [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1), a curve, that is used in ETH & [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381) for ETH2.

**Comment by paulmillr** [comment]
Mistake.

**Comment by philknows** [comment]
4.x will be supporting BigInts.
