### ISSUE TITLE
npm install web3   error

### ISSUE THREAD

**Issue by wjl8** [ethereum/web3.js#3975]
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit  git+https://github.com/frozeman/bignumber.js-nolookahead.git resetting remote /home/ubuntu/.npm/_git-remotes/git-https-github-com-frozeman-bignumber-js-nolookahead-git-18eea52a because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm WARN deprecated multicodec@0.5.7: stable api reached
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
loadDep:setimmediate → 30 
WARN engine secp256k1@4.0.2: wanted: {"node":">=10.0.0"} (current: {"node":"8.10loadDep:setimmediate → ad 
WARN engine keccak@3.0.1: wanted: {"node":">=10.0.0"} (current: {"node":"8.10.0"npm ERR! Linux 5.4.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "web3@^0.20.0"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

**Comment by GregTheGreek** [comment]
This is not enough information, can you please provide the commands you used to install this, the web3js & nodejs version and any other relevant information.

**Comment by adriandelgg** [comment]
If you're on Linux, make sure to do 

`$ sudo npm install web3`

**Comment by alexthehurst** [comment]
This error is telling you that the dependencies require Node version 10.0.0 or above, but you're running version 8.10. To fix, you can upgrade to a newer version of Node.

`WARN engine secp256k1@4.0.2: wanted: {"node":">=10.0.0"} (current: {"node":"8.10loadDep:setimmediate → ad`
