### ISSUE TITLE
Unsubscring Using Subscription ID

### ISSUE THREAD

**Issue by bkr32** [ethereum/web3.js#4007]
In the docs https://web3js.readthedocs.io/en/v1.3.4/web3-eth-subscribe.html#subscribe
a return of the subscribe function is `subscribtion.id` , the docs mentions as follows
```
subscription.id: The subscription id, used to identify and unsubscribing the subscription.
```
however i have been unable to find any information relating to the same.

How can `subscription.id` be used to unsubscribe a subscription

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention, at first glance it does seem like `subscription.id` is unused, as `unsubscribe` exists as a method on the subscription instance. I do not have the availability to confirm this, but someone from our team might

**Comment by bkr32** [comment]
@spacesailor24 after hours of pondering, I came to realize that the `subscription.id` is only used when calling `unsubscribe` directly to the intended subscription, I'm not quite sure if this is a intended behavior or if `subscription.id` actually was intended to be called to unsubscribe a subscription ie `unsubscribe(subscription.id)` or similar

**Comment by GregTheGreek** [comment]
@bkr32 Is this still an issue?

**Comment by bkr32** [comment]
@GregTheGreek if it is at all possible to call `unsubscribe` using the `subscription.id` it'd be great, however if this is `unsubscribe's` intended behaviour that's fine as well, just hope it can be clearified in the docs since i was under the impression that there's a method in which we can pass said `id` to unsubscribe
