### ISSUE TITLE
RequestManager.prototype.poll not throwing any exceptions while connection errors

### ISSUE THREAD

**Issue by anton44eg** [ethereum/web3.js#401]
Maybe we should throw error [here](https://github.com/ethereum/web3.js/blob/0ae82cf895b74b264d309d21feecbf3645713d0b/lib/web3/requestmanager.js#L234) ?

**Comment by frozeman** [comment]
This will be reworked anyway. Thanks

**Comment by frozeman** [comment]
Or basically already is: https://github.com/ethereum/web3.js/pull/379

**Comment by anton44eg** [comment]
great! thanks
