### ISSUE TITLE
How get new transactionHash after sped up trx

### ISSUE THREAD

**Issue by StKostyantin** [ethereum/web3.js#4011]
If you use the code like this, you can get data about the accelerated transaction

```
method(...args).send({
        gasPrice,
        ...options,
      })
      .on('transactionHash', (hash: string) => {
        console.log('transactionHash', hash);
      });
      .on('confirmation', (confirmationNumber: number, receipt: TransactionReceipt) => {
        console.log('confirmationNumber', confirmationNumber);
        console.log('confirmation receipt', receipt);
      });
```

But this code I can not control(use with react-query and etc)

I need something like that 

```
useMutation(() => method(...args).send(options))
```

that is, I need the promise to work, but since the hash has changed - the promise (contract context) has changed.
My question is - how do I get the new hash? 

or what context to transfer to emitters? 
Because if you wrap "send" in a promise, then when the hash changes, the context changes and you get an eternal wait

Like this:
```
useMutation(() => method(...args).send({
        gasPrice,
        ...options,
      })
      .on('transactionHash', (hash: string) => {
        console.log('transactionHash', hash);
      });
      .on('receipt', (receipt: TransactionReceipt) => {
        console.log('confirmation receipt', receipt);
      }))
```

**Comment by Spacesai1or** [comment]
Thank you for making us aware of this issue! Right now our team is focused on rewriting the library (`4.x`), so we may not have the ability to work on this currently. You're welcome to try and add this feature yourself though!

**Comment by GregTheGreek** [comment]
There is an active [EIP-2831](https://eips.ethereum.org/EIPS/eip-2831) and unfortunately we have to wait for other wallets to implement it.

Your only other solution is to poll for the transaction
