### ISSUE TITLE
Events aren't fired

### ISSUE THREAD

**Issue by gen4sp** [ethereum/web3.js#4017]
#### Expected behavior
I work with a standard ERC-721 contract. And after I mint a new token I do expect an event `Transfer` fired.

#### Actual behavior
Contract works fine if I call the mint method via remix. My node.js script is also run fine, but no any events fired. 
I've tried getPastEvents, allEvents and usual subscriptions  - nothing. 

What could be wrong?

Web3, WS, Geth, Ropsten
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by GregTheGreek** [comment]
What network did you fire this off to? Do you have any reproducible scripts you can share?

**Comment by gen4sp** [comment]
> What network did you fire this off to? Do you have any reproducible scripts you can share?

I've tried Ropsten and Rinkeby - same results.


```
  async mintSigned(receiver, sender) {
        const encoded = instance.methods.mint(receiver).encodeABI()
        const gasPrice = await web3.eth.getGasPrice()
        const gasEstimate = await instance.methods
            .mint(receiver)
            .estimateGas({ from: sender })
        const tx = {
            to: CONTRACT_ADDR,
            from: sender,
            data: encoded,
            gasPrice,
            gas: Math.round(gasEstimate * 10),
        }

        return web3.eth.accounts
            .signTransaction(tx, WALLET_KEY)
            .then((signed) => {
                return web3.eth
                    .sendSignedTransaction(signed.rawTransaction)
                    .on('transactionHash', function (hash) {
                        console.log('transactionHash', hash)
                    })
                    .on('Transfer', function (hash) {
                        console.log('Transfer', hash)
                    })
                    .on('receipt', function (receipt) {
                        console.log('receipt', receipt)
                        instance.getPastEvents(
                            'Transfer',
                            {
                                fromBlock: 0,
                                toBlock: 'latest',
                            },
                            (a, b) => {
                                console.log('PAST events ', a, b)
                            }
                        )
                    })

            })
    }
```

**Comment by gen4sp** [comment]
any ideas?

**Comment by xiangma9712** [comment]
Mint function is not fully standardized, although the EIP requires to emit Transfer event when NFTs are created/destroyed.

I suppose you'd better check implementation of the contract you use.

Or...
from log of transaction receipt you can check events emitted within the transaction. Isn't there any log?

**Comment by gen4sp** [comment]
sorry for the false alarm - it was wrong contract address
