### ISSUE TITLE
Would like to execute only sendSignedTransaction without getTransactionReceipt

### ISSUE THREAD

**Issue by usd-yamazaki** [ethereum/web3.js#4034]
Reopen #3204.

> I am running a lot of sendSignedTransaction to measure the performance of private ethereum.
> However, because sendSignedTransaction automatically calls getTransactionReceipt, it puts extra load on the node.
> For the tests I want to do, getTransactionReceipt need only be executed once at the end.
> So, could you give sendSignedTransaction an option not to execute getTransactionReceipt?

This is something you can do with web3.py and not with web.js.

**Comment by Spacesai1or** [comment]
Thank you for requesting this feature, I do agree that this would be helpful in your benchmarking, however, the team's focus right now is on the rewrite and security vulnerabilities. We might have the availability to implement this, but you're also welcome to try and implement it yourself :)

**Comment by usd-yamazaki** [comment]
bump

**Comment by usd-yamazaki** [comment]
bump

**Comment by Spacesai1or** [comment]
Perhaps you can make use of [send](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-requestmanager/src/index.js#L166) and [eth_sendRawTransaction](https://eth.wiki/json-rpc/API#eth_sendTransaction) until the rewrite is done:

```javascript
web3.currentProvider.send({
    method: 'eth_sendRawTransaction',
    params: [rawSignedTxData],
    jsonrpc: "2.0",
}, (error, result) => { ... });
```

**Comment by usd-yamazaki** [comment]
@spacesailor24 
Thanks for the great idea. I'll give it a try.
