### ISSUE TITLE
Request: ecrecover

### ISSUE THREAD

**Issue by MrChico** [ethereum/web3.js#404]
Since we have web3.eth.sign, I'm thinking that it would only make sense to also have ecrecover.

**Comment by frozeman** [comment]
This would need to be added to the node as RPC API. Makes probably sense, though we want to move away from singing inside the node.

I plan to add signing and account generation functionality to web3 directly, so we could add this then

**Comment by MrChico** [comment]
But ecrecover can be done without access to the accounts, so we wouldn't need access to the node?

**Comment by izqui** [comment]
Hi! What is the status of this? 

It seems that web3.eth.sign is broken since this https://github.com/ethereum/go-ethereum/pull/2940 ot merged into geth.

Would a PR implementing 'personal_sign' and 'personal_recover' be welcomed?

**Comment by izqui** [comment]
Big problem is that the current sign is now non-deterministic, which is no good.

<img width="950" alt="2016-12-15 at 9 06 17 pm" src="https://cloud.githubusercontent.com/assets/447328/21240221/a418aa4c-c30a-11e6-8ca6-0751e7126859.png">

**Comment by frozeman** [comment]
We have that now: http://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#recover
