### ISSUE TITLE
[Rewrite] Implement Polling for web3-providers-http

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4046]
`web3-providers-http` should implement a `subscribe` method from `IWeb3Provider` and use polling to provide similar functionality. 

- Consider adding argurments:
    - `interval`: sets how often (in second) a request is made
    - ~`maxNumberRequests`: sets how many total requests will be made before polling terminates itself~ Mover to #4111

**Comment by Ricardo11v** [comment]
Hola

**Comment by ohadgk** [comment]
Hello any update on this idea?
I saw it marked as completed but im getting this error:

```
SubscriptionError: The current provider does not support subscriptions
```
