### ISSUE TITLE
undocumented behavior of contract-send:

### ISSUE THREAD

**Issue by exx8** [ethereum/web3.js#4052]
I am using contract-send:
https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-send
And I was to pass the nonce parameter in the options, and it actually works.
Maybe the docs are out to date?

example code:
```
	let contract= new web3.eth.Contract(
	BinaryOption.abi,
	//deployedNetwork.address
	);
	const nonce=await web3.eth.getTransactionCount(address);
	contract=await contract.deploy({data: BinaryOption.bytecode})
	.send({from: address, gas: 12487782, gasPrice: '20000000000',nonce});
```
Types are also missing.

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention!

**Comment by exx8** [comment]
Ping?

**Comment by luu-alex** [comment]
Thank you for this issue, your changes have been merged :D
