### ISSUE TITLE
eth_createAccessList Support

### ISSUE THREAD

**Issue by AusIV** [ethereum/web3.js#4081]
With the Berlin hard fork, access lists were added to offset some of the gas costs introduced with EIP-2929.

Geth supports eth_createAccessList to generate the input to transactions.

I have a contract that is currently broken by EIP-2929 (which I realize is not a web3.js problem), and while eth_createAccessList would resolve our problem, there's not an easy way to use it in the context of web3.js.

It would be great to have web3.js explicitly support eth_createAccessList, but if somebody has a guide on how to use eth_createAccessList with web3.js without explicit support that would be most welcome.

**Comment by GregTheGreek** [comment]
Hey @AusIV thanks for the suggestion, we were running into some weird issues with Berlin, but think we've got most of it sorted out. We can definitely look into adding this as an rpc method!

**Comment by GregTheGreek** [comment]
Realising there is very little documentation surround this call.. looking into it, but not sure if it will be included in the next release

**Comment by GregTheGreek** [comment]
Tracking Open RPC addition https://github.com/ethereum/eth1.0-specs/pull/196

**Comment by AusIV** [comment]
It's probably worth calling out that in my mind this would ideally be something along the lines of:

```
request = contract.methods.myMethod(some, parameters)
request.createAccessList({from: myAddress}).then((access_list) => {
  request.send({from: myAddress, access_list: access_list});
}) 
```

Not just a simple exposure of:

```
web3.eth.createAccessList()
```

(I'm also not sure if it's possible to send an access list through `request.send()` in the current implementation.)

**Comment by AusIV** [comment]
I'd hate to see this go stale. Any prospects on this?

**Comment by Spacesai1or** [comment]
Hey there @AusIV, just wanted to let you know that I'm currently looking into this to gauge the feasibility of implementing what you've requested

**Comment by Lucienest** [comment]
Any update on this? it's been a while.
