### ISSUE TITLE
Error while transfering tokens

### ISSUE THREAD

**Issue by shivam0110** [ethereum/web3.js#4089]
## I am trying to transfer some tokens, using the following code:

    const contract = new web3.eth.Contract(ABI,token_contract_address);

    const data = contract.methods.transfer(to, req.body.value).encodeABI();

    const rawTransaction = {
		'from': from,
		'nonce': web3.utils.toHex(web3.eth.getTransactionCount(from)),
		'gasPrice': 1,
		'gasLimit': req.body.gas,
		'to': token_contract_address,
		'value': 0,
		'data': data,
		'chainId': web3.utils.toHex(web3url[0].chainid)
	};

    const privateKey = new Buffer.from(req.body.PrivateKey, 'hex');
    const tx = new Tx(rawTransaction);
    tx.sign(privateKey);

    const serializedTx = tx.serialize();
	web3.eth.sendSignedTransaction(('0x' + serializedTx.toString('hex')),req.body.PrivateKey) 

    // const signed = await web3.eth.accounts.signTransaction(rawTransaction, req.body.PrivateKey);
    // web3.eth.sendSignedTransaction(signed.rawTransaction)
    .then(function (result) {
        res.statusCode = 200;
        res.setHeader('Content-Type', 'application/json');
        res.json(result*decimals);
        console.log(result);
    })
    .catch((err) => next(err));

#### Expected behavior

Returns a transaction receipt 

#### Actual behavior

but I keep getting the following error:

Getting the Following error:
Returned error: only replay-protected (EIP-155) transactions allowed over RPC
Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC
    at Object.ErrorResponse (D:\ME\Internship\Adigos\ETH api\node_modules\web3-core-helpers\lib\errors.js:28:19)
    at D:\ME\Internship\Adigos\ETH api\node_modules\web3-core-requestmanager\lib\index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (D:\ME\Internship\Adigos\ETH api\node_modules\web3-providers-http\lib\index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (D:\ME\Internship\Adigos\ETH api\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (D:\ME\Internship\Adigos\ETH api\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (D:\ME\Internship\Adigos\ETH api\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (D:\ME\Internship\Adigos\ETH api\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Also note I have already added chainId in rawTransaction.

web3 version - 1.3.6

**Comment by luu-alex** [comment]
Looking at the actual behavior, I see that you are getting an EIP-155 error. Can you console log the chainId and verify that the chainID you are using is the intended chainId?

**Comment by shivam0110** [comment]
Yes the chain ID was correct apparently there was some problem with the Ethereum node that I was working on, in the code above the commented lines are working so the final code becomes

```
 const contract = new web3.eth.Contract(ABI,token_contract_address);

        const data = contract.methods.transfer(to, req.body.value).encodeABI();

        const rawTransaction = {
            from: from,
            gasLimit: req.body.gas, 
            to: token_contract_address,
            value: 0,
            data: data,
            chainId: web3.utils.toHex(web3url[0].chainid)
        };

        const signed = await web3.eth.accounts.signTransaction(rawTransaction, PrivateKey);
        web3.eth.sendSignedTransaction(signed.rawTransaction)
        .then(function (result) {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'application/json');
            res.json(result);
            console.log(result);
        })
        .catch((err) => next(err)); 
```
