### ISSUE TITLE
Listening to all transactions related to an account

### ISSUE THREAD

**Issue by Meshugah** [ethereum/web3.js#4091]
@spacesailor24 Wanted to ask anything has been done about this? I've run into the same issue and the original one has been marked stale(listening to all new transactions related to an account **#3921**).

> Original post: Hi. I'm using the following code snippet that is provided in the web3 documentation to listen to new transactions related to an account but it prints nothing.
> 
> var subscription = web3.eth.subscribe('logs', {
> address: address,
> }, function(error, result){
> if (!error)
> console.log(result);
> })
> .on("data", function(log){
> console.log(log);
> })
> .on("changed", function(log){
> });
> what should I do?
> I'm using 'wss://mainnet.infura.io/ws/v3/project API key'

**Comment by Meshugah** [comment]
https://github.com/ChainSafe/web3.js/blob/5d027191c5cb7ffbcd44083528bdab19b4e14744/packages/web3-core-subscriptions/src/subscription.js#L260

Is this relevant? 

@karalabe 

I'd like to work on it if it is. Some direction would help.

**Comment by Spacesai1or** [comment]
Closing and reopening original issue

@Meshugah I don't believe that code to be relevant, as the issue seems be subscribing to new logs
