### ISSUE TITLE
Remove eth-lib

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#4095]
[eth-lib](https://github.com/maiavictor/eth-lib#readme) has not been maintained or quite sometime now, and I believe that the ethereumjs [monorepo](https://github.com/ethereumjs/ethereumjs-monorepo) should contain everything we need.

**Comment by akshatamohanty** [comment]
I'd like to work on this if it's up for grabs?

Created a WIP [PR](https://github.com/ChainSafe/web3.js/pull/4101). Getting stuck finding the equivalent of `account` in `ethereumjs-utils` though. How do I go about that?
