### ISSUE TITLE
[Rewrite] Update linter git hook to only error/warn and run pre-push

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4099]
Currently the git hook runs pre-commit, and will write the linter changes to the file, meaning the dev's commit is usually successful, but without linter fixes. The dev then has to make a second commit to include linter fixes

Instead, `yarn lint:check` should run only before a push, and would provide the dev linter errors, so that the hook aborts the push until the linter is satisfied (by running `yarn lint`)

**Comment by rbrishabh** [comment]
Hey! I can help with this :)

**Comment by rbrishabh** [comment]
Okay, two questions!
1. Could you please point me to the pre-commit hook file that we're currently using?
2. If I add the check before a push, the dev would still have two commits before they can push their changes. Is this the intended flow?

Thank you!

**Comment by Spacesai1or** [comment]
Closed by #4127
