### ISSUE TITLE
Incorrect handling of web3.toHex for bignumber decimals

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#410]
```
web3.toHex(web3.toBigNumber(1.1))
"0x1.19999999999999999999"
```

Not sure what the best way to handle is. Maybe throw an error?

**Comment by niran** [comment]
I think I hit a side-effect of this bug: passing a fractional wei value to send in a transaction ends up sending 1/16th of the amount. Rounding the value first fixes it. Throwing an error would be nice since fractional hex values never make sense in the context of web3.

**Comment by frozeman** [comment]
web3.js 1.0 works differently, as we don't expose big number objects anymore if thats still an issue, please reopen.
