### ISSUE TITLE
Websocket 403 on browser

### ISSUE THREAD

**Issue by MartinCarniello** [ethereum/web3.js#4102]
I've got a 403 error when I'm trying to connect to websocket provider. I'm using etherjs library on client side (electron frontend application).

`browser.js:25 WebSocket connection to 'wss://bsc.getblock.io/testnet/?api_key=<api_key>' failed: Error during WebSocket handshake: Unexpected response code: 403`

**Request headers:**
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Cache-Control: no-cache
Connection: Upgrade
Host: bsc.getblock.io
Origin: file://
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: RthSzB85Q6Wf2siJukA/Xw==
Sec-WebSocket-Protocol: echo-protocol
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.60 Electron/11.0.1 Safari/537.36

Is this library prepared to be used on frontend side on a browser/electron application?

**Comment by luu-alex** [comment]
Hi, can you double check you are using a working websocket connection?
