### ISSUE TITLE
throws should return an Error and not swallow lower level errors

### ISSUE THREAD

**Issue by barkthins** [ethereum/web3.js#411]
from:   [StackExchange](http://ethereum.stackexchange.com/questions/2069/why-does-web3-js-throw-anonymous-errors-and-swallow-errors)

These items throw an anonymous error, no stack trace so it's hard to debug.  For example if you don't set an account in ether-pudding when calling a contract `new()` you get an 'invalid address' error and you don't know where it came from.

some examples:

```
./node_modules/web3/lib/web3/formatters.js:    throw 'invalid address';
./node_modules/web3/dist/web3-light.js:    throw 'invalid address';
./node_modules/web3/dist/web3.js:    throw 'invalid address';
```

In a (possibly separate issue) you swallow XML errors in HTTP provider, so it's nearly impossible to debug what's going on if the `XMLHttprrequest.js`  library you are using has an error.  For example if you are low on memory and run in synchronous mode, the XML library you are using performs a spawn which can run out of memory, generating an error, which gets swallowed by web3.js, leaving it very difficult to debug.

for example, if request.send is called and `XMLHttpRequest` has an error, it won't be debuggable:

```
HttpProvider.prototype.send = function (payload) {
    var request = this.prepareRequest(false);

    try {
        request.send(JSON.stringify(payload));
    } catch(error) {
        throw errors.InvalidConnection(this.host);
    }
```

from lib/XMLHttpRequest.js, line 620:  `spawn(process.argv[0], ["-e", execString]);`, which uses a lot of memory.

I did not find all the places web3.js throws.  There's probably more than the above.

Here's some best practices notes on throw in javascript.  I note that I get a warning when I attempt to throw with a just a string from nodejs.  It would appear that best practices are to use Error()

[Browser](https://www.nczonline.net/blog/2009/03/03/the-art-of-throwing-javascript-errors/)
[general](http://stackoverflow.com/questions/11502052/throwing-strings-instead-of-errors):

**Comment by frozeman** [comment]
We should have better error reporting in web3.js 1.0, please reopen if its still an issue.
