### ISSUE TITLE
Inefficiency in submitting multiple transactions in bulk (idea for improvement)

### ISSUE THREAD

**Issue by Viserius** [ethereum/web3.js#4110]
(The issue I encountered is also described by #3204 and #4034, but these issues request for a specific feature. This issue highlights the problem more irrespective of the feature request there).

When submitting multiple transactions, let's say a 100, 500 or 1000, Web3.js opens a new subscription for block headers at a node for **every** submitted transaction. So in reality, if we submit 100 transactions at block B, and they are all included at block B+30, block headers are received through the subscriptions for all 30 blocks, for every transaction, thus, 30*100=3.000 times. To stress this, it means that the network/communication overhead is a lot more than required (in this case 100x as high if we send 100 txs).

To resolve this, the component for submitting a transaction and waiting for its reply should be refactored. This should follow a singleton pattern, such that it does not matter if we send 1 or a million transactions, the client always receives the same block header only once (instead of once per submitted tx). This likely requires one to keep track of multiple transactions we are waiting for a reply from, and if no reply is received for all of them (and the reply-waiting-queue is empty), the subscription should be closed until a new transaction is submitted.

To highlight the magnitude of the inefficiency, sending 50.000 transactions to a node for which transactions have to wait for about 50 blocks results in 10GB of outgoing network traffic. When the waiting time is close to 1 block, this is about 200MB for the same amount of transactions.

**Comment by GregTheGreek** [comment]
This makes a lot of sense! Thank you for reporting this.

Since the majority of our work is getting the 4.x branch out the door I think it makes most sense to implement this there!

**Comment by mconnelly8** [comment]
Closing this, but tracking something similar with #5521
