### ISSUE TITLE
Invalid Hex value : web3.utils

### ISSUE THREAD

**Issue by rac-sri** [ethereum/web3.js#4113]
Based on the discussion here: https://forum.openzeppelin.com/t/low-level-delegate-call-failed-eip1967/10650
#### Expected behavior
The output should be 0x for an empty string.

#### Actual behavior
Returns  0x00. 0x00 is an array of 1 byte.

#### Steps to reproduce the behavior

Truffle Test:

```
console.log(web3.utils.asciiToHex(""));
```

#### Logs

```
0x00
```

#### Environment

- Truffle
- Ubuntu 20.4
- Web3
- Ganache

**Comment by kalikho** [comment]
web3.utils.asciiToHex("") returns the hex representation of  input as a string.  The hex representation of an empty string or NULL is 0x00. Simply 0x is not a valid representation.

Reference: 
http://www.asciitable.com/
