### ISSUE TITLE
Solidity formatter: formatOutputInt return positive number for negative value

### ISSUE THREAD

**Issue by djhi** [ethereum/web3.js#414]
In `lib/solidity/formatters.js`, the `formatOutputInt` function does detect negative values from param. However, it return a positive number after [L136](https://github.com/ethereum/web3.js/blob/master/lib/solidity/formatters.js#L136).

**Comment by frozeman** [comment]
I dint look into this part yet, but i assume this wanted to return a twos complement, not sure how though..
If you have a good fix, we will be happy to look at a PR.

I would look into this part a bit into the future from now. Im very busy with other stuff.

**Comment by djhi** [comment]
Sorry, the function does return the correct value. We just misunderstood that it returns a BigNumber and that we needed to use its `toNumber` method to work with it.
