### ISSUE TITLE
Web3 with Electron + hot reload crash my Devtools (and my app)

### ISSUE THREAD

**Issue by SimonR-Nano** [ethereum/web3.js#4153]
Hey,

I just found a little problem with web3 in Electron.

In fact, in my Electron project I installed a hot reload, like https://github.com/sindresorhus/electron-reloader
and everytime I save my file to reload my view/code my devtools crash:

![image](https://user-images.githubusercontent.com/6979203/123323611-0a23ca00-d536-11eb-9bbe-41f4bd241d85.png)

AND my app. Nothing works, i need to stop and recompile.

I got this warning too:
`(node:5916) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron --trace-deprecation ...` to show where the warning was created)
`

If I delete web3 all my app works perfectly, so I don't know what web3 does, but with "ethers" i don't have any problem.

Steps to reproduce:
Install this: https://github.com/electron/electron-quick-start
Install web3
Install https://github.com/sindresorhus/electron-reloader
Create a little function to call "getBalance" for example
Update index.html and save.

Thank you!

**Comment by Spacesai1or** [comment]
Hey there! Thank you for bringing this to our attention and even giving us steps to reproduce! We'll take a look at this to determine if the error is indeed caused by web3.js

**Comment by SimonR-Nano** [comment]
Hey! No problem, i just made for you an example with the little "crash" :)

Thank you!

[example.zip](https://github.com/ChainSafe/web3.js/files/6711879/example.zip)

**Comment by nazarhussain** [comment]
I was able to reproduce the error with following versions: 

```
"electron": "^14.0.1",
"electron-reloader": "^1.2.1"
"web3": "^1.5.2"
```

The error occurred only by including `web3` package to the app process. 

```
const Web3 = require('web3');
``` 

And its not that Electron cashes but rather Devtools disconnect during hot reload. But it also connects back when you make some change again and hot module reload trigger again. 

Not sure if this is something to do with web3 directly, as the Devtool disconnect error is very common in the Electron, a quick search can lead to many other packages and many other causes as well.  

We should investigate it further but don't consider its a blocker for web3.

**Comment by philknows** [comment]
Our current priority is to push the 4.x rewrite and this issue will be placed on hold.

**Comment by ahluwalij** [comment]
Getting this same issue, the only thing I can do to work around it is to automatically refresh on a crash event. Anyone found a fix?
