### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Transaction was not mined within 750 seconds

### ISSUE THREAD

**Issue by ahmedeid6842** [ethereum/web3.js#4156]
I got this error :  "UnhandledPromiseRejectionWarning: Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!"

when I'm trying to deploy my contract to Rinkeby network through infura and web3 

I don't know the reason of that error

**Comment by EresDev** [comment]
One of the reasons can be a too-high gas limit (close to max) or too low gas price. Try changing them. 

https://ethereum.stackexchange.com/questions/95100/transaction-not-being-mined-within-750-seconds
https://ethereum.stackexchange.com/questions/80145/error-transaction-was-not-mined-within-750-seconds-please-make-sure-your-trans
https://ethereum.stackexchange.com/questions/71545/truffle-deploy-live-transaction-not-mined-within-750-seconds
