### ISSUE TITLE
web3.eth.sendSignedTransaction fails with "invalid value null"

### ISSUE THREAD

**Issue by pedrouid** [ethereum/web3.js#4158]
#### Expected behavior

web3.eth.sendSignedTransaction should broadcast signed transaction blob

#### Actual behavior

web3.eth.sendSignedTransaction fails and throws with error message ` Errors encountered in param 0: Invalid value null supplied to : DATA`

yet the same signed transaction works if I send a JSON-RPC request with method `eth_sendRawTransaction` directly to the node

**Comment by philknows** [comment]
We are unsure how to reproduce this, please provide more information if re-opening.
