### ISSUE TITLE
Web3 : TypeError: Class extends value undefined is not a constructor or null 

### ISSUE THREAD

**Issue by sjshank** [ethereum/web3.js#4165]
I am trying to load Web3 in my React-Typescript project. While creating a Web3 object, getting TypeError from dependent file ethereum-cryptography/keccak.js

#### Expected behavior

Web3 should be compatible with Typescript. It Should load Web3 & create an instance.

#### Actual behavior

Web3 is not compatible with Typescript.

Uncaught TypeError: Class extends value undefined is not a constructor or null
    at module.exports (keccak.js?e073:3)
    at module.exports (index.js?c98c:5)
    at eval (js.js?6983:1)
    at Object../node_modules/keccak/js.js (main.164bc0ef9eb1cf8a59d3.js:4714)
    at __webpack_require__ (main.164bc0ef9eb1cf8a59d3.js:7291)
    at eval (keccak.js?c331:4)
    at Object../node_modules/ethereum-cryptography/keccak.js (main.164bc0ef9eb1cf8a59d3.js:3542)
    at __webpack_require__ (main.164bc0ef9eb1cf8a59d3.js:7291)
    at eval (hash.js?eb21:4)
    at Object../node_modules/ethereumjs-util/dist/hash.js (main.164bc0ef9eb1cf8a59d3.js:3839)

#### Steps to reproduce the behavior

**Package.json**

"dependencies": {
    "@headlessui/react": "^1.3.0",
    "@heroicons/react": "^1.0.1",
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.58",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.1.9",
    "@types/jest": "^26.0.23",
    "@types/node": "^15.12.5",
    "@types/react": "^17.0.11",
    "@types/react-dom": "^17.0.8",
    "@types/react-router-dom": "^5.1.7",
    "assert": "^2.0.0",
    "axios": "^0.21.1",
    "buffer": "^6.0.3",
    "clsx": "^1.1.1",
    "crypto-browserify": "^3.12.0",
    "https-browserify": "^1.0.0",
    "lodash": "^4.17.21",
    "os-browserify": "^0.3.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-number-format": "^4.6.3",
    "react-redux": "^7.2.4",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scroll-up-button": "^1.6.4",
    "react-toast-notifications": "^2.4.4",
    "redux": "^4.1.0",
    "redux-thunk": "^2.3.0",
    "stream": "0.0.2",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "web3": "^1.4.0"
  },

**tsConfig.json**

{
  "compilerOptions": {
    "target": "es6",
    "lib": ["ES5", "ES2015", "dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "module": "esnext",
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "jsx": "react",
  },
  "include": ["src"]
}

**Webpack.js**

module.exports = {
  entry: './src/index.tsx',
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
    fallback: { "os": false, "https": false, "http": false, "crypto": false, "stream": false, "assert": false },
  },
  output: {
    path: __dirname + '/build',
    publicPath: '/',
    filename: '[name].[contenthash].js',
    chunkFilename: '[name].[contenthash].js'
  },
.....

 plugins: [
    new CleanWebpackPlugin(),
    new webpack.ProvidePlugin({
      process: 'process/browser',
      Buffer: ['buffer', 'Buffer'],
    }),
    new HtmlWebpackPlugin({ inject: true, template: path.resolve(__dirname, 'public', 'index.html') }),
  ]

**Web3Loader.tsx**

import Web3 from "web3";
const provider = new Web3.providers.HttpProvider("http://127.0.0.1:8545");
const web3 = new Web3(provider);
....

#### Logs

Uncaught TypeError: Class extends value undefined is not a constructor or null
    at module.exports (keccak.js?e073:3)
    at module.exports (index.js?c98c:5)
    at eval (js.js?6983:1)
    at Object../node_modules/keccak/js.js (main.4af9f56f5dc4569a48eb.js:5406)
    at __webpack_require__ (main.4af9f56f5dc4569a48eb.js:9986)
    at eval (keccak.js?c331:4)
    at Object../node_modules/ethereum-cryptography/keccak.js (main.4af9f56f5dc4569a48eb.js:4553)
    at __webpack_require__ (main.4af9f56f5dc4569a48eb.js:9986)
    at eval (hash.js?eb21:23)
    at Object../node_modules/ethereumjs-util/dist/hash.js (main.4af9f56f5dc4569a48eb.js:4641)

**Comment by GregTheGreek** [comment]
We are currently focusing most of our energy on a re-write of web3.js in TypeScript (4.x branch).

**Comment by philknows** [comment]
Will be addressed with 4.x
