### ISSUE TITLE
Documentation only shows up to v1.3.4

### ISSUE THREAD

**Issue by Morinohtar** [ethereum/web3.js#4166]
The current version is v1.4.0 but the website documentation still refers to [v1.3.4](https://web3js.readthedocs.io/en/v1.3.4/).

I tried searching here in the issues (old and new) and the net and i couldnt find anything related to the update of the documentation... might be blind but...
So, i wanted to know if there are anything new that is missing from v1.3.5, v1.3.6, v1.4.0, or that it wasnt updated because there isnt anything really to update, besides the "title" of the doc.

Thanks.

**Comment by GregTheGreek** [comment]
Thanks for addressing this, read the docs didn't catch the version update, its been corrected.
