### ISSUE TITLE
quasar framework 2.0 Unable to import web3js

### ISSUE THREAD

**Issue by zj978643142** [ethereum/web3.js#4169]
App • ERROR • UI in ./node_modules/eth-lib/lib/bytes.js

Module not found: Can't resolve imported dependency "crypto"
Did you forget to install it? You can run: npm install --save crypto

App • ERROR • UI in ./node_modules/ethereumjs-util/dist/account.js

Module not found: Can't resolve imported dependency "assert"
Did you forget to install it? You can run: npm install --save assert

App • ERROR • UI in ./node_modules/web3-eth-accounts/lib/index.js

Module not found: Can't resolve imported dependency "crypto"
Did you forget to install it? You can run: npm install --save crypto

App • ERROR • UI in ./node_modules/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js

Module not found: Can't resolve imported dependency "crypto"
Did you forget to install it? You can run: npm install --save crypto

App • ERROR • UI in ./node_modules/web3-providers-http/lib/index.js

Module not found: Can't resolve imported dependency "http"
Did you forget to install it? You can run: npm install --save http

App • ERROR • UI in ./node_modules/web3-providers-http/lib/index.js

Module not found: Can't resolve imported dependency "https"
Did you forget to install it? You can run: npm install --save https

App • ERROR • UI in ./node_modules/xhr2-cookies/dist/xml-http-request.js

Module not found: Can't resolve imported dependency "http"
Did you forget to install it? You can run: npm install --save http

App • ERROR • UI in ./node_modules/xhr2-cookies/dist/xml-http-request.js

Module not found: Can't resolve imported dependency "https"
Did you forget to install it? You can run: npm install --save https

Even if I install it manually, I will still prompt this error

**Comment by patofet** [comment]
can you get it working? I have the same problem

**Comment by snwokenk** [comment]
Check this out
[Handling Webpackk5 polyfill](https://quasar.dev/start/upgrade-guide#webpack-v5)

Quasar 2 uses Webpack 5, which no more has polyfills for core node modules. so the link above should show you how to add the required polyfills

**Comment by patofet** [comment]
> 
> 
> Check this out
> [Handling Webpackk5 polyfill](https://quasar.dev/start/upgrade-guide#webpack-v5)
> 
> Quasar 2 uses Webpack 5, which no more has polyfills for core node modules. so the link above should show you how to add the required polyfills

I tried it, but now it gives me this error multiple times:

```

App •  ERROR  •  UI  in ./node_modules/graceful-fs/graceful-fs.js

Module not found: Can't resolve imported dependency "fs"
Did you forget to install it? You can run: npm install --save fs

 App •  ERROR  •  UI  in ./node_modules/jest-worker/build/workers/ChildProcessWorker.js

Module not found: Can't resolve imported dependency "child_process"
Did you forget to install it? You can run: npm install --save child_process

```

**Comment by philknows** [comment]
Sorry, supporting individual frameworks is out of scope at this time. Closing.
