### ISSUE TITLE
Webpack5 support for create-react-app 

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#4173]
When a user uses the create-react-app to make their React project, it comes pre bundled with webpack 5. The scope will be to ensure that web3.js can be successfully bundled using webpack 5 and within a React project made with the create-react-app.

**Comment by luu-alex** [comment]
CRA Tracking issue https://github.com/facebook/create-react-app/issues/9994#issuecomment-883445878

**Comment by luu-alex** [comment]
Still being looked into

**Comment by luu-alex** [comment]
Will be blocked until [5.0](https://github.com/facebook/create-react-app/milestone/81) releases which includes webpack 5 support.

**Comment by ArthurGerbelot** [comment]
This is an important one. 
I loose days  trying to fix it. 

I'm done and will use https://www.npmjs.com/package/ethers instead

**Comment by luu-alex** [comment]
> This is an important one. I loose days trying to fix it.
> 
> I'm done and will use https://www.npmjs.com/package/ethers instead

Hi @ArthurGerbelot we are waiting for create-react-app to upgrade to support webpack 5, once they do we will create support ASAP. Currently the latest version of create-react-app does work with web3.js so If you are facing a problem please create an issue. 

Sorry if you are facing any issues

**Comment by luu-alex** [comment]
https://github.com/ChainSafe/web3.js#web3-and-create-react-app Instructions now exist for getting create-react-app working with web3js
