### ISSUE TITLE
webpack5 support for angular-cli

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/web3.js#4174]
When a user uses the Angular CLI to make their Angular project, it comes pre bundled with webpack 5. The scope will be to ensure that web3.js can be successfully bundled using webpack 5 and within an Angular project made with the Angular CLI.

**Comment by luu-alex** [comment]
The old instructions on the readme to solve this problem does not work in the latest angular version,
so in the upcoming [PR](https://github.com/ChainSafe/web3.js/pull/4342) I included instructions to solve the build error in the `readme` for the web3js library, to help out angular users when they run into this.
