### ISSUE TITLE
getTransaction fails retrieving a pending 1559-style transaction

### ISSUE THREAD

**Issue by turboboost55** [ethereum/web3.js#4179]
#### Expected behavior

Should be able to retrieve a 1559-style transaction from the mempool, before it has been mined.

#### Actual behavior

On Ropsten or Goerli network, getTransaction throws an error with message `TypeError: Cannot read property 'toString' of null Given value: "null"` when you try to retrieve a transaction in the pending state.  Once the transaction has been mined, everything works fine.  Also, if you try to retrieve a legacy transaction, it also works as expected.

#### Steps to reproduce the behavior

1. Send a new style EIP-1559 transaction to either the Ropsten or Goerli network
2. Before it gets mined, use getTransaction to try to retrieve it.

#### Logs

```
Error: TypeError: Cannot read property 'toString' of null Given value: "null"
    at Object.toBN (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-utils/lib/utils.js:60:15)
    at outputBigNumberFormatter (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-core-helpers/lib/formatters.js:64:18)
    at Method.outputTransactionFormatter [as outputFormatter] (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-core-helpers/lib/formatters.js:205:19)
    at Method.formatOutput (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-core-method/lib/index.js:523:33)
    at /mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-core-requestmanager/lib/index.js:308:9
    at XMLHttpRequest.request.onreadystatechange (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/mnt/c/Projects/0xBitcoin/TokenPool/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Environment

npm v6.14.6
node v10.22.1
web3 v1.4.0
Ubuntu 18.04 (WSL)

**Comment by BigtoC** [comment]
I have a similar issue, also crashed when using the getTransation() function to process 1559 transactions, my error message is:
```
Error: [number-to-bn] while converting number undefined to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: \"undefined\"","level":"error"}
```
This is the transaction [0x4892eb4e48f81a20f707e631d3e13599c134c18cfc0477420a9003865f0ee869](https://ropsten.etherscan.io/tx/0x4892eb4e48f81a20f707e631d3e13599c134c18cfc0477420a9003865f0ee869)

**Comment by BigtoC** [comment]
> I have a similar issue, also crashed when using the getTransation() function to process 1559 transactions, my error message is:
> 
> ```
> Error: [number-to-bn] while converting number undefined to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: \"undefined\"","level":"error"}
> ```
> 
> This is the transaction [0x4892eb4e48f81a20f707e631d3e13599c134c18cfc0477420a9003865f0ee869](https://ropsten.etherscan.io/tx/0x4892eb4e48f81a20f707e631d3e13599c134c18cfc0477420a9003865f0ee869)

Updated OpenEthereum to v3.3.0-rc.4-stable-a92e5e7-20210714, this error is gone, looks good now.

**Comment by Spacesai1or** [comment]
Hi there, EIP1559 support was added to the latest RC version: `1.5.0-rc.0`. If you could try upgrading to that version and letting us know if your issue still persists, thank you!

**Comment by mining-visualizer** [comment]
Just tested it with 1.5.0-rc.0, and the problem seems to have been solved.

**Comment by badkk** [comment]
+1

**Comment by badkk** [comment]
> 1.5.0-rc.0

I tested with `1.5.0-rc0` with error:
```
Error: Returned error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash
```

My code is:
```typescript
    // 1. Connect to eth endpoint
    const web3 = new Web3(new Web3.providers.HttpProvider(ethEndpoint));

    // 2. Parse tx by tx hash
    const currentBN = await web3.eth.getBlockNumber(); // Can work
    const tx = await web3.eth.getTransaction(txHash); // Error here!
```
ethEndpoint: from Infura
txHash: https://rinkeby.etherscan.io/tx/0xe1413acecda0e789674aeb6e9db63fdde742af80c428778d04608f425dd46440

**Comment by GregTheGreek** [comment]
@zikunfan can you try the latest release 1.5.0-rc.1?

Also where are you getting the txHash? Can you provide the hash you used?

**Comment by GregTheGreek** [comment]
I was unable to reproduce this on `v1.5.0-rc.1`
File:
```
const Web3 = require('web3');

const web3 = new Web3(<rinkeby>);

(async () => {
  const tx = await web3.eth.getTransaction("0xe1413acecda0e789674aeb6e9db63fdde742af80c428778d04608f425dd46440")
  console.log(tx)
})();
```
Output:
```
 3% ➜ node index.js
{
  blockHash: '0xfa6219b3b28a909f7fe5fb66d8536798ca229d3526b38a2b8f22daa64525b255',
  blockNumber: 8985520,
  from: '0x110eA27b24c9E973098A69dd93cf831b7896b81f',
  gas: 34488,
  gasPrice: '1000000000',
  hash: '0xe1413acecda0e789674aeb6e9db63fdde742af80c428778d04608f425dd46440',
  input: '0xa9059cbb00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000008ac7230489e80000',
  nonce: 17,
  r: '0x3d7c53f4d691cfef029b4f566ad38238df455b14d21d1592e2cc721ae1732d97',
  s: '0x2bb62c79da6e9fe34569cc26a9c468d97acf816cd464efd7be90c42cb631b27b',
  to: '0x002F24009DF0c1E9215C98cEC76f18d8EAF3dB0f',
  transactionIndex: 23,
  type: 0,
  v: '0x2c',
  value: '0'
}
```
