### ISSUE TITLE
shh example doesn't work, web3.shh.post may be the culprit

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/web3.js#419]
This should work and doesn't:

``` js
// define web3 object
var web3 = new Web3();

// setup provider
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

// new identity, topic, payload
var identity = web3.shh.newIdentity();
var topic = 'some-topic-example';
var payload = 'some payload text';

// build message object
var message = {
    from: identity,
    topic: [topic],
    payload: payload,
    ttl: 100,
    priority: 100
};

// setup filter for messages on topic
var filter = web3.shh.filter({
    topics: [web3.fromAscii(topic)]
});

// watch for changes on filter
filter.watch(function (err, result) {
    console.log(err, result, web3.toAscii(result.payload));
});

web3.shh.post(message, function (err, result) {
    console.log(err, result);
});
```

Geth:

```
geth --testnet --unlock "0" --shh --rpc --rpcapi="db,eth,net,web3,shh" --rpcaddr="0.0.0.0" --rpccorsdomain="*"
```

Notes:

(1) Filtering works fine when I use other apps to post messages to my node on the topic I'm listening for. Which validates that the filtering/topic filtering works with web3.js
(2) I think it is something to do with the `web3.shh.post` method and the message object encoding that is causing problems here. Messages I post dont seem to get brought into the filters.
(3) The examples in the docs don't specify whether the message object should/can/must contain a `priority` property or a `workToProve` property. That should be clarified.
(4) The web3.shh methods seem tempermental at best and need to be re-tested with geth 1.5.1

**Comment by coderwithattitude** [comment]
we had the same issue we changed  'topic' to 'topics' and that solved the problem

**Comment by frozeman** [comment]
Please try out the new whisper and API and see if you have issues
