### ISSUE TITLE
Plans to support eth_maxPriorityFeePerGas method?

### ISSUE THREAD

**Issue by brg8** [ethereum/web3.js#4195]
I've gone through the EIP 1559 PR and could not find support for this new method. There is a separate PR for eth_feeHistory, which is fantastic. What is the reasoning behind ignoring eth_maxPriorityFeePerGas? Your hard work is appreciated!

**Comment by GregTheGreek** [comment]
Hey! I don't think that's apart of the official spec. If that's changed do you mind pointing me to that documentation we can quickly add it :)

**Comment by brg8** [comment]
You're right! It's not part of the official spec, it's geth specific.

I've done some snooping, but I guess I'll ask here -- do you expose a function to send an arbitrary method call to the provider? So that I can call node-client-specific methods when needed.

Thanks!

**Comment by GregTheGreek** [comment]
No, but that could be a nice feature.

@spacesailor24 thoughts?

**Comment by luu-alex** [comment]
Hey, we don't plan on supporting this feature for 1.x, but possibly add this to the roadmap for 4.x. Although if you wanted to add a customRPC call like eth_maxPriorityFeePerGas you can do something like this:
```
const Web3 = require('web3')
const Method = require('web3-core-method');

const web3 = new Web3("")
web3.eth.customRPC = function (opts) {
    const _this = this;
    const newMethod = new Method({
        name: opts.name,
        call: opts.call,
        params: opts.params || 0,
        inputFormatter: opts.inputFormatter || null,
        outputFormatter: opts.outputFormatter || null,
    })
    newMethod.attachToObject(_this);
    newMethod.setRequestManager(_this._requestManager, _this.accounts)

}
console.log(web3.eth.customRPC)
web3.eth.customRPC({name: "testMethod", call: "eth_testMethod"});
```

**Comment by Muhammad-Altabba** [comment]
Reopening this issue as `eth_maxPriorityFeePerGas` become part of the official specs (https://ethereum.github.io/execution-apis/api-documentation/)
