### ISSUE TITLE
Provide an EventEmitter for watching events

### ISSUE THREAD

**Issue by Latrasis** [ethereum/web3.js#420]
Currently the only way of watching events is through single seperate callbacks, while this interface is simple, it doesn't fare well with working with frp and forces the user to wrap the callback. It would be nice to access the underlying stream as well. This also would bring compatibility with `WebSockets`, such as the lib `socket.io`.

An example:
```
var events = myContractInstance.events;
events.on("MyContract", (err, data) => {
     console.log("I'm the stream!");
})
```

**Comment by frozeman** [comment]
We are working on this, see https://github.com/ethereum/web3.js/tree/newContract

**Comment by Latrasis** [comment]
Awesome! Thanks!
