### ISSUE TITLE
Refactor Error Handling for Rewrite

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4203]
#### 4.x Improvement

In `Web3ProvidersHttp` following throw statements must be before / outside `try` block, it will be more standard and efficient as it will not (throw, catch and again throw), but instead directly throw.

https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-providers-http/src/index.ts#L43
https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-providers-http/src/index.ts#L69
https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-providers-http/src/index.ts#L87
https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-providers-http/src/index.ts#L132

**Comment by Spacesai1or** [comment]
I actually want to do a complete overhaul on handling errors, and will take this into account

[EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) has a format and some error codes for dealing with RPC errors, and I want to follow the pattern to create a `web3-core-errors` package that standardizes errors for all of web3.js (similar to Ethers' [logger](https://github.com/ethers-io/ethers.js/blob/master/packages/logger/src.ts/index.ts) package)

**Comment by Spacesai1or** [comment]
https://github.com/MetaMask/eth-rpc-errors

**Comment by Spacesai1or** [comment]
This include the initialization of the `web3-eth-logger` package

**Comment by Spacesai1or** [comment]
Closing as it doesn't pertain to rewrite of 4.x
