### ISSUE TITLE
Don't require `chainId` if `common` is present [eth.accounts.signTransaction]

### ISSUE THREAD

**Issue by Mr-VIT** [ethereum/web3.js#4208]
https://github.com/ChainSafe/web3.js/blob/458a47af814982df6cfd111c0d8a8f9b17581937/packages/web3-eth-accounts/src/index.js#L266-L267
`transaction.chainId` is not used anyway if `transaction.common` is present:
https://github.com/ChainSafe/web3.js/blob/458a47af814982df6cfd111c0d8a8f9b17581937/packages/web3-eth-accounts/src/index.js#L185-L192

**Comment by GregTheGreek** [comment]
This makes sense, we should probably just update the `chainId` within the `if` block on line 186
