### ISSUE TITLE
Calling structs incorrectly decodes non-32-byte data

### ISSUE THREAD

**Issue by ckeenan** [ethereum/web3.js#421]
A struct with bytesX where X < 32 will overflow the subsequent fields of the struct when called via web3. Placing the bytesX type last will work, however (if it is the only one of its kind in the struct). Using `web3@0.15.3`

For example

```
struct SomeStruct {
    bytes2 testB;
    bytes32 testA;
}

testStruct = SomeStruct({
    testA: 0x0c98fceab753c7528a29469e19c7901cab3e987b379bf0627c4027ef0a6993c4,
    testB: 0x1210
});
```

testStruct will return `[ '0x1210', '0x0000000000000000000000000000000000000000000000000000000000000c98' ]` when accessed

reversing the field order results in correct values

```
struct SomeStruct {
    bytes32 testA;
    bytes2 testB;
}
```

**Comment by frozeman** [comment]
@chriseth

**Comment by ckeenan** [comment]
I see this with LOGs too. For example `event Test(bytes2 testA, bytes32 testB);` results in args values of:
```
{ testA: '0x1234',
  testB: '0x0000000000000000000000000000000000000000000000000000000000003ac2' }
```
while `event Test(bytes32 testB, bytes2 testA);` will show correct arg values

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
