### ISSUE TITLE
web3.eth.sign never returns never calls back

### ISSUE THREAD

**Issue by XOCODE-OP** [ethereum/web3.js#4214]
(This is using local ganache, metamask set up to localhost which is working otherwise)
web3.js is 1.5.0

Iam seeing there is some other issues regarding singing and this might be because of it.
I am trying to establish how to sign, here is my code:

        async function sign()
        {
            console.log("sign func");

            let accounts = await web3.eth.getAccounts();
            console.log("account:", accounts[0]);
            let msg = "Some data";
            console.log("in data message:", msg);
            let prefix = "\x19Ethereum Signed Message:\n" + msg.length;
            let msgHash1 = web3.utils.sha3(prefix+msg);
            console.log("using hash:", msgHash1);

            let sig1 = await web3.eth.sign(msg, accounts[0]);
            console.log("signing...", sig1);

            //web3.eth.sign(msg, accounts[0]).then(console.log);

            let whoSigned1 = await web3.eth.accounts.recover(msg, sig1);
            console.log("WHO SIGNED", whoSigned1);
        }
(code is triggered via a button, works fine functionally aka it gets called)

All console logs until eth.sign happen just normal, correct account as well. Then metamask asks to confirm the signature, just like I would expect.

[https://i.stack.imgur.com/8dpTc.png](https://i.stack.imgur.com/8dpTc.png)

I click sign and thats it, nothing ever happens. The function does not return, no further code is ever called. Meaning it never calls back, it awaits forever. I also used then() syntax, same thing, never calls back.

If I do another transaction, while waiting, like minting an NFT, no problem goes through.

I switched metamask to rinkeby, same behavior. Switched it's mainnet, same. So I guess it's my code?

**Comment by distantstatic** [comment]
I am also having this issue.
`

        web3.eth.sign('asdf', account)
            .then((data) => {
                console.log(`heres data: ${data}`);
                console.log('past it');
            })
            .catch((error) => {
                console.log(error);
            })
`
MetaMask Sign Message popup will display the hashed string but promise is not resolved despite pressing sign.

Catch will be called upon cancelling.
> {code: 4001, message: 'MetaMask Message Signature: User denied message signature.'}

------------------------------
Edit:

Apparently the eth_sign method is deprecated for security reasons.

personal_sign is the preferred method of signing data as to avoid users being fed a transaction through raw data from a malicious site.

Maybe its worth deprecating eth.sign here as well?

Nonetheless data can be signed by using personal.sign while using MetaMask or the Trezor or Ledger hardware wallets.

Source: [https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask](url)
