### ISSUE TITLE
release 0.16 to NPM

### ISSUE THREAD

**Issue by harlantwood** [ethereum/web3.js#422]
The last version on NPM is 0.15.3

**Comment by kumavis** [comment]
+1

**Comment by redsquirrel** [comment]
:+1:

**Comment by chmanie** [comment]
npm versions are in a very weird state. There are versions 0.16.0 now and 0.17-alpha but these are definitely not the versions that are in this repo. For example `httpprovider` in v0.16 still has the `Npm.require` call in it (as well in v0.17).

**Comment by kumavis** [comment]
as a workaround, im calling out the tags from github directly in the dependencies
`"web3": "ethereum/web3.js#0.16.0",`
