### ISSUE TITLE
Legacy gas fee estimation

### ISSUE THREAD

**Issue by florianib** [ethereum/web3.js#4249]
I am currently testing a created web app which uses web3.js. When I am trying to send a transaction, I receive following warning message:
![image](https://user-images.githubusercontent.com/21081469/129722556-fa559917-7b39-46c1-8511-6f9bafb22bc0.png)

Before continuation, I need to manually change the gas fee. Is there a way to use another gas calculation, so that the webapp correctly calculates the fee?

Currently it calculates it way too low.

![image](https://user-images.githubusercontent.com/21081469/129722839-eb431fcd-64dd-4197-a67d-55592b13fee6.png)

**Comment by luu-alex** [comment]
Which web application are you using?

**Comment by florianib** [comment]
It's just a plain HTML page which includes the .js file and calls a contract function:
```
await window.contract.methods.testFunction().send({ from: account, value: web3.utils.toWei('0.03', "ether") });
```

The .js file is included like this:
```
 <script src='./web3.min.js'></script>
```

**Comment by jdevcs** [comment]
@0x00xx  Please could you share following info:


#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Environment

Versions used of:  (applicable) Web3.js, npm, Node, OS, device , browser, wallet ..... etc

**Comment by jdevcs** [comment]
No 'Steps to reproduce' provided so closing, until.
