### ISSUE TITLE
Revisit types in web3-providers-ws

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4255]
Can we use [RpcResponse](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-core-types/src/types.ts#L169) here? Looks like we need to update `result` to optional and add `error`

_Originally posted by @spacesailor24 in https://github.com/ChainSafe/web3.js/pull/4209#r690892338_

**Comment by jdevcs** [comment]
its already done in 4.x new architecture web3-common so closing this issue.
