### ISSUE TITLE
If network supports EIP-1559, then we cannot send a legacy transaction

### ISSUE THREAD

**Issue by floatcoder** [ethereum/web3.js#4258]
#### Expected behavior
I would expect to be able to specify a legacy `tx.type` (i.e. "0x0" ) and allow for the gasPrice to be auto-filled. The motivation for this is that some hardware wallets do not yet support EIP1559 transactions, while the network provider will.

#### Actual behavior
Instead the `maxFeePerGas` and `maxPriorityFeePerGas` are set causing a transaction envelope rejection. This I imagine is due to the difference between [web3-core-method](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L853-L878) `_handleTxPricing` and [web3-eth-accounts](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js#L376-L380) `_handleTxPricing`. `web3-eth-accounts` checks the `tx.type` while `web3-core-method` does not.

Note that this is the reverse of the issue mentioned in https://github.com/MetaMask/metamask-extension/issues/11824 where if we intend to do a legacy transaction, the `gasPrice` gets overwritten.

#### Steps to reproduce the behavior

1. Create a `const ethContract = new web3.eth.Contract(...)`
2. Send a transaction via the contract methods `ethContract.methods["approve"].send({ type: "0x0" })`

#### Logs
> Invalid transaction envelope type: specified type "0x0" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2"

#### Environment

web3 1.5.2

**Comment by floatcoder** [comment]
Temporary fix for this if anyone experiences this is:
1. Downgrade to web3 1.5.1
2. Ensure you always set the type to `0x2` if EIP1559 is supported.
3. If EIP1559 is not supported, you can then set the type to `0x0` and it'll work as expected.

Note that if you try to do a legacy transaction `0x0` when EIP1559 is supported this still breaks on MetaMask's side due to https://github.com/MetaMask/metamask-extension/issues/11824

**Comment by melvinmcrn** [comment]
@floatcoder I've tried what you have suggested and it's working for me (for both hot wallet and hardware wallet connecting via MetaMask). However, there is an error log in my console with a message as `Invalid transaction envelope type: specified type \"0x02\" but including maxFeePerGas and maxPriorityFeePerGas requires type: \"0x2\"` for the hot wallet case.

ps. I haven't really tried confirming the tx in MetaMask but the MetaMask UI doesn't show any error nor reverted.
ps2. I have tried with web3 1.5.0 and it seem to be working without any error. Are there any known problem with the v1.5.0?

**Comment by Pasha8914** [comment]
for some reason, the ability to send legacy tx was removed

https://github.com/ChainSafe/web3.js/pull/4241/files#diff-9050e060908a6957eb4e25bb2f4b8930f5097e55e846e0e8194ff5fa3a3440a4R862

**Comment by rstormsf** [comment]
WTF???? I still WANT to send a LEGACY transaction EVEN though it DOES support EIP. 
Terrible decision making policy at web3. We have MULTIPLE apps with customers who doesn't WANT to send EIP tx.

**Comment by Spacesai1or** [comment]
[v1.5.3-rc.0](https://github.com/ChainSafe/web3.js/releases/tag/v1.5.3-rc.0) has been released to NPM, please test to verify it solves encountered issues
