### ISSUE TITLE
London Hard Fork Support

### ISSUE THREAD

**Issue by philknows** [ethereum/web3.js#4262]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by such** [comment]
It seems the typescript types have not been updated.
For instance TransactionConfig in `web3-core/types/index.d.ts` should accept `maxFeePerGas` now right?

**Comment by jdevcs** [comment]
@such This is Epic for tracking all London HF related stuff only, Thanks for mentioning it. There is similar issue / PR as well    [already in](https://github.com/ChainSafe/web3.js/pull/4232)

**Comment by Lucid36** [comment]
Pull request
