### ISSUE TITLE
Typescript issue - how to get Contract type?

### ISSUE THREAD

**Issue by romeerez** [ethereum/web3.js#4265]
```ts
const w3 = new Web3()
export const contract = new w3.eth.Contract({}, 'address')
```

Using version 1.3.5 this gives typescript error:
The inferred type of 'contract' cannot be named without a reference to 'web3/node_modules/web3-eth-contract'. This is likely not portable. A type annotation is necessary.

I tried to install web3-eth-contract and to use `Contract` type from that package with no luck, TS was saying types are not compatible.

Using latest version 1.5.2 contract has `any` type

**Comment by Spacesai1or** [comment]
You could trying importing `Contract` from `web3-eth-contract` and doing the following:

```javascript
import { Contract } from 'web3-eth-contract';

const w3 = new Web3()
export const contract as Contract = new w3.eth.Contract({}, 'address')
```

But I don't think the library currently has strong typing support for contracts. This is something we will aim to fix in the rewrite of library that is currently taking place

In case it helps you, we're going to try to make use of [typechain](https://github.com/dethcrypto/TypeChain) to generate strong contract typings
