### ISSUE TITLE
 what is the web3.eth.sign and the web3.eth.accounts.sign difference , And solidity erecover used the web3.eth.accounts.sign  is not correct

### ISSUE THREAD

**Issue by malingzhao** [ethereum/web3.js#4266]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by malingzhao** [comment]
my code is 
    let sign1 = web3.eth.accounts.sign(web3.eth.accounts.hashMessage(message), privKey1);
and the solidity code is 
  function messageToRecover(address erc20Contract, address destination, uint256 value) public view returns (bytes32) {
    
    bytes32 hashedUnsignedMessage = generateMessageToSign(erc20Contract, destination, value);
    
    bytes memory prefix = "\x19Ethereum Signed Message:\n32";
    return keccak256(abi.encodePacked(prefix, hashedUnsignedMessage));
  }

**Comment by malingzhao** [comment]
I found I use the soliditySha3 is correct , But When I use the account.HashMessage get the message is not what i want

**Comment by malingzhao** [comment]
I found the code Accounts.prototype.hashMessage = function hashMessage(data) {
    var messageHex = utils.isHexStrict(data) ? data : utils.utf8ToHex(data);
    var messageBytes = utils.hexToBytes(messageHex);
    var messageBuffer = Buffer.from(messageBytes);
    var preamble = '\x19Ethereum Signed Message:\n' + messageBytes.length;
    var preambleBuffer = Buffer.from(preamble);
    var ethMessage = Buffer.concat([preambleBuffer, messageBuffer]);
    return Hash.keccak256s(ethMessage);
};

**Comment by malingzhao** [comment]
I want to know  how to archieve the web3.eth.accounts.hashMessage in solidity

**Comment by jdevcs** [comment]
I believe you are trying to ecrecover , may be you can use some thing like:

```
pragma solidity ^0.4.11;
contract Test {

  function ecrecover1(bytes32 msgHash, uint8 v, bytes32 r, bytes32 s) constant returns(address) {
      bytes memory prefix = "\x19Ethereum Signed Message:\n32";
      bytes32 prefixedHash = keccak256(prefix, msgHash);
      return ecrecover(prefixedHash, v, r, s);
  }
}

```



```
    const message = web3.sha3('Test Message')           
    const signature = await web3.eth.accounts.sign( message, '0x00PrivateKey')   

    r = signature.substr(0, 66)
    s = '0x' + signature.substr(66, 64)
    v = '0x' + signature.substr(130, 2)
    
    const recoveredAddress = await this.contract.ecrecover1(message, v, r, s)
```
[`web3.eth.sign` signs data with account that is already unlocked]( https://web3js.readthedocs.io/en/v1.5.0/web3-eth.html#sign )

[while `web3.eth.accounts.sign` signs data with provided private key]( https://web3js.readthedocs.io/en/v1.5.0/web3-eth-accounts.html#sign)

**Comment by malingzhao** [comment]
ok, Thank you very much
