### ISSUE TITLE
The method personal_unlockAccount does not exist/is not available

### ISSUE THREAD

**Issue by vijayr2410** [ethereum/web3.js#427]
function unlockAcct()
    {
        var unlock = web3.personal.unlockAccount(web3.eth.accounts[0]);
        alert(unlock);
    }

The line " web3.personal.unlockAccount(web3.eth.accounts[0]);" returns an error "method personal_unlockAccount does not exist/is not available" when I try to execute from DApp.

**Comment by AlexanderKozhevin** [comment]
Having the same problem with creating new account - #494

**Comment by AlexanderKozhevin** [comment]
@vijayr2410 
Well. Looks like it's just require to specify following parameters to resolve this issue. You can close an issue 🆗 
```bash 
--rpcapi="db,eth,net,web3,personal,web3"
```

**Comment by vijayr2410** [comment]
Thank you Alexander! I did find that solution elsewhere. I am closing the issue.

**Comment by sagargohil** [comment]
Hi,
i am not getting where i need to execute --rpcapi="db,eth,net,web3,personal,web3"
this command.
i am using putty app to connect to my Etherium VM.

@vijayr2410 - which way did you find? can you please help me resolve this.

**Comment by AlexanderKozhevin** [comment]
@sagargohil When you start ethereum wallet itself. Specify parameters I mentioned.

**Comment by sagargohil** [comment]
i am not clear about where i need to run this command.. --rpcapi="db,eth,net,web3,personal,web3"
because i have tried on geth console but its not executing.

**Comment by Shubhabrata-Mukherjee** [comment]
run geth -rpc  --rpcapi="db,eth,net,web3,personal,web3" to make it work.

**Comment by bellaj** [comment]
as you might notice web3.personal.unlockAccount" means unlockAccount is part of personal API so in geth activate (or add ) this rpc api geth --rpcapi="personal"

**Comment by vijayst** [comment]
I am using testrpc with --secure flag. How do I get `web3.personal.unlockAccount` to work with testrpc? Thanks.

**Comment by bingtimren** [comment]
Is there a purpose to have "web3" appeared twice here? Or "db,eth,net,web3,personal" should be fine?

**Comment by bingtimren** [comment]
Ok, I read from https://github.com/ethereum/meteor-dapp-wallet/issues/89 unlocking account can only be done through IPC not http anymore.

**Comment by FatCache** [comment]
But is there any solution to unlock it over http during testing? I have a private blockchain running using Ganache but I'm unable to do any transaction. The following is not working

`mist --rpcapi="db,eth,net,web3,personal,web3" --rpc http://127.0.0.1:7545` 

A solution to this would really speed up my development time.

**Comment by Vishwas1** [comment]
> Thank you Alexander! I did find that solution elsewhere. I am closing the issue.

Bro how did you fix the issue? I am getting it now :(  If we do not run the geth using rpi option then it should activate all apis right?

**Comment by anistark** [comment]
If I'm connecting via infura, I wouldn't need to specify this `--rpcapi="db,eth,net,web3,personal,web3"`. right?

How to fix it in that case?

**Comment by RAFI-006** [comment]
My one same sceniarion as anistrak ,pls help if anybody knows Thanksss By the Way...........

**Comment by JahangirJadi** [comment]
I am also getting the same error in Android. I am using web3 core v4.8.7
