### ISSUE TITLE
Revisit types

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4270]
This is extremely annoying and I believe is a symptom of improper typing

_Originally posted by @spacesailor24 in https://github.com/ChainSafe/web3.js/pull/4269#r695346064_

Once the following packages are stable, we should revisit types:

- `web3-providers-http`
- `web3-providers-ws`
- `web3-eth2-beaconchain`

**Comment by philknows** [comment]
Link dependencies when possible.
