### ISSUE TITLE
What's the best way to get pending transactions?

### ISSUE THREAD

**Issue by tj327** [ethereum/web3.js#4271]
Hey team, I am currently using latest version of the web3 library and trying to get the list of pending transactions using subscribe.
To use subscribe function, I had to use socket provider instead of httpprovider but for some reasons, I am getting this error continuously.
`connection not open on send()`

Tried filter and getPendingTransactions function using lower version of web3 but all doesn't seem to work.
What's the best way to get pending transactions with latest version of web3?
Hope you help me with this.
Thanks

**Comment by jdevcs** [comment]
Its not reproducible. tested with `"web3": "^1.5.2"` . 

``` 
const Web3 = require('web3');

const web3 = new Web3( 
	 // use your own wss "wss://mainnet.infura.io/ws/v3/abc"
	);

var subscription = web3.eth.subscribe('pendingTransactions', function(error, result){
    if (!error)
        console.log(result);
})
.on("data", function(transaction){
    console.log(transaction);
});
 ```

Might be your node wss is not open or not configured properly.
