### ISSUE TITLE
doc update job

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4279]

**Comment by philknows** [comment]
Can we automate the process for readthedocs with @GregTheGreek for document version bump?

**Comment by GregTheGreek** [comment]
I dont think so, its a total pain

**Comment by philknows** [comment]
@jdevcs we've bumped the docs up to v1.5.0. I think we might be missing some info on where baseFee shows up. Should fix that, bump to 1.5.2, then close this as it doesn't clearly define additional tasks.

**Comment by GregTheGreek** [comment]
I lied, it looks relatively easy https://docs.readthedocs.io/en/stable/api/v3.html#build-triggering
