### ISSUE TITLE
stateless functions should be part of Web3 as opposed to web3. 

### ISSUE THREAD

**Issue by wighawag** [ethereum/web3.js#428]
The following  stateless functions attached to prototype should be instead attach to Web3 directly

This way we could access them without the need to get a hang on an instance of Web3.

```
Web3.prototype.toHex = utils.toHex;
Web3.prototype.toAscii = utils.toAscii;
Web3.prototype.toUtf8 = utils.toUtf8;
Web3.prototype.fromAscii = utils.fromAscii;
Web3.prototype.fromUtf8 = utils.fromUtf8;
Web3.prototype.toDecimal = utils.toDecimal;
Web3.prototype.fromDecimal = utils.fromDecimal;
Web3.prototype.toBigNumber = utils.toBigNumber;
Web3.prototype.toWei = utils.toWei;
Web3.prototype.fromWei = utils.fromWei;
Web3.prototype.isAddress = utils.isAddress;
Web3.prototype.isChecksumAddress = utils.isChecksumAddress;
Web3.prototype.toChecksumAddress = utils.toChecksumAddress;
Web3.prototype.isIBAN = utils.isIBAN;


Web3.prototype.sha3 = function(string, options) {
    return '0x' + sha3(string, options);
};

/**
 * Transforms direct icap to address
 */
Web3.prototype.fromICAP = function (icap) {
    var iban = new Iban(icap);
    return iban.address();
};
```

**Comment by frozeman** [comment]
Thanks for the input, though we will restructure many of those functions anyway, in a refactor. I will keep it in mind to add stateless functions to the Web3 object prototype..

**Comment by wighawag** [comment]
Cool

to be clear the snippset I showed is what currently in web3.js

What i would like to be able to do is to access them via Web3 directly (no web3)

I would like this
```
Web3.toWei(2,"ether";
```
as opposed to
```
var web3 = new Web3();
web3.toWei(2,"ether");
```

Thanks

**Comment by frozeman** [comment]
I understand, makes sense to me. Thanks for your input i will have a look once i do this!

**Comment by frozeman** [comment]
This is now exposed in web2.js 1.0 on `Web3.utils`
