### ISSUE TITLE
eth_requestAccounts returns address in lowercase not checksum

### ISSUE THREAD

**Issue by steveDL** [ethereum/web3.js#4286]
#### Steps to reproduce the behavior

1. Generate an address with lower and uppercase letters in MetaMask.
2. Use eth_requestAccounts to get the first account
`this.web3 = new Web3(window.ethereum);`
`window.ethereum.request({ method: 'eth_requestAccounts'})`
3. log result 

#### Expected behavior
1. Generate an address with lower and uppercase letters in MetaMask.
2. Use eth_requestAccounts to get the first account
3. log result and you will see the address is a checksum

#### Actual behavior
1. Generate an address with lower and uppercase letters in MetaMask.
2. Use eth_requestAccounts to get the first account
3. log result and you will see the address is NOT a checksum

#### Logs
Below my log is lower case:
![Screenshot 2021-08-31 at 23 05 43](https://user-images.githubusercontent.com/8135124/131582217-a91cfe63-bd88-42b5-bcb2-7eb821dd59e5.png)

Below my MetaMask address is Checksum

![Screenshot 2021-08-31 at 23 08 22](https://user-images.githubusercontent.com/8135124/131582160-804d92e6-c78b-4874-9a4c-5a8cf036c6b5.png)

#### Environment
`"web3": "^1.5.2",`

****
Have found that `this.web3.utils.toChecksumAddress(account[0])` will work.

**Comment by Spacesai1or** [comment]
A checksummed address is not expected to be returned. As you've discovered, you can use `web3.utils.toChecksumAddress` to convert it
