### ISSUE TITLE
Error: Network not synced; last block was 1630989984.464 seconds ago

### ISSUE THREAD

**Issue by ralyodio** [ethereum/web3.js#4294]
been getting this error for over a week. I don't think the seconds have changed.

```
Error: Network not synced; last block was 1630989984.464 seconds ago
```

```
 const addr = await ens.recordExists(`${word}.eth`)
```

this appears to be the error. I'm running a full node. when i do `eth.syncing` in console its still behind but if I do `eth.blockNumber` I get `0`

**Comment by Spacesai1or** [comment]
Hello there, this doesn't seem to be an issue regarding Web3.js, so I'm going to close it

Please take a look at [this](https://stackoverflow.com/a/52616590) as it may be related to your issue
