### ISSUE TITLE
Opinions on future-proof use of web3.js on immutable/permanent web

### ISSUE THREAD

**Issue by Cortexelus** [ethereum/web3.js#4297]
What's the best future-proof way to use `web3.js` on an immutable/permanent webpage (e.g. ipfs/arweave)? 

If we just include web3.js normally, what are the dangers? What if providers go offline? Can we rely on the browser wallet to always inject a working provider onto the window object? Can we rely that eip1193 will be supported long into the future? Can we rely on browser/webkit upgrades not creating breaking changes? 

Or is it better to build dapps with mutability/upgradability, just in case things break?

Opinions?

**Comment by Spacesai1or** [comment]
I mean technically the best way would be running a node, but if you aren't wanting to do that, then I'm not really sure. I don't know enough about the future development of Ethereum to know if eip1193 would get dropped. It might be replaced by a more accommodating eip in the future, although I'd assume it would be in a backwards compatible way
