### ISSUE TITLE
Transaction 'to' returning null

### ISSUE THREAD

**Issue by pipaman** [ethereum/web3.js#430]
Hi,
I'm using getBlock API with true to return the transaction objects and sometimes I'm getting null To field where they shouldn't.
For example if I do getBlock(529870, true) I get the correct from but the To is null.
Looking to the transaction I can see the To in this transaction (Hash: "0x9610082f3ba072240c42fc697d6e67bf83803dd10d74fc46650c087beb362c00"):
https://www.etherchain.org/block/529870

Thanks on advanced.
P/

**Comment by frozeman** [comment]
This works for me in web3.js 1.0. Please test yourself and reopen if its still an issue.
