### ISSUE TITLE
Typescript: web3_1.default is not a constructor

### ISSUE THREAD

**Issue by Cheny-chen** [ethereum/web3.js#4301]
[](https://github.com/ChainSafe/web3.js/issues/4257)

I follow the issue 4257, I still get the same problem.

I still have the same problem.
It is not solve.

I did { module:"commonjs" } in tsconfig

```
import Web3 from 'web3';
const web3 = new Web3( RPC_PROVIDER );
```

I still get the same error
TypeError: web3_1.default is not a constructor

**Comment by Cheny-chen** [comment]
I found answer in 
[](https://ethereum.stackexchange.com/questions/62693/typeerror-web3-1-default-is-not-a-constructor)

need to add  "esModuleInterop": true  in tsconfig
become 
"compilerOptions": {
		"target": "ES6",
		"module": "CommonJS",
		"resolveJsonModule": true,
		"strictNullChecks": true,
		"esModuleInterop": true,
}

**Comment by crazyoptimist** [comment]
Thank you

**Comment by jaxrunboo** [comment]
> useful
