### ISSUE TITLE
web3 left-aligns values when passed to `bytes32` argument.

### ISSUE THREAD

**Issue by Arachnid** [ethereum/web3.js#431]
In Solidity, casting an `address` or other shorter numeric value to a `bytes32` left-pads the value, as you'd expect, so casting back again gives the correct result. When web3 is given a hex string to pass to a function that expects `bytes32`, it instead right-pads it, leading to rather odd results:

test.js:

```
contract('address cast to bytes32', function(accounts) {
    it('should be left padded and cast back correctly', function(done) {
        var test = Test.deployed();
        test.implicitCast.call(test.address).then(function(ret) {
            assert.equal(ret, test.address);
        }).then(done).catch(done);
    })
});
```

Test.sol:

```
contract Test {
    function implicitCast(bytes32 a) returns (address) {
        return address(a);
    }
}
```

Output:

```
$ truffle test test/test.js
Using environment test.
Compiling contracts...


  Contract: address cast to bytes32
    1) should be left padded and cast back correctly
    > No events were emitted


  0 passing (587ms)
  1 failing

  1) Contract: address cast to bytes32 should be left padded and cast back correctly:
     AssertionError: expected '0x1fe28adc7c10597f000000000000000000000000' to equal '0x691436bbdd1b6a0ed90044e01fe28adc7c10597f'
      at test.js:6:11
```

**Comment by chriseth** [comment]
Not sure if this is a bug or just odd behaviour.
This depends on the type information that is available for `this.address` in javascript. Of course, javascript is untyped, so if `this.address` is not a number but a hex string, web3.js can only right-pad it.

**Comment by Arachnid** [comment]
I'd say it's definitely a bug somewhere - implicit casts should always be free of information loss.

web3 treats a string starting with "0x" differently to other strings - if it didn't, the return value would be doubly-encoded hex, starting with the hex encoding of "0x".

**Comment by zmitton** [comment]
Im having an issue inputting a hex string into a solidity function which expects bytes32. I tried using a Buffer datatype from web3 but didnt seem to help. I believe I'm dealing with the same issue.

**Comment by frozeman** [comment]
We are doing this here: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-abi/src/types/formatters.js#L71

We can simply switch to leftPadding. Which is the correct behaviour for bytes???

**Comment by Arachnid** [comment]
> Explicit conversion from bytes32 to address loses information, it is an explicit type conversion.

It's an explicit conversion in Solidity, but there's no explicit conversion occurring in web3 - and there's no way to specify type information in web3.

I think that web3 should left-pad hex-encoded bytes arguments instead of right-padding them, or else error and refuse to accept them entirely (better yet, web3 shouldn't infer type information from the contents of a string, but that's a separate battle).

**Comment by chriseth** [comment]
Yeah, the best solution would probably be to throw an error if the length does not match the type and ask for padding direction from the developer.

**Comment by frozeman** [comment]
Hm im not exactly sure how to best code that up, without breaking a lot of apps probably, which are used to the right padding.

**Comment by Arachnid** [comment]
Can you make 1.0 just throw an exception if it's passed a short argument to a fixed-width type? This seems like a good time to introduce such a breaking change.

**Comment by nivida** [comment]
This got implemented with the usage of the AbiCoder of ethers.js.
