### ISSUE TITLE
web3.eth.getBlock() returns baseFeePerGas field as hex string instead of BN or number

### ISSUE THREAD

**Issue by haltman-at** [ethereum/web3.js#4326]
#### Expected behavior

The field should be a `BN`, a `number`, or possibly a (decimal) numeric string.

#### Actual behavior

The field is a hexadecimal string.

#### Steps to reproduce the behavior

Start a private blockchain with Geth, using `geth --dev --http`.   In a location where web3 is installed, run `node --experimental-repl-await` to open a Node console.  Do:

```
Web3 = require("web3")
web3 = new Web3("http://localhost:8545/")
await web3.eth.getBlock("latest")
```

You will see that the `baseFeePerGas` field is returned as a hexadecimal string rather than any of the possibilities above.

#### Logs

```
> await web3.eth.getBlock("latest")
{
  baseFeePerGas: '0x3b9aca00',
  difficulty: '1',
  extraData: '0x0000000000000000000000000000000000000000000000000000000000000000e136d1f0e70b67d39719a234df75ca7ad60313410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  gasLimit: 11500000,
  gasUsed: 0,
  hash: '0xb0da7449ddcfd6a2a452464fc7ac58e9ec0be13cbbd3861b0a69498e90f25d9a',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  miner: '0x0000000000000000000000000000000000000000',
  mixHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  nonce: '0x0000000000000000',
  number: 0,
  parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  size: 627,
  stateRoot: '0x9f3a58bdd7a3fd28c637dc5d94dc07aee2226ccea79bbadb60b9093ac299357e',
  timestamp: 0,
  totalDifficulty: '1',
  transactions: [],
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  uncles: []
}
```

#### Environment

Geth: 1.10.6-stable-576681f2
Web3.js: 1.5.2
Npm: 6.14.11
Node.js: v12.21.0

**Comment by Spacesai1or** [comment]
This is a simple fix, however I'm slightly concerned being that this is technically a breaking change

**Comment by philknows** [comment]
@spacesailor24 Once you have the PR, can we connect it and discuss as mentioned in today's call? Thanks. cc: @jdevcs to follow up on best way forward due to potential breaking change.

**Comment by 3alpha** [comment]
Related to this issue, in Typescript you can't access `(await web3.eth.getBlock(londonBlockNumber)).baseFeePerGas` property because:
```
Property 'baseFeePerGas' does not exist on type 'BlockTransactionString
```


As a quick fix I just added that property [here](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth/types/index.d.ts#L397) and I just wanted you to be aware.

**Comment by philknows** [comment]
This breaking change is being pushed to the next release (1.5.4) to not interfere with the already released 1.5.3-rc0.

**Comment by haltman-at** [comment]
Not stale, unless it's already done and wasn't properly closed.

**Comment by haltman-at** [comment]
Not stale, unless it's already done and wasn't properly closed.

**Comment by kfazil** [comment]
What is the returned unit for baseFeePerGas? Is it wei or Gwei?

**Comment by gordilovvv** [comment]
> 
Wei

**Comment by AlexandraC0DE** [comment]
`node --experimental-repl-await
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> Web3 = require("web3")
Uncaught Error: Cannot find module 'web3'
Require stack:
- <repl>
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15
)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
> web3 = new Web3("http://localhost:8545/")
Uncaught ReferenceError: Web3 is not defined
> await web3.eth.getBlock("latest")
Uncaught ReferenceError: web3 is not defined
    at REPL3:1:16

`
