### ISSUE TITLE
access to member variable should not  trigger side effects (rpc call)

### ISSUE THREAD

**Issue by wighawag** [ethereum/web3.js#433]
currently  web3 does rpc call on member access (like eth.accounts). This is annoying and should be avoided.
I suggest getting rid of the synchronous api all together but getting rid of these side effect in member variable would be a minimum.

my main motivation for writing this issue come from my use of a test library that pretty print assert values. This triigger the rpc call when doing so.

**Comment by frozeman** [comment]
Done in web3.js 1.0
