### ISSUE TITLE
Migrate validation utils functions from 1.x

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4351]
### Description

Migrate the following functions form `web3-utils` 1.x branch. 

- isHex
- isHexStrict
- isBloom
- isUserEthereumAddressInBloom
- isContractAddressInBloom
- isTopic
- isTopicInBloom
- isInBloom
- compareBlockNumbers
- checkAddressChecksum

### Acceptance Criteria

- All the functions mentioned above should migrated 
- All the functions must be covered with their unit tests 

### Additional Information

- Don't use `BigNumber` where needed instead use native `BigInt`

**Comment by Spacesai1or** [comment]
We probably don't need to support `isBN`, `isBigNumber`, and `toBN`, but we should make a decision now if we're going to support them otherwise we should make a note that we're dropping support for these methods in `4.x` (so we remember when making the migration guide)
