### ISSUE TITLE
Refactor Labels for issues and PRs

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4358]
We should reduce the labels as much as possible to make it easier to label something, and to reduce spread amongst many labels

Suggested labels:

- Bug (Something isn't working)
- Documentation (Improvements or additions to documentation)
- Duplicate (This issue or pull request already exists)
- Feature Request (New feature request or improvement)
- Good First Issue (Good for newcomers)
- Help Wanted (Extra attention is needed)
- Invalid (This doesn't seem right)
- Discussion (Question or something that needs to be discussed)
- Needs Clarification (Not enough info provided)
- Wont Fix (This will not be worked on)
- On Ice (Important, but not actively worked on)
- 1.x (1.x related)
- 4.x (4.x related)
- Release (Is a release pull request)

We also need to determine which tags should be applied to keep StaleBot from marking the issue/PR stale

**Comment by philknows** [comment]
@mconnelly8 @jdevcs Would suggest keeping this open for reorganising the repo.
