### ISSUE TITLE
eth.sendTransaction() does not send type 2 EIP 1559  transaction from node.js

### ISSUE THREAD

**Issue by david03g** [ethereum/web3.js#4364]
#### Expected behavior

  ```
 WEB3.eth.sendTransaction({
            from: address,
            to: to,
            value: value,
            type:'0x2',
            gas: 21000,
            maxFeePerGas: maxFeePerGas,
            maxPriorityFeePerGas: maxPriorityFeePerGas,
        })
```

EIP 1559 type 2 transactions sends perfectly from browser environment but not from node.js. 

#### Actual behavior

Only type 0 (legacy) transaction is sent.

#### Environment

truffle/hdwallet-provider@1.4.1
node.js@12
web3.js@1.5.2

Goerli test network

**Comment by jdevcs** [comment]
@david03g could you check and verify? , Seems related with [this](https://github.com/ChainSafe/web3.js/issues/4261#issuecomment-913526007)

**Comment by david03g** [comment]
@jdevcs it was related to that issue. Replacing @truffle/hdwallet-provider fixed the problem.

```
const wsProvider = new Web3.providers.WebsocketProvider('wss://...');
const web3 = new Web3(wsProvider);
web3.eth.accounts.wallet.add(web3.eth.accounts.privateKeyToAccount('0x' + <private key>)); 
```
