### ISSUE TITLE
bignumber.js dependency breaks some frontend js compilers

### ISSUE THREAD

**Issue by dalexj** [ethereum/web3.js#437]
the bignumber.js `"main"` field in its package.json is incorrect. I've submitted a PR to the fork to fix this. (https://github.com/debris/bignumber.js/pull/1). I'm using brunch to build my frontend javascript which completely breaks for this package since that main file is not found. can I get some attention to make this change?

**Comment by frozeman** [comment]
Please test with the lastest web3.js 1.0
