### ISSUE TITLE
web3.providers-http: ETH2 Style JSON RPC Schema support

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4374]
[ETH2 Style JSON RPC Schema](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon)

- `GET` requests with URL parameters
    ```typescript
    `http://127.0.0.1/eth/v1/beacon/states/${state_id}/validators/${validator_id}`
    ```
- `POST` requests with URL parameters and request body
    - [Publishing a signed block](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/publishBlock)
    - [Submit attestation](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/submitPoolAttestations)
    - [Submit attester slashing](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/submitPoolAttestations)

**Comment by philknows** [comment]
Outstanding issue to be discussed later. Need to further investigate provider architecture.
