### ISSUE TITLE
How to encrypt/decrypt large data with the wallet's AES key?

### ISSUE THREAD

**Issue by markg85** [ethereum/web3.js#4378]
Hi,

I made a website ([link](https://imagecompare.sc2.nl/)) that allows one to decrypt images given that the person knows:

- The decryption key
- The image CID (all of this is hosted on IPFS, CID's are the norm on that site)

This logic works just fine. A user can locally (with openssl) create encrypted files, store it on IPFS and then open it on that site with the key and cid of that image (+ the initialization vector).

(case 1) When "sending" images from person A to B this logic is fine.
(case 2) When making images available for yourself but online then the key is annoying to supply every time.

Now for that second case i'm trying to have the key be either stored or generated from web3. I want to "login" on that website with metamask and have that supply my AES key for decrypting images.

Or alternatively and more general. How can i "link" some data in web3 that is encrypted by my web3 public key. My thinking here is to generate a AES key and encrypt that key itself using the public key of my web3 eth account.

I know for sure that the encryption/decryption of a little piece of text is possible as shown [here](https://metamask.github.io/test-dapp/).

Cheers,
Mark

**Comment by nazarhussain** [comment]
Hi @markg85 I am not sure if question is really related to `web3` as its not an encryption/decryption library. The example you shared is clearly explaining it well. It's using [tweetnacl](https://tweetnacl.js.org/#/) library under the hood. I can suggest you to explore JS API [readAsBinaryString](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString) and then encrypt it with `tweetnacl`.

For generating public key, I believe `web3` can't help you there either. Its a particular API of the Metamask [eth_getEncryptionPublicKey](https://docs.metamask.io/guide/rpc-api.html#eth-getencryptionpublickey) that you can call and get public key form Metamask. 

I hope I answered to your questions, let us know if there is any thing particular related to `web3` we can help you further.

**Comment by markg85** [comment]
Hi @nazarhussain, thank you for your reply!
I do fear we have a bit of a miscommunication here.

There seems to be a lot of overlap here in the extremely thin line between web3 and metamask/eth. Both have encryption and decryption methods. Both have a slew of eth methods (why does web3 even have eth? look at [web3.eth](https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html) and all the other web3/eth* methods, why isn't web3 a general abstract library?). I get the Metamask/eth binding as the wallet is literally developed for ethereum. I don't get the web3+eth binding, it makes it all so super vague.

To me it's therefore **really difficult** to know where a question belongs.

My [example](https://imagecompare.sc2.nl/) already demonstrates that i can decrypt just fine.
Note: in the following i say "wallet" but in my mind it might as well be "web3", it makes no difference to me hence showing the vagueness in wallet and web3.

What i'm looking for is how to let my wallet be the "owner" of my AES key? How can i ask my wallet: "give me my AES128 key"? Or if that's not possible, how can i "ask my wallet to give/generate me a new AES128 key"? Lastly, if i have a key, how can i tie my wallet and the AES keys together? I want to get a key (or the keys) that i know belongs to me.

As for "tie my wallet and the AES128 keys together", i probably do know - conceptually - how that's done. It's probably generating a new AES128 key which is then encrypted by the wallet's public key. The result of that encryption should then be signed by the private key. The total package of "the key" would contain the encrypted key and the sign which can be verified by my public key. Hence kind of tying the AES128 key to my keypair.

Please do not refer me to encryption libraries! I roughly understand how encryption and decryption works, how else could i have made my example work otherwise. The complexity i'm facing is when i'm combining this with web3 and a wallet. And i **want** a wallet because that is my entry point to web3 (and have access to ethereum). Once i login i want to have access to "my keys" and use them to decrypt the images on that site.

**Comment by nazarhussain** [comment]
@spacesailor24 Can you guide us here in this question?

**Comment by jdevcs** [comment]
Its not directly in web3.js scope .
As I understood  @markg85 wants asymmetric encryption of AES keys using web3 generated account.

So you should encrypt AES128 key with receivers public key, and send encrypted AES128 key on wire etc, After that receiver can decrypt it using his private key.

**Comment by markg85** [comment]
> So you should encrypt AES128 key with receivers public key, and send encrypted AES128 key on wire etc, After that receiver can decrypt it using his private key.

Ahh, that makes more sense! Thank you for that hint!

I can in fact use such a key in native browser constructs (crypto.subtle.importKey) to encrypt and decrypt AES128 data. I do think those crypto.subtle primitive are (pun intended) really primitive. There are much more encrypt ways and options that are totally missing there. It would be so awesome if support for more advanced primitives were to be available in web3?!

Oh well, that's a question for another time. And potentially not even for web3 but for some browser standard discussion. Not something i'm going to worry about now :)
