### ISSUE TITLE
[REDACTED]

### ISSUE THREAD

**Issue by SaulMoonves** [ethereum/web3.js#4389]
[REDACTED]

**Comment by SaulMoonves** [comment]
It looks like I can change the digit immediately to the right of the colon and whatever it is between the two strings, the hash comes out the same.

**Comment by fafrd** [comment]
Issue appears to be with the eth-lib library web3 is using:
https://github.com/MaiaVictor/eth-lib/blob/master/lib/hash.js#L317-L319

This library checks if the string is a hex string in a very simple way, it just checks 
```
  if (str.slice(0, 2) === "0x") {
    msg = [];
    for (var i = 2, l = str.length; i < l; i += 2) msg.push(parseInt(str.slice(i, i + 2), 16));
```
but the string isn't actually hex, so parseInt incorrectly interprets the string.

**Comment by SaulMoonves** [comment]
I see, so ":[digit]" was being pushed as NaN which is why any combination had the same hash.

**Comment by fafrd** [comment]
More generally, the issue is that, if the string starts with `0x`, any non-hex can be substituted with other non-hex characters, and the hash will be the same.

For example, the Web3Utils.sha3 hash of `0xzzz` is the same as the hash of `0xqqq`.
