### ISSUE TITLE
Synchronous XMLHttpRequest warning in Chrome

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/web3.js#44]
Running the balance.html example, I get the following warning in Chrome 40.0.2214.91 on OSX:

```
httpsync.js:62
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects
to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

**Comment by debris** [comment]
we are aware of it and we will keep an eye on it. wontfix for now

**Comment by caktux** [comment]
Why force the use of a deprecated standard? Might have been a good idea to keep async requests after all.

**Comment by tcoulter** [comment]
+1 for async requests across the board. Synchronous requests will stall all javascript execution until they complete, halting user interfaces and web servers (say, when used within Node).

**Comment by tcoulter** [comment]
For all those interested, I wrote a wrapper around some of the important pieces of web3.js that only makes asynchronous calls. Check it out here: https://github.com/tcoulter/Web3RPC

I'd be more than happy to integrate this work into web3.js proper.

**Comment by debris** [comment]
all requests should have async versions by now.  I'm closing this issue.

**Comment by tcoulter** [comment]
There doesn't appear to be callback functions when making calls using the contract abstraction. i.e., 
```
var result = myContractInstance.myConstantMethod('myParam');
```
From: https://github.com/ethereum/wiki/wiki/JavaScript-API#example-43

This is super important in the browser for snappy user interfaces, but also when using web3 in node as there's a pesky bug that blocks making any synchronous calls (and instead your app hangs). Am I just missing documentation?

Would definitely push for this if it doesn't exist. Detecting a callback function the last parameter would be a great solution.

**Comment by tcoulter** [comment]
See this note under "Known Issues" with the XMLHttpRequest library web3 is using (https://github.com/driverdan/node-XMLHttpRequest):

> Synchronous requests freeze node while waiting for response (But that's what you want, right? Stick with async!).

**Comment by debris** [comment]
>Would definitely push for this if it doesn't exist. Detecting a callback function the last parameter would be a great solution.

It's already implemented. Documentation needs to be updated.
