### ISSUE TITLE
async version of isConnected missing

### ISSUE THREAD

**Issue by wighawag** [ethereum/web3.js#440]
It would be nice to have an async version of isConnected

**Comment by frozeman** [comment]
The isConnected is not part of web3.js 1.0 anymore, we might add one back. i need to think about it

**Comment by naddison36** [comment]
@frozeman so there is no way to check the connection was established before sending a transaction?

I've written a small node.js cli using Web3 1.0 to issue tokens to members of a Meetup group. Ideally, I want to detect connection failures in the following line before I try a send transaction to deploy a contract or issue tokens to members
https://github.com/SydEthereum/meetup-token/blob/master/src/transferableToken.ts#L34
