### ISSUE TITLE
Events: new contract deployed

### ISSUE THREAD

**Issue by maraboo-afk** [ethereum/web3.js#4402]
Hey. I'm looking for a way to build a mempool listener for the all new contracts deployed. Is there any way to get something like this?

```
...
[block #77777]
contract 0x123..... created at tx 0x987....
...
...
...
[block #77780]
contract 0x456..... created at tx 0x654....
...
```

**Comment by spacesailor24** [comment]
Hi there, if you opened this to describe an issue you are facing, can you provide more detail? A code example or test repo would be very helpful

**Comment by Spacesai1or** [comment]
So if I'm not mistaken, observing the mempool is going to specific to the node you're connected to (different nodes might have a different set of transaction in their mempool). Additionally, a transaction sitting in the mempool hasn't been mined and is therefore not part of a block. To get the output you mentioned, you'd need to wait for the transaction to be mined

I've put together an [example](https://github.com/spacesailor24/web3-4402-deployed-contracts) of how to do what you've requested. It's definitely not the most performant approach, but [here's](https://gist.github.com/ross-p/bd5d4258ac23319f363dc75c2b722dd9) something that might provide inspiration if you choose to develop this further
