### ISSUE TITLE
Web3.utils._ undefined

### ISSUE THREAD

**Issue by JahanzebNawaz** [ethereum/web3.js#4403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was testing Web3 utils and in documents [Web3.utils._](https://web3js.readthedocs.io/en/v1.5.2/web3-utils.html#id2), it is specified about underscore library, but while testing it seems we don't have underscore library in package anymore. 
`Web3.utils._;` returns `undefined` 
I have gone through the utils file in the package couldn't find the **underscore** library imported or mentioned. 

As per this issue [2282](https://github.com/ChainSafe/web3.js/issues/2282) it seems the underscore library is no more in use. changed to lodash. 

### Expected Behavior

As per the documents, it should be present and in working condition. if it's deprecated please update the documents.

### Steps to Reproduce

Need to update documents if the library is deprecated.  

### Web3.js Version

1.5.3

### Environment

- Operating System: Ubuntu 21.04
- Browser:   Firefox Browser 92.0 (64bit). 
- Node.js Version: v12.21.0
- NPM Version: 7.20.5

**Comment by luu-alex** [comment]
We removed the underscore package recently and web3.utils._ should be removed from the docs, thank you for pointing this out :)

**Comment by JahanzebNawaz** [comment]
Thanks, @luu-alex for the confirmation.

**Comment by JahanzebNawaz** [comment]
@luu-alex I updated the docs and tried to push but it seems I need to get permission first? is there any way to get permission I want to be part of the community?
Thanks

**Comment by nazarhussain** [comment]
@JahanzebNawaz You have to fork the repo and then make changes to it and create a pull request agains the our repo. For further details you can can check [this link](https://www.dataschool.io/how-to-contribute-on-github/).  You should also look our [contribution guide](https://github.com/ChainSafe/web3.js/blob/1.x/CONTRIBUTIONS.md) for more details.

**Comment by JahanzebNawaz** [comment]
Thanks, @nazarhussain
