### ISSUE TITLE
npm install --save web3 not working 

### ISSUE THREAD

**Issue by akshaymohan29** [ethereum/web3.js#4404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PS C:\Users\AKS> npm install --save web3
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\AKS\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'C:\Users\AKS\node_modules\is-number-object\LICENSE'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'C:\\Users\\AKS\\node_modules\\is-number-object\\LICENSE'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\AKS\\node_modules\\cids',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'C:\Users\AKS\node_modules\cids\dist\index.js'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'C:\\Users\\AKS\\node_modules\\cids\\dist\\index.js'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\AKS\\node_modules\\ethjs-unit',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'C:\Users\AKS\node_modules\ethjs-unit\dist\ethjs-unit.js.map'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'C:\\Users\\AKS\\node_modules\\ethjs-unit\\dist\\ethjs-unit.js.map'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm notice
npm notice New patch version of npm available! 7.24.0 -> 7.24.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.24.1
npm notice Run npm install -g npm@7.24.1 to update!
npm notice
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AKS\AppData\Local\npm-cache\_logs\2021-09-29T13_18_18_504Z-debug.log
PS C:\Users\AKS> npm install -g npm@7.24.1^C
PS C:\Users\AKS> npm install -g npm@7.24.1

added 4 packages, and audited 37 packages in 16s

found 0 vulnerabilities

### Expected Behavior

install web3

### Steps to Reproduce

npm install --save web3

### Web3.js Version

latest

### Environment

- Operating System: windows10
- Browser: brave Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)
- Node.js Version: v16.10.0
- NPM Version: 7.24.0

**Comment by nazarhussain** [comment]
We just published `1.6.0` release and I tried tried it on Mac and Windows 10 and it works fine. From the error messages it seems like some permission issue with your machine. Please try out with latest version or would be nice to also try one different machine. 

I am closing this issue for now, if you can reproduce this issue on different machine as well, feel free to reopen with more insights.
