### ISSUE TITLE
Consider ethereumjs-abi as a dependency instead of internal encoder

### ISSUE THREAD

**Issue by axic** [ethereum/web3.js#441]
It aims to be a lightweight ABI implementation and could replace the internal Solidity coder. Also supports Serpent type notation and Solidity's tight packing methods (`sha3(1, "hello", 0x1234)`).

It is currently used in browser-solidity for decoding response values.

**Comment by frozeman** [comment]
I will take a look at this once i get to the decoder.

**Comment by nivida** [comment]
I've closed this issue because we are using now the ABICoder of ethers.js.
