### ISSUE TITLE
Missing RPC methods throw an exception

### ISSUE THREAD

**Issue by axic** [ethereum/web3.js#442]
```
> web3.personal.listAccounts(function(err, res) { console.log(err, res); }))

web3.min.js:1 Uncaught Error: The method personal_listAccounts does not exist/is not available(…)
e.exports.InvalidResponse @ web3.min.js:1
s.send @ web3.min.js:2
(anonymous function) @ web3.min.js:2
(anonymous function) @ VM4856:2
InjectedScript._evaluateOn @ (program):878
InjectedScript._evaluateAndWrap @ (program):811
InjectedScript.evaluate @ (program):667
```

while other errors are properly sent back via the callback:

```
> web3.eth.getAccounts(function(err, res) { console.log(err, res); })

VM4794:2 Error: no keys in store(…) undefined
```

I think it would make sense not throwing an exception, but sending back the error.

**Comment by axic** [comment]
Now I see that `listAccounts` was executed via the synchronous `send`, while `getAccounts` was executed via `sendAsync`.

@frozeman do you see a reason why that would happen?

**Comment by axic** [comment]
I see, `listAccounts` is a property and is therefore synchronous. I should call it with `getListAccounts`.

I think this is a bit counter intuitive and should be documented.

**Comment by frozeman** [comment]
Please test with 1.0 again
