### ISSUE TITLE
Feature request: Get state *within* a block by also providing txIndex along with blockNumber

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/web3.js#4421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

For my purposes, getting a value from the chain (with "call()") by specifying the blockNumber isn't sufficient as there are often several transactions within the same block (bot action or w/e). 

I need to get the state of the variable at a specific txIndex. Getting the value after the entire block has been processed is no good because the variable I want to read could have changed by then.

Could we make it possible within "call()" to specify blockNumber=X as well as txIndex=Y?

### Use Cases

I need to read the state of my contract storage after each transaction in order to read the new state and find out how the transasction changed the state from the last state capture. Currently the web3.js library only allows reading state at the end of each block.

### Implementation Ideas

Probably blockNumber=x and txIndex=y, but blockNumber.txIndex (where txIndex is padded with some safe number of zeros) could also work, I guess?

### Are you willing to implement this feature?

- [ ] Yes

**Comment by cyrusadkisson** [comment]
call(txHash) would also be sufficient

**Comment by nazarhussain** [comment]
Hi @cyrusadkisson. That seems to be a nice feature. I am moving this request to further discussion, but as our current priority is 4.x rewrite so we may not able to respond to this request soon and not in 1.x in any case. After the 4.x rewrite we will look into feasibility for this feature and then schedule.
