### ISSUE TITLE
Feature request: read bytes from string field, regardless of UTF-8 validity

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/web3.js#4422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

Add a parameter to call() that enables getting the raw hex data of a string field, if the caller so chooses

### Use Cases

I'm trying to make use of a string field on my contract that was deployed years ago by writing and reading hex bytes to it.

By carefully assembling the raw hex string for the transaction, I can get the data onto the chain just fine.

The problem is reading the data with web3.methods.myMethod(params).call()... this function returns an error becuase it (correctly) sees invalid UTF-8 data.

But I don't care about that. I just want the bytes.

Can we add a parameter to call() that allows the caller to get the raw hex data, if they so choose?

### Are you willing to implement this feature?

- [ ] Yes

**Comment by nazarhussain** [comment]
I am not sure if that's possible, or even feasible to include as a feature. The behaviour of decoding binary data is tightly integrated with the ABI interface of your contact. We will discuss further to include this as a feature after 4.x rewrite. 

For now, try changing the ABI interface to treat that field as raw bytes before `call()` and see if it works.
