### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Morinohtar** [ethereum/web3.js#4425]
Please update the documentation.

It's missing the v1.5.3, v1.5.6 and v3.0.0 (final). They might be a bit different so...

Thanks

**Comment by luu-alex** [comment]
Thank you for noticing the missing documentation, v 3.0.0 is still in the drafts so the final documentation will be updated as soon as its released. I'll see if I can update v1.5.3 as well we dont have a v1.5.6

**Comment by luu-alex** [comment]
Hello thank you for making this issue. a dependancy for readthedocs updated, causing a bug and our latest build versions to fail (1.5.3, 1.6.0, 1.6.1...) Fortunately only `1.6.1` introduced new [documentation](https://github.com/ChainSafe/web3.js/releases/tag/v1.6.1). We wont have documentation available for the failed versions, but we have merged a fix and for any future releases new documentation will be built succesfully.
