### ISSUE TITLE
string of numbers to bytes32 conversion?

### ISSUE THREAD

**Issue by bl4ck5un** [ethereum/web3.js#444]
I notice that when sending transactions in web3js, strings of numbers are encoded to bytes as if they're numerical values. For example: "32884794" is encoded as 0x1f5c83a. But in some cases, I want "32884794" to be a string, whose the "correct" encoding #should be "0x3332383834373934".

This seems to stem from `web3.toHex`, 

```
> web3.toHex("32884794")
"0x1f5c83a"
> web3.toHex("a32884794")
"0x613332383834373934"
```

Is there a way to control the encoding? If no, I think this could be considered as a bug.

Fan

**Comment by bl4ck5un** [comment]
Any thought on this issue?

**Comment by frozeman** [comment]
toHex is only used in one place in the new web3.js 1.0 and thats for auto detection of `web3.utils.soliditySha3`. So i assume we can close this. Please reopen if that still an issue.

**Comment by bl4ck5un** [comment]
But I don't think my original question gets answered. Do you suggest we use other functions than `toHex` to convert values to hex strings?

**Comment by frozeman** [comment]
yes all the util conversion functions you can find here: http://web3js.readthedocs.io/en/1.0/web3-utils.html

**Comment by bl4ck5un** [comment]
@frozeman good to know. Thanks!
