### ISSUE TITLE
web3.eth.getPendingTransactions doesn't work

### ISSUE THREAD

**Issue by zeleniy** [ethereum/web3.js#4441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
# node src/resubmit.js 
(node:249) UnhandledPromiseRejectionWarning: Error: Returned error: The method eth_pendingTransactions does not exist/is not available
    at Object.ErrorResponse (/root/ethereum-app/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /root/ethereum-app/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/root/ethereum-app/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/ethereum-app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/root/ethereum-app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/root/ethereum-app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/root/ethereum-app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior

Should work as [defined in docs](https://web3js.readthedocs.io/en/v1.3.6/web3-eth.html#getpendingtransactions).

### Steps to Reproduce

```
web3.eth.getPendingTransactions().then(console.log);
```

### Web3.js Version

1.3.6

### Environment

```
# npm list --depth=0
ethereum.udiar.net@1.0.0 /root/ethereum-app
+-- commander@7.2.0
+-- ethereumjs-tx@2.1.2
+-- keythereum@1.2.0
+-- moment@2.29.1
+-- properties-reader@0.3.1
+-- sprintf-js@1.1.2
`-- web3@1.3.6
```

**Comment by nazarhussain** [comment]
@zeleniy As the error describes `The method eth_pendingTransactions does not exist/is not available`, which means the RPC method `eth_pendingTransactions` is not supported by the provider you are connected to. You didn't described which service you are connected to or you are connected to a local node. I assume here that you are using Infura which does not support this RPC method. 

Try using the `pendingTransactions` subscription with Infura and see if it works for your use-case. 

https://web3js.readthedocs.io/en/v1.5.0/web3-eth-subscribe.html#subscribe-pendingtransactions

**Comment by nazarhussain** [comment]
@zeleniy Did you tried using `pendingTransactions` subscription to get through this issue? We look forward to your response.

**Comment by zeleniy** [comment]
As i can understand `pendingTransactions` subscription should be loaded as daemon or background process. And it will not  fire any events fot txs which already are pending. So i don't want to register any handlers. I just want to know if i have any pending txs.

> The method eth_pendingTransactions does not exist/is not available

Yes, i use Infura. And i don't think they developed their own software for Ethereum interaction. But it doesn't matter. Looks like `eth_pendingTransactions` implemented nowhere.

Sake of the problem is that sometimes i send txs to Ethereum. And sometimes they are hangs in pending status. When you have pending tx you can't send any more txs until that one will be canceled, dropped or resended with higher gas fees. So before sending next one tx i want to know have i any pending tx. Just like:
```
web3.eth.getPendingTransactions().then((pendingTx) => {
  if (pendingTx) {
    // cancel that pendingTx
  }

  // send new tx
});
```
But i have no tool to detect pending txs and no tool to cancel them... i can't wait 5 days before Ethereum drop the tx by itseslf.

**Comment by nazarhussain** [comment]
Unless `eth_pendingTransactions` is supported by the provider you are using the `web3.eth.getPendingTransactions` would not return any thing helpful. 

The problem you described is more of the implementation technique. Any transaction you sent to the network, you must keep track of their hash as well as nonce and watch for their confirmations. You can use local storage or any other storage for that purpose and don't remove that list unless you are sure that transaction is submitted. It's pretty easy to check if a transaction is confirmed or not. Mover over you can subscribe to `pendingTransactions` before sending the transaction. This will also help to track the any transaction stuck in the network. 

In not difficult to cancel (a.k.a. replace) a transaction, just need to send a tx with same nonce but higher gas fee. Check the following [article](https://info.etherscan.com/how-to-cancel-ethereum-pending-transactions/) for more details. 

As this issue does not highlight any bug related to `web3` library, so I am closing it. If you found more insights to it directing it a bug, feel free to reopen the issue.

**Comment by ttodua** [comment]
> @zeleniy As the error describes `The method eth_pendingTransactions does not exist/is not available`, which means the RPC method `eth_pendingTransactions` is not supported by the provider you are connected to. You didn't described which service you are connected to or you are connected to a local node. I assume here that you are using Infura which does not support this RPC method.
> 
> Try using the `pendingTransactions` subscription with Infura and see if it works for your use-case.
> 
> https://web3js.readthedocs.io/en/v1.5.0/web3-eth-subscribe.html#subscribe-pendingtransactions

Can you please tell from your experience, for BSC (`https://bsc-dataseed1.binance.org:443`) which method would you use to get pending transactions?
