### ISSUE TITLE
Add/update license headers for the new files and add linting rule

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

1. For the `4.x` rewrite all the new files are missing license headers. We need copy the license from `1.x`
2. If possible add a linting rule to verify every file must contain a license header. 

### Use Cases

To avoid any file to be committed without license headers it's better to add a linting rule. 

### Implementation Ideas

https://github.com/Stuk/eslint-plugin-header

### Are you willing to implement this feature?

- [X] Yes

**Comment by mconnelly8** [comment]
Already implemented.
