### ISSUE TITLE
Bring web3 sha3 API in line with Solidity sha3

### ISSUE THREAD

**Issue by jtremback** [ethereum/web3.js#445]
I had to spend a lot of time figuring out how to get sha3 to produce the same hashes in web3 and in my contracts. I think we should consider giving them both the same API. Here is a function that should do it:

```
function solSha3 (...args) {
    args = args.map(arg => {
        if (typeof arg === 'string') {
            if (arg.substring(0, 2) === '0x') {
                return arg.slice(2)
            } else {
                return web3.toHex(arg).slice(2)
            }
        }

        if (typeof arg === 'number') {
            return leftPad((arg).toString(16), 64, 0)
        } else {
          return ''
        }
    })

    args = args.join('')

    return '0x' + web3.sha3(args, { encoding: 'hex' })
}
```

**Comment by jtremback** [comment]
Needs something for BigNumber.js, probably.

**Comment by ethers** [comment]
related #226

**Comment by elenadimitrova** [comment]
+1

**Comment by ethers** [comment]
If `web3.sha3` is going to start returning the "0x", perhaps it could be done by an extra parameter to `web3.sha3`, to avoid breaking existing stuff (which add the "0x" themselves already).

**Comment by jtremback** [comment]
That's a valid concern, but honestly at some point you just have to correct blatant errors with a breaking update.

**Comment by graup** [comment]
This change is VERY needed! I just spent hours trying to find out how to do this.

The function given is good, but to make it work with negative numbers, I had to change the 'number' handling to this:

```
        if (typeof arg === 'number') {
            if (arg < 0) {
              return leftPad((arg >>> 0).toString(16), 64, 'F');
            }
            return leftPad((arg).toString(16), 64, 0);
        }
```

**Comment by raineorshine** [comment]
I took the suggestions from this issue and wrapped them all up into an npm library:
https://github.com/raineorshine/solidity-sha3

Here's the source code in its entirety:

```js
import Web3 from 'web3'
import leftPad from 'left-pad'
const web3 = new Web3()

// the size of a character in a hex string in bytes
const HEX_CHAR_SIZE = 4

// the size to hash an integer if not explicity provided
const DEFAULT_SIZE = 256

const isHex = val => val.toString().slice(0, 2) === '0x'

/** Encodes a values in hex and adds padding to the given size if needed. Curried args. */
const encodeWithPadding = size => value => {
  return typeof value === 'string' && !isHex(value)
    // non-hex string
    ? web3.toHex(value)
    // numbers, big numbers, and hex strings
    : leftPad(web3.toHex(value >>> 0).slice(2), size / HEX_CHAR_SIZE, value < 0 ? 'F' : '0')
}

/** Hashes one or more arguments, using a default size for numbers. */
export default (...args) => {
  const paddedArgs = args.map(encodeWithPadding(DEFAULT_SIZE)).join('')
  return web3.sha3(paddedArgs, { encoding: 'hex' })
}

/** Hashes a single value at the given size. */
export const sha3withsize = (value, size) => {
  const paddedArgs = encodeWithPadding(size)(value)
  return web3.sha3(paddedArgs, { encoding: 'hex' })
}
```

**Comment by u2** [comment]
Great!

**Comment by axic** [comment]
This is actually implemented in [ethereumjs-abi](https://github.com/ethereumjs/ethereumjs-abi) too:

```js
var abi = require('ethereumjs-abi')
var BN = require('bn.js')

abi.soliditySHA3(
    [ "address", "address", "uint", "uint" ],
    [ new BN("43989fb883ba8111221e89123897538475893837", 16), 0, 10000, 1448075779 ]
).toString('hex')
```

**Comment by raineorshine** [comment]
@axic Thanks... kind of a bummer to have done duplicate work, but I'm glad to know. I'll make a note to myself to find what docs this should go in so that it is not so secret. None of us on the gitter channel were aware of this.

**Comment by axic** [comment]
@raineorshine It was no secret, it was there since last November :)

I think I've linked to it on stackexchange.

**Comment by raineorshine** [comment]
If I ask about sha3 on gitter, StackExchange, google it, write a library
for it, publish it, and THEN hear about this from one person, then yes, for
the purpose of OSS, it is basically a secret :). So, I respectfully
disagree.

**Comment by Schaeff** [comment]
Hey, why can't we merge this into `web3`? :)

**Comment by frozeman** [comment]
Can someone explain me the issue better?
So currently sha3 is simply taking anything and sha3 it with no special treatment.
You guys say we should convert input data before to EVM abi before having it?

**Comment by frozeman** [comment]
Here it is: http://web3js.readthedocs.io/en/1.0/web3-utils.html#soliditysha3

**Comment by raineorshine** [comment]
Thanks Fabian!

**Comment by elenadimitrova** [comment]
@frozeman I noticed the `soliditySha3` reuses `ethjs-sha3` library which is marked defunct
https://www.npmjs.com/package/ethjs-sha3 
Is this intentional?

**Comment by speakerwiggin** [comment]
@frozeman are there any plans to support array hashing before 1.0 is out of beta?

**Comment by saveriocastellano** [comment]
[https://github.com/raineorshine/solidity-sha3/issues/9](url)

**Comment by blueto01h** [comment]
@saveriocastellano try the solution with ethereumjs-abi, works like a charm.
