### ISSUE TITLE
getPastEvents always return empty array in case invalid RPC

### ISSUE THREAD

**Issue by duongvansang** [ethereum/web3.js#4450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I try to get past events from my contract,
I realized that even I set to web3js and invalid RPC URL, it still returns right again empty list before invalid response error is throw

It should throw errors for this case and need to wait until has response or timeout from RPC.

### Expected Behavior

no response, throw timeout or Invalid RPC response

### Steps to Reproduce

```
let web3 = new Web3('Invalid RPC URL')
let contract = new web3.eth.Contract(abi, address);
let events = await contract.getPasstEvent('MyEvent', {from: , to: });

console.log(events) --> always return events = [], right away.

```

### Web3.js Version

1.6.0

### Environment

node.js version: v12.22.2

**Comment by nazarhussain** [comment]
I tried with a working script but not for `getPastEvent` and got following error `Error: connection not open on send()`. 

Can you please share the reproducible script or the ABI you are using that will be helpful to investigate further.
