### ISSUE TITLE
"Uncaught TypeError: o.data.substring is not a function" calling a contract function reverting

### ISSUE THREAD

**Issue by nicos99** [ethereum/web3.js#4454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get an "*Uncaught TypeError: o.data.substring is not a function*" In the console of my internet browser  when I **call()** a contract function that revert due to an `require` not satified, using `handleRevert = true` and web3.js version >= 1.2.10 (ok until 1.2.9, still nok with 1.5.2).

For instance `rocketContract.methods.SetSpeed(101).call()` with this extract of the contract :
```sol
function SetSpeed(uint _speedPercent) public {
        require(_speedPercent <= 100, "speed invalid");
        speed = _speedPercent;
    }
```
In addition I can not intercept the exception in my code.

Complete call stack with web3.js 1.5.2 :
```
Uncaught TypeError: o.data.substring is not a function
    o index.js:630
    n index.js:172
    onreadystatechange index.js:111
    send index.js:99
    send index.js:187
    h index.js:763
    n index.js:797
    _executeMethod index.js:945
    CallSetSpeed call-revert-bug-v2.1.html:121
    onclick call-revert-bug-v2.1.html:1
```

### Expected Behavior

I can catch an exception and get the revert raison. Until version 1.2.9 we get `Returned error: VM Exception while processing transaction: revert speed invalid` using this code :
```js
rocketContract.methods.SetSpeed(speed).call()
	.then(txt => {
		alert("Call SetSpeed() ok, send is likely to succeed");
	})
	.catch(err => {
		console.error(err);
    		alert("Call SetSpeed() error ! send is likely to failed\n" + err.message);
  	});
```

### Steps to Reproduce

1. run a local Ganache instance,
2. copy this web page on a webserver: [call-revert-bug-v2.1.html ](https://gist.github.com/nicos99/f197c5c8257272c04339a5cc1cd4dfc6#file-call-revert-bug-v2-1-html),
3. got to the webpage and open your browser's console (F12),
4. clic on the "Init" button,
5. set speed above 100 in the input field,
6. clic on the "Call SetSpedd() !" button.

### Web3.js Version

1.5.2

### Environment

- Operating System: Windows 10 Famille, version 20H2, build 19042.1237
- Browser: Firefox 93.0 (64 bits)
- Node.js Version: 7.5.3
- Ganache CLI: v6.12.2 (ganache-core: 2.13.2)

### Anything Else?

There is no issue using web3 as node library. You can find this test script [testSpeed.js](https://gist.github.com/nicos99/f197c5c8257272c04339a5cc1cd4dfc6#file-testspeed-js) that demonstrates it (download the file into an empty folder, `npm install web3@1.5.2` in the that folder and then `mocha --timeout 999999 testSpeed` having a live locale Ganache instance).

I discovered this bug months ago but I thought it was the #3742.

**Comment by nazarhussain** [comment]
@nicos99 As I [explained](https://github.com/ChainSafe/web3.js/issues/3742#issuecomment-928102801) earlier in issue #3742 this error does not relate to `web3`. The standard implementation of Eth Client is `geth` and I tested the `web3` with it for the similar contract you shared and it works fine. During that investigation I found the problem which was caused by [hardhat provider](https://github.com/nomiclabs/hardhat/issues/1910).

Similarly this issue seems related to `Ganache` and not `web3`. We will try to investigate it further but that may take some time. I suggest to you as well to look into Ganache for probable issue.

**Comment by FanM** [comment]
I hit the same error on Binance Test Chain. After some debugging, I found the _o.data_ returned was somehow an object, not a string:
![Screen Shot 2021-10-15 at 2 53 00 PM](https://user-images.githubusercontent.com/1220176/137445437-2a54f8c7-37a4-462e-8d0f-62fc786f5591.png)
I think maybe the code on https://github.com/ChainSafe/web3.js/blob/40974e9fe9a8f9075fcbb4c002430c6480d83031/packages/web3-core-method/src/index.js#L644 should check the type first.

**Comment by nicos99** [comment]
@nazarhussain I opened this ticket to explain precisely my problem (the #3742 having a short description) and to give a simpler code example (without relying on MetaMask as you suggested to me).

But you are right, the wrongs are shared because the bug does not appear when using `Geth` instead of `Ganache` (tested with 1.10.1-stable). So one might think that Ganache does not respect the protocol and Web3 (as the final package that embedded some third party libraries if I follow you) does not protect himself adequately.

I will probably update the description when I test with other clients (latest Ganache, Ropsten, Main net) to help determine the impact. Thank you for your expertise.

**Comment by raf202** [comment]
The problem is not Ganache, I'm getting the same problem with Polygon testnet (not using Ganache). 
@FanM  is probably right

**Comment by gitalvininfo** [comment]
@sigmaxf @FanM did you manage to solve this issue? Currently I'm having the same as yours.

**Comment by gitalvininfo** [comment]
I notice using old version of web3 and instantiating the smart contract in frontend fix the issue but I want to use the latest version of web3 and latest instantiation of smart contract.

**Comment by gitalvininfo** [comment]
I deployed my smart contract using the node of Moralis but still the error still exist.

**Comment by FanM** [comment]
> @sigmaxf @FanM did you manage to solve this issue? Currently I'm having the same as yours.

I added a [type check](https://github.com/FanM/web3.js/commit/62f1137136e80f23b5e16ba50cbf787ad82a3973#diff-9050e060908a6957eb4e25bb2f4b8930f5097e55e846e0e8194ff5fa3a3440a4R630) to work around this.

**Comment by gitalvininfo** [comment]
@FanM Thanks
However I'm using a CDN version of web3 with a version of release candidate 1.6.1. Anyways I try to dig it up hoping I would fix this soon. 

I look in your work around, clever solution. Thank you.

**Comment by gitalvininfo** [comment]
I think my issue for now is fixed, my issue in **"o.data.substring is not a function"** triggers in my ERC20 token **contract(MyToken.sol)**. I **change the order of loading of (MyToken.sol)** in frontend as the first smart contract that loads and I don't know what happen but the error is gone. Previously (MyToken.sol) is loaded second before my other contract(TokenTimeLock.sol) in asynchronous way.

So that is my case.

**Comment by nicos99** [comment]
here are two scenarios that show the structure of the data of the error object returned via MetaMask when revert, the basis of my work to correct:
![RPC Error](https://user-images.githubusercontent.com/32513365/228082337-9473abde-12bd-4e6c-9ff3-9adb2b9c6e23.png)
![RPC Error 2](https://user-images.githubusercontent.com/32513365/228082359-d4ddf653-3b1e-4cc7-ac21-9cb904561322.png)
