### ISSUE TITLE
Depends on json-loader if used with webpack.

### ISSUE THREAD

**Issue by Legogris** [ethereum/web3.js#446]
Would it make sense to rename `version.json` to `version.js`? When I use web3 in my webpack build process, it fails if I don't:

```
/node_modules/web3/lib/version.json on Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
| {
|     "version": "0.15.3"
| }
| 
 @ ./~/web3/lib/web3.js 36:14-39
```

Not sure exactly why this is, but either way it might be good to not make users of web3 have to be aware of this kind of thing ^^

**Comment by ptraverse** [comment]
Bump. Suggested fix by @Legogris works.

//versions.js
var version = "0.17.0-alpha";
module.exports = {
    version: version
}

//web3.js
...
var version = require('./version.js');

**Comment by frozeman** [comment]
I would love if somebody can make web3.js build using web pack and we can move away from browserify.
This should now work differently in web3.js 1.0, please test again

**Comment by lukehedger** [comment]
@frozeman Would definitely vote for moving away from Browserify but [worth considering Rollup](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c), which is geared toward libraries. Happy to help if you decide it is worth the effort.
