### ISSUE TITLE
Remove no-underscore-dangle and no-magic-numbers eslint rules

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4461]
### 

- [X] This is not a Bug Report, Feature Request, or related to Documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

To avoid having one-off inline rules disables, I would like to remove these rules from eslint config:

- `no-underscore-dangle`
- `@typescript-eslint/no-magic-numbers`

### Examples/References

- [no-underscore-dangle](https://github.com/ChainSafe/web3.js/pull/4459/files/5bf49b0330a0cfe8c1101220c67f0f59443370a8#diff-92338be6c5cafbe406d5f751665ce1ac5c5c8ac415e6400313d99b50ed4af2d5R22)
- [@typescript-eslint/no-magic-numbers](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-utils/test/fixtures/converters.ts#L1)

**Comment by mpetrunic** [comment]
@typescript-eslint/no-magic-numbers is somewhat important keep. You can disable it for test only though

**Comment by nazarhussain** [comment]
@mpetrun5 No-magic-number is only for tests. @spacesailor24 I knew these are gonna come. 😃

**Comment by Spacesai1or** [comment]
I like the use of labeling magic numbers with constants, but there have been multiple instances of simple indexes in iterative functions where labeling the magic number is unnecessary given that it's short lived. I think it would be okay to not enforce these rules for tests, although then we'd be relying only on code reviews to make sure undocumented nontrivial magic numbers don't sneak in. Perhaps the best option is to just use in-line error disables when needed (I wouldn't disable the entire file though, like how some tests are set currently)?

@nazarhussain Yes you did mention this would be an issue, I didn't consider what's happening now, so thank you for mentioning it way back when

**Comment by nazarhussain** [comment]
I remember few years back a friend @vitaly-t asked me to watch movie `The Hitchhiker's Guide to the Galaxy` which explains the magic number `42` 😄 which I never did. Seems I must watch now.
