### ISSUE TITLE
Lowercase enum keys for PredefinedBlockNumbers

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Values](https://github.com/ChainSafe/web3.js/blob/b0c383f4bc3bc00d561071cceb360ba6f472dc83/packages/web3-common/src/types.ts#L189) are in all caps

### Expected Behavior

Should be lowercased to support indexing with enum values

### Steps to Reproduce

N/A

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

Lodestar is doing something [similar](https://github.com/ChainSafe/lodestar/blob/456b50ee628eb60e3daba23cbb596cef41ea6113/packages/lodestar/src/sync/interface.ts#L68)

**Comment by nazarhussain** [comment]
I prefer keeping them uppercase. That give sense of a constant values. 

1)
```ts
enum PredefinedBlockNumbers {
	LATEST = 'latest',
	PENDING = 'pending',
	EARLIEST = 'earliest',
}
```

2)
```ts
enum PredefinedBlockNumbers {
	Latest = 'latest',
	Pending = 'pending',
	Earliest = 'earliest',
}
```

Either of above two approaches are preferred for enum values. Microsoft and all Typescript documentation is using (2) approach. Its give much better readability. Using lowercase or camelCase enum values mixed up between class static attributes.

**Comment by nazarhussain** [comment]
After discussion we decided to stick with the (1) pattern. Since we already following it in 4.x branch so no change required. 

FYI. @spacesailor24 @luu-alex @jdevcs
