### ISSUE TITLE
Create web3-eth2-beacon package structure

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

For `4.x` we will want to handle the eth2-beacon JSON-RPC requests and create a structure for it.

### Use Cases

query and participate in Ethereum 2.0 phase 0 beacon chain.

### Feature Examples/References

Apart of epic: #4324

### Are you willing to implement this feature?

- [X] Yes

**Comment by mconnelly8** [comment]
Re-estimate

**Comment by mconnelly8** [comment]
Per 12/12/23 team meeting, this is low priority and not scheduled to be completed before 2024 Q2.  Will reassess later in 2024.

**Comment by mconnelly8** [comment]
Closing the issue and will look at adding [EIP-4788](https://eips.ethereum.org/EIPS/eip-4788) functionality in the future that will provide the information.
