### ISSUE TITLE
`Failure to correctly pad number for bytes32 inputs

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#447]
http://ethereum.stackexchange.com/questions/3784/byte32-to-uint-convesion-is-incorrect?noredirect=1#comment3880_3784

`10` is encoded as `0xa` instead of `0x00000...0a`

**Comment by starcharles** [comment]
I got the same return value, using 'browser-solidity'.(latest version https://github.com/ethereum/browser-solidity)

running contract is below and input value is 10.
```
contract Thing{
  uint public number;
  function Thing(bytes32 _number){
    number = uint(_number);
  }
}
```

bug occured below

web3.js (line 2819)
```
var encodeConstructorParams = function (abi, params) {
    return abi.filter(function (json) {
        return json.type === 'constructor' && json.inputs.length === params.length;
    }).map(function (json) {
        return json.inputs.map(function (input) {
            return input.type;
        });
    }).map(function (types) {
        return coder.encodeParams(types, params);
    })[0] || '';
};
```

this returned 

 "a000000000000000000000000000000000000000000000000000000000000000"

**Comment by frozeman** [comment]
Can you retest with web3.js 1.0, and reopen if its still an issue?
