### ISSUE TITLE
Wallet local storage

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4477]
`save` : Stores the wallet encrypted and as string in local storage. params are password to encrypt before storage and optional keyname used for local storage position.

`load` : Loads a wallet from local storage and decrypts it. params are password and keyName if used non default during storage.

**Comment by nazarhussain** [comment]
@jdevcs its already created and merged. 

https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-core/src/local_storage_wallet.ts

**Comment by jdevcs** [comment]
Its not under `web3.eth.accounts.wallet` so will made available/re-export this functionality under mentioned package / class , for not having breaking change.
