### ISSUE TITLE
BigNumber Precision Can't Handle Solidity Uint

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#448]
BigNumber can't handle precision greater than 15. This is problematic since solidity handles 2^256 or  precision of around 77. Received a "unable to parse number" error when I tried to send 1,000,000,000,000,000 + of testnet ether

**Comment by aakilfernandes** [comment]
It looks like the max that can be handled correctly is < 1000 eth. Can we make this issue a priority? It can easily break a lot of unsuspecting dapps

![screen shot 2016-06-23 at 12 26 41 pm](https://cloud.githubusercontent.com/assets/1577353/16311905/5ba8a694-3940-11e6-8171-81d0e9a41181.png)

**Comment by danielfebrero** [comment]
A workaround would be to use literal numbers like 8.333333333333333e+25
But the problem here is that we are also loosing precision if the original numbers was different of 8.333333333333333000e+25 like 8.333333333333333456e+25 for example.

**Comment by frozeman** [comment]
Im closing this for now. If you have any idea how to deal with such large amounts let me know. We are using BN.js in web3.js 1.0, which might be able to handle that.
