### ISSUE TITLE
Incorrect types definition for web3-eth-contract

### ISSUE THREAD

**Issue by guenoledc** [ethereum/web3.js#4480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using typescript, and importing the package "web3-eth-contract" (`npm install web3-eth-contract`) 

You have an error message that `Contract` is not a constructor

```typescript

import storageAbi from "./abi/storage";
import { AbiItem } from "web3-utils";
import {Contract} from "web3-eth-contract";


async function run(): Promise<void> {
  const c = new Contract(storageAbi as AbiItem[])

  console.log("Contract", c)
}

run()
```

Generates the error message 
```
TypeError: web3_eth_contract_1.Contract is not a constructor
    at /Users/xxxxx/contracts/index.ts:8:13

```

### Expected Behavior

Should not fail with this error.

### Steps to Reproduce

See Current behaviour

### Web3.js Version

1.6.0

### Environment

- Operating System: MacOs
- Browser: N/A
- Node.js Version: v16.8.0
- NPM Version: 7.21.0

### Anything Else?

I could fix the problem by editing the `node_modules/web3-eth-contract/types/index.d.ts` file and making the `Contract`class being the default export (as it is in the js in `module.exports = Contract`)

```typescript
...
import {AbiItem} from 'web3-utils';

// TODO: Add generic type!
export default class Contract {
    constructor(
        jsonInterface: AbiItem[],
        address?: string,
        options?: ContractOptions
    );
 ...
```

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention! Unfortunately we can't make any changes to the typings for `1.x` versions of library, since they'll be breaking changes. Our team is currently working on a re-write of the library (`4.x` branch), which is written in Typescript, which won't suffer from incorrect type declarations
