### ISSUE TITLE
4.x build analysis

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4494]
Using some good tool ( like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) ) for 4.x build analysis, once we are using webpack for 4.x.

**Comment by mconnelly8** [comment]
Need to review before 4.x Alpha release

**Comment by jdevcs** [comment]
@mconnelly8 We will be able to see this issue after 4.x alpha packages completion. Its blocked until that.

**Comment by jdevcs** [comment]
![image](https://user-images.githubusercontent.com/86780488/188690104-2f7542a2-80cc-4801-8090-5faee9698c0b.png)

**Comment by jdevcs** [comment]
minified build:
node_modules is : 1.56 MB

Top three libs:

- (ethereumjs  299.21 KB
- idna-map / idna-uts46-hx  160.15 KB  ( only its opne function is used in ENS )
- ethers   134.54 KB)

**Comment by jdevcs** [comment]
4.x main branch analysis on 8 Feb 2023: 
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/86780488/217497394-ac82573b-10fc-4002-a47a-320598b91393.png">
