### ISSUE TITLE
WS unit tests and other Changes

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4495]
- WS Unit tests
- errors with Error Constructor

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4495?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24

**Comment by Nijakisan** [comment]
It's my first day when i try this creating so still learning if i broke somethung i', so sorry !
