### ISSUE TITLE
Web3 batch requests fail with latest Geth 1.4.4-stable-8ea3c88e

### ISSUE THREAD

**Issue by johnmcdowall** [ethereum/web3.js#450]
Previously working batch request code has started failing with the following message being returned over the RPC from Geth: `invalid or missing value for params[1]`. Here is the code in question: 

```
let request = thRawContract.owners.request( i, foundOwner.bind(null, i) );
batch.add(request);
```

The code stopped working after we upgraded our Geth node. 

Investigating, it seems that Geth now requires a default block parameter to be passed along: https://github.com/ethereum/go-ethereum/issues/2472

Tracing the function calls to `lib/web3/function.js#SolidityFunction.prototype.request` shows that the call to `toPayload` throws away additional arguments (that are not objects), creating a `param` array of one entry, when Geth is now expecting an array of 2 entries for `param`, where the second entry is the default block parameter. 

I'm getting around this issue by manually pushing `'latest'` onto the param array:

```
let request = thRawContract.owners.request( i, foundOwner.bind(null, i) );
request.params.push('latest');
batch.add(request);
```

Which makes the calls work again. 

Is this a bug with web3 or is there a way for me to construct the calls correctly using existing web3 functionality?

**Comment by kumavis** [comment]
confirmed as an issue

**Comment by kumavis** [comment]
ethereum/go-ethereum#2472 made it sound like the blockTag was going to be made optional again, but this suggests otherwise https://github.com/ethereum/go-ethereum/pull/2473#issuecomment-212619256

**Comment by frozeman** [comment]
Could you please confirm that with web3.js 1.0 an reopen if its still an issue?
