### ISSUE TITLE
Don't autofill gasPrice on transactions

### ISSUE THREAD

**Issue by danfinlay** [ethereum/web3.js#4509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a report from etherscan that they are using web3.js, and it seems to be auto-filling a `gasPrice` parameter, which MetaMask currently interprets to mean the site is deliberately overriding the wallet's own suggested price. This is resulting in user transaction overpayment.

### Expected Behavior

Unless a developer has explicitly included a `gasPrice` parameter, no `gasPrice` parameter should be passed to the provider in a `sendTransaction` call.

### Steps to Reproduce

```javascript
var Web3 = require('web3');
var web3 = new Web3(Web3.givenProvider || 'ws://some.local-or-remote.node:8546');

// using the promise
web3.eth.sendTransaction({
    from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe',
    to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
    value: '1000000000000000'
})
.then(function(receipt){

});
```

### Web3.js Version

1.5.3

### Environment

- Operating System: All
- Browser: All
- Node.js Version: 
- NPM Version:

**Comment by nazarhussain** [comment]
This seems to be the exact behaviour what is explained in the issue. 

But changing this behaviour may cause unseen effects on the usability of the library and definitely it should be considered as breaking change. 

Need further thought process how to proceed on it. 

https://github.com/ChainSafe/web3.js/blob/7682f1adb520c592b0b25f9dcf8aa6437be935f6/packages/web3-core-method/src/index.js#L787-L800

**Comment by nazarhussain** [comment]
@danfinlay I opened a [discussion](https://github.com/ChainSafe/web3.js/discussions/4533) thread for the issue. Please share your feedback on it.

**Comment by nazarhussain** [comment]
Based on discussion among team, we decided to implement this as a new feature. There should be a configuration option in all related functions to fill in or not fill-in default values for transaction with default behavior matching to 1.x release.

**Comment by danfinlay** [comment]
Thanks, I'm glad this is moving forwards!

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4509?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
