### ISSUE TITLE
Error returning a uint256 value stored in array.

### ISSUE THREAD

**Issue by srnidheesh** [ethereum/web3.js#451]
When i returning a uint256 value to html page i am getting a value like this let meknow why sir, how to fix it.
0x0289e0a5be50079ade5fb7f771ae291ad1cc5630d9922ad4147074ffd984615

**Comment by redsquirrel** [comment]
@srnidheesh Can you please show the code you're using?

**Comment by srnidheesh** [comment]
contract Student
{
	uint256 index=0;
	function Students(bytes32 name,  uint256 adNo) returns (uint256 vid)
	{
		index++;
    	Name[index]=name;
		AdmissionNo[index]=adNo;
		vid=index;
	}
	mapping(uint256 => bytes32) public Name;
	mapping(uint256 => uint256) public AdmissionNo;
}
 the return value for vid is like 0xca297a8080be23ace753b20084fd853533af205c16bbfef7aa466208aa0341d5 when printing in html

**Comment by redsquirrel** [comment]
That is the transaction hash. You need to poll using [web3.eth.getTransactionReceipt](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt) to tell you when your transaction has been mined into a block.

Even then, you'll need to make another call to get the value of `index`. I recommend making `index` public:

`uint256 public index = 0;`

Then you can call get the value synchronously like `web3.eth.contract(abi).at(address).index()` after your transaction receipt has been returned.

If you need more help, please provide your JavaScript.

**Comment by srnidheesh** [comment]
<!doctype>
<html>
<head>
<script type='text/javascript'>
web3.eth.defaultAccount = web3.eth.accounts[0]
function get() {
	var index = document.getElementById('index').value;
	var name = contracts['Student'].contract.Name(index);
	var adNo = contracts['Student'].contract.AdmissionNo(index);
	document.getElementById('queryres').innerText = hex2a(name)+"   "+adNo;
	document.getElementById("queryres").appendChild(document.createElement("BR"));

}

function set() {
	var name = document.getElementById('name').value;
	var adNo = document.getElementById('adNo').value;
	var res = contracts['Student'].contract.Students(name,adNo);
	document.getElementById('queryres').innerText = res;
}
	function hex2a(hex)
		{
			//hex = document.calcform.hex.value;
			hex = hex.match(/[0-9A-Fa-f]{2}/g);
			len = hex.length;
			if( len==0 ) return;
			txt='';
			for(i=0; i<len; i++)
			{
				h = hex[i];
				code = parseInt(h,16);
				t = String.fromCharCode(code);
				txt += t;
			}
			return txt;
		}


</script>
</head>
<body bgcolor='#E6E6FA'>
	<h3>Students</h3>
<div>
Store:
	<input type='text' id='name'>
	<input type='number' id='adNo'>
	<button onclick='set()'>Save</button>
</div>
<div>
Query:
	<input type='number' id='index'>
	<input value='get' type='button' id='query' onclick='get()' />
	<div id='queryres'></div>
</div>
</body>
</html>
``

**Comment by srnidheesh** [comment]
<!doctype>
<html>
<head>
<script type='text/javascript'>
web3.eth.defaultAccount = web3.eth.accounts[0]
function get() {
	var index = document.getElementById('index').value;
	var name = contracts['Student'].contract.Name(index);
	var adNo = contracts['Student'].contract.AdmissionNo(index);
	document.getElementById('queryres').innerText = hex2a(name)+"   "+adNo;
	document.getElementById("queryres").appendChild(document.createElement("BR"));

}

function set() {
	var name = document.getElementById('name').value;
	var adNo = document.getElementById('adNo').value;
	var res = contracts['Student'].contract.Students(name,adNo);
	document.getElementById('queryres').innerText = res;
}
	function hex2a(hex)
		{
			//hex = document.calcform.hex.value;
			hex = hex.match(/[0-9A-Fa-f]{2}/g);
			len = hex.length;
			if( len==0 ) return;
			txt='';
			for(i=0; i<len; i++)
			{
				h = hex[i];
				code = parseInt(h,16);
				t = String.fromCharCode(code);
				txt += t;
			}
			return txt;
		}


</script>
</head>
<body bgcolor='#E6E6FA'>
	<h3>Students</h3>
<div>
Store:
	<input type='text' id='name'>
	<input type='number' id='adNo'>
	<button onclick='set()'>Save</button>
</div>
<div>
Query:
	<input type='number' id='index'>
	<input value='get' type='button' id='query' onclick='get()' />
	<div id='queryres'></div>
</div>
</body>
</html>

**Comment by srnidheesh** [comment]
```
<!doctype>
<html>
<head>
<script type='text/javascript'>
web3.eth.defaultAccount = web3.eth.accounts[0]
function get() {
	var index = document.getElementById('index').value;
	var name = contracts['Student'].contract.Name(index);
	var adNo = contracts['Student'].contract.AdmissionNo(index);
	document.getElementById('queryres').innerText = hex2a(name)+"   "+adNo;
	document.getElementById("queryres").appendChild(document.createElement("BR"));

}

function set() {
	var name = document.getElementById('name').value;
	var adNo = document.getElementById('adNo').value;
	var res = contracts['Student'].contract.Students(name,adNo);
	document.getElementById('queryres').innerText = res;
}
	function hex2a(hex)
		{
			//hex = document.calcform.hex.value;
			hex = hex.match(/[0-9A-Fa-f]{2}/g);
			len = hex.length;
			if( len==0 ) return;
			txt='';
			for(i=0; i<len; i++)
			{
				h = hex[i];
				code = parseInt(h,16);
				t = String.fromCharCode(code);
				txt += t;
			}
			return txt;
		}


</script>
</head>
<body bgcolor='#E6E6FA'>
	<h3>Students</h3>
<div>
Store:
	<input type='text' id='name'>
	<input type='number' id='adNo'>
	<button onclick='set()'>Save</button>
</div>
<div>
Query:
	<input type='number' id='index'>
	<input value='get' type='button' id='query' onclick='get()' />
	<div id='queryres'></div>
</div>
</body>
</html>

```

**Comment by srnidheesh** [comment]
when clicking save button it should save and return index of the student

**Comment by redsquirrel** [comment]
Behind the scenes, `contracts['Student'].contract.Students(name,adNo)` is using `web3.eth.sendTransaction`, which is asynchronous. You can read the documentation about that [here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction).

If you need more help, I recommend posting your question to: http://ethereum.stackexchange.com/
