### ISSUE TITLE
getFeeHistory gives error when running local fork with hardhat

### ISSUE THREAD

**Issue by gndelia** [ethereum/web3.js#4510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sure if this is an error in web3.js or in hardhat, but after reading some docs and tracing the possible bug fix I think it should be fixed here (I might be wrong!)

When calling `getFeeHistory` in my app, using a local fork with hardhat, I get the following error

```
Error: Internal JSON-RPC error.
{
  "code": -32602,
  "message": "Errors encountered in param 0: Invalid value 1 supplied to : QUANTITY"
}
```

### Expected Behavior

I expect the proper response of `eth_feeHistory`, something like

```
{
        "oldestBlock": "0xce1806",
        "baseFeePerGas": [
            "0x26a51093d0",
            "0x2532e26b6d"
        ],
        "gasUsedRatio": [
            0.35032733868710536
        ]
    }
```

### Steps to Reproduce

(according to the docs, these are valid parameters)

```js

web3.eth.getFeeHistory('0x1', 'latest', []).then(console.log).catch(console.error)
```

By running this with a local fork with hardhat, I get the above-mentioned error (See below for hardhat config)

### Web3.js Version

1.5.3

### Environment

- Operating System: Mac OS 11.6
- Browser:  Brave
- Node.js Version: 14.16.1
- NPM Version: 6.14.32

### Anything Else?

hardhat config is pretty simple

```js
.'use strict'
require('dotenv').config()

module.exports = {
  defaultNetwork: 'hardhat',
  networks: {
    hardhat: {
      accounts: {
        accountsBalance: '10000000000000000000000',
        mnemonic: process.env.MNEMONIC
      },
      forking: {
        url: process.env.BASE_NODE_URL,
        blockNumber: 8
      }
    },
    mainnet: {
      url: process.env.BASE_NODE_URL,
      chainId: 1
    }
  }
}
```

hardhat version: 2.6.7

so I just run `npx hardhat node` and connect with Metamask to that local fork

Then, the code of the app just do what I wrote in the "Steps to Reproduce" section
After a couple of hours of debugging; I found that if I change [this line right here](https://github.com/ChainSafe/web3.js/blob/7682f1adb520c592b0b25f9dcf8aa6437be935f6/packages/web3-eth/src/index.js#L411), updating the formatters for `eth_feeHistory` from 

```js
new Method({
  name: 'getFeeHistory',
  call: 'eth_feeHistory',
  params: 3,
  inputFormatter: [utils.toNumber, formatter.inputBlockNumberFormatter, null]
}),
```

to

```js
new Method({
  name: 'getFeeHistory',
  call: 'eth_feeHistory',
  params: 3,
  // replace utils.toNumber here with utils.numberToHex
  inputFormatter: [utils.numberToHex, formatter.inputBlockNumberFormatter, null]
}),
```

then it works. I found this as part of implementing EIP-1559 for a dapp.

I tried to use this method with a fork with ganache-cli, but I also failed to make it work, but I am still unsure of the reasons, as the error was different.

Not sure if this is a problem in web3 or in hardhat though 😓

**Comment by luu-alex** [comment]
Hey, sorry to hear you've been having issues with an RPC call. 

I installed the same version of web3js and was able to sucessfully perform `getFeeHistory`, perhaps it is hardhat? 
```
Web3.eth.getFeeHistory('0x1', 'latest', []).then(console.log).catch(console.error)
Promise { <pending> }
> {
  baseFeePerGas: [ '0x30aea7270d', '0x2deb22f72d' ],
  gasUsedRatio: [ 0.27291628440852755 ],
  oldestBlock: '0xce36b8'
}
```
If theres anything that points to web3js being an issue let us know and we'll try to investigate it when we can :)

**Comment by gndelia** [comment]
Thanks for your response! I'll try to ping them on their side. I'm ok if you want to close this in the meantime. Thank you!

**Comment by fvictorio** [comment]
Hey @luu-alex, are you sure this isn't a problem in web3?

The `eth_feeHistory` section of [the spec](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) says that the first argument should be a hex-encoded unsigned string:

![image](https://user-images.githubusercontent.com/417134/140562593-baa8c24b-bba2-4196-8759-1aa758e6efc6.png)


But here:

https://github.com/ChainSafe/web3.js/blob/3a3cb32b6434656131f0bfc4a8622130d19d2338/packages/web3-eth/src/index.js#L411

Web3 seems to be converting it to a plain number (as far as I understand, at least).

Some nodes might be more permissive in what they accept, which makes sense. But we try to follow the spec as much as possible, so that code that runs on Hardhat will run in any spec-compliant node.

**Comment by luu-alex** [comment]
Ah that makes alot of sense, thank you for this. A PR will be out shortly

**Comment by luu-alex** [comment]
Hey @fvictorio thank you for taking a look, that makes alot of sense. I have reopened the issue and will try to tackle this problem. @gndelia I was curious are you still facing issues with a fork from ganache-cli? If so what was the error.

**Comment by gndelia** [comment]
I get `Method eth_feeHistory not supported.` - but that might be that I just need to update ganache-cli 😬
