### ISSUE TITLE
'0x' strings returned by contract are incorrectly interpreted as nulls

### ISSUE THREAD

**Issue by Pzixel** [ethereum/web3.js#4512]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

'0x' strings returned by contract are incorrectly interpreted as nulls

### Expected Behavior

They should be regular 2 chars length strings

### Steps to Reproduce

Consider following contract function

```solidity
function test() external view returns (string memory) {
    return '0x';
}
```
Now if we call it:

```js
const myContract = await MyContract.new();
expect(await myContract.test()).to.be.equal('0x');
```

We will see `AssertionError: expected null to equal '0x'`

### Web3.js Version

1.5.3

### Environment

- Operating System: Win10 x64
- Browser: All
- Node.js Version: v16.2.0
- NPM Version: 7.23.0

**Comment by luu-alex** [comment]
Hey Pzixel, I'm currently taking a look. thank you for creating an issue
