### ISSUE TITLE
Buggy `BlockHeader` interface

### ISSUE THREAD

**Issue by karim-en** [ethereum/web3.js#4517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The name of the `receiptRoot` property of the `BlockHeader` class is not correct.

wiki:
https://eth.wiki/json-rpc/API#:~:text=of%20the%20block.-,receiptsRoot,-%3A

Related issue:
ethereum/go-ethereum#3084

### Expected Behavior

we should use `receiptsRoot` instead of `receiptRoot`

```
export interface BlockHeader {
    number: number;
    hash: string;
    parentHash: string;
    nonce: string;
    sha3Uncles: string;
    logsBloom: string;
    transactionRoot: string;
    stateRoot: string;
    receiptsRoot: string;
    miner: string;
    extraData: string;
    gasLimit: number;
    gasUsed: number;
    timestamp: number | string;
    baseFeePerGas?: number;
}

```

### Steps to Reproduce

just call `web3.eth.getBlock()` and check the returned object

### Web3.js Version

1.5.3

**Comment by jdevcs** [comment]
included in https://github.com/ChainSafe/web3.js/pull/4445
