### ISSUE TITLE
Web3BaseProviderStatus should be an enum

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4518]
### 

- [X] This is not a Bug Report, Feature Request, or related to Documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

[provider statuses](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-common/src/web3_base_provider.ts#L9) should be an enum such as:

```typescript
export enum Web3BaseProviderStatus {
    CONNECTING = 'connecting',
    CONNECTED = 'connected',
    DISCONNECTED = 'disconnected'
}
```

**Comment by mconnelly8** [comment]
Not needed any longer.  Closing.
