### ISSUE TITLE
Contract.allEvents does not support further filtering based on topics parameter in the option.

### ISSUE THREAD

**Issue by IamSandipC** [ethereum/web3.js#452]
Though in the documentation https://github.com/ethereum/wiki/wiki/JavaScript-API#parameters-33, it is mentioned that "Object - Additional filter options, see filters parameter 1 for more"...Contract.allEvents does not support further filtering based on topics parameter in the option.

If we have a contract

```
contract C1{
    event E1(uint indexed e11);
    event E2(uint indexed e22);

    function test(uint i, uint j){
        E1(i);
        E2(j);
    }
}
```

Let's call the test() function once. So we have two events in the log.

Now following code returns both the events though it is filtered by single topic.

```
c1.allEvents({fromBlock: 0, toBlock: 'latest', topics:["0x47e2689743f14e97f7dcfa5eec10ba1dff02f83b3d1d4b9c07b206cbbda66450"]})
.get(function(e,logs){console.log(logs);});
```

However filter works just fine and it returns a single event (E1)

```
web3.eth.filter({fromBlock: 0, toBlock: 'latest', topics:["0x47e2689743f14e97f7dcfa5eec10ba1dff02f83b3d1d4b9c07b206cbbda66450"], address:"0x538c2b120085470ec0bb2fe90c626165f5d124dd"})
.get(function(e,logs){console.log(logs);});
```

**Comment by Moejoe90** [comment]
Anyone tested this lately i seem to be having the same issue.

**Comment by frozeman** [comment]
Can you please test with web3.js 1.0 and see if it is working there?

**Comment by gabriel-gex** [comment]
```
contract.events.allEvents({ filter: {}, fromBlock: 0, toBlock: 'latest' }, function(error, result){
    if (!error){
        submitEventToPortal(result, 'present');
    }
});
```

but it return all event, even the fromblock is 5xxxxx

**Comment by nivida** [comment]
I've closed this issue due to inactivity.
