### ISSUE TITLE
Passing dynamic variables with web3js

### ISSUE THREAD

**Issue by berktaylan** [ethereum/web3.js#4528]
### 

- [X] This is not a Bug Report, Feature Request, or related to Documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Hello everyone,

Is it possible  to pass dynamic parameters with call data to smart contract.
As example i want to use  eth.getStorageAt & blocknumber ( the blocknumber, when my transaction executed ), and pass that values dynamicly.

Thanks.

**Comment by nazarhussain** [comment]
Hi @berktaylan Thanks for reaching out to us. I could not grasp your question. If you want to use `eth.getStorageAt` then you have to provider the block number. If you want to get that block number from some other transaction, then you can invoke that first and execute both in a promise chain. 

If that does not answer your question, please provide a code example that you want to make work and you are facing problem with it. That will help us better guide you.

**Comment by berktaylan** [comment]
hi @nazarhussain i figure out the problem. but now i have another question.

im using myContract.events.MyEvent to subscribe events of a contract for pending blocks,
howeever on data im able to see blocknumber means tx already mined. I want to see newly broadcasted transactions to the network. But fromBlock: "pending" looks not working ? 

```
contract.events.allEvents({
    fromBlock: "pending"
}, function(error, event){ console.log(event); })
.on("connected", function(subscriptionId){
    console.log(subscriptionId);
})
.on('data', function(event){
    console.log(event); // same results as the optional callback above
})
.on('changed', function(event){
    // remove event from local database
})
.on('error', function(error, receipt) { // If the transaction was rejected by the network with a receipt, the second parameter will be the receipt.
    
});
```

**Comment by nazarhussain** [comment]
Hi @berktaylan I replied to the other [issue#4554](https://github.com/ChainSafe/web3.js/issues/4554) you created, let's use that for further discussion of that topic. 

Since this issue no more relevant I am closing it.
