### ISSUE TITLE
Balance does not include decimals

### ISSUE THREAD

**Issue by justekoro** [ethereum/web3.js#4539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The returned balance is 599998320000000000000

### Expected Behavior

The returned balance should be 599.998320000000000000

### Steps to Reproduce

```
const web3 = new Web3(Web3.givenProvider || "ws://localhost:8546");
web3.eth.getBalance("0x0739e6c0a339ac473f58922c0cb41704b2bb09ae").then(b=>{console.log(b)})
```

### Web3.js Version

1.6.0

### Environment

- Operating System: Windows 11 (V 10.0.22494 build 22494)
- Browser: Opera GX
- Node.js Version: 16.8.0
- NPM Version: 7.24.1

**Comment by jdevcs** [comment]
This function returns balance in [wei](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getbalance) , so you can convert to other units by using  [web3.utils.fromWei](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#fromwei) [examples](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#id84)

**Comment by justekoro** [comment]
thank you!
