### ISSUE TITLE
Chrome warning about synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by thiagodelgado111** [ethereum/web3.js#454]
### OS and Chrome info

Mac OS X 10.11.4
Chrome Version 50.0.2661.102 (64-bit)
### Details

Chrome gives me this warning:

> "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

Referring to this line: https://github.com/ethereum/web3.js/blob/master/lib/web3/httpprovider.js#L61

**Comment by redsquirrel** [comment]
I'm seeing the same thing.

Mac OS X 10.10.5
Chrome Version 50.0.2661.102 (64-bit)

**Comment by Overdrivr** [comment]
I am getting the same warning on Ubuntu 16.04 with Firefox 49.0.2

**Comment by JasoonS** [comment]
I'm getting this warning on all the browsers that I try. Followed by some kind of error (ie something stops working).

**Comment by nueverest** [comment]
@JasoonS same here.  Am running Parity and NodeJS on localhost.

**Comment by JasoonS** [comment]
@nueverest I have moved over to using Truffle now, and I am no longer having this issue. I actually still don't know what the issue was, but somehow the truffle framework manages things to avoid this issue.

**Comment by frozeman** [comment]
Should not be an issue with web3.js 1.0

**Comment by kadnan** [comment]
> Oops, please disregard this comment. I was making a synchronous call to web3.
@redsquirrel How did you fix it? I am getting error on the following:

```
web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
```

**Comment by kyriediculous** [comment]
If only web3 1.0.0 were compatible with metamask ;)
