### ISSUE TITLE
"Provider not set or invalid" on balance request

### ISSUE THREAD

**Issue by O-Shevtsov** [ethereum/web3.js#4548]
Hello!
I start to use that plugin for unity. At now just configured login to metamask wallet and tried to get some wallet balance. But I have `Provider not set or invalid` in balance response.
Login looks like valid with existing account id.
My code is
`
        BigInteger wallet = BigInteger.Zero;
        
        wallet = await ERC1155.BalanceOf(Chain, Network, Contract, 
            PlayerPrefs.GetString(Account), TokenId);

        Debug.Log(wallet);
`
Calls immedeatly after login.

After that call I have next errors:
- POST https://api.gaming.chainsafe.io/evm/call 400 (Bad Request)
- Provider not set or invalid

Using Unity 2020.3.17f, web.

Can anyone help me? Maybe I miss something?
Thanks

**Comment by Spacesai1or** [comment]
Hi there, I don't think this is an issue with Web3.js, could you try opening your issue [here](https://github.com/ChainSafe/web3.unity)?

**Comment by O-Shevtsov** [comment]
True... Sorry
