### ISSUE TITLE
Migrate set registry functions from 1.x for 4.x rewrite

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4552]
### Description

Migrate the following functions from `web3-eth-ens` contract functions for registry 1.x branch to 4.x rewrite.
- setOwner
- setTTL
- setSubnodeOwner
- setRecord
- setSubnodeRecord
- setApprovalForAll
- setResolver

### Deprecated functions from 1.x
- resolver
- owner

### Acceptance Criteria
- All functions above should be migrated
- All functions should be covered with unit tests
### Links and resources
- https://github.com/ChainSafe/web3.js/blob/9b7540d283c3c72978ebdfacc0dea2d0f3f36a05/packages/web3-eth-ens/src/contracts/Registry.js

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4552?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24

**Comment by jdevcs** [comment]
these function (except setRecord) added in PR 4762
