### ISSUE TITLE
Migrate SET ENS functions  from 1. to 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4553]
### Description

Migrate the following functions and config file from `web3-eth-ens` ens 1.x branch to 4.x rewrite.
Functions:
- setAddress
- setPubkey
- setContent
- setContenthash
- setMultihash

### Deprecated functions from 1.x
- resolver
- owner

### Acceptance Criteria
- All functions above should be migrated (except deprecated functions)
- All functions should be covered with unit tests
### Links and resources

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4553?planning-poker) with ZenHub @jdevcs @nazarhussain @stupeters187 @luu-alex

**Comment by mconnelly8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4553?planning-poker) with ZenHub @spacesailor24
