### ISSUE TITLE
myContract.events.MyEvent with pending returns blocknumber

### ISSUE THREAD

**Issue by berktaylan** [ethereum/web3.js#4554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello im using myContract.events.MyEvent to subscribe events of a contract for pending blocks,
howeever on data im able to see blocknumber means tx already mined. I want to see newly broadcasted transactions to the network. But fromBlock: "pending" looks not working ? 

```js
contract.events.allEvents({
    fromBlock: "pending"
}, function(error, event){ console.log(event); })
.on("connected", function(subscriptionId){
    console.log(subscriptionId);
})
.on('data', function(event){
    console.log(event); // same results as the optional callback above
})
.on('changed', function(event){
    // remove event from local database
})
.on('error', function(error, receipt) { // If the transaction was rejected by the network with a receipt, the second parameter will be the receipt.
    
});
```

### Expected Behavior

Get events data which broadcasted to network newly ( pending/mempool )

### Steps to Reproduce

```js
contract.events.allEvents({
    fromBlock: "pending"
}, function(error, event){ console.log(event); })
.on("connected", function(subscriptionId){
    console.log(subscriptionId);
})
.on('data', function(event){
    console.log(event); // same results as the optional callback above
})
.on('changed', function(event){
    // remove event from local database
})
.on('error', function(error, receipt) { // If the transaction was rejected by the network with a receipt, the second parameter will be the receipt.
    
});
```

### Web3.js Version

1.5.2

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nazarhussain** [comment]
Hey @berktaylan I am not sure if I understand the issue correctly. If `on('data')` is working as expected and you got the new blocks then you can use `web3.eth.getBlock` to fetch transactions for that block. If you are looking for pending transactions in general you can use `web3.eth.subscribe('pendingTransactions')`. 

I would suggest to share more explanations of the issue and create a sample repository with the contract code so we can debug it quickly.

**Comment by nazarhussain** [comment]
Hi @berktaylan Did you get a chance to look at this thread? Please provide more details so we can debug the issue further.

**Comment by berktaylan** [comment]
Hi @nazarhussain , i was wrong about thinking `contract.events.allEvents` will work with `from: pending` parameter.
I tried with the way you told and its working.

I got another question, generating raw tx ( signed ) takes 15 to 20ms. Do you have any idea how can i speed that step ?

**Comment by nazarhussain** [comment]
Hi @berktaylan I am glad that your issue is solved. I would be closing this issue now. 

For your other question you I think 15-20ms is pretty fast to sign a transaction. What's your expectations for it? Please create a separate issue for it with some code snippet you trying with we can discuss it further there.
