### ISSUE TITLE
Improve `formatParam` to not mutate the input

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4556]
#### Expected behavior

No input parameters should be mutated. 

#### Actual behavior

Currently the `formatParam` function in `web3-eth-abi` package is mutating the input parameters. That can have side effects and may result in introducing bugs. Would be nice fix it. 

https://github.com/ChainSafe/web3.js/blob/d9726d41babe14bc823d5d2ea4e4af15ef5914ac/packages/web3-eth-abi/src/utils.ts#L120

https://github.com/ChainSafe/web3.js/blob/a1c7d71973ec17f9287fbea8939e64a80e589fc6/packages/web3-eth-abi/src/index.js#L249

#### Environment

1.x, 4.x

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4556?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
