### ISSUE TITLE
unable to catch "Invalid JSON RPC Response" exception

### ISSUE THREAD

**Issue by sirpy** [ethereum/web3.js#4569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When web3 client throws this exception it is not catchable either via the event emitter .on('error') or via wrapping the call/send with try/catch

### Expected Behavior

All exceptions should be catchable so you could retry or handle it gracefully

### Steps to Reproduce

any call/send that results in this exception

### Web3.js Version

1.5.3

### Environment

- Operating System: any
- Browser: any
- Node.js Version: any 
- NPM Version: any

**Comment by nazarhussain** [comment]
Hi @sirpy Thanks for reaching out to us. Unfortunately it didn't provide enough details to debug the issue. Please share a reproducible code snippet related to the issue. We will look further as we get your response.

**Comment by nazarhussain** [comment]
Hi @sirpy  as we didn't heard back from you with more details to understand the issue. I have to close this one. If you can collect more information feel free to re-open the issue.
