### ISSUE TITLE
distant contract call using meteor

### ISSUE THREAD

**Issue by zikilemini** [ethereum/web3.js#457]
Hello,

I want to build a server using meteor which have access to the blockchain.

The goal is to generate a Transaction, send it to client, make it signed by the client, send it back to the server to apply the transation to the blockchain.

My problem is that i don't know how to generate the 'data' part of a transaction when i must call a contract. I saw i could use the code at 'web3/lib/web3/function' but i don't understand how to access it via meteor.

Thanks for your help !

**Comment by frozeman** [comment]
You can checkout the new http://web3js.readthedocs.io/en/1.0/web3-eth-abi.html functions in web3.js 1.0
