### ISSUE TITLE
getPastEvents fromBlock and toBlock confusing, allow the use of just 'block'

### ISSUE THREAD

**Issue by danstarns** [ethereum/web3.js#4570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

When calling the [https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#getpastevents](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#getpastevents) method on a contract instance it's rather confusing what blocks you will get when using the `fromBlock` and `toBlock` params. This feature request is to allow another parameter called `block` that will only get the events in that specific block. 

### Use Cases

Developer experience, I don't have to think about what events are going to be included in my query and can simply give the method a block and receive the events only in that block. 

### Implementation Ideas

```js
const contractInstance = new web3.eth.Contract(ABI, ADDRESS);

const events = await contractInstance.getPastEvents(EVENT, {
  block: 12345678
});
```

### Are you willing to implement this feature?

- [X] Yes

**Comment by mconnelly8** [comment]
Reviewed 10/1/24, current design of fromBlock and toBlock appears sufficient.  Closing.
