### ISSUE TITLE
eip-155 chainId in Transaction

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4573]
`chainId` param is missing in [Transaction](https://github.com/ChainSafe/web3.js/blob/16abe310f2af3b98750bdd7e1ec7c792f49c9e61/packages/web3-common/src/eth_execution_api.ts#L35)   EIP155

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4573?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
