### ISSUE TITLE
ENS add new ABI contract functions for feature parity with ENS in 4.x 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4600]
Feature parity with ENS for the ABI contract functions for 4.x rewrite
Includes:

ReverseRegistrar Abi:
- claim
- claimWithResolver
- setName
- node
- defaultResolver

TestRegistrar Abi:
- register
- expiryTimes

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4600?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
