### ISSUE TITLE
Migrate registry ABI from 1.x for 4.x rewrite

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4601]
Migrate the following ABI from web3-eth-ens 1.x branch to 4.x rewrite
Testing to deploy on private chain and testing the contract code.
Registry Abi:

owner
resolver
ttl
setOwner
setResolver
setTTL
setSubnodeOwner
setRecord
setSubnodeRecord
setApprovalForAll
isApprovedForAll
recordExists

### Related Resources

- https://docs.ens.domains/deploying-ens-on-a-private-chain
- [Github repo](https://github.com/ensdomains/ens) (may be deprecated)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4601?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
