### ISSUE TITLE
Migrate get registry functions from 1.x to 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4603]
### Description

Migrate the following functions from `web3-eth-ens` contract functions for registry 1.x branch to 4.x rewrite.
- registryAddress
- getOwner
- getTTL
- isApprovedForAll
- recordExists
- getResolver

### Deprecated functions from 1.x
- resolver
- owner

### Acceptance Criteria
- All functions above should be migrated
- All functions should be covered with unit tests

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4603?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain
