### ISSUE TITLE
Testing contract code and ABI - 4.x rewrite

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4609]
We want to be able to test Contract code
A discussion on possible ways to test:
- Abi is validated from what we copy into 4.x. 
- Detection in changes of registry abi on mainnet.
- Create a test suite to test out ABI code

### Links and resources
- https://github.com/ChainSafe/web3.js/blob/9b7540d283c3c72978ebdfacc0dea2d0f3f36a05/packages/web3-eth-ens/src/contracts/Registry.js

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4609?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
