### ISSUE TITLE
support of tuple[2] type

### ISSUE THREAD

**Issue by GANFI** [ethereum/web3.js#4610]
Hello

I have method in my contract

```js
{
  inputs: [
    { internalType: "uint256", name: "_someId", type: "uint256" },
    { internalType: "uint256", name: "_timeExp", type: "uint256" },
    { internalType: "uint256", name: "_timeDeadLine", type: "uint256" },
    { internalType: "string", name: "_Symbol", type: "string" },
    {
      components: [
        { internalType: "enum Actions", name: "compare", type: "uint8" },
        { internalType: "int256", name: "value", type: "int256" },
        { internalType: "int256", name: "raise", type: "int256" },
        { internalType: "uint256", name: "bet", type: "uint256" },
        { internalType: "bool", name: "isWin", type: "bool" },
      ],
      internalType: "struct Outcome[2]",
      name: "_outcomes",
      type: "tuple[2]",
    },
  ],
  name: "makeSchedule",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
}
```

How can I pass `_outcomes` ? I try like this , but have error: Uncaught (in promise) TypeError: param.map is not a function
```
[ [1,4815087599255,0,0,false], [4,4815087599255,0,0,false] ]
```

**Comment by nazarhussain** [comment]
Hi @GANFI Thanks for reaching out to us, we will be happy to help. 

Apparently it seems the right usage for that parameter. Can you share complete params that you pass to your method along with complete error log to debug it further.

**Comment by GANFI** [comment]
Hi @nazarhussain 

So I try to call this method of contact like this:
`const gas = await tokenInstance.methods.makeSchedule( 0,
          1638793499935,
          1638914400000,
          'BTC/USD',
          [
              [1,4815087599255,0,0,false],
              [4,4815087599255,0,0,false]
          ]
            ).estimateGas({from: account})
          .then((response: any) => {
              response.toString()
          })
          .catch((error: any) => {
              console.log(error);
              return 0;
          });`
  In console I have this errors:         
  
  ```
Uncaught (in promise) TypeError: param.map is not a function
    modifyParams index.js:105
    modifyParams index.js:105
    modifyParams index.js:105
    modifyParams index.js:105
    modifyParams index.js:105
    params index.js:116
    encodeParameters index.js:93
    paramsABI index.js:450
    _encodeMethodABI index.js:449
    _processExecuteArguments index.js:713
    _executeMethod index.js:732
    _callee11$ useContract.tsx:171
    Babel 8
    createBetHandler HowCreateBetSidebar.tsx:95
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 4
   index.js:105
```
 
 So I try change type in ABI file from `tuple[2]` to `tuple[]` and I don`t have error, but I have error code from contact response

**Comment by nazarhussain** [comment]
Thanks we will look into it further and investigate the problem.

**Comment by layinka** [comment]
+1 this
