### ISSUE TITLE
running out of memory when decoding parameters

### ISSUE THREAD

**Issue by dnjscksdn98** [ethereum/web3.js#4612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In one of my projects there is a process that I have to decode the input data of a transaction.
It worked very fine so far, but today my app kept on crashing by running out of memory.
So I tried to debug to find exactly where the error point was and I found out that it was the function call from "decodedParameters".

And this is a similar code that can reproduce that same error.
The transaction is from BSC mainnet in block 13303917.

```
  // tx=0xabab2f00754b617478dfd2e200e917e8b604a548b3b9c95fe919d9ecb8d910e4
  const result = web3.eth.abi.decodeParameters(
    ['uint256', 'uint256', 'address[]', 'address', 'uint256'],
    '00000000000000000000000000000000000000000000000000005af3107a40001e66666666666600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000364426a650dfefefc645de176569e5648b91766f00000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000005ca42204cdaa70d5c773946e69de942b85ca6706000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
  );
  console.log(result);
```

And the error result shows up like this. The process runs for about 5~10 seconds and then it crashes like below.

<img width="2111" alt="Screen Shot 2021-12-09 at 12 50 58 PM" src="https://user-images.githubusercontent.com/59077132/145331458-1cec8e7f-0282-44d7-8379-7d5945cfb14f.png">

### Expected Behavior

Even though it is a failed transaction, if the input data is valid it should return the correct decoded parameters, or else in my opinion I would prefer that it throws an error that my code could catch and handle the error on my own without my app crashing.

### Steps to Reproduce

```typescript
import Web3 from 'web3';

const provider = new Web3.providers.HttpProvider('your provider url');
const web3 = new Web3(provider);

async function main() {
  const result = web3.eth.abi.decodeParameters(
    ['uint256', 'uint256', 'address[]', 'address', 'uint256'],
    '00000000000000000000000000000000000000000000000000005af3107a40001e66666666666600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000364426a650dfefefc645de176569e5648b91766f00000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000005ca42204cdaa70d5c773946e69de942b85ca6706000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c',
  );
  console.log(result);
}
main();
```

### Web3.js Version

1.6.1

### Environment

- Operating System: Mac OS
- Browser: Chrome
- Node.js Version: 17.0.1
- NPM Version: 8.1.0

**Comment by nazarhussain** [comment]
Hi @dnjscksdn98 Thanks for reporting the issue. I was able to reproduce it with the given example. We will look further into it and get back to you.

**Comment by 0xthierry** [comment]
Hey, I started investigating this issue.

I was able to reproduce the same behavior. I started debugging and got the following results when I call `ethersAbiCoder.decode` we got an out of memory, so it looks that the problem is inside `@ethersproject/abi`.

I added the logs bellow

```javascript
console.log('before call ethersAbiCoder.decode')
var res = ethersAbiCoder.decode(mapTypes, '0x' + bytes.replace(/0x/i, ''), loose);
console.log('after call ethersAbiCoder.decode')
```

Results:

```
before call ethersAbiCoder.decode

<--- Last few GCs --->

[95182:0x102e95000]    39697 ms: Scavenge 1865.9 (1879.1) -> 1864.9 (1902.1) MB, 11.0 / 0.0 ms  (average mu = 0.992, current mu = 0.992) allocation failure 
[95182:0x102e95000]    40136 ms: Scavenge 1880.9 (1902.1) -> 1882.8 (1904.1) MB, 19.4 / 0.0 ms  (average mu = 0.992, current mu = 0.992) allocation failure 
[95182:0x102e95000]    40159 ms: Scavenge 1882.9 (1904.1) -> 1880.9 (1918.1) MB, 23.6 / 0.0 ms  (average mu = 0.992, current mu = 0.992) allocation failure 


<--- JS stacktrace --->
```

Do we should open an issue in **[ethersproject](https://github.com/ethers-io/ethers.js/tree/master/packages/abi)** or keep the investigation here? @nazarhussain 

Obs: It's my first time contributing to the project so I'm learning, feel free to correct me @nazarhussain

**Comment by dnjscksdn98** [comment]
Hi any progress for this issue?
