### ISSUE TITLE
EIP-1559 transaction but the current network does not support - code: -32602

### ISSUE THREAD

**Issue by codecube47** [ethereum/web3.js#4619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi There! Do you have any idea what is going on here, 

`" MetaMask - RPC Error: Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559 {code: -32602, message: “Invalid transaction params: params specify an EIP-…but the current network does not support EIP-1559 "}`

This is the way I called

     ` const WETH9 = new web3.eth.Contract(abiWETH9, contractAddressERC20);
      WETH9.methods.approve(marketContract, amount).send({from: walletAddress})`

The above code is working on some of Metamasks, Is this something related to Metamask?.

### Expected Behavior

This is working on some of Metamask but not in window metamask

### Steps to Reproduce

```
const WETH9 = new web3.eth.Contract(abiWETH9, contractAddressERC20);
WETH9.methods.approve(marketContract, amount).send({from: walletAddress})
.on('receipt', function (receipt) {
    console.log("log")
})
```

### Web3.js Version

1.6.1

### Environment

- Operating System:  Windows
- Browser:  Chrome
- Node.js Version:  v12.22.1
- NPM Version:  6.14.12

**Comment by sweetmantech** [comment]
I'm seeing the same behavior.

Does anyone know a solution?

**Comment by jdevcs** [comment]
@vusaalab web3.js already supports eip1559 . This seems issue in metamask.
