### ISSUE TITLE
In web3-core update TransactionConfig Interface to include gasLimit

### ISSUE THREAD

**Issue by FraSaid** [ethereum/web3.js#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

As of version 1.6.1 if a user was to use typescript to send a transaction theu a eth based chain it would fail, with error: "Missing Gas".
This is simply the consequence of a missing property in the TransactionConfig Interface.

### Use Cases

Whoever may want to send an eth compatible transaction using Typescript instead of Javascript would actually be able to do this without editing the Interface himself

### Implementation Ideas

export interface TransactionConfig {
    from?: string | number;
    to?: string;
    value?: number | string | BN;
    gas?: number | string;
    gasPrice?: number | string | BN;
    gasLimit?: number | string | BN;
    data?: string;
    nonce?: number;
    chainId?: number;
    common?: Common;
    chain?: string;
    hardfork?: string;
}

### Are you willing to implement this feature?

- [X] Yes

**Comment by nazarhussain** [comment]
Hi @FraSaid Thanks for reaching out to us. That's obviously a nice idea and most of it already been in discussion to make transaction creation and signing more flexible. Currently all our efforts are focused on `4.x` rewrite so I will include your request to be considered for that release. If you want to know further about `4.x` please checkout our [blog post](https://medium.com/chainsafe-systems/web3-js-solid-foundations-create-stable-structures-1674514fe35) for it.

**Comment by mconnelly8** [comment]
Hi @FraSaid, we suggest that you use 4.x when it is released.  This will not be an issue in the rewrite.   We will be closing this issue since an update will not be made to 1.x.
