### ISSUE TITLE
Add getTransactions(address)!

### ISSUE THREAD

**Issue by carsenk** [ethereum/web3.js#463]
This was already posted almost a year ago: https://github.com/ethereum/go-ethereum/issues/1897

I am really surprised this still has not been added, it is a must have function to be able to pull in transactions from a particular address, all we currently have is getTransactionCount.

Post here if you agree with adding: **getTransaction(address)**

It would be nice to see like getContracts etc. as well...

**Comment by ArtemKo7v** [comment]
+1
We can't build full featured app without this feature. Highly demanded.

**Comment by obscuren** [comment]
We understand this is a highly requested feature. For all the right and wrong reasons please refer to the other issue that was mentioned in @carsenk feature request.

**Comment by frozeman** [comment]
Yes this is not the right place to debate this. See https://github.com/ethereum/go-ethereum/issues/1897
