### ISSUE TITLE
Link `tsconfig.json` file for `web3-eth-accounts` package to templates

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to the issue https://github.com/ethereumjs/ethereumjs-monorepo/issues/1615 we have to create an independent `tsconfig.json` file for `web3-eth-accounts` package. 

So we have to track the issue and once its fix on our side. 

### Expected Behavior

The `tsconfig.json` files for every package should be linked to the templates. 

### Steps to Reproduce

https://github.com/ChainSafe/web3.js/pull/4607/files#r768699324

### Web3.js Version

4.x

**Comment by RenoBozo** [comment]
I have an ongoing isssue on this with the poly pointing to the tsconfig file on nodejs...

**Comment by mconnelly8** [comment]
Will need to review to see if the external issue still exists.
