### ISSUE TITLE
Module not found / Configure polyfill

### ISSUE THREAD

**Issue by RenoBozo** [ethereum/web3.js#4638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Compiled with problems:X

ERROR in ./node_modules/eth-lib/lib/bytes.js 9:193-227

Module not found: Error: Can't resolve 'crypto' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\eth-lib\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

ERROR in ./node_modules/web3-eth-accounts/lib/index.js 31:74-91

Module not found: Error: Can't resolve 'crypto' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\web3-eth-accounts\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

ERROR in ./node_modules/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js 7:193-227

Module not found: Error: Can't resolve 'crypto' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\web3-eth-accounts\node_modules\eth-lib\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

ERROR in ./node_modules/web3-providers-http/lib/index.js 30:11-26

Module not found: Error: Can't resolve 'http' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\web3-providers-http\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }

ERROR in ./node_modules/web3-providers-http/lib/index.js 32:12-28

Module not found: Error: Can't resolve 'https' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\web3-providers-http\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }

ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js 37:11-26

Module not found: Error: Can't resolve 'http' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }

ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js 39:12-28

Module not found: Error: Can't resolve 'https' in 'D:\Metaverse\Code\Tutorials\NFTGame\v3\gamenpm\node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }

### Expected Behavior

To be able to import web3 on a react app build on node js as expected

### Steps to Reproduce

npx create-react-app app
cd app
yarn add redux
yarn add redux-thunk
yarn add react-redux
yarn add web3
yarn add styled-components
yarn add @openzeppelin/contracts

tried with npm -> same issue

in App.js → import Web3 from "web3";

### Web3.js Version

^1.6.1

### Environment

- Operating System: win
- Browser: chrome
- Node.js Version: v16.13.0
- NPM Version: 8.1.0

### Anything Else?

Thanks for the help

**Comment by Loque18** [comment]
I am having this same error, is not even necessary to add other libraries, I got this error doing the following 

npx create-react-app app
cd app
npm i web3 
in App.js → import Web3 from "web3";

web3.js version → 1.6.1

for now Only solution is to downgrade web3 version :(

**Comment by nazarhussain** [comment]
Seems related to https://github.com/ChainSafe/web3.js/issues/4579

**Comment by nazarhussain** [comment]
@RenoBozo Thanks for reaching out to us. I linked another issue which also reflects the similar bug, see the discussion there. it may solve your problem. 

It seems lie the issue related to your build manage, probably webpack in case of React. Recent version of webpack [drops support for native node js polyfils by default](https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1). So you have to add a polyfil to your project dependencies by your self. Check this [doc](https://webpack.js.org/configuration/resolve/#resolvefallback) which also listed the fallback configuration for the `crypto` package. 

Let me know if that helps.

**Comment by ratracegrad** [comment]
The issue is only with create-react-app v5 which was released 5 days ago. They use Webpack v5 which removed polyfills for node. As mentioned above if you follow these steps:
npx create-react-app myApp (must use create-react-app v5)
cd myApp
npm install web3
open up App.js and add line to import in web3 <- it is adding this line causes errors related to the polyfills that have been removed in Webpack v5 mainly support for node.

**Comment by ehteshaxm** [comment]
What's the permanent solution for this? For now, I just downgraded to react-scripts@4.0.3 and its working fine

**Comment by danim72** [comment]
Here you have the solution that works out for gatsby 

https://stackoverflow.com/questions/66952972/cannot-add-web3-to-react-project

**Comment by danim72** [comment]
Resolved using the following webpack 5.x configuration though:

(Adding the following config in gatsby-node.js)
```

// Following snippet from solution checked under https://stackoverflow.com/questions/66952972/cannot-add-web3-to-react-project
const webpack = require("webpack");

exports.onCreateWebpackConfig = ({ actions }) => {
    actions.setWebpackConfig({
        plugins: [
            new webpack.ProvidePlugin({
              process: 'process/browser',
              Buffer: ['buffer', 'Buffer'],
            }),
            new webpack.DefinePlugin({
              'process.env.NODE_ENV': JSON.stringify('development')
            })
        ],
        resolve: {
          fallback: {
            assert: require.resolve('assert'),
            buffer: require.resolve('buffer'),
            console: require.resolve('console-browserify'),
            constants: require.resolve('constants-browserify'),
            crypto: require.resolve('crypto-browserify'),
            domain: require.resolve('domain-browser'),
            events: require.resolve('events'),
            http: require.resolve('stream-http'),
            https: require.resolve('https-browserify'),
            os: require.resolve('os-browserify/browser'),
            path: require.resolve('path-browserify'),
            punycode: require.resolve('punycode'),
            process: require.resolve('process/browser'),
            querystring: require.resolve('querystring-es3'),
            stream: require.resolve('stream-browserify'),
            string_decoder: require.resolve('string_decoder'),
            sys: require.resolve('util'),
            timers: require.resolve('timers-browserify'),
            tty: require.resolve('tty-browserify'),
            url: require.resolve('url'),
            util: require.resolve('util'),
            vm: require.resolve('vm-browserify'),
            zlib: require.resolve('browserify-zlib')
          },
        },
    })
}
```

**Comment by nazarhussain** [comment]
As mentioned by https://github.com/ChainSafe/web3.js/issues/4638#issuecomment-997318810 and https://github.com/ChainSafe/web3.js/issues/4638#issuecomment-996777895 the issue is caused by behavior of Webpack5, which removes the support for the NodeJS polyfills by default. 



As mentioned by above comment one can add those polyfills back with webpack config `resovle`.

**Comment by nolanjannotta** [comment]
> What's the permanent solution for this? For now, I just downgraded to react-scripts@4.0.3 and its working fine

I would like to echo this, worked for me too. 
I changed the react-scripts version, then uninstalled and reinstalled web3, then restarted the react server and it works 👍
Im not sure if the last two steps were necessary but, it works now!
Thanks @ehteshaxm

**Comment by ion-girloanta** [comment]
> > What's the permanent solution for this? For now, I just downgraded to react-scripts@4.0.3 and its working fine
> 
> I would like to echo this, worked for me too. I changed the react-scripts version, then uninstalled and reinstalled web3, then restarted the react server and it works 👍 Im not sure if the last two steps were necessary but, it works now! Thanks @ehteshaxm

Work for me to       npm install --save --save-exact react-scripts@4.0.2

**Comment by DecoratedWings** [comment]
> 

Worked for me thanks!

**Comment by DecoratedWings** [comment]
> > > What's the permanent solution for this? For now, I just downgraded to react-scripts@4.0.3 and its working fine
> > 
> > 
> > I would like to echo this, worked for me too. I changed the react-scripts version, then uninstalled and reinstalled web3, then restarted the react server and it works 👍 Im not sure if the last two steps were necessary but, it works now! Thanks @ehteshaxm
> 
> Work for me to npm install --save --save-exact react-scripts@4.0.2

Worked for me, thanks!

**Comment by taimaruuu** [comment]
also worked for me. make sure to close the running localhost and re-run 'npm start'

**Comment by taimaruuu** [comment]
> 

Also worked for me. Be sure to re-run 'npm start' after doing this though.

**Comment by taimaruuu** [comment]
> > > > What's the permanent solution for this? For now, I just downgraded to react-scripts@4.0.3 and its working fine
> > > 
> > > 
> > > I would like to echo this, worked for me too. I changed the react-scripts version, then uninstalled and reinstalled web3, then restarted the react server and it works 👍 Im not sure if the last two steps were necessary but, it works now! Thanks @ehteshaxm
> > 
> > 
> > Work for me to npm install --save --save-exact react-scripts@4.0.2
> 
> Worked for me, thanks!

Also worked for me. Be sure to re-run 'npm start' after doing this though.

**Comment by itssaptarshi** [comment]
Compiled with problems:X

ERROR in ../../../../../node_modules/cipher-base/index.js 3:16-43

Module not found: Error: Can't resolve 'stream' in 'C:\Users\KOYEL DUTTA\node_modules\cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }


ERROR in ../../../../../node_modules/eth-lib/lib/bytes.js 9:193-227

Module not found: Error: Can't resolve 'crypto' in 'C:\Users\KOYEL DUTTA\node_modules\eth-lib\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }


ERROR in ../../../../../node_modules/web3-eth-accounts/lib/index.js 31:74-91

Module not found: Error: Can't resolve 'crypto' in 'C:\Users\KOYEL DUTTA\node_modules\web3-eth-accounts\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }


ERROR in ../../../../../node_modules/web3-eth-accounts/node_modules/eth-lib/lib/bytes.js 7:193-227

Module not found: Error: Can't resolve 'crypto' in 'C:\Users\KOYEL DUTTA\node_modules\web3-eth-accounts\node_modules\eth-lib\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }


ERROR in ../../../../../node_modules/web3-providers-http/lib/index.js 30:11-26

Module not found: Error: Can't resolve 'http' in 'C:\Users\KOYEL DUTTA\node_modules\web3-providers-http\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }


ERROR in ../../../../../node_modules/web3-providers-http/lib/index.js 32:12-28

Module not found: Error: Can't resolve 'https' in 'C:\Users\KOYEL DUTTA\node_modules\web3-providers-http\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }


ERROR in ../../../../../node_modules/xhr2-cookies/dist/xml-http-request.js 37:11-26

Module not found: Error: Can't resolve 'http' in 'C:\Users\KOYEL DUTTA\node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }


ERROR in ../../../../../node_modules/xhr2-cookies/dist/xml-http-request.js 39:12-28

Module not found: Error: Can't resolve 'https' in 'C:\Users\KOYEL DUTTA\node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }


ERROR in ../../../../../node_modules/xhr2-cookies/dist/xml-http-request.js 41:9-22

Module not found: Error: Can't resolve 'os' in 'C:\Users\KOYEL DUTTA\node_modules\xhr2-cookies\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }



I am getting this exact error whatever I do, can anyone tell me how to solve this?
