### ISSUE TITLE
Returned values aren't valid, did it run Out of Gas

### ISSUE THREAD

**Issue by VictorPulzz** [ethereum/web3.js#4641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello guys please help me,
This my code: 
![image](https://user-images.githubusercontent.com/23406402/146566109-a2fb30d3-a27e-40d9-bfae-40cac8433ef8.png)
This code work correctly when I use test network in metamask, but when I switch to other, I got this issue:
![image](https://user-images.githubusercontent.com/23406402/146565762-35396bf6-69f1-49b7-b4f3-d785bf0fa489.png)

### Expected Behavior

Not got error :D

### Steps to Reproduce
In here contract: https://rinkeby.etherscan.io/address/0x619b945d410841597bcca76dec750653e3ccd10e
```
const contract = new web3.eth.Contract(abi, contractToken, {
  from: publicAddress,
});
Web3.utils.fromWei(await contract.methods.balanceOf(publicAddress).call()```

### Web3.js Version

1.6.0

### Environment

- Operating System: Windows 10 x64 
- Browser: Chrome
- Node.js Version: 14.16.0
- NPM Version: 6.14.11


### Anything Else?

_No response_

**Comment by JulienRst** [comment]
Hi @VictorPulzz , how did you manage to fix your issue ?
