### ISSUE TITLE
`WebEthTx` class

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4652]
- Should create an [@ethereumjs/tx](https://www.npmjs.com/package/@ethereumjs/tx) transaction instance using provided transaction object
- Static methods
    - The below methods should support a user defined method being passed as an argument to override default way of determination
        - `detectTransactionType` method
        - `validateTransaction` method
        - `fillTransaction` method
- Should have setting in `Web3Context` for default transaction type when `detectTransactionType` is inconclusive

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4652?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
