### ISSUE TITLE
Methods that require to use .request in batch calls fail typescript

### ISSUE THREAD

**Issue by Nilotaviano** [ethereum/web3.js#4655]
Same issue as: https://github.com/ChainSafe/web3.js/issues/3144

> ### Description
> To perform batch requests and add to batches we need to append `.request` on methods i.e
> 
> ```
>  batch.add(web3.eth.getBlock.request(blockNumber));
> ```
> 
> I believe type definitions don't have this `.request` option specified as it fails.
> 
> #### Expected behavior
> Appending `.request` in batches should not throw type errors.
> 
> #### Actual behavior

> ### Description
> To perform batch requests and add to batches we need to append `.request` on methods i.e
> 
> ```
>  batch.add(web3.eth.getBlock.request(blockNumber));
> ```
> 
> I believe type definitions don't have this `.request` option specified as it fails.
> 
> #### Expected behavior
> Appending `.request` in batches should not throw type errors.
> 
> #### Actual behavior
> <img alt="Screenshot 2019-10-18 at 16 55 46" width="739" src="https://user-images.githubusercontent.com/3154053/67100349-29e2e680-f1c8-11e9-8a4e-b1be61e0be8a.png">
> 
> ### Versions
> * web3.js: 2.0.0-alpha.1
> * nodejs: 10.16.3
> * browser: Chrome latest
> * ethereum node: Metamask

**Comment by thierrysantos** [comment]
Hey @Nilotaviano,

I will be investigating this issue

**Comment by FreetzBB** [comment]
same issue here
cannot batch.add sendSignedTransaction:
 
batch.add(web3.eth.sendSignedTransaction.request(signedtxObjectApproval.rawTransaction ....
gives ERROR: the property "request" does not exist on type PromiEvent

**Comment by nazarhussain** [comment]
@Nilotaviano Thanks for sharing this issue. 

I tried the following code with `1.5.2` version and was able to reproduce the error. 


```ts
import Web3 from "web3";
const web3 = new Web3(Web3.givenProvider || "http://localhost:8545");

const batch = new web3.BatchRequest();
batch.add(web3.eth.getBlock.request(1));

```

The detail error is: 

```
error TS2339: Property 'request' does not exist on type '{ (blockHashOrBlockNumber: BlockNumber): Promise<BlockTransactionString>; (blockHashOrBlockNumber: BlockNumber, returnTransactionObjects: boolean): Promise<...>; (blockHashOrBlockNumber: BlockNumber, callback?: (error: Error, block: BlockTransactionString) => void): Promise<...>; (blockHashOrBlockNumber: BlockNumber...'.
```

We will look into this further.

**Comment by Nilotaviano** [comment]
Thank you for looking into it, @nazarhussain!

**Comment by Ezzahhh** [comment]
Just chiming in to say that this is still a problem 👍

**Comment by dattp** [comment]
> same issue here cannot batch.add sendSignedTransaction:
> 
> batch.add(web3.eth.sendSignedTransaction.request(signedtxObjectApproval.rawTransaction .... gives ERROR: the property "request" does not exist on type PromiEvent

same issue when i using `web3.eth.call.request(trans, callback)`. 
@nazarhussain  when will there be a new update for this issue?

**Comment by alexleventer** [comment]
Also running into this

**Comment by nazarhussain** [comment]
According to the workload we will plan this in some future sprints. FYI @jdevcs

**Comment by aymantaybi** [comment]
While waiting for the issue to be resolved, here’s a workaround :

```
var batch = new web3.BatchRequest();

var getBlock: any = web3.eth.getBlock;

batch.add(getBlock.request("latest"));
```
