### ISSUE TITLE
Wrong input type in first parameter of web3.eth.sign in documentation.

### ISSUE THREAD

**Issue by mpcabete** [ethereum/web3.js#4657]
I am referring to this line plus the example:
https://github.com/ChainSafe/web3.js/blob/87e668275ac7d9b8af7c909137fc0626c3866929/docs/web3-eth.rst#L1582

The documentations specify that the first input should be :
`String - Data to sign. If it is a string it will be converted using web3.utils.utf8ToHex.`

If an string or an string parsed trough "web3.utils.utf8ToHex()" is passed the function returns the following error:
`{ code: -32602, message: "eth_sign requires 32 byte message hash" }`
when the first argument is the hash provided by web3.utils.sha3() the function executes successfully.

ps:
if an random (yet valid) address is provided, it returns the following error:
`Object { code: -32602, message: "Invalid parameters: must provide an Ethereum address." }`
which is not very helpful. the error message should be more specific.

**Comment by luu-alex** [comment]
Hey thanks for creating this issue, I was able to succesfully pass a string without returning the error, as well I passed a string through `web3.utils.uf8ToHex()` in the first parameter and was succesful.

Can you paste the code that lead to you these errors?

**Comment by Deekor** [comment]
I'm having the same issue. I noticed the docs only go to `v1.5.2` and I'm on `v1.6.1` could something have changed in the newest version? I should note I'm attempting this with metamask.

Edit:
I discovered `web3.eth.personal.sign` is working properly.

**Comment by jdevcs** [comment]
Hi @Deekor , Could you test it using 1.7.0 and latest doc is now available for [1.7.0](https://web3js.readthedocs.io/en/v1.7.0/) , you may re open issue if `web3.eth.personal.sign` is not working in 1.7.0

**Comment by Deekor** [comment]
@jdevcs personal was working, it was `web3.eth.sign` that wasn't working.

**Comment by AlbertLin0327** [comment]
Either the doc is incorrect or the function is incorrect.
https://web3js.readthedocs.io/en/v1.7.0/web3-eth.html#sign

**Comment by evvvritt** [comment]
I'm also getting the same error in 1.7.0, following the inputs from the docs.

**Comment by evvvritt** [comment]
I guess I was looking for a `signTypedData` / EIP 712 method. Only found a lot of pain in #3449 and #2697. Instead, I found [this guide](https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290) and adapted to the following:
```
const msgParams = [
  {
    type: 'string',      // Any valid solidity type
    name: 'Message',     // Any string label you want
    value: 'Hi, Alice!'  // The value to sign
 },
 {   
   type: 'uint32',
      name: 'A number',
      value: '1337'
  }
] 

// Get the current account:
web3.eth.getAccounts(function (err, accounts) {
  if (!accounts) return
  signMsg(msgParams, accounts[0])
})

// helper
function signMsg(msgParams, from) {
  web3.currentProvider.sendAsync({
    method: 'eth_signTypedData',
    params: [msgParams, from],
    from: from,
  }, function (err, result) {
    if (err) return console.error(err)
    if (result.error) {
      return console.error(result.error.message)
    }
    console.log('signature:', result.result)
  })
}
```

**Comment by lbhsot** [comment]
So we cannot use `web3.eth.sign` any more?
