### ISSUE TITLE
Error :  Redefinition of module 'fmt'  in xcode 13

### ISSUE THREAD

**Issue by virendrasinhr** [ethereum/web3.js#4660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Build fail in xcode 13 due to following error:  
   Error :  Redefinition of module 'fmt'.

### Expected Behavior

Build project with web3 to implement blockchain.

### Steps to Reproduce

in pod file :

```
  pod 'MagicSDK'

  pod 'BigInt'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-selectable-text', :path => '../node_modules/@astrocoders/react-native-selectable-text'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  
```

  also tried: 
  
  pod web3 , '~> (versions)'

### Web3.js Version

1.6.1

### Environment

- Operating System:  mac m1 
- Browser: chrome
- Node.js Version:  12.22.1
- NPM Version: 6.4.12

- MagicSdk : 2.4.0

- Technology : react-native

**Comment by nazarhussain** [comment]
@royalvirendra Apparently this does not seems related to `web3.js`. As we don't have or using any `fmt` package.

Please share more details to this error. At least the complete error trace.

**Comment by virendrasinhr** [comment]
We are not able to reproduce this issue, because we are facing  the below mentioned issue  :

Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Build/Products/Debug-iphonesimulator/BigInt/BigInt.swiftmodule

![image](https://user-images.githubusercontent.com/75446531/148640452-87abc320-7d45-47a4-8cd3-9d31577a23a2.png)

### For More Info: 

https://github.com/magiclabs/magic-js/issues/259#issuecomment-1007947265

**Comment by nazarhussain** [comment]
As per the error log it does not seems to be related to the `web3` library it self. I suggest you should take up this issue with https://github.com/attaswift/BigInt. 

I am closing this issue for now, feel free to re-open if you have any web3 relevant findings.
