### ISSUE TITLE
`web3-validator` TODOs

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4667]
- [x] [Remove duplicate `web3-validator` code](https://github.com/ChainSafe/web3.js/tree/e21d55bd6cdc8c181289e8faaf9afa691508d2e1/packages/web3-validator/src/validation)
- [x] [Validate nested arrays](https://github.com/ChainSafe/web3.js/blob/e21d55bd6cdc8c181289e8faaf9afa691508d2e1/packages/web3-validator/src/utils.ts#L19)
- [x] [Investiate strippedType error](https://github.com/ChainSafe/web3.js/pull/4625/files?authenticity_token=Jyj1HxIDxE56HhVoTr8sPe_cV9Yu9mtl6oOI1tHXqSDztypQkrLr4Ceiot-NPh1RSlyOmBZjiYuhbahkaEVXIA&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts#diff-e86b1e01f7a57301af06c74bc73538ab099d9ca77afb1ae178aa0faf0acf5c9aR30)

**Comment by yangm33** [comment]
> * [x]  [Remove duplicate `web3-validator` code](https://github.com/ChainSafe/web3.js/tree/e21d55bd6cdc8c181289e8faaf9afa691508d2e1/packages/web3-validator/src/validation)
> * [x]  [Validate nested arrays](https://github.com/ChainSafe/web3.js/blob/e21d55bd6cdc8c181289e8faaf9afa691508d2e1/packages/web3-validator/src/utils.ts#L19)
> * [x]  [Investiate strippedType error](https://github.com/ChainSafe/web3.js/pull/4625/files?authenticity_token=Jyj1HxIDxE56HhVoTr8sPe_cV9Yu9mtl6oOI1tHXqSDztypQkrLr4Ceiot-NPh1RSlyOmBZjiYuhbahkaEVXIA&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts#diff-e86b1e01f7a57301af06c74bc73538ab099d9ca77afb1ae178aa0faf0acf5c9aR30)
