### ISSUE TITLE
Create the web3 package structure for 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4679]
## Description: 
Web3 is its own package so to start we need to create a package structure.

## Acceptance criteria:

Package must have same package information as 1.x branch
Package must have jest unit test configurations

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4679?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
