### ISSUE TITLE
Create the Web3 class - 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4680]
## Description:
- Web3 object includes: 
- Web3.version 
- Web3.utils
- Web3.modules - Include the packages that will be released with 4.0 alpha release within modules (without bzz and shh package)
- Web3.setProvider
- Web3.providers
- Web3.givenProvider
- Web3.currentProvider
- Web3.BatchRequest

## Acceptance Criteria:
Create the Web3 type to have same functionality as 1.x
Create unit test cases for the web3 type

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4680?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
