### ISSUE TITLE
Property 'send' does not exist on type 'string'. Why a provider can be a string?

### ISSUE THREAD

**Issue by brucexu-eth** [ethereum/web3.js#4684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

Hi guys, I'm doing an example with TypeScript, the code sandbox is https://codesandbox.io/s/rough-shadow-m85c3?file=/src/App.tsx.

When I invoke the send from `web3.currentProvider`, TS throw an error: Property 'send' does not exist on type 'string'.

![image](https://user-images.githubusercontent.com/95468177/148841549-32c70f26-815c-4db9-a6d0-cd91fa4361fc.png)

So I took a look at the code and document, the type definition is in here https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core/types/index.d.ts#L455 and from the document, didn't find it can return a string https://web3js.readthedocs.io/en/v1.5.2/web3.html#currentprovider.

![image](https://user-images.githubusercontent.com/95468177/148842055-8290908e-0d01-4fd6-9423-b7c713b9cf51.png)

Also, it doesn't make sense to me that one of the providers is a string, so just wondering if it is a Type definition issue or a document issue? Thanks.

**Comment by nicholaswhittle** [comment]
Did you find the issue with this?
