### ISSUE TITLE
IBAN Basic Functions

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4687]
### Description:

- toAddress: Converts a direct IBAN address into an Ethereum address.
- toIban: Converts an Ethereum address to a direct IBAN address.
- From address: Converts an Ethereum address to a direct IBAN instance.
- from Bban: Converts BBAN address to a direct IBAN instance.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4687?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
