### ISSUE TITLE
Checksum institution and Client functions

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4689]
### Description:

- checksum: Returns the checksum of the IBAN instance.
- institution: Returns the institution of the IBAN instance.
- client: Returns the client of the IBAN instance.
- toString: Returns the IBAN address of the IBAN instance.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4689?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
