### ISSUE TITLE
Error: data out-of-bounds when calling any contract via Websocket Infura RPC

### ISSUE THREAD

**Issue by danielblnc** [ethereum/web3.js#4695]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After changing RPC provider from Infura HTTPS to WSS, every contract call throws a "data out-of-bounds", "BUFFER_OVERRUN" error.

```
Error: data out-of-bounds (length=3, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)
...callstack...
reason: 'data out-of-bounds',
  code: 'BUFFER_OVERRUN',
  length: 3,
  offset: 32
```

### Expected Behavior

Contract should be called with no error.

### Steps to Reproduce

I can reproduce the issue with this code:

```
require('dotenv').config()
const Web3 = require('web3')
const HDWalletProvider = require('@truffle/hdwallet-provider')
const ERC20_ABI = require("./ABIs/ERC20.json")

const rpcUrl = "wss://mainnet.infura.io/ws/v3/" + process.env.INFURA_TOKEN
const rpcUrlHttps = "https://mainnet.infura.io/v3/" + process.env.INFURA_TOKEN

const provider = new HDWalletProvider(process.env.PRIVATE_KEY, rpcUrl)
const web3 = new Web3(provider)


const daiContract = new web3.eth.Contract(ERC20_ABI, "0x6B175474E89094C44Da98b954EedeAC495271d0F")

async function test() {
    const totalSupply = await daiContract.methods.totalSupply().call()
    console.log(totalSupply)
}

test()
```

When using `rpcUrlHttps` instead of `rpcUrl` the correct result is shown in the console.

### Web3.js Version

1.6.1

### Environment

- Operating System: Windows 11
- Node.js Version: 16.13.1 
- NPM Version: 8.1.2

### Anything Else?

These questions seem to be related:

[https://ethereum.stackexchange.com/questions/87717/contract-call-data-out-of-bounds](url)
[https://ethereum.stackexchange.com/questions/92486/web3-error-value-out-of-bounds-when-passing-in-value-for-smart-contract-call](url)

Also this issue:
[https://github.com/ChainSafe/web3.js/issues/3863](url)

**Comment by luu-alex** [comment]
Thank you for this issue, a team member will take a look into this when we have the bandwidth to investigate.

**Comment by igostavro** [comment]
bump. I am experiencing the same issue, and I don't see that it was moved or resolved. Any ideas?

UPDATE AND FIX for anyone else who lands here:

"@truffle/hdwallet-provider": "^2.1.7", <-- make sure this is at least this version in your package.json
