### ISSUE TITLE
web3-providers-http@1.61 pins "xhr2-cookies": "1.1.0" in "dependencies", a node.js-only polyfil

### ISSUE THREAD

**Issue by TimDaub** [ethereum/web3.js#4696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- xhr2-cookies uses the nodejs "os" package: https://nodejs.org/api/os.html
- E.g. browsers don't have a "os" module available. The "os" module cannot be shimmed in a browser environment either.
- A problem can be that, hence, an application that uses web3 cannot create working builds for the browser: https://github.com/oceanprotocol/ocean.js/issues/1155#issuecomment-1010863005

### Expected Behavior

- A `web3-providers-http` provider that both works on all environments equally
- e.g. "cross-fetch" implements a What-WG standard that ends up being natively implemented on all JavaScript platforms

### Steps to Reproduce

- Use web3-providers-http and try using it in a browser

### Web3.js Version

1.61

**Comment by jdevcs** [comment]
@TimDaub Thanks for reporting this. 
We are using [cross-fetch](https://github.com/ChainSafe/web3.js/blob/24b4ca7feafb29baf2cee9e5d860c946b51b709a/packages/web3-providers-http/package.json#L43) in web3.js [4.x](https://github.com/ChainSafe/web3.js/tree/4.x) , so this issue will be fixed 4.x release.
