### ISSUE TITLE
Web3 extend functionality - 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4699]
Still need discussion on the importance and use cases of web3.extend

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by Spacesai1or** [comment]
[Open discussion](https://github.com/ChainSafe/web3.js/discussions/4653)

**Comment by jdevcs** [comment]
@spacesailor24 In Package Instantiation discussion this [extend](https://web3js.readthedocs.io/en/v1.7.0/web3.html#extend) should also be part of requirement.
