### ISSUE TITLE
Required bignumber.js inaccessible

### ISSUE THREAD

**Issue by flyswatter** [ethereum/web3.js#470]
Not sure if this is just me, but as of today, if I try to `npm install` web3, I get a failure at the `bignumber.js` dependency.

```
npm ERR! git fetch -a origin (https://github.com/debris/bignumber.js.git) fatal: unable to access 'https://github.com/debris/bignumber.js.git/': Couldn't connect to server
```

I notice it's hardcoded at `https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2`. Maybe there's a newer version that also works?

I also tried pulling this commit manually and it failed, I'm not sure it's still available.

**Comment by frozeman** [comment]
we didnt publish a new version, can you try again, maybe your internet was down. The commit definitely exists in debris library

**Comment by flyswatter** [comment]
Yup, this was a crazy git problem with an https proxy, thanks!

**Comment by apackin** [comment]
A few of us are getting this same issue over at https://github.com/npm/npm/issues/17413
How did you end up fixing this @flyswatter ?

**Comment by stanishev** [comment]
seems like we're seeing the same symptoms but for different reasons. a pr is in progress here: 
https://github.com/ethereum/web3.js/issues/904
