### ISSUE TITLE
Security lack in web3.personal

### ISSUE THREAD

**Issue by zikilemini** [ethereum/web3.js#471]
Hello,

I saw you can send transaction by unlocking account with web3.personal. But it doesn't seems secure at all ! Some could send ransaction with the accoutn during the unlocking time.

Is there a lib or something like that I could use in my Dapp to send transaction ?

**Comment by frozeman** [comment]
RPC over HTTP is not activated by default in the nodes and shouldn't. Its up to the developer to protect his dapp when using this function.

To generate and send signed transaction your can use the new `web3.eth.accounts` in web3.js 1.0 http://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html
