### ISSUE TITLE
Web3 Eth Personal

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4720]
### Description
**Following function are for interacting with wallet located in Eth node, these are not for local wallet.**
Having following functionality in 4.x:

- newAccount: Creates a new account
- sign : The method used for signing
- ecRecover : Recovers the account that signed the data.
- signTransaction: Signs a transaction. This account needs to be unlocked.
- sendTransaction: This method sends a transaction over the management API.
- unlockAccount: Signs data using a specific account.
- lockAccount: locksthe given account.
- getAccounts: Returns a list of accounts the node controls by using the provider and calling the RPC method personal_listAccounts
- importRawKey: Imports the given private key into the key store, encrypting it with the passphrase.

### Acceptance Criteria
This package must also expose following functionality by using existing packages.

- setProvider: Will change the provider for its module.
- providers: Contains the current available providers.
- givenProvider: When using web3.js in an Ethereum compatible browser, it will set with the current native provider by that browser. Will return the given provider by the (browser) environment, otherwise null.
- currentProvider: Will return the current provider, otherwise null.
- BatchRequest: Class to create and execute batch requests.

**Comment by cisan86** [comment]
web3.personal.unlockAccount        the method personal_unlockAccount does not exist/is not available

**Comment by jdevcs** [comment]
@cisan86 are you using geth?

**Comment by jdevcs** [comment]
If so : 

> The personal RPC namespace is now deprecated. In order to interact with personal APIs, you need to specifically allow it via the --rpc.enabledeprecatedpersonal command-line flag.
https://github.com/ethereum/go-ethereum/releases/tag/v1.11.0
