### ISSUE TITLE
Some exceptions thrown by web3-eth-account cannot be caught

### ISSUE THREAD

**Issue by kai-alpha** [ethereum/web3.js#4724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Accounts.signTransaction()` can generate a stray Promise under JS job queue, and there's no way for library users to catch any exceptions the stray promise throws, which can [kill the entire Node.js process](https://nodejs.org/api/process.html#event-uncaughtexception). A library shouldn't allow this to happen.

### Expected Behavior

`try { ... await account.signTransaction(tx) } catch (e) { ... }` should be able to catch any exceptions thrown (conceptually) within `signTransaction()` method

### Steps to Reproduce

Set `tx.maxPriorityFeePerGas` but not `maxFeePerGas` and send it to BSC (or any EVM-compatible blockchains without EIP-1559) to hit this `throw` at
https://github.com/ChainSafe/web3.js/blob/2b7c50a4cd27e5b21def779dd757cdacd2afd31a/packages/web3-eth-accounts/src/index.js#L433

Yes I know that doesn't make sense at all, but that's another story. A bug in our quick & dirty sandbox script led me to the issue.

### Web3.js Version

1.7.0

### Anything Else?

`_handleTxPricing()` runs something like
```
return new Promise((resolve, reject) => {
  try {
    Promise.all([two async REST calls]).then(
      ...use the return value of the two REST calls...;
      resolve(suggested values for maxPriorityFeePerGas and maxFeePerGas))
  } catch (e) { reject(e) }
}
```
to asynchronously return the suggested values with `resolve()`, but I think the problem is that any exceptions thrown within the inner `Promise.all()` (and its `then()` chain) aren't propagated to `reject()` from the outer Promise.

Here is what I believe is a minimal repro: [TS playground](https://www.typescriptlang.org/play?#code/DYUwLgBGAWBOD2B3A+hAvFWBXEAoXAZlgHYDGYAlvMRAQBQCUEA3rhBLOFrDcSIhAAKCALYUAziDp1O4+MABuIADQcQAKxDkmaAHws27TAE8DRo6WpzQAOmDwA5nQDkwAIYlS0CsQcQ3wMDODIbmwvBikjYBwHQA2gC6DDYwIMTSsljAYOI6+qzm5pbE1iB2ji4xALSpNJykIBRKACbOqpnZuaGFFAQQdDAIKEwFhUVW8mX2Ts6DSD5+WAAOwd1jcwIAorAIsC7ibq0hY+wAvmsWE7bTlYE10GkQzdQgqydq1koyIOJZOceFU4A8YlSblGbuTwPZr+QJvIynCCkNxgLz9EAjC7FUrglycTTkBYQRAUGBtCAYi74rRgOiU8znM4hc64NziYxkWieSjUCBOTHsMCwUyjdjYyAdHLofyINyk2iMbrYsE3Zx+eqNFrkyVdM5IlFoukCy6g64VNX6rAOaBgcn0iDnFnKs0zcRgNywSi+Vb8mzI1HQOnofTOqbm16qDEhUO41xsyAAGQA8gBhYJAA)

JS isn't among my core expertise, I can't use JS Promise without async/await so this is all I can share.

Ping @spacesailor24 according to Git history

**Comment by nazarhussain** [comment]
Thanks @kai-alpha for reporting the issue. We will look into to investigate further.

**Comment by kai-alpha** [comment]
wut, this is a real bug

**Comment by kristjanpeterson1** [comment]
Are there any updates on this? Seems like a very serious issue..

**Comment by kai-alpha** [comment]
Hmm nobody is fixing this bug? Last attempt to get attention (I'll let the bot close it next time)

**Comment by andreistefanwork** [comment]
Hi @kai-alpha! I was able to reproduce this issue as well. The problem seems to be indeed inside the inner Promise.all([promise1, promise2]) and its then() chain.

If an error occurs in either promise1, promise2 or inside then(...), it's not propagated to the outer Promise

This can be fixed using a catch(...) on the inner Promise.all()

I created the following [PR](https://github.com/ChainSafe/web3.js/pull/5080), in which I also included a test to cover this change. 

Can you double check everything looks alright?

**Comment by TangMonk** [comment]
Still problem?

**Comment by jdevcs** [comment]
@TangMonk @kai-alpha are you still able to reproduce ?

**Comment by cocacola-lover** [comment]
It still happens on 4.6.0
```
(async function test() {
  try {
    await web3.eth.sendSignedTransaction("")
  } catch (e) {
    console.log(e)
  }
})()
```
