### ISSUE TITLE
Docs: `Getting Started` does not mention node-polyfills for webpack & rollup

### ISSUE THREAD

**Issue by imsys** [ethereum/web3.js#4726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

The information is in the github Readme. Okay, I just saw it now but I would expect the ReadTheDocs to be more complete and have it there already.
The docs says to just use `npm install web3` and it will be all fine. At least have a link there saying: "to have information on how to make it work on bundles check the github readme"
The first error we get from not knowing this is: https://github.com/browserify/node-util/issues/43 and we all go ask support in their repo.

Anyway, there is also a node-polyfill for Vite, Rollup or SvelteKit that someone has posted a good working example at: https://github.com/blocknative/onboard/issues/762#issuecomment-997246672

The point is that not everyone could be finding how to make it work with bundlers, I was using it with <script> tags and doing some hackish things to get it working, and already planning to move all my code to ethers so I could integrate it well with a bundler.. but then I found the solution and I think this should be more visible so others doesn't spend so much time on this as well.

**Comment by jdevcs** [comment]
@imsys Thanks for suggestion, could you open PR and suggest changes in documentation.
