### ISSUE TITLE
Misc. 4.x Alpha items

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#4727]
( This is Epic for 4.x Management )

This Epic is for tracking required improvements or missing items in 4.x Alpha.

- [ ] https://github.com/ChainSafe/web3.js/issues/4735

- [ ] https://github.com/ChainSafe/web3.js/issues/4774

**Comment by jdevcs** [comment]
Added https://github.com/ChainSafe/web3.js/issues/4774
