### ISSUE TITLE
Trouble importing web3 to react app.

### ISSUE THREAD

**Issue by mtajammulzia** [ethereum/web3.js#4732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m running “npm install web3” and then “import Web3 from ‘web3’” and I’m getting a bunch of errors saying that “crypto” and other modules can’t be found cause of some polyfill error.

### Expected Behavior

Running “npm install web3” and then “import Web3 from ‘web3’” should not result in errors.

### Steps to Reproduce

Create a new react app -- npx create-react-app my-app
Go in the directory -- cd my-app
Install web3 -- npm i web3
Import web3 in src/App.js -- import Web3 from "web3"

### Web3.js Version

1.7.0

### Environment

- Operating System: Mac OS
- Browser: Chrome
- Node.js Version: 14.18.2
- NPM Version: 8.3.2

**Comment by AlexanderMint** [comment]
Just like the author, I get errors

**Comment by luu-alex** [comment]
theres a [solution ](https://github.com/ChainSafe/web3.js#web3-and-create-react-app)on the repo. check it out.
