### ISSUE TITLE
Docs: getTransaction documentation incorrect

### ISSUE THREAD

**Issue by BlockChange** [ethereum/web3.js#474]
Right here: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransaction

It says:

`web3.eth.getTransaction(transactionHash [, callback])`

Then the example goes:

`web3.eth.getTransaction(blockNumber, indexOfTransaction);`

So:
`blockNumber` has to be `transactionHash`, and I don't even know where `indexOfTransaction` is coming from, it's used nowhere else and seems to be confused with the `getTransactionFromBlock` example.

(Also: someone should test this on `testrpc`, it returns `null` every time, see: https://github.com/ethereumjs/testrpc/issues/121)

(Update: `geth` also returns `null`)

**Comment by frozeman** [comment]
Thanks, fixed the docs.
