### ISSUE TITLE
Error with command: npm install web3

### ISSUE THREAD

**Issue by mohamedmehdigara** [ethereum/web3.js#4740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.       
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-01-27T16_06_27_309Z-debug.log

### Expected Behavior

imported packages from contributors

### Steps to Reproduce

npm install web3

### Web3.js Version

1.5.3

### Environment

- Operating System: Windows 10
- Browser: Chrome
- Node.js Version: 16.13.1
- NPM Version: 7.20.5

### Anything Else?

I have not searched the existing issue.

**Comment by luu-alex** [comment]
Are you sure its not your internet connection? I was able to succesfully npm install. Closing
