### ISSUE TITLE
EventLog.removed has not been typed

### ISSUE THREAD

**Issue by hellowodl** [ethereum/web3.js#4747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Listening to web3.eth.Contract.events.Event.on('changed', EventLog => {}) returns an EventLog without { removed: boolean }.
Web3's type definitions don't account for `removed` to exist.

### Expected Behavior

The EventLog on the `changed` event, should return { removed: boolean } as well.

According to the documentation `removed` is added to the object, though typescript says otherwise.
https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-events-return

### Steps to Reproduce

Not applicable

### Web3.js Version

1.7.0

**Comment by nazarhussain** [comment]
Thanks @hellowodl for reaching to us with the issue. We would encourage if you create a pull request for it, or we will plan it further considering our capacity.

**Comment by samlaf** [comment]
I also need `removed` to be added asap. Currently using ethersjs' Log type...
