### ISSUE TITLE
create the ENS class - 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4752]
## Description
The ENS class needs to be created for the ENS library .

## Criteria
Should be up to parity with 1.x. 
All methods and the ENS object should be tested. 
Resources: https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-ens/src/ENS.js

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4752?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
