### ISSUE TITLE
Simple-get high severity vulnerability issue.

### ISSUE THREAD

**Issue by DarkMiclos** [ethereum/web3.js#4753]
#### Expected behavior

You run npm install web3 and everything works fine.

#### Actual behavior

After installing web3 package I get 2 high severity vulnerablilities from the xhr-request package wich is used as a dependancy in the web3 package.
As commented on github this is a security issue with cookies: In versions of simple-get prior to 4.0.1 when fetching a remote url with a cookie location response headers will be followed potentially resulting in an exposure of the session cookie to a third party.

#### Solution

I have been able to solve the vulnerability by downloading the latest simple-get version 4.0.1 and than in the node_modules under xhr-request/package.json and xhr-request/node_modules/simple-get/package.json I updated the version to the bug patched version.

I thought I wanna get this out to the community so it gets fixed since I'm just starting out in writing smart contracts and I struggled a lot with solving this security issue at least on my end.

**Comment by nazarhussain** [comment]
@DarkMiclos Thanks for reaching to us. I believe this issue is already addressed with this PR https://github.com/ChainSafe/web3.js/pull/4728. The change is not yet released. We will double check to make before release to fix any high vulnerablilities in dependencies.

**Comment by CryptoChip8888** [comment]
Any fix? I am new to coding but I keep getting:

simple-get  3.0.0 - 3.1.0
Severity: high
Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv
fix available via `npm audit fix`
node_modules/simple-g
