### ISSUE TITLE
Can't ESM import web3

### ISSUE THREAD

**Issue by TheDutchCoder** [ethereum/web3.js#4756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to use ESM, the following error is thrown: "The requested module '/node_modules/web3/dist/web3.min.js' does not provide an export named 'default'"

```ts
import Web3 from 'web3'
```

### Expected Behavior

The module to be loaded.

### Steps to Reproduce

```typescript
import Web3 from 'web3'
```

### Web3.js Version

1.7.0

### Environment

- Operating System:  MacOS
- Browser: Chrome
- Node.js Version: N/A
- NPM Version: N/A

**Comment by TheDutchCoder** [comment]
To add, this works fine with 1.6.1, so it broke in the 1.7.0 build

**Comment by Spacesai1or** [comment]
Hi there, could you provide a test repo that produces this error? I installed `web3@1.7.0` in [this](https://github.com/spacesailor24/web3-3891-receipt/blob/f13cb26adb6c58dc9c334d5583608e33e5ac4a75/index.ts#L1) test repo and the code executes without error

Also we've had 70k+ weekly downloads of `1.7.0` and haven't received any other bug reports related to this, so I believe something may be wrong with your setup

**Comment by jdevcs** [comment]
> Hi there, could you provide a test repo that produces this error? I installed `web3@1.7.0` in [this](https://github.com/spacesailor24/web3-3891-receipt/blob/f13cb26adb6c58dc9c334d5583608e33e5ac4a75/index.ts#L1) test repo and the code executes without error
> 
> Also we've had 70k+ weekly downloads of `1.7.0` and haven't received any other bug reports related to this, so I believe something may be wrong with your setup

@TheDutchCoder
