### ISSUE TITLE
Connects to the wallet via walletconnect and listens to contract events, but cannot listen to any data

### ISSUE THREAD

**Issue by Cjw-259** [ethereum/web3.js#4758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I connected to the metamask wallet via @walletconnect/web3-provider, then sent a transaction via the contract, listened to an event on the contract and the event was successfully triggered on the chain, but my code does not listen to the event, other methods such as using the pc metamask extension do. Except for walletconnect

### Expected Behavior

Connects to the wallet via walletconnect and listens to contract events, but cannot listen to any data

### Steps to Reproduce

Connects to the wallet via walletconnect and listens to contract events, but cannot listen to any data

### Web3.js Version

1.7.0

### Environment

- Operating System: mac
- Browser: Google
- Node.js Version: 16.13.1
- NPM Version: 8.1.2

**Comment by Cjw-259** [comment]
I've tried changing versions and that didn't fix it either

**Comment by jdevcs** [comment]
Hi @Cjw-259 thanks for reporting the issue, could you share snippet for reproducing this bug.
