### ISSUE TITLE
SHH Filter Topics not returned

### ISSUE THREAD

**Issue by macrauder** [ethereum/web3.js#476]
When I send a post message with a topic, these topic isn't in the message that the receiver gets back.
I think every topic should be returnd to the receiver.
Sample Code:

```js
var Web3 = require('web3');

// define web3 object
var web3 = new Web3();

// setup provider
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

// new identity, topic, payload
var identity = web3.shh.newIdentity();
var topic = 'TEST';
var payload = 'some payload text'+ Date.now();
console.log(identity);

// build message object
var message = {
    from: identity,
    topics: [web3.fromAscii(topic)],
    payload: web3.fromAscii(payload)
};

// setup filter for messages on topic
var filter = web3.shh.filter({
    topics: [web3.fromAscii(topic)]
});

// watch for changes on filter
filter.watch(function (err, result) {
    console.log(err, result, web3.toAscii(result.payload), result.topics);
});

web3.shh.post(message, function (err, result) {
    console.log(err, result);
});
```

**Comment by hacktar** [comment]
I found the same issue! The topics array is empty in the result recived from filter watch.
Any suggestions?

**Comment by coderwithattitude** [comment]
we had the same issue we changed  'topic' to 'topics' and that solved the problem

**Comment by hacktar** [comment]
@coderwithattitude could you explain?
In the result the topic array is always empty yet!

**Comment by coderwithattitude** [comment]
hello @hacktar my apologies it seems we arent having the same problem, as i re-read your code and i see you used 'topics' pardon the misleading

**Comment by frozeman** [comment]
web3.js 1.0 contains the new whisper API v5, can you please retest and see if the issue is there as well. If so please create a new issue, or reopen.
