### ISSUE TITLE
Do not send transaction on brave browser

### ISSUE THREAD

**Issue by phamhongphuc1999** [ethereum/web3.js#4760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I send a transaction from my wallet address(metamask wallet) by web3js on brave browser. In other browsers, it is always successful but in brave browser i get a issues ``{code: -32602, message: "'from' is not authorized to send transactions"}``.  you can see more detail in below image

<img width="892" alt="Screen Shot 2022-02-08 at 15 25 02" src="https://user-images.githubusercontent.com/56115755/152947182-40b65e37-b01e-4172-8a98-75cc839b9da3.png">

### Expected Behavior

I expect my sending transaction in brave browser is successful like other browsers

### Steps to Reproduce

this is example code which i use for sending my transaction

``
MyContract.methods.myFunction(param1, param2, param3).send({ from: walletAddress });
``

### Web3.js Version

1.2.2

### Environment

- Operating System: MacOS Montery v12.0.1
- Browser: Brave Browser
- Node.js Version: 14.17.6
- NPM Version: 6.14.15

**Comment by ryanio** [comment]
have you unlocked and connected the same `walletAddress` you specified to the website running the web3.js code? see `eth_requestAccounts`

also since you are on web3.js 1.2.2, would recommend updating to the latest 1.x so that would be 1.7.0, to rule out any possible fixes between the versions.

**Comment by phamhongphuc1999** [comment]
> have you unlocked and connected the same `walletAddress` you specified to the website running the web3.js code? see `eth_requestAccounts`
> 
> also since you are on web3.js 1.2.2, would recommend updating to the latest 1.x so that would be 1.7.0, to rule out any possible fixes between the versions.

**Comment by phamhongphuc1999** [comment]
Thank you for your support, i updated web3 version to 1.7.0 and it run very well with brave browser
