### ISSUE TITLE
ETH Tx Utilities TODOs [1/5] - Refactor formatters to JSON schemas and TypeScript band-aid solution

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4778]
Originally mentioned [here](https://github.com/ChainSafe/web3.js/pull/4718#issuecomment-1032134238)

#4778 is being split into multiple issues, this issue being tasks not needed to be addressed before `v4.0.0-alpha`:

- [Replacing formatters with JSON schemas](https://github.com/ChainSafe/web3.js/pull/4718/files#r789942037)
- [Refactor](https://github.com/ChainSafe/web3.js/blob/49171a15d58b3f541337cd3d95178e49f7d18ed7/packages/web3-eth/src/eth_tx.ts#L276) typing to make TSC happy

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4778?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
