### ISSUE TITLE
Log Filter Topic type and digest

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4784]
- [ ] [Log Filter Topic](https://github.com/ChainSafe/web3.js/blob/cc6e15b1de5312b5a665606c1403958073807720/packages/web3-utils/src/types.ts#L25) can also be null or array according to [execution api def](https://github.com/ethereum/execution-apis/blob/68cf607f01bd41aecd0aaafd2bfc01928e188cc2/src/schemas/filter.json#L66) . 
    - [ ] Update [topics](https://github.com/ChainSafe/web3.js/blob/cc6e15b1de5312b5a665606c1403958073807720/packages/web3-common/src/eth_execution_api.ts#L139) type in Log to include `null` and `Topic` (so final type would be `null | Topics | Topics[]`

- [ ] ~Also need to update [topics](https://github.com/ChainSafe/web3.js/blob/cc6e15b1de5312b5a665606c1403958073807720/packages/web3-common/src/eth_execution_api.ts#L139) type in Log to be directly [byte32 array](https://github.com/ethereum/execution-apis/blob/68cf607f01bd41aecd0aaafd2bfc01928e188cc2/src/schemas/receipt.json#L42) instead of `Topics[]` if its updated in above item~

- [ ] Third [param](https://github.com/ChainSafe/web3.js/blob/cc6e15b1de5312b5a665606c1403958073807720/packages/web3-common/src/eth_execution_api.ts#L253) of `eth_submitWork` is digest (also called some time mix hash or mix digest) instead of difficulty [exe api](https://github.com/ethereum/execution-apis/blob/68cf607f01bd41aecd0aaafd2bfc01928e188cc2/src/eth/mining.json#L70).

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4784?planning-poker) with ZenHub @jdevcs @luu-alex @nazarhussain @spacesailor24
