### ISSUE TITLE
Deprecated event listener

### ISSUE THREAD

**Issue by antonio-fr** [ethereum/web3.js#4786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running web3.js with Metamask, the latter informs with a warning that the "close" may be removed in any future version.

`new window.Web3(window.ethereum)`

➡️ 
_MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect_

```
_warnOfDeprecation @ inpage.js:1
on @ inpage.js:1
u.setProvider @ web3.js:15
e @ web3.js:15
packageInit @ web3.js:3
d @ web3.js:15
Web3Wallet @ wallet.js...
startWeb3 @ xxx
```

### Expected Behavior

Should use a current method, not a deprecated one.

### Steps to Reproduce

Use dist/web3.min.js v1.7.0 in a browser with Metamask :
`new window.Web3(window.ethereum)`

### Web3.js Version

1.7.0

### Environment

- Operating System: Win10
- Browser: Chromium 97.0.4692.71
- Node.js Version: 16.13.0
- NPM Version: 8.1.0

**Comment by jdevcs** [comment]
@antonio-fr  thanks for mentioning it, 1.x is already handling [this case](https://github.com/ChainSafe/web3.js/blob/bd6a9d86bbb9dc6e1fbe74216f9d7d44d7ba2b47/packages/web3-core-requestmanager/src/index.js#L152).  could you go ahead and open PR for removing `close`.
