### ISSUE TITLE
Missing revert reason on error for `send` call

### ISSUE THREAD

**Issue by laygir** [ethereum/web3.js#4787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been trying to get the revert reason of a `send` call on my contract but the returned error object does not include the `revertReason` field. I did try both `web3.eth.Contract.handleRevert = true;` and `web3.eth.handleRevert = true;` 

if I call `call`  on the contract method I get the revert reason but not on a `send` call.

### Expected Behavior

I expect to get the reason why a `send` call on a contract method reverted.

For `call` on a method, I get the revert reason as data and after I can find the actual string message after converting it. But handle revert doesn't seem to have any effect on this, whether it's true or false. 
https://web3js.readthedocs.io/en/v1.7.0/web3-eth.html#handlerevert

### Steps to Reproduce

```javascript
await myContract.methods
  .mint(1)
  .send(tx)
  .on('error', (error) => {
      console.log(error)
   });
```

### Web3.js Version

1.7.0 (package says 1.7.0 but instance shows 1.6.0 🤷🏻‍♂️)

### Environment

- Operating System: Mac
- Browser: Brave, Chrome
- Node.js Version: v14.18.1
- NPM Version: 6.14.15

### Anything Else?

I found multiple issues around this topic and they seem to have been closed without proper resolution.

For instance: https://github.com/ChainSafe/web3.js/issues/3939#issuecomment-1046292218

I jumped on ChainSafe Discord, couldn't get any feedback, web3 channel there seems a bit inactive.

**Comment by jdevcs** [comment]
Thanks @laygir for informing us, 

I checked web3.js `1.7.0` Geth is returning revert reason as:

`"{\"jsonrpc\":\"2.0\",\"id\":16,\"error\":{\"code\":3,\"message\":\"execution reverted: speed invalid\",\"data\":\"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d737065656420696e76616c696400000000000000000000000000000000000000\"}}\n"`  for this [example](https://github.com/ChainSafe/web3.js/issues/3742#issuecomment-928102801)

and web3.js was able to get and parse revert reason correctly. 

I also checked it with ganache but ganache is returning empty string in [result](https://github.com/ChainSafe/web3.js/blob/bd6a9d86bbb9dc6e1fbe74216f9d7d44d7ba2b47/packages/web3-providers-http/src/index.js#L105) (that is invalid response) so web3 wasn't able to parse and return it.

Could you tell us which provider you are using, also which eth-client it is connected?

**Comment by laygir** [comment]
Hello @jdevcs thank you for taking the time to look at it 🙏

I've tried with Alchemy and Metamask on a contract deployed on Rinkeby.
On my frontend calling `web3.eth.getNodeInfo()` returns the following;

`Geth/v1.10.15-stable-8be800ff/linux-amd64/go1.17.5`

**Comment by jdevcs** [comment]
Hi, could you share another item by debugging: result of `eth_call` received by web3.js in your case.
_______________
In above example with Geth `eth_call` was:
`{
  jsonrpc: "2.0",
  id: 16,
  method: "eth_call",
  params: [
    {
      data: "0xf06a29c90000000000000000000000000000000000000000000000000000000000000066",
      from: undefined,
      gasPrice: undefined,
      gas: undefined,
      to: "0xb574bea5f4a28c04b95ebb350db386f0d9309fdd",
    },
    "latest",
  ],
}` and result mentioned:


> "{\"jsonrpc\":\"2.0\",\"id\":16,\"error\":{\"code\":3,\"message\":\"execution reverted: speed invalid\",\"data\":\"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d737065656420696e76616c696400000000000000000000000000000000000000\"}}\n"

**Comment by laygir** [comment]
Hey @jdevcs 

I tried to create a reproduction case by using this [example](https://github.com/ChainSafe/web3.js/issues/3742#issuecomment-928102801) you mentioned. 

When I change the `call` to `send` like below in the example code;

Replaced following:
```javascript 
await contractInstance.methods.Start(102).call();
```

With this:
```javascript
await contractInstance.methods.Start(102).send({
    from: accounts[0],
    gas: 2850000,
  });
```

I get the following errors:

<img width="400" alt="Screenshot 2022-02-21 at 23 29 06" src="https://user-images.githubusercontent.com/772730/155034540-dabe7ff2-67fa-48fe-b916-36a6ef66bca2.png">


You can find the isolated case here on: https://github.com/laygir/web3-revert-test

What am I doing wrong? 👀

**Comment by laygir** [comment]
If I use the example as it is, then I get the following. Which has the revert reason unlike `send` call.

<img width="400" alt="Screenshot 2022-02-21 at 23 09 10" src="https://user-images.githubusercontent.com/772730/155035392-8655ceb6-c88c-4eb5-badb-9e0aa06075b8.png">

**Comment by laygir** [comment]
Now tried with Alchemy using their web3.js wrapper, `@alch/alchemy-web3` (internally their package seem to have web3 version 1.6.0)

On `send` call using Alchemy the retry exhaustion and all those thrown errors went away. Following is returned but no revert reason.

<img width="400" alt="Screenshot 2022-02-22 at 00 43 00" src="https://user-images.githubusercontent.com/772730/155040368-3a9efa56-5028-4428-acc3-15ddfec2a203.png">


On `call` using Alchemy, I get the following. Revert reason available. Expectation is that same revert reason also returned on a `send` call.

<img width="400" alt="Screenshot 2022-02-22 at 00 53 56" src="https://user-images.githubusercontent.com/772730/155040427-fb0fe083-323a-483e-b699-0d9d5d517957.png">

Find these changes on: https://github.com/laygir/web3-revert-test/tree/using-alchemy

**Comment by laygir** [comment]
Hey @jdevcs 

Should I assume that the `investigate` label means there is indeed an issue and probably will not be resolved in a week? How do you see it? 😓

I'm blocked by this issue and considering switching to ethers.js if you think this may take some time. ✌️

**Comment by nazarhussain** [comment]
@laygir The tag `investigate` tags means we foresee some issue but need time to investigate. Unfortunately our bandwidth are limited and we are focusing all our effort for 4.x rewrite, to bring your loved library with all new architecture to provide native TS support and flexibility to refactor for future improvement and extensions. We will investigate this issue for 1.x, unfortunately not soon enough. We would also encourage community to contribute.

**Comment by SyedImam1998** [comment]
hey @laygir  you can use this for now...
to show the user a appropriate message so the user can understand for that we can use below code. To get the reason from the reverted response. use the below code in nodeJS/expressjs code....

```
try {
    await myContract.methods.foo().send();
} catch (e) {
    const data = e.data;
    const txHash = Object.keys(data)[0]; 
    const reason = data[txHash].reason;

    console.log(reason); 
}
```

**Comment by laygir** [comment]
Hello @SyedImam1998 

Thank you for your suggestion! 🙌 
Unfortunately that does not seem to be working in my case. (Please notice that I'm on the frontend/browser.)

When I try your suggestion using Metamask as provider, as before a series of errors are thrown, exactly like in the screenshot of this [comment](https://github.com/ChainSafe/web3.js/issues/4787#issuecomment-1047277430)
Since errors are thrown, there is no `error.data` to access the values.

When I try your suggestion using Alchemy's wrapper of Web3js (`@alch/alchemy-web3`) similar as [before](https://github.com/ChainSafe/web3.js/issues/4787#issuecomment-1047309410), there is no revert reason or `error.data`

Below you can find the repos' I'm using to reproduce and test this case. If you feel like, please do take a look at those and see if you can get an expected result or maybe you spot something I'm doing wrong 🙏 

https://github.com/laygir/web3-revert-test
https://github.com/laygir/web3-revert-test/tree/using-alchemy

**Comment by kaizen-sven** [comment]
Ran into the same issue, when working with web3 through Metamask (and other mobile wallets). 

The problem itself seems to be a combination of an issue in the web3 code for handleRevert (at least on Binance Smart Chain), and an issue with Metamask/mobile wallets throwing the error instead of catching it.

I created a hack to sort this to be able to show a nice error message on the customer side on what exactly failed, together with a description of what they need to do to solve it before making an additional transaction.

I have attached the hack as patch files to the post, though please note as mentioned that it's an ugly hack that provides a workaround. I am certain that someone that regularly works with javascript, can create a more elegant solution.

The workaround, create another method that you can call if the contract interaction failed "getRevertError()" which will give you the actual revert error of the transaction. Basically, we pass the error up from the core methods library back to the contract library, which is the messy part.

Though, if you need the ability to show the actual revert errors when interacting with Metamask/mobile wallet today, it provides this ability until the issue is fixed in a future update of the web3 libary.

[web3 v1.7.1 patch (revert error).zip](https://github.com/ChainSafe/web3.js/files/8363262/web3.v1.7.1.patch.revert.error.zip)

**Comment by nazarhussain** [comment]
Hi, Currently we are investing all resources in 4.x rewrite. We will investing this issue and plan for some future sprints.

**Comment by ruben-certhis** [comment]
i found a solution : 

```
var supply = await int_contract_collection.methods.index_nft();
  supply = await supply.call({
    data: supply.encodeABI(),
  });
```

**Comment by lightingraven** [comment]
What is the solution, if the problem is on send() not in call()?

**Comment by lightingraven** [comment]
I created this approach which worked fine to me, a "pre-flifht" with a call first:

```javascript
//Preflight check
let preflightCheck = await this.preflightCheck(
  contract.methods.yourFunction(params),
  {
    from: account,
  }
);

if (preflightCheck === true) {
  const tx = await contract.methods
    .yourFunction(params)
    .send({
      from: account,
    });
}
else {
  alert("Error processing tx: " + preflightCheck);
}
```

The preflight function:

```javascript
preflightCheck: async (fn, params) => {
    try {
      await fn.call(params);
      return true;
    } catch (callError) {
      console.error("Transaction will fail:", callError);
      if (callError.message) {
        console.error(
          "Revert reason:",
          callError.data.message.replace(
            "VM Exception while processing transaction: revert ",
            ""
          )
        );
      }

      return callError.data.message.replace(
        "VM Exception while processing transaction: revert ",
        ""
      );
    }
  },
```

disclaimer: I'm not JS programmer, so feel free to improve the code.
