### ISSUE TITLE
Missing Transaction related RPC Methods

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4789]
### Missing RPC Methods

- `sendTransaction`
- `signTransaction`
- `call`

---

These methods need to include [promiEvent](https://web3js.readthedocs.io/en/v1.7.0/callbacks-promises-events.html) support

- `sendTransaction`
- `sendSignedTransaction` (a.k.a `sendRawTransaction`)

---

[Nice to have](https://github.com/ChainSafe/web3.js/issues/3204)

**Comment by mconnelly8** [comment]
@spacesailor24 will document issues/options for later discussion.
