### ISSUE TITLE
Event.watch not working as intended.

### ISSUE THREAD

**Issue by AustP** [ethereum/web3.js#479]
I'm trying to get historic events working. Consider the following code:

**MetaCoin.sol**

```
// This is just a simple example of a coin-like contract.
// It is not standards compatible and cannot be expected to talk to other
// coin/token contracts. If you want to create a standards-compliant
// token, see: https://github.com/ConsenSys/Tokens. Cheers!

contract MetaCoin {
    mapping (address => uint) balances;

    function MetaCoin() {
        balances[tx.origin] = 10000;
    }

    event Transfer(address indexed _from, address indexed _to, uint256 _value);

    function sendCoin(address receiver, uint amount) returns(bool sufficient) {
        if (balances[msg.sender] < amount) return false;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        Transfer(msg.sender, receiver, amount);
        return true;
    }

    function getBalance(address addr) returns(uint) {
        return balances[addr];
    }

    function topOff() {
        balances[msg.sender] = 10000;
    }
}
```

**app.js**

```
var MetaCoin = web3.eth.contract(abi);
var meta = MetaCoin.at(address);
var Transfer = meta.Transfer({}, {fromBlock: 0, toBlock: 10});
Transfer.watch(function(err, e) {
    if (err) {
        console.log(err);
    } else {
        console.log('Transfer Event 0 - 9: ' + e.blockNumber);
    }
});
```

Each time I make a transfer, the blockNumber gets logged until I reach block 10. Any transfers after that don't get logged. That is good.

![recorded](https://cloud.githubusercontent.com/assets/2007045/17258907/56e04b96-5586-11e6-976f-5516f230f219.gif)

But then if I refresh the dapp, all of the transfers will be logged again but instead of cutting off at 10, it logs every transfer. And once it logs all of the transfers, it starts over and logs them all again.

![recorded](https://cloud.githubusercontent.com/assets/2007045/17259051/ebc73c2e-5586-11e6-86d5-0ebfab1337c6.gif)

Also when using `Transfer.get`, the blocks returned aren't confined to my specified `toBlock` (10).

**Comment by bellaj** [comment]
I have the same issue any solution?

**Comment by flyswatter** [comment]
Your RPC nose needs to be running in archive mode to store old logs, since logs are not stored by default.
