### ISSUE TITLE
How to query transaction information, and mining information

### ISSUE THREAD

**Issue by skygong** [ethereum/web3.js#480]
How to query transaction information, and mining information？

**Comment by frozeman** [comment]
Thats not really possible, except you have the transaction hash. Then use `web3.eth.getTransaction(hash)`

For mining, there should be `web3.eth.mining` and `web3.eth.hashrate`

**Comment by jackson-sandland** [comment]
Could you elaborate on this? Where does `hash` come from?

**Comment by chentschel** [comment]
hash = await someContractInstance.someContractMethod([method_args], { transaction_args }).send()

**Comment by hrachbkweb** [comment]
https://rinkeby.etherscan.io/tx/some_address  - shows all info in ehterscan 
but 
`let order=web3.eth.getTransaction(orders[0].txHash)` is returning empty object 
Is there smth I am missing ?
