### ISSUE TITLE
Add Use of Local Wallet Support to Non-`web3-eth-account` Packages

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4814]
Various packages (namely `web3-eth`) need to check whether a local wallet has been instantiated so a `transaction.from` can be defaulted and a private key can be accessed to sign the transaction e.g.:

- [x] [One](https://github.com/ChainSafe/web3.js/blob/96026ec5990cd01a6ccfe33daa68b67de50bd1ad/packages/web3-eth/src/rpc_method_wrappers.ts#L385)
- [x] [Two](https://github.com/ChainSafe/web3.js/blob/96026ec5990cd01a6ccfe33daa68b67de50bd1ad/packages/web3-eth/src/rpc_method_wrappers.ts#L459)

**Comment by mconnelly8** [comment]
@nazarhussain Please review estimate
