### ISSUE TITLE
Init `transactionReceiptFormatter`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#4815]
A function, much like [formatTransaction](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-eth/src/format_transaction.ts), should be created to format transaction receipts to a desired `ValidType`

Examples places of use:

- [One](https://github.com/ChainSafe/web3.js/blob/96026ec5990cd01a6ccfe33daa68b67de50bd1ad/packages/web3-eth/src/rpc_method_wrappers.ts#L406)
- [Two](https://github.com/ChainSafe/web3.js/blob/96026ec5990cd01a6ccfe33daa68b67de50bd1ad/packages/web3-eth/src/rpc_method_wrappers.ts#L446)

**Comment by nazarhussain** [comment]
Closed by https://github.com/ChainSafe/web3.js/pull/4859
