### ISSUE TITLE
effective gas price should be a big number.

### ISSUE THREAD

**Issue by mark-b-ab** [ethereum/web3.js#4819]
effective gas price and other price values should be a big number.

Starting web3.js 1.7.1 you will be unable to get a receipt for [the transaction](https://etherscan.io/tx/0xeda3bf566ae21fbc7bbfcb805d73181b0037036d700d57695e28f1e9bfe0d69c)

Reason - very big gas price, number overflow

_Originally posted by @mark-b-ab in https://github.com/ChainSafe/web3.js/issues/4694#issuecomment-1058089193_

**Comment by ghost** [comment]
Instead of bignumber, would be great to return value in String like what value is returned from getTransaction.

**Comment by jdevcs** [comment]
This issue was fixed in https://github.com/ChainSafe/web3.js/pull/5157#pullrequestreview-1023233829
