### ISSUE TITLE
web3.eth.personal.sign typing is wrong

### ISSUE THREAD

**Issue by TheDutchCoder** [ethereum/web3.js#4831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `web3.eth.personal.sign` with TypeScript, there's a mandatory 3rd parameter (password), but it's not actually required. The typing for sign is:
```typescript
    sign(
        dataToSign: string,
        address: string,
        password: string,
        callback?: (error: Error, signature: string) => void
    ): Promise<string>;
```

But should be:
```typescript
    sign(
        dataToSign: string,
        address: string,
        password?: string,
        callback?: (error: Error, signature: string) => void
    ): Promise<string>;
```

### Expected Behavior

The 3rd param to be optional

### Steps to Reproduce

```typescript
signature.value = await web3.eth.personal.sign('some string', '0xsomeaccount')
```

### Web3.js Version

1.7.1

### Environment

- Operating System:  Mac OS
- Browser: Chrome
- Node.js Version: 16.14.0
- NPM Version: 8.3.1

**Comment by nazarhussain** [comment]
@TheDutchCoder Thanks for reaching to us with the feedback. We are currently occupied in 4.x rewrite which will not have that issue. For 1.x we will keep it in pipeline and work as we get some bandwidth.

**Comment by SamsonChoo** [comment]
May I ask what is the workaround for this issue if I am using TypeScript and it throws me errors? Just ignore the line?
I would think this seems like a relatively straightforward fix, if I create a PR would the devs be interested in reviewing and merging it?
