### ISSUE TITLE
encodePacked type issue 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4835]
Needs investigation, there maybe an issue with the returned values of our web3-utils package not being the same as abi.encodePacked from solidity

**Comment by jdevcs** [comment]
We need more info for how to reproduce above mentioned issue. 

If type is specified in `web3.utils.encodePacked()` it should return correct result. 
like: `web3.utils.encodePacked({type: 'uint32', value: '4294967295'})`

solidity:
```
    function getuint64() public pure returns (bytes memory) {
        return abi.encodePacked(uint64(18446744073709551615));
    }
```
`console.log(await contractInstance.methods.getuint64().call());`
gives: `0xffffffffffffffff`

`console.log(web3.utils.encodePacked({type: 'uint64', value: '18446744073709551615'}));`
gives:` 0xffffffffffffffff`

and if type not specified it will give wrong result
`console.log(web3.utils.encodePacked(18446744073709551615))`
gives: `0x0000000000000000000000000000000000000000000000010000000000000180`

**Comment by VictorZhang2014** [comment]
Hi @luu-alex  @jdevcs  Thank you so much for the quickly response for the problem.

In practices, the issues only emerged when we don't specify the concrete type in js code, so it will always occur in auto type inferences scenario, and it's easy to reproduce the incorrect outputs, as the code below shown.
```
let web3 = new Web3(window.ethereum);

// 1.Prepare the input data
let a = 10;
let b = 200;
let c = "12567"
let d = "6780945"
let e = (123 * 1e18).toString()
let f = (678 * 1e6).toString(16)

// 2.Output the results by web3.utils.encodePacked()
let a1 = web3.utils.encodePacked(a);
let b1 = web3.utils.encodePacked(b);
let c1 = web3.utils.encodePacked(c);
let d1 = web3.utils.encodePacked(d);
let e1 = web3.utils.encodePacked(e);
let f1 = web3.utils.encodePacked(f);

// 2.Connect with Rinkeby Ethereum
let contractAddress = "0x0ad8600c815bd22033acabe305862c3074e1ccf5"
let contractAbi = [{ "inputs": [{ "internalType": "uint8", "name": "a", "type": "uint8" }, { "internalType": "uint16", "name": "b", "type": "uint16" }, { "internalType": "uint32", "name": "c", "type": "uint32" }, { "internalType": "uint64", "name": "d", "type": "uint64" }, { "internalType": "uint128", "name": "e", "type": "uint128" }, { "internalType": "uint256", "name": "f", "type": "uint256" }], "name": "encode", "outputs": [{ "internalType": "bytes", "name": "a_", "type": "bytes" }, { "internalType": "bytes", "name": "b_", "type": "bytes" }, { "internalType": "bytes", "name": "c_", "type": "bytes" }, { "internalType": "bytes", "name": "d_", "type": "bytes" }, { "internalType": "bytes", "name": "e_", "type": "bytes" }, { "internalType": "bytes", "name": "f_", "type": "bytes" }], "stateMutability": "pure", "type": "function" }]
let myContract = new web3.eth.Contract(contractAbi, contractAddress);

// 3.Read the returned value
let result = await myContract.methods["encode"](a, b, c, d, e, f).call();
console.log(result)

// 4.Compare the results through auto type inferences 
console.log("web3.js a =", a1)
console.log("rinkeby a =", result[0])
console.log("web3.js b =", b1)
console.log("rinkeby b =", result[1])
console.log("web3.js c =", c1)
console.log("rinkeby c =", result[2])
console.log("web3.js d =", d1)
console.log("rinkeby d =", result[3])
console.log("web3.js e =", e1)
console.log("rinkeby e =", result[4])
console.log("web3.js f =", f1)
console.log("rinkeby f =", result[5])

// 5.Finally, if we use this form of code snippet : web3.utils.encodePacked({ t: 'uint8', v: 10 }) 
// all are working very well!
```

On the contrary, if we write the code `web3.utils.encodePacked({ t: 'uint8', v: a }) ` and we will get the same output as Solidity output.

For Solidity code and deployed on Rinkeby network https://rinkeby.etherscan.io/address/0x0ad8600c815bd22033acabe305862c3074e1ccf5#code

Completely Solidity Code:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract ABIEncodePackedTester {

    function encode(uint8 a, uint16 b, uint32 c, uint64 d, uint128 e, uint256 f) 
    external 
    pure 
    returns 
    (bytes memory a_, bytes memory b_, bytes memory c_, bytes memory d_, bytes memory e_, bytes memory f_) {
      a_ = abi.encodePacked(a);
      b_ = abi.encodePacked(b);
      c_ = abi.encodePacked(c);
      d_ = abi.encodePacked(d);
      e_ = abi.encodePacked(e);
      f_ = abi.encodePacked(f);
    }

}
```

And then, we get the result as following:
<img width="549" alt="aa-11" src="https://user-images.githubusercontent.com/6853884/157658220-cab7d389-27c8-4a55-b08a-161b214d389d.png">


Ultimately, we use the specified type and value in our js code for signing and verifing in our NFT project, everything works well!

Thank you all again!

**Comment by luu-alex** [comment]
Thank you for the response :) 
We are aware that `encodePacked` may try to auto type numbers and will have unintended outputs, we are rewriting the whole library under the version of 4.x and have already made it mandatory to specify the type, an alpha will be released later this year! 
But yes you should be fine if you specify the type. If theres anything else feel free to comment and i can reopen this issue
