### ISSUE TITLE
Human Readable ABI

### ISSUE THREAD

**Issue by xGGCrypto** [ethereum/web3.js#4846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

Would like for Human Readable ABI to be implemented in web3.js
Human Readable ABI is currently a feature in ethers.js

https://docs.ethers.io/v5/api/utils/abi/formats/#abi-formats--human-readable-abi

### Use Cases

Human Readable ABI Description: 

> This allows for a simple format which is both machine-readable (since the parser is a machine) and human-readable (at least developer-readable), as well as simple for humans to type and inline into code, which improves code readability. The Human-Readable ABI is also considerably smaller, which helps reduce code size.

### Are you willing to implement this feature?

- [ ] Yes

**Comment by Muhammad-Altabba** [comment]
Hi @xGGCrypto,
We have **[a web3.js plugin](https://www.npmjs.com/package/web3-plugin-craftsman)** that can help you in generating the ABI (as well as the bytes code) directly from solidity code. It is not what you are requesting. But it could be even more convenient for some cases. Could you please use it and let us know if it fulfill your requirements?
Thanks,

**Comment by mconnelly8** [comment]
Hey @xGGCrypto, I'm going to close this issue for now since Muhammad gave you a suggestion that could help solve your issue.  If you have anything more to add, please reopen this and let us know.
