### ISSUE TITLE
Web3 Eth - 1 - 4.0.0 Alpha.1 System Tests 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4849]
System tests for:

## Web3.eth package

- [x] All rpc functions tests ( getProtocolVersion, isSyncing, getCoinbase, isMining, getHashrate, getGasPrice, getAccounts, getBlockNumber, getBalance, getStorageAt, getCode, getBlock, getBlockTransactionCount, getBlockUncleCount, getTransaction, getPendingTransactions, getTransactionFromBlock, getTransactionReceipt, getTransactionCount, getPastLogs, getWork, requestAccounts, getChainId, getNodeInfo, getProof ) 
- [x] setProvider
- [x] List providers
- [x] given Provider
- [x] Current Provider
- [x] BatchRequests
- [x] Defaults tests ( account, block, hardfork, chain, common, transactionBlockTimeout, transactionPollingtimeout, handleRevert, maxListenersWarningThreshold  )

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4849?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24

**Comment by Spacesai1or** [comment]
Refer to [this](https://github.com/trufflesuite/ganache/blob/develop/src/chains/ethereum/ethereum/RPC-METHODS.md) for what methods are supported by Ganache
