### ISSUE TITLE
Web3 Contracts - 1 - 4.0.0 Alpha.0 System Tests 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4850]
System tests for:

## Web3.eth.contracts package

- [x] 	Defaults tests ( account, block, hardfork, chain, common, transactionBlockTimeout, transactionConfirmationBlocks, transactionPollingTimeout, handleRevert  )
- [x] 	Options tests ( from, gas, gasPrice, address, jsonInterface ) 
- [x] 	Clone test
- [x] Contract deploy test

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4850?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24
