### ISSUE TITLE
Main web3 package - 4.0.0 Alpha.1 System Tests 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4851]
System tests for:

## Main web3 package

- [x] Using http, websocket, IPC provider strings create web3 instance
- [x] Using external connection provider create web3 instance
- [x] Using external wallet provider create web3 instance
- [x] setProvider
- [ ] List providers
- [ ] given Provider
- [ ] Current Provider
- [x] BatchRequests
- [ ] All modules instantiation

Users are able to query via eth package and are able to get Tx signed via Accounts package with web3 instances created with above mentioned providers.

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4851?planning-poker) with ZenHub @jdevcs @luu-alex @spacesailor24 @nikoulai @avkos
