### ISSUE TITLE
Web3 Personal- 4.0.0 Alpha.0 System Tests 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4853]
System tests for:

## Web3.eth.personal

- [ ] newAccount
- [ ] sign
- [ ] ecRecover
- [ ] signTransaction
- [ ] unlockAccount
- [ ] lockAccount
- [ ] getAccounts
- [ ] importRawKey

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4853?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24

**Comment by Spacesai1or** [comment]
According to [this](https://github.com/trufflesuite/ganache/blob/develop/src/chains/ethereum/ethereum/RPC-METHODS.md), Ganache doesn't appear to support `ecRecover`

**Comment by luu-alex** [comment]
This epic is done, but an investigation has popped from merging the PR for this issue. https://github.com/ChainSafe/web3.js/issues/5046
