### ISSUE TITLE
Polygon  chain trades gas price insufficient  - 1.7.1

### ISSUE THREAD

**Issue by 0123cf** [ethereum/web3.js#4857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Polygon Chain was unable to initiate transactions and gasPrice was in serious shortage

### Expected Behavior

The default gasPrice won't work on Matic, which is currently 2, but actually needs at least 30.

Should maxPriorityFeePerGas not get, use responses.GasPrice

### Steps to Reproduce

Contract.methods
.creatorClaim(poolId)
.send({ from: address })

### Web3.js Version

1.7.1

### Environment

- NPM Version: 1.7.1

**Comment by 0123cf** [comment]
version: 1.7.2

use
```
provider.defaultOnlineGasPrice = 1;
const web3 = new Web3(provider);
```

**Comment by 0123cf** [comment]
polygon use WalletConnect 

NewBlockHeaders usage reference is not supported

```
provider.notSupportNewBlockHeaders = 1;
const web3 = new Web3(provider);
```

**Comment by jdevcs** [comment]
Based on user needs, instead of using default `maxPriorityFeePerGas` 2.5 Gwei there is method of setting it explicitly:

1. estimate maxPriorityFee by using getfeehistory https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html#getfeehistory
2. set it explicitly using ` tx.maxPriorityFeePerGas`
