### ISSUE TITLE
Mismatched interface

### ISSUE THREAD

**Issue by tdelabro** [ethereum/web3.js#4871]
https://github.com/ChainSafe/web3.js/blob/505b833b0952b231ef2728c752d6667c9ed0f858/packages/web3-eth/types/index.d.ts#L404

The actual key described in the protocol is `transactionsRoot` with a `s`.
See: https://eth.wiki/json-rpc/API#eth_getlogs

**Comment by nazarhussain** [comment]
@tdelabro Thanks for reaching to us with the issue. We will try to get it fixed as soon we have some bandwidth.

**Comment by tdelabro** [comment]
If you agree on this change and that it require nothing more than changing this file, I can do a pull request myself

**Comment by OscBacon** [comment]
Hey, any updates on this? I can't see a relevant pull request, and it would make things easier than having to redefine an interface to work with web3js

**Comment by nikoulai** [comment]
Hi, @OscBacon Thanks for reaching out to us. Currently, all our resources are focused on 4.x rewrite. Feel free to open a PR addressing this.

**Comment by OscBacon** [comment]
Sure!

**Comment by OscBacon** [comment]
Hey, so the PR is ready, and has one approval, but it's missing another approval to get merged. Let's aim to wrap this up soon!
