### ISSUE TITLE
Web3 Eth - 2 - 4.0.0 Alpha.1 System Tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4880]
System tests for:

## Web3.eth package

- [ ] sendTransaction, 
- [ ] sendSignedTransaction, 
- [ ] sign, 
- [ ] signTransaction, 
- [ ] call 
- [ ] estimateGas,  submitWork
- [x] defaults Being done in #5082
- [x] BatchRequests~ Being done in #5015

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4880?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24

**Comment by Spacesai1or** [comment]
FYI, the RPC method for `sendSignedTransaction` is actually `sendRawTransaction` (Web3.js just aliases it)
