### ISSUE TITLE
Web3 Contracts - 2 - 4.0.0 Alpha.0 System Tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4881]
System tests for:

## Web3.eth.contracts package

- [x] 	Create Contract Instance ( **erc20, erc721** )
- [x] 	Defaults tests ( defaultBlock, defaultAccount )
- [x] 	Options tests ( from, gas, gasPrice, address, jsonInterface ) 
- [x] Contract methods test with call and send for eth_call and send transaction
- [x]  estimateGas, encodeABI tests
- [x] Events tests ( subscribe, once, specific event, all events, get past events tests ) 

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4881?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24

**Comment by Spacesai1or** [comment]
- [ERC20 standard](https://ethereum.org/en/developers/docs/standards/tokens/erc-20/)
- [ERC721 standard](https://ethereum.org/en/developers/docs/standards/tokens/erc-721/)

**Comment by jdevcs** [comment]
Related issue https://github.com/ChainSafe/web3.js/issues/4979

**Comment by nazarhussain** [comment]
Created a separate [issue](https://github.com/ChainSafe/web3.js/issues/5096) to cover other default attributes.
