### ISSUE TITLE
1.x updates

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4888]
- [ ] Remove [Legacy](https://github.com/lerna/lerna#legacy-fields) field in [lerna.json ](https://github.com/ChainSafe/web3.js/blob/d46d922e2d9714b6e8bd72db665f708f12e222ea/lerna.json#L3)

- [ ] update github CI [action](https://github.com/ChainSafe/web3.js/blob/d46d922e2d9714b6e8bd72db665f708f12e222ea/.github/workflows/build.yml#L49) , include node 14, 16, 18 for build tests ( [node releases](https://nodejs.org/en/about/releases/) )

**Comment by luu-alex** [comment]
Updated github ci actions to 14,16. didnt include 18 due to issues building with legacy modules. will be closing this out as both tasks are completed
