### ISSUE TITLE
IPC Provider - 4.x System Tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4896]
System tests for:

## IPC Provider package

- [x] connect tests
- [x] getStatus tests
- [x] Event subscription 'message' | 'connect' | 'disconnect' tests
- [x] removeAllListeners and removeListener tests
- [x] disconnect and reset tests
- [x] send multiple requests and receive response 

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Client: Geth

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
This can be testing for Beta, but if we have time it should be added to Alpha.
