### ISSUE TITLE
WebSocket Provider - 4.x System Tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4897]
System tests for:

## WebSocket Provider package

- [x] connect tests
- [ ] subscribe events tests
- [ ] disconnect and reset tests
- [ ] getStatus get and validate all status tests
- [ ] send multiple Requests on same connection with valid payload and receive response tests
- [ ] Support of Basic Auth tests
- [ ] Fault Tolerance tests

#### Min Platform Requirements:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Client: Geth

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

**Comment by mconnelly8** [comment]
This can be testing for Beta, but if we have time it should be added to Alpha.
