### ISSUE TITLE
`hexToNumber` to check MIN_SAFE_INTEGER

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4900]
`hexToNumber` actually checks if:

```typescript
if (num > Number.MAX_SAFE_INTEGER) {
		return negative ? -num : num;
	}
```

so if we update it to also check for `Number.MIN_SAFE_INTEGER`, than my concern should be covered

_Originally posted by @spacesailor24 in https://github.com/ChainSafe/web3.js/pull/4859#discussion_r837727682_

**Comment by nikoulai** [comment]
Why do we need this check?  `-` is subtracted from the hex string in the beginning of the function, will `num` ever be negative?

**Comment by jdevcs** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4900?planning-poker) with ZenHub @avkos @luu-alex @nikoulai @spacesailor24
