### ISSUE TITLE
handleRevert implementation broken when no value is specified for gasPrice on eth_sendRawTransaction

### ISSUE THREAD

**Issue by drub0y** [ethereum/web3.js#4902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`checkConfirmation` in `web3-core-method/src/index.js` on line `458` ([here](https://github.com/ChainSafe/web3.js/blob/d46d922e2d9714b6e8bd72db665f708f12e222ea/packages/web3-core-method/src/index.js#L458)) throws an internal error because it blindly accesses `parsedTx.gasPrice` to call its `.toHexString()`, but this property is undefined for all EIP-1559 transactions. This is then captured by an internal try/catch, swallowed and turned into `TransactionRevertedWithoutReasonError` and the app receives no `reason`.

### Expected Behavior

I expect the logic to be aware of the fact that `gasPrice` will be `undefined` for EIP-1559 transactions and not call `.toHextString()` on it in that case so that it doesn't cause an internal error that stops fetching the `reason` for the failure from the RPC node with `eth_call`.

### Steps to Reproduce

1. Set `web3.eth.handleRevert = true`
2. Send a transaction that should return a revert reason through the `eth_sendRawTransaction`
3. Catch the error
4. Notice it has no `reason` when it should

### Web3.js Version

1.7.1

### Environment

Shouldn't matter, but I'm on Node.js Version 16.14.0.

### Anything Else?

Simply adding the null propagation operator like so is all that is needed to fix:

```JavaScript
gasPrice: parsedTx.gasPrice?.toHexString(),
```

I have tested this by manually editing the version in `lib` locally and everything works as expected then. If trying to be backwards compatible and not use null propagation operator the following fixes as well:

```JavaScript
gasPrice: parsedTx.gasPrice ? parsedTx.gasPrice.toHexString() : undefined,
```

**Comment by nazarhussain** [comment]
@drub0y Thanks for reaching back to us. We will investigate this issue and try to get it fixed as soon we have some bandwidth. Currently all our resources are focused towards 4.x rewrite.

**Comment by drub0y** [comment]
@nazarhussain No problem! Fix is already PR'd actually and looks to be slated for inclusion into 1.7.3. 🤞

**Comment by jdevcs** [comment]
Merged into 1.x via https://github.com/ChainSafe/web3.js/pull/4940
