### ISSUE TITLE
Documentation is inconsistent between the "defaultAccount" and "from" of the ContractOptions

### ISSUE THREAD

**Issue by Laurianti** [ethereum/web3.js#4906]
As reported in these documentation parts:

https://web3js.readthedocs.io/en/v1.7.1/web3-eth-contract.html#defaultaccount
https://web3js.readthedocs.io/en/v1.7.1/web3-eth.html#defaultaccount

> This default address is used as the default "from" property

While, in this documentation part:

https://web3js.readthedocs.io/en/v1.7.1/web3-eth-contract.html#methods-mymethod-send

We can see that the _from_ property is **required**, and not optional.

If I try to set both _defaultAccount_:

```
web3.eth.defaultAccount = '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe';

new web3.eth.Contract(<args>).defaultAccount = '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe';
```

I have this error:

> Error: No "from" address specified in neither the given options, nor the default options.

The only way to have the _send_ working is to set the _from_ explicitly in the _ContractOptions_ of the new Contract istance or to set it in every _send_.

**Comment by nazarhussain** [comment]
@Laurianti Thanks for highlighting this issue in the documentation. We will investigate it further as soon we get some bandwidth.

**Comment by idan-orbs** [comment]
Noticed the same thing. 
@Laurianti did you manage to overcome this? I'm looking for a way to set a default account for contract sends.

**Comment by Laurianti** [comment]
I could not.
My best solution:
```
    web3.eth.defaultAccount = '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe';
    let contract = new web3.eth.Contract(abi, address, <ContractOptions>{ from: web3.eth.defaultAccount } );
```
