### ISSUE TITLE
Add ERC 147 to web3 init

### ISSUE THREAD

**Issue by frozeman** [ethereum/web3.js#492]
When a web3.js instance is cerated and no provider is given, the system tries to find it using the `ETHEREUM_SOCKET` environment variable.

**Comment by Aikon77** [comment]
#!/usr/bin/env node

var Web3 = require('../index.js');
var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

var coinbase = web3.eth.coinbase;
console.log(coinbase);

var balance = web3.eth.getBalance(coinbase);
console.log(balance.toString(10))

**Comment by bitpshr** [comment]
@frozeman I took care of this in #1453.

**Comment by nivida** [comment]
@frozeman I think we can close this issue because of the EthereumProvider right?

**Comment by Asone** [comment]
@nivida : does this mean we can provide `ETHEREUM_SOCKET` env var with current web3 release ?

**Comment by nivida** [comment]
Sorry I did not notice that we are talking here about the node environment I thought it would be about the browser. But yes I would like to have something for the node environment too because we do have a similar thing in the browser with ```window.ethereumProvider```. @Asone
