### ISSUE TITLE
Unhandled promise rejection when contacting the node fails in _handleTxPricing

### ISSUE THREAD

**Issue by sirasistant** [ethereum/web3.js#4921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are getting random unhandled rejections while sending transactions with undefined gasPrice. This happens because when the gas price is not defined, the function `_handleTxPricing` is executed and it has a number of issues.

The main problem is that during the pricing process, the requests to the node might fail. In that case, the transaction sending launches an unhandled exception that crashes the node.js process. It is not possible to catch this exception, as is not exposed by web3.

The function `_handleTxPricing` uses internally a [Promise.all](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L865) that wraps two JSON-RPC calls to make them concurrently. The issue is that this Promise.all does not handle promise rejections (it's missing a `.catch(handler)`). The try catch wrapping it is not covering rejections in the Promise.all since it's not being awaited.

There is also another issue, the _handleTxPricing function can reject  [here](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L902), but only the .then listener is set [on the calling function](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L801).

When the `eth_getBlockByNumber` or the `eth_gasPrice` call fail, the promise rejects and no one catches it because of the above issues, so you get the unhandled promise rejection.

### Expected Behavior

Internal promises throwing should either be catched and handled or passed upwards, but in any case they should not be unhandled.

### Steps to Reproduce

Send any transaction wrapped in a try catch but make the `eth_gasPrice` call fail, for example. You'll see the unhandled rejection. 

### Web3.js Version

1.7.0

### Environment

- Operating System: Ubuntu 20.04
- Browser: 
- Node.js Version: v14.17.0
- NPM Version: 6.14.13

**Comment by nazarhussain** [comment]
Hey @sirasistant Thanks for reaching to us. Would be nice if you can share some code snippet that can easily reproduce the issue.

**Comment by sirasistant** [comment]
```
const Web3 = require('web3');

const GANACHE_INSTANCE = 'http://127.0.0.1:8545';


function wrapProvider(provider) {
    const originalSend = provider.send.bind(provider);

    provider.send = (payload, callback) => {
        console.log('Invoking', payload.method);
        if (payload.method === 'eth_gasPrice') {
            callback(new Error('Fake error'));
        } else {
            originalSend(payload, callback);
        }
    };

    return provider;
}

async function main() {
    try {
        const decoratedProvider = wrapProvider(new Web3.providers.HttpProvider(GANACHE_INSTANCE));
        const web3 = new Web3(decoratedProvider);
        const accObject = web3.eth.accounts.create();

        web3.eth.accounts.wallet.add(accObject);

        await web3.eth.sendTransaction({
            from: accObject.address,
            to: '0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe',
            value: '0',
            gasLimit: '0x5208',
        });
    } catch (err) {
        console.info('Was able to catch the expected error!', err.message);
    }
}


main().then(() => {
    console.info('If you read this, there is no bug ✅✅✅✅✅✅');
});

```
Here you are! The expected output is:
```
If you read this, there is no bug ✅✅✅✅✅✅
```
The actual output is:
```
Invoking eth_getBlockByNumber
Invoking eth_gasPrice
(node:201828) UnhandledPromiseRejectionWarning: Error: Fake error
    at HttpProvider.provider.send (/home/sirasistant/Escritorio/web3bug/index.js:12:22)
    at RequestManager.send (/home/sirasistant/Escritorio/web3bug/node_modules/web3-core-requestmanager/lib/index.js:159:23)
    at sendRequest (/home/sirasistant/Escritorio/web3bug/node_modules/web3-core-method/lib/index.js:624:42)
    at send (/home/sirasistant/Escritorio/web3bug/node_modules/web3-core-method/lib/index.js:656:13)
    at /home/sirasistant/Escritorio/web3bug/node_modules/web3-core-method/lib/index.js:691:17
    at new Promise (<anonymous>)
    at _handleTxPricing (/home/sirasistant/Escritorio/web3bug/node_modules/web3-core-method/lib/index.js:672:12)
    at Eth.send [as sendTransaction] (/home/sirasistant/Escritorio/web3bug/node_modules/web3-core-method/lib/index.js:633:13)
    at main (/home/sirasistant/Escritorio/web3bug/index.js:29:24)
    at Object.<anonymous> (/home/sirasistant/Escritorio/web3bug/index.js:41:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:201828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:201828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sirasistant** [comment]
@nazarhussain I provided the steps to reproduce above. Thanks!

**Comment by sirasistant** [comment]
Hi!

Have you been able to reproduce this issue?

Thanks!

**Comment by nazarhussain** [comment]
@sirasistant Yes I can confirm I was able to reproduce the issue. Right now we are investing all our resources on 4.x rewrite. We will look into and plan this issue in future sprints.
