### ISSUE TITLE
The web3.eth.sign method prepends also the EIP-191 prefix to the message without notice in the documentation

### ISSUE THREAD

**Issue by ericnordelo** [ethereum/web3.js#4923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

The web3.eth.sign method prepends also the EIP-191 prefix to the message without notice in the documentation, as well as the web3.eth.accounts.sign (this method is well documented).

Internally, web3.eth.sign calls web3.eth.accounts.sign, and also, 

THERE IS NO WAY IN WEB3 TO SIGN A TRANSACTION WITHOUT PREPENDING THE HASH, I CAN'T FOR EXAMPLE SIGN EIP-712 MESSAGES BECAUSE OF THIS

**Comment by luu-alex** [comment]
Hey, thanks for submitting this issue and bringing this to our attention 👍.  For a solution to this issue, are you suggesting that we update our documentation? If so, feel free to update the documentation and contribute with a PR.
