### ISSUE TITLE
Compile solidity returns "Error: TypeError: Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by mardlin** [ethereum/web3.js#493]
Let me know if I'm doing something wrong, but I'm unable to get the web3js solidity compiler to work, whereas I am able to use the solc npm package to compile. 

This works: 

```
var solc = require('solc');
var input = "contract test {function multiply(uint a) returns(uint d) {return a * 7;}};"
var output = solc.compile(input, 0); // this works 
```

This returns an error: 

```
var Web3 = require('web3');
web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
var input = "contract test {function multiply(uint a) returns(uint d) {return a * 7;}};"
var output = web3.eth.compile.solidity(input); // this prints the following output
```

> Error: TypeError: Cannot read property 'split' of undefined
>     at Compiler.compile_solidity (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/compiler.js:14:34)
>     at Manager.eth_compileSolidity (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/manager.js:197:23)
>     at Manager.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/manager.js:75:10)
>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
>     at VmSubprovider.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)
>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
>     at GethDefaults.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/gethdefaults.js:17:12)
>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
>     at FilterSubprovider.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:76:7)
>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
>     at Object.module.exports.InvalidResponse (/Users/johnmardlin/node_modules/web3/lib/web3/errors.js:35:16)
>     at RequestManager.send (/Users/johnmardlin/node_modules/web3/lib/web3/requestmanager.js:61:22)
>     at Object.send [as solidity](/Users/johnmardlin/node_modules/web3/lib/web3/method.js:145:58)
>     at Object.<anonymous> (/Users/johnmardlin/Projects/eth-play/eth-arbitrary/myFlow/myFlow.js:12:31)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
> [Finished in 2.1s with exit code 7]

Other functions of web3js are working fine.

**Comment by frozeman** [comment]
The difference is that the web3.js solidity compiler uses the compiler from the node, which need to be installed on the system so that geth can provide it. While solc is standalone.

If we would add solc to web3.js it would make it rather huge.

But i might add this as an optional package soon

**Comment by frozeman** [comment]
Additionally it could be a bug. Will look into this some time.

**Comment by mardlin** [comment]
Thank you. If it helps, I was running testrpc at the time, I experience the same issue when running `parity --geth`. Testrpc should at least work though, right?

When running geth, the error actually changes to: 
> Error: Invalid JSON RPC response: undefined

**Comment by tarunbatra** [comment]
@mardlin I believe the error you are facing with geth is unrelated to the bug and will be solved with [this](http://ethereum.stackexchange.com/questions/2080/error-invalid-json-rpc-response-undefined-from-node-web3-js-app)

**Comment by nivida** [comment]
Compiler methods are no longer supported.
