### ISSUE TITLE
Rollup Web3 support added to "Known issues" section

### ISSUE THREAD

**Issue by jeanlambert17** [ethereum/web3.js#4932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

When using web3 with rollup there are issues that are already covered in the "Known issues" section for differents bundlers or libraries, but these solutions don't work with rollup, at least not at first glance, so, it'd be awesome to add a section for rollup users.

### Use Cases

Facilitate building of libraries that want to use web3 alongside rollup.

### Implementation Ideas

If I'm honest I've been working on this for a day already and haven't been able to make it work, I'm trying to create a development server using rollup, web3 and react (as a demo for the actual library) and it's causing a lot of issues.

### Are you willing to implement this feature?

- [X] Yes

**Comment by nazarhussain** [comment]
Hi @jeanlambert17 Thanks for reaching back to us. It would be a nice feature and that's great you you want to contribute yourself. Please consider that `1.x` branch and `4.x` are totally different codebase, so I would suggest to create two different PR's for both branches.
