### ISSUE TITLE
historical transactions

### ISSUE THREAD

**Issue by cao148** [ethereum/web3.js#4933]
Excuse me, I am using web3, how should I get the historical transaction information of an address. Such as TransactionHash, from, to, amount...

**Comment by King-PyxiS** [comment]
If you have a wallet that allows you to sweep the private key of a particular address then do so. If not you can  trace transactions down for BTC @https://mempool.space
@https://etherscan.io
@https://BSCscan.com
@https://BlockScan.com
@https://PolyScan.com

**Comment by cao148** [comment]
I am now planning to make a wallet like this. I want to use the web3 library to implement it. Historical transactions have become difficult.

**Comment by cao148** [comment]
> 如果您有一个允许您扫描特定地址的私钥的钱包，那么请这样做。如果没有，您可以跟踪 BTC @ https://mempool.space @ https://etherscan.io @ https://BSCscan.com @ https://BlockScan.com @ [https://PolyScan.com的交易](https://PolyScan.com)

I am now planning to make a wallet like this. I want to use the web3 library to implement it. Historical transactions have become difficult.

**Comment by cao148** [comment]
@King-PyxiS Is the web3.eth.getPastLogs method in web3 ^1.7.1 can only get the information of the contract address? I tried to get the data through this method but the returned data is empty

**Comment by luu-alex** [comment]
When you use getPastLogs, be sure to include the fromBlock, which indicates the range of the starting block to current,, for example 
```
web3.eth.getPastLogs({fromBlock:'0x0',address:'0x9e3319636e2126e3c0bc9e3134AEC5e1508A46c7'})
.then(res => {
  res.forEach(rec => {
    console.log(rec.blockNumber, rec.transactionHash, rec.topics);
  });
```

**Comment by nazarhussain** [comment]
Hi @cao148, Did you tried solution suggested by @luu-alex ? Hope that solved your problem, if not please share more details so we can look into it.
