### ISSUE TITLE
Fix the skipped tests for web3-eth

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4935]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

There are some fixtures which are not matching with the tests expectations. There are two level of methods which are mocked. 

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L36-L37

Once we mocked `rpc_method_wrappers`, there is no need to mock nested level of `rpc_methods`. As after the wrappers are mocked the internal logic will not execute and neither the `rpc_methods` will be called. 

There are some tests which are using internal `rpc_methods` in expectations, since these are never been called so these tests are failing. 

### Examples/References

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L249

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L262

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L275

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L285

https://github.com/ChainSafe/web3.js/blob/9a88cb96e96d7b97a8cacb6bf2eb46e7137c4b90/packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts#L295

**Comment by nikoulai** [comment]
https://github.com/ChainSafe/web3.js/pull/4920 deprecates this issues
