### ISSUE TITLE
web3: include an option to enable/disable autoconnect

### ISSUE THREAD

**Issue by TheJagpreet** [ethereum/web3.js#4957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

Currently web3 supports a feature of `reconnect` by which we can configure the reconnection parameters. A similar feature is needed to enable/disable the autoconnect to the mentioned provider.

Specifically, enveloping the condition of connection only if autoconnect parameter is set as true [here](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-providers-ws/src/index.js#L89) and similar places.

### Use Cases

There are certain scenarios where this feature can come in handy, like when we want to test some codebase containing web3 library, but cannot pass the provider; in such case we can simple turn off autoconnect to avoid connection in the first place.

One of such usages can come in handy while testing [this](https://github.com/hyperledger/cactus/blob/dda3f00c5319e22b03c73fe6dbc645dea41cc58e/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts#L151)

### Implementation Ideas

This can be easily implemented by enveloping [this](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-providers-ws/src/index.js#L89) with a condition which checks if the `autoconnect` parameter is set or not (should be defaulted to `true` to avoid possible code crashes for devs upgrading to the version of web3 including this feature)

### Are you willing to implement this feature?

- [X] Yes

**Comment by jdevcs** [comment]
@jagpreetsinghsasan Thanks for this, our  [4.x](https://github.com/ChainSafe/web3.js/tree/4.x) will be best candidate for this feature. Feel free to open PR if you have time.

**Comment by TheJagpreet** [comment]
Sure, I will create a PR soon.

**Comment by luu-alex** [comment]
Hey there, we include an enable/disable autoconnect in 4.x, https://docs.web3js.org/guides/web3_upgrade_guide/x/providers_migration_guide#websocketprovider if theres any other issues feel free to comment and ill reopen the issue. Thank u!
