### ISSUE TITLE
how do I run in testnet

### ISSUE THREAD

**Issue by cheershendtco** [ethereum/web3.js#496]
1.
I use `geth --rpc --rpccorsdomain "*"` to run my geth
2.
and open `balance.html` in `/web3.js-develop/example/`
3.
click watch balance button and it shows

```
coinbase: 0xae87c0d473c62930cc1d3177439e7becc52bfc4d
original balance: 0 watching...
```

everything looks fine

but how can I run in testnet.

if I use `geth --rpc --rpccorsdomain="http://localhost:8485" --testnet console`
to run my geth
everything not work.

Thanks

**Comment by nicoszerman** [comment]
This question should be in StackOverflow not here.
