### ISSUE TITLE
contract.at(undefined) should fail quickly

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/web3.js#497]
I suggest that calling `contract.at(undefined)` should immediately fail instead of returning a `Contract` and inevitably failing later when one of the contract's methods are called. When connected to testrpc, the following code fails with a `stack underflow` error, rather than a `missing/invalid address` error.

``` javascript
var Web3 = require('web3');
var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://0.0.0.0:8545'));
web3.eth.defaultAccount = web3.eth.coinbase;

var abi = [
    {"constant":false,"inputs":[{"name":"name","type":"bytes32"}],"name":"wat","outputs":[],"payable":false,"type":"function"}
];

var contract = web3.eth.contract(abi);
var instance = contract.at(undefined);
instance.wat("Hi");
```

**Comment by MrTibbles** [comment]
Second this. More informative error logging definitely needs to be a point of focus moving forward.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
