### ISSUE TITLE
Providers decode responses as ISO-8859-1 instead of UTF-8, resulting in mojibake in error messages

### ISSUE THREAD

**Issue by haltman-at** [ethereum/web3.js#4976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently (or at least as of 1.5.3 -- I don't think this has been fixed since then), providers (or at least `HttpProvider`s) seem to decode HTTP (and possibly other?) responses as ISO-8859-1, instead of UTF-8.  This can, for instance, result in incorrect error messages when a call reverts.

Suppose, for instance, that we make a call that reverts with the message "¡¡¡".  Then the error message ought to contain the string "¡¡¡".  Instead, however, it contains the string "Â¡Â¡Â¡", which is mojibake resulting from decoding the UTF-8 HTTP response as ISO-8859-1 instead.

[RFC 4627](https://www.ietf.org/rfc/rfc4627.txt) explicitly specifies that responses that with the `application/json` MIME type shall be decoded as UTF-8 unless another character set is specified, so to default to ISO-8859-1 instead is an error.  Moreover, UTF-8 is ubiquitous in Ethereum contexts, so this error has a visible effect in the form of mangled error messages.

### Expected Behavior

Decoding of HTTP (and other?) responses by the provider should use UTF-8 by default, not ISO-8859-1.

### Steps to Reproduce

I've created a reproduction project in Truffle [here](https://github.com/haltman-at/utf8-repro); I hope you don't mind my use of Truffle for the reproduction, but I thought it was the easiest way.  Anyway if you don't like using Truffle I'm sure you can adapt it.

(That does mean this is using web3 1.5.3, but I don't see anything in the release notes since then that would fix this?)

Anyway, if you check out my reproduction repo, you can then just do the following:
1. `npm install` to install axios;
2. `truffle compile` to compile the contract;
3. `truffle test` to run the tests.

There are three tests.  Each makes an `eth_call` to the same function, which will always revert with message "¡¡¡".  The test then extracts the error string in an appropriate manner, and checks that it does contain the correct revert string "¡¡¡", and that it does *not* contain the mojibake revert string "Â¡Â¡Â¡".  (Actually, it checks these in the other order, in case of other errors... failing the non-inclusion test immediately tells you that it's the mojibake error and not some other error.)

The difference between the three tests is *how* they make the call.  The first test uses web3.  It fails; the mojibake is present in the error message.

The second test goes a bit lower-level, and instead uses the provider, which is an `HttpProvider`.  It also fails for the same reason.  So the problem is already present at the provider level; it's a provider problem, not a `web3.eth.call` problem.

Finally, the third test goes all the way down and uses `axios` to directly perform the HTTP request.  This test *passes*; unlike the `HttpProvider`, `axios` correctly decodes the response as UTF-8, resulting in a correctly-displayed "¡¡¡" and no mojibake.  This demonstrates that the problem is in fact due to `HttpProvider`, and is not due to an error in Ganache; I had initially thought the problem was with Ganache, but in fact Ganache is returning the correct UTF-8, it's just that `HttpProvider` is incorrectly decoding it as ISO-8859-1.

Of course, in all of these cases, the raw hex response is present in the error too, and so the correct revert message should be decoded from that... but the string form should still be correct.  The fact that one *can* decode the correct revert message from the raw hex doesn't mean it's OK for the error message to be incorrect like this; the error message should be correctly decoded and without mojibake.

All of these problems could also be demonstrated with an `estimateGas` intead of a `call`.  I assume the problem is quite general.

Thank you!

### Web3.js Version

1.5.3

### Environment

- Operating System: Release Linux Mint 20.3 Una 64-bit
- Node.js Version: I was using 12.22.10, but I'm pretty sure this is version-independent, so please don't ignore this based on node 12 EOL
- NPM Version: 6.14.16

**Comment by nazarhussain** [comment]
Hi @haltman-at Thanks for reaching to us with and with such detail about the issue. Currently we are occupied in `4.x` rewrite, but will look into this issue in near future.

**Comment by haltman-at** [comment]
Not stale.

**Comment by haltman-at** [comment]
Not stale.

**Comment by haltman-at** [comment]
Not stale.

**Comment by cds-amal** [comment]
bump.

**Comment by haltman-at** [comment]
Not stale.

**Comment by mconnelly8** [comment]
6/12 - keep & investigate
