### ISSUE TITLE
Enable ganache for system tests to forge the block on regular interval

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4981]
It [looks](https://github.com/trufflesuite/ganache/blob/90329d886cf05df409a9474edc4e15f653c2d5b4/src/packages/ganache/README.md?plain=1#L285) like we'd need to pass `-b 1` which would mine a block every 1 second

_Originally posted by @spacesailor24 in https://github.com/ChainSafe/web3.js/pull/4945#discussion_r858964766_

**Comment by mconnelly8** [comment]
Tests are already done, but need to revisit tests.

**Comment by mconnelly8** [comment]
Need to investigate scenarios based on node configurations

**Comment by mconnelly8** [comment]
Duplicate of #5297, so will close this one.
