### ISSUE TITLE
Run integration tests in parallel and isolate the accounts

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4982]
Yes it is. The real solution would be to isolate the accounts for each tests. Means every test generate it's own accounts for testing. So it does not mixup with others.

_Originally posted by @nazarhussain in https://github.com/ChainSafe/web3.js/pull/4945#discussion_r858968806_

**Comment by mconnelly8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4982?planning-poker) with ZenHub @luu-alex

**Comment by mconnelly8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4982?planning-poker) with ZenHub @spacesailor24

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4982?planning-poker) with ZenHub @jdevcs @nazarhussain

**Comment by mconnelly8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4982?planning-poker) with ZenHub @nikoulai

**Comment by mconnelly8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4982?planning-poker) with ZenHub @avkos

**Comment by mconnelly8** [comment]
10/1/24 - reviewed and can close.
