### ISSUE TITLE
Contract.new callback being called twice.

### ISSUE THREAD

**Issue by Levino** [ethereum/web3.js#500]
The fact that a callback is fired twice is just wrong. The very definition of callback is, that is called exactly once. Nobody expects this strange behaviour. Make the function accept two callbacks, one for the hash and one for the address.

**Comment by eiabea** [comment]
I also found this quite strange, maybe an event emitter could be a cleaner approach?

**Comment by jamesprinc3** [comment]
In my case the callback only seems to fire once.

**Comment by Levino** [comment]
Wait a little. It fires twice.

**Comment by apateiro** [comment]
This looks like an ungly hack indeed, and build upon this is even worst. 

I'm currently ignoring the second call (I'll get the contract address later running periodic tasks). But knowing there is some pending callback on the air, even if I do nothing for the second call, just doesn't feel right.

I would like to know more about other implentations using this function and its code design, if anybody would like to share it.

**Comment by meinharrd** [comment]
i heard from @frozeman that this behaviour will be fixed/changed in v1.0 😎

**Comment by frozeman** [comment]
Yes, that is on purpose :)
But the new web3.js 1.0 (not released yet) will have a event based approach: http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id11
