### ISSUE TITLE
How set gas price for my project?

### ISSUE THREAD

**Issue by hej6666** [ethereum/web3.js#5013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

How set gas price for my project?
I can see gas price from  'https://etherchain.org/tools/gasnow' or 'https://polygonscan.com/' .
but I want use API get it. 
can i get gas price from last block?
how do it.
thanks

**Comment by avkos** [comment]
Hello. Thank you for your question. You can use [this function](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getgasprice) to get the current gas price

**Comment by hej6666** [comment]
> Hello. Thank you for your question. You can use [this function](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getgasprice) to get the current gas price

Thanks,Thanks,Thanks
