### ISSUE TITLE
Meteor.js package update

### ISSUE THREAD

**Issue by D-Nice** [ethereum/web3.js#502]
Any plans to update the package? It's currently stuck on 0.15.3 which is back from February.

**Comment by ethernomad** [comment]
I don't think web3.js uses Meteor.

**Comment by D-Nice** [comment]
I'm speaking in regards to the ethereum:web3 package for Meteor.js to be updated to a newer version, as it's using the web3 build from February.

**Comment by ethernomad** [comment]
This package: https://atmospherejs.com/ethereum/web3 ?

I don't know who is responsible for that.

**Comment by D-Nice** [comment]
Yep, that's the package.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
