### ISSUE TITLE
Discuss/Implement Migration Away From Lerna [1. x]

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5021]
[Lerna](https://github.com/lerna/lerna) seems to no longer be maintained, so for `1.x` we'll need to R&D a solution for managing local dependencies and NPM publishing since it uses NPM instead of Yarn

**Comment by jdevcs** [comment]
As discussed in last sprint meeting, we will continue using `lerna` https://github.com/lerna/lerna/issues/3121 and will wait for new road-map announcement.
