### ISSUE TITLE
Clarification: Different behavior on the same setup

### ISSUE THREAD

**Issue by maxamly** [ethereum/web3.js#5026]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

I have a DApp developed by our team, when we set it up locally it worked fine, but when we have done the same things to deploy it on server an error appeared? How does web3 call `Contract.methods.set(...).send({'from': address})` on our local machine returns this 

> calling sendAsync{"jsonrpc":"2.0","id":46,"method":"eth_sendTransaction","params":[{"from":"0x47997a5e81b42d977aabc9ff05d95157334d3930","data":"0x1ab06ee500000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000003","gasPrice":"0x4a817c800","to":"0x7f64363d57bf7497ddf38db46c9680708bd54de2"}]}

^^^ usual legacy transaction type (0) before EIP-1559^^^^

And on our server the same line of code gives us:
>calling sendAsync{"jsonrpc":"2.0","id":27,"method":"eth_sendTransaction","params":[{"from":"0x47997a5e81b42d977aabc9ff05d95157334d3930","data":"0x1ab06ee500000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000003","to":"0x6dbdd2314f07f79e78ade7832915944baaaf0980","maxPriorityFeePerGas":"0x9502F900","maxFeePerGas":"0x9502f9ae"}]}

^^^which is totally EIP-1559 transaction^^^

Is there any way to define exact behaviour?

**Comment by nikoulai** [comment]
Hey, thanks for reaching out.
Have you tried to set the `type` parameter in the `send` function ([ref](https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html#sendtransaction))?

**Comment by maxamly** [comment]
Yep, I've tried and it worked, I just wanted to know how web3 decides which type of transaction to use if type is not set?

**Comment by nikoulai** [comment]
It checks the parameters passed by the user( maxFeePerGas, etc.) and checks if the network which is connected supports the transaction. 
You can take a look here:

(https://github.com/ChainSafe/web3.js/blob/b4a52d6d3246395075f3083be80610df135bc926/packages/web3-core-method/src/index.js#L833)

Since you found a solution I close the issue. Feel free to reach us if you have any more questions (you can also check our Discord).
