### ISSUE TITLE
./node_modules/@solana/buffer-layout-utils/lib/esm/web3.mjs Can't import the named export 'PublicKey' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by zihangg** [ethereum/web3.js#5027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS fails to build the website citing this error. 

Did a fresh install locally to replicate the error. Seems like web3 forcing the installation of this module when it didn't previously.

### Expected Behavior

Build successful without facing this issue. 

### Steps to Reproduce

npm install 

### Web3.js Version

1.7.0

### Environment

- Operating System: Windows
- Browser: Brave/Chrome
- Node.js Version: 16.4.0
- NPM Version: 7.18.1

**Comment by barhouum7** [comment]
Same here, got the same issue today after adding React Moralis Provider, but removing Moralis Provider wrapper from my code fixing this issue

**Web3.js Version**

> 1.3.0

or 

> 1.7.3

**Environment**

- Operating System: WSL
- Browser: Brave
- Node.js Version: v16.14.0
- NPM Version: 8.5.4
- moralis: 1.7.0
- react-moralis: 1.3.4

> Same issue with `react-moralis: 1.3.5`

![image](https://user-images.githubusercontent.com/28789723/168448990-c25c2cec-2098-4572-a998-338397799c9e.png)

**Comment by dannicada** [comment]
Please I have the same issue while running `react-scripts build` on docker

Web3.js Version
1.7.3

Environment

- Operating system: ZorinOs (ubuntu based)
- Node.js Version: v16.15.0
- NPM Version: 8.5.5
- Moralis Version: 1.7.0
- React-Moralis version: 1.3.5

**Comment by michalko** [comment]
same error here after update to newest libraries

    "@solana/spl-token": "^0.1.8",
    "@solana/spl-token-registry": "^0.2.268",
    "@solana/wallet-adapter-base": "^0.6.0",
    "@solana/wallet-adapter-react": "^0.12.0",
    "@solana/wallet-adapter-react-ui": "^0.4.1",
    "@solana/wallet-adapter-wallets": "^0.10.0",
    "@solana/web3.js": "^1.42.0",

Please help

**Comment by avkos** [comment]
Hi. Thank you for your question. It looks like this problem is not related to the web3.js package.
It is not reproduced locally/docker.
If you think of another way, please describe the steps to reproduce in detail
