### ISSUE TITLE
exception should expose error code

### ISSUE THREAD

**Issue by drortirosh** [ethereum/web3.js#5035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the RPC API [https://eips.ethereum.org/EIPS/eip-1474] defines error conditions with codes and semi-standard error messages.
The error messages themselves are not standardised, and different nodes return different values.
e.g. if one make a call to an RPC call that might not exist (e.g. eth_feeHistory which was added lately), there is no "canonical" way to know if an exception was generated by "method not found" or some other reason, since the error code (-32601) is not exposed in the exception, and different nodes return different error string.

### Expected Behavior

When processing an RPC error response, in addition to "`message`" and "`data`", the thrown Error object should also include the "`code`" from the rpc response.

### Steps to Reproduce

```js
//the following sample attempt to reference nonexistent method.
// the underlying "-32601" error code is hidden from the application
// the string result differs based on ethereum node version

 Web3 = require( 'web3')
 const web3 = new Web3('http://localhost:8545')
 const web3 = new Web3('https://dai.poa.network')
web3.eth.extend({methods:[{name: 'test', call: 'eth_test'}]})

web3.eth.test()
.catch(e=>console.log(e))
.finally(process.exit)
```

### Web3.js Version

1.7.3

**Comment by nazarhussain** [comment]
Hi @drortirosh Thank for reaching out to us. I think that's a valid point you raised the error code should be included as part of the response. As we are currently we are investing all efforts to the 4.x rewrite, so we will consider this to be done for that release as well.
