### ISSUE TITLE
investigate web3 Personal- 4.0.0 System test - sign

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5046]
https://github.com/ChainSafe/web3.js/pull/4984#discussion_r875220297
Based off of the discussion of properly testing geth `sign` in the file `packages/web3-eth-personal/test/integration/personal.test.ts` we need to find a way to statically produce the same signature from geth so that `expect(signature).toBe(signatureFromConfig);`

**Comment by mconnelly8** [comment]
Low priority and not really needed.  Moving to Ice Box

**Comment by Muhammad-Altabba** [comment]
I think this could be closed as `personal` endpoint is deprecated: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-personal
