### ISSUE TITLE
Problem deleting account when checksummed address is equal to lowercase address

### ISSUE THREAD

**Issue by pietro-lopes** [ethereum/web3.js#5049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you add an account to a wallet, it creates:

- An index;
- A checksummed address;
- A lowercase address.

So you can access using any of those keys.

When you want to remove an account it does the same process, but when you have a checksummed that is equal to lowercase, the line (681) that access the lowercase address will throw an exception because it doesn't exists anymore.

`Uncaught TypeError TypeError: Cannot set properties of undefined (setting 'privateKey')`

### Expected Behavior

No error.

### Steps to Reproduce

```js
const Accounts = require('web3-eth-accounts')

const accounts = new Accounts()
// add an account address that lowercase and checksummed are equal : 0x92b7254537e2890f728187988b829b28a01333ce
accounts.wallet.add('0xaa237230fc60e46175256cbc931852514364089a9f4e5b59b5217483b2df4df7') // not used pvt key, don't worry
// remove account with index 0
accounts.wallet.remove(0)
```

https://github.com/ChainSafe/web3.js/blob/2c0324af2da467ee1acb72452f20000e916e4306/packages/web3-eth-accounts/src/index.js#L673-L693

### Web3.js Version

1.7.3

### Environment

- Operating System: Windows 10 Pro
- Browser: None
- Node.js Version: v16.13.2
- NPM Version: 8.1.2

**Comment by andreistefanwork** [comment]
Hi @unknownrj!

I am also able to reproduce the issue; I'm happy to help and I have tried fixing the problem & created a [PR](https://github.com/ChainSafe/web3.js/pull/5050) 

Can you please have a look if everything looks fine?

Thanks!
