### ISSUE TITLE
remove polyfill packages to support webpack 5 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5053]
connected to #5031 in order to support create-react-app and angular5 out of the box with web3js we need to get rid of these dependancies from our library: 
crypto-browserify,
stream-browserify,
assert,
stream-http,
 https-browserify,
os-browserify,
url

**Comment by marko911** [comment]
+1 on this. This causes a lot of problems for bundling and tons of workarounds need to be injected to get things working.

**Comment by jdevcs** [comment]
@luu-alex can we close this issue?

**Comment by luu-alex** [comment]
@jdevcs closed
