### ISSUE TITLE
Transient dependency on safer-buffer breaks builds that polyfill with rollup

### ISSUE THREAD

**Issue by JonathanLorimer** [ethereum/web3.js#5059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running web3.js in the browser via a react app served with [snowpack](https://www.snowpack.dev/) I get this error:
![1653232319_grim](https://user-images.githubusercontent.com/32466011/169702238-b84e754c-6760-409c-bf6e-9467c340cec4.png)

### Expected Behavior

Should be able to polyfill buffer using rollup.

### Steps to Reproduce

```
npx create-snowpack-app react-snowpack --template @snowpack/app-template-minimal
cd react-snowpack
yarn add web3
echo "import web3 from 'web3'" >> index.js
echo "const web3 = new Web3(window.ethereum)" >> index.js
```
- Edit package.json and set snowpack version to `3.8.6`
- Add `polyfillNode: true` to the `packageOptions` array in `snowpack.config.mjs'
- Run `yarn start`

### Web3.js Version

1.7.3

### Environment

- Operating System: NixOS
- Browser: Firefox
- Node.js Version: 18.1.0
- NPM Version: Yarn 1.22.18

### Anything Else?

The dependencies that transiently depend on `safer-buffer`:
- crypto-browserify
- express > body-parser > raw-body > iconv-lite
- request > http-signature > sshpk 
- browserify-sign > parse-asn1 > asn1.js

Related Issues:
 - [Removing browserify-crypto](https://github.com/ChainSafe/web3.js/issues/5053)
 - [safer-buffer issue](https://github.com/ChALkeR/safer-buffer/issues/7)
 - [Snowpack issue](https://github.com/FredKSchott/snowpack/issues/2869)

**Comment by luu-alex** [comment]
Hey thanks for submitting this issue, what is specifically causing this issue? crpyto-browserify?
