### ISSUE TITLE
web3 does not throw 'Exceeds block gas limit' in web3.eth.estimateGas but in web3.eth.sendRawTransaction

### ISSUE THREAD

**Issue by theotow** [ethereum/web3.js#506]
Hello,

i am wondering currenlty if this is a bug or if this is intended behaviour.
As from my understanding web3.eth.estimateGas simulates the sending of an transation but does not broadcast it to other peers, thats why i thought if an transaction has an 'Exceeds block gas limit', the web3.eth.estimateGas method would already tell me that in advance that the transaction will be 'rejected / exceed an limit' later  in web3.eth.sendRawTransaction

Would appreciated any answer which can shed some light on this.

Thanks a lot

**Comment by frozeman** [comment]
@karalabe @fjl we should discuss if we want to return errors on `eth_estimateGas` when exceeding the block gas limit. The pro would be that it is easier to handle for developers.
The con is that you cannot estimate gas usage above the block gas limit, which might be very useful for some use cases

**Comment by karalabe** [comment]
The way the new gas estimation works is it will return the maximum allowance if a transaction would fail. If you don't specify an upper limit, the one used will be the block gas limit, if you do specify an upper limit, that will be the one in case of a failing transaction.

This covers both cases, and if you'd like to be able to detect whether a transaction succeeds or not, you might manually input the upper limit to the block limit, and check the estimate whether it's lower or the same. If the same, the tx will fail.

**Comment by karalabe** [comment]
This is the new estimator: https://github.com/ethereum/go-ethereum/pull/3587
