### ISSUE TITLE
Implement getRevertReason for 4.x

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5069]
implement all things related to `handleRevert:true` setting

Documentation:
https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html?highlight=handlerevert#handlerevert
https://web3js.readthedocs.io/en/v1.7.3/web3-eth-contract.html?highlight=handlerevert#handlerevert

Implementation in 1.x
https://github.com/ChainSafe/web3.js/blob/2c0324af2da467ee1acb72452f20000e916e4306/packages/web3-core-method/src/index.js#L917

https://github.com/ChainSafe/web3.js/blob/2c0324af2da467ee1acb72452f20000e916e4306/packages/web3-core-method/src/index.js#L442

Also, add integration test in `web3-eth/test/integration/defaults.test.ts`

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5069?planning-poker) with ZenHub @jdevcs @nazarhussain @luu-alex @avkos @nikoulai
