### ISSUE TITLE
Investigate signtransaction testcases

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. For this [testcase](https://github.com/ChainSafe/web3.js/blob/1.x/test/eth.accounts.signTransaction.js#L167) the decoded rawTransaction does not match the return value of r and s from function account signtransaction. 
rawTransaction: `0xf85f800a827c6d94f0109fc8df283027b6285cc889f5aa624eac1f55808025a03cbfff5b8ef4588b930ecbf9b85388795875edf814dfc6c71884f99b6d7555cca057142e729c1c83bfccb2785e629fc32dffb2e613df565e78e119aa4694cb1df9`
Decoded rawTransaction: 
```
{
  "nonce": 0,
  "gasPrice": {
    "_hex": "0x0a"
  },
  "gasLimit": {
    "_hex": "0x7c6d"
  },
  "to": "0xf0109fc8df283027b6285cc889f5aa624eac1f55",
  "value": {
    "_hex": "0x0"
  },
  "data": "0x",
  "v": 37,
  "r": "0x3cbfff5b8ef4588b930ecbf9b85388795875edf814dfc6c71884f99b6d7555cc",
  "s": "0x57142e729c1c83bfccb2785e629fc32dffb2e613df565e78e119aa4694cb1df9"
}
```
While the r value returned is `0x22f17b38af35286ffbb0c6376c86ec91c20ecbad93f84913a0cc15e7580cd9` and s value is `0x83d6e12e82e3544cb4439964d5087da78f74cefeec9a450b16ae179fd8fe20`

### Expected Behavior

decoded rawTransaction from testcase should match r and s value.

### EDIT Part 2 is complete. 

2. For this post EIP1559 [testcase] (https://github.com/ChainSafe/web3.js/blob/1.x/test/eth.accounts.signTransaction.js#L656)
we receive different a `rawTransaction` when maxgas and priorityFee is type bn.
RawTransaction when `maxPriorityFeePerGas` and `maxFeePerGas` is type BN:
`0x02f86e018084c733124884cb72ec20826a4094f0109fc8df283027b6285cc889f5aa624eac1f55843b9aca0080c001a08896fb9a5c033e0163b073cf7a951a1db2dca41b26b4188f13a05158eb26fd32a005e8855691199cd0b6dcae88f3325c374e2f0697b9c528a5c10d5bd8dfb6a3e3`
RawTransaction When `maxPriorityFeePerGas` and `maxFeePerGas` is hex: `0x02f86e0180843b9aca0084b2d05e00826a4094f0109fc8df283027b6285cc889f5aa624eac1f55843b9aca0080c080a0d1290a118d51918c1ca17e3af0267c45efcd745cf42e78eabc444c424d6bcf37a003c81e1fda169575023a94200ee034128747f91020e704abaee30dbcfc785c36` 

### Steps to Reproduce

Do above

### Web3.js Version

1.7.3

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by jdevcs** [comment]
@luu-alex with mentioned merged PRs this issue should be closed. Or is there any thing pending?

**Comment by luu-alex** [comment]
@jdevcs this investigation had 2 issues, 1. still needs investigation but 2. is done.
