### ISSUE TITLE
Update BN.js dependecy to v5.2.1

### ISSUE THREAD

**Issue by gregorfelkar** [ethereum/web3.js#5072]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

* Fix serious issue in `.toString(16)`

The hex encoding of some numbers is wrong. Since the string representation
is also used for interoperability between BigInt libraries, this bug is
causing a number modification when a BN.js number is converted into
another BigInt class, for example the BigNumber of ethers.js.

https://github.com/indutny/bn.js/commit/042ab62e70418c15f189b45460709a51faf303cc

Currently it will install:
```
│ └─┬ web3-utils@1.7.3
│   ├── bn.js@4.12.0
```

**Comment by plusminushalf** [comment]
Hey I am new to the repo, will this be a good first issue? If yes I would like to pick this up.

**Comment by luu-alex** [comment]
Thank you for this @gregorfelkar this looks serious and we'll update BN as soon as we can
