### ISSUE TITLE
Investigate `4.x` Symlinks Not Working On Windows

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5075]
There was a report in the ChainSafe discord that the symlinks don't work on Windows and therefore the `4.x` branch cannot be properly setup in a Windows env

**Comment by luu-alex** [comment]
Symlinks do not work for windows machines becauase symlinks are not compatible with linux paths. 

in linux directories are specified with a forward slash for example [tsconfig.types.json symlink](https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-accounts/tsconfig.types.json): `../../config/tsconfig.types.json`

In windows, this would be:
`..\..\config\tsconfig.types.json` 

Replacing the symlinks with a copy of the file would be the easiest option to allow our project to be built in both linux and windows machines.

Edit: Had a chat with Junaid and this PR can wait until after release.

**Comment by jdevcs** [comment]
@luu-alex have you tried building 4.x using:
Windows Subsystem for Linux (WSL)
