### ISSUE TITLE
Geth returns non `HexStringBytes` value for `eth_signTransaction`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5077]
Currently [eth_signTransaction](https://github.com/ChainSafe/web3.js/blob/82574a2587810f9bea26ba65da48fe667162e573/packages/web3-common/src/eth_execution_api.ts#L284) is typed to return `HexStringBytes`, but when working on #5056, I discovered Geth returns [an object](https://github.com/ethereum/go-ethereum/blob/c1b69bd12184cc6278f5641c14bc72ca0a42d397/internal/ethapi/api.go#L1735)

[More context](https://github.com/ChainSafe/web3.js/pull/5056/files#r885098419)

To solve the issue mentioned in `More context`, I believe we'd need to implement a util method similar to [ethers.js' parse](https://github.com/ethers-io/ethers.js/blob/master/packages/transactions/src.ts/index.ts#L478)

**Comment by jdevcs** [comment]
Fix tests in packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts

https://github.com/ChainSafe/web3.js/pull/5137#discussion_r901853796
