### ISSUE TITLE
Hanging promise in `web3-eth` integration tests

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5079]
`--forceExit` flag should be removed from the `test:integration` npm script in `web3-eth` package, but can't because there seems to be hanging promises in:

- [rpc.test.ts](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-eth/test/integration/rpc.test.ts)
- [subscription_logs.test.ts](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-eth/test/integration/subscription_logs.test.ts)

**Comment by jdevcs** [comment]
Web3 Eth integration tests with websocket:
(test/integration/web3_eth/send_transaction.test.ts:73:90)
(test/integration/web3_eth/send_transaction.test.ts:104:92)
(test/integration/web3_eth/send_transaction.test.ts:135:103)

**Comment by jdevcs** [comment]
defaults.test.ts - Websocket
- System Test Utils ( number of functions )
- transactionConfirmationBlocks
- transactionConfirmationBlocks implementation
- should fallback to polling if provider support `on` but `newBlockHeaders` does not arrive in `blockHeaderTimeout` seconds
- defaultTransactionType

**Comment by jdevcs** [comment]
bug:
setMaxListenerWarningThreshold(); is not called for setting `MaxListenerWarningThreshold` in event emitter if config is set via `setConfig()`, so `maxListenersWarningThreshold` doesn't match with config and eventemitter Threshold values

**Comment by jdevcs** [comment]
defaults.transactionBlockTimeout.test.ts - Websocket
- should fail if transaction was not mined within `transactionBlockTimeout` blocks
- should fail if transaction was not mined within `transactionBlockTimeout` blocks - when subscription is used

**Comment by jdevcs** [comment]
should fail if transaction was not mined within `transactionBlockTimeout` blocks
should fail if transaction was not mined within `transactionBlockTimeout` blocks - when subscription is used

**Comment by jdevcs** [comment]
list of tests in get_revert_reason.test.ts  - Websocket

**Comment by jdevcs** [comment]
Tests in:

- Defaults
- defaults.transactionBlockTimeout
- getRevertReason
- WatchTransaction
