### ISSUE TITLE
No resolve transaction when event index is big

### ISSUE THREAD

**Issue by tungmaimt** [ethereum/web3.js#5084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had do some tests and it seem that when smart contract emit and event with big indexed params, it will lead to failling to decode it. And this cause to action send do not resolve or reject when the transaction done, it just does not run into then or catch. The event subcribe is affect to, but thank god it had an error.

![image](https://user-images.githubusercontent.com/33393379/170682575-5d02e0c7-3eff-47f4-9f05-918f2290ee15.png)

### Expected Behavior

The resolve of send function should be called normally when transaction success or reject if there is something wrong.

### Steps to Reproduce

Smart contract event:
```
event SomethingWithBigIndex(
    address[] indexed tokenAddresses,
    uint256[] indexed tokenIds,
    address[] froms,
    address[] tos,
    uint256[] amounts
);

function callSomethingBig(
    address[] memory tokenAddresses,
    uint256[] memory tokenIds,
    address[] memory froms,
    address[] memory tos,
    uint256[] memory amounts
) external{
     emit SomethingWithBigIndex(tokenAddresses, tokenIds, froms, tos, amounts);
}
```
Web3 smart contract method call:
```
myContract.methods.callSomethingBig(
    addresses,
    tokenids,
    froms,
    tos,
    amounts,
).send({
    from: address,
    gas: estimateGas
}).then(transactionReceipt => {
    console.log('should go here but it's not')
}).catch(error => {
    console.log('or should go error but it's not')
})
```

### Web3.js Version

1.7.3

### Environment

- Operating System: Window10
- Browser: Version 101.0.4951.67 (Official Build) (64-bit)
- Node.js Version: v16.14.0
- NPM Version: 8.3.1

### Anything Else?

I can fix this with removing index at the contract event and it will process perfectly. But I think we should not go with this so hope you guys can do something about this issue.

**Comment by nazarhussain** [comment]
@tungmaimt That seems a bug. Can you share some reproducible code that we can execute to verify it. Or some sample value you used for the above script.

**Comment by tungmaimt** [comment]
> SomethingWithBigIndex(tokenAddresses, tokenIds, froms, tos, amounts);

Sorry for my late reply.

I had deployed a test contract to BSC testnet and had verified it. Here is the info:
- Address: 0xb54859bE787Bfb86DDcF1d2F8947E41956d992a2
- Scan url: https://testnet.bscscan.com/address/0xb54859bE787Bfb86DDcF1d2F8947E41956d992a2
- Sol and ABI file: [TestBigIndex.zip](https://github.com/ChainSafe/web3.js/files/9367578/TestBigIndex.zip)

Transaction hash: 0xe138d6ca2b581822d01cb40647df9f594eb4281d42148a3af35fc0f73c5bcd3f
Transaction scan url: https://testnet.bscscan.com/tx/0xe138d6ca2b581822d01cb40647df9f594eb4281d42148a3af35fc0f73c5bcd3f

![image](https://user-images.githubusercontent.com/33393379/185291788-a320b902-2293-40fb-bb6f-39a7e582c561.png)


Params I use for test:
```
myContract.methods.callSomethingBig(
    [
        "0x7c539601a0Be3AbF343F39F4ee0Be85a8AB50FF9",
        "0x9489a42DeE60Ef79aEb8c53786BA583D3004b732",
        "0x10549805E68A158192f7F5592ca76cf1dC1e3C06",
        "0x83D4A49a54a7619F87B5DBa6f2b05aC30dD0AA55",
        "0xfBA0C1f770D1788D84CB8cE4eaFfaaA12d2c32B6",
        "0x37641cfd745c81301CFb31C95433bBfF678EB378",
    ],
    [ "0" ],
    [ "0x7c539601a0Be3AbF343F39F4ee0Be85a8AB50FF9" ],
    [ "0x7c539601a0Be3AbF343F39F4ee0Be85a8AB50FF9" ],
    [ "0" ],
).send({
    from: address,
    gas: estimateGas,
}).then(transactionReceipt => {
    console.log('should go here but it's not')
}).catch(error => {
    console.log('or should go error but it's not')
})
```

**Comment by mconnelly8** [comment]
6/12 - keep, also check in 4.x

**Comment by mconnelly8** [comment]
10/1 Meeting - Shouldn't be an issue with 4.x, but need to double check.

**Comment by luu-alex** [comment]
Fixed in 4.x. closing
