### ISSUE TITLE
Implement defaultCommon, maxListenersWarningThreshold

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5087]
Implement all things related with `defaultCommon`, `maxListenersWarningThreshold` in 4.x

Doc:
- https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html?highlight=defaultCommon#defaultcommon
- https://web3js.readthedocs.io/en/v1.7.3/web3-eth-contract.html?highlight=defaultCommon#defaultcommon
- https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html?highlight=maxListenersWarningThreshold#maxlistenerswarningthreshold

Tests
- add integration test to `packages/web3-eth/test/integration/defaults.test.ts`
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5087?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain
