### ISSUE TITLE
Web3js stop firing event on subscription with Hardhat Node 

### ISSUE THREAD

**Issue by NatPDeveloper** [ethereum/web3.js#5088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run less of the unit tests, the current tests that are failing pass. I am running this on a c5.xlarge ec2 instance using docker containers.  The project can be found here: https://github.com/DAPPNetworkLabs/dapp-workers/.

I tried increasing the instance size and monitoring the memory usage.

### Expected Behavior

I expect the events to be captured based on the subscriptions I setup here: https://github.com/DAPPNetworkLabs/dapp-workers/blob/main/services/orchestrator/src/index.ts#L308

### Steps to Reproduce

You can recreate the issue by running the unit tests for this repo (https://github.com/DAPPNetworkLabs/dapp-workers/) with:

```
./scripts/all-test.sh
```

You will also need to export an IPFS and ALECHEMY_ADDRESS environment variables

```
export IPFS_HOST=HOST_IP
ALCHEMY_ADDRESS=https://eth-mainnet.alchemyapi.io/v2/API_KEY_HERE
```

If you need an IPFS host IP / Alchemy key to test you can hit me up on Telegram @natpd.

This will build the docker images and run the:
- IPFS instance
- Hardhat node forking mainnet with alchemy key
- Orchestrator backend API (dispatches docker container creation)
- Nexus hardhat unit tests with forked mainnet node

Be sure to add a `.config.json` to `./eth/.config.json` and `./nexus/.config.json` so hardhat has the proper alchemy (https://www.alchemy.com/) keys to for the ETH mainnet. 

    {
        "alchemyKey": ""
    }

  [1]: https://github.com/DAPPNetworkLabs/dapp-workers/blob/main/services/orchestrator/src/index.ts#L308

### Web3.js Version

1.7.0

### Environment

- Operating System: Ubuntu 18
- Browser: Brave
- Node.js Version: v16.14.2 base, in docker 17
- NPM Version: 8.5.0

### Anything Else?

Thank you : )

**Comment by luu-alex** [comment]
Hey there @NatPDeveloper, can you give us the error or snippet of code of which testcase is failing

**Comment by NatPDeveloper** [comment]
> Hey there @NatPDeveloper, can you give us the error or snippet of code of which testcase is failing

Hello there! All tests passed when reordered for whatever timeout issue or API issue I seem to be experiencing. Perhaps it's an alchemy thing. 

> Free tier users will be limited to 10 concurrent requests per WebSocket connection.

https://docs.alchemy.com/alchemy/apis/ethereum/eth-subscribe-1

Otherwise when the tests are fully uncommented the git-cloner test is the first to fail where the web socket stops emitting events with no history of error, disconnect, reconnect, close, or other issues.

https://github.com/DAPPNetworkLabs/dapp-workers/blob/main/nexus/test/Nexus.spec.js#L931

When you run the docker compose with the script, there will be output from all files. You will see the ETH node logs receiving 3 transactions from the test, but the orchestrator API will respond to nothing and the test will timeout.

Perhaps as a smaller reproduceable issue you could setup a simple contract and web socket events that emits more than 15 times to see if it works. And also if it will do the 15 over say 15 minutes. Mine will not and fails consistently at the same test which leads me to believe this is a limitation in the api (though it says concurrent not consecutive) or a timeout of the APIs availability by web socket.

**Comment by NatPDeveloper** [comment]
It seems the issue is having more than 10 concurrent event channels opened at a time.

After receiving the desired event or hitting a timeout you can use the following if using [ethers js](https://docs.ethers.io/v4/api-contract.html?highlight=removealllisteners#event-emitter).

```
await contract.removeAllListeners(event);
```

I'll reopen if that's not the case, thanks.
