### ISSUE TITLE
TypeError: value.toLowerCase is not a function

### ISSUE THREAD

**Issue by NickKelly1** [ethereum/web3.js#5089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Web3.utils.toHex` unexpectedly throws an error when given certain `BN` inputs due to incorrectly inferring a `BN` is an address and therefore a string.

### Expected Behavior

`Web3.utils.toHex` should not throw an error given the valid `BN` input.

### Steps to Reproduce

Using this code:

```js
const Web3 = require('web3');

const bn1 = Web3.utils.toBN('1000000000000000000001000000000000000000')
const bn2 = Web3.utils.toBN('0x2f050fe938943acc46d460d33a7640000');
console.log('are equal: ', (bn1.toString(16) === bn2.toString(16)));

// error is caused by this line in "web3-utils/lib/utils.js"
// function: "isAddress" thinks this BN input is an address:
if (/^(0x|0X)?[0-9a-f]{40}$/.test(bn1) || /^(0x|0X)?[0-9A-F]{40}$/.test(bn1)) {
  // if this resolves true, then the value is considered an address
  console.info('BN resolved as address');
}


// throws:
//  TypeError: value.toLowerCase is not a function
const hex = Web3.utils.toHex(bn1);
```

Throws
```sh
➜  23 node src/main.js    
are equal:  true
BN resolved as address
/home/nick/development/tmp/20x/23/node_modules/.pnpm/web3-utils@1.7.3/node_modules/web3-utils/lib/utils.js:292
        return returnType ? 'address' : '0x' + value.toLowerCase().replace(/^0x/i, '');
                                                     ^

TypeError: value.toLowerCase is not a function
    at Object.toHex (/home/nick/development/tmp/20x/23/node_modules/.pnpm/web3-utils@1.7.3/node_modules/web3-utils/lib/utils.js:292:54)
    at Object.<anonymous> (/home/nick/development/tmp/20x/23/src/main.js:17:24)
```

### Web3.js Version

1.7.3

### Environment

- Operating System: Ubuntu 20.04
- Browser: None
- Node.js Version: 18.0.0
- NPM Version: 8.7.0

**Comment by ashwinYardi** [comment]
If my understanding is correct,  regex used in `isAddress` also passes 40 digit Bignumbers as address. We can mitigate this by adding additional check in `isAddress` as follows:
`value.substring(0, 2) === '0x' || value.substring(0, 2) === '0X' ` 
@NickKelly1 @luu-alex

**Comment by ashwinYardi** [comment]
@NickKelly1 You can also use `utils.numberToHex()`. It works correctly.
