### ISSUE TITLE
Improve the integration tests for contracts default attributes.

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5096]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

During the first phase of the integration tests we covered the following default configuration options:

1. defaultAccount
2. defaultBlock

Following attributes should be covered further in the integration tests. 

1. [ ] defaultHardfork
2. [x] defaultChain
3. [ ] defaultCommon
4. [x] transactionBlockTimeout
5. [x] blockHeaderTimeout
6. [x] transactionConfirmationBlocks
7. [x] transactionPollingTimeout
8. [ ] transactionPollingInternval
9. [ ] handleRevert

All these attributes should be tested on contract **static** level as well as **instance** level. 

### Examples/References

https://github.com/ChainSafe/web3.js/pull/5093

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5096?planning-poker) with ZenHub @luu-alex @nikoulai @spacesailor24 @nazarhussain @jdevcs @avkos
