### ISSUE TITLE
4.x CI / CD Improvements

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5097]
- [x]    Check build size
- [ ]     Github Secrets Scanning ( https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories )
- [ ]     Discover vulnerabilities https://codeql.github.com/
- [x]     using codecov https://about.codecov.io/language/typescript/
- [x]     Auto publish doc ~~with tag push~~
- [ ]     Test build on tag push with external apps
- [ ]     Supplychain security ( Configuring the dependency graph https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-the-dependency-graph )

**Comment by mconnelly8** [comment]
Closing issue.  Opened new issues to work on remaining tasks (#5628 , #6529 , #6530 , #6531 )
