### ISSUE TITLE
Migration Guide/Breaking Changes - Accounts/Wallet

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#5104]
This information relates to the API documentation.

**Comment by jdevcs** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5104?planning-poker) with ZenHub @avkos @luu-alex @nikoulai @spacesailor24
