### ISSUE TITLE
Ability to register (watch) a contract form a DAPP

### ISSUE THREAD

**Issue by chevdor** [ethereum/web3.js#511]
It would be nice to have in `web3.js` a way to propose a contract watch from a dapp.

The request could look like:
```
{
  name: 'Suggested name for the contract',
  description: 'This contract does this and that.....',
  address: '0x1234...',
  abi: '[.....]',
  tags: ['tag1', ...]
}
```

Obviously, we don´t want DAPPs to register contracts in the back of the user. Such a request shows a popup to the user with the details of the request. 
If the user rejects, well... life goes on :)
If the user confirms, the contract is added to the watched contracts. The user can edit the name, the description and the tags but not the address and the abi.

That would allow for instance users to register (watch) their Multisig Wallets from a DAPP that would only ask for the address.

In general, for DAPPs deploying contracts, it would allow making the user´s life easier and with less copy/paste always prone to errors.

I proposed the same in `parity.js`

See https://github.com/ethcore/parity/issues/3217

**Comment by cokia** [comment]
I think this is a really necessary function.

**Comment by chevdor** [comment]
Hello @nivida, is there a reason why this issue could never move on or be commented ?
