### ISSUE TITLE
Implement all things related with blockHeaderTimeout

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5112]
Documentation
[https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html?highlight=blockHeaderTimeout#blockheadertimeout](https://web3js.readthedocs.io/en/v1.7.3/web3-eth.html?highlight=blockHeaderTimeout#blockheadertimeout)

add integration tests here: packages/web3-eth/test/integration/defaults.test.ts

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5112?planning-poker) with ZenHub @nazarhussain @jdevcs @luu-alex @avkos
