### ISSUE TITLE
Default account is not implemented in .call method

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5117]
Methods to fix:
eth.call()
contract.methods?.someMethod().call();

after fixing uncomment tests here `packages/web3-eth/test/integration/defaults.test.ts`

#### Expected behavior
eth.call() should send request with `from = defaultAccount`
contract.methods?.someMethod().call(); should send request with `from = defaultAccount`

#### Actual behavior
eth.call() should send request with `from = undefined`
contract.methods?.someMethod().call(); should send request with `from = undefined`

#### Steps to reproduce the behavior

1. For the test you can use `MsgSender.sol`
2. set default account to contract
```ts
    contract.setConfig({
                defaultAccount: accounts[0],
     });
```
2. send a request for a contract
```ts
 const res = await contractMsgFrom.methods?.from().call();
```
3. res should be `defaultAccount`

**Comment by jdevcs** [comment]
Check this with 1.x, if its adding default account for eth_call
