### ISSUE TITLE
Upgrade ethereum-cryptography to 1.0

### ISSUE THREAD

**Issue by paulmillr** [ethereum/web3.js#5122]
You're using 0.2 in util. 1.0 should be used, because it consumes 5 dependencies instead of 38; and has massive security improvement.

Blog post: https://medium.com/nomic-foundation-blog/a-safer-smaller-and-faster-ethereum-cryptography-stack-5eeb47f62d79

**Comment by nazarhussain** [comment]
Already doing it in 4.x

**Comment by paulmillr** [comment]
This line in branch 4.x says you're still using v0.2:

https://github.com/ChainSafe/web3.js/blob/059e6cd6100f67db3d337b91875c1fe44f1724fc/packages/web3-utils/package.json#L45

**Comment by paulmillr** [comment]
4.x web3-validator is also using the legacy version:

https://github.com/ChainSafe/web3.js/blob/059e6cd6100f67db3d337b91875c1fe44f1724fc/packages/web3-validator/package.json#L29

**Comment by paulmillr** [comment]
Note that 1.x uses bigints extensively, so it would play nice with #5128.

**Comment by jdevcs** [comment]
@paulmillr Thanks for highlighting this. Could you go ahead and open 4.x PR?

**Comment by paulmillr** [comment]
@jdevcs not really. I've spent around 30 mins, but your build process a) takes forever to download all packages b) is filled with errors and doesn't allow me to build the package on my machine. Here's output of `build` in root directory:

```
web3-eth-abi: src/ethers_abi_coder.ts(18,26): error TS2307: Cannot find module '@ethersproject/abi' or its corresponding type declarations.
web3-eth-abi: src/ethers_abi_coder.ts(20,38): error TS7006: Parameter 'type' implicitly has an 'any' type.
web3-eth-abi: src/ethers_abi_coder.ts(20,44): error TS7006: Parameter 'value' implicitly has an 'any' type.
web3-eth-abi: src/utils.ts(19,37): error TS2307: Cannot find module '@ethersproject/abi' or its corresponding type declarations.
web3-eth-abi: src/api/parameters_api.ts(19,27): error TS2307: Cannot find module '@ethersproject/abi' or its corresponding type declarations.
web3-eth-abi: error Command failed with exit code 1.
web3-eth-abi: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So I would suggest to do it on your own. We've worked hard to ensure the upgrade process is as simple as possible — see [README](https://github.com/ethereum/js-ethereum-cryptography#upgrading).

**Comment by jdevcs** [comment]
@mconnelly8 this update for next Sprint.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5122?planning-poker) with ZenHub @jdevcs @nikoulai @luu-alex @nazarhussain
