### ISSUE TITLE
Incompatible return types for 4.x implementations 

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5126]
While migrating [truffle](https://github.com/trufflesuite/truffle) came across a few changes which are required to make web3@4x compatible with a lot of projects our there.

Here is the the list of individual changes:

1. [ ] `web3.eth.getTransaction` should always return transaction or throw. Should not have return type of `undefined`. 
2. [ ] `web3.eth.getTransactionReceipt` should always return receipt or throw. Should not have return type of `undefined`.
3. [ ] `TransactionReceipt` property `address` should not be optional.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5126?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain @nikoulai
