### ISSUE TITLE
Add missing functionality from main Web3 class

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5133]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Add some missing features to web3 main class:

Missing features
- [x] web3.version
- [x] web3.utils not exported
- [x] web3.modules not exported
- [x] web3.extend not implemented

**Comment by jdevcs** [comment]
its implemented in 4x
