### ISSUE TITLE
web3.eth.accounts.signTransaction VS EIP-1559

### ISSUE THREAD

**Issue by overdoignism** [ethereum/web3.js#5141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

When we read the document part for web3.eth.accounts.signTransaction,
There is only have gas and gas price, no max priority, no max fee.

May you update this part document for support EIP-1559?
Or it need to update the API library code?

Thanks.

**Comment by overdoignism** [comment]
BTW, When I am using the maxFeePerGas and maxPriorityFeePerGas with gasPrice in web3.eth.accounts.signTransaction (undocumented way)

It will say and error: eip-1559 transactions don't support gasPrice

But if I remove gasPrice , it will execute web3.eth.gasPrice and make me can't sign offline. 

Looks like a code problem?

**Comment by nikoulai** [comment]
Hi @overdoignism, thanks for reaching out.

EIP 1559 is supported by web3js, however, gasPrice shouldn't be passed in this case.
Could you provide an example of what you are trying to achieve?

Regarding the documentation, could you open a PR updating the docs? Our focus this period is the 4.x rewriting.

**Comment by overdoignism** [comment]
> Hi @overdoignism, thanks for reaching out.
> 
> EIP 1559 is supported by web3js, however, gasPrice shouldn't be passed in this case. Could you provide an example of what you are trying to achieve?
>

I'm trying to use the web3js to make an offline sign,  for studying and a little offline wallet project. 

Sorry for that--  I really don't know the relationship between max/priority fee and gas price.
There are too many theories on the Internet, and English is not my native language. :~
(Some said that if a wallet using gas price which is an old type and it will cost higher gas fee)

> Regarding the documentation, could you open a PR updating the docs? Our focus this period is the 4.x rewriting.

Sorry - I have no idea how to fix the document. (What is correct?) :~

**Comment by luu-alex** [comment]
Hi @overdoignism  can you provide what options you are passing into signTransaction? this is the logic behind signTransaction https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js#L355
We will try to update the docs when we can 👍 thank you for reaching out

**Comment by overdoignism** [comment]
> Hi @overdoignism can you provide what options you are passing into signTransaction? this is the logic behind signTransaction https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js#L355 We will try to update the docs when we can 👍 thank you for reaching out

It's my code:

	var transaction = {
		to: Reciver_Addr,
		value: TrueSendETH.toString(),
		gas: 21000,
		gasPrice: TrueSendGas.toString(),
		nonce: Sender_nonce,
		chainId: ChainID,
		maxFeePerGas: 50, // a casual value
		maxPriorityFeePerGas: 50,
	};

	var TR_SIGN_OBJ;
	var TR_SIGN;

	try {
		TR_SIGN_OBJ = await web3.eth.accounts.signTransaction(transaction, Private_Key);
		TR_SIGN = JSON.stringify(TR_SIGN_OBJ);
	} catch (exception) {
		res.write(exception.message);
	}

Everything work fine but If maxFeePerGas and maxPriorityFeePerGas present, 
it will throw exception.message "eip-1559 transactions don't support gasPrice"

**Comment by nazarhussain** [comment]
@overdoignism Yes documentation needs to be updated. Would like to contribute and open PR for that change?

**Comment by overdoignism** [comment]
> @overdoignism Yes documentation needs to be updated. Would like to contribute and open PR for that change?

I hope but have no idea how to... :~

I still studying about Ethereum, web3js, even the JavaScript and GitHub, on the basic stage.
Sorry for that...

**Comment by nikoulai** [comment]
This [PR](https://github.com/ChainSafe/web3.js/pull/5121#event-6859009196) addresses documentation
