### ISSUE TITLE
IPC Provider - Batch requests

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5144]
Make Batch requests work with the IPC provider.

Turn on Batch requests tests:
`packages/web3-eth/test/integration/eth.test.ts`
`packages/web3/test/integration/main_web3.test.ts`

#### Steps to reproduce the behavior

1. run geth locally  `yarn geth:start`. after that you will have ipc socket file here `tmp/ipc`
2. set env variable `export WEB3_SYSTEM_TEST_PROVIDER=$(pwd)/tmp/ipc`
3. try to run batch request test
`packages/web3-eth/test/integration/eth.test.ts`
`packages/web3/test/integration/main_web3.test.ts`

**Comment by Muhammad-Altabba** [comment]
Hello @avkos 
Could those be resolved now:? 

1. https://github.com/web3/web3.js/blob/b2b5a95d927845d5963d89c781acf8d9fbac94d1/packages/web3/test/integration/main_web3.test.ts#L252
2. https://github.com/web3/web3.js/blob/b2b5a95d927845d5963d89c781acf8d9fbac94d1/packages/web3-eth/test/integration/defaults.test.ts#L302
