### ISSUE TITLE
web3.utils.toHex wrong result

### ISSUE THREAD

**Issue by sturmenta** [ethereum/web3.js#5148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when transform decimal to hex, show a different hex than previously ingresed

first hex
```
0x02ea6174f3bb89f5c3ad6ddd8af235ef41de683c6a45997a494cc9cea77cd50d
```

decimal result
```
1318740532742162690744885990779947901626425298206064255871929395343091619085
```

result and different hex
```
0x2ea6174f3bb89f5c3ad6ddd8af235ef41de683c6a45997a494cc9cea77cd50d
```

### Expected Behavior

the starting way of resulting hex is different `ingresed -> 0x02` and `result -> 0x2`

### Steps to Reproduce

code

```js
const Web3 = require("web3");
const web3 = new Web3();

const hex =
  "0x02ea6174f3bb89f5c3ad6ddd8af235ef41de683c6a45997a494cc9cea77cd50d";

console.log(`hex`, hex, typeof hex);

const hexToDec = web3.utils.toBN(hex).toString();
console.log(`hexToDec`, hexToDec, typeof hexToDec);

const decToHex = web3.utils.toHex(hexToDec);
console.log(`decToHex`, decToHex, typeof decToHex);

```

results

```
hex 0x02ea6174f3bb89f5c3ad6ddd8af235ef41de683c6a45997a494cc9cea77cd50d string
hexToDec 1318740532742162690744885990779947901626425298206064255871929395343091619085 string
decToHex 0x2ea6174f3bb89f5c3ad6ddd8af235ef41de683c6a45997a494cc9cea77cd50d string
```

### Web3.js Version

1.7.3

### Environment

- Operating System: macOs Monterey 12.4
- Node.js Version: v14.19.3
- NPM Version: 6.14.17

**Comment by sturmenta** [comment]
```md
There's no difference between 0x01 and 0x1.
```

> There's no difference between 0x01 and 0x1. In hexadecimal notation 0x1, 0x01, 0x001, and so on, they all means 1. About transaction's status code, if it is set to 1 it always means a successful execution. Check [this question/answer](https://ethereum.stackexchange.com/questions/28889/what-is-the-exact-meaning-of-a-transactions-new-receipt-status-field) for more details.

 [source](https://ethereum.stackexchange.com/questions/51272/difference-between-0x01-and-0x1-status-code)

**Comment by sturmenta** [comment]
`0x0b` is different to this `0xb` in etherscan

work https://etherscan.io/tx/0x0b8291d81ac84dbbde31cd54a934de594189702a98629df6b80d51653b567e06
doesn't https://etherscan.io/tx/0xb8291d81ac84dbbde31cd54a934de594189702a98629df6b80d51653b567e06

Is the `web3.utils.toHex` function considering these cases?

**Comment by nikoulai** [comment]
Hi @sturmenta , thanks for reaching out to us.

`0x01` and `0x1` are the same if they are used as number values (they mean the same). However, `transactionsHash` is a string and is meant to have a specific length (0x + 64 [A-Fa-f0-9] chars). 
On that, `web3.utils.toHex` works for values, is not specific to transaction hash, you will have to ensure on your part that you pass a valid txHash.

Why would you need to transform txHash to integer??

**Comment by sturmenta** [comment]
hi @nikoulai , thanks for the response

> Why would you need to transform txHash to integer??

trying to convert a privateKey to a mnemonic with https://github.com/mbrubeck/mnemonic.js
