### ISSUE TITLE
Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by jacobtt21** [ethereum/web3.js#5152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I try and write to my Smart Contract, I continue to get this error. I have checked Google and Github, but nothing seems to give any sort of answer/solution. I have no idea how to correct this.

### Expected Behavior

I expected it to work, it was working on Thursday, but now it doesn't.

### Steps to Reproduce

`const receipt = await contract.methods.NAMEOFMETHOD(parameters, ...).send({ 
  from: user ETH Address,
  gas: 100000000000
});`

### Web3.js Version

^1.7.3

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nikoulai** [comment]
Hey @jacobtt21 , thanks for reaching out!

Have you tried to use the listener for `receipt`?
```
.on('receipt', function(receipt){
    // receipt example
    console.log(receipt);
    })
```

**Comment by nazarhussain** [comment]
@jacobtt21 What's the error you are getting? And also share a reproducible code that we can use to investigate.

**Comment by jacobtt21** [comment]
Turns out this was a problem with my RPC provider, I switched to Infura and it works now!
