### ISSUE TITLE
Onlyowner restricted type function is acessible by all the accounts present in the wallet

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [ethereum/web3.js#5154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hii sir greeting's of the day .i am making an simple voting application in that i makes the smart contract and there i made a function declare_winner( ) which is restricted to use and called by the owner only but  whenver i call this function( ) it is.acessible by all the account avialable in the wallet ...
please help in this issue ..

### Expected Behavior

i want that only owner can call that function using web3.js in the frontend 

### Steps to Reproduce

u can find the code here : 

https://github.com/Vikash-8090-Yadav/Web3.0-World/tree/main/Level0/Voting

### Web3.js Version

1.2.7-rc.0

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nikoulai** [comment]
Hi, thanks for reaching out.

Restriction for only owner should take place in the smart contract by using the modifier. This would revert the transaction for any other user trying to call it.

If you would like to hide the button for the rest of the users you could read the owner address of the smart contract and ensure it is the one injected from the wallet. However, you cannot restrict who is trying to interact with the contract, although, their transactions are going to be reverted.

I'm going to close the issue, if you need any help with web3js don't hesitate to join our discord and contact us.

**Comment by Vikash-8090-Yadav** [comment]
Thanks for the very fast reply sir !!
The main probelm with my applicattion is that all the thing's which u guide above is up to date 
The problem  is that it is not reverting idk why ?? but in plcae of reverting it is showing the result to the non owner address also 


**Can u please provide me the link of your web3.js discord server ..!**

**Comment by nikoulai** [comment]
I guess it's not a problem with web3js. Could you provide some output?

To join the discord:
https://discord.gg/Hq9ttqqU

**Comment by Vikash-8090-Yadav** [comment]
Yes u can see this video in this i  first clicked int he button using the .call( ) method which is giving not correct ans . and if i am using the .send( ) in this is giving the correct output !! 
As the function is the write only  so that i can't use the .send( ) .. 
I hope u understand the question please provide the solution for this .. 
U can also find my whole code on this : 

https://github.com/Vikash-8090-Yadav/Web3.0-World/tree/main/Level0/Voting


Video -->>

https://www.veed.io/view/44215818-2765-4dbe-a9cc-f7222a02a68b
