### ISSUE TITLE
Regarding new web3.js - use CSP channels and/or Rx.js

### ISSUE THREAD

**Issue by kristianmandrup** [ethereum/web3.js#516]
I just listened to your talk at Devcon two. I understand you are refactoring using promises. 
I'd recommend using async/await and then compiling via Babel. 
Consider using [CSP channels](https://github.com/ubolonton/js-csp) and/or [Rx.js](http://reactivex.io/) Observable streams. 
I think it would simplify the API a lot!
I'd be happy to contribute in refactoring this essential library.
Cheers :)

**Comment by nivida** [comment]
Thanks for your suggestions we will refactor the web3.js to es6 after the 1.0 release. If you like to contribute have a look at the ```1.0ES6``` branch. :)
