### ISSUE TITLE
How to get balance at block number?

### ISSUE THREAD

**Issue by mfnatiq** [ethereum/web3.js#5163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

How to get ERC20 token balance at a particular block number?

```
{
  "code": -32000,
  "message": "missing trie node ...
}
```

### Expected Behavior

Expected to see the correct balance:

### Steps to Reproduce

Working:
```
contract.methods
            .balanceOf(userAddr)
            .call()
```

Not working:
```
contract.methods
            .balanceOf(userAddr)
            .call(undefined, 28150045)
```

### Web3.js Version

1.7.3

### Environment

- Operating System: Windows 10
- Browser: Chrome
- Node.js Version: v16.13.2
- NPM Version: 8.1.2

**Comment by WizardsOrb** [comment]
```ts
import { toChecksumAddress } from 'web3-utils'

async function balanceOf (token: string, holder: string, block: string | number = 'latest') {
  if (typeof block === 'number') block = `0x${block.toString(16)}`
  holder = toChecksumAddress(holder).substring(2)

  return web3.eth.call({
    to: toChecksumAddress(token),
    data: `0x70a08231000000000000000000000000${holder}`
  }, block)
}

const hexBalance = await balanceOf(token, address, 1337)
```

**Comment by mfnatiq** [comment]
> ```ts
> import { toChecksumAddress } from 'web3-utils'
> 
> async function balanceOf (token: string, holder: string, block: string | number = 'latest') {
>   if (typeof block === 'number') block = `0x${block.toString(16)}`
>   holder = toChecksumAddress(holder).substring(2)
> 
>   return web3.eth.call({
>     to: toChecksumAddress(token),
>     data: `0x70a08231000000000000000000000000${holder}`
>   }, block)
> }
> 
> const hexBalance = await balanceOf(token, address, 1337)
> ```

hi @WizardsOrb thanks for your reply, but i get the same error as my OP

**Comment by layonthebeech** [comment]
I am having the same issue but getting this response (i'm also using the bsc RPC)

var err = new Error('Returned error: ' + message);              
Error: Returned error: header not found

https://github.com/ChainSafe/web3.js/issues/1262

no longer seems relevant or working
