### ISSUE TITLE
`eth.getAccounts` doesn't return checksum addressed

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5166]
### Is there an existing issue for this?

First mentioned here: https://github.com/ChainSafe/web3.js/pull/5136#discussion_r904756710

- [X] I have searched the existing issues

### Current Behavior

addresses are not returned as checksum:
```
await web3Eth.getAccounts();
//[
//  '0xf4ffff492596ac13fee6126846350433bf9a5021',
//  '0xdc6bad79dab7ea733098f66f6c6f9dd008da3258'
//]
```

### Expected Behavior

should return:

[
  '0xF4FfFF492596ac13fee6126846350433bF9a5021',
  '0xdc6BAD79dAb7EA733098f66F6C6F9dd008Da3258'
]

### Steps to Reproduce

```
import Web3Eth from "web3-eth";

let web3Eth = new Web3Eth("http://localhost:8545");
console.log(await web3Eth.getAccounts());
```

### Web3.js Version

4.x

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5166?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain @nikoulai
