### ISSUE TITLE
Web3-Common and Web3-Core Documentation - Defaults

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5167]
A lot of behavior and properties are inherited from the `Web3Context` and few others to the `contracts`, `eth` and `web3` package. 

We need to document all default configuration and properties from `web3-common` and `web3-core` packages. These docs must cover

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5167?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain @nikoulai

**Comment by jdevcs** [comment]
defaultAccount, defaultBlock, defaultHardFork, defaultCommon, transactionBlockTimeout, transactionConfirmationBlocks, transactionPoolingInteval, transactionREceiptPollingInterval, blockHeaderTimeout, handleRevert
