### ISSUE TITLE
`eth.getFeeHistory` doesn't return all values

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

returns 
```
{ oldestBlock: 1n }
```

### Expected Behavior

1.x returns
```
{
  oldestBlock: '0x1',
  baseFeePerGas: [ '0x342770c0', '0x2da89983' ],
  gasUsedRatio: [ 0.0018243056410397187 ]
}
```

### Steps to Reproduce

await web3Eth.getFeeHistory("0x1", "latest", []);

### Web3.js Version

4.x

**Comment by Spacesai1or** [comment]
[This](https://github.com/ChainSafe/web3.js/blob/9d4ba98da3272a352992f10dd9a933baa2c6796f/packages/web3-eth/src/schemas.ts#L393) schema probably just need to have `gasUsedRatio` added to it
