### ISSUE TITLE
Registrar deprecated

### ISSUE THREAD

**Issue by bas-vk** [ethereum/web3.js#517]
The old registrar is succeeded by ENS and can be removed.

**Comment by frozeman** [comment]
Sure, will be changed in 1.0

**Comment by evbots** [comment]
@frozeman @bas-vk Is the "old" registrar you are referencing implemented by the method `web3.eth.namereg`? I'm reading the Ethereum wiki contract tutorials and it references a registrar but the documentation on this is pretty sparse.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
