### ISSUE TITLE
Update Wallet.encrypt function signature - 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

4.x [Wallet encrypt](https://github.com/ChainSafe/web3.js/pull/5164/files#diff-eb74ad4a6da9b86debef3794235c12e70ccdcdc4aed9ec77b7ccf70b2fef10fcR273) returns a string instead of an object, which is a breaking feature from 1.x. 

### Expected Behavior

Should be an object like 1.x

### Steps to Reproduce

web3.eth.accounts.wallet.create(1)
	 * web3.eth.accounts.wallet.encrypt("abc").then(console.log);
	 * > [
	 * '{"version":3,"id":"fa46e213-a7c3-4844-b903-dd14d39cc7db",
	 * "address":"fa3e41a401609103c241431cbdee8623ae2a321a","crypto":
	 * {"ciphertext":"8d179a911d6146ad2924e86bf493ed89b8ff3596ffec0816e761c542016ab13c",
	 * "cipherparams":{"iv":"acc888c6cf4a19b86846cef0185a7164"},"cipher":"aes-128-ctr",
	 * "kdf":"scrypt","kdfparams":{"n":8192,"r":8,"p":1,"dklen":32,"salt":"6a743c9b367d15f4758e4f3f3378ff0fd443708d1c64854e07588ea5331823ae"},
	 * "mac":"410544c8307e3691fda305eb3722d82c3431f212a87daa119a21587d96698b57"}}'
	 * ]

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by mconnelly8** [comment]
Set to 2, but need to investigate further.
