### ISSUE TITLE
contract.at([address]) expect address without '0x' prefix

### ISSUE THREAD

**Issue by DurandA** [ethereum/web3.js#519]
Getting an existing contract using `myContract.at([address])` requires the address without the hex/`0x` prefix.
I think this is inconsistent behavior as the address from a newly created contract contains the `0x` prefix.
```
myContract.new({data: code, gas: 3000000}, function (err, contract) {
    if(contract.address){
        console.log(contract.address); // with 0x prefix
    }
});
```
I also noticed that calling `contractInstance.address` on an existing contract output the address without the `0x` prefix.

**Comment by frozeman** [comment]
The contractInstance.address comes from the receipt and it depends on the node, if it comes with a 0x. This is certainly then wrong on the node. Though please check on the web3. 1.0 beta if its a problem there too.
