### ISSUE TITLE
what is difference between web3.eth.sendTransaction and web3.eth.personal.sendTransaction on Web3.js

### ISSUE THREAD

**Issue by gloomydumber** [ethereum/web3.js#5191]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

I found there are two `sendTransaction` methods on `web3.js (v1.7.4)`.

First one is `web3.eth.sendTransaction`. (https://web3js.readthedocs.io/en/v1.7.4/web3-eth.html#sendtransaction)

The other one is `web3.eth.personal.sendTransaction`. (https://web3js.readthedocs.io/en/v1.7.4/web3-eth-personal.html#sendtransaction)

It seems the latter one has security issue though (use with `web3.eth.personal.unlockAccount`), What is use of first one?

I thought The general way of sending transaction on `web3.js` is below.

1.`web3.eth.signTransaction`
2.`web3.eth.sendSignedTransaction`

then, What is use of `web3.eth.sendTransaction`?

I think Document is not that detail.

**Comment by nikoulai** [comment]
Hey @gloomydumber, thanks for your message.

There are two different questions in your message.

First, regarding `personal` sendTransaction. Taken from the documentation: 

`The web3-eth-personal package allows you to interact with the Ethereum node’s accounts.` So using this sendTransaction you are trying to execute the transaction using one of the accounts in the node.

Regarding the second part, `web3.eth.signTransaction` & `web3.eth.sendSignedTransaction` vs `web3.eth.sendTransaction`.  Internally, `sendTransaction` signs the transaction and maybe is the most used. Signing and sending the transaction if different steps is more flexible. You can use an account to sign the transaction and another to send and pay for the fees etc.

**Comment by gloomydumber** [comment]
@nikoulai wow, thank you for your perfect answer 👍
