### ISSUE TITLE
submit work doc

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

Example for submit work has error, its not array: https://web3js.readthedocs.io/en/v1.7.4/web3-eth.html#id114

Using array as its param : `Error: Invalid number of parameters for "submitWork". Got 1 expected 3!`

**Comment by totgard** [comment]
The same situation if you try to invoke the contract method.

```
args = ['1','1','1']
contract.methods['methodName'](args)
```
Result
```
web3.min.js:22 Uncaught Error: Invalid number of parameters for <methodName>. Got 1 expected 3!
    at Object.InvalidNumberOfParams (web3.min.js:22:368881)
    at y._createTxObject (web3.min.js:22:227981)
    at <anonymous>:1:24
```

But if call method like this:
```
contract.methods['methodName'](arg1, arg2, arg3)
```
Everything works.

But in docs:
```myContract.methods.myMethod([param1[, param2[, ...]]]).send(options[, callback])```
Link to docs: [https://web3js.readthedocs.io/en/v1.7.4/web3-eth-contract.html](https://web3js.readthedocs.io/en/v1.7.4/web3-eth-contract.html#methods-mymethod-send)
