### ISSUE TITLE
Contract events does not support `fromBlock` property

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following two code snippets behaves exactly the same: 

```ts
myContract.events.MyEvent({fromBlock: 0})
```

```ts
myContract.events.MyEvent()
```

### Expected Behavior

If one subscribe for the events with `fromBlock` it should get the past logs with `getPastEvents` and emit those. 

```ts
myContract.events.MyEvent({fromBlock: 0})
```

### Steps to Reproduce

Following snippet should emit the two events which were triggered in the past. 

```ts
myContract.methods.fireStrintEvent('event1'); 
myContract.methods.fireStrintEvent('event2'); 

(await myContract.events.MyEvent({fromBlock: 0})).on('data', console.log));
```

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

This behavior can be implemented with combination of `getPastEvents` inside the event subscriber.

**Comment by Anassabguerbeh** [comment]
Hey
