### ISSUE TITLE
Types for the overloaded ABI functions are not supported

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we have a contract with overloaded methods, the types does not support those. 

```solidity
contract FuncOverload {    
  address owner;    
  
  constructor() public {        
    owner = msg.sender;    
  }    
  
  function transfer(address _to, uint _amount) public returns (bool) {
    return doTransfer(_to, _amount);    
  }    
  function transfer(address _to) public returns (bool) {        
    return doTransfer(_to, 1 ether);
  }
}
```

### Expected Behavior

The type should detect and throw error on compile time, if user pass different number of arguments for overloaded functions. 

### Steps to Reproduce

```ts
await myContract.methods.transer(address).send();
await myContract.methods.transer(address, 10000).send();
```

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

In alpha release of 4.x the the behavior exists but the types does not support. For now use `as any` to bypass this check.

**Comment by mconnelly8** [comment]
Duplicate issue. Keeping #5486
