### ISSUE TITLE
getFeeHistory fails to encode reward percentiles

### ISSUE THREAD

**Issue by lykhonis** [ethereum/web3.js#5224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I call hardhat local network (but the call does not hit RCP endpoint):
```typescript
await web3.eth.getFeeHistory(1, 'latest', [50])
```

Fails with:
```
{code: -32602, message: "'50' must be non-empty string", stack: "Error: '50' must be non-empty string\n    at o (chr…ejhcdkdegadjgmckkodgnoeo/background.js:1:4415397)"}
```

### Expected Behavior

getFeeHistory should return `blocks` containing `baseFeePerGas` and `reward` arrays of values.

### Steps to Reproduce

```typescript
await web3.eth.getFeeHistory(1, 'latest', [50])
```

### Web3.js Version

1.7.4

### Environment

- Operating System: Mac OS
- Browser: Chrome
- Node.js Version: v16.15.0
- NPM Version: 8.5.5
- Yarn Version: 1.22.19

**Comment by jdevcs** [comment]
Tested 1.7.4 and this bug is not reproducible :

` web3.eth.getFeeHistory(1, 'latest', [50]).then(console.log);`
 
 results:
 
`{
  baseFeePerGas: [ '0x7', '0x7', '0x7', '0x7', '0x7' ],
  gasUsedRatio: [
    0.03449083333333333,
    0.0033333333333333335,
    0.2802569,
    0.054526733333333334
  ],
  oldestBlock: '0xbfd1ad',
  reward: [
    [ '0x58e2d6ae', '0x58e2d6ae', '0x9502f8f9' ],
    [ '0x58e2d6ae', '0x58e2d6ae', '0x58e2d6ae' ],
    [ '0x58e2d6ae', '0x59682f00', '0x9502f900' ],
    [ '0x58e2d6ae', '0x9502f900', '0x9502f900' ]
  ]
}`

**Comment by lykhonis** [comment]
Is this RPC endpoint related? I am trying again, but still same problem:
```
{code: -32602, message: "'50' must be non-empty string", stack: "Error: '50' must be non-empty string\n    at o (chr…ejhcdkdegadjgmckkodgnoeo/background.js:1:4415397)"}
```

**Comment by lykhonis** [comment]
Looks like some sort of environment setup. I have other project, it works fine.
