### ISSUE TITLE
get_price plugin

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#5233]
**Scope of Work:** Add “Get Price” method to web3.eth API for pulling Chainlink prices

**Tasks:**
Add web3.eth.get_price method to web3.eth API for pulling chainlink prices (name just a placeholder, Chainsafe’s discretion to select)
Update the documentation, test, and code comments as necessary

**Deliverable:**
Using the API, developers will be able to get price feed data by using the existing patterns. For example, using ETH/USD Feed only requires the user pass the contract address:

>>> web3.eth.get_price('0x9326BFA02ADD2366b30bacB125260Af641031331')
303573902829

**Comment by ghost** [comment]
@mconnelly8 Why not add an API method to get 1inch's [spot price aggregator](https://github.com/1inch/spot-price-aggregator) contract as well? I have something similar here https://github.com/ayanamitech/1inch-spot-price-sdk.

**Comment by mconnelly8** [comment]
Hey @ayanamidev, this is our first step in adding something like this.  Down the road this could open up to more possibilities.
