### ISSUE TITLE
Allow sendTransaction fromAddress to be omitted

### ISSUE THREAD

**Issue by kumavis** [ethereum/web3.js#524]
In some cases, the dapp need not care about the sender. The user-agent  (mist/metamask/etc) can auto-fill, or allow the user to select a sender. If not specifying a sender is a problem, we still don't need to error at the web3.js level, we can allow the error to come from the RPC endpoint.

**Comment by kumavis** [comment]
related: https://github.com/ethereum/web3.js/issues/319

**Comment by nivida** [comment]
Closed because it should throw an error on the client and not from the connected node. I think we should do as many as possible on the client.
