### ISSUE TITLE
ESM and CJS builds

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5241]
We should have support of `ESM` builds along with `CJS` in future 4.x ( beta TBD). 
Currently we have `CJS` build in 4.x and should be offering separate `ESM` and `CJS` builds.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5241?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain @nikoulai @spacesailor24
