### ISSUE TITLE
Web3.eth.subscribe syncing test

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5242]
Before start check [this PR](https://github.com/ChainSafe/web3.js/pull/5005)

System tests for:

## Web3.eth.subscribe

- [x] subscribe(“syncing”)

#### Min Platform Requirements for 4.x Alpha:
- Node: v14, v16
- Browsers: Firefox, Brave
- Eth Clients: Geth, Ganache

More details are in [Epic](https://github.com/ChainSafe/web3.js/issues/4711)

related to [#4990](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/chainsafe/web3.js/4990)

**Comment by mconnelly8** [comment]
#5004 needs to be completed before this can be estimated.
