### ISSUE TITLE
4.x RC Testing Infrastructure

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5246]
### Description  

This issue has requirements for **4.x beta tests infrastructure setup**. 

- [ ] https://github.com/ChainSafe/web3.js/issues/5290
- [ ] https://github.com/ChainSafe/web3.js/issues/5291
- [ ] https://github.com/ChainSafe/web3.js/issues/5292

**Comment by mconnelly8** [comment]
Need to decompose into multiple tasks
