### ISSUE TITLE
web3 tree shaking support and document

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5248]
[ts-loader](https://github.com/ChainSafe/web3.js/blob/25bcd32e625a021ade8a415407749ada2915d8b8/webpack.base.config.js#L41) uses tsc, the TypeScript compiler, and relies on your tsconfig.json configuration. 

If `module` is set to "[CommonJS](https://github.com/ChainSafe/web3.js/blob/25bcd32e625a021ade8a415407749ada2915d8b8/tsconfig.json#L6)", webpack won't be able to tree-shake code.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5248?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nazarhussain @nikoulai @spacesailor24

**Comment by jdevcs** [comment]
Create a sample application and see web3 treeshaking support , also document how users can tree shake.
