### ISSUE TITLE
Webpack - types definition bundle for web3.min.js web build

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5249]
Create type definition bundle for web3.js web build ( via webpack ), 
its for supporting other projects that use our lib and will have type intellisense with it

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5249?planning-poker) with ZenHub @jdevcs @nazarhussain @avkos @Muhammad-Altabba

**Comment by Muhammad-Altabba** [comment]
To look at: https://www.npmjs.com/package/declaration-bundler-webpack-plugin thanks to @jdevcs.

**Comment by jdevcs** [comment]
discussed in team its not required, its experimental feature.
