### ISSUE TITLE
web3.utils.toBN vs new web3.utils.BN

### ISSUE THREAD

**Issue by CaledoniaProject** [ethereum/web3.js#5257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

From [the document][1] toBN is safer than new BN. However, given the same hex hash string, it results in something different:

```
(new web3.utils.BN('0x149e7b36b314b81fbe1762060fcae0f43be82f1251166a61fc7669e7c236c4bf')).toString()
// results in: '331504813713151826241762061631415442483512511670626276704822372525'

web3.utils.toBN('0x149e7b36b314b81fbe1762060fcae0f43be82f1251166a61fc7669e7c236c4bf').toString()
// results in: '9326269197397511364330713577831447135626556432227477146325167069213775807679'
```

Now I'm wondering which one should I use for hex string?

**PS**

For non-hex string, it creates the same value:

```
(new web3.utils.BN('57896044618658097711785492504343953926634992332820282019728792003956564819968')).toString()
// results in: '57896044618658097711785492504343953926634992332820282019728792003956564819968'

web3.utils.toBN('57896044618658097711785492504343953926634992332820282019728792003956564819968').toString()
// results in: '57896044618658097711785492504343953926634992332820282019728792003956564819968'
```

  [1]: https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#utils-tobn

### Examples/References

Correct the document

**Comment by Muhammad-Altabba** [comment]
Hello @CaledoniaProject,
I checked the code scenario and both gave me `9326269197397511364330713577831447135626556432227477146325167069213775807679`.
Here you can check the code: 
https://codesandbox.io/s/hardcore-glitter-q5rsx3?file=/index.ts


I would close the issue for now.  Feel free to reopen it and provide a sample to reproduce the issue if you still face it. And be sure to use the latest version (I used in the provided sample 1.7.5).

**Comment by CaledoniaProject** [comment]
@Muhammad-Altabba Try     "web3": "^1.7.0",

**Comment by CaledoniaProject** [comment]
@Muhammad-Altabba I would like to see if this is a bug or not

**Comment by Muhammad-Altabba** [comment]
Yes, I now tried with version 1.7.0 (using the link I provided, you can change the package version and try), and yes the bug was there. Kindly update to the latest version (version 1.7.4 and 1.7.5 does not have this issue). Or just use `web3.utils.toBN` with any version.
Thanks for opening an issue. And I hope it is all clear now.
All the best,

**Comment by CaledoniaProject** [comment]
Yes, it's cleared by now. I'll do the upgrade, thanks!
