### ISSUE TITLE
4.0.0-alpha.0 Blackbox tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5261]
Add initial simple Blackbox tests for web3.js imports using web3 node module and minified build.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5261?planning-poker) with ZenHub @jdevcs @nazarhussain @spacesailor24 @luu-alex @Muhammad-Altabba @nikoulai @avkos
