### ISSUE TITLE
Improve the types interfaces for `web3-types` packages

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5268]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

We created a package `web3-types` package which consists of all reuseable and shared types from different packages. Some of the types defined in that package are redundant. More specifically the `*API` types are redundant and been defined this way to have exact match with the `Eth Specification`. 

e.g. There is a type `TransactionReceipt` and `TransactionReceiptAPI`. The difference between both is the use of fixed versus union types. Means use of `Unit` versus `Numbers`. 

We can look closely in each type and can optimize the declarations further.

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5268?planning-poker) with ZenHub @avkos @jdevcs @Muhammad-Altabba @nazarhussain

**Comment by mconnelly8** [comment]
Per the 8/11/22 meeting, we will add sub-tasks to this for the list of types to test.

**Comment by luu-alex** [comment]
list of duplicates

export interface TransactionReceiptAPI {
    readonly transactionHash: HexString32Bytes;
    readonly transactionIndex: Uint;
    readonly blockHash: HexString32Bytes;
    readonly blockNumber: Uint;
    readonly from: Address;
    readonly to: Address;
    readonly cumulativeGasUsed: Uint;
    readonly gasUsed: Uint;
    readonly contractAddress?: Address;
    readonly logs: LogAPI[];
    readonly logsBloom: HexString256Bytes;
    readonly root: HexString32Bytes;
    readonly status: '0x1' | '0x0';
    readonly effectiveGasPrice: Uint;
}


export interface TransactionReceipt {
    readonly transactionHash: Bytes;
    readonly transactionIndex: Numbers;
    readonly blockHash: Bytes;
    readonly blockNumber: Numbers;
    readonly from: Address;
    readonly to: Address;
    readonly cumulativeGasUsed: Numbers;
    readonly gasUsed: Numbers;
    readonly effectiveGasPrice?: Numbers;
    readonly contractAddress?: Address;
    readonly logs: Log[];
    readonly logsBloom: Bytes;
    readonly root: Bytes;
    readonly status: Numbers;
    readonly type?: Numbers;
}

export type TransactionInfoAPI = TransactionSignedAPI & {
    readonly blockHash?: HexString32Bytes;
    readonly blockNumber?: Uint;
    readonly from: Address;
    readonly hash: HexString32Bytes;
    readonly transactionIndex?: Uint;
};

export interface TransactionInfo extends Transaction {
    readonly blockHash?: Bytes;
    readonly blockNumber?: Numbers;
    readonly from: Address;
    readonly hash: Bytes;
    readonly transactionIndex?: Numbers;
}


export interface Block {
    readonly parentHash: Bytes;
    readonly sha3Uncles: Bytes;
    readonly miner: Bytes;
    readonly stateRoot: Bytes;
    readonly transactionsRoot: Bytes;
    readonly receiptsRoot: Bytes;
    readonly logsBloom?: Bytes;
    readonly difficulty?: Numbers;
    readonly number: Numbers;
    readonly gasLimit: Numbers;
    readonly gasUsed: Numbers;
    readonly timestamp: Numbers;
    readonly extraData: Bytes;
    readonly mixHash: Bytes;
    readonly nonce: Numbers;
    readonly totalDifficulty: Numbers;
    readonly baseFeePerGas?: Numbers;
    readonly size: Numbers;
    readonly transactions: TransactionHash[] | TransactionInfo[];
    readonly uncles: Uncles;
    readonly hash?: Bytes;
}
export interface BlockAPI {
    readonly parentHash: HexString32Bytes;
    readonly sha3Uncles: HexString32Bytes;
    readonly miner: HexString;
    readonly stateRoot: HexString32Bytes;
    readonly transactionsRoot: HexString32Bytes;
    readonly receiptsRoot: HexString32Bytes;
    readonly logsBloom?: HexString256Bytes;
    readonly difficulty?: Uint;
    readonly number?: Uint;
    readonly gasLimit: Uint;
    readonly gasUsed: Uint;
    readonly timestamp: Uint;
    readonly extraData: HexStringBytes;
    readonly mixHash: HexString32Bytes;
    readonly nonce?: Uint;
    readonly totalDifficulty: Uint;
    readonly baseFeePerGas?: Uint;
    readonly size: Uint;
    readonly transactions: TransactionHash[] | TransactionInfoAPI[];
    readonly uncles: Uncles;
    readonly hash?: HexString32Bytes;
}

export interface Log {
    readonly removed?: boolean;
    readonly logIndex?: Numbers;
    readonly transactionIndex?: Numbers;
    readonly transactionHash?: Bytes;
    readonly blockHash?: Bytes;
    readonly blockNumber?: Numbers;
    readonly address?: Address;
    readonly data?: Bytes;
    readonly topics?: Bytes[];
    readonly id?: string;
}

export interface LogAPI {
    readonly removed?: boolean;
    readonly logIndex?: Uint;
    readonly transactionIndex?: Uint;
    readonly transactionHash?: HexString32Bytes;
    readonly blockHash?: HexString32Bytes;
    readonly blockNumber?: Uint;
    readonly address?: Address;
    readonly data?: HexStringBytes;
    readonly topics?: Topic | Topic[];
}

export interface TransactionReceipt {
    readonly transactionHash: Bytes;
    readonly transactionIndex: Numbers;
    readonly blockHash: Bytes;
    readonly blockNumber: Numbers;
    readonly from: Address;
    readonly to: Address;
    readonly cumulativeGasUsed: Numbers;
    readonly gasUsed: Numbers;
    readonly effectiveGasPrice?: Numbers;
    readonly contractAddress?: Address;
    readonly logs: Log[];
    readonly logsBloom: Bytes;
    readonly root: Bytes;
    readonly status: Numbers;
    readonly type?: Numbers;
}

export interface TransactionReceiptAPI {
    readonly transactionHash: HexString32Bytes;
    readonly transactionIndex: Uint;
    readonly blockHash: HexString32Bytes;
    readonly blockNumber: Uint;
    readonly from: Address;
    readonly to: Address;
    readonly cumulativeGasUsed: Uint;
    readonly gasUsed: Uint;
    readonly contractAddress?: Address;
    readonly logs: LogAPI[];
    readonly logsBloom: HexString256Bytes;
    readonly root: HexString32Bytes;
    readonly status: '0x1' | '0x0';
    readonly effectiveGasPrice: Uint;
}

export interface FeeHistoryResultAPI {
    readonly oldestBlock: Uint;
    readonly baseFeePerGas: Uint;
    readonly reward: number[][];
}

export interface FeeHistory {
    readonly oldestBlock: Numbers;
    readonly baseFeePerGas: Numbers;
    readonly reward: Numbers[][];
    readonly gasUsedRatio: Numbers;
}
