### ISSUE TITLE
Switch to different linting tool.

### ISSUE THREAD

**Issue by NodeGuy** [ethereum/web3.js#528]
There's extraneous whitespace floating around the code which makes diffs harder to read.

JSHint used to have an flag for warning about extra whitespace but it was removed.  Let's switch to a modern linter such as [ESLint](http://eslint.org/) or even better adopt [JavaScript Standard Style](http://standardjs.com/) instead.

**Comment by nivida** [comment]
I switched to eslint and prettier as you can see here: #2000 :-)

**Comment by vibern0** [comment]
> I switched to eslint and prettier as you can see here: #2000 :-)

Then, should this be moved to **done**?
