### ISSUE TITLE
Crashes in Service Worker: XHR2 is not a constructor

### ISSUE THREAD

**Issue by Jack-Works** [ethereum/web3.js#5281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5390719/180977446-6dd2a0dd-c3c9-43c6-a794-dfd9764d7345.png)

![Uploading image.png…]()

### Expected Behavior

Working.

### Steps to Reproduce

Run web3.js in worker.

### Web3.js Version

1.7.4

### Anything Else?

Should use fetch if possible.

**Comment by Jack-Works** [comment]
Note: it try to use `xhr2-cookies` as a fallback, but it is a Node module, not work on Worker either. We've patched `xhr2-cookies` to return empty.

**Comment by Muhammad-Altabba** [comment]
Could you please point to a minimal repository or make new one fast on codesandbox.io or similar cloud IDE, so we can help you more?
Thanks,

**Comment by Jack-Works** [comment]
I tried to reproduce this and found XMLHttpRequest is defined in a Worker, but not in a Service Worker.

Our app runs in a service worker (Chrome extension), where XMLHttpRequest is undefined.

The code use `typeof XMLHttpRequest === 'undefined'` to detect if the runtime is NodeJS, which is incorrect on our platform. Is there anything else you can use? For example, `typeof self === 'undefined'`.

![image](https://user-images.githubusercontent.com/5390719/182997331-dcc3decd-072d-41bf-b5de-fb877da856bc.png)

**Comment by Jack-Works** [comment]
I guess this is fixed by #5085?
