### ISSUE TITLE
Web3Eth Doc Improvements

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5295]
- We should implement a disclaimer as mentioned [here](https://github.com/ChainSafe/web3.js/pull/5251#discussion_r932016753) that notifies the user that methods exported from `rpc_method_wrappers.ts` are expected to not be used by most users
- We should investigate how to use `@inheritDoc` to avoid duplicate code between `Web3Eth` and `rpc_method_wrappers` as mentioned [here](https://github.com/ChainSafe/web3.js/pull/5251#discussion_r929883330)

**Comment by spacesailor24** [comment]
It doesn't appear that `inheritDoc` from ts-doc is going to work with Docusaurus. An alternative is maybe we do this:

```typescript
/**
 * Visit {@link Web3Eth.getProtocolVersion} for the documentation on this function.
 * @param web3Context ({@link Web3Context}) Web3 configuration object that contains things such as the provider, request manager, wallet, etc.
 */
export const getProtocolVersion = async (web3Context: Web3Context<EthExecutionAPI>) =>
	ethRpcMethods.getProtocolVersion(web3Context.requestManager);
```

Which yields:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/20375610/234790387-8dbc9982-1b6e-4c90-a9a1-1f48b7a27ce5.png">

And this is how it is currently (a duplication of `api/web3-eth/class/Web3Eth#getProtocolVersion`

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/20375610/234790778-a20aace1-0310-44b3-ad49-ec2d75423aab.png">

**Comment by Spacesai1or** [comment]
I got `{@linkcode }` to work and it looks like:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/20375610/234922487-38c5d0eb-e3d8-473e-bba9-553846651535.png">

**Comment by Spacesai1or** [comment]
```typescript
/**
 * @inheritDoc Web3Eth.getProtocolVersion
 */
```

Seems to work as well, but doesn't seem to support inheriting from a different file
