### ISSUE TITLE
Review and clean up 4.x Documentation

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#5298]
There is some inconsistency with the 4.x documentation

Review 4.x documentation and make necessary updates for consistency and improvements

**Comment by jdevcs** [comment]
- [ ] `Guides` link in footer doesn't work, it needs to be fixed

- [ ] Point following button on home page to empty page with "Tutorials coming soon" message in it and change title of this button
![image](https://user-images.githubusercontent.com/86780488/182355821-440d29f2-5e74-4802-a2c1-b5f5f8425871.png)
