### ISSUE TITLE
Duplication between .on("data") and .on("changed")

### ISSUE THREAD

**Issue by NikoKodzhabashev** [ethereum/web3.js#5299]
### This is not a Bug Report, Feature Request, or related to Documentation

- [x] I have searched the existing issues

### Is there an existing issue for this?

- [x] I have searched the existing issues

### What's up?

Hello. Hope you are doing well. I have noticed that when reorg has happened "changed" and "data" callbacks are invoked with duplicated data and the only difference is in the "removed" property:
"data -> removed: false", "changed -> removed: true".

So I was wondering if this is intentional. 

P.S: In the end, I am getting back 3x data: 2x in "data" callback and 1x in "changed"

**Comment by nikoulai** [comment]
Hey @NikoKodzhabashev Thanks for reaching out!
Could you please provide an example  of this?
