### ISSUE TITLE
E2E tests for Injected providers

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5309]
Add E2E tests for 3rd party Injected providers

- [x] For e2e testing few requests via Eth package with injected provider 
       - For testing providers that are in compliance with JSON RPC 2.0 Specs
       - For testing providers that are NOT in compliance with JSON RPC 2.0 Specs
       
List of providers: ( Ganache provider , IN3 Provider, ... TBD )

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5309?planning-poker) with ZenHub @avkos @jdevcs @Muhammad-Altabba @nazarhussain
