### ISSUE TITLE
adding a way to cancel a tx before it is signed/broadcasted

### ISSUE THREAD

**Issue by wighawag** [ethereum/web3.js#532]
In the current web3 api, there is no way a dapp can cancel a tx. In the case where the node is unlocked, there is actually no way to stop it, but for many web3 client, teh transaction require user ' approval and such approval has no time limit.

I have a use case where tx validity are time dependent and while the smart contract will reject such transaction, it will incur a gas cost to the user. 

If the web3 api were to rovide a mechanism by which a dapp could cancel a transaction. my dapp could abort the transaction before it is actually signed/broadcasted .

**Comment by nivida** [comment]
I think you could "out-gassing" the transaction as described here: https://ethereum.stackexchange.com/questions/31298/is-it-possible-to-cancel-a-transaction. But I don't think we will implement a method for "cancling" a transaction in web3 🤔

**Comment by wighawag** [comment]
Thanks for looking at the issue,

The proposal here was not to cancel a tx after it has been broadcasted (as you say this is not really possible without incurring gas cost) but **before** it is approved by the user (so while the signer is waiting for the user to approve).

This was needed for my application which was expecting user to approve in the next minute of showing the approval popup as if they took longer, the tx will likely fails (time dependent)

**Comment by nivida** [comment]
Oh sorry I got you wrong. I will overthink it and maybe implement it in a future version of web3. 🤔
