### ISSUE TITLE
Eth Testnet  - 4.x RC Testing Infrastructure

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5348]
4.x Beta Testing Infrastructure

### Description  

- **eth live NW tests** 
- [x] Tests on at least 1 testnet via Infura (`sepolia network` )
     - [x] read calls (block, account state, balance ..etc)
     - [x] and also setup tests for functions doing changes to be mined in blocks (run once with pre funded account on testnet)
          - [x] value transfer tx, 
          - [x] contract deployment tx, 
          - [x] contract function tx, 
          - [x] 0x0, 0x1 and 0x2 tx
( create a separate test file and use pre funded private key from env variable for live tests on sepolia testnet , do not integrate this in github CI actions)

- [x] Read calls on `mainnet` via Infura ( TBD )

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/5348?planning-poker) with Zenhub @avkos @jdevcs @luu-alex @Muhammad-Altabba @nazarhussain @nikoulai @spacesailor24
