### ISSUE TITLE
Filtering events by arguments not working

### ISSUE THREAD

**Issue by andrejc** [ethereum/web3.js#535]
I have an event in my contract like this:

`event SendEmail(address indexed fromAddress, address indexed toAddress, string ipfsHash);`

Then from web3 I try to watch only those events where fromAddress matches some specific address:

`var sendEvent = emailer.SendEmail({fromAddress: eth.accounts[0]},{fromBlock: 0, toBlock: 'latest'});`

However, when I call watch() on the sendEvent object, I get all corresponding events, not only those where fromAddress is matched.

**Comment by JackBekket** [comment]
Have same issue

**Comment by JackBekket** [comment]
contract event like
```
event LogEvent(uint indexed lockId, string dataInfo, uint indexed version, uint16 eventType, address indexed sender, uint payment);
```
from web3 I try to watch like this:
```
event=contract.LogEvent({eventType: 1},{fromBlock: 0, toBlock: 'latest'});
```
And it's return me Logs with all status but not only with event type '1'.

**Comment by andrejc** [comment]
The problem for me was actually that the parameter I was filtering by was not labeled as "indexed" in the deployed contract. 

This seems to be the case in your code as well, so adding "indexed" before eventType should fix it. You will however have to unindex one of the 3 other parameters because there is a limit of maximum 3 indexed arguments per event.

**Comment by kraeki** [comment]
I have the same issue with a indexed boolean.
My event looks like this: 
```
event OnRent(bool indexed error, address indexed renter, uint start, uint end, string msg);
```
Now if I want to filter for the first parameter `bool indexed error` I observe a strange behaviour. If I filter with `{error: true}` I get the correct events, but if I filter with `{error: false}` I always get all events and not the filtered list.

```
// returns the correct filtered list of events
filterForNewRents = rentable.OnRent({error: true, {fromBlock: 0, toBlock: 'latest'})                                                                            

// returns always all events
filterForNewRents = rentable.OnRent({error: false, {fromBlock: 0, toBlock: 'latest'})                                                                            
```

Any ideas on this?

**Comment by almindor** [comment]
Seems I have the same issue. Specifying anything in the first argument (object, array etc.) doesn't seem to change the returned filter object in any way and I get all the events.

I have the argument indexed, double checked on the compiled JSON interface too.

**Comment by almindor** [comment]
@oney why is this a requirement? Is it a bug?

**Comment by oney** [comment]
@almindor It's not a requirement. Yes, I think that is a bug.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.

**Comment by RudrikaFichadiya** [comment]
> The problem for me was actually that the parameter I was filtering by was not labeled as "indexed" in the deployed contract.
> 
> This seems to be the case in your code as well, so adding "indexed" before eventType should fix it. You will however have to unindex one of the 3 other parameters because there is a limit of maximum 3 indexed arguments per event.


@andrejc  already have indexed before that parameter still not able to get events based on filters.

**Comment by RudrikaFichadiya** [comment]
@oney contract ABI has indexed: true but still not working.

**Comment by JesseAbram** [comment]
Hey having the same issue here when trying to filter events by boolean, we moved to a uint like 0 false 1 true and it seem to have fixed itself, so it may be an issue with filtering by boolean

**Comment by anisurrahman072** [comment]
Hi, geeks this is very simple to filter All Indexed Logs.

✅ In solidity, this is my Indexed Event 👇
<img width="696" alt="image" src="https://user-images.githubusercontent.com/40535268/213352707-ebdff335-116c-4aff-a526-4a4a60acf108.png">

✅ Now from my Node.js App using Web3 by contract instance 👇
<img width="683" alt="image" src="https://user-images.githubusercontent.com/40535268/213352981-85062977-b304-42db-9972-7efa54e5c91e.png">

✅ Output: Printed all events emitted before 🎉
