### ISSUE TITLE
IPC provider / second callback for contract.new triggers internal error.

### ISSUE THREAD

**Issue by Niklas345** [ethereum/web3.js#536]
Hallo,

During development of a DAPP, we encountered the following error, which is, for this code, only problematic when using an async. IPC call for contract.new.

The first time the callback is executed properly, without an error. The second time, the callback is executed - when the contract is mined, which is happening - the following error get's thrown:
`Error: You tried to send "eth_uninstallFilter" synchronously. Synchronous requests are not supported by the IPC provider.`

The stacktrace is attached as a file.

Replication of the error:
1) Create a new contract via IPC: `var contract = IPCProvider.eth.contract(this.projectABI);`
2) Try to instantia the contract: `contract.new(..., callback)`
3) When callback is executed the second time, the error occurs.

After debugging and going through parts of web3js source code, we believe this error is withint web3js.

[stacktrace.txt](https://github.com/ethereum/web3.js/files/657304/stacktrace.txt)

**Comment by subhog** [comment]
The bug is gone in v. 0.18.0.
