### ISSUE TITLE
ahhh i think i found your issue, this is a mismatch issue with the angular-cli-files default `browser.js` settings and is something you have to fix to get `web3` to work on angular apps.

### ISSUE THREAD

**Issue by araaan12** [ethereum/web3.js#5368]
ahhh i think i found your issue, this is a mismatch issue with the angular-cli-files default `browser.js` settings and is something you have to fix to get `web3` to work on angular apps. 

if you create a file called `patch.js` in the root of the angular app

```
const fs = require('fs');
const f = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js';

fs.readFile(f, 'utf8', function (err, data) {
    if (err) {
        return console.log(err);
    }
    var result = data.replace(/node: false/g, 'node: {crypto: true, stream: true}');

    fs.writeFile(f, result, 'utf8', function (err) {
        if (err) return console.log(err);
    });
});
```

then in your `package.json` under `scripts` add ` "postinstall": "node patch.js"`

run `npm install` again and then `ng build` will all work and you shouldn't have anymore issues. 

This is because we have to replace the `node:false` in the `/angular-cli-files/models/webpack-configs/browser.js` with `'node: {crypto: true, stream: true}'` to allow `web3` to work with angular (as they enforce `node: false`.)

I just did that and boom worked on your repo: 

![image](https://user-images.githubusercontent.com/18472422/51907783-c574c280-23bf-11e9-8088-1f9ce907c34f.png)

I will look further into this and try to find a way we can fix this within the install of `web3` as its pretty annoying to have to add the above and hard to know how to sort if you not came across it before. 

Cheers @RohanKapurDEV

_Originally posted by @joshstevens19 in https://github.com/ChainSafe/web3.js/issues/2260#issuecomment-458519127_

**Comment by luu-alex** [comment]
hey, web3js should work with angular apps now using the 1.8 version. If u find an issue feel free to reopen this
