### ISSUE TITLE
Responses get mixed up due to conflicting payload IDs (v 4.x)

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Discuss the issue https://github.com/ChainSafe/web3.js/issues/5327 at v4.x

### Expected Behavior

To have a unique number for the Json RPC message id like in https://github.com/ChainSafe/web3.js/pull/5371.
However, version 1.x it was better to not change the type of `jsonrpc` `id` from being a number to being a string or a UUID
But, for v4.x, I suggest one of the following instead of an incremental value:
- A UUID with will ensure being unique.
- Or using a pattern like [random-word]-[incremental-counter] if it is preferable to have an incremental part for easy tracking.

### Steps to Reproduce

As in https://github.com/ChainSafe/web3.js/issues/5327

### Web3.js Version

4.x

**Comment by ravenflores** [comment]
same problem I got one do u have solutions ?

 erver\node_modules\web3-providers-ws\lib\index.js:260
        id = payload[0].id;

**Comment by Muhammad-Altabba** [comment]
Thanks @ravenflores ,
The changes are done now for 1.x and it will be available in the next release. And this issue has been addressed here and is in discussion for version 4.x.

**Comment by jdevcs** [comment]
Using uuid will be good fix for this problem, optionally we can also allow user to control assigning id functionality as additional feature in 4.x as well.
