### ISSUE TITLE
`gasLimit` vs `gas`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5387]
Originally brought up [here](https://github.com/ChainSafe/web3.js/pull/5312#issue-1328068259) in PR #5312, there are instances where our library will return `gasLimit` and other times when it returns `gas` within transaction objects. This issue tracks the decision and implementation on how the library should handle the use of `gasLimit` vs `gas`

**Comment by Muhammad-Altabba** [comment]
https://github.com/ethereum/execution-apis/issues/283
Thanks @jdevcs

**Comment by jdevcs** [comment]
PR merged so closing issue,
