### ISSUE TITLE
Error: Maximum number of reconnect attempts reached!

### ISSUE THREAD

**Issue by ravenflores** [ethereum/web3.js#5389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im running a server to scan blocks transaction reciepts and for about few hrs it stopped and show like this 
![image](https://user-images.githubusercontent.com/66240114/187165266-d4aaae21-3a45-45ce-a902-99a70d4c22e8.png)

### Expected Behavior

it will run smoothly

### Steps to Reproduce

   
   
   **I tried this** 
   
   var options = {
  timeout: 30000,
  clientConfig: {
    maxReceivedFrameSize: 100000000,
    maxReceivedMessageSize: 100000000,
  },
  reconnect: {
    auto: true,
    delay: 5000, 
    maxAttempts: 15,
    onTimeout: false,
  },
};
**also this**

var options = {
  timeout: 30000,
  clientConfig: {
    maxReceivedFrameSize: 100000000,
    maxReceivedMessageSize: 100000000,
  },
     reconnect: {
        auto: true,
        delay: 1000, // ms
        onTimeout: false,
        maxAttempts: 1
      }
};

    
    
    
    
    
    **this is where error shows after  few hrs**
    
    if(arg.length == 0) {
       console.log("block has no tx")
    } else {
     
      const web3s = new Web3s(new Web3.providers.WebsocketProvider(url, options));
      const batch = new web3s.BatchRequest();  
      arg.forEach((res, index) => { 
          
        
        batch.add( web3s.eth.getTransaction.request(res,(err, result) =>  {
             
          if(!err) {

            result['input'] = result['input'].slice(0,10)
             const input = result['input']
            //  console.log(input.slice(0,10))
             if(input.slice(0,4) == '0x60') {
              console.log(index)

### Web3.js Version

3.0.0

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by luu-alex** [comment]
hey were u able to try this using the 1.8x version? 3.0.0 is currently deprecated
