### ISSUE TITLE
Please add examples that are compatible with go-ethereum CLI client

### ISSUE THREAD

**Issue by drcode** [ethereum/web3.js#54]
Hi, I detailed the changes needed and implemented them in some gists in this forum post: http://forum.ethereum.org/discussion/1784/my-working-steps-go-ethereum-cli-json-rpc-chrome-browser-etherum-js-solidity#latest

...just wanted to share them here in case it saves you guys some effort.

**Comment by debris** [comment]
[event_int example](https://github.com/ethereum/web3.js/blob/master/example/event_inc.html) should be compatible... and eveything else also. We unified go && cpp JSONRPC interfaces. And everything that works in one client and does not in another is an issue and should be reported :)
