### ISSUE TITLE
Add support for ENS name resolution wherever addresses are expected

### ISSUE THREAD

**Issue by Arachnid** [ethereum/web3.js#540]
ENS deployment on Mainnet is coming soon, and it'd be awesome if web3 supported transparently resolving names any place an address is expected - for instance, `myContract.at('foo.eth')`.

An ENS library is already available here: https://www.npmjs.com/package/ethereum-ens

**Comment by frozeman** [comment]
The only problem is that web3.js has to be aware of the network its on. And therefore needs to make async calls on init to determine the network, which is not ideal.

Will have to think about that how to solve that.

**Comment by Arachnid** [comment]
Can it simply have a default address for the registry, and optionally accept an address to override the default?

**Comment by nivida** [comment]
I'll add full support of ENS as soon as possible. Currently we have only the ENS module and I will add ENS support for all from or to properties/arguments too.
