### ISSUE TITLE
Tests coverage

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5400]
- [ ] Some packages % Lines test coverage is <80% push coverage to 80%+

**Comment by jdevcs** [comment]
% Lines coverage unit testing

**web3                    0**
web3-core               82.2
web3-errors             95.68
web3-eth                83.6
web3-eth-abi            88.15
web3-eth-accounts       88.46
**web3-eth-contract       31.92**
**web3-eth-ens            29.82**
web3-eth-iban           90.47
web3-eth-personal       100
web3-net                100
web3-providers-http     100
**web3-providers-ipc      30.61
web3-providers-ws       50.75**
web3-types              NA
**web3-utils              72.87
web3-validator          78.91**

**Comment by jdevcs** [comment]
Coverage update:

**web3 0**
web3-core 82.32
web3-errors 94.15
**web3-eth 74.96**
**web3-eth-abi 79.14**
web3-eth-accounts 88.55
**web3-eth-contract 75.22**
web3-eth-ens  98.82
web3-eth-iban 90.47
web3-eth-personal 100
web3-net 100
web3-providers-http 100
**web3-providers-ipc 29.41**
**web3-providers-ws  50.75**
web3-rpc-methods 88.88
web3-types NA
web3-utils 83.44
web3-validator 91.82

**Comment by mconnelly8** [comment]
Need to update coverage %

**Comment by jdevcs** [comment]
Hi Mike, Once https://github.com/web3/web3.js/pull/5799 PR is merged we will have coverage checks available automatically in CI.
