### ISSUE TITLE
Generic Type for web3-contract `methods`

### ISSUE THREAD

**Issue by rotexhawk** [ethereum/web3.js#5424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

Can we populate the types for the `method` object based on the type of abi provided when the contract is initialized or pass it the `AbiItem` type.  

A simple solution is to probably encode the types for the standard methods. So a Union of `StandardMethods & any` 

### Use Cases

This will be a big help to the newcomers like me. Took me a long time to figure out what functions were accessible in this object and what parameters they expected. 

### Are you willing to implement this feature?

- [ ] Yes

**Comment by Spacesai1or** [comment]
Hey @rotexhawk, just wanted to mention that this will be a feature of the rewrite of the library `v4.x`; we probably won't be adding this feature to `v1.x`

**Comment by rotexhawk** [comment]
thanks for the updated. Excited for the v4 version.
