### ISSUE TITLE
web3.eth.getTransactionReceipt() fails for particular transaction

### ISSUE THREAD

**Issue by SaulMoonves** [ethereum/web3.js#5432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Block: 13307440
Transaction: 0x2c9931793876db33b1a9aad123ad4921dfb9cd5e59dbb78ce78f277759587115

calling getTransactionReceipt for this transaction fails with: "Error: Number can only safely store up to 53 bits"

### Expected Behavior

transaction receipt object

### Steps to Reproduce

await web3.eth.getTransactionReceipt('0x2c9931793876db33b1a9aad123ad4921dfb9cd5e59dbb78ce78f277759587115')

### Web3.js Version

1.7.5

### Environment

- Operating System: Ubuntu 20.04
- Node.js Version: v16.16.0
- NPM Version: 8.11.0

### Anything Else?

The transaction fee paid was over 7,000ETH, that is probably what's causing this.

**Comment by jdevcs** [comment]
@SaulMoonves 

you can explicitly specify to use hex encoding and it will not throw this error:

```
web3.eth.getTransactionReceipt('0x2c9931793876db33b1a9aad123ad4921dfb9cd5e59dbb78ce78f277759587115','hex')
.then(console.log);
```
