### ISSUE TITLE
getting Uncaught (in promise) Error: invalid BigNumber when calling SC method from react

### ISSUE THREAD

**Issue by ashish077** [ethereum/web3.js#5436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting the following error when hitting metamask from react app for a smart contract method. The peculiar thing about this error is it is working fine in few system and in few it is failing with the below error. I am also mentioning the method for which it is giving the error. Errors have only been observed in mac so far.
```
index.ts:261 Uncaught (in promise) Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    at e.value (index.ts:261:28)
    at e.value (index.ts:273:20)
    at e.value (index.ts:277:21)
    at Function.value (bignumber.ts:238:27)
    at Function.value (bignumber.ts:250:30)
    at a.value (number.ts:25:27)
    at array.ts:71:19
    at Array.forEach (<anonymous>)
    at x (array.ts:54:12)
    at a.value (tuple.ts:54:16)
```
following method is throwing the error
```
const requestService = async (selectedId, id, capacity, limit, account) => {
  // console.log("selectedId",selectedId,"id",id,"capacity",capacity,"account",account);
  // console.log(window.ethereum);
  console.log("limit:", limit);
  console.log("capacity", capacity);
  const res = await P2P.methods
    .requestService(
      parseInt(selectedId),
      parseInt(id),
      parseInt(capacity),
      ethers.utils.parseEther(String(limit))
    
    )
    .send({
      from: account,
      gas: 2000000,
    });
```
here P2P is the smart contract object and is coming from the following piece of code
```
import web3 from './web3';

const buildJson = require('./Ropsten/SC_NAME.json')
const abi = buildJson.abi
const ropsten_address=process.env.REACT_APP_SC_ADDRESS;
const contract=new web3.eth.Contract(abi,ropsten_address);
// @ts-ignore
export default new web3.eth.Contract(abi,ropsten_address);`
```

So we thought it is because of ethers.utils method but even if we replace it with parseInt(somenumber) or a bignumber it is occuring.  It is failing in metamask only so it is failing before it even reaches metamask.

### Expected Behavior

for the function to run successfully

### Steps to Reproduce

So I can breakdown the method and the fields so it could be used to reproduce the issue

```
const requestService = async (selectedId, id, capacity, limit, account) => {
  // console.log("selectedId",selectedId,"id",id,"capacity",capacity,"account",account);
  // console.log(window.ethereum);
  console.log("limit:", limit);
  console.log("capacity", capacity);
  const res = await P2P.methods
    .requestService(
      parseInt(selectedId),
      parseInt(id),
      parseInt(capacity),
      ethers.utils.parseEther(String(limit))
    
    )
    .send({
      from: account,
      gas: 2000000,
    });
  console.log("response", res);
  return res;
};
```
here limit is a eth value is a number which is then converted into a bignumber by ethers.utils.parseEther. We are hitting a requestService sc method. It is failing in the metamask wallet with the error mentioned above

### Web3.js Version

1.7.4

### Environment

- Operating System:  mac
- Browser:  chrome
- Node.js Version: 16.17.0
- NPM Version: 8.15.0

**Comment by Muhammad-Altabba** [comment]
Thanks @ashish077 ,
It would be very useful if you could provide a link to the full code, or even better to compose the scenario at some could IDE like [https://codesandbox.io/](https://codesandbox.io/), please. Because things like the smart contract function parameters' types and also the return value are needed for the investigation. And also, the ABI that you are using... 
And what are the values you are passing for: `selectedId`, `id`, `capacity` and `limit`? Could you try passing just the number 10 for each one as see if it fails with the same error?

**Comment by ashish077** [comment]
Hi,
I will create a code sandbox of the application and send it. As for passing numbers rather than ethers. utils.ParseEther() we have done it. just with numbers for all 4 arguments. I think it cant be because of the smart contract also because for that the request should at least reach metamask, whereas it is failing at the metamask itself. But I will create a code sandbox nonetheless

**Comment by ashish077** [comment]
Thanks for your clarification. on further investigation the error was due to something else and not web3.  My apologies for the inconvenience

**Comment by Muhammad-Altabba** [comment]
Thanks for telling. And you are always welcome @ashish077.
