### ISSUE TITLE
web3.eth.subscribe not working in v4 but working in v1

### ISSUE THREAD

**Issue by emmtte** [ethereum/web3.js#5446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Receive nothing with v4 but receive blocks with v1

### Expected Behavior

same as v1

### Steps to Reproduce

```
import Web3 from 'web3'
const web3 = new Web3('wss://rpc.gnosischain.com/wss')
const subscription = web3.eth.subscribe(
 "newBlockHeaders",
 (err, result) => {
     const { number } = result;
     console.log(number)
});
```

### Web3.js Version

4

### Environment

- Operating System: Linux
- Node.js Version: v18.8.0
- Yarn Version: 1.22.19

**Comment by Spacesai1or** [comment]
Hi there! Thank you for bringing this to our attention, and thank you very much for trying out version 4 of the library :rocket:

What you're trying to do is done a little bit differently in v4 of the library:

```typescript
import Web3 from 'web3';

(async () => {
    const web3 = new Web3('wss://rpc.gnosischain.com/wss')
    const sub = await web3.eth.subscribe('newBlockHeaders');
    sub.on('data', result => {
        const { number } = result;
        console.log(number);
    });
    sub.on('error', error => console.error(error));
})();
```

**Comment by emmtte** [comment]
Thanks for your quick help
