### ISSUE TITLE
console.warn considered harmfull

### ISSUE THREAD

**Issue by superboss224** [ethereum/web3.js#5447]
https://github.com/web3/web3.js/blob/c924148e34600e61c4d1326a9d30fcec83fa9f97/packages/web3-eth-ens/src/lib/ResolverMethodHandler.js#L245

The **harmfull** `console.warn` here should be removed, the lib should not display an error message if we are already catching potential errors in our code

More information : https://www.slideshare.net/dd105/logging-consideredharmful

**Comment by mconnelly8** [comment]
Hey @superboss224 , please try out our 4.x version where this wouldn't be an issue.  This would be a breaking change in 1.x, so it will not be implemented.
