### ISSUE TITLE
Write a script that parses all the CHANGELOG.md files exist in each package and updates the one on the root

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5451]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Would be useful to automate the update of the main `CHANGELOG.md` file, based on the updates of each `CHANGELOG.md` in each package.
As suggested here: https://github.com/web3/web3.js/pull/5435#discussion_r972574314

**Comment by mconnelly8** [comment]
Suggested by @spacesailor24, we should add a check to verify change logs were updated.
