### ISSUE TITLE
PREVRANDAO Support

### ISSUE THREAD

**Issue by mattdesl** [ethereum/web3.js#5459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

Looking for a way to access PREVRANDAO (the mix of the RANDAO from the previously confirmed block).

From what I understand this might be already working in web3.js but under the name `mixHash`, and could be renamed to `prevRandao`.

For details:
https://eips.ethereum.org/EIPS/eip-4399

### Use Cases

Simple and convenient use of a strong verifiable PRNG using Ethereum blockchain, for apps and games.

### Are you willing to implement this feature?

- [ ] Yes

**Comment by luu-alex** [comment]
Hey there, the web3js team is trying to minimize adding new features to the 1.x branch and strictly for necessary updates or bug fixes. Perhaps this could be an extension used for 4.x but were still in process for development, but for now we will close this issue.
