### ISSUE TITLE
Error at Pipeline `authentication needed: password or unlock` for the integration test `contract › deploy › should deploy the contract`

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The pipeline for [`Integration IPC (14, geth, ipc)`](https://github.com/web3/web3.js/actions/runs/3093668033/jobs/5006334611#logs) sometimes fails with the following error:

```
web3-eth-contract: FAIL test/integration/contract_deploy.test.ts (13.091 s)
web3-eth-contract:   ● contract › deploy › should deploy the contract
web3-eth-contract:     ResponseError: Returned error: authentication needed: password or unlock
web3-eth-contract:       218 | 			} else {
web3-eth-contract:       219 | 				this._emitter.emit('message', response, undefined);
web3-eth-contract:     > 220 | 				requestItem?.reject(new ResponseError(response));
web3-eth-contract:           | 				                    ^
web3-eth-contract:       221 | 			}
web3-eth-contract:       222 |
web3-eth-contract:       223 | 			this._requestQueue.delete(requestId);
web3-eth-contract:       at IpcProvider._onMessage (../web3-providers-ipc/src/index.ts:220:25)
```

Retry running the Pipeline sometime cause the error to disappear.
 

### Expected Behavior

To run the Pipeline without issues.

### Steps to Reproduce

Check: https://github.com/web3/web3.js/actions/runs/3093668033/jobs/5006334611

### Web3.js Version

4.x

### Environment

At GitHub Pipeline.

### Anything Else?

The current pipeline for 4.x is failing with this error after merging `Create sample application & review web3 treeshaking support (#5425) `. I am not sure, but it seems to be originated even before that merge.

**Comment by Muhammad-Altabba** [comment]
It also sometime fails when deploying the contract at the test file `test/integration/contract_erc721.test.ts` as in here https://github.com/web3/web3.js/actions/runs/3371895223/jobs/5594751521#step:4:637 

```
web3-eth-contract: FAIL test/integration/contract_erc721.test.ts (16.297 s)
web3-eth-contract:   ● contract › erc721 › should deploy the contract
web3-eth-contract:     expect(received).resolves.toBeDefined()
web3-eth-contract:     Received promise rejected instead of resolved
web3-eth-contract:     Rejected to value: [ResponseError: Returned error: authentication needed: password or unlock]
web3-eth-contract:       53 |
web3-eth-contract:       54 | 		it('should deploy the contract', async () => {
web3-eth-contract:     > 55 | 			await expect(contract.deploy(deployOptions).send(sendOptions)).resolves.toBeDefined();
web3-eth-contract:          | 			      ^
web3-eth-contract:       56 | 		});
```

**Comment by luu-alex** [comment]
Investigated, I don't think we get this issue anymore because of this [pr I think](https://github.com/web3/web3.js/commit/4daf9f2561a8328d52089a6600c0be7fbe494c54#diff-71e71e9c3bad12fbad2024acefe2b04840e36cb01182c4c6a6f87520ecd95b8c) thanks @avkos 🙏
