### ISSUE TITLE
Create local wallet user guides

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5477]
It will be nice to have these guides:

ETH
- sign and send transaction with the local wallet

Contract
- sign and deploy the contract with the local wallet
- sign and send the contract method with the local wallet

**Comment by mconnelly8** [comment]
Documentation new feature

**Comment by mconnelly8** [comment]
Discuss in future backlog grooming call before documentation updates.

**Comment by mconnelly8** [comment]
Add to the tutorials/videos we will be doing.
