### ISSUE TITLE
web3j : The term 'web3j' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by AlejoRivera26** [ethereum/web3.js#5478]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Im trying to generate the java code of a contract using web3j but it keeps telling me i dont have web3 installed or its either not working, but i already did npm install web3. also when i check the web3 version with npm ls web3 it appears to be installed correctly: `-- web3@1.8.0. any solution?

**Comment by luu-alex** [comment]
Hey there, what is the code you are writting to get this error?
