### ISSUE TITLE
Does utils.hexToNumberString retain full precision for very very large numbers.

### ISSUE THREAD

**Issue by Bug-Reaper** [ethereum/web3.js#5479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

The documentation doesn't speak to whether or not full precision is retained for very large numbers. Can someone confirm this method won't result in loss of precision for very large numbers?

https://web3js.readthedocs.io/en/v1.8.0/web3-utils.html#hextonumberstring

**Comment by luu-alex** [comment]
Yes it will retain full precision. Closing
