### ISSUE TITLE
bug in 0.18.1

### ISSUE THREAD

**Issue by iurimatias** [ethereum/web3.js#548]
steps:
1. install 0.18.1 (npm install web3)
2. run node
3. require('web3')

result:
ReferenceError: XMLHttpRequest is not defined
    at Object.<anonymous> (/Users/iurimatias/Projects/embark-framework/node_modules/web3/lib/web3/httpprovider.js:37:20)

probably caused by this change https://github.com/ethereum/web3.js/compare/0.18.0...0.18.1#diff-aebc199fe327a7153e7d6274435f1476R30

**Comment by y12studio** [comment]
I have the same issue.

**Comment by frozeman** [comment]
im aware of it, fixing it right now
