### ISSUE TITLE
[Reproducible] Websocket Timeout not working as expected

### ISSUE THREAD

**Issue by bvanderdrift** [ethereum/web3.js#5493]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

When `.send` is called on the `WebsocketProvider` **after** a connection is already established and the server is unreachable (e.g. internet dropped), the `timeout` property doesn't seem to be respected and no reconnect is triggered.

I've created a reproducible repo [here](https://github.com/bvanderdrift/web3-ws-timeout). See the README for a concise expected/actual example.

I'm happy opening a PR, but first wanted to check whether I'm missing something.

_Context_: In a project I'm trying to switch from the `HttpProvider` to the `WebsocketProvider`. Our app gets stuck upon an short internet drop, because the `WebsocketProvider` doesn't seem to reconnect.

### Examples/References

https://github.com/bvanderdrift/web3-ws-timeout

**Comment by avkos** [comment]
The problem is you should pass reconnection option as a third parameter. So, @bvanderdrift please try this code:
```js
const web3 = new Web3(new WebSocketProvider(process.env.WEBSOCKET_ENDPOINT,
    {
        clientConfig: {
            // Useful to keep a connection alive
            keepalive: true,
            keepaliveInterval: 5000, // ms
        },
    }, {
        // Enable auto reconnection
        auto: true,
        delay: 1000, // ms
        maxAttempts: 1,
    }));
```

**Comment by avkos** [comment]
@bvanderdrift I used your code and it works. I've just added try catch to see the error here:

```js
const printGasPrice = async () => {
    try{
        console.log("Fetching gas price")
        const gasPrice = await web3.eth.getGasPrice();
        console.log(`Fetched gas price: ${gasPrice}`);
    }catch (error) {
        console.log('error',error)
    }
};
```

And I receive 2 errors:
First one was `CONNECTION ERROR: Provider started to reconnect before the response got received!`
Second one: `Error: Maximum number of reconnect attempts reached!`

When I set `maxAttempts: 10` - also works. so I switched off the internet and after 30 sec turned on and it successfully reconnected.

Please try again and make sure that you use last version of web3.js. If you have any other questions please feel free to ask.

**Comment by mconnelly8** [comment]
Hey @bvanderdrift, as mentioned before, we recommend using the latest version which is v4.   We recently released the production version a couple weeks ago. Here's a couple links for you to review:
https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1
