### ISSUE TITLE
estimateGas() does not return the out of gas error ?

### ISSUE THREAD

**Issue by JTorresConsulta** [ethereum/web3.js#5494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

A function of my smart contract do a data loop.
Depends on parameters sometimes return the blockchain return the error "exceeds block gas limit"

I am trying to get it first with estimateGas() function but it never happens.

How could I know if a call will return a "exceeds block gas limit" error with web3 js?

Thanks

**Comment by luu-alex** [comment]
Hey there, what is the error you are receiving instead? any chance you can share the code snippet?

**Comment by mconnelly8** [comment]
Hey @JTorresConsulta, due to no response to this in over 2 months, we are closing this issue. If the issue is still persisting, please follow up with additional information with a code snippet.
