### ISSUE TITLE
web3.eth.getBlock() work only on firefox

### ISSUE THREAD

**Issue by yoyoyman** [ethereum/web3.js#5497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello. 
I would like to get the current block with a simple call to web3.eth.getBlockNumber().
This is working only on firefox, all other browsers return an exception

thanks for your help

### Expected Behavior

get an object with the block

### Steps to Reproduce

//include web3js in your page
//https://cdnjs.cloudflare.com/ajax/libs/web3/1.8.0/web3.min.js

```js
web3.eth.getBlockNumber().then((theBlockNumber) => {
            console.log('theBlockNumber',theBlockNumber);
        }).catch((err) => {
            console.log('error theBlockNumber',err);
        });
```
//you get an error in every browser excepted firefox

### Web3.js Version

1.8

### Environment

- Operating System: win10
- Browser: all
- Node.js Version: not running on node
- NPM Version: 

### Anything Else?

here is an example you can test to reproduce the bug
https://codepen.io/yoyoy13/pen/poVVxvN

edit : this append on BNB testnet (chain 97) , seems to work on other chains ...

**Comment by rtt63** [comment]
Unable to reproduce in Chrome Version 106.0.5249.119, seems ok

**Comment by luu-alex** [comment]
Hey are you still facing this issue?
