### ISSUE TITLE
error with Events using indexed string

### ISSUE THREAD

**Issue by iurimatias** [ethereum/web3.js#550]
steps:

contract:
```
pragma solidity ^0.4.7

contract Test {

  event TestEvent {
    string indexed _foo,
    string bar
  }

  function Test() {
  }

  function triggerEvent() {
     testEvent("hello", "world");
  }
}
```

javascript code:
```javascript
   var contract = web3.eth.contract(abi).at(address);
   contract.TestEvent(function() {
      console.log("event triggered!");
   });
   contract.triggerEvent();
```

expected: prints "event triggered!"
actual: Uncaught Error: new BigNumber() not a base 16 number: 

Changing the indexed to another type such as uint256 (and calling testEvent(123, "world")) works as expected it seems to only happen when it's a (indexed) string.

**Comment by ygnr** [comment]
You cannot add indexed to string, as string can have arbitrary length. Event arguments that are indexed end up in topics and topics can have only fixed types. Indexed strings are hashed and you will get hash of the string in topics. This is the reason for your error.

**Comment by MichalZalecki** [comment]
You can index by string and bytes but what is going to be stored as topic is Keccak-256 hash. The problem is that web3 just fails to parse it.
