### ISSUE TITLE
sendSignedTransaction takes really long

### ISSUE THREAD

**Issue by SurpriseMF3000** [ethereum/web3.js#5511]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Hello,
I want to send the Signed Transaction via RPC like shown below.
The only problem is that this takes up to 2 Minutes:(
Is there any faster way to `broadcast` the `Transaction` to the `network` than this?

```
await web3.eth.sendSignedTransaction(SignedTransaction.rawTransaction).then((receipt) => {
    console.log(receipt);
  });
```

Thanks for Help;)

**Comment by nikoulai** [comment]
hey, thanks for reaching out!

It sounds like a network issue and something related to the library. This is the only way to send a signed transaction.

I'm going to close the issue since it doesn't seem related to web3js. Feel free to reach out to us again, if you think it's related to the library.
