### ISSUE TITLE
Are there plans to create a version of web3.js for the dart language?

### ISSUE THREAD

**Issue by MiniSuperDev** [ethereum/web3.js#5513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

* version of web3.js for the dart language

### Use Cases

* the advantages of this library but in the dart language

### Are you willing to implement this feature?

- [ ] Yes

**Comment by luu-alex** [comment]
Currently no, we are focusing on rewriting web3.js exclusively in typescript.
