### ISSUE TITLE
Memory leak for the `fromWei` utility function for stirng input

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#5515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the input value for the `fromWei` function is a string type, it leaks the memory and heap continuously increased. 

### Expected Behavior

There should not be a memory leak regardless of the type of input. 

### Steps to Reproduce

```js
// test.js
const { fromWei } = require('web3-utils');

const limit = 2_000_000;

const toKb = num => (num / 1024).toFixed();

new Array(limit).fill('10000').forEach((d, i) => {
	if (i % 10000 === 0) {
		const mem = process.memoryUsage();
		console.log(`heap: ${toKb(mem.heapUsed)}, total: ${toKb(mem.heapTotal)} rss: ${toKb(mem.rss)}`);
	}
	fromWei(d, 'ether');
});
```

Start the node process with following options. 

```bash
NODE_OPTIONS=--max-old-space-size=500 node test.js
```

### Web3.js Version

4.x

### Environment

- Operating System: Mac/Linux
- Node.js Version: 16.6
- NPM Version: 8.11

### Anything Else?

This behaviour was not seen with the 1.x.

**Comment by mpetrunic** [comment]
The leak is in web3-validator specifically ajv so the issue should be renamed. Ajv is using object ref as a key for caching compiled schema so every `validate(['uint'], 123)` is compiled and cached separately. https://github.com/web3/web3.js/pull/5574 tries to reduce the leak but it's not perfect.

A better solution would be to precompile all the used schemas or implement custom validation for validating primitive types.
