### ISSUE TITLE
Some events are hanging when the code has lots of socket's subscriptions

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some events are hanging when the code has more subscriptions. Implementing https://github.com/web3/web3.js/pull/5481/ involved adding subscriptions to detect new blockheads. And this caused some test cases that involve waiting for events to sometime hang forever.  And as the code, that do more subscriptions, should not affect the events, this issue was created to investigate this matter.
However, this seems to be already noticed some time ago: https://github.com/web3/web3.js/blob/a10d2333e52088f09c0f573e9fef028fe4a133df/packages/web3-eth-contract/test/integration/contract_events.test.ts#L144

It could be that because the tests are running all in parallel the provider is not responding to the WebSocket as expected.

In all cases, this issue needs more investigation...

### Expected Behavior

Adding more subscriptions should not affect the event listening.

### Steps to Reproduce

Use more subscriptions and run the tests, you will have something similar to https://github.com/web3/web3.js/pull/5481/commits/8765d60f40404e8bccc937c9b5769214342a848d

However, the issue is not present every time. So, you may need to re-run the tests if they do not show up.

The tests that cause the issue are located at [web3-eth-contract/test/integration/contract_events.test.ts](https://github.com/web3/web3.js/blob/feature/5467/use-subscription-at-rejectIfBlockTimeout-when-the-provider-supports-subscription/packages/web3-eth-contract/test/integration/contract_events.test.ts)
at the MR: https://github.com/web3/web3.js/pull/5481/. And, to reproduce, try to checkout this MR and set `enableExperimentalFeatures` to `true`.

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by mconnelly8** [comment]
#5521 is replacing this issue, so closing this one.
