### ISSUE TITLE
Some events are emitting empty data when the code has lots of socket's subscriptions

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar to https://github.com/web3/web3.js/issues/5517 but for some events, it happens to be emitted but with empty data. This happens inside the tests (if there are lots of subscriptions like what is implemented in https://github.com/web3/web3.js/pull/5481):

- contract › erc721 › contract instance › events › should emit transfer event
- contract › erc20 › contract instance › events › should emit transfer event

The error would be similar to https://github.com/web3/web3.js/actions/runs/3222101381/jobs/5270875102.

This issue seems to be separated from https://github.com/web3/web3.js/issues/5517 but it could be linked to it.

However, in all cases, this issue needs more investigation...

### Expected Behavior

Adding more subscriptions should not affect the fired event data.

### Steps to Reproduce

Checkout this MR: https://github.com/web3/web3.js/pull/5481/ and set `enableExperimentalFeatures` to `true`.

The tests that would fail are inside https://github.com/web3/web3.js/pull/5481/ at:
`packages/web3-eth-contract/test/integration/contract_erc721.test.ts`
- contract › erc721 › contract instance › events › should emit transfer event

`packages/web3-eth-contract/test/integration/contract_erc20.test.ts`
- contract › erc20 › contract instance › events › should emit transfer event

However, the issue is not present every time. So, you may need to re-run the tests if they do not show up.

### Web3.js Version

4.x

### Environment
This happens at the CI pipeline: https://github.com/web3/web3.js/actions/runs/3222101381/jobs/5270875102

**Comment by mconnelly8** [comment]
#5521 is replacing this issue, so closing this one.
