### ISSUE TITLE
[Question] Does web3js recycle ws connection?

### ISSUE THREAD

**Issue by fireridlle** [ethereum/web3.js#5524]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

I was just wondering if web3js recycles connections. In my case, I might have hundreds of addresses to watch on. 
Will web3js recycle one connection? if not, how many connections will be opened  per each contract event listener?

### Examples/References

```javascript
     const wssUrl = `wss://${network}.infura.io/ws/v3/${INFURA_KEY}`;
     const websocketProvider = new Web3.providers.WebsocketProvider(wssUrl);
    const web3 = new Web3(websocketProvider);
    
    const addresses = [.....]
    for(const address of addresses) {
       const contract = new provider.web3.eth.Contract(erc20ABI, address);
       contract.events.Transfer({ filters: {...} }).on('data', cb)
    }
```

**Comment by Muhammad-Altabba** [comment]
Hello @fireridlle ,
It is only one instance of the socket that will be used inside every web3. This is how it works. And if you came to a conclusion that does not comply with that, please let us know.
All the best,
