### ISSUE TITLE
web3 should not transparently cast JS numbers to addresses in ABIs

### ISSUE THREAD

**Issue by Arachnid** [ethereum/web3.js#554]
Currently, the following snippet throws no exception:

    var testContract = eth.contract([{"inputs":[{"name":"a","type":"address"}],"payable":false,"type":"constructor"}])
    var test = testContract.new(0x112234455c3a32fd11230c42e7bccd4a84e02010, {from: eth.accounts[0], data: '0x'})

Javascript silently converts the unquoted hex address to a Number, losing precision, and then web3 silently translates it back into a 160 bit address, with the last few bytes replaced by 0s. This leads to subtle and difficult to diagnose bugs, and can lead to lost funds.

Web3 should throw an exception if given a Number in place of an address.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
