### ISSUE TITLE
web3 + webpack causes `SyntaxError: missing ; ` ln contract.js

### ISSUE THREAD

**Issue by barryWhiteHat** [ethereum/web3.js#555]
I use webpack to pack web3. But i get [`SyntaxError: missing ;`](https://github.com/ethereum/web3.js/blob/152a92c195c116ad200d09540e269d0939945aad/lib/web3/contract.js#L201)

which is at statement   `var ContractFactory = function (eth, abi) {` on line  `line })[0] ||Â {};` i rolled back to version 0.17.0-alpha which fixed it. But it exists in use 0.18.2.

I raised this in the truffle [gitter](https://gitter.im/ConsenSys/truffle?at=5894f875a5805a273e0ef2d5) they confirmed it was a bug and suggested the cause was [encoding](https://github.com/webpack/webpack/issues/3893) of the editor used likely [sublime](http://stackoverflow.com/questions/21289157/set-encoding-of-file-to-utf8-with-bom-in-sublime-text-3).

If this is an isolated case i can make a PR. If not my PR will only fix this single issue. So let me know if i should move forward with that.

**Comment by tcoulter** [comment]
Confirmed on my end as well.

**Comment by zmitton** [comment]
+1. mine comes up as: `Uncaught SyntaxError: Unexpected token {` 
but it's this same error from the above `ContractFactory` line.

**Comment by zmitton** [comment]
I added a pull request #563 which removes the character fixes the error.

**Comment by wojo** [comment]
Be nice to get a new build containing this fix, it looks the dist folder is behind.

**Comment by axsauze** [comment]
+1

**Comment by zmitton** [comment]
@frozeman I didn't do the build with my PR because you don't know me too well, and it would be a security issue to merge what would amount to a HUGE chunk of code too big for you to verify.
