### ISSUE TITLE
Unsubscribing on a event does not work

### ISSUE THREAD

**Issue by yanikitat** [ethereum/web3.js#5579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Does not unsubscribe from the event - The handler still gets called whenever an new block is created.

### Expected Behavior

Calling .unsubscibe() on an event listener unsubscribes from an event

### Steps to Reproduce

```typescript
const web3 = new Web3(webSocketProviderURI);

const subscription = web3.eth.subscribe("newBlockHeaders", (err, blockHeader) => {
  console.log(blockHeader);
}).on("connected", (subscriptionId: string) => {
  console.log(subscriptionId);
});

subscription.unsubscribe(); // Does not unsubscribe
```

Also `subscription.id.` is equal to null, but `.on("connected", ...)` is called succesfully after couple of seconds and I see `subscriptionId`

### Web3.js Version

1.5.3

### Environment

- Operating System: Linux Mint 21 Cinnamon
- Browser: 
- Node.js Version: v16.18.0
- NPM Version: 8.19.2

### Anything Else?

Actually this is the clone of this issue https://github.com/web3/web3.js/issues/3822
I have na exatly the same problem as described in issue below. But I didn't find a solution

**Comment by Muhammad-Altabba** [comment]
Many thanks @yanikitat for opening this issue. However, I think it is better to continue on the old one so I am closing this issue and re-opening the old one.
