### ISSUE TITLE
Refactor to parse errorsAbi

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5587]
We have lines
`packages/web3-eth-contract/src/contract.ts 1024`
and
`packages/web3-eth-contract/src/contract.ts 1050`
```ts
send: (options?: PayableTxOptions) =>
this._contractMethodSend(methodAbi, params, options), // TODO: refactor to parse errorsAbi
```
need to investigate what exactly it means and refactor it.

**Comment by Muhammad-Altabba** [comment]
Thanks for @nikoulai for his contribution to this issue through https://github.com/web3/web3.js/pull/5659
