### ISSUE TITLE
not described off method in PromiEvent<TransactionReceipt>

### ISSUE THREAD

**Issue by kricha** [ethereum/web3.js#5598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not described off method in type PromiEvent<TransactionReceipt>
<img width="756" alt="image" src="https://user-images.githubusercontent.com/4619899/200564351-7da060e6-7c90-4689-92f4-0ff8d895c1a8.png">

### Expected Behavior

need to be described

### Steps to Reproduce

```typescript
const txListener = web3.eth.sendSignedTransaction(signedTx.rawTransaction)
                                .on('confirmation', (confNumber, receipt, latestBlockHash) => {
                                    if (confNumber > 2) {
                                        txListener.off('confirmation');
                                    }
                                    console.log({confNumber, receipt, latestBlockHash})
                                })

```

### Web3.js Version

1.8.0

### Environment

- Operating System:  Docker apline
- Browser: 
- Node.js Version: v16.18.0
- NPM Version: 8.19.2

**Comment by Muhammad-Altabba** [comment]
Thanks @kricha for notifying us, we will probably take care of this soon.

And by the way, the 4.x version is in beta now. And you can checkout the branch `4.x` and check the new version that is fully written in Typescript.

**Comment by kricha** [comment]
> Thanks @kricha for notifying us, we will probably take care of this soon.
> 
> 
> 
> And by the way, the 4.x version is in beta now. And you can checkout the branch `4.x` and check the new version that is fully written in Typescript.

Thanks, but I'll wait for production release)))

**Comment by Spacesai1or** [comment]
Just adding context for this issue, from [1.x docs](https://web3js.readthedocs.io/en/v1.8.1/callbacks-promises-events.html#promievent):

> PromiEvents work like a normal promises with added on, once and off functions. This way developers can watch for additional events like on “receipt” or “transactionHash”.

**Comment by mconnelly8** [comment]
Hey @kricha, we released the v4 production version a couple weeks ago.  You can check things out with these links:
https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1
