### ISSUE TITLE
Make HttpProvider autodetect network.

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/web3.js#560]
If I settting this `web3.setProvider(new web3.providers.HttpProvider('http://localhost:8103'));`

But one day this RPC server end,how to make web3  autodetect another validate RPC server?

**Comment by EasonWang01** [comment]
If I set `if else` how do I know this RPC server is already connect other peers that have the correct blockchain data?

**Comment by peculiarity** [comment]
well in this case you need service discovery. Everything a new instances is lighted up, it register itself to common repository. Then the HttpProvider can read from this repository and check for online instances.

**Comment by nivida** [comment]
I'm closing this issue because we can't provide a service discovery in web3. It has to be done by the dapp developer it self sorry.
