### ISSUE TITLE
One failed test at GitHub actions (1.x) - Error: Failed to connect to Infura over websockets

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5604]
Some PRs like (#5550 & #5551) and have the same error in the logs for `[e2e_windows](https://github.com/web3/web3.js/actions/runs/3416365903/jobs/5686436199#logs)` with the error:

```
>>>>>>
HTTP:MAINNET getBlock
>>>>>>
Error: Failed to connect to Infura over websockets after 10 tries
    at getBlockWithRetry (D:\a\web3.js\web3.js\windows_test\basic_usage.js:31:15)
Error: Process completed with exit code 1.
```

 > I suspect it may be the effect of The Merge and the testnet deprecation by Infura:
https://blog.infura.io/post/deprecation-timeline-for-rinkeby-ropsten-and-kovan-testnets
_Originally posted by @zlumer in https://github.com/web3/web3.js/issues/5550#issuecomment-1306630537_

**Comment by jdevcs** [comment]
Its due to external users dnt have access to github secrets ( in this case our infura keys ).

**Comment by Muhammad-Altabba** [comment]
As discussed, the best solution, for now, could be to close the MR and open another one by one of the team members. And later we may have a fallback for the Infura key access.
