### ISSUE TITLE
Add support for personal_sign and personal_ecRecover

### ISSUE THREAD

**Issue by danfinlay** [ethereum/web3.js#562]
Both geth and parity now support these methods, and MetaMask is ready to support them too.  We just need the JS abstractions added to the web3 object.

**Comment by peculiarity** [comment]
https://github.com/ethereum/web3.js/pull/565

**Comment by kumavis** [comment]
wiki entry https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sign

**Comment by danfinlay** [comment]
Was merged.
