### ISSUE TITLE
Unable to decode logs for Swap transactions

### ISSUE THREAD

**Issue by umerDev** [ethereum/web3.js#5625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to decode a log that contains a swap transaction for example any of these:

- [Transaction 1](https://etherscan.io/tx/0x933fd631d8c555cf9cf3b8f5ed7a4c3c62a99cf3bac5ff468d626eafe4d28cff)
- [Transaction 2](https://etherscan.io/tx/0x3b1010acde4839d636983000850f1bd5eee6ecff3486f0ef479741bb6b0c1508)

The web3 api returns an empty array, despite there being logs on etherscan.

### Expected Behavior

It should return the logs shown in etherscan that match the Topic of Transfer.

### Steps to Reproduce

Using ether Infura or Rivet try to get the past logs for the below transaction
```
const logs = await web3.eth.getPastLogs({
    fromBlock: 15940142,
    toBlock: 15940142,
    topics: ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'],
    address: ['0x0087bb802d9c0e343f00510000729031ce00bf27'],
  });
```

### Web3.js Version

^1.7.3

**Comment by WilliamWelsh** [comment]
The address you specified in the address array is the contract the transaction interacted with in the first transaction, not the address for the log. If you go to the logs tab on Etherscan, you need to use the address that is listed at the top of the log you want. `0x0087bb802d9c0e343f00510000729031ce00bf27` isn't an address for any of the logs in the transactions you listed, it's in the topics. If you find in the log where the address if part of your topics, click the decode button and get the hex version, and put it in your topic array, I think that's what you're looking for.

```js
const logs = await web3.eth.getPastLogs({
  fromBlock: 15940142,
  toBlock: 15940142,
  topics: [
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
    "0x0000000000000000000000000087bb802d9c0e343f00510000729031ce00bf27",
  ],
});
```

```bash
[
  {
    address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000000087bb802d9c0e343f00510000729031ce00bf27',
      '0x00000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640'
    ],
    data: '0x000000000000000000000000000000000000000000000019302e0cda33d50000',
    blockNumber: 15940142,
    transactionHash: '0x933fd631d8c555cf9cf3b8f5ed7a4c3c62a99cf3bac5ff468d626eafe4d28cff',
    transactionIndex: 0,
    blockHash: '0x3ec828ca7e754c3a931048cd6b6bd398530747d524f02e18e4428a99001fe22b',
    logIndex: 1,
    removed: false,
    id: 'log_ada234e8'
  }
]
```

**Comment by umerDev** [comment]
> The address you specified in the address array is the contract the transaction interacted with in the first transaction, not the address for the log. If you go to the logs tab on Etherscan, you need to use the address that is listed at the top of the log you want. `0x0087bb802d9c0e343f00510000729031ce00bf27` isn't an address for any of the logs in the transactions you listed, it's in the topics. If you find in the log where the address if part of your topics, click the decode button and get the hex version, and put it in your topic array, I think that's what you're looking for.
> 
> ```js
> const logs = await web3.eth.getPastLogs({
>   fromBlock: 15940142,
>   toBlock: 15940142,
>   topics: [
>     "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
>     "0x0000000000000000000000000087bb802d9c0e343f00510000729031ce00bf27",
>   ],
> });
> ```
> 
> ```shell
> [
>   {
>     address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
>     topics: [
>       '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
>       '0x0000000000000000000000000087bb802d9c0e343f00510000729031ce00bf27',
>       '0x00000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640'
>     ],
>     data: '0x000000000000000000000000000000000000000000000019302e0cda33d50000',
>     blockNumber: 15940142,
>     transactionHash: '0x933fd631d8c555cf9cf3b8f5ed7a4c3c62a99cf3bac5ff468d626eafe4d28cff',
>     transactionIndex: 0,
>     blockHash: '0x3ec828ca7e754c3a931048cd6b6bd398530747d524f02e18e4428a99001fe22b',
>     logIndex: 1,
>     removed: false,
>     id: 'log_ada234e8'
>   }
> ]
> ```

Hey William thanks for the reply.

I might be missing something, or not understanding the way `swap` transactions work.

I'm able to get logs for this [Transaction](https://etherscan.io/tx/0xefd596e1adff0234a917c218a1de6d43b1f39a67e0c34fbd8df61ff9c3f7a686) by doing the following:

```typescript
const logs2 = await web3.eth.getPastLogs({
      fromBlock: 15139396,
      toBlock: 15139396,
      topics: ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"],
      address: ["0xdac17f958d2ee523a2206206994597c13d831ec7"],
  });
```

**Comment by WilliamWelsh** [comment]
The address you specify is the address for the log, that's why it shows up 
![image](https://user-images.githubusercontent.com/16886888/202251649-2b0ed5fb-dee0-4c6a-af88-36555d8ae88e.png)

That transaction is not a swap, just a transfer. Keep in mind the topic you are using is for a transfer, not an actual swap. If you go back to [this transaction](https://etherscan.io/tx/0x933fd631d8c555cf9cf3b8f5ed7a4c3c62a99cf3bac5ff468d626eafe4d28cff#eventlog), you see the third log is the actual swap. To decode that log you need the ABI of the contract the transaction interacted with.
