### ISSUE TITLE
Track request for payment

### ISSUE THREAD

**Issue by redimongo** [ethereum/web3.js#5626]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

I have tried to find a solution which does not require us linking to a 3rd party payment gateway like coinGate. What we want to do is accept ETH. 

The idea is we generate a QR code that the user can scan with their wallet that is on their smart phone. I was hoping that web3 would allow an invoice number or Transaction ID.

I am wondering is it possible to set up a request payment without knowing the users wallet address?

**Comment by avkos** [comment]
@redimongo thank you for your idea. Web3 is a library that works with blockchain. To send payment transactions, we need an address. In my opinion, if you want to create a solution without an address, you need some 3d party service, database, or smart contract (which has mapping some `invoice_id` to `address`).
