### ISSUE TITLE
IpcProvider does not have `.disconnect()` method

### ISSUE THREAD

**Issue by kykungz** [ethereum/web3.js#5641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

`IpcProvider` should have `.disconnect()` method just like `HttpProvider` and `WebsocketProvider`, as creating an `IpcProvider` will prevent node.js process from exiting.

There is a workaround by calling `web3.currentProvider.connect.end()`
```js
const web3 = new Web3(new Web3.providers.IpcProvider('/path/to/geth.ipc', net))

// ... do some stuff ...

web3.currentProvider.connection.end()
```

But imo, every `Provider` should have the same interface so that `.disconnect()` can be used universally.

### Use Cases

To correctly close IPC connection and make node.js process exits correctly.

### Implementation Ideas

There seems to be a PR (https://github.com/web3/web3.js/pull/1881) solving this already, but it was closed for unknown reasons.

```js
/**
Disconnects from the IPC endpoint. This allows freeing the socket.

@method disconnect
*/
IpcProvider.prototype.disconnect = function () {
    if (this.connection) {
        this.connection.end();
    }
};
```

### Feature Examples/References

- https://github.com/web3/web3.js/issues/1850
- https://github.com/web3/web3.js/pull/1881
- https://github.com/web3/web3.js/pull/2003

### Are you willing to implement this feature?

- [ ] Yes

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention, our team will discuss whether we'd like to add this feature to the `1.x` version of Web3. Currently we're working on a rewrite of the library (version `4.x` that's currently in alpha) where we have addressed this issue 

https://github.com/web3/web3.js/blob/650a7ec695dc3308dea29d00f8470ce6a6b5f0fe/packages/web3-providers-ipc/src/index.ts#L116

**Comment by jdevcs** [comment]
Closing this issue in favor of 4.x release:
https://github.com/web3/web3.js/releases/tag/v4.0.1
https://www.npmjs.com/package/web3/v/4.0.1
