### ISSUE TITLE
A suggestion to added as a testing repo separated from web3.js repo

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5643]
A suggestion to added as a testing repo separated from web3.js repo.

This is to test web3.js with other libraries like Ganache, Truffle, OpenZeppelin, ..., Angular, React... and etc. 
Maybe we can include a testing pipeline that we run after (or before) we publish any RC version, for example.
 
_Originally posted by @luu-alex in https://github.com/web3/web3.js/issues/5614#issuecomment-1322410714_

**Comment by Muhammad-Altabba** [comment]
Maybe as @nikoulai suggested at https://github.com/web3/web3.js/pull/5614#issuecomment-1323289664. We can have those external libraries as `devDependency`.

**Comment by Spacesai1or** [comment]
We have `ganache-cli` (the older version of `ganache`) as a `devDependency` in [1.x](https://github.com/web3/web3.js/blob/316bb6ca0d8aaea56c824efb517c2db1286bba46/package.json#L121)

**Comment by Muhammad-Altabba** [comment]
Closed in favor of https://github.com/web3/web3.js/issues/5292#issuecomment-1440304555
