### ISSUE TITLE
Error: Invalid sender

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/web3.js#566]
I am using 
Where is issue i am not getting . 

   ```
       var Tx = require('ethereumjs-tx')
          var privateKey = new Buffer('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')

          var gasPrice = privateWeb3.eth.gasPrice;
          var gasPriceHex = privateWeb3.toHex(gasPrice);
          var nonce = privateWeb3.eth.getTransactionCount(req.body.fromAddress);
          var nonceHex = privateWeb3.toHex(nonce);
          var rawTx = {
            from: req.body.fromAddress,
              nonce: nonceHex,
              gasPrice: gasPriceHex,
              gasLimit: '0x2710000000',
              to: req.body.toAddress,
              from: req.body.fromAddress,
             data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
              chainId: privateWeb3.toHex(6)
          }
            Logger.info("rawTx in transaction", rawTx)
          var tx = new Tx(rawTx)
          console.log(tx);
          tx.sign(privateKey)

          var serializedTx = tx.serialize()
          console.log(serializedTx.toString('hex'),tx)
          privateWeb3.eth.sendRawTransaction(serializedTx.toString('hex'), function(err, hash) {
              //  if (!err)

              console.log("hiii", err, hash); // "0x7f9fade1c0d57a7af66ab4ead79fade1c0d57a7af66ab4ead7c2c2eb7b11a91385"
              callback(err,hash);
          });
```
**But on    privateWeb3.eth.sendRawTransaction(serializedTx.toString('hex'), function(err, hash) { it says error**

Error: Invalid sender
    at Object.InvalidResponse (/home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/web3/lib/web3/errors.js:35:16)
    at /home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/web3/lib/web3/requestmanager.js:86:36
    at request.onreadystatechange (/home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/web3/lib/web3/httpprovider.js:110:13)
    at dispatchEvent (/home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/himanshu/Documents/project/ethereumGit/my4chain/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by 0xcaff** [comment]
Does this help? https://ethereum.stackexchange.com/questions/13498/invalid-sender-error-on-private-chain

**Comment by davux** [comment]
@nivida Do you have any explanation to share about closing this issue? Is it fixed? In what branch/release?

**Comment by nivida** [comment]
@davux I closed it because there was no answer from @himanshuoodles . If this issue is still here and the stackoverflow URL cant help you than I will reopen this Issue. I'm currently trying to clean up the long issue list we have.

**Comment by namelessperson0** [comment]
Change the below 
``` 
      const Tx = require('ethereumjs-tx').Transaction;

      var rawTx = {
        "from": myAddress,
        "gasPrice": web3js.utils.toHex(20 * 1e9),
        "gasLimit": web3js.utils.toHex(210000),
        "to": contractAddress,
        "value": "0x0",
        "data": contract.methods.safeTransferFrom(myAddress, toAddress, tokenId).encodeABI(),
      }

        var privateKey = Buffer.from('abcde', 'hex')

        var transaction = new Tx(rawTx,{ chain: 'ropsten' , hardfork: 'petersburg' });

        transaction.sign(privateKey);

        web3js.eth.sendSignedTransaction('0x' + transaction.serialize().toString('hex'))
            .on('transactionHash', console.log);
```
to the below
```
      const Tx = require('ethereumjs-tx').Transaction;

      var rawTx = {
        "from": myAddress,
        "gasPrice": web3js.utils.toHex(20 * 1e9),
        "gasLimit": web3js.utils.toHex(210000),
        "to": contractAddress,
        "value": "0x0",
        "data": contract.methods.safeTransferFrom(myAddress, toAddress, tokenId).encodeABI(),
      }

        var privateKey ='abcde'

        web3js.eth.accounts.signTransaction(rawTx, privateKey)
        .then(function(value){
            web3js.eth.sendSignedTransaction(value.rawTx)
            .then(function(response){
              console.log("response:" + JSON.stringify(response, null, ' '));
            })
          })
```
`web3js.eth.accounts.signTransaction` will take the burden of including the correct chainId and nonce .
