### ISSUE TITLE
Possibility to add custom subscription

### ISSUE THREAD

**Issue by feazzu** [ethereum/web3.js#5668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

It would be useful to be able to add new _Subscriptions_ with the _extends_ method, as it is already possible to do with the _Method_.

### Use Cases

I need to add new subscription method, in particular "droppedPendingTransactions" from a Hyperldger Besu node, but at the moment i'm not able to do it.

### Implementation Ideas

Give the possibility to use the method _extends_ with _Subscriptions_ too.

### Are you willing to implement this feature?

- [ ] Yes

**Comment by Muhammad-Altabba** [comment]
Thanks @feazzu for opening the issue,
Which version are you using? I hope you are experimenting with v4.x :smile: 

Does using `await web3Eth.subscribe('droppedPendingTransactions' as any);` works for you? If yes, we will manage to change the generic types to eliminate the need for casting to `any` here. 

And could you please share a code snippet or better: a simple sample of what you are exactly trying to do on a cloud IDE (like https://codesandbox.io/)? 

Many thanks,

**Comment by feazzu** [comment]
Thanks @Muhammad-Altabba for the quick response.

Unfortunately i'm still using latest 1.x release because i need a stable version, but i'll definitely update when 4.x version became more stable.

Using `web3.eth.subscribe('droppedPendingTransactions' as any, (txHash: string) => {})` still gives me a validation error because it treats this method as a `logs` subscribe, forcing me to define `options` as second parameter (but this could be a good thing, with a view of a generic use of the subscribe method), but forcing me also to define a callback `(error: Error, log: Log) => void` like `logs` subscription need.

I share you a codesandbox with a very simple example.
[EDIT] The link: [Codesandbox](https://codesandbox.io/s/withered-butterfly-l2kv0l?file=/src/index.ts:106-108)
Many  thanks

**Comment by Muhammad-Altabba** [comment]
Thanks @feazzu for your collaboration,
So I guess the following trick code get you pass this for now till we modify this in our next version:
```typescript
import Web3 from "web3";

const web3 = new Web3();

web3.eth.subscribe(
  // this is really ugly work around but seems to do the trick for now
  ("droppedPendingTransactions" as unknown) as "pendingTransactions",
  (error: Error, tx: string) => {
    console.log(tx);
  }
);
```
And here is the forked sandbox: https://codesandbox.io/s/intelligent-mcclintock-bwudsg?file=/src/index.ts

I hope this can resolve your issue till the next version is ready.

**Comment by feazzu** [comment]
Thank you @Muhammad-Altabba.

This solution seems to work for now.
But speaking about of more flexibility of the subscribe method, it needs the chance to define `option` field even in currents subscribe methods.
I have updated the [Codesandbox](https://codesandbox.io/s/withered-butterfly-l2kv0l?file=/src/index.ts:106-108) with a new example that seems that i can't use right now.

I need to call `newHeads` subscription with extra `options`, but i get the following error:
`Error: Invalid number of parameters for "newHeads". Got 1 expected 0!
`

**Comment by feazzu** [comment]
Hi again @Muhammad-Altabba.
Just to update you, I've tried the work around but it doesn't work, or rather, it works as a "pendingTransaction" subscription. 
So seems that there is no way to subscribe to different topics other than the default fours.

**Comment by Muhammad-Altabba** [comment]
Many thanks for sharing the update @feazzu

**Comment by mconnelly8** [comment]
Hey @feazzu, we discussed this as a team and decided to keep this as a feature request for v4, but will not be doing it for v1.

Web3.js 4.x has been released, so it's highly encouraged to use the latest web3.js:
https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1

**Comment by Muhammad-Altabba** [comment]
This issue will be implemented for version 4.x. And it will be tracked on https://github.com/web3/web3.js/issues/6223
Version 4.x is the fully supported version and in it, we implement feature suggestions.

For any further suggestions regarding this feature, let us continue the discussion there: https://github.com/web3/web3.js/issues/6223
