### ISSUE TITLE
Mismatch information on the type for `gas` for the `signTransaction` method.

### ISSUE THREAD

**Issue by FidelVe** [ethereum/web3.js#5674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

The description of the parameters for the TX object describes the `gas` parameter as of type `string` but the example afterwards uses a value of type `number`

### Examples/References

screenshot for the parameters section
![Screenshot from 2022-12-01 21-30-54](https://user-images.githubusercontent.com/43641727/205194417-e057f250-408a-4347-9a17-fad05609a3dc.png)

screenshot for the examples used
![Screenshot from 2022-12-01 21-31-17](https://user-images.githubusercontent.com/43641727/205194459-25becbc2-aaa4-4ecd-9663-0ef787e29c13.png)

link of the section in the docs:

https://web3js.readthedocs.io/en/v1.2.11/web3-eth-accounts.html#signtransaction

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention!

**Comment by FidelVe** [comment]
> Hi there, thank you for bringing this to our attention!

Is the correct type `number`? I think it should be appropriate for the param to accept a hex string as a value.

**Comment by luu-alex** [comment]
Hi the correct type for gas is `number` and it gets turned into a hex string. But as you mention, it would make sense to accept hex strings directly as well. Thank you for this we'll update you soon
