### ISSUE TITLE
web3JS 1.8.1, contract instance with defaultAccount filled not using the defaultAccount when sending transactions

### ISSUE THREAD

**Issue by moda20** [ethereum/web3.js#5696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- specify default account to use via `web3.eth.defaulmtAcount`
- create contract instance
- inspect contract instance object and see the defaultAccount ass the one set in the first step
- send a transaction without specifying the `from` argument
- receive no from account error

### Expected Behavior

not receive the error

### Steps to Reproduce

- specify default account to use via `web3.eth.defaulmtAcount`
- create contract instance
- inspect contract instance object and see the defaultAccount ass the one set in the first step
- send a transaction without specifying the `from` argument

### Web3.js Version

1.8.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention! Someone from our team should be able to investigate this soon

**Comment by mconnelly8** [comment]
6/12 - keep
