### ISSUE TITLE
getTransaction: Error: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by Sotatek-TuanNguyen7** [ethereum/web3.js#5703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction: 0xa648ab6d55adad2cc0df5c43499710cf010d58cacb16195d5338ade168d9e20c
calling getTransaction for this transaction fails with: "Error: Number can only safely store up to 53 bits"

### Expected Behavior

get success transaction success

### Steps to Reproduce

web3.eth.getTransaction('0xa648ab6d55adad2cc0df5c43499710cf010d58cacb16195d5338ade168d9e20c')

### Web3.js Version

1.8.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Spacesai1or** [comment]
Hi, thank you for bringing this to our attention. Could you provide what chain this transaction exists on? Doesn't seem to be on ETH mainnet, any of the testnets, or Binance chain

Most likely there is a property of the transaction object that web3 is attempting to convert from hex to a number and is causing an overflow. We've seen [this issue before](https://github.com/web3/web3.js/search?q=Number+can+only+safely+store+up+to+53+bits&type=issues) and have introduced a fix in rewrite of the library (`v4.x`)

**Comment by Sotatek-TuanNguyen7** [comment]
> Hi, thank you for bringing this to our attention. Could you provide what chain this transaction exists on? Doesn't seem to be on ETH mainnet, any of the testnets, or Binance chain
> 
> Most likely there is a property of the transaction object that web3 is attempting to convert from hex to a number and is causing an overflow. We've seen [this issue before](https://github.com/web3/web3.js/search?q=Number+can+only+safely+store+up+to+53+bits&type=issues) and have introduced a fix in rewrite of the library (`v4.x`)

i'm use bsc testnet: https://testnet.bscscan.com/tx/0xa648ab6d55adad2cc0df5c43499710cf010d58cacb16195d5338ade168d9e20c

**Comment by nikoulai** [comment]
Hey @Sotatek-TuanNguyen7, 

As a workaround, you can pass the string `hex` as the last parameter and get the result in hex.
Please see https://github.com/web3/web3.js/issues/5432

**Comment by Sotatek-TuanNguyen7** [comment]
> 0xa648ab6d55adad2cc0df5c43499710cf010d58cacb16195d5338ade168d9e20c

Hi @nikoulai ,
My problem is getTransaction not getTransactionReceipt

**Comment by nikoulai** [comment]
> > 0xa648ab6d55adad2cc0df5c43499710cf010d58cacb16195d5338ade168d9e20c
> 
> Hi @nikoulai , My problem is getTransaction not getTransactionReceipt

👍 my bad

**Comment by Muhammad-Altabba** [comment]
This is possibly the same as https://github.com/web3/web3.js/issues/5761
