### ISSUE TITLE
Memory leak in web3.eth.Contract

### ISSUE THREAD

**Issue by Adeel-trimulabs** [ethereum/web3.js#5704]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

I have made a fully synced ethereum node using binaries (heimdall and bor) and use its RPC point to get blockchain's data. When i start processing blocks, after some time the heap is out of memory. Upon investigating I got to know that this issue is because of `web3.eth.Contract`.

### Environment
Operating system: Mac
bor version: v0.2.16
heimdall version: v0.2.11
web3-eth-contract : v1.8.1

### Steps to reproduce
You can run the following sample code with
`````
const Contract = require("web3-eth-contract");
export const getContract = (tokenAddress: string) => {
  Contract.setProvider(web3.currentProvider);
  const contract = new Contract([],'0xc14ca0805194dc4a1319dcad80352d8033763b92');
  return contract;
};
`````

### Examples/References

I have tried different approaches specially from these two links https://github.com/web3/web3.js/issues/3042 https://github.com/web3/web3.js/pull/3866 but my issue persists

**Comment by avkos** [comment]
Checked with 1.x and 4.x version this code:
```js
const Web3 = require('web3')

async function main() {
  const web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io'))

  for (let i = 0; ;i++) {
    new web3.eth.Contract([], '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2')
    if ((i % 1000) === 0) {
      // Use node --expose-gc ./testLeak.js
      if (global.gc) { global.gc() }
      const used = process.memoryUsage().heapUsed / 1024 / 1024
      console.log(`Heap used ${used}`)
    }
  }
}

main()
```

**Comment by kondakovdmitry** [comment]
@avkos This memory leak issue is still there in the latest version. Can be checked by your code snipped above.
