### ISSUE TITLE
web3.eth.getTransactionReceipt gets unexpected response?

### ISSUE THREAD

**Issue by kevgithub** [ethereum/web3.js#5708]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Here is my code:

```
function listenTransaction(data, contractaddress, hash, fnSuccess, fnFailed){
web3.eth.getTransactionReceipt(hash, function(error, receipt){
    if(!receipt){
         listenTransaction(data, contractaddress, hash, fnSuccess, fnFailed);
    }
     else{
        fnSuccess && fnSuccess(receipt);
     }
    if(error){
         error = typeof error === 'string' ? error : JSON.stringify(error);
        ajaxErrorLog('Error，' + error);
    }
     if(receipt && !receipt.status){
        ajaxErrorLog('Error，' + JSON.stringify(receipt));
    }
})
};
```
According to the documentation, when a transaction is pending, both ‘**error**’ and ‘**receipt**’ should be null. When the transaction is confirmed, the **receipt** returns a value, but recently I found a transaction in my log file, `hash:0xaa0a83f7b0e1d26b4983d433d80466c246d68ccbfa0379537f03d5ea56e6f48f`, the **error** keeps returning {}(not null), and the **receipt** is always empty. This situation lasts for more than 30 minutes, causing my program to think that the transaction has not been successful, but I checked the transaction on Etherscan, and it actually has been confirmed within 9 seconds,

### Expected Behavior

why is this happening?

### Steps to Reproduce

why is this happening?

### Web3.js Version

1.5

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nikoulai** [comment]
hey @kevgithub, happy new year!

I just tested on `1.8.1` and everything seemed to work fine. Could you please verify?
