### ISSUE TITLE
4.x ABI: tuples not properly decoded

### ISSUE THREAD

**Issue by martialc** [ethereum/web3.js#5709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I exported an contract ABI through bscscan, for contract address 0x8b4062be0ad413d2e60e132a1797fe7540702755
When using it locally to interact with it, everything seems to be working OK, up until I try methods that return tuples (like getParticipant)

When running this method with my own address, I get something like this:
`{
  '0': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '1': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '2': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '3': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '4': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '5': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '6': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '7': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '8': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '9': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '10': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '11': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '12': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '13': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '14': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '15': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '16': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '17': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '18': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  },
  '19': {
    '0': undefined,
    '1': undefined,
    '2': undefined,
    internalType: undefined,
    name: undefined,
    type: undefined
  }
}`

### Expected Behavior

The ABI defines 20 components for the tuple, I'm expecting to be able to extract data out of these components

### Steps to Reproduce

```javascript
      const stats:any = await this.contract.methods.getParticipant(%myuseraccount%).call(); // this.contract is assigned with the return from  new this.web3JS.eth.Contract(ABI, address); 
      console.dir(stats);
```

And I've zipped the extracted ABI here: [0x8b4062be0ad413d2e60e132a1797fe7540702755.zip](https://github.com/web3/web3.js/files/10261333/0x8b4062be0ad413d2e60e132a1797fe7540702755.zip)

### Web3.js Version

4.0.1-alpha.2

### Environment

- Operating System: Ubuntu 20.04 (through Win 11 Pro / WSL2)
- Browser: Microsoft Edge Version 108.0.1462.54
- Node.js Version: v14.17.6
- NPM Version: 8.19.2 (using yarn 1.22.17)

### Anything Else?

To extract the ABI, I used this link: https://bscscan.com/address/0x8b4062be0ad413d2e60e132a1797fe7540702755#code
As for package version (4.x vs 1.x), I'm running this tool locally for fun and (my own) education purposes, it's not meant for production, I'll be happy to be your guinea pig on this one, if necessary

**Comment by luu-alex** [comment]
Thank you for creating this issue! A [PR](https://github.com/web3/web3.js/pull/5715) has been merged to address this issue and will be available for next release. 
Using the new 4.x branch with the new merged PR with the same method, the output is now:
```
{
  '0': 0n,
  '1': 0n,
  '2': '0x0000000000000000000000000000000000000000',
  '3': 0n,
  '4': 0n,
  '5': 0n,
  '6': 0n,
  '7': 0n,
  '8': false,
  '9': false,
  '10': false,
  '11': false,
  '12': false,
  '13': false,
  '14': 0n,
  '15': 0n,
  '16': 0n,
  '17': 0n,
  '18': 0n,
  '19': 0n,
  __length__: 20,
  startTime: 0n,
  balance: 0n,
  referrer: '0x0000000000000000000000000000000000000000',
  deposited: 0n,
  compounded: 0n,
  claimed: 0n,
  taxed: 0n,
  awarded: 0n,
  negative: false,
  penalized: false,
  maxed: false,
  banned: false,
  teamWallet: false,
  complete: false,
  maxedRate: 0n,
  availableRewards: 0n,
  lastRewardUpdate: 0n,
  directReferrals: 0n,
  airdropSent: 0n,
  airdropReceived: 0n
}
```
If theres anything else feel free to comment anything. Happy new year :D
