### ISSUE TITLE
geth --dev console: unable to deploy contract

### ISSUE THREAD

**Issue by DSofter** [ethereum/web3.js#571]
I know this comes up a lot, maybe I'm missing something here. I'm trying to get my hello world program running on dev net, and these are the steps I followed (according to https://ethereum.org/greeter):

```
pragma solidity ^0.4.9;

contract greeter {
    address owner;
    /* define variable greeting of the type string */
    string greeting;

    /* this runs when the contract is executed */
    function greeter(string _greeting) public {
        greeting = _greeting;
    }

    /* main function */
    function greet() constant returns (string) {
        return greeting;
    }
    
    /* this function is executed at initialization and sets the owner of the contract */
    function mortal() { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() { if (msg.sender == owner) selfdestruct(owner); }
}
```

I got the compiled code from the online compiler: 
![image](https://cloud.githubusercontent.com/assets/1687829/23584826/9200d366-0121-11e7-80ae-70789af1a272.png)

Executed under `geth --dev console` and got this:
![image](https://cloud.githubusercontent.com/assets/1687829/23584828/ab895e8e-0121-11e7-823f-5dde7ef4b9eb.png)

which is not what the tutorial described `Contract mined! address: ...`.

I went ahead and assumed the `0x98ee3bbf859259c4092ec13d5ef90d3a77d24e54` returned is the contract address and ran the following code:
```js
var abi = [{"constant":false,"inputs":[],"name":"kill","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"greet","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"mortal","outputs":[],"payable":false,"type":"function"},{"inputs":[{"name":"_greeting","type":"string"}],"payable":false,"type":"constructor"}];
var greeter = eth.contract(abi).at('0x98ee3bbf859259c4092ec13d5ef90d3a77d24e54');
greeter.greet();
```
and this is what I got:
![image](https://cloud.githubusercontent.com/assets/1687829/23584841/53c01d7c-0122-11e7-8d9f-4e36d1970a16.png)

Anything I'm missing?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
