### ISSUE TITLE
"CONNECTION ERROR: Couldn't connect..." when interacting with 'web3.js' from browser console

### ISSUE THREAD

**Issue by Miragecoder** [ethereum/web3.js#572]
Given the following sequence of statements:

```
var web3 = new Web3();
web3.setProvider(new Web3.providers.HttpProvider("http://localhost:8545/"));
var connected = web3.isConnected();
```

When this sequence of statements is being run in the browser from a JavaScript code file, `web3.isConnected` returns `true`. However, if I issue the set of statements interactively from within a browser console, I'm given `false`.

I don't understand this behaviour. Am I unaware of something? Or is it a bug?

Note: I'm connecting with TestRPC.

**Comment by frozeman** [comment]
The is connected makes a sync call under the hood, if that call fails it returns false. Tho this will be removed in 1.0 as its unreliable and sync calls are a no go

**Comment by Miragecoder** [comment]
Frozeman, thanks for your reply! `isConnected` indeed performs an API call, but my question is **why** it fails when I'm invoking it from the debugger console?

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
