### ISSUE TITLE
Some transactions do not mine when we use geth-binary and IPC provider

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5730]
#### Expected behavior
All tests pass

#### Actual behavior
Test fails. Errors in blockchain logs
`err="sealing paused while waiting for transactions"`
#### Steps to reproduce the behavior

1. Start geth-binary: `yarn geth-binary:start`
2. Generate accounts: `yarn generate:accounts`
3. Go to web3-eth package: `cd packages/web3-eth`
4. Remove timeout `packages/web3-eth/test/integration/helper.ts:43`
5. try to run test few times which send few transaction in a row. 
For example:
`yarn test:integration test/integration/watch_transaction.test.ts`
or
`yarn test:integration test/integration/subscription`

Also, this task can be related to load testing tasks

**Comment by jdevcs** [comment]
We are running local geth with POA instant seal engine config, so can safety ignore following : 
`"err="sealing paused while waiting for transactions""`
