### ISSUE TITLE
Example of EIP-1559 Transfer for ERC20 token

### ISSUE THREAD

**Issue by innerop** [ethereum/web3.js#5732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

This particular example of an EIP-1559 transaction to transfer ER20 token from one address to another, which should be very common (e.g. for sending USDC), is not covered in the docs and I googled the entire web with no results. Can you please help?

**Comment by jdevcs** [comment]
We should add this in 4.x docs

**Comment by mconnelly8** [comment]
Add a tutorial and add it to the SmartContract section.  Also refer to - https://docs.web3js.org/guides/basics/eth/#eip-1559-transaction

**Comment by sarthak1dev** [comment]
Hey would love to take this up

**Comment by mconnelly8** [comment]
Hey @sarthak1dev, thanks for offering.  Please assign yourself and let us know if you have any questions.

**Comment by sarthak1dev** [comment]
The structure for this doc would be as follows
- The need for eip1559
- Brief about gas fee changes due to eip1159
- Example of a simple transaction with a walkthrough(tutorial)

Is this acceptable?

**Comment by sarthak1dev** [comment]
Created docs with a  detailed example and sent pull request #6874

**Comment by sarthak1dev** [comment]
the commits on this branch are messed up on my side, so I will just create a new clean pr
