### ISSUE TITLE
I cant install web3 use neither yarn nor npm

### ISSUE THREAD

**Issue by 596094101** [ethereum/web3.js#5733]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

my web3 version is 1.0.0-beta.37;
my system is macOS Monterey;

### Examples/References

![image](https://user-images.githubusercontent.com/28803960/210975203-e500b513-8df6-44b4-8849-330c9d67a6bd.png)
![image](https://user-images.githubusercontent.com/28803960/210975349-aa1bfdf4-b11a-4d6b-9610-cfbb210b630d.png)

**Comment by luu-alex** [comment]
have you tried installing the latest version? `npm install web3@1.8.0`
