### ISSUE TITLE
Events with multiple unnamed args are decoded incorrectly

### ISSUE THREAD

**Issue by mkalinin** [ethereum/web3.js#574]
Let's take e.g. `e1(string, uint)`, its json looks like
```
{
  "anonymous": false,
  "inputs": [
    {
      "indexed": false,
      "name": "",
      "type": "string"
    },
    {
      "indexed": false,
      "name": "",
      "type": "uint256"
    }
  ],
  "name": "e1",
  "type": "event"
}
```
Decoding such an event we got only second argument in `args` property of resulting object. It caused by [using argument name](https://github.com/ethereum/web3.js/blob/develop/lib/web3/event.js#L157) as a key. Second argument just replaces first one in the map cause they both have same empy name `""`

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
