### ISSUE TITLE
Whitelist only `lib` for `files` entry in `package.json`s

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5743]
For npm whitelisting only `lib` , this will filter out `dist` form including in published lib. 
This will impact CDN as current CDN is configured to pick minified build through npm ( as per Greg info, I discussed with him last time ). 

I personally like it, as it will reduce lib size , so users node_modules will be of less size ( by excluding minified builds) but we will need to configure explicitly CDN for 4.x.

_Originally posted by @jdevcs in https://github.com/web3/web3.js/pull/5739#discussion_r1066023760_

**Comment by jdevcs** [comment]
until we have same CDN structure, we will need to whitelist `dist` as well so its not filtered, fix posted in above PR.

**Comment by jdevcs** [comment]
related: https://github.com/web3/web3.js/issues/6037
