### ISSUE TITLE
4.x Tests Coverage - github CI action

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#5747]
- [x] CodeCov vs other tools usage

**Comment by mconnelly8** [comment]
Need to research/investigate and come back to a team discussion.

**Comment by jdevcs** [comment]
Shared findings in team meeting of codecov pros and cons, currently integrated few features of codecov in 4.x for evaluation for some time and in future if we decide to continue, we can add/use more features like:

Features to be implemented:
- CodeCov bot report should have ( coverage report per package ( per `component` feature of codecov ) for unit tests )
- CodeCov actions ( per `component` feature of codecov )  in github should fail if coverage drops from 80%

Current limitations:
- Removing old unused flags feature is missing in CodeCov
- report comment is not updated properly 


Currently unit test coverage is uploaded per `UnitTest` single flag. and all packages are marked with `components` feature of codecov.
