### ISSUE TITLE
Uncaught Error: new BigNumber() not a number: [object Object]

### ISSUE THREAD

**Issue by ankithrajhassan** [ethereum/web3.js#575]
I am trying to build a dapp using meteor. I am having a little trouble with calling a function of the contract using web3.
Here's the code snippet that's trying to call the function of the contract:

myContract.startAFunc.sendTransaction(
  "Name",{from: fromaddress, value: 500000000000000000},
  function(err,address) {
    if(!err)
      console.log(address);});

//myContract is the ABI array at the contract address, startAFunc is the function name

The function prototype is as follows:
function startABet(string _Input} payable

I am getting this error:
Uncaught Error: new BigNumber() not a number: [object Object]

The code was working a while ago. I wanted to make a little modification by sending a variable instead of a hard coded value for wei, but was not able to do so. Later I tried to revert back by sending in hard coded values, now this is not working either.
I have spent days on this, but haven't been able to figure it out.
I am running it on chrome browser with metamask extension on a ubuntu machine.

**Comment by ankithrajhassan** [comment]
Silly thing. I changed the name of the function and it worked.! I have no idea how, but it worked.!

**Comment by titscrypto** [comment]
In my case this error occured when I've changed order of parameters and transaction context object
This gives no errors
 await tokenICO.buy(accounts[0],{value:1});
this cause mentioned error
 await tokenICO.buy({value:1},accounts[0]);
