### ISSUE TITLE
Web3 Validator minified build

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If web3-validator minified build is created and web3.js is published, web3-plugin browser tests fails as mentioned in this [issue](https://github.com/web3/web3.js/issues/5706). 

### Expected Behavior

Publishing web3 lib with web3-validator minified build and using it in other projects should not throw error as [mentioned](https://github.com/web3/web3.js/issues/5706). 

### Steps to Reproduce

Mentioned in https://github.com/web3/web3.js/issues/5706

### Web3.js Version

4.0.1-alpha.4

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Spacesai1or** [comment]
Fixed by #5755
