### ISSUE TITLE
Spelling correction API Reference -> Web3 -> utils

### ISSUE THREAD

**Issue by SrijanShovit** [ethereum/web3.js#5758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

![Screenshot (58)](https://user-images.githubusercontent.com/86592220/212464332-f4089b49-2534-428c-b63f-4dd5f1764b55.png)
 
I found this while I was reading and learning through the docs!!
I have marked the spelling mistake with blue :
It is written: Utility functions are also exposes on the Web3 class object directly.
What I feel the change should be: Utility functions are also exposed on the Web3 class object directly.

Web3 team kindly rectify it😊

**Comment by luu-alex** [comment]
Good catch. thanks for looking out! 👍  If you would like to contribute, you can create a PR with the neccesary changes otherwise i'll make one when I can

**Comment by SrijanShovit** [comment]
Sorry!😅 Actually I tried to do it first myself but got lost in the folders so finally raised an issue.
Thanks for responding 👍

**Comment by luu-alex** [comment]
No worries, i'll create one shortly.

**Comment by Coollaitar** [comment]
I will look after this issue @luu-alex  please assign me this issue

**Comment by luu-alex** [comment]
@Coollaitar  thank you, create a PR

**Comment by Coollaitar** [comment]
@luu-alex  Created PR ☑️
 Please Check
