### ISSUE TITLE
filter problem

### ISSUE THREAD

**Issue by zyairzy** [ethereum/web3.js#577]
Hello, I'm a freshman on Ethereum, I have a problem on 'filter', my codes as follows:  

	var filter = web3.eth.filter({ fromBlock:1000, toBlock:"latest"});
        filter.watch(function(err, result){ if(!err) console.log(JSON.stringify(result)) });

I want to watch 1000 to latest block, but when new block with no transactions, this filter does't work at all.

New block with transactions, the filter works.
I don't know why. Is there any one can help me this problem?
Thanks.

**Comment by frozeman** [comment]
This will call getPastLogs under the hood, not sure what exactly is not working. going from block 1000 to 3M might take up to a min in `geth`

**Comment by nivida** [comment]
I'm closing it because there was no answer from @zyairzy
