### ISSUE TITLE
4.x schema with key or id "${id}" already exists

### ISSUE THREAD

**Issue by martialc** [ethereum/web3.js#5772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I exported a contract ABI through bscscan, for contract address 0x66665ca5cb0f83e9cb813e89ca64bd6cdd4c6666
When using it locally, it immediately triggers the following error message:
```
Error: schema with key or id "1066c1c1e9545479d0a6dacf687763315a77dec942e449ac2d73f088f8f1b391541879a1b56ca748e0dc06fe69bfb8bb7a0920c63e5a93baf5563150735d4271" already exists
    at Ajv._checkUnique (../node_modules/ajv/lib/core.ts:727:13)
    at Ajv._addSchema (../node_modules/ajv/lib/core.ts:718:24)
    at Ajv.addSchema (../node_modules/ajv/lib/core.ts:486:30)
    at Web3Validator.validate (../node_modules/web3-validator/src/web3_validator.ts:105:20)
    at Object.<anonymous> (../node_modules/web3-eth-contract/src/contract.ts:1028:15)
    at Stats.<anonymous> (../src/classes/projects/Ark/Actions/Stats.ts:25:55)
    at Generator.next (<anonymous>)
```

### Expected Behavior

I expect to receive the result of calling methods on this contract.
The same code works with ABIs of other contracts, but never on any methods of this contract.

### Steps to Reproduce

Using this code:
```typescript
// @ts-ignore
const balance:any = await this.contract.methods.principalBalance(this.web3.getUserWalletAddress()).call(); // this.contract is assigned with the return from new this.web3JS.eth.Contract(ABI, address);
console.log(balance);
```
Here is the contract ABI: [0x66665ca5cb0f83e9cb813e89ca64bd6cdd4c6666.zip](https://github.com/web3/web3.js/files/10472773/0x66665ca5cb0f83e9cb813e89ca64bd6cdd4c6666.zip)

### Web3.js Version

4.0.1-alpha.5

### Environment

Operating System: Ubuntu 20.04 (through Win 11 Pro / WSL2)
Browser: Microsoft Edge Version 108.0.1462.54
Node.js Version: v18.10.0
NPM Version: 9.3.1 (using yarn 1.22.19)

### Anything Else?

To extract the ABI, I used this link: https://bscscan.com/address/0x66665ca5cb0f83e9cb813e89ca64bd6cdd4c6666#code
As for package version (4.x vs 1.x), I'm running this tool locally for fun and (my own) education purposes, it's not meant for production, I'll be happy to be your guinea pig on this one, if necessary

**Comment by Muhammad-Altabba** [comment]
Many thanks @martialc for raising the issue and providing all the details. We will investigate this further.
However, it would be also great if you provide a link to an online sandbox using a cloud IDE like https://codesandbox.io/ that contains the full code.
Thanks again,

**Comment by martialc** [comment]
Sure thing @Muhammad-Altabba, I've never used such tools, but I'll see what I can do about it. Is it possible to share this privately, though? It's quite early code that can help with some DeFi automation, but it hasn't been through any security checks, I would feel awful if someone copied it over and got into trouble with it

**Comment by Muhammad-Altabba** [comment]
Many thanks @martialc , Actually, you just need to share the minimal code that produces the error. The would make it easier for us also to debug it...

**Comment by martialc** [comment]
Ok, I'll do that later today (I'm in CEST)

**Comment by mconnelly8** [comment]
Hey @martialc, can you share the minimal code that produces the error when you get a chance?

**Comment by martialc** [comment]
Sorry for the delays, here is the smallest piece of code I can produce to reproduce this error:
https://codesandbox.io/p/sandbox/silly-sky-ndszu8
Simply running `ts-node src/index.ts` will trigger the error
