### ISSUE TITLE
Fix docker run - Github Actions

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5778]
#### Expected behavior
Change in `scripts/geth.sh`
`ethereum/client-go:stable` to `ethereum/client-go:latest`
and fix to successful run

#### Actual behavior
we use previous version and it works:
ethereum/client-go:stable

#### Logs
error log `etherbase must be explicitly specified`

**Comment by jdevcs** [comment]
This is already done in 4.x

**Comment by jdevcs** [comment]
https://github.com/web3/web3.js/pull/6020
