### ISSUE TITLE
 If i remove then in web3/lib/web3/contract.js in 137 -140 what will it impact ?

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/web3.js#578]
What is the use of 

// attach events and methods again after we have
                                addFunctionsToContract(contract);
                                addEventsToContract(contract);

in this function 

  contract._eth.getTransactionReceipt(contract.transactionHash, function(e, receipt){
                    if(receipt && !callbackFired) {

                        contract._eth.getCode(receipt.contractAddress, function(e, code){
                            /*jshint maxcomplexity: 6 */

                            if(callbackFired || !code)
                                return;

                            filter.stopWatching();
                            callbackFired = true;

                            if(code.length > 3) {

                                // console.log('Contract code deployed!');

                                contract.address = receipt.contractAddress;

                                // attach events and methods again after we have
                                addFunctionsToContract(contract);
                                addEventsToContract(contract);

                                // call callback for the second time
                                if(callback)
                                    callback(null, contract);

                            } else {
                                if(callback)
                                    callback(new Error('The contract code couldn\'t be stored, please check your gas amount.'));
                                else
                                    throw new Error('The contract code couldn\'t be stored, please check your gas amount.');
                            }
                        });
                    }
                });

If i remove then in web3/lib/web3/contract.js in 137 -140 what will it impact .

**Comment by nivida** [comment]
Because this is a question, I will refer you to: https://ethereum.stackexchange.com/
