### ISSUE TITLE
1.x web3.providers.givenProvider inconsistent testcase 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inconsistent testcase timing out 
https://github.com/web3/web3.js/actions/runs/4045312337/jobs/6956615427
1) Web3.providers.givenProvider
       should be set if window.ethereum is available
         when instantiating Web3:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/web3.js/web3.js/test/1_givenProvider-ethereumProvider.js)
      at processImmediate (internal/timers.js:464:21)

### Expected Behavior

Shouldnt timeout

### Steps to Reproduce

Run pipelines

### Web3.js Version

1.8.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by mconnelly8** [comment]
6/12 - closing
