### ISSUE TITLE
using nx dev tool with lerna

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5797]
- [ ] looking to use nx dev tool with lerna as [discussed here](https://github.com/web3/web3.js/pull/5680#issuecomment-1412345189).

**Comment by JamesHenry** [comment]
Hi Web3.js Folks 👋 

I'm James, you might possibly know me already from having created https://github.com/typescript-eslint/typescript-eslint or my work on some other popular open-source tools over the years such as ESLint, Prettier and Babel. Right now I've got my Lerna maintainer hat on 🐉  

My colleague Juri was already in touch on the linked issue, and I just wanted to follow up to ask when this call is scheduled to discuss this item?

I would be very happy to pull down your repo in advance of that and prepare a video walkthrough explaining how I would optimize your setup for maximum benefits. You could then review and discuss.

Let me know what you think!

James

**Comment by jdevcs** [comment]
Hi, @JamesHenry  We will keep you in loop for this change. Many Thanks for your contribution if you have time sure you may create PR for it in advance .

**Comment by mconnelly8** [comment]
6/12 - keep, low priority
