### ISSUE TITLE
`new Contract(abi, web3Context)` doesn't apply context to instance

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```typescript
const web3Context = new Web3Context('http://127.0.0.1:8545');
const contract = new Contract(abi, web3Context);
```

Should apply `web3Context` to `contract` instance, but [this](https://github.com/web3/web3.js/blob/e00bd8425ef6f2c6122030838bae665b3475a4ab/packages/web3-eth-contract/src/contract.ts#L322) `context` argument is never used within the constructor

### Expected Behavior

`new Contract(abi, web3Context);` applied the given context to the `Contract` instance

### Steps to Reproduce

```typescript
const web3Context = new Web3Context('http://127.0.0.1:8545');
const contract = new Contract(abi, web3Context);
```

### Web3.js Version

4.x.x

**Comment by kevinam99** [comment]
Opened https://github.com/web3/web3.js/pull/5850 to fix this

**Comment by jdevcs** [comment]
@spacesailor24 PR is merged so closing it. can you update its estimate for sprint.
