### ISSUE TITLE
myContract.events.MyEvent([options][, callback]) does not work when filter parameter of string

### ISSUE THREAD

**Issue by lee8710** [ethereum/web3.js#5806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ContractA.sol:
    
    event LogString(string indexed  aa,string bb);

    function get() public pure returns(string memory cc){
        emit LogString('indexeddede','22dsa');         
        cc='AA';
    }

Web3:

var sha3Param=web3.utils.soliditySha3('indexeddede');

contractA.events.LogString({filter:{aa:sha3Param}}).on('data',function(obj){
		console.log(obj) ;// **this line was not execute when  get() was called**
	});

### Expected Behavior

console.log(obj) ; should be excute when get() in Sol was called

### Steps to Reproduce

1:node xx.js  in cmd of windows11
2:call get() in Remix

### Web3.js Version

1.8.1

### Environment

- Operating System: windows11
- Browser: REPL
- Node.js Version: 14.21.1
- NPM Version: 6.14.17

**Comment by nikoulai** [comment]
Hey, thanks for reaching out 
This seems to be an old bug https://github.com/web3/web3.js/issues/3053 
can you try this workaround:
```
contractA.events.LogString({tpics:[sha3Param,]}).on('data',function(obj){ //note second argument in array is empty 
   console.log(obj) ;// this line was not execute when get() was called
});
```

**Comment by lee8710** [comment]
> Hey, thanks for reaching out This seems to be an old bug #3053 can you try this workaround:
> 
> ```
> contractA.events.LogString({tpics:[sha3Param,]}).on('data',function(obj){ //note second argument in array is empty 
>    console.log(obj) ;// this line was not execute when get() was called
> });
> ```



> Hey, thanks for reaching out This seems to be an old bug #3053 can you try this workaround:
> 
> ```
> contractA.events.LogString({tpics:[sha3Param,]}).on('data',function(obj){ //note second argument in array is empty 
>    console.log(obj) ;// this line was not execute when get() was called
> });
> ```
Thanks for your reply, I tried 
contractA.events.LogString({topics :[event
Signature,sha3Param]}).on('data',function(obj){ 
>    console.log(obj) ;// 
> });
It’s works now,seems topics[0] must be event signature

**Comment by nikoulai** [comment]
great! 😊
