### ISSUE TITLE
Ensure filtering works for strings on events

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5807]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

In `1.x` seems that there is a bug and strings cannot be used to filter indexed events

Example 
```
contract.events.MyEvent({filter: {a: "string"}})
``` 
We should ensure that this works on `4.x`

### Examples/References

Reported lately: https://github.com/web3/web3.js/issues/5806
Initial issue: https://github.com/web3/web3.js/issues/3053

**Comment by Spacesai1or** [comment]
Currently in `4.x`, filtering of non-indexed events arguments does not work. Instead all the events are returned

**Comment by Spacesai1or** [comment]
In addition to this, filtering of indexed strings was not supported
