### ISSUE TITLE
Incorrect decodeParameter typings 

### ISSUE THREAD

**Issue by CallumGrindle** [ethereum/web3.js#5812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The  `decodeParameter` function of `web3-eth-abi` package has return typing of `{ [key: string]: any }`. Though this function returns `string | boolean | number ` when `type` is set to `bytes`, `bool`, or `uint` and not a bytes array type.

For example, when decoding a `'bool'` type the return value is just `true` or `false` and is not wrapped in any object/array.

This means that to use typings properly with this function the result needs to be type cast to unknown 

e.g:
```ts
const boolean = decodeParameter('bool', boolBytes) as unknown as boolean
```

### Expected Behavior

Returning `string | number | boolean` should be included in the return typings

```ts
const booleanValue = decodeParameter('bool', boolBytes) as boolean
```

or better yet

```ts
const booleanValue = decodeParameter('bool', boolBytes)
console.log(typeof booleanValue) // boolean
```

### Steps to Reproduce

```ts
decodeParameter('bool', boolBytes) as unknown as boolean
```

### Web3.js Version

1.8.2

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by mconnelly8** [comment]
Hey @CallumGrindle, please look into the updated 4.x version where this isn't an issue.  We will not be making any updates with this in 1.x due to the new version.
