### ISSUE TITLE
_triggerConfigChange consistent usage

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5813]
Use [`_triggerConfigChange`](https://github.com/web3/web3.js/blob/ab31eb08b3373292dbc65e744685fb84f0941ac3/packages/web3-core/src/web3_config.ts#L515) consistently in `Web3Config` instead of directly triggering event like:
https://github.com/web3/web3.js/blob/ab31eb08b3373292dbc65e744685fb84f0941ac3/packages/web3-core/src/web3_config.ts#L303
on multiple places in config class.

**Comment by ptdatta** [comment]
Hey @jdevcs , Can I work on it??

**Comment by jdevcs** [comment]
@Parthib314 sure. Thanks for your interest in web3.js contributions

**Comment by ptdatta** [comment]
Hey @jdevcs I have made a [PR](https://github.com/web3/web3.js/pull/6025) please review it. Thanks.
