### ISSUE TITLE
About 'Transaction' type definition

### ISSUE THREAD

**Issue by ethereumNetStats** [ethereum/web3.js#5821]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

The `Transaction` definition in `/web3-core/types/index.d.ts` is :
```
export interface Transaction {
    hash: string;
    nonce: number;
    blockHash: string | null;
    blockNumber: number | null;
    transactionIndex: number | null;
    from: string;
    to: string | null;
    value: string;
    gasPrice: string;
    maxPriorityFeePerGas?: number | string | BN;
    maxFeePerGas?: number | string | BN;
    gas: number;
    input: string;
}
```
However, the example of a  return of the web3.eth.getTransaction() is :
```
{
  blockHash: '0x6f963667c7addd5c4f7f770acfb43ab26db08691452c6ba74f9f93380474bce5',
  blockNumber: 16577785,
  from: '0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990',
  gas: 27500,
  gasPrice: '38071567292',
  maxFeePerGas: '38071567292',
  maxPriorityFeePerGas: '0',
  hash: '0x703ae22035f97dd28df234eeadea3ab7f73533885ad74d0fe2b14ee59ffed54d',
  input: '0x',
  nonce: 171506,
  to: '0x4675C7e5BaAFBFFbca748158bEcBA61ef3b0a263',
  transactionIndex: 168,
  value: '32831138171266576',
  type: 2,
  accessList: [],
  chainId: '0x1',
  v: '0x1',
  r: '0x1dd0570de26aaac93c22722778e03e87170d6922ca0a0b6e4b2ca1332cd6a4da',
  s: '0x7f171741b9a4cc5d6bee8d8a6b68b0b58d8f72b2a05eddce3b1ae4368ab4dd6c'
}
```
The `Transaction` doesn't have definitions of `type, v, r, s, chainId, accessList`.
Why?

web3.js: version 1.8.2

**Comment by Muhammad-Altabba** [comment]
Thanks @ethereumNetStats the definition for those properties are available at version 4.x. However, it is still in alpha.
And we will discuss if adding them to 1.x is necessary.

**Comment by dawgbytes** [comment]
For a new token that was being worked on was about to be approved (smart contract) and the contract address was entered into etherscan and also uniswap to try to find the deployed contract.  Before it made it to "Dexscreaner" thus could not yet be locked .... the address (called "builder0x690b9a9e9aa1c9db991c7721a92d351db4fac990") 
0x690b9a9e9aa1c9db991c7721a92d351db4fac990
unfortunately leached onto my beloved Smart Contract and siphoned out the hope that I had for the coin that deployment ..

How can this be avoided and am I drawing the correct conclusion ... this is a hacker who is stealing coins prior to public release?

Thank you - Best Regards

**Comment by Muhammad-Altabba** [comment]
> For a new token that was being worked on was about to be approved (smart contract) and the contract address was entered into etherscan and also uniswap to try to find the deployed contract. Before it made it to "Dexscreaner" thus could not yet be locked .... the address (called "builder0x690b9a9e9aa1c9db991c7721a92d351db4fac990") 0x690b9a9e9aa1c9db991c7721a92d351db4fac990 unfortunately leached onto my beloved Smart Contract and siphoned out the hope that I had for the coin that deployment ..
> 
> How can this be avoided and am I drawing the correct conclusion ... this is a hacker who is stealing coins prior to public release?
> 
> Thank you - Best Regards

Sorry @dawgbytes ,your problem is not related to this opened issue nor it is related to web3.js. We can only help you here if there is something specific with web3.js library.
