### ISSUE TITLE
yarn audit reports transitive dependency cacheable-request vulnerable

### ISSUE THREAD

**Issue by mrsarm** [ethereum/web3.js#5832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Having in package.json an older or the last version of web3 `"web3": "^1.8.2"`, I got the following checking vulnerabilities:

```sh
$ yarn audit --groups dependencies
┌---------------┬--------------------------------------------------------------┐
│ high          │ cacheable-request depends on http-cache-semantics, which is  │
│               │ vulnerable to Regular Expression Denial of Service           │
├---------------+--------------------------------------------------------------┤
│ Package       │ cacheable-request                                            │
├---------------+--------------------------------------------------------------┤
│ Patched in    │ >=10.2.7                                                     │
├---------------+--------------------------------------------------------------┤
│ Dependency of │ web3                                                         │
├---------------+--------------------------------------------------------------┤
│ Path          │ web3 > web3-bzz > got > cacheable-request                    │
├---------------+--------------------------------------------------------------┤
│ More info     │ https://www.npmjs.com/advisories/1091050                     │
└---------------┴--------------------------------------------------------------┘

```

### Expected Behavior

I expected that removing the pinned dependencies in `yarn.lock` would solve the issue, but turns out they are pinned in web3 itself, so here is the transitive path expanded with the exact versions:

```
web3 "1.8.2" > web3-bzz "1.8.2" > got "12.1.0" > cacheable-request "^7.0.2"
```

The only dependency that has a range is the last one, but still a range that does not meet the criteria to avoid the vulnerability.

### Steps to Reproduce

Just add one of the last web3 versions in any project, and then execute `yarn audit`.

### Web3.js Version

1.8.2

### Environment

- Operating System: Ubuntu Linux 20.04
- Browser: 
- Node.js Version: v18.13.0
- NPM Version: yarn 1.22.19

**Comment by Spacesai1or** [comment]
Thank you for bringing this to our attention, it seems that the reported vulnerability has changed slightly:

```bash
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Server-Side Request Forgery in Request                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ request                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ web3                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ web3 > web3-bzz > swarm-js > eth-lib > servify > request     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091459                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found - Packages audited: 334
Severity: 1 Moderate
```

**Comment by Spacesai1or** [comment]
`web3-bzz` is soft-deprecated as it currently and hasn't worked for a while now, and is completely deprecated in version `4.x` of web3.js. Due to this, and because the [request](https://github.com/request/request) library (where the vulnerability comes from) is also deprecated (hasn't been touched in ~5 years), the team has decided not to act on this issue as it won't exist in `4.x` version of the library and this shouldn't affect users of `1.x`

Thank you for bringing this to our attention!
