### ISSUE TITLE
Bad Transaction type in v1.x

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#5834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We get the following values returned but they arent typed: 
```
 chainId: string;
 v: string;
 r: string;
 s: string;
 type: number;
```

### Expected Behavior

Those values are a part of the ``Transaction`` interface: 
```
 chainId: string;
 v: string;
 r: string;
 s: string;
 type: number;
 ```

### Steps to Reproduce

Look at the types haha ;-)

### Web3.js Version

<=1.8.x

### Environment

- Operating System: Debian
- Browser: NaN
- Node.js Version: latest
- NPM Version: latest

**Comment by nivida** [comment]
Duplication of https://github.com/web3/web3.js/issues/5821 sorry

**Comment by luu-alex** [comment]
Thanks for this bringing more attention to this, we'll take a look when possible :)
