### ISSUE TITLE
`Web3RequestManager.send` should return errors for `Web3Provider`s instead of throwing them

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

With the error message received from the transaction sent in `1.`, there is no opportunity for the web3.js developer to capture the RPC error and repackage it as, for example, `InsufficientFundsError` that has a specific error code that users could look up in the docs to learn more about it. I think inside web3.js we'd want to return errors that can be parsed and repackaged as needed up until the point where there is nothing the library can do and we throw it

I'm proposing we update [_processJsonRpcResponse](https://github.com/web3/web3.js/blob/f3b8ca88eb34dbf73f8e3dc9f5995c4c1a54fa87/packages/web3-core/src/web3_request_manager.ts#L312) to return errors instead of throwing them. When [Web3Providers](https://github.com/web3/web3.js/blob/f3b8ca88eb34dbf73f8e3dc9f5995c4c1a54fa87/packages/web3-core/src/web3_request_manager.ts#L178) use the `requestManager` they'll be able to receive the RPC error for further processing while other providers will continue to throw the errors as their supposed to (e.g. EIP-1193 providers)

### Use Cases

Would be used to to get a contract revert reason. Right now it's not possible to parse revert reason in `sendTransaction` because the thrown error is from the `Web3RequestManager` and is thrown before `sendTransaction` has the ability to catch the error for further processing

### Are you willing to implement this feature?

- [ ] Yes

**Comment by Spacesai1or** [comment]
While working on this, I found that we can wrap the [trySendTransaction](https://github.com/web3/web3.js/blob/a5aa3220733f8af8aca7a09ebe02224979153f2d/packages/web3-eth/src/rpc_method_wrappers.ts#L1133) in a try catch allowing us to parse the error thrown by the request manager for further processing. I started adding checks for the possible error messages, throwing new errors with specific codes like so:

```typescript
const parsedError = parseTransactionError(error);

if (typeof parsedError === 'string') {
	switch (parsedError) {
		case 'intrinsic gas too low':
			throw new IntrinsicGasTooLowError();
		case 'insufficient funds for transfer':
			throw new InsufficientFundsError();
		case 'unknown account':
			throw new UnknownAccountError();
	
		default:
			throw error
	}
}
```

but then I realized that the parsed error string is specific to clients (e.g. Geth returns `unknown account`, but Ganache returns `sender account not recognized`). So, I think we could just create a generic `TransactionFailed` error and pass it the parsed error string/parsed contract error (if the user provides the contract abi when calling `sendTransaction`)

Does anyone have any better ideas?

**Comment by Spacesai1or** [comment]
There's also just a lot of [possible errors](https://github.com/ethereum/go-ethereum/blob/master/core/error.go), and I don't think we'd want a custom error for each case

**Comment by jdevcs** [comment]
IMO in this case we should throw generic transaction failed error, and put specific error obj/details in generic error body. As for diff clients there can be different errors for same problem, and give control to user how he want to handle it.

**Comment by Muhammad-Altabba** [comment]
> There's also just a lot of [possible errors](https://github.com/ethereum/go-ethereum/blob/master/core/error.go), and I don't think we'd want a custom error for each case

I think we need to utilize the `innerError` object. Because we cannot keep up with every new error added at every provider. As, the list of possible errors is unlimited because it will keep growing and possibly variate between different providers. So, we need just to handle the general cases and pass the internal error to the user through `innerError`. So, the user can check and do something accordingly.

Updated:
So, I agree with @jdevcs idea of passing the details of the error to the user. And more specifically doing this by putting the full details of the error inside `innerError`.
