### ISSUE TITLE
JSON RPC Response Errors Shouldn't be Returned as `InvalidResponseErrors`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5848]
@jdevcs That's a good point. I think the error in the chunk parser should remain `InvalidResponseError`, but errors like the gas too low from above should be renamed to something like `RpcError`. The gas too low isn't an `InvalidResponse` it's just an error returned from the EVM because the transaction was invalid

If you agree, I can create an issue for it, merge this PR, then make the error name change?

_Originally posted by @spacesailor24 in https://github.com/web3/web3.js/pull/5844#discussion_r1110327172_

**Comment by mconnelly8** [comment]
This will cause a breaking change, so closing issue.
