### ISSUE TITLE
CodeCov report enhancements

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5879]
Remove per package coverage info table in PRs by modifying codecode github ci, 
___

**Comment by avkos** [comment]
CodeCov doesn't fully support components and customization of PR comment.
If we want to create a custom comment with table columns like
Package - Unit tests coverage/diff - Integration tests coverage/diff
we need to create a custom comment with a custom bot connected to GitHub.

To receive coverage information, we can still use CodeCov by API https://docs.codecov.com/reference/overview
