### ISSUE TITLE
checkNetwork function in ens package is failing on infura mainnet

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The code: 
```ts
const web3 = new Web3(
    "https://goerli.infura.io/v3/-----------------------"
  );
  console.log(await web3.eth.ens.checkNetwork());
```
Fails with: 
```
RangeError: The number 1678199576.042 cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at ENS.<anonymous> (/Users/nikos/Desktop/web3.js/packages/web3-eth-ens/src/ens.ts:348:20)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nikos/Desktop/web3.js/packages/web3-eth-ens/lib/ens.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Should return the registry address.

### Steps to Reproduce

see above

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Dharshan-K** [comment]
Hi I am interested in this bug. are you still working on this bug?

**Comment by nikoulai** [comment]
Hi @Dharshan-K ,

Thanks for reaching out! Yes, this is still an open issue. As far as I know, we haven't started working on it yet.
