### ISSUE TITLE
npm run test error and timeout

### ISSUE THREAD

**Issue by gzliudan** [ethereum/web3.js#5900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
npm run test test/contract.js
```

After a long timeout, it report below result:

```text
  168 passing (5s)

/home/xxxxxx/web3.js/node_modules/mocha/lib/runner.js:950
    throw err;
    ^
AssertionError: Should not throw error: expected true to be false
    at Promise.<anonymous> (/home/xxxxxx/web3.js/test/contract.js:2460:28)
    at Promise.emit (/home/xxxxxx/web3.js/node_modules/eventemitter3/index.js:182:35)
    at Timeout._onTimeout (/home/xxxxxx/web3.js/packages/web3-utils/lib/index.js:70:21)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  showDiff: true,
  actual: true,
  expected: false,
  operator: 'notStrictEqual'
}
```

### Expected Behavior

Should no error after test and no timeout

### Steps to Reproduce

```shell
git clone https://github.com/web3/web3.js
cd web3.js
npm run build
npm run test test test/contract.js
```

### Web3.js Version

commit 2b3fb3a231534e94c7b3892f37ff77100067b9e9

### Environment

- Operating System: Ubuntu 22.04.2 LTS
- Browser: none
- Node.js Version: v18.12.1 or v16.19.1
- NPM Version: 9.6.0

### Anything Else?

If I change https://github.com/web3/web3.js/blob/2b3fb3a231534e94c7b3892f37ff77100067b9e9/test/contract.js#L2460 

to

```js
assert.isTrue(e instanceof Error, 'Should not throw error');
```

The error disappeared, but still very long timeout.

**Comment by Muhammad-Altabba** [comment]
Thanks @gzliudan ,
You may look at the GitHub actions to see how tests are running. Like in here for example: https://github.com/web3/web3.js/actions/runs/4354445064/jobs/7610168520
And here is the steps I applied locally and they worked for me:
```sh
git clone https://github.com/web3/web3.js
cd web3.js
npm i
npm run build
npm run test test/contract.js

```
Note: it is `npm run test test/contract.js` not `npm run test test test/contract.js`


However, I strongly recommend and encourage you to check [v4.x](https://github.com/web3/web3.js/tree/4.x). The alpha is ready now. And the RC0 is very close. It is a big shift with TypeScript rewrite and the support for plugins...
