### ISSUE TITLE
Http provider for web3js 1.8.2 is working locally but not on github actions.

### ISSUE THREAD

**Issue by Raveen-Senanayake** [ethereum/web3.js#5901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have added this script which uses a basic script to call the smart contract to call the symbol. We use a private network. 

const web3 = new Web3(rpcUrl);
const contract_address = addressEnvironment["dev"];
const contract = new web3.eth.Contract(abi, contract_address)

We use similar code on some of our integration tests. We are observing some weird behaviour. When we use web3.js 1.7.3, this script runs locally and on GitHub actions. but when using 1.8.2, which is the latest version of web3.js, it runs locally but fails when it is run on the GitHub actions server.

We get an error called "Cant connect To The Node". We can guarantee that all credentials are correct. Any advice would be appreciated.

### Expected Behavior

Runs locally and on github actions server for web3@1.8.2

### Steps to Reproduce

const web3 = new Web3(rpcUrl);
const contract_address = addressEnvironment["dev"];
const contract = new web3.eth.Contract(abi, contract_address)

### Web3.js Version

1.8.2

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Muhammad-Altabba** [comment]
Hello @Raveen-Senanayake ,
You can check the GitHub actions on this repository. They are running as expected. So, I am afraid that we cannot help you except if you can provide a reproducible scenario that we can check on any machine.
So, I am going to close this issue. But, please, feel free to reopen it if you could have a reproducible scenario. And I guess once you will be able to reproduce the issue. You will be able to fix it yourself as I expect it is a configuration issue.
Best wishes.
