### ISSUE TITLE
GitHub actions fails for geth with http and ws: InvalidResponseError: Returned error: method handler crashed

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5903]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Many of the web3-eth tests are failing, It seems that geth has been updated with breaking changes.
 
> web3-eth: FAIL test/integration/block/rpc.getBlock.test.ts
> web3-eth:   ● rpc with block › methods › getBlock
> web3-eth:     InvalidResponseError: Returned error: method handler crashed
> web3-eth:       370 | 				}
> web3-eth:       371 | 			} else if (!Web3RequestManager._isReverted(response)) {
> web3-eth:     > 372 | 				throw new InvalidResponseError<ErrorType>(response);
> web3-eth:           | 				      ^
> web3-eth:       373 | 			}
> web3-eth:       374 | 		}
> web3-eth:       375 |
> web3-eth:       at Web3RequestManager._processJsonRpcResponse (../web3-core/src/web3_request_manager.ts:372:11)
> web3-eth:       at Web3RequestManager.<anonymous> (../web3-core/src/web3_request_manager.ts:216:16)
> web3-eth:       at fulfilled (../web3-core/lib/web3_request_manager.js:5:58)

https://github.com/web3/web3.js/actions/runs/4356949188/jobs/7629234777

**Comment by jdevcs** [comment]
https://github.com/ethereum/go-ethereum/issues/26830
