### ISSUE TITLE
EIP 712 method eth_signTypedData not found in web3.js 

### ISSUE THREAD

**Issue by iamgauravpant** [ethereum/web3.js#5927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

I tried searching for the method but could not found anything .

### Examples/References

https://eips.ethereum.org/EIPS/eip-712
This is the official documentation of EIP-712 .
I want to create a DApp in which on click of a button I am able to return the user his signature ( EIP-712 signature ) .
I haven't found how to achieve this in web3.js documentation .

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention! From what I can tell, this wasn't implemented in `1.x`, nor do I think this exists the next version of web3.js, `4.x`. I will take this to our team for further discussion on this

Some reference links for this issue:

- [EIP 712](https://eips.ethereum.org/EIPS/eip-712)
- [1.x PR](https://github.com/web3/web3.js/pull/3449) to implement this but was never merged
- [Issue](https://github.com/web3/web3.js/issues/2697) created to track this back in 2019
- Some attempted work arounds by users ([one](https://ethereum.stackexchange.com/questions/74027/eip712-implementation-for-web3-1-0) and [two](https://ethereum.stackexchange.com/questions/129707/get-signature-for-tuple-input-for-eip712))

**Comment by mconnelly8** [comment]
@iamgauravpant , we discussed this as a team and decided to close it and it will not be implemented.

**Comment by Spacesai1or** [comment]
Hey @iamgauravpant, just wanted to follow up and say we've implemented the RPC wrapper for `eth_signTypedData` and `eth_signTypedData_v4`. While not officially released yet, the [canary release](https://www.npmjs.com/package/web3/v/4.0.4-dev.933ef51.0) (`4.0.4-dev.933ef51.0`) is available for testing

**Comment by iamgauravpant** [comment]
I wasn't able to follow up with this issue . many many thanks @spacesailor24 !
