### ISSUE TITLE
The request manager should also return the result to avoid confusion

### ISSUE THREAD

**Issue by lodembeep** [ethereum/web3.js#5935]
Maybe the requestmanager should also return the result content to show the difference.
i found out about it this way : 

```
RequestManager.prototype._jsonrpcResultCallback = function (callback, payload) {
    return function (err, result) {
        if (result && result.id && payload.id !== result.id) {
            console.log("dumping everything : ");
            console.log("RESULT :", result);
            console.log("PAYLOAD :", payload);
            return callback(new Error('Wrong response id ${result.id} (expected: ${payload.id}) in ${JSON.stringify(payload)}'));
        }
        if (err) {
            return callback(err);
        }
        if (result && result.error) {
            return callback(errors.ErrorResponse(result));
        }
        if (!Jsonrpc.isValidResponse(result)) {
            return callback(errors.InvalidResponse(result));
        }
        callback(null, result.result);
    };
};
```

in the result i found a response saying that i reached the rate limit.

_Originally posted by @lodembeep in https://github.com/web3/web3.js/issues/4392#issuecomment-1475250116_

**Comment by lodembeep** [comment]
For reference, you can find the 4.x version here : https://github.com/web3/web3.js/blob/1e5a4c3c22d8d4b363395bf288f861e84f8acad1/packages/web3-core/src/web3_request_manager.ts#L421

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention and pointing out where we have accounted for this issue in `4.x`. Because it's being handled in `4.x` and the official release of `4.x` is near, our team may opt to not implement this in `1.x` and encourage our users to upgrade to latest web3.js version. Either way, I'll bring this to our team for discussion

**Comment by lodembeep** [comment]
Thanks for your input, if 4.x is close, then i guess it is fine.
Web3.js is made to work with a node, but since we have more and more API providers it would be good to adapt some debuging features towards that use case.

**Comment by mconnelly8** [comment]
@lodembeep, we will not be implementing this as a new feature to v1, but we will keep it for consideration in v4 that was recently released.

**Comment by lodembeep** [comment]
I will give it a try and see how it goes thanks 🙏
