### ISSUE TITLE
Update @ethereumjs/tx Lib to 4.x

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5943]
Review breaking changes and  @ethereumjs/tx Lib upgrade to 4.x as mentioned [here](https://github.com/web3/web3.js/pull/5904/files#r1143992147)

**Comment by mpetrunic** [comment]
This is already done in #5791

**Comment by jdevcs** [comment]
As we moved eth/tx into web3 so this change is not required.
