### ISSUE TITLE
refactor: Remove the unnecessary chainId parameter

### ISSUE THREAD

**Issue by in74mz** [ethereum/web3.js#5949]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

The **toChecksumAddress()** function had an unnecessary **chainId** parameter.
In fact, the **chainId** parameter is not used within the **toChecksumAddress()** function, so I've removed it because it might raise questions about why it exists when you want to use that function.
(web3.js/packages/web3-utils/types/index.d.ts)

**Comment by jdevcs** [comment]
This was merged via 5888
