### ISSUE TITLE
4.x - web3.min.js is not included in rc

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

web3.min.js isn't included in the rc

### Expected Behavior

web3.min.js isincluded 

### Steps to Reproduce
install web3 4.x rc

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by Spacesai1or** [comment]
I don't think any code change is needed for this, I think we forgot to do [this](https://github.com/web3/web3.js/blob/9e3f3c0988ac182060a876f999060b6fda141a12/RELEASE.md?plain=1#L31) step when releasing RC or `dist/` just wasn't present when we published to NPM - files are [there](https://www.npmjs.com/package/web3/v/4.0.1-alpha.5?activeTab=code) in `4.0.1-alpha.5` and previous releases

**Comment by luu-alex** [comment]
@spacesailor24 Yes that seems to be correct, I closed a PR that I made for this as well. Will be closing up this issue. Thanks
