### ISSUE TITLE
[4.x] Contract returns BigNumber instead of BigInt when bundled for browser

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#5959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running in nodejs, the return type from the contract is BigInt but when bundled for the browser, the return type is BigNumber. I suspect, ethers abi encoder is to blame but maybe not.

### Expected Behavior

The return type should always be BigInt.

### Steps to Reproduce

https://github.com/mpetrunic/repro

### Web3.js Version

4.0.1-rc.0

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by jdevcs** [comment]
https://github.com/web3/web3.js/pull/5965
