### ISSUE TITLE
Listening events on v4 is not working

### ISSUE THREAD

**Issue by BeroBurny** [ethereum/web3.js#5989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When contract events happen on the chain, web3 v4 does not do anything

### Expected Behavior

When contract events happen on-chain should trigger a callback.

### Steps to Reproduce

1. Open [stackblitz main.ts](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=src/main.ts) there should be all run-able code
2. Start new [remix](https://remix.ethereum.org/) project with a basic template
3. Change all content from `1_Storage.sol` with one from [stackblitz Storage.sol](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=Storage.sol)
4. Build a contract and deploy it with an `Injected Provider` - get a contract address
5. Update `contractAddress` inside [stackblitz main. ts](https://stackblitz.com/edit/vitejs-vite-enrpyq?file=src/main.ts) with the contract address from the remix
6. just in case save all inside stackblitz and refresh page 
7. call `store` method with some numeric value from remix
8. watch changes on stackblitz preview

eventually you will get something like this
![image](https://user-images.githubusercontent.com/6376047/229818683-79a34f77-4466-463a-84a8-d059f84cd2e7.png)

### Web3.js Version

4.0.1-rc.0

### Anything Else?

Events are set as https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-events there is nothing breaking in the migration guide https://docs.web3js.org/docs/guides/web3_migration_guide/contracts_migration_guide
and in tests, seems you can listen for events without providing any options
https://github.com/web3/web3.js/blob/8463f6bd45d79874b004ea128bb9d8aec63431b8/packages/web3-eth-contract/test/integration/contract_events.test.ts#L59

**Comment by deekshithpranav** [comment]
Will this be a good first issue to work on?

**Comment by jdevcs** [comment]
I was able to reproduce this with `http` provider in another code example. The error is thrown here : 
https://github.com/web3/web3.js/blob/8463f6bd45d79874b004ea128bb9d8aec63431b8/packages/web3-eth-contract/src/contract.ts#L1171
caused due to :
https://github.com/web3/web3.js/blob/8463f6bd45d79874b004ea128bb9d8aec63431b8/packages/web3-core/src/web3_subscription_manager.ts#L115

While using `websocket` provider code is not throwing error and able to subscribe + get correct event, tested on local geth node. 

We should add more error details here in case of any error : 
https://github.com/web3/web3.js/blob/8463f6bd45d79874b004ea128bb9d8aec63431b8/packages/web3-eth-contract/src/contract.ts#L1171

**Comment by mpetrunic** [comment]
@jdevcs Seems like tests are also faulty as they aren't being run for HTTP provider: https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-contract/test/integration/contract_events.test.ts#L55

**Comment by avkos** [comment]
@BeroBurny , Thanks for using version 4.x. I have two questions for you:
1. Can you try to use the WebSocket connection instead of HTTP?
2. Did you try to use an HTTP request for a subscription with version 1.x?

**Comment by mpetrunic** [comment]
> @BeroBurny , Thanks for using version 4.x. I have two questions for you:
> 1. Can you try to use the WebSocket connection instead of HTTP?
> 2. Did you try to use an HTTP request for a subscription with version 1.x?
> 

It works with websocket but events with http provider are crucial feature which 1.x supported (as well as other libraries). We are support to call eth_newFilter and then poll eth_getFilterChanges with filter id.

**Comment by avkos** [comment]
Web3js 1.x does not fail with error but does not support events with an HTTP provider.
Web3js 4.x fails with an error to inform you this is not supported.

**Comment by mpetrunic** [comment]
@avkos Seems like there was a confusion in this issue. The actual error is unrelated to http/ws provider. If you check Bero's repro case, it's actually using an injected provider. Web3.js@1.x events listening with injected provider worked while 4.x doesn't.
