### ISSUE TITLE
Error: "`n.data.substring` is not a function", when setting `web.eth.handleRevert = true`

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting `web.eth.handleRevert = true` and calling any Smart Contract method that reverts with an error:
The following error is raised: "`n.data.substring` is not a function".

### Expected Behavior

To return an error that contains the actual error from the Smart Contract.

### Steps to Reproduce

The full details are at: https://github.com/web3/web3.js/issues/5677#issuecomment-1499986255

### Web3.js Version

1.8.2

### Anything Else?

The current version of the Infura provider seems to be updated to put the error inside `data.data`. And here is what the internal object looks like with Infura:
![image](https://user-images.githubusercontent.com/24407834/230818491-545546b5-e62f-4b32-9c88-55f3711eac65.png)
 

And so we need to update web3.js to handle this. And here is the line that needs to be changed:
https://github.com/web3/web3.js/blob/2948927a18a2424621743294a80ea3ee5bf0e1e9/packages/web3-core-method/src/index.js#L629
And it could be changed to something like:
```ts
    reasonData = (err.data.data || err.data).substring(10);
```

**Comment by nicos99** [comment]
It's basically the same problem as #4454
