### ISSUE TITLE
Update `import` syntax for `web3`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#6006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to say about Web3.js' documentation?

Docs mention user must import `web3` using: `import { web3 }  from 'web3';` when currently the only supported syntax is `import Web3 from 'web3';`

### Examples/References

[This](https://github.com/web3/web3.js/blob/e75582eceb3a2dcd3b19502d9aaf79155a1ef491/docs/docs/guides/web3_migration_guide/index.md?plain=1#L26) line

**Comment by nikoulai** [comment]
During the migration in truffle, I had to use the ` {}` syntax, or I would get the `TypeError: Web3 is not a constructor` error. Please see my comment:

https://github.com/trufflesuite/truffle/pull/5393#discussion_r1189511705
