### ISSUE TITLE
Remove & Replace the AJV dependency

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6012]

**Comment by Spacesai1or** [comment]
AJV unpacked size: `1.02 MB`
 
Some AJV alternatives:

- [superstruct](https://www.npmjs.com/package/superstruct?activeTab=readme): `178 kB`
- [jtd](https://www.npmjs.com/package/jtd?activeTab=readme): `47.6 kB`
- [joi](https://www.npmjs.com/package/joi): `531 kB`
- [yup](https://www.npmjs.com/package/yup): `243 kB`
- ~[json schema](https://www.npmjs.com/package/@hyperjump/json-schema): `347 kB`~
