### ISSUE TITLE
Add additional testing package

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6013]
transactions.json.gz testing package

**Comment by jdevcs** [comment]
As shared in team meeting:
I imported transactions.json file with transactions test cases 

- and there were list of tests that were not passing validation ( missing to, missing gas etc ) fields so these test cases were removed ( as if I include missing fields it was changing output raw tx )

Following two bugs / discussion items are discovered :

- https://github.com/web3/web3.js/issues/6065
- https://github.com/web3/web3.js/issues/6063

**Comment by jdevcs** [comment]
transactions.json file is used from ethers repo for testing web3 4.x tx. 

- Only transactions with:
`to, nonce, gasPrice, gasLimit` or
`to, nonce, maxFeePerGas, maxPriorityFeePerGas, gasLimit` fields
are used for testing in this PR.


- Some Transactions with gasPrice `0x4617ee7c40` has error :

`"Eip1559GasPriceError: Invalid value given \"0x4617ee7c40\". Error: eip-1559 transactions don't support gasPrice."` https://github.com/web3/web3.js/issues/6065  These txs data is excluded in this PR, it should be investigated under 6065.

- There are some tests where RAW transaction output is not matching so these are also excluded in this PR and should be investigated under https://github.com/web3/web3.js/issues/6072
