### ISSUE TITLE
Execution reverted: SafeMath: subtraction overflow

### ISSUE THREAD

**Issue by rajesh1158** [ethereum/web3.js#6031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the below exception in nodejs when I call the `web3.eth.estimateGas` for sending a transaction for SHIB contract `0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce` on the Ethereum mainnet blockchain:

    Returned error: execution reverted: SafeMath: subtraction overflow
        at Object.ErrorResponse (/home/XX/node_modules/web3-core-helpers/lib/errors.js:28:19)
        at /home/XX/node_modules/web3-core-requestmanager/lib/index.js:300:36
        at /home/XX/node_modules/web3-providers-http/lib/index.js:124:13
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

### Expected Behavior

I should get the estimated gas price for the given transaction, and not an exception

### Steps to Reproduce

    var contract = new web3.eth.Contract([...], '0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce', { from: '0x1234' });
    var trdata = contract.methods.transfer('0x6789', BigInt(amount)).encodeABI();

    //values below are only for an example, actual addresses and fee values are different
    const rawTransaction = {
	        "from": "0x1234",
	        "to": "0x6789",
	        "value": "0x0",
	        "data": trdata,
	        "nonce": web3.utils.toHex(2),
	        "chainId": web3.utils.toHex(1),
	        "type": web3.utils.toHex(2),
	        "maxFeePerGas": web3.utils.toHex('1'),
	        "maxPriorityFeePerGas": web3.utils.toHex('1')
	    };

    await web3.eth.estimateGas(rawTransaction);

### Web3.js Version

1.8.0

### Environment

- Operating System: centos 7
- Browser: -
- Node.js Version: v16.16.0
- NPM Version: n8.11.0

**Comment by nikoulai** [comment]
Hey @rajesh1158, thanks for reaching out.
I've started looking into the issue, however, I cannot really reproduce it. Can you share the exact values used? If you prefer, send me a dm in Discord (nikoulai#3471).

**Comment by rajesh1158** [comment]
Thanks for replying @nikoulai 

In the below code, you just have to change the FROM address in 2 places as indicated in the code comments. All other values are exactly what I used to send the transfer and I got the error described.

    var abi = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"sender","type":"address"},{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"value","type":"uint256"}],"name":"burn","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"account","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"spender","type":"address"},{"name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"recipient","type":"address"},{"name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"owner","type":"address"},{"name":"spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"name","type":"string"},{"name":"symbol","type":"string"},{"name":"decimals","type":"uint8"},{"name":"totalSupply","type":"uint256"},{"name":"feeReceiver","type":"address"},{"name":"tokenOwnerAddress","type":"address"}],"payable":true,"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"}];

    var contract = new web3.eth.Contract(abi, '0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce', { from: '0x1234' }); //change the from address
    var trdata = contract.methods.transfer('0x8673962535B4D4bF7F1497D5095065Cf5c1cf2E0', BigInt('1115935200000000000000000')).encodeABI();

    //values below are only for an example, actual addresses and fee values are different
    const rawTransaction = {
        "from": "0x1234", //change the from address
        "to": "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce",
        "value": "0x0",
        "data": trdata,
        "nonce": web3.utils.toHex(0),
        "chainId": web3.utils.toHex(1), //ethereum mainnet
        "type": web3.utils.toHex(2), //EIP-1559
        "maxFeePerGas": web3.utils.toHex('68'),
        "maxPriorityFeePerGas": web3.utils.toHex('1')
    };

    await web3.eth.estimateGas(rawTransaction);

**Comment by nikoulai** [comment]
Cannot reproduce the error. If it persists please feel free to reopen.
