### ISSUE TITLE
Deprecated "Components" object warning in web3.js

### ISSUE THREAD

**Issue by victorgustavomd** [ethereum/web3.js#6039]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Hello web3.js team,

I recently encountered a warning in my browser console while using the latest version of web3.js in my project, which states: `The Components object is deprecated. It will be removed soon.`

This occurs when using the latest version of web3.js available at https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js.

Although the warning is not causing any immediate functional issues in my application, I am concerned about potential future problems when the Components object is removed.

Environment:
- Browser: Firefox 112.0.1
- Operating System: Windows 10
- web3.js Version: Lastest version as mentioned above

Steps to reproduce:
1. Include the latest version of web3.js in the project using the URL mentioned above.
2. Initialize the Web3 object and perform basic operations, such as getting the balance of an Ethereum account.
3. Observe the warning in the browser console about the deprecated Components object.

I kindly request that you investigate this warning and, if it is an issue within the web3.js library, consider working on a fix. This will ensure that developers can continue to use the library with confidence, knowing they will not encounter issues when the Components object is removed.

If you need more information or if I can assist in any way, please let me know.

Thank you for your time and for continuing to improve the web3.js library.

Sincerely,
Víctor Gustavo.

**Comment by Muhammad-Altabba** [comment]
Hello @victorgsfigueiredo 
Thanks for opening an issue at web3.js. However, the warning you are facing is not related to web3.js. Please check your browser and its plugins. And you may find more on this when you google the error. And this link might help (as it seems related to FireFox): https://stackoverflow.com/questions/59107409/what-to-do-about-the-components-object-is-deprecated-it-will-soon-be-removed 

However, if you still face this issue and it is only with web3.js, kindly provide a complete sample to reproduce the issue (either a  repo at github.com or a link to an online IDE like https://codesandbox.io/). And reopen this issue so we can look at it again.

Thanks,
