### ISSUE TITLE
eth_sendTransaction data vs input

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#6074]
Hardhat provider expects data field with eth_sendTransaction API which is inconsistent with the spec.

#### Expected behavior
For web3.js to work in the hardhat.

#### Actual behavior
The transaction gets reverted because of the missing data field. Alternatively, we can try to patch the provider in the hardhat-web3 package.

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by mpetrunic** [comment]
Potential solution, send both input and data

**Comment by mpetrunic** [comment]
cc @spacesailor24

**Comment by mpetrunic** [comment]
This is blocking: https://github.com/web3/hardhat/pull/1

**Comment by Spacesai1or** [comment]
Submitting both `input` and `data` seems to be fine for both Geth and Ganache. However, `getTransaction` only returns `input` for both clients

@mpetrunic @web3/web3-js Should we format the response for `getTransaction` to return `data` when only `input` is present and vice versa, or just leave it as whatever the client returns? One downside of leaving it as is, if a user submits `tx.data`, they'd probably expect to be able to access `data` like so: `(await getTransaction(txHash)).data`

**Comment by mpetrunic** [comment]
@spacesailor24 I think it's fine to leave only "input" for getTransaction. We have return types (and docs) in place so if user tries to use .data it will get type error.
