### ISSUE TITLE
Truffle-migtration-4.x/Error with schema

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#6090]
During the migration, I got an error from about an already existing schema 

See the test: 

https://github.com/trufflesuite/truffle/blob/38edf2ee94dc5a21d6fa3546042ea7256f509565/packages/decoder/test/current/test/downgrade-test.js#L305

**Comment by nikoulai** [comment]
I was taking a look into the truffle project in general, as this error doesn't exist after the `ajv` removal. Just needed to increase the timeout of the test.

**Comment by Muhammad-Altabba** [comment]
Thanks @nikoulai , I concluded the same :+1: .
