### ISSUE TITLE
Update docusaurus

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#6093]
Dosusaures was added almost a year ago in the project, and we are using it's `beta` 2 version, which was the latest then. 
```
"@docusaurus/core": "^2.0.0-beta.21",
"@docusaurus/preset-classic": "^2.0.0-beta.21",
"@docusaurus/theme-live-codeblock": "^2.0.0-beta.21",
```
Now it is at the `2.4.0` version. We may want to do the update.

**Comment by nikoulai** [comment]
fixed in https://github.com/web3/web3.js/pull/6089

**Comment by dotarjun** [comment]
pls close this issue
