### ISSUE TITLE
Module not found with Web3 v4.0.1-rc.1, Typescript and ESM.

### ISSUE THREAD

**Issue by SalamandraDevs** [ethereum/web3.js#6105]
Hi guys, after a read the documentation, searched on google and stackoverflow, even having worked with ChatGPT, I came to this point. 

In order to work with this Issue, I wrote an example project using web3 v4.x with ESM __("type": "module" in package.json)__, in this project I am trying to use batchRequest with the new way of doing, also I have a submodule to test both scenarios (a single module and a module with a submodule). After several hours working finally the compiler is not giving me errors, then I proceeded to execute my index.js file with some errors.

#### Expected behavior
Execution succeeded and batch Request retrieving 5 pairs addresses.

#### Actual behavior
Execution error:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/user/web3v4.x-example/node_modules/web3/lib/esm/web3' imported from /home/user/web3v4.x-example/node_modules/web3/lib/esm/index.js`
#### Steps to reproduce the behavior

1. [First step]
Clone or fork this repository: [web3v4.x-example](https://github.com/SalamandraDevs/web3v4.x-example)
3. [Second step]
Go inside and run: `npm install; npm install -w submodule; npm run start:all`

I have tested this with several combination of options in the tsconfig.json file, including: "moduleResolution": "node", "modue": "nodenext", "importHelpers": "true", "baseUrl": ".", paths and others, the result is always the same. Also I tested writing the import of web3 like this: `import Web3 from 'web3';` and `import * as Web3 from 'web3'`, considering that I have enabled the "esModuleInterop": "true" option wich includes "allowSyntheticDefaultImports" on, and as I mentioned later with the "importHelpers" turned on, but this time te error is about "not constructable signatures" in the instatiation of the web3 object.

I can see that you are not using .js extensions with the import and export sentences, because you are relying on "moduleResolution": "node", maybe it is better to write the extensiones, this could improve the compatibility of the module, because if I add it manually to the files into /lib/esm directories, the error starts to jump to another not found module, but there are may modules to edit and obviously this approach is not recommended.

#### Environment
Ubuntu 23.04 AMD64
node --version: v18.15.0
npm --version: 9.6.1
npx tsc --version: Version 5.0.4
web3: 4.0.1-rc.1 from npm

**Comment by luu-alex** [comment]
Thank you for creating the issue, we'll get someone to investigate this sometime this or next week

**Comment by jdevcs** [comment]
@SalamandraDevs try running your script with `--experimental-specifier-resolution=node` flag

**Comment by SmartArray** [comment]
> @SalamandraDevs try running your script with `--experimental-specifier-resolution=node` flag


It works, but with my configuration I get

```
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///tmp/test/node_modules/web3-eth-accounts/lib/esm/common/chains/goerli.json" needs an import assertion of type "json"
```

I am using `node` `v16.15.1`

**Comment by jdevcs** [comment]
@SmartArray thanks for testing, the error you mentioned is fixed under https://github.com/web3/web3.js/issues/6032 and will be release in next week ( in next RC )

**Comment by SalamandraDevs** [comment]
> It works, but with my configuration I get
> 
> `TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///tmp/test/node_modules/web3-eth-accounts/lib/esm/common/chains/goerli.json" needs an import assertion of type "json"`
> 
> I am using node v16.15.1

Same error.

@jdevcs let us know when the fix comes to upstream.

**Comment by SmartArray** [comment]
> @SmartArray thanks for testing, the error you mentioned is fixed under #6032 and will be release in next week ( in next RC )

Thank you so much

**Comment by jdevcs** [comment]
@SalamandraDevs [4.x RC.2](https://www.npmjs.com/package/web3/v/4.0.1-rc.2)

**Comment by SalamandraDevs** [comment]
> @SalamandraDevs [4.x RC.2](https://www.npmjs.com/package/web3/v/4.0.1-rc.2)

Thanks @jdevcs, now the code compiles but I am getting this error in the execution:

```
Pairs: 
 []
file:///home/haldrik/dev/contribuciones/web3v4.x-example/packages/submodule/dist/pairs.js:25
            throw new Error(error);
                  ^

Error: [object Object]
    at file:///home/haldrik/dev/contribuciones/web3v4.x-example/packages/submodule/dist/pairs.js:25:19                                                          
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Comming from this [code](https://github.com/SalamandraDevs/web3v4.x-example/blob/main/packages/submodule/src/pairs.ts), maybe that error makes sense to you.
