### ISSUE TITLE
Memory Leak when doing 1000s of calls

### ISSUE THREAD

**Issue by AR1011** [ethereum/web3.js#6106]
## Expected behavior
You should be able to make an infinite number of requests and there should be no problem with memory consumption to continuously increase.

## Actual behavior
The Memory consumption continues to increase while requests are being sent, until the process crashes due to OOM.

### Steps to reproduce the behavior
To test this I used the getBlock method, but i have also had memory leak issues when using various eth_call methods too such as 
```js
const ca = new w3.eth.Contract(erc20ABI, address);
ca.methods.decimals().call(),
ca.methods.totalSupply().call()
```

I have made a simple script which has a client and server. The server is emulating an eth node and just returns the same data for each call. The client is using web3.js to getBlock for every block starting at 0.

### Client.js
In the client.js, there are two functions to get the block data. `getAllBlocksJRPC` uses the rpc api directly, and does not have a memory leak. `getAllBlocksWeb3` uses web3 library and will cause memory usage to increase until it fills and causing a node.js out of memory error. 

When using `getAllBlocksJRPC` the memory consumption is constantly below 150MB even after 200k requests. It also varies up and down.
However when using `getAllBlocksWeb3`, memory consumption is constantly increasing and it never goes down. After around 170k requests i get an OOM error in node.js

```js
const Web3 = require("web3");
const localURL = "http://127.0.0.1:12348";
const web3 = new Web3(new Web3.providers.HttpProvider(localURL));

// using direct fetch : no memory leak
async function getAllBlocksJRPC(blockNumber) {
  const response = await fetch(localURL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      jsonrpc: "2.0",
      method: "eth_getBlockByNumber",
      params: [blockNumber.toString(16), true],
      id: 1,
    }),
  });
  let data = await response.json();

  //console.log(data); // uncomment to see the data

  data = null;
  return;
}

// memory leak function
async function getAllBlocksWeb3(blockNumber) {
  let block = await web3.eth.getBlock(blockNumber);

  // console.log(block); // uncomment to see the data

  block = null;

  return;
}

async function getAllBlocks() {
  maxBlock = 17000000;
  for (let i = 0; i < maxBlock; i++) {
    await getAllBlocksWeb3(i);

    if (i % 1000 == 0) {
      // keep track of where we are
      console.log(i);
    }
  }
}

getAllBlocks();
```

### Server.js
```js
const express = require("express");
const app = express();

app.use(express.json());

app.post("/", (req, res) => {
  const { jsonrpc, method, params, id } = req.body;
  //console.log(req.body);

  if (jsonrpc !== "2.0" || !method || !id) {
    res.status(400).json({ error: "Invalid JSON-RPC request" });
    return;
  }

  if (method === "eth_getBlockByNumber") {
    const blockNumber = params[0];
    // Dummy implementation: Return the same dummy data for all block numbers
    const dummyBlockData = {
      difficulty: "17179869184",
      extraData: "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
      gasLimit: `0x${(8000000).toString(16)}`,
      gasUsed: `0x${(0).toString(16)}`,
      hash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      logsBloom:
        "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      miner: "0x0000000000000000000000000000000000000000",
      mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
      nonce: "0x0000000000000042",
      number: `${blockNumber.toString(16)}`,
      parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
      receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      size: `0x${(1000).toString(16)}`,
      stateRoot: "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544",
      timestamp: `0x${parseInt(Date.now() / 1000).toString(16)}`,
      totalDifficulty: "17179869184",
      transactions: [],
      transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      uncles: [],
    };
    //console.log(dummyBlockData)
    res.json({ jsonrpc: "2.0", result: dummyBlockData, id });
  } else if (method === "eth_blockNumber") {
    let r = { jsonrpc: "2.0", id: 1, result: "0x107ccd7" };
    res.json({ jsonrpc: "2.0", result: "0x107ccd7", id });
  } else {
    res.status(404).json({ error: "Method not found" });
  }
});

app.listen(12348, "127.0.0.1", () => {
  console.log("Server is listening on http://127.0.0.1:12348");
});
```

## Logs
![image](https://github.com/web3/web3.js/assets/77502086/ac703db7-484c-4aa6-9614-c519a48a22b0)
1: client.js
2: server.js
The client will continue to eat up memory until OOM occurs at around 170k requests on my machine.

## Environment

OS: `Windows 11`
Node.js Version : `v18.16.0`
web3 Version: `1.10.0`

**Comment by james4171** [comment]
There is a memory leak that can occur in 1.x when creating new contracts, i've run into this problem in the past too.  There's a related issue here with some explanation

https://github.com/web3/web3.js/issues/4580

And some more discussion in this pull request, but i don't think it was merged.  It seems to be won't fix with the intention of dealing with the issue in 4.x

https://github.com/web3/web3.js/pull/3866

From what I gathered the contracts you create need to keep a reference to the provider that created them so that if you change the RPC of the provider the contracts are automatically updated to that new RPC.  This in turn means that contracts won't be garbage collected.  If you do end up creating a new contract in the same variable then you'll lose your reference to the original and it will become orphaned and if this continues over time you'll eventually get a memory leak.

The workaround is to reuse the contracts you've created instead of creating contracts dynamically.  You can create a cache of contracts like this and reference them by address

```
const contracts = {}; // cache of contracts

function getContractFromCache(address) {
  let contract = contracts[address];
  if (!contract) {
    contract = new web3.eth.Contract(erc20ABI, address);
    contracts[address] = contract; // add new contract to cache
  }
  return contract;
}

async function getData() {
  const contract = getContractFromCache("0x0000000000000000000000000000000SOMETHING");
  const d = await contract.methods.decimals().call();
}

```

I never saw a memory leak using `getBlock` though, so i'm not sure about that one

**Comment by AR1011** [comment]
# Update
I added a line to log the current memory consumption every 1000 reqs, then tested it on a mac and there was no memory leak. However on my windows pc it definitely does still have a memory leak.

## Windows
```
...
Memory: 787.7 MB
32000
Memory: 811.52 MB
33000
Memory: 835.2 MB
34000
Memory: 868.05 MB
35000
Memory: 892.51 MB
36000
Memory: 916.12 MB
37000
Memory: 939.65 MB
38000
Memory: 972.65 MB
39000
Memory: 996.08 MB
40000
Memory: 1019.77 MB
41000
Memory: 1052.59 MB
42000
Memory: 863.59 MB
43000
Memory: 896.33 MB
44000
Memory: 919.86 MB
45000
Memory: 944 MB
46000
Memory: 967.6 MB
47000
Memory: 1000.34 MB
48000
Memory: 1023.97 MB
49000
Memory: 1047.56 MB
50000
Memory: 1071.22 MB
51000
Memory: 1104.02 MB
52000
Memory: 1127.59 MB
53000
Memory: 1152.31 MB
54000
Memory: 1185.11 MB
55000
Memory: 1208.6 MB
56000
Memory: 1232.37 MB
57000
Memory: 1255.86 MB
58000
Memory: 1288.77 MB
59000
Memory: 1312.2 MB
60000
...
```

## Mac
```
...
Memory: 35.42 MB
192000
Memory: 37.78 MB
193000
Memory: 30.01 MB
194000
Memory: 32.5 MB
195000
Memory: 35.11 MB
196000
Memory: 37.6 MB
197000
Memory: 29.03 MB
198000
Memory: 31.56 MB
199000
Memory: 33.95 MB
200000
Memory: 36.51 MB
201000
Memory: 27.62 MB
202000
Memory: 30.18 MB
203000
Memory: 32.65 MB
204000
Memory: 34.93 MB
205000
Memory: 26.12 MB
206000
Memory: 28.52 MB
207000
Memory: 31.05 MB
208000
Memory: 33.56 MB
209000
Memory: 26.09 MB
210000
...
```

As you can see on the mac memory usage is pretty much constant around 30-35MB, however on windows its continuously increasing.

So it seems its a windows or node version related issue not web3.js
