### ISSUE TITLE
Fix ESM builds

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#6108]
Fix ESM builds to build properly export structure:

`export {some} from ''`

error inside `ethereum-cryptography/secp256k1.js` => `export { secp256k1 } from "@noble/curves/secp256k1";`

#### Expected behavior
should work this way for cjs and esm builds:
```ts
import { secp256k1 } from 'ethereum-cryptography/secp256k1';
```

#### Actual behavior
```ts
// cjs
import { secp256k1 } from 'ethereum-cryptography/secp256k1';

// esm
import secp256k1 from 'ethereum-cryptography/secp256k1';
```

The bug was temporary fixed [this way](https://github.com/web3/web3.js/pull/6100/files#diff-4a05face85188690c4f210c5b5bcd1d1855fa148e6b711fbb9d854901947fa1dR20)

path: `packages/web3-eth-accounts/src/tx/constants.ts`

**Comment by mconnelly8** [comment]
Closing issue since it has been fixed
