### ISSUE TITLE
add a parameter for .subscribe("newPendingTransactions")

### ISSUE THREAD

**Issue by damartripamungkas** [ethereum/web3.js#6122]
latest version of geth supports newPendingTransaction by returning full transaction object need to add 1 boolean parameter (true/false) if true will return full object if false will return string hash only

```javascript
// work and only return hash
.subscribe("newPendingTransactions")

// not work expect return full object transaction
.subscribe("newPendingTransactions", true)
```

web3.js version: 4.0.1-rc.1
node.js version: 20.1.0

refrence: 
https://github.com/ethereum/go-ethereum/commit/5b1a04b9c749d804b51159fe12246c56de8515c1
https://github.com/ethereum/go-ethereum/issues/26030

**Comment by jdevcs** [comment]
@damartripamungkas Thanks, if you have time could you open PR or one of our team member will look it

**Comment by damartripamungkas** [comment]
> @damartripamungkas Thanks, if you have time could you open PR or one of our team member will look it

how to make a custom subscription?? i will utilize the current version before doing PR

**Comment by damartripamungkas** [comment]
move to #6225
