### ISSUE TITLE
`TransactionConfig` typescript types does not include `type` field. 

### ISSUE THREAD

**Issue by soloseng** [ethereum/web3.js#6123]
`type` should be included in the `TransactionConfig` typescript types, just as specified in the [docs](https://web3js.readthedocs.io/en/v1.10.0/web3-eth.html)

``` typescript
await web3.eth.sendTransaction({
        from: network.from,
        to: reserve.address,
        value: web3.utils.toWei(config.reserve.initialBalance.toString(), 'ether').toString(),
        hardfork: 'istanbul',
        type: 0, // currently not included in types
      })
```

#### Logs

Argument of type '{ from: any; to: string; value: string; hardfork: string; type: number; }' is not assignable to parameter of type 'TransactionConfig'.
  Object literal may only specify known properties, and 'type' does not exist in type 'TransactionConfig'.

#### Environment

- Node18.14.2
- npm 9.5.0
- web3js 1.10.0

**Comment by Coollaitar** [comment]
@jdevcs  is this a valid issue?

**Comment by jdevcs** [comment]
I'll suggest to use our 4.x version for full types support in near future.

@Coollaitar yes, 

@soloseng Thanks for identifying, could one of you create a PR for this in 1.x?

**Comment by Coollaitar** [comment]
> I'll suggest to use our 4.x version for full types support in near future.
> 
> @Coollaitar yes,
> 
> @soloseng Thanks for identifying, could one of you create a PR for this in 1.x?

If you allow I can work on this issue!

**Comment by jdevcs** [comment]
sure,

**Comment by mconnelly8** [comment]
Hey @soloseng, the new v4 release with full type support.  We suggest using the new v4.   We will not be making any of these changes to v1.
