### ISSUE TITLE
4.x remove polyfills

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#6146]
https://github.com/web3/web3.js/issues/5994#issuecomment-1570947666
removing polyfills will reduce build size and allow cra and angular build from esm/cjs files
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by mpetrunic** [comment]
@luu-alex Seems like is-my-json-valid brought up nodejs dependency: https://github.com/mafintosh/generate-function/blob/master/index.js#LL1C1-L1C1

Just add https://www.npmjs.com/package/util as a dependency for web3-validator to fix that
