### ISSUE TITLE
Find replacement for is-my-json-valid

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#6156]
#### Expected behavior
- library is not browser friendly as it uses dependencies that depend on nodejs "util" as well as "process" global which causes build to fail in angular. Related to #6146 

#### Actual behavior

Using browser friendly library by either forking is-my-json valid or finding some browser friendly validator

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by Loque18** [comment]
+1 I'm having the same issue
