### ISSUE TITLE
Real-time swapped transaction monitoring

### ISSUE THREAD

**Issue by NonameASecret** [ethereum/web3.js#6160]
I need a little help from an expert. Can anyone tell me the method for using real-time swapped transaction monitoring for Arbiscan? I know I can use a WebSocket, but I'm unsure about the specific method to subscribe to events like "newBlockHeader" or "logs" in an RPC provider. Additionally, how can I filter out swapped transactions? Is it correct to use the topic `web3.utils.sha3('Swap(address,uint256,address)')` for filtering swapped transactions?

**Comment by luu-alex** [comment]
Hey there, I saw your discord message. Will respond there and close this issue
