### ISSUE TITLE
Error: Could not find a declaration file for module 'ws' ... Try `npm i --save-dev @types/ws`...

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6162]
#### Description
I faced the following errors when I used `web3` as the only dependency inside the chainlink plugin:

```sh
node_modules/isomorphic-ws/index.d.ts:6:28 - error TS7016: Could not find a declaration file for module 'ws'. '/web3.js-plugin-chainlink/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

6 import WebSocket = require('ws')
                             ~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:4:21 - error TS2305: Module '"isomorphic-ws"' has no exported member 'ClientOptions'.

4 import WebSocket, { ClientOptions, CloseEvent } from 'isomorphic-ws';
                      ~~~~~~~~~~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:4:36 - error TS2305: Module '"isomorphic-ws"' has no exported member 'CloseEvent'.

4 import WebSocket, { ClientOptions, CloseEvent } from 'isomorphic-ws';
                                     ~~~~~~~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:4:54 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

4 import WebSocket, { ClientOptions, CloseEvent } from 'isomorphic-ws';
                                                       ~~~~~~~~~~~~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:8:10 - error TS2305: Module '"isomorphic-ws"' has no exported member 'ClientOptions'.

8 export { ClientOptions } from 'isomorphic-ws';
           ~~~~~~~~~~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:8:31 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

8 export { ClientOptions } from 'isomorphic-ws';
                                ~~~~~~~~~~~~~~~

node_modules/web3-providers-ws/lib/commonjs/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'ws'.

1 /// <reference types="ws" />
                        ~~
```

And I had overcome his by adding
`@types/ws` to the `devDependencies` as you can find in: https://github.com/ChainSafe/web3.js-plugin-chainlink/pull/27/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

#### Steps to reproduce the behavior
 
- Clone `https://github.com/ChainSafe/web3.js-plugin-chainlink` and checkout the branch `1-use-only-web3-as-dependency`.
- Remove `"@types/ws"` from the project devDependencies. It is located at line https://github.com/ChainSafe/web3.js-plugin-chainlink/pull/27/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
- Run `yarn && yarn build`.

#### Thoughts
We need to prevent this error from happening without the addition of `@types/ws` to the `devDependencies` to the project that uses `web3`. 
And we need to prevent this for all `devDependencies` used inside our sub-packages. The error shows for `ws`. But it could happen with other packages depending on the scenario.

**Comment by Muhammad-Altabba** [comment]
Whoever faces this issue, in the meantime he can run:
`npm i --save-dev @types/ws`  or `yarn add --dev @types/ws`

And if the missed package was something other than the types of `ws`. Try, similarly, to install it on your `devDependencies`.

**Comment by Themvp07** [comment]
verified
