### ISSUE TITLE
Unsafe eval

### ISSUE THREAD

**Issue by gintsmurans** [ethereum/web3.js#6168]
Hi! 

Congrats on the new version! Just tried updating to v4.0.1 - lucky coincidence that it was released yesterday.  :)

Anyways, I am using web3js in browser extension and after update I am getting error: "Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' ". I tracked it down to a validator.js which is using "is-my-json-valid" package, which in turn is using genfun from generate-function where the error comes from. 

This makes current version unusable in extension environment. Does anyone have any suggestions on how to solve it?

**Comment by jdevcs** [comment]
@gintsmurans Thanks for checking 4.x and sharing feedback, 
is-my-json-valid is on list for [replacement](https://github.com/web3/web3.js/issues/6156).

**Comment by luu-alex** [comment]
Hi there @gintsmurans , thanks for reporting this issue. We plan on removing this library, as its been causing a few issues. unfortunately we don't have a workaround this yet but if something comes up that would be great

**Comment by fatchan** [comment]
> This makes current version unusable in extension environment. 

Or anybody not willing to tolerate allowing eval() in their CSP. Would be great to have this fixed 👍🏻
