### ISSUE TITLE
canary (`dev`) versions need to have higher version number than the last release

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6175]
Running `lerna publish from-package --canary ...` (while having the versions at pachage.json files not increased) causes it to not publish the `dev` version. And it provided this log:
```bash
lerna notice from-package No unpublished release found
lerna success No changed packages to publish 
```

You can check the logs here: https://github.com/web3/web3.js/actions/runs/5218529567/jobs/9419407963
Actually, this error came because we are still having the same 4.0.1 version in the package.json files (and 1.0.1 for a few of them). And learna is right to be confused. Because we should not publish the dev version after with published the release of that version.
So, there is a need to increase the versions numbers and then publish the dev versions. I think that: this is something that we missed taking care of earlier, because we did not have the canary configuration back then. 

And now as we have the configuration for canary release. I think we need to have ,as part of our release process, to increase the versions of the packages so the `dev` versions are published for that next version before its release.

i.e the flow I am suggesting will be like this, for example:
- We published 4.0.1 release.
- We increase the version to 4.0.2 as part of the release process (we need to update it).
- At each MR, if there is a need to increase the minor or major version number because of a breaking change for example, we probably need to increase it inside the MR that caused that change. And this change is compared to the last release version and not compared to the last MR merged.
- Github will publish dev versions for 4.0.2 automatically for every merge. 
- Later when 4.0.2 is ready. We publish its `release` and we increase the version at package.json files at the same `release` MR
- and so on...

Let me know what you think or if I missed something.

**Comment by mpetrunic** [comment]
This is already happening as you can see in github action: https://github.com/web3/web3.js/actions/runs/5218203312/jobs/9418782981

**Comment by mpetrunic** [comment]
![image](https://github.com/web3/web3.js/assets/8836210/2a042d9a-4c0c-4367-9b7a-e3906aabcfc5)
