### ISSUE TITLE
Error when publishing some of the canary versions: Two-factor authentication is required to publish this package but an automation token was specified

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6176]
At the GitHub action that publishes the canary versions. There is this error:

```bash
lerna ERR! E403 Two-factor authentication is required to publish this package but an automation token was specified
```
https://github.com/web3/web3.js/actions/runs/5216910711/jobs/9416150841#step:6:246

However, this error came after publishing 2 packages. So, for some packages, this issue is not present. And for some others, it needs to be handled.

I think one of the npm contributors can configure this.

Thanks,

**Comment by mpetrunic** [comment]
Fixed!
