### ISSUE TITLE
BabyDoge Token Transfer Issue using web3.js

### ISSUE THREAD

**Issue by ghasemsabery** [ethereum/web3.js#6184]
Hello, hope you can assist me. I am currently working on the Ethereum network and have a few questions regarding a token transfer using web3.js.

#### Expected behavior
I expect to be able to successfully transfer BabyDoge tokens on the Ethereum network.

#### Actual behavior
I encountered some issues while attempting to transfer BabyDoge tokens using the following code:
```
 const filePath = path.join(__dirname, '..', 'abi.json');
    const tokenAbi = JSON.parse(readFileSync(filePath, 'utf8'));

    //* Initialize Web3
    const web3 = this.init(parameter);

    //* Get the account address from which to send the transaction

    const account = await web3.eth.getAccounts();

    const amountToSend = web3.utils.toWei('0.00001', "ether");

    const gasPrice = await web3.eth.getGasPrice();
    const gasLimit = 200000;

    const nonce = await web3.eth.getTransactionCount(account[0]);

    const tokenAddress = '0xAC57De9C1A09FeC648E93EB98875B212DB0d460B'; // Baby Doge Coin

    const tokenContract = new web3.eth.Contract(tokenAbi, tokenAddress);

    const toAddress = parameter.outputs[0].toAddress;

    const tx = {
      from: account[0],
      to: toAddress,
      value: '0x0',
      data: tokenContract.methods.transfer(toAddress, amountToSend).encodeABI(),
      gasPrice: gasPrice,
      gasLimit: gasLimit,
      nonce: nonce,
      chainId: 3 //  Ropsten
    };

    console.log(tx);

    // Check if sender balance is sufficient for transaction
    const senderBalance = await web3.eth.getBalance(account[0]);
    console.log(senderBalance);

    if (parseInt(senderBalance) < parseInt(amountToSend)) {
      throw new Error("Insufficient balance!");
    }

    // Check if destination address is valid
    if (!web3.utils.isAddress(toAddress)) {
      throw new Error("Invalid destination address!");
    }

    // Send transaction
    const receipt = await web3.eth.sendTransaction(tx);

    console.log(receipt);
```
#### Steps to reproduce the behavior

1. Attempt to transfer BabyDoge tokens using the code above.
2. Observe that the transaction fails.
#### Logs
No logs are available at this time.

#### Environment
Versions used:

web3.js: "^1.10.0"

### Additional context
I also have a few questions regarding the validity of my token transfer code. Is the code written correctly for transferring Ethereum tokens? Additionally, where can I obtain test BabyDoge tokens for testing purposes on a test network such as Ropsten or Kovan?

Thank you in advance for your help!

**Comment by jdevcs** [comment]
@ghasemsabery what error message you are getting?

Regarding getting test tokens, we are not maintaining BabyDoge. so cannot help on this.

**Comment by mconnelly8** [comment]
Closing issue due to no response
