### ISSUE TITLE
TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by eliashezron** [ethereum/web3.js#6187]
#### Expected behavior
view screen on deployment

#### Actual behavior

failing to view screen on deployment because of the error, This is the error ```TypeError: Cannot convert a BigInt value to a number``` that seems to be coming from the ```converter.ts``` file. line ```40``` in the screenshot below
<img width="594" alt="Screenshot 2023-06-12 at 14 40 01" src="https://github.com/web3/web3.js/assets/60871378/2256043e-d932-47f9-835e-8c111cb703aa">

#### Steps to reproduce the behavior

1. [First step]
create-react-app
2. [second step]
install the lastest web3 package ```yarn add web3```
3. [third step]
build the project
4. [and so on...]
deploy to [netlify](app.netlify.com) or [vercel](vercel.com)

#### Logs

<img width="795" alt="Screenshot 2023-06-12 at 14 34 30" src="https://github.com/web3/web3.js/assets/60871378/6d3f8a74-fb67-4103-8218-f972218ebb18">

#### Environment
npm ```9.6.2```
node ```v18.15.0```
web3js ```v4.0.1```
OS ```macOS```
device ```macbook```

**Comment by Muhammad-Altabba** [comment]
Thanks @eliashezron for opening an issue.

However, in order to help you, we need the code that caused the error. And it will be great if you could make it available at some cloud IDE like https://codesandbox.io/.

Thanks,

**Comment by eliashezron** [comment]
so I am trying to create an chrome extension, I create a reactapp and the add web3 package to the app, Then call a function to get the balance of an address, Build and deploy. Thats where the error comes from. try it out here

https://codesandbox.io/s/web3jstypeerrorcannot-convert-a-bigint-value-to-a-number-cljhk7?file=/src/App.js:772-788

**Comment by Xaber20110202** [comment]
Same problem, I just set version to 1.9.0, solved this problem. @eliashezron

**Comment by valentin-uskov** [comment]
@eliashezron Hi!
Same problem. Change browsers list in package.json, solved this problem

````
"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  ````

**Comment by eliashezron** [comment]
> @eliashezron Hi! Same problem. Change browsers list in package.json, solved this problem
> 
> ```
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```

This solution worked for me. Thank you @valentin-uskov

**Comment by milaabl** [comment]
@eliashezron , indeed @valentin-uskov  is a life saver! Thanks

**Comment by pablogeek** [comment]
This doesn't fix my issue.... any other thing I can try?

**Comment by Edison4mobile** [comment]
@valentin-uskov 
you saved my time.

**Comment by devilbcsswap** [comment]
> @eliashezron Hi! Same problem. Change browsers list in package.json, solved this problem
> 
> ```
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```

Fkkk. You saved my life. Thanks.

**Comment by Muhammad-Altabba** [comment]
Thanks all for your shared findings.
We will try to look deeper into this.

**Comment by dhruv2185** [comment]
> @eliashezron Hi! Same problem. Change browsers list in package.json, solved this problem
> 
> ```
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```

Thank you very much, wasn't able to fix this bug for days. You are a lifesaver!

**Comment by mconnelly8** [comment]
Per 9/5 meeting, need to investigate.

**Comment by inspi-writer001** [comment]
> @eliashezron Hi! Same problem. Change browsers list in package.json, solved this problem
> 
> ```
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
> ```

Thanks man, I've been on this for daysss

Finally, your solution helped me

**Comment by inspi-writer001** [comment]
also , if you're using web3.js on the baackend, say a nodejs app,

use module `import Web3 from "web3"` instead of `const Web3 =  require("web3")`
this'll prevent the "Web3 is not a constructor" issue

**Comment by moojing** [comment]
> > @eliashezron Hi! Same problem. Change browsers list in package.json, solved this problem
> > ```
> > "browserslist": {
> >     "production": [
> >       "chrome >= 67",
> >       "edge >= 79",
> >       "firefox >= 68",
> >       "opera >= 54",
> >       "safari >= 14"
> >     ],
> >     "development": [
> >       "last 1 chrome version",
> >       "last 1 firefox version",
> >       "last 1 safari version"
> >     ]
> >   },
> > ```
> 
> Fkkk. You saved my life. Thanks.

this solve my problem too!! Even I'm in other similar situation! thx.

**Comment by Muhammad-Altabba** [comment]
Hi all,
This issue is because React uses babel for transpilation. And babel has issues with bigint as you can find here: https://github.com/babel/babel/issues/13109
And so, not only react applications will face this issues. But also any application that uses babel unless it add the `browserslist` to package.json as described in the issue: https://github.com/babel/babel/issues/13109 and as pointed in: https://github.com/web3/web3.js/issues/6187#issuecomment-1601223430.

However, we will try to overcome this by avoid using `**` with BigInt. So, in the next version there would be no need to add something to your package.json.

**Comment by Muhammad-Altabba** [comment]
The code has been modified so this issue should not be present once the next release takes a place. 

If anyone still face this issue, one of the following should resolve it:
- If you are using web3.js version <= 4.1.2, apply this: https://github.com/web3/web3.js/issues/6187#issuecomment-1601223430
- Update web3.js version to `4.2.0`

However, if one of the above did not solve your issue. Please provide the full details and steps to replicate the case. And preferably provide your code at a cloude IDE.
