### ISSUE TITLE
1.8.0 web3.utils.sha3 output change

### ISSUE THREAD

**Issue by invissiblecat** [ethereum/web3.js#6199]
I have a project where some hash is being calculated using `web3.utils.sha3` function and stored in blockchain. Now I need to recalculate it using data I have on backend and retrieve data from smart contract. By accident, on the backend I used an older version of web3 (1.3.4). It turned out that sha3 function has changed somewhere in between 1.3.4 and 1.8.0 so now it calculates hash differently. 

For example, I have a following string: `0xe5191113941947ec4aa8cf1335c488a334f87a2a24a9c1d47f3957fe1ed4e5e700007d3bd29486c1d84fbbc1dfa717e8a80629c40e3b69abfd63829d828051555802232`.
 
1.3.4 `sha3` result: `0xd572e76ec4d6e78f396689fa325149e8cf70e7f39b15aff428da61e000d86418`
1.8.0 `sha3` result:  `0xbbf9241959e0b98ece63699a6519cbfd5a021dd3f5de405ebbfa024d90b2a16f`

All change I could find is [Updated sha3 and sha3Raw type definition to accept Buffer](https://github.com/web3/web3.js/blob/release/1.8.0/CHANGELOG.md#changed-20) (code difference can be found in this [comparison](https://github.com/web3/web3.js/compare/release/1.3.4...release/1.8.0#diff-a4ca995dceda554733d516972c314e4fefbb8affd41b0ac28357e77e1f24b772R485)).
It also can be [1.6.0 Partially replace usage of eth-lib with ethereumjs-util](https://github.com/web3/web3.js/blob/release/1.8.0/CHANGELOG.md#160).

It doesn't seem like conceived change. I believe that hashing functions should not change the way they behave. Tell me in details if I am wrong.

**Comment by jdevcs** [comment]
@invissiblecat related issue and further info : https://github.com/web3/web3.js/issues/4698

**Comment by jdevcs** [comment]
There was a bug/issue that was fixed in older version of web3 and it caused this change. If you want to have same output I'll suggest to use older version of 1.x web3.

**Comment by invissiblecat** [comment]
@jdevcs yeah, I eventually stuck to the older version of web3 to get my app working. this kind of change seemed strange, thanks for providing more info to me
