### ISSUE TITLE
GetBlock returning BigInts instead of Numbers

### ISSUE THREAD

**Issue by andrewm1tchell** [ethereum/web3.js#6208]
#### Expected behavior
 web3.eth.getBlock(16589615).then(function(result) {
                                                    console.log(result);
});
returns something like this, where the Numbers do not have a lowercase "n" at the end (signifying BigInt).
<img width="1064" alt="image" src="https://github.com/web3/web3.js/assets/5866724/35e48165-e234-48b3-b667-1c7e6cdac7a7">

#### Actual behavior
 web3.eth.getBlock(16589615).then(function(result) {
                                              console.log(result);
});
Returns this:
<img width="637" alt="image" src="https://github.com/web3/web3.js/assets/5866724/39bbb2e5-9b79-448a-8955-a5869658a99d">
Notice that timestamp is a BigInt in the response^ 
This does not match the documentation. (https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getblock)

#### Steps to reproduce the behavior

1.  Paste this code into a "test.html" file:
<head>
    <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
</head>
<script>
        const ethNetwork = 'https://mainnet.infura.io/v3/dd434b70c6a7487c92efdded13e7f1a3';
        const web3 = new Web3(new Web3.providers.HttpProvider(ethNetwork));
         web3.eth.getBlock(16589615).then(function(result) {
                                                    console.log(result);
                                                });
</script>
2. Open the file, view the console.

#### Environment

Using web3.js

**Comment by jdevcs** [comment]
@andrewm1tchell  you are using web3 4.x and referring 1.x documentation, 

In web3 4.x you can get number format in result by explicitly specifying format type: 

[web3.eth.getBlock](https://docs.web3js.org/api/web3-eth/class/Web3Eth#getBlock)(16589615, false, { number: [FMT_NUMBER](https://docs.web3js.org/api/web3-types/enum/FMT_NUMBER).NUMBER , bytes: FMT_BYTES.HEX })
