### ISSUE TITLE
[4.x] Rollout own Abi coder to replace ethers abi coder

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#6211]
#### Feature
- own performant abi coder with good error handling

Some design choices I've made:
- use uint8array everywhere to avoid 0x prefixes nightmare and to make it more performant
- detailed error handling to enable user to locate error

Tasks:
- [ ] implement all basic encoders
- [ ] implement complex encoders
- [ ] implement all basic decoders
- [ ] implement complex decoders
- [ ] add unit tests using ethers test suite

I've started working on it in a branch `feat/abi-coder` (it was old branch that got rebased so some stuff is not aligned). I plan to work on it in my spare time. If you decide to pick it up, we can divide tasks.

**Comment by shrpne** [comment]
What do you think about using https://github.com/wagmi-dev/abitype instead?

**Comment by mpetrunic** [comment]
> What do you think about using https://github.com/wagmi-dev/abitype instead?

Those are just abi types not abi coder which we already have our own^^
