### ISSUE TITLE
Eth Subscription Manager does not allow custom subscriptions

### ISSUE THREAD

**Issue by zk-doge** [ethereum/web3.js#6223]
#### Expected behavior
```
const web3Sub = new Web3("ws://mynode:8546");
web3Sub.eth.subscribe("myRpcSubscriptionName");
```
Should work as for standard eth subscriptions

#### Actual behavior
web3_subscription_manager throws: `SubscriptionError: Invalid subscription type`

#### Environment

web3js v 4.0.1

**Comment by jdevcs** [comment]
related https://github.com/web3/web3.js/issues/5668

**Comment by Muhammad-Altabba** [comment]
> related #5668

Thanks @jdevcs 
It seems to me exactly the same as #5668. I will work on it...
