### ISSUE TITLE
[4.x] how to subscribe to custom events

### ISSUE THREAD

**Issue by damartripamungkas** [ethereum/web3.js#6225]
i want to subscribe to a special event like "newPendingTransactions" and have a true/false BOOLEAN parameter, i have tried the code below but it failed

```javascript
const initSubscribe = await web3Init.eth.subscribe("newPendingTransactions", true);
initSubscribe.on("connected", () => console.log("subscribe connected"));
initSubscribe.on("data", (txObj) => console.log(txObj));
initSubscribe.on("error", (err) => console.log(`subscribe error: ${err}`));
```

#### Environment
web3.js version 4.0.1-rc.1
node.js version 20.3.1

**Comment by luu-alex** [comment]
Hi there @damartripamungkas  this seems like a bug. We'll get someone on the team to work/discuss this further. thank you for reporting this

**Comment by Muhammad-Altabba** [comment]
Thanks @luu-alex  
It seems to me exactly the same as #5668. I will work on it...

I will write a guide for this issue `how to subscribe to custom events` and I will keep this issue open to track this guide writing. I will work on the guide after closing #6223.

**Comment by Muhammad-Altabba** [comment]
Hello @damartripamungkas 
The guide is ready at https://docs.web3js.org/guides/events_subscriptions/custom_subscriptions. And this functionality is currently available with the `web3@dev` version. And it will be available at the next release version.
