### ISSUE TITLE
Please add the documentation link to the project description (About section)

### ISSUE THREAD

**Issue by mlibre** [ethereum/web3.js#6231]
#### Expected behavior

Can find documentation link (https://web3-js-docs.pages.dev/) in the `About` section in GitHub:

![image](https://github.com/web3/web3.js/assets/8473036/3d46de41-f1ae-4b03-bf37-81982051e772)

#### Actual behavior

No link

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by Muhammad-Altabba** [comment]
Many thanks @mlibre pinging us regarding this,

**Comment by jdevcs** [comment]
added Thanks
