### ISSUE TITLE
Cannot read properties of undefined (reading 'n')

### ISSUE THREAD

**Issue by rvarhola** [ethereum/web3.js#6232]
Hi all. I have installed web3 v4.0.1 on aws lambda function, and i have run code

`const { Web3 } = require('web3');`

#### Expected behavior

Installation and build completes successfully.

#### Actual behavior

Throws error
(See Logs below)

#### Logs
```
"TypeError: Cannot read properties of undefined (reading 'n')",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/web3-eth-accounts/lib/commonjs/tx/constants.js:55:51)",
        "    at Module._compile (node:internal/modules/cjs/loader:1196:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1074:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:909:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1098:19)",
        "    at require (node:internal/modules/cjs/helpers:108:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/web3-eth-accounts/lib/commonjs/account.js:35:24)",
        "    at Module._compile (node:internal/modules/cjs/loader:1196:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)"
```
#### Environment

aws lambda function
node - v16, 
architecture - x86_64

**Comment by Muhammad-Altabba** [comment]
Thanks @rvarhola for opening an issue.
Could you please provide more into the context? How can someone replicate this on his machine?
Or it would be best if you could please provide an example where this issue is present on a cloud editor like https://codesandbox.io/.

**Comment by mconnelly8** [comment]
Closing issue due to no response
