### ISSUE TITLE
Fix estimate gas tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6234]
- [ ] Fix estimate gas tests:

If from is included with low balance [this](https://github.com/web3/web3.js/actions/runs/5378976558/jobs/9765021066?pr=6226#step:5:457) error is thrown

**Comment by Spacesai1or** [comment]
I think [this](https://github.com/web3/web3.js/blob/ebd0c578d34795d7d5a2e3d1cedd3ae1c3031c68/templates/.secrets.json.tmpl#L16) address should be changed to `0x0000000000000000000000000000000000000000`
