### ISSUE TITLE
Some types are missing on v4 (`eth.personal` does not exist)

### ISSUE THREAD

**Issue by paulrostorp** [ethereum/web3.js#6236]
#### Expected behavior
Types should be there :)

#### Actual behavior
`eth.personal` is not defined. Other types are possibly missing too.

#### Steps to reproduce the behavior

on versions greater than 4, `eth.personal` is untyped:
<img width="747" alt="Screenshot 2023-06-27 at 18 01 48" src="https://github.com/web3/web3.js/assets/1866649/41981522-7814-4c66-b75c-9f7907bce5ab">

#### Environment
nodejs 18
web3 `4.0.1`, `4.0.2`
typescript `4.9.5`

**Comment by jdevcs** [comment]
@paulrostorp thanks for testing, the fix will be available with `dev` tag in npm once #6245 PR is merged and also in next web3 patch release.
