### ISSUE TITLE
Web3 Expo support

### ISSUE THREAD

**Issue by yao8384** [ethereum/web3.js#6247]
## Web3.js`s version comes '4.x' now;  We can still only import the web3 browser version in our Vite and TS project;
the 'vite:import-analysis' plugin will throw an error, telling me the 'web3 'package is not exporting web3.min.js;

###  so i have a idea;  as we add a declaration in web3 package.json ; and next, everything are working fine; codes are as follow:
``` js
"exports": {
".": {
	"types": "./lib/types/index.d.ts",
	"import": "./lib/esm/index.js",
	"require": "./lib/commonjs/index.js"
},
 // Add this line. it can solve errors from vite-scan;!!!
"./dist/web3.min.js": "./dist/web3.min.js"
},
```
#### how i use web3.js 4.x  in my vite&ts project;
``` js 
resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      web3: "web3/dist/web3.min.js",
    },
  }
```

#### Environment
- Web3.js 4.0.1
- vite & ts & vue3;
- windows 10;

**Comment by Muhammad-Altabba** [comment]
Thanks @yao8384 for opening an issue for this.
We will look into it.

**Comment by olafkrawczyk** [comment]
Hi, I think it also affects web3-validator package.  When trying to use web3-validator in Expo the package is resolved as undefined. After adding this line to it's package.json it works ok.
<img width="569" alt="image" src="https://github.com/web3/web3.js/assets/9090094/d401ff57-d2bd-443c-959b-d8c973095c0a">

**Comment by khalidmaquilang** [comment]
i am receiving this error 
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
```

**Comment by jdevcs** [comment]
We should test 4.x builds with Expo.

**Comment by Rag0n** [comment]
I use this patch for the latest web3 4.4.0 & bare expo 49.0 & RN 0.72.9:
<img width="804" alt="CleanShot 2024-02-10 at 11 48 22@2x" src="https://github.com/web3/web3.js/assets/1951128/9819120f-0066-44e4-a31d-8f51234232e4">
