### ISSUE TITLE
4.x Web3 custom RPC plugin Tutorial 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6261]
4.x Web3 plugin tutorial for custom RPC methods ( for motivating community to use plugin feature in place of web3.extend ), also link this in migration guide under `web3.extend` part.

**Comment by Spacesai1or** [comment]
Essentially a guide for this [plugin example code](https://github.com/web3/web3.js/blob/4.x/tools/web3-plugin-example/src/custom_rpc_methods.ts)
