### ISSUE TITLE
Rollout own ABI coder: add unit tests using ethers test suite

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6273]
**Feature**
- own performant abi coder with good error handling

**Some design choices previously chosen:**
- use uint8array everywhere to avoid 0x prefixes nightmare and to make it more performant
- detailed error handling to enable user to locate error

**Task:**
- [x] add unit tests using ethers test suite

Tasks started at`feat/abi-coder` (it was old branch that got rebased so some stuff is not aligned). Marin plans to work on it in his own time, but can split tasks.

**Comment by mconnelly8** [comment]
#6211

**Comment by jdevcs** [comment]
added ethers tests in abi PR , all encode and decode parameters tests are passing now.
