### ISSUE TITLE
Web3 4.x Testing with Hardhat

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6277]
- [ ]  Migrate Hardhat to the latest 4.x release and share any bugs discovered.

**Comment by jdevcs** [comment]
https://github.com/NomicFoundation/hardhat/pull/4178

**Comment by jdevcs** [comment]
https://github.com/NomicFoundation/hardhat/pull/4017

**Comment by Muhammad-Altabba** [comment]
It is done here: https://github.com/NomicFoundation/hardhat/pull/4570
