### ISSUE TITLE
Some CI jobs fails occasionally and pass after retry and lots of warning logs make it harder to investigate

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6290]
Some of the tests are failing sometimes. Additionally, there are many logs that do not make it easy to investigate the issues.
A sample failing test:
https://github.com/web3/web3.js/actions/runs/5585779852/jobs/10209097808

Regarding the warnings, for example, the following could be handled by adding an optional parameter to the Web3 constructor that prevents consoling this warning.
> web3:     console.warn
web3:       NOTE: web3.js is running without provider. You need to pass a provider in order to interact with the network!

**Comment by jdevcs** [comment]
also stale rule needs to be fixed: https://github.com/web3/web3.js/actions/runs/5585779741/workflow
