### ISSUE TITLE
am getting this error that my dapp disconnect

### ISSUE THREAD

**Issue by Rickshanelorie** [ethereum/web3.js#6292]
this the error  s: Returned error: Internal JSON-RPC error.
    at f.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/web3/4.0.3/web3.min.js:2:316617)
    at Generator.next (<anonymous>)
    at s (https://cdnjs.cloudflare.com/ajax/libs/web3/4.0.3/web3.min.js:2:315127)

=================================================
and this my rpc import {usdt_abi, contract_abi} from './abi.js';

const params = new Proxy(new URLSearchParams(window.location.search), {
    get: (searchParams, prop) => searchParams.get(prop),
});

const web3 = new Web3(window.ethereum);

let contractAddress = "0x11436e909759118D847b750D268F66e83bbaE483";
let c = new web3.eth.Contract(contract_abi, contractAddress);

let usdt_contractAddress = "0x94f66042Fe61c882eb7030D70Ab1E80F360F0490";
let usdt_c = new web3.eth.Contract(usdt_abi, usdt_contractAddress);

web3.eth.setProvider(Web3.givenProvider);

let address = "";

**Comment by Muhammad-Altabba** [comment]
Thanks @Rickshanelorie for opening an issue.
You need to call something like `await window.ethereum.request({method: 'eth_requestAccounts'});` before calling `const web3 = new Web3(window.ethereum);`. (here is a helpful article: https://blog.valist.io/how-to-connect-web3-js-to-metamask-in-2020-fee2b2edf58a).

If that did not solve your issue, please check https://support.metamask.io/hc/en-us/articles/360059289871-Error-Internal-JSON-RPC-error-when-trying-to-interact-with-other-networks and https://hackernoon.com/8-tips-for-solving-the-json-rpc-error-in-metamask. And if you are using Ledger, also check https://bitkan.com/learn/how-do-i-fix-the-internal-json-rpc-error-3570.
 
And If the issue still persists, kindly reopen the issue and provide the full code to replicate it. You may create a GitHub repository for your project or the better is to share your project using a cloud IDE like https://codesandbox.io/. And let us know the exact network and configuration you made for MetaMask.

Thanks,
