### ISSUE TITLE
[docs] Tree Shaking Guide not available

### ISSUE THREAD

**Issue by meri-maki** [ethereum/web3.js#6295]
#### Expected behavior

Wanted to read about tree shaking when I found the link on github
![image](https://github.com/web3/web3.js/assets/97887955/97d1e682-b0f3-4115-ab0b-6bb71a565f39)

#### Actual behavior
https://docs.web3js.org/docs/guides/web3_tree_shaking_support_guide

Page is not available

**Comment by tiseysoft** [comment]
Hi, thank you for pointing this out, 

If any maintainers would like me to add content about the tree shaking guide, I would love to work on it

**Comment by Muhammad-Altabba** [comment]
Hi @meri-maki @tiseysoft ,
Sorry, the guide has been moved to https://docs.web3js.org/guides/advanced/web3_tree_shaking_support_guide/ But the link was not updated.

It would be great if you @tiseysoft create an MR to update the link. And also, to write a guide or a tutorial for some of the needed stuff. More on this at https://github.com/web3/web3.js/discussions/6214

Thanks,

**Comment by tiseysoft** [comment]
Alright, thanks! 

would work on it immediately. Created a PR for the fixed issue.
