### ISSUE TITLE
how to import abi json file as const in typescript (web3js ^4.0.3)

### ISSUE THREAD

**Issue by rickiey** [ethereum/web3.js#6297]
I couldn't import abi file as const, in web3js v4 + ,it's must be "as const"
```
import * as contractABI from "../contract_abi/MyContract.json"

async function main() {

    // contractABI as const
    const sc = contractABI as const
```

`error TS1355: A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object literals`

**Comment by rickiey** [comment]
I don't want to paste ABI into the code

**Comment by rickiey** [comment]
same https://github.com/web3/web3.js/issues/6275

**Comment by Jenishgondaliya** [comment]
hii @rickiey 
 i have solution for that you can manually create a const assertion for the contract ABI

import * as contractABI from "../contract_abi/MyContract.json"
const sc: typeof contractABI = contractABI as any as typeof contractABI;

async function main() {
  // Now you can use sc as a const object
}

**Comment by Muhammad-Altabba** [comment]
Hallo @rickiey ,

First, assign your ABI to a variable inside a .ts file like:

```ts
// file name my-contract.ts

const MyContractAbi = [ YOUR_ABI... ] as const 
```

Then this is how to import the ABI:
```ts
import { MyContractAbi } from '../my-contract';
```

Please let me know if this does not answer your question.

And please close the issue if this is what you were seeking.

Thanks,

**Comment by rickiey** [comment]
Thanks
