### ISSUE TITLE
Issue on contract.d.ts 

### ISSUE THREAD

**Issue by rosarioborgesi** [ethereum/web3.js#6298]
Hello,
I am experimenting an issue on Typescript when I call:

`contract = await new web3.eth.Contract(JSON.parse(abi)) 
        .deploy({ data: byteCode, arguments: ['My String'] }) `

Passing  `arguments: ['My String']` to the deploy method the compiler complains:` Type 'string' is not assignable to type 'undefined'`

In the file contract.d.ts at node_modules/web3-eth-contract/lib/commonjs/contract.d.ts
I have replaces the line 251:` arguments?: ContractConstructorArgs<Abi>; ` with ` arguments?: unknown[]; ` and it works now but I am not sure that this was good.

The file which has the issue is[ inbox.test.ts](https://github.com/RosarioB/ethereum-simple-contract/blob/issue%236298_web3.js/src/test/inbox.test.ts).

And you can find the whole repository [here](https://github.com/RosarioB/ethereum-simple-contract/tree/issue%236298_web3.js).

**Comment by luu-alex** [comment]
Hi there, thank you for reporting this issue. Your solution should be able to fix it for now but i'll investigate further.

**Comment by avkos** [comment]
Looks like this problem the same as [this one](https://github.com/web3/web3.js/issues/6275) (incorrect parsing types from ABI)

**Comment by mconnelly8** [comment]
@RosarioB, we will be tracking this in #6275 and closing this one.
