### ISSUE TITLE
100% test coverage

### ISSUE THREAD

**Issue by debris** [ethereum/web3.js#63]
develop: [![Coverage Status Develop][coveralls-image-develop]][coveralls-url-develop]
master: [![Coverage Status Master][coveralls-image-master]][coveralls-url-master]
pull requests are welcomed

[coveralls-image-develop]: https://coveralls.io/repos/ethereum/ethereum.js/badge.svg?branch=develop
[coveralls-url-develop]: https://coveralls.io/r/ethereum/ethereum.js?branch=develop

[coveralls-image-master]: https://coveralls.io/repos/ethereum/ethereum.js/badge.svg?branch=master
[coveralls-url-master]: https://coveralls.io/r/ethereum/ethereum.js?branch=master

**Comment by chevdor** [comment]
I got a little more than +2% on master :smile:

**Comment by chevdor** [comment]
Pull request #104 is adding a few tests and organising the test folder.

**Comment by chevdor** [comment]
We need to decide whether we include the RPC tests within this repo.
If we do, we will have to use something like nock. I experimented with that and it fails "in the browser".
Topic discussed here: https://github.com/pgte/nock/issues/150

If we decide to exclude the RPC tests, then we won´t reach 100%
