### ISSUE TITLE
Cannot access Error object and sendTransaction.on(error) not firing

### ISSUE THREAD

**Issue by meri-maki** [ethereum/web3.js#6300]
#### Expected behavior
While working on error handling I noticed that I'm catching transaction errors in this format:

```
vt: Returned error: MetaMask Tx Signature: User denied transaction signature.
```

With this error I cannot access error code and other useful staff..

Tried adding web3.eth.sendTransaction.on('error', (error) => {} as written in docs, and access the innerError object 
(https://docs.web3js.org/guides/basics/sign_and_send_tx/promi_event)

Tested with transaction cancellation but the event is not firing, but it should, right?

#### Steps to reproduce the behavior
```
	const onSubmitForm = (e) => {
		e.preventDefault()
		resetPurchase()

		const amount = Math.max(0, parseFloat(ethInputAmount))
		if (amount < 0.000001 || !amount) {
			return
		}

		setPurchaseLoading(true)

		let selectedAccount

		authorize({
			force: false,
			metaMaskDeeplinkUrl: appendParamsToUrl(window.location.href, {
				[ethAmountQueryKey]: amount,
			}),
		})
			.then((res) => {
				web3 = res
				return getAuthorizedAccounts()
			})
			.then(async (accounts) => {
				selectedAccount = accounts[0]
				let transaction = {
					from: selectedAccount,
					to: window.toonAppData.address,
					data: "0x64edfbf0e2c706ba4a09595315c45355a341a576cc17f3a19f43ac1c02f814ee",
					value: web3.utils.toWei(String(amount), "ether"),
				}
				transaction = { ...transaction, gas: await web3.eth.estimateGas(transaction) }
				return web3.eth
					.sendTransaction(transaction)
					.on("transactionHash", function (txHash) {
						setPurchaseLoading(false)

						if (txHash !== undefined) {
							setEthInputAmount("")
							scheduleTxCheckStatus(txHash)
						}
					})
					.on("error", (error) => {
						console.log(error.innerError)
						console.log(error.code)
						console.log(error.message)
						throw new Error(error.innerError)
					})
			})
			.then(function (receipt) {
				console.log("receipt2", receipt)
			})
			.catch((error) => {
				setPurchaseLoading(false)


				console.log(error)
				setPurchaseError({ status: true, message: error.message })
			})
	}
```

the logic above was mentioned in this issue (https://github.com/web3/web3.js/issues/6249)
and previous logic was handling errors correctly (returning Error object, not vt)

#### Environment

"web3": "^4.0.3",
"web3-eth": "^4.0.3"

**Comment by luu-alex** [comment]
Thank you for submitting this error, it seems odd that our error is not catching this. I'll take a look into this

**Comment by meri-maki** [comment]
@luu-alex hi! could it be the error in the code itself? or is on.error definetely not catching anything?

**Comment by meri-maki** [comment]
any news...?

**Comment by luu-alex** [comment]
Hey there, sorry for the long response. The issue `vt: Returned error: MetaMask Tx Signature: User denied transaction signature.` will not fire an 'error' event. When using the method `sendTransaction` The errors web3js will listen to will be coming from the rpc node response, not from metamask. So you should not expect an error event to be fired. I hope this answers your question and if you have anymore feel free to ask. Thanks for your patience

**Comment by meri-maki** [comment]
Okay, but if you have insufficient funds, for example, should it fire an error?

Here are a few examples of errors I get:

1. insufficient funds with MM extension for Chrome - I get correct error first (with correct codes and stuff) and then carching VT
<img width="535" alt="Снимок экрана 2023-07-27 в 10 43 19" src="https://github.com/web3/web3.js/assets/97887955/385ea87f-4dc9-4941-9ab7-f4e103d74c41">

2. same MM but denied transaction
<img width="540" alt="Снимок экрана 2023-07-27 в 10 43 39" src="https://github.com/web3/web3.js/assets/97887955/9c8a9ab7-7f00-4edd-9a22-04272e3c236f">

3. Connected with WalletConnect with Rainbow app - first cancelled, then funds
<img width="517" alt="Снимок экрана 2023-07-27 в 10 46 21" src="https://github.com/web3/web3.js/assets/97887955/ecf32410-9ac0-4246-9659-cc185d001819">

4. This is example with "web3": "^1.8.0", "web3-eth": "^1.8.0" and a bit different logic I will share below
As you can see, I'm catching correct error object and not VT returned error
<img width="526" alt="Снимок экрана 2023-07-27 в 10 47 28" src="https://github.com/web3/web3.js/assets/97887955/cfb5728f-7546-4aab-ae00-0fd484d93738">


Here is the code with old logic but it was catching errors correctly and that way I could easily filter errors by their codes and return respective UI
Since updating to the latest web3, I thought that error catching behavior would be the same but for some reason it's not...
```
const onSubmitForm = (e) => {
		e.preventDefault()

		const amount = Math.max(0, parseFloat(ethInputAmount))
		if (amount < 0.000001 || !amount) {
			return
		}

		setPurchaseLoading(true)

		let selectedAccount

		debounce("purchase", 400, function () {
			const amount = Math.max(0, parseFloat(ethInputAmount))

			authorize({
				force: false,
				metaMaskDeeplinkUrl: appendParamsToUrl(window.location.href, {
					[ethAmountQueryKey]: amount,
				}),
			})
				.then((res) => {
					web3 = res
					return getAuthorizedAccounts()
				})
				.then((accounts) => {
					selectedAccount = accounts[0]					

					return web3.eth
						.sendTransaction({
							from: selectedAccount,
							to: window.toonAppData.address,
							data: "0x64edfbf0e2c706ba4a09595315c45355a341a576cc17f3a19f43ac1c02f814ee",
							value: web3.utils.toWei(amount.toString(), "ether"),
						})
						.on("transactionHash", function (txHash) {
							setPurchaseLoading(false)

							if (txHash !== undefined) {
								setEthInputAmount("")
								scheduleTxCheckStatus(txHash)
							}
						})
				})
				.then(function (receipt) {
					console.log("receipt2", receipt)
				})
				.catch(function (err) {
					console.error(err)
					setPurchaseLoading(false)

					if (err.code === 4001) {
						return
					}
					setPurchaseError(true)
					setPurchaseErrorMessage(err.message)
				})
		})
	}
	```

**Comment by meri-maki** [comment]
@luu-alex hope it makes sense)

**Comment by luu-alex** [comment]
Ah I see what you, version 4 metamask errors are not returning properly with error and code like version 1 errors. This is definitely an issue. I'll take a look into this and update when I have a solution for this. Thank you for reporting this)

**Comment by meri-maki** [comment]
@luu-alex hi! any updates? )

**Comment by luu-alex** [comment]
Hey there! Sorry was away this week, I have a PR created and should be good to go for next week. thank you for waiting.

**Comment by luu-alex** [comment]
Hi there @meri-maki the PR has been merged and is now in the dev branch. web3@4.1.1-dev.622174c.0 as well it'll be part of next release. When catching the error, make sure to use `error.toJSON()` and the error and errorcode you will want will be apart of `error.toJSON().innerError`.

If theres any other issues please let me know.

**Comment by meri-maki** [comment]
Hi @luu-alex ! I updated to 4.1.0 and replaced 
 ```
.catch(function (err) {
					console.error(err)

				})
```

to 

```
.catch((error) => {
				const err = error.toJSON()
				console.log(err)

			})
```

Here is what i get in console...

<img width="606" alt="Снимок экрана 2023-08-17 в 16 05 37" src="https://github.com/web3/web3.js/assets/97887955/4f34855a-dcf0-4dcf-9fae-846ea273cc1f">


innerError object is undefined, the code is always 100...
I guess the issue remains, do i need to refactor the function itself? because .on(error) is still not working...

**Comment by luu-alex** [comment]
can you install the dev branch? https://www.npmjs.com/package/web3-eth/v/4.1.1-dev.622174c.0 `yarn add web3@4.1.1-dev.622174c.0` or `npm install web3@web3@4.1.1-dev.622174c.0` @meri-maki

**Comment by meri-maki** [comment]
@luu-alex do i need to add web3-eth of this version as well?

**Comment by meri-maki** [comment]
@luu-alex updated, still a no
maybe a repo will help? i will make one

**Comment by meri-maki** [comment]
@luu-alex here is the repo
https://github.com/meri-maki/web3-error

main component: https://github.com/meri-maki/web3-error/blob/main/src/components/widgets/Purchase%20Widgets/MintForm/MintForm.jsx

**Comment by meri-maki** [comment]
After updating to ```v4.1.1``` I'm able to access ```innerError``` object so finally RESOLVED

**Comment by meri-maki** [comment]
unfortunately, this is not working with transactions via WalletConnect wallets, but that's another story
![Снимок экрана 2023-08-22 в 14 43 27](https://github.com/web3/web3.js/assets/97887955/c1e899ac-63fc-4f8c-8025-7bbf26901ebd)
