### ISSUE TITLE
Duplicate "Data" and "Input" Fields in eth_call

### ISSUE THREAD

**Issue by 0xJchen** [ethereum/web3.js#6301]
#### Expected behavior
When using `eth_call` to a read-only function on contract, `param` fields should not contain duplicate fields.

Code:

```
const { Web3 } = require('web3');
const web3 = new Web3(`http://localhost:8545`); // or you can use alchemy rpc
const contractAbi = [{
  "inputs": [],
  "name": "getReserves",
  "outputs": [
    {
      "internalType": "int256",
      "name": "",
      "type": "int256"
    }
  ],
  "stateMutability": "view",
  "type": "function"
}]

const contractAddress = '0xc3d688B66703497DAA19211EEdff47f25384cdc3'; 

const contract = new web3.eth.Contract(contractAbi, contractAddress);

contract.methods.getReserves().call({}).then((values) => {
  console.log(values);
}
);
```
The expected payload should not duplicate `input` and `data` field.

#### Actual behavior

The actual request sent by web3js is:

```
  request: {
    jsonrpc: '2.0',
    id: '2914ddfa-c9d4-4bd2-8895-31a8064e6681',
    method: 'eth_call',
    params: [
      {
        to: '0xc3d688B66703497DAA19211EEdff47f25384cdc3',
        input: '0x0902f1ac',
        data: '0x0902f1ac'
      },
      '0x10e91ba'
    ]
  }
}
```

The alchemy backend deals with the duplicate fields problem. For others that use Rust json pkg `https://github.com/paritytech/jsonrpsee`, it will reports the following error:

```
/home/ubuntu/test/node_modules/web3-core/lib/commonjs/web3_request_manager.js:258
                throw new web3_errors_1.InvalidResponseError(response, payload);
                      ^

InvalidResponseError: Returned error: Invalid params
    at Web3RequestManager._processJsonRpcResponse (/home/ubuntu/test/node_modules/web3-core/lib/commonjs/web3_request_manager.js:258:23)
    at Web3RequestManager.<anonymous> (/home/ubuntu/test/node_modules/web3-core/lib/commonjs/web3_request_manager.js:156:29)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/test/node_modules/web3-core/lib/commonjs/web3_request_manager.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  innerError: {
    code: -32602,
    message: 'Invalid params',
    data: 'duplicate field `data` at line 1 column 78'
  },
  code: 101,
  data: 'duplicate field `data` at line 1 column 78',
  request: {
    jsonrpc: '2.0',
    id: '2914ddfa-c9d4-4bd2-8895-31a8064e6681',
    method: 'eth_call',
    params: [
      {
        to: '0xc3d688B66703497DAA19211EEdff47f25384cdc3',
        input: '0x0902f1ac',
        data: '0x0902f1ac'
      },
      '0x10e91ba'
    ]
  }
}
```

#### Steps to reproduce the behavior

run the above code, and use an rpc from a rust implementation of the Ethereum client (like RETH).

#### Logs

as above

#### Environment

web3js v4.0.3, node 16

**Comment by luu-alex** [comment]
Hi there! thank you for the issue. We have a [PR ](https://github.com/web3/web3.js/pull/6294)to deal with this in progress. There wont be both data and input fields filled in.

**Comment by 0xJchen** [comment]
Thank you. Great to hear that. Should I close this issue?

**Comment by luu-alex** [comment]
Yup, i'll close it now. Thanks, and i'll give you a heads-up when this is merged

**Comment by Muhammad-Altabba** [comment]
Thanks all,
And for those who come to this issue in the future, here is the conclusion as shared in https://github.com/paradigmxyz/reth/issues/3875#issuecomment-1675535067:
> - The last version of `reth` ([Reth v0.1.0-alpha.5](https://github.com/paradigmxyz/reth/releases/tag/v0.1.0-alpha.5))  no more throws when facing this case. (Thanks @mattsse for making this possible at this MR: https://github.com/paradigmxyz/reth/pull/3911):
> - Additionally, the next version of web3.js (v4.1.0) will not fill both `data` and `input` (done in this MR: https://github.com/web3/web3.js/pull/6294).
> 
> So, upgrading to the latest `reth` or upgrading `web3.js` to v4.1.0 once it is released, would resolve this issue.
