### ISSUE TITLE
getPastEvents check ''allEvents'' instead of "ALLEVENTS"

### ISSUE THREAD

**Issue by AndreyShashlovDev** [ethereum/web3.js#6306]
web3 4.0.3

it is not possible to subscribe to all events of the contract.

```
const contract = new this.web3.eth.Contract(abi, address)
this.contract.events.allEvents({fromBlock: 'latest'})
```

inside the _createContractEvent method, the getPastEvents method is called with the abi.name argument.

but in getPastEvents code checks for (abi.name) "allEvents" instead of 'ALLEVENTS'
https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-contract/src/contract.ts#L720

but actually for function 'allEvents' we have name of event ALLEVENTS
https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-contract/src/constants.ts#L22
 
"ALLEVENTS" created here https://github.com/web3/web3.js/blob/4.x/packages/web3-eth-contract/src/contract.ts#L859

**Comment by avkos** [comment]
Thank you for finding these things. We will work on it as soon as possible.

**Comment by jcislo** [comment]
This is causing me some struggle as well. When I input my event name in "getPastEvents" I receive a type-error on the event name.

**Comment by jdevcs** [comment]
@AndreyShashlovDev `this.contract.events.allEvents` works without filter, but with filter it throws error:
```
/web3-eth-contract/lib/commonjs/contract.js:627
                    sub.emit('error', new web3_errors_1.SubscriptionError('Failed to get past events.'));
                                      ^

SubscriptionError: Failed to get past events.
```

are you experiencing same problem?

**Comment by jdevcs** [comment]
> This is causing me some struggle as well. When I input my event name in "getPastEvents" I receive a type-error on the event name.

@jcislo could you share a code snippet for reproducing it?

**Comment by SmartArray** [comment]
I get the `Failed to get past events` error. I did some digging and found out that the underlying issue is `Web3ContractError: Event ALLEVENTS not found`

That's because it compares the event type with `allEvents`, instead of `ALLEVENTS`. I might publish a PR soon

**Comment by jdevcs** [comment]
@SmartArray which web3 version you used? a fix is published yesterday.
