### ISSUE TITLE
The returned logs of a contract event are not of an event object 

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6312]
Investigate why the test `"should return transaction hash, logs and receipt when using synchronised transactions"` at  https://github.com/nazarhussain/truffle/blob/656263aadf21612b17829483d7376eb7afbe63aa/packages/artifactor/test/contracts.js#L195 is failing with 4.x.

un-skip the test to investigate the error:
   "AssertionError: expected 'ExampleEvent' to equal undefined"
The issue seems to be that the returned logs are not of an event.
   (The returned log does not include the properties: `event` and `args`)
```
  logs: [
    {
      address: '0x608fcae953f6ecbb979bd670260fea9052a7e527',
      blockHash: '0x3a5f39352e0fd37c6a0b7870b16d585a10dde1fec30b0e1b64b6065caef5469a',
      blockNumber: 2n,
      logIndex: 0n,
      removed: false,
      transactionHash: '0xd9ad9f8a3d74c8bad000249977ec60d8313b2e4bbc389de06709a45cd5e0cb31',
      transactionIndex: 0n
    }
  ]
```

**Comment by jdevcs** [comment]
Related issue : https://github.com/web3/web3.js/issues/6351 should be fixed under this issue.
