### ISSUE TITLE
Incorrect logs issue in latest web3 4.0.3

### ISSUE THREAD

**Issue by navdeep1998** [ethereum/web3.js#6314]
Hi 
Firstly I've created instance with web3 and after that I'm trying to get all Past events .And got the all events successfully ,but the major issue is that , sometime getting the wrong format of logs and values are appended n in all values.Like :- block number : 176367475n.Whenever i'v downgraded the web3 verision than  everything is working fine.Below I've attached the screenshot of incorrect logs.Please help If anybody facing the same issue and reslove  same.
![Screenshot from 2023-07-26 18-11-03](https://github.com/web3/web3.js/assets/66154486/1a74f57c-b64c-4ac5-bebe-6747f2d2047d)
Thanks in advance

**Comment by Muhammad-Altabba** [comment]
Hello @navdeep1998 and thanks for opening an issue.

And you stated that you face 2 problems: 
> sometime getting the wrong format of logs and values are appended n in all values

But sorry it is not clear to me. So, could you help clarify:

- What is the exact `wrong format of logs` that you are mentioning?
- And what are those you described as `values are appended n in all values`. What else than blockNumber that you are getting and you think you should not?
- And why do you think getting the `blockNumber` is an issue?
 
 Thanks again,

**Comment by navdeep1998** [comment]
Hi @Muhammad-Altabba 

For  now i have no screenshot of the wrong format  and I'm getting this issue earlier but if i am facing this issue
again i'll update you and correct me if i'm wrong.please let me know if i
have an event where the one param is amount and its respective value is
1000000n.Than how i can manage this. And please check the screenshot again
all values have n at the end.please let me know if it is not an issue.

Thanks

**Comment by Muhammad-Altabba** [comment]
I got you now. It seems you are confused by the `n` at the end of the numbers and you thought it is wrong.
Web3.js v4 uses the `BigInt` data type as stated in the migration guide: https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_eth_migration_guide

To learn more about the `BigInt` data type I suggest you check this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

I will close this issue now. However, if you still think there is an issue. Then, please, reopen the issue and provide a fully working sample code, and point to the line where the issue present and what is the exact error/logs you are getting.

Thanks,

**Comment by navdeep1998** [comment]
Okay thanks
