### ISSUE TITLE
`soliditySha3` behaves differently on 4.x when one of the values is `BN` or a string that contains a number

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6327]
The function `soliditySha3` behave differently on 4.x when one of the values is BN or a string that contains a number.

#### Steps to reproduce the behavior

Import with 4.x:
```js
import * as Web3Utils from "web3-utils";
```
Import with 1.x:
```js
import Web3Utils from "web3-utils";
```

The rest of the code is the same:
```js
import BN from "bn.js";

let args: any[] = ["0x70696e67", 0];
let sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

args = ["0x70696e67", "0"];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

args = ["0x70696e67", new BN(0)];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

document.writeln("<br />");
document.writeln("<br />");

// a value of 10

args = ["0x70696e67", 10];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

args = ["0x70696e67", "10"];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

args = ["0x70696e67", new BN(10)];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);

```

#### Logs

Output with 1.10.0: 
> 0xe54a278c69f07b6b4f0736dc55c389cd2d3f31365b090c9f76a414fb51552c53 0xe54a278c69f07b6b4f0736dc55c389cd2d3f31365b090c9f76a414fb51552c53 0xe54a278c69f07b6b4f0736dc55c389cd2d3f31365b090c9f76a414fb51552c53

> 0x418e921c5c859d5f560b89ad03a6672907d66de336392a5178ea69281feff40a 0x418e921c5c859d5f560b89ad03a6672907d66de336392a5178ea69281feff40a 0x418e921c5c859d5f560b89ad03a6672907d66de336392a5178ea69281feff40a

Output with 4.0.3: 
> 0xe54a278c69f07b6b4f0736dc55c389cd2d3f31365b090c9f76a414fb51552c53 0x7e3fb05ec35afb64b8c5e400b9e38d018e2080c7d9fcd78483354e85ee124985 0x081b33dbb559c5a1282758548b15c6fe0970613daef623844717969e19370c7f

> 0x418e921c5c859d5f560b89ad03a6672907d66de336392a5178ea69281feff40a 0x5e4b0e77f6bd34d1fb92f75f563e3afed530512616c4f4c777ffc098b5fd11a1 0xd024fcef68e90a093e62b68c99891ad2514db78c580ee4830a2ca2e2ef249901

#### Complet code
Using 4.x:
https://codesandbox.io/s/soliditysha3-4-x-hkxqpm?file=/src/index.ts 
Using 1.x:
https://codesandbox.io/s/soliditysha3-1-x-5rvxxg?file=/src/index.ts

**Comment by jdevcs** [comment]
It seems for param passed as string its treating it as string and not number, so makes sense for:
```
args = ["0x70696e67", "0"];
sha = Web3Utils.soliditySha3(...args);
document.writeln(sha);
```
to be different.

however for new BN(0), I think output should not change.

**Comment by jdevcs** [comment]
As we internally support BigInt in 4.x consistently, instead of BN external lib, so i'll suggest if any proj is using BN , it should convert that into BigInt first for above function: 
```
const BN = require('bn.js');
const bn = new BN('12345678901234567890');
const bi = BigInt(bn.toString());
```
and pass `bi` to web3.js , above PR has support of BigInt now for soliditysha3

**Comment by jdevcs** [comment]
@Muhammad-Altabba
