### ISSUE TITLE
waitForTransactionReceipt is checking for transactions forever for transactions that never complete

### ISSUE THREAD

**Issue by dannnnthemannnn** [ethereum/web3.js#6328]
#### Expected behavior
There is a way to cancel the waitForTransactionReceipt polling or a timeout

#### Actual behavior
There is no timeout or ability to cancel this call: 
https://github.com/web3/web3.js/blob/b77111264dbdacf34d0c9ebe803efddf372ce3f1/packages/web3-eth/src/utils/wait_for_transaction_receipt.ts#L37

The timeout just below it doesn't cancel the above in the "finally" block:
https://github.com/web3/web3.js/blob/b77111264dbdacf34d0c9ebe803efddf372ce3f1/packages/web3-eth/src/utils/wait_for_transaction_receipt.ts#L66

It seems like the pollTillDefined above just runs forever which would explain our eth_getTransactionReceipt calls repeating forever

#### Steps to reproduce the behavior

Call sendTransaction with a call that doesnt get a transaction receipt and see that it keeps checking for transactionreceipts repeatedly

**Comment by Muhammad-Altabba** [comment]
Thanks @dannnnthemannnn for pointing this out. We will work on it.
