### ISSUE TITLE
decodeParameter - value out of range

### ISSUE THREAD

**Issue by Sv3nskie** [ethereum/web3.js#6333]
here I error I keep getting, below I try to decode A transfer event 
"Transfer (index_topic_1 address from, index_topic_2 address to, uint256 amount)"

I am using web3.js V4.0.3 and node.js v18.17.0

```javascript
import Web3 from 'web3';

const web3 = new Web3();

const log = {
    address: '0x000000000482aa9817645c3d56aa2230f6573532',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x000000000000000000000000b1cb88b1a1992deb4189ea4f566b594c13392ada',
      '0x2753c6df35e9cf1fcdf1e46d9aa538330781bd6268a28841e724e514a3e975ad'
    ],
    data: '0x000000000000000000000000000000000000000000000000000000456f6d9f9e',
    blockNumber: 30547686n,
    transactionHash: '0x4cbf7c21e34bd2567c6f1fb0424061252ea90dd0f028c854f242a1ec43e2234d',
    transactionIndex: 92n,
    blockHash: '0x2b31703d233348dae5a6a827f73bfea045f3f8bc8cf2f1b276ca41f40d74093a',
    logIndex: 8303n,
    removed: false
};

try {
    const tokenAddress = log.address;
    console.log(tokenAddress)
    const from = web3.eth.abi.decodeParameter('address', log.topics[1]);
    console.log(from)
    const to = web3.eth.abi.decodeParameter('address', log.topics[2]);
    console.log(to)
    // Remove the "0x" prefix from the data before decoding it
    const value = web3.eth.abi.decodeParameter('uint256', log.data.slice(2));
    console.log(value)
    console.log({ tokenAddress, from, to, value });
} catch (error) {
    console.log(error);
};
```

the error I get 

```bash
NOTE: web3.js is running without provider. You need to pass a provider in order to interact with the network!
0x000000000482aa9817645c3d56aa2230f6573532
0xb1CB88B1a1992deB4189Ea4f566b594c13392Ada
AbiError: Parameter decoding error: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at decodeParametersWith (file:///C:/Users/hp/Documents/Sv3n/Work/DMC/scraperNew/node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:155:15)
    at decodeParameters (file:///C:/Users/hp/Documents/Sv3n/Work/DMC/scraperNew/node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:262:49)
    at Object.decodeParameter (file:///C:/Users/hp/Documents/Sv3n/Work/DMC/scraperNew/node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:326:48)
    at file:///C:/Users/hp/Documents/Sv3n/Work/DMC/scraperNew/test.js:26:29
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  innerError: undefined,
  code: 205
}
```

it seems to fail to decode the 'to' variable, but the log data is correct and web3js V1 can decode it perfectly.

**Comment by jdevcs** [comment]
@Sv3nskie for which 1.x version it was working for you?

I tested with 1.10.0 and got error:
```
null: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/p1/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/p1/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/p1/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at hexZeroPad (/p1/node_modules/@ethersproject/bytes/lib/index.js:274:16)
    at AddressCoder.decode (/p1/node_modules/@ethersproject/abi/lib/coders/address.js:40:65)
    at /p1/node_modules/@ethersproject/abi/lib/coders/array.js:109:31
    at Array.forEach (<anonymous>)
    at unpack (/p1/node_modules/@ethersproject/abi/lib/coders/array.js:88:12)
    at TupleCoder.decode (/p1/node_modules/@ethersproject/abi/lib/coders/tuple.js:74:60)
    at AbiCoder.decode (/p1/node_modules/@ethersproject/abi/lib/abi-coder.js:98:22)
    at ABICoder.decodeParametersWith (/p1/node_modules/web3-eth-abi/lib/index.js:310:30)
    at ABICoder.decodeParameters (/p1/node_modules/web3-eth-abi/lib/index.js:291:17)
    at ABICoder.decodeParameter (/p1/node_modules/web3-eth-abi/lib/index.js:280:17)
```

Its originating from one of our dependencies. 

seems `log.topics[1]` is not encoded address, are you sure you are providing correct abi type for it?

**Comment by jdevcs** [comment]
@Sv3nskie ?

**Comment by jdevcs** [comment]
we are removing abi dependency from v4.

**Comment by damartripamungkas** [comment]
how to hide log this from console?, I want to use Web3 only with url string without web3 provider : 
NOTE: web3.js is running without provider. You need to pass a provider in order to interact with the network!

**Comment by jdevcs** [comment]
@damartripamungkas for this feature create new issue in our repo and we can make all warnings controlled with flag.

**Comment by Muhammad-Altabba** [comment]
Hello all,
The `abi` that had been used was replaced. So, this issue is not suppose to happen again. So, I am closing this issue.
However, if you still facing this error, kindly reopen this issue and provide the full details (the exact version, steps and code snippets) to reproduce the issue.
Thanks,

**Comment by Mae6e** [comment]
this is my function for transaction details in log for bep20:
async getContractTransactionsByHash(network, transactionHash) {
        const web3 = this.initialWeb3Network(network);
        let rsponse = await web3.eth.getTransactionReceipt(transactionHash);

        let data = [];
        if (rsponse.status !== '1') {
            return data;
        }
        if (rsponse.logs && rsponse.logs.length > 0) {
            for (let i = 0; i < rsponse.logs.length; i++) {
                const item = rsponse.logs[i];
                if (item.topics[0] === '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
                    && item.data !== '0x') {
                    let txObject = {};
                    txObject.contract = item.address;
                    txObject.hash = transactionHash;

                    let transaction = web3.eth.abi.decodeLog([{
                        type: 'address',
                        name: 'from',
                        indexed: true
                    }, {
                        type: 'address',
                        name: 'to',
                        indexed: true
                    }, {
                        type: 'uint256',
                        name: 'value',
                        indexed: true
                    }],
                        item.index,
                        [item.topics[1], item.topics[2], item.data]);

                    txObject.from = transaction.from.toLowerCase();
                    txObject.to = transaction.to.toLowerCase();
                    txObject.value = transaction.value.toString();
                    data.push(txObject);
                }
            }
        }
        return data;
    }

**Comment by Mae6e** [comment]
this is my function for transaction details in logs for bep20:

`

        const web3 = this.initialWeb3Network(network);
        let rsponse = await web3.eth.getTransactionReceipt(transactionHash);
        let data = [];
        if (rsponse.status !== '1') {
            return data;
        }
        if (rsponse.logs && rsponse.logs.length > 0) {
            for (let i = 0; i < rsponse.logs.length; i++) {
                const item = rsponse.logs[i];
                if (item.topics[0] === '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
                    && item.data !== '0x') {
                    let txObject = {};
                    txObject.contract = item.address;
                    txObject.hash = transactionHash;

                    let transaction = web3.eth.abi.decodeLog([{
                        type: 'address',
                        name: 'from',
                        indexed: true
                    }, {
                        type: 'address',
                        name: 'to',
                        indexed: true
                    }, {
                        type: 'uint256',
                        name: 'value',
                        indexed: true
                    }],
                        item.index,
                        [item.topics[1], item.topics[2], item.data]);

                    txObject.from = transaction.from.toLowerCase();
                    txObject.to = transaction.to.toLowerCase();
                    txObject.value = transaction.value.toString();
                    data.push(txObject);
                }
            }
        }
        return data;

`

can use that too:
`

        if (item.topics[1])
            trx.from = web3.eth.abi.decodeParameter('address', item.topics[1]);

        if (item.topics[2])
            trx.to = web3.eth.abi.decodeParameter('address', item.topics[2]);

        if (item.data)
            trx.value = web3.eth.abi.decodeParameter('uint256', item.data);
`
