### ISSUE TITLE
v4 and CSP - still no workaround?

### ISSUE THREAD

**Issue by web3-anon** [ethereum/web3.js#6338]
Is there no v4 extension that can go through CSP? Is there any workaround? Been trying to find a solution for this for hours. I don't wanna go back to v1.

**Comment by mconnelly8** [comment]
Hey @web3-anon , can you explain more on what CSP is and send us a code snippit to reproduce this that would help.

**Comment by luu-alex** [comment]
@web3-anon What errors are you getting when creating an extension with web3js? There was a PR that was merged to remove the module that was giving us an issue with CSP but would love to know if the issue has changed

**Comment by jdevcs** [comment]
@web3-anon ?

**Comment by web3-anon** [comment]
Can you guys let me know which version I'm supposed to try? About the issue, it's the same as #6168

**Comment by jdevcs** [comment]
@web3-anon test with v4.x and share error details that you are facing.

**Comment by Muhammad-Altabba** [comment]
Hi all,
Closing this issue as it is in active for more than 1 month.
However, if you still facing this error, kindly reopen this issue and provide the full details (the exact version, steps and code snippets) to reproduce the issue.
Thanks,
