### ISSUE TITLE
How can this error callback obtain the status of the user rejecting the transfer, and under what circumstances will this error be triggered

### ISSUE THREAD

**Issue by xx237461269** [ethereum/web3.js#6340]
```ts
const sendObject = myContract.methods
    .transfer(receiving_address.value, amount)
    .send(
      { from: payment_address, gas: gas_limit, gasPrice: gas_price }
    );

  sendObject.on("error",function (error, receipt) {
      console.log(error, "error");
      console.log(receipt, "receipt");
      socket.value.send(
        JSON.stringify({
          transaction_hash: receipt.transactionHash || "",
          isPayError: true,
          orderId: query.orderId,
        })
```

#### Expected behavior

How can this error callback obtain the status of the user rejecting the transfer, and under what circumstances will this error be triggered

**Comment by Muhammad-Altabba** [comment]
Hello @xx237461269,
Generally speaking, in case of an issue while transferring, web3.js will provide you with the Error supplied by your provider, that is the wallet (like MetaMask) or the Ethereum node (like Ganache, geth, reth or Nethereum) that you are connected to. 
To check the error you just need to check the `error.code`.

However, bear in mind, that there are many possible errors and each one has its code. And you can find them all in: https://github.com/web3/web3.js/blob/ed2770c8e9dade23b3577612201269a0b004aac0/packages/web3-errors/src/error_codes.ts

And, I suspect when you said "the user rejecting the transfer" is that you are talking about some wallet like MetaMask. And if so, here is more about the error codes: https://blog.logrocket.com/understanding-resolving-metamask-error-codes/ 

I hope this answers your question. If not, please provide more into the context and your full scenario including the full code (you may provide a link to a GitHub repo or a link to a Cloud IDE like https://codesandbox.io/)

All the best,

**Comment by xx237461269** [comment]
```js
async function startTransfer() {
  const typeParams = query.blockChainModel.toUpperCase();
  await getExchange(typeParams);
  let contract_abi = contractABI[query.blockChainModel];
  let contract_address = contractAddress[query.blockChainModel];

  let cur_price = query.price / accountTypesData[query.blockChainModel].rate;
  let myContract = new web3js.eth.Contract(contract_abi, contract_address);
  if (amount_balance.value < cur_price) {
    title.value = "Your balance is insufficient";
    return;
  } else {
    title.value = "Initiating transaction request";
  }
  let amount = Number(
    (
      (query.price * query.couponRate) /
      accountTypesData[query.blockChainModel].rate
    ).toFixed(4)
  );
  if (query.blockChainModel === "bsc_usd" || query.blockChainModel === "busd") {
    amount = web3js.utils.toWei(amount, "ether");
  } else {
    amount = web3js.utils.toWei(amount, "mwei");
  }
  let gas_price = await web3js.eth.getGasPrice().then((res) => {
    console.log(res);
    return res;
  });
  let gas_limit = await myContract.methods
    .transfer(receiving_address.value, amount)
    .estimateGas({ from: payment_address, gas: 5000000 });
  const sendObject = myContract.methods
    .transfer(receiving_address.value, amount)
    .send({ from: payment_address, gas: gas_limit, gasPrice: gas_price });
  title.value = "Transfer request initiated";

  console.log(sendObject, "sendObject");
  sendObject.on("transactionHash", function (hash) {
    transaction_hash.value = hash;
    console.log(hash, "hash");
  });
  sendObject.on("receipt", function () {
    // console.log(receipt, "receipt");
  });
  sendObject.on("confirmation", function (confirmationNumber) {
    console.log(confirmationNumber, "confirmationNumber");

    transaction_hash.value = confirmationNumber.receipt.transactionHash;
    socket.value.send(
      JSON.stringify({
        transaction_hash: transaction_hash.value,
        isPaySuccess: true,
        orderId: query.orderId,
      })
    );
    socket.value.close();
  });
  sendObject.on("error", function (error, receipt) {
    console.log(error, "error");
    console.log(receipt, "receipt");
    socket.value.send(
      JSON.stringify({
        transaction_hash: receipt.transactionHash || "",
        isPayError: true,
        orderId: query.orderId,
      })
    );
  });
  sendObject.catch((error) => {
    console.dir(error);
    if (error?.message?.indexOf("User denied transaction signature") > -1) {
      title.value = "You have rejected this transaction";
      socket.value.send(
        JSON.stringify({
          isPayError: true,
          orderId: query.orderId,
        })
      );
    }
  });
}
```

Yes, I did say that in the case of interaction with metamask, the user refused the transaction after initiating the transfer, but sendObject. on ("error") could not catch this error. Therefore, I added the sendObject. catch event later, but I am not sure if this will cause other problems or if there are other better methods

**Comment by Muhammad-Altabba** [comment]
Thanks @xx237461269  for sharing the full code and for telling that you are using MetaMask, just now :smile: .

And yes, you are doing it right. And your code will not cause other problems.
However, I recommend using `try { await sendObject } catch(error) {...}` instead of `sendObject.catch((error) => {...}`. Just because using `await` is generally preferred for promises.
And to give you more illustration: your `sendObject` is a promise that will generally throw in case there is an error that prevent the transaction from being sent. And the event `on('error', ...)` will be emitted in case of an error during the transaction execution (like an error thrown inside solidity code).

**Comment by xx237461269** [comment]
Thank you for your answer
