### ISSUE TITLE
Not receiving more than one confirmation for a transaction

### ISSUE THREAD

**Issue by ruben-certhis** [ethereum/web3.js#6349]
Hello,

I'm trying to wait for three confirmations before executing a function. However, I only receive the first confirmation and then nothing follows. I've tried increasing the transactionConfirmationBlocks, but it hasn't made any difference. Does anyone have any idea or suggestion on how to resolve this issue?

```
  mycall.on("confirmation", (confirmation) => {
      console.log(confirmation);
      });
```

Thank you in advance for your help.

**Comment by avkos** [comment]
Hi. Thank you for your contribution. I've checked `on("confirmation") and it works well. here is a code that you can try:
```ts
const waitConfirmations = 3;
// set amount of confirmation to web3 config
contract.setConfig({ transactionConfirmationBlocks: waitConfirmations });
const sentTx = contract.deploy(deployOptions).send(sendOptions);

let shouldBe = 1;
const confirmationPromise = new Promise((resolve: Resolve) => {
   void sentTx.on('confirmation', ({ confirmations }) => {
      expect(Number(confirmations)).toBeGreaterThanOrEqual(shouldBe);
      shouldBe += 1;
      if (shouldBe > waitConfirmations) {
         resolve();
      }
   });
});

// send some transaction to node to confirm our main transaction
await sendFewSampleTxs(3);
await confirmationPromise;
```


If you will still have a problem with this please provide more information to make us possible to investigate the issue deeper.

**Comment by ruben-certhis** [comment]
@avkos,

Following my tests, I've identified that the issue is related to Metamask. Could you please confirm if this problem is specific to my Metamask setup or if it's a widespread issue affecting all Metamask wallet?

Thank you in advance for your insights.

Best regards,
Ruben

**Comment by Muhammad-Altabba** [comment]
> @avkos,
> 
> Following my tests, I've identified that the issue is related to Metamask. Could you please confirm if this problem is specific to my Metamask setup or if it's a widespread issue affecting all Metamask wallet?
> 
> Thank you in advance for your insights.
> 
> Best regards, Ruben

Hi @ruben-certhis,
Maybe it is not related to MetaMask at all. 
I need you to confirm if you are using a local dev node? As for local dev nodes like `Ganache` or `geth --div`. By default, you never get new blocks except when you send a transaction. So, to get 3 confirmations you need to send 3 transactions after you start listening. And you may need to wait probably like 1 second between every transaction and the other.

**Comment by ruben-certhis** [comment]
Hi @Muhammad-Altabba ,
Thank you for your reply. To clarify, I am using the Mumbai and Goerli test networks, not a local dev node.

**Comment by Muhammad-Altabba** [comment]
Hello @ruben-certhis,
Do you face this issue only with MetaMask and it works with other providers? Then I suggest to open an issue at their repo. 
If it is not only with MetaMask, could you share the full repository on a cloud IDE like https://codesandbox.io/? Or provide a link to a repository on GitHub? (please use a code that is similar to the provided in https://github.com/web3/web3.js/issues/6349#issuecomment-1687324190
Thanks,

**Comment by jdevcs** [comment]
@ruben-certhis

**Comment by mconnelly8** [comment]
@ruben-certhis, since there hasn't been a response, we need to close this issue.  If it persists, please reopen issue.
