### ISSUE TITLE
receipt.events Missing After Migrating from v1 to v4

### ISSUE THREAD

**Issue by ruben-certhis** [ethereum/web3.js#6351]
I've recently migrated my project from web3.js v1 to v4 and I've encountered an issue: I no longer receive the `receipt.events` after a transaction is confirmed.
![Capture d’écran 2023-08-14 à 13 13 00](https://github.com/web3/web3.js/assets/109523233/03c831b1-3f70-44ad-b4ce-55eaf5aaeabc)

**Comment by ruben-certhis** [comment]
In my smart contract, I emit an event. With the v1 of web3.js, I received receipt.events with a return value. However, in v4, I didn't receive anything. I've since created a function for it based on the log.

```
var decodeLogsUntilEventName = function (
    logs,
    abi,
    targetEventName,
    targetParamName
  ) {
    var web3 = new Web3();
    const contract = new web3.eth.Contract(abi);
    let results = [];

    for (let log of logs) {
      const eventSignature = log.topics[0];
      for (let eventAbi of abi) {
        if (
          eventAbi.type === "event" &&
          web3.eth.abi.encodeEventSignature(eventAbi) === eventSignature
        ) {
          const decodedData = web3.eth.abi.decodeLog(
            eventAbi.inputs,
            log.data,
            log.topics.slice(1)
          );

          if (eventAbi.name === targetEventName) {
            results.push(decodedData[targetParamName].toString());
          }
          break;
        }
      }
    }

    return results.length ? results : null; 
  };

```

**Comment by jdevcs** [comment]
Thanks for details, we will investigate this.

**Comment by avkos** [comment]
I've reproduced this issue locally. It returns only logs and no events. Related to this [issue](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/gh/web3/web3.js/6312)

**Comment by jdevcs** [comment]
closing this issue as it will be fixed under https://github.com/web3/web3.js/issues/6351

**Comment by jdevcs** [comment]
closing this issue as it will be fixed under https://github.com/web3/web3.js/issues/6312
