### ISSUE TITLE
Error Sending Transaction: InvalidResponseError: Returned error: unknow

### ISSUE THREAD

**Issue by ruben-certhis** [ethereum/web3.js#6353]
Hello,

I encountered an issue when trying to send a transaction using web3.js v4. Below is a snippet of the code I'm using:

```
const web3 = new Web3(new Web3.providers.HttpProvider(rpc_url));
web3.eth.accounts.wallet.add(secretPhrase);

await safemint
  .send({
    from: '0x883f9048936a7Ab0DB1e352fe27760830Bcxxxxx',
    value: 0,
    gasLimit: 453034n,
    gas: 453034n,
    gasPrice: 1500000018n,
    nonce: 328n
  })
```
When I run the code, I get the following error:

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

InvalidResponseError: Returned error: unknown account
    at Web3RequestManager._processJsonRpcResponse (../node_modules/web3-core/lib/commonjs/web3_request_manager.js:258:23)
    at Web3RequestManager.<anonymous> (../node_modules/web3-core/lib/commonjs/web3_request_manager.js:156:29)
    ... (other stack trace details)
  innerError: { code: -32000, message: 'unknown account' },
  code: 101,
  data: undefined,
  request: {
    ... (other request details)
  }
```
Any assistance or pointers on how to fix this would be greatly appreciated.

Thank you for your time!

**Comment by jdevcs** [comment]
@ruben-certhis web3.js lib's internal wallet doesn't support HD wallet functions. You may inject some other HD wallet into web3.js lib for using.

**Comment by jdevcs** [comment]
We already have issue for developing this feature https://github.com/web3/web3.js/issues/5595 so I will close this issue.

**Comment by ruben-certhis** [comment]
@jdevcs ,

Thank you for your quick response. I noticed that this functionality was present in web3.js v1. So, it seems like a missing feature in v4. Before considering downgrading to v1, I wanted to check if there's an alternative solution in v4 that I might have missed.

Do you have any recommendations or workarounds that would allow me to continue using v4 without the need to inject an external HD wallet or downgrade?

Thank you for your assistance!

**Comment by luu-alex** [comment]
@ruben-certhis i assume you are the person asking on discord, but if you aren't. check out https://www.npmjs.com/package/@truffle/hdwallet-provider for an alternative solution.
