### ISSUE TITLE
Typo in Providers Guide

### ISSUE THREAD

**Issue by Wzb3422** [ethereum/web3.js#6363]
#### Expected behavior

> WebSocketProvider instance will be created for string containing `ws` or `wss`.

#### Actual behavior

Duplicated `ws`

> WebSocketProvider instance will be created for string containing `ws` or `ws`.

#### Steps to reproduce the behavior
- Visit: https://docs.web3js.org/guides/web3_providers_guide/
- Or directly check this line: https://github.com/web3/web3.js/blob/4.x/docs/docs/guides/web3_providers_guide/index.md?plain=1#L36C248-L36C260

#### Logs

N/A

#### Environment

Not Needed

**Comment by luu-alex** [comment]
Thank you for creating this issue, would you like to make a PR and contribute to the project :) otherwise ill create one later.

**Comment by anik-bin** [comment]
Hey, I have fixed this issue and made a PR

**Comment by jdevcs** [comment]
@anik-bin PR merged, Thanks, https://github.com/web3/web3.js/pull/6370
