### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by khalidmaquilang** [ethereum/web3.js#6371]
#### Expected behavior
Web3 should be run without error in vuejs.

#### Actual behavior
it displays 
![image](https://github.com/web3/web3.js/assets/120788000/a6cc66ea-0b90-456f-b6bc-63351420fff6)

#### Steps to reproduce the behavior

1. Fresh installed Laravel
2. Install Jetstream
3. Install Inertiajs

#### Environment
```
"@inertiajs/vue3": "^1.0.0",
"@tailwindcss/forms": "^0.5.2",
"@tailwindcss/typography": "^0.5.2",
"@vitejs/plugin-vue": "^4.0.0",
"autoprefixer": "^10.4.7",
"axios": "^1.1.2",
"laravel-vite-plugin": "^0.8.0",
"postcss": "^8.4.14",
"tailwindcss": "^3.1.0",
"vite": "^4.0.0",
"vue": "^3.2.31"
"web3": "^4.1.0"
```

**Comment by jdevcs** [comment]
@khalidmaquilang could you create a sample project repo or online create sandbox using some tool like https://codesandbox.io/ with this error?

**Comment by 0xGoenka** [comment]
@jdevcs  https://github.com/estebanadams/react-web3

Here is a repo reproducing, I got the exact same problem

**Comment by 0xGoenka** [comment]
@khalidmaquilang ching web3js version 1.10.0 fixed the pb for me

**Comment by khalidmaquilang** [comment]
> @khalidmaquilang ching web3js version 1.10.0 fixed the pb for me

actually i fixed it by downgrading but i want to use the latest.. thanks for producing a repo.. please investigate it @jdevcs

**Comment by jdevcs** [comment]
We will schedule it in next sprint starting tomorrow. cc: @mconnelly8 ?

**Comment by 0xGoenka** [comment]
If you can put the MR link after you fixed in this comment, it would be
great, I'm curious about what is the problem :)

**Comment by LingTaixu** [comment]
why don't you give it a try
`npm i events` or `yarn add events`

**Comment by Muhammad-Altabba** [comment]
Hello @estebanadams,
I just want to say that as @LingTaixu suggested, running `yarn add events`  or `npm i events` (adding `"events": "^3.3.0"` to your dependencies at package.json), will fix the issue. So, you can use this for now as a quick fix.
However, we will investigate further for the best solution.

Hi @LingTaixu,
Many thanks for your suggestion. And actually, it is `events` and not `event`. So, I edited  your comment to fix this :smile:
