### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Capmendez** [ethereum/web3.js#6374]
ERROR in ./node_modules/web3-errors/lib/esm/errors/rpc_error_messages.js 17:0-481
Module not found: Error: Can't resolve '../error_codes' in 'C:\Users\hp\Desktop\Web Development Projects\myairdropfeg\feg-2.0\node_modules\web3-errors\lib\esm\errors'
Did you mean 'error_codes.js'?
BREAKING CHANGE: The request '../error_codes' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by SoarinSkySagar** [comment]
I am also getting the same error, very annoying. Easy to fix in localhost by deleting the node_modules/web3-errors/lib/esm/package.json file but there's no way to do that in production environments like Vercel, so deployment is a pain.

**Comment by avkos** [comment]
Thank you for your contribution. Could you please provide information about the web3js@4.x version that you use to receive this problem?

**Comment by jdevcs** [comment]
Its fixed in recent 4.x patch release.
