### ISSUE TITLE
Method decimals of contract returns different behavior  when using different nodes

### ISSUE THREAD

**Issue by Nicholas090** [ethereum/web3.js#6379]
**Expected behavior**

Method _decimals_ of contract returns number / BSC Testnet

**Actual behavior**

Method of contract returns error if I use bscTestnetNodeWithErr

Beside, with web3@1.10.1 everything okay

Steps to reproduce the behavior

1. Start a new project npm init -y &&  npm i web3@4.0.2 && npm i human-standard-token-abi

2. Create the a simple code

```
const { Web3 } = require('web3');
const abi = require('human-standard-token-abi');

const bscTestnetNode = 'https://data-seed-prebsc-1-s1.binance.org:8545/';
const bscTestnetNodeWithErr = 'https://bsc-testnet.public.blastapi.io/';
const client = new Web3(bscTestnetNode);
const contractAddress = '0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee'
const contract = new client.eth.Contract(abi, contractAddress);

contract.methods.decimals().call().then((decimals) => {
    console.log(decimals);
});
```

**Logs**
case bscTestnetNode - 18n

case bscTestnetNodeWithErr - 
```
           throw new web3_errors_1.ContractExecutionError(error);

ContractExecutionError: Error happened while trying to execute a function inside a smart contract
    at Function._isReverted (/Users/vadim/Desktop/LazyAnts/test-web3/node_modules/web3-core/lib/commonjs/web3_request_manager.js:311:19)
    at Web3RequestManager._processJsonRpcResponse (/Users/vadim/Desktop/LazyAnts/test-web3/node_modules/web3-core/lib/commonjs/web3_request_manager.js:257:42)
    at Web3RequestManager.<anonymous> (/Users/vadim/Desktop/LazyAnts/test-web3/node_modules/web3-core/lib/commonjs/web3_request_manager.js:156:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vadim/Desktop/LazyAnts/test-web3/node_modules/web3-core/lib/commonjs/web3_request_manager.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  innerError: [Eip838ExecutionError: execution reverted] {
    innerError: undefined,
    code: -32000,
    receipt: undefined,
    data: undefined
  },
  code: 310,
  receipt: undefined
}
```
**Environment**

OS: MacOs 13.5.1
NODE: v16.19.0
NPM: 9.8.1

**Comment by jdevcs** [comment]
Thanks for details. I was also able to reproduce it. 

It seems both eth node clients are different, one expects strictly `data` field for eth_call, while other works with `both` data or `input`. 
1.x always uses `data` field so it works on both nodes, while 4.x uses `input` field so it works on one node and not on other. 

1.x always sends `data` field for `eth_call` : 
```
{
  jsonrpc: "2.0",
  id: 4083981738803212,
  method: "eth_call",
  params: [
    {
      data: "0x313ce567",
      from: undefined,
      gasPrice: undefined,
      gas: undefined,
      to: "0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee",
    },
    "latest",
  ],
}
```
4.x:
```
{
  jsonrpc: "2.0",
  id: "da0ebf20-b7d0-46f7-8bbf-c23b3223d841",
  method: "eth_call",
  params: [
    {
      to: "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee",
      input: "0x313ce567",
    },
    "latest",
  ],
}
```

**Comment by Nicholas090** [comment]
> Thanks for details. I was also able to reproduce it.
> 
> It seems both eth node clients are different, one expects strictly `data` field for eth_call, while other works with `both` data or `input`. 1.x always uses `data` field so it works on both nodes, while 4.x uses `input` field so it works on one node and not on other.
> 
> 1.x always sends `data` field for `eth_call` :
> 
> ```
> {
>   jsonrpc: "2.0",
>   id: 4083981738803212,
>   method: "eth_call",
>   params: [
>     {
>       data: "0x313ce567",
>       from: undefined,
>       gasPrice: undefined,
>       gas: undefined,
>       to: "0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee",
>     },
>     "latest",
>   ],
> }
> ```
> 
> 4.x:
> 
> ```
> {
>   jsonrpc: "2.0",
>   id: "da0ebf20-b7d0-46f7-8bbf-c23b3223d841",
>   method: "eth_call",
>   params: [
>     {
>       to: "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee",
>       input: "0x313ce567",
>     },
>     "latest",
>   ],
> }
> ```

Thanks. It works with data.

**Example** 
``` 
const data = {
    data: "0x313ce567",
    to: "0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee",
}

contract.methods.decimals().call(data).then((decimals) => {
    console.log(decimals);
});


```

**Comment by jdevcs** [comment]
reopening issue for internal discussion.

**Comment by mconnelly8** [comment]
Need to try to reproduce.  If not, can close.

**Comment by jdevcs** [comment]
@Nicholas090 you should pass `{dataInputFill: "data"}` or `{dataInputFill: "both"}` when creating contract instance and it will work on both nodes:

`const contract = new client.eth.Contract(abi, contractAddress,  {dataInputFill: "data"});`

Explanation:
as mentioned in https://github.com/web3/web3.js/issues/6379#issuecomment-1696931653
some eth nodes expects data `data` and `input` and some strictly `data` field only. now its configurable in web3.js lib.
by default web3 lib sends `input` field and

- `dataInputFill: "data"`  web3 will send only `data` field to node
- `dataInputFill: "input"` web3 will send only `data` field to node
- `dataInputFill: "both"` web3 will send `data` and `input` field to node

**Comment by jdevcs** [comment]
also mentioned in  docs https://docs.web3js.org/guides/smart_contracts/deploying_and_interacting_with_smart_contracts#troubleshooting-and-errors
