### ISSUE TITLE
Insecure Credential Storage Security Alert on web3 package

### ISSUE THREAD

**Issue by saiakhil2012** [ethereum/web3.js#6387]
Current web3 package usage has vulnerability of Insecure Credential Storage. The corresponding Vulnerability from Github Advisory Database: https://github.com/advisories/GHSA-27v7-qhfv-rqq8

Wanted to check are there any planned or ongoing resolution efforts for the above?

#### Expected behavior
There should not be atleast any known open vulnerability on the web3 package

#### Actual behavior
Any usage of web3 package brings about a Dependabot alert with above advisory vulnerability

#### Steps to reproduce the behavior
Usage of Dependabot for a Github repository which uses web3 package

#### Logs
Not applicable

#### Environment
Github Dependabot

**Comment by jdevcs** [comment]
Its pointing to <= 1.5.2. version. use latest 4.x
