### ISSUE TITLE
web3js deviates from the Error handling standard

### ISSUE THREAD

**Issue by moshmage** [ethereum/web3.js#6388]
on the creation of a `ContractExecutionError` that extends a `Web3ContractError` (that ultimately extends an `Error`) the code starts the `super` class (eventually starting the `Error`) with a pre-defined message ("Error happened while trying to execute a function inside a smart contract") and appends _the original error_ in a `innerError` prop. 

This causes a deviance from Error handling standards, as a developer I'd like to know the actual stack and error message, and cause, that came along.

I propose to use the [cause standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#parameters) and call `super('message', {cause: rpcError})`

#### Expected behavior

- Errors to use `{cause: error}`

#### Actual behavior

- Errors use `innerError`

#### Steps to reproduce the behavior
Check this line, https://github.com/web3/web3.js/blob/4.x/packages/web3-errors/src/errors/contract_errors.ts#L222

#### Environment

- web3js 4.1.0

**Comment by jdevcs** [comment]
Thanks for details and proposing improvement, We will discuss this in team.

**Comment by calmacfadden** [comment]
This issue impacts the ethereum remix ide. 
https://github.com/ethereum/remix-project/issues/4241

**Comment by mconnelly8** [comment]
Need to investigate
