### ISSUE TITLE
Fix an issue in Truffle pipeline in the upgrade MR: Fail! Dependencies not listed in package.json: node:crypto

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6391]
There is an error with the dependency check as shown here (https://github.com/trufflesuite/truffle/actions/runs/5986540392/job/16239827872):

> lerna info Executing command in 52 packages: "dependency-check --missing ."
truffle: Fail! Dependencies not listed in package.json: node:crypto

**Comment by jdevcs** [comment]
@Muhammad-Altabba plus open issue in truffle repo for this as discussed and link with it. thanks.

**Comment by Muhammad-Altabba** [comment]
Fixed at: https://github.com/trufflesuite/truffle/pull/5393/commits/08e1a592fe399f1b6ab09076df0c35e6373ade7b
Thanks,
