### ISSUE TITLE
`web3.eth.ens.registryAddress` does not change the address of registry

### ISSUE THREAD

**Issue by Throvn** [ethereum/web3.js#6399]
#### Expected behavior

When setting `web3.eth.ens.registryAddress`, the library should resolve names by using the supplied contract address.

#### Actual behavior

The hardcoded ens address is still used.

#### Steps to reproduce the behavior
I'm using hardhat. Run a local node with `npx hardhat node` and use this to check the logs.

But the basic setup script is this:
```javascript
var web3 = new Web3();
web3.setProvider('http://127.0.0.1:8545');
web3.eth.ens.registryAddress = '0x1D13fF25b10C9a6741DFdce229073bed652197c7';
web3.eth.ens.getOwner('test.eth').then(console.log).catch(console.error)
```

The script is run in the browser, but in the node.js environment I got the same results.

#### Logs

```shell
eth_call
  WARNING: Calling an account which is not a contract
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e
```

#### Environment

npm: 9.8.1
node: v16.15.0
web3.js: 4.1.1

**Comment by luu-alex** [comment]
I'll take a look into this, sorry that you are facing this error

**Comment by luu-alex** [comment]
This issue is related to a merge that happened in our latest release. It'll be fixed soon but in the meantime use version 4.0.3 for working behavior.

**Comment by luu-alex** [comment]
I believe its an issue with the web3.js package, could you try using the ENS package independently?
```
import { ENS } from 'web3-eth-ens';

const ens = new ENS(registryAddress);
ens.setProvider(setYourProvider)

ens.getOwner('test.eth').then(console.log)
```

**Comment by jdevcs** [comment]
During web3 main obj instantiation default address is set : https://github.com/web3/web3.js/blob/702aeca3d5c3dad663f72b7144be659b3c3004fe/packages/web3/src/web3.ts#L160

and in normal flow, currently only opportunity of setting address is in constructor of ENS when registry contract instance is created. https://github.com/web3/web3.js/blob/702aeca3d5c3dad663f72b7144be659b3c3004fe/packages/web3-eth-ens/src/ens.ts#L73

I think we should expose another function set address,

**Comment by Throvn** [comment]
Thanks for being so eager to solve it! I will try this out asap, and get back to you.

**Comment by mconnelly8** [comment]
Hey @Throvn, were you able to solve the issue with the suggestion above?

**Comment by krzysu** [comment]
Hey, just to confirm, you can only specify your own registry address when instantiating the `ENS` class from the `web3-eth-ens` package. Unfortunately, there’s no way to change the default registry address when using `Web3` directly from the `web3` package.

For the use case mentioned in the issue, this approach works:

```ts
import { ENS } from 'web3-eth-ens';

const ens = new ENS(yourRegistryAddress, yourProvider);
```

Also, just a heads-up: `web3.eth.ens.registryAddress` is a read-only value (it should actually be a constant), so attempting to overwrite it won’t have any effect.


With all that being said, I'm closing this issue.
