### ISSUE TITLE
Sepolia Error: Sending Empty Contract Byte Code

### ISSUE THREAD

**Issue by ajmalmohad** [ethereum/web3.js#6400]
#### Expected behavior
Deploy the contract with correct bytecode

#### Actual behavior
deploys the contract with empty bytecode ("0x")

#### Steps to reproduce the behavior
I'm using truffle HDWalletProvider as the provider for web3
- Setup ACCOUNT_MNUEMONIC and INFURA_SEPOLIA_ENDPOINT in .env file
```js
require('dotenv').config();

const HDWalletProvider = require('@truffle/hdwallet-provider');
const { Web3 }= require('web3');
const { abi, bytecode } = require('./compile.js')

const mneumonic = process.env.ACCOUNT_MNEUMONIC;
const testnet =  process.env.INFURA_SEPOLIA_ENDPOINT;

const provider = new HDWalletProvider( mneumonic, testnet );
const web3 = new Web3(provider);

(async () => {

    const accounts = await web3.eth.getAccounts();
    console.log('Deploying from Account: ' + accounts[0]);
    const result = await new web3.eth.Contract(abi)
    .deploy({ data: bytecode, arguments:['Hello There!'] })
    .send({ from: accounts[0], gas: '3000000' });
    console.log('Contract deployed to: ' + result.options.address);

})();
```

- The Contract will be deployed successfully but the input data field is empty. The deploy function is getting the actual values - I tried hardcoding the values and it didn't work either. 

![image](https://github.com/web3/web3.js/assets/55492635/958f5eaf-82bf-4716-bf2d-537d17d8235a)
This is the deployed contract with the issue

#### Logs

![image](https://github.com/web3/web3.js/assets/55492635/267e98ad-417d-4f17-b5ef-0fa9e9374cb8)
As the code is empty geth debug trace has 0 steps

#### Environment

node: v18.17.1
npm: 9.6.7
web3.js: 4.1.1
os: windows 11

#### What worked for me

When I switched the version of web3 .js to "1.5.2" , it works correctly. The exact same code above works with web3 1.5.2 just by changing ```const { Web3 }= require('web3');``` to  ```const Web3 = require('web3');```

![image](https://github.com/web3/web3.js/assets/55492635/249ab78b-a231-48c5-95d4-128b5483bc17)
This is the deployed contract working with web3.js 1.5.2

**Comment by luu-alex** [comment]
Hey there, theres a fix for this issue coming soon. https://github.com/web3/web3.js/pull/6377 . In the meantime you can either use web3.js version 1.x or 4.0.3 and it'll work until the next version. sorry about the inconvenience

**Comment by jdevcs** [comment]
@luu-alex once your PR merged could you track all related issues with users with dev release?
