### ISSUE TITLE
Cannot create property 'npmrc-tmpl' on string '{\"npmrc-tmpl\":true}'

### ISSUE THREAD

**Issue by ser0ja** [ethereum/web3.js#6408]
I'm trying to build web3 library locally but I'm getting an error

![image](https://github.com/web3/web3.js/assets/5020923/acc82fd7-c626-4f61-8455-7e65a428dacc)

![image](https://github.com/web3/web3.js/assets/5020923/40bb9d53-54e2-40c5-982b-bd304c7113bf)

How can this be fixed?

```
windows 11
$ npm --version
10.0.0
$ yarn --version
1.22.15
$ node --version
18.17.1
```

**Comment by Muhammad-Altabba** [comment]
Hello @ser0ja,
This seems to be an issue with your project configuration that is not related to web3.js. 

So, kindly try to remove web3.js from dependencies and see if the error disappears or not. If it did not disappear, then it is something not related to web3.js so please close this issue and probably post your question to StackOverflow or so. 
But, if the issue disappeared once you removed web3.js from the dependencies then we need to investigate more to check more on this. And, in this case, please provide your project code where this issue exists but with the minimum possible configuration. You may share the link with use using any cloud IDE like https://codesandbox.io/.

However, here is a hint: I think it could be inside your `.npmrc` file. I advise you to search inside your project for the string `npmrc-tmpl` and I think you are miswriting it with a hyphen `-` instead of a dot `.`.

**Comment by ser0ja** [comment]
Hello @Muhammad-Altabba 
I am trying to build a web3 project (https://github.com/web3/web3.js)
I cloned it and run the `yarn` command
My `.npmrc` file is empty
This file in web3 project has this line https://github.com/web3/web3.js/blob/4.x/.npmrc

**Comment by Muhammad-Altabba** [comment]
Oh, sorry @ser0ja. I got you know.
And sorry we did not test this on Windows. 
I suggest running the command inside vscode "JavaScript Debug Terminal" and trying to debug the file.
Also, the screenshot shows that there is a yarn-error.log file. Could you open it and check it? And then share it?

**Comment by ser0ja** [comment]
@Muhammad-Altabba, I found the reason
it's all about `symlinks`

**Comment by Muhammad-Altabba** [comment]
Great news!
And where are you able to fix the issue? Could you, please, share your findings so other developers who use Windows can check it?

**Comment by ser0ja** [comment]
Possible solution: redo all symbolic links and correct `echo` in files

1. In git\bin\bash.exe - `git ls-files -s | awk '/120000/{print $4}' > symlinks.txt`
2. Create `windows.mjs`
```
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { execSync } from 'node:child_process'

export const __filename = fileURLToPath(import.meta.url)
export const __dirname = path.dirname(__filename)

// git ls-files -s | awk '/120000/{print $4}' > symlinks.txt

// const stdout = execSync('git ls-files -s | awk \'/120000/{print $4}\'', { windowsHide: true })
// console.log(stdout)
// fs.writeFileSync('symlinks.txt', stdout)

let symlinks_error = false
const stdout = fs.readFileSync('symlinks.txt', { encoding: 'utf8', flag: 'r' })
const files = stdout.trim().split('\n')
for (const file of files) {
    const link = fs.readFileSync(file, { encoding: 'utf8', flag: 'r' })
    const link_cl = link.replace(/^(\.\.\/)+/g, '')
    fs.rm(file, { force: true }, (e) => {
        if (!e) {
            execSync(`mklink ${ path.join(__dirname, file) } ${ path.join(__dirname, link_cl) }`)
        }
        else {
            symlinks_error = true
        }
    })
}

if (!symlinks_error) {
    function* walk_sync(dir) {
        const files = fs.readdirSync(dir, { withFileTypes: true })
        for (const file of files) {
            const { name, path: link } = file
            const file_path = path.join(dir, name)
            if (file.isDirectory()) {
                yield* walk_sync(file_path)
            }
            else {
                if (name === 'package.json' && link.search('node_modules') === -1) {
                    const data = fs.readFileSync(file_path, { encoding: 'utf8', flag: 'r' })
                    const result = data.replace(/echo\s('|\\")(.*?)('|\\")\s>/g, 'echo \$2 >')
                    fs.writeFileSync(file_path, result, { encoding: 'utf8', flag: 'w+' })
                    yield file_path
                }
            }
        }
    }

    walk_sync(__dirname)
}
```
3. Open Windows Terminal as **ADMIN** and `node windows.mjs`
4. `yarn`

**Comment by ser0ja** [comment]
After that I get an error when building, but that's another story
![image](https://github.com/web3/web3.js/assets/5020923/cbe6e226-67fa-4e66-b97a-df46e250354a)

**Comment by ser0ja** [comment]
Hello @Muhammad-Altabba
This error is caused by the `package.json` file` '{"type": "module"}' `, which is invalid due to extra quotes created by the command
corrects the situation
```
"build:cjs": "tsc --build tsconfig.cjs.json && echo {\"type\": \"commonjs\"} > ./lib/commonjs/package.json"
"build:esm": "tsc --build tsconfig.esm.json && echo {\"type\": \"module\"} > ./lib/esm/package.json",

and

"version:output": "[ -z $npm_package_version ] && rm ./src/version.ts || echo /* eslint-disable header/header */ export const Web3PkgInfo = { version: '$npm_package_version' }; > ./src/version.ts",
```

![image](https://github.com/web3/web3.js/assets/5020923/212f1602-0468-4871-8937-74852e57c2e5)

ps. updated the file in the previous message

**Comment by jdevcs** [comment]
@ser0ja have you tried using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) on windows for building web3.js project? plus use that and share list of errors.

**Comment by codersjj** [comment]
> [@ser0ja](https://github.com/ser0ja) have you tried using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) on windows for building web3.js project? plus use that and share list of errors.

I tried using WSL, and it works well.

![Image](https://github.com/user-attachments/assets/562b9201-8d10-4e65-9760-3b5ea2bc35a0)

The build process seems to require a certain amount of memory, so I set the memory to 8GB; otherwise, WSL would disconnect.

`.wslconfig`:

```
[wsl2]
memory=8GB
```
