### ISSUE TITLE
v1.10.2

### ISSUE THREAD

**Issue by Hasinafidahussain** [ethereum/web3.js#6412]
## Discussed in https://github.com/web3/web3.js/discussions/6383

<div type='discussions-op-text'>

<sup>Originally posted by **jdevcs** August 28, 2023</sup>
### Fixed

- Fixed broken fetch for Node.js > 18.x and fixed double callback (#6381)

<hr /><em>This discussion was created from the release <a href='https://github.com/web3/web3.js/releases/tag/v1.10.2'>v1.10.2</a>.</em></div>

**Comment by jdevcs** [comment]
@Hasinafidahussain what is this issue about?
