### ISSUE TITLE
[BUG] SocketProvider by default tries to reconnect on chunked request 

### ISSUE THREAD

**Issue by BitOfUniverse** [ethereum/web3.js#6416]
#### Expected behavior

SocketProvider be aware of chunked request and shouldn't rely on empty responses (no full response yet) as a indicator of closed connection. Instead it should check for a event data itself or get additional flag ChunkResponseParser that indicates a chunked response.

#### Actual behavior

When `autoReconnect` is set to true (which is default) SocketProvider always tries to reconnect.
```js
const DEFAULT_RECONNECTION_OPTIONS = {
	autoReconnect: true,
	delay: 5000,
	maxAttempts: 5,
};
```

https://github.com/web3/web3.js/blob/4.x/packages/web3-utils/src/socket_provider.ts#L468-L473
```js
protected _onMessage(event: MessageEvent): void {
		const responses = this._parseResponses(event);
		if (responses.length === 0) {
			// no responses means lost connection, autoreconnect if possible
			if (this._reconnectOptions.autoReconnect) {
				this._reconnect();
			}
			return;
		}
		...
````

#### Steps to reproduce the behavior

1. Connect to WS or IPC provider 
```js
const web3 = new Web3(rpc);
  web3.currentProvider?.on("connect", () => {
    console.log("[Web3] connect");
  });
```
2. Subscribe to new blocks `web3.eth.subscribe("newBlockHeaders")`
3. Check console for `[Web3] connect` logs.

#### Logs
Add these lines to socker_provider.ts / _onMessages: https://github.com/web3/web3.js/blob/4.x/packages/web3-utils/src/socket_provider.ts#L468-L473
```
protected _onMessage(event: MessageEvent): void {
		const responses = this._parseResponses(event);
		if (responses.length === 0) {
			// no responses means lost connection, autoreconnect if possible
			if (this._reconnectOptions.autoReconnect) {
				console.log(`Assumed to lost connection`); // <<<
				console.log(responses);// <<<
				console.log(event);// <<<
				
				
				this._reconnect();
			}
			return;
		}
```

**Result in console:**

```
Assumed to lost connection
[]
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0xd6acda8ad693c3a39359f289d665bcb9","result":{"parentHash":"0x000397c80000023295e4b9741962db028477716bd9000e49c36c20ba47cce21b","sha3Uncles":"0x0000000000000000000000000000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x9f98d7aaf77b802b4549de5e6d1a2a68451037422ed362c8c66aba753776ab79","transactionsRoot":"0x09a3420b620489678e7fa99680837272e82e987650398f3218200f4d6ef1b4d8","receiptsRoot":"0xc104f9efe352c9a57bd8b7dba648b309ea8bc51e2380dba87645078a56ab6b26","logsBloom":"0x000504001400120001001000210000000400000000800080000001800850000203480800000040080805000051000008010000180010000080000080103000800000088000404001004002080004000404000080000202010000000000008000440000020601000800c02000000008004000000203021804001000100000000000020820020200008400800000904820000102080002280000840010804020000210004a000010000800040000001020001010000a000800000001000000240800441902000000002440010201008000000000
```
you can see response chunk, but connection is definitely alive. 

#### Environment

web3 4.1.1
runtime: bun 1.0 (this might be related to the size of a chunk, but bug still relevant)
OS: macos

**Comment by jdevcs** [comment]
@BitOfUniverse Thanks for providing detailed info on socket provider. I wasn't able to reproduce above issue while I was connected with Infure via ws. Means there wasnt any `_onMessage` event with 0 data ( empty chunk ), 
however it make sense that if connection is open and server sends back message with 0 data web3.js lib should not do reconnect.

**Comment by BitOfUniverse** [comment]
@jdevcs I think that problem here is not that response returns empty data, but logic itself treats chunked response (meaning that data was too big and only part of the data was returned)  and therefore `this._parseResponses(event)` returns empty responses object (because there is no entire response yet). I should probably provide fully working example for this issue, because this bug might not occur for WS connection with larger buffer which can fit entire response.

**Comment by jdevcs** [comment]
In case of large response that cannot fit in one reply we have chunks processing logic but after that if chunks processing is WIP there is bug that treats it as 0 data and try to reconnect. Thanks for clarification. We will fix it.

**Comment by jdevcs** [comment]
@BitOfUniverse After above PR's CI there will be dev tag available in npm for your testing.
