### ISSUE TITLE
Calls to eth_getTransactionReceipt not according to transactionConfirmationBlocks setup

### ISSUE THREAD

**Issue by playnance-games** [ethereum/web3.js#6421]
Hi,
I'm using web3.js library(version 1.10.2) and I have an issue.
Although I've set transactionConfirmationBlocks = 2 on web3 object I see a lot of requests to the JSON-RPC Blockchain provider.

The requests are to eth_getTransactionReceipt.

    const promiEvent = new Web3PromiEvent()
    let txEvent = this.contract.methods[methodName](...params)
      .send({
        from: this.from,
        gasLimit: 2000000,
        value
      })
      .on('transactionHash', hash => {
        promiEvent.eventEmitter.emit('transactionHash', hash);
      })
      .on('confirmation', (confNumber, receipt) => {
        promiEvent.eventEmitter.emit('confirmation', confNumber, receipt);
      })
      .on('error', async (err, receipt) => {
        if (receipt && err.message.match(/Transaction has been reverted/)) {
          const reason = await this.getRevertReason(receipt.transactionHash)
          promiEvent.reject(reason)
        }
      })
      .then(receipt => {
        promiEvent.resolve(receipt);
      })
      .catch(err => {
        console.log(err);
      })

    return promiEvent.eventEmitter
  }

It takes a lot of resources and money to poll the JSON RPC provider if I want only 2 confirmations?

Please assist.

Thanks.

**Comment by avkos** [comment]
Hi, thank you for your question. 
It looks like you use httpProvider If you do not want to have a lot of requests you can use WebSocket provider (it will subscribe for the event and wait for confirmation).

Anyway, I suggest you move to the latest version web3js@4

**Comment by playnance-games** [comment]
Hi,
I cannot change to WebSocket provider because I use other libraries that needs http endpoint and websocket.
For using web3js@4 I need to rewrite my code.
Also I noticed that ether.js library works correctly in such cases.

**Comment by avkos** [comment]
to use ether.js you also need to rewrite your code. So, why do not rewrite it to web3js v4?
we have a great [guide](https://docs.web3js.org/guides/web3_upgrade_guide/x/) on how to upgrade from 1.x to 4.x 

and if you have any questions our team will help you in our [discord](https://discord.com/channels/593655374469660673/719602820801888337)

**Comment by jdevcs** [comment]
@playnance-games recently we have made improvements in v4, so can you test latest v4 now? and share your experience.

**Comment by playnance-games** [comment]
@avkos , @jdevcs We already switched to ethers.js but I saw the new version of web3.js has a lot of improvements.
Can you share the cons and pros of using v4 vs ethers.js?

**Comment by jdevcs** [comment]
Web3 v4 ABI encoding and decoding is more fast as compared to ethers, dynamic contract typings, also due to [plugins feature](https://docs.web3js.org/guides/web3_plugin_guide/) anyone can extend web3.js functionality surface, there are [list of plugins](https://web3js.org/plugins) and in future it will increase.
