### ISSUE TITLE
Electron with web3.js: Post-Packaging 'Cannot find module 'crypto'' Error

### ISSUE THREAD

**Issue by infra403** [ethereum/web3.js#6432]
#### Steps to reproduce the behavior

While trying to fetch account balance using web3.js in Electron, post-packaging, I receive the error: Error: Cannot find module 'crypto'.

#### Logs

Uncaught Exception:
Error: Cannot find module 'crypto'

#### Environment
node: v20.4.0
web3: 4.10

**Comment by jdevcs** [comment]
@infra403 can you add in your package.json
```
 "dependencies": {
        "crypto-browserify": "3.12.0",}
 
```
 and in webpack.config.js add  `crypto: require.resolve('crypto-browserify'),`
 
```
 module.exports = {
    resolve: {
        alias: {
            '@': path.resolve('resources/js'),
        },
        fallback: {
            crypto: require.resolve('crypto-browserify'),
            stream: require.resolve('stream'),
        },
    },
};
```

**Comment by jdevcs** [comment]
@infra403 ?

**Comment by jdevcs** [comment]
There is no response / activity on this issue so closing, feel free to reopen if issue still persists and you have more info. Thanks
