### ISSUE TITLE
Web3 4.x Browser tests with UI frameworks / tools

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6443]
- [ ] React 
- [ ] Angular
- [ ] Expo
- [ ] next.js  ( CSR, SSR )
- [ ] vue.js

- add tests of above list for web3 4.x ( add one simple function from web3-eth, web3-contract, web3-accounts ) running in browser

- also write one page doc if any extra steps are required for any config at user side they are using 4.x with above frameworks (for prod builds).

**Comment by mconnelly8** [comment]
Closing issue and created 4 new issues to break the work down (#6523 , #6524 , #6525 , #6526 , #6527 )
