### ISSUE TITLE
[1.x] Update docs with links to 4.x docs

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#6458]
#### Expected behavior
Considering 4.x is stable, 1.x docs should urge people to migrate to 4.x

#### Actual behavior
Nothing related to 4.x is in 1.x docs

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by hardiktheprogrammer** [comment]
@jdevcs  I would like to work on this issue can please assign me this task

**Comment by jdevcs** [comment]
@hardiktheprogrammer assigned, Thanks

**Comment by hardiktheprogrammer** [comment]
@jdevcs  thanks
@jdevcs  sorry can please Reassignes  me   by mistake click on unassign me button

**Comment by sarthak1dev** [comment]
is this issue still open?

**Comment by mconnelly8** [comment]
Hey @hardiktheprogrammer, are you still working on this?  If not, no problem, we can let someone else have a try with it.

**Comment by mconnelly8** [comment]
Hey @sarthak1dev, would you like to take this on?

**Comment by SantiagoDevRel** [comment]
closing this issue

![image](https://github.com/web3/web3.js/assets/83420872/bcf64ce3-c010-48c2-a0fc-fd233432cef1)
