### ISSUE TITLE
Type error in withdrawals schemas

### ISSUE THREAD

**Issue by kkeolmusae** [ethereum/web3.js#6470]
#### Expected behavior
In the withdrawals schema, the format of the address must be address or bytes. 

#### Actual behavior

Issue found while customizing and using web3-eth because withdrawls data was required when the getBlock method was called.  

I modified the blockSchema to call the getBlock method and confirmed that the schema of withdrawals is bytes32, so the value of 32bytes length is returned like hash.

I think the format of the schema should be 'address' or 'bytes'.

#### Steps to reproduce the behavior
Check file (`/web3.js/packages/web3-eth/src/schemas.ts`)

#### Environment

yarn: 3.6.3
Node: v18.17.1
web3.js: ^4.1.1
OS: Mac m1

**Comment by jdevcs** [comment]
@kkeolmusae thanks for testing v4 and this info.
