### ISSUE TITLE
clearSubscriptions on 1.x version contains incorrect type definition

### ISSUE THREAD

**Issue by Verisana** [ethereum/web3.js#6488]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `web3-eth@1.10.2` for the project I'm working on.

This is a minor change. According to your documentation and the underlying code, I think type definition of function clearSubscriptions in index.d.ts 'web3-eth' is not correct. You can see my proposal below :) 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/web3-eth/types/index.d.ts b/node_modules/web3-eth/types/index.d.ts
index 5c8a551..4da48e7 100644
--- a/node_modules/web3-eth/types/index.d.ts
+++ b/node_modules/web3-eth/types/index.d.ts
@@ -98,7 +98,7 @@ export class Eth {
 
     extend(extension: Extension): any;
 
-    clearSubscriptions(callback: (error: Error, result: boolean) => void): void;
+    clearSubscriptions(keepIsSyncing: boolean): boolean;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by luu-alex** [comment]
Hey there :) I believe you are right, would you like to create a PR for this?

**Comment by Verisana** [comment]
Thanks for quick feedback :)
I would like for sure, but hard to predict exact time. Once have free time, will take care :+1:

**Comment by jdevcs** [comment]
@Verisana for latest types support use web3.js v4
