### ISSUE TITLE
ReferenceError: Can't find variable: BigInt

### ISSUE THREAD

**Issue by zahir-dct** [ethereum/web3.js#6495]
#### Actual behavior
App crashes

#### Steps to reproduce the behavior
add web3 package to an expo app

#### Logs
ERROR  ReferenceError: Can't find variable: BigInt

ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.   

ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.  

#### Environment
"expo": "~47.0.12",
 "react": "18.1.0",
 "react-native": "0.70.8",
 "web3": "^1.8.2",
 
 #### Note
 I removed "^" from "^1.8.2", the app doesn't crash

**Comment by jdevcs** [comment]
@zahir-dct can you create a small repository on GitHub or create a sample on a Cloud IDE like https://codesandbox.io/ with above error.

**Comment by zahir-dct** [comment]
> @zahir-dct can you create a small repository on GitHub or create a sample on a Cloud IDE like https://codesandbox.io/ with above error.

https://github.com/zahir-dct/reproduction

**Comment by Muhammad-Altabba** [comment]
Hi @zahir-dct,
Did you try with web3.js version 4.x? 
And does adding `/* global BigInt */` to the top of your `app.js` would resolve the problem?
Thanks,

**Comment by zahir-dct** [comment]
> Hi @zahir-dct, Did you try with web3.js version 4.x? And does adding `/* global BigInt */` to the top of your `app.js` would resolve the problem? Thanks,

I already tried version 4.x, but it doesn't work.
Adding big-integer would be a workaround. It doesn't fix the actual issue.

**Comment by Muhammad-Altabba** [comment]
Hi @zahir-dct 
I checked the issue, and I confirm that it is with `expo`. So, you need to open an issue at their side. They do not support `BigInt`.

By the way, I tried adding `/* global BigInt */`. And I also tried doing a ployfill using the `big-integer` package. And both did not work with `expo`. So, you may try to "eject" from `expo` but there could be some other solutions. And to find the right way you would need to check with them.

However, I will keep this issue open in order to check for possible workarounds till expo supports BigInt.

**Comment by Muhammad-Altabba** [comment]
I am closing this issue as there is nothing to be done at web3.js.

However, for those facing this error, here is a way to work around it (as mentioned in https://github.com/facebook/react-native/issues/28492#issuecomment-824698934):
1. Add [rn-nodeify](https://github.com/tradle/rn-nodeify) to your dev dependencies with: `yarn add --dev rn-nodeify`.
2. Add big-integer package with: `yarn add big-integer`.
3. Create a file named `shim.js` at the root of your project. And add the following pollyfill to it:
  ```js
  if (typeof BigInt === 'undefined') {
      global.BigInt = require('big-integer');
  }
  ```
4. Import your shim.js file at the top of your App.js:
```js
// make sure you use `import` and not `require`!
import './shim.js'
```

However, if the above did not work, or if you did not like the way it works, I suggest to check with, rn-nodeify, expo and react-native...

**Comment by zahir-dct** [comment]
> #### Actual behavior
> App crashes
> 
> #### Steps to reproduce the behavior
> add web3 package to an expo app
> 
> #### Logs
> ERROR ReferenceError: Can't find variable: BigInt
> 
> ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> 
> ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter. A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> 
> #### Environment
> "expo": "~47.0.12", "react": "18.1.0", "react-native": "0.70.8", "web3": "^1.8.2",
> 
> #### Note
> I removed "^" from "^1.8.2", the app doesn't crash

react-native 0.70 (expo sdk 47) does not support BigInt. please try to update to [latest sdk](https://blog.expo.dev/expo-sdk-49-c6d398cdf740) for the BigInt support.
https://github.com/expo/expo/issues/24960#issuecomment-1776314183

**Comment by noname0486** [comment]
> I am closing this issue as there is nothing to be done at web3.js.
> 
> However, for those facing this error, here is a way to work around it (as mentioned in [facebook/react-native#28492 (comment)](https://github.com/facebook/react-native/issues/28492#issuecomment-824698934)):
> 
> 1. Add [rn-nodeify](https://github.com/tradle/rn-nodeify) to your dev dependencies with: `yarn add --dev rn-nodeify`.
> 2. Add big-integer package with: `yarn add big-integer`.
> 3. Create a file named `shim.js` at the root of your project. And add the following pollyfill to it:
> 
> ```js
> if (typeof BigInt === 'undefined') {
>     global.BigInt = require('big-integer');
> }
> ```
> 
> 4. Import your shim.js file at the top of your App.js:
> 
> ```js
> // make sure you use `import` and not `require`!
> import './shim.js'
> ```
> 
> However, if the above did not work, or if you did not like the way it works, I suggest to check with, rn-nodeify, expo and react-native...

It work with my project. Thank you very much
