### ISSUE TITLE
4.x CI / CD Improvements: Supply chain security

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6531]
- [x]     Supplychain security ( Configuring the dependency graph https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-the-dependency-graph )

- Improve security score (SNYK) - https://snyk.io/advisor/npm-package/web3

**Comment by jdevcs** [comment]
dependency graph is already enabled.

**Comment by jdevcs** [comment]
For Improve security score (SNYK) there are some PRs created recently and will discuss this in team meeting.
