### ISSUE TITLE
Add a troubleshooting page in our documentation

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6533]
It is good to add a troubleshooting page in our documentation.
We can start the first section in the troubleshooting page by documenting the workaround for the issue with BigInt at expo. Here is the steps for expo shimming and poly-filling `BigInt`: https://github.com/web3/web3.js/issues/6495#issuecomment-1771011375

**Comment by hardiktheprogrammer** [comment]
@Muhammad-Altabba  I would Like to work on this , can you please assign me

**Comment by jdevcs** [comment]
@hardiktheprogrammer

**Comment by mconnelly8** [comment]
Hey @hardiktheprogrammer, you still working on this?
