### ISSUE TITLE
Insufficient funds for gas * price + value when migrating from 1.x to 4.x

### ISSUE THREAD

**Issue by M0cK1nG-b1Rd** [ethereum/web3.js#6544]
hello, I am trying to update my web3 dependencies, from 1.7.0 to 4.2.0 and get the following error:
```
 TransactionRevertInstructionError: Transaction has been reverted by the EVM
    at /home/test/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:48:21
    at Generator.next (<anonymous>)
    at /home/test/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/home/test/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:20:12)
    at getTransactionError (/home/test/node_modules/web3-eth/lib/commonjs/utils/get_transaction_error.js:33:12)
    at SendTxHelper.<anonymous> (/home/test/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:74:84)
    at Generator.next (<anonymous>)
    at fulfilled (/home/test/node_modules/web3-eth/lib/commonjs/utils/send_tx_helper.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: undefined,
  reason: 'err: insufficient funds for gas * price + value: address 0x4b3ABe20fb75a3D0B3c9dF385Ebf3721dA284eb1 have 51039247781579884 want 725244160242779704823955000000 (supplied gas 3000000)',
  signature: undefined,
  receipt: undefined,
  data: undefined,
  code: 402
}
```
it is requiring a far more reasonable gas of `725244160242779704823955000000`, the exact same transaction can be sent via 1.7.0 without error. The transaction looks like this
```
async function test() {
    let accountNonce = await web3.eth.getTransactionCount(recipient, 'pending');
    accountNonce = Number(accountNonce)
    const rawBuyTx = {
        nonce: accountNonce,
        gasPrice: '0xb2d05e00',
        gasLimit: '0x2dc6c0',
        to: '0x49fa1603fc4e795f111b044e5283832779fa9ecd',
        value: '0x0',
        data: '...'
    }
    const buyTx = LegacyTransaction.fromTxData(rawBuyTx, { common: customCommon })
    const signedTx = buyTx.sign(hexToBytes(privatekey));
    accountNonce = accountNonce + 1;
    try {
        const result = await web3.eth.sendSignedTransaction(signedTx.serialize());

    } catch (error) {
        console.log(error)
    }
}

test()
```
A bit similar with #6249 , but I think I am facing a different situation. I am sending this transactoin on bsc mainnet. I try to put extra gas in the wallet but still get the error. And the 725244160242779704823955000000 keep the same whenever this error occurs. Can someone help me to locate the problem?

**Comment by Muhammad-Altabba** [comment]
Hello @M0cK1nG-b1Rd ,
What is the value you get when you execute: `const gas = await web3.eth.estimateGas(transaction)`?

And did you try to pass the gas in the transaction with: `gas: await web3.eth.estimateGas(transaction)`?

[Generally we support Ethereum mainnet implementation and its test and dev nets. However, we will try to help you for this BSC transaction]

**Comment by M0cK1nG-b1Rd** [comment]
heyyy, I think I find the problem. You inspire me to use `const gas = await web3.eth.estimateGas(transaction)` for my transanction.  And the result is like
```
InvalidResponseError: Returned error: gas required exceeds allowance (0)
    at Web3RequestManager._processJsonRpcResponse (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:258:23)
    at Web3RequestManager.<anonymous> (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:156:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: { code: -32000, message: 'gas required exceeds allowance (0)' },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: 'eb0aafb6-4854-4eb9-9711-931f4f25bc98',
    method: 'eth_estimateGas',
    params: [ [Object], 'latest' ]
  }
}
```
my original code when defining a raw tx is 
```js
rawSellTx = {
    'nonce': web3.utils.toHex(accountNonce),
    'gasPrice': web3.utils.toHex("3100000001"),
    'gasLimit': web3.utils.toHex(3000000),
    'to': myRouterAddress,
    'value': web3.utils.toHex(0),
    'data': webMyRouter.methods.aaa(pcs, tokenAddress, liquidity).encodeABI()
}
```
It turns out that there is some change in `web3.utils.toHex` that cause this problem. In 1.X I use `web3.utils.toHex("3100000001")`, but in 4.X we should use `web3.utils.toHex(3100000001)`  , the result are totally different when use `console.log(web3.utils.toHex("3100000001"))` in 4.X ,as it treat it as a string and get something like `0x33313030303030303031`.

Anyway, thanks for the inspiration. BTW may be an update in doc is needed as I didn't see this function in [migration guide](https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_utils_migration_guide)

**Comment by Muhammad-Altabba** [comment]
Thanks @M0cK1nG-b1Rd for sharing your conclusion.
We will double check this and possibly update the docs.
