### ISSUE TITLE
Can't call ERC-20 transfer method using metamask

### ISSUE THREAD

**Issue by sattarrasouli** [ethereum/web3.js#6551]
#### Steps to reproduce the behavior

i've spent four days on it checked different things and finally i found out i can't send any tx using web3js and metamask.
and got to use ethersjs and it works.

**Comment by luu-alex** [comment]
hey there sorry that your facing this issue, do you have a code snippet?

**Comment by AlbertFiat24** [comment]
Same issue, in my methods I cannot do any send() request. Call() works fine. But when using send, it does not use the method properly and changes the method to a basic ETH Transfer.

I call the methods as such:
myContract.method.MyMethod.send({ gas, from });

where myContract is init using the new web3.eth.Contract(abi, address)

**Comment by jdevcs** [comment]
seems due to metamask filtering `input` field? due to bug in metamask: https://github.com/MetaMask/metamask-extension/issues/21467

**Comment by luu-alex** [comment]
Merged a fix for this, will be included next patch but if you would like to use it asap
web3@[4.2.2-dev.b05345b.0](https://www.npmjs.com/package/web3/v/4.2.2-dev.b05345b.0)
