### ISSUE TITLE
Error in Batch Request

### ISSUE THREAD

**Issue by mouisaac** [ethereum/web3.js#6573]
The example for a batch request in web3.js 4.X from the doc doesn't work, and I would like to figure out what I'm missing. I've been trying to make a batch request with a more complex array of requests, and then I realized that even a single request is giving me an error (as well as the exact code from the example). Did I overlook something obvious?

I have a button that, when clicked, sends a batch request. The code within the handler is copied straight from the documentation. The code sits inside a react component.

```
  const clickHandler = async () => {
    const batch = new web3.BatchRequest();
    const request1 = {
      jsonrpc: '2.0',
      id: 10,
      method: 'eth_getBalance',
      params: ['0xf4ffff492596ac13fee6126846350433bf9a5021', 'latest'],
    };
    const request2 = {
      jsonrpc: '2.0',
      id: 12,
      method: 'eth_getBalance',
      params: ['0xdc6bad79dab7ea733098f66f6c6f9dd008da3258', 'latest'],
    };
    batch.add(request1);
    const request2Promise = batch.add(request2);
    request2Promise.then(response => {
      console.log(response);
    });
    const responses = await batch.execute();
  }
```

#### Expected behavior

It should not give an error on the line ```const responses = await batch.execute();```

#### Logs

inpage.js:1 Uncaught (in promise) Error: Expected a single, non-array, object argument.
    at o (inpage.js:1:107851)
    at Object.invalidRequest (inpage.js:1:108300)
    at d.request (inpage.js:1:76680)
    at Object.apply (inject.chrome.d91a949f.js:1:7026)
    at Web3RequestManager.<anonymous> (web3_request_manager.ts:240:1)
    at Generator.next (<anonymous>)
    at web3_request_manager.ts:1:1
    at new Promise (<anonymous>)
    at __awaiter (web3_request_manager.ts:1:1)
    at Web3RequestManager._sendRequest (web3_request_manager.ts:197:1)

#### Environment

Tested with web3.js 4.2.2 and node v18.18.2

**Comment by jdevcs** [comment]
Hi I am able to get batch request result:

```
import { Web3 } from 'web3';

const web3 = new Web3("http://127.0.0.1:7545");

const clickHandler = async () => {
    const batch = new web3.BatchRequest();
    const request1 = {
        jsonrpc: '2.0',
        id: 1,
        method: 'eth_getBalance',
        params: ['0x18532dF2Ab835d4E9D07a8b9B759bf5F8f890f49', 'latest'],
    };
    const request2 = {
        jsonrpc: '2.0',
        id: 2,
        method: 'eth_getBalance',
        params: ['0x018e221145dE7cefAD09BD53F41c11A918Bf1Cb7', 'latest'],
    };
    const request3 = {
        jsonrpc: '2.0',
        id: 3,
        method: 'eth_getBalance',
        params: ['0x67AE7e4b867330013808fD4EE92FEDbb31CCc3bb', 'latest'],
    };

    batch.add(request1);
    batch.add(request2);
    batch.add(request3);

    return batch.execute();
}

clickHandler().then(r => {
    console.log(r);
});
```
gets on local ganache:
```
[
  { id: 1, jsonrpc: '2.0', result: '0x21e19d73e5127b53174' },
  { id: 2, jsonrpc: '2.0', result: '0x21e19e0c9bab240012c' },
  { id: 3, jsonrpc: '2.0', result: '0x21e19e0c9bab2400000' }
]
```

**Comment by jdevcs** [comment]
Could you share simple react app in some code sandbox website or repo with above error reproducible? @mouisaac

**Comment by mouisaac** [comment]
> Could you share simple react app in some code sandbox website or repo with above error reproducible? @mouisaac

I tried to cut down from my existing app while still keeping the error.

https://github.com/mouisaac/test_batchrequest

Apologize if it was an obvious problematic code from my part. Really like to figure out what is causing it.

**Comment by furkanksl** [comment]
Hey @mouisaac , the problem comes from `window.ethereum`  i guess.

When you initialize web3 object like that : `new Web3(window.ethereum)` , **it does not recognize the rpc to communicate**. 

So your problem will be gone if you initialize your web3 instance like this ( example with sepolia testnet ) : 

```
const web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ethereum-sepolia.publicnode.com"));
```

( You can use also HttpProvider, I used WebsocketProvider for example )

And also you can get chain id that user is on like this: 

```
const chainId : number = parseInt(
      await window.ethereum.request({
          method: "eth_chainId",
          params: [],
      })
  )
  ```
Once you get the chain id you can reach rpc urls of that chain from this way and pick one of them : `https://chainlist.org/chain/${chainId}`  

example : [https://chainlist.org/chain/11155111](https://chainlist.org/chain/11155111) 


I cloned your repo and just changed the web3 initialization like above and it worked! 

<img width="818" alt="Screenshot 2023-12-26 at 4 59 38 AM" src="https://github.com/web3/web3.js/assets/49058467/59199dca-f300-4e26-83be-547d8bc17158">

End of it my clickHandler function was like that : 
```
const clickHandler = async () => {
        const web3 = new Web3(new Web3.providers.WebsocketProvider("wss://ethereum-sepolia.publicnode.com"));
        const batch = new web3.BatchRequest();

        const request1 = {
            jsonrpc: "2.0",
            id: 1,
            method: "eth_getBalance",
            params: ["0xe833C56fd5cDc02ec0F968DbBca317029CB1a814", "latest"],
        };

        const request2 = {
            jsonrpc: "2.0",
            id: 2,
            method: "eth_getBalance",
            params: ["0x018e221145dE7cefAD09BD53F41c11A918Bf1Cb7", "latest"],
        };

        batch.add(request1);
        batch.add(request2);
        console.log(await batch.execute());

        return;
    };
```

_This may not be the solution you looking for but I hope it gives you a perspective 💪_

**Comment by Muhammad-Altabba** [comment]
Thanks @furkanksl for sharing you findings,
We will check and fix or document why `new Web3(window.ethereum)` is giving an error with batch requests.

**Comment by mconnelly8** [comment]
Need to investigate why it's not working with Metamask.  Double check they support it.

**Comment by jdevcs** [comment]
metamask `.request` method doesn't support it, if you directly send array of requests like following:

```
      const res = await window.ethereum.request([
        {
          "jsonrpc": "2.0",
          "id": 1,
          "method": "eth_getBalance",
          "params": [
            "0x18532dF2Ab835d4E9D07a8b9B759bf5F8f890f49",
            "latest"
          ]
        },
        {
          "jsonrpc": "2.0",
          "id": 2,
          "method": "eth_getBalance",
          "params": [
            "0x018e221145dE7cefAD09BD53F41c11A918Bf1Cb7",
            "latest"
          ]
        },
        {
          "jsonrpc": "2.0",
          "id": 3,
          "method": "eth_getBalance",
          "params": [
            "0x67AE7e4b867330013808fD4EE92FEDbb31CCc3bb",
            "latest"
          ]
        }
      ]);
      console.log(res);

```

metamask throws error, and sending raw request directly to some node it accepts:

```
curl --location 'https://ethereum-rpc.publicnode.com' \
--header 'Content-Type: application/json' \
--data '[
    {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "eth_getBalance",
        "params": [
            "0x18532dF2Ab835d4E9D07a8b9B759bf5F8f890f49",
            "latest"
        ]
    },
    {
        "jsonrpc": "2.0",
        "id": 2,
        "method": "eth_getBalance",
        "params": [
            "0x018e221145dE7cefAD09BD53F41c11A918Bf1Cb7",
            "latest"
        ]
    },
    {
        "jsonrpc": "2.0",
        "id": 3,
        "method": "eth_getBalance",
        "params": [
            "0x67AE7e4b867330013808fD4EE92FEDbb31CCc3bb",
            "latest"
        ]
    }
]'

```

gives:

```
[
    {
        "jsonrpc": "2.0",
        "id": 1,
        "result": "0x0"
    },
    {
        "jsonrpc": "2.0",
        "id": 2,
        "result": "0x0"
    },
    {
        "jsonrpc": "2.0",
        "id": 3,
        "result": "0x0"
    }
]

```

**Comment by TNBT12g** [comment]
Hi everyone, I get this result: 
```
[
    {
        "id": 1,
        "jsonrpc": "2.0",
        "result": "0x0"
    },
    {
        "id": 2,
        "jsonrpc": "2.0",
        "result": "0x56bc75e2d63100000"
    },
    {
        "id": 3,
        "jsonrpc": "2.0",
        "result": "0x3cb71c7c357af8200"
    }
]
```
`
export default async function getBalances() {
  const web3 = new Web3(new Web3.providers.HttpProvider("HTTP://127.0.0.1:7545"));
  // const web3 = new Web3("http://127.0.0.1:7545");
  const startTime = Date.now()

  const batch = new web3.BatchRequest();
  const request1: any = {
      jsonrpc: '2.0',
      id: 1,
      method: 'eth_getBalance',
      params: ['0x9F636e8b5f6d096430E0b260093eBc09A16501fA', 'latest'],
  };
  const request2: any = {
      jsonrpc: '2.0',
      id: 2,
      method: 'eth_getBalance',
      params: ['0xc31FA525Cc32646B97e7B9BdCCd46Fd35F40925e', 'latest'],
  };
  const request3: any = {
      jsonrpc: '2.0',
      id: 3,
      method: 'eth_getBalance',
      params: ['0x4cc2d26822aD627619b7F1426A4B5aE1e68E014e', 'latest'],
  };

  batch.add(request1);
  batch.add(request2);
  batch.add(request3);

  console.log(await batch.execute());
  return;

}
`
I dont know what this is, I thought it will give us the balance of wallet. Please explain to me. Thank everyone.
