### ISSUE TITLE
toHex converts '4' to 0x34

### ISSUE THREAD

**Issue by ittayd** [ethereum/web3.js#6584]
The problem is that the parameter is a string, that represents an int and it not Number.isFinite and therefore is treated as utf8 byte array where '4' has the ascii value 52 that is then 0x34

#### Expected behavior
return '0x4'

#### Actual behavior
returns '0x34'

#### Steps to reproduce the behavior

1. toHex('4')

#### Environment

web3-utils 4.0.7

**Comment by jdevcs** [comment]
You may use `web3.utils.numberToHex('4');`
