### ISSUE TITLE
sendTransaction to anvil, fail with error: "unknown field `chain`"

### ISSUE THREAD

**Issue by Jayanring** [ethereum/web3.js#6597]
#### Steps to reproduce the behavior

I use `web3.eth.sendTransaction` to send transaction to an anvil local testnet without specifing gas.

```
    const tx = {
        from: fromAddress,
        to: toAddress,
        data: "0x1234abcd",
    }

    await web3.eth.sendTransaction(tx)
```

```
$ node demo.js 
(node:10247) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/home/w/node_modules/web3-core/lib/commonjs/web3_request_manager.js:279
                throw new web3_errors_1.InvalidResponseError(response, payload);
                      ^

InvalidResponseError: Returned error: unknown field `chain`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `input`, `nonce`, `chainId`, `accessList`, `type`
    at Web3RequestManager._processJsonRpcResponse (/home/w/node_modules/web3-core/lib/commonjs/web3_request_manager.js:279:23)
    at Web3RequestManager.<anonymous> (/home/w/node_modules/web3-core/lib/commonjs/web3_request_manager.js:177:29)
    at Generator.next (<anonymous>)
    at fulfilled (/home/w/node_modules/web3-core/lib/commonjs/web3_request_manager.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: {
    code: -32602,
    message: 'unknown field `chain`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `input`, `nonce`, `chainId`, `accessList`, `type`'
  },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: 'ff609723-5191-4fb7-9ea5-bde4f71e5475',
    method: 'eth_estimateGas',
    params: [
      {
        from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        to: '0x1e1f37Deadc0289f95428ec99C0e2c4731Ae5018',
        data: '0x1234abcd',
        maxPriorityFeePerGas: '0x9502f900',
        maxFeePerGas: '0x10c388d00',
        nonce: '0x0',
        value: '0x0',
        chain: 'mainnet',
        hardfork: 'london',
        chainId: '0x7a69',
        networkId: '0x7a69',
        type: '0x2',
        accessList: []
      },
      'latest'
    ]
  }
}

Node.js v21.1.0
```

It works if I specify a gas filed

#### Environment

web3.js: 4.2.2
anvil 0.2.0 (529559c 2023-11-13T00:17:09.520018400Z)

**Comment by Muhammad-Altabba** [comment]
Hi @Jayanring,
Thanks for opening an issue.
As the message state, the field `chain` is unsupported to be passed to the method `sendTransaction`. And actually, the field `chainId` is the only one that you need to specify the network. As every network (chain) has its unique `chainId`.

I am closing this issue, as resolved. However, you can reopen this issue if you feel there is more to it.

**Comment by Jayanring** [comment]
Thanks for replying.

Please notice that I've not pass `chain` to `sendTransaction`, this function fills in some fileds itself, like `chain`, and use them to call `eth_estimateGas`, but `anvil` doesn't seem to accept those, and then an error returns.

```
    const tx = {
        from: fromAddress,
        to: toAddress,
        data: "0x1234abcd",
    }

    await web3.eth.sendTransaction(tx)
```

The codes above work with `Ganache`，but not with `Anvil`.

**Comment by Muhammad-Altabba** [comment]
Thanks @Jayanring,
We will see if we can not fill `chain` some how (not filing it at all or provide an option for the user to decide).

**Comment by Muhammad-Altabba** [comment]
We will work on enabling the user to pass `chain: undefined`,  to tell web3.js to not pass the chain when sending the transaction.

**Comment by luu-alex** [comment]
Hey there! I was able to use your example and send a transaction sucessfully, so i believe this issue is fixed. if its still occuring feel free to comment again and ill re-open up the issue.
