### ISSUE TITLE
Enable passing a privatekey an optional parameter to signTransaction and Contract to use it to sign the transactions

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6600]
Currently, eth.sendTransaction and Contract deployment and send methods uses the providers' account.
It would be nice to the enable passing a privatekey, or a wallet object that contains a privatekey, as an optional parameter to sendTransaction and Contract in order to use it to sign the transactions.

I suggest to implement `web3.eth.accounts.sendTransaction` that accepts the private key as a parameter. And also add this parameter as optional to `web3.eth.sendTransaction` so they become aliases.
And also to add the private key parameter to `web3.eth.signTransaction` so it becomes an alias to `web3.eth.account.signTransaction`

**Comment by mpetrunic** [comment]
What would be usecase for that? 
Like you can already add account from private key once and use "from" field to use that account, no?

Generally, I don't think the right direction is to use private key too much. It would make a lot more sense to enable people integration with some more secure components that can keep private key secure.
