### ISSUE TITLE
Add methods to populate transaction data of contract deploy and send methods

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6601]
Add a method to construct the transaction for the contract deploy and send methods. So the user can can sign and send later this transaction object.
We might name this methods `populateTransaction` like in ethers.js. And add a method called `encodeFunctionData`, that just return the `input` field, like in viem. In order to keep the convention with some other web3 libraries.

**Comment by mpetrunic** [comment]
But we can already do that, in web3-eth-abi there is method encodeFunctionCall and all contract methods have encodeABI method that returns tx data that can be submitter later on
