### ISSUE TITLE
Hardhat tutorial (web3js docs)

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6632]
Hi guys, given the recent [compatibility update](https://github.com/NomicFoundation/hardhat/pull/4570) of Hardhat plugin [hardhat-web3-v4](https://www.npmjs.com/package/@nomicfoundation/hardhat-web3-v4), I propose creating a tutorial to guide developers about using web3js through hardhat (since Truffle is deprecated).

**Comment by Thanos107** [comment]
Hey @SantiagoDevRel can I take the issue?

**Comment by SantiagoDevRel** [comment]
Hey @Thanos107 thanks for your interest! I was planning to start with this next week, but I'm glad you want to contribute to the Hardhat guide. Of course! 
How long do you think it will take you to have a first draft?
Thank you!

**Comment by Thanos107** [comment]
I can prepare the draft within a few days. But can you guide me through a step-by-step process of what you need in the documentation?

**Comment by SantiagoDevRel** [comment]
Sure! I'll reach out to you on linkedIn/twitter to provide some guidance

**Comment by bobeu** [comment]
Hello @SantiagoDevRel May I ask to work on this issue if yet to be resolved?

**Comment by SantiagoDevRel** [comment]
Hey @bobeu, feel free to work on it, are u able to make a PR within 1 week?  
these 2 links might be useful
[sample repo](https://github.com/SantiagoDevRel/hardhat-web3js)
[web3 hardhat plugin](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-web3-v4)

**Comment by bobeu** [comment]
Thank you @SantiagoDevRel I'll try my best to send in PR within that time.

**Comment by bobeu** [comment]
> Hey @bobeu, feel free to work on it, are u able to make a PR within 1 week? these 2 links might be useful [sample repo](https://github.com/SantiagoDevRel/hardhat-web3js) [web3 hardhat plugin](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-web3-v4)

@SantiagoDevRel Where do I push an update if I need to? I meant if I could push to this repository.

**Comment by SantiagoDevRel** [comment]
@bobeu i think you are able to do this:
1. Create a branch 'git checkout -b hardhat-guide-6632
2. Add and commit to the branch
3. Push to the branch
4. Compare and PR (maybe a PR draft if is not ready yet would be fine) 

Lmk if u are able to follow that!💪 thanks

**Comment by bobeu** [comment]
> Hey @bobeu, feel free to work on it, are u able to make a PR within 1 week? these 2 links might be useful [sample repo](https://github.com/SantiagoDevRel/hardhat-web3js) [web3 hardhat plugin](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-web3-v4)

Ok great. Now I get it. Thanks.

**Comment by SantiagoDevRel** [comment]
Oh yeah, the link above is just a repo i was doing to play around with hardhat, so it might be helpful for your reference, but no need to do anything there

**Comment by SantiagoDevRel** [comment]
Hi @bobeu , any updates?

**Comment by bobeu** [comment]
> Hi @bobeu , any updates?

@SantiagoDevRel I will make the PR within 48 hours from now. I have been down for days. I am getting better. In 12 hours, I should be back home. Expect an update shortly. Thanks

**Comment by SantiagoDevRel** [comment]
No problem at all @bobeu , health comes first! 
Take your time and feel free to do it by the end of this week, dont worry 👍👍

**Comment by bobeu** [comment]
@SantiagoDevRel I made a push [here](https://github.com/web3/web3.js/pull/6806) Please check to see if I have done what you expected. I will make a few changes tomorrow plus any requested changes you may have.

**Comment by jdevcs** [comment]
@bobeu Thanks for your contributions

**Comment by bobeu** [comment]
> @bobeu Thanks for your contributions

My pleasure @jdevcs
