### ISSUE TITLE
Recent Upgrade - 1.10.0 to 4.3.0 toWei as value not working as expected

### ISSUE THREAD

**Issue by c1im4cu5** [ethereum/web3.js#6651]
I've poured over the documentation for the newest version (v4.3.0) . Funcitonality works in v1.10.  

The value of a transaction object sent in wei is not intepreted as expected.  See below. When sending a single ether as a value in the object, the user signing value does not match the expected value.

```
const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
const wallet = accounts[0];
const contractInstance = new web3.eth.Contract(contractABI, contractAddress);

const bnValue = 1;
const bnWei = web3.utils.toWei(bnValue, 'ether');
const bnWeiString = web3.utils.toWei(bnValue.toString(), 'ether');

console.log("BN WEI: ", bnWei);
console.log("BN WEI String: ", bnWeiString);

// Create a transaction object
const transactionObject = {
  from: wallet,
  to: contractAddress,
  data: contractInstance.methods.executeCondemned(
                                            sendString,
                                            true,
                                            bnWei).encodeABI(),
  value: bnWei,
};

let gasEstimate = await web3.eth.estimateGas(transactionObject);
console.log("Estimate: ", gasEstimate);
let gasPrice = await web3.eth.getGasPrice();
console.log("PRICE: ", gasPrice);
let gasFee = gasEstimate
console.log("FEE: ", gasFee);

// Now, you can construct and send your transaction with the calculated gas values
const newTxParameters = {
  ...transactionObject,
  gas: web3.utils.toHex(gasFee), // Use the estimated gas cost
  gasPrice: web3.utils.toHex(gasPrice), // Use the current gas price
};

//Send to user via eth_sendTransaction request with parameters
const transactionHash = await window.ethereum.request({
  method: 'eth_sendTransaction',
  params: [newTxParameters]
});
```

#### Expected behavior
I am expecting the attached value (in Wei) to be a single ether. 

#### Actual behavior
"value" sent as bnWei is 4500+ ether when attempting to sign the transaction. bnValue is hard-coded as a single digit (1). 

#### Steps to reproduce the behavior
Vyper contract is deployed to Avalanche Fuji. Please reach out for interaction details if you wish to reproduce.

#### Environment
React, NodeJS, Vyper

**Comment by mconnelly8** [comment]
Hey @c1im4cu5, sorry you are experiencing this.  I'll try and find a solution for you.

**Comment by c1im4cu5** [comment]
I really appreciate it @mconnelly8 

It could be a few problems (along with me). The loss of toBN() in v4.3 created some problems for me. I cannot figure out if it is toWei causing the problem, toBigInt or my own fault, lol.

For v1.10, I would use

web3.utils.toWei(web3.utils.toBN(value))

web3.utils.toWei(web3.utils.toBigInt(value)) does not accomplish the task correctly. 

Manually setting value at value = value * 10 ** 18 doesn't work (string or int).

Suggestions are very welcome!

**Comment by Muhammad-Altabba** [comment]
Thanks @c1im4cu5 for sharing this.
Could you please also share the full code so we can reproduce? You may share a github repository or better to share on some Cloud IDE like https://codesandbox.io/, for example.
Did you try this on Ethereum mainnet, a test net or geth?
Also could you please edit your post to add what every console.log gives? 
Thanks in advance,

**Comment by jdevcs** [comment]
@c1im4cu5 if you are sending tx by skipping web3.js's  sendTransaction() and via: `window.ethereum.request()` use following:
```
 const transactionObject = {
         //...
          value: web3.utils.toHex(web3.utils.toNumber(bnWei)),
        };
```
and if you want to using `web3.eth.sendTransaction()` it will internally take care formatting, and you can pass string
