### ISSUE TITLE
Search for websites that still pointing to web3.js docs v1.x, and ask to update them 

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6652]
Many websites  still pointing to web3.js docs version 1. We need to search for those and asks to update the URL. And when there is a description to update the description as well.
 
For example:

- Open a PR to update at: https://github.com/yjjnls/awesome-blockchain
- Right a comment or send a message to update the link and the description at: https://dev.to/envoy_/awesome-web3-519
- ... many many many others

Actually, searching for "web3.js documentation" or "web3.js docs" on google currently gives the version 1.x first. This indicate that most of the websites are still referencing the old version. As google rank the pages is partially depends on the number of mentions in other websites.

There are some tools to find the places that needs updates. Here is an example of an article that list some of them: https://www.reliablesoft.net/who-links-to-my-site/

**Comment by Topichido** [comment]
I will take over this

**Comment by Topichido** [comment]
https://docs.google.com/document/d/1V95Y-MlLwqyGRloBJ9optyB414rrFGpABNm37eNZe78/edit - Please do check the document, I made corrections to articles, made tweets, and commented on youtube videos that hold the Web3.js V1 information.

@mconnelly8

**Comment by jdevcs** [comment]
@Topichido Thanks for your contributions
