### ISSUE TITLE
Update jest version

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6654]
The pipeline is falling with an error:
> web3-eth-ens:  FAIL  test/unit/ens.test.ts
web3-eth-ens:   ● Test suite failed to run
web3-eth-ens:     TypeError: Cannot assign to read only property 'performance' of object '[object global]'
web3-eth-ens:       24 | import { ENS } from '../../src/ens';
web3-eth-ens:       25 |
web3-eth-ens:     > 26 | jest.useFakeTimers().setSystemTime(new Date('2020-01-01'));
web3-eth-ens:          |      ^
web3-eth-ens:       27 |
web3-eth-ens:       28 | jest.mock('web3-eth', () => ({
web3-eth-ens:       29 | 	__esModule: true,
web3-eth-ens:       at hijackMethod (../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:946:32)
web3-eth-ens:       at Object.install (../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1733:17)
web3-eth-ens:       at FakeTimers.useFakeTimers (../../node_modules/@jest/fake-timers/build/modernFakeTimers.js:110:36)
web3-eth-ens:       at Object.<anonymous> (test/unit/ens.test.ts:26:6)

Failed job: https://github.com/web3/web3.js/actions/runs/7171874933/job/19529211496?pr=6647#step:5:209

And updating jest would resolve the issues. However, the generated test snapshots would need to be re-generated in order to be compatible with the new version.

We need to update jest in all dependencies like this: https://github.com/web3/web3.js/pull/6647/commits/93d340ab9b48448a852131b6076008a932d6a15a, re-generate the test snapshots and modify for any other breaking changes in the new jest version.

**Comment by ilKhr** [comment]
I have the same problem

```log
FAIL src/message.test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      4 | const fakeTime = 168260239
      5 |
    > 6 | jest.useFakeTimers().setSystemTime(new Date(fakeTime));
        |      ^
      7 |
      8 | jest.mock('src/constants/env', () => {
      9 |   const oldModule = jest.requireActual('src/constants/env');

      at hijackMethod (../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:946:32)
      at Object.install (../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1733:17)
      at Object.<anonymous> (src/message.test.ts:6:6)
```

**Comment by ilKhr** [comment]
https://github.com/nodejs/node/issues/51048#issuecomment-1845910727
