### ISSUE TITLE
web3js@latest : Uncaught TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by zoubair-hattab** [ethereum/web3.js#6660]
Could you please assist me in resolving an issue with the latest version of web3.js 4.x. I'm attempting to connect with MetaMask using the following code:

export const loadWeb3 = async (dispatch) => {
  console.log(Web3);
  const web3 = new Web3(Web3.givenProvider || 'http://localhost:8545');
  dispatch(actions.web3Loaded(web3));
  return web3;
};

However, I've encountered an error: "Do not know how to serialize a BigInt TypeError: Do not know how to serialize a BigInt." The interesting part is that everything works perfectly when I use a legacy version of web3.js. Any insights or assistance would be greatly appreciated.

**Comment by mconnelly8** [comment]
Hey @zoubair-hattab, take a look at this [solution](https://github.com/GoogleChromeLabs/jsbi/issues/30) and let me know if that helps. 

JS doesn't support serialization of BigInt yet.

**Comment by zoubair-hattab** [comment]
@mconnely8:i have used this but the same issue still

**Comment by mconnelly8** [comment]
@zoubair-hattab, can you send me the code snippet you are using with that workaround?

**Comment by mconnelly8** [comment]
Hey @zoubair-hattab, closing this issue do to no response.  If you are still experiencing the issue, please provide us with the code snippet to review and reopen.  Thanks.
