### ISSUE TITLE
Blank website

### ISSUE THREAD

**Issue by jeluard** [ethereum/web3.js#6664]
Main website is completely blank for me on chrome. 

I can see the following error in the console:

```js
Error: Cannot find module './fr/messages.js'
    at |groupOptions: {}|namespace object:10:12
```

Might be due to some locale handling issue?

**Comment by mconnelly8** [comment]
Hey @jeluard, what "main website"?

**Comment by jeluard** [comment]
By main website I mean https://web3js.org/.

<img width="1226" alt="Capture d’écran 2023-12-14 à 23 41 06" src="https://github.com/web3/web3.js/assets/359723/5210e435-6862-4c5c-b641-ae137db1b724">

**Comment by luu-alex** [comment]
does it work now? its loading for me

**Comment by jeluard** [comment]
No, tried on safari, firefox and chrome.

**Comment by jeluard** [comment]
@luu-alex does it work for you when you configure your browser with french as locale?

I can confirm that switching to english as locale fixes the issue.

This looks suspicious to me: https://github.com/web3/web3js-landing/blob/main/src/App.tsx#L67
While the french locale doesn't exist: https://github.com/web3/web3js-landing/tree/main/src/locales

**Comment by luu-alex** [comment]
thanks for this, will try to contact the right ppl to fix this

**Comment by jeluard** [comment]
See https://github.com/web3/web3js-landing/pull/43

**Comment by luu-alex** [comment]
thanks, this should be fixed soon

**Comment by luu-alex** [comment]
merged, changes should be reflected soon. thanks!

**Comment by jeluard** [comment]
I can confirm it now works?

FYI I now get the following error message in the console:

```js
TypeError: Cannot assign to read only property '0' of object '[object String]'
    at Function.assign (<anonymous>)
    at n.value (toConsumableArray.js:7:1)
    at toConsumableArray.js:7:1
    at Array.forEach (<anonymous>)
    at n.value (toConsumableArray.js:7:1)
    at LanguageContext.tsx:92:14
```

It might be related to the `en` `messages.js` which is empty.
