### ISSUE TITLE
How to getBalance from wallet in backend nodejs?

### ISSUE THREAD

**Issue by maitsysraja** [ethereum/web3.js#6671]
Hi, 

The following snippet works fine in client-side Javascript. I have two tokens in the meta-mask 
wallet and it shows the selected one. 
 
     if (typeof window.ethereum !== 'undefined') {
        const web3 = new Web3(window.ethereum);
        var accounts = await web3.eth.getAccounts();
        const n = await web3.eth.getBalance(accounts[0]);
        const balance = web3.utils.fromWei(n, "ether");
        console.log(balance);
      try {
        // Request account access
        await window.ethereum.enable();
        return true
      } catch(e) {
        // User denied access
        return false
        }
       }
     } 
      web3JSDemo();
    
The below snippet in the backend code is always returning 0. 
Also, How do I get the balance and the corresponding token information?
I have ETH and tBNB tokens in my wallet.

      export async function getWalletByCreated(created_by, web3_wallet) {
           const object = new Web3(new Web3.providers.HttpProvider([process.env.cryptoNetwork](https://palm-testnet.infura.io/v3/api_key)));
          const n = await object.eth.getBalance(web3_wallet);
          const balance = object.utils.fromWei(n, "ether");
          const blockNumber=await object.eth.getBlockNumber();
          console.log('Latest block number:', blockNumber);
          return { balance: Number(balance) }   
     }

**Comment by SantiagoDevRel** [comment]
Hi @maitsysraja , that's the right way of getting the balance of a wallet `await web3.eth.getBalance(address)`.
I'm just thinking there are 2 potential issues: 
1. The provider endpoint, are you calling the right network? is it returning the last block number properly?
2. Make sure the `web3_wallet` you are using as an argument is sending the right wallet address, maybe do a console.log(web3_wallet) before?
