### ISSUE TITLE
Incorrect return type when calling contract methods

### ISSUE THREAD

**Issue by bossikkk** [ethereum/web3.js#6672]
```
  import Web3, { FMT_BYTES, FMT_NUMBER, HttpProvider } from 'web3';

  const lib = new Web3(new HttpProvider('https://bsc-dataseed4.defibit.io'));

  const contract = new lib.eth.Contract(
      [
        {
          inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
          name: 'balanceOf',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
        },
      ] as const,
      '0x6233fb6434e423e47b82c26a1d8294f954c92a47',
      {
        number: FMT_NUMBER.STR,
        bytes: FMT_BYTES.HEX,
      }
    );

    const walletAddress = '0xe5cB0ee3007D9188c006EeCA1523455E0e044E18';
    const balance = await contract.methods.balanceOf(walletAddress).call();

    console.log(typeof balance);
```
Expect: type string
Actual: type bigint

Web3: v4.3.0
Node js: v18.12.1

**Comment by furkanksl** [comment]
Hey @bossikkk 

In your contract initialization,

checkout abi part : 
```
[
       {
          inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
          name: 'balanceOf',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
        },
 ] as const,
 ```
 
 
 in `outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }]` section, it says it is going to return `uint256`.  
 
 If you want to convert to string, you can convert to number with toNumber() and then to string with toString()

**Comment by bossikkk** [comment]
@furkanksl Hey. I understand it. But why **contextOrReturnFormat** parameter don't convert result to string? 
```
  {
        number: FMT_NUMBER.STR,
        bytes: FMT_BYTES.HEX,
  }
```

**Comment by furkanksl** [comment]
Hey @bossikkk , yes you are right. There is a bug on convertion.  I got same error you got. 

@Muhammad-Altabba  I think that is a bug on v4.x . 

<img width="797" alt="Screenshot 2024-01-08 at 8 55 13 PM" src="https://github.com/web3/web3.js/assets/49058467/fc045f37-b45e-4b76-b82a-23a908eebd70">

<img width="463" alt="Screenshot 2024-01-08 at 8 58 13 PM" src="https://github.com/web3/web3.js/assets/49058467/152717a7-9a09-481b-958f-a39b41cf12d6">

**Comment by mconnelly8** [comment]
Hey @bossikkk & @furkanksl, thank you for the information and talking through this.   The team will be reviewing this tomorrow and determining next steps.

**Comment by Muhammad-Altabba** [comment]
Hi @bossikkk and @furkanksl,
Thanks for opening the issue and providing your findings.

The passed format at the constructor is only used to format the provided address and the emitted contract events later.
For formatting the returned value. You may use something like:
```ts
    const balance = utils.format({ eth: 'unit' },await contract.methods.balanceOf(walletAddress).call(), returnFormat);
```

However, we will discuss within the team if we will change to get the format from the constructor, or to keep the current behavior and document it.
Thanks,

**Comment by mconnelly8** [comment]
Hey @bossikkk & @furkanksl,
The team discussed this and determined that we need to create a guide/tutorial outlining this.   We will be tracking the tutorial with #6711.
