### ISSUE TITLE
Web3 is not a constructor

### ISSUE THREAD

**Issue by wantairanwtr** [ethereum/web3.js#6691]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by SantiagoDevRel** [comment]
Hi @wantairanwtr please share your code, but I'm almost sure you are importing incorrectly the  Web3 object, it should be with curly brackets:

`const { Web3 } = require("web3")` or `import { Web3 } from "web3";`

**Comment by QuentinNev** [comment]
I got this error too but `const { Web3 } = require("web3");` doesn't work. (Using 4.7.0)
