### ISSUE TITLE
Result of contract method .send is hard to type

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#6701]
If you wanna pass returned Web3PromiEvent it's hard to preserve typing. Maybe makes sense to provide some utility type for that

**Comment by mpetrunic** [comment]
Also Web3PromiEvent doesn't seem to be exported

**Comment by avkos** [comment]
@mpetrunic , `Web3PromiEvent` exported in `web3-core` package
https://github.com/web3/web3.js/blob/4.x/packages/web3-core/src/web3_promi_event.ts

**Comment by mpetrunic** [comment]
> @mpetrunic , `Web3PromiEvent` exported in `web3-core` package https://github.com/web3/web3.js/blob/4.x/packages/web3-core/src/web3_promi_event.ts

Maybe also add here: https://github.com/web3/web3.js/blob/4.x/packages/web3/src/index.ts#L336 ?
