### ISSUE TITLE
Bug: the interval in the confirmTransaction runs endlessly and not cleared

### ISSUE THREAD

**Issue by Fleynaro** [ethereum/web3.js#6733]
When I call **sendSignedTransaction**, it sometimes runs an infinite interval with a call to **eth_getTransactionReceipt** to make sure the transaction is mined. Even if the transaction is mined and **eth_getTransactionReceipt** returns the success result, the interval is not cleared.

I investigated and found out that the problem lies here:
https://github.com/web3/web3.js/blob/24d310caa06af88cb1fe236b7d3b9d135f053d71/packages/web3-core-method/src/index.js#L202

If the timeout https://github.com/web3/web3.js/blob/24d310caa06af88cb1fe236b7d3b9d135f053d71/packages/web3-core-method/src/index.js#L578 is executed earlier than the event newBlockHeaders https://github.com/web3/web3.js/blob/24d310caa06af88cb1fe236b7d3b9d135f053d71/packages/web3-core-method/src/index.js#L566, then the interval will be started. But then the **newBlockHeaders** event handler will be executed, thanks to which the result promise could be resolved (_getTransactionReceipt returned success response_) but the interval will NOT be cleared.

So I get a situation when `promiseResolved = true;`, but **the interval** continues to work.
Of course, there may be other reasons

#### Expected behavior
The interval should be cleared when **getTransactionReceipt** returns the success response.

#### Actual behavior
The interval is not cleared and runs endlessly in the background.

#### Steps to reproduce the behavior
Very hard to reproduce the problem because of a race condition. But if you set `web3.blockHeaderTimeout` to less than 1 (e.g. 0.5) and call **sendSignedTransaction**, the problem is very likely occured. In the production I use the default value of `web3.blockHeaderTimeout`.

#### Logs
No errors written to the console, but I have the following diagram.
With each call to sendSignedTransaction, the number of calls to eth_getTransactionReceipt also increases as non-cleared background intervals increases.

![image](https://github.com/web3/web3.js/assets/17672473/356739cc-da17-4689-b771-91f615e8aff8)

#### Environment

nodejs: 16.20.0
webjs: 1.10.3

**Comment by Fleynaro** [comment]
At the moment I am using this fix and the problem seems to have disappeared.

```
diff --git a/node_modules/web3-core-method/lib/index.js b/node_modules/web3-core-method/lib/index.js
index 5dc909e..d53c38b 100644
--- a/node_modules/web3-core-method/lib/index.js
+++ b/node_modules/web3-core-method/lib/index.js
@@ -401,10 +401,12 @@ Method.prototype._confirmTransaction = function (defer, result, payload) {
                             utils._fireError(errors.TransactionOutOfGasError(receipt), defer.eventEmitter, defer.reject, null, receipt);
                         }
                     }
+                    promiseResolved = true;
+                }
+                if (promiseResolved) {
                     if (canUnsubscribe) {
                         sub.unsubscribe();
                     }
-                    promiseResolved = true;
                 }
             })
                 // time out the transaction if not mined after 50 blocks
@@ -441,6 +443,7 @@ Method.prototype._confirmTransaction = function (defer, result, payload) {
     var startWatching = function (existingReceipt) {
         let blockHeaderArrived = false;
         const startInterval = () => {
+            if (intervalId) return;
             intervalId = setInterval(checkConfirmation.bind(null, existingReceipt, true), method.transactionPollingInterval);
         };
         // If provider do not support event subscription use polling
```

**Comment by SantiagoDevRel** [comment]
Hi @Fleynaro , thank you so much for submitting this valuable issue, one of our core devs will take a look at this soon 💪

**Comment by jdevcs** [comment]
@Fleynaro did you try [web3 v4 ](https://www.npmjs.com/package/web3)for above scenario?

**Comment by Muhammad-Altabba** [comment]
Hello @Fleynaro ,
In v4.x, we have a test that is running with other tests after every code update. At it works well.
https://github.com/web3/web3.js/blob/b49094b953f9c9292891057e83842937cba92b7c/packages/web3-eth/test/unit/utils/watch_transaction_by_subscription.test.ts#L107
Could you please update to web3.js version 4? And let us know if you face any issue?

I will close this issue in favor of updating to version 4. However, if you faced the same issue there, please feel free to reopen it. And if you faced any other issue, please open a separate issue for that.
