### ISSUE TITLE
Events Guide

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6741]
2024 H1 Action Items: Expand web3.js documentation with 5 guides explaining common usage and/or best practices

**Comment by SantiagoDevRel** [comment]
References:
- Change this [`introduction`](https://docs.web3js.org/guides/events_subscriptions/) section for `Mastering events subcriptions` and include sample codes for every supported subscriptions
- add a sample code to subscribe to a smart contract events using the contract instance  (with comments and more organized)
```ts
import {Web3} from "web3";
  
const web3 = new Web3("provider");

const contract = new web3.eth.Contract(abi, address);

const subscription = contract.events.RandomNo()
subscription.on("data", console.log);
```

**Comment by Yazi27** [comment]
Also, chaining .on's does not work anymore as stated on the 1.2.0 docs
