### ISSUE TITLE
Utils Guide

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6742]
2024 H1 Action Items: Expand web3.js documentation with 5 guides explaining common usage and/or best practices

Multiple guides on Utils will be created.

**Comment by SantiagoDevRel** [comment]
References:
- Create a folder (category) named `📦 Web3 Utils module` with `Mastering web3-utils` submenu
- Create a guide showcasing some of the most important `utils` methods and use cases for it
- Video for reference https://www.youtube.com/watch?v=fmwwzVCETh0
- add live code editor to it

**Comment by mabsattar** [comment]
Hi, I would like to work on this, can you please assign me.

**Comment by SantiagoDevRel** [comment]
Amazing @mabsattar feel free to take it over and tag me if u have any questions

**Comment by jdevcs** [comment]
@mabsattar are you working on this issue? dnt forget to link PR with issue for tracking, Thanks

**Comment by mabsattar** [comment]
Hi @jdevcs  Yes, i'm working on to make some changes, will push the commits soon.

**Comment by mabsattar** [comment]
@jdevcs  I've made the changes and pushed it.
