### ISSUE TITLE
Web3Modal client for web3.js: Implemenation

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6747]
[Web3Modal](https://docs.walletconnect.com/web3modal/about)  : is built on top of [Wagmi](https://wagmi.sh/react/guides/connect-wallet#third-party-libraries), It handle all the edge cases around wallet connection, and provide a seamless Connect Wallet UX that you can use in your Dapp. In this task Web3Modal client for web3.js should be implement as standalone lib. 

- [ ] Implement Functionality: Create web3modal lib for web3.js ( [like](https://www.npmjs.com/package/@web3modal/ethers) )

**Comment by Muhammad-Altabba** [comment]
Implementation goes here: https://github.com/ChainSafe/web3modal/pull/2
However, subsequent follow issues are to be created.
