### ISSUE TITLE
Web3Modal client for web3.js: Documentation

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6749]
Web3Modal : is built on top of Wagmi, It handle all the edge cases around wallet connection, and provide a seamless Connect Wallet UX that you can use in your Dapp. In this task Web3Modal client for web3.js should be implement as standalone lib.

- [ ] Add documentation: in [web3 modal docs](https://docs.walletconnect.com/web3modal/react/about?platform=ethers)

**Comment by mconnelly8** [comment]
Will write the default documentation from our side.  Once it's added to Web3Modal, they can update in their text.

**Comment by luu-alex** [comment]
https://github.com/ChainSafe/web3modal/pull/22
