### ISSUE TITLE
Web3Modal client for web3.js: Tests

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6750]
[Web3Modal](https://docs.walletconnect.com/web3modal/about)  : is built on top of [Wagmi](https://wagmi.sh/react/guides/connect-wallet#third-party-libraries), It handle all the edge cases around wallet connection, and provide a seamless Connect Wallet UX that you can use in your Dapp. In this task Web3Modal client for web3.js should be implement as standalone lib. 

- [ ] Test Modal:
- [config](https://docs.walletconnect.com/web3modal/react/about?platform=ethers#implementation) Test
- [Trigging modal](https://docs.walletconnect.com/web3modal/react/about?platform=ethers#trigger-the-modal) Test
- [Smart contract interaction](https://docs.walletconnect.com/web3modal/react/about?platform=ethers#smart-contract-interaction) Test
- Writing GitHub action scripts for tests

**Comment by avkos** [comment]
For test you can use a separate repository with cypress. like [this one](https://github.com/avkos/wagmi-web3js-example-app)

**Comment by Muhammad-Altabba** [comment]
web3modal has automated tests at apps / laboratory which uses PlayWright for testing.
Currently tests which are located at those files passes:
- basic-tests.spec.ts
- canary.spec.ts
- connect-qr.spec.ts
- wallet.spec.ts
- siwe.spec.ts

![image](https://github.com/web3/web3.js/assets/24407834/eee9f21a-e9be-4900-887f-8ef14e79b474)

![image](https://github.com/web3/web3.js/assets/24407834/0dcf6eac-84cc-4e4b-9e8f-6e58e02fad16)


For context: https://github.com/ChainSafe/web3modal/pull/2#issuecomment-2071966907 and https://github.com/ChainSafe/web3modal/pull/2#issuecomment-2069022889


The rest of the tests are for emails and smart accounts. And they needed to be verified and probably fixed at this follow-up issue: https://github.com/web3/web3.js/issues/6995.
