### ISSUE TITLE
Typo in docs while importing web3

### ISSUE THREAD

**Issue by vedant-asati** [ethereum/web3.js#6761]
#### Actual behavior
Web3 isnt getting imported properly due to minor error in web3.js [documentation](https://web3js.readthedocs.io/en/v1.8.2/getting-started.html).

#### Steps to reproduce the behavior

1. Try running this code on node repl:
<img width="362" alt="image" src="https://github.com/web3/web3.js/assets/114929867/cc552ad7-7e2a-46d4-973f-d2f2e048fbd5"><br>
2. uncomment the first line while using node.
<img width="323" alt="image" src="https://github.com/web3/web3.js/assets/114929867/acf22c86-12d7-4988-98c4-d96205d73dfd">

#### Proposed Solution
The issue is resolved when i use {Web3} instead of Web3 while importing.
<img width="433" alt="image" src="https://github.com/web3/web3.js/assets/114929867/cad10c05-6d0c-4436-909c-843f9f8d395e">

#### Environment
npm : 10.2.3
Node : v20.10.0
web3.js : 10.2.3
OS: Windows 11

**Comment by SantiagoDevRel** [comment]
Hi @Vedant-asati , you are referencing `web3 v1` which will be deprecated in a couple of months, please check `web3 v4` [docs](https://docs.web3js.org/)

**Comment by vedant-asati** [comment]
Thanks. I am a beginner and I mistakenly took it for an issue.

**Comment by SantiagoDevRel** [comment]
No problem at all, welcome to web3 then!💪
Feel free to join the [discord](https://discord.gg/SqrsW4apvB) and ask any questions related to web3.js in the channel `#web3js-general`
