### ISSUE TITLE
`web3.eth.accounts.wallet.create()` expected 1 argument

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6771]
Hi guys, will update this [page](https://docs.web3js.org/guides/wallet/local_wallet/) in the docs, since when you use the method `create()` for wallet, it works well with javascript (and it creates an empty wallet) but for typescript it shows the error `Expected 1 arguments, but got 0` so it might be confusing. this was shared by Greg.

**Comment by kamuik16** [comment]
> Hi guys, will update this [page](https://docs.web3js.org/guides/wallet/local_wallet/) in the docs, since when you use the method `create()` for wallet, it works well with javascript (and it creates an empty wallet) but for typescript it shows the error `Expected 1 arguments, but got 0` so it might be confusing. this was shared by Greg.

Hey @SantiagoDevRel! I have identified the issue and understood the code that when using `TypeScript` you need to pass in the number of wallets you want to create. Can I contribute on this?

See [here](https://github.com/web3/web3.js/blob/a72e99a4c3fee0069ca4bf7a8222b02ec5a60426/packages/web3-eth-accounts/src/wallet.ts#L125-L131).
