### ISSUE TITLE
Highlight web3.js features [docs/articles]

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6781]
Highlight web3.js bundle size by the different packages, in the docs and articles.
references:
- This can be added in the `Introduction` section of the `Getting started` category
- potentially research and add other advantages of web3.js over other libraries and add them

![image](https://github.com/web3/web3.js/assets/83420872/0f3f5fc1-1c9c-4a8c-9829-e2408fbbd53f)

**Comment by drparadox05** [comment]
Hey @SantiagoDevRel where should I add the advantages section on the page?

**Comment by SantiagoDevRel** [comment]
Hey @Deepak2030 , I think in the [Introduction](https://docs.web3js.org/guides/getting_started/introduction) below the: 
## Features

not sure what's the best way to show it, I think copy/pasting the image is not the best, maybe try to think about 1-2 nice ways to show that? feel free to create a chart, image, text, or whatever you'd like to see as a dev. Thank u!

**Comment by jdevcs** [comment]
@Deepak2030 are you still available to work on this, Thanks

**Comment by drparadox05** [comment]
Hey, I'm sorry I was busy for past few weeks. will complete it in couple of days if its fine?

**Comment by SantiagoDevRel** [comment]
Yes, go ahead, no problem @Deepak2030

**Comment by drparadox05** [comment]
Sorry for the delay, here's my PR: https://github.com/web3/web3.js/pull/6852
let me know if it needs any changes
