### ISSUE TITLE
Include features of web3.js in the npm package description

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6784]
Add web3.js general features in the [npm package](https://www.npmjs.com/package/web3) by editing the [README](https://github.com/web3/web3.js/blob/4.x/packages/web3/README.md)

**Comment by SantiagoDevRel** [comment]
Add the following:

- **[Web3.js Plugins](https://docs.web3js.org/guides/web3_plugin_guide/)**: Enhance or add any functionality by creating scalable web3 plugins for any project.
- **Abstractions over the [JSON-RPC API](https://ethereum.org/en/developers/docs/apis/json-rpc/)**: Simplifying interaction for your Developer Experience.
- **Language aligned to the official [Ethereum terminology](https://ethereum.org/en/glossary/)**
- **Tree-shaking focus:** Include only what you need during bundling for optimized performance.
- **Dynamic contract types and full API in TypeScript**: Enforced with strict types for enhanced security and safety.
- **Complete utilities and functionalities for all your Ethereum needs.**
- **More efficient ABI Encoder & Decoder**
- **Extensive [documentation](https://docs.web3js.org/) with guides and APIs**
- **Large collection of test cases**
- **First-class APIs for interacting with [Smart Contracts](https://ethereum.org/en/glossary/#smart-contract)**
- **ESM and CJS module builds**: Support for both ECMAScript module and CommonJS module builds for flexible integration with various project setups.
[Contracts dynamic types](https://docs.web3js.org/guides/smart_contracts/infer_contract_types/) & full API in TypeScript
- **Using native BigInt instead of large BigNumber libraries**: Use native BigInt for improved efficiency compared to using large external BigNumber libraries.
- **Custom Output formatters**: Format any returned value to be a string, number, BigInt, etc., providing flexibility in handling output data.

**Comment by AllenWasupan** [comment]
I can update this!

**Comment by SantiagoDevRel** [comment]
Perfect! @AllenWasupan , let me know if you need any support with making the PR or something. Please do it before next tuesday 💪👍

**Comment by SantiagoDevRel** [comment]
@AllenWasupan How is it going? - pls once u submit the PR, mention this issue #6784 in the PR.
If you face any issueus or you have any questions, feel free to DM me (linkedin, telegram or discord) or leave a comment here, I can help you with anything u need💪

**Comment by drparadox05** [comment]
Hey I've raised a PR here with the desired fix: https://github.com/web3/web3.js/pull/6804
