### ISSUE TITLE
[Docs] Issue when sending rawTxs to smart contracts

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6786]
Hi guys, this example of [Sending raw tx](https://docs.web3js.org/guides/wallet/transactions#sending-a-raw-transaction) works perfectly for sending value, but not for interacting with smart contracts, since the TX object must have `maxFeePerGas`, `maxPriorityFeePerGas` and `gasLimit`. 
PR ready for review:
#6783

**Comment by Mae6e** [comment]
innerError: { code: -32000, message: 'replacement transaction underpriced' },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: 'dadd3cb3-191d-46f7-a961-0656e9e06fa3',
    method: 'eth_sendRawTransaction',
    params: [
      '0xf8a6031483011d2894ed24fc36d5ee211ea25a80239fb8c4cfd80f12ee80b844a9059cbb0000000000000000000000000043bce89170e637807ddf72e2ef81ee14642acf0000000000000000000000000000000000000000000000008ac7230489e8000081e6a0d151457206f2fff1bf455d806698d2133df934b7760482e0cd17b38eddb20938a011747efde5b7cab58b2bd794e191113c0c4dfcaa7a615b319b3ab77664ea33bc'
    ]
  }

what is mean. why don't have a good document for transfer contracts and tokens?
