### ISSUE TITLE
2d array with web3 validator

### ISSUE THREAD

**Issue by ernieyang09** [ethereum/web3.js#6798]
For below scenario, it will fail in web3 validator
```javascript
    inputs: [
      { internalType: "address[]", name: "addr1", type: "address[]" },
      { internalType: "address[][]", name: "addr2", type: "address[][]" },
    ],
```

```javascript
const addr1 = ['0xaddr']
const addr2 [['0xaddr','0xaddr','0xaddr'],['0xaddr'], ['0xaddr','0xaddr'], ...]
contract.methods.xxMethod(addr1, addr2).estimateGas()
```

check the jsonSchema

```
{"type":"array","items":[{"type":"array","$id":"addr1","items":{"format":"address","required":true}},{"type":"array","items":[{"type":"array","$id":"addr2","items":{"for
mat":"address","required":true}}]}],"maxItems":2,"minItems":2}
```

Also the encodeABI method gave wrong output.

Test in web3.js v1.10.2. Works as expected.

#### Logs

```
code: 1100,
      errors: [
        {
          keyword: 'maxItems',
          instancePath: '/1',
          schemaPath: '#1/maxItems',
          params: { limit: 1 },
          message: 'must NOT have more than 1 items'
        }
      ]
```

#### Environment

web3.js 4.4.0

**Comment by SantiagoDevRel** [comment]
Hi @ernieyang09 
Please migrate to [web3.js v4](https://docs.web3js.org/) since v1 will be deprecated in a couple of months.
Pls try v4 and let us know if it doesn't work and we will be able to find a solution as soon as possible👍

**Comment by SantiagoDevRel** [comment]
Hi @ernieyang09 thanks for submitting the issue, the devs will take a look at it as soon as possible!👍

**Comment by RaghavenderSingh** [comment]
> Hi @ernieyang09 

Hey, I'm interested in working on this one

**Comment by SantiagoDevRel** [comment]
Great! Feel free to submit a PR and mention this issue on it #6798
Pls tag me so I can ping the team to look into it once it's done @RaghavenderSingh

**Comment by EtlesL** [comment]
Hi @SantiagoDevRel @RaghavenderSingh , I encountered the same issue in my work. Since the project is quite urgent, I took the initiative to debug and identify the problem myself. I have already submitted a PR for it. Here is the link: #6836

**Comment by jdevcs** [comment]
@EtlesL Thanks
