### ISSUE TITLE
Expand web3config guide [docs]

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6805]
We should expand this page of the docs [web3config](https://docs.web3js.org/guides/web3_config/)
- add code samples and explanation of each parameter that can be changed.
- parameter are listed [here](https://docs.web3js.org/guides/web3_config/#configuration-parameters)
Example:

### [handleRevert](https://docs.web3js.org/api/web3-core/class/Web3Config#handleRevert)

- Explain what handleRevert is, how it works, why is useful
- Code sample to set handleRevert at global leve
```js
new Web3({
  provider: 'https://mainnet.infura.io/v3/YOURID',
  config: {
    handleRevert: true,
  },
});
```
- Code sample to set handleRevert at package level
```js
const context = new Web3Context('http://127.0.0.1:7545');
context.setConfig({ handleRevert: true });
``` 

### [defaultAccount](https://docs.web3js.org/api/web3-core/class/Web3Config#defaultAccount)

- Explain what defaultAccount is, how it works, why is useful
- Code sample to set `defaultAccount` at global level 
- Code sample to set `defaultAccount` at package level...

**Comment by MeenuyD** [comment]
Hello @SantiagoDevRel I would like to work on this issue can you please assign it to me.

**Comment by MeenuyD** [comment]
Hello @SantiagoDevRel I would like to work on this issue can you please assign it to me

**Comment by mmyyrroonn** [comment]
@SantiagoDevRel @jdevcs Hello, I noticed the previous pull request hasn't been updated for a while and is about to be closed. May I take over this issue?

**Comment by SantiagoDevRel** [comment]
Hey @mmyyrroonn , feel free to take it over, thanks 💪!

**Comment by mmyyrroonn** [comment]
@SantiagoDevRel Hi, I opened a PR to fix this issue, could you help review it?
