### ISSUE TITLE
Why did stripHexPrefix move into web3-eth-accounts instead of web3-utils?

### ISSUE THREAD

**Issue by richtera** [ethereum/web3.js#6807]
https://github.com/web3/web3.js/blob/d8b64a831defaf52a302002ce6e6051f32edaaaf/CHANGELOG.md?plain=1#L296

For some reason I am not finding stripHexPrefix in the correct monorepo package

<img width="1058" alt="image" src="https://github.com/web3/web3.js/assets/708186/ac1f6986-5fc6-42ac-a32d-313c5c0b7bc7">

**Comment by mconnelly8** [comment]
Thanks @richtera!  Someone from the team will review this and get back with you soon.

**Comment by jdevcs** [comment]
It should be mentioned in migration guide that its in accounts package. Thanks @richtera for pointing it.

**Comment by richtera** [comment]
@jdevcs @avkos @mconnelly8 This is causing major problems making it impossible to upgrade or downgrade web3 within webpack or vite. Basically it means that all node modules using web3 have to use the same version of web3 as the base dapp. I am no longer sure if this is just a documentation issue. There are many APIs which have moved :(. I am trying to release a new version of one of our modules, but I cannot test it without also upgrading the dapp and all other modules.

=> There is a temporary workaround by disabling module resolutions within webpack or vite. Configuring the modules path will make it use the root modules of course. Maybe that's the way to go; increases the bundle sizes until everything is upgraded.
