### ISSUE TITLE
Fix link pointing to the CONTRIBUTING.md in the pull request template

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6809]
The link in the [description](https://github.com/web3/web3.js/blob/4.x/.github/PULL_REQUEST_TEMPLATE.md) of the Pull request template is pointing to a 404 page

- Must be updated to point to this one: https://github.com/web3/web3.js/blob/4.x/.github/ISSUE_TEMPLATE/issue-template.md
- When submitting your PR, don't forget to mention this issue in the PR.

**Comment by omahs** [comment]
Hey, just opened a PR for this

**Comment by SantiagoDevRel** [comment]
That was quick @omahs , thanks!
The devs will approved it and u will be able to merge it
