### ISSUE TITLE
[DOCS] Fix link in README to tree shaking guide

### ISSUE THREAD

**Issue by 0xthorazine** [ethereum/web3.js#6817]
Link in README to web3.js tree shaking guide points to a page that returns a 404

#### Expected behavior

Should go to the right page

#### Actual behavior

404 error

#### Steps to reproduce the behavior

Click the link

**Comment by SantiagoDevRel** [comment]
Thanks for pointing this out @0xthorazine , would you like to fix this issue and submit a PR? pls let me know so I can assign you this issue
this is the correct link https://docs.web3js.org/guides/advanced/tree_shaking

**Comment by SantiagoDevRel** [comment]
Oh I just saw ur PR, thanks @0xthorazine

**Comment by kaksv** [comment]
@SantiagoDevRel , Is the issue already solved? OR It is yet to be assigned?

**Comment by SantiagoDevRel** [comment]
Hey @kaksv , yeah this was already solved, thank you.
