### ISSUE TITLE
Create 📚 Resources page in the docs

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6821]
References: 
- Create a resources page in the docs to showcase 2 main playlists so far:
- web3.js v4 course [link](https://youtu.be/3ZO_t-Kyr1g?si=F9TA_7VVh30sW7U8)
- web3.js series [link](https://www.youtube.com/watch?v=BQ_bDH91S4k&list=PLPn3rQCo3XrNf__8irs4-MjMt4fJqW2I_)
- maybe more useful articles/tutorials/videos that are useful (only good quality content about web3.js v4) - this point is not mandatory.
- the page must be at the end of the docs (after [🗣️ Feedback](https://docs.web3js.org/guides/feedback/) and should be called  `📚 Resources`

`Please comment on the issue if you are interested in taking over the task, so we can assign it to you`

**Comment by MAGICXPLUS** [comment]
Y

**Comment by omahs** [comment]
@SantiagoDevRel Hey, I'm interested in working on this one

**Comment by SantiagoDevRel** [comment]
Sure, thank u! @omahs

**Comment by kaksv** [comment]
Has this been worked on or I can jump in as well?

**Comment by omahs** [comment]
@SantiagoDevRel I just made a first draft here: https://github.com/omahs/web3.js/blob/patch-7/docs/docs/guides/resources/resources.md
Can I have your feedback on this?

**Comment by SantiagoDevRel** [comment]
Hey @kaksv , yes, this has been assign to Omahs, thank u.

**Comment by SantiagoDevRel** [comment]
Hey @omahs , looks good, those a heads up here:
1. pls dont include outdateed info, for ex the one of dapp university is outdated since it's importing web3.js v1 and not v4 ( you can noticed this by the way you import `const {Web3}`, v4 is with curly brackets)
2. pls check the structure of the other folders, so you might need to create a `category.yml` file and add the title (and include the books emoji as well)
anyway, feel free to submit the PR and we can also review it from there, thanks!
