### ISSUE TITLE
Plugin Guide 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6840]
Plugin Guide for advance plugin developers

Add a plugin guide that shows what web3.js components a plugin developer can use:
web3 context, request manager, wallet, other packages, config params, ...
and how they should use existing pattern for defining plugin errors and define types .

**Comment by Redoudou** [comment]
@SantiagoDevRel could we re-use somewhat the presentation you did with the Chainlink plugin as a documentation ?

**Comment by SantiagoDevRel** [comment]
Yes @Redoudou , Oleksii's video should super helpful here as well, let me add an issue to make it.
#6866

**Comment by SantiagoDevRel** [comment]
#6941 merged
