### ISSUE TITLE
Implement Chainstack Plugin

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6847]
The Web3.js Chainstack plugin will allow users to use Chainstack out of the box with web3.js library as provider, It will also add capability for users to query Chainstack platform components. 

- Getting Org Data
- Getting Nodes Data ( using node id and for all nodes ) 
- Getting Networks Data ( using NW id and for all NWs )
- Getting Project Data ( using id and for all projs )

**Comment by Muhammad-Altabba** [comment]
Repo at: https://github.com/ChainSafe/web3-plugin-chainstack

**Comment by jdevcs** [comment]
When creating the instance of Chainstack plugin, users will be able to give parameters to directly connecting to the required Blockchain network. Additionally there will be an option to connect with password protected networks in Chainstack projects using username and passwords. For querying Chainstack platform API there will be an option of providing API key. 

Once a Chainstack plugin instance will be created and registered with Web3.js as mentioned in the last step, users will be able to use it as following

```
import{ChainstackPlugin, ChainstackAuth}
from '@chainsafe/web3-plugin-chainstack';
import{Web3} from 'web3';


const web3 = new Web3();

const userAuth: ChainstackAuth = {
  username: "exampleUser",
  password: "examplePassword",
  apiKey: "key" 
// optional apikey for using Chainstack Platform API functions
};

const chainstackPlugin = new ChainstackPlugin(userAuth);
web3.registerPlugin(chainstackPlugin);

web3.eth.getBlock(0).then(console.log);


```

**Comment by jdevcs** [comment]
https://github.com/ChainSafe/web3-plugin-chainstack/pull/1
