### ISSUE TITLE
 Intermittent False Return from web3js.eth.getTransactionReceipt() a

### ISSUE THREAD

**Issue by tarunkridafans** [ethereum/web3.js#6854]
I'm using the web3js.eth.getTransactionReceipt() function to track transaction mining status and success/failure.

Sometimes, although transaction receipts are generated, the function returns false, even when the transaction is successfully completed on the blockchain. Moreover, I need to trigger a backend API call upon transaction completion, but I'm encountering intermittent issues where the API isn't reliably hit.

**Comment by SantiagoDevRel** [comment]
Hi @tarunkridafans , which version are you using?
