### ISSUE TITLE
Change order of the interactive code editor

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6860]
References:
- We have implemented this `live code editor` in 3 pages: [Quickstart](https://docs.web3js.org/), [Mastering Providers](https://docs.web3js.org/guides/web3_providers_guide/), and [Mastering wallets and accounts](https://docs.web3js.org/guides/wallet/)
- in those 3 pages the `live code editor` is all the way to the bottom, **we want to move it to the top of each page instead**

**Pls comment this issue if you want to take it over, so we can assign it to you.**

**Comment by sarthak1dev** [comment]
Would love to take this up!!

**Comment by rhlshah** [comment]
I have fixed this and have also raised a PR #6865  . Kindly please review
