### ISSUE TITLE
Add videos to the Plugin section in the docs

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#6866]
References:
- add this video https://www.youtube.com/watch?v=fW1PDApXCtM&list=PLPn3rQCo3XrP4LbQcOyyHQR8McV7w3HZT&index=13 into  [For Plugin Developers](https://docs.web3js.org/guides/web3_plugin_guide/plugin_authors)
- add this video https://www.youtube.com/watch?v=iF_O7ggQaQw&t=1s into [For Plugin Users](https://docs.web3js.org/guides/web3_plugin_guide/plugin_users)
 
pls comment this issue so we can assign it to you!

**Comment by sarthak1dev** [comment]
Would love to take this up

**Comment by rhlshah** [comment]
@SantiagoDevRel Could you please provide more details as in where (top / bottom) to add this video into [For Plugin Developers](https://docs.web3js.org/guides/web3_plugin_guide/plugin_authors/) page. Do we need to make a separate section for that?

**Comment by SantiagoDevRel** [comment]
Hey @rhlshah feel free to do in a way that as a developer you'd like to see it😂
I think it can catch more attention at the top with a section called 'plugin usage example' and 'create your plugin in 10minutes' or something like that. Thanks!

**Comment by rhlshah** [comment]
Hi, I have added the videos and have also raised a PR #6870. Please have a look !

**Comment by sarthak1dev** [comment]
Added an in docs video viewer, so that the users don't have to leave the site and watch it outside

**Comment by SantiagoDevRel** [comment]
Thanks @sarthak1dev , our devs will review the PR in the upcoming days
