### ISSUE TITLE
Calling estimateGas on USDT contract with polygon trigger "Error happened while trying to execute a function inside a smart contract"

### ISSUE THREAD

**Issue by 0xMrZK** [ethereum/web3.js#6868]
Hi,

I've been struggling with this issue since 48 hours, I'm not sure if it's a problem with me or the library. Any kind of help or direction would be extremely appreciated.

#### Actual behavior

> Error happened while trying to execute a function inside a smart contract

#### Steps to reproduce the behavior

`
let network_url = 'https://polygon-bor-rpc.publicnode.com';

let token_address = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F";

const from = '0x..' //10 USDT and MATIC on this account
const to = '0x..';

let contract = new web3.eth.Contract(abi, token_address);

let amount_to_transfer = "5440000"; //This is to transfer the 5.44 USDT from the wallet.

let estimated_gas_for_contract_call = await contract.methods.transfer(to,  web3.utils.toHex(amount_to_transfer)).estimateGas();

`

ABI Contracts come from here : https://polygonscan.com/address/0x7ffb3d637014488b63fb9858e279385685afc1e2#code
It is not the one fom the contract address as it is only the proxy one : https://polygonscan.com/address/0xc2132D05D31c914a87C6611C10748AEb04B58e8F#code

#### Logs

error: ContractExecutionError: Error happened while trying to execute a function inside a smart contract
    at Web3RequestManager._isReverted (node_modules/web3-core/lib/commonjs/web3_request_manager.js:311:19)

#### Environment
linux / ubuntu
node v20.10.0
npm 10.2.3
web3.js v4.5

**Comment by SantiagoDevRel** [comment]
Hi @MrKalten thanks for pointing this out, please try the following:
When estimating gas, the web3js library will assume there is a wallet in the background already set to send the transaction, so u must initialize the wallet and have funds there (regardless that estimating gas doesn't require any funds)
`const wallet = web3.eth.wallet.add("0x...");`

Pls try that and lmk if that works!

**Comment by 0xMrZK** [comment]
Thanks for responding, the wallet does exists with funds. But it still throwing this weird error.

When there is no fund it tells you that there is not enough gas on the wallet.

By the way I got it to work on the BSC with the USDT. The difference is that with BSC the USDT is not a bridge. So maybe this is where it gets tricky.

One other possibility would be that estimateGas need some parameter to work (even that the doc says its optional). On BSC I had to add this to make it work, but no success on polygon.

```
 let estimated_gas_for_contract_call = await contract.methods.transfer(to, amount_to_transfer).estimateGas(
        {
            from: from,       
        }
    );
```

**Comment by SantiagoDevRel** [comment]
Hmmm interesting, let me ping the devs to investigate a bit more here, thanks for submitting the issue @MrKalten

**Comment by avkos** [comment]
@MrKalten Could you please check that you approve your wallet address in USDT contract before call estimateGas for Transfer method. Or you have enough usdt funds on the wallet

**Comment by avkos** [comment]
So the main idea is that you should have everything you need to transfer the token and then call `estimateGas`. Because `estimateGas` method emulates calling the function and if you do not have enough balance or another reason it will fail.

**Comment by 0xMrZK** [comment]
Thank you for helping me. It's working now. If anyone passes after me they were a few things wrong on my end : 

- web3.utils.toHex() was not needed in the transfer method
- always make sure that the amount is using the good number of decimals 
- always make sure you have enough gas (gas for executing the contract can be a lot more than just one transaction)

So nothing wrong for with the web3 lib, unless maybe some error that can (maybe ?) be improved for better understanding.

Thank you for the good job !

I close the issue.
