### ISSUE TITLE
[Error: crypto.getRandomValues must be defined] with react native

### ISSUE THREAD

**Issue by duync2006** [ethereum/web3.js#6879]
I try to run the method with smart contract in web3js with the function below:

```
const touristRewardPointOnPostID = async (user_address, post_id) => {
  try {
    return await contract_4R.methods.touristRewardOnPostID(user_address, post_id).call();
  } catch (error) {
    console.error("Error in touristRewardPointOnPostID:", error);
    throw error; // Re-throw the error if needed
  }
}
```

In the react native app, i try to fetch data from web3js and it throw error: 

```
const fetchRewards = async () => {
        console.log("calls");
        const reviews = await touristRewardPointOnPostID('0x1a620c351c07763f430897AeaA2883E37cA0aaCD', '0x26eecb00ddef76d58362552f4fd2e782ae49d1e064ccd5b06bd70dcd8039ec35');
        console.log(reviews);    
    };

```

 ERROR  Error in touristRewardPointOnPostID: [Error: crypto.getRandomValues must be defined]

**Comment by duync2006** [comment]
The web3 version i used is 4.1.2

I found a way to fix this problem by using an older version (version 1.8.0)

**Comment by SantiagoDevRel** [comment]
Hi @duync2006 , can u pls share the ABI, network and contract address for me to reproduce this?
Also, if you try to run this in a normal js script, does it work? or is only on react?

**Comment by duync2006** [comment]
Hi @SantiagoDevRel,

This is the ABI: 
```
{
		"inputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			},
			{
				"internalType": "bytes32",
				"name": "",
				"type": "bytes32"
			}
		],
		"name": "touristRewardOnPostID",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
```
The contract address is: _0xd3e7B4BF6FB03bdECbe5Db0b348285A22bF33Bf6_

The network i used is **Sepolia Testnet**

Also, when i run this in a normal js script, run with nodejs, it still work okey. But it does not work when i try with react. But the version 1.8.0 can run.

**Comment by SantiagoDevRel** [comment]
Hey @duync2006 I just tried and my code worked well within a react app and i got the result `33750000000000000000n`
something I did change was to put the `[]` in the ABI
check this repo https://github.com/SantiagoDevRel/help-devs-web3js/blob/main/react/test/src/App.js

```js
import { Web3 } from "web3";
import ABI from "./ABI.json";

function App() {
  const contract_address = "0xd3e7B4BF6FB03bdECbe5Db0b348285A22bF33Bf6";

  async function main() {
    const web3 = new Web3(window.ethereum);

    const contract = new web3.eth.Contract(ABI, contract_address);

    const result = await contract.methods.touristRewardOnPostID("0x1a620c351c07763f430897AeaA2883E37cA0aaCD", "0x26eecb00ddef76d58362552f4fd2e782ae49d1e064ccd5b06bd70dcd8039ec35").call();
    console.log("result", result);
  }

  return (
    <div className="App">
      <button onClick={main}>Connect</button>
    </div>
  );
}

export default App;
```

Make sure: 
1. Use web3 4.6.0 
2. Your metamask is on the sepolia network 
3. Your abi starts with `[]`

**Comment by duync2006** [comment]
Hello @SantiagoDevRel, it works now. 

I sure that i follow these rules that you mentioned above, i used web 4.6.0 ask you told, and it work. 

Then i tried to used web3 4.1.2 (the version that have this bug). It's still work :-) 

Perhaps there are something wrong in my coding, thank you for your support !

**Comment by SantiagoDevRel** [comment]
@duync2006 im sure it was the ABI without the [] !
You are welcome💪
