### ISSUE TITLE
Web3 v1.10.1 : encodeFunctionSignature broken

### ISSUE THREAD

**Issue by JiggyJinjo** [ethereum/web3.js#6890]
Hello,

I updated the web3 lib from 1.10.0 to 1.10.1 (issue up to 1.10.4) and I now have issues when dealing with signatures, ie. web3.eth.abi.encodeFunctionSignature

Here's the test mock I'm giving it :
```typescript
web3.eth.abi.encodeFunctionSignature( {
    constant: true,
    inputs: [{ name: '_interfaceID', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  })
```
It returns the following error and stack :
```typescript
 Uint8Array expected
        at Object.bytes (apps/node_modules/@noble/hashes/_assert.js:22:15)
        at bytes (apps/node_modules/ethereum-cryptography/utils.js:48:27)
        at Object.keccak256 [as sha3] (apps/node_modules/web3-utils/lib/utils.js:444:50)
        at ABICoder.sha3 [as encodeFunctionSignature] (apps/node_modules/web3-eth-abi/lib/index.js:52:18)
        at encodeFunctionSignature (myFrontEndCallingEncodeFunctionSignature/index.tsx:104:36)
```
I compared the changes between version 1.10.0 and 1.10.1 and this is the change that breaks it :
```typescript
// node_modules/web3-utils/lib/utils.js line 444
// v1.10.1
var returnValue = ethereumjsUtil.bufferToHex(keccak256(value));
```
```typescript
// v1.10.0
var returnValue = ethereumjsUtil.bufferToHex(ethereumjsUtil.keccak256(value));
```
What I'm seeing is that on v1.10.0, the keccak256 function signature accepts a Buffer object and in v1.10.4, it accepts a Uint8Array which could indicate why the function is now broken.

By manually editing the same line and converting to Uint8Array before passing the value to keccak256, the function works properly without throwing any errors : 

```typescript
var returnValue = ethereumjsUtil.bufferToHex(keccak256(new Uint8Array(value)));
```

Node version: 18.19.1
yarn: 1.22.21

**Comment by SantiagoDevRel** [comment]
Hi @JiggyJinjo , please upgrade to `web3 4.6.0` and let me know if you still face this issue.
`web3 v1` will be deprecated in ~3 weeks
