### ISSUE TITLE
Contribution guide readme file not available for 4.x branch

### ISSUE THREAD

**Issue by pradipkhomane** [ethereum/web3.js#6896]
I was checking the contribution guide for the web3.js repository but the latest 4.x version branch doesn't have the readme file present in the below URL link.

[Link](https://github.com/web3/web3.js/blob/4.x/CONTRIBUTIONS.md)

<img width="1262" alt="Screenshot 2024-03-13 203254" src="https://github.com/web3/web3.js/assets/20298999/72e82931-37fd-40c2-a2b3-478f9102d142">

**Comment by SantiagoDevRel** [comment]
Hi @pradipkhomane pls check https://github.com/web3/web3.js/blob/4.x/.github/CONTRIBUTING.md

Its just inside the .github folder now, if there is a broken link somewhere, feel free to update it💪

Is this what u mean, right? Thank u!

**Comment by pradipkhomane** [comment]
Hi, @SantiagoDevRel Yes there was a broken link that I have fixed in PR #6901 .  I was trying to find it to start contributing and faced this issue.

**Comment by SantiagoDevRel** [comment]
Amazing, now you are set to start contributing! ;)💪

**Comment by pradipkhomane** [comment]
Yes!
