### ISSUE TITLE
Keystore into file

### ISSUE THREAD

**Issue by Jouzep** [ethereum/web3.js#6912]
Is there a function that create a keystore and then save it into a file and vice versa ??
In GETH there is an implementation like that

**Comment by SantiagoDevRel** [comment]
Hey @Jouzep , sorry for our late reply, I was on vacation last week, not sure if you want to encrypt and decrypt a pair of keys?
Pls take a look at [this](https://docs.web3js.org/libdocs/Accounts#encrypt) and lmk if it helps, and pls provide a reference for the GETH implementation, thanks!💪

**Comment by mconnelly8** [comment]
Hey @Jouzep , since we didn't get a response, we will close this issue.  If you need to follow up, please reopen it.
