### ISSUE TITLE
Create plugin: Wallet RPC Methods

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#6946]
should support general wallet rpc methods 
https://eips.ethereum.org/EIPS/eip-3085
https://ethereum-magicians.org/t/eip-3326-wallet-switchethereumchain/5471
methods supproted by metamask that isnt specifically metamask
https://docs.metamask.io/wallet/reference/wallet_switchethereumchain/

**Comment by krzysu** [comment]
## Table view

| **Wallet RPC API**           | **EIP**  | **web3js plugin** | **MetaMask Supported** | **Implemented by viem**                                                                        |
| ---------------------------- | -------- | ----------------- | ---------------------- | ---------------------------------------------------------------------------------------------- |
| `wallet_addEthereumChain`    | EIP-3085 | ✓                 | ✓                      | ✓                                                                                              |
| `wallet_updateEthereumChain` | EIP-2015 |                   |                        |                                                                                                |
| `wallet_switchEthereumChain` | EIP-3326 | ✓                 | ✓                      | ✓                                                                                              |
| `wallet_getOwnedAssets`      | EIP-2256 |                   |                        |                                                                                                |
| `wallet_watchAsset`          | EIP-747  | ✓                 | ✓                      | ✓                                                                                              |
| `wallet_requestPermissions`  | EIP-2255 | ✓                 | ✓                      | ✓                                                                                              |
| `wallet_getPermissions`      | EIP-2255 | ✓                 | ✓                      | ✓                                                                                              |
| `wallet_revokePermissions`   |          | ✓                 | ✓                      | [mentioned](https://github.com/search?q=repo%3Awevm%2Fviem+wallet_revokePermissions&type=code) |
| `wallet_registerOnboarding`  |          |                   | ✓                      |                                                                                                |
| `wallet_scanQRCode`          |          |                   | ✓                      |                                                                                                |


See also the result of my tests with different browser extension wallets: https://github.com/web3/web3-wallet-rpc-utils/blob/main/WALLET_SUPPORT.md

## List view

Wallet RPC related EIPs:

- wallet_addEthereumChain (eip-3085)
- wallet_updateEthereumChain (eip-2015)
- wallet_switchEthereumChain (eip-3326)
- wallet_getOwnedAssets (eip-2256)
- wallet_watchAsset (eip-747)
- wallet_requestPermissions (eip-2255)
- wallet_getPermissions (eip-2255)

Metamask supported:
- wallet_addEthereumChain
- wallet_switchEthereumChain
- wallet_watchAsset
- wallet_getPermissions
- wallet_requestPermissions
- wallet_revokePermissions
- wallet_registerOnboarding
- wallet_scanQRCode

Implemented by viem:
- wallet_addEthereumChain
- wallet_switchEthereumChain
- wallet_getPermissions
- wallet_requestPermissions
- wallet_watchAsset
- Wallet Call API as experimental [eip-5792](https://eips.ethereum.org/EIPS/eip-5792)

Other finds:
- Wallet Call API [eip-5792](https://eips.ethereum.org/EIPS/eip-5792)
  - wallet_sendCalls
  - wallet_getCallsStatus
  - wallet_showCallsStatus
  - wallet_getCapabilities
- wallet_signIntendedValidatorData (eip-7749)
- wallet_sendTransaction === eth_sendTransaction -> [in viem](https://github.com/wevm/viem/blob/9d905707553380d348031387e140d1f74805bb71/src/actions/wallet/sendTransaction.ts#L235)
- wallet_requestAccounts === eth_requestAccounts -> [in ethers](https://github.com/ethers-io/ethers.js/blob/9e7e7f3e2f2d51019aaa782e6290e079c38332fb/src.ts/providers/provider-jsonrpc.ts#L1011)

**Comment by krzysu** [comment]
You can track the ongoing work here: https://github.com/web3/web3-wallet-rpc-utils/pulls

**Comment by krzysu** [comment]
the wallet plugin was released, see more:
- on npm https://www.npmjs.com/package/web3-plugin-wallet-rpc 
- or in the docs https://web3.github.io/web3-plugin-wallet-rpc/
