### ISSUE TITLE
export eip6963 types

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#6952]
eip6963 types are not being exported to the package, this makes using eip6963 hard for users,
https://github.com/web3/web3.js/blob/4.x/packages/web3/src/web3_eip6963.ts types should be exported and available for ease

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by danforbes** [comment]
These types are exported under the `providers` namespace
