### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by Mae6e** [ethereum/web3.js#6961]
hi, how can resolve this innerError?

innerError: {
    code: -32000,
    message: 'insufficient funds for gas * price + value: balance 285419491325000000, queued cost 2750000, tx bumped 285419491324450000, overshot 2200000'
  }

code:
    const nonce = await web3.eth.getTransactionCount(fromAddr, 'latest');
    const gasPrice = await web3.eth.getGasPrice();
    const fee = gasPrice.toString() * web3GasLimit;

   const transaction = {
      'to': toAddr,
      'value': value,
      'gas': web3GasLimit,
      'gasPrice': gasPrice,
      'nonce': nonce,
    };
    const signedTx = await web3.eth.accounts.signTransaction(transaction, key);
    const response = await web3.eth.sendSignedTransaction(signedTx.rawTransaction);

values:
balance:  285419491325000000
fee:  105000000000000
value:  285314491325000000
web3GasLimit:  21000
gasPrice:  5000000000

**Comment by SantiagoDevRel** [comment]
Hi @Mae6e , are you trying to sign the transaction and then send the raw tx to the network?
Anyway, maybe try this code and let me know if it works:
```js
const rawTransaction = {
  from: "0x...",
  to: "0x...",
  value: 0,
  maxFeePerGas: (await web3.eth.getBlock()).baseFeePerGas * 2n, 
  maxPriorityFeePerGas: 100000, //high
  gasLimit: 2000000,
  nonce: await web3.eth.getTransactionCount("0x..."), 
  data: "0x0",
};
```

btw, are u using web3.js 4.x?

**Comment by Mae6e** [comment]
@SantiagoDevRel 
Hi. I use 4.x version.
web3.balance return 285419491325000000.
but the actual value is (the error message say that):285419491324450000

When i have a balance with more than decimalPoint number i have this error.
I resolved with tofixed 8 point.

**Comment by SantiagoDevRel** [comment]
Thanks @Mae6e , for visibility i'm tagging @jdevcs

**Comment by jdevcs** [comment]
>Hi. I use 4.x version.
web3.balance return 285419491325000000.
but the actual value is (the error message say that):285419491324450000
When i have a balance with more than decimalPoint number i have this error.
I resolved with tofixed 8 point.

@Mae6e in "web3.balance return 285419491325000000." do you mean using web3.eth.getBalance? as in 4.x by default bigint format is returned.
