### ISSUE TITLE
Middleware documentation / Guide

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6963]
- [x] web3 middleware usecase test / feedback: Check with real usecase if any breaking changes are required before merging and release
- [x] publish middleware ( include in next release )

Related feature work can be found at: 
#7134
#7002
#7003

**Comment by jdevcs** [comment]
Create plugin developers Guide for Middleware implementation:
**Types of Middleware**: 
**1 - Request Middleware**: can be use to modify request before sent to RPC node by web3.js and/or modify response before returning back to web3.js, steps: 
- Middleware Interface and methods specs: https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/packages/web3-core/src/types.ts#L39
( examples are linked in following steps)
A. Implement [middleware](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/request_manager_middleware.ts#L27).
B. [Create its instance based on your logic in plugin](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/custom_rpc_methods.ts#L36)
C. [set middleware in link method](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/custom_rpc_methods.ts#L43)
Once its set , any JSON RPC request from all web3 packages will go through this middleware

**2- Transaction Middleware**: ( works for Eth and Contracts package ) 
steps: 
- Middleware Interface and methods specs: https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/packages/web3-eth/src/types.ts#L100
A. [Example implementation](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware.ts#L21)
B. [Create Instance in plugin example](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L30)
C. [Set Transaction middleware example](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L39) 
Once its set , web3 will call Transaction middleware before signing transaction. 

Some code snippets in tests:
Requests middleware:
https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/test/unit/request_manager_middleware.test.ts#L24
Eth Transaction middleware: https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/test/unit/transaction_middleware.test.ts#L26
Contract Transaction middleware:
https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/test/unit/contract_transaction_middleware.test.ts#L30

**Comment by danforbes** [comment]
@jdevcs why is it necessary to [add a new property to the plugin class](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L30) AND [register the plugin in the `link` method](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L39)?

**Comment by jdevcs** [comment]
> @jdevcs why is it necessary to [add a new property to the plugin class](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L30) AND [register the plugin in the `link` method](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L39)?

@danforbes [add a new property to the plugin class](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/tools/web3-plugin-example/src/transaction_middleware_plugin.ts#L30) is not necessary, middleware can be injected in plugin, or plugin can have access to middleware via other ways, 

but registering (Transaction or Request ) middleware in link method is necessary because it will set middleware via web3-context to Web3-Eth & Web3-Contract or Web3-Request-Manager, so when normal request is sent via other web3 packages it can see if middleware is there or not for usage.
