### ISSUE TITLE
Test repository setup and testing time

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6966]
Original Action Item for H1 2024 was to reduce time by 50%.

Previous work can be found in #6684, #6685, #6686

**Comment by avkos** [comment]
### Release 4.2.1 (25 Oct 2023)
**32m 26s**
https://github.com/web3/web3.js/actions/runs/6642072792
<img width="1065" alt="image" src="https://github.com/web3/web3.js/assets/9366141/92359e15-db9d-4a1b-90fd-9f2fcbcfbc3f">



Release 4.8.0 (17 Apr 2024)
**10m 56s**
https://github.com/web3/web3.js/actions/runs/8731958937
<img width="1062" alt="image" src="https://github.com/web3/web3.js/assets/9366141/6b277d10-33e5-45f3-80f0-f734958a3fd2">

**It was 1946 seconds and now 656 seconds. The processing time was decreased by 66.29%**

**Comment by avkos** [comment]
If compare only unit tests and eslint:

### [Release 4.2.1 (25 Oct 2023)](https://github.com/web3/web3.js/actions/runs/6642072792/usage)
eslint time: 5m 13s
unit tests: 4m 51s

<img width="854" alt="image" src="https://github.com/web3/web3.js/assets/9366141/f9e2b260-a53f-4859-b4ee-03e8ecb131d3">


### [Tests & ESLint Improvements](https://github.com/web3/web3.js/actions/runs/8925848233/usage?pr=7027)
eslint time: 44s  (**85% decreased**)
unit tests: 3m 40s (**30% decreased**)

<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm12QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32f0febd5b49caab4fac1aaa67cb1be487d9c123/image.png" alt="image.png" />

**Comment by luu-alex** [comment]
👍
