### ISSUE TITLE
Unable to see events

### ISSUE THREAD

**Issue by fansari6** [ethereum/web3.js#6970]
I am testing this using ganachi-cli and Remix (to fire the events). I can see the transaction hash in the ganachi-cli, it matches the ones in Remix, so I know events are coming through. I know my contract address and ABI are correct. I did a console.log(contract.events and see all the event names & parameters but my event subscription code is not being executed due to some reason that I have failed to understand. console.log('Inside contract.events callback'); is not executing.

If someone knows what I am doing wrong, please help!

Thank you so much!

Here's my code:
const config = require('./config');
const Express = require('express');
const { Web3 } = require('web3');
const app = Express();

const ABI = require('./abis/SupplyChain.json');

const web3 = new Web3(new Web3.providers.WebsocketProvider(config.ethereumRpc));
const contract = new web3.eth.Contract(ABI, config.address);

// console.log('contract.events: ', contract.events);

// Subscribe to events
const eventNames = [
  'PurchaseRequestCreated',
  'PurchaseRequestApproved',
  'PurchaseRequestDeclined',
  'PurchaseOrderCreated',
  'PurchaseOrderAccepted',
  'PurchaseOrderDeclined',
  'PurchaseOrderShipped',
  'PurchaseOrderDelivered',
  'PurchaseOrderAcceptedWH',
  'PurchaseOrderRejectedWH',
];

// Subscribe to events
eventNames.forEach((eventName) => {
  contract.events[eventName]({ fromBlock: 0 }, (error, event) => {
    console.log('Inside contract.events.allEvents callback');
    if (error) {
      console.error('Error:', error);
    } else {
      event = JSON.parse(JSON.stringify(event));
      // const values = event.returnValues;
      // const eventStatus = event.event;
      // console.log('VALUES:', values);
      // console.log('EVENT STATUS: ', eventStatus);
      // console.log('->', values.customer);

      console.log('Event:', event.event);
      // console.log('Arguments:', event.returnValues);
      // console.log('Title:', event.returnValues.title);
      // console.log('Description:', event.returnValues.description);
      console.log('GOT HERE');
    }
  });
});

**Comment by fansari6** [comment]
FYI...Using "web3": "^4.7.0"

**Comment by SantiagoDevRel** [comment]
Hey @fansari6 , if you try to register only to 1 event, it still doesn't work? (I'm just trying to debug the error)

**Comment by fansari6** [comment]
> Hey @fansari6 , if you try to register only to 1 event, it still doesn't work? (I'm just trying to debug the error)

Thank you! I have tried just one event but it still does not work.

**Comment by mconnelly8** [comment]
Hey @fansari6 , are you able to reproduce this on any other platform outside of Ganache?

**Comment by avkos** [comment]
Looks like you use the old way of events subscription. Here is the example how to use events with version 4
<img width="859" alt="image" src="https://github.com/web3/web3.js/assets/9366141/ed0402d6-2bb2-4601-83cf-ebfc780b9244">

You can find an example on the main page https://web3js.org/ in "Listen for on-chain events." section
