### ISSUE TITLE
web3js-web3modal client implemented for next.js

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#6991]
This task is for creating web3modal to support next.js builds with web3.js
task for #6990

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by luu-alex** [comment]
completed in https://github.com/Muhammad-Altabba/web3modal/tree/feat/support-web3js

**Comment by Muhammad-Altabba** [comment]
For reference: https://github.com/luu-alex/web3js-web3modal
