### ISSUE TITLE
Insure web3modal/web3 functionality is similar to the other web3modals

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6997]
Double check (and fix) the web3modal/web3 draft code to insure its functioning properly.

Changes to be maid in an MR to https://github.com/ChainSafe/web3modal/tree/feat/support-web3js

**Comment by luu-alex** [comment]
In default laboratory,
Signing a transaction will fail when it should sign properly,

Contract write is failing to estimate gas 
it should estimate when interacting with the smart contract button
edit: fixed

Wallets such as phantom is failing when rejecting to sign/send a transaction
