### ISSUE TITLE
Create a sample repository of a web3 based hardhat stack

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#7013]
creating a sample repository of how a good web3 based hardhat stack should look, it can be inspired in the stack that gets created when you initialize a project using ethers or viem.

bare minimum web3+hardhat sample repo so it can be used later to integrate in hardhat cli.

**Comment by jdevcs** [comment]
1. Create sample repo
2. Contract deployment function using web3 in HRE and HRE artifacts 
3. Contract calls and send function with web3 in HRE
4. Deployment on live testnet
5. Contract deployment function using web3 in HRE and HRE artifacts  ( with libraries ) and all above steps test

**Comment by jdevcs** [comment]
https://github.com/web3/hardhat-web3

**Comment by jdevcs** [comment]
Create HH+web3.js examples for JS and TS:

1. Create sample repo
2. Contract deployment function using web3 in HRE and HRE artifacts 
3. Contract calls with web3 in HRE
4.  Contract calls send transaction function with web3 in HRE
5. Contract events

**Comment by jdevcs** [comment]
TS, yarn, Web3.js, Hardhat, and Lock Contract: https://github.com/web3/hardhat-web3/tree/hardhat-web3-ts
JS, NPM, Web3.js, Hardhat, and Token Contract: https://github.com/web3/hardhat-web3
