### ISSUE TITLE
Create a package 'create-hardhat-web3', so that people can initialize project with 'npm init hardhat-web3'

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#7014]
creating a package `create-hardhat-web3`, so that people can initialize project with `npm init hardhat-web3`. this package should create [this mentioned](https://github.com/web3/web3.js/issues/7013) bare minimum sample repo with web3.js+hardhat on command: `npm init hardhat-web3`. `npm init <x> === npx create-<x>`

**Comment by jdevcs** [comment]
https://github.com/web3/hardhat-web3/pull/1

**Comment by jdevcs** [comment]
https://www.npmjs.com/package/create-hardhat-web3
