### ISSUE TITLE
web3.utils.fromWei/web3.utils.toWei bug?

### ISSUE THREAD

**Issue by HelloFeture** [ethereum/web3.js#7018]
#### Expected behavior
the result  should be same as input 0.0033086855466118933
#### Actual behavior
this result is 0.033086855466118933
#### Steps to reproduce the behavior

1. [write js script]
2. [run js script]
3. [check the console log output]

#### Logs
`
const web3 = require("web3");
const inst = new web3.Web3();
console.log(inst.utils.fromWei(inst.utils.toWei("0.0033086855466118933", "ether"), "ether"));
`
the log output is 0.033086855466118933
expected output 0.0033086855466118933

#### Environment
npm 10.2.4
node 20.11.1
os Win 11

**Comment by HelloFeture** [comment]
web3.js version 4.8.0

**Comment by SantiagoDevRel** [comment]
Hi @HelloFeture!

I just checked and you are right, there is a difference between web3.js and using https://eth-converter.com/ in the first function `toWei()`, i'll ping the team to investigate this asap!

```ts
// import web3 module
import { Web3 } from "web3";

const web3 = new Web3("https://rpc2.sepolia.org");

const firstConversion = web3.utils.toWei("0.0033086855466118933", "ether"); //ether to wei
console.log(firstConversion);
//33086855466118933 => web3.js
//3308685546611893   => eth-converter
```

**Comment by luu-alex** [comment]
Hey there @HelloFeture, `toWei("0.0033086855466118933", "ether")` will return 3308685546611893, we trim any fractional value because we don't want to be having a decimal of a wei. if theres any other issues please let comment otherwise i will be closing this issue. thanks!
