### ISSUE TITLE
"Wagmi Web3js Adapter" example doesn't work

### ISSUE THREAD

**Issue by sequencerr** [ethereum/web3.js#7020]
the docs page with example: https://docs.web3js.org/guides/wagmi_usage/wagmi/#reference-implementation

code 
```js
const client = getClient(wagmiConfig, { chainId: mainnet.id });
const accounts = await new Web3(client.transport).eth.getAccounts();
```

error: 
```
RpcRequestError: RPC Request failed.

URL: https://cloudflare-eth.com/
Request body: {"method":"eth_accounts","params":[]}

Details: Method not supported
Version: viem@2.9.29
```

**Comment by SantiagoDevRel** [comment]
Hi @sequencerr thanks for submitting this! right, the method that its sending should be `eth_requestAccounts` no `eth_accounts`, the devs will look into this, thank u!

**Comment by avkos** [comment]
Looks like the network `https://cloudflare-eth.com/` does not support `eth_accounts` method. Check their documentation for available RPC methods. @sequencerr

**Comment by avkos** [comment]
if you need to send RPC that doesn't exists inside web3js. You can send it using this code

```ts
web3.requestManager.send({
  method: 'eth_requestAccounts', // method name
  params: [....], // method params
});

```

**Comment by sequencerr** [comment]
https://developers.cloudflare.com/web3/ethereum-gateway/reference/supported-api-methods

Can I leave all in wagmi client.transport but change to some other Ethereum JSON-RPC API node Gateway url?

**Comment by sequencerr** [comment]
import { mainnet } from '@wagmi/core/chains';
(mainnet.rpcUrls.default.http as unknown as string) = 'https://some-eth-rpc.com'; // maybe better to defineChain() by hand

**Comment by avkos** [comment]
```ts
export function clientToWeb3js(client?: Client<Transport, Chain>) {
    if (!client) {
        return new Web3()
    }

    const {transport} = client

    if (transport.type === 'fallback') {
        return new Web3(transport.transports[0].value.url) // <== HERE
    }
    return new Web3(transport) // <== HERE
}
```
actually, yes you can set any URL you want
But, I think using Wagmi it is better to set the correct chain in Wagmi config
https://wagmi.sh/core/api/chains

**Comment by sequencerr** [comment]
(mainnet.rpcUrls.default.http as unknown as string[]) = ['https://rpc.ankr.com/eth'];

**Comment by sequencerr** [comment]
```ts
import { mainnet } from '@wagmi/core/chains';
(mainnet.rpcUrls.default.http as unknown as string[]) = ['https://some-eth-rpc.com']; // or maybe better with defineChain()
```

Thank you!
