### ISSUE TITLE
Add metamask signing and sending transaction examples to the docs

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#7038]
- Rename this section https://docs.web3js.org/guides/getting_started/metamask to "Interacting with metamask" or similar
- Add metamask signing and sending transaction examples to the docs
- Add interactive code example

**Comment by jdevcs** [comment]
add example of using: https://docs.web3js.org/guides/web3_providers_guide/eip6963

**Comment by Ashish-Kumar-007** [comment]
Hey @avkos can I work on it?

Please let me know if there are any specific guidelines I should follow.

**Comment by EmmanuelOluwafemi** [comment]
@danforbes @avkos @SantiagoDevRel Has this been done? If not, can I work on it?

**Comment by danforbes** [comment]
@EmmanuelOluwafemi - this Issue has not been prioritized yet. We'll reach out to you if we decide to seek help from external contributors on this issue. Thank you for checking in 🙏🏻
