### ISSUE TITLE
`web3.utils.toWei(amount, ether)` fix required when decimals in input are overflown.

### ISSUE THREAD

**Issue by hammersharkfish** [ethereum/web3.js#7044]
MRE :

```
x = "1.123456789123456789123"
const amountInWei = web3.utils.toWei(x, 'ether')

console.log(amountInWei, typeof(amountInWei))

``` 

Output: `1123456789123456789123 string` . 
This output is equivalent to `1123.456789123456789123 ether` while we provided `1.123456789123456789123` as input .

**Comment by hammersharkfish** [comment]
`converter.ts`

```
	// if value is decimal e.g. 24.56 extract `integer` and `fraction` part
	// to avoid `fraction` to be null use `concat` with empty string
	const [integer, fraction] = String(
		typeof number === 'string' && !isHexStrict(number) ? number : toNumber(number),
	)
		.split('.')
		.concat('');

	// join the value removing `.` from
	// 24.56 -> 2456
	const value = BigInt(`${integer}${fraction}`);

	// multiply value with denomination
	// 2456 * 1000000 -> 2456000000
	const updatedValue = value * denomination;
```


```const value = BigInt(`${integer}${fraction}`);```
This part is concatenating the `integer` and `fraction` together resulting in digits after the 18th decimal place from `fraction` side also joining the `integer` side  . The user can provide >18 decimal places string input either mistakenly or by design thinking that the method will approximate it  for him .

**Comment by mconnelly8** [comment]
Thanks @hammersharkfish.  We are currently working on this.
