### ISSUE TITLE
Avoid site suggest gas fee - stick with Market

### ISSUE THREAD

**Issue by umbecanessa** [ethereum/web3.js#7081]
#### Expected behavior

Usually I was adding:

`maxPriorityFeePerGas: null,
        maxFeePerGas: null`

to the send object and with this it was skip the site suggest and going directly on market suggested by metamask, moved now to 4.9.0 and by reading the documentation I see it should be:

`maxPriorityFeePerGas: undefined,
        maxFeePerGas: undefined`

#### Actual behavior

Despite the "fix" metamask still receive a wrong site suggested fee, while I was expecting to not have the site suggested fee at all.

**Comment by mconnelly8** [comment]
Thanks @umbecanessa.  The team will review this soon and get back with you.

**Comment by Cam-B** [comment]
similar issue here. The method mentioned by OP doesn't seem to let Metamask handle gas dynamically. 

In my case the following example seems to set the correct gas fee, but Metamask shows the transaction as failed, even though the transaction was actually successful. So I'd prefer to just let Metamask handle gas completely. 

```
      const gasEstimate = await erc20Contract.methods.approve(contractAddress, maxAllowance).estimateGas({ from: account });
      const gasPrice = await web3.eth.getGasPrice();

      const result = await erc20Contract.methods.approve(contractAddress, maxAllowance).send({
        from: account,
        gas: gasEstimate,
        gasPrice: gasPrice 
```
If we do this and then set "market" within Metamask gas settings, the transaction doesn't show as failed.

**Comment by luu-alex** [comment]
Hey there, this is something we definitely can fix. Will probably be added as a flag to allow metamask to make suggestions. What methods were u using?

**Comment by Cam-B** [comment]
Here's a very basic example:
```
import React from 'react';
import Web3 from 'web3';

const SimpleTransaction = () => {

    const sendTransaction = async () => {
        const web3 = new Web3(window.ethereum);
        await window.ethereum.request({ method: 'eth_requestAccounts' });
        const fromAccount = (await web3.eth.getAccounts())[0];

        const transactionParameters = {
            to: '0x.....',
            from: fromAccount,
            value: web3.utils.toWei('0.05', 'ether'),
            maxPriorityFeePerGas: undefined,
            maxFeePerGas: undefined
        };

        web3.eth.sendTransaction(transactionParameters);
    };

    return (
        <div className="flex flex-col items-center">
            <h1>Send Simple Transaction</h1>
            <button onClick={sendTransaction}>
                Send Transaction
            </button>
        </div>
    );
};

export default SimpleTransaction;
```

This is a snapshot of Metamask showing wrong gas fee instead of using "market" suggested gas:

![metagas](https://github.com/web3/web3.js/assets/31628918/8abefa92-8605-4f08-96f6-3201d7f7e4b3)

**Comment by jdevcs** [comment]
https://github.com/web3/web3.js/blob/4c36f55f2c8e9f8b393d8919b05d7abb46cb2432/packages/web3-eth/src/web3_eth.ts#L1086

https://github.com/web3/web3.js/blob/4c36f55f2c8e9f8b393d8919b05d7abb46cb2432/packages/web3-eth/src/types.ts#L70

can you use above?

**Comment by jdevcs** [comment]
use boolean flag to ignore gas price

**Comment by luu-alex** [comment]
@umbecanessa  @Cam-B Hey there sorry this needs to be clearer in the docs, but you can use the ignoreGasPricing flag
``` 
const transaction = await web3.eth.sendTransaction(
        {
          from: accounts[0],
          to: 'address',
          value: '1',
          data: '0x01',
        },
        { bytes: ETH_DATA_FORMAT.bytes, number: ETH_DATA_FORMAT.number },
        { ignoreGasPricing: true }
```
We'll close this issue now, but let us know if there are any other issues and we'll open it again
