### ISSUE TITLE
encodeFunctionSignature returned signature is not identical with online

### ISSUE THREAD

**Issue by leslie555** [ethereum/web3.js#7087]
### env
web3.js: v4.9.0
node: v18.18.2
pnpm: v8.7.2

The contract address: https://basescan.org/address/0x19ceead7105607cd444f5ad10dd51356436095a1#code

I downloaded the contract abi and generated signatures for each writable function. However, I found that some functions have different signatures from online.

eg.
```
const abiItem = {
  inputs: [
    {
      components: [
        { internalType: 'address', name: 'inputToken', type: 'address' },
        { internalType: 'uint256', name: 'inputAmount', type: 'uint256' },
        { internalType: 'address', name: 'inputReceiver', type: 'address' },
        { internalType: 'address', name: 'outputToken', type: 'address' },
        { internalType: 'uint256', name: 'outputQuote', type: 'uint256' },
        { internalType: 'uint256', name: 'outputMin', type: 'uint256' },
        { internalType: 'address', name: 'outputReceiver', type: 'address' },
      ],
      internalType: 'struct OdosRouterV2.swapTokenInfo',
      name: 'tokenInfo',
      type: 'tuple',
    },
    { internalType: 'bytes', name: 'pathDefinition', type: 'bytes' },
    { internalType: 'address', name: 'executor', type: 'address' },
    { internalType: 'uint32', name: 'referralCode', type: 'uint32' },
  ],
  name: 'swap',
  outputs: [{ internalType: 'uint256', name: 'amountOut', type: 'uint256' }],
  stateMutability: 'payable',
  type: 'function',
};

const signature =new Web3().eth.abi.encodeFunctionSignature(abiItem) //0x3b635ce4
```
The attachment below is the online signature, it is different. So there is a bug in the method. (Maybe the online web page shows the wrong signature, not sure!)
![image](https://github.com/web3/web3.js/assets/40735433/5e0f5153-d002-4b21-ae03-97ccf5d6d65f)

**Comment by SantiagoDevRel** [comment]
Hi @leslie555 you are right its showing a different result. I'm not really aware of the process of etherscan to get the signature, but I do tried this one in remix and it returns the same value as web3.js (0x3b635ce4) , and the signature is the first 4 bytes of the keccak256, so not sure if etherscan is using a different method to get this :/
    
```solidity
function getSwapFunctionSelector() public pure returns (bytes4) {
        return bytes4(keccak256("swap((address,uint256,address,address,uint256,uint256,address),bytes,address,uint32)"));
    }
```

EDIT:
I've tried using `viem` and it returns the same result as `web3.js` and `solidity`: `0x3b635ce4`

**Comment by SantiagoDevRel** [comment]
Hey @leslie555 i'll close this Issue, i'll encourage you to ask Etherscan [Github](https://github.com/etherscan)/[Twitter](https://x.com/etherscan)/Discord to see what they are using to get those functions signature
