### ISSUE TITLE
Invalid type for block transactions

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#7090]
#### Expected behavior

The `eth.getBlock().transactions` should either return empty array in case of empty block, or include `undefined` as part of its return type.

#### Actual behavior

```ts
import { Web3 } from "web3";

const web3 = new Web3('https://sepolia.infura.io/v3/xxxxxx');

const block = await web3.eth.getBlock(6058307, true);

console.log(block.transactions); // this is undefined!
```

#### Steps to reproduce the behavior

1. use `web3.eth.getBlock` on an empty block.

#### Logs

Doesn't matter.

#### Environment

Doesn't matter.

**Comment by SantiagoDevRel** [comment]
Hi @sharifzadesina thanks for submitting this, you are right, the taem will work on it soon! thanks

**Comment by luu-alex** [comment]
Created a [PR](https://github.com/web3/web3.js/pull/7151) for this, thanks

**Comment by luu-alex** [comment]
merged. will be available next release
