### ISSUE TITLE
`Web3ExternalProvider` Should Support Configuration of Selected Transport Mechanism

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#7117]
The [`Web3ExternalProvider` constructor](https://github.com/web3/web3.js/blob/0db2b18418b232d431dd5c2f6a543b66d27451a3/packages/web3-rpc-providers/src/web3_provider.ts#L51-L55) allows developers to select the [transport type](https://github.com/web3/web3.js/blob/0db2b18418b232d431dd5c2f6a543b66d27451a3/packages/web3-rpc-providers/src/types.ts#L18-L21), but this option is limited to either `HTTPS` or `WebSocket` and does not provide developers with the ability to configure the selected transport mechanism (e.g. [HTTP provider configuration](https://docs.web3js.org/guides/web3_providers_guide/#configuring-http-providers), [WebSocket provider configuration](https://docs.web3js.org/guides/web3_providers_guide/#configuring-websocket-providers)). The `Web3ExternalProvider` class should support configuration of the chosen transport mechanism.

**Comment by danforbes** [comment]
@luu-alex - I have updated the title and description of this Issue to add more details. Can you please confirm that my understanding of your feature request is correct?

**Comment by danforbes** [comment]
@jdevcs can you sanity-check [the documentation for this change](https://github.com/web3/web3.js/pull/7119/commits/a75d72b10132c7d30c281106b15c4b831c68fb84)?
