### ISSUE TITLE
getFeeHistory type problem

### ISSUE THREAD

**Issue by Jack-Works** [ethereum/web3.js#7135]
Version: web3-types@1.7.0, web3-eth@4.8.0

<https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_eth_migration_guide#web3ethgetfeehistory>

<img width="683" alt="document" src="https://github.com/web3/web3.js/assets/5390719/1d938db4-a774-4a94-b90b-ec67459c842b">

Actual type:

```ts
{
    readonly oldestBlock: bigint;
    readonly baseFeePerGas: bigint; // !! Not a string[] in the document or 1.x !!
    readonly reward: bigint[][];
    readonly gasUsedRatio: bigint[];
}
```

<img width="680" alt="document" src="https://github.com/web3/web3.js/assets/5390719/3f6d6471-5159-406c-bcbf-4dc7ef4f5a28">

Which one is true?

**Comment by SantiagoDevRel** [comment]
@luu-alex

**Comment by luu-alex** [comment]
Hey Thanks for reporting this, we wont be able to update this for the V4 has this would be a breaking change but this is something we can change back for the next major release. in the meantime you can use web3.utils to change bigint -> hex

**Comment by Jack-Works** [comment]
> Hey Thanks for reporting this, we wont be able to update this for the V4 has this would be a breaking change but this is something we can change back for the next major release. in the meantime you can use web3.utils to change bigint -> hex

I just want to know which one is correct, document or type definition, not asking for a breaking change.

**Comment by luu-alex** [comment]
if your using 4.x it will be returned as a bigint

**Comment by luu-alex** [comment]
With 4.x, baseFeePerGas will return bigint. The type definition is correct. Thanks for catching this, if you would like to create a PR to fix the docs feel free. Otherwise @SantiagoDevRel  can you take care of this problem

**Comment by sampleblood** [comment]
readonly baseFeePerGas: import("web3-types").NumberTypes[ReturnFormat["number"]]; 
should be Array?:
readonly baseFeePerGas: import("web3-types").NumberTypes[ReturnFormat["number"]][];
