### ISSUE TITLE
abitype@npm:0.7.1 [20ff3] → >=4.9.4 ✘

### ISSUE THREAD

**Issue by Dilrong** [ethereum/web3.js#7144]
#### Expected behavior
➤ YN0002: │ web3-eth-abi@npm:4.2.2 doesn't provide typescript (p6fa46), requested by abitype
- Not seeing the above message when yarn install

#### Actual behavior
➤ YN0002: │ web3-eth-abi@npm:4.2.2 doesn't provide typescript (p6fa46), requested by abitype
- see the above message when yarn install

#### Steps to reproduce the behavior

1. `yarn install`
2. web3-eth-abi@npm:4.2.2 doesn't provide typescript (p6fa46), requested by abitype
3. `yarn explain peer-requirements p6fa46`
4.  `abitype@npm:0.7.1 [20ff3] → >=4.9.4 ✘`

#### Logs
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ web3-eth-abi@npm:4.2.2 doesn't provide typescript (p6fa46), requested by abitype
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code

yarn explain peer-requirements p6fa46
➤ YN0000: web3-eth-abi@npm:4.2.2 doesn't provide typescript, breaking the following requirements:

➤ YN0000: abitype@npm:0.7.1 [20ff3] → >=4.9.4 ✘
```
![2024-07-09 15 41 22](https://github.com/web3/web3.js/assets/13635654/867bc92b-bbfc-48f0-875d-8b2f1b12836c)
I think the problem is caused by using typescript version 4.7.4 on `web3-eth-abi`.

#### Environment
Node: v16.19.1
typescript: v4.9.5
web3.js: v4.10.0

**Comment by luu-alex** [comment]
is this breaking your app? try using node v18, some of our dependancies may not work for nodev16

**Comment by Dilrong** [comment]
@luu-alex hello. I did a yarn install with node v18 but I get the same error.
![2024-07-15 10 00 14](https://github.com/user-attachments/assets/2f2fe6e2-7485-4b26-8013-8cc319d5d4ca)

**Comment by luu-alex** [comment]
seems to be an issue on dependancy abitype and web3.js typescript lib might not be compatible.

**Comment by Dilrong** [comment]
plans to update a typescript version of web3.js?

**Comment by Dilrong** [comment]
![2024-07-23 17 41 57](https://github.com/user-attachments/assets/9dab9785-d3f2-4648-a9af-ba3dd8ad34f4)
This is an image of package.json of abitype used by web3.js.

**Comment by luu-alex** [comment]
ya ill take a look into this, can u show me ur package.json

**Comment by Dilrong** [comment]
```json
{
  "name": "web3-abi-type-error",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "web3": "^4.11.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.3.1",
    "@types/supertest": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "jest": "^29.5.0",
    "prettier": "^3.0.0",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.4.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.1.3"
  },
  "yarn": {
    "packageManager": "yarn@3.6.0"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

The same error occurs with `web3js` installed in `nest init`
The `package.json` is as above.
