### ISSUE TITLE
Getting addresses and amount from internal transaction (Coinbase exchange)

### ISSUE THREAD

**Issue by dinumo12** [ethereum/web3.js#7146]
Nodejs, Web3Js

Hello. Can you tell me how to get recipient addresses and ETH amounts in this transaction? ABIDecoder didn't help me :(

https://etherscan.io/tx/0xa22daa186ebcdfc3c65fa40b9f689e3cd46cb34604bd407e591ef18610e76dd7

![image](https://github.com/web3/web3.js/assets/56683688/5b18008e-2660-44fb-9938-8e1224793e8b)

**Comment by luu-alex** [comment]
Issues on github is for reporting bugs in the library, this issue looks like a problem on the users side. To get advice or help i see you've asked on discord so we'll continue the convo there. Closing
