### ISSUE TITLE
add eth_newPendingTransactionFilter to rpc method wrappers

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#7188]
eth_newPendingTransactionFilter exists in rpc methods, its just not being exposed by web3.eth. Double check and make sure other methods are implemented as well 
https://github.com/web3/web3.js/issues/4483
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newpendingtransactionfilter

- [x] List all RPC methods
- [x] Move to library
- [x] Doc Update

**Comment by mconnelly8** [comment]
9/3 Meeting - should have this to support execution level.  Just need to expose it to the public in the lib.

**Comment by jdevcs** [comment]
following function are available in RPC Methods package but are not exported via Eth class:


| Function Name          | [JSON RPC API](https://ethereum.org/en/developers/docs/apis/json-rpc/) | [EL Specs](https://github.com/ethereum/execution-apis) |
|------------------------|----------|----------|
| getCompilers        |    x     |     x     |
| compileSolidity     |    x      |    x      |
| compileLLL          |     x     |     x     |
| compileSerpent      |     x     |     x     |
| `newFilter`           |    ✓     |     ✓     |
| `newBlockFilter`      |     ✓     |     ✓    |
| `uninstallFilter`     |     ✓     |    ✓      |
| `getFilterChanges`    |    ✓      |   ✓       |
| `getFilterLogs`       |     ✓     |    ✓      |
| submitHashrate      |    x      |     x     |
| `newPendingTransactionFilter` |  ✓     |    ✓      |
