### ISSUE TITLE
web3 components loading time

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#7189]
- Create a list of major lib components for benchmarking loading times and comparison with other libs ( send transaction, RPC calls, ABI encoding, contract deployment, utils, ..)
- Measure loading time of these components ( if used individual packages ) 
   (use suitable framework for achieving more consistent and reliable results, use dedicated testing tools and conducting tests under controlled conditions for factors like browser performance, network conditions, server response time, device capabilities)

**Comment by Redoudou** [comment]
@luu-alex the format of the file ideally would be like that. 
<img width="775" alt="image" src="https://github.com/user-attachments/assets/cb35aa5c-1b59-4e70-9428-0cb4f625d8bc">

**Comment by Redoudou** [comment]
@jdevcs  @luu-alex the `GetSign TransactionTime` is abnormally high about **400 Time** higher than Viem or Ether. Is the data correct ? Can we investigate a bit more ?

**Comment by luu-alex** [comment]
I don't believe it's an errror, I believe sign transaction does an rpc call to get nonce (not sure which rpc method off the top of my head) that's something we can fix to make it align with the other libraries
