### ISSUE TITLE
`CalculateFeeData`

### ISSUE THREAD

**Issue by SantiagoDevRel** [ethereum/web3.js#7206]
Hi guys,

When I try to use `eth.calculateFeeData()` when creating a plugin, it gives me this error `export 'eth'.'calculateFeeData' (imported as 'eth') was not found in 'web3' `

But when using it in another file as `web3.eth.calculateFeeData()` it works properly, not sure if the methos is not exported somewhere, or not sure if i'm missing something.
working 
```js
import { Web3 } from "web3";

const web3 = new Web3("https://sepolia.drpc.org");

async function main() {
  console.log(await web3.eth.calculateFeeData());
}
main()

```

Not working
```js
import { Web3PluginBase, eth, } from "web3";

export default class PluginTest extends Web3PluginBase {
  pluginNamespace = "test";

  async main() {
     const fee = await eth.calculateFeeData();
  }
}

```

**Comment by jdevcs** [comment]
@SantiagoDevRel eth is not exported to support : 
```
import { Web3PluginBase, eth, } from "web3";

export default class PluginTest extends Web3PluginBase {
  pluginNamespace = "test";

  async main() {
     const fee = await eth.calculateFeeData();
  }
}
```

Even if we export it, you will need to create instance of eth.`Web3Eth` class and pass provider / context in it to use, that you can already do by importing Web3Eth directly. Another (more neat) way is to use rpc wrapper functions and pass context from plugin to these https://github.com/web3/web3.js/blob/9b322052ef266cc57b29080b20053991e0c9a0a9/packages/web3-eth/src/rpc_method_wrappers.ts#L1019


or import https://www.npmjs.com/package/web3-rpc-methods and directly use [rpc methods](https://github.com/web3/web3.js/blob/9b322052ef266cc57b29080b20053991e0c9a0a9/packages/web3-rpc-methods/src/eth_rpc_methods.ts#L509) by passing context.requestManager in those
