### ISSUE TITLE
[plugin] customTransactionSchema follow-up

### ISSUE THREAD

**Issue by nicolasbrugneaux** [ethereum/web3.js#7273]
Greetings! Thanks again for merging my work in 
- #7227 

Sadly, it's _still_ not enough to allow for extra fields in transactions. Indeed, this function [`getEthereumjsTxDataFromTransaction`](https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/utils/prepare_transaction_for_signing.ts#L37-L56) is trimming down fields [despite being validated earlier](https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/utils/prepare_transaction_for_signing.ts#L150)

**Comment by nicolasbrugneaux** [comment]
I'm happy to propose changes but I just wanted to get your opinion on what you think should happen, I believe the function is somewhat redudant and could be limited to field aliasing (data<->input, gas<->gasLimit)

**Comment by jdevcs** [comment]
@nicolasbrugneaux considering getEthereumjsTxDataFromTransaction is used https://github.com/web3/web3.js/blob/6f9a485e0715a70170bf170ca1e1d1b26b43f6c3/packages/web3-eth/src/utils/prepare_transaction_for_signing.ts#L150 I think it can be modified to use alias for (data<->input, gas<->gasLimit) and spread all existing other fields from the transaction to return obj.

**Comment by aaronmgdr** [comment]
what about a test in web3 like "allows for plugins to add new tx fields" to make sure this works and prevent regressions

**Comment by nicolasbrugneaux** [comment]
- https://github.com/web3/web3.js/pull/7282
