### ISSUE TITLE
Cannot prevent site suggested gas price in Metamask

### ISSUE THREAD

**Issue by jalaguerom** [ethereum/web3.js#7303]
#### Expected behavior
Passing `maxPriorityFeePerGas` and `maxFeePerGas` as undefined to contract.method.send function should make Metamask calculate gas prices on its own based on market value. 

#### Actual behavior
Metamask shows site suggested gas price and incorrect speed time values

#### Steps to reproduce the behavior

1. Install latest Metamask version
2. Try to send a transaction to a smart contract abi method using send function, without sending `maxPriorityFeePerGas` and `maxFeePerGas`

Related issue: https://github.com/web3/web3.js/issues/7081. Solution talks about `ignoreGasPricing` parameter but it is not present in the send function

![Captura de pantalla 2024-10-04 a las 14 55 02](https://github.com/user-attachments/assets/d1185672-2f51-4ec2-bfb5-2ec4f218b2aa)

web3js version: 4.13.0

**Comment by mconnelly8** [comment]
Hey @jalaguerom, I'll have someone look into this soon.

**Comment by jdevcs** [comment]
@jalaguerom we will expose this ignore gas pricing flag at contract send level ( for each send() call and also I think at contract instance level). 
cc: @mconnelly8

**Comment by luu-alex** [comment]
Hey there in the meantime of fixing this, you can encode your abi contract into data and send it as a transaction. @jdevcs  we can add this as a ignoregas as a config as well. 
```

        const contract = new web3.eth.Contract(yourContract)
        const data = marketplaceContract.methods.yourmethod("param1", "param2").encodeABI();
        web3.eth.sendTransaction({from: accounts[0], data, to: "address"}, undefined, {ignoreGasPricing: false})
```

**Comment by zikyfranky** [comment]
Hey @luu-alex, going through this problem as well.

While your fix works, it's tedious to rewrite every instance where I used the .send function, is it possible to specify the ignoreGasPricing flag on the Contract Instance? That way I run my code as is.

**Comment by luu-alex** [comment]
@zikyfranky a fix will be created soon, sorry your also running into this issue.

**Comment by jalaguerom** [comment]
Thanks a lot. I'll be waiting until that feature is included @jdevcs

**Comment by jdevcs** [comment]
cc: @mconnelly8 for next sprint.

**Comment by luu-alex** [comment]
@jdevcs i think we should include it in this sprint, i can fix this and get it released this sprint.

**Comment by lukatavcer** [comment]
> @jdevcs i think we should include it in this sprint, i can fix this and get it released this sprint.

I would also appreciate if you include it in the current sprint, thanks :)

**Comment by mconnelly8** [comment]
@luu-alex, added it to the sprint!  Do your thing!

**Comment by lukatavcer** [comment]
> #### Expected behavior
> Passing `maxPriorityFeePerGas` and `maxFeePerGas` as undefined to contract.method.send function should make Metamask calculate gas prices on its own based on market value.
> 
> #### Actual behavior
> Metamask shows site suggested gas price and incorrect speed time values
> 
> #### Steps to reproduce the behavior
> 1. Install latest Metamask version
> 2. Try to send a transaction to a smart contract abi method using send function, without sending `maxPriorityFeePerGas` and `maxFeePerGas`
> 
> Related issue: #7081. Solution talks about `ignoreGasPricing` parameter but it is not present in the send function
> 
> ![Captura de pantalla 2024-10-04 a las 14 55 02](https://private-user-images.githubusercontent.com/35574907/373645303-d1185672-2f51-4ec2-bfb5-2ec4f218b2aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTA5MTYsIm5iZiI6MTcyODQ5MDYxNiwicGF0aCI6Ii8zNTU3NDkwNy8zNzM2NDUzMDMtZDExODU2NzItMmY1MS00ZWMyLWJmYjUtMmVjNGYyMThiMmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYzRlZWYwNjc2MDAzYTVjYmM3NmYxNTZiNDU0ZjVhMzVmMGJlOGM2ZGYxN2QzYTM5MGVjMjMzN2IxNjBlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vVN7vRQWsUT2LNwRGjCjnvd1uafZ1qmtiXoN3dG8d8U)
> 
> web3js version: 4.13.0

what also works is setting `gasPrice: ""`

```js
someContract.methods.someMethod().send({
    from: activeAccountAddress,
    gasPrice: "",
}
```

**Comment by luu-alex** [comment]
Added ignoregaspricing config to prevent site suggested gas price in metamask. This release will be aiming for monday, you can see usage [here](https://github.com/web3/web3.js/pull/7320/files#diff-592f07799efde08938fb9faa3f66b57bcb9bf2699633d981799ae24e3e51d541R503) 
Thanks everyone :)
