### ISSUE TITLE
Include EIP-4788 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#7312]
info regarding beacon should be included in block to replace web3-eth2-beacon 
https://eips.ethereum.org/EIPS/eip-4788 

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by luu-alex** [comment]
https://github.com/web3/web3.js/pull/6937

**Comment by jdevcs** [comment]
changes for this issue were added via 6937
