### ISSUE TITLE
Create a web3.js wiki page

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#7317]

**Comment by danforbes** [comment]
The [draft article](https://docs.google.com/document/d/1ozd7d1GPnK1b4CA-8jz6vJ8CpjbANgzyeERYGJTBn5E/edit?usp=sharing) is visible to ChainSafe employees

**Comment by danforbes** [comment]
The [article](https://en.wikipedia.org/wiki/Draft:Web3.js) has been created and submitted for review.
