### ISSUE TITLE
Type of `Web3Eth.calculateFeeData` Param `baseFeePerGasFactor` Should Support Decimals

### ISSUE THREAD

**Issue by danforbes** [ethereum/web3.js#7321]
When specifying the `baseFeePerGasFactor` for the `Web3Eth.calculcateFeeData` method, users may wish to specify a percentage, such as %112.5. To support this, the type of this parameter should be changed from `bigint` to a type that supports decimal values.

**Comment by TemirlanBasitov** [comment]
you can use baseFeePerGasFactor: number = 2, instead of bigint(2)

**Comment by TemirlanBasitov** [comment]
https://github.com/web3/web3.js/pull/7332
