### ISSUE TITLE
Typo in subscribe migration guide

### ISSUE THREAD

**Issue by Joro97** [ethereum/web3.js#7324]
There is a small typo in the subscribe migration guide. [This PR](https://github.com/web3/web3.js/pull/7325) should fix it.

#### Steps to reproduce the behavior

1. Open https://docs.web3js.org/guides/web3_upgrade_guide/subscribe_migration_guide/#subscribing-to-events
2. Read the third bullet under "Differences"
3. "...you code..." should become "...your code..."

#### Logs
Typo can be seen highlighted on the image below. "...you code..." should become "...your code..."
<img width="906" alt="image" src="https://github.com/user-attachments/assets/c12da390-8d22-4aa8-9b44-769439b2948e">

#### Environment
Tested on latest Brave + macOS version.

**Comment by mconnelly8** [comment]
Thanks @Joro97, the team will review the PR.
