### ISSUE TITLE
Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

### ISSUE THREAD

**Issue by VoQuocViet** [ethereum/web3.js#7376]
Can't import the named export 'hashForSignTypedDataLegacy' (imported as 'eip712') from default-exporting module

my ver
"web3": "1.10.0",

**Comment by mconnelly8** [comment]
Thanks @VoQuocViet, we will take a look at this.

**Comment by shayesteMalekpour** [comment]
i'm getting this error. would you please fix it?

**Comment by krzysu** [comment]
We recommend using Web3.js v4. Please upgrade to the latest version and let us know if you encounter any issues.
