### ISSUE TITLE
Does web3.isChecksumAddress works correctly?

### ISSUE THREAD

**Issue by ruchevits** [ethereum/web3.js#842]
Referring to the accepted answer on Ethereum Stack Exchange: http://ethereum.stackexchange.com/a/331/143

```js
'use strict'
const Web3 = require('web3')
const url = 'http://localhost:78545'
const provider = new Web3.providers.HttpProvider(url)
const web3 = new Web3(provider)
const res = web3.isChecksumAddress("0xCd2a3d9f938e13Cd947eC05ABC7fe734df8DD826")
console.log(res)
```

The code above outputs `false` while I expect `true`.

**Comment by frozeman** [comment]
Yes it doesn't, but you address checksum is wrong: The correct checksum is: `0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826` (see the second D)

```
web3.toChecksumAddress('0xCd2a3d9f938e13Cd947eC05ABC7fe734df8DD826'.toLowerCase())
```
