### ISSUE TITLE
creating a tx with bytes param sends as string

### ISSUE THREAD

**Issue by slothbag** [ethereum/web3.js#843]
I'm trying to create a tx which requires a bytes type as an argument, however the solidity contract is receiving the data as a text string, so passing in 0x1234 would report as length of 4 in solidity instead of 2.

**Comment by thisbejim** [comment]
Any update here?

**Comment by dev1644** [comment]
The Contract function's signature and its arguments need to be in encoded ABI. It doesn't matter if the function receives a string, uint etc. The data field in the transaction is needed to an ABI encoded string.

**Comment by nivida** [comment]
Did you test it with the latest version of Web3.js? 
and could you add a code example here?

**Comment by nivida** [comment]
Closed due to no reaction of the creator.
