### ISSUE TITLE
Leaking XMLHttpRequest into the global scope

### ISSUE THREAD

**Issue by fabioberger** [ethereum/web3.js#844]
Current behavior:
After requiring web3, global.XMLHttpRequest is defined. Before the require it wasn't.

Expected behavior:
Requiring web3 should not add properties to the global scope.

Affecting other projects that use web3: https://github.com/trufflesuite/truffle-contract/issues/14

**Comment by LogvinovLeon** [comment]
+1

**Comment by fabioberger** [comment]
Any update on this @frozeman? Still running into this issue often.

**Comment by nivida** [comment]
This shoud be fixed with the PR #2000

**Comment by nivida** [comment]
This got fixed with the [ProvidersModuleFactory](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/factories/ProvidersModuleFactory.js#L88).
