### ISSUE TITLE
outputLogFormatter param check error

### ISSUE THREAD

**Issue by Blacknikomo** [ethereum/web3.js#846]
There is error in web3.js:3802 
Sometimes i receive argument 'log' as string (like 0xABCDE0-9...).

And i receive error, then web3 try to find param of string-like log. 
This code attempt add parameter blockNumber to string.
Therefore this condition always return TRUE and i receive error: 

Uncaught TypeError: Cannot create property 'blockNumber' on string '0xabcde...'

I recommend you to use next condition:
   `if(log.blockNumber && log.blockNumber !== null)
        log.blockNumber = utils.toDecimal(log.blockNumber);`

instead of 
`if(log.blockNumber !== null)
        log.blockNumber = utils.toDecimal(log.blockNumber);`

**Comment by nivida** [comment]
This is fixed since beta.38.
