### ISSUE TITLE
Stringify error : XMLHttpRequest is not an function

### ISSUE THREAD

**Issue by glaulom** [ethereum/web3.js#847]
Hi guys,
I am having the following error :
`I20170329-19:15:06.245(2)? Exception while invoking method 'contractCreation' TypeError: XMLHttpRequest is not a function
I20170329-19:15:06.246(2)?     at [object Object].HttpProvider.prepareRequest (packages/ethereum_web3.js:4259:17)
I20170329-19:15:06.246(2)?     at [object Object].HttpProvider.send (packages/ethereum_web3.js:4275:24)
I20170329-19:15:06.247(2)?     at [object Object].RequestManager.send (packages/ethereum_web3.js:6206:32)
I20170329-19:15:06.247(2)?     at Eth.get [as coinbase] (packages/ethereum_web3.js:6109:62)
I20170329-19:15:06.248(2)?     at Object.stringify (native)
I20170329-19:15:06.248(2)?     at Object.stringify (/home/glaulom/.meteor/packages/ecmascript-runtime/.0.3.15.1ry5oia++os+web.browser+web.cordova/npm/node_modules/core-js/modules/es6.symbol.js:224:23)
I20170329-19:15:06.248(2)?     at [object Object].Meteor.methods.contractCreation (server/methods.js:16:25)
I20170329-19:15:06.249(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170329-19:15:06.250(2)?     at packages/ddp-server/livedata_server.js:719:19
I20170329-19:15:06.250(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
`

When trying to stringify the result of contract() :
`Meteor.methods({
    'contractCreation': function(){
        var myContract = web3.eth.contract(ABIArray).at(contractAddress);
        var json = JSON.stringify(myContract); // convert objecto to JSON
        // return EJSON.fromJSONValue(json) // conver JSON to EJSON
    }
});`

**Comment by Joeblockmark** [comment]
@glaulom did you fix this?

**Comment by glaulom** [comment]
@Joeblockmark no I didn't manage to make this work...

**Comment by Joeblockmark** [comment]
@glaulom the issue is caused by the fact that meteor uses [meteor HTTP]() instead of XMLHttpRequest which is what web3 is trying to use. I am experimenting with using meteor.call() as recommended by [this comment](https://stackoverflow.com/a/39129365) e.g. `HTTP.call('POST',"http://localhost:8545",{data:{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}},function(error, res){console.log(res)})` to get the blocknumber.
