### ISSUE TITLE
sha3 returning wrong result

### ISSUE THREAD

**Issue by madvas** [ethereum/web3.js#850]
In solidity we get:
```
function getSha() public constant returns (bytes32) {
     address addr = 0xb1c5a3554588d9b165a72bf916475b7aaf893ac8;
     return sha3("a", addr);
}
// 0x437295b586f19ad521f7fa3ee4cf3092f2f584ff1c871d4250d42d7bd1d3f0c0
```
To try to get the same in JS we would do something like this, but result is not the same:
```javascript
Web3.prototype.sha3(["0x61", "0xb1c5a3554588d9b165a72bf916475b7aaf893ac8"].join(""), {encoding: "hex"});
// 0xe409105258dceb3e6554e641ec0f2264f99f787f9cf78889aa9991db076aed03
```
Which is exactly what [solidity-sha3](https://github.com/raineorshine/solidity-sha3) would do under the hood:
```javascript
SoliditySha3.sha3("a", "0xb1c5a3554588d9b165a72bf916475b7aaf893ac8");
// 0xe409105258dceb3e6554e641ec0f2264f99f787f9cf78889aa9991db076aed03
```

So that's obviously a problem, not sure if I'm missing something or it's a bug. Interestingly, if I remove last 2 characters from the address, everything seems to be working fine:

```
function getSha() public constant returns (bytes32) {
     address addr = 0xb1c5a3554588d9b165a72bf916475b7aaf893a;
     return sha3("a", addr);
}
// 0x8cdeb39f61507ec5a71a736fc15276675ad8dcfa12e258eb8579aa953f2727be
```

```javascript
Web3.prototype.sha3(["0x61", "0xb1c5a3554588d9b165a72bf916475b7aaf893a"].join(""), {encoding: "hex"});
// 0x8cdeb39f61507ec5a71a736fc15276675ad8dcfa12e258eb8579aa953f2727be
```
```javascript
SoliditySha3.sha3("a", "0xb1c5a3554588d9b165a72bf916475b7aaf893a");
// 0x8cdeb39f61507ec5a71a736fc15276675ad8dcfa12e258eb8579aa953f2727be
```

I'm using web3 0.18.4
solc Version: 0.4.10+commit.f0d539ae.Darwin.appleclang

**Comment by madvas** [comment]
So what helped was to remove `0x` as so:
```javascript
Web3.prototype.sha3(["0x61", "b1c5a3554588d9b165a72bf916475b7aaf893ac8"].join(""), {encoding: "hex"});
// 0x437295b586f19ad521f7fa3ee4cf3092f2f584ff1c871d4250d42d7bd1d3f0c0
```
Although doesn't work for solidity-sha3: 
```javascript
SoliditySha3.sha3("a", "b1c5a3554588d9b165a72bf916475b7aaf893ac8")
// 0x6dc713dbcf145a4f5b3613ce9413dbe8692cdd56e6a8074680cbf2d9546db244
```

**Comment by imosdevteam** [comment]
I've been using [solidity-sha3](https://www.npmjs.com/package/solidity-sha3) @ npm for quite a while with good results instead of web3.sha3 . This is from their readme: 

> web3.sha3 doesn't always match the behavior of sha3 in Solidity. This one does.

gl

**Comment by mcdee** [comment]
There is a long-standing PR for solidity-sha3 at https://github.com/raineorshine/solidity-sha3/pull/1 that fixes this issue.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.

**Comment by mcdee** [comment]
So the choice for web3.js is now either a deprecated version or a beta version...
