### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by bioponx** [ethereum/web3.js#852]
When running meteor update, I receive error below.  Appreciate any suggestions.

While checking for ethereum:web3@0.18.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.

**Comment by bioponx** [comment]
I am using Mac OS Sierra, Meteor 1.4.3.2

**Comment by nschulte** [comment]
+1

**Comment by amisolution** [comment]
Same for me on ubuntu 16.04 METEOR@1.4.4.1

**Comment by ProphetDaniel** [comment]
Same for me on KDE neon based on ubuntu 16.04 LTS Meteor@1.4.4.1

`* These packages have been updated to new versions that are not backwards
compatible.
app: updated to Meteor 1.4.4.1.               
=> Errors while upgrading packages:           
                                              
While checking for ethereum:web3@0.18.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
platform.
`

**Comment by itisBaga** [comment]
The same...

**Comment by AlexandreRoba** [comment]
Same Error:
```bash
aroba@AROBAMBP:~/projects/myDapp$ meteor add ethereum:web3
 => Errors while adding packages:             
                                              
While checking for ethereum:web3@0.18.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by stabenfeldt** [comment]
```bash
$ meteor add ethereum:web3
   Selecting package versions                \
 => Errors while adding packages:             \

While checking for ethereum:web3@0.18.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by raymondcarl** [comment]
I downgraded Meteor to 1.2.0.2, which is the last known version I have the works with web3.  I'm sure that an later version also works, but didn't have time to see which one is the most recent, compatible release.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
