### ISSUE TITLE
Invalid address when parsing address[]

### ISSUE THREAD

**Issue by tuytuy** [ethereum/web3.js#853]
`var zones= {0x977cb939d18895f8127d3e775c6c37c73da30d7b, 0x977cb939d18895f8fd5d6s3445c6c37c73da30d7b};` 
`var name = "helo";
var startDate = "12/12/12";
var duration = 2;` 
` var abi = [{"constant":false,"inputs":[{"name":"addr","type":"address"}],"name":"isContract","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"zones","type":"address[]"},{"name":"name","type":"bytes32"},{"name":"startingDate","type":"bytes32"},{"name":"duration","type":"uint256"}],"name":"newTrip","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"details","outputs":[{"name":"phoneNumber","type":"string"},{"name":"physicalAddress","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getTrips","outputs":[{"name":"","type":"address[]"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"orgAddresses","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"trips","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"getDetails","outputs":[{"name":"","type":"string"},{"name":"","type":"string"},{"name":"","type":"address"}],"payable":false,"type":"function"},{"inputs":[{"name":"orgAddress","type":"address"},{"name":"phoneNumber","type":"string"},{"name":"physicalAddress","type":"string"}],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"address"}],"name":"LogCreatedTrip","type":"event"}])
` 
` var ethMedicalStaffObject = web3.eth.contract(abi).at("0xcab63dc5574fb6afe5b8294f0c13ea6d768015d5");` 
  ` ethMedicalStaffObject.newTrip(zones, name, startDate, duration, function(error, result){
        if (!error) {
            console.log("it worked");
        } else {
            console.log(error);
            callback({success: false, message: error});
        }
    });` 

I get and Invlalid error on the line var ethMedicalStaffObject, what am I doing wrong ?

**Comment by nivida** [comment]
Variable zones should be an array not an object.  I will close this Issue.
