### ISSUE TITLE
new BigNumber() not a base 16 number: " error occurs when not refreshing without the cache

### ISSUE THREAD

**Issue by glaulom** [ethereum/web3.js#855]
Hi,
I've been experiencing a very weird bug. I  have a contract with this code :
`function consultFile(uint _idDocument, address _patientAddress) returns (string _fileName, string _fileDescription){
		if(records[_patientAddress].rights[msg.sender].consultAccess || records[_patientAddress].files[_idDocument].isPublic || _patientAddress==msg.sender){
			_fileName = records[_patientAddress].files[_idDocument].fileName;
			_fileDescription = records[_patientAddress].files[_idDocument].fileDescription;
		}else{
			throw;
		}
	}`

And I use web3 in meteor, when trying to execute this function this way  : 
`myContract.consultFile.call(i,"0x2b461Db580028F263351B969cFd8542db696787E",function(err, res){
			if(err){
				console.log("Erreur : ");
				console.log(err);
			} else {
				var doc = {Title : res[0], Description : res[1]};
				array.push(doc);
				TemplateVar.set(template, "files", array);	
			}
		});`
It does'nt work unless I use "ctrl+shif+r" in order to load withou the cache. Otherwise I keep getting the following error :
`Error: new BigNumber() not a base 16 number: 
    at T (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6708:28898)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6709:2445
    at new e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6708:26415)
    at i.w [as _outputFormatter] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:9973)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:14661
    at i.decode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:14683)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:7489
    at Array.map (native)
    at d.decodeParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:7462)
    at s.unpackOutput (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:5426)`

I hope someone could help if it's due to my code ! Thank you guys !

**Comment by glaulom** [comment]
Am I the only one to experiencing this bug ? @frozeman ?
Or am I doing something wrong ?

**Comment by CraigglesO** [comment]
This error was SOOO frustrating for 3 hours of debugging. Turns out it comes from something in the solidity code that web3 does not like. For instance (in my case) when you make an event, you can not use `indexed` for strings (don't know why this trips bigNumber up, but it does)

for me I changed:
```
event Event(string indexed n, string indexed m, uint indexed t);
```
To:
```
event Event(string n, string m, uint indexed t);
```

and all was well with the world

**Comment by glaulom** [comment]
Thanks for the feedback.

Strangely, after deploying my Dapp on a server the problem stopped occuring... I can't figure out why, but it's okay I gues.

Thanks again.
