### ISSUE TITLE
web3

### ISSUE THREAD

**Issue by Katsu1991** [ethereum/web3.js#856]
hi guys,  
"web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545')); // 8080 for cpp/AZ, 8545 for go/mist"
what's mean of this  code ? especially  annotations “8080 for cpp/AZ, 8545 for go/mist”， beacese i can use ：http://localhost:8080 to open the application (truffle metacoin demo). Hope your answers.

**Comment by mrslvr1346** [comment]
Hi Katsu1991,
web3.SetProvider methods sets the API endpoint. For this to work a node must be running. 
For cpp node (eth) and AlthZero node (AZ) default port is 8080 and for GO (geth) and Mist default port is 8545 on localhost.
You can change the default host and port at the time you start your node by providing additional arguments in cli. 
Correct me if I am wrong.
