### ISSUE TITLE
Can't Install web3 package to meteor project

### ISSUE THREAD

**Issue by billh93** [ethereum/web3.js#864]
For some reason I'm not able to install the package using meteor. I can install it using npm so I just wanted to give everyone a heads up. I also came across the same issue #546 from January of this year.

```
bill:mixgif bill$ meteor add ethereum:web3
 => Errors while adding packages:             
                                              
While checking for ethereum:web3@0.18.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

```

**Comment by tpaixao** [comment]
Also having this error... For reference, Using Windows 7 and meteor 1.4.4.1

**Comment by rodrigueGit** [comment]
Also having this issue on MacOS Sierra 10.12.4.

**Comment by JohnAllen** [comment]
Anyone found a solution to this?  Tried multiple earlier versions.

**Comment by JohnAllen** [comment]
Nevermind using the npm version.  **duh**

**Comment by Deozaan** [comment]
I am also having this problem.

```
While checking for ethereum:web3@0.19.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

On Windows 10, using Meteor 1.4.4.3.

**Comment by JohnAllen** [comment]
Use the npm package. Works fine.

**Comment by Deozaan** [comment]
> Use the npm package. Works fine.

I saw that suggested in #546 but it didn't work for me either.

I've just grabbed the web3.js file manually for now.

**Comment by VinZ73** [comment]
@Deozaan 

Hello could you please tell me, where to manually copy (in which path / ) into meteor the web3.js file ?

thank's a lot

**Comment by Deozaan** [comment]
@VinZ73 I'm not sure. I made a project using `meteor create myProject` and then placed the `web3.js` inside `myProject/lib/`

So far in my tests it appears to be working, but I'm not sure if that's because Metamask is injecting the web3.js or because it's automatically loading web3.js from the `lib` folder.

Sorry I couldn't be of more help. Good luck!

**Comment by tsouza** [comment]
I am also with this problem. I could install an older version `0.18.3`
