### ISSUE TITLE
filter.watch sometimes just stops working after about 36 hours

### ISSUE THREAD

**Issue by morelazers** [ethereum/web3.js#871]
I'm watching a few contracts (~15) from the same process, and usually after running for a day or so, events just stop coming through into the callback.

As far as I can tell there are no errors passed into the callback handler. I asked someone else with a similar problem and they mentioned that their workaround was simply to restart the process, but I'd like to avoid that, if at all possible.

If there's anything you can suggest to help provide better feedback please let me know and I'll get on it.

**Comment by Plinpod** [comment]
@morelazers I am running into the same issue, did you ever get this sorted?

**Comment by morelazers** [comment]
@Plinpod IIRC we ended up creating our own watcher by listening for incoming blocks (npm's [ethereum-blocks](https://www.npmjs.com/package/ethereum-blocks) library is pretty decent at this, though it's prone to swallowing errors so make sure you use try catch statements heavily) and scanning their logs. The fallback for that was polling for new blocks every few minutes and then retrieving & scanning their logs. So it's a fair bit more effort, but it was _much_ more reliable.

**Comment by Plinpod** [comment]
@morelazers Thanks for the quick reply. I'll check out ethereum-blocks

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
