### ISSUE TITLE
Web3.toHex remove most significant zero

### ISSUE THREAD

**Issue by mhgharieb** [ethereum/web3.js#873]
when using web3.toHex to convert from number to hex, if the most significant nibble is zeros, it removes that nibble. this can case problem if that number will be passed to a contract and saved in bytes

Ex
```
var a = 159340662;
a_hex = web3.toHex(a); //  result : a_hex = '0x97f5876' but the correct one is '0x097f5876'

contract test{
   bytes a;
   function test(bytes _a){
     a = _a;
   }
   function get() returns(bytes){
     return a
   }
}

// running
test(web3.toHex(a))
the result of get function will be '0x97f587'

web3 gives '0x97f5876' and contract gives '0x97f587' but the correct one is  '0x097f5876'
```

**Comment by D-Nice** [comment]
Same issue, I had to add an npm module called `left-pad` to handle this, and ensure what web3 returns in hex, has an even number of characters, and left pads by one if not, but I believe this should be handled internally, and it should not be returning odd-numbered hex representations.

**Comment by danieljbruce** [comment]
So are you two looking for the twos complement output of http://www.rapidtables.com/convert/number/decimal-to-hex.htm? Note that this calculator maps -15 and 657468657265756d to the same value.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
