### ISSUE TITLE
Update shh methods to whisper v5

### ISSUE THREAD

**Issue by kenshyx** [ethereum/web3.js#874]
After the release of `geth 1.6.1` some of the rpc methods were removed from the shh module, one example would be `shh_newIdentity` which throws an error right now `Error: The method shh_newIdentity does not exist/is not available`

**Comment by gluk256** [comment]
The new release has switched from Whisper v.2 to Whisper v.5. 
Method newIdentity was changed. It was renamed to "subscribe" and params are changed.
More info here: https://github.com/ethereum/go-ethereum/wiki/Whisper

**Comment by TylorShin** [comment]
Does anyone be working on it now?
I think that we should change methods of web3.js's shh object.

**Comment by hootstheowl** [comment]
Looks like the updated methods are currently available in the [develop branch](https://github.com/ethereum/web3.js/blob/develop/lib/web3/methods/shh.js).

**Comment by nivida** [comment]
The latest whisper API should be implemented in web3 1.0.0-beta.

**Comment by 0xli** [comment]
check shh options of geth 
geth --shh --rpc --rpcapi web3,eth,net,shh
