### ISSUE TITLE
`.dividedBy` on big numbers may freeze Safari

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/web3.js#877]
* If you run `web3.toBigNumber("99728875900000000000").dividedBy("1000000000000000000")` in Safari, it freezes.
* If you run the same in Chrome, or Node, it works and does not freeze.

This appears to be caused by the [forked version](https://github.com/debris/bignumber.js) of BigNumber. Indeed, if you use its `bignumber.js`:

* If you run `new BigNumber("99728875900000000000").dividedBy("1000000000000000000")` in Safari, it freezes.
* If you run the same in Chrome, it works and does not freeze.

Also, the [original repo](https://github.com/MikeMcl/bignumber.js) does not freeze either Safari or Chrome.

**Comment by xwartz** [comment]
I fund this bug, the original repo fixed it via this [commit](https://github.com/MikeMcl/bignumber.js/pull/122/files). 

I wonder why web3.js not use the  original repo, https://github.com/ethereum/web3.js/issues/904#issuecomment-311246171

**Comment by binhnd-socicom** [comment]
The same issue occur on React-native if turn off Chrome debug

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
