### ISSUE TITLE
Provider filter leak: Event.get() creates new filter instead of getting logs

### ISSUE THREAD

**Issue by danfinlay** [ethereum/web3.js#879]
The [Filter.get() method](https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L205-234) creates a new filter on the provider, and never deallocates it.

This is a serious memory leak, and it's totally unnecessary, because it could simply call `getLogs` on the provider instead of installing a filter at all.

**Comment by flyswatter** [comment]
Furthermore, it looks like there is no way to simply trigger an `eth_getLogs` request by itself using web3 currently, because [the mere instantiation of the event object requests the creation of a filter on the provider](https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L148).

Here's an example:

```javascript
  const Registrar = web3.eth.contract(abi)
  registrar = Registrar.at(registrarAddress)

  window.reg = registrar

  // This simple log query, for just two blocks,
  // Will send a `eth_newFilter` request to the provider,
  // Registering a filter process on the provider.
  var auctionStarted = reg.AuctionStarted({}, {
    fromBlock: 3767372,
    toBlock: 3767373,
  })

  // Currently this simply pushes on the filter logs request stack,
  // Firing an `eth_getFilterLogs` request, when no filter is needed for this request.
  auctionStarted.get(function(error, logs) {
    console.log('auctionstarted get returned', error, logs)
  })
```

**Comment by flyswatter** [comment]
I created a minimal web dapp with the code shown above (it only console logs, no UI):

https://flyswatter.github.io/web3-event-get-leak-example/

**Comment by wighawag** [comment]
I am right now looking at using logs and would like to avoid creating a filter on the remote node so I wanted to use ```eth_getLogs``` and found that issue while I was looking for a different api that creating a filter first.

web3 should provide a function to get logs using ```eth_getLogs``` without the need to instantiate a filter

**Comment by flyswatter** [comment]
At this point, you're best off using `web3.currentProvider.sendAsync({ type: 'eth_getLogs' })` directly, to bypass this web3 bug, I don't see it getting fixed with much urgency.

**Comment by wighawag** [comment]
Hi Dan, thanks
that was my plan too but I wanted to add a voice. Web3 definitely needs some love :)

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
