### ISSUE TITLE
Unable to install web3.js for meteor

### ISSUE THREAD

**Issue by DhaneshKothari** [ethereum/web3.js#883]
Hi,
I'm trying to get web3.js added to my meteor package.
I tried from command prompt as well as from poweshell with admin rights with following command:
I'm getting following error while trying to install web3.js
meteor add ethereum:web3

Each time I'm getting following error:
No compatible binary build found for this package. Contact the    package author and ask them to publish it for your platform.

I also tried to forcefully install earlier version, but even that didn't work.

meteor npm install web3 is also not working due to some remote repository access related issues.

Any help will be highly appreciated.

Thanks

**Comment by VinZ73** [comment]
I have the exact same issue 
and when running Dapp on meteor i get this : on the webconsole

Error: invalid argument 0: missing 0x prefix for hex data  ethereum_web3.js:3142:16

**Comment by GitSpree23** [comment]
Same issue. Meteor v1.5 on Win 10.
Error found
> While checking for ethereum:web3@0.19.0

**Comment by prabhu15bgp** [comment]
meteor add ethereum:web3

No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

Same error

**Comment by TylerL-uxai** [comment]
+1 error for meteor

**Comment by chronakazi** [comment]
same here

**Comment by prabhu15bgp** [comment]
meteor add ethereum:web3@=0.18.3

This command downloads the packages .Web3 versions above this shows the same error.

**Comment by chronakazi** [comment]
^ that did it! Thanks so much.
