### ISSUE TITLE
how to pass an array like byte[] to smart contract using javascript?

### ISSUE THREAD

**Issue by xuxiao415** [ethereum/web3.js#885]
my contract code:
function addVideo(string videoSHA224, byte[] videoSHA256) public {
       //my codes
    }

**Comment by okpalindrome** [comment]
Would you please share how did you solve this. my code is kinda same 
`function setatt(string[] arrayName){
//code
}`

**Comment by adeeba2** [comment]
Any solution on this?

**Comment by sehrixhshafeeq** [comment]
Do we have any update how can we can send array of addresses as parameters in web3.js?
