### ISSUE TITLE
Unable to connect to node using HttpProvider on GCE

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/web3.js#888]
The webpage is hosting on my local server and HttpProvider connect to node on GCE.

```
sudo geth --ipcdisable --rpc --rpcport 8114 --datad
ir "./node01/data" --networkid 123 --rpcapi="db,eth,net,web3,personal" --n
odiscover --port=30319 --rpccorsdomain="*" console
```
```
web3.setProvider(new web3.providers.HttpProvider('http://35.187.147.241:8114'));
```

firewall allow
<img width="727" alt="2017-06-11 8 12 56" src="https://user-images.githubusercontent.com/11001914/27010934-c67ec706-4ee2-11e7-946e-c6c3fdb94a5c.png">

On localhost node works good,but don't know why it can't connect to nodes running on GCE.

**Comment by shayanb** [comment]
is there any specific reason you disabled ipc `--ipcdisable` ?

**Comment by EasonWang01** [comment]
Because it using RPC here but ipc is default option.

**Comment by 0xcaff** [comment]
Try adding `-rpcaddr=0.0.0.0`

**Comment by nivida** [comment]
Closing this because of the answer from 0xcaff.
