### ISSUE TITLE
Better handling of arguments when doing calls and constructing.

### ISSUE THREAD

**Issue by beether** [ethereum/web3.js#889]
I'm not sure if this is already slated, but it would be _massively_ helpful to have interactions with Web3 be as simple as possible.  Variable length arguments are not simple.

It would be great if calls / constructors always took two params:
`myContract.someFunction( argsToSomeFunc, opts )` and `MyContract.net(constructorArgs, opts)`

It would also be great if the args could be a object with name/value pairs.  An error can be thrown if incorrect params are passed, omitted, or of the wrong type.  This would catch errors a lot sooner and would be extremely helpful to developers.  Moreover, it would make code read much better.

eg:

```
// assume an ABI declares a constructor with three params:
// uint wingspan, bytes32 chirpNoise, uint age

// compare this, which may cause unexpected results (since the `age` param may be defaulted to 0)
Bird.new(10, "tweet");

//to this, which is more readable, and will immediately throw `param 'uint age' not provided`
Bird.new({wingspan: 10, chirpNoise: "tweet"});

// this would also throw:  `unknown param 'chirpSound'`
Bird.new({wingspan: 10, chirpSound: "tweet", age: 3});
````

At the very least, please please please consider having the "arguments" be an array rather than cardinal:

`Bird.new([10, "tweet", 3], {.. opts ..})`

For a few reasons:
* It's so much easier knowing that `.new` always takes two parameters.
* It's easier to pass an array than it is to call .apply or .call
* Dealing with variable length arguments leads to difficult-to-read code, and ambiguities

**Comment by awgneo** [comment]
+1000 to name/value pairs; so many needless hours of debugging could be squashed :)

**Comment by antho1404** [comment]
I also have issues when trying to call a function that contains an array as a first argument that might be related to this and could be solved by passing an object or a clear array.
eg:
```
{
    "constant": true,
    "inputs": [
      {
        "internalType": "uint160[]",
        "name": "exitIds",
        "type": "uint160[]"
      }
    ],
    ...
}
```
