### ISSUE TITLE
More easily manually specify call vs transaction

### ISSUE THREAD

**Issue by beether** [ethereum/web3.js#891]
It would be nice to manually specify a call or transaction by just tacking on some extra code.

`myInstance.someFunc({ ..args.. }, { ..opts.. }).asCall()`

I realize it may be slightly awkward, as the result of `myInstance.someFunc({ ... })` is a promise, but there's nothing to stop you from change the request before `nextTick()` occurs.

Alternatively, and more easily, it could be an option:

`myInstance.someFunc({ ..args.. }, {as: "call" || "transaction"})`

**Comment by shayanb** [comment]
if you use `myContract.methods.myMethod([param1[, param2[, ...]]])` [docs](http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id12) it will automatically detect if call or send is needed for the called function. however, you can also specify either way:

```
Call:
myContract.methods.myMethod(123).call({from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe'}, function(error, result){

Send:
myContract.methods.myMethod(123).send({from: '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe'})
```
More examples here: http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id15

this issue can be closed now.

**Comment by Dibri** [comment]
Hi, I'm trying to create a transaction that call a method in a smart contract.
`
var contract = web3.eth.contract(ABI).at(contractAddress)

function showStatus() {
var result =  contract.turnOffAllLamps().sendTransaction({from: 'myAddress'});
}
`
I've tried your version too but it can't find the methods field and if i remove it, the error is the same of my version:     throw new Error('invalid address');
