### ISSUE TITLE
Invalid Address error when calling a function added to Contract after passing an object to web3.eth.contract.at()

### ISSUE THREAD

**Issue by qjflores** [ethereum/web3.js#892]
An Invalid Address error is thrown when you call on a function added to the contract after pass an object in to web3.eth.contract.at()

example
```
const contractAddress = {address: 'valid_contract_address'}
const contractFactory = web3.eth.contract(validContractAbi)
const contractInstance = contractFactory.at(contractAddress)

contractInstance.myFunction() // this will throw an Invalid Address error
```
I notice that there is no check in lib/web3/contract.js
```
ContractFactory.prototype.at = function (address, callback) {
    var contract = new Contract(this.eth, this.abi, address);

    // this functions are not part of prototype,
    // because we dont want to spoil the interface
    addFunctionsToContract(contract);
    addEventsToContract(contract);

    if (callback) {
        callback(null, contract);
    }
    return contract;
};
```

**Comment by kuanlim** [comment]
g'b'h

**Comment by PHPJourney** [comment]
I am stop here. contract anything api can't used。
you mean contract api need add module call?

**Comment by qjflores** [comment]
I mean that there is no validation to check in contractFactory that the address is a valid address

**Comment by PHPJourney** [comment]
ok.
 i mean i just need contract api used action.  the contract question be hard

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
