### ISSUE TITLE
contract.watchAll() returns logs of other contracts

### ISSUE THREAD

**Issue by beether** [ethereum/web3.js#895]
It seems the intended behavior of the SolidityAllEvents class is to return all logs produced by the contract itself, and not other contracts.  Right now it looks at all logs and filters them by topic (but not address).  The result is that logs from other contracts (that have matching topics) are returned when you specify someContract.watchAll()

This should filter by address as well, which is passed into the constructor, to ensure the only logs returned are those of the object being watched.

```
    // lib/web3/allevents.js, line 56
    var match = this._json.filter(function (j) {
        return eventTopic === sha3(utils.transformToFullName(j));
    })[0];
```

**Comment by shayanb** [comment]
@beether If you pass the address to your filter it should filter out only the events that are triggered by the contract
```js
var filter = web3.eth.filter({event:'eventNameHere',fromBlock:'latest', address:'0xCONTRACT_ADDRESS' });
```

If this doesn't answer your question, please include a code snippet to reproduce the issue.

**Comment by beether** [comment]
@shayanb yes, you can work around the issue.

The expected behavior is very clearly that you shouldn't have to filter by an address if you're listening from an instance of a contract.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
