### ISSUE TITLE
TypeError: Cannot access member 'match' of undefined

### ISSUE THREAD

**Issue by br4nd0n** [ethereum/web3.js#898]
When executing contract methods within the Geth console on the Ropsten test network, I'm getting the following error:

myContract.notarize.sendTransaction('123', {from: "0x6b804e5c1c876229606b249554f20573ab478b8f"})

TypeError: Cannot access member 'match' of undefined
    at web3.js:539:14
    at web3.js:660:16
    at filter (<native code>)
    at web3.js:659:24
    at web3.js:850:16
    at map (<native code>)
    at web3.js:849:12
    at web3.js:691:25
    at web3.js:3983:46
    at web3.js:4054:19

(Note that when executing this contract method from the Truffle console against the Ropsten test network, it executes successfully)

This appears to be web3/dist/web3.js line 539, which is:

SolidityTypeAddress.prototype.isType = function (name) {
    return !!name.match(/address(\[([0-9]*)\])?/);
};

which would indicate 'name' is being passed in as undefined

The contract and method I'm running are this:
pragma solidity ^0.4.2;
// Proof of Existence contract, version 3
contract ProofOfExistence3 {
  mapping (bytes32 => bool) private proofs;
  // store a proof of existence in the contract state
  function storeProof(bytes32 proof) {
    proofs[proof] = true;
  }
  // calculate and store the proof for a document
  function notarize(string document) {
    var proof = calculateProof(document);
    storeProof(proof);
  }
  // helper function to get a document's sha256
  function calculateProof(string document) constant returns (bytes32) {
    return sha256(document);
  }
  // check if a document has been notarized
  function checkDocument(string document) constant returns (bool) {
    var proof = calculateProof(document);
    return hasProof(proof);
  }
  // returns true if proof is stored
  function hasProof(bytes32 proof) constant returns(bool) {
    return proofs[proof];
  }
}

**Comment by br4nd0n** [comment]
Using Geth 1.6.5-stable

**Comment by karthiknvlr** [comment]
I am facing the same issue while I try to access my contract in private network.
I am using web3@0.20.0 for interacting with my smart contract.
`/home/karthikeyan/Desktop/testblc/node_modules/web3/lib/solidity/address.js:23
    return !!name.match(/address(\[([0-9]*)\])?/);
                 ^
TypeError: Cannot read property 'match' of undefined`

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
