### ISSUE TITLE
unable to call web3.isAddress from JSONRPC

### ISSUE THREAD

**Issue by underst00d** [ethereum/web3.js#899]
web3.isAddress (and other web3 methods such as toWei) works fine in the geth console, but when called from RPC (or IPC), it always returns

`{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"The method is_address does not exist/is not available"}}`

web3 is enabled by default, but still i explicitly used `--rpcapi web3`. This is confirmed by socat `{"jsonrpc":"2.0","id":1,"result":{"admin":"1.0","debug":"1.0","eth":"1.0","miner":"1.0","net":"1.0","personal":"1.0","rpc":"1.0","txpool":"1.0","web3":"1.0"}}`

i tried all possible combinations i can think of, such as web3_is_address. still no luck. any one can shed some light on this? Thanks.

**Comment by PHPJourney** [comment]
hi, you used JSONRPC . me too.
there have more question. something api can't find or used. 
do you know contract how used.

this contract i can't find use action.  and how to query Tokens transaction? main chain no find Tokens amount

#934 if you know solution.  please tell me

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
