### ISSUE TITLE
TypeErrors from Filter.outputLogFormatter spamming node.js console

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ethereum/web3.js#901]
After successful deployment of a contract via `web3.js` running on latest node.js (8.1.2), verified by copy/pasting the new contract address from the `geth` console (this is a private blockchain w/ custom `genesis.json`) and using with `MyContract.at(...)` to retrieve an object with expected and functioning contract methods, `Filter.outputLogFormatter` begins spewing errors into the node.js console, such as:

`TypeError: Cannot create property 'blockNumber' on string '0x381a5df1fa5a342ecf0dca13f64f3c5445a241c4e1de5d6f623f33d4462c7598' at Filter.outputLogFormatter [as formatter] (/path/to/dapp/node_modules/web3/lib/web3/formatters.js:194:25`

At that point, the node.js console becomes barely usable and after digging around for some time, I have no idea if I'm doing something wrong or I've run into a bug, or...?

**Comment by frozeman** [comment]
Can you still reprouce this, and can you please test if you have the same issue with 1.0.0-beta.17?

**Comment by nivida** [comment]
@michaelsbradleyjr any news about it? :)

**Comment by nivida** [comment]
I'm closing this issue because there was no reaction. Please drop a comment if I should reopen it.
