### ISSUE TITLE
Error while adding to Meteor

### ISSUE THREAD

**Issue by ENiG87** [ethereum/web3.js#903]
Hello, 

I tried to add web3 to Meteor via the recommended method. I already created my meteor project called Prototyp and then I entered the following code and get this negative result back:

```
C:\Users\Henning Wagner\Desktop\ProjectDApp\Prototyp>meteor add ethereum:web3
 => Errors while adding packages:

While checking for ethereum:web3@0.19.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it
for your platform.
```

I don't know which additional infos you need to troubleshoot this, but don't hesitate to just ask. I will provide whatever I can.

Thank you

**Comment by cyntechtic** [comment]
Try using meteor add ethereum:web3@=0.18.3
I think it has do with version 0.19.0 that it is trying to download though I'm still checking for solution

**Comment by ENiG87** [comment]
I tried that yesterday and it worked. Then I tried  meteor add
ethereum:tools and it worked too. Thanks anyway.

cyntechtic <notifications@github.com> schrieb am Sa. 24. Juni 2017 um 03:30:

**Comment by shayanb** [comment]
I think this issue is resolved. please close the issue. @frozeman
