### ISSUE TITLE
BigNumber dependency

### ISSUE THREAD

**Issue by orlandoc01** [ethereum/web3.js#904]
The dependency listed here https://github.com/ethereum/web3.js/blob/develop/package.json#L11 points to a github repo that no longer exists. Until this dependency is resolved, I can no longer install and use this library

**Comment by maraoz** [comment]
+1

**Comment by obale** [comment]
+1

Same problem we are facing.

**Comment by alankritjoshi** [comment]
How is 1.0 handling BigNumber (devdependency) 4.0.0? Can we backport the changes to fix this issue? [https://github.com/ethereum/web3.js/blob/1.0/package.json](url)

**Comment by shayanb** [comment]
this should fix the issue, not sure if bignumber updates have broken anything on web3.js but it seems to work. I'm going to run more tests to be sure. 

https://github.com/ethereum/web3.js/pull/905

**Comment by ericmuyser** [comment]
Ironically, the top recommended comment to "Ethereum is impossible to get started" is `use embark` which has dep on web3 which doesn't install due to this 😂 
https://www.reddit.com/r/ethereum/comments/6iorba/getting_started_on_ethereum_is_impossible_my/?st=j4aee9mk&sh=54e30401

**Comment by theporpoise** [comment]
hey, just came here to say I ran into the same issue.  Is there a workaround until this patch is pushed?

**Comment by shayanb** [comment]
@theporpoise one way is to change your package file to use the fixed version. I'm using this at the moment `"web3": "https://github.com/shayanb/web3.js#develop"` in `package.json

**Comment by theporpoise** [comment]
thanks @shayanb !

**Comment by nicoschtein** [comment]
I was trying to fix this after checking https://github.com/ethereum/web3.js/pull/439 but indeed the repo is not available anymore.

**Comment by wangjia184** [comment]
Modify package.json as below
```
{
  "dependencies": {
    "web3": "github:shayanb/web3.js#develop"
  }
}
```

**Comment by orlandoc01** [comment]
Looks like PR [#905](https://github.com/ethereum/web3.js/pull/905) that was merged fixed the issue in the `develop` branch. However, since the situation requires a hotfix, there should be a patch made to the `master` branch and probably a new release to fix this issue, unless the team is planning on releasing v1.0 soon (since it appears to be fixed there)? Otherwise the published npm module is still broken and everyone depending on it through an npm installation can not use this.

**Comment by orlandoc01** [comment]
Something like this? https://github.com/ethereum/web3.js/pull/906

**Comment by MitchK** [comment]
Can someone please release the hotfix on npm?

**Comment by burritofridays** [comment]
Yep my issue is with npm as well.

**Comment by OR13** [comment]
This is currently breaking testrpc as well.

https://travis-ci.org/ethereumjs/testrpc/jobs/246462784

**Comment by frozeman** [comment]
Seems like marek did remove bignumber.js from his repo

**Comment by adonley** [comment]
Having issues with truffle ATM as well.

**Comment by frozeman** [comment]
I merged @orlandoc01 PR and published 0.19.1, but i can't get the meteor version uploaded, something is broken on the meteor servers.
@adonley you still have the issues with the current develop?

**Comment by adonley** [comment]
@frozeman I'm good with develop in my package.json but I can't get truffle to grab it's deps correctly - I'll checkout 0.19.1 . Thanks for moving quickly on this.

**Comment by MitchK** [comment]
thanks @frozeman for moving quickly!

**Comment by frozeman** [comment]
Ok got 0.19.11 published on meteor as well.

**Comment by doppio** [comment]
Thank you!! This was a huge headache for me.

**Comment by frozeman** [comment]
@all i switched to the older bignum version with lookahead disabled, which is necessary for web3.js working in the geth console.
Can you please test the develop branch and tell me if its working for you guys?

**Comment by burritofridays** [comment]
web3 npm is working again.

ethereumjs-testrpc however has the same issue as described above.

**Comment by imosdevteam** [comment]
Shouldn't the fix involve updating all bignumber.js deps to use the master repro here: https://github.com/MikeMcl/bignumber.js/  ?

**Comment by debris** [comment]
sry guys for breaking that. Thanks to @iurimatias the repo is back up and even old versions of `web3.js` should be working

**Comment by xwartz** [comment]
I wonder why not use the  [original repo](https://github.com/MikeMcl/bignumber.js)?
And why not use npm to manage the dependency?
I saw the only different code is this [commit](https://github.com/debris/bignumber.js/commit/94d7146671b9719e00a09c29b01a691bc85048c2).
I think we should create a PR to the  [original repo](https://github.com/MikeMcl/bignumber.js).

**Comment by frozeman** [comment]
@xwartz because its a degradation of a feature, but necessary so it runs in the otto VM

**Comment by xwartz** [comment]
@frozeman  thanks for replying. I have seen bignumber.js as devDependency in web3.js 1.0. That's greate!

**Comment by Clement-Bresson** [comment]
I am encountering this same issue again. Anyone else ?
npm version : 5.6.0 (lastest)

**Comment by burritofridays** [comment]
I just rebuilt from version web3.js v1 beta 29 a few nights ago and so far so good.

**Comment by DurandA** [comment]
When using bower and installing `web3@1.0.0-beta.34`, this is still an issue:
```
bower web3#1.0.0-beta.34        cached https://github.com/ethereum/ethereum.js.git#1.0.0-beta.34
bower web3#1.0.0-beta.34      validate 1.0.0-beta.34 against https://github.com/ethereum/ethereum.js.git#1.0.0-beta.34
bower bn.js#>=4.11.6         ENOTFOUND Package bn.js not found
```

**Comment by nival999** [comment]
Fork the bignumber repo. Upload it to npm. Point the package.json from web3 to that repo. Republish web3 on npm. cloning from the development branch is not working.
