### ISSUE TITLE
How to prevent from reconnecting?

### ISSUE THREAD

**Issue by florianmaxim** [ethereum/web3.js#907]
When my local geth's arpc server is not running and I once call:
new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
it keeps spamming my console with these "OPTION"-Errors. 
So I check for a signal before I connect. Is there any better option to stop it
from auto reconnecting? Because it can really slow my app down..

`fetch('http://localhost:8545', {

        method: 'get'

        }).then((response) =>{

          console.log('Signal available, connecting...');

          this.web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));

        }).catch((err) => {

          console.log('No RPC signal available. Do not even try to connect.');

        });`

<img width="276" alt="screen shot 2017-06-24 at 14 59 10" src="https://user-images.githubusercontent.com/17391294/27509029-827556a4-58f3-11e7-8f77-63ff2063fcb7.png">

**Comment by nivida** [comment]
It does not look like this issue is directly related to web3.js and because of that I'closing it.
