### ISSUE TITLE
Message undefined when calling batch.execute

### ISSUE THREAD

**Issue by glowkeeper** [ethereum/web3.js#908]
I get the following error in the console when calling `execute()` on a batch created via `web3.createBatch()`

```
TypeError: message is undefined
	Jsonrpc.toBatchPayload/< http://127.0.0.1:8081/bundle.js%20line%203400%20%3E%20eval:80:9
	map self-hosted:275:17
	Jsonrpc.toBatchPayload http://127.0.0.1:8081/bundle.js%20line%203400%20%3E%20eval:79:12
	RequestManager.prototype.sendBatch http://127.0.0.1:8081/bundle.js%20line%208591%20%3E%20eval:105:19
	Batch.prototype.execute http://127.0.0.1:8081/bundle.js%20line%208444%20%3E%20eval:48:5
	executeBatch
```

Interestingly, all the transactions I added to the batch seem to run successfully, so it seems the 'error' isn't terminal.....

ps. I'm using `testrpc` - might that be the 'problem'?

**Comment by nivida** [comment]
@glowkeeper Is this issue still there in the latest version of web3?

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
