### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by MeoowWoof** [ethereum/web3.js#915]
I can't seem to get web3 installed via npm. It always fails with the following error.

Cmd : npm install web3
Error : npm ERR! Path must be a string. Received undefined

Log 

`
 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'web3' ]
2 info using npm@5.0.4
3 info using node@v8.1.3
4 verbose npm-session 02c74f27df35fda1
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/web3 236ms (from cache)
8 silly pacote tag manifest for web3@latest fetched in 269ms
9 verbose stack TypeError: Path must be a string. Received undefined
9 verbose stack     at assertPath (path.js:28:11)
9 verbose stack     at Object.relative (path.js:1248:5)
9 verbose stack     at computeVersionSpec (/usr/lib/node_modules/npm/lib/install/deps.js:282:27)
9 verbose stack     at Installer.normalizeCurrentTree (/usr/lib/node_modules/npm/lib/install.js:370:69)
9 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
9 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
9 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
9 verbose stack     at iferr (/usr/lib/node_modules/npm/lib/install.js:328:5)
9 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
9 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
9 verbose stack     at /usr/lib/node_modules/npm/node_modules/call-limit/call-limit.js:22:12
9 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:95:7)
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
10 verbose cwd /home/username
11 verbose Linux 4.11.7-1-ARCH
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "web3"
13 verbose node v8.1.3
14 verbose npm  v5.0.4
15 error Path must be a string. Received undefined
16 verbose exit [ 1, true ]

`

**Comment by MeoowWoof** [comment]
Tried with stable on  node@v8.0.0 ; encountering same issue.

**Comment by frozeman** [comment]
Works for me
```
test npm install web3 --save
Mist@0.8.10 /Users/frozeman/Sites/_ethereum/test
└─┬ web3@0.18.4
  ├── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  ├── crypto-js@3.1.8
  ├── utf8@2.1.2
  ├── xhr2@0.1.4
  └── xmlhttprequest@1.8.0
```

**Comment by frozeman** [comment]
Reopen if it still persists.

**Comment by MeoowWoof** [comment]
Not that i did not try re-installing it , but on 2nd re-install it worked seamlessly. I am not sure what caused the issue , and the solution is not conclusive. If any one encounters it , please try to re-install and keep a close eye on the dependency , It might be down to some weird dependency which was not cleaned or got upgraded on re-installation.
