### ISSUE TITLE
(Why) are underscored event args not shown in console?

### ISSUE THREAD

**Issue by sudokoin** [ethereum/web3.js#921]
When I prefix Solidity event parameter names with underscores (like proposed in ERC20), the fields do not show in geth Web3.js console.

When I remove the underscores, I can inspect event fields without problems.

Is this a bug or am I doing something wrong?

Using
solidity/solc 0.4.11
Geth/v1.6.6-unstable/darwin-amd64/go1.8.3
Web3.js 0.18.1

```JavaScript
// watcher code

var errors = [];
var events = [];

contractInstance.allEvents(
  function(err, ev) {
    if(err){
      errors.push(err);
      return;
    }
    events.push(ev);
  }
);
```

(copied from https://ethereum.stackexchange.com/questions/20963/underscore-prefixed-event-arguments-wont-show-in-console)

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
