### ISSUE TITLE
Constructor taking too long when no remote node exists

### ISSUE THREAD

**Issue by jefffreey** [ethereum/web3.js#922]
When I try to initialize web3 from Node.js, i.e.: 
`web3 = new Web3(new Web3.providers.HttpProvider("http://1.2.3.4:8545"));`
with a non-existent remote node address, it takes too long trying to (not) find the node. Can we have a preliminary check that quickly returns false when the target does not exist?

Thanks,

**Comment by 0xcaff** [comment]
How would you implement this? Figuring out whether the node exists takes time because the network could be flaky.
