### ISSUE TITLE
Addition of swarm-js causes webpack builds to fail

### ISSUE THREAD

**Issue by christopherdro** [ethereum/web3.js#923]
The addition of the swarm-js library on branch 1.0 introduced issues on client side apps that may be using webpack.

`Module not found: Can't resolve 'child_process' in '/Users/christopherdro/Desktop/sample-app/node_modules/web3/packages/web3-bzz/node_modules/swarm-js/lib'
`
/cc @MaiaVictor

**Comment by christopherdro** [comment]
Fixed via https://github.com/ethereum/web3.js/commit/443b4f18cabc454215692f31238357bd48806d87

**Comment by stevendikowitz** [comment]
Any resolution to this? Getting the error as well.

**Comment by apraka16** [comment]
Same issue this side.

**Comment by MaiaVictor** [comment]
Sorry, I didn't see this before. This commit should fix it.

**Comment by christopherdro** [comment]
fd2a9471dd2a77a4ba360f2f44033c32625f2c78

**Comment by bellaj** [comment]
npm install web3@0.19
