### ISSUE TITLE
Version 19.0 no longer supports BigNumber objects in contract methods

### ISSUE THREAD

**Issue by D-Nice** [ethereum/web3.js#925]
It appears that the latest update has broken contract methods, which are directly passed BigNumber objects now, from the following release change:
`Checks for the right argument number in contract functions`

The error returned when passing a formerly working function, with a BigNumber as a parameter is:
`Error: Invalid number of arguments to Solidity function`

Reverting to `18.2` or calling `.valueOf()` on the BigNumber parameter is a temporary patch, but I believe this should be fixed, as it states in the web3 API doc that the BigNumber type is a valid parameter to pass directly!

This issue was previously brought up on metamask https://github.com/MetaMask/metamask-extension/issues/1778

**Comment by frozeman** [comment]
Is this still an issue in 0.20.0?

**Comment by D-Nice** [comment]
I haven't tried with 0.20.0 but will give it a try when able, but I think I've seen some fix potentially implemented back in 0.19.1 so I'll report back on those results.

**Comment by D-Nice** [comment]
To report back, this is broken in 19.0, but other versions appear fine.

**Comment by frozeman** [comment]
We are focusing on the 1.0 branch, can you make sure that issue doesnt exist there?, also please re-test with 0.20.2
