### ISSUE TITLE
1.0-branch : WebsocketProvider throws when sending a transaction directly after creating it

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/web3.js#930]
```javascript 
const Web3=require('web3')
const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8546'))
web3.eth.getBlockNumber().then(console.log)
``` 
This will throw an error
```javascript 
  throw new Error('cannot call send() while not connected');
``` 

The reason is simply because the connected-event fromt the websocket-client is handled async later in the evenqueue.

As a workaround this would work:

```javascript 
const Web3=require('web3')
const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8546'))
setTimeout(()=>web3.eth.getBlockNumber().then(console.log),500)
```

But I think we should rather change the send-function:

```javascript 
W3CWebSocket.prototype.send = function(data) {
    if (this._readyState !== OPEN) {
        if (this._readyState === CONNECTING) 
             // if we are still waiting for the connec-even, we simply retry later
             setTimeout(()=>this.send(data),200)
        else
            throw new Error('cannot call send() while not connected');
    }
```
Instead of just throwing this error we should first check, if we are actually waiting for the connect-event and in this case rescedule or retry it later.

**Comment by frozeman** [comment]
Thanks will change

**Comment by frozeman** [comment]
I added the async call. But i can't test on my side as my geth WS fails for some reason.
I published beta.6 with this change.

**Comment by Kannanravindran** [comment]
I am still getting this issue. Was there a fix in web3 ?
@simon-jentzsch Even the workaround doesn't have any effect. My connection closes anyway. Also tried using `setInterval` . No luck!
```
web3 version: 1.0.0.beta.29
provider: wss://ropsten.infura.io/ws
```

**Comment by zhahaoyu** [comment]
same here

**Comment by aibric1407** [comment]
Same here

**Comment by Plinpod** [comment]
Still having this issue

**Comment by lijodigiledge** [comment]
error in npm start

connection not open on send()
connection not open on send()
connection not open on send()
Error: connection not open
at WebsocketProvider.send (/home/lijo/philippines/chakka/node_modules/web3-providers-ws/src/index.js:247:18)
at Timeout._onTimeout (/home/lijo/philippines/chakka/node_modules/web3-providers-ws/src/index.js:232:19)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)

**Comment by frozeman** [comment]
Is the connection open on the nodes end? And the wsorigin is set properly?

On 23

**Comment by lijodigiledge** [comment]
ws port 8546 is not opened
