### ISSUE TITLE
contract.transferFrom callback "new BigNumber() not a number: [object object]"

### ISSUE THREAD

**Issue by PHPJourney** [ethereum/web3.js#934]
i am try tes abi send Transaction

about transferFrom and transfer . I don't know how used this params.

test system is GETH and wallet console.

```
cf = web3.eth.contract(abi).at(address);
cf.transferFrom({from: cf.address,to: web3.eth.accounts[2],value: 1000}]

cf.transferFrom([{from: cf.address,to: web3.eth.accounts[2],value: 1000}]]

cf.transferFrom(cf.address,web3.eth.accounts[2],1000)
```
I get two error message.

No.1 invalid address

No.2 
```
Error:new BigNumber() not a number : [object,object]
at raise (web3.js:14632:29)
at web3.js:14620:33
at BigNumber (Web3.js:13648:67)
at BigNumber (web3.js:13658:29)
at web3.js :2212:16
at web3.js:2223:21
at web3.js:930:32
at web3.js:1576:12
at web3.js:694:16
at map ((native code))
```

@frozeman

**Comment by PHPJourney** [comment]
No.3 
```
(anonymous): Line 1:22 Unexpected token: (and 7 more errors)
```

**Comment by frozeman** [comment]
It expects parameters like `cf.transferFrom(cf.address, web3.eth.accounts[2], 1000, {from: 'the address you want to execute this tx from', gas: 200000})`

**Comment by PHPJourney** [comment]
@frozeman ok,thanks. i'm try. 
a new question. I used curl can't call eth.contract Object. JSON-RPC like not match contract api。
the JSON-RPC lack some api， about contract。
