### ISSUE TITLE
installation error with beta7

### ISSUE THREAD

**Issue by rsaccon** [ethereum/web3.js#938]
I managed to install beta5 (after installing globally lerna first), but with beta7 I get the following errror:
```

Robertos-MacBook-Pro:app robertosaccon$ yarn add web3
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
⠁ 
⠁ 
⠁ 
⠁ 
error /Users/robertosaccon/kelor/app/node_modules/web3: Command failed.
Exit code: 127
Command: sh
Arguments: -c ./node_modules/lerna/bin/lerna.js bootstrap
Directory: /Users/robertosaccon/kelor/app/node_modules/web3
Output:
sh: ./node_modules/lerna/bin/lerna.js: No such file or directory
```
also lerna is still globally installed, so I would assume that should have been picked ...

**Comment by MichalZalecki** [comment]
I have the same problem (also macOS): https://github.com/ethereum/web3.js/issues/933

**Comment by simon-jentzsch** [comment]
if you use web3 beta5 as a dependency, it will run the postinstall-script and assumes to find lerna as dependecy under ./node_modules/lerna, but in that case it would actually be found ../node_modules/lerna. I forked it and removed the ./node_modules in the postinstall-script since lerna can also be found in the path under node_modules/.bin/lerna 
See https://github.com/slockit/web3.js/commit/08d20ffb675414bce638e8445a64420d37835aba

**Comment by futuremarc** [comment]
Can also confirm this issue, also on macOS

**Comment by SeyZ** [comment]
+1 same issue

**Comment by hartct** [comment]
+1 same issue on Windows 10 as well

**Comment by thisbejim** [comment]
+1 Mac

**Comment by thevaleriemack** [comment]
+1 mac

**Comment by garethfoote** [comment]
+1 mac

**Comment by frozeman** [comment]
hm, the reason why i made it this way is to not make people install learn globally.
It should actually install the local lerna and have it present. Maybe because its only a devDependecy?

Any idea how to solve that without making people install learn globally?

**Comment by hartct** [comment]
@frozeman for what it's worth, I have lerna installed globally and still have this problem.

**Comment by MichalZalecki** [comment]
@frozeman This PR doesn't require having it installed globally: https://github.com/ethereum/web3.js/pull/939

**Comment by songsb13** [comment]
Is there any workaround install web3 on Windows?

**Comment by AoDev** [comment]
Same issue with `lerna`, I tried to install on OSX (node 8, npm 5)

Tried versions:

- web3 `0.20.0`
- web3 `1.0.0-beta7`

Tried installing lerna locally. 
Nothing worked. 

Any reason it is not in web3 dependencies?
- It is not in master/develop (currently even) 
- It is in devDependencies in branch 1.0 so it won't install.

**Comment by frozeman** [comment]
web3@1.0.0-beta.10 should fix that
