### ISSUE TITLE
Unhandled rejection Error: Wrong response id "25" 

### ISSUE THREAD

**Issue by hrishikeshio** [ethereum/web3.js#940]
Version 1.0 (commit hash = c154988   )

Many of the examples given in documentation don't work and give this error. here's an example. The response id keeps increasing.
Os: mac os x
Browser: latest Chrome

```js
web3.eth.accounts.signTransaction({
    to: '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
    value: '1000000000',
    gas: 2000000
}, '0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318')
.then(console.log);

i {_bitField: 0, _fulfillmentHandler0: undefined, _rejectionHandler0: undefined, _promise0: undefined, _receiver0: undefined…}
web3-1.0.min.js:1 Unhandled rejection Error: Wrong response id "25" (expected: "3823692783358944") in {"jsonrpc":"2.0","id":3823692783358944,"method":"net_version","params":[]}
    at http://localhost/stateChannel/js/web3-1.0.min.js:1:431701
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8222:5
From previous event:
    at i.d [as _captureStackTrace] (http://localhost/stateChannel/js/web3-1.0.min.js:1:362390)
    at i._resolveFromExecutor (http://localhost/stateChannel/js/web3-1.0.min.js:1:395366)
    at new i (http://localhost/stateChannel/js/web3-1.0.min.js:1:387897)
    at e.exports (http://localhost/stateChannel/js/web3-1.0.min.js:1:429178)
    at s.i [as getId] (http://localhost/stateChannel/js/web3-1.0.min.js:1:350837)
    at m.signTransaction (http://localhost/stateChannel/js/web3-1.0.min.js:1:657911)
    at <anonymous>:1:19
```

**Comment by frozeman** [comment]
I cannot reproduce this. To which node are you connecting?

Works for me:
<img width="640" alt="screen shot 2017-07-24 at 19 21 52" src="https://user-images.githubusercontent.com/232662/28535638-63d252fa-70a5-11e7-808c-5128dfb0fb1d.png">

**Comment by hrishikeshio** [comment]
Using metamask - rinkeby testnet (which i think is infura)
I did not compile by the way. Using precompiled web3.min.js in the repo. @frozeman

**Comment by frozeman** [comment]
@kumavis are you altering the response IDs in any way?

**Comment by hrishikeshio** [comment]
@frozeman No. I dont really know what these are.. can you explain?

**Comment by frozeman** [comment]
Every JSON rpc request contains a `id` which needs to come back with the same ID, so the calling library can match requests and responses. It looks like meta mask is changing the returning ID. (i guess at least)

**Comment by subramanianv** [comment]
@hrishikeshio Did you fix this problem ? I have the same issue and I am stuck

**Comment by phra** [comment]
@frozeman i got the same error while upgrading from metamask own web3 to one included by me to fix some deprecation warnings. maybe we have to reset some data somewhere in order to make the nonces to restart from 1?

**Comment by rmi7** [comment]
any news about this?

**Comment by frozeman** [comment]
I was currently on holidays. The person who could help with that the best would be @kumavis

**Comment by JamesKnippel** [comment]
coming from #981 since it was closed. some of us have been seeing this error:

`MetamaskInpageProvider - sendAsync not overwritten` 

this fixed when I created a storage variable for my defaultAccount like so:

`this.web3.eth.defaultAccount = ''0x0myAddress'';
  this.defaultAddress = this.web3.eth.defaultAccount;`

if I were not to do the above, this following deployment would error. 

` deployWill = () => {
    this.willContract
      .new({
        from: this.defaultAddress,
      })
      .then((result) => {
        console.log('did this contract deploy?', result);
        this.contractAddress = result.address;
        this.contractInstance = result;
      })
      .catch(e => {
        console.log(e);
      });
  } `

feels really strange and sloppy, but I had to do so.

**Comment by phra** [comment]
it seems to be fixed, have a look at https://github.com/MetaMask/metamask-extension/issues/1940

**Comment by nivida** [comment]
Please drop a comment if this isn't solved.

**Comment by JoshuaQYH** [comment]
I encountered this problem suddenly. But I could run the code before.(I didn't change them). So I thought it might be **a tempory bug in metaMask** and then I just logged out the metamask account and logged in again. It turned right.  May be it's helpful for you.

**Comment by eccentricexit** [comment]
I still encounter this error. Switching accounts in metamask fixes the issue but do we have another fix or workaround for this? It's terrible UX to ask users to do this for a dapp to work.

**Comment by sbwengineer** [comment]
I met the same issue when I try to get status of public mapping variable from bscscan.com.
Did anyone solve this issue?

**Comment by JoshuaQYH** [comment]
你好！你的邮件我已收到！
