### ISSUE TITLE
Add event signature to the object received in callback

### ISSUE THREAD

**Issue by vdrg** [ethereum/web3.js#942]
Please correct me if I'm wrong, but when using `contract.allEvents().watch(...)` you don't really have a way to identify the event that was received in the callback, as there can be multiple events with the same name but different signatures.

Shouldn't the event object include the signature as well?

**Comment by frozeman** [comment]
Thats a valid point, and something i can consider for 1.0.0

**Comment by frozeman** [comment]
Actually we do have that already in 1.0 beta. We include the raw event data, see:
http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id30

You can then check like `event.raw.topics[0]`

**Comment by vdrg** [comment]
That's awesome :)

**Comment by frozeman** [comment]
I just added it in beta.11: http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id30
