### ISSUE TITLE
web3 devDependency underscore conflict with meteor

### ISSUE THREAD

**Issue by destinatis** [ethereum/web3.js#945]
My meteor dApp relies on underscore and works fine with web3@0.18.2. However, when I npm install web3@1.0.0-beta.11 and run my dApp I get the following. Reverting back to 0.18 fixes the problem. Removing meteor's underscore package does not resolve the problem.

![screen shot 2017-07-24 at 8 55 32 pm](https://user-images.githubusercontent.com/11956729/28555113-9069dfa6-70b2-11e7-93af-40a48fbcd270.png) 

Any ideas? What else should I try?

**Comment by frozeman** [comment]
works for me:
![screen shot 2017-07-25 at 13 54 37](https://user-images.githubusercontent.com/232662/28570978-e0be7e92-7140-11e7-833b-de6bc138f623.png)

Maybe something wrong with your meteor setup? you can try `meteor reset`, but this will also erase you DB

**Comment by destinatis** [comment]
meteor reset did not work. I am using meteor 1.5.1.

**Comment by destinatis** [comment]
Created a blank app, installed 1.0.0beta works.
Pasted source from my previous app, same issue... uninstall 1.0.0 and install 0.20... works.

**Comment by destinatis** [comment]
Tried with meteor 1.4.1.  Now I am getting... otherwise works with 0.20.

![screen shot 2017-07-25 at 3 28 14 pm](https://user-images.githubusercontent.com/11956729/28596555-0199f2f6-714e-11e7-9690-b3fb091f61cd.png)

**Comment by destinatis** [comment]
So, I narrowed down the issue. The problem happens when I try to use require. Haven't found the work around yet. Open to suggestions.

<img width="935" alt="screen shot 2017-07-25 at 5 40 02 pm" src="https://user-images.githubusercontent.com/11956729/28599710-94def6fc-7161-11e7-947d-1ba7fe8a43ed.png">

**Comment by destinatis** [comment]
Okay, so it's definitely the library. Started brand new app with meteor 1.5.1 and added var Web3 = require('web3'); to main.js in the client. Getting same error.

**Comment by frozeman** [comment]
btw why you are not using the meteor package ethereum:web3 ?

**Comment by frozeman** [comment]
I think the issue is when meteor tries to compile the rather complex web3.js lib for the frontend. Something is breaking there. The `ethereum:web3` package for example is only linking the already prebuild web3.js.min.js. Which works only for the frontend. Otherwise adding it as backend lib shouldn't simply work as a npm module.

Will close that for now, if you find a solution how meteor can build that, let me know. Otherwise use the meteor package.
