### ISSUE TITLE
1.0: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thisbejim** [ethereum/web3.js#948]
When calling a contract method that does not have any arguments I am getting the following error: `TypeError: Cannot read property 'length' of undefined`. 

It looks to be coming from [_encodeMethodABI](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/index.js#L362) where `args` is undefined rather than an array.

**Comment by chchmatt** [comment]
There is a bug here. See my post and answer here:

https://ethereum.stackexchange.com/a/23062/7132

**Comment by frozeman** [comment]
Will be fixed in the next version, thanks for noticing.

**Comment by frozeman** [comment]
Should be fixed in beta.12

**Comment by chchmatt** [comment]
Thanks. Keep up the great work!

**Comment by SergeSysoev** [comment]
Hello. It's still happening in 1.0.0-beta.24.

**Comment by nivida** [comment]
Pls reopen this issue still exists in beta27 :)

**Comment by scientistnik** [comment]
I installed beta.48....still exists

**Comment by rayyan808** [comment]
Still exists on 1.3.4, how to solve?

**Comment by mayankjindalmj** [comment]
Still exists on 1.6.1

**Comment by 0xrishavsharma** [comment]
The bug still exists in 2.9.6

**Comment by luisantoniocrag** [comment]
Still exists on 1.7.3

**Comment by rafaelmrdyn** [comment]
actually you should check your data if there is not undefined
