### ISSUE TITLE
Module not found: Error: Can't resolve 'child_process' in swarm-js/lib

### ISSUE THREAD

**Issue by niksmac** [ethereum/web3.js#949]
> Module not found: Error: Can't resolve 'child_process' in '/Users/niksair/iWork/projects/df/newui/node_modules/web3/packages/web3-bzz/node_modules/swarm-js/lib'

- node v8.2.1
- npm v5.3.0

Here is the [debug log](https://pastebin.com/0qGeesSL)

**Comment by christopherdro** [comment]
Duplicate https://github.com/ethereum/web3.js/issues/923

**Comment by christopherdro** [comment]
Fixed via fd2a9471dd2a77a4ba360f2f44033c32625f2c78

@frozeman This can be closed
