### ISSUE TITLE
Cannot redefine property: currentProvider beta-1.0

### ISSUE THREAD

**Issue by gswftw** [ethereum/web3.js#953]
Upgraded to 1.0.0-beta.13, but getting this error when setting up the http provider to connect to testrpc or geth rpc local testnet (same url for both).  Code is the following as given in the documentation:

`var Web3 = require('web3');
var web3 = new Web3('http://localhost:8454');
`

**Comment by jdkanani** [comment]
Can be related to https://github.com/ethereum/web3.js/issues/956.

**Comment by frozeman** [comment]
Please try again with the beta.15, if not reopen
