### ISSUE TITLE
Create official TypeScript typings

### ISSUE THREAD

**Issue by doppio** [ethereum/web3.js#954]
TypeScript has gained a lot of popularity in recent years. It is non-trivial to use web3 in TypeScript without a lot of configuration. An official set of type declarations for the library would make it much easier for developers to incorporate web3 into their library.

There are several half-baked web3 type definition files floating around online, but an official one that is maintained in parallel with the library would allow for a much smoother development experience. It might make most sense to add this alongside (or after) version 1.0 once the API is not in flux.

See https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html for information about declaration files.

**Comment by frozeman** [comment]
There is a PR open, maybe you can test it: https://github.com/ethereum/web3.js/pull/897

**Comment by doppio** [comment]
Awesome, I didn't see that! I think discussion on this topic can be taken to the PR, then. Feel free to close this issue if you'd like.
