### ISSUE TITLE
1.0 beta13 Subscribed contract events not firing over http

### ISSUE THREAD

**Issue by walteriousnut** [ethereum/web3.js#961]
Using 1.0 beta13 against TestRPC, I can successfully subscribe as follows:
```javascript
oracleInstance.events.allEvents((error,event) => console.log(event))
.on('data', function(event) {
  console.log('data!');
  console.log(event);
})
.on('changed', function(event) {
  console.log('change!');
  console.log(event);
})
.on('error', console.error);
```

But none of these fire when the event is called in the contract.

I know the event has fired because getPastEvents includes the events I'm expecting.
```javascript
oracleInstance.getPastEvents('allEvents', { fromBlock: 0 }).then(events => console.log(events));
```

Do subscriptions require web sockets? If so, that's a significant impact to the test toolchain that includes TestRPC
I'll validate this shortly over ws:8546 against a real network and report back.

**Comment by frozeman** [comment]
Yes it requires WS, or IPC connections. Subscriptions don't work over HTTP as it has no push. We are thinking of adding an additional `eth_pollSubscription` but its not a priority.

**Comment by ta20170412** [comment]
Does not work for me over IPC either:

```javascript
web3.eth.subscribe("newBlockHeaders",function(err, res){
        console.log(err, res);
        // never called
      })
      .on("data", (log)=>{
        console.log(log);
        // never called
      })
```
Another one:
```javascript
web3.eth.subscribe("logs", {
        //fromBlock:  null // uncommenting this leads to processing of events for single block (latest complete) 
      }, function(err){
        console.log(err);
      })
      .on("data", (log)=>{
        console.log(log);
      })
      .on("changed", (log)=>{
        console.log(log);
      })
```

web3: web3@1.0.0-beta.4
geth: Geth/v1.6.6-stable-10a45cb5/linux-amd64/go1.8.3
node: v6.11.1

**Comment by ta20170412** [comment]
Updated web3 to version web3@1.0.0-beta.13 .
Same behavior.

**Comment by detailyang** [comment]
+1 v1.0.0-beta.15

**Comment by frozeman** [comment]
I will look into this.

**Comment by frozeman** [comment]
I just tested and blockheads work, though only on WS and IPC.
It doesn't work for HTTP though. 
Please reopen if the issue persists with beta.16 and giving me some reproducible examples.

**Comment by onairelav** [comment]
maybe
