### ISSUE TITLE
Unable to install web3 on macOS

### ISSUE THREAD

**Issue by akhilesharora** [ethereum/web3.js#963]
macOS Seirra - 10.12.5
node version - v8.2.1

**Unable to install web3 even with superuser permission**  Tried installing it many time but failed. Please suggest me some workaround.

akhilesh:user$ sudo npm i -g web3

> web3@1.0.0-beta.13 postinstall /usr/local/lib/node_modules/web3
> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! installInDir Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir  problem backing up package.json { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! installInDir   errno: -13,
lerna ERR! installInDir   code: 'EACCES',
lerna ERR! installInDir   syscall: 'rename',
lerna ERR! installInDir   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! installInDir   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
lerna ERR! execute Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! execute   errno: -13,
lerna ERR! execute   code: 'EACCES',
lerna ERR! execute   syscall: 'rename',
lerna ERR! execute   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! execute   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:132
    throw err
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/web3/lerna-debug.log.4119643886'
    at Object.fs.openSync (fs.js:652:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:117:17)
    at writeLogFile (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/utils/writeLogFile.js:43:29)
    at BootstrapCommand._complete (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:310:36)
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:292:20
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/commands/BootstrapCommand.js:140:11
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:44:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.13 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-07-30T21_09_41_718Z-debug.log

<img width="1233" alt="screen shot 2017-07-31 at 3 51 30 am" src="https://user-images.githubusercontent.com/484069/28757578-a3dee978-75a3-11e7-89c1-54f2d6f3ada2.png">
_Screen shot of  /Users/user/.npm/_logs/2017-07-30T21_09_41_718Z-debug.log_

**Comment by lukehedger** [comment]
Hey Akhilesh - No reason to [install NPM packages with `sudo`](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and Web3 should be installed locally to a project.

Try this to get the latest 1.0.0 beta release:
```
npm i web3@latest
```

**Comment by frozeman** [comment]
Please try again with the beta.15, if not reopen

**Comment by akhilesharora** [comment]
Thanks @frozeman, it got installed now. Added sudo because it was asking for more permissions.

**Comment by sandeep1116** [comment]
I am also facing same problem macos with command  I used sudo npm  i web3@latest


npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /Users/sandeepkumar/Documents/latestWeb3/node_modules/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: in `/Users/sandeepkumar/Documents/latestWeb3/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details


> scrypt@6.0.3 install /Users/sandeepkumar/Documents/latestWeb3/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/sandeepkumar/Documents/latestWeb3/node_modules/scrypt/build'
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sandeepkumar/Documents/latestWeb3/node_modules/scrypt
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/sandeepkumar/Documents/latestWeb3/package.json'
npm WARN latestWeb3 No description
npm WARN latestWeb3 No repository field.
npm WARN latestWeb3 No README data
npm WARN latestWeb3 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sandeepkumar/.npm/_logs/2018-07-13T10_16_21_897Z-debug.log

**Comment by zhuza** [comment]
I used the command " sudo npm i web3@latest "
the following shows I still failed
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/xiaobaozhu/anaconda/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xiaobaozhu/node_modules/scrypt
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/xiaobaozhu/package.json'
npm WARN xiaobaozhu No description
npm WARN xiaobaozhu No repository field.
npm WARN xiaobaozhu No README data
npm WARN xiaobaozhu No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaobaozhu/.npm/_logs/2018-10-04T13_37_44_980Z-debug.log

**Comment by adarshsrivastava11** [comment]
`npm i web3@0.20.2`
This worked for me!

**Comment by zhuza** [comment]
Yes, I tried again. Use: npm i web3@0.20.2
At first, wrong message:
npm WARN saveError ENOENT: no such file or directory, open '/Users/xiaobaozhu/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/xiaobaozhu/package.json'
I change 'package-lock.json' to 'package.json', the problem was solved. 
It works.:
Xiaobaos-MacBook-Pro:~ xiaobaozhu$ npm ls web3
/Users/xiaobaozhu
└── web3@0.20.2 
Thank you Adarsh srivastava !

> `npm i web3@0.20.2`
> This worked for me!

**Comment by southpeak** [comment]
The same problem, when i install the web3 with: sudo npm i --save web3@latest

the error message is 

```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! Error while executing:
npm ERR! /usr/local/git/bin/git ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: read error: Connection reset by peer
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
```

and it's ok to install web3@0.20.2
