### ISSUE TITLE
Web3.js returns "Cannot find module 'web3-requestManager'"

### ISSUE THREAD

**Issue by guidosegni** [ethereum/web3.js#966]
Using node 6.11.1 on a macosx

I installed web3 with the following command:
> npm install web3

Then i launch this - apparently - simple node command:
> Web3 = require('web3');

Well, it returns the following error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fremente/Dropbox/Influx Design/Web htdocs/ethereum/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
it looks like it require some module (e.g. 'web3-requestManager') that aren't installed with the package.

Any Idea? Am i doing something wrong?

**Comment by Moejoe90** [comment]
I'm having the same issue apparently, when i try to install the needed file manually i get only an older version

**Comment by jdkanani** [comment]
I am getting same issue. @frozeman

**Comment by cowpig** [comment]
having the same issue

**Comment by frozeman** [comment]
It was a package renaming issue, i fixed in the latest beat.15

**Comment by jefflau** [comment]
I just installed web3 today and I am also getting this issue. Is this already on npm?

**Comment by jefflau** [comment]
Not sure what happened but the error disappeared. Maybe have something to do with metamask? After that error disappeared i couldn't get it working in metamask, but it works in Mist fine

**Comment by rongierlach** [comment]
@jefflau any idea of what might have fixed it? Getting this issue when I install `truffle-contract`.

**Comment by frozeman** [comment]
I forgot to publish this module. i published it, so the issue should go away.

**Comment by frozeman** [comment]
Truffle is and should not using the latest web3.js 1.0 beta, as its -> beta :)
@tcoulter you should definitely take look at it though :)

**Comment by rongierlach** [comment]
Looks like truffle-contract is looking for web3 internal packages by names no longer on the npm registry, I moved my web3 version from ^1.0.0-beta.17 to 1.0.0-beta.15, removed node_modules, and re-npm installed to fix.

**Comment by frozeman** [comment]
That doesn't sound like a fix, and like i wrote truffle is probably not working with web3.js 1.0.0 yet

**Comment by jdkanani** [comment]
@frozeman I am still getting this error.

**Comment by jdkanani** [comment]
I think I found the problem. Checkout: https://github.com/yarnpkg/yarn/issues/711

Yarn doesn't handle nested `node_modules` as npm does.

**Comment by luck2011** [comment]
@jdkanani you saved my day! 
Just use ```npm install``` instead of ```yarn install```, and the error was gone.

**Comment by pcjose** [comment]
I added this in the .bashrc

NODE_PATH=${HOME}/node_modules

and the problem was solved.

**Comment by robert-zaremba** [comment]
@pcjose this somehow a workaround. I would like to keep all modules in my project directory. I've tried with:

    NODE_PATH=<absolute-path-to-project-root>/node_modules

And it didn't work.

Is there any way to tell `yarn` to install / link all dependencies recursively?

**Comment by tcoulter** [comment]
@frozeman 

> Truffle is and should not using the latest web3.js 1.0 beta, as its -> beta :)

Just to clear up any issues here, we haven't switched to 1.0 yet (nothing we have should be using it now, or has in the passed). But we will switch once released.

**Comment by stefanhuber** [comment]
Unfortunately, I have this problem with beta18. I tried to use web3 inside an ionic app. The following errors I get:

`Cannot find module "web3-core-requestmanager"`

```
Error: Cannot find module "web3-core-requestmanager"
    at webpackMissingModule (http://localhost:8100/build/vendor.js:116468:86)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:116468:187)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.module.exports.version (http://localhost:8100/build/vendor.js:116365:12)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.191 (http://localhost:8100/build/main.js:44:63)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.262 (http://localhost:8100/build/main.js:222:75)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.213 (http://localhost:8100/build/main.js:163:73)
```

What should I do?

**Comment by jdkanani** [comment]
@stefanhuber 

Please use `npm install --save web3` instead of `yarn add web3` as workaround of this bug!

Now, for webpack to work:

```js
const { lstatSync, readdirSync } = require('fs');
const { join } = require('path');

// is directory
const isDirectory = source => lstatSync(source).isDirectory();
// get directories
const getDirectories = source => readdirSync(source).map(name => join(source, name)).filter(isDirectory);

const modules = getDirectories(`${__dirname}/node_modules/web3/packages`); // web3 node_modules
let nodeModules = [`${__dirname}/node_modules`];
nodeModules.push(...modules.map(m => join(m, 'node_modules')));

// in webpack rules use
resolve: {
    modulesDirectories: nodeModules,
]
```

**Comment by jdkanani** [comment]
By the way, for webpack to work, this request https://github.com/ethereum/web3.js/pull/1006 needs to get merged too.

**Comment by stefanhuber** [comment]
thanks for your fast reply. I use npm and not yarn. It seems that my problem really has todo with webpack...

**Comment by jdkanani** [comment]
@stefanhuber Try adding extra modules directories as I mentioned above https://github.com/ethereum/web3.js/issues/966#issuecomment-324604175 and see if works?

**Comment by stefanhuber** [comment]
@jdkanani thank you for your solution. However I have no idea where I should add this script. Could you a little bit more specific on that?

**Comment by jdkanani** [comment]
@stefanhuber Add that script (or javascript equivalent) into your `webpack.config.js`. It just creates array with extra modules path to resolve imports for webpack.

`nodeModules` will have something like this:
```
[
'/Users/stefanhuber/...yourprojectpath.../node_modules',
'/Users/stefanhuber/...yourprojectpath.../node_modules/web3/packages',
'/Users/stefanhuber/...yourprojectpath.../node_modules/web3/packages/web3-core/node_modules',
'/Users/stefanhuber/...yourprojectpath.../node_modules/web3/packages/web3-core-requestmanager/node_modules',
.....
.....
]
```

Now you assign that array to your webpack rules (in js/jsx loader) in webpack.config file.

**Comment by stefanhuber** [comment]
@jdkanani ok I managed to organize this inside the webpack and it seems to work.

web3.version is 1.0.0-beta.18, however the object web3.eth.contract is undefined. is there a different api?

```
TypeError: window.web3.eth.contract is not a function
    at http://localhost:8100/build/main.js:71:44
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at invoke (http://localhost:8100/build/polyfills.js:3:10945)
    at n (http://localhost:8100/build/polyfills.js:2:28549)
```

**Comment by cmditch** [comment]
@stefanhuber [web3.eth.Contract](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#new-contract)

**Comment by varadarajana** [comment]
I just added 
export NODE_PATH=path/yo/node modules
and web3 gets loaded. THis is same as commented by @pcjose

**Comment by bwheeler96** [comment]
Out of curiosity, why would beta software become the default download of NPM vs whatever the previous stable is?

**Comment by eafelix** [comment]
Someone still has this issue? 
It still appears in the last version "web3": "^1.0.0-beta2"

**Comment by davesag** [comment]
This just started happening to me this morning trying to start `truffle develop`.

Running `web3 1.0.0-beta.26`
`npm outdated` reports the latest as being `1.0.0-beta2`

Now I'm confused as to which is actually the most recent.  Either way I tried installing `1.0.0-beta2` instead and I get the same error.  Running Truffle 4.0.1

**Comment by bwheeler96** [comment]
@davesag I've downgraded to web3.js 0.20.2

Bottom line: web3 is in fucking shambles. There are a billion versions of every method across a bunch of "beta" releases, the "beta" is the default from the npm registry, and the documentation is fragmented.

Use anything else if you can

**Comment by icetique** [comment]
To fix:
`Error: Cannot find module 'web3-requestManager'`

Try installing specified, latest version. The problem seems to be that npm is confused what version is the latest and also not all dependencies work. When you run `npm outdated` and it seems like this:
```
Package           Current        Wanted         Latest  Location
web3          1.0.0-beta2   1.0.0-beta2  1.0.0-beta.26
```

It may not work. Your current version should match the latest version, so use:
`npm install web3@1.0.0-beta.26`

Your `npm outdated` will show you that you don't have the wanted version:
web3       1.0.0-beta.26   1.0.0-beta2  1.0.0-beta.26

But it works. I don't know why the people who package web3 didn't see there is clearly a problem. Maybe they know some workaround? It seems that node is stripping out the '6' at the end of the wanted version so if you run `npm install web3` it install latest version of npm, but is considering it as '1.0.0-beta2' which does not resolve some dependencies.

**Comment by emazurek** [comment]
FYI, I had this problem. Here's what caused the problem.
1. upgraded node
2. tried to start my project, ran into a scrypt compile error.
3. did npm update

My web3 submodules were deleted.

To bring them back, I removed and then reinstalled web3.

**Comment by lsaether** [comment]
This error still persists. As others have pointed out, NPM seems to be downloading `web3@1.0.0-beta2` in place of `web3@1.0.0-beta.2*`.

In my case I'm trying to distribute a package that uses `web3@1.0.0-beta.28` to users over NPM. The package will download the wrong web3 version anytime someone tries to install my package. It is unfortunate, but I am forced to downgrade to the stable version for now until a workaround is found...

**Comment by cosminstefanxp** [comment]
Same issue while trying to deploy a code that uses web3 to Firebase Functions. @frozeman, any updates?

**Comment by srameshr** [comment]
Stuck with this. ```npm install web3``` installs ```0.2``` version. It does not even support promises.

**Comment by bent0b0x** [comment]
Any chance this may be resolved soon?  I am also stuck having to use an ugly workaround 😅 .

Thanks!

**Comment by elijahmurray** [comment]
Still appears to be happening…why is this closed? Tried everything in this thread with no luck.

**Comment by vsdigitall** [comment]
The same thing after update to web3@1.0.0-beta2

**Comment by daniyalzade** [comment]
Resolved the web3-requestManager issue by pinning to 1.0.0-beta.29 version. Previously it was installing 1.0.0-beta.2.

**Comment by shuji-koike** [comment]
I came across a same problem after I did `yarn upgrade`.
As @daniyalzade has mentioned above, "pinning" the version explicitly (without `^` or `~`) in package.json could be a workaround.
```
  "dependencies": {
    "web3": "1.0.0-beta.31"
  }
```
Seems like the version `1.0.0-beta2` which not having a "dot" after beta is somehow confusing yarn to resolve the latest version.

**Comment by roppa** [comment]
I'm getting this in 1.0.0-beta.31, but it works with 1.0.0-beta.30

**Comment by ondratra** [comment]
I had same issue but changing to fixed old version didn't help. Then I realized I am using very new version of Ganache that itself depended on new Web3.js version, thus overriding my package.json Web3js version.

**Comment by roschler** [comment]
I'm leaving this message in case it helps anyone since I had a fair amount of fumbling before I got things working and I was getting the same error message when I tried run my Node.js app that uses Web3.js

I had to upgrade to the latest Web3.js beta to get things to work.  This may seem obvious but like many people I originally did an *"npm install web3 --save"* operation to install the Web3.js package.  This left an older version number in package.json so npm was not getting the latest version of the beta when I executed *"npm update"*.

- I ran "npm outdated" to get the latest version of Web3.js which was locally installed.
- I grabbed the version number from the *Latest* column, which at the time this was written was *"web3": "^1.0.0-beta.33"* and changed my *"web3"* entry in my *package.json* file to that version number.
- I then installed that version by executing "npm install web3@1.0.0-beta.33", requesting the exact version I had updated my *package.json* file with.  

After doing this, I was able to run my Node.js app without it choking on the *Web3* package require/import.  Note, if you installed *Web3* globally you will have to execute the global versions of the *npm* commands shown above.  Also, you could probably do "npm install web3@1.0.0-beta.33" with the  save and save-exact flags instead of editing *package.json*, but I wanted to share exactly the steps I took to make things work.

**Comment by nickjuntilla** [comment]
For deploying to firebase functions it seems they use yarn and removing the ^ allowed it to deploy successfully for me. Apparently yarn has trouble parsing this version syntax for nested dependencies.

**Comment by maginkgo** [comment]
@nickjuntilla thanks. It worked!

**Comment by sasikumar13** [comment]
thanks vsdigitall 
my error cleared..
Error: Cannot find module 'web3-requestManager'

reinstalling helps:

# npm r web3
# npm i web3

**Comment by marcelovue** [comment]
I started getting this error after I ran `npm update`, I had to get the original package.json that was in my remote github, remove the local node_modules and then run: `npm install`

**Comment by wjmelements** [comment]
I have seen this after `npm audit fix` which downgraded my web3 to the [deprecated](https://www.npmjs.com/package/web3/v/1.0.0-beta2) 1.0.0-beta2. The fix was to return to the non-broken version.

**Comment by HP213** [comment]
npm install web3@1.0.0-beta.26, just go for it

**Comment by dconroy** [comment]
how do we get "npm audit fix" not default to deprecated versions of web3?

**Comment by Kishanjvaghela** [comment]
@cosminstefanxp I had same problem with web and firebase.. this is worked for me
- remove the `^` for web3. (In package.json). Mine is like this `"web3": "1.0.0-beta.37"`
- delete `node_modules`
- delete `package-lock.json`
- then `npm install`

**Comment by tvance929** [comment]
@Kishanjvaghela - that was it for me!  My package had a github address for web3... i replaced it with your version then followed your steps and Im up.  Thanks so much!
