### ISSUE TITLE
hashMessage cannot encode UTF

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/web3.js#971]
When I try to hash this message:
```javascript
web3.eth.accounts.hashMessage('0x01234567890ABCDEF01234567890ABCDEF01234567890ABCDEF01234567890ABCDEF01234567890ABCDEF01234567890ABCDEF01234')
```

I get 
```
Error: Invalid UTF-8 detected
    at decodeSymbol (/Users/simon/ws/slock/usn/usn-lib/node_modules/web3/packages/web3-utils/node_modules/utf8/utf8.js:194:9)
    at Object.utf8decode [as decode] (/Users/simon/ws/slock/usn/usn-lib/node_modules/web3/packages/web3-utils/node_modules/utf8/utf8.js:206:17)
    at Object.hexToUtf8 (/Users/simon/ws/slock/usn/usn-lib/node_modules/web3/packages/web3-utils/src/utils.js:207:17)
    at Accounts.hashMessage (/Users/simon/ws/slock/usn/usn-lib/node_modules/web3/packages/web3-eth-accounts/src/index.js:176:45)

```

**Comment by simon-jentzsch** [comment]
if the message comming in is already hex-coded it does not make a lot of sense to encode it UTF and then to decode it again.

```javascript
Accounts.prototype.hashMessage = function hashMessage(data) {
    var message = utils.isHex(data) ? utils.hexToUtf8(data) : data;
    var ethMessage = "\x19Ethereum Signed Message:\n" + message.length + message;
    return Hash.keccak256s(ethMessage);
};
```

changing this function to work on hex seems to help:

```javascript
Accounts.prototype.hashMessage = function hashMessage(data) {
  var message = utils.isHex(data) ? data : utils.toHex(data);
  var ethMessage = utils.toHex("\x19Ethereum Signed Message:\n" + (message.length - 2) / 2 + message.substring(2));
  return Hash.keccak256s(ethMessage);
}
```

**Comment by frozeman** [comment]
To eth sign you have to hex encode it before passing. This needs the raw message to be part of `"\x19Ethereum Signed Message:\n" + message.length + message`
I dont know if it would return the same signature if you are passing it as hex to the above.
Ion you want you can create a PR and add some extra tests to test for those use cases.
Important is that it matches eth_sign

**Comment by simon-jentzsch** [comment]
I just tested the function (after fixing a minor, but important typo) and for plain-texts or hexcode devolved from plain text it returned exactly the same result as the current function.
I also compared it to the result returned from eth_sign (at least parity) and I also got the same result.
I will try to add some tests and create a PR in the next days.

**Comment by frozeman** [comment]
Thanks!

**Comment by nivida** [comment]
@simon-jentzsch Have you fixed this with an PR?

**Comment by nivida** [comment]
I've closed this issue due to inactivity. Write a comment here and tag me if this error still occurs.
