### ISSUE TITLE
Event listener receiving incorrect values

### ISSUE THREAD

**Issue by dospunk** [ethereum/web3.js#973]
I have an event that's supposed to provide the `msg.sender` value and a string. When receiving the event (using the node.js web3 module) the address sometimes comes through as `0x0000000000000000000000000000000000000020` instead of the value of `msg.sender`, and the string is sometimes just the last 32 characters of the full string.

I know the issue is with web3 because in Mist the event log shows the correct values.

web3 version: 0.20.0
Node version: v8.2.1
Solidity version: 0.4.11
OS: macOS Sierra (10.12.5)

**Comment by dospunk** [comment]
I think this is probably related to #434

**Comment by frozeman** [comment]
closing in favour of #434
