### ISSUE TITLE
Unable to install web3 on windows10

### ISSUE THREAD

**Issue by skarred14** [ethereum/web3.js#974]
C:\>npm install -g web3
> web3@1.0.0-beta.17 postinstall C:\Users\David\AppData\Roaming\npm\node_modules\web3
> lerna bootstrap
lerna info version 2.0.0
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! Can't install C:\Users\David\AppData\Roaming\npm\node_modules\web3\packages\web3-bzz: Missing package name
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_48_191Z-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (C:\Users\David\AppData\Roaming\npm\node_modules\web3\node_modules\execa\index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:169:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install
lerna ERR! execute npm ERR! Can't install C:\Users\David\AppData\Roaming\npm\node_modules\web3\packages\web3-bzz: Missing package name
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_48_191Z-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (C:\Users\David\AppData\Roaming\npm\node_modules\web3\node_modules\execa\index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:169:7)
lerna ERR! execute   stack: 'Error: Command failed: npm install\nnpm ERR! Can\'t install C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\web3\\packages\\web3-bzz: Missing package name\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\David\\AppData\\Roaming\\npm-cache\\_logs\\2017-08-08T17_14_48_191Z-debug.log\n\n    at Promise.all.then.arr (C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\web3\\node_modules\\execa\\index.js:210:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm ERR! Can\'t install C:\\Users\\David\\AppData\\Roaming\\npm\\node_modules\\web3\\packages\\web3-bzz: Missing package name\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\David\\AppData\\Roaming\\npm-cache\\_logs\\2017-08-08T17_14_48_191Z-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
(node:4216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: npm install
npm ERR! Can't install C:\Users\David\AppData\Roaming\npm\node_modules\web3\packages\web3-bzz: Missing package name
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_48_191Z-debug.log
(node:4216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Command failed: npm install
npm ERR! Can't install C:\Users\David\AppData\Roaming\npm\node_modules\web3\packages\web3-eth-abi: Missing package name
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_48_207Z-debug.log
(node:4216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Command failed: npm install
┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\David\.config │
└────────────────────────────────────────────────────────────┘
npm ERR! Can't install C:\Users\David\AppData\Roaming\npm\node_modules\web3\packages\web3-utils: Missing package name
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_48_989Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.17 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.17 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_14_56_209Z-debug.log

Tried installing a more stable version 0.20.0 but it doesn't work either:

C:\>npm install -g web3@^0.20.0
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/frozeman/bignumber.js-nolookahead.git
npm ERR!
npm ERR!
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2017-08-08T17_21_32_909Z-debug.log

**Comment by stephanelebrun** [comment]
Same problem

**Comment by psnmissaka** [comment]
Have anyone found a fix for this? Does this have to do something with having to install windows 10 SDK?

**Comment by stephanelebrun** [comment]
`$npm install web3@^0.20.0` worked for me. Issue solved on #950

**Comment by 0xcaff** [comment]
I had this same problem installing the beta on linux. Using `web3@^0.20.0` worked for me too.

**Comment by yuandi0823** [comment]
I had this same problem installing the beta on linux. Using web3@^0.20.0 worked for me too.

**Comment by ProphetDaniel** [comment]
@yuandi0823 It also worked for me.

**Comment by frozeman** [comment]
As 1.0 is the next version and has major improvements it would be good to find the issue on windows. Can you guys please retry the latest version?

**Comment by pd164594** [comment]
I have the same issue

**Comment by barnendu** [comment]
I have same issue . I have tried with version web3@1.0.0-beta.18 and web3@^0.20.0 .  In both case i am facing same issue. Please suggest.

**Comment by valkn0t** [comment]
I had same issue on Windows 10, attempted install for a React app. I looked at the debug logs, looks like a dependency (fsevents@1.1.2) doesn't support Windows OS platform. It tried skipping it, then got an error at scrypt@6.0.3 install: `node-gyp rebuild`. 

[2017-11-03T17_49_21_086Z-debug.log](https://github.com/ethereum/web3.js/files/1442020/2017-11-03T17_49_21_086Z-debug.log)

**Comment by ptxd** [comment]
Same issue as @valkn0t on Windows10 but works with web3@^0.20.0

**Comment by mrgrotts** [comment]
I am running Windows 10, Node 9.3, NPM 5.6 and I got the latest web3 working by following these steps:

1. uninstall / reinstall node (deleted all related folders in local directory too)
2. npm install --global --production windows-build-tools
3. npm install --save --no-optional web3

**Comment by Nagaraj007** [comment]
I had same issue, web3 was giving me error while installing. Its has been solved after using 
`npm install --global --production windows-build-tools`  in windows 10 run  power shell has admin.
`npm install --save web3@^0.20.0`

**Comment by yutaowang** [comment]
240 error argv "/usr/bin/node" "/bin/npm" "install" "--save" "web3@^0.20.0"
241 error node v6.9.4
242 error npm  v3.10.10
243 error code 128
244 error Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/frozeman/bignumber.js-nolookahead.git /root/.npm/_git-remotes/git-https-github-com-frozeman-bignumber-js-nolookahead-git-18eea52a
244 error Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-frozeman-bignumber-js-nolookahead-git-18eea52a'...
244 error fatal: Authentication failed for 'https://github.com/frozeman/bignumber.js-nolookahead.git/'

**Comment by yutaowang** [comment]
what the fuck is "Authentication failed" 
for 'https://github.com/frozeman/bignumber.js-nolookahead.git/'" ??

**Comment by confused1108** [comment]
Its still a issue 
npm install -g web3@1.0.0-beta.26  failed

npm install web3@^0.20.0 worked for me

**Comment by Couranos** [comment]
npm install web3@^0.20.0 worked for me

**Comment by Farhan-riasat** [comment]
try thi one 
npm install --save web3@1.0.0-beta.34

**Comment by barakman** [comment]
Now it fails for web3@1.0.0-beta.35.

**Comment by igoreskin** [comment]
The problem with web3@^0.20.0 and probably with other versions earlier than web3@^1.0.0-beta.36 is that modules like web3.utils necessary for getting balances, building transactions etc. don't seem to work or perhaps even exist, so installing the 0.20.0 version doesn't really solve the problem. I am not 100% sure, but it seems that running npm install --global --production windows-build-tools from Windows PowerShell (as an ADMIN!) and then installing web3@^1.0.0-beta.36 is the only way.

**Comment by barakman** [comment]
@igoreskin:
These modules exist alright, just not under `web3.utils`.
I've been using web3 v0.18.4 with Truffle, and web3 v1.0.0-beta.34 when working outside of the Truffle framework, and both are fine (even though the API is different in many places).

**Comment by pradeepgarje** [comment]
Hi,
I have installed Node.js first and then opened Node.js command prompt and entered different command to install web3. But not able to install it. Can someone please help me to understand the problem? your response will be highly appreciated. thank you.
Commands used: 
<h5>npm install web3 
AND npm install --save web3@^0.20.0 </h5>

Node.js version installed: 10.15.3 (Recommanded for most users)

Error Message:

C:\>npm install --save web3@^0.20.0
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/frozeman/bignumber.js-nolookahead.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\US9959\AppData\Roaming\npm-cache\_logs\2019-03-28T00_35_11_423Z-debug.log

**Comment by ZeeshanAhmadKhalil** [comment]
Its still an issue when we use simple `npm install web3` on windows 10. 
For me, it is solved by using 

> npm install web3@0.19

But `web3@0.19` does not have some modules.

**Comment by Jtindi-cypto** [comment]
having issues install web3 on windows 10 i have tried all the suggestions but its still not working, what's the latest way of solving this
