### ISSUE TITLE
React-scripts build fails to minify with web3@1.0.0-beta.18

### ISSUE THREAD

**Issue by vbaranov** [ethereum/web3.js#977]
I develop dapp with React and web3
And `npm run build` fails to minify with web3@1.0.0-beta.18

build script looks like:
```
"scripts": {
   "build": "react-scripts build",
 }
```
react-scripts@1.0.11

Error output:
```
Failed to minify the code from this file: 

 ./node_modules/web3/packages/web3-eth-accounts/node_modules/eth-lib/src/bytes.js line 3:0 
```

If I use web3@0.19.0, there is no error.

Is there a bug? If so, could it be fixed with a new version of web3 package?

`node -v` 
v6.11.2
`npm -v` 
3.10.10

**Comment by frozeman** [comment]
Web3 0.x and 1.0 are very different. 
The issue seems to be related to eth-lib who h is es6.  @maiavictor can you please look at your precompileing. I already use 0.1.24

**Comment by brentkirkland** [comment]
I am receiving the same issue

**Comment by OFRBG** [comment]
The error seems to lie on the ES6 change. A partial fix for those who are using 1.0.0, download `web3.min.js`, place it in `src`, and access it from there. In any case, the injected web3 object already has the object. Access it with `window.web3`. Does this fix your problems for client-side? @brentkirkland @vbaranov

**Comment by brentkirkland** [comment]
I agree this is a temporary remedy. Thanks for the knowledge

**Comment by vbaranov** [comment]
For me, it works with web3@1.0.0-beta.22 for now. I think, issue could be closed.
