### ISSUE TITLE
Error: invalid address during truffle migration process

### ISSUE THREAD

**Issue by LordotU** [ethereum/web3.js#978]
Hi, guys!

It might be interesting for you: trufflesuite/truffle#534

Please, tell if additional details are needed.

**Comment by LordotU** [comment]
I've found the reason.
contractAddress is null because I'm using geth node in embedded/light mode - it hasn't enough information about blockchain.
Issue may be closed.

**Comment by ligi** [comment]
you should be able to deploy contracts in light mode
