### ISSUE TITLE
Web3 Error on RunKit

### ISSUE THREAD

**Issue by ninesalt** [ethereum/web3.js#980]
I'm trying to create an instance of Web3 on RunKit but I'm getting an error saying:

>  Cannot find module 'bignumber.js'

RunKit is supposed to already have all the modules so this error is likely something wrong with the Web3 code.  [Here ](https://runkit.com/embed/1oymz4btqwih)is the RunKit playbook.

**Comment by 0xcaff** [comment]
The error goes away if you add a require for bignumber:

    const bignumber = require('bignumber.js');

**Comment by frozeman** [comment]
Which version of web3 you are using.

**Comment by Swailem95** [comment]
@frozeman The latest one available on RunKit, which is 0.20.0. @0xcaff The error goes away but I can't get it to do anything useful. See [here](https://runkit.com/embed/5ynwkrkg1jpy)
