### ISSUE TITLE
Specify local sign provider

### ISSUE THREAD

**Issue by tcz001** [ethereum/web3.js#984]
Is there any plan to implement local sign provider?
I met with some problems when interacting with Public Ethereum API like infura and etc.
Especially when the node doesn't provide Keystore services. Web3.js is not able to sign and send contract method calls. I can help to implement this feature but just in case it's not against the basic idea of web3.js.

**Comment by MrTibbles** [comment]
> Web3.js is not able to sign and send contract method calls

http://web3js.readthedocs.io/en/1.0/web3-eth.html#sign
http://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction

**Comment by frozeman** [comment]
1.0 has that feature
