### ISSUE TITLE
web3.eth.contract is not a function

### ISSUE THREAD

**Issue by jesuprakash** [ethereum/web3.js#985]
Getting this when I am using 1.0.0-beta.18

during
var contract = web3.eth.contract(ABI).at(contractAddress);

**Comment by onbjerg** [comment]
The API changed. This would work:

```js
var contract = new web3.eth.Contract(abi, contractAddress)
```

Refer to the docs: http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#new-contract

**Comment by mbrooks** [comment]
If the API changed, then why are the tests still testing it?

https://github.com/ethereum/web3.js/blob/62dd77c7f43522eb568a001cf4c4df726f8efa69/test/web3.eth.contract.js#L29

**Comment by onbjerg** [comment]
@mbrooks You're on the wrong branch 😊

**Comment by sidharthaa** [comment]
Its "C" now instead of "c"

**Comment by lakshmankashyap** [comment]
but how can call contract method in web3 beta version  always show error unknown account

not work unlock account here any solutions
