### ISSUE TITLE
web3.eth.Contract.allEvents does not work in Web3 1.0.0-beta16 using WebSockets

### ISSUE THREAD

**Issue by onbjerg** [ethereum/web3.js#989]
Using ``allEvents`` in Web3 1.0.0 does not return any events. My code is as follows:

```js
this.contract.events.allEvents({
  fromBlock: 0,
  toBlock: 'latest'
}, (err, event) => {
  console.log(err, event)
})
```

Using ``getPastEvents`` works. It seems like the subscription is never given an ID(?):

```js
Subscription {
  id: null,
  callback: [Function],
  arguments:
   [ { toBlock: 'latest',
       address: '0x59c3b17749502874f237467818dfe46170ba92d8',
       topics: [] } ],
  _reconnectIntervalId: null,
  options:
   { subscription:
      { params: 1,
        inputFormatter: [Array],
        outputFormatter: [Function: bound ],
        subscriptionHandler: [Function: subscriptionHandler] },
     type: 'eth',
     requestManager: RequestManager { provider: [Object], providers: [Object], subscriptions: {} },
     params:
      { toBlock: 'latest',
        address: '0x59c3b17749502874f237467818dfe46170ba92d8',
        topics: [] } },
  subscriptionMethod: 'logs' }
```

I am using geth 1.6.7-stable.

**Comment by Forbu** [comment]
I am using web3 1.0.0 and I have somewhat the same problem.
I did some test with this simple contract (using testrpc as the rpc provider) :
`pragma solidity ^0.4.11;
contract eventc {

event Top(string yolo);

function event_testing(string test){
  Top(test);
}
}`

`contract_event.methods.event_testing("tessssst").send({from: address_pers,gas: 1500000,
      gasPrice: 15000000}).then(console.log);

contract_event.events.Top({
    fromBlock: 0,
    toBlock: 'latest'
}, function(error, event){
console.log("event : ",event);
});`

The console only return : `event :  null` despite multiple events in the blockchain.

**Comment by Forbu** [comment]
I am using web3 1.0.0 and I have somewhat the same problem.
I did some test with this simple contract (using testrpc as the rpc provider) :
```solidity
contract eventc {

event Top(string yolo);

function event_testing(string test){
  Top(test);
}
}
```

```javascript
contract_event.methods.event_testing("tessssst").send({from: address_pers,gas: 1500000,
      gasPrice: 15000000}).then(console.log);

contract_event.events.Top({
    fromBlock: 0,
    toBlock: 'latest'
}, function(error, event){
console.log("event : ",event);
});
```

The console only return : `event :  null` despite multiple events in the blockchain.

**Comment by Forbu** [comment]
I tried `event_sub.subscribe();` and I get 
```
 at Subscription.subscribe (XXXXX/node_modules/web3/packages/web3-core-subscriptions/src/subscription.js:208:14)
    at Object.<anonymous> (XXXXX/testing_contract.js:247:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

On line 208 of the subscription.js file : 

```
    // throw error, if provider doesnt support subscriptions
    if(!this.options.requestManager.provider.on) {
        var err2 = new Error('The current provider doesn\'t support subscriptions: '+ this.options.requestManager.provider.constructor.name);
        this.callback(err2, null, this);
        this.emit('error', err2);
        return this;
    }
```
It seems that my testrpc doesn't support subscription.

**Comment by xphoniex** [comment]
same problem as Forbu

@onbjerg how did you enable ws? I'm trying `ws://localhost:8546` but it's timing out when using parity...

**Comment by gchinis** [comment]
Hello,

Same for me, `getPastEvents` works `allEvents` does not.

The following code raises:
```js
const eventHandler = clientReceipt.events.allEvents((error, event) => {
    if(error) {
        throw error
    }

    console.log('Event:');
    console.log(event);
});
```

```
Error: Returned error: Method not found
    at Object.ErrorResponse (/home/vagrant/app/node_modules/web3/packages/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/home/vagrant/app/node_modules/web3/packages/web3-core-requestmanager/src/index.js:137:36)
    at callback (/home/vagrant/app/node_modules/web3/packages/web3-providers-ipc/src/index.js:65:40)
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/vagrant/app/node_modules/web3/packages/web3-providers-ipc/src/index.js:76:51)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at Pipe.onread (net.js:585:20)
```

Versions:
- Web3 1.0.0-beta.18
- Parity 1.7.0

**Comment by dskvr** [comment]
Also having this issue, `getPastEvents()` but `allEvents()` and consequently `contract.events.Event()` do not work as expected, they do not poll. I've tried both WS and IPC transport.

**Comment by beetleman** [comment]
same story with: ` web3.eth.subscribe` ;(

**Comment by NicholasJarr** [comment]
I subscribed to the event but it was not working. The callback was never called. Then I found out that I needed to activate the WebSockets server (--ws and similar in geth).
Found it in this [Ethereum Stack Exchange Post](https://ethereum.stackexchange.com/questions/25451/web3-provider-for-events-get-watch)

**Comment by Oxyaction** [comment]
Issuing the same problem with `1.0.0-beta.24`
When trying to in nodejs script
```
contract.events.allEvents({ fromBlock: 'latest' })
    .on('data', console.log)
    .on('changed', console.log)
    .on('error', console.log)
```
Nothing happens, script doesn't log anything and just exits while expecting it to hang and listen to the events, when I change code to this:
`contract.events.allEvents({ fromBlock: 'latest' }, console.log)`
Getting the error 
`Error: The current provider doesn't support subscriptions: HttpProvider`

Connecting to local json rpc client 
`const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));`
which launched with following params
`geth --rpcapi "db,eth,net,web3,personal,web3" --rpc --rpcaddr "localhost" --rpcport "8545" --rpccorsdomain "*" --identity "MyTestNode" --datadir "./data" --testnet --fast`

**Comment by Oxyaction** [comment]
Tested with websocket providers - everything works fine

**Comment by alexey-ernest** [comment]
@Oxyaction could you please share the full code snippet, can't make it work either.

**Comment by Oxyaction** [comment]
@alexey-ernest 
started geth node with:
```
geth --rpcapi "db,eth,net,web3,personal" --ws --wsaddr "localhost" --wsport "8545" --wsorigins "*" --identity "MyTestNode" --datadir "./data" --testnet --fast
```
connected to web3:
```
const web3 = new Web3(new Web3.providers.WebsocketProvider('http://127.0.0.1:8545'));
```
listening:
```
contract.events.allEvents({ fromBlock: 'latest' }, console.log)
```

**Comment by AndreyPatseiko** [comment]
I can't use webSokets. How I can catch contract  events?
web3 - version 1.0.0-beta23

**Comment by Oxyaction** [comment]
@AndreyPatseiko 
Suppose it is impossible by it's nature, event should be initiated by the server and it is impossible with plain http protocol

**Comment by AndreyPatseiko** [comment]
You right. I was angry because about it any single word in the documentation. 
Thanks for you example - if use webSocets all work correct, like as described in web3 documentation.

**Comment by TSIApatruno** [comment]
Anyone having a problem with watch all events not working after about 10 minutes?

**Comment by Deams51** [comment]
Works if "latest" is used as fromBlock param, but does not work here if the fromBlock is different from latest.

**Comment by bohendo** [comment]
Was just exploring this same issue. Expanding @dskvr's observations, I wrapped my event listeners in a call to web3.eth.getBlock('latest') and explicitly pass the latest block number as `fromBlock`. I'm doing this in docker w nodemon so it's been starting & restarting pretty wildly without any issues (so far). My setup looks something like:

```
web3.eth.getBlock('latest').then(res => {
  console.log(`Starting event watchers from block ${res.number}`)
  contract.events.allEvents({ fromBlock: res.number }, eventHandler)
})
```

Earlier I was debugging something similar and realized I only halfway enabled my websockets connection. Remember to specify websockets both while specifying the web3 provider `ws://localhost:8546` and while starting `geth --ws --wsorigins="*"`.

**Comment by khaschuluu** [comment]
Same here using parity and web3 1.0.0-beta21

**Comment by onairelav** [comment]
no, here is working

**Comment by onbjerg** [comment]
Sorry, forgot to close it. It works for me most of the time, but there are some things to keep in mind:

- Only use WebSocket or IPC provider
- If you want to listen for a bunch of events, don't use INFURA (that also means don't use MetaMask unless you add a custom node), since it's hella slow for event aggregation

Happy hacking

**Comment by bohendo** [comment]
To expand the comments by @onbjerg I also want to suggest one more troubleshooting tip for those who find themselves here:

 - Try a different Ethereum client. If you're using parity and are having trouble fetching old logs, try geth instead.

See [parity issue 6637](https://github.com/paritytech/parity/issues/6637) for details although it looks like this might have been fixed a couple days ago... Geth, on the other hand, has always been extremely reliable while fetching historical events.

**Comment by JimLynchCodes** [comment]
Eth is straight garbage, I think. I am using websocket provider, but my web3 side hears ZERO events being emitted in my smart contract deployed on polygon Mumbai... wtf? 🤔
