### ISSUE TITLE
suggestion: use indutny bn.js (bignumber library)

### ISSUE THREAD

**Issue by ethers** [ethereum/web3.js#99]
https://github.com/indutny/bn.js/

It's one of the (if not) fastest.
eg:
http://blog.bitpay.com/2014/07/22/bitcore-3000-is-three-times-faster-for-bitcoin-on-the-web.html
https://gist.github.com/wanderer/5aab77502625d6e2e1d5

**Comment by debris** [comment]
ok!

**Comment by wanderer** [comment]
:+1: bn.js is great

**Comment by debris** [comment]
BigNumber.js is currently part of our public interface. Changing it now to bn.js would be really hard. We aren't doing any heavy calculations in web3.js, so lets stay with BigNumber.js
