### ISSUE TITLE
How to use Web3js on ios

### ISSUE THREAD

**Issue by dtco-kimi** [ethereum/web3.js#991]
I'm trying to use Obj-c to invoke Web3js functions. I have couple questions.

First, all the example I could find need to set a provider after new Web3 object. We are running a private chain so  any interaction with the chain  on the mobile devices have to pass through our API server. Therefore, we don't want/need to run a node on the device. My first question is, do I have to set a provider to use Web3.js functions?

Second, I have found a way to invoke js functions from Obj-c. However, I use 'require' to import Web3js modules, it throws 'ReferenceError: Can't find variable: require'. I know it's about node.js runtime, but I have no idea to solve it. I'm totally new to js. Do you have any suggestions?

Here is my js 
```
function getAddress(prvKey)
{
  try{
      var Web3 = require('../../3rd_party/web3.js-1.0.0');     
      var web3 = new Web3();
      return web3.eth.accounts.privateKeyToAccount(prvKey);
  }
  catch (e)
  {
      return e;
  }
}
```

Here is my Obj-c
```
NSString* path = [[NSBundle mainBundle] pathForResource:@"bridge/src/index" ofType:@"js"];
jsFunc = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil];

JSContext* jsContext = [[JSContext alloc] init];
[jsContext evaluateScript:jsFunc];
JSValue* func = jsContext[@"getAddress"];
JSValue* = [func2 callWithArguments:@[@"0x8730f6ad1c0d387644590966bdbfedba44fe250118df0f97f11190ad5727b312"]];```

Any help is appreciated.

**Comment by dmitrychaban** [comment]
Any news about running Web3js on ios?

**Comment by KimiWu123** [comment]
The first question is No. You just new a web3 object

    var web3 = new Web3();

The second question, my solution is  Browserify. Packing all the js dependencies into a single js file and then invoke it by a html file. In iOS, use webview to call js functions in the html file.

**Comment by carsonHoney** [comment]
hello my brother,i got seem question,did you solve it?

**Comment by KimiWu123** [comment]
@carsonHoney ,
Yes, I have solved it by using webview to load js files. If you could read Chinese, you can refer [this article](http://kimiwublog.blogspot.tw/2017/09/objective-c-javascript-part-i.html).

**Comment by carsonHoney** [comment]
thanks my brother.but still have a question.when I did ‘npm install web3’ I got a lot of files and i don’t know which file i can use in webview .can you tell me?thanks.

**Comment by carsonHoney** [comment]
The second question, my solution is Browserify. Packing all the js dependencies into a single js file and then invoke it by a html file. In iOS, use webview to call js functions in the html file. 
I don’t know how to packing all is into a single is,may I get some details?

**Comment by nivida** [comment]
Please ask your questions on: https://ethereum.stackexchange.com/
