### ISSUE TITLE
subcribe to pendingTransactions does not work with Parity 

### ISSUE THREAD

**Issue by jbentke** [ethereum/web3.js#992]
web3 version 1.0.0-beta.17
Parity version Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-macos/rustc1.18.0

Basically, I subscribe to pending transactions but the event emitter is not triggered. I can however subscribe to newBlockHeaders without problems.

There is no error message. Just nothing happens

I have a private Partiy Morden network setup. Two Parity instances are running on the same machine. Transactions from neither are triggering subscribe. The transactions are however in the pending list after I signed them. Checked through parity_pendingTransactions.

Everything works like a charm on Geth.

The code for subscribe:

```javascript
var Web3 = require('web3')
var net = require('net')
//var web3 = new Web3('./parity.ipc', net)    <- does not work either
var web3 = new Web3("ws://localhost:8546")

var subscription = web3.eth.subscribe('pendingTransactions', function(error, result) {
  if (!error) {
    //do something
  }
})
  .on("data", async function(transaction) {
    console.log("Received a pending transaction")
  })
```

I run this code and then simply send a transaction via web3 and sign it on the localhost website.

I hope I provided all the necessary information needed :)

**Comment by k06a** [comment]
Got error: 
```
Error: Returned error: This request is not implemented yet. Please create an issue on Github repo.
```

**Comment by epheph** [comment]
@k06a the issue you received is from parity, not web3. The feature has recently been added to parity nightly
