### ISSUE TITLE
remove lerna-temp tag from web3-core npm registry

### ISSUE THREAD

**Issue by perissology** [ethereum/web3.js#994]
the `lerna-temp` tag is causing yarn to incorrectly resolve the dependencies for `web3-core`.

I filed an [issue](https://github.com/yarnpkg/yarn/issues/4208) with yarnpgk, but until that is resolved, it would be helpful if you could remove the `lerna-temp` tag from the npm registry.

**Comment by stilesb** [comment]
Bump

**Comment by frozeman** [comment]
Where is this tag supposedly?

**Comment by dacarley** [comment]
The tag is on web3-core.  See `npm dist-tag ls web3-core`

It appears that the tag can be removed by running `npm dist-tag rm

See https://docs.npmjs.com/cli/dist-tag for more info

**Comment by dacarley** [comment]
Removing this dist-tag should allow `yarn add web3` to operate correctly.

**Comment by frozeman** [comment]
Ok did that, thanks!
