### ISSUE TITLE
web3-core-requestmanager

### ISSUE THREAD

**Issue by vivekebics** [ethereum/web3.js#996]
Hi, I am trying to import web3 in react native project. I have the following error. Please help me to solve it. 
![screen shot 2017-08-18 at 9 56 16 pm](https://user-images.githubusercontent.com/29792642/29484630-64e42084-84e0-11e7-8187-4ba04d2d32e1.png)

**Comment by jdkanani** [comment]
Related to https://github.com/ethereum/web3.js/issues/966

**Comment by vivekebics** [comment]
**Fixed:**  https://github.com/ethereum/web3.js/issues/576

Edit The Following File

	/node_modules/bignumber.js/bignumber.js

edit as follows:

	-if ( !crypto ) try { crypto = require('crypto'); } catch (e) {}
	+if ( !crypto ) try { crypto = require('crypto-js'); } catch (e) {} 
	
**Web3 Version: 0.18.2**
