### ISSUE TITLE
VM : Out of gas exception on calling only the non-constant functions

### ISSUE THREAD

**Issue by sivachaitanya** [ethereum/web3.js#998]
The code ran well in truffle console, Remix and even on Web3 too untill I make a call to non-constant method on my contract instance. Following is the stack trace seen in the browser console 

```
app.js:39931 Uncaught Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (app.js:39931)
    at RequestManager.send (app.js:121538)
    at Eth.send [as sendTransaction] (app.js:33631)
    at SolidityFunction.sendTransaction (app.js:120111)
    at SolidityFunction.execute (app.js:120197)
    at app.js:75795
    at Object.callback (app.js:120092)
    at app.js:33628
    at app.js:121566
    at XMLHttpRequest.request.onreadystatechange (app.js:120349)
InvalidResponse @ app.js:39931
RequestManager.send @ app.js:121538
send @ app.js:33631
SolidityFunction.sendTransaction @ app.js:120111
SolidityFunction.execute @ app.js:120197
(anonymous) @ app.js:75795
(anonymous) @ app.js:120092
(anonymous) @ app.js:33628
(anonymous) @ app.js:121566
request.onreadystatechange @ app.js:120349
XMLHttpRequest.send (async)
HttpProvider.sendAsync @ app.js:120358
RequestManager.sendAsync @ app.js:121557
send @ app.js:33627
SolidityFunction.call @ app.js:120081
verifyUser @ app.js:75788
onclick @ (index):42
```
Following is the log from testrpc, as we can see it was able to create a new contract instance but when calling a non-constant based function reg_org it fails saying out of gas with gas usage of 90000 ?-

```

  Transaction: 0x292e55f036a66614db77c133254b92ae7d35ecbb953ba869452720d92a91f95d
  Contract created: 0x9006f345f5f4dad102789ad795d03a284a4ec027
  Gas usage: 1066838
  Block Number: 50
  Block Time: Sun Aug 20 2017 22:41:27 GMT+0530 (India Standard Time)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_accounts
eth_sign
eth_call
eth_sendTransaction

  Transaction: 0x22127d49f80acac79f724d08dc72c221f6bf72168f00f6242e3e70a2851cc13b
  Gas usage: 90000
  Block Number: 51
  Block Time: Sun Aug 20 2017 22:41:30 GMT+0530 (India Standard Time)
  Runtime Error: out of gas


```
 I have attached my app.js, index.html and EcrecTest.sol for your reference. I'm really clueless what is causing the issue when same code works well in Remix and Truffle console. Can you please help me resolve this ?

[EcrecTest.zip](https://github.com/ethereum/web3.js/files/1237218/EcrecTest.zip)

**Comment by YOHANMAURIN** [comment]
Hello, 
Did you manage to solve your problem ?
Best regards

**Comment by dev1644** [comment]
It seems to me that, either you are providing less than sufficient Gas Limit to your function or your function consumes too much gas i.e the Gas consumption of your function is more than current block's Gas Limit.

Edited:
The function register_org needs at least 102499 Gas to execute and you are providing 90000, that's why you are getting error.

@nivida  I think we can close this issue.
